define({
  "tabs_section_Label": "Schede",
  "addTab": "Aggiungi scheda",
  "layerName": "Layer",
  "layerType": "Tipo di analisi",
  "layerLabel": "Etichetta",
  "actions": "Azioni",
  "closest": "Feature più vicina",
  "proximity": "Prossimità",
  "summary": "Riepilogo",
  "select_lbl": "-- Seleziona --",
  "general_setting_Label": "Impostazioni generali",
  "units_text_lbl": "Unità Distanza",
  "miles": "Miglia",
  "kilometers": "Chilometri",
  "feet": "Piede",
  "meters": "Metri",
  "yards": "Iarde",
  "nauticalMiles": "Miglia nautiche",
  "maximum_distance_lbl": "Distanza massima della feature più vicina",
  "buffer_text_lbl": "Etichetta del buffer",
  "buffer_lbl": "Distanza di buffer",
  "buffer_max_lbl": "Distanza massima del buffer",
  "buffer_min_lbl": "Distanza minima del buffer",
  "routing_checkBox": "Abilita itinerario",
  "weather_Label": "Opzioni meteo",
  "weather_checkBox": "Includi informazioni meteo",
  "selectLayers": "Seleziona layer meteo",
  "currentlySelectedLayer": "Layer meteo attualmente selezionati",
  "missingTabLabel": "Manca l'etichetta ad almeno una scheda",
  "missingLayerInWebMap": "Nessun layer operativo trovato.",
  "selectFields": "Seleziona campi",
  "addField": "Aggiungi Campo",
  "sum": "SOMMA",
  "min": "MIN",
  "max": "MAX",
  "avg": "MEDIA",
  "count": "COUNT",
  "area": "AREA",
  "length": "LENGTH",
  "count_checkBox": "Visualizza conteggio feature",
  "area_checkBox": "Visualizza somma dell'area",
  "length_checkBox": "Visualizza somma della lunghezza",
  "max_records": "Raggiunto limite massimo",
  "save_label": "Salva opzioni",
  "save_checkbox": "Abilita salvataggio",
  "csv_label": "Opzioni CSV",
  "csv_checkbox": "Esporta tutti i campi nel layer",
  "display_label": "Opzioni di visualizzazione",
  "display_checkbox": "Visualizza riepilogo delle feature",
  "must_select_template": "Selezionare uno dei modelli di modifica nelle opzioni di salvataggio.",
  "count_label": "Etichetta conteggio",
  "area_label": "Etichetta area",
  "length_label": "Etichetta lunghezza",
  "invalid_string_width": "Il valore è troppo lungo. ",
  "layer_type_not_supported": "Il tipo di layer non è supportato: ",
  "groupedSummary": "Conteggi raggruppati",
  "groupByField": "Raggruppa per campo",
  "labelType": "Aggiungi etichetta",
  "prefix": "Come prefisso",
  "suffix": "Come suffisso",
  "need_group_field": "Utilizzare l'azione Modifica per definire un Gruppo per campo.",
  "fieldTitle": "Campo",
  "typeTitle": "Tipo",
  "actionsTitle": "Azioni"
});