define({
  "businessAnalyst": "Business Analyst",
  "defineWhichInfographics": "Définir les infographies disponibles dans le widget :",
  "defineWhichReports": "Définir les rapports disponibles dans le widget :",
  "defaultValues": "Valeurs par défaut :",
  "disable": "Désactiver",
  "driveTime": "Temps de conduite",
  "infographics": "Infographie",
  "invalidValueRing": "Les valeurs doivent être comprises entre 0 et 1 000.",
  "invalidValueDTWT": "Les valeurs doivent être comprises entre 0 et 300.",
  "km": "km",
  "miles": "miles",
  "minutes": "minutes",
  "radius": "Rayon",
  "reports": "Rapports",
  "rings": "Anneaux",
  "selectCountry": "Sélectionner le pays :",
  "thisEntryIsNotValid": "L’entrée n’est pas valide.",
  "time": "Durée",
  "walkTime": "Temps de marche"
});