define({
  "chartSettingLabel": "Kaavion asetukset",
  "addNewLabel": "Lisää uusi",
  "generalSettingLabel": "Yleiset asetukset",
  "layerChooser": {
    "title": "Valitse kaavion lisättävä karttataso",
    "selectPolygonLayerLabel": "Valitse karttataso",
    "selectPolygonLayerHintText": "Vihje: jos määrität useita kaavioita, karttatasojen on oltava samaa geometriatyyppiä",
    "selectRelatedTableLayerLabel": "Valitse karttatasoon liittyvä taulukko",
    "selectRelatedTableLayerHintText": "Vihje: vain numerokenttiä sisältävä taulukot näytetään",
    "errorInSelectingPolygonLayer": "Valitse karttataso, jossa on siihen liittyvä pistekarttataso.",
    "errorInSelectingRelatedLayer": "Valitse kelvollinen karttatasoon liittyvä taulukko tai karttataso.",
    "polygonLayerNotHavingRelationships": "Valitussa karttatasossa ei ole yhtään liittyvää taulukkoa tai karttatasoa."
  },
  "ChartSetting": {
    "sectionTitle": "Osan otsikko",
    "sectionTitleHintText": "Vihje: näytetään osan ylätunnisteen otsikossa",
    "chartTitle": "Kaavion otsikko",
    "chartTitleHintText": "Vihje: näytetään keskitettynä kaavion yläreunassa",
    "chartDescription": "Kuvaus",
    "chartDescriptionHintText": "Vihje: näytetään kaavion alapuolella",
    "chartType": "Kaavion tyyppi",
    "barChart": "Palkkikaavio",
    "pieChart": "Ympyräkaavio",
    "polarChart": "Napakaavio",
    "dataSeriesField": "Aineistosarjakenttä",
    "labelField": "Tunnustekstikenttä",
    "chartColor": "Kaavion väri",
    "singleColor": "Yksittäinen väri",
    "colorByTheme": "Väritä teemoittain",
    "colorByFieldValue": "Väritä kentän arvon mukaan",
    "xAxisTitle": "X-akselin otsikko",
    "xAxisHintText": "Vihje: X-akselin otsikko",
    "yAxisTitle": "Y-akselin otsikko",
    "yAxisHintText": "Vihje: Y-akselin otsikko",
    "fieldColorLabel": "Tunnusteksti",
    "fieldColorColor": "Väri",
    "defaultFieldSelectLabel": "Valitse",
    "errMsgFieldValuesNotFound": "Valitun kentän arvoja ei löydy",
    "errMsgSectionTitle": "Anna osan otsikko",
    "errMsgFieldByValue": "Valitse kentän arvo",
    "settingTabTitle": "Asetus",
    "layoutTabTitle": "Asettelu",
    "polarChartSelectFieldsHintText": "Vihje: valitse kentät napakaavion luomista varten",
    "visibilityText": "Näkyvyys",
    "fieldNameText": "Kentän nimi",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Valitse vähintään kolme kenttää napakaavion luomista varten",
    "polarChartPolygonFillLabel": "Täyttöalue",
    "polarChartPolygonFillHintText": "Vihje: näytä aluekohteilla täytetty napakaavio valitsemalla valintaruutu",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Levä",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Autiomaa",
      "themeDistinctive": "Erikoislaatuinen",
      "themeDollar": "Dollari",
      "themeGrasshopper": "Heinäsirkka",
      "themeGrasslands": "Ruohotasanko",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmonia",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minttu",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Kosteikko",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Yleiset asetukset",
    "locationSymbolLabel": "Graafinen sijainnin symboli",
    "locationSymbolHintText": "Vihje: käytetään osoitteen symbolin näyttämiseen ja sijainnin napsauttamiseen",
    "refreshIntervalLabel": "Päivitysväli",
    "refreshIntervalHintText": "Vihje: Käytetään kaavioiden päivittämiseen tämän aikavälin perusteella. Määritä arvo väliltä 1–1 440 minuuttia",
    "errMsgRefreshInterval": "Määritä päivitysväliksi 0–1 440 minuuttia",
    "symbolPickerPreviewText": "Esikatselu:"
  }
});