define({
  "searchTabTitle": "إعداد مصدر البحث",
  "routeTabTitle": "إعداد المسار",
  "add": "إضافة مصدر البحث",
  "addGeocoder": "إضافة مكود جغرافي",
  "geocoder": "مكود جغرافي",
  "setLayerSource": "تحديد مصدر الطبقة",
  "setGeocoderURL": "تعيين عنوان URL للمكود الجغرافي",
  "searchableLayer": "طبقة المعالم",
  "name": "الاسم",
  "countryCode": "كود الدولة أو المنطقة",
  "countryCodeEg": "مثال ",
  "countryCodeHint": "سيؤدي ترك هذه القيمة فارغة إلى البحث في كل الدول والمناطق",
  "showInfoWindowOnSelect": "عرض عناصر منبثقة للمعلم أو الموقع الذي يتم العثور عليه",
  "showInfoWindowOnSelect2": "عرض العنصر المنبثق عند العثور على المعلم أو الموقع.",
  "searchInCurrentMapExtent": "البحث في مدى الخريطة الحالي فقط",
  "setSearchFields": "تعيين حقول البحث",
  "set": "تعيين",
  "fieldSearchable": "قابل للبحث",
  "zoomScale": "تدرج التكبير/التصغير",
  "locatorUrl": "عنوان URL للمكود الجغرافي",
  "locatorName": "اسم المكود الجغرافي",
  "locatorExample": "مثال",
  "locatorWarning": "يعد إصدار خدمة التكويد الجغرافي غير مدعوم. يدعم عنصر واجهة المستخدم خدمة التكويد الجغرافي 10.1 والإصدارات الأحدث.",
  "locatorTips": "لا توجد اقتراحات بسبب عدم دعم خدمة التكويد الجغرافي لإمكانية الاقتراح.",
  "layerSource": "مصدر الطبقة",
  "searchLayerTips": "لا توجد اقتراحات بسبب عدم دعم خدمة المعالم لإمكانية الحدود الفاصلة للصفحات.",
  "placeholderText": "النص النائب",
  "searchFields": "حقول البحث",
  "displayField": "عرض الحقل",
  "exactMatch": "تطابق تام",
  "maxSuggestions": "الحد الأقصى من المقترحات",
  "maxResults": "الحد الأقصى للنتائج",
  "enableLocalSearch": "تمكين البحث المحلي",
  "minScale": "أدنى مقياس",
  "minScaleHint": "عندما يكون مقياس الخريطة أكبر من هذا المقياس، سيتم تطبيق البحث المحلي",
  "radius": "نصف القطر",
  "radiusHint": "يُحدد مُحيط المنطقة حول مركز الخريطة الحالية المستخدمة لتحسين رتبة مرشحي التكويد الجغرافي؛ حتى يتم إرجاع المرشحين الأقرب للموقع أولاً",
  "invalidUrlTip": "عنوان URL لـ ${URL} غير صحيح أو لا يمكن الوصول إليه.",
  "routeUrl": "عنوان URL للمسار",
  "geocoderOptions": "خيارات المكود الجغرافي",
  "autoComplete": "اكتمال تلقائي",
  "maximumSuggestions": "الحد الأقصى من المقترحات",
  "minCharacters": "الأحرف الدُنيا",
  "searchDelay": "تأخير البحث",
  "placeholder": "عنصر نائب",
  "routeOptions": "خيارات التوجيه",
  "directionsLanguage": "لغة الاتجاهات",
  "directionsLengthUnits": "وحدات طول الاتجاهات",
  "directionsOutputType": "نوع الاتجاهات الناتج",
  "impedanceAttribute": "معاوقة البيانات الجدولية",
  "kilometers": "كيلومترات",
  "miles": "أميال",
  "meters": "مترات",
  "feet": "قدم",
  "yards": "ياردات",
  "nauticalMiles": "أميال بحرية",
  "parametersTip": "الرجاء تعيين المعلمات بشكل صحيح!",
  "complete": "إكمال",
  "completeNoEvents": "إكمال لا توجد أحداث",
  "instructionsOnly": "التعليمات فقط",
  "standard": "قياسي",
  "summaryOnly": "الملخص فقط",
  "travelModesUrl": "عنوان URL لأوضاع السفر",
  "searchPlaceholder": "العثور على عنوان أو مكان ما",
  "trafficLayerUrl": "عنوان URL لطبقة حركة المرور",
  "barrierLayerUrl": "عنوان URL لطبقة الحاجز",
  "presetDestinations": "تعيين مُسبق لعلامات التوقف",
  "startPoint": "نقطة البدء",
  "endPoint": "نقطة النهاية",
  "destinationHolder": "العناوين أو الإحداثيات",
  "optional": "اختياري.",
  "barrierLayers": "طبقات العوائق",
  "pointBarrier": "عوائق النقاط",
  "lineBarrier": "عوائق الخط",
  "polygonBarrier": "عوائق المضلع",
  "noPointBarrier": "تحديد العوائق النقطية",
  "noLineBarrier": "تحديد العوائق الخطية",
  "noPolygonBarrier": "تحديد عوائق المضلع"
});