define({
  "defaultAreaUnit": "หน่วยพื้นที่ตั้งต้น",
  "defaultLengthUnit": "หน่วยความยาวตั้งต้น",
  "acres": "เอเคอร์",
  "sqMiles": "ตารางไมล์",
  "sqKilometers": "ตารางกิโลเมตร",
  "hectares": "เฮกตาร์",
  "sqYards": "ตารางหลา",
  "sqFeet": "ตารางฟุต",
  "sqMeters": "ตารางเมตร",
  "miles": "ไมล์",
  "kilometers": "กิโลเมตร",
  "feet": "ฟุต",
  "meters": "เมตร",
  "yards": "หลา",
  "nauticalMiles": "ไมล์ทะเล",
  "showArea": "พื้นที่",
  "showDistance": "ระยะทาง",
  "showLocation": "ตำแหน่ง",
  "showtools": "แสดงเครื่องมือวัด:",
  "allHidedTips": "ต้องมีอย่างน้อยหนึ่งเครื่องมือที่ถูกเลือก"
});