define({
  "_widgetLabel": "Smart redigering",
  "_featureAction_SmartEditor": "Smart redigering",
  "noEditPrivileges": "Kontoen har ikke rettigheter til å opprette eller endre data.",
  "widgetActive": "Aktiv",
  "widgetNotActive": "Ikke aktiv",
  "pressStr": "Trykk på ",
  "ctrlStr": " CTRL ",
  "snapStr": " for å aktivere festing",
  "noAvailableTempaltes": "Ingen tilgjengelige maler",
  "editorCache": " - Redigeringsbuffer",
  "presetFieldAlias": "Felt",
  "presetValue": "Forhåndsinnstilt verdi",
  "usePresetValues": " Bruk forhåndsinnstilte verdier (kun nye geoobjekter)",
  "editGeometry": " Rediger geometri",
  "savePromptTitle": "Lagre geoobjekt",
  "savePrompt": "Vil du lagre gjeldende geoobjekt?",
  "deletePromptTitle": "Slett geoobjekt",
  "deletePrompt": "Er du sikker på at du vil slette det valgte geoobjektet?",
  "attachmentLoadingError": "Feil under opplasting av vedlegg",
  "attachmentSaveDeleteWarning": "Advarsel: Endringer i vedlegg lagres automatisk",
  "autoSaveEdits": "Lagrer nytt geoobjekt automatisk",
  "addNewFeature": "Opprett nytt geoobjekt",
  "featureCreationFailedMsg": "Kan ikke opprette ny post / nytt geoobjekt",
  "relatedItemTitle": "Relatert tabell/lag",
  "invalidRelationShipMsg": "Kontroller at feltet for primærnøkkel: '${parentKeyField}' inneholder en gyldig verdi",
  "pendingFeatureSaveMsg": "Lagre geoobjektsredigeringene før du oppretter et relatert geoobjekt.",
  "attachmentsRequiredMsg": "(*) Vedlegg er obligatorisk.",
  "coordinatePopupTitle": "Flytt geoobjekt til XY-posisjonen",
  "coordinatesSelectTitle": "Koordinatsystem:",
  "mapSpecialReferenceDropdownOption": "Kartets romlige referanse",
  "latLongDropdownOption": "Lengdegrad/breddegrad",
  "xAttributeTextBoxLabel": "X-koordinat:",
  "yAttributeTextBoxLabel": "Y-koordinat:",
  "latitudeTextBoxLabel": "Breddegrad:",
  "longitudeTextBoxLabel": "Lengdegrad:",
  "filterEditor": {
    "all": "Alle",
    "noAvailableTempaltes": "Ingen tilgjengelige maler",
    "searchTemplates": "Søk i maler"
  },
  "invalidConfiguration": "Widgeten er ikke konfigurert eller lagene i konfigurasjonen finnes ikke i kartet lenger. Åpne appen i byggemodus, og konfigurer widgeten på nytt.",
  "geometryServiceURLNotFoundMSG": "Kan ikke hente URL for geometritjeneste",
  "clearSelection": "Tøm",
  "refreshAttributes": "Oppdater geoobjektattributter",
  "automaticAttributeUpdatesOn": "Oppdater geoobjektattributter automatisk: PÅ",
  "automaticAttributeUpdatesOff": "Oppdater geoobjektattributter automatisk: AV",
  "moveSelectedFeatureToGPS": "Flytt det valgte geoobjektet til gjeldende GPS-posisjon",
  "moveSelectedFeatureToXY": "Flytt det valgte geoobjektet til XY-posisjonen",
  "mapNavigationLocked": "Kartnavigering: Låst",
  "mapNavigationUnLocked": "Kartnavigering: Ulåst"
});