define({
  "_widgetLabel": "Nutikas redaktor",
  "_featureAction_SmartEditor": "Nutikas redaktor",
  "noEditPrivileges": "Teie kontol puudub andmete loomise või muutmise õigus.",
  "widgetActive": "Aktiivne",
  "widgetNotActive": "Pole aktiivne",
  "pressStr": "Snäppimise võimaldamiseks ",
  "ctrlStr": " vajutage ",
  "snapStr": " CTRL",
  "noAvailableTempaltes": "Ühtki malli pole saadaval",
  "editorCache": " - redaktori vahemälu",
  "presetFieldAlias": "Väli",
  "presetValue": "Eelseatud väärtus",
  "usePresetValues": " Kasuta eelseatud väärtusi (ainult uute objektide korral)",
  "editGeometry": " Muuda geomeetriat",
  "savePromptTitle": "Salvesta objekt",
  "savePrompt": "Kas soovite salvestada praeguse objekti?",
  "deletePromptTitle": "Kustuta objekt",
  "deleteAttachment": "Kustuta manus",
  "deletePrompt": "Kas soovite kindlasti kustutada valitud objekti?",
  "attachmentLoadingError": "Tõrge manuste üleslaadimisel",
  "attachmentSaveDeleteWarning": "Hoiatus: manuste muudatused salvestatakse automaatselt",
  "autoSaveEdits": "Uus objekt salvestatakse automaatselt",
  "addNewFeature": "Loo uus objekt",
  "featureCreationFailedMsg": "Uut kirjet/objekti ei saa luua",
  "relatedItemTitle": "Seotud tabel/kiht",
  "relatedFeatureCount": "${layerTitle} koos ${featureCount} objektiga",
  "createNewFeatureLabel": "Loo kihi ${layerTitle} jaoks uus objekt",
  "invalidRelationShipMsg": "Veenduge, et primaarvõtme väljal „${parentKeyField}“ oleks sobiv väärtus.",
  "pendingFeatureSaveMsg": "Enne seotud objekti loomist salvestage objekti osas tehtud muudatused.",
  "attachmentsRequiredMsg": "(*) Manused on nõutavad.",
  "coordinatePopupTitle": "Teisalda objekt XY-asukohta",
  "coordinatesSelectTitle": "Koordinaatsüsteem:",
  "mapSpecialReferenceDropdownOption": "Kaardi koordinaatsüsteem",
  "latLongDropdownOption": "Laius/Pikkus",
  "xAttributeTextBoxLabel": "X-koordinaat:",
  "yAttributeTextBoxLabel": "Y-koordinaat:",
  "latitudeTextBoxLabel": "Laiuskraad:",
  "longitudeTextBoxLabel": "Pikkuskraad:",
  "presetGroupFieldsLabel": "${groupName} rakendatakse järgmistele kihiväljadele:",
  "presetGroupNoFieldsLabel": "Grupil ${groupName} pole seostatud välju",
  "groupInfoLabel": "Grupi ${groupName} teave",
  "editGroupInfoIcon": "Muuda grupi ${groupName} väärtust",
  "filterEditor": {
    "all": "Kõik",
    "noAvailableTempaltes": "Ühtki malli pole saadaval",
    "searchTemplates": "Otsingumallid",
    "filterLayerLabel": "Filtreeri kihid"
  },
  "invalidConfiguration": "Vidin on konfigureerimata või pole konfiguratsioonis sisalduvad kihid enam kaardil. Avage rakendus koostajarežiimis ja konfigureerige vidin uuesti.",
  "geometryServiceURLNotFoundMSG": "Geomeetriateenuse URL-i ei saa tuua",
  "clearSelection": "Tühjenda",
  "refreshAttributes": "Uuenda objekti atribuute",
  "automaticAttributeUpdatesOn": "Uuenda objekti atribuudid automaatselt: SEES",
  "automaticAttributeUpdatesOff": "Uuenda objekti atribuudid automaatselt: VÄLJAS",
  "moveSelectedFeatureToGPS": "Teisalda valitud objekt praegusesse GPS-i asukohta",
  "moveSelectedFeatureToXY": "Teisalda valitud objekt XY-asukohta",
  "mapNavigationLocked": "Kaardil navigeerimine: lukustatud",
  "mapNavigationUnLocked": "Kaardil navigeerimine: lukustamata",
  "copyFeatures": {
    "title": "Kopeeri objektid",
    "createFeatures": "Loo objektid",
    "createSingleFeature": "Loo üks mitmeosalise geomeetriaga objekt",
    "noFeaturesSelectedMessage": "Objekte pole valitud",
    "selectFeatureToCopyMessage": "Kopeerimiseks valige objektid.",
    "multipleFeatureSaveWarning": "Märkus: mitme objekti loomisel kopeerimisfunktsiooniga salvestatakse kõik objektid kohe"
  },
  "addingFeatureError": "Viga valitud objektide kihile lisamisel. Palun proovige uuesti",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' objekti ei õnnestunud kopeerida.",
  "selectingFeatureError": "Viga objektide valimisel kihis. Palun proovige uuesti",
  "customSelectOptionLabel": "Valige kopeeritavad objektid",
  "noFeatureSelectedMessage": "Objekte ei ole valitud.",
  "multipleFeatureSaveMessage": "Kõik objektid salvestatakse kohe. Kas soovite jätkata?",
  "relativeDates": {
    "dateTypeLabel": "Kuupäeva tüüp",
    "valueLabel": "Väärtus",
    "fixed": "Parandatud",
    "current": "Praegune",
    "past": "Möödas",
    "future": "Tulevane",
    "popupTitle": "Vali väärtus",
    "hintForFixedDateType": "Vihje: Eelseadistatud vaikeväärtusena kasutatakse määratud kuupäeva ja kellaaega.",
    "hintForCurrentDateType": "Vihje: Eelseadistatud vaikeväärtusena kasutatakse praegust kuupäeva ja kellaaega.",
    "hintForPastDateType": "Vihje: määratud väärtus lahutatakse valmisvaikeväärtuse saamiseks praegusest kuupäevast ja kellaajast",
    "hintForFutureDateType": "Vihje: määratud väärtus liidetakse valmisvaikeväärtuse saamiseks praegusele kuupäevale ja kellaajale",
    "noDateDefinedTooltip": "Kuupäeva pole määratletud",
    "relativeDateWarning": "Eelseadistatud vaikeväärtuse salvestamiseks tuleb määrata kuupäeva või kellaaja väärtus."
  }
});