define({
  "showArcgisBasemaps": "Zahrnout podkladové mapy portálu",
  "add": "Kliknutím přidáte novou podkladovou mapu.",
  "edit": "Vlastnosti",
  "titlePH": "Název podkladové mapy",
  "thumbnailHint": "Kliknutím na obrázek jej aktualizujete.",
  "urlPH": "Adresa URL vrstvy",
  "addlayer": "Přidat podkladovou mapu",
  "warning": "Nesprávný vstup",
  "save": "Zpět a Uložit",
  "back": "Zpět a Zrušit",
  "addUrl": "Přidat URL",
  "autoCheck": "Automatická kontrola",
  "checking": "Probíhá kontrola…",
  "result": "Úspěšně uloženo",
  "spError": "Všechny podkladové mapy přidané do galerie musí mít stejný souřadnicový systém.",
  "invalidTitle1": "Podkladová mapa '",
  "invalidTitle2": "' již existuje. Zvolte jiný název.",
  "invalidBasemapUrl1": "Vrstvu tohoto typu nelze použít jako podkladovou mapu.",
  "invalidBasemapUrl2": "Souřadnicový systém přidávané podkladové mapy se liší od souřadnicového systému současné mapy.",
  "addBaselayer": "Přidat vrstvu podkladové mapy"
});