define({
  "_widgetLabel": "Üzleti elemző",
  "addPoint": "Adjon meg pontot a térképre kattintva",
  "addRingsDtWt": "Adjon hozzá köröket, vezetési időt vagy gyaloglási időt.",
  "apply": "Alkalmaz",
  "back": "Vissza",
  "colon": ":",
  "creditInformation": "Hitelinformáció",
  "driveTime": "Vezetési idő",
  "esriInfographics": "Esri-infografika",
  "esriReports": "Esri-jelentések",
  "headerDescription_km": "kilométer",
  "headerDescription_miles": "mérföld",
  "headerDescription_minutes": "szögperc",
  "infographics": "Infógrafika",
  "invalidValueRing": "Az értékeknek 0-1000 között kell lennie.",
  "invalidValueDTWT": "Az értékeknek 0-300 között kell lennie.",
  "km": "km",
  "miles": "mérföld",
  "minutes": "perc",
  "myInfographics": "Saját infógrafika",
  "myReports": "Saját jelentések",
  "noPermissions": "Fiókja nem jogosult az Üzleti elemző widget fuittatására.  Az Üzleti elemző widget futtatásához szervezete rendszergazdájának Téradatbővítés- és hálózatelemzés-<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">jogosultságot</a> kell adnia Önnek, továbbá <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">krediteket</a> kell hozzárendelnie.",
  "radii": "sugarak",
  "radius": "Sugár",
  "radius_lowercase": "sugár",
  "reports": "Jelentések",
  "ring": "Gyűrű",
  "rings": "Gyűrűk",
  "runInfographic": "Infografika futtatása",
  "runReport": "Jelentés futtatása",
  "selectPointOrPolygon": "Válasszon pont vagy polygon vektoros elemet a térképen, keressen címet vagy helyet, vagy pedig helyezzen el jelölőt a térképen, ha szeretne további információkat megtekinteni a területekre vonatkozóan.",
  "selectReport": "Jelentés kiválasztása",
  "selectTemplate": "Sablon kiválasztása",
  "sharedInfographics": "Megosztott infógrafika",
  "sharedReports": "Megosztott jelentések",
  "thisEntryIsNotValid": "A megadott érték érvénytelen.",
  "time": "Idő",
  "walkTime": "Gyaloglási idő",
  "widgetDescription": "Az adott terület fő mutatóit és adatait összegző inforgrafikákhoz és jelentésekhez férhet hozzá.",
  "None": "Kiválasztás…"
});