define({
  "tabs_section_Label": "Separadores",
  "addTab": "Adicionar Separador",
  "layerName": "Camada",
  "layerType": "Tipo de Análise",
  "layerLabel": "Rótulo",
  "actions": "Acções",
  "closest": "Elemento Mais Próximo",
  "proximity": "Proximidade",
  "summary": "Resumo",
  "select_lbl": "-- Seleccionar --",
  "general_setting_Label": "Configurações Gerais",
  "units_text_lbl": "Unidades de Distância",
  "miles": "Milhas",
  "kilometers": "Quilómetros",
  "feet": "Pés",
  "meters": "Metros",
  "yards": "Jardas",
  "nauticalMiles": "Milhas Náuticas",
  "maximum_distance_lbl": "Escolher Máxima Distancia de Elemento",
  "buffer_text_lbl": "Etiqueta de Buffer",
  "buffer_lbl": "Distância do Buffer",
  "buffer_max_lbl": "Distancia Máxima de Buffer",
  "buffer_min_lbl": "Distancia Mínima de Buffer",
  "routing_checkBox": "Activar Roteamento",
  "weather_Label": "Opções de Condições Atmosféricas",
  "weather_checkBox": "Incluir Informações de Condições Atmosféricas",
  "selectLayers": "Seleccionar Camadas de Condições Atmosféricas",
  "currentlySelectedLayer": "Camadas Meteorológicas Atualmente Selecionadas",
  "missingTabLabel": "Está a faltar uma etiqueta a pelo menos um separador",
  "missingLayerInWebMap": "Nenhuma camada operacional encontrada.",
  "selectFields": "Selecionar Campos",
  "addField": "Adicionar Campo",
  "sum": "SOMA",
  "min": "MÍNIMO",
  "max": "MÁXIMO",
  "avg": "MÉDIA",
  "count": "CONTAGEM",
  "area": "ÁREA",
  "length": "COMPRIMENTO",
  "count_checkBox": "Exibir Contagem de Elementos",
  "area_checkBox": "Exibir Soma de Área",
  "length_checkBox": "Exibir Soma de Comprimento",
  "max_records": "Limite máximo atingido",
  "save_label": "Guardar Opções",
  "save_checkbox": "Ativar Guardar",
  "csv_label": "Opções CSV",
  "csv_checkbox": "Exportar Todos os Campos da Camada",
  "display_label": "Opções de Exibição",
  "display_checkbox": "Exibir Resumo de Elementos",
  "must_select_template": "Por favor, selecione um dos modelos de edição em Guardar Opções.",
  "count_label": "Etiqueta de Contagem",
  "area_label": "Etiqueta de Área",
  "length_label": "Etiqueta de Comprimento",
  "invalid_string_width": "O valor é muito comprido. ",
  "layer_type_not_supported": "Tipo de camada não suportada: ",
  "groupedSummary": "Contagens Agrupadas",
  "groupByField": "Agrupar por Campos",
  "labelType": "Incluir Rótulo",
  "prefix": "Como Prefixo",
  "suffix": "Como Sufixo",
  "need_group_field": "Por favor, utilize a ação Editar para definir um Grupo Por campo",
  "fieldTitle": "Campo",
  "typeTitle": "Tipo",
  "actionsTitle": "Acções"
});