define({
  "addTaskTip": "Pridėti vieną arba daugiau filtrų į valdiklį ir konfigūruoti kiekvieno iš jų parametrus.",
  "enableMapFilter": "Pašalinti iš anksto nustatytą sluoksnio filtrą iš žemėlapio.",
  "newFilter": "Naujas filtras",
  "filterExpression": "Filtravimo išraiška",
  "layerDefaultSymbolTip": "Naudoti sluoksnio numatytąjį simbolį",
  "uploadImage": "Įkelti atvaizdą",
  "selectLayerTip": "Pasirinkite sluoksnį.",
  "setTitleTip": "Nurodykite pavadinimą.",
  "noTasksTip": "Nesukonfigūruota jokių filtrų. Norėdami pridėti naują, spustelėkite \"${newFilter}\".",
  "collapseFiltersTip": "Suglausti filtro išraiškas (jei tokių yra), kai atidaromas valdiklis",
  "zoomtoTip": "Pritaikius sluoksnio filtrą, priartinti likusius elementus",
  "zoombacktoTip": "Išjungus visus sluoksnio filtrus, grįžti į pradinę žemėlapio aprėptį",
  "groupByLayerTip": "Grupuoti filtrus pagal sluoksnį",
  "autoApplyWhenValueInput": "Įvedus reikšmę, šį filtrą taikyti automatiškai",
  "autoApplyWhenWidgetOpen": "Šį filtrą taikyti, kai valdiklis atidarytas",
  "info": "Informacija",
  "expressions": "Išraiškos",
  "allowCustom": "Leisti kurti pasirinktinius filtrus",
  "filterActions": "Pasirinktinio filtro veiksmai",
  "custom": "Įgalinti pasirinktinį filtrą",
  "resetAll": "Įgalinti visų įvesties reikšmių nustatymą iš naujo",
  "turnOffAll": "Įgalinti visų filtrų išjungimą",
  "matchMsgSetAll": "Rodyti elementus, atitinkančius visus filtrus",
  "matchMsgSetAny": "Rodyti elementus, atitinkančius bet kurį filtrą"
});