define({
  "_widgetLabel": "Vẽ",
  "selectDrawMode": "Chọn chế độ vẽ",
  "clear": "Xóa",
  "point": "Điểm",
  "line": "Đường",
  "polyline": "Đa tuyến",
  "freehandPolyline": "Đa tuyến vẽ tay",
  "triangle": "Hình tam giác",
  "extent": "Đường bao",
  "circle": "Hình tròn",
  "ellipse": "Hình Elip",
  "polygon": "Vùng",
  "freehandPolygon": "Vùng vẽ tự do",
  "text": "Văn bản",
  "style": "Kiểu",
  "alpha": "Độ trong suốt",
  "width": "Chiều rộng",
  "size": "Kích cỡ",
  "color": "Màu sắc",
  "markerColor": "Màu điểm đánh dấu",
  "outlineColor": "Màu đường viền",
  "lineColor": "Màu đường",
  "fillColor": "Tô màu",
  "showMeasurements": "Hiển thị các phép đo",
  "showLocationMeasurement": "Hiển thị phép đo khoảng cách",
  "showAreaMeasurement": "Hiển thị phép đo diện tích",
  "showDistanceMeasurement": "Hiển thị phép đo khoảng cách",
  "showDistanceMeasurementForLine": "Hiển thị phép đo chiều dài",
  "showDistanceMeasurementForPolygon": "Hiển thị phép đo chu vi",
  "locationToggleOn": "Nhấn nút chuyển đổi để hiển thị phép đo vị trí",
  "locationToggleOff": "Nhấn nút chuyển đổi để ẩn phép đo vị trí",
  "areaToggleOn": "Nhấn nút chuyển đổi để hiển thị phép đo diện tích",
  "areaToggleOff": "Nhấn nút chuyển đổi để ẩn phép đo diện tích",
  "distanceForLineToggleOn": "Nhấn nút chuyển đổi để hiển thị phép đo chiều dài",
  "distanceForLineToggleOff": "Nhấn nút chuyển đổi để ẩn phép đo chiều dài",
  "distanceForPolygonToggleOn": "Nhấn nút chuyển đổi để hiển thị phép đo chu vi",
  "distanceForPolygonToggleOff": "Nhấn nút chuyển đổi để ẩn phép đo chu vi",
  "areaUnits": "Đơn vị diện tích",
  "distanceUnits": "Đơn vị khoảng cách",
  "kilometers": "Kilômét",
  "miles": "Dặm",
  "meters": "Mét",
  "feet": "Feet",
  "yards": "Thước",
  "nauticalmiles": "Hải lý",
  "squareKilometers": "Kilômét vuông",
  "squareMiles": "Dặm vuông",
  "acres": "Mẫu Anh",
  "hectares": "Hecta",
  "squareMeters": "Mét vuông",
  "squareFeet": "Feet vuông",
  "squareYards": "Thước vuông",
  "undo": "Hoàn tác",
  "redo": "Làm lại",
  "results": "Kết quả",
  "points": "Điểm",
  "lines": "Đường",
  "areas": "Khu vực",
  "locationLabel": "Vị trí: ${value}",
  "areaLabel": "Diện tích: ${value} ${unit}",
  "distanceLabel": "Khoảng cách: ${value} ${unit}",
  "distanceLabelForLine": "Chiều dài: ${value} ${unit}",
  "distanceLabelForPolygon": "Chu vi: ${value} ${unit}"
});