define({
  "transparencyLabel": "Przezroczystość",
  "outline": "Obrys",
  "fill": "Wypełnienie (kolor zostanie zastosowany tylko wtedy, gdy wybranym stylem jest styl pełny)",
  "style": "Styl",
  "mandatoryLabel": "Obowiązkowa odległość ewakuacji",
  "mandatoryButtonLabel": "Skonfiguruj ustawienia obowiązkowej odległości ewakuacji",
  "safeLabel": "Bezpieczna odległość ewakuacji",
  "safeButtonLabel": "Skonfiguruj ustawienia bezpiecznej odległości ewakuacji",
  "selectOpLayerLabel": "Wybierz warstwę operacyjną dla wyników",
  "selectDefaultMeasurementLabel": "Wybierz domyślną jednostkę miary",
  "helpIconTooltip": "Lista warstw operacyjnych jest zapełniana warstwami z bieżącej mapy internetowej o typie geometrii poligonowej.",
  "lineStyles": {
    "esriSLSDash": "Kreska",
    "esriSLSDashDot": "Kreska-kropka",
    "esriSLSDashDotDot": "Kreska-kropka-kropka",
    "esriSLSDot": "Kropka",
    "esriSLSLongDash": "Długa kreska",
    "esriSLSLongDashDot": "Długa kreska-kropka",
    "esriSLSNull": "Pusta wartość",
    "esriSLSShortDash": "Krótka kreska",
    "esriSLSShortDashDot": "Krótka kreska-kropka",
    "esriSLSShortDashDotDot": "Krótka kreska-kropka-kropka",
    "esriSLSShortDot": "Krótka kropka",
    "esriSLSSolid": "Stały"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Cofnij",
    "esriSFSCross": "Krzyż",
    "esriSFSDiagonalCross": "Po przekątnej",
    "esriSFSForwardDiagonal": "Dalej",
    "esriSFSHorizontal": "Poziomo",
    "esriSFSNull": "Pusta wartość",
    "esriSFSSolid": "Stały",
    "esriSFSVertical": "Pionowo"
  },
  "threatTypeLabel": "Typ zagrożenia",
  "symbologyLabel": "Symbolizacja",
  "generalLabel": "Ogólne",
  "addThreatTypesLabel": "Dodaj typ zagrożenia",
  "threatTypeColLabel": "Typ zagrożenia",
  "actions": "Akcje",
  "newThreatTypePopupLabel": "Nowy typ zagrożenia",
  "chooseDefaultThreatTypeIconLabel": "Wybierz spośród domyślnych",
  "mandatoryDistance": "Obowiązkowa odległość ewakuacji",
  "safeDistance": "Bezpieczna odległość ewakuacji",
  "units": "Jednostki",
  "chooseDefaultThreatLabel": "Wybierz domyślny typ zagrożenia",
  "defaultThreatTypePopUpLabel": "Domyślne typy zagrożeń",
  "editThreatLabel": "Edytuj zagrożenie",
  "defaultThreatTypeIconTooltip": "Lista domyślnych typów zagrożeń",
  "uniqueThreatTypeMsg": "Wprowadź unikalny typ zagrożenia. Typ zagrożenia o tej nazwie już istnieje.",
  "requiredThreatTypeMsg": "To pole jest wymagane",
  "unitMeasureLabel": "Odległości są podawane w {0}",
  "pipeBombLabel": "Bomba rurowa",
  "suicideBombLabel": "Bomba samobójcza",
  "briefcaseLabel": "Teczka",
  "carLabel": "Samochód",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Mały samochód dostawczy",
  "containerWaterTruckLabel": "Pojazd kontenerowy/cysterna",
  "semiTrailerLabel": "Naczepa"
});