define({
  "symbolologyTabLabel": "Konfigurér symbologi",
  "facilitiesDescription": "Laget Faciliteter",
  "demographicsDescription": "Laget Demografi",
  "settingsTitle": "Indstillinger",
  "spillLocationLabel": "Udslippets placering",
  "spillLocationButtonLabel": "Konfigurér indstillinger for udslipsposition",
  "IISettingsLabel": "Første isolationszone",
  "IIButtonLabel": "Konfigurér indstillinger for første isolation",
  "PASettingsLabel": "Beskyttelseszone",
  "PAButtonLabel": "Konfigurér indstillinger for beskyttelsesforanstaltninger",
  "downwindSettingsLabel": "Medvindszone",
  "downwindButtonLabel": "Konfigurer medvindsindstillinger",
  "fireSettingsLabel": "Brandisolationszone",
  "fireButtonLabel": "Konfigurér indstillinger for brandisolation",
  "bleveSettingsLabel": "BLEVE-isolationszone",
  "bleveButtonLabel": "Konfigurer BLEVE-indstillinger",
  "transparency": "Gennemsigtighed",
  "outline": "Kontur",
  "fill": "Fyld (farve anvendes kun, når typografien er indstillet til massiv)",
  "style": "Type",
  "selectOpLayerLabel": "Vælg et operationelt lag for at opnå resultater",
  "selectDefaultMeasurementLabel": "Vælg en standardmåleenhed",
  "helpIconTooltip": "Listen med operationelle lag består af lag fra det aktuelle webkort, der er af geometritypen polygon.",
  "colorPicker": "Farvevælger",
  "lineStyles": {
    "esriSLSDash": "Streg",
    "esriSLSDashDot": "Streg-prik",
    "esriSLSDashDotDot": "Streg-prik-prik",
    "esriSLSDot": "Prik",
    "esriSLSLongDash": "Lang streg",
    "esriSLSLongDashDot": "Lang streg-prik",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Kort streg",
    "esriSLSShortDashDot": "Kort streg-prik",
    "esriSLSShortDashDotDot": "Kort streg-prik-prik",
    "esriSLSShortDot": "Kort prik",
    "esriSLSSolid": "Udfyldt"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Baglæns",
    "esriSFSCross": "Kryds",
    "esriSFSDiagonalCross": "Diagonalt",
    "esriSFSForwardDiagonal": "Frem",
    "esriSFSHorizontal": "Vandret",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Udfyldt",
    "esriSFSVertical": "Lodret"
  }
});