define({
  "tabs_section_Label": "לשוניות",
  "addTab": "הוסף לשונית",
  "layerName": "שכבה",
  "layerType": "סוג ניתוח",
  "layerLabel": "תווית",
  "actions": "פעולות",
  "closest": "היישות הקרובה ביותר",
  "proximity": "קרבה",
  "summary": "סיכום",
  "select_lbl": "-- בחר --",
  "general_setting_Label": "הגדרות כלליות",
  "units_text_lbl": "יחידות מרחק",
  "maximum_distance_lbl": "מרחק מקסימום מהישות הקרובה ביותר",
  "buffer_text_lbl": "תווית חיץ",
  "buffer_lbl": "מרחק חיץ",
  "buffer_max_lbl": "מרחק מקסימום לחיץ",
  "buffer_min_lbl": "מרחק מינימום לחיץ",
  "buffer_default_lbl": "מרחק ברירת מחדל לחיץ",
  "not_less_than_max": "המרחק חייב להיות קטן ממרחק החיץ המרבי",
  "not_between": "המרחק חייב להיות בין מרחק החיץ המרבי והמינימלי",
  "not_more_than_min": "המרחק חייב להיות גדול ממרחק החיץ המינימלי",
  "not_valid_number": "חייב להיות מספר חוקי",
  "invalid_value": "הערך '‎${type}‎' לא חוקי",
  "routing_checkBox": "הפעל ניתוב",
  "weather_removed_message": "אפשרויות מזג האוויר אינן זמינות עוד לווידג'ט זה.",
  "currentlySelectedLayer": "בחר משכבות מפה",
  "missingTabLabel": "לפחות לאחת מהלשוניות חסרה תווית",
  "missingLayerInWebMap": "לא נמצאו שכבות אופרטיביות.",
  "selectFields": "בחר שדות",
  "addField": "הוסף שדה",
  "sum": "סכום",
  "min": "מינימום",
  "max": "מקסימום",
  "avg": "ממוצע",
  "count": "ספירה",
  "area": "אזור",
  "length": "אורך",
  "count_checkBox": "הצג ספירת ישויות",
  "area_checkBox": "הצג סכום שטח",
  "length_checkBox": "הצג סכום אורך",
  "max_records": "הגעת למספר המקסימלי",
  "save_label": "שמור אפשרויות",
  "save_checkbox": "הפעל שמירה",
  "report_label": "אפשרויות דוח",
  "report_checkbox": "הפעל דוח",
  "csv_label": "אפשרויות CSV",
  "display_label": "הצג אפשרויות",
  "display_checkbox": "הצג ישויות סיכום",
  "setSelectionColor": "הגדר את צבע הבחירה",
  "snapshot_label": "אפשרויות צילום בזק",
  "snapshot_checkbox": "אפשר צילום בזק",
  "must_select_template": "בחר אחת מתבניות העריכה תחת 'שמור אפשרויות'",
  "count_label": "תווית מונה",
  "area_label": "תווית שטח",
  "length_label": "תווית אורך",
  "invalid_string_width": "הערך ארוך מדי. ",
  "layer_type_not_supported": "סוג השכבה אינו נתמך",
  "groupedSummary": "ספירות מקובצות",
  "groupByField": "קיבוץ לפי שדה",
  "labelType": "הוסף תווית",
  "prefix": "כתחילית",
  "suffix": "כסיומת",
  "need_group_field": "השתמש בפעולת העריכה להגדרת 'קיבוץ לפי שדה'.",
  "fieldTitle": "שדה",
  "typeTitle": "סוג",
  "actionsTitle": "פעולות",
  "save_point_checkbox": "שמור נקודות",
  "save_line_checkbox": "שמור קווים",
  "save_poly_checkbox": "שמור פוליגונים",
  "no_valid_popup_fields": "אין שדות חוקיים ב-Popup. השתמש בפעולת העריכה כדי לקבוע שדה.",
  "no_valid_fields": "אין שדות חוקיים. השתמש בפעולת העריכה כדי לקבוע להגדרות תצוגה.",
  "incident_label": "תווית כרטיסייה",
  "locate_incident_label": "אזור תווית עניין",
  "incident": "מקרה",
  "locate_incident": "אתר מקרים",
  "buffer_value": "מרחק חיץ",
  "tab_options": "ניתוח",
  "export_options": "פלט",
  "instruction_save": "שמור את המיקום בשירות ישות.",
  "instruction_snapshot": "צור webmap המבוסס על המיקום.",
  "instruction_report": "צור דוח מודפס של המיקום.",
  "instruction_all_fields": "הרחב שדות עם הורדת CSV.",
  "data_label": "הגדרות פלט נתונים",
  "layer_error": "שכבה חסרה או לא חוקית.",
  "visibility_checkBox": "השבת את הניהול של ניראות השכבות",
  "allFieldsLabel": "כל השדות",
  "configuredPopUpFieldsLabel": "הגדר שדות חלונות קופצים",
  "analysisTypeFieldsLabel": "שדות סוג ניתוח",
  "reportOptionsMsg": "יש לבחור אפשרות דוח אחת לפחות",
  "analysisSummaryLabelForReport": "סיכום סוג ניתוח",
  "popUpSummaryLabelForReport": "הגדר תצורה של סיכום שדות חלונות קופצים",
  "downloadTab": {
    "reportLegend": "הגדרות דוח",
    "textColorLabel": "בחר צבע עבור כותרת העמודה",
    "setButtonLabel": "הגדר",
    "printGPServiceLabel": "URL של שירות הדפסה",
    "logoLabel": "לוגו",
    "logoChooserHint": "לחץ על התמונה כדי לשנותה",
    "footnoteLabel": "הערת שוליים"
  },
  "roundValue": "עיגול ל-",
  "roundValueTitle": "עיגול ערכי שדה",
  "truncateValue": "חיתוך ל-",
  "truncateValueTitle": "חיתוך ערכי שדה",
  "significantFigures": "נתונים מובהקים",
  "fieldOptions": "אפשרויות שדה",
  "modifyValues": "שינוי ערכי שדה",
  "validatePlaces": "חייב להיות מספר שלם",
  "onlyDouble": "אפשרויות השדה הנוספות נתמכות עבור שדות מספריים בלבד.",
  "layerNotAvalible": "השכבה לא נמצאה",
  "missingLayer": "שם: ‎${name}‎",
  "missingLayerHint": "שכבה אחת או יותר שאליה קיימת הפניה בתצורה זו אינה זמינה כעת.",
  "drawGeodesic": "שרטט צורות גיאודזיות"
});