define({
  "transparencyLabel": "Transparencia",
  "outline": "Lista",
  "fill": "Relleno (el color solo se aplica si el estilo es sólido)",
  "style": "Estilo",
  "mandatoryLabel": "Distancia de evacuación obligatoria",
  "mandatoryButtonLabel": "Configurar los ajustes de Distancia de evacuación obligatoria",
  "safeLabel": "Distancia de evacuación segura",
  "safeButtonLabel": "Configurar los ajustes de Distancia de evacuación segura",
  "selectOpLayerLabel": "Seleccionar una capa operativa para los resultados",
  "selectDefaultMeasurementLabel": "Seleccionar una unidad de medida predeterminada",
  "helpIconTooltip": "La lista de capas operativas se rellena con las capas del mapa web actual que corresponden al tipo de geometría de polígono.",
  "lineStyles": {
    "esriSLSDash": "Guion",
    "esriSLSDashDot": "Guion Punto",
    "esriSLSDashDotDot": "Guion Punto Punto",
    "esriSLSDot": "Punto",
    "esriSLSLongDash": "Guion largo",
    "esriSLSLongDashDot": "Guion largo, Punto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Guion corto",
    "esriSLSShortDashDot": "Guion corto Punto",
    "esriSLSShortDashDotDot": "Guion corto Punto Punto",
    "esriSLSShortDot": "Corto Punto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atrás",
    "esriSFSCross": "Cruz",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Hacia delante",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  },
  "threatTypeLabel": "Tipo de amenaza",
  "symbologyLabel": "Simbología",
  "generalLabel": "General",
  "addThreatTypesLabel": "Agregar tipo de amenaza",
  "threatTypeColLabel": "Tipo de amenaza",
  "actions": "Acciones",
  "newThreatTypePopupLabel": "Nuevo tipo de amenaza",
  "chooseDefaultThreatTypeIconLabel": "Elegir de entre los valores predeterminados",
  "mandatoryDistance": "Distancia de evacuación obligatoria",
  "safeDistance": "Distancia de evacuación segura",
  "units": "Unidades",
  "chooseDefaultThreatLabel": "Seleccionar un tipo de amenaza predeterminado",
  "defaultThreatTypePopUpLabel": "Tipos de amenaza predeterminados",
  "editThreatLabel": "Editar amenaza",
  "defaultThreatTypeIconTooltip": "Lista de tipos de amenaza predeterminados",
  "uniqueThreatTypeMsg": "Introduzca un tipo de amenaza único; ya existe un tipo de amenaza con este nombre.",
  "requiredThreatTypeMsg": "Este campo es obligatorio.",
  "unitMeasureLabel": "Las distancias están en {0}",
  "pipeBombLabel": "Bomba casera",
  "suicideBombLabel": "Bomba suicida",
  "briefcaseLabel": "Maletín",
  "carLabel": "Automóvil",
  "suvVanLabel": "Todoterreno/furgoneta",
  "smallDeliveryTruckLabel": "Camión de reparto pequeño",
  "containerWaterTruckLabel": "Contenedor/camión cisterna",
  "semiTrailerLabel": "Semirremolque"
});