define({
  "showArcgisBasemaps": "Vis bakgrunnskart fra portal",
  "add": "Klikk for å legge til et nytt bakgrunnskart",
  "edit": "Egenskaper",
  "titlePH": "Tittel på bakgrunnskart",
  "thumbnailHint": "Klikk på bildet for å oppdatere",
  "urlPH": "Lag-URL",
  "addlayer": "Legg til bakgrunnskart",
  "warning": "Feil inndata",
  "save": "Tilbake og lagre",
  "back": "Tilbake og avbryt",
  "addUrl": "Legg til URL",
  "autoCheck": "Automatisk kontroll",
  "checking": "Kontrollerer ...",
  "result": "Lagring vellykket",
  "spError": "Alle bakgrunnskart som legges til i galleriet, må ha den samme geografiske referansesystem.",
  "invalidTitle1": "Bakgrunnskartet",
  "invalidTitle2": "finnes allerede. Du må velge en annen tittel.",
  "invalidBasemapUrl1": "Denne typen lag kan ikke brukes som bakgrunnskart.",
  "invalidBasemapUrl2": "Bakgrunnskartet du legger til har en annen geografisk referanse enn det gjeldende kartet.",
  "addBaselayer": "Legg til bakgrunnskartlag"
});