define({
  "_widgetLabel": "Anàlisi d'incidents",
  "_featureAction_SetAsIncident": "Defineix com a incident",
  "incident": "Incident",
  "weather": "El temps",
  "locate_incident": "Localitza l'incident",
  "clear_incidents": "Esborrar els incidents",
  "reverse_geocoded_address": "Adreça més propera",
  "reverse_geocoded_error": "No disponible",
  "miles": "Milles",
  "kilometers": "Quilòmetres",
  "feet": "Peus",
  "meters": "Metres",
  "yards": "Iardes",
  "nauticalMiles": "Milles nàutiques",
  "now": "NOW",
  "wind": "WIND",
  "SUN": "DG.",
  "MON": "DL.",
  "TUE": "DT.",
  "WED": "DC.",
  "THU": "DJ.",
  "FRI": "DV.",
  "SAT": "DS.",
  "defaultTabMsg": "No s'ha identificat cap incident.",
  "useMapExtent": "Utilitza l'extensió de mapa actual",
  "noFeaturesFound": "No s'ha trobat cap entitat.",
  "downloadCSV": "BAIXA EL CSV",
  "sum": "SUM",
  "min": "MIN",
  "max": "MAX",
  "avg": "AVG",
  "count": "COUNT",
  "area": "AREA",
  "length": "LENGTH"
});