define({
  "transparencyLabel": "Läbipaistvus",
  "outline": "Äärejoon",
  "fill": "Täida (värv rakendatakse ainult juhul, kui valitud on pidev laad)",
  "style": "Laad",
  "mandatoryLabel": "Kohustuslik evakuatsioonikaugus",
  "mandatoryButtonLabel": "Konfigureeri kohustusliku evakuatsioonikauguse sätted",
  "safeLabel": "Ohutu evakuatsioonikaugus",
  "safeButtonLabel": "Konfigureeri ohutu evakuatsioonikauguse sätted",
  "selectOpLayerLabel": "Vali tulemuste töökiht",
  "selectDefaultMeasurementLabel": "Vali vaikimisi mõõtühik",
  "helpIconTooltip": "Töökihtide nimekiri sisaldab kihte praeguselt veebikaardilt, mis on polügooni tüüpi.",
  "lineStyles": {
    "esriSLSDash": "Katkendlik",
    "esriSLSDashDot": "Katkendlik punktiga",
    "esriSLSDashDotDot": "Katkendlik kahe punktiga",
    "esriSLSDot": "Punktiir",
    "esriSLSLongDash": "Pikk katkendlik kriips",
    "esriSLSLongDashDot": "Pikk katkendlik kriips punktiga",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Lühike katkendlik kriips",
    "esriSLSShortDashDot": "Lühike katkendlik kriips punktiga",
    "esriSLSShortDashDotDot": "Lühike katkendlik kriips kahe punktiga",
    "esriSLSShortDot": "Lühike punktiir",
    "esriSLSSolid": "Pidev"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Tagasi",
    "esriSFSCross": "Rist",
    "esriSFSDiagonalCross": "Diagonaal",
    "esriSFSForwardDiagonal": "Edasi",
    "esriSFSHorizontal": "Horisontaalne",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Pidev",
    "esriSFSVertical": "Vertikaalne"
  },
  "threatTypeLabel": "Ohu tüüp",
  "symbologyLabel": "Sümboloogia",
  "generalLabel": "Üldine",
  "addThreatTypesLabel": "Lisa ohu tüüp",
  "threatTypeColLabel": "Ohu tüüp",
  "actions": "Toimingud",
  "newThreatTypePopupLabel": "Uus ohu tüüp",
  "chooseDefaultThreatTypeIconLabel": "Vali vaikeväärtusest",
  "mandatoryDistance": "Kohustuslik evakueerimise kaugus",
  "safeDistance": "Ohutu evakueerimise kaugus",
  "units": "Ühikud",
  "chooseDefaultThreatLabel": "Vali ohu vaiketüüp",
  "defaultThreatTypePopUpLabel": "Ohu vaiketüübid",
  "editThreatLabel": "Muuda ohtu",
  "defaultThreatTypeIconTooltip": "Ohu vaiketüüpide loend",
  "uniqueThreatTypeMsg": "Sisestage unikaalne ohu tüüp; selle nimega ohu tüüp on juba olemas.",
  "requiredThreatTypeMsg": "See väli on nõutav",
  "unitMeasureLabel": "Kauguste mõõtühik on {0}",
  "pipeBombLabel": "Torupomm",
  "suicideBombLabel": "Enesetapupomm",
  "briefcaseLabel": "Portfell",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Väike kaubaauto",
  "containerWaterTruckLabel": "Konteinerveok/Veepaagiga veok",
  "semiTrailerLabel": "Poolhaagis"
});