define({
  "chartSettingLabel": "图表设置",
  "addNewLabel": "新增",
  "generalSettingLabel": "常规设置",
  "layerChooser": {
    "title": "选择要制表的图层",
    "selectPolygonLayerLabel": "选择图层",
    "selectPolygonLayerHintText": "提示: 如果配置多个图表，则图层必须为相同的几何类型",
    "selectRelatedTableLayerLabel": "选择图层的相关表",
    "selectRelatedTableLayerHintText": "提示: 仅显示含数值字段的表",
    "errorInSelectingPolygonLayer": "请选择具有相关点图层的图层。",
    "errorInSelectingRelatedLayer": "请选择图层的有效相关表/图层。",
    "polygonLayerNotHavingRelationships": "所选图层不具有任何相关表/图层。"
  },
  "ChartSetting": {
    "sectionTitle": "章节标题",
    "sectionTitleHintText": "提示: 显示在章节页眉标题中",
    "chartTitle": "图表标题",
    "chartTitleHintText": "提示: 居中显示在图表顶部",
    "chartDescription": "说明",
    "chartDescriptionHintText": "提示: 显示在图表下方",
    "chartType": "图表类型",
    "barChart": "条形图",
    "pieChart": "饼图",
    "polarChart": "极坐标图",
    "dataSeriesField": "数据系列字段",
    "labelField": "标注字段",
    "chartColor": "图表颜色",
    "singleColor": "单色",
    "colorByTheme": "按主题分类的颜色",
    "colorByFieldValue": "按字段值分类的颜色",
    "xAxisTitle": "X 轴标题",
    "xAxisHintText": "提示: X 轴标题",
    "yAxisTitle": "Y 轴标题",
    "yAxisHintText": "提示: Y 轴标题",
    "fieldColorLabel": "标注",
    "fieldColorColor": "颜色",
    "defaultFieldSelectLabel": "选择",
    "errMsgFieldValuesNotFound": "无法找到所选字段的值",
    "errMsgSectionTitle": "请输入章节标题",
    "errMsgFieldByValue": "请选择字段值",
    "settingTabTitle": "设置",
    "layoutTabTitle": "布局",
    "polarChartSelectFieldsHintText": "提示: 选择字段以生成极坐标图",
    "visibilityText": "可见性",
    "fieldNameText": "字段名",
    "aliasNameText": "别名",
    "errMsgPolarFieldsRequired": "请选择三个或更多的字段以生成极坐标图",
    "polarChartPolygonFillLabel": "填充面",
    "polarChartPolygonFillHintText": "提示: 选择复选框以显示填充极坐标图的面",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "常规设置",
    "locationSymbolLabel": "图形位置符号",
    "locationSymbolHintText": "提示: 用于显示地址符号和单击位置",
    "refreshIntervalLabel": "刷新间隔",
    "refreshIntervalHintText": "提示: 用于根据此间隔刷新图表。请在 1 到 1440 分钟的区间内指定一个值",
    "errMsgRefreshInterval": "请在 0 到 1440 分钟的区间内指定刷新间隔",
    "symbolPickerPreviewText": "预览:"
  }
});