define({
  "settings": "הגדרות",
  "titleSettings": "הגדרות טקסט",
  "imageSettings": "הגדרות תמונה",
  "backgroundColor": "צבע רקע",
  "alignment": "יישור",
  "textSize": "גודל טקסט",
  "textColor": "צבע טקסט",
  "dataSource": "מקור הנתונים",
  "chartSettings": "הגדרות תרשים",
  "data": "נתונים",
  "dataLabels": "תוויות נתונים",
  "displayMode": "מצב תצוגה",
  "featureOption": "הצג ערכים עבור כל ישות בנפרד",
  "categoryOption": "הצג ערכים לפי קטגוריות",
  "countOption": "הצג מספרי ישויות לפי קטגוריות",
  "fieldOption": "הצג ערכי מאפיינים כתרשימים",
  "categoryField": "שדה קטגוריה",
  "labelField": "שדה תווית",
  "valueFields": "שדות ערך",
  "operation": "תפעולי",
  "sumOption": "סכום",
  "averageOption": "ממוצע",
  "minOption": "מינימום",
  "maxOption": "מקסימום",
  "dataFormat": "פורמט נתונים",
  "decimalPlaces": "ספרות עשרוניות",
  "prefix": "קידומת",
  "suffix": "סיומת",
  "dataType": "סוג נתונים",
  "featureCount": "ספירת יישויות",
  "fieldStatistics": "סטטיסטיקת שדה",
  "display": "תצוגה",
  "chartColor": "צבע תרשים",
  "horizontalAxis": "ציר אופקי",
  "verticalAxis": "ציר אנכי",
  "legend": "מקרא",
  "position": "מיקום",
  "top": "עליון",
  "bottom": "תחתון",
  "useDataSourceSelection": "השתמש בבחירה",
  "dataSourceFilterByExtent": "סינון לפי תיחום",
  "changeTemplate": "שנה תבנית",
  "numberSettings": "הגדרות מספר",
  "gaugeSettings": "הגדרות מדיד",
  "indicators": "מחוונים",
  "ifValue": "ערך 'אם'",
  "and": "וגם",
  "numberOperatorIsLessThan": "הוא פחות מ-",
  "numberOperatorIsGreaterThan": "הוא גדול מ-",
  "numberOperatorIsBetween": "הוא בין",
  "numberOperatorIsEqual": "שווה ל-",
  "numberOperatorIsNotEqual": "לא שווה ל-",
  "then": "אז",
  "ratio": "יחס",
  "trueValue": "ערך True",
  "changeValueColor": "שנה צבע ערך ל",
  "changeGaugeColor": "שנה צבע מדיד ל",
  "setIndicatorIcon": "הגדר סמל מחוון כ",
  "icons": "סמלים",
  "style": "סגנון",
  "placement": "מיקום",
  "left": "שמאל",
  "replace": "החלף",
  "right": "ימין",
  "color": "צבע",
  "dataRange": "טווח נתונים",
  "targetValue": "ערך יעד",
  "currentValue": "ערך נוכחי",
  "gaugeColor": "צבע מדיד",
  "min": "מינימום",
  "max": "מקסימום",
  "displayValueIn": "הצג ערך ב",
  "noData": "אין נתונים",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "אזהרה",
  "noSettingWaring1": "לחץ על אלמנט כדי להגדיר את המאפיינים שלו.",
  "noSettingWaring2": "גרור כדי לשנות גודל או לסדר מחדש אלמנט.",
  "donNotShowAgain": "אל תציג שוב",
  "changeTemplateWarning": "פעולה זו תמחק את כל ההגדרות שלך ותפתח תבנית ריקה חדשה.",
  "requiredFieldWarning": "חובה להכניס ערך זה:",
  "dataSourceNotSet": "הגדר מקור נתונים.",
  "addIndicatorTip": "הוסף מחוון",
  "chooseTemplatePopupTitle": "בחר תבנית",
  "stringsInTemplate": {
    "name_number": "מספר",
    "name_gauge": "מדיד",
    "name_vertical_gauge": "מדיד אנכי",
    "name_horizontal_gauge": "מדיד אופקי",
    "name_pie_chart": "תרשים עוגה",
    "name_column_chart": "תרשים עמודות",
    "name_bar_chart": "תרשים עמודות",
    "name_line_chart": "תרשים קו",
    "titleOfTheInfographic": "כותרת האינפוגרפיקה",
    "description": "תיאור: מידע נוסף על אינפוגרפיקה זו."
  }
});