define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "マップ上をクリックしてポイントを追加",
  "addRingsDtWt": "リング、運転時間、徒歩時間の追加",
  "apply": "適用",
  "back": "戻る",
  "colon": ":",
  "creditInformation": "クレジット",
  "driveTime": "運転時間",
  "esriInfographics": "Esri インフォグラフィックス",
  "esriReports": "Esri レポート",
  "headerDescription_km": "キロメートル",
  "headerDescription_miles": "マイル",
  "headerDescription_minutes": "分",
  "infographics": "インフォグラフィックス",
  "invalidValueRing": "値 は 0 ～ 1,000 の範囲内でなければなりません。",
  "invalidValueDTWT": "値 は 0 ～ 300 の範囲内でなければなりません。",
  "km": "キロメートル",
  "miles": "マイル",
  "minutes": "分",
  "myInfographics": "マイ インフォグラフィックス",
  "myReports": "マイ レポート",
  "noPermissions": "お使いのアカウントで Business Analyst ウィジェットを実行できません。  Business Analyst ウィジェットを実行するには、組織の管理者がジオエンリッチメントとネットワーク解析の<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">権限</a>を付与し、<a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">クレジット</a>も割り当てる必要があります。",
  "radii": "半径",
  "radius": "半径",
  "radius_lowercase": "半径",
  "reports": "レポート",
  "ring": "リング",
  "rings": "複数のリング",
  "runInfographic": "インフォグラフィックスの実行",
  "runReport": "レポートの実行",
  "selectPointOrPolygon": "マップ上のポイントまたはポリゴン フィーチャを選択するか、住所または場所を検索するか、マップ上にピンを配置してエリアの詳細情報を表示します。",
  "selectReport": "レポートの選択",
  "selectTemplate": "テンプレートの選択",
  "sharedInfographics": "共有インフォグラフィックス",
  "sharedReports": "共有レポート",
  "thisEntryIsNotValid": "このエントリは有効ではありません。",
  "time": "時間",
  "walkTime": "徒歩時間",
  "widgetDescription": "エリアの主要指標とデータを集計するインフォグラフィックスとレポートにアクセスします。",
  "None": "選択..."
});