define({
  "_widgetLabel": "Dibujar",
  "selectDrawMode": "Seleccionar modo de dibujo",
  "clear": "Borrar",
  "point": "Punto",
  "line": "Línea",
  "polyline": "Polilínea",
  "freehandPolyline": "Polilínea a mano alzada",
  "triangle": "Triángulo",
  "extent": "Contorno",
  "circle": "Círculo",
  "ellipse": "Elipse",
  "polygon": "Polígono",
  "freehandPolygon": "Polígono a mano alzada",
  "text": "Texto",
  "style": "Estilo",
  "alpha": "Transparencia",
  "width": "Ancho",
  "size": "Tamaño",
  "color": "Color",
  "markerColor": "Color de marca",
  "outlineColor": "Color del contorno",
  "lineColor": "Color de línea",
  "fillColor": "Color de relleno",
  "showMeasurements": "Mostrar medidas",
  "showLocationMeasurement": "Mostrar medición de ubicación",
  "showAreaMeasurement": "Mostrar medición de área",
  "showDistanceMeasurement": "Mostrar medición de distancia",
  "showDistanceMeasurementForLine": "Mostrar medición de longitud",
  "showDistanceMeasurementForPolygon": "Mostrar medición de perímetro",
  "locationToggleOn": "Pulse el botón de alternancia para mostrar la medición de ubicación",
  "locationToggleOff": "Pulse el botón de alternancia para ocultar la medición de ubicación",
  "areaToggleOn": "Pulse el botón de alternancia para mostrar la medición de área",
  "areaToggleOff": "Pulse el botón de alternancia para ocultar la medición de área",
  "distanceForLineToggleOn": "Pulse el botón de alternancia para mostrar la medición de longitud",
  "distanceForLineToggleOff": "Pulse el botón de alternancia para ocultar la medición de longitud",
  "distanceForPolygonToggleOn": "Pulse el botón de alternancia para mostrar la medición de perímetro",
  "distanceForPolygonToggleOff": "Pulse el botón de alternancia para ocultar la medición de perímetro",
  "areaUnits": "Unidades de área",
  "distanceUnits": "Unidades de distancia",
  "kilometers": "Kilómetros",
  "miles": "Millas",
  "meters": "Metros",
  "feet": "Pies",
  "yards": "Yardas",
  "nauticalmiles": "Millas náuticas",
  "squareKilometers": "Kilómetros cuadrados",
  "squareMiles": "Millas cuadradas",
  "acres": "Acres",
  "hectares": "Hectáreas",
  "squareMeters": "Metros cuadrados",
  "squareFeet": "Pies cuadrados",
  "squareYards": "Yardas cuadradas",
  "undo": "Deshacer",
  "redo": "Rehacer",
  "results": "Resultados",
  "points": "Puntos",
  "lines": "Líneas",
  "areas": "Áreas",
  "locationLabel": "Ubicación: ${value}",
  "areaLabel": "Área: ${value} ${unit}",
  "distanceLabel": "Distancia: ${value} ${unit}",
  "distanceLabelForLine": "Longitud: ${value} ${unit}",
  "distanceLabelForPolygon": "Perímetro: ${value} ${unit}"
});