define({
  "defaultAreaUnit": "Alapértelmezett terület-mértékegység",
  "defaultLengthUnit": "Alapértelmezett hosszmértékegység",
  "acres": "acre",
  "sqMiles": "négyzetmérföld",
  "sqKilometers": "négyzetkilométer",
  "hectares": "hektár",
  "sqYards": "négyzetyard",
  "sqFeet": "négyzetláb",
  "sqFeetUS": "négyzetláb (US)",
  "sqMeters": "négyzetméter",
  "miles": "mérföld",
  "kilometers": "kilométer",
  "feet": "láb",
  "feetUS": "láb (US)",
  "meters": "méter",
  "yards": "yard",
  "nauticalMiles": "tengeri mérföld",
  "showArea": "Terület",
  "showDistance": "Távolság",
  "showLocation": "Hely",
  "showtools": "Mérési eszközök megjelenítése:",
  "operationalLayer": "Adja hozzá a mérési grafikát a térkép operatív rétegeként.",
  "allHidedTips": "Legalább egy eszközt ki kell választani."
});