define({
  "chartSettingLabel": "Diagraminställningar",
  "addNewLabel": "Lägg till ny",
  "generalSettingLabel": "Allmänna inställningar",
  "layerChooser": {
    "title": "Välj vilka lager som ska användas i diagrammet",
    "selectPolygonLayerLabel": "Välj lager",
    "selectPolygonLayerHintText": "Tips: Om du konfigurerar flera diagram, måste lagren vara av samma geometrityp",
    "selectRelatedTableLayerLabel": "Välj en tabell med en relation till lagret",
    "selectRelatedTableLayerHintText": "Tips: Endast tabeller med numeriska fält visas",
    "errorInSelectingPolygonLayer": "Välj ett lager som har ett tillhörande punktlager.",
    "errorInSelectingRelatedLayer": "Välj en giltig relaterad tabell eller ett giltigt relaterat lager som ska användas i lagret.",
    "polygonLayerNotHavingRelationships": "Det markerade lagret har inte någon relaterad tabell eller något relaterat lager."
  },
  "ChartSetting": {
    "sectionTitle": "Avsnittets rubrik",
    "sectionTitleHintText": "Tips: Visas i avsnittsrubriken",
    "chartTitle": "Diagramtitel",
    "chartTitleHintText": "Tips: Visas centrerad ovanför diagrammet",
    "chartDescription": "Beskrivning",
    "chartDescriptionHintText": "Tips: Visas under diagrammet",
    "chartType": "Diagramtyp",
    "barChart": "Liggande stapeldiagram",
    "pieChart": "Cirkeldiagram",
    "polarChart": "Radardiagram",
    "dataSeriesField": "Fält för dataserie",
    "labelField": "Etikettfält",
    "chartColor": "Diagramfärg",
    "singleColor": "En färg",
    "colorByTheme": "Färg enligt tema",
    "colorByFieldValue": "Färg enligt fältvärde",
    "xAxisTitle": "Titel för X-axel",
    "xAxisHintText": "Tips: Titel för X-axel",
    "yAxisTitle": "Titel för Y-axel",
    "yAxisHintText": "Tips: Titel för Y-axel",
    "fieldColorLabel": "Etikett",
    "fieldColorColor": "Färg",
    "defaultFieldSelectLabel": "Välj",
    "errMsgFieldValuesNotFound": "Det gick inte att hitta några värden för det valda fältet",
    "errMsgSectionTitle": "Ange avsnittstiteln",
    "errMsgFieldByValue": "Ange fältvärdet",
    "settingTabTitle": "Inställning",
    "layoutTabTitle": "Layout",
    "polarChartSelectFieldsHintText": "Tips: Välj fält för att generera radardiagram",
    "visibilityText": "Synlighet",
    "fieldNameText": "Fältnamn",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Välj tre eller fler fält för att generera radardiagram",
    "polarChartPolygonFillLabel": "Fyll polygon",
    "polarChartPolygonFillHintText": "Tips: Markera kryssrutan för att visa polygonfyllning i radardiagram",
    "ThemeSelector": {
      "themeAdobebricks": "Adobe-tegel",
      "themeAlgae": "Alger",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlåSkymning",
      "themeCubanShirts": "Kubaskjortor",
      "themeDesert": "Öken",
      "themeDistinctive": "Distinkt",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Gräshoppa",
      "themeGrasslands": "Grässtäpp",
      "themeGreySkies": "GråSkyar",
      "themeHarmony": "Harmoni",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurpur",
      "themeSageToLime": "SalviaTillLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "Strandkant",
      "themeWetlandText": "Våtmark",
      "themePlotKitblue": "PlotKit.blå",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.grön",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.lila",
      "themePlotKitred": "PlotKit.röd"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Allmänna inställningar",
    "locationSymbolLabel": "Grafisk platssymbol",
    "locationSymbolHintText": "Tips: Används för att visa symbolen för adress och plats som någon klickat på",
    "refreshIntervalLabel": "Uppdateringsintervall",
    "refreshIntervalHintText": "Tips: Används för att uppdatera diagram baserat på detta intervall. Ange ett värde mellan 1 och 1 440 minuter",
    "errMsgRefreshInterval": "Ange ett värde för uppdateringsfrekvensen mellan 0 och 1 440 minuter",
    "symbolPickerPreviewText": "Förhandsgranska:"
  }
});