define({
  "_widgetLabel": "Zeichnen",
  "selectDrawMode": "Darstellungsmodus auswählen",
  "clear": "Löschen",
  "point": "Punkt",
  "line": "Linie",
  "polyline": "Polylinie",
  "freehandPolyline": "Freihand-Polylinie",
  "triangle": "Dreieck",
  "extent": "Envelope",
  "circle": "Kreis",
  "ellipse": "Ellipse",
  "polygon": "Polygon",
  "freehandPolygon": "Freihand-Polygon",
  "text": "Text",
  "style": "Style",
  "alpha": "Transparenz",
  "width": "Breite",
  "size": "Größe",
  "color": "Farbe",
  "markerColor": "Markerfarbe",
  "outlineColor": "Umrissfarbe",
  "lineColor": "Linienfarbe",
  "fillColor": "Füllfarbe",
  "showMeasurements": "Messwerte anzeigen",
  "showLocationMeasurement": "Position anzeigen",
  "showAreaMeasurement": "Flächenmessung anzeigen",
  "showDistanceMeasurement": "Entfernungsmesswert anzeigen",
  "showDistanceMeasurementForLine": "Längenmessung anzeigen",
  "showDistanceMeasurementForPolygon": "Umfangsmessung anzeigen",
  "locationToggleOn": "Zum Anzeigen der Position Umschaltfläche drücken",
  "locationToggleOff": "Zum Ausblenden der Position Umschaltfläche drücken",
  "areaToggleOn": "Zum Anzeigen der Flächenmessung Umschaltfläche drücken",
  "areaToggleOff": "Zum Ausblenden der Flächenmessung Umschaltfläche drücken",
  "distanceForLineToggleOn": "Zum Anzeigen der Längenmessung Umschaltfläche drücken",
  "distanceForLineToggleOff": "Zum Ausblenden der Längenmessung Umschaltfläche drücken",
  "distanceForPolygonToggleOn": "Zum Anzeigen der Umfangsmessung Umschaltfläche drücken",
  "distanceForPolygonToggleOff": "Zum Ausblenden der Umfangsmessung Umschaltfläche drücken",
  "areaUnits": "Flächeneinheiten",
  "distanceUnits": "Abstandseinheiten",
  "kilometers": "Kilometer",
  "miles": "Meilen",
  "meters": "Meter",
  "feet": "Fuß",
  "yards": "Yard",
  "nauticalmiles": "Seemeilen",
  "squareKilometers": "Quadratkilometer",
  "squareMiles": "Quadratmeilen",
  "acres": "Acres",
  "hectares": "Hektar",
  "squareMeters": "Quadratmeter",
  "squareFeet": "Quadratfuß",
  "squareYards": "Quadratyard",
  "undo": "Rückgängig",
  "redo": "Wiederholen",
  "results": "Ergebnisse",
  "points": "Punkte",
  "lines": "Linien",
  "areas": "Flächen",
  "locationLabel": "Position: ${value}",
  "areaLabel": "Fläche: ${value} ${unit}",
  "distanceLabel": "Entfernung/Umfang: ${value} ${unit}",
  "distanceLabelForLine": "Länge: ${value} ${unit}",
  "distanceLabelForPolygon": "Umfang: ${value} ${unit}"
});