define({
  "_widgetLabel": "Transmissió",
  "streamControls": "Controls de transmissió",
  "streamFilter": "Filtre",
  "startStreaming": "Inicia la transmissió",
  "stopStreaming": "Atura la transmissió",
  "streamLayers": "Capes de transmissió",
  "startStopStream": "Habilita l'opció Atura la transmissió o Inicia la transmissió",
  "clearStream": "Habilita l'opció Esborra les observacions anteriors",
  "attributeFilter": "Habilita el filtre d'atributs",
  "spatialFilter": "Habilita un filtre espacial",
  "configFilter": "Configura el filtre d'atributs de transmissió",
  "drawPrevious": "Habilita l'opció Dibuixa les observacions anteriors",
  "addNew": "Afegeix un filtre",
  "setFilterName": "Defineix el nom del filtre",
  "filterNameExists": "El nom del filtre ja existeix a la taula.",
  "invalidFilterName": "El nom hauria que ser una paraula que contingui a-z, A-Z, 0-9 o _.",
  "noFilterTip": "No hi ha cap filtre configurat",
  "addFilterFailed": "No s'ha pogut afegir el filtre",
  "filterName": "Nom del filtre",
  "limitMapExtent": "Limita les observacions a l'àrea del mapa actual",
  "limitDrawExtent": "Limita les observacions a l'àrea definida per l'usuari",
  "newFilter": "Filtre nou",
  "filterReadOnly": "El filtre heretat del mapa web és només de lectura."
});