define({
  "gridTabLabel": "Siatka",
  "labelTabLabel": "Etykiety",
  "referenceSystemTabLabel": "System referencyjny",
  "gridTabDescription": "Określa wygląd i zachowanie komórek siatki.",
  "cellOutlineColor": "Kolor obramowania komórki",
  "cellFillColor": "Kolor wypełnienia komórki",
  "transparency": "Przezroczystość",
  "cellShapeDropDown": "Kształt komórki",
  "default": "Prostokąt",
  "hexagon": "Sześciokąt",
  "cellUnitsDropDown": "Jednostki komórki",
  "miles": "Mile",
  "kilometers": "Kilometry",
  "feet": "Stopy",
  "meters": "Metry",
  "yards": "Jardy",
  "nautical-miles": "Mile morskie",
  "gridOriginDropDown": "Punkt zaczepienia siatki",
  "lowerLeft": "Dolny lewy",
  "lowerRight": "Dolny prawy",
  "upperLeft": "Górny lewy",
  "upperRight": "Górny prawy",
  "center": "Na środku",
  "selectOpLayerLabel": "Warstwa operacyjna dla wyników",
  "helpIconTooltip": "Lista warstw operacyjnych jest zapełniana warstwami z bieżącej mapy internetowej o typie geometrii poligonowej.",
  "labelTabDescription": "Określa wygląd i zachowanie etykiet siatki.",
  "labelSettings": "Styl etykiety",
  "font": "Czcionka",
  "textSize": "Wielkość tekstu",
  "textColor": "Kolor tekstu",
  "halo": "Otoczka",
  "show": "Pokaż",
  "labelTypeDropDown": "Typ etykiety",
  "alphaNumeric": "Alfanumeryczny",
  "alphaAlpha": "Alfa-alfa",
  "numeric": "Numeryczny",
  "labelDirectionDropDown": "Kierunek etykiety",
  "horizontal": "Poziomo",
  "vertical": "Pionowo",
  "labelOriginDropDown": "Punkt zaczepienia etykiety",
  "referenceSystemlTabDescription": "Określa domyślny system odniesienia.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Ustawienia blokowania — uniemożliwia użytkownikowi zmianę dowolnego ustawienia konfiguracyjnego w widżecie"
});