define({
  "_widgetLabel": "Конвертація координат",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Десяткові градуси - Широта/довгота",
  "DDLongLatNotation": "Десяткові градуси - Довгота/широта",
  "DDMLatLongNotation": "Градуси, десяткові хвилини - Широта/довгота",
  "DDMLongLatNotation": "Градуси, десяткові хвилини - Довгота/широта",
  "DMSLatLongNotation": "Градуси, хвилини, секунди - Широта/довгота",
  "DMSLongLatNotation": "Градуси, хвилини секунди - Довгота/широта",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - літера каналу",
  "UTMHemNotation": "UTM - півкуля (N/S)",
  "formatInput": "Введення формату",
  "copyAll": "Копіювати всі",
  "copySuccessful": "Копіювання успішне",
  "copyFailed": "Неможливо копіювати. Як варіант, натисніть ctrl+c.",
  "parseCoordinatesError": "Неможливо аналізувати координати. Перевірте своє введення.",
  "comfirmInputNotation": "Підтвердіть введення умовного позначення",
  "latLongWarningMessage": "Було виявлено, що введення координат має як префікс, так і суфікс для значення широти або довготи; виведена координата основана на префіксі.",
  "inputLabel": "Введення",
  "outputLabel": "Виведення",
  "cancelButtonLabel": "Скасувати",
  "applyButtonLabel": "Застосувати",
  "posNegPrefixLabel": "Додати префікс «+/-» до позитивних та негативних чисел",
  "editCoordinateDialogTitle": "Задати рядок формату координат",
  "rememberDecisionLabel": "Запам’ятати мій вибір та не питати знову.<br/>",
  "coordinateInputLabel": "Введіть координати або клацніть на карті",
  "zoomLabel": "Масштабування",
  "multipleNotationLabel": "знайдено умовні позначення, які збігаються з вашим введенням. Підтвердіть, які ви бажаєте використовувати:",
  "copyToClipboard": "Копіювати до буферу обміну",
  "formatOutput": "Виведення формату",
  "addNewNotation": "Додати нове умовне позначення",
  "notationAddedMessage": "Нове умовне позначення додано",
  "addLabel": "Додати",
  "removeCoordinate": "Видалити координату",
  "expandOutput": "Розгорнути виведення",
  "latitudeLabel": "Широта",
  "longitudeLabel": "Довгота",
  "quadrantLabel": "Квадрант",
  "keyLabel": "Ключ",
  "fifteenDegreeLabel": "Квадрант 15°",
  "oneDegreeLabel": "Квадрант 1°",
  "eastingLabel": "Відлік по осі абсцис",
  "northingLabel": "Величина ординати",
  "zoneLabel": "Зона",
  "bandLabel": "Канал",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Квадрат сітки",
  "hemisphereLabel": "Півкуля",
  "addPointLabel": "Додати точку"
});