define({
  "_widgetLabel": "थ्रेट विश्लेषण",
  "threatAnalysisMainPageTitle": "JCAT काउंटर आतंकवाद गाइड के आधार पर",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "स्थान दर्ज करें",
  "interactive": "संवादपरक",
  "fromCoord": "नियत निर्देशांक",
  "existingFeature": "मौजूदा सुविधाओं से",
  "threatAnalysisCoordInputLabel": "खतरे का स्थान",
  "enterCoords": "गुणांक दर्ज करें",
  "threatAddPointToolTip": "खतरे का स्थान जोड़ें",
  "threatDrawPointToolTip": "खतरे का स्थान जोड़ने के लिए क्लिक करें",
  "threatType": "खतरे का प्रकार",
  "threatPlaceholder": "किसी खतरे की खोज करने के लिए टाइप करना प्रारंभ करें",
  "mandatoryLabel": "अनिवार्य निकासी दूरी",
  "safeLabel": "स्थान ज़ोन में आश्रय",
  "zoneTypeLabel": "ज़ोन या क्षेत्र प्रकार",
  "feetLabel": "फुट",
  "metersLabel": "मीटर",
  "unitsLabel": "इकाइयां",
  "settingsTitle": "सेटिंग्स",
  "mandatoryButtonLabel": "अनिवार्य निकासी दूरी सेटिंग कॉन्फ़िगर करें",
  "safeButtonLabel": "आश्रय स्थान सेटिंग कॉन्फ़िगर करें",
  "style": "शैली",
  "lineStyles": {
    "esriSLSDash": "डैश",
    "esriSLSDashDot": "डैश डॉट",
    "esriSLSDashDotDot": "डैश डॉट डॉट",
    "esriSLSDot": "बिंदु",
    "esriSLSLongDash": "लोंग डैश (लंबा डैश)",
    "esriSLSLongDashDot": "लोंग डैश डॉट (लंबा डैश डॉट)",
    "esriSLSNull": "शून्य",
    "esriSLSShortDash": "शॉर्ट डैश",
    "esriSLSShortDashDot": "शॉर्ट डैश डॉट (छोटा डैश डॉट)",
    "esriSLSShortDashDotDot": "शॉर्ट डैश डॉट डॉट",
    "esriSLSShortDot": "शॉर्ट डॉट",
    "esriSLSSolid": "ठोस"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "पीछे की ओर",
    "esriSFSCross": "क्रॉस",
    "esriSFSDiagonalCross": "तिरछा/विकर्ण",
    "esriSFSForwardDiagonal": "आगे करें",
    "esriSFSHorizontal": "क्षैतिज",
    "esriSFSNull": "शून्य",
    "esriSFSSolid": "ठोस",
    "esriSFSVertical": "लंबवत"
  },
  "resultsTitle": "परिणाम",
  "publishTABtn": "प्रकाशित करें",
  "layerName": "प्रकाशित लेयर का नाम",
  "invalidLayerName": "लेयर के नाम में केवल अक्षरांकीय वर्ण और अंडरस्कोर होना चाहिए",
  "missingLayerName": "आपको लेयर के लिए एक नाम दर्ज करना होगा",
  "missingLayerNameMessage": "प्रकाशित करने से पहले आपको वैध लेयर का नाम दर्ज करना होगा",
  "publishingFailedLayerExists": "प्रकाशन विफल: आपके पास पहले से ही {0} नाम की एक फ़ीचर सेवा है। कृपया कोई दूसरा नाम चुनें।",
  "checkService": "सेवा की जाँच करें: {0}",
  "createService": "सेवा बनाएँ: {0}",
  "unableToCreate": "बनाने में अक्षम: {0}",
  "addToDefinition": "परिभाषा में जोड़ें: {0}",
  "successfullyPublished": "सफलतापूर्वक प्रकाशित वेब लेयर{0}वेब लेयर प्रबंधित करें",
  "userRole": "सर्विस तैयार करने में अक्षम हैं, क्योंकि उपयोगकर्ता को अनुमति नहीं है",
  "transparencyLabel": "पारदर्शिता",
  "outline": "आउटलाइन",
  "fill": "भरें (स्टाइल के ठोस पर सेट होने पर ही रंग लागू होत हैं)",
  "createBtn": "क्षेत्र निर्मित करें",
  "clearBtn": "हटाएँ",
  "invalidNumberMessage": "दर्ज की गई संख्या मान्य नहीं है",
  "invalidRangeMessage": "मान 0 से अधिक होना आवश्यक है",
  "parseCoordinatesError": "निर्देशांक पार्स करने में असमर्थ। कृपया अपना इनपुट जाँचें।"
});