define({
  "queries": "Sorgular",
  "addNew": "Yeni Ekle",
  "newQuery": "Yeni Sorgu",
  "queryLayer": "Sorgu Katmanı",
  "setSource": "Ayarla",
  "setDataSource": "Veri Kaynağını Belirt",
  "name": "Adı",
  "querySource": "Veri kaynağı",
  "queryName": "Görev Adı",
  "queryDefinition": "Filtre Tanımı",
  "resultsSetting": "Sonuçlar Ayarı",
  "symbolSetting": "Sembol Ayarı",
  "resultSettingTip": "Hangi çıktı sonuçlarının nasıl görüntüleneceğini tanımlayın.",
  "resultItemTitle": "Her sonuç öğesinin başlığı",
  "resultItemContent": "Bu alan öznitelikleri gösterilecek",
  "fieldsSetTip": "Görüntülemek istediğiniz alanları denetleyin. Takma adı güncellemek, sıralamak ve biçimlendirmek için bir alan seçin.",
  "addField": "Alan Ekle",
  "visibility": "Görünürlük",
  "alias": "Takma Ad",
  "specialType": "Özel Tür",
  "actions": "İşlemler",
  "none": "Hiçbiri",
  "link": "Bağlantı",
  "image": "Görüntü",
  "noField": "Alan yok",
  "operationalLayerTip": "Sonucu işlem katmanı olarak ekle",
  "setLayerSymbolTip": "Sorgu sonuçları için simgeyi ayarla: ",
  "setSelectedSymbolTip": "Seçilen detayın simgesini ayarlayın.",
  "notUseFilter": "Filtre kullanma",
  "setSourceTip": "Sorgu kaynağını belirtin.",
  "setFilterTip": "Filtreyi düzgün şekilde ayarlayın.",
  "ok": "Tamam",
  "cancel": "İptal",
  "noFilterTip": "Tanımlı filtre ifadesi olmadan, bu sorgu görevi belirtilen veri kaynağındaki tüm detayları listeleyecektir.",
  "relationships": "İlişkiler",
  "addRelationshipLayer": "Yeni İlişki Ekle",
  "relatedTo": "İlgili",
  "selectOption": "Seçim yapın..",
  "resultItemSorting": "Sonuç Öğesi Sıralama",
  "field": "Alan",
  "sortingOrder": "Sırala",
  "configureFieldsTip": "Sorgu sonucu için sıralama ölçütü olarak kullanılacak alanları yapılandırın.",
  "setSortingFields": "Sıralama Alanlarını Ayarla",
  "ascending": "Artan",
  "descending": "Azalan",
  "sortBy": "Şuna göre sırala:",
  "thenBy": "Ardından şuna göre",
  "addTask": "Görev Ekle",
  "noTasksTip": "Yapılandırılmış sorgu yok. Yeni bir sorgu eklemek için \"${newQuery}\" öğesine tıklayın.",
  "infoText": "Bilgi",
  "filters": "Filtreler",
  "results": "Sonuçlar",
  "optionsText": "Seçenekler",
  "summaryText": "Özet",
  "attributeFilter": "Öznitelik filtresi",
  "attributeFilterTip": "Sorgu katmanını filtrelemek için araç içinde kullanılacak öznitelik ifadelerini tanımlayın.",
  "defineWhereClause": "Sorgu için bir where ifadesi tanımlayın.",
  "noExpressionDefinedTip": "Tanımlı deyim yok. Tüm kayıtlar döndürülecek.",
  "setExpressions": "İfade Ayarla",
  "spatialFilter": "Mekansal filtreler",
  "spatialFilterTip": "Son kullanıcılara hangi mekansal filtrelerin sunulacağını belirleyin.",
  "defaultOption": "Varsayılan",
  "useCurrentExtentTip": "Yalnızca geçerli harita yayılımındaki detayları döndür",
  "useDrawGraphicTip": "Yalnızca haritada çizilen şekil ile kesişen detayları döndür",
  "useFeaturesTip": "Yalnızca başka bir katmandaki detaylarla mekansal ilişkisi olan detayları döndür",
  "noSpatialLimitTip": "Haritanın tam yayılımı içindeki detayları döndür",
  "drawingTools": "Çizim araçları seçin",
  "bufferSettings": "Tampon seçeneğini etkinleştir",
  "defaultDistance": "Varsayılan mesafe",
  "bufferDistance": "Tampon mesafesi",
  "defaultUnit": "Varsayılan birim",
  "miles": "Mil",
  "kilometers": "Kilometre",
  "feet": "Fit",
  "meters": "Metre",
  "yards": "Yarda",
  "nauticalMiles": "Deniz Mili",
  "availableSpatialRelationships": "Mekansal ilişki kurallarını seçin",
  "setSpatialRelationships": "Mekansal İlişki Ayarla",
  "availability": "Yararlanırlık",
  "relationship": "İlişki",
  "label": "Etiket",
  "intersect": "kesişen",
  "contain": "içeren",
  "areContainedIn": "içinde bulunuyor",
  "cross": "çapraz",
  "envelopeIntersect": "zarf kesişmesi",
  "overlap": "örtüşme",
  "areOverlapped": "örtüşüyor",
  "touch": "dokunmatik",
  "within": "birliktelik",
  "areWithin": "birlikte",
  "indexIntersect": "dizin kesişmesi",
  "itemTitle": "Öğe Başlığı",
  "displayFields": "Görüntüleme Alanları",
  "sortingFields": "Sonuç öğelerini sırala",
  "setDisplayFields": "Görüntüleme Alanlarını Ayarla",
  "symbol": "Sembol",
  "setSymbol": "Özel sembolü ayarla",
  "serviceSymbolTip": "Katman tarafından tanımlanan simgeleri kullan",
  "exportTip": "Sonuçları aktarmaya izin ver",
  "keepResultsTip": "Araç kapatıldıktan sonra sonuçları haritada sakla",
  "queryRelatedRecords": "Sorgu ile ilgili kayıtlar",
  "createLayerForTaskTip": "Sorgu görevinin nasıl katman oluşturduğunu belirtin",
  "oneLayerForTaskTip": "Sorgu her yürütüldüğünde katmanın üzerine yaz",
  "multipleLayerForTaskTip": "Sorgu her yürütüldüğünde yeni bir katman oluştur",
  "makeDefault": "Varsayılan yap",
  "icon": "Simge",
  "newTask": "Yeni Görev",
  "addTaskTip": "Araca bir veya birkaç sorgu ekleyin ve her biri için parametreleri yapılandırın.",
  "webMapPopupTip": "Web haritasında katmanın açılır yapılandırma penceresini kullan",
  "customPopupTip": "Özel içeriği yapılandır",
  "showResultsSetActions": "Sonuç kümesi için eylemleri göster",
  "zoomTo": "Yakınlaştır",
  "openAttributeTable": "Öznitelik Tablosunda Aç",
  "content": "İçerik",
  "displaySQLTip": "Son kullanıcılar için SQL deyimini görüntüle",
  "useLayerDefaultSymbol": "Katmanın varsayılan sembolünü kullan",
  "setCustomIcon": "Özel simgeyi ayarla",
  "layerDefaultSymbolTip": "Katmanın varsayılan sembolünü kullan",
  "uploadImage": "Görüntü yükle",
  "attributeCriteira": "Öznitelik ölçütleri",
  "specifyFilterAtRuntimeTip": "Kullanıcılar bu deyim için parametre belirtmek zorundadır",
  "value": "DEĞER",
  "hideLayersTip": "Araç kapalıyken sorgu sonucu katmanları kapatılsın."
});