define({
  "transparencyLabel": "Läpinäkyvyys",
  "outline": "Ääriviiva",
  "fill": "Täyttö (väriä käytetään vain, kun tyyliksi on määritetty yhtenäinen)",
  "style": "Tyyli",
  "mandatoryLabel": "Pakollinen evakuointietäisyys",
  "mandatoryButtonLabel": "Määritä pakollisen evakuointietäisyyden asetukset",
  "safeLabel": "Turvallinen evakuointietäisyys",
  "safeButtonLabel": "Määritä turvallisen evakuointietäisyyden asetukset",
  "selectOpLayerLabel": "Valitse toiminnallinen karttataso tuloksia varten",
  "selectDefaultMeasurementLabel": "Valitse oletusmittayksikkö",
  "helpIconTooltip": "Toiminnallisten karttatasojen luettelo täytetään nykyisen web-karttan karttatasoilla, jotka ovat tyypiltään aluekohdegeometrioita.",
  "lineStyles": {
    "esriSLSDash": "Viiva",
    "esriSLSDashDot": "Viiva-piste",
    "esriSLSDashDotDot": "Viiva-piste-piste",
    "esriSLSDot": "Piste",
    "esriSLSLongDash": "Pitkä viiva",
    "esriSLSLongDashDot": "Pitkä viiva-piste",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Lyhyt viiva",
    "esriSLSShortDashDot": "Lyhyt viiva-piste",
    "esriSLSShortDashDotDot": "Lyhyt viiva-piste-piste",
    "esriSLSShortDot": "Lyhyt piste",
    "esriSLSSolid": "Yhtenäinen"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Taaksepäin",
    "esriSFSCross": "Risti",
    "esriSFSDiagonalCross": "Lävistäjän suunnassa",
    "esriSFSForwardDiagonal": "Eteenpäin",
    "esriSFSHorizontal": "Vaaka",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Yhtenäinen",
    "esriSFSVertical": "Pysty"
  },
  "threatTypeLabel": "Uhkan laji",
  "symbologyLabel": "Symbolit",
  "generalLabel": "Yleinen",
  "addThreatTypesLabel": "Lisää uhkan laji",
  "threatTypeColLabel": "Uhkan laji",
  "actions": "Toiminnot",
  "newThreatTypePopupLabel": "Uusi uhkan laji",
  "chooseDefaultThreatTypeIconLabel": "Valitse oletusarvoista",
  "mandatoryDistance": "Pakollinen evakuointietäisyys",
  "safeDistance": "Turvallinen evakuointietäisyys",
  "units": "Yksiköt",
  "chooseDefaultThreatLabel": "Valitse oletusarvoinen uhkan laji",
  "defaultThreatTypePopUpLabel": "Uhkan lajin oletusarvot",
  "editThreatLabel": "Muokkaa uhkaa",
  "defaultThreatTypeIconTooltip": "Uhkan lajin oletusarvoluettelo",
  "uniqueThreatTypeMsg": "Anna yksilöllinen uhkan laji. Samanniminen uhkan laji on jo olemassa.",
  "requiredThreatTypeMsg": "Tämä on pakollinen kenttä",
  "unitMeasureLabel": "Etäisyydet ovat yksikössä {0}",
  "pipeBombLabel": "Putkipommi",
  "suicideBombLabel": "Itsemurhapommi",
  "briefcaseLabel": "Salkku",
  "carLabel": "Auto",
  "suvVanLabel": "Kaupunkimaasturi/pakettiauto",
  "smallDeliveryTruckLabel": "Pieni jakeluauto",
  "containerWaterTruckLabel": "Säiliö-/vesisäiliöauto",
  "semiTrailerLabel": "Puoliperävaunu"
});