define({
  "transparencyLabel": "Gennemsigtighed",
  "outline": "Kontur",
  "fill": "Fyld (farve anvendes kun, når typografien er indstillet til massiv)",
  "style": "Type",
  "mandatoryLabel": "Obligatorisk evakueringsafstand",
  "mandatoryButtonLabel": "Konfigurér indstillinger for Obligatorisk evakueringsafstand",
  "safeLabel": "Sikker evakueringsafstand",
  "safeButtonLabel": "Konfigurér indstillinger for Sikker evakueringsafstand",
  "selectOpLayerLabel": "Vælg et operationelt lag for at opnå resultater",
  "selectDefaultMeasurementLabel": "Vælg en standardmåleenhed",
  "helpIconTooltip": "Listen med operationelle lag består af lag fra det aktuelle webkort, der er af geometritypen polygon.",
  "lineStyles": {
    "esriSLSDash": "Streg",
    "esriSLSDashDot": "Streg-prik",
    "esriSLSDashDotDot": "Streg-prik-prik",
    "esriSLSDot": "Prik",
    "esriSLSLongDash": "Lang streg",
    "esriSLSLongDashDot": "Lang streg-prik",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Kort streg",
    "esriSLSShortDashDot": "Kort streg-prik",
    "esriSLSShortDashDotDot": "Kort streg-prik-prik",
    "esriSLSShortDot": "Kort prik",
    "esriSLSSolid": "Udfyldt"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Baglæns",
    "esriSFSCross": "Kryds",
    "esriSFSDiagonalCross": "Diagonalt",
    "esriSFSForwardDiagonal": "Frem",
    "esriSFSHorizontal": "Vandret",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Udfyldt",
    "esriSFSVertical": "Lodret"
  },
  "threatTypeLabel": "Trusselstype",
  "symbologyLabel": "Symbologi",
  "generalLabel": "Generelt",
  "addThreatTypesLabel": "Tilføj trusselstype",
  "threatTypeColLabel": "Trusselstype",
  "actions": "Handlinger",
  "newThreatTypePopupLabel": "Ny trusselstype",
  "chooseDefaultThreatTypeIconLabel": "Vælg fra standard",
  "mandatoryDistance": "Obligatorisk evakueringsafstand",
  "safeDistance": "Sikker evakueringsafstand",
  "units": "Enheder",
  "chooseDefaultThreatLabel": "Vælg en standard-trusselstype",
  "defaultThreatTypePopUpLabel": "Standard-trusselstyper",
  "editThreatLabel": "Rediger trussel",
  "defaultThreatTypeIconTooltip": "Liste over standard-trusselstyper",
  "uniqueThreatTypeMsg": "Indtast unik trusselstype, en trusselstype med dette navn findes allerede.",
  "requiredThreatTypeMsg": "Dette felt er obligatorisk.",
  "unitMeasureLabel": "Afstand er i {0}",
  "pipeBombLabel": "Rørbombe",
  "suicideBombLabel": "Selvmordsbombe",
  "briefcaseLabel": "Dokumentmappe",
  "carLabel": "Bil",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Lille varevogn",
  "containerWaterTruckLabel": "Container-/vandlastbil",
  "semiTrailerLabel": "Sættevogn"
});