define({
  "_widgetLabel": "距離と方向",
  "tabLineTitle": "線分",
  "tabCircleTitle": "円",
  "tabEllipseTitle": "楕円",
  "tabRingsTitle": "リング",
  "multipleNotationsMessage": " 入力と一致する表記。使用する内容を確認してください。",
  "invalidCoordinateMessage": "無効な座標",
  "confirmInputNotationMessage": "入力表記の確認",
  "prefixSuffixMessage": "入力座標は、緯度と経度の値に接頭辞と接尾辞が付いていることが検出されました。返される座標は、接頭辞に基づいています。",
  "rememberDecisionMessage": "選択内容を記憶して、今後このメッセージを表示しません。<br/>",
  "majorAxisTooltipMessage": "長軸の長さをクリックします。",
  "minorAxisTooltipMessage": "マウスを開始位置に戻して、短軸を設定し、楕円の描画を完了します。",
  "clickToFinishLineMessage": "クリックしてラインの描画を完了します。",
  "doubleClickEllipseMesage": "ダブルクリックして、範囲リングの描画を完了します。",
  "invalidCoordinateTypeMessage": "入力座標のタイプを決定できません。入力を確認してください。",
  "noCenterPointSetMessage": "中心点が設定されていません。入力を確認してください。",
  "ellipseMajorAxis": "主軸",
  "ellipseMinorAxis": "補助軸",
  "degreesRangeMessage": "値は 0 ～ 360 の間でなければなりません",
  "millsRangeMessage": "値は 0 ～ 6400 の間でなければなりません",
  "lengthLabel": "ライン",
  "angleLabel": "角度",
  "startPointLabel": "出発地",
  "endPointLabel": "端点",
  "centerPointLabel": "中心点",
  "distanceTableErrorMessage": "距離テーブルが空です。距離が入力されていることを確認してください。",
  "setCoordFormatStringMessage": "座標形式の文字列の設定",
  "prefixMessage": "正と負の数値に '+/-' の接頭辞を追加",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "度 (10進) - 緯度/経度",
  "DDLongLatNotation": "度 (10進) - 経度/緯度",
  "DDMLatLongNotation": "度分 (10進) - 緯度/経度",
  "DDMLongLatNotation": "度分 (10進) - 経度/緯度",
  "DMSLatLongNotation": "度分秒 - 緯度/経度",
  "DMSLongLatNotation": "度分秒 - 経度/緯度",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - バンド文字",
  "UTMHemNotation": "UTM - 半球 (N/S)",
  "circleTitle": "円を作成",
  "radiusLabel": "半径",
  "diameterLabel": "直径",
  "startPointPlaceHolderLabel": "座標値入力",
  "formatInputLabel": "入力の書式設定",
  "drawCircleLabel": "円の描画",
  "drawLineLabel": "ラインの描画",
  "createCircleInteractivelyLabel": "対話形式で円を作成",
  "rangeErrorMessage": "半径または直径が無効です。",
  "numericInvalidMessage": "数値を入力してください。",
  "timeLabel": "時間",
  "invalidTimeMessage": "時間の値が無効です。",
  "hoursLabel": "時間",
  "minutesLabel": "分",
  "secondsLabel": "秒",
  "rateLabel": "レート",
  "invalidDistanceMessage": "無効な距離値",
  "feetSecondsLabel": "フィート/秒",
  "feetHourLabel": "フィート/時",
  "kmSecondLabel": "キロメートル/秒",
  "kmHourLabel": "キロメートル/時",
  "metersSecondLabel": "メートル/秒",
  "metersHourLabel": "メートル/時",
  "milesSecondLabel": "マイル/秒",
  "milesHourLabel": "マイル/時",
  "nauticalMilesSecondLabel": "海里/秒",
  "nauticalMilesHourLabel": "海里/時",
  "clearGraphicsLabel": "グラフィックの削除",
  "ellipseTypeLabel": "楕円のタイプ",
  "ellipseSemiLabel": "半楕円",
  "ellipseFullLabel": "全楕円",
  "drawEllipseLabel": "楕円の描画",
  "createEllipseInteractively": "対話形式で楕円を作成",
  "axisLabel": "軸",
  "unitLabel": "単位",
  "majorRadiusLabel": "長径",
  "majorDiameterLabel": "外径 (直径)",
  "axisErrorMessage": "値は 0 より大きくなければなりません。",
  "minorRadiusLabel": "短径",
  "minorDiameterLabel": "内径 (直径)",
  "orientationLabel": "方向",
  "orientationErrorMessage": "値は 0 ～ 360 の間でなければなりません",
  "warningMessage": "警告: 楕円ツールを使用して生成されたグラフィックは測地タイプではありません。",
  "fromLabel": "開始",
  "distanceBearingLabel": "距離と方向",
  "pointsLabel": "ポイント",
  "createLineInteractively": "対話形式でラインを作成",
  "lineLengthErrorMessage": "無効なライン長",
  "degreesLabel": "度",
  "milsLabel": "ミル",
  "lineTypeLabel": "種類",
  "interactiveLabel": "対話的",
  "fixedLabel": "固定",
  "originLabel": "原点",
  "cumulativeLabel": "累積",
  "numberOfRingsLabel": "リング数",
  "ringsErrorMessage": "無効なリング数",
  "distanceBetweenRingsLabel": "リング間の距離",
  "ringsDecimalErrorMessage": "小数点以下第 2 位に数値を入力してください。",
  "distanceUnitsLabel": "距離単位",
  "distancesLabel": "距離",
  "numberOfRadialsLabel": "放射の数",
  "upLabel": "上へ",
  "downLabel": "下へ",
  "deleteLabel": "削除",
  "radialsErrorMessage": "放射の数が無効です。最大許容値は 360 です。",
  "radialsInvalidMessage": "半径の値が無効です",
  "addPointLabel": "ポイントの追加",
  "valueLabel": "値",
  "valueText": "値を入力",
  "actionLabel": "アクション",
  "distanceCalculatorLabel": "距離計算",
  "abbrevMetersLabel": "m",
  "abbrevFeetLabel": "フィート",
  "abbrevKmLabel": "キロメートル",
  "abbrevMilesLabel": "マイル",
  "abbrevYardsLabel": "yd",
  "abbrevNauticalMilesLabel": "nm",
  "abbrevDegreesLabel": "°",
  "abbrevMilsLabel": "ミル",
  "abbrevHoursLabel": "h",
  "abbrevMinutesLabel": "m",
  "abbrevSecondsLabel": "s",
  "abbrevFeetSecondsLabel": "ft/s",
  "abbrevFeetHourLabel": "ft/h",
  "abbrevKmSecondLabel": "km/s",
  "abbrevKmHourLabel": "km/h",
  "abbrevMetersSecondLabel": "m/s",
  "abbrevMetersHourLabel": "m/h",
  "abbrevMilesSecondLabel": "mi/s",
  "abbrevMilesHourLabel": "mi/h",
  "abbrevNauticalMilesSecondLabel": "nm/s",
  "abbrevNauticalMilesHourLabel": "nm/h",
  "publishDDBtn": "公開",
  "publishTitle": "グラフィックスの公開",
  "ddLayerName": "公開されたレイヤー名",
  "missingDDLayerName": "レイヤーの名前を入力する必要があります",
  "publishToNewLayer": "新しいフィーチャ レイヤーに結果を公開",
  "checkService": "次のサービスを確認: {0}",
  "createService": "次のサービスを作成: {0}",
  "unableToCreate": "次のものを作成できません: {0}",
  "addToDefinition": "定義に追加: {0}",
  "successfullyPublished": "Web レイヤー {0} を正常に公開できました。Web レイヤーの管理",
  "userRole": "ユーザーにアクセス権限がないため、サービスを作成できません。",
  "missingLayerNameMessage": "公開の前に、有効なレイヤー名を入力する必要があります。",
  "invalidLayerName": "レイヤー名は、英数字とアンダースコア (_) だけを含むようにする必要があります。",
  "distanceLabel": "距離",
  "radiusDistance": "半径距離",
  "radials": "半径",
  "rings": "複数のリング",
  "orientationUnit": "方向単位",
  "radiusUnit": "半径単位",
  "angleUnitLabel": "角度単位"
});