define(
   ({
    addLayer: "Thêm Lớp",
    layerName: "Lớp",
    layerRefresh: "Làm mới",
    layerLabel: "Nhãn",
    actions: "Các hành động",
    popupOk: "OK",
    popupCancel: "Hủy",
    mainPanelTextPlaceholder: "ví dụ: ĐIỀU KIỆN ĐƯỜNG QUỐC LỘ",
    invalidInterval: "Chỉ hỗ trợ các ký tự số.",
    uploadImage: "Tải ảnh lên",
    iconColumnText: "Biểu tượng",
    refreshInterval: "1 \'Được đánh giá bằng thời gian tính bằng Phút\'",
    refreshIntervalTitle: "Được đánh giá bằng thời gian tính bằng Phút",
    mainPanelText: "Văn bản Bảng điều khiển Chính",
    mainPanelIcon: "Hình ảnh Bảng điều khiển Chính",
    refreshIntervalInstruction: "Khoảng làm mới",
    optionsText: "Tùy chọn",
    symbolOptionsText: "Tùy chọn Ký tự",
    iconOptionsText: "Tùy chọn Biểu tượng",
    sympolPopupTitle: "Ký hiệu Thiết lập",
    rdoLayer: "Ký hiệu Lớp",
    rdoCustom: "Ký hiệu Tùy chỉnh",
    chkCluster: "Bật Gom cụm",
    defineClusterSymbol: "Ký hiệu Cụm",
    defineThemeClusterSymbol: "Ký hiệu Cụm từ Chủ đề",
    rdoEsri: "Ký hiệu Esri",
    rdoLayerIcon: "Sử dụng Ký hiệu làm Biểu tượng",
    rdoCustomIcon: "Tải lên Biểu tượng Tùy chỉnh",
    editCustomSymbol: "Sửa Ký hiệu Tùy chỉnh",
    editCustomIcon: "Sửa Biểu tượng Tùy chỉnh",
    missingRefreshValue: "Vui lòng cung cấp giá trị khoảng thời gian làm mới.",
    panelIconOption: "Hiển thị Tiêu đề Bảng điều khiển",
    enableRefresh: "Bật Làm mới Lớp",
    disableRefresh: "Làm mới Lớp Chỉ Được hỗ trợ đối với Bộ sưu tập Đối tượng",
    layer_type_not_supported: "Loại lớp không được hỗ trợ: "
  })
);
