define({
  "serviceUrl": "Nastavi url storitve:",
  "minIntSpacingLabel": "Najmanjši razmik intervala",
  "lineOpacityLabel": "Neprosojnost linije",
  "labelOpacityLabel": "Neprosojnost napisa",
  "centerLabelOpacityLabel": "Postavi neprosojnost napisa na sredino",
  "gridZonePlacementLabel": "Postavitev napisa mrežne cone",
  "verticalLineLabels": "Napisi vertikalne linije",
  "styleHeaderLabel": "Slog",
  "indexHeaderLabel": "Kazalo",
  "colorHeaderLabel": "Barva",
  "fontSizeHeaderLabel": "Velikost pisave",
  "lineWidthHeaderLabel": "Debelina linije",
  "horizontalLabel": "Horizontalno",
  "verticalLabel": "Vertikalno",
  "upperLeftLabel": "Zgoraj levo",
  "upperRightLabel": "Zgoraj desno",
  "lowerLeftLabel": "Spodaj levo",
  "lowerRightLabel": "Spodaj desno",
  "centerLabel": "Na sredino",
  "errorMessage": "Konfiguracijska stran vsebuje napake. Popravite, preden shranite.",
  "checkBoxLabel": "Prikaži mrežo, ko je pripomoček zaprt"
});