define({
  "_widgetLabel": "المسافة والاتجاه",
  "tabLineTitle": "خط",
  "tabCircleTitle": "دائرة",
  "tabEllipseTitle": "قطع ناقص",
  "tabRingsTitle": "حلقات",
  "multipleNotationsMessage": " التعليقات التي تطابق المدخلات. يرجى تأكيد ما تريد استخدامه:",
  "invalidCoordinateMessage": "الإحداثيات غير صحيحة",
  "confirmInputNotationMessage": "تأكيد علامة المدخلات",
  "prefixSuffixMessage": "تم الكشف عن تنسيق الإدخال حيث تحتوي على بادئة ولاحقة لقيمة خط العرض أو الطول، ويستند التنسيق المرتجع إلى البادئة.",
  "rememberDecisionMessage": "تذكر قراري ولا تسألني مرة أخرى.<br/>",
  "majorAxisTooltipMessage": "انقر على طول المحور الرئيسي",
  "minorAxisTooltipMessage": "قم بتحريك الماوس إلى الخلف حتى موضع البدء من أجل تعيين محور فرعي وإنهاء رسم القطع الناقص.",
  "clickToFinishLineMessage": "انقر لإنهاء خط الرسم",
  "doubleClickEllipseMesage": "انقر مرتين لإنهاء رسم حلقات النطاق",
  "invalidCoordinateTypeMessage": "يتعذر تحديد نوع الإحداثيات المدخلة. يرجى فحص المدخلات",
  "noCenterPointSetMessage": "لم يتم تعيين نقطة مركز. يرجى التحقق من المدخلات",
  "ellipseMajorAxis": "محور رئيسي",
  "ellipseMinorAxis": "محور فرعي",
  "degreesRangeMessage": "يجب أن تكون القيمة بين 0 و360",
  "millsRangeMessage": "يجب أن تكون القيمة بين 0 و6400",
  "lengthLabel": "الطول",
  "angleLabel": "زاوية",
  "startPointLabel": "نقطة البداية",
  "endPointLabel": "نقطة النهاية",
  "centerPointLabel": "نقطة المركز",
  "distanceTableErrorMessage": "جدول المسافة فارغ. يرجى التأكد من إدخال بعض المسافات.",
  "setCoordFormatStringMessage": "تعيين سلسلة تنسيق الإحداثيات",
  "prefixMessage": "أضف البادئة '+/-' إلى الأرقام السالبة والموجبة",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "درجة دقيقة ثانية",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "الدرجات العشرية - دائرة العرض/خط الطول",
  "DDLongLatNotation": "الدرجات العشرية - خط الطول/دائرة العرض",
  "DDMLatLongNotation": "دقائق عشرية درجات - دائرة العرض/خط الطول",
  "DDMLongLatNotation": "دقائق عشرية درجات - خط الطول/دائرة العرض",
  "DMSLatLongNotation": "ثواني دقائق درجات - دائرة العرض/خط الطول",
  "DMSLongLatNotation": "ثواني دقائق درجات - خط الطول/دائرة العرض",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - حرف الحزمة",
  "UTMHemNotation": "UTM - نصف الكرة (N/S)",
  "circleTitle": "إنشاء نموذج دائرة",
  "radiusLabel": "نصف القطر",
  "diameterLabel": "القُطر",
  "startPointPlaceHolderLabel": "أدخل الإحداثيات",
  "formatInputLabel": "مدخلات التنسيق",
  "drawCircleLabel": "رسم دائرة",
  "drawLineLabel": "رسم خط",
  "createCircleInteractivelyLabel": "إنشاء دائرة بشكل تفاعلي",
  "rangeErrorMessage": "نصف القطر أو المحيط غير صحيح",
  "numericInvalidMessage": "يرجى إدخال قيمة رقمية",
  "timeLabel": "الوقت",
  "invalidTimeMessage": "قيمة الوقت غير صحيحة",
  "hoursLabel": "ساعات",
  "minutesLabel": "دقائق",
  "secondsLabel": "ثواني",
  "rateLabel": "المعدل",
  "invalidDistanceMessage": "قيمة مسافة غير صالحة",
  "feetSecondsLabel": "قدم/ثانية",
  "feetHourLabel": "قدم/ساعة",
  "kmSecondLabel": "كم/ثانية",
  "kmHourLabel": "كم/ساعة",
  "metersSecondLabel": "متر/ثانية",
  "metersHourLabel": "متر/ساعة",
  "milesSecondLabel": "ميل/ثانية",
  "milesHourLabel": "ميل/ساعة",
  "nauticalMilesSecondLabel": "ميل بحري/ثانية",
  "nauticalMilesHourLabel": "ميل بحري/ساعة",
  "clearGraphicsLabel": "مسح الرسومات البيانية",
  "ellipseTypeLabel": "نوع القطع الناقص",
  "ellipseSemiLabel": "شِبه",
  "ellipseFullLabel": "كامل",
  "drawEllipseLabel": "رسم قطع ناقص",
  "createEllipseInteractively": "إنشاء قطع ناقص بشكل تفاعلي",
  "axisLabel": "محور",
  "unitLabel": "وحدة",
  "majorRadiusLabel": "رئيسي (نصف القطر)",
  "majorDiameterLabel": "أكبر (قطر)",
  "axisErrorMessage": "يجب أن تكون القيمة أكبر من 0",
  "minorRadiusLabel": "فرعي (نصف القطر)",
  "minorDiameterLabel": "أصغر (قطر)",
  "orientationLabel": "توجيه",
  "orientationErrorMessage": "يجب أن تكون القيمة بين 0 و360",
  "warningMessage": "تحذير: لا تعد الرسومات البيانية المنشأة باستخدام أداة القطع الناقص رسومات بيانية جيوديسية",
  "fromLabel": "من",
  "distanceBearingLabel": "المسافة وزاوية البعد",
  "pointsLabel": "النقاط",
  "createLineInteractively": "إنشاء الخط بشكل تفاعلي",
  "lineLengthErrorMessage": "طول الخط غير صحيح",
  "degreesLabel": "الدرجات",
  "milsLabel": "أميال",
  "lineTypeLabel": "النوع",
  "interactiveLabel": "بشكل تفاعلي",
  "fixedLabel": "ثابت",
  "originLabel": "أصل",
  "cumulativeLabel": "تراكمي",
  "numberOfRingsLabel": "عدد الحلقات",
  "ringsErrorMessage": "عدد حلقات غير صحيح",
  "distanceBetweenRingsLabel": "المسافة بين الحلقات",
  "ringsDecimalErrorMessage": "أدخل قيمة رقمية إلى خانتين عشريتين",
  "distanceUnitsLabel": "وحدات المسافة",
  "distancesLabel": "مسافات",
  "numberOfRadialsLabel": "عدد الأشعة",
  "upLabel": "أعلى",
  "downLabel": "أسفل",
  "deleteLabel": "حذف",
  "radialsErrorMessage": "عدد الأشعة غير صحيح. الحد الأقصى المسموح به هو 360.",
  "radialsInvalidMessage": "القيمة غير صحيحة للتقديرات الشعاعية",
  "addPointLabel": "إضافة نقطة",
  "valueLabel": "قيمة",
  "valueText": "إدخال قيمة",
  "actionLabel": "إجراء",
  "distanceCalculatorLabel": "حاسبة المسافة",
  "abbrevMetersLabel": "متر",
  "abbrevFeetLabel": "قدم",
  "abbrevKmLabel": "كيلومتر",
  "abbrevMilesLabel": "ميل",
  "abbrevYardsLabel": "يارد",
  "abbrevNauticalMilesLabel": "ميل بحري",
  "abbrevDegreesLabel": "°",
  "abbrevMilsLabel": "ميل",
  "abbrevHoursLabel": "ساعة",
  "abbrevMinutesLabel": "متر",
  "abbrevSecondsLabel": "s",
  "abbrevFeetSecondsLabel": "قدم/ثانية",
  "abbrevFeetHourLabel": "قدم/ساعة",
  "abbrevKmSecondLabel": "كم/ثانية",
  "abbrevKmHourLabel": "كم/ساعة",
  "abbrevMetersSecondLabel": "متر/ثانية",
  "abbrevMetersHourLabel": "متر/ساعة",
  "abbrevMilesSecondLabel": "ميل/ثانية",
  "abbrevMilesHourLabel": "ميل/ساعة",
  "abbrevNauticalMilesSecondLabel": "نانومتر/ثانية",
  "abbrevNauticalMilesHourLabel": "نانومتر/ساعة",
  "publishDDBtn": "نشر",
  "publishTitle": "نشر الرسومات",
  "ddLayerName": "اسم الطبقة المنشورة",
  "missingDDLayerName": "يجب عليك إدخال اسم للطبقة",
  "publishToNewLayer": "نشر النتائج إلى طبقة معلم جديدة",
  "checkService": "فحص الخدمة: {0}.",
  "createService": "إنشاء الخدمة: {0}.",
  "unableToCreate": "يتعذر إنشاء: {0}",
  "addToDefinition": "إضافة إلى تعريف: {0}",
  "successfullyPublished": "تم نشر طبقة الويب بشكل ناجح{0}إدارة طبقة الويب",
  "userRole": "يتعذر إنشاء الخدمة لأن المستخدم لا يمتلك الأذونات",
  "missingLayerNameMessage": "يجب إدخال اسم طبقة صالح قبل النشر",
  "invalidLayerName": "يجب ألا يحتوي اسم الطبقة إلا على أحرف أبجدية رقمية وتسطير سفلي",
  "distanceLabel": "المسافة",
  "radiusDistance": "مسافة نصف القطر",
  "radials": "شعاعي",
  "rings": "حلقات",
  "orientationUnit": "وحدة الاتجاه",
  "radiusUnit": "وحدات نصف القطر",
  "angleUnitLabel": "وحدة الزاوية"
});