define({
  "_widgetLabel": "Επεξεργασία",
  "_featureAction_Edit": "Επεξεργασία",
  "title": "Επιλέξτε ένα πρότυπο για τη δημιουργία στοιχείων",
  "pressStr": "Πατήστε ",
  "ctrlStr": " CTRL ",
  "snapStr": " για να ενεργοποιηθεί η λειτουργία αγκίστρωσης",
  "close": "Κλείσιμο",
  "featureLayers": "Feature layers",
  "searchTemplates": "Αναζήτηση προτύπων",
  "noAvailableTempaltes": "Δεν υπάρχουν διαθέσιμα πρότυπα",
  "noCanCreateLayerAreCurrentlyVisible": "Δεν υπάρχουν αυτή τη στιγμή ορατά θεματικά επίπεδα με δυνατότητα δημιουργίας.",
  "layersAreInvisibleOrOutOfScaleRange": "Τα θεματικά επίπεδα είναι μη ορατά ή εκτός εύρους κλίμακας.",
  "relatedTables": "Σχετικοί πίνακες:",
  "relatedRecords": "Σχετικές εγγραφές:",
  "noRelatedRecotds": "Δεν βρέθηκαν σχετικές εγγραφές.",
  "startToDraw": "Κάντε κλικ για να αρχίσετε να σχεδιάζετε.",
  "startToAddPoint": "Κάντε κλικ για προσθήκη σημείου",
  "editRelatedFeature": "Επεξεργασία συσχετιζόμενου στοιχείου"
});