define({
  "_widgetLabel": "Převod souřadnic",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "formatInput": "Formátovat vstup",
  "copyAll": "Kopírovat vše",
  "copySuccessful": "Kopírování bylo úspěšné",
  "copyFailed": "Nelze kopírovat. Použijte příkaz Ctrl+C.",
  "parseCoordinatesError": "Souřadnice nelze analyzovat. Zkontrolujte zadané hodnoty.",
  "comfirmInputNotation": "Potvrďte označení vstupu",
  "latLongWarningMessage": "Vstupní souřadnice má předponu i příponu pro hodnotu zeměpisné šířky nebo zeměpisné délky, vrácená souřadnice je založena na předponě.",
  "inputLabel": "Vstup",
  "outputLabel": "Výstup",
  "cancelButtonLabel": "Storno",
  "applyButtonLabel": "Použít",
  "posNegPrefixLabel": "Přidejte předponu +/- ke kladným a záporným číslům",
  "editCoordinateDialogTitle": "Nastavit řetězec formátu souřadnic",
  "rememberDecisionLabel": "Zapamatovat mou volbu a znovu se již neptat.<br/>",
  "coordinateInputLabel": "Zadejte souřadnice nebo klikněte na mapu",
  "zoomLabel": "Zvětšení",
  "multipleNotationLabel": "označení odpovídají vašemu vstupu. Potvrďte, které chcete použít:",
  "copyToClipboard": "Kopírovat do schránky",
  "formatOutput": "Formátovat výstup",
  "addNewNotation": "Přidat nové označení",
  "notationAddedMessage": "Byla přidána nová notace",
  "addLabel": "Přidat",
  "removeCoordinate": "Odebrat souřadnici",
  "expandOutput": "Rozbalit výstup"
});