define(
   ({
    addLayer: "הוסף שכבה",
    layerName: "שכבה",
    layerRefresh: "רענן",
    layerLabel: "תווית",
    actions: "פעולות",
    popupOk: "אישור",
    popupCancel: "בטל",
    mainPanelTextPlaceholder: "דוגמה: תנאי כביש ראשי",
    invalidInterval: "יש תמיכה בתווים מספריים בלבד.",
    uploadImage: "העלאת תמונה",
    iconColumnText: "סמל",
    refreshInterval: "1 \'הערכת זמן בדקות\'",
    refreshIntervalTitle: "הערכת זמן בדקות",
    mainPanelText: "טקסט של לוח ראשי",
    mainPanelIcon: "תמונה של לוח ראשי",
    refreshIntervalInstruction: "עדכון מרווח",
    optionsText: "אפשרויות",
    symbolOptionsText: "אפשרויות סמל",
    iconOptionsText: "אפשרויות צלמית",
    sympolPopupTitle: "הגדר סמל",
    rdoLayer: "סמל שכבה",
    rdoCustom: "סמל מותאם אישית",
    chkCluster: "אפשר אשכול",
    defineClusterSymbol: "סמל אשכול",
    defineThemeClusterSymbol: "סמל אשכול מנושא",
    rdoEsri: "סמל Esri",
    rdoLayerIcon: "השתמש בסמל כצלמית",
    rdoCustomIcon: "העלה צלמית מותאמת אישית",
    editCustomSymbol: "ערוך סמל מותאם אישית",
    editCustomIcon: "ערוך צלמית מותאמת אישית",
    missingRefreshValue: "ספק ערך מרווח ריענון.",
    panelIconOption: "הצג כותרת לוח",
    enableRefresh: "אפשר ריענון שכבה",
    disableRefresh: "ריענון שכבה נתמך רק עבור אוספי ישויות",
    layer_type_not_supported: "סוג השכבה לא נתמך: "
  })
);
