define({
  "addLayer": "הוסף שכבה",
  "layerName": "שכבה",
  "layerRefresh": "רענן",
  "layerLabel": "תווית",
  "actions": "פעולות",
  "mainPanelTextPlaceholder": "דוגמה: עודכן לאחרונה:",
  "invalidInterval": "יש תמיכה בתווים מספריים בלבד.",
  "uploadImage": "העלאת תמונה",
  "iconColumnText": "תצוגה",
  "refreshInterval": "זמן בדקות",
  "refreshIntervalTitle": "הערכת זמן בדקות",
  "mainPanelText": "טקסט של לוח ראשי",
  "mainPanelIcon": "תמונה של לוח ראשי",
  "refreshIntervalInstruction": "רענן שכבות מדי:",
  "optionsText": "אפשרויות",
  "symbolOptionsText": "סימבולוגיית מפה",
  "iconOptionsText": "סימבולוגיית חלונית",
  "sympolPopupTitle": "הגדרות תצוגה",
  "rdoLayer": "סימבול ברירת מחדל",
  "rdoCustom": "השתמש בתמונה",
  "chkCluster": "אפשר אשכול",
  "defineClusterSymbol": "ציין סמל אשכול",
  "rdoEsri": "בחר סמל",
  "rdoLayerIcon": "השתמש בסמל מפה",
  "rdoCustomIcon": "השתמש בתמונה",
  "editCustomSymbol": "ערוך סמל מותאם אישית",
  "editCustomIcon": "ערוך צלמית מותאמת אישית",
  "missingRefreshValue": "ספק ערך מרווח ריענון.",
  "panelIconOption": "הצג תמונת לוגו",
  "enableRefresh": "אפשר ריענון שכבה",
  "disableRefresh": "ריענון שכבה נתמך רק עבור אוספי ישויות",
  "layer_type_not_supported": "סוג השכבה לא נתמך: ",
  "refreshUnit": "דקות.",
  "symbolOptions": "סמל",
  "panelFeatureDisplay": "חלונית",
  "chkGroup": "קבץ ישויות",
  "selectField": "שדה",
  "fieldLabel": "תווית",
  "addField": "הוסף שדה",
  "featureOptionsText": "אפשרויות שכבה",
  "groupOptionsText": "אפשרויות קבוצה",
  "panelCountOption": "הצג ספירות ישויות",
  "rdoStack": "הצג שורה חדשה לכל שדה",
  "rdoAppend": "הוסף שדות בשורה יחידה",
  "missingLayerInWebMap": "לא נמצאו שכבות אופרטיביות.",
  "displayClusterCnt": "הצג ספירת ישויות",
  "defineClusterFont": "ציין צבע גופן",
  "max_records": "הגעת למספר השדות המקסימלי"
});