define({
  "transparencyLabel": "Transparència",
  "outline": "Contorn",
  "fill": "Emplenament (el color només s'aplica quan l'estil està definit com a cos geomètric)",
  "style": "Estil",
  "mandatoryLabel": "Distància d'evacuació obligatòria",
  "mandatoryButtonLabel": "Configura la distància d'evacuació obligatòria",
  "safeLabel": "Distància d'evacuació segura",
  "safeButtonLabel": "Configura la distància d'evacuació segura",
  "selectOpLayerLabel": "Seleccioneu una capa operativa per als resultats",
  "selectDefaultMeasurementLabel": "Seleccioneu una unitat de mesura per defecte",
  "helpIconTooltip": "La llista de capes operatives s'emplena amb capes del mapa web actual amb el tipus de geometria de polígon.",
  "lineStyles": {
    "esriSLSDash": "Guió",
    "esriSLSDashDot": "Guió punt",
    "esriSLSDashDotDot": "Guió punt punt",
    "esriSLSDot": "Punt",
    "esriSLSLongDash": "Guió llarg",
    "esriSLSLongDashDot": "Guió llarg punt",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Guió curt",
    "esriSLSShortDashDot": "Guió curt punt",
    "esriSLSShortDashDotDot": "Guió curt punt punt",
    "esriSLSShortDot": "Punt",
    "esriSLSSolid": "Cos geomètric"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Enrere",
    "esriSFSCross": "Creu",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Endavant",
    "esriSFSHorizontal": "Horitzontal",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Cos geomètric",
    "esriSFSVertical": "Vertical"
  },
  "threatTypeLabel": "Tipus d'amenaça",
  "symbologyLabel": "Simbologia",
  "generalLabel": "General",
  "addThreatTypesLabel": "Afegeix un tipus d'amenaça",
  "threatTypeColLabel": "Tipus d'amenaça",
  "actions": "Accions",
  "newThreatTypePopupLabel": "Nou tipus d'amenaça",
  "chooseDefaultThreatTypeIconLabel": "Trieu dels valors per defecte",
  "mandatoryDistance": "Distància d'evacuació obligatòria",
  "safeDistance": "Distància d'evacuació segura",
  "units": "Unitats",
  "chooseDefaultThreatLabel": "Seleccioneu un tipus d'amenaça per defecte",
  "defaultThreatTypePopUpLabel": "Tipus d'amenaces per defecte",
  "editThreatLabel": "Edita l'amenaça",
  "defaultThreatTypeIconTooltip": "Llista de tipus d'amenaces per defecte",
  "uniqueThreatTypeMsg": "Introduïu un nom d'amenaça únic; ja existeix un tipus d'amenaça amb aquest nom.",
  "requiredThreatTypeMsg": "Aquest camp és obligatori",
  "unitMeasureLabel": "Les distàncies s'indiquen en {0}",
  "pipeBombLabel": "Bomba casolana",
  "suicideBombLabel": "Bomba suïcida",
  "briefcaseLabel": "Maletí",
  "carLabel": "Cotxe",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Camió de distribució petit",
  "containerWaterTruckLabel": "Camió cisterna/contenidor",
  "semiTrailerLabel": "Semiremolc"
});