define({
  "addTaskTip": "Adăugaţi unul sau mai multe filtre în widget şi configuraţi parametri pentru fiecare dintre acestea.",
  "enableMapFilter": "Eliminaţi filtrul stratului tematic presetat din hartă.",
  "newFilter": "Filtru nou",
  "filterExpression": "Expresie de filtrare",
  "layerDefaultSymbolTip": "Utilizați simbolul implicit al stratului tematic",
  "uploadImage": "Încărcaţi o imagine",
  "selectLayerTip": "Selectaţi un strat tematic.",
  "setTitleTip": "Setaţi un titlu.",
  "noTasksTip": "Niciul filtru configurat. Faceţi clic pe \"${newFilter}\" pentru a adăuga unul.",
  "collapseFiltersTip": "Restrângeți expresiile de filtrare (dacă există) când se deschide controlul",
  "zoomtoTip": "Panoramați pe obiectele spațiale rămase după ce filtrul este aplicat",
  "groupByLayerTip": "Gruparea filtrelor după stratul tematic",
  "autoApplyWhenValueInput": "Aplicaţi acest filtru automat după introducerea unei valori",
  "autoApplyWhenWidgetOpen": "Aplicaţi acest filtru atunci când widget-ul este deschis",
  "info": "Informaţii",
  "expressions": "Expresii",
  "allowCustom": "Se permite crearea unor filtre particularizate",
  "filterActions": "Acțiuni de filtru personalizate",
  "custom": "Activare filtre personalizate",
  "resetAll": "Activare resetare toate",
  "turnOffAll": "Activare dezactivare toate",
  "matchMsgSetAll": "Afișați obiectele spațiale care se potrivesc cu toate filtrele",
  "matchMsgSetAny": "Afișați obiectele spațiale care se potrivesc cu oricare dintre filtre"
});