define({
  "_widgetLabel": "Viedais redaktors",
  "_featureAction_SmartEditor": "Viedais redaktors",
  "noEditPrivileges": "Jūsu kontam nav piešķirta atļauja izveidot vai modificēt datus.",
  "widgetActive": "Aktīvs",
  "widgetNotActive": "Neaktīvs",
  "pressStr": "Nospiediet ",
  "ctrlStr": " CTRL ",
  "snapStr": " , lai iespējotu pieķeršanos",
  "noAvailableTempaltes": "Nav pieejamu sagatavju",
  "editorCache": " - Redaktora kešatmiņa",
  "presetFieldAlias": "Lauks",
  "presetValue": "Iepriekš iestatīta vērtība",
  "usePresetValues": " Izmantot iepriekš iestatītās vērtības (tikai jauniem elementiem)",
  "editGeometry": " Rediģēt ģeometriju",
  "savePromptTitle": "Saglabāt elementu",
  "savePrompt": "Vai vēlaties saglabāt esošo elementu?",
  "deletePromptTitle": "Izdzēst elementu",
  "deletePrompt": "Vai tiešām vēlaties izdzēst izvēlēto elementu?",
  "attachmentLoadingError": "Augšupielādējot pielikumus, radās kļūda",
  "attachmentSaveDeleteWarning": "Brīdinājums: pielikumos saglabātās izmaiņas tiek saglabātas automātiski",
  "autoSaveEdits": "Automātiski saglabā jaunu elementu",
  "addNewFeature": "Izveidot jaunu elementu",
  "featureCreationFailedMsg": "Nevar izveidot jaunu ierakstu/elementu",
  "relatedItemTitle": "Saistītā tabula/slānis",
  "invalidRelationShipMsg": "Lūdzu, pārliecinieties, vai primārās atslēgas laukam '${parentKeyField}' ir derīga vērtība",
  "pendingFeatureSaveMsg": "Lūdzu, saglabājiet elementu labojumus, pirms veidojat saistītu elementu.",
  "attachmentsRequiredMsg": "(*) Piesaistes ir nepieciešamas.",
  "coordinatePopupTitle": "Pārvietot elementu uz XY novietojumu",
  "coordinatesSelectTitle": "Koordinātu sistēma",
  "mapSpecialReferenceDropdownOption": "Kartes telpiskā atskaite",
  "latLongDropdownOption": "Platums/Garums",
  "xAttributeTextBoxLabel": "X koordināte:",
  "yAttributeTextBoxLabel": "Y koordināte:",
  "latitudeTextBoxLabel": "Platums:",
  "longitudeTextBoxLabel": "Garums:",
  "filterEditor": {
    "all": "Visi",
    "noAvailableTempaltes": "Nav pieejamas sagataves",
    "searchTemplates": "Meklēt sagataves"
  },
  "invalidConfiguration": "Logrīks nav konfigurēts vai konfigurētie slāņi vairs nav kartē. Lūdzu, atveriet programmu veidotāja režīmā un konfigurējiet logrīku atkārtoti.",
  "geometryServiceURLNotFoundMSG": "Nevar iegūt ģeometrijas servisa URL",
  "clearSelection": "Notīrīt",
  "refreshAttributes": "Atjaunināt elementu atribūtus",
  "automaticAttributeUpdatesOn": "Automātiski atjaunināt elementu atribūtus: Ieslēgt",
  "automaticAttributeUpdatesOff": "Automātiski atjaunināt elementu atribūtus: Izslēgt",
  "moveSelectedFeatureToGPS": "Pārvietot izvēlēto elementu uz pašreizējo GPS novietojumu",
  "moveSelectedFeatureToXY": "Pārvietot izvēlēto elementu uz XY novietojumu",
  "mapNavigationLocked": "Kartes navigācija: bloķēta",
  "mapNavigationUnLocked": "Kartes navigācija: atbloķēta"
});