define({
  "_widgetLabel": "Análise de ameaças",
  "threatAnalysisMainPageTitle": "Baseado no Guia de contraterrorismo JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Introduzir localização",
  "interactive": "Interativo",
  "fromCoord": "Coordenadas fixas",
  "existingFeature": "A partir de elementos existentes",
  "threatAnalysisCoordInputLabel": "Localização de ameaças",
  "enterCoords": "Introduzir Coordenadas",
  "threatAddPointToolTip": "Adicionar localização da ameaça",
  "threatDrawPointToolTip": "Clicar para adicionar localização da ameaça",
  "threatType": "Tipo de ameaça",
  "threatPlaceholder": "Começar a digitar para pesquisar uma ameaça",
  "mandatoryLabel": "Distância de evacuação obrigatória",
  "safeLabel": "Distância de evacuação segura",
  "zoneTypeLabel": "Tipo de zona",
  "feetLabel": "Pés",
  "metersLabel": "Metros",
  "unitsLabel": "Unidades",
  "threatGraphicLayer": "Gráfico de Ameaças",
  "settingsTitle": "Configurações",
  "mandatoryButtonLabel": "Configurar definições de distância de evacuação obrigatória",
  "safeButtonLabel": "Configurar as definições de abrigo no local",
  "style": "Estilo",
  "lineStyles": {
    "esriSLSDash": "Traço",
    "esriSLSDashDot": "Traço e Ponto",
    "esriSLSDashDotDot": "Traço, Ponto e Ponto",
    "esriSLSDot": "Ponto",
    "esriSLSLongDash": "Traço Longo",
    "esriSLSLongDashDot": "Traço Longo e Ponto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Traço Curto",
    "esriSLSShortDashDot": "Traço Curto e Ponto",
    "esriSLSShortDashDotDot": "Traço Curto, Ponto e Ponto",
    "esriSLSShortDot": "Traço Curto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Ao Contrário",
    "esriSFSCross": "Cruz",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Para a frente",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  },
  "resultsTitle": "Resultados",
  "publishTABtn": "Publicar",
  "layerName": "Nome da camada publicada",
  "invalidLayerName": "O nome da camada pode apenas conter caracteres alfanuméricos e traços inferiores.",
  "missingLayerName": "Tem de introduzir um nome para a camada",
  "missingLayerNameMessage": "Tem de introduzir um nome de camada válido antes de poder publicar",
  "publishingFailedLayerExists": "Falha ao publicar: já possui um serviço de elementos denominado {0}. Escolha outro nome.",
  "checkService": "Verificar Serviço: {0}",
  "createService": "Criar Serviço: {0}",
  "unableToCreate": "Não é possível criar: {0}",
  "addToDefinition": "Adicionar a definição: {0}",
  "successfullyPublished": "Camada web publicada com sucesso{0}Gerir a camada web",
  "userRole": "Não é possível criar o serviço porque o utilizador não possui permissões",
  "transparencyLabel": "Transparência",
  "outline": "Contorno",
  "fill": "Preenchimento (Apenas é aplicada cor quando o estilo é definido como sólido)",
  "createBtn": "Criar Zonas",
  "clearBtn": "Apagar",
  "invalidNumberMessage": "O valor introduzido não é válido",
  "invalidRangeMessage": "O valor tem de ser maior do que 0",
  "parseCoordinatesError": "Não foi possível analisar as coordenadas. Verifique a introdução.",
  "manualCoordinateInputInfo": "Introduza manualmente as coordenadas e clique em <b>Enter</b> para ampliar",
  "pipeBombLabel": "Bomba de Tubo",
  "suicideBombLabel": "Bomba Suicida",
  "briefcaseLabel": "Pasta",
  "carLabel": "Carro",
  "suvVanLabel": "SUV/CARRINHA",
  "smallDeliveryTruckLabel": "Carrinha de Entregas Pequena",
  "containerWaterTruckLabel": "Camião Cisterna/de Água",
  "semiTrailerLabel": "Semirreboque",
  "selectDrawModeLabel": "Selecionar Modo de Desenho",
  "selectFeatureLabel": "Selecionar Elemento Desta Camada"
});