define({
  "_widgetLabel": "Modifica",
  "_featureAction_Edit": "Modifica",
  "title": "Selezionare un modello per creare le feature",
  "pressStr": "Premere ",
  "ctrlStr": " CTRL ",
  "snapStr": " per abilitare lo snap",
  "close": "Chiudi",
  "featureLayers": "Feature layer",
  "searchTemplates": "Cerca modelli",
  "noAvailableTempaltes": "Nessun modello disponibile",
  "noCanCreateLayerAreCurrentlyVisible": "Nessun layer creabile è attualmente visibile.",
  "layersAreInvisibleOrOutOfScaleRange": "I layer sono invisibili o fuori scala.",
  "relatedTables": "Tabelle correlate:",
  "relatedRecords": "Record correlati:",
  "noRelatedRecotds": "Nessun record correlato trovato.",
  "startToDraw": "Fare clic per iniziare a disegnare",
  "startToAddPoint": "Fare clic per aggiungere un punto",
  "editRelatedFeature": "Modifica feature correlata",
  "duplicateValueWarning": " Impossibile inserire un valore duplicato in ${fieldName} di ${tableName}. Il valore duplicato è: ${value}"
});