define({
  "taskUrl": "Opgave-URL",
  "serviceURLPlaceholder": "Angiv geoprocesseringsopgavens URL",
  "layerOrder": "Lagrækkefølge",
  "defaultValue": "Standardværdi",
  "inputFeatureBy": "Angiv objekt efter",
  "inputRecordBy": "Angiv post efter",
  "renderer": "Gengivelsesværktøj",
  "displayType": "Vis type",
  "helpUrl": "Hjælp-URL",
  "useResultMapService": "Vis resultat med en korttjeneste",
  "drawOnMap": "Interaktiv tegning på kortet",
  "selectLayer": "Vælg et lag fra kortet",
  "selectTable": "Vælg en tabel fra kortet",
  "shareResults": "Tilføj resultat som operationelt lag",
  "setTask": "Indstil",
  "setTaskTitle": "Indstil GP-opgave",
  "enablePopup": "Aktivér pop-up-vindue",
  "unSupportGeometryType": "Kan ikke indstille gengivelsesværktøj på grund af ukendt geometritype.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Overfør fil",
  "selectFileToUpload": "Vælg fil...",
  "rasterFormat": "Rasterdataformat",
  "noFileSelected": "Ingen fil valgt!",
  "uploadSuccess": "Har overført fil uden fejl!",
  "showLayerContent": "Vis lagindhold",
  "urlPlaceholder": "URL til at få adgang til dataene",
  "useShapefile": "Brug shapefil i lokalt filsystem",
  "allowToExport": "Tillad eksport af resultater",
  "useDynamicSchema": "Output kan have et andet skema, brug dynamisk skema i stedet for et foruddefineret skema.",
  "useCurrentMapExtent": "Gem aktuelt kortområde",
  "ignoreOutput": "Tilsidesæt dette output",
  "turnOffOutput": "Deaktivér dette lag som standard",
  "inputJSONString": "Input JSON-streng"
});