define({
  "_widgetLabel": "Nacrtaj",
  "selectDrawMode": "Izaberi režim crtanja",
  "clear": "Izbriši",
  "point": "Tačka",
  "line": "Linija",
  "polyline": "Polilinija",
  "freehandPolyline": "Polilinija slobodnom rukom",
  "triangle": "Trougao",
  "extent": "Pravougaonik",
  "circle": "Krug",
  "ellipse": "Elipsa",
  "polygon": "Poligon",
  "freehandPolygon": "Poligon crtan slobodnom rukom",
  "text": "Tekst",
  "style": "Stil",
  "alpha": "Prozirnost",
  "width": "Širina",
  "size": "Veličina",
  "color": "Boja",
  "markerColor": "Boja označivača",
  "outlineColor": "Boja kontura",
  "lineColor": "Boja linije",
  "fillColor": "Boja ispune",
  "showMeasurements": "Prikaži mere",
  "showLocationMeasurement": "Prikaži merenje lokacije",
  "showAreaMeasurement": "Prikaži merenje površine",
  "showDistanceMeasurement": "Prikaži merenje rastojanja",
  "showDistanceMeasurementForLine": "Prikaži merenje dužine",
  "showDistanceMeasurementForPolygon": "Prikaži merenje obima",
  "locationToggleOn": "Pritisnite dugme za uključivanje/isključivanje da biste prikazali merenje lokacije",
  "locationToggleOff": "Pritisnite dugme za uključivanje/isključivanje da biste sakrili merenje lokacije",
  "areaToggleOn": "Pritisnite dugme za uključivanje/isključivanje da biste prikazali merenje površine",
  "areaToggleOff": "Pritisnite dugme za uključivanje/isključivanje da biste sakrili merenje površine",
  "distanceForLineToggleOn": "Pritisnite dugme za uključivanje/isključivanje da biste prikazali merenje dužine",
  "distanceForLineToggleOff": "Pritisnite dugme za uključivanje/isključivanje da biste sakrili merenje dužine",
  "distanceForPolygonToggleOn": "Pritisnite dugme za uključivanje/isključivanje da biste prikazali merenje obima",
  "distanceForPolygonToggleOff": "Pritisnite dugme za uključivanje/isključivanje da biste sakrili merenje obima",
  "areaUnits": "Jedinice površine",
  "distanceUnits": "Jedinice rastojanja",
  "kilometers": "Kilometri",
  "miles": "Milje",
  "meters": "Metri",
  "feet": "Stope",
  "yards": "Jardi",
  "nauticalmiles": "Nautičke milje",
  "squareKilometers": "Kvadratni kilometri",
  "squareMiles": "Kvadratne milje",
  "acres": "Ari",
  "hectares": "Hektari",
  "squareMeters": "Kvadratni metri",
  "squareFeet": "Kvadratne stope",
  "squareYards": "Kvadratne jarde",
  "undo": "Opozovi radnju",
  "redo": "Ponovi radnju",
  "results": "Rezultati",
  "points": "Tačke",
  "lines": "Linije",
  "areas": "Površine",
  "locationLabel": "Lokacija: ${value}",
  "areaLabel": "Površina: ${value} ${unit}",
  "distanceLabel": "Rastojanje: ${value} ${unit}",
  "distanceLabelForLine": "Dužina: ${value} ${unit}",
  "distanceLabelForPolygon": "Obim: ${value} ${unit}"
});