define({
  "_widgetLabel": "Disegna",
  "selectDrawMode": "Seleziona modalità disegno",
  "clear": "Cancella",
  "point": "Punto",
  "line": "Linea",
  "polyline": "Polilinea",
  "freehandPolyline": "Polilinea a mano libera",
  "triangle": "Triangolo",
  "extent": "Inviluppo",
  "circle": "Cerchio",
  "ellipse": "Ellisse",
  "polygon": "Poligono",
  "freehandPolygon": "Poligono a mano libera",
  "text": "Testo",
  "style": "Stile",
  "alpha": "Trasparenza",
  "width": "Larghezza",
  "size": "Dimensione",
  "color": "Colore",
  "markerColor": "Colore marcatore",
  "outlineColor": "Colore contorno",
  "lineColor": "Colore linea",
  "fillColor": "Colore riempimento",
  "showMeasurements": "Mostra misurazioni",
  "showLocationMeasurement": "Mostra misura di posizione",
  "showAreaMeasurement": "Mostra misura dell’area",
  "showDistanceMeasurement": "Mostra misura della distanza",
  "showDistanceMeasurementForLine": "Mostra la misurazione della lunghezza",
  "showDistanceMeasurementForPolygon": "Mostra la misurazione del perimetro",
  "locationToggleOn": "Premere il pulsante di selezione per mostrare la misura della posizione",
  "locationToggleOff": "Premere il pulsante di selezione per nascondere la misura della posizione",
  "areaToggleOn": "Premere il pulsante di selezione per mostrare la misura dell’area",
  "areaToggleOff": "Premere il pulsante di selezione per nascondere la misura dell’area",
  "distanceForLineToggleOn": "Premere il pulsante di selezione per mostrare la misura della lunghezza",
  "distanceForLineToggleOff": "Premere il pulsante di selezione per nascondere la misura della lunghezza",
  "distanceForPolygonToggleOn": "Premere il pulsante di selezione per mostrare la misura del perimetro",
  "distanceForPolygonToggleOff": "Premere il pulsante di selezione per nascondere la misura del perimetro",
  "areaUnits": "Unità area",
  "distanceUnits": "Unità di distanza",
  "kilometers": "Chilometri",
  "miles": "Miglia",
  "meters": "Metri",
  "feet": "Piedi",
  "yards": "Iarde",
  "nauticalmiles": "Miglia nautiche",
  "squareKilometers": "Chilometri quadrati",
  "squareMiles": "Miglia quadrate",
  "acres": "Acri",
  "hectares": "Ettari",
  "squareMeters": "Metri quadrati",
  "squareFeet": "Piedi quadrati",
  "squareYards": "Iarde quadrate",
  "undo": "Annulla",
  "redo": "Ripeti",
  "results": "Risultati",
  "points": "Punti",
  "lines": "Linee",
  "areas": "Aree",
  "locationLabel": "Posizione: ${value}",
  "areaLabel": "Area: ${value} ${unit}",
  "distanceLabel": "Distanza: ${value} ${unit}",
  "distanceLabelForLine": "Lunghezza: ${value} ${unit}",
  "distanceLabelForPolygon": "Perimetro: ${value} ${unit}"
});