define({
  root: ({
    _widgetLabel: "Business Analyst",
    addPoint: "Add point by clicking on the map",
    addRingsDtWt: "Add rings, drive time or walk time.",
    apply: "Apply",
    back: "Back",
    colon: ":",
    creditInformation: "Credit Information",
    driveTime: "Drive time",
    esriInfographics: "Esri Infographics",
    esriReports: "Esri Reports",
    headerDescription_km: "kilometer",
    headerDescription_miles: "mile",
    headerDescription_minutes: "minute",
    infographics: "Infographics",
    invalidValueRing: "The values must be in range of 0 to 1,000.",
    invalidValueDTWT: "The values must be in range of 0 to 300.",
    km: "km",
    miles: "miles",
    minutes: "minutes",
    myInfographics: "My Infographics",
    myReports: "My Reports",
    noPermissions: "Your account cannot run the Business Analyst widget.  In order to run the Business Analyst widget, the administrator of your organization needs to grant you GeoEnrichment and Network Analysis <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privileges</a>, and also allocate <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">credits</a>.",
    radii: "radii",
    radius: "Radius",
    radius_lowercase: "radius",
    reports: "Reports",
    ring: "Ring",
    rings: "Rings",
    runInfographic: "Run Infographic",
    runReport: "Run Report",
    selectPointOrPolygon: "Select a Point or Polygon feature on the map, search for an address or place, or drop a pin on the map to view more information for areas.",
    selectReport: "Select Report",
    selectTemplate: "Select Template",
    sharedInfographics: "Shared Infographics",
    sharedReports: "Shared Reports",
    thisEntryIsNotValid: "This entry is not valid.",
    time: "Time",
    walkTime: "Walk time",
    widgetDescription: "Access Infographics and Reports that summarize key indicators and data for any area.",

    // Filtering Select
    None: "Select..."
  }),
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
