define({
  "taskUrl": "Uzdevuma URL",
  "setTask": "Iestatīt",
  "setTaskPopupTitle": "Iestatīt uzdevumu",
  "validate": "Iestatīt",
  "inValidGPService": "Ievadiet derīgu ģeodatu apstrādes servisu.",
  "noOutputParameterWithGeometryType": "Izvēlētajā ģeodatu apstrādes servisā jābūt vismaz vienam izvades parametram ar norādītu ģeometrijas veidu. Lūdzu, izvēlieties citu ģeodatu apstrādes servisu.",
  "invalidOutputGeometry": "Izvēlētā ģeodatu apstrādes servisa izvades ģeometrijas veids nav saderīgs ar projekta iestatījumiem. Nevar saglabāt ģeodatu apstrādes servisa rezultātus.",
  "GPFeatureRecordSetLayerERR": "Ievadiet ģeodatu apstrādes servisu tikai ar ievadņu veidu “GPFeatureRecordSetLayer”.",
  "invalidInputParameters": "Ievades parametru skaits ir mazāks par 1 vai lielāks par 3. Lūdzu, atveriet derīgu ģeodatu apstrādes servisu.",
  "projectSetting": {
    "title": "Projekta iestatījumi",
    "note": "Piezīme. Projekta iestatījumi nav obligāti, jo lietotājs var saglabāt projektu vēlamajos tīmekļa kartes slāņos ar tīkla zuduma teritoriju un ievades parametriem. Lietotājs var saglabāt citus izvades parametrus no grupas “Izvade” cilnē “Ievade/izvade”.",
    "projectPolygonLayer": "Projekta laukumu slānis",
    "outputParameterName": "Izvades parametra nosaukums",
    "projectPointLayer": "Projekta punktu slānis",
    "selectLabel": "Atlasīt",
    "polygonLayerHelp": "<p>Tiks parādīts daudzstūra slānis ar šādiem nosacījumiem:<br/><ul><li>Slānī jābūt rediģēšanas iespējām, piemēram, “Izveidot”, “Dzēst” un “Atjaunināt”</li><li>Slānī jābūt diviem laukiem ar precīzu nosaukumu un datu tipu:</li><ul><li>nosaukums (virknes tipa lauks)</li><li>GlobalID (GlobalID tipa lauks)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>Tiks parādīti izvades laukuma slāņi no uzdevuma vietrāža (URL)<p/>",
    "pointLayerHelp": "<p>Tiks parādīts punktu slānis ar šādiem nosacījumiem:<br/><ul><li>Slānī jābūt rediģēšanas iespējām, piemēram, “Izveidot”, “Dzēst” un “Atjaunināt”</li><li>Slānī jābūt diviem laukiem ar precīzu nosaukumu un datu tipu:</li><ul><li>inputtype (virknes tipa lauks)</li><li>projectid (GUID tipa lauks)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "Karogs",
    "barrier": "Barjera",
    "skip": "Izlaist",
    "title": "Ievade/izvade",
    "inputSettingsLabel": "Ievades iestatījumi",
    "outputSettingsLabel": "Izvades iestatījumi",
    "inputLabel": "Kartes teksts",
    "inputTooltip": "Rīka padoms",
    "symbol": "Simbols",
    "typeText": "Veids",
    "outputParametersText": "Izvades parametri",
    "saveToLayerText": "Saglabāt slānī (pēc izvēles)",
    "skipText": "Izlaižams",
    "visibilityText": "Redzams",
    "exportToCsvText": "Eksportēt uz CSV",
    "exportToCsvDisplayText": "CSV",
    "settitngstext": "Iestatījumi",
    "addFieldTitle": "Pievienot lauku",
    "enterDisplayText": "Ievadīt parādāmo tekstu",
    "setScale": "Iestatīt mērogu",
    "outputDisplay": "Parādīt tekstu",
    "saveToLayerHelp": "<p>Tiks parādīts slānis ar šādiem nosacījumiem<br/><ul><li>Slānī jābūt rediģēšanas iespējām, piemēram, “Izveidot”, “Dzēst” un “Atjaunināt”</li><li>Slānī jābūt diviem laukiem ar nosaukumu un datu tipu:</li><ul><li>parametername (virknes tipa lauks)</li><li>projectid (Guid tipa lauks)</li></ul></ul><p/>"
  },
  "summaryTab": {
    "title": "Vispārīgie iestatījumi",
    "summaryFieldsetText": "Kopsavilkuma iestatījumi",
    "inputOutput": "Ievade/izvade",
    "field": "Lauks",
    "operator": "Operators",
    "inputOperatorCountOption": "Skaits",
    "outputOperatorCountOption": "Skaits",
    "outputOperatorSkipCountOption": "Izlaist skaitu",
    "fieldOperatorSumOption": "Summa",
    "fieldOperatorMinOption": "Min.",
    "fieldOperatorMaxOption": "Maks.",
    "fieldOperatorMeanOption": "Vidējais",
    "expressionAddButtonText": "Pievienot",
    "expressionVerifyButtonText": "Verificēt",
    "summaryEditorText": "Kopsavilkuma teksts",
    "autoZoomAfterTrace": "Papildu opcijas",
    "zoomText": "Automātiska tālummaiņa pēc trasēšanas",
    "summarSettingTooltipText": "Pievienot ievades/izvades skaitu"
  },
  "validationErrorMessage": {
    "webMapError": "Tīmekļa karte nav neviena pieejama slāņa. Lūdzu, izvēlieties derīgu tīmekļa karti.",
    "inputTypeFlagGreaterThanError": "Ievadē karoga veids nevar būt vairāk par viena veida karogu (sākuma punktu).",
    "inputTypeFlagLessThanError": "Ir nepieciešama vismaz viena ievade veidā karogs (sākuma punkts).",
    "inputTypeBarrierErr": "Ievadē barjeras veids nevar būt vairāk par vienu barjeras veidu.",
    "inputTypeSkipErr": "Ievadē izlaišanas veids nevar  būt vairāk par vienu  ievadi.",
    "displayTextForButtonError": "Pogas “Palaist” parādāmais teksts nevar būt tukšs.",
    "UnableToLoadGeoprocessError": "Nevar ielādēt ģeodatu apstrādes servisu.",
    "invalidSummaryExpression": "Nederīga izteiksme.",
    "validSummaryExpression": "Izdevās!",
    "invalidProjectSettings": "Nederīgi projekta iestatījumi.<br/> Lūdzu, izvēlieties derīgu vērtību sadaļā “${projectSetting}”."
  },
  "hintText": {
    "labelTextHint": "Padoms. Nodrošiniet kartes attēlojuma tekstu izvades parametru rezultātu panelim.",
    "displayTextHint": "Padoms. Tas tiks parādīts šī izvades parametra datu panelī.",
    "inputTextHint": "Padoms. Izveidojiet savu izteiksmi, izvēloties ievades, izvades un lauka nosaukumus.",
    "expressionHint": "Padoms. Izvēlieties vienības un noklikšķiniet uz Pievienot, lai izveidotu izteiksmi."
  }
});