define({
  "_widgetLabel": "Gràfic",
  "executeChartTip": "Feu clic en un dels elements de tasca següents per executar el gràfic.",
  "invalidConfig": "Configuració no vàlida.",
  "noneChartTip": "No s'ha configurat cap tasca de gràfic per a aquest widget.",
  "chartParams": "Opcions",
  "charts": "CHARTS",
  "apply": "APPLY",
  "useSpatialFilter": "Utilitza un filtre espacial per limitar les entitats",
  "useCurrentMapExtent": "Només les entitats que s'intersequen amb l'àrea del mapa actual",
  "drawGraphicOnMap": "Només les entitats que s'intersequen amb una àrea definida per l'usuari",
  "chartResults": "Resultats del gràfic",
  "clearResults": "Esborra els resultats",
  "noPermissionsMsg": "No teniu permisos per accedir a aquest servei.",
  "specifySpatialFilterMsg": "Especifiqueu el filtre espacial per a aquesta tasca.",
  "queryError": "Error de consulta.",
  "noResults": "No s'ha trobat cap entitat.",
  "category": "Categoria",
  "count": "Recompte",
  "label": "Etiqueta",
  "horizontalAxis": "Eix horitzontal",
  "verticalAxis": "Eix vertical",
  "dataLabels": "Etiquetes de dades",
  "color": "Color",
  "colorful": "Colorit",
  "monochromatic": "Monocromàtic",
  "tasks": "Tasques",
  "results": "Resultats",
  "applySpatialFilterToLimitResults": "Aplica un filtre espacial per limitar els resultats",
  "useCurrentExtentTip": "Parcialment o totalment dins de l'extensió de mapa actual",
  "useDrawGraphicTip": "Parcialment o totalment dins de la forma dibuixada al mapa",
  "useFeaturesTip": "En funció de les ubicacions pel que fa a les entitats d'una altra capa",
  "noSpatialLimitTip": "No limitis espacialment els resultats",
  "applySearchDistance": "Aplica una distància de cerca",
  "spatialRelationship": "Relació espacial",
  "relatedLayer": "Capa relacionada",
  "clear": "Esborra",
  "bufferDistance": "Distància d'àrea d'influència",
  "miles": "Milles",
  "kilometers": "Quilòmetres",
  "feet": "Peus",
  "meters": "Metres",
  "yards": "Iardes",
  "nauticalMiles": "Milles nàutiques",
  "back": "Enrere",
  "execute": "Aplica"
});