define({
  "showArcgisBasemaps": "Uwzględnij mapy bazowe z portalu",
  "add": "Kliknij, aby dodać nową mapę bazową",
  "edit": "Właściwości",
  "titlePH": "Tytuł mapy bazowej",
  "thumbnailHint": "Kliknij obraz do zaktualizowania",
  "urlPH": "Adres URL warstwy",
  "addlayer": "Dodaj mapę bazową",
  "warning": "Nieprawidłowe dane wejściowe",
  "save": "Wróć i zapisz",
  "back": "Wróć i anuluj",
  "addUrl": "Dodaj adres URL",
  "autoCheck": "Automatyczne sprawdzanie",
  "checking": "Trwa sprawdzanie...",
  "result": "Zapisano pomyślnie",
  "spError": "Wszystkie mapy bazowe dodane do galerii muszą mieć to samo odniesienie przestrzenne.",
  "invalidTitle1": "Mapa bazowa '",
  "invalidTitle2": "' już istnieje. Wybierz inny tytuł.",
  "invalidBasemapUrl1": "Warstwy tego typu nie można użyć jako mapy bazowej.",
  "invalidBasemapUrl2": "Dodawana mapa bazowa ma inne odniesienie przestrzenne od bieżącej mapy.",
  "addBaselayer": "Dodaj warstwę mapy bazowej"
});