define({
  "_widgetLabel": "Synlighet",
  "observerLocation": "Observatørlokasjon",
  "formatIconTooltip": "Formater inndata",
  "addPointToolTip": "Legg til observatørlokasjon",
  "fieldOfView": "Synsfelt",
  "useMilsText": "Bruk strek for vinkler",
  "observerHeight": "Observatørhøyde",
  "minObsDistance": "Min. observasjonsavstand",
  "maxObsDistance": "Maks. observasjonsavstand",
  "taskURLError": "Konfigurasjonsfilen for miniprogrammet inneholder en URL som ikke kan nås.  Kontakt systemadministratoren.",
  "taskURLInvalid": "Geoprosesseringsoppgaven som er konfigurert med dette miniprogrammet, er ikke gyldig. Kontakt systemadministratoren.",
  "viewshedError": "Det oppstod en feil under oppretting av synlighet. Kontroller at observatørlokasjonen er innenfor høydeoverflaten.</p>",
  "validationError": "<p>Skjemaet for oppretting av synlighet har manglende eller ugyldige parametere. Kontroller at:</p><ul><li>Det er angitt en observatørlokasjon.</li><li>Synsfeltet for observatøren ikke er 0.</li><li>Det er angitt en gyldig verdi for observatørhøyde.</li><li>Det er angitt gyldige verdier for min. og maks. observasjonsavstand.</li></ul>",
  "comfirmInputNotation": "Bekreft inndatanotasjon",
  "notationsMatch": "notasjoner samsvarer med inndataene. Bekreft hvilke du vil bruke:",
  "createBtn": "Opprett",
  "clearBtn": "Tøm",
  "setCoordFormat": "Angi koordinatformatstreng",
  "prefixNumbers": "Legg til prefikset \"+/-\" for positive og negative tall",
  "parseCoordinatesError": "Kan ikke analysere koordinater. Sjekk inndataene.",
  "cancelBtn": "Avbryt",
  "applyBtn": "Bruk",
  "invalidMessage": "Angi en numerisk verdi.",
  "observerRangeMessage": "Ugyldig observatørhøyde",
  "minimumRangeMessage": "Ugyldig minste observasjonsområde",
  "maximumRangeMessage": "Største observasjonsområde må være større enn minste observasjonsområde og kan ikke være mer enn ${limit} ${units}.",
  "portalURLError": "URL-en til ArcGIS Online-organisasjonen eller Portal for ArcGIS er ikke konfigurert. Sjekk med systemadministratoren.",
  "privilegeError": "Brukerrollen din har kan ikke utføre analyser. Hvis du vil utføre analyser, må administratoren i organisasjonen gi deg bestemte <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">rettigheter</a>.",
  "noServiceError": "Høydeanalysetjeneste er ikke tilgjengelig. Sjekk konfigurasjonen for ArcGIS Online-organisasjonen eller Portal for ArcGIS.",
  "pointToolTooltip": "Klikk for å legge til obervatørlokasjon",
  "degreesLabel": "grader",
  "milsLabel": "tusendels tommer",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Desimalgrader - Breddegrad/lengdegrad",
  "DDLongLatNotation": "Desimalgrader - Lengdegrad/breddegrad",
  "DDMLatLongNotation": "Grader og desimalminutter - Breddegrad/lengdegrad",
  "DDMLongLatNotation": "Grader og desimalminutter - Lengdegrad/breddegrad",
  "DMSLatLongNotation": "Grader Minutter Sekunder - Breddegrad/lengdegrad",
  "DMSLongLatNotation": "Grader Minutter Sekunder - Lengdegrad/breddegrad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Båndbokstav",
  "UTMHemNotation": "UTM - Halvkule (N/S)",
  "mainPageTitle": "Radial siktlinje",
  "resultsTitle": "Resultater",
  "publishBtnLabel": "Publiser",
  "layerName": "Publisert lagnavn",
  "invalidLayerName": "Lagnavn kan bare inneholde alfanumeriske tegn og understrekingstegn",
  "missingLayerName": "Angi navn på laget",
  "back": "Tilbake",
  "publishingFailedLayerExists": "Publiseringen mislyktes: Du har allerede en geoobjektstjeneste med navnet {0}. Velg et annet navn.",
  "checkService": "Kontroller tjeneste: {0}",
  "createService": "Opprett tjeneste {0}",
  "unableToCreate": "Kan ikke opprette: {0}",
  "addToDefinition": "Legg til definisjon: {0}",
  "successfullyPublished": "Vellykket publisering av weblag{0}Administrer weblaget",
  "userRole": "Kan ikke opprette tjeneste fordi brukeren ikke har tillatelser",
  "publishToNewLayer": "Publiser resultater til et nytt geoobjektlag",
  "missingLayerNameMessage": "Du må angi et gyldig lagnavn før du kan publisere",
  "regionTypeLabel": "Regiontype",
  "centerPointLabel": "Midtpunkt",
  "observationHeightLabel": "Observasjonshøyde",
  "heightUnitLabel": "Høydeenhet",
  "minObservationDistanceLabel": "MinObservation-avstand",
  "maxObservationDistance": "MaxObservation-avstand",
  "distanceUnitLabel": "Avstandsenhet",
  "fovstartAngleLabel": "FOV-startvinkel",
  "fovEndAngleLabel": "FOV-sluttvinkel",
  "andleUnitsLabel": "Vinkelenheter"
});