define({
  "_widgetLabel": "Muuda",
  "_featureAction_Edit": "Muuda",
  "title": "Valige objektide loomiseks mall",
  "pressStr": "Snäppimise kasutamiseks ",
  "ctrlStr": " vajutage ",
  "snapStr": " CTRL",
  "close": "Sule",
  "featureLayers": "Objektikihid",
  "searchTemplates": "Otsingu mallid",
  "noAvailableTempaltes": "Ühtki malli pole saadaval",
  "noCanCreateLayerAreCurrentlyVisible": "Praegu ei ole nähtaval ühtki kihti, mida saab luua.",
  "layersAreInvisibleOrOutOfScaleRange": "Kihid on nähtamatud või mõõtkavavahemikust väljas.",
  "relatedTables": "Seotud tabelid:",
  "relatedRecords": "Seotud kirjed:",
  "noRelatedRecotds": "Seotud kirjeid ei leitud.",
  "startToDraw": "Kliki joonistamiseks",
  "startToAddPoint": "Kliki punkti lisamiseks",
  "editRelatedFeature": "Seotud objekti muutmine",
  "duplicateValueWarning": " Tabeli ${tableName} väljale ${fieldName} ei saa topeltväärtust sisestada. Topeltväärtus on: ${value}"
});