define({
  "_widgetLabel": "Editor Inteligente",
  "_featureAction_SmartEditor": "Editor Inteligente",
  "noEditPrivileges": "Sua conta não tem permissão para criar ou modificar dados.",
  "widgetActive": "Ativo",
  "widgetNotActive": "Inativo",
  "pressStr": "Pressione ",
  "ctrlStr": " CTRL ",
  "snapStr": " para habilitar o ajuste",
  "noAvailableTempaltes": "Nenhum modelo disponível",
  "editorCache": " - Cache de Editor",
  "presetFieldAlias": "Campo",
  "presetValue": "Valor Pré-Configurado",
  "usePresetValues": " Utilizar Valores Pré-Configurados (Novas feições somente)",
  "editGeometry": " Editar Geometria",
  "savePromptTitle": "Salvar feição",
  "savePrompt": "Gostaria de salvar a feição atual?",
  "deletePromptTitle": "Excluir feição",
  "deletePrompt": "Tem certeza que deseja excluir a feição selecionada?",
  "attachmentLoadingError": "Erro ao transferir anexos",
  "attachmentSaveDeleteWarning": "Aviso: As alterações dos anexos são salvas automaticamente",
  "autoSaveEdits": "Salva a nova feição automaticamente",
  "addNewFeature": "Criar nova feição",
  "featureCreationFailedMsg": "Não é possível criar um novo registro/feição",
  "relatedItemTitle": "Camada/Tabela Relacionada",
  "invalidRelationShipMsg": "Certifique-se que o campo de chave primária: '${parentKeyField}' tenha um valor válido",
  "pendingFeatureSaveMsg": "Salve as edições da feição antes de criar uma feição relacionada.",
  "attachmentsRequiredMsg": "(*) Anexos são exigidos.",
  "coordinatePopupTitle": "Mover feição para localização XY",
  "coordinatesSelectTitle": "Sistema de Coordenadas:",
  "mapSpecialReferenceDropdownOption": "Referência Espacial do Mapa",
  "latLongDropdownOption": "Latitude/Longitude",
  "xAttributeTextBoxLabel": "Coordenada-X:",
  "yAttributeTextBoxLabel": "Coordenada-Y:",
  "latitudeTextBoxLabel": "Latitude:",
  "longitudeTextBoxLabel": "Longitude:",
  "filterEditor": {
    "all": "Todos",
    "noAvailableTempaltes": "Nenhum modelo disponível",
    "searchTemplates": "Pesquisar Modelos"
  },
  "invalidConfiguration": "O Widget não está configurado ou as camadas na configuração não estão mais no mapa.  Abra o aplicativo no modo do construtor e configure novamente o widget.",
  "geometryServiceURLNotFoundMSG": "Não foi possível obter URL do Serviço de Geometria",
  "clearSelection": "Apagar",
  "refreshAttributes": "Atualizar atributos da feição",
  "automaticAttributeUpdatesOn": "Atualizar automaticamente atributos da feição: ATIVADO",
  "automaticAttributeUpdatesOff": "Atualizar automaticamente atributos da feição: DESATIVADO",
  "moveSelectedFeatureToGPS": "Mover feição selecionada para a localização atual do GPS",
  "moveSelectedFeatureToXY": "Mover feição selecionada para localização XY",
  "mapNavigationLocked": "Navegação do Mapa: Bloqueada",
  "mapNavigationUnLocked": "Navegação do Mapa: Desbloqueada"
});