define({
  "_widgetLabel": "脅威分析",
  "threatAnalysisMainPageTitle": "JCAT Counterterrorism Guide に基づく",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "入力位置",
  "interactive": "対話的",
  "fromCoord": "固定座標",
  "existingFeature": "既存のフィーチャから",
  "threatAnalysisCoordInputLabel": "脅威の位置",
  "enterCoords": "座標値入力",
  "threatAddPointToolTip": "脅威の位置の追加",
  "threatDrawPointToolTip": "クリックして脅威の位置を追加",
  "threatType": "脅威タイプ",
  "threatPlaceholder": "脅威の検索のための入力を開始",
  "mandatoryLabel": "必須避難距離",
  "safeLabel": "シェルター内避難ゾーン",
  "zoneTypeLabel": "ゾーン タイプ",
  "feetLabel": "フィート",
  "metersLabel": "メートル",
  "unitsLabel": "単位",
  "settingsTitle": "設定",
  "mandatoryButtonLabel": "必須避難距離設定の構成",
  "safeButtonLabel": "シェルター内避難設定の構成",
  "style": "スタイル",
  "lineStyles": {
    "esriSLSDash": "破線",
    "esriSLSDashDot": "1 点鎖線",
    "esriSLSDashDotDot": "2 点鎖線",
    "esriSLSDot": "点",
    "esriSLSLongDash": "長い破線",
    "esriSLSLongDashDot": "長い 1 点鎖線",
    "esriSLSNull": "NULL",
    "esriSLSShortDash": "短い破線",
    "esriSLSShortDashDot": "短い 1 点鎖線",
    "esriSLSShortDashDotDot": "短い 2 点鎖線",
    "esriSLSShortDot": "点線",
    "esriSLSSolid": "実線"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "逆方向",
    "esriSFSCross": "十字",
    "esriSFSDiagonalCross": "対角線",
    "esriSFSForwardDiagonal": "正方向",
    "esriSFSHorizontal": "水平方向",
    "esriSFSNull": "NULL",
    "esriSFSSolid": "実線",
    "esriSFSVertical": "垂直"
  },
  "resultsTitle": "結果",
  "publishTABtn": "公開",
  "layerName": "公開されたレイヤー名",
  "invalidLayerName": "レイヤー名は、英数字とアンダースコア (_) だけを含むようにする必要があります。",
  "missingLayerName": "レイヤーの名前を入力する必要があります",
  "missingLayerNameMessage": "公開の前に、有効なレイヤー名を入力する必要があります。",
  "publishingFailedLayerExists": "公開に失敗しました: フィーチャ サービス名 {0} はすでに存在しています。 別の名前を選択してください。",
  "checkService": "次のサービスを確認: {0}",
  "createService": "次のサービスを作成: {0}",
  "unableToCreate": "次のものを作成できません: {0}",
  "addToDefinition": "定義に追加: {0}",
  "successfullyPublished": "Web レイヤー {0} を正常に公開できました。Web レイヤーの管理",
  "userRole": "ユーザーにアクセス権限がないため、サービスを作成できません。",
  "transparencyLabel": "透過表示",
  "outline": "アウトライン",
  "fill": "塗りつぶし (スタイルを実線に設定した場合のみ色を適用)",
  "createBtn": "ゾーンの作成",
  "clearBtn": "消去",
  "invalidNumberMessage": "入力された値が有効ではありません。",
  "invalidRangeMessage": "値は 0 より大きくなければなりません。",
  "parseCoordinatesError": "座標を解析できません。 入力を確認してください。"
});