define({
  "_widgetLabel": "Matomumas",
  "observerLocation": "Stebėtojo vieta",
  "formatIconTooltip": "Formato įvestis",
  "addPointToolTip": "Pridėti stebėtojo vietą",
  "fieldOfView": "Matymo laukas",
  "useMilsText": "Naudoti mylias kampams",
  "observerHeight": "Stebėtojo aukštis",
  "minObsDistance": "Mažiausias stebimas atstumas",
  "maxObsDistance": "Didžiausias stebimas atstumas",
  "taskURLError": "Valdiklio konfigūracijoje yra nepasiekiamas URL. Kreipkitės į sistemos administratorių",
  "taskURLInvalid": "Geoapdorojimo užduotis, sukonfigūruota su šiuo valdikliu yra netinkama. Kreipkitės į sistemos administratorių",
  "viewshedError": "Kuriant matomumą įvyko klaida. Pasirūpinkite, kad jūsų stebėtojo vieta būtų aukščio paviršiaus aprėptyje.</p>",
  "validationError": "<p>Matomumo kūrimo formos nėra arba jos parametrai netinkami, Įsitikinkite, ar:</p><ul><li>Nustatyta stebėtojo vieta.</li><li>Stebėtojo matomumo laukas yra 0.</li><li>Stebėtojo aukščio reikšmė yra tinkama.</li><li>Mažiausios ir didžiausios stebimo atstumo reikšmės yra tinkamos.</li></ul>",
  "comfirmInputNotation": "Patvirtinkite įvesties žymėjimą",
  "notationsMatch": "žymėjimai atitinka įvestį, patvirtinkite, kurį norite naudoti:",
  "createBtn": "Kurti",
  "clearBtn": "Valyti",
  "setCoordFormat": "Nustatyti koordinačių formato eilutę",
  "prefixNumbers": "Pridėti „+/-“ prefiksą prie teigiamų ir neigiamų skaičių",
  "parseCoordinatesError": "Negalima analizuoti koordinačių. Patikrinkite savo įvestį.",
  "cancelBtn": "Atšaukti",
  "applyBtn": "Taikyti",
  "invalidMessage": "Įveskite skaitinę reikšmę.",
  "observerRangeMessage": "Netinkamas stebėtojo aukštis",
  "minimumRangeMessage": "Netinkamas minimalus stebimas atstumas",
  "maximumRangeMessage": "Maksimalus stebimas atstumas turi būti didesnis negu minimalus stebimas atstumas ir negali būti didesnis nei ${limit} ${units}.",
  "portalURLError": "Nesukonfigūruotas jūsų ArcGIS Online organizacijos arba Portal for ArcGIS URL. Kreipkitės į sistemos administratorių.",
  "privilegeError": "Jūsų vartotojo rolė negali vykdyti analizės. Kad galėtumėte atlikti analizę, jūsų organizacijos administratorius turi jums suteikti tam tikras <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">teises</a>.",
  "noServiceError": "Aukščių analizės paslauga nepasiekiama. Peržiūrėkite savo ArcGIS Online organizacijos arba Portal for ArcGIS konfigūracijas.",
  "pointToolTooltip": "Spustelėkite norėdami pridėti stebėtojo vietą",
  "degreesLabel": "laipsniai",
  "milsLabel": "mylios",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "Laipsniai, Minutės, Sekundės",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Dešimtainiai laipsniai – platuma / ilguma",
  "DDLongLatNotation": "Dešimtainiai laipsniai – ilguma / platuma",
  "DDMLatLongNotation": "Dešimtainių laipsnių minutės – platuma / ilguma",
  "DDMLongLatNotation": "Dešimtainių laipsnių minutės – ilguma / platuma",
  "DMSLatLongNotation": "Dešimtainių laipsnių sekundės – platuma / ilguma",
  "DMSLongLatNotation": "Dešimtainių laipsnių sekundės – ilguma / platuma",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - dažnio raidė",
  "UTMHemNotation": "UTM – pusrutulis (Š/P)"
});