define({
  "defaultAreaUnit": "Noklusējuma laukuma vienība",
  "defaultLengthUnit": "Noklusējuma garuma vienība",
  "acres": "Akri",
  "sqMiles": "Kv. jūdzes",
  "sqKilometers": "Kv. kilometri",
  "hectares": "Hektāri",
  "sqYards": "Kv. jardi",
  "sqFeet": "Kv. pēdas",
  "sqMeters": "Kv. metri",
  "miles": "Jūdzes",
  "kilometers": "Kilometri",
  "feet": "Pēdas",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Jūras jūdzes",
  "showArea": "Laukums",
  "showDistance": "Distance",
  "showLocation": "Izvietojums",
  "showtools": "Rādīt mērīšanas rīkus:",
  "allHidedTips": "Ir jāatlasa vismaz viens rīks."
});