define({
  "searchTabTitle": "Pretraži postavku izvora",
  "routeTabTitle": "Postavka rute",
  "add": "Dodaj izvor pretrage",
  "addGeocoder": "Dodaj geokoder",
  "geocoder": "Geokoder",
  "setLayerSource": "Postavi izvor sloja",
  "setGeocoderURL": "Postavi URL adresu geokodera",
  "searchableLayer": "Sloj geoobjekata",
  "name": "Naziv",
  "countryCode": "Kôd(ovi) zemlje ili regiona",
  "countryCodeEg": "npr. ",
  "countryCodeHint": "Ako ova vrednost ostane prazna, pretražuju se sve zemlje i regioni",
  "showInfoWindowOnSelect": "Prikaži iskačući prozor za pronađeni geoobjekat ili lokaciju",
  "showInfoWindowOnSelect2": "Prikaži iskačući prozor kada se pronađe geoobjekat ili lokacija.",
  "searchInCurrentMapExtent": "Pretraži samo u trenutnom obuhvatu mape",
  "setSearchFields": "Postavi polja pretrage",
  "set": "Postavi",
  "fieldSearchable": "pretraživo",
  "zoomScale": "Skala zumiranja",
  "locatorUrl": "URL adresa geokodera",
  "locatorName": "Ime geokodera",
  "locatorExample": "Primer",
  "locatorWarning": "Ova verzija servisa geokodiranja nije podržana. Vidžet podržava servis geokodiranja 10.1 i novije.",
  "locatorTips": "Predlozi nisu dostupni jer servis geokodiranja ne podržava predloženu mogućnost.",
  "layerSource": "Izvor sloja",
  "searchLayerTips": "Predlozi nisu dostupni jer servis geoobjekata ne podržava mogućnost paginacije.",
  "placeholderText": "Tekst čuvara mesta",
  "searchFields": "Polja za pretragu",
  "displayField": "Prikaži polje",
  "exactMatch": "Potpuno podudaranje",
  "maxSuggestions": "Maksimalno predloga",
  "maxResults": "Maksimalno rezultata",
  "enableLocalSearch": "Omogući lokalnu pretragu",
  "minScale": "Min. razmera",
  "minScaleHint": "Kada je razmera mape veća od ove razmere, primenjuje se lokalna pretraga",
  "radius": "Poluprečnik",
  "radiusHint": "Definiše poluprečnik oblasti oko trenutnog centra mape koja se koristi za poboljšavanje rangiranja kandidata za geokodiranje kako bi se prvo vraćali kandidati najbliži lokaciji",
  "invalidUrlTip": "URL adresa ${URL} nije validna ili nije dostupna.",
  "routeUrl": "URL adresa usmeravanja",
  "geocoderOptions": "Opcije geokodera",
  "autoComplete": "Automatsko popunjavanje",
  "maximumSuggestions": "Maksimalno predloga",
  "minCharacters": "Minimalno karaktera",
  "searchDelay": "Odlaganje pretrage",
  "placeholder": "Čuvar mesta",
  "routeOptions": "Opcije usmeravanja",
  "directionsLanguage": "Jezik uputstava",
  "directionsLengthUnits": "Jedinice dužine u uputstvima za navigaciju",
  "directionsOutputType": "Tip izlaznih rezultata uputstva za navigaciju",
  "impedanceAttribute": "Atributi otpora",
  "kilometers": "Kilometri",
  "miles": "Milje",
  "meters": "Metri",
  "feet": "Stope",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "parametersTip": "Pravilno postavite parametre!",
  "complete": "Završi",
  "completeNoEvents": "Završi bez događaja",
  "instructionsOnly": "Samo instrukcije",
  "standard": "Standardna verzija",
  "summaryOnly": "Samo rezime",
  "travelModesUrl": "URL adresa režima putovanja",
  "searchPlaceholder": "Pronađi adresu ili mesto",
  "trafficLayerUrl": "URL adresa sloja saobraćaja",
  "barrierLayerUrl": "URL adresa barijere",
  "presetDestinations": "Unapred podešena zaustavljanja",
  "startPoint": "Početna tačka",
  "endPoint": "Krajnja tačka",
  "destinationHolder": "Adresa ili koordinate",
  "optional": "Opcionalno.",
  "barrierLayers": "Slojevi barijere",
  "pointBarrier": "Tačkaste barijere",
  "lineBarrier": "Linijske barijere",
  "polygonBarrier": "Poligonalne barijere",
  "noPointBarrier": "Izaberite tačkaste barijere",
  "noLineBarrier": "Izaberite linijske barijere",
  "noPolygonBarrier": "Izaberite poligonalne barijere"
});