define({
  "_widgetLabel": "Distància i direcció",
  "tabLineTitle": "Línia",
  "tabCircleTitle": "Cercle",
  "tabEllipseTitle": "El·lipse",
  "tabRingsTitle": "Anells",
  "multipleNotationsMessage": " notacions que coincideixen amb la vostra entrada. Confirmeu quina voleu utilitzar:",
  "invalidCoordinateMessage": "Coordenada no vàlida",
  "confirmInputNotationMessage": "Confirma la notació d'entrada",
  "prefixSuffixMessage": "S'ha detectat que la coordenada d'entrada té un prefix i un sufix pel valor de la latitud o la longitud, i la coordenada retornada es basa en el prefix.",
  "rememberDecisionMessage": "Recorda la meva decisió i no m'ho tornis a preguntar.<br/>",
  "majorAxisTooltipMessage": "Feu clic a la longitud de l'eix major",
  "minorAxisTooltipMessage": "Torneu el ratolí a la posició inicial per definir l'eix menor i acabar de dibuixar l'el·lipse",
  "clickToFinishLineMessage": "Feu clic per acabar de dibuixar la línia",
  "doubleClickEllipseMesage": "Feu doble clic per acabar de dibuixar els anells de l'interval",
  "invalidCoordinateTypeMessage": "No es pot determinar el tipus de coordenada d'entrada. Comproveu l'entrada",
  "noCenterPointSetMessage": "No s'ha definit cap punt central. Comproveu l'entrada",
  "ellipseMajorAxis": "Eix major",
  "ellipseMinorAxis": "Eix menor",
  "degreesRangeMessage": "El valor ha d'estar comprès entre 0 i 360",
  "millsRangeMessage": "El valor ha d'estar comprès entre 0 i 6.400",
  "lengthLabel": "Longitud",
  "angleLabel": "Angle",
  "startPointLabel": "Punt inicial",
  "endPointLabel": "Punt final",
  "centerPointLabel": "Punt central",
  "distanceTableErrorMessage": "La taula de distància és buida. Assegureu-vos d'introduir algunes distàncies.",
  "setCoordFormatStringMessage": "Defineix la cadena de format de coordenades",
  "prefixMessage": "Afegeix el prefix \"+/-\" als nombres positius i negatius",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Graus decimals: latitud/longitud",
  "DDLongLatNotation": "Graus decimals: longitud/latitud",
  "DDMLatLongNotation": "Graus minuts decimals: latitud/longitud",
  "DDMLongLatNotation": "Graus minuts decimals: longitud/latitud",
  "DMSLatLongNotation": "Graus minuts segons: latitud/longitud",
  "DMSLongLatNotation": "Graus minuts segons: longitud/latitud",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM: lletra de banda",
  "UTMHemNotation": "UTM: hemisferi (N/S)",
  "circleTitle": "Crea un cercle des de",
  "radiusLabel": "Radi",
  "diameterLabel": "Diàmetre",
  "startPointPlaceHolderLabel": "Introduïu les coordenades",
  "formatInputLabel": "Entrada de format",
  "drawCircleLabel": "Dibuixa un cercle",
  "drawLineLabel": "Dibuixa una línia",
  "createCircleInteractivelyLabel": "Crea un cercle de manera interactiva",
  "rangeErrorMessage": "Radi o diàmetre no vàlid",
  "numericInvalidMessage": "Introduïu un valor numèric",
  "timeLabel": "Hora",
  "invalidTimeMessage": "Valor d'hora no vàlid",
  "hoursLabel": "Hores",
  "minutesLabel": "Minuts",
  "secondsLabel": "Segons",
  "rateLabel": "Velocitat",
  "invalidDistanceMessage": "Valor de distància no vàlid",
  "feetSecondsLabel": "Peus/segon",
  "feetHourLabel": "Peus/hora",
  "kmSecondLabel": "Quilòmetres/segon",
  "kmHourLabel": "Quilòmetres/hora",
  "metersSecondLabel": "Metres/segon",
  "metersHourLabel": "Metres/hora",
  "milesSecondLabel": "Milles/segon",
  "milesHourLabel": "Milles/hora",
  "nauticalMilesSecondLabel": "Milles nàutiques/segon",
  "nauticalMilesHourLabel": "Milles nàutiques/hora",
  "clearGraphicsLabel": "Esborra els gràfics",
  "ellipseTypeLabel": "Tipus d'el·lipse",
  "ellipseSemiLabel": "Semi",
  "ellipseFullLabel": "Completa",
  "drawEllipseLabel": "Dibuixa una el·lipse",
  "createEllipseInteractively": "Crea una el·lipse de manera interactiva",
  "axisLabel": "Eix",
  "unitLabel": "Unitat",
  "majorRadiusLabel": "Major (radi)",
  "majorDiameterLabel": "Major (diàmetre)",
  "axisErrorMessage": "El valor ha de ser més gran que 0",
  "minorRadiusLabel": "Menor (radi)",
  "minorDiameterLabel": "Menor (diàmetre)",
  "orientationLabel": "Orientació",
  "orientationErrorMessage": "El valor ha d'estar comprès entre 0 i 360",
  "warningMessage": "Avís: els gràfics que es generen amb l'eina d'el·lipse no són geodèsics",
  "fromLabel": "Des de",
  "distanceBearingLabel": "Distància i rumb",
  "pointsLabel": "Punts",
  "createLineInteractively": "Crea una línia de manera interactiva",
  "lineLengthErrorMessage": "Longitud de línia no vàlida",
  "degreesLabel": "Graus",
  "milsLabel": "Mil·liradians",
  "lineTypeLabel": "Tipus",
  "interactiveLabel": "Interactiva",
  "fixedLabel": "Fixa",
  "originLabel": "Origen",
  "cumulativeLabel": "Acumulativa",
  "numberOfRingsLabel": "Nombre d'anells",
  "ringsErrorMessage": "Nombre d'anells no vàlid",
  "distanceBetweenRingsLabel": "Distància entre els anells",
  "ringsDecimalErrorMessage": "Introduïu un valor numèric de fins a 2 decimals",
  "distanceUnitsLabel": "Unitats de distància",
  "distancesLabel": "Distàncies",
  "numberOfRadialsLabel": "Nombre de radials",
  "upLabel": "Amunt",
  "downLabel": "Avall",
  "deleteLabel": "Suprimeix",
  "radialsErrorMessage": "Nombre de radials no vàlid. El màxim permès és de 360",
  "radialsInvalidMessage": "Valor de radials no vàlid",
  "addPointLabel": "Afegeix un punt",
  "valueLabel": "Valor",
  "valueText": "Introduïu un valor",
  "actionLabel": "Acció",
  "distanceCalculatorLabel": "Calculadora de distància",
  "abbrevMetersLabel": "m",
  "abbrevFeetLabel": "ft",
  "abbrevKmLabel": "km",
  "abbrevMilesLabel": "mi",
  "abbrevYardsLabel": "yd",
  "abbrevNauticalMilesLabel": "nm",
  "abbrevDegreesLabel": "°",
  "abbrevMilsLabel": "mil",
  "abbrevHoursLabel": "h",
  "abbrevMinutesLabel": "min",
  "abbrevSecondsLabel": "s",
  "abbrevFeetSecondsLabel": "ft/s",
  "abbrevFeetHourLabel": "ft/h",
  "abbrevKmSecondLabel": "km/s",
  "abbrevKmHourLabel": "km/h",
  "abbrevMetersSecondLabel": "m/s",
  "abbrevMetersHourLabel": "m/h",
  "abbrevMilesSecondLabel": "mi/s",
  "abbrevMilesHourLabel": "mi/h",
  "abbrevNauticalMilesSecondLabel": "nm/s",
  "abbrevNauticalMilesHourLabel": "nm/h",
  "publishDDBtn": "Publica",
  "publishTitle": "Publica els gràfics",
  "ddLayerName": "Nom de la capa publicada",
  "missingDDLayerName": "Heu d'introduir un nom per a la capa",
  "publishToNewLayer": "Publica els resultats en una nova capa d'entitats",
  "checkService": "Comprova el servei: {0}",
  "createService": "Crea el servei: {0}",
  "unableToCreate": "No es pot crear: {0}",
  "addToDefinition": "Afegeix a la definició: {0}",
  "successfullyPublished": "S'ha publicat correctament la capa web{0}Administra la capa web",
  "userRole": "No es pot crear el servei perquè l'usuari no té permisos",
  "missingLayerNameMessage": "Heu d'introduir un nom de capa vàlid per poder fer la publicació",
  "invalidLayerName": "El nom de la capa només pot contenir caràcters alfanumèrics i de subratllat",
  "distanceLabel": "Distància",
  "radiusDistance": "Distància del radi",
  "radials": "Radials",
  "rings": "Anells",
  "orientationUnit": "Unitat d'orientació",
  "radiusUnit": "Unitat de radi",
  "angleUnitLabel": "Unitat d'angle"
});