define({
  "_widgetLabel": "Phân tích Mối đe dọa",
  "threatAnalysisMainPageTitle": "Dựa trên Hướng dẫn Chống khủng bố JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Vị trí đầu vào",
  "interactive": "Tương tác",
  "fromCoord": "Tọa độ cố định",
  "existingFeature": "Từ các đối tượng hiện tại",
  "threatAnalysisCoordInputLabel": "Vị trí Mối đe dọa",
  "enterCoords": "Nhập Tọa độ",
  "threatAddPointToolTip": "Thêm Vị trí Mối đe dọa",
  "threatDrawPointToolTip": "Bấm để thêm vị trí mối đe dọa",
  "threatType": "Loại Mối đe dọa",
  "threatPlaceholder": "Bắt đầu nhập để tìm kiếm mối đe dọa",
  "mandatoryLabel": "Khoảng cách Sơ tán Bắt buộc",
  "safeLabel": "Khoảng cách Sơ tán An toàn",
  "zoneTypeLabel": "Loại Khu vực",
  "feetLabel": "Feet",
  "metersLabel": "Mét",
  "unitsLabel": "Đơn vị",
  "threatGraphicLayer": "Đồ thị-Mối đe dọa",
  "settingsTitle": "Thiết lập",
  "mandatoryButtonLabel": "Cấu hình Thiết lập Khoảng cách Sơ tán Bắt buộc",
  "safeButtonLabel": "Cấu hình Thiết lập vị trí trú ẩn tại chỗ",
  "style": "Kiểu",
  "lineStyles": {
    "esriSLSDash": "Gạch",
    "esriSLSDashDot": "Chấm Gạch",
    "esriSLSDashDotDot": "Gạch Chấm Chấm",
    "esriSLSDot": "Chấm",
    "esriSLSLongDash": "Nét đứt dài",
    "esriSLSLongDashDot": "Chấm đứt dài",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Nét đứt ngắn",
    "esriSLSShortDashDot": "Chấm đứt ngắn",
    "esriSLSShortDashDotDot": "Hai chấm đứt ngắn",
    "esriSLSShortDot": "Chấm ngắn",
    "esriSLSSolid": "Đậm"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Về phía sau",
    "esriSFSCross": "Gạch ngang",
    "esriSFSDiagonalCross": "Chéo",
    "esriSFSForwardDiagonal": "Chuyển tiếp",
    "esriSFSHorizontal": "Ngang",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Đậm",
    "esriSFSVertical": "Dọc"
  },
  "resultsTitle": "Kết quả",
  "publishTABtn": "Xuất bản",
  "layerName": "Tên Lớp đã Xuất bản",
  "invalidLayerName": "Tên lớp chỉ được chứa các ký tự chữ số và dấu gạch dưới",
  "missingLayerName": "Bạn phải nhập tên cho lớp",
  "missingLayerNameMessage": "Bạn phải nhập tên lớp hợp lệ trước khi có thể xuất bản",
  "publishingFailedLayerExists": "Xuất bản không thành công: Bạn đã có dịch vụ đối tượng có tên {0}. Vui lòng chọn tên khác.",
  "checkService": "Kiểm tra Dịch vụ: {0}.",
  "createService": "Tạo Dịch vụ: {0}",
  "unableToCreate": "Không thể tạo: {0}",
  "addToDefinition": "Thêm vào định nghĩa: {0}",
  "successfullyPublished": "Xuất bản lớp web thành công{0}Quản lý lớp web",
  "userRole": "Không thể tạo dịch vụ do người dùng không có đủ quyền",
  "transparencyLabel": "Độ trong suốt",
  "outline": "Viền",
  "fill": "Tô đầy (Màu chỉ áp dụng khi kiểu được thiết lập thành dạng khối)",
  "createBtn": "Tạo Vùng",
  "clearBtn": "Xóa",
  "invalidNumberMessage": "Giá trị đã nhập không hợp lệ",
  "invalidRangeMessage": "Giá trị phải lớn hơn 0",
  "parseCoordinatesError": "Không thể phân tích tọa độ. Vui lòng kiểm tra thông tin đầu vào.",
  "manualCoordinateInputInfo": "Nhập tọa độ thủ công và nhấp vào <b>Enter</b> để thu phóng",
  "pipeBombLabel": "Bom ống",
  "suicideBombLabel": "Bom tự sát",
  "briefcaseLabel": "Cặp tài liệu",
  "carLabel": "Xe ô tô",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Xe tải giao hàng nhỏ",
  "containerWaterTruckLabel": "Container/Xe tưới nước",
  "semiTrailerLabel": "Xe bán tải",
  "selectDrawModeLabel": "Chọn Chế độ Vẽ",
  "selectFeatureLabel": "Chọn Đối tượng từ Lớp này"
});