define({
  "_widgetLabel": "Verkon jäljitys",
  "_featureAction_NetworkTraceSkip": "Ohita kohta seurannassa",
  "_featureAction_NetworkTraceUnskip": "Poista ohitettavista sijainneista",
  "removedFromSkipLocations": "Poistettu ohitettavista sijainneista",
  "alreadyRemovedFromSkipLocations": "On jo poistettu ohitettavista sijainneista",
  "locationSkipped": "Sijainti on ohitettu",
  "configError": "Pienoisohjelmaa ei ole määritetty oikein.",
  "geometryServiceURLNotFoundMSG": "Geometriapalvelun URL-osoitetta ei voi noutaa",
  "clearButtonValue": "Tyhjennä",
  "GPExecutionFailed": "Jäljitystä ei voi tehdä loppuun. Yritä uudelleen.",
  "backButtonValue": "Edellinen",
  "exportToCSVSuccess": "Vienti CSV-muotoon onnistui.",
  "lblInputLocTab": "Lähtöaineiston sijainnit",
  "lblBlockLocTab": "Lohkosijainnit",
  "lblInputLocation": "Lähtöaineiston kohde",
  "lblBlockLocation": "Lohkokohde",
  "lblInputLocHeader": "Lähtöaineiston sijainnit (0)",
  "lblBlockLocHeader": "Lohkosijainnit (0)",
  "inputTabTitle": "Lähtöaineisto",
  "outputTabTitle": "Tulosaineisto",
  "exportSelectAllCheckBoxLabel": "Valitse kaikki",
  "lblSkipLocHeader": "Ohitussijainnit (0)",
  "lblSkipLocation": "Sijainti",
  "lblSkipLocTab": "Ohitussijainnit",
  "skipAllLocationButtonLabel": "Ohita kaikki sijainnit",
  "confirmSkipAllLocationsMessage": "Kaikki sijainnit ohitetaan. Haluatko jatkaa?",
  "locationAlreadySkippedMessage": "Sijainti on jo ohitettu",
  "removeAllSkipLocationLabel": "Poista kaikki",
  "newProjectOptionText": "Uusi projekti",
  "selectProject": "Valitse projekti",
  "saveButtonLabel": "Tallenna",
  "exportToCSVText": "Vie CSV-tiedostoon",
  "editProjectAttributesToolTip": "Muokkaa projektin ominaisuustietoja",
  "projectNameLabel": "Projektin nimi",
  "saveProjectPopupTitle": "Tallenna",
  "saveAsLabel": "Tallenna nimellä",
  "saveChangesMsg": "Haluatko tallentaa projektiin <b>${loadProjectDropdownlabel}</b> tekemäsi muutokset vai tallentaa ne uutena projektina?",
  "creatingNewProjectErrorMessage": "Virhe uuden projektin luonnissa. Yritä uudelleen.",
  "projectNameFetchingErr": "Virhe noudettaessa aiemmin luotujen projektien nimiä. Yritä uudelleen.",
  "projectAttributeLoadingErr": "Virhe ladattaessa projektin ominaisuustietoja. Yritä uudelleen.",
  "attributeUpdatedMsg": "Ominaisuustietojen päivitys onnistui.",
  "projectAttributeUpdatingErr": "Virhe päivitettäessä projektin ominaisuustietoja.",
  "loadingProjectDetailsErrorMessage": "Virhe noudettaessa lippuja, esteitä ja ohitussijainteja. Yritä uudelleen.",
  "savingProjectDetailsErr": "Virhe tallennettaessa projektin tietoja. Yritä tallentaa projekti uudelleen.",
  "updatingOutagePolygonErr": "Virhe päivitettäessä katkon aluekohdetta. Yritä tallentaa projekti uudelleen.",
  "deletingExistingPolygonErr": "Virhe poistettaessa aiemmin luotua katkon aluekohdetta. Yritä tallentaa projekti uudelleen.",
  "loadingProjectFeaturesErr": "Virhe ladattaessa projektin kohteita. Yritä ladata projekti uudelleen.",
  "addingProjectFeaturesErr": "Virhe lisättäessä projektin kohteita. Yritä tallentaa projekti uudelleen.",
  "deletingExistingProjectFeaturesErr": "Virhe poistettaessa aiemmin luotuja projektin kohteita. Yritä tallentaa projekti uudelleen.",
  "projectNotFoundErr": "Projektia ei löydy",
  "projectLayersNotFound": "Määritetyt projektiasetusten karttatasot eivät ole käytettävissä kartassa. Pienoisohjelma ladataan luonnostelutilassa.",
  "fetchingOutagePolygonMessage": "Virhe noudettaessa katkon aluekohdetta. Yritä ladata projekti uudelleen.",
  "projectNameExistsMessage": "Projektin nimi on jo olemassa. Käytä yksilöllistä projektin nimeä.",
  "fetchingProjectNamesErrorMessage": "Virhe noudettaessa aiemmin luotujen projektien nimiä. Yritä tallentaa projekti uudelleen.",
  "enterProjectNameMessage": "Anna projektin nimi.",
  "projectLengthErrorMessage": "Projektin nimi ei voi olla suurempi kuin",
  "gpServiceNotAccessible": "Tililläsi ei ole käyttöoikeutta pakolliseen palveluun tämän jäljityksen suorittamista varten.",
  "loadingClonedLayerErrorMessage": "Virhe ladattaessa kloonattua kohdekarttatasoa. Yritä uudelleen.",
  "addingFeatureInClonedLayerError": "Virhe lisättäessä grafiikkaa kloonattuun kohdekarttatasoon. Yritä uudelleen.",
  "selectingFeatureInClonedLayerError": "Virhe valittaessa grafiikkaa kloonatusta kohdekarttatasosta. Yritä uudelleen.",
  "filteredProjectError": "Virhe tarkistettaessa noudettavia suodatettuja projektitietoja. Yritä uudelleen.",
  "filteredProjectMessage": "Valitut projektin ominaisuustiedot eivät ole käytettävissä web-kartassa tai toisessa pienoisohjelmassa käytettyjen suodattimien takia. Tyhjennä suodattimet ja yritä uudelleen.",
  "filteredProjectLoadMessage": "Projektisi ei ole enää käytettävissä. Valitse aktiivinen projekti.",
  "defaultValueForRunButton": "Suorita",
  "closeButtonLabel": "Poista"
});