define({
  "_widgetLabel": "Rajzolás",
  "selectDrawMode": "Rajzolási mód kiválasztása",
  "clear": "Törlés",
  "point": "Pont",
  "line": "Vonal",
  "polyline": "Polyline",
  "freehandPolyline": "Szabadkézi vonallánc",
  "triangle": "Háromszög",
  "extent": "Befoglaló téglalap",
  "circle": "Kör",
  "ellipse": "Ellipszis",
  "polygon": "Polygon",
  "freehandPolygon": "Szabadkézi sokszög",
  "text": "Szöveg",
  "style": "Stílus",
  "alpha": "Átlátszóság",
  "width": "Szélesség",
  "size": "Méret",
  "color": "Szín",
  "markerColor": "Jelölőszín",
  "outlineColor": "Kontúrszín",
  "lineColor": "Vonalszín",
  "fillColor": "Kitöltőszín",
  "showMeasurements": "Méretek megjelenítése",
  "showLocationMeasurement": "Helyszínmérések megjelenítése",
  "showAreaMeasurement": "Területmérés megjelenítése",
  "showDistanceMeasurement": "Távolságmérés megjelenítése",
  "showDistanceMeasurementForLine": "Hosszmérések megjelenítése",
  "showDistanceMeasurementForPolygon": "Kerületmérések megjelenítése",
  "locationToggleOn": "A helyszínmérések megjelenítéséhez nyomjon a váltógombra",
  "locationToggleOff": "A helyszínmérések elrejtéséhez nyomjon a váltógombra",
  "areaToggleOn": "A területmérések megjelenítéséhez nyomjon a váltógombra",
  "areaToggleOff": "A területmérések elrejtéséhez nyomjon a váltógombra",
  "distanceForLineToggleOn": "A hosszmérések megjelenítéséhez nyomjon a váltógombra",
  "distanceForLineToggleOff": "A hosszmérések elrejtéséhez nyomjon a váltógombra",
  "distanceForPolygonToggleOn": "A peremmérések megjelenítéséhez nyomjon a váltógombra",
  "distanceForPolygonToggleOff": "A peremmérések elrejtéséhez nyomjon a váltógombra",
  "areaUnits": "Terület mértékegységek",
  "distanceUnits": "Távolság-mértékegységek",
  "kilometers": "kilométer",
  "miles": "mérföld",
  "meters": "méter",
  "feet": "láb",
  "yards": "yard",
  "nauticalmiles": "tengeri mérföld",
  "squareKilometers": "négyzetkilométer",
  "squareMiles": "négyzetmérföld",
  "acres": "acre",
  "hectares": "hektár",
  "squareMeters": "négyzetméter",
  "squareFeet": "négyzetláb",
  "squareYards": "négyzetyard",
  "undo": "Visszavonás",
  "redo": "Újra",
  "results": "Eredmények",
  "points": "Pontok",
  "lines": "Vonalak",
  "areas": "Területek",
  "locationLabel": "Helyszín: ${value}",
  "areaLabel": "Terület: ${value} ${unit}",
  "distanceLabel": "Távolság: ${value} ${unit}",
  "distanceLabelForLine": "Hossz: ${value} ${unit}",
  "distanceLabelForPolygon": "Kerület: ${value} ${unit}"
});