define({
  "enableUndoRedo": "Активувати функцію «Відмінити/повторити»",
  "toolbarVisible": "Панель інструментів видима",
  "toolbarOptions": "Опції панелі інструментів",
  "mergeVisible": "Об’єднати",
  "cutVisible": "Вирізати",
  "reshapeVisible": "Змінити форму",
  "back": "Назад",
  "label": "Шар",
  "edit": "Редагований",
  "update": "Деактивувати оновлення геометрії",
  "fields": "Поля",
  "actions": "Дії",
  "editpageName": "Назва",
  "editpageAlias": "Псевдонім",
  "editpageVisible": "Видимий",
  "editpageEditable": "Редагований",
  "noLayers": "Редаговані векторні шари недоступні",
  "configureFields": "Налаштувати поля шару",
  "useFilterEdit": "Використовувати фільтр шаблону об'єкту",
  "display": "Відображати",
  "autoApplyEditWhenGeometryIsMoved": "Автоматично застосувати редагування при переміщенні геометрії",
  "snappingTolerance": "Задати допуск замикання в пікселях",
  "popupTolerance": "Задати допуск спливаючого вікна редагування атрибуту в пікселях",
  "stickyMoveTolerance": "Задати допуск переміщення курсору в пікселях",
  "usingSaveButton": "Не застосовувати редагування до атрибутів, поки не буде натиснуто кнопку «Зберегти»",
  "generalSettings": "Загальні налаштування",
  "editableLayersSetting": "Налаштування редагованих шарів",
  "honorTheWebMapSetting": "Перевага налаштувань у веб-карті",
  "honorTheWebMapSettingTip1": "Ці налаштування включають:",
  "honorTheWebMapSettingTip2": "Які шари є редагованими",
  "honorTheWebMapSettingTip3": "Поля, які потрібно відобразити та редагувати",
  "honorTheWebMapSettingTip4": "Псевдонім, порядок та формат поля",
  "customSettings": "Налаштування користувача"
});