define({
  "serviceUrl": "Service-URL festlegen:",
  "minIntSpacingLabel": "Mindestabstand zwischen Intervallen",
  "lineOpacityLabel": "Linientransparenz",
  "labelOpacityLabel": "Beschriftungstransparenz",
  "centerLabelOpacityLabel": "Transparenz der mittigen Beschriftung",
  "gridZonePlacementLabel": "Platzierung der Gitter-Zonenbeschriftung",
  "verticalLineLabels": "Beschriftungen für vertikale Linien",
  "styleHeaderLabel": "Style",
  "indexHeaderLabel": "Index",
  "colorHeaderLabel": "Farbe",
  "fontSizeHeaderLabel": "Schriftgröße",
  "lineWidthHeaderLabel": "Linienbreite",
  "horizontalLabel": "Horizontal",
  "verticalLabel": "Vertikal",
  "upperLeftLabel": "Oben links",
  "upperRightLabel": "Oben rechts",
  "lowerLeftLabel": "Unten links",
  "lowerRightLabel": "Unten rechts",
  "centerLabel": "Zentriert"
});