define({
  "symbolologyTabLabel": "Konfigureeri sümboloogia",
  "facilitiesDescription": "Rajatisekihid",
  "demographicsDescription": "Demograafiateabe kiht",
  "settingsTitle": "Sätted",
  "spillLocationLabel": "Saastumiskoht",
  "spillLocationButtonLabel": "Konfigureeri saastumiskoha sätted",
  "IISettingsLabel": "Algne isolatsioonitsoon",
  "IIButtonLabel": "Konfigureeri algse isoleerimise sätted",
  "PASettingsLabel": "Kaitsetoimingute tsoon",
  "PAButtonLabel": "Konfigureeri kaitsetoimingute sätted",
  "downwindSettingsLabel": "Allatuuletsoon",
  "downwindButtonLabel": "Konfigureeri allatuulesätted",
  "fireSettingsLabel": "Tuleisolatsiooni tsoon",
  "fireButtonLabel": "Konfigureeri tuleisolatsiooni sätted",
  "bleveSettingsLabel": "BLEVE isolatsiooni tsoon",
  "bleveButtonLabel": "Konfigureeri BLEVE sätted",
  "transparency": "Läbipaistvus",
  "outline": "Äärejoon",
  "fill": "Täida (värv rakendatakse ainult juhul, kui valitud on pidev laad)",
  "style": "Stiil",
  "selectOpLayerLabel": "Vali tulemuste töökiht",
  "selectDefaultMeasurementLabel": "Vali vaikimisi mõõtühik",
  "helpIconTooltip": "Töökihtide nimekiri sisaldab kihte praeguselt veebikaardilt, mis on polügooni tüüpi.",
  "colorPicker": "Värvi valimine",
  "lineStyles": {
    "esriSLSDash": "Katkendlik",
    "esriSLSDashDot": "Katkendlik punktiga",
    "esriSLSDashDotDot": "Katkendlik kahe punktiga",
    "esriSLSDot": "Punktiir",
    "esriSLSLongDash": "Pikk katkendlik kriips",
    "esriSLSLongDashDot": "Pikk katkendlik kriips punktiga",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Lühike katkendlik kriips",
    "esriSLSShortDashDot": "Lühike katkendlik kriips punktiga",
    "esriSLSShortDashDotDot": "Lühike katkendlik kriips kahe punktiga",
    "esriSLSShortDot": "Lühike punktiir",
    "esriSLSSolid": "Pidev"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Tagasi",
    "esriSFSCross": "Rist",
    "esriSFSDiagonalCross": "Diagonaal",
    "esriSFSForwardDiagonal": "Edasi",
    "esriSFSHorizontal": "Horisontaalne",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Pidev",
    "esriSFSVertical": "Vertikaalne"
  }
});