define({
  root: ({
    _widgetLabel: "Network Trace",
    _featureAction_NetworkTraceSkip: "Skip in Trace",
    _featureAction_NetworkTraceUnskip: "Remove from skip locations",
    removedFromSkipLocations: "Removed from skip locations",
    alreadyRemovedFromSkipLocations: "Already removed from skip locations",
    locationSkipped: "Location skipped",
    configError: "Widget is not properly configured.",
    geometryServiceURLNotFoundMSG: "Unable to get Geometry Service URL",
    clearButtonValue: "Clear",
    GPExecutionFailed: "The trace cannot be completed. Please try again.",
    backButtonValue: "Back",
    exportToCSVSuccess: "Export to CSV is successfully completed.",
    lblInputLocTab: "Input Locations",
    lblBlockLocTab: "Block Locations",
    lblInputLocation: "Input Feature",
    lblBlockLocation: "Block Feature",
    lblInputLocHeader: "Input Locations (0)",
    lblBlockLocHeader: "Block Locations (0)",
    inputTabTitle: "Input",
    outputTabTitle: "Output",
    exportSelectAllCheckBoxLabel:"Select All",
    lblSkipLocHeader: "Skip Locations (0)",
    lblSkipLocation: "Location",
    lblSkipLocTab: "Skip Locations",
    skipAllLocationButtonLabel: "Skip All Locations",
    confirmSkipAllLocationsMessage: "All the locations will be skipped, do you want to continue?",
    locationAlreadySkippedMessage: "Location already skipped",
    removeAllSkipLocationLabel: "Remove All",
    newProjectOptionText: "New Project",
    selectProject: "Select Project",
    saveButtonLabel: "Save",
    exportToCSVText: "Export To CSV",
    editProjectAttributesToolTip: "Edit Project Attributes",
    projectNameLabel : "Project Name",
    saveProjectPopupTitle : "Save",
    saveAsLabel : "Save As",
    saveChangesMsg : "Want to save your changes to <b>${loadProjectDropdownlabel}</b> or save as new project?",
    creatingNewProjectErrorMessage: "Error while creating new project. Please try again.",
    projectNameFetchingErr: "Error while fetching existing project names. Please try again.",
    projectAttributeLoadingErr: "Error while loading project attributes. Please try again.",
    attributeUpdatedMsg: "Attributes updated successfully.",
    projectAttributeUpdatingErr: "Error while updating project attributes.",
    loadingProjectDetailsErrorMessage: "Error while fetching flags, barriers and skip locations. Please try again.",
    savingProjectDetailsErr: "Error while saving project details. Please try saving project again.",
    updatingOutagePolygonErr: "Error while updating outage polygon. Please try saving project again.",
    deletingExistingPolygonErr: "Error while deleting existing outage polygon. Please try saving project again.",
    loadingProjectFeaturesErr: "Error while loading project features. Please try loading project again.",
    addingProjectFeaturesErr: "Error while adding project features. Please try saving project again.",
    deletingExistingProjectFeaturesErr: "Error while deleting existing project features. Please try saving project again.",
    projectNotFoundErr: "Project not found",
    projectLayersNotFound: "Configured Project settings layers are not available in map. Widget will be loaded in 'Sketch mode'.",
    fetchingOutagePolygonMessage: "Error while fetching outage polygon. Please try loading project again.",
    projectNameExistsMessage: "Project name already exists. Please use unique project name.",
    fetchingProjectNamesErrorMessage: "Error while fetching existing project names. Please try saving project again.",
    enterProjectNameMessage: "Please enter project name.",
    projectLengthErrorMessage: "Project name cannot be greater than",
    gpServiceNotAccessible: "Your account does not have access to the required service to preform this trace.",
    loadingClonedLayerErrorMessage: "Error while loading the cloned feature layer. Please try again.",
    addingFeatureInClonedLayerError: "Error while adding the graphics into cloned feature layer. Please try again.",
    selectingFeatureInClonedLayerError: "Error while selecting the graphics in cloned feature layer. Please try again.",
    filteredProjectError: "Error while checking fetching filtered project details. Please try again.",
    filteredProjectMessage: "Selected project attributes are not available due to the applied filters from the webmap or another widget. Clear the filter(s) and try again.",
    filteredProjectLoadMessage: "Your project is no longer available. Please select an active project.",
    defaultValueForRunButton: "Run",
    closeButtonLabel: "Remove"
  }),
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
