define({
  "_widgetLabel": "Smart-redigering",
  "_featureAction_SmartEditor": "Smart-redigering",
  "noEditPrivileges": "Din konto har ikke rettigheder til at oprette eller redigere data.",
  "widgetActive": "Aktiv",
  "widgetNotActive": "Ikke aktiv",
  "pressStr": "Tryk ",
  "ctrlStr": " CTRL ",
  "snapStr": " for at aktivere snapping",
  "noAvailableTempaltes": "Ingen tilgængelige skabeloner",
  "editorCache": " - Editor-cache",
  "presetFieldAlias": "Mark",
  "presetValue": "Foruddefineret værdi",
  "usePresetValues": " Brug foruddefinerede værdier (kun for nye objekter)",
  "editGeometry": " Redigér geometri",
  "savePromptTitle": "Gem objekt",
  "savePrompt": "Vil du gemme det aktuelle objekt?",
  "deletePromptTitle": "Slet objekt",
  "deleteAttachment": "Slet vedhæftning",
  "deletePrompt": "Er du sikker på, at du vil slette det valgte objekt?",
  "attachmentLoadingError": "Fejl ved overførsel af vedhæftninger",
  "attachmentSaveDeleteWarning": "Advarsel: Ændringer i vedhæftninger gemmes automatisk",
  "autoSaveEdits": "Gemmer automatisk nyt objekt",
  "addNewFeature": "Opret et nyt objekt",
  "featureCreationFailedMsg": "Kan ikke oprette en ny post/et nyt objekt",
  "relatedItemTitle": "Tilknyttede tabeller/lag",
  "relatedFeatureCount": "${layerTitle} med ${featureCount} objekter",
  "createNewFeatureLabel": "Opret et nyt objekt for ${layerTitle}",
  "invalidRelationShipMsg": "Kontrollér, at det primære nøglefelt: '${parentKeyField}' har en gyldig værdi",
  "pendingFeatureSaveMsg": "Gem ændringerne i objektet, før du opretter et tilknyttet objekt.",
  "attachmentsRequiredMsg": "(*) Vedhæftninger er påkrævet.",
  "coordinatePopupTitle": "Flyt objekt til XY-placering",
  "coordinatesSelectTitle": "Koordinatsystem:",
  "mapSpecialReferenceDropdownOption": "Kort-spatial reference",
  "latLongDropdownOption": "Breddegrad/længdegrad",
  "xAttributeTextBoxLabel": "X-koordinat:",
  "yAttributeTextBoxLabel": "Y-koordinat:",
  "latitudeTextBoxLabel": "Bredde:",
  "longitudeTextBoxLabel": "Længde:",
  "presetGroupFieldsLabel": "'${groupName}' anvendes på følgende lagfelter:",
  "presetGroupNoFieldsLabel": "'${groupName}' har ikke nogen tilknyttede felter",
  "groupInfoLabel": "Gruppeoplysninger for '${groupName}'",
  "editGroupInfoIcon": "Rediger gruppeværdi for ${groupName}",
  "filterEditor": {
    "all": "Alle",
    "noAvailableTempaltes": "Ingen tilgængelige skabeloner",
    "searchTemplates": "Søgeskabeloner",
    "filterLayerLabel": "Filtrér lag"
  },
  "invalidConfiguration": "Widget'en er enten ikke konfigureret, eller lagene i konfigurationen findes ikke længere i kortet. Åbn app'en i builder-tilstand, og omkonfigurér widget'en.",
  "geometryServiceURLNotFoundMSG": "Kan ikke hente geometritjeneste-URL",
  "clearSelection": "Ryd",
  "refreshAttributes": "Opdatér objekters attributter",
  "automaticAttributeUpdatesOn": "Automatisk opdatering af objekters attributter: TIL",
  "automaticAttributeUpdatesOff": "Automatisk opdatering af objekters attributter: FRA",
  "moveSelectedFeatureToGPS": "Flyt det valgte objekt til den aktuelle GPS-placering",
  "moveSelectedFeatureToXY": "Flyt det valgte objekt til XY-placering",
  "mapNavigationLocked": "Kortnavigation: låst",
  "mapNavigationUnLocked": "Kortnavigation: ulåst",
  "copyFeatures": {
    "title": "Kopiér objekter",
    "createFeatures": "Opret objekter",
    "createSingleFeature": "Opret 1 Multigeometri-objekt",
    "noFeaturesSelectedMessage": "Ingen funktioner valgt",
    "selectFeatureToCopyMessage": "Vælg de objekter, der skal kopieres.",
    "multipleFeatureSaveWarning": "Bemærk: Hvis du opretter flere objekter ved at kopiere dem, gemmes alle objekterne med det samme."
  },
  "addingFeatureError": "Fejl under tilføjelse af valgte objekter i laget. Prøv igen.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' objekter kunne ikke kopieres.",
  "selectingFeatureError": "Fejl under valg af objekter i laget. Prøv igen.",
  "customSelectOptionLabel": "Vælg objekter, der skal kopieres",
  "noFeatureSelectedMessage": "Ingen funktioner valgt.",
  "multipleFeatureSaveMessage": "Alle objekterne vil blive gemt med det samme. Vil du fortsætte?",
  "relativeDates": {
    "dateTypeLabel": "Datotype",
    "valueLabel": "Værdi",
    "fixed": "Fast",
    "current": "Aktuelt",
    "past": "Tidligere",
    "future": "Fremtidig",
    "popupTitle": "Vælg værdi",
    "hintForFixedDateType": "Tip: Den angivne dato og det angivne klokkeslæt bruges som forudindstillet standardværdi",
    "hintForCurrentDateType": "Tip: Den aktuelle dato og det aktuelle klokkeslæt bruges som forudindstillet standardværdi",
    "hintForPastDateType": "Tip: Den angivne værdi trækkes fra den aktuelle dato og det aktuelle klokkeslæt for at give standardværdien for forudindstilling.",
    "hintForFutureDateType": "Tip: Den angivne værdi lægges til den aktuelle dato og det aktuelle klokkeslæt for at give standardværdien for forudindstilling.",
    "noDateDefinedTooltip": "Ingen dato er defineret"
  }
});