define({
  "taskUrl": "Taak-URL",
  "serviceURLPlaceholder": "Voer de URL van de geoprocessingtaak in",
  "layerOrder": "Laagvolgorde",
  "defaultValue": "Standaardwaarde",
  "inputFeatureBy": "Invoerobject op",
  "inputRecordBy": "Invoer record door",
  "renderer": "Renderer",
  "displayType": "Weeergavetype",
  "helpUrl": "Help-URL",
  "useResultMapService": "Bekijk resultaat met een map service",
  "drawOnMap": "Interactief tekenen op de kaart",
  "selectLayer": "Een kaartlaag selecteren vanaf de kaart",
  "selectTable": "Een tabel selecteren vanaf de kaart",
  "shareResults": "Resultaat toevoegen als operationele laag",
  "setTask": "Instellen",
  "setTaskTitle": "GP-taak instellen",
  "enablePopup": "Pop-up inschakelen",
  "unSupportGeometryType": "Kan geen renderer instellen vanwege onbekend geometrietype.",
  "useUrlForGPInput": ".URL",
  "useUploadForGPInput": "Bestand uploaden",
  "selectFileToUpload": "Bestand selecteren...",
  "rasterFormat": "Bestandsformaat rooster",
  "noFileSelected": "Geen bestand geselecteerd!",
  "uploadSuccess": "Bestand güpload!",
  "showLayerContent": "Content van de laag weergeven",
  "urlPlaceholder": "Link voor toegang tot de gegevens",
  "useShapefile": "Gebruik shapefile in het lokale bestandssysteem",
  "allowToExport": "Resultaten exporteren",
  "useDynamicSchema": "Uitvoer kan ander schema hebben, gebruik dynamisch schema in plaats van voorgedefinieerd.",
  "useCurrentMapExtent": "Huidig kaartextent gebruiken",
  "ignoreOutput": "Deze uitvoer negeren",
  "turnOffOutput": "Deze laag standaard uitschakelen",
  "inputJSONString": "Invoer JSON-tekst"
});