define({
  "taskUrl": "URL adresa zadatka",
  "serviceURLPlaceholder": "Unesite URL adresu zadatka geoprocesiranja",
  "layerOrder": "Redosled sloja",
  "defaultValue": "Podrazumevana vrednost",
  "inputFeatureBy": "Unos geoobjekata po",
  "inputRecordBy": "Unesite zapis po",
  "renderer": "Prikazivač",
  "displayType": "Tip prikaza",
  "helpUrl": "URL adresa pomoći",
  "useResultMapService": "Prikaži rezultat pomoću servisa mape",
  "drawOnMap": "Interaktivno crtajte na mapi",
  "selectLayer": "Izaberite sloj sa mape",
  "selectTable": "Izaberite tabelu sa mape",
  "shareResults": "Dodaj rezultate kao operativni sloj",
  "setTask": "Postavi",
  "setTaskTitle": "Postavi zadatak GP",
  "enablePopup": "Omogući iskačuće prozore",
  "unSupportGeometryType": "Ne može da postavi renderovanje zbog nepoznatog geometrijskog tipa.",
  "useUrlForGPInput": "URL adresa",
  "useUploadForGPInput": "Otpremi datoteku",
  "selectFileToUpload": "Izaberite datoteku...",
  "rasterFormat": "Format rasterskih podataka",
  "noFileSelected": "Nema izabrane datoteke!",
  "uploadSuccess": "Datoteka uspešno otpremljena!",
  "showLayerContent": "Prikaži sadržaj sloja",
  "urlPlaceholder": "URL adresa za pristup podacima",
  "useShapefile": "Koristite datoteku „shapefile“ u lokalnom sistemu datoteka",
  "allowToExport": "Dozvoli izvoz rezultata",
  "useDynamicSchema": "Izvoz može da ima različitu šemu, koristite dinamičnu šemu umesto predefinisane.",
  "useCurrentMapExtent": "Koristi trenutni obuhvat mape",
  "ignoreOutput": "Zanemari ovaj izlazni rezultat",
  "turnOffOutput": "Podrazumevano isključi ovaj sloj",
  "inputJSONString": "Unesite JSON nisku"
});