define({
  root: ({
    searchTabTitle: "Search source setting",
    routeTabTitle: "Route setting",

    add: "Add search source",
    addGeocoder: "Add geocoder",
    geocoder: "Geocoder",
    setLayerSource: "Set layer source",
    setGeocoderURL: "Set geocoder URL",
    searchableLayer: "Feature layer",
    name: "Name",
    countryCode: "Country or region code(s)",
    countryCodeEg: "e.g. ",
    countryCodeHint: "Leaving this value blank will search all countries and regions",
    showInfoWindowOnSelect: "Show pop-up for the found feature or location",
    showInfoWindowOnSelect2: "Show pop-up when the feature or location is found.",
    searchInCurrentMapExtent: "Only search in current map extent",
    setSearchFields: "Set search fields",
    set: "Set",
    fieldSearchable: "searchable",
    zoomScale: "Zoom scale",
    locatorUrl: "Geocoder URL",
    locatorName: "Geocoder name",
    locatorExample: "Example",
    locatorWarning: "This version of geocoding service is not supported. The widget supports geocoding service 10.1 and above.",
    locatorTips: "Suggestions are not available because the geocoding service doesn't support suggest capability.",
    layerSource: "Layer source",
    searchLayerTips: "Suggestions are not available because the feature service doesn't support pagination capability.",
    placeholderText: "Placeholder text",
    searchFields: "Search fields",
    displayField: "Display field",
    exactMatch: "Exact match",
    maxSuggestions: "Maximum suggestions",
    maxResults: "Maximum results",
    enableLocalSearch: "Enable local search",
    minScale: "Min scale",
    minScaleHint: "When the map scale is larger than this scale, local search will be applied",
    radius: "Radius",
    radiusHint: "Specifies the radius of an area around current map center that is used to boost the rank of geocoding candidates so that candidates closest to the location are returned first",
    invalidUrlTip: "The URL ${URL} is invalid or inaccessible.",
 
    routeUrl: "Route URL",
    locatorUrl: "Geocoder URL",
    geocoderOptions: "Geocoder options",
    autoComplete: "Autocomplete",
    maximumSuggestions: "Maximum suggestions",
    minCharacters: "Minimum characters",
    searchDelay: "Search delay",
    placeholder: "Placeholder",
    routeOptions: "Route options",
    directionsLanguage: "Directions language",
    directionsLengthUnits: "Directions length units",
    directionsOutputType: "Directions output type",
    impedanceAttribute: "Impedance attribute",
    kilometers: "Kilometers",
    miles: "Miles",
    meters: "Meters",
    feet: "Feet",
    yards: "Yards",
    nauticalMiles: "Nautical miles",
    parametersTip: "Please set parameters correctly !",
    complete: "Complete",
    completeNoEvents: "Complete No Events",
    instructionsOnly: "Instructions only",
    standard: "Standard",
    summaryOnly: "Summary only",
    travelModesUrl: "Travel modes URL",
    searchPlaceholder: "Find address or place",
    trafficLayerUrl: "Traffic layer URL",
    barrierLayerUrl: "Barrier layer URL",
    presetDestinations: "Preset stops",
    startPoint: "Start point",
    endPoint: "End point",
    destinationHolder:"Address or coordinates",
    optional: "Optional.",

    barrierLayers: "Barrier Layers",
    pointBarrier: "Point barriers",
    lineBarrier: "Line barriers",
    polygonBarrier: "Polygon barriers",
    noPointBarrier: "Select point barriers",
    noLineBarrier: "Select line barriers",
    noPolygonBarrier: "Select polygon barriers"
  }),
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
