define({
  "_widgetLabel": "Vészhelyzeti tevékenységi útmutató",
  "ergMainPageTitle": "Az Emergency Response Guidebook 2016 kiadvány alapján",
  "coordInputLabelStart": "Kifolyás helye (DD)",
  "coordInputLabel": "Kifolyás helye",
  "addPointToolTip": "Kifolyás helyének hozzáadása",
  "drawPointToolTip": "Kattintson ide a kifolyási hely hozzáadásához",
  "material": "Anyag",
  "materialPlaceholder": "Kezdje el a beírást az anyag kereséséhez",
  "table3Message": "A kiválasztott anyaghoz további információkra van szükség, ha nagy kifolyást kezel.\n\nEllenőrizze, hogy helyes értékeket adott-e meg a szélsebességnél és a szállítókonténernél.",
  "table2Message": "A kiválasztott anyag nagy mennyiségű mérgező gázt bocsáthat ki, ha vízzel keveredik.\n\nA következő anyag(ok) használatát célszerű megfontolnia:\n\n",
  "spillSize": "Kifolyás mérete",
  "small": "Kicsi",
  "large": "Nagy",
  "fireLabel": "Tűz izolációs zóna megjelenítése",
  "weatherLabel": "Aktuális időjárás a kifolyás helyén",
  "weatherIntialText": "<br />Frissül, amikor sikerül a kiömlés helyének meghatározása",
  "temperature": "Hőmérséklet",
  "wind": "Szél",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "Nincsenek lekért időjárási adatok. Frissítse egyénileg a szélsebesség és a kiömlés idejének értékét",
  "windDirection": "Szélirány (amerre fúj)",
  "timeOfSpill": "Kiömlés ideje",
  "day": "Nappal",
  "night": "Éjszaka",
  "windSpeed": "Szél sebessége",
  "low": "Alacsony",
  "moderate": "Mérsékelt",
  "high": "Magas",
  "transportContainer": "Szállítókonténer",
  "rail": "Vasúti tartálykocsi",
  "semi": "Közúti tartálykocsi vagy tréler",
  "mton": "Többtonnás hengeres tartály",
  "ston": "Több kis hengeres tartály vagy egy tonnás hengeres tartály",
  "ag": "Mezőgazdasági hígtrágya szórótartály",
  "msm": "Több kis hengeres tartály",
  "bleveLabel": "BLEVE izolációs zóna megjelenítése",
  "capacity": "Konténer kapacitása (liter)",
  "bleveMessage": "A kiválasztott anyagnál egy további evakuálási távolság jeleníthető meg a BLEVE esetében.\n\nEnnek engedélyezéséhez állítsa Be értékűre a BLEVE izolációs zóna megjelenítése beállítást, és válassza ki megfelelő konténerkapacitást.",
  "noPAZoneMessage": "Ennél az anyagnál nincsenek védelmizóna-távolságok. Csak az első izoláció zónája és az evakuálási zóna számítható ki",
  "settingsTitle": "Beállítások",
  "spillLocationLabel": "Kifolyás helye",
  "spillLocationButtonLabel": "Kifolyás helyére vonatkozó beállítások konfigurálása",
  "IISettingsLabel": "Első izolációs zóna",
  "IIButtonLabel": "Első izolációs zóna beállításainak konfigurálása",
  "PASettingsLabel": "Védelmi műveletek zónája",
  "PAButtonLabel": "Védelmi műveletekre vonatkozó beállítások konfigurálása",
  "downwindSettingsLabel": "Szélárnyékos zóna",
  "downwindButtonLabel": "Széllel ellentétes (szélárnyékos) oldal beállításainak konfigurálása",
  "fireSettingsLabel": "Tűzzáró zóna",
  "fireButtonLabel": "Tűzzáró zóna beállításainak konfigurálása",
  "bleveSettingsLabel": "BLEVE izolációs zóna",
  "bleveButtonLabel": "BLEVE beállításainak konfigurálása",
  "style": "Stílus",
  "lineStyles": {
    "esriSLSDash": "Szaggatott",
    "esriSLSDashDot": "Vonal-pont",
    "esriSLSDashDotDot": "Vonal-pont-pont",
    "esriSLSDot": "Pont",
    "esriSLSLongDash": "Hosszú vonal",
    "esriSLSLongDashDot": "Hosszú vonal-pont",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Rövid vonal",
    "esriSLSShortDashDot": "Rövid vonal-pont",
    "esriSLSShortDashDotDot": "Rövid vonal-pont-pont",
    "esriSLSShortDot": "Rövid pont",
    "esriSLSSolid": "Folytonos"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Hátra",
    "esriSFSCross": "Kereszt",
    "esriSFSDiagonalCross": "Átlós",
    "esriSFSForwardDiagonal": "Előre",
    "esriSFSHorizontal": "Vízszintes",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Folytonos",
    "esriSFSVertical": "Függőleges"
  },
  "resultsTitle": "Eredmények",
  "publishERGBtn": "Közzététel",
  "ERGLayerName": "Közzétett ERG-réteg neve",
  "invalidERGLayerName": "A réteg neve csak alfanumerikus karaktereket és aláhúzás karaktereket tartalmazhat",
  "missingERGLayerName": "Meg kell adnia az ERG nevét",
  "publishingFailedLayerExists": "Sikertelen közzététel: Már van {0} nevű vektoros szolgáltatás. Válasszon másik nevet.",
  "checkService": "Szolgáltatás ellenőrzése: {0}",
  "createService": "Szolgáltatás létrehozása: {0}",
  "unableToCreate": "Nem lehet létrehozni: {0}",
  "addToDefinition": "Hozzáadás a meghatározáshoz: {0}",
  "successfullyPublished": "A(z) {0} webes réteg sikeresen közzétéve. Kezelje a webes réteget",
  "userRole": "Nem lehet létrehozni a szolgáltatást, mert a felhasználónak nincs megfelelő engedélye",
  "transparency": "Átlátszóság",
  "outline": "Körvonal",
  "fill": "Kitöltés (a Szín beállítás csak az egyszínű stílus beállítása esetén érhető el)",
  "createERGBtn": "Zónák létrehozása",
  "clearERGBtn": "Törlés",
  "labelFormat": "Felirat formátuma",
  "helpIconTooltip": "A kis- és a nagyméretű kiömlések közötti határérték:\nFolyadékok – 208 liter (55 gallon)\nSzilárd anyagok – 300 kilogramm (60 font)",
  "cellWidth": "Cella szélessége (x)",
  "cellHeight": "Cella magassága (y)",
  "invalidNumberMessage": "A megadott érték nem érvényes",
  "invalidRangeMessage": "Az értéknek 0-nál nagyobbnak kell lennie",
  "gridAngleInvalidRangeMessage": "Az értéknek -89,9 és 89,9 között kell lennie",
  "formatIconTooltip": "Formátumbemenet",
  "setCoordFormat": "Koordináta-formátum beállítása",
  "prefixNumbers": "A „+/-” előtag hozzáadása a pozitív és negatív számok jelöléséhez",
  "cancelBtn": "Mégse",
  "applyBtn": "Alkalmaz",
  "comfirmInputNotation": "Bemeneti jelölés megerősítése",
  "notationsMatch": "jelölés felel meg a bemenetnek. Pontosítsa, hogy melyiket szeretné használni:",
  "missingLayerNameMessage": "Meg kell adnia egy érvényes rétegnevet a közzététel előtt",
  "parseCoordinatesError": "Nem sikerült a koordináták elemzése. Ellenőrizze a bevitt adatokat.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Tized fokok - szélesség/hosszúság",
  "DDLongLatNotation": "Tizedes fokok - hosszúság/szélesség",
  "DDMLatLongNotation": "Fokok és tized fokpercek - szélesség/hosszúság",
  "DDMLongLatNotation": "Fokok és tized fokpercek - szélesség/hosszúság",
  "DMSLatLongNotation": "Fokok, fokpercek és fokmásodpercek - szélesség/hosszúság",
  "DMSLongLatNotation": "Fokok, fokpercek és fokmásodpercek - hosszúság/szélesség",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - sávbetűjel",
  "UTMHemNotation": "UTM - félteke (É/D)"
});