define({
  "tabs_section_Label": "tabbladen",
  "addTab": "Tabblad toevoegen",
  "layerName": "Kaartlaag",
  "layerType": "Analysetype",
  "layerLabel": "Label",
  "actions": "Acties",
  "closest": "Dichtstbijzijnde object",
  "proximity": "Nabijheid",
  "summary": "Samenvatting",
  "select_lbl": "-- Selecteren --",
  "general_setting_Label": "Algemene instellingen",
  "units_text_lbl": "Afstandseenheden",
  "maximum_distance_lbl": "Dichtstbijzijnde object maximale afstand",
  "buffer_text_lbl": "Bufferlabel",
  "buffer_lbl": "Bufferafstand",
  "buffer_max_lbl": "Maximale bufferafstand",
  "buffer_min_lbl": "Minimale bufferafstand",
  "routing_checkBox": "Routeren inschakelen",
  "weather_Label": "Weeropties",
  "weather_checkBox": "Weerberichten opnemen",
  "selectLayers": "Weerlagen selecteren",
  "currentlySelectedLayer": "Momenteel geselecteerde weerlagen",
  "missingTabLabel": "Er ontbreekt minstens één label in het tabblad",
  "missingLayerInWebMap": "Geen operationele lagen gevonden.",
  "selectFields": "Velden selecteren",
  "addField": "Veld toevoegen",
  "sum": "Som",
  "min": "Minimum",
  "max": "Maximum",
  "avg": "Gemiddelde",
  "count": "TELLEN",
  "area": "GEBIED",
  "length": "LENGTE",
  "count_checkBox": "Objecttelling weergeven",
  "area_checkBox": "Totale oppervlakte weergeven",
  "length_checkBox": "Totale lengte weergeven",
  "max_records": "Maximumlimiet bereikt",
  "save_label": "Opties opslaan",
  "save_checkbox": "Opslaan activeren",
  "csv_label": "Resultaten exporteren",
  "csv_checkbox": "Alle velden in de laag exporteren.",
  "display_label": "Weergaveopties",
  "display_checkbox": "Samenvatting objecten weergeven",
  "snapshot_label": "Snapshotopties",
  "snapshot_checkbox": "Snapshot inschakelen",
  "must_select_template": "Selecteer één van de bewerkingsjablonen in Opties opslaan.",
  "count_label": "Tellinglabel",
  "area_label": "Gebiedlabel",
  "length_label": "Lengtelabel",
  "invalid_string_width": "De waarde is te lang. ",
  "layer_type_not_supported": "Laagtype wordt niet ondersteund: ",
  "groupedSummary": "Gegroepeerde telling",
  "groupByField": "Groeperen per veld",
  "labelType": "Label toevoegen",
  "prefix": "Als voorvoegsel",
  "suffix": "Als achtervoegsel",
  "need_group_field": "Gebruik de actie Bewerken om Groeperen per veld te definiëren.",
  "fieldTitle": "Veld",
  "typeTitle": "Type",
  "actionsTitle": "Acties",
  "save_point_checkbox": "Punten opslaan",
  "save_line_checkbox": "Lijnen opslaan",
  "save_poly_checkbox": "Polygonen opslaan",
  "no_valid_popup_fields": "Geen geldige velden in de pop-up. Gebruik de actie bewerking om een veld te definiëren.",
  "no_valid_fields": "Geen geldige velden. Gebruik de actie bewerking om weergave-opties te definiëren.",
  "incident_label": "Tabbladlabel",
  "locate_incident_label": "Interessegebiedlabel",
  "incident": "Incident",
  "locate_incident": "Incident zoeken",
  "buffer_value": "Bufferafstand"
});