define(
   ({
    _widgetLabel: "Situationsbewusstsein",
    locate_incident: "Ereignis verorten",
    clear_incidents: "Ereignisse löschen",
    reverse_geocoded_address: "Nächstgelegene Adresse",
    reverse_geocoded_error: "Nicht verfügbar",
    miles: "Meilen",
    kilometers: "Kilometer",
    feet: "Fuß",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Seemeilen",
    now: "JETZT",
    wind: "WIND",
    SUN: "SO",
    MON: "MO",
    TUE: "DI",
    WED: "MI",
    THU: "DO",
    FRI: "FR",
    SAT: "SA",
    defaultTabMsg: "Definieren Sie einen Ereignisbereich.",
    actionLabel: "Als Ereignis festlegen",
    drawPoint: "Punkt zeichnen",
    drawLine: "Linie zeichnen",
    drawPolygon: "Polygon zeichnen",
    saveIncident: "Ereignis speichern",
    clearIncident: "Ereignis löschen",
    useMapExtent: "Die aktuelle Kartenausdehnung verwenden",
    noFeaturesFound: "Keine Features gefunden.",
    downloadCSV: "CSV HERUNTERLADEN",
    editComplete: "Feature wurde erfolgreich gespeichert.",
    updateComplete: "Feature wurde erfolgreich aktualisiert.",
    deleteComplete: "Feature wurde erfolgreich gelöscht.",
    sum: "SUMME",
    min: "MINIMUM",
    max: "MAXIMUM",
    avg: "DURCHSCHNITT",
    count: "ANZAHL",
    area: "FLÄCHE",
    length: "LÄNGE",
    notPolySave: "Geben Sie vor dem Speichern eine Pufferentfernung an.",
    update_btn: "Fertig",
    delete_btn: "Löschen",
    get_directions: "Wegbeschreibung abrufen",
    incident: "Ereignis",
    weather: "Wetter"
  })
);
