define({
  "_widgetLabel": "Okos szerkesztő",
  "_featureAction_SmartEditor": "Okos szerkesztő",
  "noEditPrivileges": "A fiókja nem teszi lehetővé az adatok létrehozását vagy módosítását.",
  "widgetActive": "Aktív",
  "widgetNotActive": "Nem aktív",
  "pressStr": "Nyomja meg a ",
  "ctrlStr": " CTRL ",
  "snapStr": " billentyűt a hozzáillesztés engedélyezéséhez",
  "noAvailableTempaltes": "Nincsenek elérhető sablonok",
  "editorCache": " - Szerkesztő gyorsítótára",
  "presetFieldAlias": "Mező",
  "presetValue": "Előre beállított érték",
  "usePresetValues": " Előre beállított értékek használata (csak új vektoros elemekhez)",
  "editGeometry": " Geometria szerkesztése",
  "savePromptTitle": "Vektoros elem mentése",
  "savePrompt": "Szeretné menteni az aktuális vektoros elemet?",
  "deletePromptTitle": "Vektoros elem törlése",
  "deletePrompt": "Biztosan törli a kiválasztott vektoros elemet?",
  "attachmentLoadingError": "Hiba a csatolmányok feltöltésekor",
  "attachmentSaveDeleteWarning": "Figyelmeztetés: A csatolmányok módosításai automatikusan mentésre kerülnek",
  "autoSaveEdits": "Automatikusan menti az új vektoros elemet",
  "addNewFeature": "Új vektoros elem létrehozása",
  "featureCreationFailedMsg": "Nem lehet új rekordot/vektoros elemet létrehozni",
  "relatedItemTitle": "Kapcsolt tábla/réteg",
  "invalidRelationShipMsg": "Győződjön meg arról, hogy az elsődleges kulcs '${parentKeyField}' mezőjében érvényes érték szerepel",
  "pendingFeatureSaveMsg": "Mentse a vektoros elem módosításait, mielőtt kapcsolt vektoros elemet hoz létre.",
  "attachmentsRequiredMsg": "(*) A csatolmányok megadása kötelező.",
  "coordinatePopupTitle": "A vektoros elem áthelyezése XY helyszínre",
  "coordinatesSelectTitle": "Koordináta-rendszer:",
  "mapSpecialReferenceDropdownOption": "Térkép koordináta-rendszere",
  "latLongDropdownOption": "Hosszúság/szélesség",
  "xAttributeTextBoxLabel": "X-koordináta:",
  "yAttributeTextBoxLabel": "Y-koordináta:",
  "latitudeTextBoxLabel": "Szélesség:",
  "longitudeTextBoxLabel": "Hosszúság:",
  "filterEditor": {
    "all": "Mind",
    "noAvailableTempaltes": "Nincsenek elérhető sablonok",
    "searchTemplates": "Sablonok keresése"
  },
  "invalidConfiguration": "A widget nincs konfigurálva, vagy a konfigurációban lévő rétegek már nem szerepelnek a térképen. Nyissa meg az alkalmazást építő módban, és konfigurálja újra a widgetet.",
  "geometryServiceURLNotFoundMSG": "Nem sikerült meghatározni a geometriai adatszolgáltatás URL-címét",
  "clearSelection": "Törlés",
  "refreshAttributes": "Vektoroselem-attribútumok frissítése",
  "automaticAttributeUpdatesOn": "A vektoros elemek attribútumainak frissítése: BE",
  "automaticAttributeUpdatesOff": "A vektoros elemek attribútumainak frissítése: KI",
  "moveSelectedFeatureToGPS": "A kijelölt vektoros elem áthelyezése az aktuális GPS helyszínre",
  "moveSelectedFeatureToXY": "A kijelölt vektoros elem áthelyezése XY helyszínre",
  "mapNavigationLocked": "Térképnavigáció: zárolva",
  "mapNavigationUnLocked": "Térképnavigáció: engedélyezve"
});