define(
   ({
    addLayer: "เพิ่มชั้นข้อมูล",
    layerName: "ชั้นข้อมูล",
    layerRefresh: "รีเฟรช",
    layerLabel: "ป้ายชื่อ",
    actions: "การดำเนินการ",
    popupOk: "ตกลง",
    popupCancel: "ยกเลิก",
    mainPanelTextPlaceholder: "อดีต : ทางหลวง",
    invalidInterval: "สนับสนุนเฉพาะค่าที่เป็นตัวเลขเท่านั้น",
    uploadImage: "อัพโหลดรูปภาพ",
    iconColumnText: "ไอค่อน",
    refreshInterval: "1 การประเมินเวลาเป็นนาที",
    refreshIntervalTitle: "การประเมินเวลาเป็นนาที",
    mainPanelText: "ข้อความหลัก",
    mainPanelIcon: "รูปภาพหลัก",
    refreshIntervalInstruction: "ระยะห่างการรีเฟรช",
    optionsText: "ตัวเลือก",
    symbolOptionsText: "การกำหนดสัญลักษณ์",
    iconOptionsText: "การกำหนดไอค่อน",
    sympolPopupTitle: "ตั้งค่าสัญลักษณ์",
    rdoLayer: "สัญลักษณ์ชั้นข้อมูล",
    rdoCustom: "จัดสัญลักษณ์เอง",
    chkCluster: "เปิดใช้งานคลัสเตอร์",
    defineClusterSymbol: "จัดสัญลักษณ์คลัสเตอร์",
    defineThemeClusterSymbol: "จัดสัญลักษณ์คลัสเตอร์จากธีม",
    rdoEsri: "สัญลักษณ์อีเอสอาร์ไอ",
    rdoLayerIcon: "ใช้สัญลักษณ์แทนไอค่อน",
    rdoCustomIcon: "อัพโหลดไอค่อนเฉพาะ",
    editCustomSymbol: "แก้ไขสัญลักษณ์เฉพาะ",
    editCustomIcon: "แก้ไขไอค่อนเฉพาะ",
    missingRefreshValue: "เตรียมรีเฟรสค่าที่ห่างเท่ากัน",
    panelIconOption: "แสดงผลส่วนหัวเพจ",
    enableRefresh: "เปิดการใช้งานการรีเฟรชชั้นข้อมูล",
    disableRefresh: "การรีเฟรชชั้นข้อมูลสนับสนุนฉพาะการรวบรวมชิ้นข้อมูลเท่านั้น",
    layer_type_not_supported: "ประเภทชั้นข้อมูลไม่รองรับ "
  })
);
