define({
  "enableUndoRedo": "Aktiver Angre/Gjenta",
  "toolbarVisible": "Verktøylinje synlig",
  "toolbarOptions": "Verktøylinjealternativer",
  "mergeVisible": "Slå sammen",
  "cutVisible": "Klipp ut",
  "reshapeVisible": "Omforme",
  "back": "Bak",
  "label": "Lag",
  "edit": "Redigerbar",
  "update": "Deaktiver geometrioppdatering",
  "fields": "Felter",
  "actions": "Handlinger",
  "editpageName": "Navn",
  "editpageAlias": "Alias",
  "editpageVisible": "Synlig",
  "editpageEditable": "Redigerbar",
  "noLayers": "Det er ingen redigerbare geoobjektlag tilgjengelig",
  "configureFields": "Konfigurer felter for lagene",
  "useFilterEdit": "Bruk geoobjektmal-filter",
  "display": "Vis",
  "autoApplyEditWhenGeometryIsMoved": "Bruk redigeringen automatisk når geometrien flyttes",
  "snappingTolerance": "Angi toleransen for festing i piksler",
  "popupTolerance": "Angi toleransen for attributtredigeringspopupen i piksler",
  "stickyMoveTolerance": "Angi toleransen for fast flytting i pisker"
});