define({
  "_widgetLabel": "Geoprocesiranje",
  "_featureAction_ReceiveFeatureSet": "Nastavi kot vnos od ",
  "requiredInfo": "je obvezno.",
  "drawnOnMap": "Rezultat je narisan na karti.",
  "noToolConfig": "Predkonfigurirane naloge geoprocesiranja niso na voljo.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Naloži datoteko",
  "selectFileToUpload": "Izberi datoteko...",
  "rasterFormat": "Format rastrskih podatkov",
  "noFileSelected": "Nobena datoteka ni izbrana!",
  "uploadSuccess": "Datoteka je uspešno naložena!",
  "showLayerContent": "Pokaži vsebino sloja",
  "invalidUrl": "Neveljaven url geoobjektne storitve",
  "urlPlaceholder": "URL za dostop do podatkov",
  "addShapefile": "Dodaj shapefile",
  "generateShapefileError": "Generirana je napaka shapefile, preverite: ",
  "cleared": "Rezultat je bil počiščen.",
  "enlargeView": "Povečaj pogled",
  "exportOutput": "Izvozi",
  "emptyResult": "Rezultat je prazen.",
  "useSelectedFeatureset": "Uporabi geoobjekte rezultant.",
  "closeSelectedFeatureset": "Počisti in uporabi možnost konfiguriranega vnosa.",
  "currentMapExtent": "Trenutni obseg karte",
  "generalize": "Posplošite geometrije",
  "jsonPlaceholder": "Niz JSON podatkov",
  "chooseATable": "---Izberi tabelo---"
});