define(
   ({
    addLayer: "Lägg till lager",
    layerName: "Lager",
    layerRefresh: "Uppdatera",
    layerLabel: "Etikett",
    actions: "Åtgärder",
    popupOk: "OK",
    popupCancel: "Appar",
    mainPanelTextPlaceholder: "Exempel: MOTORVÄGSFÖRHÅLLANDEN",
    invalidInterval: "Bara numeriska tecken är tillåtna.",
    uploadImage: "Överför bild",
    iconColumnText: "Ikon",
    refreshInterval: "1 ”Evalueras som tid i minuter”",
    refreshIntervalTitle: "Evalueras som tid i minuter",
    mainPanelText: "Huvudtext för panel",
    mainPanelIcon: "Huvudbild för panel",
    refreshIntervalInstruction: "Uppdateringsintervall",
    optionsText: "Alternativ",
    symbolOptionsText: "Symbolalternativ",
    iconOptionsText: "Ikonalternativ",
    sympolPopupTitle: "Ange symbol",
    rdoLayer: "Lagersymbol",
    rdoCustom: "Anpassad symbol",
    chkCluster: "Aktivera klustring",
    defineClusterSymbol: "Klustersymbol",
    defineThemeClusterSymbol: "Klustersymbol från tema",
    rdoEsri: "Esri-symbol",
    rdoLayerIcon: "Använd symbol som ikon",
    rdoCustomIcon: "Överför anpassad ikon",
    editCustomSymbol: "Redigera anpassad symbol",
    editCustomIcon: "Redigera anpassad ikon",
    missingRefreshValue: "Ange ett intervallvärde för när uppdatering ska ske.",
    panelIconOption: "Visa panelrubrik",
    enableRefresh: "Aktivera lageruppdatering",
    disableRefresh: "Lageruppdatering stöds bara för geoobjektssamlingar",
    layer_type_not_supported: "Lagertypen stöds inte: "
  })
);
