define({
  "addLayer": "Lägg till lager",
  "layerName": "Lager",
  "layerRefresh": "Uppdatera",
  "layerLabel": "Etikett",
  "actions": "Åtgärder",
  "mainPanelTextPlaceholder": "Exempel: Senast uppdaterat:",
  "invalidInterval": "Bara numeriska tecken är tillåtna.",
  "uploadImage": "Överför bild",
  "iconColumnText": "Visa",
  "refreshInterval": "Tid i minuter",
  "refreshIntervalTitle": "Evalueras som tid i minuter",
  "mainPanelText": "Huvudtext för panel",
  "mainPanelIcon": "Huvudbild för panel",
  "refreshIntervalInstruction": "Uppdatera lagren var",
  "optionsText": "Alternativ",
  "symbolOptionsText": "Kartsymbologi",
  "iconOptionsText": "Panelsymbologi",
  "sympolPopupTitle": "Visningsinställningar",
  "rdoLayer": "Standardsymbol",
  "rdoCustom": "Använd en bild",
  "chkCluster": "Aktivera klustring",
  "defineClusterSymbol": "Ange klustersymbol",
  "rdoEsri": "Välj en symbol",
  "rdoLayerIcon": "Använd kartsymbol",
  "rdoCustomIcon": "Använd en bild",
  "editCustomSymbol": "Redigera anpassad symbol",
  "editCustomIcon": "Redigera anpassad ikon",
  "missingRefreshValue": "Ange ett intervallvärde för när uppdatering ska ske.",
  "panelIconOption": "Visa logobild",
  "enableRefresh": "Aktivera lageruppdatering",
  "disableRefresh": "Lageruppdatering stöds bara för geoobjektssamlingar",
  "layer_type_not_supported": "Lagertypen stöds inte: ",
  "refreshUnit": "minut.",
  "symbolOptions": "Symbol",
  "panelFeatureDisplay": "Panel",
  "chkGroup": "Gruppera geoobjekt",
  "selectField": "Fält",
  "fieldLabel": "Etikett",
  "addField": "Lägg till fält",
  "featureOptionsText": "Lageralternativ",
  "groupOptionsText": "Gruppalternativ",
  "panelCountOption": "Visa geoobjektsantal",
  "rdoStack": "Visa ny rad för varje fält",
  "rdoAppend": "Bifoga fält på en enda rad",
  "missingLayerInWebMap": "Inga funktionslager hittades.",
  "displayClusterCnt": "Visa geoobjektsantal",
  "defineClusterFont": "Ange teckensnittsfärg",
  "max_records": "Maxgränsen för fält är nådd"
});