define({
  "addTaskTip": "Adjon hozzá egy vagy több szűrőt a widgethez, és konfigurálja a paramétereiket.",
  "enableMapFilter": "Előre beállított rétegszűrő eltávolítása a térképről.",
  "newFilter": "Új szűrő",
  "filterExpression": "Szűrőkifejezés",
  "layerDefaultSymbolTip": "A réteg alapértelmezett szimbólumának használata",
  "uploadImage": "Kép feltöltése",
  "selectLayerTip": "Válasszon ki egy réteget.",
  "setTitleTip": "Állítsa be a címet.",
  "noTasksTip": "Nincsenek beállítva szűrők. Kattintson a(z) „${newFilter}” gombra új szűrő hozzáadásához.",
  "collapseFiltersTip": "Szűrőkifejezések bezárása (ha vannak) a widget megnyitásakor",
  "zoomtoTip": "Nagyítás a rétegre a szűrő alkalmazásakor",
  "groupByLayerTip": "Szűrők csoportosítása réteg szerint",
  "autoApplyWhenValueInput": "Szűrő automatikus alkalmazása egy érték bevitele után",
  "autoApplyWhenWidgetOpen": "Szűrő alkalmazása a widget megnyitásakor",
  "info": "Információ",
  "expressions": "Kifejezések",
  "allowCustom": "Egyedi szűrők létrehozásának engedélyezése",
  "matchMsgSetAll": "Az összes szűrőnek megfelelő vektoros elemek megjelenítése",
  "matchMsgSetAny": "Bármelyik szűrőnek megfelelő vektoros elemek megjelenítése"
});