define({
  "_widgetLabel": "Svjesnost o situaciji",
  "locate_incident": "Pronađi incident",
  "clear_incidents": "Izbriši incidente",
  "reverse_geocoded_address": "Najbliža adresa",
  "reverse_geocoded_error": "Nije dostupno",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "now": "SADA",
  "wind": "VJETAR",
  "SUN": "NED",
  "MON": "PON",
  "TUE": "UTO",
  "WED": "SRI",
  "THU": "ČET",
  "FRI": "PET",
  "SAT": "SUB",
  "defaultTabMsg": "Definirajte područje incidenta.",
  "actionLabel": "Postavi kao incident",
  "drawPoint": "Nacrtaj točku",
  "drawLine": "Nacrtaj liniju",
  "drawPolygon": "Nacrtaj poligon",
  "saveIncident": "Spremi incident",
  "clearIncident": "Izbriši incident",
  "useMapExtent": "Upotrijebi trenutačni obuhvat karte",
  "noFeaturesFound": "Nema geoobjekata.",
  "downloadCSV": "PREUZMI CSV",
  "editComplete": "Geoobjekt uspješno spremljen.",
  "updateComplete": "Geoobjekt uspješno ažuriran.",
  "deleteComplete": "Geoobjekt uspješno izbrisan.",
  "sum": "ZBROJ",
  "min": "MIN.",
  "max": "MAKS.",
  "avg": "PROSJEK",
  "count": "BROJ",
  "area": "POVRŠINA",
  "length": "DULJINA",
  "notPolySave": "Odredite veličinu pojasa prije spremanja.",
  "update_btn": "Gotovo",
  "delete_btn": "Izbriši",
  "get_directions": "Dobivanje uputa za vožnju",
  "incident": "Incident",
  "weather": "Vrijeme",
  "poweredBy": "Omogućuje"
});