define({
  "chartSettingLabel": "Setări diagramă",
  "addNewLabel": "Adăugare nou",
  "generalSettingLabel": "Setări generale",
  "layerChooser": {
    "title": "Selectare strat tematic pentru diagramă",
    "selectPolygonLayerLabel": "Selectare strat tematic",
    "selectPolygonLayerHintText": "Sugestie: Dacă realizaţi configurarea mai multor diagrame, atunci straturile tematice trebuie să fie de acelaşi tip de geometrie",
    "selectRelatedTableLayerLabel": "Selectare tabel corelat stratului tematic",
    "selectRelatedTableLayerHintText": "Sugestie: Numai tabelele cu câmpuri numerice sunt afişate",
    "errorInSelectingPolygonLayer": "Vă rugăm să selectaţi un strat tematic care are un strat tematic de puncte corelat.",
    "errorInSelectingRelatedLayer": "Vă rugăm să selectaţi un tabel/strat tematic corelat stratului tematic.",
    "polygonLayerNotHavingRelationships": "Stratul tematic selectat nu are niciun tabel/strat tematic corelat."
  },
  "ChartSetting": {
    "sectionTitle": "Titlu secţiune",
    "sectionTitleHintText": "Sugestie: Afişat în titlul antetului secţiunii",
    "chartTitle": "Titlu diagramă",
    "chartTitleHintText": "Sugestie: Afişat centrat deasupra diagramei",
    "chartDescription": "Descriere",
    "chartDescriptionHintText": "Sugestie: Afişat sub diagramă",
    "chartType": "Tip diagramă",
    "barChart": "Diagramă cu bare",
    "pieChart": "Diagramă radială",
    "polarChart": "Diagramă polară",
    "dataSeriesField": "Câmp şiruri de date",
    "labelField": "Câmp etichetă",
    "chartColor": "Culoare diagramă",
    "singleColor": "O singură culoare",
    "colorByTheme": "Culoare în funcţie de temă",
    "colorByFieldValue": "Culoare în funcţie de valoarea câmpului",
    "xAxisTitle": "Titlu axa X",
    "xAxisHintText": "Sugestie: Titlu axa X",
    "yAxisTitle": "Titlu axa Y",
    "yAxisHintText": "Sugestie: Titlu axa Y",
    "fieldColorLabel": "Etichetă",
    "fieldColorColor": "Culoare",
    "defaultFieldSelectLabel": "Selectare",
    "errMsgFieldValuesNotFound": "Nu s-au putut găsi valori pentru câmpul selectat",
    "errMsgSectionTitle": "Vă rugăm să introduceţi un titlu de secţiune",
    "errMsgFieldByValue": "Vă rugăm să selectaţi valoarea câmpului",
    "settingTabTitle": "Configurare",
    "layoutTabTitle": "Configuraţie",
    "polarChartSelectFieldsHintText": "Sugestie: Selectaţi câmpurile pentru a genera diagrama polară",
    "visibilityText": "Vizibilitate",
    "fieldNameText": "Nume câmp",
    "aliasNameText": "Pseudonim",
    "errMsgPolarFieldsRequired": "Selectaţi trei sau mai multe câmpuri pentru a genera diagrama polară",
    "polarChartPolygonFillLabel": "Umplere poligon",
    "polarChartPolygonFillHintText": "Sugestie: Selectaţi caseta de bifare pentru a afişa umplerea poligonului în diagrama polară",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Deşert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irlanda",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Zonă umedă",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Setări generale",
    "locationSymbolLabel": "Simbol grafic locaţie",
    "locationSymbolHintText": "Sugestie: Utilizat pentru afişarea simbolului pentru adresă şi locaţia apăsării",
    "refreshIntervalLabel": "Interval de reîmprospătare",
    "refreshIntervalHintText": "Sugestie: Utilizat pentru reîmprospătarea diagramelor pe baza acestui interval. Specificaţi o valoare între 1 şi 1440 minute",
    "errMsgRefreshInterval": "Vă rugăm să specificaţi intervalul de reîmprospătare de la 0 la 1440 minute",
    "symbolPickerPreviewText": "Previzualizare:"
  }
});