define({
  "_widgetLabel": "Геообробка",
  "_featureAction_ReceiveFeatureSet": "Задати як введення ",
  "requiredInfo": "потрібно.",
  "drawnOnMap": "Результат відображається на карті.",
  "noToolConfig": "Попередньо налаштована задача геообробки недоступна.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Передати файл",
  "selectFileToUpload": "Вибрати файл...",
  "rasterFormat": "Формат растрових даних",
  "noFileSelected": "Файл не вибрано!",
  "uploadSuccess": "Файл успішно передано!",
  "showLayerContent": "Показати зміст шару",
  "invalidUrl": "Недійсний URL сервісу об'єктів",
  "urlPlaceholder": "URL для доступу до даних",
  "addShapefile": "Додати шейп-файл",
  "generateShapefileError": "Помилка генерування шейп-файлу, перевірте: ",
  "cleared": "Результат було видалено.",
  "enlargeView": "Збільшити вид",
  "exportOutput": "Експорт",
  "emptyResult": "Результат порожній.",
  "useSelectedFeatureset": "Використовувати підсумковий об'єкт(-и).",
  "closeSelectedFeatureset": "Очистити та використовувати налаштовану опцію введення.",
  "currentMapExtent": "Поточний екстент карти",
  "generalize": "Генералізувати геометрії",
  "jsonPlaceholder": "Рядок JSON даних",
  "chooseATable": "---Вибрати таблицю---"
});