define({
  "_widgetLabel": "Hotanalys",
  "threatAnalysisMainPageTitle": "Baseras på JCAT Counterterrorism Guide",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Plats för indata",
  "interactive": "Interaktiv",
  "fromCoord": "Fast koordinat",
  "existingFeature": "Från befintliga geoobjekt",
  "threatAnalysisCoordInputLabel": "Hotplats",
  "enterCoords": "Ange koordinater",
  "threatAddPointToolTip": "Lägg till hotplats",
  "threatDrawPointToolTip": "Klicka för att lägga till hotplats",
  "threatType": "Typ av hot",
  "threatPlaceholder": "Börja skriva för att söka efter ett hot",
  "mandatoryLabel": "Obligatorisk evakueringsdistans",
  "safeLabel": "Zon för katastrofskydd på plats",
  "zoneTypeLabel": "Zontyp",
  "feetLabel": "Fot",
  "metersLabel": "Meter",
  "unitsLabel": "Enheter",
  "settingsTitle": "Inställningar",
  "mandatoryButtonLabel": "Konfigurera inställningar för obligatorisk evakueringsdistans",
  "safeButtonLabel": "Konfigurera inställningar för katastrofskydd på plats",
  "style": "Format",
  "lineStyles": {
    "esriSLSDash": "Streck",
    "esriSLSDashDot": "Streck punkt",
    "esriSLSDashDotDot": "Streck punkt punkt",
    "esriSLSDot": "Punkt",
    "esriSLSLongDash": "Långt streck",
    "esriSLSLongDashDot": "Lång streck-punkt",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kort streck",
    "esriSLSShortDashDot": "Kort streck-punkt",
    "esriSLSShortDashDotDot": "Kort streck-punkt-punkt",
    "esriSLSShortDot": "Kort punkt",
    "esriSLSSolid": "Solid"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Bakåt",
    "esriSFSCross": "Kors",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Framåt",
    "esriSFSHorizontal": "Horisontell",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Solid",
    "esriSFSVertical": "Vertikal"
  },
  "resultsTitle": "Resultat",
  "publishTABtn": "Publicera",
  "layerName": "Publicerat lagernamn",
  "invalidLayerName": "Lagrets namn får endast innehålla alfanumeriska tecken och understreck",
  "missingLayerName": "Du måste ange ett namn för lagret",
  "missingLayerNameMessage": "Du måste ange ett giltigt lagernamn innan du kan publicera",
  "publishingFailedLayerExists": "Publiceringen misslyckades: Du har redan en geoobjekttjänst med namnet {0}. Välj ett annat namn.",
  "checkService": "Kontrollera tjänst: {0}",
  "createService": "Skapa tjänst: {0}",
  "unableToCreate": "Det gick inte att skapa: {0}",
  "addToDefinition": "Lägg till i definition: {0}",
  "successfullyPublished": "Webblagret har publicerats{0}Hantera webblagret",
  "userRole": "Det går inte att skapa tjänsten eftersom användaren inte har behörighet",
  "transparencyLabel": "Transparens",
  "outline": "Kontur",
  "fill": "Fyllningsfärg (Färgen tillämpas enbart när stilen anges till solid)",
  "createBtn": "Skapa zoner",
  "clearBtn": "Avmarkera",
  "invalidNumberMessage": "Det angivna värdet är ogiltigt",
  "invalidRangeMessage": "Värdet måste vara större än 0",
  "parseCoordinatesError": "Det gick inte att tolka koordinaterna. Kontrollera vad du skrivit."
});