define({
  "selectAnalysisTools": "Válassza ki a widgetben használni kívánt elemzési eszközöket.",
  "graphicalDisplay": "Grafikus megjelenítés",
  "toolSetting": "Eszköz részleteinek beállítása",
  "toolLabel": "Az eszköz megjelenített neve",
  "showHelpTip": "Súgóhivatkozások megjelenítése a widgetben",
  "showCurrentMapExtent": "Az aktuális térképkiterjedés használatára vonatkozó beállítás megjelenítése",
  "showCredits": "A <b>Készítők megjelenítése</b> beállítás mutatása",
  "saveAsFeatureService": "Az eredmény mentése a felhasználó fiókjában",
  "showReadyToUseLayers": "Használatra kész rétegek megjelenítése az ArcGIS Online valós idejű világatlaszából (Living Atlas)",
  "toolNotAvailable": "Ez az eszköz nem áll rendelkezésre, mert a térkép nem tartalmazza a szükséges rétegeket.",
  "aggregatePoints": "Pontok összevonása",
  "aggregatePointsUsage": "Pontok összevonása polygonná ahol a pont elhelyezkedik.",
  "calculateDensity": "Sűrűség számítása",
  "calculateDensityUsage": "Sűrűségtérkép létrehozása pont vagy vonal típusú vektoros elemekből egy adott jelenség térbeli eloszlásának ábrázolásával (a pontok vagy vonalak attribútumaiként).",
  "connectOriginsToDestinations": "Kiindulópontok összekapcsolása a célokkal",
  "connectOriginsToDestinationsUsage": "Pontpárok közötti utazási idő vagy távolság mérése.",
  "createBuffers": "Bufferek létrehozása",
  "createBuffersUsage": "Buffersokszögek létrehozása a vektoros elemekből álló bemenet alapján.",
  "createDriveTimeAreas": "Elérésiidő-térkép létrehozása",
  "createDriveTimeAreasUsage": "Elérési időnek (vagy elérési távolságnak) megfelelő polygonok létrehozása a bemeneti pontok körül a megadott elérési időértékek alapján.",
  "createViewshed": "Láthatóság kiértékelése",
  "createViewshedUsage": "Olyan területek létrehozása, amelyek az Ön által megadott helyekről láthatók.",
  "createWatersheds": "Vízgyűjtő területek létrehozása",
  "createWatershedsUsage": "Vízgyűjtő területek létrehozása az Ön által megadott helyek alapján.",
  "deriveNewLocations": "Új helyek származtatása",
  "deriveNewLocationsUsage": "A megadott lekérdezésnek megfelelő vektoros elemek származtatása a bemenő rétegek alapján",
  "dissolveBoundaries": "Határok összeolvasztása",
  "dissolveBoundariesUsage": "Az egymással átfedésben lévő, illetve közös határvonalon osztozó polygonok összeolvasztása.",
  "enrichLayer": "Rétegbővítés",
  "enrichLayerUsage": "A bemenő vektoros elemek bővítése személyekkel, helyekkel és üzleti adatokkal a közeli területekre vonatkozóan.",
  "extractData": "Adatkinyerés",
  "extractDataDesc": "Adatok kinyerése egy vagy több rétegből egy adott kiterjedésen belül",
  "findCentroids": "Centroidok keresése",
  "findCentroidsUsage": "Megkeresi minden egyes bemeneti multipoint, vonal vagy terület vektoros elem reprezentatív középpontját (centroid).",
  "findExistingLocations": "Meglévő helyek keresése",
  "findExistingLocationsUsage": "Adott attribútumnak és/vagy térbeli lekérdezésnek megfelelő vektoros elemek kijelölése a bemenő rétegen",
  "findHotSpots": "Hotspotok keresése",
  "findHotSpotsUsage": "Bemenő vektoros elemek vagy magas/alacsony értékek statisztikailag szignifikáns klasztereinek keresése.",
  "findNearest": "Legközelebbi keresése",
  "findNearestUsage": "Másik rétegen lévő legközelebbi vektoros elem keresése a bemenő réteg minden vektoros eleméhez",
  "findPointClusters": "Pontklaszterek keresése",
  "findPointClustersUsage": "Ez az eszköz azokat a területeket észleli, ahol a pontok koncentráltan helyezkednek el, és ahol üres vagy ritka területek választják el őket.",
  "findSimilarLocations": "Hasonló helyek keresése",
  "findSimilarLocationsUsage": "Potenciálisan alkalmas helyek hasonlóságának mérése egy vagy több referenciahelyhez.",
  "geocodeLocations": "Geokódolási helyszínek táblázatból",
  "geocodeLocationsUsage": "Kényelmes megoldás címek nagy tábláinak és fájljainak geokódolására.",
  "interpolatePoints": "Pontok interpolálása",
  "interpolatePointsUsage": "Értékek előrejelzése új helyeken egy adott pontcsoportból származó mérések alapján.",
  "mergeLayers": "Rétegek összeillesztése",
  "mergeLayersUsage": "Több rétegből származó vektoros elemek összeillesztése új rétegbe",
  "overlayLayers": "Fedvényműveletek",
  "overlayLayersUsage": "Több réteg kombinálása egyetlen rétegbe az eredeti rétegek információinak megőrzésével.",
  "planRoutes": "Útvonalak tervezése",
  "planRoutesUsage": "A feladatok hatékony felosztási módjának meghatározása a mobil munkaerő tagjai között.",
  "summarizeCenterAndDispersion": "Középpont és szóródás összefoglalása",
  "summarizeCenterAndDispersionUsage": "Pontszerű vektoros elemek segítségével számítja ki a központi vektoros elemet, az átlagos középpontot, a medián középpontot vagy az ellipszist (eloszlás).",
  "summarizeNearby": "Közeli területek összegzése",
  "summarizeNearbyUsage": "Másik rétegen lévő vektoros elemektől adott távolságon belül található adatok összegzése egy bemenő réteg minden vektoros eleméhez.",
  "summarizeWithin": "Területen belüli összegzés",
  "summarizeWithinUsage": "Másik réteg polygonon belül található vektoros elemeinek adatösszegzése egy bemenő polygon réteg minden egyes polygonjához.",
  "traceDownstream": "Kijelölés áramlási irányba",
  "traceDownstreamUsage": "A lefolyási útvonalak meghatározása a megadott helyektől a folyásirányban.",
  "allowToExport": "Eredmények exportálásának engedélyezése",
  "joinFeatures": "Vektorelemek összekapcsolása",
  "joinFeaturesUsage": "A Vektorelemek összekapcsolása eszközzel egy rétegről vagy tábláról térbeli és attribútumkapcsolatok alapján attribútumok vihetők át egy másikra. Lehetőség van az összekapcsolt vektoros elemek statisztikáinak kiszámítására is.",
  "includeRouteLayer": "Útvonalrétegekkel együtt",
  "findOutliers": "Kiugró értékek keresése",
  "findOutliersUsage": "A Find Outliers eszközzel meghatározható, hogy vannak-e statisztikailag szignifikáns kiugró értékek az adatok térbeli mintázatában."
});