define({
  "_widgetLabel": "能見度",
  "observerLocation": "觀察者位置",
  "formatIconTooltip": "格式輸入",
  "addPointToolTip": "新增觀察者位置",
  "fieldOfView": "視野",
  "useMilsText": "使用密爾代表角度",
  "observerHeight": "觀察者高度",
  "minObsDistance": "可觀察的最短距離",
  "maxObsDistance": "可觀察的最長距離",
  "taskURLError": "widget 配置檔包含無法連線的 URL。請洽詢您的系統管理員",
  "taskURLInvalid": "此 widget 配置的地理處理任務無效。請洽詢您的系統管理員",
  "viewshedError": "建立可見性時出錯。 請確定觀察者位置位於高程表面範圍內。</p>",
  "validationError": "<p>可見性建立表單具有無效參數或缺少參數，請確定:</p><ul><li>已設定觀察者位置。</li><li>觀察者「視野」不是 0。</li><li>觀察者高度包含有效值。</li><li>最短和最長的可觀察距離包含有效值。</li></ul>",
  "comfirmInputNotation": "確認輸入標記法",
  "notationsMatch": "符合您輸入的標記法，請確認您要使用哪個標記法:",
  "createBtn": "建立",
  "clearBtn": "清除",
  "setCoordFormat": "設定座標格式字串",
  "prefixNumbers": "新增 '+/-' 字首以變為正數和負數",
  "parseCoordinatesError": "無法剖析座標。 請檢查您的輸入。",
  "cancelBtn": "取消",
  "applyBtn": "套用",
  "invalidMessage": "請輸入數值。",
  "observerRangeMessage": "觀察者高度無效",
  "minimumRangeMessage": "觀察者範圍下限無效",
  "maximumRangeMessage": "觀察者範圍上限必須大於觀察者範圍下限，且不可超過 ${limit} ${units}。",
  "portalURLError": "未配置 ArcGIS Online 組織或 Portal for ArcGIS 的 URL。 請聯絡您的系統管理員",
  "privilegeError": "您的使用者角色無法執行分析。 為了執行分析，您的組織管理員需要將特定的<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">權限</a>授與您。",
  "noServiceError": "高程分析服務不可用。 請勾選您的 ArcGIS Online 組織或 Portal for ArcGIS 配置。",
  "pointToolTooltip": "按一下以新增觀察者位置",
  "degreesLabel": "度",
  "milsLabel": "密耳",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "十進位度 - 緯度/經度",
  "DDLongLatNotation": "十進位度 - 經度/緯度",
  "DDMLatLongNotation": "度十進制分 - 緯度/經度",
  "DDMLongLatNotation": "度十進制分 - 經度/緯度",
  "DMSLatLongNotation": "度分秒 - 緯度/經度",
  "DMSLongLatNotation": "度分秒 - 經度/緯度",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - 頻段字母",
  "UTMHemNotation": "UTM - 半球 (N/S)",
  "mainPageTitle": "徑向視線",
  "resultsTitle": "結果",
  "publishBtnLabel": "發佈",
  "layerName": "發佈的圖層名稱",
  "invalidLayerName": "圖層名稱只能包含英數字元和底線",
  "missingLayerName": "輸入圖層名稱",
  "back": "上一步",
  "publishingFailedLayerExists": "發佈失敗: 您已擁有名為 {0} 的圖徵服務。 請選擇其他名稱。",
  "checkService": "檢查服務: {0}",
  "createService": "建立服務: {0}",
  "unableToCreate": "無法建立: {0}",
  "addToDefinition": "新增至定義: {0}",
  "successfullyPublished": "已成功發佈 Web 圖層{0}管理 Web 圖層",
  "userRole": "無法建立服務，因為使用者沒有權限",
  "publishToNewLayer": "將結果發佈到新圖徵圖層",
  "missingLayerNameMessage": "您必須先輸入有效的圖層名稱，之後才能發佈",
  "regionTypeLabel": "地區類型",
  "centerPointLabel": "中心點",
  "observationHeightLabel": "觀察高度",
  "heightUnitLabel": "高度單位",
  "minObservationDistanceLabel": "MinObservation 距離",
  "maxObservationDistance": "MaxObservation 距離",
  "distanceUnitLabel": "距離單位",
  "fovstartAngleLabel": "FOV 開始角度",
  "fovEndAngleLabel": "FOV 結束角度",
  "andleUnitsLabel": "角度單位"
});