define({
  "_widgetLabel": "Analiza pretnje",
  "threatAnalysisMainPageTitle": "Zasnovano na JCAT Counterterrorism Guide (JCAT vodiču za borbu protiv terorizma)",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Ulazna lokacija",
  "interactive": "Interaktivno",
  "fromCoord": "Fiksna koordinata",
  "existingFeature": "Iz postojećih geoobjekata",
  "threatAnalysisCoordInputLabel": "Lokacija pretnje",
  "enterCoords": "Unesite koordinate",
  "threatAddPointToolTip": "Dodaj lokaciju pretnje",
  "threatDrawPointToolTip": "Kliknite da biste dodali lokaciju pretnje",
  "threatType": "Tip pretnje",
  "threatPlaceholder": "Počnite upisivanje da biste pretražili pretnju",
  "mandatoryLabel": "Obavezna evakuaciona razdaljina",
  "safeLabel": "Bezbedna evakuaciona razdaljina",
  "zoneTypeLabel": "Tip zone",
  "feetLabel": "Stope",
  "metersLabel": "Metri",
  "unitsLabel": "Jedinice",
  "threatGraphicLayer": "Grafika pretnje",
  "settingsTitle": "Postavke",
  "mandatoryButtonLabel": "Konfigurišite postavke obavezne evakuacione razdaljine",
  "safeButtonLabel": "Konfigurišite postavke skloništa u mestu",
  "style": "Stil",
  "lineStyles": {
    "esriSLSDash": "Crta",
    "esriSLSDashDot": "Crta tačka",
    "esriSLSDashDotDot": "Crta tačka tačka",
    "esriSLSDot": "Tačka",
    "esriSLSLongDash": "Duga crta",
    "esriSLSLongDashDot": "Duga crta tačka",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kratka crta",
    "esriSLSShortDashDot": "Kratka crta tačka",
    "esriSLSShortDashDotDot": "Kratka crta tačka tačka",
    "esriSLSShortDot": "Kratka tačka",
    "esriSLSSolid": "Neprozirno"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Unazad",
    "esriSFSCross": "Krst",
    "esriSFSDiagonalCross": "Dijagonalno",
    "esriSFSForwardDiagonal": "Unapred",
    "esriSFSHorizontal": "Horizontalno",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Neprozirno",
    "esriSFSVertical": "Vertikalno"
  },
  "resultsTitle": "Rezultati",
  "publishTABtn": "Objavi",
  "layerName": "Naziv objavljenog sloja",
  "invalidLayerName": "Ime sloja sme da sadrži samo alfanumeričke znakove i donje crte",
  "missingLayerName": "Morate da unesete naziv za sloj",
  "missingLayerNameMessage": "Morate da unesete važeće ime sloja da biste mogli da objavite",
  "publishingFailedLayerExists": "Objavljivanje nije uspelo: Već imate servis geoobjekata sa nazivom {0}. Izaberite drugi naziv.",
  "checkService": "Provera servisa: {0}",
  "createService": "Kreiranje servisa: {0}",
  "unableToCreate": "Kreiranje nije moguće: {0}",
  "addToDefinition": "Dodaj u definiciju: {0}",
  "successfullyPublished": "Uspešno objavljen veb sloj{0}Upravljaj veb slojem",
  "userRole": "Kreiranje servisa nije moguće, jer korisnik nema dozvole",
  "transparencyLabel": "Prozirnost",
  "outline": "Kontura",
  "fill": "Popuna (boja se primenjuje samo kada je stil podešen da bude neproziran)",
  "createBtn": "Kreiraj zone",
  "clearBtn": "Obriši",
  "invalidNumberMessage": "Uneta vrednost nije važeća",
  "invalidRangeMessage": "Vrednost mora da bude veća od 0",
  "parseCoordinatesError": "Raščlanjivanje koordinata nije moguće. Proverite unos.",
  "manualCoordinateInputInfo": "Ručno unesite koordinate i kliknite na <b>Unesi</b> da biste zumirali na njih",
  "pipeBombLabel": "Cevna bomba",
  "suicideBombLabel": "Samoubilačka bomba",
  "briefcaseLabel": "Aktovka",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/KOMBI",
  "smallDeliveryTruckLabel": "Mali dostavni kamion",
  "containerWaterTruckLabel": "Kamion sa cisternom",
  "semiTrailerLabel": "Poluprikolica",
  "selectDrawModeLabel": "Izaberite režim crtanja",
  "selectFeatureLabel": "Izaberite geoobjekat iz ovog sloja"
});