define({
  "transparencyLabel": "Trasparenza",
  "outline": "Bordo",
  "fill": "Riempimento (Il colore si applica solo quando lo stile è impostato su tinta unita)",
  "style": "Stile",
  "mandatoryLabel": "Distanza di evacuazione obbligatoria",
  "mandatoryButtonLabel": "Configurare le impostazioni della distanza di evacuazione obbligatoria",
  "safeLabel": "Distanza di evacuazione di sicurezza",
  "safeButtonLabel": "Configurare le impostazioni della distanza di evacuazione di sicurezza",
  "selectOpLayerLabel": "Selezionare un layer operativo per i risultati",
  "selectDefaultMeasurementLabel": "Selezionare un'unità di misura predefinita",
  "helpIconTooltip": "L'elenco dei layer operativi è popolato con i layer della mappa Web corrente che sono di tipo a geometria poligonale.",
  "lineStyles": {
    "esriSLSDash": "Trattino",
    "esriSLSDashDot": "Trattino punto",
    "esriSLSDashDotDot": "Trattino Punto Punto",
    "esriSLSDot": "Punto",
    "esriSLSLongDash": "Trattino lungo",
    "esriSLSLongDashDot": "Trattino lungo punto",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Trattino corto",
    "esriSLSShortDashDot": "Trattino corto punto",
    "esriSLSShortDashDotDot": "Trattino corto punto punto",
    "esriSLSShortDot": "Punto corto",
    "esriSLSSolid": "Tinta unita"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Indietro",
    "esriSFSCross": "Croce",
    "esriSFSDiagonalCross": "Diagonale",
    "esriSFSForwardDiagonal": "Avanti",
    "esriSFSHorizontal": "Orizzontale",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Tinta unita",
    "esriSFSVertical": "Verticale"
  },
  "threatTypeLabel": "Tipo di minaccia",
  "symbologyLabel": "Simbologia",
  "generalLabel": "Generale",
  "addThreatTypesLabel": "Aggiungere tipo di minaccia",
  "threatTypeColLabel": "Tipo di minaccia",
  "actions": "Azioni",
  "newThreatTypePopupLabel": "Nuovo tipo di minaccia",
  "chooseDefaultThreatTypeIconLabel": "Scegliere da predefiniti",
  "mandatoryDistance": "Distanza di evacuazione obbligatoria",
  "safeDistance": "Distanza di evacuazione di sicurezza",
  "units": "Unità",
  "chooseDefaultThreatLabel": "Selezionare un tipo di minaccia predefinito",
  "defaultThreatTypePopUpLabel": "Tipi di minaccia predefiniti",
  "editThreatLabel": "Modifica minaccia",
  "defaultThreatTypeIconTooltip": "Elenco dei tipi di minaccia predefiniti",
  "uniqueThreatTypeMsg": "Immettere un tipo di minaccia univoco; esiste già un tipo di minaccia con questo nome.",
  "requiredThreatTypeMsg": "Campo obbligatorio",
  "unitMeasureLabel": "Le distanze sono in {0}",
  "pipeBombLabel": "Tubo bomba",
  "suicideBombLabel": "Bomba suicida",
  "briefcaseLabel": "Valigetta",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Furgone per le consegne",
  "containerWaterTruckLabel": "Container/Cisterna",
  "semiTrailerLabel": "Semirimorchio"
});