define({
  "_widgetLabel": "Vidljivost",
  "observerLocation": "Lokacija posmatrača",
  "formatIconTooltip": "Unos formata",
  "addPointToolTip": "Dodaj lokaciju posmatrača",
  "fieldOfView": "Vidno polje",
  "useMilsText": "Koristi mil za uglove",
  "observerHeight": "Visina posmatrača",
  "minObsDistance": "Min. rastojanje koje je moguće posmatrati",
  "maxObsDistance": "Maks. rastojanje koje je moguće posmatrati",
  "taskURLError": "Datoteka konfiguracije vidžeta sadrži URL adresu koja je nedostupna. Proverite kod administratora sistema",
  "taskURLInvalid": "Zadatak geoprocesiranja koji je konfigurisan sa ovim vidžetom nije važeći. Proverite kod administratora sistema",
  "viewshedError": "Došlo je do greške prilikom kreiranja vidljivosti. Vodite računa da se lokacija posmatrača nalazi unutar obuhvata elevacione površi.</p>",
  "validationError": "<p>Obrazac za kreiranje vidljivosti ima parametre koji nedostaju ili su nevažeći. Uverite se da :</p><ul><li>Lokacija posmatrača je podešena.</li><li>Vidno polje posmatrača nije 0.</li><li>Visina posmatrača sadrži važeću vrednost.</li><li>Min. i maks. rastojanja koja je moguće posmatrati sadrže važeće vrednosti.</li></ul>",
  "comfirmInputNotation": "Proverite unesenu oznaku",
  "notationsMatch": "oznake se podudaraju sa unosom potvrdite koje biste želeli da koristite:",
  "createBtn": "Kreiraj",
  "clearBtn": "Obriši",
  "setCoordFormat": "Postavi nisku formata koordinata",
  "prefixNumbers": "Dodajte prefiks '+/-' pozitivnim i negativnim brojevima",
  "parseCoordinatesError": "Raščlanjivanje koordinata nije moguće. Proverite unos.",
  "cancelBtn": "Otkaži",
  "applyBtn": "Primeni",
  "invalidMessage": "Unesite brojčanu vrednost.",
  "observerRangeMessage": "Nevažeća visina posmatrača",
  "minimumRangeMessage": "Nevažeći minimalni opseg za posmatranje",
  "maximumRangeMessage": "Maksimalni opseg za posmatranje mora da bude veći od minimalnog opsega za posmatranje i ne može da bude veći od ${limit} ${units}.",
  "portalURLError": "URL adresa za vašu ArcGIS Online organizaciju ili Portal for ArcGIS nije konfigurisana. Proverite sa vašim administratorom sistema.",
  "privilegeError": "Vaša korisnička uloga ne može da vrši analizu. Da bi analiza bila izvršena, administrator organizacije mora da vam omogući određene <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilegije</a>.",
  "noServiceError": "Servis analize elevacije nije dostupan. Proverite konfiguracije za ArcGIS Online organizaciju ili Portal for ArcGIS.",
  "pointToolTooltip": "Kliknite da biste dodali lokaciju posmatrača",
  "degreesLabel": "stepeni",
  "milsLabel": "Mil",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "Univerzalni Transverzalni Merkatorov koordinatni sistem (H)",
  "UTM": "Univerzalni Transverzalni Merkatorov koordinatni sistem (UTM)",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalni stepeni – geografska širina/dužina",
  "DDLongLatNotation": "Decimalni stepeni – geografska dužina/širina",
  "DDMLatLongNotation": "Decimalni stepeni minuti – geografska širina/dužina",
  "DDMLongLatNotation": "Decimalni stepeni minuti – geografska dužina/širina",
  "DMSLatLongNotation": "Decimalni stepeni sekundi – geografska širina/dužina",
  "DMSLongLatNotation": "Decimalni stepeni sekundi – geografska dužina/širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – slovo opsega",
  "UTMHemNotation": "UTM – hemisfera (S/J)"
});