define({
  "enableUndoRedo": "Aktifkan Urungkan/Ulangi",
  "toolbarVisible": "Bilah alat terlihat",
  "toolbarOptions": "Opsi bilah alat",
  "mergeVisible": "Gabungkan",
  "cutVisible": "Potong",
  "reshapeVisible": "Ubah bentuk",
  "back": "Kembali",
  "label": "Layer",
  "edit": "Dapat Diedit",
  "update": "Nonaktifkan Pembaruan Geometri",
  "fields": "Kolom",
  "actions": "Tindakan",
  "editpageName": "Nama",
  "editpageAlias": "Alias",
  "editpageVisible": "Terlihat",
  "editpageEditable": "Dapat Diedit",
  "noLayers": "Tidak tersedia layer fitur yang dapat diedit",
  "configureFields": "Konfigurasikan kolom layer",
  "useFilterEdit": "Gunakan filter template fitur",
  "display": "Tampilkan",
  "autoApplyEditWhenGeometryIsMoved": "Terapkan edit otomatis ketika geometri dipindahkan",
  "snappingTolerance": "Tetapkan toleransi pelekat dalam piksel",
  "popupTolerance": "Tetapkan toleransi popup pengeditan atribut dalam piksel",
  "stickyMoveTolerance": "Tetapkan toleransi gerakan pelekat dalam piksel",
  "usingSaveButton": "Jangan terapkan editan ke atribut-atribut hingga mengklik tombol Simpan",
  "generalSettings": "Pengaturan umum",
  "editableLayersSetting": "Pengaturan layer dapat diedit",
  "honorTheWebMapSetting": "Ikuti pengaturan di web map",
  "honorTheWebMapSettingTip1": "Pengaturan ini mencakup:",
  "honorTheWebMapSettingTip2": "Layer mana yang dapat diedit",
  "honorTheWebMapSettingTip3": "Kolom yang ingin Anda tampilkan dan edit",
  "honorTheWebMapSettingTip4": "Alias, urutkan, dan format kolom",
  "customSettings": "Pengaturan kustom"
});