define({
  "gridTabLabel": "Griglia",
  "labelTabLabel": "Etichette",
  "referenceSystemTabLabel": "Sistema di riferimento",
  "gridTabDescription": "Impostare l’aspetto e il comportamento delle celle della griglia.",
  "cellOutlineColor": "Colore dei bordi delle celle",
  "cellFillColor": "Colore di riempimento delle celle",
  "transparency": "Trasparenza",
  "cellShapeDropDown": "Forma della cella",
  "default": "Rettangolo",
  "hexagon": "Esagono",
  "cellUnitsDropDown": "Unità della cella",
  "miles": "Miglia",
  "kilometers": "Chilometri",
  "feet": "Piedi",
  "meters": "Metri",
  "yards": "Iarde",
  "nautical-miles": "Miglia nautiche",
  "gridOriginDropDown": "Origine griglia",
  "lowerLeft": "In basso a sinistra",
  "lowerRight": "In basso a destra",
  "upperLeft": "In alto a sinistra",
  "upperRight": "In alto a destra",
  "center": "Centrato",
  "selectOpLayerLabel": "Layer operativo per i risultati",
  "helpIconTooltip": "L'elenco dei layer operativi è popolato con i layer della mappa Web corrente che sono di tipo a geometria poligonale.",
  "labelTabDescription": "Impostare l’aspetto e il comportamento delle etichette della griglia.",
  "labelSettings": "Stile etichetta",
  "font": "Carattere",
  "textSize": "Dimensione testo",
  "textColor": "Colore del testo",
  "halo": "Alone",
  "show": "Mostra",
  "labelTypeDropDown": "Tipo di etichetta",
  "alphaNumeric": "Alfanumerico",
  "alphaAlpha": "Alfabetico",
  "numeric": "Numerico",
  "labelDirectionDropDown": "Direzione etichetta",
  "horizontal": "Orizzontale",
  "vertical": "Verticale",
  "labelOriginDropDown": "Origine etichetta",
  "referenceSystemlTabDescription": "Impostare il sistema di riferimento predefinito.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Blocca impostazioni - Questa funzione consente di impedire all’utente di modificare le impostazioni del widget"
});