define({
  "_widgetLabel": "Bearbeiten",
  "_featureAction_Edit": "Bearbeiten",
  "title": "Vorlage zur Feature-Erstellung auswählen",
  "pressStr": "Drücken Sie ",
  "ctrlStr": " STRG ",
  "snapStr": " , um die Fangfunktion zu aktivieren.",
  "close": "Schließen",
  "featureLayers": "Feature-Layer",
  "searchTemplates": "Vorlagen durchsuchen",
  "noAvailableTempaltes": "Keine verfügbaren Vorlagen",
  "noCanCreateLayerAreCurrentlyVisible": "Zurzeit sind keine erstellbaren Layer sichtbar.",
  "layersAreInvisibleOrOutOfScaleRange": "Die Layer sind nicht sichtbar oder außerhalb des Maßstabsbereichs.",
  "relatedTables": "Zugehörige Tabellen:",
  "relatedRecords": "Zugehörige Datensätze:",
  "noRelatedRecotds": "Es wurden keine zugehörigen Datensätze gefunden.",
  "startToDraw": "Klicken, um mit dem Zeichnen zu beginnen",
  "startToAddPoint": "Klicken, um einen Punkt hinzuzufügen",
  "editRelatedFeature": "Zugehöriges Feature wird bearbeitet",
  "duplicateValueWarning": " Doppelter Wert kann nicht in ${fieldName} von ${tableName} eingefügt werden. Doppelter Wert: ${value}"
});