define(
   ({
    addLayer: "Lisää karttataso",
    layerName: "Karttataso",
    layerRefresh: "Päivitä",
    layerLabel: "Tunnusteksti",
    actions: "Toimet",
    popupOk: "OK",
    popupCancel: "Peruuta",
    mainPanelTextPlaceholder: "ulk.: VALTATIEN OLOSUHTEET",
    invalidInterval: "Vain numeromerkit ovat tuettuja.",
    uploadImage: "Lataa kuva",
    iconColumnText: "Kuvake",
    refreshInterval: "1 \"Lasketaan kertoina minuutissa\"",
    refreshIntervalTitle: "Lasketaan kertoina minuutissa",
    mainPanelText: "Pääruudun teksti",
    mainPanelIcon: "Pääruudun kuva",
    refreshIntervalInstruction: "Päivitysväli",
    optionsText: "Asetukset",
    symbolOptionsText: "Symboliasetukset",
    iconOptionsText: "Kuvakkeen asetukset",
    sympolPopupTitle: "Määritä symboli",
    rdoLayer: "Karttatason symboli",
    rdoCustom: "Mukautettu symboli",
    chkCluster: "Ota klusterointi käyttöön",
    defineClusterSymbol: "Klusterin symboli",
    defineThemeClusterSymbol: "Klusterin symboli teemasta",
    rdoEsri: "Esri-symboli",
    rdoLayerIcon: "Käytä symbolia kuvakkeena",
    rdoCustomIcon: "Lataa mukautettu kuvake",
    editCustomSymbol: "Muokkaa mukautettua symbolia",
    editCustomIcon: "Muokkaa mukautettua kuvaketta",
    missingRefreshValue: "Määritä päivitysvälin arvo.",
    panelIconOption: "Näytä ruudun ylätunniste",
    enableRefresh: "Ota karttatason päivitys käyttöön",
    disableRefresh: "Karttatason päivitys on tuettu vain kohdekokoelmissa",
    layer_type_not_supported: "Karttatasotyyppiä ei tueta: "
  })
);
