define({
  "addLayer": "Lisää karttataso",
  "layerName": "Karttataso",
  "layerRefresh": "Päivitä",
  "layerLabel": "Tunnusteksti",
  "actions": "Toimet",
  "mainPanelTextPlaceholder": "esim: Päivitetty viimeksi:",
  "invalidInterval": "Vain numeromerkit ovat tuettuja.",
  "uploadImage": "Lataa kuva",
  "iconColumnText": "Näytä",
  "refreshInterval": "Aika minuutteina",
  "refreshIntervalTitle": "Lasketaan kertoina minuutissa",
  "mainPanelText": "Pääruudun teksti",
  "mainPanelIcon": "Pääruudun kuva",
  "refreshIntervalInstruction": "Päivitä karttasot seuraavin välein:",
  "optionsText": "Asetukset",
  "symbolOptionsText": "Kartan symbolit",
  "iconOptionsText": "Paneelin symbolit",
  "sympolPopupTitle": "Näyttöasetukset",
  "rdoLayer": "Oletussymboli",
  "rdoCustom": "Käytä kuvaa",
  "chkCluster": "Ota klusterointi käyttöön",
  "defineClusterSymbol": "Määritä klusterin symboli",
  "rdoEsri": "Valitse symboli",
  "rdoLayerIcon": "Käytä karttasymbolia",
  "rdoCustomIcon": "Käytä kuvaa",
  "editCustomSymbol": "Muokkaa mukautettua symbolia",
  "editCustomIcon": "Muokkaa mukautettua kuvaketta",
  "missingRefreshValue": "Määritä päivitysvälin arvo.",
  "panelIconOption": "Näytä logokuva",
  "enableRefresh": "Ota karttatason päivitys käyttöön",
  "disableRefresh": "Karttatason päivitys on tuettu vain kohdekokoelmissa",
  "layer_type_not_supported": "Karttatasotyyppiä ei tueta: ",
  "refreshUnit": "minuuttia.",
  "symbolOptions": "Symboli",
  "panelFeatureDisplay": "Paneeli",
  "chkGroup": "Ryhmäkohteet",
  "selectField": "Kenttä",
  "fieldLabel": "Tunnusteksti",
  "addField": "Lisää kenttä",
  "featureOptionsText": "Tason asetukset",
  "groupOptionsText": "Ryhmäasetukset",
  "panelCountOption": "Näytä kohdemäärät",
  "rdoStack": "Näytä uusi rivi jokaiselle kentälle",
  "rdoAppend": "Liitä kentät yhdelle riville",
  "missingLayerInWebMap": "Toiminnallisia karttatasoja ei löytynyt.",
  "displayClusterCnt": "Näytä kohdemäärä",
  "defineClusterFont": "Määritä fontin väri",
  "max_records": "Enimmäiskenttärajoitus saavutettiin"
});