define({
  "gridTabLabel": "Grid",
  "labelTabLabel": "Tunnustekstit",
  "referenceSystemTabLabel": "Viitejärjestelmä",
  "gridTabDescription": "Määritä ruudukon solujen ulkoasu ja toiminta.",
  "cellOutlineColor": "Solun ääriviivaväri",
  "cellFillColor": "Solun täyttöväri",
  "transparency": "Läpinäkyvyys",
  "cellShapeDropDown": "Solun muoto",
  "default": "Suorakulmio",
  "hexagon": "Kuusikulmio",
  "cellUnitsDropDown": "Solun yksiköt",
  "miles": "Mailia",
  "kilometers": "Kilometriä",
  "feet": "Jalkaa",
  "meters": "Metriä",
  "yards": "Jaardia",
  "nautical-miles": "Meripeninkulmat",
  "gridOriginDropDown": "Ruudukon alkupiste",
  "lowerLeft": "Alavasen",
  "lowerRight": "Alaoikea",
  "upperLeft": "Ylävasen",
  "upperRight": "Yläoikea",
  "center": "Keskitä",
  "selectOpLayerLabel": "Toiminnallinen karttataso tuloksia varten",
  "helpIconTooltip": "Toiminnallisten karttatasojen luettelo täytetään nykyisen web-karttan karttatasoilla, jotka ovat tyypiltään aluekohdegeometrioita.",
  "labelTabDescription": "Määritä ruudukon tunnustekstien ulkoasu ja toiminta.",
  "labelSettings": "Tunnustekstin tyyli",
  "font": "Fontti",
  "textSize": "Tekstin koko",
  "textColor": "Tekstin väri",
  "halo": "Reunus",
  "show": "Näytä",
  "labelTypeDropDown": "Tunnustekstin tyyppi",
  "alphaNumeric": "Aakkosnumeerinen",
  "alphaAlpha": "Vain kirjaimia",
  "numeric": "Numeerinen",
  "labelDirectionDropDown": "Tunnustekstin suunta",
  "horizontal": "Vaaka",
  "vertical": "Pysty",
  "labelOriginDropDown": "Tunnustekstin alkupiste",
  "referenceSystemlTabDescription": "Määritä oletusviitejärjestelmä.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Lukituksen asetukset – tämä estää sen, ettei käyttäjä voi muuttaa määritettyjä asetuksia pienoisohjelmassa"
});