define(
   ({
    addLayer: "Добавить слой",
    layerName: "Слой",
    layerRefresh: "Обновить",
    layerLabel: "Подпись",
    actions: "Действия",
    popupOk: "OK",
    popupCancel: "Отменить",
    mainPanelTextPlaceholder: "ex: HIGHWAY CONDITIONS",
    invalidInterval: "Поддерживаются только числовые символы.",
    uploadImage: "Загрузить изображение",
    iconColumnText: "Значок",
    refreshInterval: "1 \'Оценено как время в минутах\'",
    refreshIntervalTitle: "Оценено как время в минутах",
    mainPanelText: "Текст основной панели",
    mainPanelIcon: "Изображение основной панели",
    refreshIntervalInstruction: "Интервал обновления",
    optionsText: "Параметры",
    symbolOptionsText: "Опции символа",
    iconOptionsText: "Опции значка",
    sympolPopupTitle: "Задать символ",
    rdoLayer: "Символ слоя",
    rdoCustom: "Пользовательский символ",
    chkCluster: "Включить кластеризацию",
    defineClusterSymbol: "Символ кластера",
    defineThemeClusterSymbol: "Символ кластера из Темы",
    rdoEsri: "Символ Esri",
    rdoLayerIcon: "Использовать символ как значок",
    rdoCustomIcon: "Выгрузить пользовательский значок",
    editCustomSymbol: "Редактировать пользовательский символ",
    editCustomIcon: "Изменить пользовательский значок",
    missingRefreshValue: "Укажите значение интервала обновления.",
    panelIconOption: "Показать заголовок панели",
    enableRefresh: "Включить обновление слоя",
    disableRefresh: "Обновление слоя поддерживается только для коллекций объектов",
    layer_type_not_supported: "Тип слоя не поддерживается: "
  })
);
