define({
  "addLayer": "Добавить слой",
  "layerName": "Слой",
  "layerRefresh": "Обновить",
  "layerLabel": "Подпись",
  "actions": "Действия",
  "mainPanelTextPlaceholder": "ex: Последнее обновление:",
  "invalidInterval": "Поддерживаются только числовые символы.",
  "uploadImage": "Загрузить изображение",
  "iconColumnText": "Отображение",
  "refreshInterval": "Время в минутах",
  "refreshIntervalTitle": "Оценено как время в минутах",
  "mainPanelText": "Текст основной панели",
  "mainPanelIcon": "Изображение основной панели",
  "refreshIntervalInstruction": "Обновлять слой каждые:",
  "optionsText": "Параметры",
  "symbolOptionsText": "Символы карты",
  "iconOptionsText": "Панель символов",
  "sympolPopupTitle": "Настройки отображения",
  "rdoLayer": "Символ по умолчанию",
  "rdoCustom": "Использовать изображение",
  "chkCluster": "Включить кластеризацию",
  "defineClusterSymbol": "Задать символ кластера",
  "rdoEsri": "Выбрать символ",
  "rdoLayerIcon": "Использовать символ карты",
  "rdoCustomIcon": "Использовать изображение",
  "editCustomSymbol": "Редактировать пользовательский символ",
  "editCustomIcon": "Изменить пользовательский значок",
  "missingRefreshValue": "Укажите значение интервала обновления.",
  "panelIconOption": "Отображать логотип",
  "enableRefresh": "Включить обновление слоя",
  "disableRefresh": "Обновление слоя поддерживается только для коллекций объектов",
  "layer_type_not_supported": "Тип слоя не поддерживается: ",
  "refreshUnit": "минут.",
  "symbolOptions": "Символ",
  "panelFeatureDisplay": "Панель",
  "chkGroup": "Группировать объекты",
  "selectField": "Поле",
  "fieldLabel": "Надпись",
  "addField": "Добавить поле",
  "featureOptionsText": "Опции слоя",
  "groupOptionsText": "Опции группировки",
  "panelCountOption": "Показать количество объектов",
  "rdoStack": "Отображать новую строку для каждого поля",
  "rdoAppend": "Присоединять поля в одну строку",
  "missingLayerInWebMap": "Не найдено рабочих слоев.",
  "displayClusterCnt": "Показать количество объектов",
  "defineClusterFont": "Выбрать цвет шрифта",
  "max_records": "Достигнуто максимальное ограничение поля"
});