define({
  "_widgetLabel": "Трассировка сети",
  "_featureAction_NetworkTraceSkip": "Пропустить в трассировке",
  "_featureAction_NetworkTraceUnskip": "Удалить из пропущенных местоположений",
  "removedFromSkipLocations": "Удалено из пропущенных местоположений",
  "alreadyRemovedFromSkipLocations": "Уже удалено из пропущенных местоположений",
  "locationSkipped": "Положение пропущено",
  "configError": "Виджет не сконфигурирован правильно.",
  "geometryServiceURLNotFoundMSG": "Невозможно получить URL сервиса геометрии",
  "clearButtonValue": "Очистить",
  "GPExecutionFailed": "Невозможно завершить трассировку. Повторите попытку еще раз.",
  "backButtonValue": "Назад",
  "exportToCSVSuccess": "Экспорт в CSV выполнен успешно.",
  "lblInputLocTab": "Входные положения",
  "lblBlockLocTab": "Блокировать положения",
  "lblInputLocation": "Входной объект",
  "lblBlockLocation": "Блокировать объект",
  "lblInputLocHeader": "Входные положения (0)",
  "lblBlockLocHeader": "Блокировать положения (0)",
  "inputTabTitle": "Входные",
  "outputTabTitle": "Выходные",
  "exportSelectAllCheckBoxLabel": "Выбрать все",
  "lblSkipLocHeader": "Пропустить положения (0)",
  "lblSkipLocation": "Положение",
  "lblSkipLocTab": "Пропустить положения",
  "skipAllLocationButtonLabel": "Пропустить все положения",
  "confirmSkipAllLocationsMessage": "Все местоположения будут пропущены, хотите продолжить?",
  "locationAlreadySkippedMessage": "Положение уже пропущено",
  "removeAllSkipLocationLabel": "Удалить все",
  "newProjectOptionText": "Новый проект",
  "selectProject": "Выбрать проект",
  "saveButtonLabel": "Сохранить",
  "exportToCSVText": "Экспорт в CSV",
  "editProjectAttributesToolTip": "Редактировать атрибуты проекта",
  "projectNameLabel": "Название проекта",
  "saveProjectPopupTitle": "Сохранить",
  "saveAsLabel": "Сохранить как",
  "saveChangesMsg": "Хотите сохранить изменения в <b>${loadProjectDropdownlabel}</b> или сохранить как новый проект?",
  "creatingNewProjectErrorMessage": "Ошибка создания нового проекта. Повторите попытку еще раз.",
  "projectNameFetchingErr": "Ошибка при получении существующих имен проектов. Повторите попытку еще раз.",
  "projectAttributeLoadingErr": "Ошибка при загрузке атрибутов проекта. Повторите попытку еще раз.",
  "attributeUpdatedMsg": "Атрибуты обновлены успешно.",
  "projectAttributeUpdatingErr": "Ошибка при обновлении атрибутов проекта.",
  "loadingProjectDetailsErrorMessage": "Ошибка при получении флагов, барьеров и пропуске положений. Повторите попытку еще раз.",
  "savingProjectDetailsErr": "Ошибка при сохранении деталей проекта. Попробуйте сохранить проект ещё раз.",
  "updatingOutagePolygonErr": "Ошибка при обновлении полигона отключения. Попробуйте сохранить проект ещё раз.",
  "deletingExistingPolygonErr": "Ошибка при удалении существующего полигона отключения. Попробуйте сохранить проект ещё раз.",
  "loadingProjectFeaturesErr": "Ошибка при загрузке объектов проекта. Попробуйте загрузить проект ещё раз.",
  "addingProjectFeaturesErr": "Ошибка при добавлении объектов проекта. Попробуйте сохранить проект ещё раз.",
  "deletingExistingProjectFeaturesErr": "Ошибка при удалении существующих объектов проекта. Попробуйте сохранить проект ещё раз.",
  "projectNotFoundErr": "Проект не найден",
  "projectLayersNotFound": "Слои настроек конфигурации проекта не доступны на карте. Виджет будет загружен в 'режим рисования'.",
  "fetchingOutagePolygonMessage": "Ошибка при получении полигона отключения. Попробуйте загрузить проект ещё раз.",
  "projectNameExistsMessage": "Имя проекта уже существует. Введите уникальное имя проекта.",
  "fetchingProjectNamesErrorMessage": "Ошибка при получении существующих имен проектов. Попробуйте сохранить проект ещё раз.",
  "enterProjectNameMessage": "Введите имя проекта.",
  "projectLengthErrorMessage": "Имя проекта не может быть больше чем",
  "gpServiceNotAccessible": "У вашей учётной записи нет прав доступа к сервису, необходимому для выполнения трассировки.",
  "loadingClonedLayerErrorMessage": "Ошибка при загрузке клонированного векторного слоя. Повторите попытку еще раз.",
  "addingFeatureInClonedLayerError": "Ошибка при добавлении графики в клонированный векторный слой. Повторите попытку еще раз.",
  "selectingFeatureInClonedLayerError": "Ошибка при выборке графики в клонированном векторном слое. Повторите попытку еще раз.",
  "filteredProjectError": "Ошибка при проверке получаемых деталей отфильтрованного проекта. Повторите попытку еще раз.",
  "filteredProjectMessage": "Выбранные атрибуты проекта недоступны из-за примененных фильтров из веб-карты или другого виджета.  Очистите фильтры и попробуйте снова.",
  "filteredProjectLoadMessage": "Ваш проект более недоступен. Выберите активный проект.",
  "defaultValueForRunButton": "Запуск",
  "closeButtonLabel": "Убрать"
});