define({
  "_widgetLabel": "Situationsbewusstsein",
  "locate_incident": "Ereignis verorten",
  "reverse_geocoded_address": "Nächstgelegene Adresse",
  "reverse_geocoded_error": "Nicht verfügbar",
  "now": "JETZT",
  "wind": "WIND",
  "SUN": "SO",
  "MON": "MO",
  "TUE": "DI",
  "WED": "MI",
  "THU": "DO",
  "FRI": "FR",
  "SAT": "SA",
  "actionLabel": "Position festlegen",
  "drawPoint": "Punkt zeichnen",
  "drawLine": "Linie zeichnen",
  "drawPolygon": "Polygon zeichnen",
  "saveIncident": "Speichern",
  "clearIncident": "Erneut starten",
  "noFeaturesFound": "Keine Features gefunden.",
  "downloadCSV": "Herunterladen",
  "sum": "Summe",
  "min": "Minimum",
  "max": "Maximum",
  "avg": "Durchschnitt",
  "count": "ANZAHL",
  "area": "FLÄCHE",
  "length": "LÄNGE",
  "update_btn": "Fertig",
  "delete_btn": "Löschen",
  "get_directions": "Wegbeschreibung abrufen",
  "incident": "Ereignis",
  "incidents": "Ereignisse",
  "buffer": "Puffer",
  "buffers": "Puffer",
  "weather": "Wetter",
  "poweredBy": "Powered by",
  "_featureAction_ActionLabel": "Position festlegen",
  "_featureAction_AddRemoveActionLabel": "Position hinzufügen/entfernen",
  "snapshot": "Snapshot-Ordner erstellt durch App-ID:",
  "user_credentials": "Benutzer hat keine gültigen Berechtigungen.",
  "snapshot_complete": "Snapshot wurde erfolgreich erstellt.",
  "snapshot_failed": "Fehler beim Erstellen des Snapshots.",
  "notPolySnapShot": "Geben Sie vor dem Erstellen eines Snapshots eine Pufferentfernung an.",
  "notValidDownload": "Keine gültigen Ergebnisse zum Herunterladen.",
  "snapshot_append": "Snapshot",
  "of_append": "von",
  "layer_append": "Layer",
  "downloadAll": "Alle herunterladen",
  "createSnapshot": "Snapshot erstellen",
  "calculated_results": "Zusammengefasste Informationen",
  "closest": "Nächstgelegenes Feature",
  "proximity": "Nachbarschaftsanalyse (Proximity)",
  "summary": "Zusammenfassung",
  "groupedSummary": "Gruppierte Anzahl",
  "_count": "Anzahl",
  "utc": "UTC",
  "approximate": "Ungefähr",
  "snapshot_name": "Name des Snapshots festlegen",
  "invalid_snapshot_name": "Ungültiger Snapshotname."
});