define({
  "_widgetLabel": "Editare",
  "_featureAction_Edit": "Editare",
  "title": "Selectaţi un şablon pentru a crea obiecte spaţiale",
  "pressStr": "Apăsaţi ",
  "ctrlStr": " CTRL ",
  "snapStr": " pentru a activa fixarea",
  "close": "Închidere",
  "featureLayers": "Straturile tematice de obiecte spaţiale",
  "searchTemplates": "Căutare şabloane",
  "noAvailableTempaltes": "Nu există şabloane disponibile",
  "noCanCreateLayerAreCurrentlyVisible": "Nu este vizibil niciun strat tematic creabil.",
  "layersAreInvisibleOrOutOfScaleRange": "Straturile tematice sunt invizibile sau nu se încadrează în intervalul de scară.",
  "relatedTables": "Tabele corelate:",
  "relatedRecords": "Înregistrări corelate:",
  "noRelatedRecotds": "Nu s-au găsit înregistrări corelate.",
  "startToDraw": "Faceți clic pentru a începe desenarea",
  "startToAddPoint": "Faceţi clic pentru a adăuga un punct",
  "editRelatedFeature": "Editare strat tematic aferent",
  "duplicateValueWarning": " Nu se poate introduce valoarea duplicată în ${fieldName} pentru ${tableName}. Valoarea duplicată este: ${value}"
});