define({
  "addLayer": "Προσθήκη θεματικού επιπέδου",
  "layerName": "Θεματικό επίπεδο",
  "layerRefresh": "Ανανέωση",
  "layerLabel": "Ετικέτα",
  "actions": "Ενέργειες",
  "mainPanelTextPlaceholder": "π.χ.: Τελευταία ενημέρωση:",
  "invalidInterval": "Υποστηρίζονται μόνο αριθμητικοί χαρακτήρες.",
  "uploadImage": "Μεταφόρτωση εικόνας",
  "iconColumnText": "Οθόνη",
  "refreshInterval": "Χρόνος σε λεπτά",
  "refreshIntervalTitle": "Αξιολόγηση ως χρόνος σε λεπτά",
  "mainPanelText": "Κείμενο κύριου πλαισίου",
  "mainPanelIcon": "Εικόνα κύριου πλαισίου",
  "refreshIntervalInstruction": "Ανανέωση θεματικού επιπέδου κάθε:",
  "optionsText": "Επιλογές",
  "symbolOptionsText": "Συμβολισμός χάρτη",
  "iconOptionsText": "Συμβολισμός πλαισίου",
  "sympolPopupTitle": "Ρυθμίσεις εμφάνισης",
  "rdoLayer": "Προκαθορισμένο σύμβολο",
  "rdoCustom": "Χρησιμοποιήστε μια εικόνα",
  "chkCluster": "Ενεργοποίηση δημιουργίας συστάδων",
  "defineClusterSymbol": "Ορίστε σύμβολο συστάδων",
  "rdoEsri": "Επιλέξτε ένα σύμβολο",
  "rdoLayerIcon": "Χρησιμοποιήστε σύμβολο χάρτη",
  "rdoCustomIcon": "Χρησιμοποιήστε μια εικόνα",
  "editCustomSymbol": "Επεξεργασία προσαρμοσμένου συμβόλου",
  "editCustomIcon": "Επεξεργασία προσαρμοσμένου εικονιδίου",
  "missingRefreshValue": "Εισαγάγετε μια τιμή διαστήματος ανανέωσης.",
  "panelIconOption": "Εμφάνιση εικόνας λογοτύπου",
  "enableRefresh": "Ενεργοποίηση ανανέωσης θεματικού επιπέδου",
  "disableRefresh": "Η ανανέωση θεματικού επιπέδου υποστηρίζεται μόνο για συλλογές στοιχείων",
  "layer_type_not_supported": "Ο τύπος θεματικού επιπέδου δεν υποστηρίζεται: ",
  "refreshUnit": "λεπτά.",
  "symbolOptions": "Σύμβολο",
  "panelFeatureDisplay": "Πλαίσιο",
  "chkGroup": "Στοιχεία ομάδας",
  "selectField": "Πεδίο",
  "fieldLabel": "Ετικέτα",
  "addField": "Προσθήκη πεδίου",
  "featureOptionsText": "Επιλογές θεματικού επιπέδου",
  "groupOptionsText": "Επιλογές ομαδοποίησης",
  "panelCountOption": "Εμφάνιση απαριθμήσεων στοιχείων",
  "rdoStack": "Εμφάνιση νέας γραμμής για κάθε πεδίο",
  "rdoAppend": "Προσάρτηση πεδίων σε μία και μόνο γραμμή",
  "missingLayerInWebMap": "Δεν βρέθηκαν επιχειρησιακά επίπεδα.",
  "displayClusterCnt": "Εμφάνιση απαρίθμησης στοιχείων",
  "defineClusterFont": "Ορίστε χρώμα γραμματοσειράς",
  "max_records": "Το μέγιστο όριο πεδίων εξαντλήθηκε"
});