define(
   ({
    addLayer: "Προσθήκη θεματικού επιπέδου",
    layerName: "Θεματικό επίπεδο",
    layerRefresh: "Ανανέωση",
    layerLabel: "Ετικέτα",
    actions: "Ενέργειες",
    popupOk: "ΟΚ",
    popupCancel: "Άκυρο",
    mainPanelTextPlaceholder: "π.χ.: ΣΥΝΘΗΚΕΣ ΑΥΤΟΚΙΝΗΤΟΔΡΟΜΟΥ",
    invalidInterval: "Υποστηρίζονται μόνο αριθμητικοί χαρακτήρες.",
    uploadImage: "Μεταφόρτωση εικόνας",
    iconColumnText: "Εικονίδιο",
    refreshInterval: "1 \'Αξιολόγηση ως χρόνος σε λεπτά\'",
    refreshIntervalTitle: "Αξιολόγηση ως χρόνος σε λεπτά",
    mainPanelText: "Κείμενο κύριου πλαισίου",
    mainPanelIcon: "Εικόνα κύριου πλαισίου",
    refreshIntervalInstruction: "Διάστημα ανανέωσης",
    optionsText: "Επιλογές",
    symbolOptionsText: "Επιλογές συμβόλων",
    iconOptionsText: "Επιλογές εικονιδίων",
    sympolPopupTitle: "Ορισμός συμβόλου",
    rdoLayer: "Σύμβολο θεματικού επιπέδου",
    rdoCustom: "Προσαρμοσμένο σύμβολο",
    chkCluster: "Ενεργοποίηση δημιουργίας συστάδων",
    defineClusterSymbol: "Σύμβολο δημιουργίας συστάδων",
    defineThemeClusterSymbol: "Σύμβολο δημιουργίας συστάδων από θέμα",
    rdoEsri: "Σύμβολο Esri",
    rdoLayerIcon: "Χρήση συμβόλου ως εικονίδιο",
    rdoCustomIcon: "Αποστολή προσαρμοσμένου εικονιδίου",
    editCustomSymbol: "Επεξεργασία προσαρμοσμένου συμβόλου",
    editCustomIcon: "Επεξεργασία προσαρμοσμένου εικονιδίου",
    missingRefreshValue: "Εισαγάγετε μια τιμή διαστήματος ανανέωσης.",
    panelIconOption: "Εμφάνιση κεφαλίδας πλαισίου",
    enableRefresh: "Ενεργοποίηση ανανέωσης θεματικού επιπέδου",
    disableRefresh: "Η ανανέωση θεματικού επιπέδου υποστηρίζεται μόνο για συλλογές στοιχείων",
    layer_type_not_supported: "Ο τύπος θεματικού επιπέδου δεν υποστηρίζεται: "
  })
);
