define({
  "serviceUrl": "Ορισμός URL υπηρεσίας:",
  "minIntSpacingLabel": "Ελάχιστο διάστημα απόστασης",
  "lineOpacityLabel": "Διαφάνεια γραμμής",
  "labelOpacityLabel": "Διαφάνεια ετικέτας",
  "centerLabelOpacityLabel": "Διαφάνεια κεντρικής ετικέτας",
  "gridZonePlacementLabel": "Τοποθέτηση ετικέτας ζώνης πλέγματος",
  "verticalLineLabels": "Ετικέτες κατακόρυφων γραμμών",
  "styleHeaderLabel": "Στυλ",
  "indexHeaderLabel": "Ευρετήριο",
  "colorHeaderLabel": "Χρώμα",
  "fontSizeHeaderLabel": "Μέγεθος γραμματοσειράς",
  "lineWidthHeaderLabel": "Πλάτος γραμμής",
  "horizontalLabel": "Οριζόντια",
  "verticalLabel": "Κατακόρυφα",
  "upperLeftLabel": "Πάνω αριστερά",
  "upperRightLabel": "Πάνω δεξιά",
  "lowerLeftLabel": "Κάτω αριστερά",
  "lowerRightLabel": "Κάτω δεξιά",
  "centerLabel": "Κέντρο"
});