define({
  "_widgetLabel": "Ellenőrző dashboard",
  "spatialFilterSelection": "Eredmények szűrése földrajzi jellemzők szerint",
  "drawSelectionArea": "Eredménykiválasztási terület rajzolása a térképen",
  "currentSelection": "Eredmények mutatása csak a jelenlegi térképkiterjedésen belül",
  "censusBlockGroup": "Eredmények mutatása földrajzi hely szerint",
  "noSpatialFilter": " Ne használjon térbeli szűrőt",
  "reviewerSessionFilter": "Eredmények szűrése az Ellenőrző munkamenete szerint",
  "selectAttributeFilters": "Válassza ki a megjelenítendő információkat",
  "phaseFieldName": "Életciklus-státusz",
  "statusFieldName": "Életciklus-státusz",
  "allSessions": "Összes munkamenet",
  "dashboardTab": "Dashboard",
  "filtersTab": "Beállítások",
  "noResults": "Nincs találat",
  "resultsBy": "Eredmények a következő szerint: ",
  "reviewed": "Ellenőrzés",
  "corrected": "Javítás",
  "verified": "Igazolás",
  "OtherCategory": "Egyéb",
  "backButton": "Vissza"
});