define({
  "searchTabTitle": "Meklēšanas avota iestatījumi",
  "routeTabTitle": "Maršruta iestatījumi",
  "add": "Pievienot meklēšanas avotu",
  "addGeocoder": "Pievienot ģeokodētāju",
  "geocoder": "Ģeokodētājs",
  "setLayerSource": "Iestatīt slāņa avotu",
  "setGeocoderURL": "Iestatīt ģeokodētāja vietrādi URL",
  "searchableLayer": "Elementu slānis",
  "name": "Vārds/nosaukums",
  "countryCode": "Valsts vai reģiona kods(-i)",
  "countryCodeEg": "piemēram, ",
  "countryCodeHint": "Ja šī vērtība tiks atstāta tukša, tiks meklētas visas valstis un reģioni.",
  "showInfoWindowOnSelect": "Rādīt atrastā elementa vai novietojuma uznirstošo logu",
  "showInfoWindowOnSelect2": "Rādīt uznirstošo logu, kad tiek atrasts elements vai novietojums.",
  "searchInCurrentMapExtent": "Meklēt tikai pašreizējā kartes pārklājumā",
  "setSearchFields": "Iestatīt meklēšanas laukus",
  "set": "Uzstādīt",
  "fieldSearchable": "meklējams",
  "zoomScale": "Mērogmaiņas skala",
  "locatorUrl": "Ģeokodētāja URL",
  "locatorName": "Ģeokodētāja nosaukums",
  "locatorExample": "Piemērs",
  "locatorWarning": "Šī ģeokodēšanas servisa versija netiek atbalstīta. Logrīks atbalsta ģeokodēšanas servisa versiju 10.0 un jaunākas.",
  "locatorTips": "Ieteikumi nav pieejami, jo ģeokodēšanas serviss neatbalsta ieteikšanas iespēju.",
  "layerSource": "Slāņa avots",
  "searchLayerTips": "Ieteikumi nav pieejami, jo elementu serviss neatbalsta lappušu numerācijas iespēju.",
  "placeholderText": "Viettura teksts",
  "searchFields": "Meklēšanas lauki",
  "displayField": "Rādāmais lauks",
  "exactMatch": "Precīza atbilstība",
  "maxSuggestions": "Maks. ieteikumu skaits",
  "maxResults": "Maks. rezultātu skaits",
  "enableLocalSearch": "Aktivizēt lokālo meklēšanu",
  "minScale": "Minimālo vērtību mērogs",
  "minScaleHint": "Ja kartes mērogs ir lielāks par šo mērogu, tiks lietota lokālā meklēšana",
  "radius": "Rādiuss",
  "radiusHint": "Norāda teritorijas rādiusu ap kartes centru, kas tiek izmantots, lai uzlabotu ģeokodēšanas kandidātu rangu un tādējādi vispirms tiktu atgriezti novietojumam tuvākie kandidāti",
  "invalidUrlTip": "URL ${URL} ir nederīgs vai tam nevar piekļūt.",
  "routeUrl": "Maršruta URL",
  "geocoderOptions": "Ģeokodētāja opcijas",
  "autoComplete": "Automātiski pabeigt",
  "maximumSuggestions": "Maksimālais ieteikumu skaits",
  "minCharacters": "Minimālais rakstzīmju skaits",
  "searchDelay": "Meklēšanas aizkave",
  "placeholder": "Vietturis",
  "routeOptions": "Maršruta opcijas",
  "directionsLanguage": "Norādījumu valoda",
  "directionsLengthUnits": "Norādījumu garuma vienības",
  "directionsOutputType": "Norādījumu izvades veids",
  "impedanceAttribute": "Impedences atribūts",
  "kilometers": "Kilometri",
  "miles": "Jūdzes",
  "meters": "Metri",
  "feet": "Pēdas",
  "yards": "Jardi",
  "nauticalMiles": "Jūras jūdzes",
  "parametersTip": "Lūdzu, iestatiet parametrus pareizi!",
  "complete": "Pabeigts",
  "completeNoEvents": "Pabeigts bez notikumiem",
  "instructionsOnly": "Tikai instrukcijas",
  "standard": "Standarta",
  "summaryOnly": "Tikai kopsavilkums",
  "travelModesUrl": "Ceļošanas režīmu URL",
  "searchPlaceholder": "Atrast adresi vai vietu",
  "trafficLayerUrl": "Satiksmes slāņa URL",
  "barrierLayerUrl": "Barjeras slāņa URL",
  "presetDestinations": "Iepriekš iestatīti apstāšanās punkti",
  "startPoint": "Sākuma punkts",
  "endPoint": "Beigu punkts",
  "destinationHolder": "Adrese vai koordinātas",
  "optional": "Pēc izvēles.",
  "barrierLayers": "Barjeras slāņi",
  "pointBarrier": "Punktu barjeras",
  "lineBarrier": "Līnijas barjeras",
  "polygonBarrier": "Laukuma barjeras",
  "noPointBarrier": "Izvēlēties punktu barjeras",
  "noLineBarrier": "Izvēlēties līniju barjeras",
  "noPolygonBarrier": "Izvēlēties laukuma barjeras"
});