define({
  "transparencyLabel": "Permatomumas",
  "outline": "Kontūras",
  "fill": "Užpildas (spalva taikoma, tik kai pasirinktas vientisas stilius)",
  "style": "Stilius",
  "mandatoryLabel": "Būtinas evakuacijos atstumas",
  "mandatoryButtonLabel": "Konfigūruoti būtino evakuacijos atstumo nustatymus",
  "safeLabel": "Saugus evakuacijos atstumas",
  "safeButtonLabel": "Konfigūruoti saugaus evakuacijos atstumo nustatymus",
  "selectOpLayerLabel": "Pasirinkite rezultatų darbinį sluoksnį",
  "selectDefaultMeasurementLabel": "Pasirinkite numatytąjį matavimo vienetą",
  "helpIconTooltip": "Darbinio sluoksnio sąrašas automatiškai užpildytas dabartinio internetinio žemėlapio poligonų geometrijos tipo sluoksniais.",
  "lineStyles": {
    "esriSLSDash": "Brūkšnys",
    "esriSLSDashDot": "Brūkšnys taškas",
    "esriSLSDashDotDot": "Brūkšnys taškas taškas",
    "esriSLSDot": "Taškas",
    "esriSLSLongDash": "Ilgas brūkšnys",
    "esriSLSLongDashDot": "Ilgas brūkšnys taškas",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Trumpas brūkšnys",
    "esriSLSShortDashDot": "Trumpas brūkšnys taškas",
    "esriSLSShortDashDotDot": "Trumpas brūkšnys taškas taškas",
    "esriSLSShortDot": "Trumpas taškas",
    "esriSLSSolid": "Vientisas"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atgal",
    "esriSFSCross": "Skersai",
    "esriSFSDiagonalCross": "Įstrižai",
    "esriSFSForwardDiagonal": "Pirmyn",
    "esriSFSHorizontal": "Horizontalė",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Vientisas",
    "esriSFSVertical": "Vertikalė"
  },
  "threatTypeLabel": "Grėsmės tipas",
  "symbologyLabel": "Simbolizacija",
  "generalLabel": "Bendra",
  "addThreatTypesLabel": "Pridėti grėsmės tipą",
  "threatTypeColLabel": "Grėsmės tipas",
  "actions": "Veiksmai",
  "newThreatTypePopupLabel": "Naujas grėsmės tipas",
  "chooseDefaultThreatTypeIconLabel": "Pasirinkti iš numatytųjų",
  "mandatoryDistance": "Būtinas evakuacijos atstumas",
  "safeDistance": "Saugus evakuacijos atstumas",
  "units": "Vienetai",
  "chooseDefaultThreatLabel": "Pasirinkti numatytąjį grėsmės tipą",
  "defaultThreatTypePopUpLabel": "Naujas grėsmės tipas",
  "editThreatLabel": "Redaguoti grėsmę",
  "defaultThreatTypeIconTooltip": "Numatytųjų grėsmės tipų sąrašas",
  "uniqueThreatTypeMsg": "Įveskite unikalų grėsmės tipą. Grėsmės tipas tokiu pavadinimu jau yra.",
  "requiredThreatTypeMsg": "Šis laukas privalomas",
  "unitMeasureLabel": "Atstumas išreikšti {0}",
  "pipeBombLabel": "Vamzdinė bomba",
  "suicideBombLabel": "Savižudžio bomba",
  "briefcaseLabel": "Portfelis",
  "carLabel": "Automobilis",
  "suvVanLabel": "SUV / VAN",
  "smallDeliveryTruckLabel": "Mažų siuntų pristatymo sunkvežimis",
  "containerWaterTruckLabel": "Konteinervežis/ vandenvežis",
  "semiTrailerLabel": "Puspriekabė"
});