define({
  "_widgetLabel": "가시성",
  "observerLocation": "관찰자 위치",
  "formatIconTooltip": "입력 형식 지정",
  "addPointToolTip": "관찰자 위치 추가",
  "fieldOfView": "시야각",
  "useMilsText": "각도에 밀 사용",
  "observerHeight": "관찰자 높이",
  "minObsDistance": "관찰 가능한 최소 거리",
  "maxObsDistance": "관찰 가능한 최대 거리",
  "taskURLError": "연결할 수 없는 URL이 위젯 구성 파일에 포함되어 있습니다. 시스템 관리자에게 문의하세요.",
  "taskURLInvalid": "이 위젯으로 구성된 지오프로세싱 작업이 올바르지 않습니다. 시스템 관리자에게 문의하세요.",
  "viewshedError": "가시성을 생성하는 중 오류가 발생했습니다. 관찰자 위치가 고도 표면 범위에 속해 있는지 확인하세요.</p>",
  "validationError": "<p>가시성 생성 양식의 매개변수가 누락되었거나 올바르지 않습니다. 다음을 확인하세요.</p><ul><li>관찰자 위치가 설정되어 있습니다.</li><li>관찰자 시야각이 0이 아닙니다.</li><li>관찰자 높이의 값이 올바릅니다.</li><li>관찰 가능한 최소 및 최대 거리의 값이 올바릅니다.</li></ul>",
  "comfirmInputNotation": "입력 표기 확인",
  "notationsMatch": "입력과 일치하는 표기입니다. 사용할 항목을 확인하세요.",
  "createBtn": "생성",
  "clearBtn": "지우기",
  "setCoordFormat": "좌표 형식 문자열 설정",
  "prefixNumbers": "양수와 음수에 '+/-' 접두사 추가",
  "parseCoordinatesError": "좌표를 분석할 수 없습니다. 입력을 확인하세요.",
  "cancelBtn": "취소",
  "applyBtn": "적용",
  "invalidMessage": "숫자 값을 입력하세요.",
  "observerRangeMessage": "관찰자 높이가 유효하지 않음",
  "minimumRangeMessage": "관찰 가능한 최소 범위가 유효하지 않음",
  "maximumRangeMessage": "관찰 가능한 최대 범위는 관찰 가능한 최소 범위보다 커야 하며 ${limit}${units}을(를) 초과할 수 없습니다.",
  "portalURLError": "ArcGIS Online 기관 또는 Portal for ArcGIS의 URL이 구성되지 않았습니다. 시스템 관리자에게 문의하세요.",
  "privilegeError": "귀하의 사용자 역할은 분석을 수행할 수 없습니다. 분석을 수행하려면 내 기관의 관리자가 특정 <a href=”http://doc.arcgis.com/en/arcgis-online/reference/roles.htm” target=”_blank”>권한</a>을 부여해야 합니다.",
  "noServiceError": "고도 분석 서비스를 사용할 수 없습니다. ArcGIS Online 기관 또는 Portal for ArcGIS의 구성을 확인하세요.",
  "pointToolTooltip": "관찰자 위치를 추가하려면 클릭",
  "degreesLabel": "도",
  "milsLabel": "밀",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM(H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "십진수(DD) - 위도/경도",
  "DDLongLatNotation": "십진수(DD) - 경도/위도",
  "DDMLatLongNotation": "도-소수-분 - 위도/경도",
  "DDMLongLatNotation": "도-소수-분 - 경도/위도",
  "DMSLatLongNotation": "도-분-초 - 위도/경도",
  "DMSLongLatNotation": "도-분-초 - 경도/위도",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - 밴드 문자",
  "UTMHemNotation": "UTM - 반구(N/S)",
  "mainPageTitle": "방사형 가시선",
  "resultsTitle": "결과",
  "publishBtnLabel": "발행",
  "layerName": "발행된 레이어 이름",
  "invalidLayerName": "레이어 이름에는 영숫자 문자와 밑줄만 포함해야 함",
  "missingLayerName": "레이어 이름 입력",
  "back": "돌아가기",
  "publishingFailedLayerExists": "발행 실패: 이름이 {0}인 피처 서비스가 이미 있습니다. 다른 이름을 선택하세요.",
  "checkService": "서비스 확인: [0]",
  "createService": "서비스 생성: [0]",
  "unableToCreate": "생성할 수 없음: {0}",
  "addToDefinition": "정의에 추가: {0}",
  "successfullyPublished": "웹 레이어가 발행되었음{0}웹 레이어 관리",
  "userRole": "사용자에게 권한이 없어 서비스를 생성할 수 없음",
  "publishToNewLayer": "새 피처 레이어에 결과 발행",
  "missingLayerNameMessage": "발행하려면 먼저 올바른 레이어 이름을 입력해야 함",
  "regionTypeLabel": "지역 유형",
  "centerPointLabel": "중심점",
  "observationHeightLabel": "관측 높이",
  "heightUnitLabel": "높이 단위",
  "minObservationDistanceLabel": "최소 관측 거리",
  "maxObservationDistance": "최대 관측 거리",
  "distanceUnitLabel": "거리 단위",
  "fovstartAngleLabel": "FOV 시작 각",
  "fovEndAngleLabel": "FOV 끝 각",
  "andleUnitsLabel": "각도 단위"
});