define({
  "_widgetLabel": "Видимость",
  "observerLocation": "Местоположение наблюдателя",
  "formatIconTooltip": "Входной формат",
  "addPointToolTip": "Добавить местоположение наблюдателя",
  "fieldOfView": "Поле зрения",
  "useMilsText": "Использовать милы для углов",
  "observerHeight": "Высота наблюдателя",
  "minObsDistance": "Мин. наблюдаемое расстояние",
  "maxObsDistance": "Макс. наблюдаемое расстояние",
  "taskURLError": "Файл настройки виджета содержит URL-адрес, который не доступен. Проверьте с вашим системным администратором",
  "taskURLInvalid": "Задача геообработки, настроенная с виджетом, недопустима. Проверьте с вашим системным администратором",
  "viewshedError": "При создании видимости произошла ошибка. Проверьте, что местоположение наблюдателя попадает в экстент поверхности высот.</p>",
  "validationError": "<p>В форме создания видимости отсутствуют параметры или имеются недопустимые параметры. Проверьте, что:</p><ul><li>Местоположение наблюдателя задано.</li><li>Поле зрения наблюдателя не равно 0.</li><li>Высота наблюдателя содержит корректное значение.</li><li>Мин. и макс. наблюдаемые расстояния содержат корректные значения.</li></ul>",
  "comfirmInputNotation": "Подтвердите входной формат",
  "notationsMatch": "2 варианта записи для входных данных. Выберите, который из них использовать:",
  "createBtn": "Создание",
  "clearBtn": "Сброс",
  "setCoordFormat": "Строка настройки формата координат",
  "prefixNumbers": "Добавьте префикс \"+/–\" для положительных и отрицательных чисел",
  "parseCoordinatesError": "Невозможно обработать координаты. Проверьте входные данные.",
  "cancelBtn": "Отмена",
  "applyBtn": "Применить",
  "invalidMessage": "Введите числовое значение.",
  "observerRangeMessage": "Некорректная высота наблюдателя",
  "minimumRangeMessage": "Некорректный минимальный диапазон наблюдателя",
  "maximumRangeMessage": "Максимальный диапазон обзора должен быть больше, чем Минимальный диапазон обзора и не может превышать ${limit} ${units}.",
  "portalURLError": "URL-адрес организации ArcGIS Online или Portal for ArcGIS не настроен. Проверьте с помощью системного администратора",
  "privilegeError": "Ваша роль пользователя не может выполнять анализ. Для выполнения анализа, администратор вашей организации должен предоставить вам определенные <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">права</a>.",
  "noServiceError": "Сервис анализа высот недоступен. Проверьте настройки организации ArcGIS Online или Portal for ArcGIS.",
  "pointToolTooltip": "Щелкните, чтобы добавить местоположение наблюдателя",
  "degreesLabel": "градусов",
  "milsLabel": "мил",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Десятичные градусы – Долгота/Широта",
  "DDLongLatNotation": "Десятичные градусы – Долгота/Широта",
  "DDMLatLongNotation": "Градусы, десятичные минуты – Долгота/Широта",
  "DDMLongLatNotation": "Градусы, десятичные минуты – Долгота/Широта",
  "DMSLatLongNotation": "Градусы минуты секунды – Долгота/Широта",
  "DMSLongLatNotation": "Градусы минуты секунды – Долгота/Широта",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Буква пояса",
  "UTMHemNotation": "UTM  – Полушарие (N/S)",
  "mainPageTitle": "Радиальная линия взгляда",
  "resultsTitle": "Результаты",
  "publishBtnLabel": "Публикация",
  "layerName": "Имя опубликованного слоя",
  "invalidLayerName": "Имя слоя должно содержать только буквы, цифры и подчеркивания.",
  "missingLayerName": "Введите имя слоя",
  "back": "Задний",
  "publishingFailedLayerExists": "Публикация не удалась: У вас уже имеется сервис объектов с именем {0}. Выберите другое имя.",
  "checkService": "Проверить сервис: {0}",
  "createService": "Создать сервис: {0}",
  "unableToCreate": "Невозможно создать: {0}",
  "addToDefinition": "Добавить в определение: {0}",
  "successfullyPublished": "Успешно опубликовать веб-слой{0}Управлять веб-слоем",
  "userRole": "Не удается создать сервис, так как у пользователя нет прав",
  "publishToNewLayer": "Публикация результатов в новый слой объектов",
  "missingLayerNameMessage": "Перед публикацией необходимо ввести корректное имя слоя",
  "regionTypeLabel": "Тип региона",
  "centerPointLabel": "Центральная точка",
  "observationHeightLabel": "Высота наблюдения",
  "heightUnitLabel": "Единица высоты",
  "minObservationDistanceLabel": "Минимальное расстояние наблюдения",
  "maxObservationDistance": "Максимальное расстояние наблюдения",
  "distanceUnitLabel": "Единицы измерения расстояния",
  "fovstartAngleLabel": "Начальный угол поля зрения",
  "fovEndAngleLabel": "Конечный угол поля зрения",
  "andleUnitsLabel": "Единицы угла"
});