define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "按一下地圖以新增點",
  "addRingsDtWt": "新增圓環、行駛時間或步行時間。",
  "apply": "套用",
  "back": "上一步",
  "colon": "支援：",
  "creditInformation": "點數資訊",
  "driveTime": "行駛時間",
  "esriInfographics": "Esri 資訊圖表",
  "esriReports": "Esri 報告",
  "headerDescription_km": "公里",
  "headerDescription_miles": "英哩",
  "headerDescription_minutes": "分鐘",
  "infographics": "資訊圖表",
  "invalidValueRing": "值必須位於範圍 0 到 1,000。",
  "invalidValueDTWT": "值必須位於範圍 0 到 300。",
  "km": "km",
  "miles": "英哩",
  "minutes": "分鐘",
  "myInfographics": "我的資訊圖表",
  "myReports": "我的報告",
  "noPermissions": "您的帳號無法執行 Business Analyst widget。 為了執行 Business Analyst widget，您的組織管理員需要將 GeoEnrichment 和網路分析<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">權限</a>授與您，並且配置<a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">點數</a>。",
  "radii": "半徑",
  "radius": "半徑",
  "radius_lowercase": "半徑",
  "reports": "報告",
  "ring": "圓環",
  "rings": "圓環",
  "runInfographic": "執行資訊圖表",
  "runReport": "執行報告",
  "selectPointOrPolygon": "在地圖上選擇點或多邊形圖徵、搜尋地址或地點，或在地圖上放置大頭針以檢視區域的詳細資訊。",
  "selectReport": "選擇報告",
  "selectTemplate": "選擇範本",
  "sharedInfographics": "分享的資訊圖表",
  "sharedReports": "分享的報告",
  "thisEntryIsNotValid": "此項目無效。",
  "time": "時間",
  "walkTime": "步行時間",
  "widgetDescription": "存取摘要了任何區域的關鍵指標和資料的資訊圖表和報告。",
  "None": "選擇..."
});