define({
  "_widgetLabel": "Rácshálós referenciakép",
  "newGRGFromAreaButtonLabel": "Rácsháló meghatározása területből",
  "newGRGFromPointButtonLabel": "Rácsháló meghatározása pontból",
  "newGRGFromAreaTitle": "Rácsháló meghatározása területből",
  "newGRGFromPointTitle": "Rácsháló meghatározása pontból",
  "newGRGBySizeButtonLabel": "Méret alapján",
  "newGRGFromRefSystemButtonLabel": "Hivatkozási rendszer alapján",
  "newGRGByTimeLabel": "Idő és távolság alapján",
  "newGRGFromNonStandardButtonLabel": "Nem szabványos rácsháló meghatározása",
  "newGRGAreaBySizeTitle": "GRG területből méret alapján",
  "newGRGAreaBySizeDefineAreaLabel": "GRG-terület",
  "addGRGAreaPolygonToolTip": "GRG-terület rajzolása polygon használatával",
  "addGRGAreaExtentToolTip": "GRG-terület rajzolása kiterjedés használatával",
  "rotation": "Rácsháló forgatása",
  "numberRowsColumnsLabel": "Sorok és oszlopok számának meghatározása",
  "newGRGAreaByRefSystemTitle": "GRG területből hivatkozási rendszer alapján",
  "gridSize": "Rácsháló mérete",
  "UTMZoneandBand": "Rácsháló zónája",
  "100000m": "100000 méter",
  "10000m": "10000 méter",
  "1000m": "1000 méter",
  "100m": "100 méter",
  "10m": "10 méter",
  "clipGrid": "Rácsháló levágása a GRG-területre",
  "newGRGAreaFromNonStandardTitle": "Új NRG",
  "newGRGPointBySizeTitle": "GRG pontból méret alapján",
  "newGRGPointByRefSystemTitle": "GRG pontból hivatkozási rendszer alapján",
  "newGRGPointByTimeTitle": "GRG pontból idő és távolság használatával",
  "time": "Idő",
  "rate": "Sebesség",
  "hours": "Óra",
  "minutes": "Perc",
  "seconds": "Másodperc",
  "ftPerSec": "Láb/másodperc",
  "ftPerHour": "Láb/óra",
  "kmPerSec": "Kilométer/másodperc",
  "kmPerHour": "Kilométer/óra",
  "mPerSec": "Méter/másodperc",
  "mPerHour": "Méter/óra",
  "miPerSec": "Mérföld/másodperc",
  "miPerHour": "Mérföld/óra",
  "nMPerSec": "Tengeri mérföld/másodperc",
  "nMPerHour": "Tengeri mérföld/óra",
  "settingsTitle": "Beállítások",
  "labelSettingsLabel": "Felirat beállításai",
  "labelSettingsButtonLabel": "Felirat beállításainak konfigurálása",
  "gridSettingsLabel": "Rácsháló beállításai",
  "gridSettingsButtonLabel": "Rácsháló beállításainak konfigurálása",
  "transparency": "Átlátszóság",
  "labelStyle": "Felirat stílusa",
  "font": "Betűtípus",
  "textSize": "Szövegméret",
  "textColor": "Szövegszín",
  "halo": "Halo",
  "show": "Megjelenítés",
  "lockSettings": "Az alkalmazás tulajdonosa zárolta a beállításokat",
  "gridSettings": {
    "cellShape": "Cella alakja",
    "cellUnits": "Cella mértékegységei",
    "cellOutline": "Cella körvonal-beállításai",
    "cellFill": "Cella kitöltési beállításai",
    "gridReferenceSystem": "Hivatkozási rendszer",
    "gridDatum": "Dátum: WGS84",
    "labelStartPosition": "Felirat kiindulási pontja",
    "labelType": "Felirat típusa",
    "labelDirection": "Felirat iránya",
    "gridOrigin": "Rácsháló kiindulási pontja",
    "default": "Téglalap",
    "hexagon": "Hatszög",
    "miles": "Mérföld",
    "kilometers": "Kilométer",
    "feet": "Láb",
    "meters": "Méter",
    "yards": "Yard",
    "nautical-miles": "Tengeri mérföld",
    "lowerLeft": "Bal alsó",
    "lowerRight": "Jobb alsó",
    "upperLeft": "Bal felső",
    "upperRight": "Jobb felső",
    "center": "Középen",
    "alphaNumeric": "Alfanumerikus",
    "alphaAlpha": "Alfa-alfa",
    "numeric": "Numerikus",
    "horizontal": "Vízszintes",
    "vertical": "Függőleges",
    "MGRS": "MGRS",
    "USNG": "USNG",
    "showLabels": "Feliratok megjelenítése"
  },
  "publishTitle": "GRG közzététele a portálon",
  "publishGRGBtn": "Közzététel",
  "GRGLayerName": "Közzétett GRG-réteg neve",
  "invalidGRGLayerName": "A réteg neve csak alfanumerikus karaktereket és aláhúzás karaktereket tartalmazhat",
  "missingGRGLayerName": "Meg kell adnia a GRG nevét",
  "publishWorskpaceError": "HIBA: Hiba történt a munkaterület megnyitásakor",
  "publishingFailedLayerExists": "Sikertelen közzététel: Már van {0} nevű vektoros szolgáltatás. Válasszon másik nevet.",
  "checkService": "Szolgáltatás ellenőrzése: {0}",
  "createService": "Szolgáltatás létrehozása: {0}",
  "unableToCreate": "Nem lehet létrehozni: {0}",
  "addToDefinition": "Hozzáadás a meghatározáshoz: {0}",
  "successfullyPublished": "A(z) {0} webes réteg sikeresen közzétéve. Kezelje a webes réteget",
  "userRole": "Nem lehet létrehozni a szolgáltatást, mert a felhasználónak nincs megfelelő engedélye",
  "createGRGBtn": "GRG létrehozása",
  "clearGRGBtn": "Törlés",
  "labelFormat": "Felirat formátuma",
  "helpIconTooltip": "Z: Rácsháló zónajelölője (GZD)\nS: 100000 méteres rácsnégyzet-azonosítás (GSID)\nX: Abszcissza (X koordináta)\nY: Ordináta (Y koordináta)\n\nPéldák:\nZSXY – 15SWC8081751205\nZS X,Y – 15SWC 80817,51205",
  "addPointToolTip": "GRG kiindulási pontjának hozzáadása",
  "cellWidth": "Cella szélessége (x)",
  "cellHeight": "Cella magassága (y)",
  "invalidNumberMessage": "A megadott érték nem érvényes",
  "invalidRangeMessage": "Az értéknek 0-nál nagyobbnak kell lennie",
  "gridAngleInvalidRangeMessage": "Az értéknek -89,9 és 89,9 között kell lennie",
  "formatIconTooltip": "Formátumbemenet",
  "coordInputLabel": "GRG kiindulási pontja (DD)",
  "setCoordFormat": "Koordináta-formátum beállítása",
  "prefixNumbers": "A „+/-” előtag hozzáadása a pozitív és negatív számok jelöléséhez",
  "cancelBtn": "Mégse",
  "applyBtn": "Alkalmaz",
  "comfirmInputNotation": "Bemeneti jelölés megerősítése",
  "notationsMatch": "A bemenetnek több jelölések felel meg. Pontosítsa, hogy melyiket szeretné használni:",
  "numberOfCellsHorizontal": "Cellák száma vízszintesen",
  "numberOfCellsVertical": "Cellák száma függőlegesen",
  "gridAngle": "Rácsháló forgatása",
  "tooManyCellsErrorMessage": "Olyan rácshálót próbál létrehozni, amely 2000-nél több cellát tartalmaz. Célszerű csökkentenie a létrehozott cellák számát a rácsháló méretének vagy a rácsháló területének megváltoztatásával.",
  "missingParametersMessage": "<p>A GRG létrehozási űrlapján hiányzó vagy érvénytelen paraméterek találhatók. Ellenőrizze a következőt:</p><ul><li>A GRG-terület megrajzolt.</li><li>A cella szélessége és magassága érvényes értékeket tartalmaz.</li></ul>",
  "missingOriginParametersMessage": "<p>A GRG létrehozási űrlapján hiányzó vagy érvénytelen paraméterek találhatók. Ellenőrizze a következőt:</p><ul><li>A GRG kiindulási pont beállított.</li><li>A bementi idő, a sebesség és a szög megadott értéke érvényes.</li></ul>",
  "invalidWidthHeightParametersMessage": "<p>A GRG létrehozási űrlapján hiányzó vagy érvénytelen paraméterek találhatók. Ellenőrizze, hogy érvényes-e a cella szélességének és magasságának értéke.</p>",
  "invalidHorizontalVerticalParametersMessage": "<p>A GRG létrehozási űrlapján hiányzó vagy érvénytelen paraméterek találhatók. Ellenőrizze, hogy érvényes-e a vízszintes és a függőleges cellaszám értéke.</p>",
  "drawPointToolTip": "Kattintson a GRG kiindulási pont hozzáadásához",
  "missingLayerNameMessage": "Meg kell adnia egy érvényes rétegnevet a közzététel előtt",
  "parseCoordinatesError": "Nem sikerült a koordináták elemzése. Ellenőrizze a bevitt adatokat.",
  "grgPolarRegionError": "A GRG-kiterjedés poláris régión belül van. A poláris régióba eső cellák nem lesznek létrehozva.",
  "grgPolarOriginError": "A GRG kiindulási pont nem lehet poláris régión belül, amikor hivatkozási rendszer alapján hozza létre a GRG-t.",
  "deleteBtn": "Törlés",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Tized fokok - szélesség/hosszúság",
  "DDLongLatNotation": "Tized fokok - szélesség/hosszúság",
  "DDMLatLongNotation": "Fokok és tized fokpercek - szélesség/hosszúság",
  "DDMLongLatNotation": "Fokok és tized fokpercek - szélesség/hosszúság",
  "DMSLatLongNotation": "Fokok, fokpercek és fokmásodpercek - szélesség/hosszúság",
  "DMSLongLatNotation": "Fokok, fokpercek és fokmásodpercek - hosszúság/szélesség",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - sávbetűjel",
  "UTMHemNotation": "UTM - félteke (É/D)"
});