define({
  "tabs_section_Label": "टैब",
  "addTab": "टैब जोड़ें",
  "layerName": "लेयर",
  "layerType": "विश्लेषण का प्रकार",
  "layerLabel": "लेबल",
  "actions": "कार्रवाइयाँ",
  "closest": "निकटतम फीचर",
  "proximity": "निकटता",
  "summary": "सार",
  "select_lbl": "-- चयन करें --",
  "general_setting_Label": "सामान्य सेटिंग",
  "units_text_lbl": "दूरी की इकाइयां",
  "maximum_distance_lbl": "निकटतम फीचर अधिकतम दूरी",
  "buffer_text_lbl": "बफर लेबल",
  "buffer_lbl": "बफर दूरी",
  "buffer_max_lbl": "अधिकतम बफर दूरी",
  "buffer_min_lbl": "न्यूनतम बफर दूरी",
  "routing_checkBox": "रूटिंग को सक्षम करें",
  "weather_Label": "मौसम विकल्प",
  "weather_checkBox": "मौसम की जानकारी शामिल करें",
  "selectLayers": "मौसम लेयरों का चयन करें",
  "currentlySelectedLayer": "वर्तमान में चयनित मौसम लेयरस",
  "missingTabLabel": "कम से कम एक टैब का लेबल उपलब्ध नहीं है",
  "missingLayerInWebMap": "कोई भी परिचालन लेयर नहीं मिली।",
  "selectFields": "फील्ड्स का चयन करें",
  "addField": "क्षेत्र जोडें",
  "sum": "योग",
  "min": "न्यूनतम",
  "max": "अधिकतम",
  "avg": "औसत",
  "count": "गणना",
  "area": "क्षेत्रफल",
  "length": "लंबाई",
  "count_checkBox": "फीचर संख्या प्रदर्शित करें",
  "area_checkBox": "क्षेत्रफल के योग का प्रदर्शन करता है",
  "length_checkBox": "लंबाई के योग का प्रदर्शन करता है",
  "max_records": "अधिकतम सीमा पूरी हो गई है",
  "save_label": "विकल्प सहेजें",
  "save_checkbox": "सहेजें को सक्षम करें",
  "csv_label": "CSV विकल्प",
  "csv_checkbox": "लेयर में सभी फ़ील्ड को निर्यात करता है",
  "display_label": "विकल्प को प्रदर्शित करता है",
  "display_checkbox": "सारांश फीचर को प्रदर्शित करता है",
  "snapshot_label": "स्नैपशॉट विकल्प",
  "snapshot_checkbox": "स्नैपशॉट को सक्षम करें",
  "must_select_template": "सहेजें विकल्प में टेम्पलेट्स संपादन में से एक का चयन करें।",
  "count_label": "गणना लेबल",
  "area_label": "क्षेत्रफल लेबल",
  "length_label": "लंबाई लेबल",
  "invalid_string_width": "मान बहुत लंबा है। ",
  "layer_type_not_supported": "लेयर प्रकार समर्थित नहीं है: ",
  "groupedSummary": "समूहित गणना",
  "groupByField": "फील्ड द्वारा समूह",
  "labelType": "लेबल सलंग्न करें",
  "prefix": "उपसर्ग के रूप में",
  "suffix": "प्रत्यय के रूप में",
  "need_group_field": "फील्ड द्वारा समूह को परिभाषित करने के लिए संपादित कार्रवाई का उपयोग करें।",
  "fieldTitle": "फ़ील्ड",
  "typeTitle": "प्रकार",
  "actionsTitle": "कार्रवाइयाँ",
  "save_point_checkbox": "बिंदु सहेजें",
  "save_line_checkbox": "रेखाओं को सहेजें",
  "save_poly_checkbox": "बहुभुज को सहेजें",
  "no_valid_popup_fields": "पॉपअप में कोई मान्य फ़ील्ड नहीं है। एक फ़ील्ड को परिभाषित करने के लिए संपादित कार्रवाई का उपयोग करें।",
  "no_valid_fields": "कोई मान्य फ़ील्ड नहीं हैं। प्रदर्शन विकल्पों को परिभाषित करने के लिए संपादित कार्रवाई का उपयोग करें।",
  "incident_label": "टैब लेबल",
  "locate_incident_label": "पसंदीदा लेबल",
  "incident": "घटना",
  "locate_incident": "घटना का पता लगाएं",
  "buffer_value": "बफर दूरी"
});