define({
  "_widgetLabel": "Рисование",
  "selectDrawMode": "Выбрать режим рисования",
  "clear": "Очистить",
  "point": "Точка",
  "line": "Линия",
  "polyline": "Линия",
  "freehandPolyline": "Произвольная полилиния",
  "triangle": "Треугольник",
  "extent": "Конверт",
  "circle": "Круг",
  "ellipse": "Эллипс",
  "polygon": "Полигон",
  "freehandPolygon": "Произвольный полигон",
  "text": "Текст",
  "style": "Стиль",
  "alpha": "Прозрачность",
  "width": "Ширина",
  "size": "Размер",
  "color": "Цвет",
  "markerColor": "Цвет маркера",
  "outlineColor": "Цвет контура",
  "lineColor": "Цвет линии",
  "fillColor": "Цвет заливки",
  "showMeasurements": "Показать измерения",
  "showLocationMeasurement": "Показать измерения местоположения",
  "showAreaMeasurement": "Показать измерение площади",
  "showDistanceMeasurement": "Показать измерение расстояния",
  "showDistanceMeasurementForLine": "Показать измерение длины",
  "showDistanceMeasurementForPolygon": "Показать измерение периметра",
  "locationToggleOn": "Нажмите кнопку  переключения, чтобы показать измерения местоположений",
  "locationToggleOff": "Нажмите кнопку  переключения, чтобы скрыть измерения местоположений",
  "areaToggleOn": "Нажмите кнопку  переключения, чтобы показать измерения площади",
  "areaToggleOff": "Нажмите кнопку  переключения, чтобы скрыть измерения площади",
  "distanceForLineToggleOn": "Нажмите кнопку  переключения, чтобы показать измерения длины",
  "distanceForLineToggleOff": "Нажмите кнопку  переключения, чтобы скрыть измерения длины",
  "distanceForPolygonToggleOn": "Нажмите кнопку  переключения, чтобы показать измерения периметра",
  "distanceForPolygonToggleOff": "Нажмите кнопку  переключения, чтобы скрыть измерения периметра",
  "areaUnits": "Единицы площади",
  "distanceUnits": "Единицы расстояния",
  "kilometers": "Километры",
  "miles": "Мили",
  "meters": "Метры",
  "feet": "Футы",
  "yards": "Ярды",
  "nauticalmiles": "Морские мили",
  "squareKilometers": "Квадратные километры",
  "squareMiles": "Квадратные мили",
  "acres": "Акры",
  "hectares": "гектары",
  "squareMeters": "Квадратные метры",
  "squareFeet": "Квадратные футы",
  "squareYards": "Квадратные ярды",
  "undo": "Отменить",
  "redo": "Повторить",
  "results": "Результаты",
  "points": "Точки",
  "lines": "Линии",
  "areas": "Области",
  "locationLabel": "Местоположение: ${value}",
  "areaLabel": "Площадь: ${value} ${unit}",
  "distanceLabel": "Расстояние: ${value} ${unit}",
  "distanceLabelForLine": "Длина: ${value} ${unit}",
  "distanceLabelForPolygon": "Периметр: ${value} ${unit}"
});