define({
  "_widgetLabel": "Apdraudējumu analīze",
  "threatAnalysisMainPageTitle": "Pamatojoties uz JCAT pretterorisma norādījumiem",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Ievadīt novietojumu",
  "interactive": "Interaktīvs",
  "fromCoord": "Fiksēta koordināta",
  "existingFeature": "No esošajiem elementiem",
  "threatAnalysisCoordInputLabel": "Apdraudējuma atrašanās vieta",
  "enterCoords": "Ievadīt koordinātas",
  "threatAddPointToolTip": "Pievienot apdraudējuma atrašanās vietu",
  "threatDrawPointToolTip": "Noklikšķiniet, lai pievienotu apdraudējuma atrašanās vietu",
  "threatType": "Apdraudējuma veids",
  "threatPlaceholder": "Sāciet rakstīt, lai meklētu apdraudējumu",
  "mandatoryLabel": "Obligātais evakuācijas attālums",
  "safeLabel": "Patvertne vietas zonā",
  "zoneTypeLabel": "Zonas veids",
  "feetLabel": "Pēdas",
  "metersLabel": "Metri",
  "unitsLabel": "Mērvienības",
  "settingsTitle": "Iestatījumi",
  "mandatoryButtonLabel": "Konfigurēt obligātā evakuācijas attāluma iestatījumus",
  "safeButtonLabel": "Konfigurēt patvertnes uz vietas iestatījumus",
  "style": "Stils",
  "lineStyles": {
    "esriSLSDash": "Svītra",
    "esriSLSDashDot": "Svītra punkts",
    "esriSLSDashDotDot": "Svītra punkts punkts",
    "esriSLSDot": "Punkts",
    "esriSLSLongDash": "Gara svītra",
    "esriSLSLongDashDot": "Gara svītra punkts",
    "esriSLSNull": "Nulle",
    "esriSLSShortDash": "Īsa svītra",
    "esriSLSShortDashDot": "Īsa svītra punkts",
    "esriSLSShortDashDotDot": "Īsa svītra punkts punkts",
    "esriSLSShortDot": "Īsa svītra",
    "esriSLSSolid": "Tīrtoņa"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atpakaļvērsts",
    "esriSFSCross": "Krusts",
    "esriSFSDiagonalCross": "Diagonāls",
    "esriSFSForwardDiagonal": "Uz priekšu",
    "esriSFSHorizontal": "Horizontāli",
    "esriSFSNull": "Nulle",
    "esriSFSSolid": "Tīrtoņa",
    "esriSFSVertical": "Vertikāli"
  },
  "resultsTitle": "Rezultāti",
  "publishTABtn": "Publicēt",
  "layerName": "Publicētā slāņa nosaukums",
  "invalidLayerName": "Slāņa nosaukums var saturēt tikai burtu un ciparu rakstzīmes, kā arī pasvītrojumus.",
  "missingLayerName": "Jums jāievada slāņa nosaukums",
  "missingLayerNameMessage": "Lai varētu publicēt, ir jāievada derīgs slāņa nosaukums",
  "publishingFailedLayerExists": "Publicēšana neizdevās: jums jau ir elementu serviss ar nosaukumu {0}. Lūdzu, izvēlieties citu nosaukumu.",
  "checkService": "Pārbaudīt servisu: {0}.",
  "createService": "Izveidot servisu: {0}",
  "unableToCreate": "Nevar izveidot: {0}",
  "addToDefinition": "Pievienot definīcijai: {0}",
  "successfullyPublished": "Veiksmīgi publicēts tīmekļa slānis{0}Pārvaldīt tīmekļa slāni",
  "userRole": "Nevar izveidot servisu, jo lietotājam nav atļauju",
  "transparencyLabel": "Caurspīdīgums",
  "outline": "Kontūra",
  "fill": "Pildījums (krāsa tiek lietota tikai tad, ja iestatīts tīrtoņa stils)",
  "createBtn": "Izveidot zonas",
  "clearBtn": "Notīrīt",
  "invalidNumberMessage": "Ievadītā vērtība nav derīga",
  "invalidRangeMessage": "Vērtībai jābūt lielākai par 0",
  "parseCoordinatesError": "Nevar parsēt koordinātas. Lūdzu, pārbaudiet ievadi."
});