define({
  "_widgetLabel": "Pametni uređivač",
  "_featureAction_SmartEditor": "Pametni uređivač",
  "noEditPrivileges": "Vaš nalog nema dozvolu za kreiranje ili izmenu podataka.",
  "widgetActive": "Aktivno",
  "widgetNotActive": "Nije aktivno",
  "pressStr": "Pritisnite ",
  "ctrlStr": " CTRL ",
  "snapStr": " da biste omogućili snapovanje",
  "noAvailableTempaltes": "Nema dostupnih šablona",
  "editorCache": " - Keš uređivača",
  "presetFieldAlias": "Polje",
  "presetValue": "Unapred postavljena vrednost",
  "usePresetValues": " Koristi unapred postavljene vrednosti (samo za nove geoobjekte)",
  "editGeometry": " Uredi geometriju",
  "savePromptTitle": "Sačuvaj geoobjekat",
  "savePrompt": "Želite li da sačuvate trenutni geoobjekat?",
  "deletePromptTitle": "Obriši geoobjekat",
  "deletePrompt": "Želite li zaista da obrišete izabrani geoobjekat?",
  "attachmentLoadingError": "Greška pri otpremanju priloga",
  "attachmentSaveDeleteWarning": "Upozorenje: izmene na prilozima se automatski čuvaju",
  "autoSaveEdits": "Automatski čuva nove geoobjekte",
  "addNewFeature": "Kreiraj novi geoobjekat",
  "featureCreationFailedMsg": "Kreiranje novog zapisa/geoobjekta nije moguće",
  "relatedItemTitle": "Povezana tabela/sloj",
  "invalidRelationShipMsg": "Vodite računa da primarno ključno polje: '${parentKeyField}' ima važeću vrednost",
  "pendingFeatureSaveMsg": "Sačuvajte izmene geoobjekta pre kreiranja povezanog geoobjekta.",
  "attachmentsRequiredMsg": "(*) Prilozi su obavezni.",
  "coordinatePopupTitle": "Pomeri geoobjekat na XY lokaciju",
  "coordinatesSelectTitle": "Koordinatni sistem:",
  "mapSpecialReferenceDropdownOption": "Prostorna referenca mape",
  "latLongDropdownOption": "Geografska širina/dužina",
  "xAttributeTextBoxLabel": "X koordinata:",
  "yAttributeTextBoxLabel": "Y koordinata:",
  "latitudeTextBoxLabel": "Geografska širina:",
  "longitudeTextBoxLabel": "Geografska dužina:",
  "filterEditor": {
    "all": "Sve",
    "noAvailableTempaltes": "Nema dostupnih šablona",
    "searchTemplates": "Pretraži šablone"
  },
  "invalidConfiguration": "Vidžet nije konfigurisan ili slojevi u konfiguraciji više nisu na mapi. Otvorite aplikaciju u graditeljskom režimu i ponovo konfigurišite vidžet.",
  "geometryServiceURLNotFoundMSG": "Dobijanje URL servisa geometrije nije moguće",
  "clearSelection": "Obriši",
  "refreshAttributes": "Ažuriranje atributa geoobjekta",
  "automaticAttributeUpdatesOn": "Automatsko ažuriranje atributa geoobjekta: UKLJUČENO",
  "automaticAttributeUpdatesOff": "Automatsko ažuriranje atributa geoobjekta: ISKLJUČENO",
  "moveSelectedFeatureToGPS": "Pomeri izabrane geoobjekte na trenutnu GPS lokaciju",
  "moveSelectedFeatureToXY": "Pomeri izabrani geoobjekat na XY lokaciju",
  "mapNavigationLocked": "Navigacija mape: zaključano",
  "mapNavigationUnLocked": "Navigacija mape: otključano"
});