define({
  "transparencyLabel": "Prozirnost",
  "outline": "Obris",
  "fill": "Ispuni (boja se primjenjuje samo kad je stil postavljen na jednobojno)",
  "style": "Stil",
  "mandatoryLabel": "Obavezna udaljenost za evakuaciju",
  "mandatoryButtonLabel": "Kofigurirajte obaveznu udaljenost za evakuaciju",
  "safeLabel": "Sigurna udaljenost za evakuaciju",
  "safeButtonLabel": "Kofigurirajte sigurnu udaljenost za evakuaciju",
  "selectOpLayerLabel": "Odabir operativnog sloja za rezultate",
  "selectDefaultMeasurementLabel": "Odabir zadane mjerne jedinice",
  "helpIconTooltip": "Operativni sloj popunjen je slojevima poligonalnog tipa geometrije iz trenutačne web-karte.",
  "lineStyles": {
    "esriSLSDash": "Linija s crticom",
    "esriSLSDashDot": "Linija s crticom i točkom",
    "esriSLSDashDotDot": "Linija s crticom i dvije točke",
    "esriSLSDot": "Točka",
    "esriSLSLongDash": "Duga crtica",
    "esriSLSLongDashDot": "Duga crtica i točka",
    "esriSLSNull": "Nema vrijednosti",
    "esriSLSShortDash": "Kratka crtica",
    "esriSLSShortDashDot": "Kratka crtica i točka",
    "esriSLSShortDashDotDot": "Kratka crtica i dvije točke",
    "esriSLSShortDot": "Kratka točka",
    "esriSLSSolid": "Puna linija"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Unatrag",
    "esriSFSCross": "Križ",
    "esriSFSDiagonalCross": "Dijagonalno",
    "esriSFSForwardDiagonal": "Naprijed",
    "esriSFSHorizontal": "Vodoravni",
    "esriSFSNull": "Nema vrijednosti",
    "esriSFSSolid": "Puna linija",
    "esriSFSVertical": "Uspravno"
  },
  "threatTypeLabel": "Vrsta prijetnje",
  "symbologyLabel": "Simbologija",
  "generalLabel": "Općenito",
  "addThreatTypesLabel": "Dodaj vrstu prijetnje",
  "threatTypeColLabel": "Vrsta prijetnje",
  "actions": "Radnje",
  "newThreatTypePopupLabel": "Nova vrsta prijetnje",
  "chooseDefaultThreatTypeIconLabel": "Izaberi iz zadanih opcija",
  "mandatoryDistance": "Obavezna udaljenost za evakuaciju",
  "safeDistance": "Sigurna udaljenost za evakuaciju",
  "units": "Jedinice",
  "chooseDefaultThreatLabel": "Odaberite zadanu vrstu prijetnje",
  "defaultThreatTypePopUpLabel": "Zadane vrste prijetnje",
  "editThreatLabel": "Uredi prijetnju",
  "defaultThreatTypeIconTooltip": "Popis zadanih vrsta prijetnje",
  "uniqueThreatTypeMsg": "Unesite jedinstvenu vrstu prijetnje. Vrsta prijetnje s tim nazivom već postoji.",
  "requiredThreatTypeMsg": "Ovo je polje obavezno",
  "unitMeasureLabel": "Udaljenosti su u: {0}",
  "pipeBombLabel": "Cijevna bomba",
  "suicideBombLabel": "Bomba za samoubilački napad",
  "briefcaseLabel": "Aktovka",
  "carLabel": "Automobil",
  "suvVanLabel": "SUV/KAMION",
  "smallDeliveryTruckLabel": "Mali kamion za dostavu",
  "containerWaterTruckLabel": "Kamion za prijevoz kontejnera/vode",
  "semiTrailerLabel": "Poluprikolica"
});