define({
  "chartSettingLabel": "Nastavitve grafa",
  "addNewLabel": "Dodaj novo",
  "generalSettingLabel": "Splošne nastavitve",
  "layerChooser": {
    "title": "Izberite sloj za izdelavo grafa",
    "selectPolygonLayerLabel": "Izberi sloj",
    "selectPolygonLayerHintText": "Namig: Če konfigurirate več grafov, morajo biti sloji istega geometrijskega tipa",
    "selectRelatedTableLayerLabel": "Izberite tabelo, ki je v relaciji s slojem",
    "selectRelatedTableLayerHintText": "Namig: Prikazane so samo tabele z numeričnimi polji",
    "errorInSelectingPolygonLayer": "Izberite sloj, ki je v relaciji s točkovnim slojem.",
    "errorInSelectingRelatedLayer": "Izberite veljavno tabelo/sloj s slojem.",
    "polygonLayerNotHavingRelationships": "Izbrani sloj nima relacijskih tebel/slojev."
  },
  "ChartSetting": {
    "sectionTitle": "Naslov odseka",
    "sectionTitleHintText": "Namig: Prikazano v naslovu glave odseka",
    "chartTitle": "Naslov grafikona",
    "chartTitleHintText": "Namig: Prikazano na sredini na vrhu grafikona",
    "chartDescription": "Opis",
    "chartDescriptionHintText": "Namig: Prikazano pod grafikonom",
    "chartType": "Tip grafikona",
    "barChart": "Palčni grafikon",
    "pieChart": "Tortni grafikon",
    "polarChart": "Polarni grafikon",
    "dataSeriesField": "Polje serije podatkov",
    "labelField": "Polje napisa",
    "chartColor": "Barva grafikona",
    "singleColor": "Ena barva",
    "colorByTheme": "Barva po temi",
    "colorByFieldValue": "Barva po vrednosti polja",
    "xAxisTitle": "Naslov osi X",
    "xAxisHintText": "Namig: Naslov osi X",
    "yAxisTitle": "Naslov osi Y",
    "yAxisHintText": "Namig: Naslov osi Y",
    "fieldColorLabel": "Napis",
    "fieldColorColor": "Barva",
    "defaultFieldSelectLabel": "Izberi",
    "errMsgFieldValuesNotFound": "Za izbrano polje ni mogoče najti vrednosti",
    "errMsgSectionTitle": "Vnesite naslov odseka",
    "errMsgFieldByValue": "Izberite vrednost polja",
    "settingTabTitle": "Nastavitev",
    "layoutTabTitle": "Postavitev",
    "polarChartSelectFieldsHintText": "Namig: Izberite polja, da generirate polarni grafikon",
    "visibilityText": "Vidnost",
    "fieldNameText": "Ime polja",
    "aliasNameText": "Vzdevek",
    "errMsgPolarFieldsRequired": "Izberite tri ali več polj, da generirate polarni grafikon",
    "polarChartPolygonFillLabel": "Zapolni poligon",
    "polarChartPolygonFillHintText": "Namig: Izberite potrditveno polje za prikaz polnila poligona v polarnem grafikonu",
    "ThemeSelector": {
      "themeAdobebricks": "Glinene opeke",
      "themeAlgae": "Alge",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "Modri mrak",
      "themeCubanShirts": "Kubanske srajce",
      "themeDesert": "Puščava",
      "themeDistinctive": "Značilno",
      "themeDollar": "Dolar",
      "themeGrasshopper": "Kobilica",
      "themeGrasslands": "Pašnik",
      "themeGreySkies": "Sivo nebo",
      "themeHarmony": "Harmonija",
      "themeIndigoNation": "Indigo Nation",
      "themeIreland": "Irska",
      "themeMiamiNice": "Miami Nice",
      "themeMinty": "Mentolova",
      "themePurpleRain": "Škrlatni dež",
      "themeRoyalPurples": "Kraljevo škrlatna",
      "themeSageToLime": "Žajbelj do limete",
      "themeTufte": "Tufte",
      "themeWatersEdge": "Rob vode",
      "themeWetlandText": "Mokrišče",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Splošne nastavitve",
    "locationSymbolLabel": "Grafični simbol lokacije",
    "locationSymbolHintText": "Namig: Uporablja se za prikaz simbola za naslov in klik lokacije",
    "refreshIntervalLabel": "Osveži interval",
    "refreshIntervalHintText": "Namig: Uporablja se za osveževanje grafikonov na podlagi tega intervala. Navedite vrednost med 1 in 1440 minut",
    "errMsgRefreshInterval": "Navedite interval osveževanja med 0 in 1440 minut.",
    "symbolPickerPreviewText": "Predogled:"
  }
});