define({
  "tabs_section_Label": "Välilehdet",
  "addTab": "Lisää välilehti",
  "layerName": "Karttataso",
  "layerType": "Analyysityyppi",
  "layerLabel": "Tunnusteksti",
  "actions": "Toimet",
  "closest": "Lähin kohde",
  "proximity": "Läheisyys",
  "summary": "Yhteenveto",
  "select_lbl": "-- Valitse --",
  "general_setting_Label": "Yleiset asetukset",
  "units_text_lbl": "Etäisyyden yksiköt",
  "maximum_distance_lbl": "Lähimmän kohteen enimmäisetäisyys",
  "buffer_text_lbl": "Puskurin selite",
  "buffer_lbl": "Puskurin etäisyys",
  "buffer_max_lbl": "Puskurin enimmäisetäisyys",
  "buffer_min_lbl": "Puskurin vähimmäisetäisyys",
  "routing_checkBox": "Ota reititys käyttöön",
  "weather_Label": "Sääolosuhteet",
  "weather_checkBox": "Sisällytä säätiedot",
  "selectLayers": "valitse sääkarttatasot",
  "currentlySelectedLayer": "Tällä hetkellä valitut sääkarttatasot",
  "missingTabLabel": "Vähintään yhdestä välilehdestä puuttuu nimiö",
  "missingLayerInWebMap": "Toiminnallisia karttatasoja ei löytynyt.",
  "selectFields": "Valitse kentät",
  "addField": "Lisää kenttä",
  "sum": "Summa",
  "min": "Minimi",
  "max": "Maksimi",
  "avg": "Keskiarvo",
  "count": "MÄÄRÄ",
  "area": "ALUE",
  "length": "PITUUS",
  "count_checkBox": "Näytä kohteiden määrä",
  "area_checkBox": "Näytä alueen summa",
  "length_checkBox": "Näytä pituuden summa",
  "max_records": "Enimmäisraja saavutettu",
  "save_label": "Tallenna asetukset",
  "save_checkbox": "Ota tallennus käyttöön",
  "csv_label": "Salli tulosten vienti",
  "csv_checkbox": "Vie kaikki karttatason kentät",
  "display_label": "Näytä asetukset",
  "display_checkbox": "Näytä kohteiden yhteenveto",
  "snapshot_label": "Tilannevedoksen asetukset",
  "snapshot_checkbox": "Ota tilannevedos käyttöön",
  "must_select_template": "Valitse yksi muokkausmalleista Tallenna asetukset -kohdassa.",
  "count_label": "Määrän selite",
  "area_label": "Alueen selite",
  "length_label": "Pituuden selite",
  "invalid_string_width": "Arvo on liian pitkä. ",
  "layer_type_not_supported": "Karttatasotyyppiä ei tueta: ",
  "groupedSummary": "Ryhmitellyt määrät",
  "groupByField": "Ryhmittele kentän mukaan",
  "labelType": "Liitä selite",
  "prefix": "Etuliitteenä",
  "suffix": "Jälkiliitteenä",
  "need_group_field": "Määritä Ryhmittele kentän mukaan -toiminto käyttämällä muokkaustoimintoa.",
  "fieldTitle": "Kenttä",
  "typeTitle": "Tyyppi",
  "actionsTitle": "Toimet",
  "save_point_checkbox": "Tallenna pisteet",
  "save_line_checkbox": "Tallenna viivat",
  "save_poly_checkbox": "Tallenna aluekohteet",
  "no_valid_popup_fields": "Ponnahdusikkunassa ei ole kelvollisia kenttiä. Määritä kenttä käyttämällä muokkaustoimintoa.",
  "no_valid_fields": "Kelvollisia kenttiä ei ole. Määritä näyttöasetukset käyttämällä muokkaustoimintoa.",
  "incident_label": "Välilehden tunniste",
  "locate_incident_label": "Kiinnostusalueen selite",
  "incident": "Tapahtuma",
  "locate_incident": "Paikanna tapahtuma",
  "buffer_value": "Puskurin etäisyys"
});