define({
  "defaultAreaUnit": "Προκαθορισμένη μονάδα εμβαδού",
  "defaultLengthUnit": "Προκαθορισμένη μονάδα μήκους",
  "acres": "Έικρ",
  "sqMiles": "Τετ. μίλια",
  "sqKilometers": "Τετ. χιλιόμετρα",
  "hectares": "Εκτάρια",
  "sqYards": "Τετ. γιάρδες",
  "sqFeet": "Τετραγωνικά πόδια",
  "sqFeetUS": "Τετρ. πόδια (US)",
  "sqMeters": "Τετ. μέτρα",
  "miles": "Μίλια",
  "kilometers": "Χιλιόμετρα",
  "feet": "Πόδια",
  "feetUS": "Πόδια (US)",
  "meters": "Μέτρα",
  "yards": "Γιάρδες",
  "nauticalMiles": "Ναυτικά μίλια",
  "showArea": "Περιοχή",
  "showDistance": "Απόσταση",
  "showLocation": "Τοποθεσία",
  "showtools": "Εμφάνιση εργαλείων μέτρησης:",
  "allHidedTips": "Πρέπει να επιλεγεί τουλάχιστον ένα εργαλείο."
});