define({
  "tabs_section_Label": "Záložky",
  "addTab": "Přidat kartu",
  "layerName": "Vrstva",
  "layerType": "Typ analýzy",
  "layerLabel": "Štítek",
  "actions": "Akce",
  "closest": "Nejbližší prvek",
  "proximity": "Obalové zóny, vzdálenost",
  "summary": "Souhrn",
  "select_lbl": "– Vybrat –",
  "general_setting_Label": "Obecná nastavení",
  "units_text_lbl": "Jednotky vzdálenosti",
  "maximum_distance_lbl": "Maximální vzdálenost k nejbližšímu prvku",
  "buffer_text_lbl": "Popisek obalové zóny",
  "buffer_lbl": "Šířka obalové zóny",
  "buffer_max_lbl": "Maximální šířka obalové zóny",
  "buffer_min_lbl": "Minimální šířka obalové zóny",
  "routing_checkBox": "Povolit vyhledávání trasy",
  "weather_Label": "Možnosti počasí",
  "weather_checkBox": "Zahrnout informace o počasí",
  "selectLayers": "Vybrat vrstvy počasí",
  "currentlySelectedLayer": "Aktuálně vybrané vrstvy počasí",
  "missingTabLabel": "Nejméně jedna karta neobsahuje popisek.",
  "missingLayerInWebMap": "Nebyly nalezeny žádné operační vrstvy.",
  "selectFields": "Vybrat pole",
  "addField": "Přidat pole (Add Field)",
  "sum": "Suma",
  "min": "Minimum",
  "max": "Maximum",
  "avg": "Průměr",
  "count": "POČET",
  "area": "PLOCHA",
  "length": "DÉLKA",
  "count_checkBox": "Zobrazit počet prvků",
  "area_checkBox": "Zobrazit součet oblasti",
  "length_checkBox": "Zobrazit součet délky",
  "max_records": "Byl dosažen maximální limit",
  "save_label": "Možnosti ukládání",
  "save_checkbox": "Povolit ukládání",
  "csv_label": "Možnosti CSV",
  "csv_checkbox": "Exportovat všechna pole ve vrstvě",
  "display_label": "Možnosti zobrazení",
  "display_checkbox": "Zobrazit prvky souhrnu",
  "snapshot_label": "Možnosti snímku",
  "snapshot_checkbox": "Povolit snímek",
  "must_select_template": "Vyberte jednu z editačních šablon v možnostech ukládání.",
  "count_label": "Popisek počtu",
  "area_label": "Popisek oblasti",
  "length_label": "Popisek délky",
  "invalid_string_width": "Hodnota je příliš dlouhá. ",
  "layer_type_not_supported": "Typ vrstvy není podporován. ",
  "groupedSummary": "Počty seskupených",
  "groupByField": "Seskupit podle pole",
  "labelType": "Připojit popisek",
  "prefix": "Jako předponu",
  "suffix": "Jako příponu",
  "need_group_field": "K definování funkce Seskupit podle pole použijte akci Úprava.",
  "fieldTitle": "Pole",
  "typeTitle": "Typ",
  "actionsTitle": "Akce",
  "save_point_checkbox": "Uložit body",
  "save_line_checkbox": "Uložit linie",
  "save_poly_checkbox": "Uložit polygony",
  "no_valid_popup_fields": "Vyskakovací okno neobsahuje žádná platná pole. Definujte pole pomocí akce Upravit.",
  "no_valid_fields": "Žádná platná pole. Definujte možnosti zobrazení pomocí akce Upravit.",
  "incident_label": "Název karty",
  "locate_incident_label": "Název zájmové oblasti",
  "incident": "Událost",
  "locate_incident": "Vyhledat událost",
  "buffer_value": "Šířka obalové zóny"
});