define({
  "_widgetLabel": "Conversão de Coordenadas",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "formatInput": "Introdução de Formato",
  "copyAll": "Copiar Todos",
  "copySuccessful": "Cópia Bem-sucedida",
  "copyFailed": "Não é possível Copiar. Por favor, utilize ctrl+c como alternativa.",
  "parseCoordinatesError": "Não foi possível analisar as coordenadas. Por favor, verifique a entrada.",
  "comfirmInputNotation": "Confirmar Notação de Entrada",
  "latLongWarningMessage": "A coordenada introduzida foi detetada como tendo tanto um prefixo como um sufixo para o valor de latitude ou longitude, a coordenada devolvida baseia-se no prefixo.",
  "inputLabel": "Introdução",
  "outputLabel": "Saída",
  "cancelButtonLabel": "Cancelar",
  "applyButtonLabel": "Aplicar",
  "posNegPrefixLabel": "Adicione o prefixo \"+/-\" a números negativos e positivos",
  "editCoordinateDialogTitle": "Definir String de Formatação de Coordenadas",
  "rememberDecisionLabel": "Lembrar a minha decisão e não voltar a perguntar.<br/>",
  "coordinateInputLabel": "Introduza coordenadas ou clique no mapa",
  "zoomLabel": "Zoom",
  "multipleNotationLabel": "notações encontradas que correspondem à sua entrada Por favor, confirme aqueles que pretende utilizar:",
  "copyToClipboard": "Copiar para a área de transferência",
  "formatOutput": "Formatar saída",
  "addNewNotation": "Adicionar Nova Notação",
  "notationAddedMessage": "Nova Notação Adicionada",
  "addLabel": "Adicionar",
  "removeCoordinate": "Remover Coordenada",
  "expandOutput": "Expandir Saída"
});