define({
  "_widgetLabel": "Tegn",
  "selectDrawMode": "Velg tegnemodus",
  "clear": "Fjern",
  "point": "Punkt",
  "line": "Linje",
  "polyline": "Polylinje",
  "freehandPolyline": "Frihåndspolylinje",
  "triangle": "Trekant",
  "extent": "Konvolutt",
  "circle": "Sirkel",
  "ellipse": "Ellipse",
  "polygon": "Polygon",
  "freehandPolygon": "Frihåndspolygon",
  "text": "Tekst",
  "style": "Stil",
  "alpha": "Gjennomsiktighet",
  "width": "Bredde",
  "size": "Størrelse",
  "color": "Farge",
  "markerColor": "Markørfarge",
  "outlineColor": "Omrissfarge",
  "lineColor": "Linjefarge",
  "fillColor": "Fyllfarge",
  "showMeasurements": "Vis målinger",
  "showLocationMeasurement": "Vis lokasjonsmåling",
  "showAreaMeasurement": "Vis områdemåling",
  "showDistanceMeasurement": "Vis avstandsmåling",
  "showDistanceMeasurementForLine": "Vis lengdemåling",
  "showDistanceMeasurementForPolygon": "Vis omkretsmåling",
  "locationToggleOn": "Trykk på veksleknappen for å vise lokasjonsmåling",
  "locationToggleOff": "Trykk på veksleknappen for å skjule lokasjonsmåling",
  "areaToggleOn": "Trykk på veksleknappen for å vise arealmåling",
  "areaToggleOff": "Trykk på veksleknappen for å skjule arealmåling",
  "distanceForLineToggleOn": "Trykk på veksleknappen for å vise lengdemåling",
  "distanceForLineToggleOff": "Trykk på veksleknappen for å skjule lengdemåling",
  "distanceForPolygonToggleOn": "Trykk på veksleknappen for å vise omkretsmåling",
  "distanceForPolygonToggleOff": "Trykk på veksleknappen for å skjule omkretsmåling",
  "areaUnits": "Arealenheter",
  "distanceUnits": "Avstandsenheter",
  "kilometers": "Kilometer",
  "miles": "Miles",
  "meters": "Meter",
  "feet": "Fot",
  "yards": "Yards",
  "nauticalmiles": "Nautiske mil",
  "squareKilometers": "Kvadratkilometer",
  "squareMiles": "Kvadratmiles",
  "acres": "Acre",
  "hectares": "Hektar",
  "squareMeters": "Kvadratmeter",
  "squareFeet": "Kvadratfot",
  "squareYards": "Kvadratyard",
  "undo": "Angre",
  "redo": "Gjør om",
  "results": "Resultater",
  "points": "Punkt",
  "lines": "Linjer",
  "areas": "Områder",
  "locationLabel": "Lokasjon: ${value}",
  "areaLabel": "Område: ${value} ${unit}",
  "distanceLabel": "Avstand: ${value} ${unit}",
  "distanceLabelForLine": "Lengde: ${value} ${unit}",
  "distanceLabelForPolygon": "Omkrets: ${value} ${unit}"
});