define({
  "tabs_section_Label": "Cilnes",
  "addTab": "Pievienot cilni",
  "layerName": "Slānis",
  "layerType": "Analīzes tips",
  "layerLabel": "Etiķete",
  "actions": "Darbības",
  "closest": "Tuvākais elements",
  "proximity": "Tuvums",
  "summary": "Kopsavilkums",
  "select_lbl": "-- Atlasīt --",
  "general_setting_Label": "Vispārējie iestatījumi",
  "units_text_lbl": "Attāluma mērvienības",
  "maximum_distance_lbl": "Tuvākā elementa maksimālais attālums",
  "buffer_text_lbl": "Buferzonas kartes teksts",
  "buffer_lbl": "Buferzonas attālums",
  "buffer_max_lbl": "Maksimālais buferzonas attālums",
  "buffer_min_lbl": "Minimālais buferzonas attālums",
  "routing_checkBox": "Aktivizēt maršrutēšanu",
  "weather_Label": "Laikapstākļu opcijas",
  "weather_checkBox": "Iekļaut informāciju par laikapstākļiem",
  "selectLayers": "atlasīt laikapstākļu slāņus",
  "currentlySelectedLayer": "Pašreiz atlasītie laikapstākļu slāņi",
  "missingTabLabel": "Vismaz vienai cilnei nav marķējuma",
  "missingLayerInWebMap": "Nav atrasti darbības slāņi.",
  "selectFields": "Atlasīt laukus",
  "addField": "Pievienot lauku",
  "sum": "Summa",
  "min": "Minimums",
  "max": "Maksimums",
  "avg": "Vidējais",
  "count": "SKAITĪT",
  "area": "APGABALS",
  "length": "GARUMS",
  "count_checkBox": "Rādīt elementu skaitu",
  "area_checkBox": "Rādīt laukuma summu",
  "length_checkBox": "Rādīt garuma summu",
  "max_records": "Sasniegts maksimālais ierobežojums",
  "save_label": "Saglabāšanas opcijas",
  "save_checkbox": "Aktivizēt saglabāšanu",
  "csv_label": "CSV opcijas",
  "csv_checkbox": "Eksportēt visus laukus slānī",
  "display_label": "Parādīšanas opcijas",
  "display_checkbox": "Parādīt kopsavilkuma elementus",
  "snapshot_label": "Momentuzņēmumu opcijas",
  "snapshot_checkbox": "Aktivizēt momentuzņēmumu",
  "must_select_template": "Lūdzu, sadaļā Saglabāšanas opcijas atlasiet vienu no rediģēšanas veidnēm.",
  "count_label": "Skaita kartes teksts",
  "area_label": "Laukuma kartes teksts",
  "length_label": "Garuma kartes teksts",
  "invalid_string_width": "Vērtība ir pārāk gara. ",
  "layer_type_not_supported": "Slāņa tips netiek atbalstīts: ",
  "groupedSummary": "Grupētie rezultāti",
  "groupByField": "Grupēt pēc lauka",
  "labelType": "Pievienot kartes tekstu",
  "prefix": "Kā prefikss",
  "suffix": "Kā sufikss",
  "need_group_field": "Izmantojiet darbību Rediģēt, lai definētu grupu pēc lauka.",
  "fieldTitle": "Lauks",
  "typeTitle": "Tips",
  "actionsTitle": "Darbības",
  "save_point_checkbox": "Saglabāt punktus",
  "save_line_checkbox": "Saglabāt līnijas",
  "save_poly_checkbox": "Saglabāt laukumus",
  "no_valid_popup_fields": "Uznirstošajā logā nav derīgu lauku. Izmantojiet darbību Rediģēt, lai definētu lauku.",
  "no_valid_fields": "Nav derīgu lauku. Izmantojiet darbību Rediģēt, lai definētu parādīšanas opcijas.",
  "incident_label": "Tabulatora kartes teksts",
  "locate_incident_label": "Interešu apgabala kartes teksts",
  "incident": "Negadījums",
  "locate_incident": "Atrast negadījumu",
  "buffer_value": "Buferzonas attālums"
});