define({
  "settings": "Настройки",
  "titleSettings": "Настройки текста",
  "imageSettings": "Настройки изображения",
  "backgroundColor": "Цвет фона",
  "alignment": "Выравнивание",
  "textSize": "Размер текста",
  "textColor": "Цвет текста",
  "dataSource": "Источник данных",
  "chartSettings": "Настройки диаграммы",
  "data": "Данные",
  "dataLabels": "Надписи данных",
  "displayMode": "Отображать режим",
  "featureOption": "Отображать значения по объектам",
  "categoryOption": "Отображать значения по категории",
  "countOption": "Отображать число объектов по категориям",
  "fieldOption": "Отображать атрибутивные значения в виде диаграмм",
  "categoryField": "Поле категории",
  "labelField": "Поле подписи",
  "valueFields": "Поля значений",
  "operation": "Операция",
  "sumOption": "Сумма",
  "averageOption": "Среднее арифметическое",
  "minOption": "Минимум",
  "maxOption": "Максимум",
  "dataFormat": "Формат данных",
  "decimalPlaces": "Десятичные знаки",
  "prefix": "Префикс",
  "suffix": "Суффикс",
  "dataType": "Тип данных",
  "featureCount": "Число объектов",
  "fieldStatistics": "Поле статистики",
  "display": "Отображение",
  "chartColor": "Цвет диаграммы",
  "horizontalAxis": "Горизонтальная ось",
  "verticalAxis": "Вертикальная ось",
  "legend": "Легенда",
  "position": "Положение",
  "top": "Сверху",
  "bottom": "Cнизу",
  "useDataSourceSelection": "Использовать выборку",
  "dataSourceFilterByExtent": "Фильтр по экстенту",
  "changeTemplate": "Изменить шаблон",
  "numberSettings": "Числовые настройки",
  "gaugeSettings": "Настройки датчика",
  "indicators": "Индикаторы",
  "ifValue": "Если значение",
  "and": "и",
  "numberOperatorIsLessThan": "меньше чем",
  "numberOperatorIsGreaterThan": "больше чем",
  "numberOperatorIsBetween": "между",
  "numberOperatorIsEqual": "равно",
  "numberOperatorIsNotEqual": "не равно",
  "then": "Тогда",
  "ratio": "Относительные",
  "trueValue": "Значение Истина",
  "changeValueColor": "изменить значение цвета на",
  "changeGaugeColor": "изменить цвета датчика на",
  "setIndicatorIcon": "установить значок индикатора как",
  "icons": "Значки",
  "style": "Стиль",
  "placement": "Размещение",
  "left": "Слева",
  "replace": "Заменить",
  "right": "Справа",
  "color": "Цвет",
  "sortBy": "Сортировать по",
  "labelAxis": "Надпись",
  "valueAxis": "Значение",
  "minPeriod": "Минимальный период",
  "automatic": "Автоматически",
  "periodsWithOutRecords": "Периоды без записей",
  "nullValue": "Пустое значение",
  "calculatedAsZero": "Вычислено как ноль",
  "ignored": "Проигнорировано",
  "maxCategories": "Максимальное количество категорий",
  "useLayerSymbology": "Использовать символы слоя",
  "hollowsize": "Размер пустот",
  "splitField": "Поле разбиения",
  "parsingperiodTip": "Не удалось вычислить. Слишком много интервалов на короткий период анализа.",
  "manyCategoryTip": "Не удалось отобразить диаграмму. Слишком много категорий.",
  "setColor": "Задать цвет",
  "setTheColorOf": "Задать цвет",
  "setTheColorAs": "Задать цвет как",
  "ifStr": "Если",
  "as": "как",
  "is": "является",
  "isNot": "не является",
  "barCluster": "кластер столбцов",
  "individualBar": "отдельный столбец",
  "allOthers": "Все остальные",
  "dataRange": "Диапазон данных",
  "targetValue": "Целевое значение",
  "currentValue": "Текущее значение",
  "gaugeColor": "Цвет датчика",
  "min": "Минимум",
  "max": "Максимум",
  "displayValueIn": "Отобразить значение в",
  "noData": "Нет данных",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "М",
  "billionAbbreviation": "G",
  "warning": "Предупреждение",
  "noSettingWaring1": "Щелкните элемент для установки его свойств.",
  "noSettingWaring2": "Потяните для изменения размера или порядка расположения элемента.",
  "donNotShowAgain": "Больше не показывать",
  "changeTemplateWarning": "Ваши настройки будут удалены и откроется новый пустой шаблон.",
  "requiredFieldWarning": "Это значение является обязательным",
  "dataSourceNotSet": "Укажите источник данных.",
  "addIndicatorTip": "Добавьте индикатор",
  "chooseTemplatePopupTitle": "Выбор шаблона",
  "stringsInTemplate": {
    "name_number": "Число",
    "name_gauge": "Датчик",
    "name_vertical_gauge": "Вертикальный датчик",
    "name_horizontal_gauge": "Горизонтальный датчик",
    "name_pie": "Круговая",
    "name_donut": "Кольцо",
    "name_bar": "Линия",
    "name_stacked_bar": "Линия с накоплением",
    "name_percentage_stacked_bar": "Процент линии с накоплением",
    "name_column": "Столбец",
    "name_stacked_column": "Столбец с накоплением",
    "name_percentage_stacked_column": "Процент столбца с накоплением",
    "name_line": "Линия",
    "name_area": "Область",
    "name_stacked_area": "Область с накоплением",
    "name_percentage_stacked_area": "Процент области с накоплением",
    "titleOfTheInfographic": "ЗАГОЛОВОК ИНФОГРАФИКИ",
    "description": "Описание: дополнительная информация об этой инфографике."
  }
});