define({
  "taskUrl": "عنوان URL للمهمة",
  "setTask": "تعيين",
  "setTaskPopupTitle": "تعيين مهمة",
  "validate": "تعيين",
  "inValidGPService": "يرجى إدخال خدمة معالجة جغرافية.",
  "GPFeatureRecordSetLayerERR": "يرجى إدخال خدمة معالجة جغرافية بمدخلات من النوع \"GPFeatureRecordSetLayer\" فقط.",
  "invalidInputParameters": "عدد معلمات الإدخال إما أقل من 1 أو أكثر من 3. يرجى إدخال خدمة معالجة جغرافية صحيحة.",
  "projectSetting": {
    "title": "إعدادات المشروع",
    "note": "ملاحظة: تصبح إعدادات المشروع اختيارية، بمجرد أن يتمكن المستخدم من تخزين المشروع في طبقات خريطة الويب المرغوبة بمنطقة انقطاع الشبكة و معلمات الإدخال. يمكن للمستخدم تخزين معلمات إخراج أخرى من مجموعة \"الإخراج\" في علامة التبويب \"الإدخال/الإخراج\".",
    "projectPolygonLayer": "طبقة مضلع المشروع",
    "outputParameterName": "اسم معلمة الإخراج",
    "projectPointLayer": "طبقة نقطة المشروع",
    "selectLabel": "تحديد",
    "polygonLayerHelp": "<p>سيتم عرض طبقات المضلع ذات الشروط التالية :<br/><li>يجب أن يكون للطبقة قدرات تحريرية أي \"الإنشاء\" و\"الحذف\" و\"التحديث\"</li><li>يجب أن يكون للطبقة حقلان بنفس الاسم ونوع البيانات:</li><ul><li>الاسم (حقل نوع السلسلة)</li><li>المعرف العالمي (حقل نوع المعرف العالمي)</li></ul><p/>",
    "outputParameterHelp": "<p>سيتم عرض طبقات مضلع الإخراج من URL المهمة<p/>",
    "pointLayerHelp": "<p>سيتم عرض طبقات النقطة ذات الشروط التالية :<br/><li>يجب أن يكون للطبقة قدرات تحريرية أي \"الإنشاء\" و\"الحذف\" و\"التحديث\"</li><li>يجب أن يكون للطبقة حقلان بنفس الاسم ونوع البيانات:</li><ul><li>نوع الإدخال (حقل نوع السلسلة)</li><li>معرف المشروع (حقل نوع الدليل)</li></ul><p/>"
  },
  "inputOutputTab": {
    "title": "الإدخال/الإخراج",
    "inputSettingsLabel": "إعدادات الإدخال",
    "outputSettingsLabel": "إعدادات الإخراج",
    "inputLabel": "التسمية",
    "inputTooltip": "تلميح الأدوات",
    "symbol": "رمز",
    "typeText": "النوع",
    "outputParametersText": "معلمات الإخراج",
    "saveToLayerText": "حفظ على الطبقة (اختياري)",
    "skipText": "يمكن تخطيه",
    "visibilityText": "مرئي",
    "exportToCsvText": "تصدير إلى CSV",
    "exportToCsvDisplayText": "CSV",
    "settitngstext": "إعدادات",
    "addFieldTitle": "إضافة حقل",
    "enterDisplayText": "إدخال نص العرض",
    "setScale": "تعيين مقياس",
    "outputDisplay": "نص العرض",
    "saveToLayerHelp": "<p>سيتم عرض الطبقة ذات الشروط التالية :<br/><li>يجب أن يكون للطبقة قدرات تحريرية أي \"الإنشاء\" و\"الحذف\" و\"التحديث\"</li><li>يجب أن يكون للطبقة حقلان باسم ونوع البيانات:</li><ul><li>اسم المعلمة (حقل نوع السلسلة)</li><li>معرف المشروع (حقل نوع الدليل)</li></ul><p/>"
  },
  "summaryTab": {
    "title": "الملخص",
    "summaryFieldsetText": "إعدادات الملخص",
    "inputOutput": "الإدخالات/المخرجات",
    "field": "حقول",
    "operator": "عوامل تشغيل",
    "inputOperatorCountOption": "العدد",
    "outputOperatorCountOption": "العدد",
    "outputOperatorSkipCountOption": "تخطي العد",
    "fieldOperatorSumOption": "مجموع",
    "fieldOperatorMinOption": "الحد الأدنى",
    "fieldOperatorMaxOption": "الحد الأقصى",
    "fieldOperatorMeanOption": "المتوسط",
    "expressionAddButtonText": "إضافة",
    "expressionVerifyButtonText": "تحقق من",
    "summaryEditorText": "نص الملخص"
  },
  "generalSettings": {
    "title": "إعدادات عامة",
    "displayTextForButtonLegend": "عرض النص لزر \"التشغيل\"",
    "displayTextforButtonDefaultValue": "تشغيل",
    "displayTextForButton": "نص العرض",
    "autoZoomAfterTrace": "خيارات التكبير/التصغير",
    "zoomText": "التكبير/التصغير بعد التتبع"
  },
  "validationErrorMessage": {
    "webMapError": "لا توجد طبقات متاحة في خريطة الويب. يرجى تحديد خريطة ويب صالحة.",
    "inputTypeFlagGreaterThanError": "لا يمكن أن يكون إدخال علم النوع أكثر من واحد.",
    "inputTypeFlagLessThanError": "يجب توافر علم نوع واحد من على الأقل.",
    "inputTypeBarrierErr": "لا يمكن أن يكون حاجز النوع أكثر من واحد.",
    "inputTypeSkipErr": "لا يمكن أن يكون تخطي النوع أكثر من واحد.",
    "displayTextForButtonError": "لا يمكن أن يكون نص العرض للزر \"تشغيل\" فارغًا.",
    "UnableToLoadGeoprocessError": "تعذر تحميل خدمة المعالجة الجغرافية.",
    "invalidSummaryExpression": "تعبير غير صالح.",
    "validSummaryExpression": "نجاح!",
    "invalidProjectSettings": "إعدادات مشروع غير صحيحة.<br/> يرجى تحديد قيمة صحيحة في '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "تلميح: ينبغي تقديم علامة عرض للوحة نتيجة معلمة الإخراج.",
    "displayTextHint": "تلميح: سيتم عرض هذا في لوحة التفاصيل لمعلمة الإخراج هذه.",
    "inputTextHint": "تلميح: أنشئ تعبيرك أعلاه عن طريق تحديد أسماء الإدخال والإخراج والحقول.",
    "expressionHint": "تلميح: حدد البنود وانقر فوق إضافة لإنشاء التعبير."
  }
});