define({
  "_widgetLabel": "Redzamība",
  "observerLocation": "Vērotāja novietojums",
  "formatIconTooltip": "Formatēt ievadi",
  "addPointToolTip": "Pievienot vērotāja novietojumu",
  "fieldOfView": "Redzamais lauks",
  "useMilsText": "Leņķiem izmantot miliradiānus",
  "observerHeight": "Vērotāja augstums",
  "minObsDistance": "Minimālais novērojamais attālums",
  "maxObsDistance": "Maksimālais novērojamais attālums",
  "taskURLError": "Logrīka konfigurācijas failā ir iekļauts nesasniedzams vietrādis URL. Lūdzu, sazinieties ar sistēmas administratoru",
  "taskURLInvalid": "Ar šo logrīku konfigurētais ģeoapstrādes uzdevums nav derīgs. Lūdzu, sazinieties ar sistēmas administratoru",
  "viewshedError": "Izveidojot redzamību, radās kļūda. Lūdzu, pārliecinieties, ka vērotāja novietojums ir uz paaugstinājuma virsmas.</p>",
  "validationError": "<p>Redzamības izveides veidlapai trūkst parametru vai ir nederīgi parametri. Lūdzu, pārliecinieties, vai:</p><ul><li>Ir iestatīts vērotāja nederīgs.</li><li>Vērotāja redzes lauks nav 0.</li><li>Vērotāja augstums satur derīgu vērtību.</li><li>Minimālais un maksimālais novērojamais attālums satur derīgu vērtību.</li></ul>",
  "comfirmInputNotation": "Apstiprināt ievades notāciju",
  "notationsMatch": "notācijas atbilst jūsu ievadei. Lūdzu, apstipriniet, kuras vēlaties izmantot:",
  "createBtn": "Izveidot",
  "clearBtn": "Notīrīt",
  "setCoordFormat": "Iestatīt koordinātu formātu virkni",
  "prefixNumbers": "Pievienot prefiksu '+/-' pozitīviem un negatīviem skaitļiem",
  "parseCoordinatesError": "Nevar parsēt koordinātas. Lūdzu, pārbaudiet ievadi.",
  "cancelBtn": "Atcelt",
  "applyBtn": "Lietot",
  "invalidMessage": "Ievadiet ciparu vērtību.",
  "observerRangeMessage": "Nederīgs vērotāja augstums",
  "minimumRangeMessage": "Nederīgs minimālais novērojamais diapazons",
  "maximumRangeMessage": "Maksimālajam novērojamajam diapazonam ir jābūt lielākam par Minimālo novērojamo diapazonu, un tas nevar būt lielāks par ${limit} ${units}.",
  "portalURLError": "Vietrādis (URL) uz jūsu ArcGIS Online organizāciju vai Portal for ArcGIS nav konfigurēts. Lūdzu, sazinieties ar sistēmas administratoru",
  "privilegeError": "Ar jums piešķirto lomu nevar veikt analīzi. Lai veiktu analīzi, jūsu organizācijas administratoram jāpiešķir jums atbilstīgu <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">atļauju</a>.",
  "noServiceError": "Augstuma analīzes serviss nav pieejams. Lūdzu, pārbaudiet savu ArcGIS Online organizāciju vai Portal for ArcGIS konfigurāciju.",
  "pointToolTooltip": "Noklikšķiniet, lai pievienotu vērotāja atrašanās vietu",
  "degreesLabel": "grādi",
  "milsLabel": "miliradiāni",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "GMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimālgrādi — platums/garums",
  "DDLongLatNotation": "Decimālgrādi — garums/platums",
  "DDMLatLongNotation": "Grādi, decimālminūtes — platums/garums",
  "DDMLongLatNotation": "Grādi, decimālminūtes — garums/platums",
  "DMSLatLongNotation": "Grādi, minūtes, sekundes — platums/garums",
  "DMSLongLatNotation": "Grādi, minūtes, sekundes — garums/platums",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM — joslas burts",
  "UTMHemNotation": "UTM — puslode (Z/D)"
});