define({
  "_widgetLabel": "Smart Editor",
  "_featureAction_SmartEditor": "Smart Editor",
  "noEditPrivileges": "Uw account heeft geen machtigingen om gegevens te maken of te wijzigen.",
  "widgetActive": "Actief",
  "widgetNotActive": "Niet actief",
  "pressStr": "Druk op ",
  "ctrlStr": " CTRL ",
  "snapStr": " om snapping in te schakelen",
  "noAvailableTempaltes": "Geen beschikbare templates",
  "editorCache": " - Editor Cache",
  "presetFieldAlias": "Veld",
  "presetValue": "Ingestelde waarde",
  "usePresetValues": " Gebruik ingestelde waarden (alleen nieuwe objecten)",
  "editGeometry": " Geometrie bewerken",
  "savePromptTitle": "Object opslaan",
  "savePrompt": "Wilt u het huidige object nu opslaan?",
  "deletePromptTitle": "Object verwijderen",
  "deleteAttachment": "Bijlage verwijderen",
  "deletePrompt": "Weet u zeker dat u het geselecteerde object wilt verwijderen?",
  "attachmentLoadingError": "Fout opgetreden tijdens het uploaden van bijlagen",
  "attachmentSaveDeleteWarning": "Waarschuwing: wijzigingen in bijlagen worden automatisch opgeslagen",
  "autoSaveEdits": "Slaat nieuw object automatisch op",
  "addNewFeature": "Een nieuw object maken",
  "featureCreationFailedMsg": "Kan geen nieuw record/object maken",
  "relatedItemTitle": "Gerelateerde tabel/laag",
  "relatedFeatureCount": "${layerTitle} met ${featureCount} objecten",
  "createNewFeatureLabel": "Nieuw object maken voor ${layerTitle}",
  "invalidRelationShipMsg": "Zorg ervoor dat het primaire sleutelveld: '${parentKeyField}' een geldige waarde heeft",
  "pendingFeatureSaveMsg": "Sla de objectbewerkingen op voordat u een gerelateerd object maakt.",
  "attachmentsRequiredMsg": "(*) Bijlagen zijn vereist.",
  "coordinatePopupTitle": "Verplaats object naar XY-locatie",
  "coordinatesSelectTitle": "Coördinatensysteem",
  "mapSpecialReferenceDropdownOption": "Ruimtelijke referentie van de kaart",
  "latLongDropdownOption": "Breedtegraad/lengtegraad",
  "xAttributeTextBoxLabel": "X-coordinaat:",
  "yAttributeTextBoxLabel": "Y-coördinaat:",
  "latitudeTextBoxLabel": "Breedtegraad:",
  "longitudeTextBoxLabel": "Lengtegraad:",
  "presetGroupFieldsLabel": "${groupName}' zal worden toegepast op de volgende laagvelden:",
  "presetGroupNoFieldsLabel": "'${groupName}' heeft geen bijbehorende velden",
  "groupInfoLabel": "Groepsinformatie voor '${groupName}'",
  "editGroupInfoIcon": "Groepswaarde bewerken voor ${groupName}",
  "filterEditor": {
    "all": "Alle",
    "noAvailableTempaltes": "Geen beschikbare templates",
    "searchTemplates": "Templates zoeken",
    "filterLayerLabel": "Lagen filteren"
  },
  "invalidConfiguration": "Widget is niet geconfigureerd of de lagen in de configuratie zijn niet langer in de kaart. Open de app in de bouwmodus en configureer de widget opnieuw.",
  "geometryServiceURLNotFoundMSG": "Kan geometrieservice-URL niet verkrijgen",
  "clearSelection": "Annuleren",
  "refreshAttributes": "De attributen van objecten bijwerken",
  "automaticAttributeUpdatesOn": "Automatisch objectattributen bijwerken: AAN",
  "automaticAttributeUpdatesOff": "Automatisch objectattributen bijwerken: UIT",
  "moveSelectedFeatureToGPS": "Verplaats geselecteerd object naar huidige GPS-locatie",
  "moveSelectedFeatureToXY": "Verplaats object naar XY-locatie",
  "mapNavigationLocked": "Kaartnavigatie: vergrendeld",
  "mapNavigationUnLocked": "Kaartnavigatie: ontgrendeld",
  "copyFeatures": {
    "title": "Objecten kopiëren",
    "createFeatures": "Objecten maken",
    "createSingleFeature": "1 multigeometrie-object aanmaken",
    "noFeaturesSelectedMessage": "Geen objecten geselecteerd",
    "selectFeatureToCopyMessage": "Selecteer de objecten die gekopieerd moeten worden.",
    "multipleFeatureSaveWarning": "Opmerking: het maken van meerdere objecten met behulp van de kopieerfunctie slaat alle objecten onmiddellijk op"
  },
  "addingFeatureError": "Fout bij het toevoegen van de geselecteerde objecten in de laag. Probeer het opnieuw.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' objecten niet gekopieerd.",
  "selectingFeatureError": "Fout bij het selecteren van objecten in de laag. Probeer het opnieuw.",
  "customSelectOptionLabel": "Selecteer objecten om te kopiëren",
  "noFeatureSelectedMessage": "Geen objecten geselecteerd.",
  "multipleFeatureSaveMessage": "Alle objecten zullen onmiddellijk worden opgeslagen. Wilt u doorgaan?",
  "relativeDates": {
    "dateTypeLabel": "Datumtype",
    "valueLabel": "Waarde",
    "fixed": "Vast",
    "current": "Huidige",
    "past": "Voorbij(e)",
    "future": "Toekomst",
    "popupTitle": "Waarde selecteren",
    "hintForFixedDateType": "Tip: De opgegeven datum en tijd worden gebruikt als vooraf ingestelde standaardwaarde",
    "hintForCurrentDateType": "Tip: Huidige datum en tijd worden gebruikt als vooraf ingestelde standaardwaarde",
    "hintForPastDateType": "Tip: De opgegeven waarde wordt afgetrokken van de huidige datum en tijd voor de standaardwaarde van de preset.",
    "hintForFutureDateType": "Tip: De opgegeven waarde wordt toegevoegd aan de huidige datum en tijd voor de standaardwaarde van de preset.",
    "noDateDefinedTooltip": "Geen datum vastgelegd"
  }
});