define({
  "_widgetLabel": "Perception de situation",
  "locate_incident": "Localiser l'incident",
  "reverse_geocoded_address": "Adresse la plus proche",
  "reverse_geocoded_error": "Non disponible",
  "now": "MAINTENANT",
  "wind": "VENT",
  "SUN": "DIM",
  "MON": "LUN",
  "TUE": "MAR",
  "WED": "MER",
  "THU": "JEU",
  "FRI": "VEN",
  "SAT": "SAM",
  "actionLabel": "Définir l'emplacement",
  "drawPoint": "Dessiner un point",
  "drawLine": "Dessiner une ligne",
  "drawPolygon": "Dessiner un polygone",
  "saveIncident": "Enregistrer",
  "clearIncident": "Recommencer à zéro",
  "noFeaturesFound": "Aucune entité n’a été trouvée.",
  "downloadCSV": "Télécharger",
  "sum": "Somme",
  "min": "Minimal",
  "max": "Maximal",
  "avg": "Moyenne",
  "count": "TOTAL",
  "area": "SURFACE",
  "length": "LENGTH",
  "update_btn": "Terminer",
  "delete_btn": "Supprimer",
  "get_directions": "Obtenir l’itinéraire",
  "incident": "Incident",
  "incidents": "Incidents",
  "buffer": "Zone tampon",
  "buffers": "Zones tampon",
  "weather": "Temps",
  "poweredBy": "Optimisé par",
  "_featureAction_ActionLabel": "Définir l'emplacement",
  "_featureAction_AddRemoveActionLabel": "Ajouter/supprimer un emplacement",
  "snapshot": "Dossier SnapShot créé par ID application :",
  "user_credentials": "L'utilisateur ne dispose pas de privilèges valides.",
  "snapshot_complete": "Vue figée créée correctement.",
  "snapshot_failed": "Echec de création de la vue figée.",
  "notPolySnapShot": "Veuillez spécifier une distance de zone tampon avant de créer une vue figée.",
  "notValidDownload": "Aucun résultat valide à télécharger.",
  "snapshot_append": "Capture d'écran",
  "of_append": "de",
  "layer_append": "couche",
  "downloadAll": "Tout télécharger",
  "createSnapshot": "Créer une vue figée",
  "calculated_results": "Informations synthétisées",
  "closest": "Entité la plus proche",
  "proximity": "Proximité",
  "summary": "Résumé",
  "groupedSummary": "Nombres groupés",
  "_count": "Effectif",
  "utc": "UTC",
  "approximate": "approximation",
  "snapshot_name": "Configurer le nom de la vue figée",
  "invalid_snapshot_name": "Nom de vue figée non valide."
});