define({
  root: ({
    showArcgisBasemaps: "Include Portal's basemaps",
    add: "Click to Add a New Basemap",
    edit: "Properties",
    titlePH: "Basemap Title",
    thumbnailHint: "Click the image to update",
    urlPH: "Layer URL",
    addlayer: "Add Basemap",
    warning: "Incorrect input",
    save: "Back and Save",
    back: "Back and Cancel",
    addUrl: "Add URL",
    autoCheck: "Auto Check",
    checking: "Checking...",
    result: "Saved successfully",
    spError: "All basemaps added to the gallery must have the same spatial reference.",
    invalidTitle1:"A basemap '",
    invalidTitle2:"' exists already. Please choose another title.",
    invalidBasemapUrl1: "This type of layer cannot be used as a basemap.",
    invalidBasemapUrl2: "The basemap you are adding has a different spatial reference from the current map.",
    addBaselayer: "Add Basemap Layer"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});