define({
  "settings": "Iestatījumi",
  "titleSettings": "Teksta iestatījumi",
  "imageSettings": "Attēlu iestatījumi",
  "backgroundColor": "Fona krāsa",
  "alignment": "Līdzinājums",
  "textSize": "Teksta lielums",
  "textColor": "Teksta krāsa",
  "dataSource": "Datu avots",
  "chartSettings": "Diagrammas iestatījumi",
  "data": "Dati",
  "dataLabels": "Datu nosaukums",
  "displayMode": "Rādīšanas režīms",
  "featureOption": "Rādīt vērtības pēc elementa",
  "categoryOption": "Rādīt vērtības pēc kategorijas",
  "countOption": "Rādīt elementu skaitus pēc kategorijas",
  "fieldOption": "Rādīt atribūtu vērtības kā diagrammas",
  "categoryField": "Kategorijas lauks",
  "labelField": "Lauka nosaukums",
  "valueFields": "Vērtību lauki",
  "operation": "Operācija",
  "sumOption": "Summa",
  "averageOption": "Vidējais",
  "minOption": "Minimums",
  "maxOption": "Maksimums",
  "dataFormat": "Datu formāts",
  "decimalPlaces": "Decimāldaļu vietas",
  "prefix": "Prefikss",
  "suffix": "Sufikss",
  "dataType": "Datu tips",
  "featureCount": "Elementu skaits",
  "fieldStatistics": "Lauka statistika",
  "display": "Parādīt",
  "chartColor": "Diagrammas krāsa",
  "horizontalAxis": "Horizontālā ass",
  "verticalAxis": "Vertikālā ass",
  "legend": "Apzīmējumi",
  "position": "Pozīcija",
  "top": "Augšdaļā",
  "bottom": "Lejasdaļā",
  "useDataSourceSelection": "Izmantot izvēli",
  "dataSourceFilterByExtent": "Filtrēt pēc pārklājuma",
  "changeTemplate": "Mainīt veidni",
  "numberSettings": "Skaitļu iestatījumi",
  "gaugeSettings": "Mērījumu iestatījumi",
  "indicators": "Indikatori",
  "ifValue": "Ja vērtība",
  "and": "un",
  "numberOperatorIsLessThan": "ir mazāka nekā",
  "numberOperatorIsGreaterThan": "ir lielāka nekā",
  "numberOperatorIsBetween": "ir starp",
  "numberOperatorIsEqual": "ir vienāda ar",
  "numberOperatorIsNotEqual": "nav vienāda ar",
  "then": "Tad",
  "ratio": "Koeficients",
  "trueValue": "Patiesa vērtība",
  "changeValueColor": "mainīt vērtības krāsu uz",
  "changeGaugeColor": "mainīt mērījuma krāsu uz",
  "setIndicatorIcon": "iestatīt indikatora ikonu kā",
  "icons": "Ikonas",
  "style": "Stils",
  "placement": "Novietojums",
  "left": "Pa kreisi",
  "replace": "Aizstāt",
  "right": "Pa labi",
  "color": "Krāsa",
  "sortBy": "Kārtot pēc",
  "labelAxis": "Nosaukums",
  "valueAxis": "Vērtība",
  "minPeriod": "Minimālais periods",
  "automatic": "Automātiski",
  "periodsWithOutRecords": "Periodi bez ierakstiem",
  "nullValue": "Nulles vērtība",
  "calculatedAsZero": "Aprēķināts kā nulle",
  "ignored": "Ignorēts",
  "maxCategories": "Maksimālās kategorijas",
  "useLayerSymbology": "Izmantot slāņa simbolizāciju",
  "dataRange": "Datu diapazons",
  "targetValue": "Mērķa vērtība",
  "currentValue": "Pašreizējā vērtība",
  "gaugeColor": "Mērījumu krāsa",
  "min": "Minimums",
  "max": "Maksimums",
  "displayValueIn": "Rādīt vērtību, izmantojot",
  "noData": "Nav datu",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "P",
  "billionAbbreviation": "G",
  "warning": "Brīdinājums",
  "noSettingWaring1": "Noklikšķiniet uz elementa, lai iestatītu tā rekvizītus.",
  "noSettingWaring2": "Velciet, lai mainītu elementa izmērus vai secību.",
  "donNotShowAgain": "Vairs nerādīt",
  "changeTemplateWarning": "Tiks izdzēsti visi jūsu iestatījumi, un tiks atvērta jauna, tukša veidne.",
  "requiredFieldWarning": "Šī vērtība ir obligāta:",
  "dataSourceNotSet": "Iestatiet datu avotu.",
  "addIndicatorTip": "Pievienot indikatoru",
  "chooseTemplatePopupTitle": "Izvēlēties veidni",
  "stringsInTemplate": {
    "name_number": "Skaitlis",
    "name_gauge": "Mērījumi",
    "name_vertical_gauge": "Vertikāls mērījums",
    "name_horizontal_gauge": "Horizontāls mērījums",
    "name_pie_chart": "Sektoru diagramma",
    "name_column_chart": "Stabiņu diagramma",
    "name_bar_chart": "Joslu diagramma",
    "name_line_chart": "Līniju diagramma",
    "titleOfTheInfographic": "INFOGRAFIKAS VIRSRAKSTS",
    "description": "Apraksts: papildinformācija par šo infografiku."
  }
});