define({
  "_widgetLabel": "Ağ İzleme",
  "_featureAction_NetworkTraceSkip": "İzde atla",
  "_featureAction_NetworkTraceUnskip": "Konumları Atla’dan kaldır",
  "removedFromSkipLocations": "Konumları Atla’dan kaldırıldı",
  "alreadyRemovedFromSkipLocations": "Konumları Atla’dan zaten kaldırıldı",
  "locationSkipped": "Konum atlandı",
  "configError": "Araç uygun şekilde yapılandırılmamış.",
  "geometryServiceURLNotFoundMSG": "Geometri Servisi URL’si alınamıyor",
  "clearButtonValue": "Temizle",
  "GPExecutionFailed": "İzleme tamamlanamadı Yeniden deneyin.",
  "backButtonValue": "Geri",
  "exportToCSVSuccess": "CSV’ye aktarma başarıyla tamamlandı.",
  "lblInputLocTab": "Girdi Konumları",
  "lblBlockLocTab": "Konumları Engelle",
  "lblInputLocation": "Detay Girdisi",
  "lblBlockLocation": "Detayı Engelle",
  "lblInputLocHeader": "Girdi Konumları (0)",
  "lblBlockLocHeader": "Konumları Engelle (0)",
  "inputTabTitle": "Girdi",
  "outputTabTitle": "Çıktı",
  "exportSelectAllCheckBoxLabel": "Tümünü Seç",
  "lblSkipLocHeader": "Konumları Atla (0)",
  "lblSkipLocation": "Konum",
  "lblSkipLocTab": "Konumları Atla",
  "skipAllLocationButtonLabel": "Tüm Konumları Atla",
  "confirmSkipAllLocationsMessage": "Tüm konumlar atlanacak, devam etmek istiyor musunuz?",
  "locationAlreadySkippedMessage": "Konum önceden atlandı",
  "removeAllSkipLocationLabel": "Hepsini Kaldır",
  "newProjectOptionText": "Yeni Proje",
  "selectProject": "Proje Seç",
  "saveButtonLabel": "Kaydet",
  "exportToCSVText": "CSV’ye Aktar",
  "editProjectAttributesToolTip": "Proje Özniteliklerini Düzenle",
  "projectNameLabel": "Proje Adı",
  "saveProjectPopupTitle": "Kaydet",
  "saveAsLabel": "Farklı Kaydet",
  "saveChangesMsg": "Değişikliklerinizi <b>${loadProjectDropdownlabel}</b> projesine mi, yoksa yeni bir proje olarak mı kaydetmek istiyorsunuz?",
  "creatingNewProjectErrorMessage": "Yeni proje oluşturulurken hata oluştu. Yeniden deneyin.",
  "projectNameFetchingErr": "Mevcut proje adları alınırken hata oluştu. Yeniden deneyin.",
  "projectAttributeLoadingErr": "Proje öznitelikleri yüklenirken hata oluştu. Yeniden deneyin.",
  "attributeUpdatedMsg": "Öznitelikler başarılı bir şekilde güncellendi.",
  "projectAttributeUpdatingErr": "Proje öznitelikleri güncellenirken hata oluştu.",
  "loadingProjectDetailsErrorMessage": "Bayraklar, engeller ve atlanacak konumlar alınırken hata oluştu. Yeniden deneyin.",
  "savingProjectDetailsErr": "Proje ayrıntıları kaydedilirken hata oluştu. Lütfen projeyi yeniden kaydetmeyi deneyin.",
  "updatingOutagePolygonErr": "Kesinti çokgeni güncellenirken hata oluştu. Lütfen projeyi yeniden kaydetmeyi deneyin.",
  "deletingExistingPolygonErr": "Mevcut kesinti çokgeni silinirken hata oluştu. Lütfen projeyi yeniden kaydetmeyi deneyin.",
  "loadingProjectFeaturesErr": "Proje detayları yüklenirken hata oluştu. Lütfen projeyi yeniden yüklemeyi deneyin.",
  "addingProjectFeaturesErr": "Proje detayları eklenirken hata oluştu. Lütfen projeyi yeniden kaydetmeyi deneyin.",
  "deletingExistingProjectFeaturesErr": "Mevcut proje detayları silinirken hata oluştu. Lütfen projeyi yeniden kaydetmeyi deneyin.",
  "projectNotFoundErr": "Proje bulunamadı",
  "projectLayersNotFound": "Yapılandırılan Proje ayarı katmanları haritada kullanılabilir değil. Araç, ‘Çizim modu’nda yüklenecek.",
  "fetchingOutagePolygonMessage": "Kesinti çokgeni alınırken hata oluştu. Lütfen projeyi yeniden yüklemeyi deneyin.",
  "projectNameExistsMessage": "Proje adı zaten var. Lütfen benzersiz proje adı girin.",
  "fetchingProjectNamesErrorMessage": "Mevcut proje adları alınırken hata oluştu. Lütfen projeyi yeniden kaydetmeyi deneyin.",
  "enterProjectNameMessage": "Lütfen proje adı girin.",
  "projectLengthErrorMessage": "Proje adı bundan büyük olamaz:",
  "gpServiceNotAccessible": "Hesabınızın, bu izlemeyi gerçekleştirmek için gerekli hizmete erişimi yok.",
  "loadingClonedLayerErrorMessage": "Klonlanan detay katmanı yüklenirken hata oluştu. Yeniden deneyin.",
  "addingFeatureInClonedLayerError": "Klonlanan detay katmanına grafik eklenirken hata oluştu. Yeniden deneyin.",
  "selectingFeatureInClonedLayerError": "Klonlanan detay katmanında grafik seçilirken hata oluştu. Yeniden deneyin.",
  "filteredProjectError": "Filtrelenen proje detaylarının alınması kontrol edilirken hata oluştu. Yeniden deneyin.",
  "filteredProjectMessage": "Seçilen proje öznitelikleri, web haritası veya başka bir araçtan uygulanan filtreler nedeniyle kullanılabilir değil. Filtreleri temizleyin ve yeniden deneyin.",
  "filteredProjectLoadMessage": "Projeniz artık kullanılamıyor. Lütfen aktif bir proje seçin.",
  "defaultValueForRunButton": "Çalıştır",
  "closeButtonLabel": "Kaldır"
});