define({
  "_widgetLabel": "Rastreio de rede",
  "_featureAction_NetworkTraceSkip": "Ignorar o Rastreio",
  "_featureAction_NetworkTraceUnskip": "Remover de Ignorar localizações",
  "removedFromSkipLocations": "Removido de Ignorar localizações",
  "alreadyRemovedFromSkipLocations": "Já removido de Ignorar localizações",
  "locationSkipped": "Localização ignorada",
  "configError": "O widget não está corretamente configurado.",
  "geometryServiceURLNotFoundMSG": "Não é possível obter o URL do Serviço de Geometria",
  "clearButtonValue": "Apagar",
  "GPExecutionFailed": "Não foi possível concluir o rastreio. Tente novamente.",
  "backButtonValue": "Voltar",
  "exportToCSVSuccess": "A exportação para CSV foi concluída com êxito.",
  "lblInputLocTab": "Introduzir Localizações",
  "lblBlockLocTab": "Bloquear Localizações",
  "lblInputLocation": "Introduzir Elemento",
  "lblBlockLocation": "Bloquear Elemento",
  "lblInputLocHeader": "Introduzir Localizações (0)",
  "lblBlockLocHeader": "Bloquear Localizações (0)",
  "inputTabTitle": "Introdução",
  "outputTabTitle": "Saída",
  "exportSelectAllCheckBoxLabel": "Selecionar Tudo",
  "lblSkipLocHeader": "Ignorar Localizações (0)",
  "lblSkipLocation": "Localização",
  "lblSkipLocTab": "Ignorar Localizações",
  "skipAllLocationButtonLabel": "Ignorar Todas as Localizações",
  "confirmSkipAllLocationsMessage": "Todas as localizações serão ignoradas, pretende continuar?",
  "locationAlreadySkippedMessage": "Localização já ignorada",
  "removeAllSkipLocationLabel": "Remover Tudo",
  "newProjectOptionText": "Novo Projecto",
  "selectProject": "Selecionar Projeto",
  "saveButtonLabel": "Guardar",
  "exportToCSVText": "Exportar para CSV",
  "editProjectAttributesToolTip": "Editar Atributos do Projeto",
  "projectNameLabel": "Nome do projeto",
  "saveProjectPopupTitle": "Guardar",
  "saveAsLabel": "Guardar Como",
  "saveChangesMsg": "Pretende guardar as suas alterações para <b>${loadProjectDropdownlabel}</b> ou guardar como novo projeto?",
  "creatingNewProjectErrorMessage": "Erro ao criar novo projeto. Tente novamente.",
  "projectNameFetchingErr": "Erro ao obter nomes de projeto existentes. Tente novamente.",
  "projectAttributeLoadingErr": "Erro ao carregar atributos do projeto. Tente novamente.",
  "attributeUpdatedMsg": "Atributos atualizados com êxito.",
  "projectAttributeUpdatingErr": "Erro ao atualizar atributos do projeto.",
  "loadingProjectDetailsErrorMessage": "Erro ao obter bandeiras, barreiras e ignorar localizações. Tente novamente.",
  "savingProjectDetailsErr": "Erro ao guardar detalhes do projeto. Tente guardar novamente o projeto.",
  "updatingOutagePolygonErr": "Erro ao atualizar polígono de interrupção. Tente guardar novamente o projeto.",
  "deletingExistingPolygonErr": "Erro ao eliminar polígono de interrupção existente. Tente guardar novamente o projeto.",
  "loadingProjectFeaturesErr": "Erro ao carregar elementos do projeto. Tente carregar novamente o projeto.",
  "addingProjectFeaturesErr": "Erro ao adicionar elementos do projeto. Tente guardar novamente o projeto.",
  "deletingExistingProjectFeaturesErr": "Erro ao eliminar elementos do projeto existentes. Tente guardar novamente o projeto.",
  "projectNotFoundErr": "Projeto não encontrado",
  "projectLayersNotFound": "As camadas de definições do Projeto configurado não estão disponíveis no mapa. O widget será carregado em \"Modo de desenho\".",
  "fetchingOutagePolygonMessage": "Erro ao obter polígono de interrupção. Tente carregar novamente o projeto.",
  "projectNameExistsMessage": "O nome do projeto já existe. Utilize um nome de projeto único.",
  "fetchingProjectNamesErrorMessage": "Erro ao obter nomes de projeto existentes. Tente guardar novamente o projeto.",
  "enterProjectNameMessage": "Introduza um nome de projeto.",
  "projectLengthErrorMessage": "O nome do projeto não pode ser maior do que",
  "gpServiceNotAccessible": "A sua conta não tem acesso ao serviço necessário para realizar este rastreio.",
  "loadingClonedLayerErrorMessage": "Erro ao carregar a camada de elementos clonada. Tente novamente.",
  "addingFeatureInClonedLayerError": "Erro ao adicionar gráficos à camada de elementos clonada. Tente novamente.",
  "selectingFeatureInClonedLayerError": "Erro ao selecionar os gráficos na camada de elementos clonada. Tente novamente.",
  "filteredProjectError": "Erro ao verificar a obtenção de detalhes de projeto filtrados. Tente novamente.",
  "filteredProjectMessage": "Os atributos do projeto selecionados não estão disponíveis devido aos filtros aplicados a partir do mapa web ou de outro widget. Limpe o(s) filtro(s) e tente novamente.",
  "filteredProjectLoadMessage": "O seu projeto já não se encontra disponível. Selecione um projeto ativo.",
  "defaultValueForRunButton": "Executar",
  "closeButtonLabel": "Remover"
});