define({
  "tabs_section_Label": "Вкладки",
  "addTab": "Додати вкладку",
  "layerName": "Шар",
  "layerType": "Тип аналізу",
  "layerLabel": "Напис",
  "actions": "Дії",
  "closest": "Найближчий об'єкт",
  "proximity": "Наближеність",
  "summary": "Коротка інформація",
  "select_lbl": "-- Вибрати --",
  "general_setting_Label": "Загальні налаштування",
  "units_text_lbl": "Одиниці відстані",
  "miles": "Милі",
  "kilometers": "Кілометри",
  "feet": "Фути",
  "meters": "Метри",
  "yards": "Ярди",
  "nauticalMiles": "Морські милі",
  "maximum_distance_lbl": "Максимальна відстань до найближчого об'єкту",
  "buffer_text_lbl": "Напис буфера",
  "buffer_lbl": "Буферна відстань",
  "buffer_max_lbl": "Максимальна буферна відстань",
  "buffer_min_lbl": "Мінімальна буферна відстань",
  "routing_checkBox": "Активувати побудування маршруту",
  "weather_Label": "Опції погоди",
  "weather_checkBox": "Включити інформацію про погоду",
  "weather_celsius": "Цельсії-кілометри",
  "selectLayers": "Вибрати погодні шари",
  "currentlySelectedLayer": "Поточні вибрані погодні шари",
  "missingTabLabel": "Щонайменше одна вкладка не має свого напису",
  "cancel": "Скасувати",
  "ok": "Ok",
  "missingLayerInWebMap": "Робочі шари не знайдено.",
  "selectFields": "Вибрати поля",
  "addField": "Додати поле",
  "sum": "СУМА",
  "min": "МІН.",
  "max": "МАКС.",
  "avg": "СЕР.",
  "count": "ЛІЧИЛЬНИК",
  "area": "ПЛОЩА",
  "length": "ДОВЖИНА",
  "count_checkBox": "Показати лічильник",
  "area_checkBox": "Показати площу",
  "length_checkBox": "Показати довжину",
  "max_records": "Досягнуто максимальне обмеження",
  "disable_checkBox": "Деактивувати керування видимістю шару",
  "optional_lbl": "Необов’язкові написи",
  "incident_lbl": "Інцидент",
  "locate_lbl": "Знайти інцидент"
});