define({
  "searchTabTitle": "원본 설정 검색",
  "routeTabTitle": "경로 설정",
  "add": "검색 원본 추가",
  "addGeocoder": "지오코더 추가",
  "geocoder": "지오코더",
  "setLayerSource": "레이어 원본 설정",
  "setGeocoderURL": "지오코더 URL 설정",
  "searchableLayer": "피처 레이어",
  "name": "이름",
  "countryCode": "국가 또는 지역 코드",
  "countryCodeEg": "예시: ",
  "countryCodeHint": "이 값을 비워 두면 모든 국가와 지역이 검색됩니다.",
  "showInfoWindowOnSelect": "발견한 피처 또는 위치에 대해 팝업 보기",
  "showInfoWindowOnSelect2": "피처나 위치를 찾은 경우 팝업을 표시합니다.",
  "searchInCurrentMapExtent": "현재 맵 범위에서만 검색",
  "setSearchFields": "검색 필드 설정",
  "set": "설정",
  "fieldSearchable": "검색 가능",
  "zoomScale": "확대 축척",
  "locatorUrl": "지오코더 URL",
  "locatorName": "지오코더 이름",
  "locatorExample": "사례",
  "locatorWarning": "해당 지오코딩 서비스 버전은 지원되지 않습니다. 지오코딩 서비스 10.1 이상이 위젯에서 지원됩니다.",
  "locatorTips": "지오코딩 서비스에서 추천 기능을 지원하지 않기 때문에 추천을 사용할 수 없습니다.",
  "layerSource": "레이어 원본",
  "searchLayerTips": "피처 서비스에서 페이지 매김 기능을 지원하지 않기 때문에 제안 사항을 사용할 수 없습니다.",
  "placeholderText": "플레이스 홀더 텍스트",
  "searchFields": "검색 필드",
  "displayField": "디스플레이 필드",
  "exactMatch": "정확히 일치",
  "maxSuggestions": "최대 추천 수",
  "maxResults": "최대 결과",
  "enableLocalSearch": "로컬 검색 사용",
  "minScale": "최소 축척",
  "minScaleHint": "맵 축척이 이 축척보다 큰 경우 로컬 검색이 적용됨",
  "radius": "반경",
  "radiusHint": "위치와 가장 가까운 후보가 제일 먼저 반환되도록 지오코딩 후보의 순위를 올리는 데 사용되는 현재 맵 중심 주변 영역의 반경을 지정함",
  "invalidUrlTip": "${URL} URL이 잘못되었거나 접근할 수 없습니다.",
  "routeUrl": "경로 URL",
  "geocoderOptions": "지오코더 옵션",
  "autoComplete": "자동 완성",
  "maximumSuggestions": "최대 추천 수",
  "minCharacters": "최소 문자",
  "searchDelay": "검색 지연",
  "placeholder": "플레이스홀더",
  "routeOptions": "경로 옵션",
  "directionsLanguage": "길찾기 언어",
  "directionsLengthUnits": "길찾기 길이 단위",
  "directionsOutputType": "길찾기 결과 유형",
  "impedanceAttribute": "임피던스 속성",
  "kilometers": "킬로미터",
  "miles": "마일",
  "meters": "미터",
  "feet": "피트",
  "yards": "야드",
  "nauticalMiles": "해리",
  "parametersTip": "매개변수를 올바르게 설정하세요.",
  "complete": "완료",
  "completeNoEvents": "완료(이벤트 없음)",
  "instructionsOnly": "지침만",
  "standard": "표준",
  "summaryOnly": "요약만",
  "travelModesUrl": "이동 모드 URL",
  "searchPlaceholder": "주소 또는 위치 찾기",
  "trafficLayerUrl": "교통량 레이어 URL",
  "barrierLayerUrl": "장애물 레이어 URL",
  "presetDestinations": "경유지 프리셋",
  "startPoint": "시작점",
  "endPoint": "끝점",
  "destinationHolder": "주소 또는 좌표",
  "optional": "선택 사항입니다.",
  "barrierLayers": "장애물 레이어",
  "pointBarrier": "포인트 장애물",
  "lineBarrier": "라인 장애물",
  "polygonBarrier": "폴리곤 장애물",
  "noPointBarrier": "포인트 경계 선택",
  "noLineBarrier": "라인 경계 선택",
  "noPolygonBarrier": "폴리곤 경계 선택"
});