define({
  "tabs_section_Label": "Вкладки",
  "addTab": "Додати вкладку",
  "layerName": "Шар",
  "layerType": "Тип аналізу",
  "layerLabel": "Напис",
  "actions": "Дії",
  "closest": "Найближчий об'єкт",
  "proximity": "Наближеність",
  "summary": "Коротка інформація",
  "select_lbl": "-- Вибрати --",
  "general_setting_Label": "Загальні налаштування",
  "units_text_lbl": "Одиниці відстані",
  "maximum_distance_lbl": "Максимальна відстань до найближчого об'єкту",
  "buffer_text_lbl": "Напис буфера",
  "buffer_lbl": "Буферна відстань",
  "buffer_max_lbl": "Максимальна буферна відстань",
  "buffer_min_lbl": "Мінімальна буферна відстань",
  "buffer_default_lbl": "Буферна відстань за замовчуванням",
  "not_less_than_max": "Відстань повинна бути менше максимальної буферної відстані",
  "not_between": "Відстань повинна бути між мінімальною та максимальною буферною відстанню",
  "not_more_than_min": "Відстань повинна бути більше мінімальної буферної відстані",
  "not_valid_number": "Повинно бути дійсним числом",
  "invalid_value": "Значення ${type} недійсне",
  "routing_checkBox": "Активувати побудову маршруту",
  "weather_removed_message": "Опції погоди більше недоступні для цього віджету.",
  "currentlySelectedLayer": "Вибрати з шарів карти",
  "missingTabLabel": "Щонайменше одна вкладка не має свого напису",
  "missingLayerInWebMap": "Робочі шари не знайдено.",
  "selectFields": "Вибрати поля",
  "addField": "Додати поле",
  "sum": "Сума",
  "min": "Мінімум",
  "max": "Максимум",
  "avg": "Середнє",
  "count": "ЛІЧИЛЬНИК",
  "area": "ПЛОЩА",
  "length": "ДОВЖИНА",
  "count_checkBox": "Відображати лічильник об'єктів",
  "area_checkBox": "Відображати суму площі",
  "length_checkBox": "Відображати суму довжини",
  "max_records": "Досягнуто максимальне обмеження",
  "save_label": "Зберегти опції",
  "save_checkbox": "Активувати збереження",
  "report_label": "Опції звіту",
  "report_checkbox": "Активувати звіт",
  "csv_label": "Опції CSV",
  "display_label": "Опції відображення",
  "display_checkbox": "Відображати підсумкові об'єкти",
  "setSelectionColor": "Задати колір вибору",
  "snapshot_label": "Опції знімку",
  "snapshot_checkbox": "Активувати знімок",
  "must_select_template": "Виберіть один із шаблонів редагування у пункті «Опції збереження».",
  "count_label": "Напис лічильника",
  "area_label": "Напис площі",
  "length_label": "Напис довжини",
  "invalid_string_width": "Значення занадто довге. ",
  "layer_type_not_supported": "Тип шару не підтримується",
  "groupedSummary": "Згруповані лічильники",
  "groupByField": "Згрупувати за полем",
  "labelType": "Приєднати напис",
  "prefix": "Як префікс",
  "suffix": "Як суфікс",
  "need_group_field": "Використовуйте дію редагування для визначення параметру «Згрупувати за полем».",
  "fieldTitle": "Поле",
  "typeTitle": "Тип",
  "actionsTitle": "Дії",
  "save_point_checkbox": "Зберегти точки",
  "save_line_checkbox": "Зберегти лінії",
  "save_poly_checkbox": "Зберегти полігони",
  "no_valid_popup_fields": "Відсутні дійсні поля у спливаючому вікні. Використовуйте дію редагування для визначення поля.",
  "no_valid_fields": "Відсутні дійсні поля. Використовуйте дію редагування для визначення опцій відображення.",
  "incident_label": "Напис закладки",
  "locate_incident_label": "Напис області інтересу",
  "incident": "Інцидент",
  "locate_incident": "Знайти інцидент",
  "buffer_value": "Буферна відстань",
  "tab_options": "Аналіз",
  "export_options": "Виведення",
  "instruction_save": "Зберегти місце розташування для сервісу об'єктів.",
  "instruction_snapshot": "Створити веб-карту на основі місця розташування.",
  "instruction_report": "Створити друкований звіт для місця розташування.",
  "instruction_all_fields": "Експорт полів із завантаженням CSV.",
  "data_label": "Налаштування виведення даних",
  "layer_error": "Шар відсутній або недійсний.",
  "visibility_checkBox": "Деактивувати керування видимістю шару",
  "allFieldsLabel": "Всі поля",
  "configuredPopUpFieldsLabel": "Налаштовані спливаючі поля",
  "analysisTypeFieldsLabel": "Поля типу аналізу",
  "reportOptionsMsg": "Повинна бути обрана щонайменше одна опція звіту",
  "analysisSummaryLabelForReport": "Статистика типу аналізу",
  "popUpSummaryLabelForReport": "Статистика налаштованих спливаючих полів",
  "downloadTab": {
    "reportLegend": "Налаштування звіту",
    "textColorLabel": "Вибрати колір для заголовку стовпця",
    "setButtonLabel": "Задати",
    "printGPServiceLabel": "URL сервісу друку",
    "logoLabel": "Логотип",
    "logoChooserHint": "Клацніть на значку зображення, щоб змінити зображення",
    "footnoteLabel": "Виноска"
  },
  "roundValue": "Округлити до",
  "roundValueTitle": "Округлені значення полів",
  "truncateValue": "Скоротити до",
  "truncateValueTitle": "Скорочені значення полів",
  "significantFigures": "значущі цифри",
  "fieldOptions": "Опції полів",
  "modifyValues": "Змінити значення полів",
  "validatePlaces": "Має бути цілим числом",
  "onlyDouble": "Додаткові опції поля підтримуються тільки для числових полів.",
  "layerNotAvalible": "Шар не знайдено",
  "missingLayer": "Ім'я: ${name}",
  "missingLayerHint": "Один або більше шарів, на які є посилання в цій конфігурації, на поточний момент не доступні.",
  "drawGeodesic": "Намалювати геодезичні форми"
});