define({
  "enableUndoRedo": "Visszavonás/Újra engedélyezése",
  "toolbarVisible": "Az eszköztár látható",
  "toolbarOptions": "Eszköztár beállításai",
  "mergeVisible": "Összeilleszt",
  "cutVisible": "Kivágás",
  "reshapeVisible": "Átformázás",
  "back": "Vissza",
  "label": "Réteg",
  "edit": "Szerkeszthető",
  "update": "Geometria frissítésének tiltása",
  "fields": "Mezők",
  "actions": "Műveletek",
  "editpageName": "Név",
  "editpageAlias": "Aliasnév",
  "editpageVisible": "Látható",
  "editpageEditable": "Szerkeszthető",
  "noLayers": "Nem érhetők el szerkeszthető vektoros rétegek",
  "configureFields": "Rétegmezők konfigurálása",
  "useFilterEdit": "Vektoros elem sablonszűrőjének használata",
  "display": "Megjelenítés",
  "autoApplyEditWhenGeometryIsMoved": "Szerkesztés automatikus alkalmazása a geometria áthelyezésekor",
  "snappingTolerance": "Hozzáillesztési tolerancia beállítása pixelben",
  "popupTolerance": "Attribútumszerkesztő felugró ablak toleranciájának beállítása pixelben",
  "stickyMoveTolerance": "Ragadós mozgatási tolerancia beállítása pixelben",
  "usingSaveButton": "Ne alkalmazza az attribútumok beállításait a Mentés gombra kattintás előtt",
  "generalSettings": "Általános beállítások",
  "editableLayersSetting": "Szerkeszthető rétegek beállításai",
  "honorTheWebMapSetting": "A webtérkép beállításainak betartása.",
  "honorTheWebMapSettingTip1": "Ilyen beállítások például a következők:",
  "honorTheWebMapSettingTip2": "Mely rétegek szerkeszthetők",
  "honorTheWebMapSettingTip3": "A megjeleníteni és szerkeszteni kívánt mezők.",
  "honorTheWebMapSettingTip4": "Mező aliasa, sorrendje és formátuma",
  "customSettings": "Egyéni beállítások"
});