define({
  "_widgetLabel": "עריכה",
  "_featureAction_Edit": "ערוך",
  "title": "בחר תבנית בכדי ליצור ישויות",
  "pressStr": "הקש על ",
  "ctrlStr": " CTRL ",
  "snapStr": " כדי להפעיל הצמדה",
  "close": "סגור",
  "featureLayers": "שכבות ישויות",
  "searchTemplates": "תבניות חיפוש",
  "noAvailableTempaltes": "אין תבניות זמינות",
  "noCanCreateLayerAreCurrentlyVisible": "אף שכבה ניתנת ליצירה אינה נראית כעת.",
  "layersAreInvisibleOrOutOfScaleRange": "השכבות לא גלויות או חורגות מטווח קנה המידה.",
  "relatedTables": "טבלאות מקושרות:",
  "relatedRecords": "רשומות מקושרות:",
  "noRelatedRecotds": "לא נמצאו רשומות קשורות.",
  "startToDraw": "לחץ כדי להתחיל בשרטוט",
  "startToAddPoint": "הקש להוספת נקודה",
  "editRelatedFeature": "עריכת ישות קשורה",
  "duplicateValueWarning": " לא ניתן להוסיף ערך משוכפל ב-${fieldName} של ${tableName}. הערך המשוכפל הוא: ${value}"
});