define({
  "businessAnalyst": "Üzleti elemző",
  "defineWhichInfographics": "Határozza meg, hogy mely infografikák álljanak rendelkezésre a widgetben:",
  "defineWhichReports": "Határozza meg, hogy mely jelentések álljanak rendelkezésre a widgetben:",
  "defaultValues": "Alapértelmezett értékek:",
  "disable": "Letiltás",
  "driveTime": "Vezetési idő",
  "infographics": "Infógrafika",
  "invalidValueRing": "Az értékeknek 0-1000 között kell lennie.",
  "invalidValueDTWT": "Az értékeknek 0-300 között kell lennie.",
  "km": "km",
  "miles": "mérföld",
  "minutes": "perc",
  "radius": "Sugár",
  "reports": "Jelentések",
  "rings": "Gyűrűk",
  "selectCountryOrRegion": "Válassza ki az országot vagy a régiót:",
  "thisEntryIsNotValid": "A megadott érték érvénytelen.",
  "time": "Idő",
  "walkTime": "Gyaloglási idő"
});