define({
  "symbolologyTabLabel": "Cấu hình Biểu tượng",
  "facilitiesDescription": "Lớp Cơ sở",
  "demographicsDescription": "Lớp Nhân khẩu học",
  "settingsTitle": "Thiết lập",
  "spillLocationLabel": "Vị trí Tràn",
  "spillLocationButtonLabel": "Cài đặt Cấu hình Vị trí Tràn",
  "IISettingsLabel": "Vùng Cô lập Ban đầu",
  "IIButtonLabel": "Cài đặt Cấu hình Cô lập Ban đầu",
  "PASettingsLabel": "Vùng Hành động Bảo vệ",
  "PAButtonLabel": "Cài đặt Cấu hình Hành động Bảo vệ",
  "downwindSettingsLabel": "Vùng Xuôi gió",
  "downwindButtonLabel": "Cài đặt Cấu hình Xuôi gió",
  "fireSettingsLabel": "Vùng Cô lập Hỏa hoạn",
  "fireButtonLabel": "Cài đặt Cấu hình Cô lập Hỏa hoạn",
  "bleveSettingsLabel": "Vùng Cô lập BLEVE",
  "bleveButtonLabel": "Cài đặt Cấu hình BLEVE",
  "transparency": "Độ trong suốt",
  "outline": "Viền",
  "fill": "Tô đầy (Màu chỉ áp dụng khi kiểu được thiết lập thành dạng khối)",
  "style": "Kiểu",
  "selectOpLayerLabel": "Chọn một lớp chuyên đề cho kết quả",
  "selectDefaultMeasurementLabel": "Chọn đơn vị mặc định của kết quả đo",
  "helpIconTooltip": "Danh sách lớp chuyên đề được quản lý với các lớp từ bản đồ web hiện tại là loại hình học dạng vùng.",
  "colorPicker": "Trình chọn màu",
  "lineStyles": {
    "esriSLSDash": "Gạch",
    "esriSLSDashDot": "Chấm Gạch",
    "esriSLSDashDotDot": "Gạch Chấm Chấm",
    "esriSLSDot": "Chấm",
    "esriSLSLongDash": "Nét đứt dài",
    "esriSLSLongDashDot": "Chấm đứt dài",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Nét đứt ngắn",
    "esriSLSShortDashDot": "Chấm đứt ngắn",
    "esriSLSShortDashDotDot": "Hai chấm đứt ngắn",
    "esriSLSShortDot": "Chấm ngắn",
    "esriSLSSolid": "Đậm"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Về phía sau",
    "esriSFSCross": "Gạch ngang",
    "esriSFSDiagonalCross": "Chéo",
    "esriSFSForwardDiagonal": "Chuyển tiếp",
    "esriSFSHorizontal": "Ngang",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Đậm",
    "esriSFSVertical": "Dọc"
  }
});