define({
  "_widgetLabel": "Conversió de coordenada",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Graus decimals: latitud/longitud",
  "DDLongLatNotation": "Graus decimals: longitud/latitud",
  "DDMLatLongNotation": "Graus minuts decimals: latitud/longitud",
  "DDMLongLatNotation": "Graus minuts decimals: longitud/latitud",
  "DMSLatLongNotation": "Graus minuts segons: latitud/longitud",
  "DMSLongLatNotation": "Graus minuts segons: longitud/latitud",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM: lletra de banda",
  "UTMHemNotation": "UTM: hemisferi (N/S)",
  "formatInput": "Format d'entrada",
  "copyAll": "Copia-ho tot",
  "copySuccessful": "S'ha copiat correctament",
  "copyFailed": "No es pot copiar. Utilitzeu Ctrl+C com a alternativa.",
  "parseCoordinatesError": "No es poden analitzar les coordenades. Comproveu l'entrada.",
  "comfirmInputNotation": "Confirma la notació d'entrada",
  "latLongWarningMessage": "S'ha detectat que la coordenada d'entrada té un prefix i un sufix per al valor de la latitud o la longitud, i la coordenada retornada es basa en el prefix.",
  "inputLabel": "Entrada",
  "outputLabel": "Sortida",
  "cancelButtonLabel": "Cancel·la",
  "applyButtonLabel": "Aplica",
  "posNegPrefixLabel": "Afegeix el prefix \"+/-\" als nombres positius i negatius",
  "editCoordinateDialogTitle": "Defineix la cadena de format de coordenades",
  "rememberDecisionLabel": "Recorda la meva decisió i no m'ho tornis a preguntar.<br/>",
  "coordinateInputLabel": "Introduïu les coordenades o feu clic al mapa",
  "zoomLabel": "Zoom",
  "multipleNotationLabel": "notacions trobades que coincideixen amb la vostra entrada. Confirmeu quina voleu utilitzar:",
  "copyToClipboard": "Copia al porta-retalls",
  "formatOutput": "Format de sortida",
  "addNewNotation": "Afegeix una notació nova",
  "notationAddedMessage": "Nova notació afegida",
  "addLabel": "Afegeix",
  "removeCoordinate": "Elimina la coordenada",
  "expandOutput": "Expandeix la sortida",
  "latitudeLabel": "Lat.",
  "longitudeLabel": "Long.",
  "quadrantLabel": "Quadrant",
  "keyLabel": "Clau",
  "fifteenDegreeLabel": "15° de quadrant",
  "oneDegreeLabel": "1° de quadrant",
  "eastingLabel": "Coordenada horitzontal",
  "northingLabel": "Coordenada vertical",
  "zoneLabel": "Zona",
  "bandLabel": "Banda",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Quadrat de la quadrícula",
  "hemisphereLabel": "Hemisferi",
  "addPointLabel": "Afegeix un punt"
});