define({
  "showArcgisBasemaps": "Uključi kartografske podloge Portala",
  "add": "Kliknite za dodavanje nove kartografske podloge",
  "edit": "Svojstva",
  "titlePH": "Naslov kartografske podloge",
  "thumbnailHint": "Kliknite na sliku za ažuriranje",
  "urlPH": "URL sloja",
  "addlayer": "Dodaj kartografsku podlogu",
  "warning": "Neispravan unos",
  "save": "Natrag i spremi",
  "back": "Natrag i odustani",
  "addUrl": "Dodaj URL",
  "autoCheck": "Automatska provjera",
  "checking": "Provjera...",
  "result": "Uspješno spremljeno",
  "spError": "Sve kartografske podloge koje su dodane u galeriju moraju imati istu prostornu referencu.",
  "invalidTitle1": "Kartografska podloga '",
  "invalidTitle2": "' već postoji. Odaberite drugi naslov.",
  "invalidBasemapUrl1": "Ova se vrsta sloja ne može upotrijebiti kao kartografska podloga.",
  "invalidBasemapUrl2": "Kartografska podloga koju dodajete ima drugačiju prostornu referencu od trenutačne karte.",
  "addBaselayer": "Dodaj sloj kartografske podloge"
});