define({
  "_widgetLabel": "Netzwerkverfolgung",
  "_featureAction_NetworkTraceSkip": "Bei der Verfolgung überspringen",
  "_featureAction_NetworkTraceUnskip": "Aus zu überspringenden Positionen entfernen",
  "removedFromSkipLocations": "Aus zu überspringenden Positionen entfernt",
  "alreadyRemovedFromSkipLocations": "Bereits aus zu überspringenden Positionen entfernt",
  "locationSkipped": "Position wurde übersprungen",
  "configError": "Das Widget wurde nicht ordnungsgemäß konfiguriert.",
  "geometryServiceURLNotFoundMSG": "URL des Geometrieservice kann nicht abgerufen werden",
  "clearButtonValue": "Entfernen",
  "GPExecutionFailed": "Die Verfolgung kann nicht abgeschlossen werden. Versuchen Sie es erneut.",
  "backButtonValue": "Zurück",
  "exportToCSVSuccess": "Export in CSV wurde erfolgreich abgeschlossen.",
  "lblInputLocTab": "Eingabepositionen",
  "lblBlockLocTab": "Block-Positionen",
  "lblInputLocation": "Eingabe-Feature",
  "lblBlockLocation": "Block-Feature",
  "lblInputLocHeader": "Eingabepositionen (0)",
  "lblBlockLocHeader": "Block-Positionen (0)",
  "inputTabTitle": "Eingabe",
  "outputTabTitle": "Ausgabe",
  "exportSelectAllCheckBoxLabel": "Alles auswählen",
  "lblSkipLocHeader": "Zu überspringende Positionen (0)",
  "lblSkipLocation": "Position",
  "lblSkipLocTab": "Positionen überspringen",
  "skipAllLocationButtonLabel": "Alle Positionen überspringen",
  "confirmSkipAllLocationsMessage": "Alle Positionen werden übersprungen. Möchten Sie fortfahren?",
  "locationAlreadySkippedMessage": "Position wurde bereits übersprungen",
  "removeAllSkipLocationLabel": "Alle entfernen",
  "newProjectOptionText": "Neues Projekt",
  "selectProject": "Projekt auswählen",
  "saveButtonLabel": "Speichern",
  "exportToCSVText": "In CSV exportieren",
  "editProjectAttributesToolTip": "Projektattribute bearbeiten",
  "projectNameLabel": "Projektname",
  "saveProjectPopupTitle": "Speichern",
  "saveAsLabel": "Speichern als",
  "saveChangesMsg": "Möchten Sie die Änderungen unter <b>${loadProjectDropdownlabel}</b> speichern oder als neues Projekt speichern?",
  "creatingNewProjectErrorMessage": "Fehler beim Erstellen eines neuen Projekts. Versuchen Sie es erneut.",
  "projectNameFetchingErr": "Fehler beim Abrufen von vorhandenen Projektnamen. Versuchen Sie es erneut.",
  "projectAttributeLoadingErr": "Fehler beim Laden von Projektattributen. Versuchen Sie es erneut.",
  "attributeUpdatedMsg": "Attribute wurden erfolgreich aktualisiert.",
  "projectAttributeUpdatingErr": "Fehler beim Aktualisieren von Projektattributen.",
  "loadingProjectDetailsErrorMessage": "Fehler beim Abrufen von Flags, Barrieren und zu überspringenden Positionen. Versuchen Sie es erneut.",
  "savingProjectDetailsErr": "Fehler beim Speichern von Projektdetails. Speichern Sie das Projekt erneut.",
  "updatingOutagePolygonErr": "Fehler beim Aktualisieren eines Ausfall-Polygons. Speichern Sie das Projekt erneut.",
  "deletingExistingPolygonErr": "Fehler beim Löschen von vorhandenen Ausfall-Polygonen. Speichern Sie das Projekt erneut.",
  "loadingProjectFeaturesErr": "Fehler beim Laden von Projekt-Features. Laden Sie das Projekt erneut.",
  "addingProjectFeaturesErr": "Fehler beim Hinzufügen von Projekt-Features. Speichern Sie das Projekt erneut.",
  "deletingExistingProjectFeaturesErr": "Fehler beim Löschen von vorhandenen Projekt-Features. Speichern Sie das Projekt erneut.",
  "projectNotFoundErr": "Projekt nicht gefunden",
  "projectLayersNotFound": "Konfigurierte Projekteinstellungs-Layer sind in der Karte nicht verfügbar. Das Widget wird im 'Skizzen-Modus' geladen.",
  "fetchingOutagePolygonMessage": "Fehler beim Abrufen von Ausfall-Polygonen. Laden Sie das Projekt erneut.",
  "projectNameExistsMessage": "Der Projektname ist bereits vorhanden. Verwenden Sie einen eindeutigen Projektnamen.",
  "fetchingProjectNamesErrorMessage": "Fehler beim Abrufen von vorhandenen Projektnamen. Speichern Sie das Projekt erneut.",
  "enterProjectNameMessage": "Geben Sie einen Projektnamen ein.",
  "projectLengthErrorMessage": "Der Projektname darf nicht länger sein als",
  "gpServiceNotAccessible": "Ihr Konto hat keinen Zugriff auf den Service, der zum Ausführen dieser Verfolgung erforderlich ist.",
  "loadingClonedLayerErrorMessage": "Fehler beim Laden des geklonten Feature-Layers. Versuchen Sie es erneut.",
  "addingFeatureInClonedLayerError": "Fehler beim Hinzufügen der Grafiken zum geklonten Feature-Layer. Versuchen Sie es erneut.",
  "selectingFeatureInClonedLayerError": "Fehler beim Auswählen der Grafiken im geklonten Feature-Layer. Versuchen Sie es erneut.",
  "filteredProjectError": "Fehler beim Überprüfen des Abrufs von gefilterten Projektdetails. Versuchen Sie es erneut.",
  "filteredProjectMessage": "Die ausgewählten Projektattribute sind aufgrund der angewendeten Filter aus der Webkarte oder einem anderen Widget nicht verfügbar. Löschen Sie die Filter, und versuchen Sie es erneut.",
  "filteredProjectLoadMessage": "Das Projekt ist nicht mehr verfügbar. Wählen Sie ein aktives Projekt aus.",
  "defaultValueForRunButton": "Ausführen",
  "closeButtonLabel": "Entfernen"
});