define({
  "styleText": "تغيير نمط أداة السحب",
  "vertical": "شريط عمودي",
  "horizontal": "شريط أفقي",
  "scope": "منظار",
  "barColor": "لون الشريط",
  "swipeMode": "وضع السحب",
  "singleLayer": "طبقة مفردة",
  "MultipleLayers": "طبقات متعددة",
  "allowToSwipe": "السماح بالسحب",
  "layer": "طبقة",
  "swipeByDefault": "سحب افتراضيًا",
  "defaultLayerMustBeVisible": "يجب أن تكون الطبقة الافتراضية مرئية",
  "noDefaultLayer": "يرجى تعيين الطبقات المطلوب سحبها افتراضيًا",
  "defaultLayerHolder": "انقر للتحديد",
  "selectLayers": "حدد الطبقات",
  "layerText": "حدد الطبقة/الطبقات التي تريد سحبها افتراضيًا",
  "spyglassText": "تحديد الطبقة المُراد ظهورها ضمن المنظار افتراضيًا.",
  "layerHint": "ملاحظة: إذا اكنت الطبقة مخفية بواسطة الطبقة الأعلى، فلن يؤثر السحب.",
  "isZoom": "تكبير/تصغير طبقة السحب",
  "isZooms": "تكبير/تصغير طبقة/طبقات السحب",
  "layersAvailable": "اختر الطبقات المطلوب سحبها:"
});