define({
  "_widgetLabel": "Geoprocessering",
  "_featureAction_ReceiveFeatureSet": "Indstil som input for ",
  "requiredInfo": "er obligatorisk.",
  "drawnOnMap": "Resultatet er tegnet på kortet.",
  "noToolConfig": "Ingen prækonfigureret geoprocesseringsopgave er tilgængelig",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Overfør fil",
  "selectFileToUpload": "Vælg fil...",
  "rasterFormat": "Rasterdataformat",
  "noFileSelected": "Ingen fil valgt!",
  "uploadSuccess": "Filoverførsel lykkedes!",
  "showLayerContent": "Vis lagindhold",
  "invalidUrl": "Ugyldig featuretjeneste-URL",
  "urlPlaceholder": "URL til at få adgang til dataene",
  "addShapefile": "Tilføj shapefil",
  "generateShapefileError": "Generér shapefil-fejl, kontrollér: ",
  "cleared": "Resultatet er blevet ryddet.",
  "enlargeView": "Forstår visning",
  "exportOutput": "Eksportér",
  "emptyResult": "Resultatet er tomt.",
  "useSelectedFeatureset": "Brug det/de resulterende objekt(er).",
  "closeSelectedFeatureset": "Ryd, og brug den konfigurerede input-indstilling.",
  "currentMapExtent": "Aktuel kortudstrækning",
  "generalize": "Generalisér geometrier",
  "jsonPlaceholder": "Dataenes JSON-streng",
  "chooseATable": "---Vælg en tabel---"
});