define({
  "settings": "Postavke",
  "titleSettings": "Postavke teksta",
  "imageSettings": "Postavke slike",
  "backgroundColor": "Boja pozadine",
  "alignment": "Poravnanje",
  "textSize": "Veličina teksta",
  "textColor": "Boja teksta",
  "dataSource": "Izvor podataka",
  "chartSettings": "Postavke grafikona",
  "data": "Podaci",
  "dataLabels": "Oznake podataka",
  "displayMode": "Način prikaza",
  "featureOption": "Prikaži vrijednosti geoobjekata po geoobjektu",
  "categoryOption": "Prikaži vrijednosti po kategoriji",
  "countOption": "Prikaži broj geoobjekata po kategoriji",
  "fieldOption": "Prikaži atributne vrijednosti kao grafikone",
  "categoryField": "Polje kategorije",
  "labelField": "Polje oznake",
  "valueFields": "Polja vrijednosti",
  "operation": "Radnja",
  "sumOption": "Zbroj",
  "averageOption": "Prosječno",
  "minOption": "Minimum",
  "maxOption": "Maksimum",
  "dataFormat": "Format podataka",
  "decimalPlaces": "Decimalna mjesta",
  "prefix": "Prefiks",
  "suffix": "Sufiks",
  "dataType": "Vrsta podataka",
  "featureCount": "Broj geoobjekata",
  "fieldStatistics": "Statistika polja",
  "display": "Prikaži",
  "chartColor": "Boja grafikona",
  "horizontalAxis": "Vodoravna os",
  "verticalAxis": "Okomita os",
  "legend": "Legenda",
  "position": "Položaj",
  "top": "Vrh",
  "bottom": "Dno",
  "useDataSourceSelection": "Upotrijebi odabir",
  "dataSourceFilterByExtent": "Filtriraj prema obuhvatu",
  "changeTemplate": "Promijeni predložak",
  "numberSettings": "Postavke broja",
  "gaugeSettings": "Postavke mjerača",
  "indicators": "Pokazatelji",
  "ifValue": "Vrijednost ako",
  "and": "i",
  "numberOperatorIsLessThan": "manje je od",
  "numberOperatorIsGreaterThan": "veće je od",
  "numberOperatorIsBetween": "je između",
  "numberOperatorIsEqual": "jednako je",
  "numberOperatorIsNotEqual": "nije jednako",
  "then": "Onda",
  "ratio": "Omjer",
  "trueValue": "Prava vrijednost",
  "changeValueColor": "promijeni boju vrijednosti u",
  "changeGaugeColor": "promijeni boju mjerača u",
  "setIndicatorIcon": "postavi ikonu pokazatelja kao",
  "icons": "Ikone",
  "style": "Stil",
  "placement": "Raspored",
  "left": "Lijevo",
  "replace": "Zamijeni",
  "right": "Desno",
  "color": "Boja",
  "sortBy": "Sortiraj prema",
  "labelAxis": "Oznaka",
  "valueAxis": "Vrijednost",
  "minPeriod": "Minimalno razdoblje",
  "automatic": "Automatski",
  "periodsWithOutRecords": "Razdoblja bez zapisa",
  "nullValue": "Nema vrijednosti",
  "calculatedAsZero": "Izračunato kao nula",
  "ignored": "Zanemareno",
  "maxCategories": "Maksimalne kategorije",
  "useLayerSymbology": "Upotrijebi simbologiju sloja",
  "dataRange": "Raspon podataka",
  "targetValue": "Ciljna vrijednost",
  "currentValue": "Trenutna vrijednost",
  "gaugeColor": "Boja mjerača",
  "min": "Minimum",
  "max": "Maksimum",
  "displayValueIn": "Prikaži vrijednosti u",
  "noData": "Nema podataka",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Upozorenje",
  "noSettingWaring1": "Kliknite na element za postavljanje njegovih svojstava.",
  "noSettingWaring2": "Povucite za mijenjanje veličine ili redoslijeda elementa.",
  "donNotShowAgain": "Ne prikazuj ponovo",
  "changeTemplateWarning": "Ovo će izbrisati sve vaše postavke i otvoriti novi prazni predložak.",
  "requiredFieldWarning": "Ova je vrijednosti potrebna:",
  "dataSourceNotSet": "Postavite izvor podataka.",
  "addIndicatorTip": "Dodajte pokazatelja",
  "chooseTemplatePopupTitle": "Odaberite predložak",
  "stringsInTemplate": {
    "name_number": "Broj",
    "name_gauge": "Mjerač",
    "name_vertical_gauge": "Okomiti mjerač",
    "name_horizontal_gauge": "Vodoravni mjerač",
    "name_pie_chart": "Tortni grafikon",
    "name_column_chart": "Stupčasti grafikon",
    "name_bar_chart": "Trakasti grafikon",
    "name_line_chart": "Linijski grafikon",
    "titleOfTheInfographic": "NASLOV INFOGRAFIKE",
    "description": "Opis: dodatne informacije o infografici."
  }
});