define(
   ({
    addLayer: "Legg til lag",
    layerName: "Lag",
    layerRefresh: "Oppdater",
    layerLabel: "Etikett",
    actions: "Handlinger",
    popupOk: "OK",
    popupCancel: "Avbryt",
    mainPanelTextPlaceholder: "ekskl.: TRAFIKKFORHOLD PÅ HOVEDVEIER",
    invalidInterval: "Det er bare numeriske tegn som støttes.",
    uploadImage: "Last opp bilde",
    iconColumnText: "Ikon",
    refreshInterval: "1 \"Evaluert som tid i minutter\"",
    refreshIntervalTitle: "Evaluert som tid i minutter",
    mainPanelText: "Tekst for hovedpanel",
    mainPanelIcon: "Bilde for hovedpanel",
    refreshIntervalInstruction: "Oppdateringsintervall",
    optionsText: "Alternativer",
    symbolOptionsText: "Alternativer for symboler",
    iconOptionsText: "Alternativer for ikoner",
    sympolPopupTitle: "Angi symbol",
    rdoLayer: "Lagsymbol",
    rdoCustom: "Egendefinert symbol",
    chkCluster: "Aktiver klynger",
    defineClusterSymbol: "Klyngesymbol",
    defineThemeClusterSymbol: "Klyngesymbol fra tema",
    rdoEsri: "Esri-symbol",
    rdoLayerIcon: "Bruk symbol som ikon",
    rdoCustomIcon: "Last opp egendefinert ikon",
    editCustomSymbol: "Rediger egendefinert symbol",
    editCustomIcon: "Rediger egendefinert ikon",
    missingRefreshValue: "Angi en verdi for oppdateringsintervall",
    panelIconOption: "Vis overskrift for panel",
    enableRefresh: "Aktiver lagoppdatering",
    disableRefresh: "Lagoppdatering støttes bare for geoobjektssamlinger",
    layer_type_not_supported: "Lagtypen støttes ikke: "
  })
);
