define({
  "businessAnalyst": "Business Analyst",
  "defineWhichInfographics": "तय करें कि विजेट में कौन-से इन्फ़ोग्राफ़िक उपलब्ध हैं:",
  "defineWhichReports": "तय करें कि विजेट में कौन-सी रिपोर्ट उपलब्ध हैं:",
  "defaultValues": "डिफ़ॉल्ट मान:",
  "disable": "अक्षम करें",
  "driveTime": "ड्राइविंग का समय",
  "infographics": "इन्फ़ोग्राफ़िक",
  "invalidValueRing": "मान 0 से 1,000 के बीच के होने चाहिए।",
  "invalidValueDTWT": "मान 0 से 300 के बीच के होने चाहिए।",
  "km": "किमी",
  "miles": "मील",
  "minutes": "मिनट",
  "radius": "त्रिज्या",
  "reports": "रिपोर्ट",
  "rings": "छल्ले",
  "selectCountryOrRegion": "देश या क्षेत्र का चयन करें:",
  "thisEntryIsNotValid": "यह प्रविष्टि मान्य नहीं है।",
  "time": "समय",
  "walkTime": "पैदल चलने का समय"
});