define({
  "_widgetLabel": "Analiza prijetnji",
  "threatAnalysisMainPageTitle": "Na temelju protuterorističkog vodiča JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Ulazna lokacija",
  "interactive": "Interaktivno",
  "fromCoord": "Fiksne koordinate",
  "existingFeature": "Iz postojećih geoobjekata",
  "threatAnalysisCoordInputLabel": "Lokacija prijetnje",
  "enterCoords": "Unesi koordinate",
  "threatAddPointToolTip": "Dodaj lokaciju prijetnje",
  "threatDrawPointToolTip": "Kliknite da biste dodali lokaciju",
  "threatType": "Vrsta prijetnje",
  "threatPlaceholder": "Počnite tipkati za traženje prijetnje",
  "mandatoryLabel": "Obavezna udaljenost za evakuaciju",
  "safeLabel": "Sigurna udaljenost za evakuaciju",
  "zoneTypeLabel": "Tip zone",
  "feetLabel": "Stope",
  "metersLabel": "Metri",
  "unitsLabel": "Jedinice",
  "threatGraphicLayer": "Grafika za prijetnju",
  "settingsTitle": "Postavke",
  "mandatoryButtonLabel": "Kofigurirajte obaveznu udaljenost za evakuaciju",
  "safeButtonLabel": "Konfigurirajte postavke aktivnog skloništa",
  "style": "Stil",
  "lineStyles": {
    "esriSLSDash": "Linija s crticom",
    "esriSLSDashDot": "Linija s crticom i točkom",
    "esriSLSDashDotDot": "Linija s crticom i dvije točke",
    "esriSLSDot": "Točka",
    "esriSLSLongDash": "Duga crtica",
    "esriSLSLongDashDot": "Duga crtica i točka",
    "esriSLSNull": "Nema vrijednosti",
    "esriSLSShortDash": "Kratka crtica",
    "esriSLSShortDashDot": "Kratka crtica i točka",
    "esriSLSShortDashDotDot": "Kratka crtica i dvije točke",
    "esriSLSShortDot": "Kratka točka",
    "esriSLSSolid": "Puna linija"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Unatrag",
    "esriSFSCross": "Križ",
    "esriSFSDiagonalCross": "Dijagonalno",
    "esriSFSForwardDiagonal": "Naprijed",
    "esriSFSHorizontal": "Vodoravni",
    "esriSFSNull": "Nema vrijednosti",
    "esriSFSSolid": "Puna linija",
    "esriSFSVertical": "Uspravno"
  },
  "resultsTitle": "Rezultati",
  "publishTABtn": "Objavi",
  "layerName": "Naziv objavljenog sloja",
  "invalidLayerName": "Naziv sloja mora sadržavati samo alfanumeričke znakove i podvlake",
  "missingLayerName": "Morate navesti naziv za sloj",
  "missingLayerNameMessage": "Morate unijeti važeći naziv sloja prije objavljivanja",
  "publishingFailedLayerExists": "Objavljivanje nije uspjelo: već imate uslugu geoobjekata s nazivom {0}. Odaberite drugi naziv.",
  "checkService": "Provjeri uslugu: {0}",
  "createService": "Stvori uslugu: {0}",
  "unableToCreate": "Nije moguće stvoriti: {0}",
  "addToDefinition": "Dodaj definiciji: {0}",
  "successfullyPublished": "Uspješno objavljen web-sloj{0}Upravljaj web-slojem",
  "userRole": "Nije moguće stvoriti uslugu jer korisnik nema dopuštenja",
  "transparencyLabel": "Prozirnost",
  "outline": "Obris",
  "fill": "Ispuni (boja se primjenjuje samo kad je stil postavljen na jednobojno)",
  "createBtn": "Stvori zone",
  "clearBtn": "Očisti",
  "invalidNumberMessage": "Unesena vrijednost nije valjana",
  "invalidRangeMessage": "Vrijednost mora biti veća od 0",
  "parseCoordinatesError": "Nije moguće parsirati koordinate. Provjerite unos.",
  "manualCoordinateInputInfo": "Ručno unesite koordinate i kliknite <b>Enter</b> za zumiranje na njih",
  "pipeBombLabel": "Cijevna bomba",
  "suicideBombLabel": "Bomba za samoubilački napad",
  "briefcaseLabel": "Aktovka",
  "carLabel": "Automobil",
  "suvVanLabel": "SUV/KAMION",
  "smallDeliveryTruckLabel": "Mali kamion za dostavu",
  "containerWaterTruckLabel": "Kamion za prijevoz kontejnera/vode",
  "semiTrailerLabel": "Poluprikolica",
  "selectDrawModeLabel": "Odaberi način crtanja",
  "selectFeatureLabel": "Odaberite geoobjekt iz ovog sloja"
});