define({
  "serviceUrl": "Definir url de serviço:",
  "minIntSpacingLabel": "Espaçamento Mínimo de Intervalo",
  "lineOpacityLabel": "Opacidade de Linha",
  "labelOpacityLabel": "Opacidade de Rótulo",
  "centerLabelOpacityLabel": "Opacidade de Rótulo Central",
  "gridZonePlacementLabel": "Colocação de Rótulo de Zona de Grelha",
  "verticalLineLabels": "Rótulos de Linhas Verticais",
  "styleHeaderLabel": "Estilo",
  "indexHeaderLabel": "Índice",
  "colorHeaderLabel": "Cor",
  "fontSizeHeaderLabel": "Tamanho de letra",
  "lineWidthHeaderLabel": "Largura de Linha",
  "horizontalLabel": "Horizontal",
  "verticalLabel": "Vertical",
  "upperLeftLabel": "Superior Esquerdo",
  "upperRightLabel": "Superior Direito",
  "lowerLeftLabel": "Inferior Esquerdo",
  "lowerRightLabel": "Inferior Direito",
  "centerLabel": "Centrar"
});