define({
  "chartSettingLabel": "Ustawienia diagramu",
  "addNewLabel": "Dodaj nowy",
  "generalSettingLabel": "Ustawienia ogólne",
  "layerChooser": {
    "title": "Wybierz warstwę do utworzenia diagramu",
    "selectPolygonLayerLabel": "Zaznacz warstwę",
    "selectPolygonLayerHintText": "Wskazówka: w przypadku konfigurowania wielu diagramów warstwy muszą mieć ten sam typ geometrii",
    "selectRelatedTableLayerLabel": "Wybierz tabelę powiązaną z warstwą",
    "selectRelatedTableLayerHintText": "Wskazówka: tylko tabele z polami liczbowymi są wyświetlane",
    "errorInSelectingPolygonLayer": "Wybierz warstwę, która ma powiązaną warstwę punktową.",
    "errorInSelectingRelatedLayer": "Wybierz prawidłową tabelę/warstwę powiązaną z warstwą.",
    "polygonLayerNotHavingRelationships": "Wybrana warstwa nie ma żadnej powiązanej tabeli/warstwy."
  },
  "ChartSetting": {
    "sectionTitle": "Tytuł sekcji",
    "sectionTitleHintText": "Wskazówka: wyświetlane w tytule nagłówka sekcji",
    "chartTitle": "Tytuł diagramu",
    "chartTitleHintText": "Wskazówka: wyświetlane na środku u góry diagramu",
    "chartDescription": "Opis",
    "chartDescriptionHintText": "Wskazówka: wyświetlane poniżej diagramu",
    "chartType": "Typ diagramu",
    "barChart": "Diagram słupkowy grupowy",
    "pieChart": "Diagram kołowy",
    "polarChart": "Wykres biegunowy",
    "dataSeriesField": "Pole serii danych",
    "labelField": "Pole etykiety",
    "chartColor": "Kolor diagramu",
    "singleColor": "Jeden kolor",
    "colorByTheme": "Kolor wg motywu",
    "colorByFieldValue": "Kolor wg wartości pola",
    "xAxisTitle": "Tytuł osi X",
    "xAxisHintText": "Wskazówka: tytuł osi X",
    "yAxisTitle": "Tytuł osi Y",
    "yAxisHintText": "Wskazówka: tytuł osi Y",
    "fieldColorLabel": "Etykieta",
    "fieldColorColor": "Kolor",
    "defaultFieldSelectLabel": "Zaznacz",
    "errMsgFieldValuesNotFound": "Nie można znaleźć wartości dla wybranego pola",
    "errMsgSectionTitle": "Podaj tytuł sekcji",
    "errMsgFieldByValue": "Wybierz wartość pola",
    "settingTabTitle": "Ustawienie",
    "layoutTabTitle": "Kompozycja",
    "polarChartSelectFieldsHintText": "Wskazówka: wybierz pola, aby wygenerować wykres biegunowy",
    "visibilityText": "Widoczność",
    "fieldNameText": "Nazwa pola",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Wybierz co najmniej trzy pola, aby wygenerować wykres biegunowy",
    "polarChartPolygonFillLabel": "Wypełnij poligon",
    "polarChartPolygonFillHintText": "Wskazówka: zaznacz pole wyboru, aby wyświetlić wypełnienie poligonu na wykresie biegunowym",
    "ThemeSelector": {
      "themeAdobebricks": "Cegły",
      "themeAlgae": "Algi",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "Błękitny zmrok",
      "themeCubanShirts": "Kubańskie koszule",
      "themeDesert": "Pustynia",
      "themeDistinctive": "Kontrasty",
      "themeDollar": "Dolar",
      "themeGrasshopper": "Pasikonik",
      "themeGrasslands": "Łąki",
      "themeGreySkies": "Szare niebo",
      "themeHarmony": "Harmonia",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irlandia",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "Purpurowy deszcz",
      "themeRoyalPurples": "Królewska purpura",
      "themeSageToLime": "Szałwia-limonka",
      "themeTufte": "Tufte",
      "themeWatersEdge": "Lustro wody",
      "themeWetlandText": "Teren podmokły",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Ustawienia ogólne",
    "locationSymbolLabel": "Graficzny symbol lokalizacji",
    "locationSymbolHintText": "Wskazówka: służy do wyświetlania symbolu dla adresu i lokalizacji kliknięcia",
    "refreshIntervalLabel": "Interwał odświeżania",
    "refreshIntervalHintText": "Wskazówka: służy do odświeżania diagramów zgodnie z tym interwałem. Określ wartość z zakresu od 1 do 1440 minut",
    "errMsgRefreshInterval": "Podaj interwał odświeżania z zakresu od 0 do 1440 minut",
    "symbolPickerPreviewText": "Zobacz podgląd:"
  }
});