define({
  "taskUrl": "Görev URL'si",
  "serviceURLPlaceholder": "Coğrafi İşleme görevi URL'si girin",
  "layerOrder": "Katman sırası",
  "defaultValue": "Varsayılan değer",
  "inputFeatureBy": "Detay girme ölçütü",
  "inputRecordBy": "Tarafından kaydedilen girdi",
  "renderer": "Canlandırıcı",
  "displayType": "Görüntüleme türü",
  "helpUrl": "Yardım URL'si",
  "useResultMapService": "Harita servisi ile sonucu görüntüle",
  "drawOnMap": "Haritada etkileşimli olarak çiz",
  "selectLayer": "Haritadan bir katman seç",
  "selectTable": "Haritadan bir tablo seç",
  "shareResults": "Sonucu işlem katmanı olarak ekle",
  "setTask": "Ayarla",
  "setTaskTitle": "GP görevi ayarla",
  "enablePopup": "Açılan pencereyi etkinleştir",
  "unSupportGeometryType": "Bilinmeyen geometri türü nedeniyle işleyici ayarlanamıyor.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Dosya yükle",
  "selectFileToUpload": "Dosya seç...",
  "rasterFormat": "Raster veri formatı",
  "noFileSelected": "Dosya seçilmedi!",
  "uploadSuccess": "Dosya başarıyla yüklendi!",
  "showLayerContent": "Katman içeriğini göster",
  "urlPlaceholder": "Verilere erişmek için URL",
  "useShapefile": "Yerel dosya sistemindeki shapefile öğesini kullan",
  "allowToExport": "Sonuçları aktarmaya izin ver",
  "useDynamicSchema": "Çıktıda farklı şema bulunabileceğinden ön tanımlı yerine dinamik şema kullanın.",
  "useCurrentMapExtent": "Geçerli harita yayılımını kullan",
  "ignoreOutput": "Bu çıktıyı dikkate alma",
  "turnOffOutput": "Bu katmanı varsayılan olarak kapat",
  "inputJSONString": "JSON dizisini gir"
});