define(
   ({
    addLayer: "레이어 추가",
    layerName: "레이어",
    layerRefresh: "새로 고침",
    layerLabel: "레이블",
    actions: "작업",
    popupOk: "확인",
    popupCancel: "취소",
    mainPanelTextPlaceholder: "예: 고속도로 상태",
    invalidInterval: "숫자 문자만 지원됩니다.",
    uploadImage: "이미지 업로드",
    iconColumnText: "아이콘",
    refreshInterval: "1 \'분 단위 시간으로 평가됨\'",
    refreshIntervalTitle: "분 단위 시간으로 평가됨",
    mainPanelText: "기본 패널 텍스트",
    mainPanelIcon: "기본 패널 이미지",
    refreshIntervalInstruction: "새로 고침 간격",
    optionsText: "옵션",
    symbolOptionsText: "심볼 옵션",
    iconOptionsText: "아이콘 옵션",
    sympolPopupTitle: "세트 심볼",
    rdoLayer: "레이어 심볼",
    rdoCustom: "사용자 정의 심볼",
    chkCluster: "군집 사용",
    defineClusterSymbol: "군집점 심볼",
    defineThemeClusterSymbol: "테마로부터의 군집점 심볼",
    rdoEsri: "Esri 심볼",
    rdoLayerIcon: "심볼을 아이콘으로 사용",
    rdoCustomIcon: "사용자 정의 아이콘 업로드",
    editCustomSymbol: "사용자 정의 심볼 편집",
    editCustomIcon: "사용자 정의 아이콘 편집",
    missingRefreshValue: "새로 고침 간격 값을 입력하세요.",
    panelIconOption: "패널 헤더 보기",
    enableRefresh: "레이어 새로 고침 사용",
    disableRefresh: "레이어 새로 고침은 피처 컬렉션에만 지원됨",
    layer_type_not_supported: "다음 레이어 유형은 지원되지 않습니다. "
  })
);
