define({
  "enableUndoRedo": "[元に戻す]/[やり直し] の有効化",
  "toolbarVisible": "ツールバーの表示",
  "toolbarOptions": "ツールバーのオプション",
  "mergeVisible": "マージ",
  "cutVisible": "切り取り",
  "reshapeVisible": "形状変更",
  "back": "戻る",
  "label": "レイヤー",
  "edit": "編集可能",
  "update": "ジオメトリ更新の無効化",
  "fields": "フィールド",
  "actions": "アクション",
  "editpageName": "名前",
  "editpageAlias": "エイリアス",
  "editpageVisible": "表示",
  "editpageEditable": "編集可能",
  "noLayers": "編集可能なフィーチャ レイヤーはありません",
  "configureFields": "レイヤー フィールドの構成",
  "useFilterEdit": "フィーチャ テンプレート フィルターの使用",
  "display": "ディスプレイ",
  "autoApplyEditWhenGeometryIsMoved": "ジオメトリが移動したときに、編集内容を自動的に適用",
  "snappingTolerance": "スナップ許容値をピクセル単位で設定",
  "popupTolerance": "属性編集ポップアップの許容値をピクセル単位で設定",
  "stickyMoveTolerance": "移動抑制許容値をピクセル単位で設定",
  "usingSaveButton": "[保存] ボタンをクリックして、属性の編集を適用",
  "generalSettings": "一般設定",
  "editableLayersSetting": "編集可能なレイヤー設定",
  "honorTheWebMapSetting": "Web マップでの設定の適用",
  "honorTheWebMapSettingTip1": "設定には次のものがあります。",
  "honorTheWebMapSettingTip2": "どのレイヤーが編集可能か",
  "honorTheWebMapSettingTip3": "表示および編集するフィールド",
  "honorTheWebMapSettingTip4": "フィールドのエイリアス、順序、および形式",
  "customSettings": "カスタム設定"
});