define(
   ({
    addLayer: "增加圖層",
    layerName: "圖層",
    layerRefresh: "重新整理(R)",
    layerLabel: "標籤",
    actions: "操作",
    popupOk: "確定",
    popupCancel: "取消",
    mainPanelTextPlaceholder: "例如: 高速公路狀況",
    invalidInterval: "僅支援數值字元。",
    uploadImage: "上傳圖像",
    iconColumnText: "圖示",
    refreshInterval: "1「以分鐘為單位所評估的時間」",
    refreshIntervalTitle: "以分鐘為單位所評估的時間",
    mainPanelText: "主面板文字",
    mainPanelIcon: "主面板圖片",
    refreshIntervalInstruction: "重新整理間隔",
    optionsText: "選項",
    symbolOptionsText: "符號選項",
    iconOptionsText: "圖示選項",
    sympolPopupTitle: "設定符號",
    rdoLayer: "圖層符號",
    rdoCustom: "自訂符號",
    chkCluster: "啟用叢集",
    defineClusterSymbol: "叢集符號",
    defineThemeClusterSymbol: "來自主題的叢集符號",
    rdoEsri: "Esri 符號",
    rdoLayerIcon: "將符號作為圖示",
    rdoCustomIcon: "上傳自訂圖示",
    editCustomSymbol: "編輯自訂符號",
    editCustomIcon: "編輯自訂圖示",
    missingRefreshValue: "請提供重新整理間隔值。",
    panelIconOption: "顯示面板標頭",
    enableRefresh: "啟用圖層重新整理",
    disableRefresh: "僅支援圖徵集合的圖層重新整理",
    layer_type_not_supported: "圖層類型不受支援: "
  })
);
