define({
  "_widgetLabel": "تحرير",
  "_featureAction_Edit": "تحرير",
  "title": "تحديد قالب لإنشاء المعالم",
  "pressStr": "اضغط ",
  "ctrlStr": " CTRL ",
  "snapStr": " لتمكين الالتقاط",
  "close": "إغلاق",
  "featureLayers": "طبقات المعالم",
  "searchTemplates": "بحث في القوالب",
  "noAvailableTempaltes": "لا توجد أي قوالب",
  "noCanCreateLayerAreCurrentlyVisible": "لا يمكن رؤية أي طبقات قابلة للإنشاء حاليًا.",
  "layersAreInvisibleOrOutOfScaleRange": "الطبقات غير مرئية أو خارج نطاق القياس.",
  "relatedTables": "الجداول ذات الصلة:",
  "relatedRecords": "السجلات ذات الصلة:",
  "noRelatedRecotds": "لم يتم العثور على أي سجلات ذات صلة.",
  "startToDraw": "انقر لبدء الرسم",
  "startToAddPoint": "انقر لإضافة نقطة.",
  "editRelatedFeature": "تحرير المعلم المرتبط",
  "duplicateValueWarning": " يتعذر إدراج قيمة متكررة في ${fieldName} لـ ${tableName}. القيمة المتكررة هي: ${value}"
});