define({
  "queries": "Query",
  "addNew": "Tambah Baru",
  "newQuery": "Query Baru",
  "queryLayer": "Layer Query",
  "setSource": "Atur",
  "setDataSource": "Atur Sumber Data",
  "name": "Nama",
  "querySource": "Sumber data",
  "queryName": "Nama Tugas",
  "queryDefinition": "Definisi Filter",
  "resultsSetting": "Pengaturan Hasil",
  "symbolSetting": "Pengaturan Simbol:",
  "resultSettingTip": "Tetapkankan apa dan bagaimana cara menampilkan hasil output.",
  "resultItemTitle": "Judul setiap item hasil",
  "resultItemContent": "Atribut kolom ini akan ditampilkan",
  "fieldsSetTip": "Periksa kolom yang ingin Anda tampilkan. Pilih kolom untuk memperbarui alias, urutan, dan formatnya.",
  "addField": "Tambahkan Kolom",
  "visibility": "Visibilitas",
  "alias": "Alias",
  "specialType": "Tipe Khusus",
  "actions": "Tindakan",
  "none": "Tidak ada",
  "link": "Tautan",
  "image": "Gambar",
  "noField": "Tidak ada kolom",
  "operationalLayerTip": "Tambahkan hasil sebagai layer operasional",
  "setLayerSymbolTip": "Tetapkan simbol untuk hasil query: ",
  "setSelectedSymbolTip": "Tetapkan simbol dari fitur terpilih.",
  "notUseFilter": "Jangan gunakan filter",
  "setSourceTip": "Harap tetapkan sumber query.",
  "setFilterTip": "Tetapkan filter dengan benar.",
  "ok": "Ya",
  "cancel": "Batal",
  "noFilterTip": "Tanpa menentukan ekspresi filter, query ini akan mencantumkan semua fitur dalam sumber data yang ditentukan.",
  "relationships": "Hubungan",
  "addRelationshipLayer": "Tambahkan Hubungan Baru",
  "relatedTo": "Terkait dengan",
  "selectOption": "Harap pilih..",
  "resultItemSorting": "Pengurutan Item Hasil",
  "field": "Kolom",
  "sortingOrder": "Urutan",
  "configureFieldsTip": "Harap konfigurasikan kolom dimana tempat hasil query tersebut akan diurutkan.",
  "setSortingFields": "Tetapkan Kolom Pengurutan",
  "ascending": "Naik",
  "descending": "Turun",
  "sortBy": "Urutkan berdasarkan",
  "thenBy": "Kemudian menurut",
  "addTask": "Tambahkan Tugas",
  "noTasksTip": "Tidak ada query yang dikonfigurasikan. Klik \"${newQuery}\" untuk menambahkan query baru.",
  "infoText": "Info",
  "filters": "Filter",
  "results": "Hasil",
  "optionsText": "Opsi",
  "summaryText": "Ringkasan",
  "attributeFilter": "Filter Atribut",
  "attributeFilterTip": "Tetapkan ekspresi atribut yang digunakan dalam widget untuk memfilter layer query.",
  "defineWhereClause": "Tetapkan tempat klausul untuk query.",
  "noExpressionDefinedTip": "Tidak ada ekspresi yang ditentukan. Semua catatan akan dikembalikan.",
  "setExpressions": "Tetapkan Ekspresi",
  "spatialFilter": "Filter spasial",
  "spatialFilterTip": "Pilih filter spasial mana yang akan tersedia bagi pengguna akhir.",
  "defaultOption": "Default",
  "useCurrentExtentTip": "Hanya mengembalikan fitur di dalam jangkauan peta saat ini",
  "useDrawGraphicTip": "Hanya mengembalikan fitur yang berpotongan dengan bentuk yang digambar pada peta",
  "useFeaturesTip": "Hanya mengembalikan fitur yang mempunyai hubungan spasial dengan fitur dalam layer lain",
  "noSpatialLimitTip": "Kembalikan fitur dalam jangkauan penuh dari peta",
  "drawingTools": "Pilih peralatan menggambar",
  "bufferSettings": "Aktifkan opsi buffer",
  "defaultDistance": "Jarak default",
  "bufferDistance": "Jarak buffer",
  "defaultUnit": "Unit default",
  "miles": "Mil",
  "kilometers": "Kilometer",
  "feet": "Kaki",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Mil Laut",
  "availableSpatialRelationships": "Pilih aturan hubungan spasial",
  "setSpatialRelationships": "Tetapkan Hubungan Spasial",
  "availability": "Ketersediaan",
  "relationship": "Hubungan",
  "label": "Label",
  "intersect": "berpotongan",
  "contain": "berisi",
  "areContainedIn": "berada di",
  "cross": "silang",
  "envelopeIntersect": "perpotongan selubung",
  "overlap": "tumpang tindih",
  "areOverlapped": "tumpang tindih",
  "touch": "sentuh",
  "within": "di dalam",
  "areWithin": "berada di",
  "indexIntersect": "perpotongan indeks",
  "itemTitle": "Judul Item",
  "displayFields": "Tampilkan Kolom",
  "sortingFields": "Urutkan item hasil",
  "setDisplayFields": "Tetapkan Kolom Tampilan",
  "symbol": "Simbol",
  "setSymbol": "Gunakan simbol khusus",
  "changeSymbolAtRuntime": "Izinkan mengubah simbol saat runtime",
  "serviceSymbolTip": "Gunakan simbol yang ditentukan oleh layer",
  "exportTip": "Izinkan untuk mengekspor hasil",
  "keepResultsTip": "Simpan hasil dalam peta setelah widget ditutup",
  "queryRelatedRecords": "Catatan terkait query",
  "createLayerForTaskTip": "Tentukan bagaimana query menyusun layer",
  "oneLayerForTaskTip": "Timpa layer setiap kali query dijalankan",
  "multipleLayerForTaskTip": "Buat layer baru setiap kali query dijalankan",
  "makeDefault": "Jadikan Default",
  "icon": "Ikon",
  "newTask": "Tugas Baru",
  "addTaskTip": "Tambahkan satu query atau lebih pada widget dan konfigurasikan parameter untuk setiap query tersebut.",
  "webMapPopupTip": "Gunakan konfigurasi pop-up layer di web map",
  "customPopupTip": "Konfigurasikan konten khusus",
  "showResultsSetActions": "Tampilkan tindakan untuk set hasil",
  "zoomTo": "Perbesar hingga",
  "openAttributeTable": "Buka dalam Tabel Atribute",
  "content": "Konten",
  "displaySQLTip": "Tampilkan ekspresi SQL untuk pengguna akhir",
  "useLayerDefaultSymbol": "Gunakan simbol default layer",
  "setCustomIcon": "Tetapkan ikon khusus",
  "layerDefaultSymbolTip": "Gunakan simbol default layer",
  "uploadImage": "Unggah gambar",
  "attributeCriteira": "Kriteria atribut",
  "specifyFilterAtRuntimeTip": "Pengguna harus menentukan parameter untuk ekspresi ini.",
  "value": "NILAI",
  "hideLayersTip": "Matikan layer hasil query saat widget ditutup."
});