define({
  "_widgetLabel": "Ärianalüütik",
  "addPoint": "Lisage punkt kaardile klikkides",
  "addRingsDtWt": "Lisage ringe, sõiduaega või kõndimisaega",
  "apply": "Rakenda",
  "back": "Tagasi",
  "colon": ":",
  "creditInformation": "Krediiditeave",
  "driveTime": "Sõiduaeg",
  "esriInfographics": "Esri infograafika",
  "esriReports": "Esri aruanded",
  "headerDescription_km": "km",
  "headerDescription_miles": "miil",
  "headerDescription_minutes": "minut",
  "infographics": "Infograafika",
  "invalidValueRing": "Väärtus peab olema vahemikus 0–1000.",
  "invalidValueDTWT": "Väärtused peavad olema vahemikus 0–300.",
  "km": "km",
  "miles": "mi",
  "minutes": "min",
  "myInfographics": "Minu infograafika",
  "myReports": "Minu aruanded",
  "noPermissions": "Teie konto ei tööta vidinas Ärianalüütik.  Vidina Ärianalüütik käitamiseks peab teie organisatsiooni administraator andma teile GeoEnrichment’i ja võrguanalüüsi <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privileges</a> ning määrama <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">õigused</a>.",
  "geServiceNotConfigured": "Business Analyst vidinat ei saa selles portaalis kasutada, sest teenus <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenrichment</a> ei ole konfigureeritud.",
  "dirRoutingServiceNotConfigured": "Business Analyst vidinat ei saa selles portaalis kasutada, sest teenus <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Directions and Routing</a> ei ole konfigureeritud.",
  "geAndDirRoutingServicesNotConfigured": "Business Analyst vidinat ei saa selles portaalis kasutada, sest teenused <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenrichment</a> and <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Directions and Routing</a> ei ole konfigureeritud.",
  "radii": "raadiused",
  "radius": "Raadius",
  "radius_lowercase": "raadius",
  "reports": "Aruanded",
  "ring": "Rõngas",
  "rings": "Ringid",
  "runInfographic": "Käitage infograafika",
  "runReport": "Käitage aruanne",
  "selectPointOrPolygon": "Valige kaardilt punkt või polügooni objekt, otsige aadressi või kohta, või märgistage mõni koht kaardil, et piirkondade kohta rohkem teavet saada.",
  "selectReport": "Valige aruanne",
  "selectTemplate": "Valige mall",
  "sharedInfographics": "Jagatud infograafika",
  "sharedReports": "Jagatud raportid",
  "thisEntryIsNotValid": "See kirje ei kehti.",
  "time": "Aeg",
  "walkTime": "Kõndimise aeg",
  "widgetDescription": "Juurdepääs infograafikale ja aruannetele, mis sisaldavad ükskõik millise piirkonna peamiste näitajate ja teabe kokkuvõtet.",
  "None": "Valige..."
});