define({
  "_widgetLabel": "Visibilitas",
  "observerLocation": "Lokasi Pengamat",
  "formatIconTooltip": "Format Input",
  "addPointToolTip": "Tambah Lokasi Pengamat",
  "fieldOfView": "Bidang Pandang",
  "useMilsText": "Gunakan mil untuk sudut",
  "observerHeight": "Tinggi Pengamat",
  "minObsDistance": "Jarak Min yang Dapat Diamati",
  "maxObsDistance": "Jarak Maks yang Dapat Diamati",
  "taskURLError": "File konfigurasi widget berisi URL yang tidak dapat dijangkau. Silakan hubungi administrator sistem Anda",
  "taskURLInvalid": "Tugas geoprocessing yang dikonfigurasikan dengan widget ini tidak valid. Silakan hubungi administrator sistem Anda",
  "viewshedError": "Kesalahan terjadi saat membuat visibilitas. Harap pastikan lokasi pengamat Anda berada dalam jangkauan permukaan elevasi Anda.</p>",
  "validationError": "<p>Formulir pembuatan visibilitas tidak ada atau parameter tidak valid. Harap pastikan:</p><ul><li>Lokasi pengamat sudah diatur.</li><li>Bidang Pandang pengamat bukan 0.</li><li>Tinggi pengamat berisi nilai valid.</li><li>Jarak min dan maks yang dapat diamati berisi nilai valid.</li></ul>",
  "comfirmInputNotation": "Konfirmasikan Notasi Input",
  "notationsMatch": "notasi sesuai dengan input Anda, harap konfirmasikan yang ingin Anda gunakan:",
  "createBtn": "Buat",
  "clearBtn": "Hapus",
  "setCoordFormat": "Atur Format Koordinat String",
  "prefixNumbers": "Tambahkan awalan '+/-' untuk nomor positif dan negatif",
  "parseCoordinatesError": "Tidak dapat mengurai koordinat. Harap periksa input Anda.",
  "cancelBtn": "Batal",
  "applyBtn": "Terapkan",
  "invalidMessage": "Harap masukkan nilai numerik.",
  "observerRangeMessage": "Tinggi Pengamat tidak valid",
  "minimumRangeMessage": "Rentang Minimum yang Dapat Diamati tidak valid",
  "maximumRangeMessage": "Rentang Maksimum yang Dapat Diamati harus lebih besar dari Rentang Minimum yang Dapat Diamati ${limit} ${units}.",
  "portalURLError": "URL ke organisasi ArcGIS Online atau Portal untuk ArcGIS Anda tidak dikonfigurasi. Harap periksa dengan administrator sistem Anda",
  "privilegeError": "Peran pengguna Anda tidak dapat melakukan analisis. Untuk melakukan analisis, administrator organisasi Anda harus memberikan <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">hak istimewa</a> kepada Anda.",
  "noServiceError": "Layanan analisis elevasi tidak tersedia. Harap periksa konfigurasi organisasi ArcGIS Online atau Portal untuk ArcGIS Anda.",
  "pointToolTooltip": "Klik untuk menambahkan lokasi pengamat",
  "degreesLabel": "derajat",
  "milsLabel": "mil",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Derajat Desimal - Garis Lintang/Garis Bujur",
  "DDLongLatNotation": "Derajat Desimal - Garis Bujur/Garis Lintang",
  "DDMLatLongNotation": "Menit Derajat Desimal - Garis Lintang/Garis Bujur",
  "DDMLongLatNotation": "Menit Derajat Desimal - Garis Bujur/Garis Lintang",
  "DMSLatLongNotation": "Detik Derajat Desimal - Garis Lintang/Garis Bujur",
  "DMSLongLatNotation": "Detik Derajat Desimal - Garis Bujur/Garis Lintang",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - Hemisfer (N/S)",
  "mainPageTitle": "Pandangan Radial",
  "resultsTitle": "Hasil",
  "publishBtnLabel": "Terbitkan",
  "layerName": "Nama Layer yang Diterbitkan",
  "invalidLayerName": "Nama layer tidak boleh mengandung karakter alfa-numerik dan garis bawah",
  "missingLayerName": "Masukkan nama layer",
  "back": "Kembali",
  "publishingFailedLayerExists": "Penerbitan Gagal: Anda telah memiliki feature service bernama {0}.  Harap pilih nama lain.",
  "checkService": "Periksa Layanan: {0}",
  "createService": "Buat Layanan: {0}",
  "unableToCreate": "Tidak dapat membuat: {0}",
  "addToDefinition": "Tambahkan ke definisi: {0}",
  "successfullyPublished": "Berhasil menerbitkan layer web{0}Kelola layer web",
  "userRole": "Tidak dapat membuat layanan karena pengguna tidak memiliki izin",
  "publishToNewLayer": "Terbitkan hasil ke feature layer baru",
  "missingLayerNameMessage": "Anda harus memasukkan nama layer yang valid sebelum Anda dapat menerbitkan",
  "regionTypeLabel": "Jenis Wilayah",
  "centerPointLabel": "Titik Tengah",
  "observationHeightLabel": "Tinggi Observasi",
  "heightUnitLabel": "Unit Tinggi",
  "minObservationDistanceLabel": "Jarak MinObservation",
  "maxObservationDistance": "Jarak MaxObservation",
  "distanceUnitLabel": "Satuan Jarak",
  "fovstartAngleLabel": "Sudut Awal FOV",
  "fovEndAngleLabel": "Sudut Akhir FOV",
  "andleUnitsLabel": "Unit Sudut"
});