define({
  "chartSettingLabel": "Настройки диаграммы",
  "addNewLabel": "Добавить новое",
  "generalSettingLabel": "Общие настройки",
  "layerChooser": {
    "title": "Выберите слой для диаграммы",
    "selectPolygonLayerLabel": "Выбрать слой",
    "selectPolygonLayerHintText": "Подсказка: Если настроено несколько диаграмм, то слои должно быть одинакового типа геометрии",
    "selectRelatedTableLayerLabel": "Выберите таблицу, связанную со слоем",
    "selectRelatedTableLayerHintText": "Подсказка: Отображаются только таблицы с числовыми полями",
    "errorInSelectingPolygonLayer": "Выберите слой, у которого есть связанный точечный слой.",
    "errorInSelectingRelatedLayer": "Выберите для слоя допустимый связанный слой/таблицу.",
    "polygonLayerNotHavingRelationships": "Выберите слой, у которого нет связанного слоя/таблицы."
  },
  "ChartSetting": {
    "sectionTitle": "Название раздела",
    "sectionTitleHintText": "Подсказка: Отображается в заголовке названия раздела",
    "chartTitle": "Заголовок диаграммы",
    "chartTitleHintText": "Подсказка: Отображение центрируется наверху диаграммы",
    "chartDescription": "Описание",
    "chartDescriptionHintText": "Подсказка: Отображение центрируется внизу диаграммы",
    "chartType": "Тип диаграммы",
    "barChart": "Столбчатая диаграмма",
    "pieChart": "Круговая диаграмма",
    "polarChart": "Полярная диаграмма",
    "dataSeriesField": "Поле серий данных",
    "labelField": "Поле подписи",
    "chartColor": "Цвет диаграммы",
    "singleColor": "Один цвет",
    "colorByTheme": "Цвет по теме",
    "colorByFieldValue": "Цвет по значению поля",
    "xAxisTitle": "Заголовок по оси X",
    "xAxisHintText": "Подсказка: Заголовок по оси X",
    "yAxisTitle": "Заголовок по оси Y",
    "yAxisHintText": "Подсказка: Заголовок по оси Y",
    "fieldColorLabel": "Подпись",
    "fieldColorColor": "Цвет",
    "defaultFieldSelectLabel": "Выбрать",
    "errMsgFieldValuesNotFound": "Невозможно найти значения для выбранного поля",
    "errMsgSectionTitle": "Введите заголовок раздела",
    "errMsgFieldByValue": "Выберите значение поля",
    "settingTabTitle": "Параметр",
    "layoutTabTitle": "Компоновка",
    "polarChartSelectFieldsHintText": "Подсказка: Выберите поля для создания полярной диаграммы",
    "visibilityText": "Видимость",
    "fieldNameText": "Имя поля",
    "aliasNameText": "Псевдоним",
    "errMsgPolarFieldsRequired": "Выберите три или более полей для создания полярной диаграммы",
    "polarChartPolygonFillLabel": "Заполнение полигона",
    "polarChartPolygonFillHintText": "Подсказка: Установите отметку, чтобы отобразить заливку полигона в полярной диаграмме",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Общие параметры",
    "locationSymbolLabel": "Графический символ местоположения",
    "locationSymbolHintText": "Подсказка: Используется для отображения символа адресов и местоположений, на которых щелкнули",
    "refreshIntervalLabel": "Интервал обновления",
    "refreshIntervalHintText": "Подсказка: Используется для обновления диаграмм на основании этого интервала. Укажите значение от 1 до 1440 минут",
    "errMsgRefreshInterval": "Укажите интервал обновления от 0 до 1440 минут.",
    "symbolPickerPreviewText": "Просмотр:"
  }
});