define({
  "tabs_section_Label": "Pestanyes",
  "addTab": "Afegeix una pestanya",
  "layerName": "Capa",
  "layerType": "Tipus d'anàlisi",
  "layerLabel": "Etiqueta",
  "actions": "Accions",
  "closest": "Entitat més propera",
  "proximity": "Proximitat",
  "summary": "Resum",
  "select_lbl": "-- Seleccioneu --",
  "general_setting_Label": "Configuració general",
  "units_text_lbl": "Unitats de distància",
  "maximum_distance_lbl": "Distància màxima a l'entitat més propera",
  "buffer_text_lbl": "Etiqueta d'àrea d'influència",
  "buffer_lbl": "Distància d'àrea d'influència",
  "buffer_max_lbl": "Distància de l'àrea d'influència màxima",
  "buffer_min_lbl": "Distància de l'àrea d'influència mínima",
  "buffer_default_lbl": "Distància d'àrea d'influència per defecte",
  "not_less_than_max": "La distància ha de ser inferior a la distància d'àrea d'influència màxima",
  "not_between": "La distància ha d'estar entre les distàncies d'àrea d'influència mínima i màxima",
  "not_more_than_min": "La distància ha de ser més gran que la distància d'àrea d'influència mínima",
  "not_valid_number": "Ha de ser un nombre vàlid",
  "invalid_value": "El valor de ${type} no és vàlid",
  "routing_checkBox": "Habilita l'encaminament",
  "weather_removed_message": "Les opcions del temps meteorològic ja no estan disponibles per a aquest widget.",
  "currentlySelectedLayer": "Seleccioneu en capes de mapes",
  "missingTabLabel": "Falta l'etiqueta en una pestanya com a mínim",
  "missingLayerInWebMap": "No s'ha trobat cap capa operativa.",
  "selectFields": "Seleccioneu els camps",
  "addField": "Afegeix un camp",
  "sum": "Suma",
  "min": "Mínim",
  "max": "Màxim",
  "avg": "Mitjana",
  "count": "COUNT",
  "area": "AREA",
  "length": "LENGTH",
  "count_checkBox": "Mostra el recompte d'entitats",
  "area_checkBox": "Mostra la suma de l'àrea",
  "length_checkBox": "Mostra la suma de la longitud",
  "max_records": "S'ha arribat al límit màxim",
  "save_label": "Opcions de desament",
  "save_checkbox": "Habilita el desament",
  "report_label": "Opcions d'informe",
  "report_checkbox": "Habilita l'informe",
  "csv_label": "Opcions de CSV",
  "display_label": "Opcions de visualització",
  "display_checkbox": "Mostra les entitats de resum",
  "setSelectionColor": "Defineix el color de selecció",
  "snapshot_label": "Opcions d'instantània",
  "snapshot_checkbox": "Habilita la instantània",
  "must_select_template": "Seleccioneu una de les plantilles d'edició a Opcions de desament.",
  "count_label": "Etiqueta de recompte",
  "area_label": "Etiqueta d'àrea",
  "length_label": "Etiqueta de longitud",
  "invalid_string_width": "El valor és massa llarg. ",
  "layer_type_not_supported": "Tipus de capa no compatible",
  "groupedSummary": "Recomptes agrupats",
  "groupByField": "Agrupa per camp",
  "labelType": "Afegeix l'etiqueta",
  "prefix": "Com a prefix",
  "suffix": "Com a sufix",
  "need_group_field": "Utilitzeu l'acció Edita per definir Agrupa per camp.",
  "fieldTitle": "Camp",
  "typeTitle": "Tipus",
  "actionsTitle": "Accions",
  "save_point_checkbox": "Desa els punts",
  "save_line_checkbox": "Desa les línies",
  "save_poly_checkbox": "Desa els polígons",
  "no_valid_popup_fields": "No hi ha cap camp vàlid a la finestra emergent. Utilitzeu l'acció Edita per definir un camp.",
  "no_valid_fields": "No hi ha cap camp vàlid. Utilitzeu l'acció Edita per definir les opcions de visualització.",
  "incident_label": "Etiqueta de pestanya",
  "locate_incident_label": "Etiqueta de l'àrea d'interès",
  "incident": "Incident",
  "locate_incident": "Localitza l'incident",
  "buffer_value": "Distància d'àrea d'influència",
  "tab_options": "Anàlisi",
  "export_options": "Sortida",
  "instruction_save": "Deseu la ubicació en un servei d'entitats.",
  "instruction_snapshot": "Creeu un mapa web basat en la ubicació.",
  "instruction_report": "Creeu un informe imprès de la ubicació.",
  "instruction_all_fields": "Exporteu els camps amb la baixada de CSV.",
  "data_label": "Configuració de sortida de dades",
  "layer_error": "La capa falta o no és vàlida.",
  "visibility_checkBox": "Deshabilita l'administració de la visibilitat de les capes",
  "allFieldsLabel": "Tots els camps",
  "configuredPopUpFieldsLabel": "Camps emergents configurats",
  "analysisTypeFieldsLabel": "Camps de tipus d'anàlisi",
  "reportOptionsMsg": "S'ha de seleccionar almenys una opció d'informe",
  "analysisSummaryLabelForReport": "Resum de tipus d'anàlisi",
  "popUpSummaryLabelForReport": "Resum de camps emergents configurats",
  "downloadTab": {
    "reportLegend": "Configuració d'informe",
    "textColorLabel": "Seleccioneu el color per a la capçalera de columna",
    "setButtonLabel": "Defineix",
    "printGPServiceLabel": "URL del servei d'impressió",
    "logoLabel": "Logotip",
    "logoChooserHint": "Feu clic a la icona de la imatge per canviar la imatge",
    "footnoteLabel": "Nota a peu de pàgina"
  },
  "roundValue": "Arrodoneix a",
  "roundValueTitle": "Arrodoneix els valors de camp",
  "truncateValue": "Truca a",
  "truncateValueTitle": "Trunca els valors de camp",
  "significantFigures": "xifres significatives",
  "fieldOptions": "Opcions de camp",
  "modifyValues": "Modifica els valors de camp",
  "validatePlaces": "Ha de ser un enter",
  "onlyDouble": "Les opcions de camps addicionals només s'admeten per a camps numèrics.",
  "layerNotAvalible": "No s'ha trobat la capa",
  "missingLayer": "Nom: ${name}",
  "missingLayerHint": "Una o diverses capes a les quals es fa referència en aquesta configuració no estan disponibles actualment.",
  "drawGeodesic": "Dibuixa formes geodèsiques"
});