define({
  "defaultAreaUnit": "Unit Area Default",
  "defaultLengthUnit": "Unit Panjang Default",
  "acres": "Acre",
  "sqMiles": "Mil Persegi",
  "sqKilometers": "Kilometer Persegi",
  "hectares": "Hektare",
  "sqYards": "Yard Persegi",
  "sqFeet": "Kaki Persegi",
  "sqFeetUS": "Kaki Persegi (AS)",
  "sqMeters": "Meter Persegi",
  "miles": "Mil",
  "kilometers": "Kilometer",
  "feet": "Kaki",
  "feetUS": "Kaki (AS)",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Mil Laut",
  "showArea": "Area",
  "showDistance": "Jarak",
  "showLocation": "Lokasi",
  "showtools": "Tampilkan alat pengukuran:",
  "allHidedTips": "Paling sedikit satu alat harus dipilih."
});