define({
  "tabs_section_Label": "Kortelės",
  "addTab": "Pridėti skirtuką",
  "layerName": "Sluoksnis",
  "layerType": "Analizės tipas",
  "layerLabel": "Žymė",
  "actions": "Veiksmai",
  "closest": "Artimiausias elementas",
  "proximity": "Artumas",
  "summary": "Santrauka",
  "select_lbl": "-- Pasirinkti --",
  "general_setting_Label": "Bendrieji parametrai",
  "units_text_lbl": "Atstumo vienetai",
  "maximum_distance_lbl": "Artimiausio elemento maksimalus atstumas",
  "buffer_text_lbl": "Buferio žymė",
  "buffer_lbl": "Buferio atstumas",
  "buffer_max_lbl": "Maksimalus buferio atstumas",
  "buffer_min_lbl": "Minimalus buferio atstumas",
  "routing_checkBox": "Įgalinti maršrutų nustatymą",
  "weather_Label": "Oro sąlygų parinktys",
  "weather_checkBox": "Įtraukti informaciją apie oro sąlygas",
  "selectLayers": "pasirinkti oro sąlygų sluoksnius",
  "currentlySelectedLayer": "Pasirinkti oro sąlygų sluoksniai",
  "missingTabLabel": "Bent vienas skirtukas neturi žymės",
  "missingLayerInWebMap": "Darbinių sluoksnių nerasta.",
  "selectFields": "Pasirinkite laukus",
  "addField": "Pridėti lauką",
  "sum": "Suma",
  "min": "Minimumas",
  "max": "Maksimumas",
  "avg": "Vidutinis",
  "count": "KIEKIS",
  "area": "PLOTAS",
  "length": "ILGIS",
  "count_checkBox": "Rodyti elementų skaičių",
  "area_checkBox": "Rodyti bendrą plotą",
  "length_checkBox": "Rodyti bendrą ilgį",
  "max_records": "Pasiekta maksimali riba",
  "save_label": "Įrašyti parinktis",
  "save_checkbox": "Įjungti įrašymą",
  "csv_label": "CSV parinktys",
  "csv_checkbox": "Eksportuoti visus sluoksnio laukus.",
  "display_label": "Rodymo parinktys",
  "display_checkbox": "Pateikti santraukos elementus",
  "snapshot_label": "Snapshot parinktys",
  "snapshot_checkbox": "Įjungti Snapshot",
  "must_select_template": "Pasirinkite vieną iš redagavimo šablonų įrašymo parinktyse.",
  "count_label": "Skaičiaus žymė",
  "area_label": "Ploto žymė",
  "length_label": "Ilgio žymė",
  "invalid_string_width": "Reikšmė per ilga. ",
  "layer_type_not_supported": "Sluoksnio tipas nepalaikomas: ",
  "groupedSummary": "Sugrupuoti skaičiavimai",
  "groupByField": "Grupuoti pagal lauką",
  "labelType": "Pridėti žymę",
  "prefix": "Kaip prefiksą",
  "suffix": "Kaip sufiksą",
  "need_group_field": "Norėdami nustatyti grupavimą pagal lauką, naudokite veiksmą Redaguoti.",
  "fieldTitle": "Laukas",
  "typeTitle": "Tipas",
  "actionsTitle": "Veiksmai",
  "save_point_checkbox": "Įrašyti taškus",
  "save_line_checkbox": "Įrašyti linijas",
  "save_poly_checkbox": "Įrašyti poligonus",
  "no_valid_popup_fields": "Nėra tinkamų laukų iššokančiame lange. Apibrėžkite lauką naudodami veiksmą Redaguoti.",
  "no_valid_fields": "Nėra tinkamų laukų. Apibrėžkite lauką naudodami veiksmą Redaguoti.",
  "incident_label": "Skirtuko žymė",
  "locate_incident_label": "Dominančio ploto žymė",
  "incident": "Įvykis",
  "locate_incident": "Rasti įvykį",
  "buffer_value": "Buferio atstumas"
});