define({
  "_widgetLabel": "Аналіз інцидентів",
  "_featureAction_SetAsIncident": "Задати як інцидент",
  "incident": "Інцидент",
  "weather": "Погода",
  "locate_incident": "Знайти інцидент",
  "clear_incidents": "Очистити інциденти",
  "reverse_geocoded_address": "Найближча адреса",
  "reverse_geocoded_error": "Не доступно",
  "miles": "Милі",
  "kilometers": "Кілометри",
  "feet": "Фути",
  "meters": "Метри",
  "yards": "Ярди",
  "nauticalMiles": "Морські милі",
  "now": "ЗАРАЗ",
  "wind": "ВІТЕР",
  "SUN": "НД",
  "MON": "ПН",
  "TUE": "ВТ",
  "WED": "СР",
  "THU": "ЧТ",
  "FRI": "ПТ",
  "SAT": "СБ",
  "defaultTabMsg": "Інциденти не визначено.",
  "useMapExtent": "Використовувати поточний екстент карти",
  "noFeaturesFound": "Об'єкти не знайдено.",
  "downloadCSV": "ЗАВАНТАЖИТИ CSV",
  "sum": "СУМА",
  "min": "МІН.",
  "max": "МАКС.",
  "avg": "СЕР.",
  "count": "ЛІЧИЛЬНИК",
  "area": "ПЛОЩА",
  "length": "ДОВЖИНА"
});