define({
  "_widgetLabel": "Редактировать",
  "_featureAction_Edit": "Редактировать",
  "title": "Выберите шаблон для создания объектов",
  "pressStr": "Нажмите ",
  "ctrlStr": " CTRL ",
  "snapStr": " чтобы включить замыкание",
  "close": "Закрыть",
  "featureLayers": "Векторные слои",
  "searchTemplates": "Поиск шаблонов",
  "noAvailableTempaltes": "Нет доступных шаблонов",
  "noCanCreateLayerAreCurrentlyVisible": "В данный момент нет видимых создаваемых слоев.",
  "layersAreInvisibleOrOutOfScaleRange": "Слои невидимы или находятся вне диапазона масштабов.",
  "relatedTables": "Связанные таблицы:",
  "relatedRecords": "Связанные записи:",
  "noRelatedRecotds": "Связанных записей не найдено.",
  "startToDraw": "Щелкните, чтобы начать рисовать",
  "startToAddPoint": "Щелкните, чтобы добавить точку",
  "editRelatedFeature": "Редактирование связанного объекта",
  "duplicateValueWarning": " Не удается вставить дублированное значение в ${fieldName} таблицы ${tableName}. Дублированное значение: ${value}"
});