define({
  "settings": "Inställningar",
  "titleSettings": "Textinställningar",
  "imageSettings": "Bildinställningar",
  "backgroundColor": "Bakgrundsfärg",
  "alignment": "Justering",
  "textSize": "Textstorlek",
  "textColor": "Textfärg",
  "dataSource": "Datakälla",
  "chartSettings": "Diagraminställningar",
  "data": "Data",
  "dataLabels": "Dataetiketter",
  "displayMode": "Visningsläge",
  "featureOption": "Visa värden geoobjekt för geoobjekt",
  "categoryOption": "Visa värden efter kategori",
  "countOption": "Visa geoobjektantal efter kategori",
  "fieldOption": "Visa attributvärden som diagram",
  "categoryField": "Kategorifält",
  "labelField": "Etikettfält",
  "valueFields": "Värdefält",
  "operation": "Åtgärd",
  "sumOption": "Summa",
  "averageOption": "Genomsnitt",
  "minOption": "Minimum",
  "maxOption": "Maximalt",
  "dataFormat": "Dataformat",
  "decimalPlaces": "Decimaler",
  "prefix": "Prefix",
  "suffix": "Suffix",
  "dataType": "Datatyp",
  "featureCount": "Antal geoobjekt",
  "fieldStatistics": "Fältstatistik",
  "display": "Visa",
  "chartColor": "Diagramfärg",
  "horizontalAxis": "Horisontell axel",
  "verticalAxis": "Vertikal axel",
  "legend": "Teckenförklaring",
  "position": "Position",
  "top": "Övre",
  "bottom": "Längst ned",
  "useDataSourceSelection": "Använd markering",
  "dataSourceFilterByExtent": "Filtrera efter utbredning",
  "changeTemplate": "Ändra mall",
  "numberSettings": "Talinställningar",
  "gaugeSettings": "Mätarinställningar",
  "indicators": "Indikatorer",
  "ifValue": "Om värdet",
  "and": "och",
  "numberOperatorIsLessThan": "är mindre än",
  "numberOperatorIsGreaterThan": "är större än",
  "numberOperatorIsBetween": "är mellan",
  "numberOperatorIsEqual": "är lika med",
  "numberOperatorIsNotEqual": "är inte lika med",
  "then": "Så",
  "ratio": "Förhållande",
  "trueValue": "värdet Sant",
  "changeValueColor": "ändrar värdefärgen till",
  "changeGaugeColor": "ändrar mätarfärgen till",
  "setIndicatorIcon": "anger indikatorikonen som",
  "icons": "Icons",
  "style": "Format",
  "placement": "Placering",
  "left": "Vänster",
  "replace": "Ersätt",
  "right": "Höger",
  "color": "Färg",
  "dataRange": "Dataintervall",
  "targetValue": "Målvärde",
  "currentValue": "Aktuellt värde",
  "gaugeColor": "Mätarfärg",
  "min": "Minimum",
  "max": "Maximalt",
  "displayValueIn": "Visa värde i",
  "noData": "Inga data",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Varning",
  "noSettingWaring1": "Klicka på ett element för att ange dess egenskaper.",
  "noSettingWaring2": "Dra för att ändra storlek eller ändra ordning för ett element.",
  "donNotShowAgain": "Visa inte igen",
  "changeTemplateWarning": "Det här raderar alla dina inställningar och öppnar en ny tom mall.",
  "requiredFieldWarning": "Det här värdet är obligatoriskt:",
  "dataSourceNotSet": "Ange datakälla.",
  "addIndicatorTip": "Lägg till en indikator",
  "chooseTemplatePopupTitle": "Välj en mall",
  "stringsInTemplate": {
    "name_number": "Nummer",
    "name_gauge": "Mätare",
    "name_vertical_gauge": "Vertikal mätare",
    "name_horizontal_gauge": "Horisontell mätare",
    "name_pie_chart": "Cirkeldiagram",
    "name_column_chart": "Kolumndiagram",
    "name_bar_chart": "Stapeldiagram",
    "name_line_chart": "Linjediagram",
    "titleOfTheInfographic": "NAMN PÅ INFOGRAFIK",
    "description": "Beskrivning: Ytterligare information om denna infografik."
  }
});