define({
  "addTaskTip": "Afegiu un o diversos filtres al widget i configureu els paràmetres de cadascun.",
  "enableMapFilter": "Elimineu el filtre de la capa predefinida del mapa.",
  "newFilter": "Filtre nou",
  "filterExpression": "Expressió de filtre",
  "layerDefaultSymbolTip": "Utilitza el símbol per defecte de la capa",
  "uploadImage": "Puja una imatge",
  "selectLayerTip": "Seleccioneu una capa.",
  "setTitleTip": "Definiu un títol.",
  "noTasksTip": "No hi ha cap filtre configurat. Feu clic a \"${newFilter}\" per afegir-ne un de nou.",
  "collapseFiltersTip": "Redueix les expressions de filtre (si n'hi ha) quan s'obri el widget",
  "zoomtoTip": "Aplica el zoom a les entitats restants un cop aplicat el filtre de la capa",
  "zoombacktoTip": "Aplica el zoom a l'extensió de mapa inicial un cop desactivats tots els filtres de la capa",
  "groupByLayerTip": "Agrupa els filtres per capa",
  "autoApplyWhenValueInput": "Aplica aquest filtre automàticament després que s'introdueixi un valor",
  "autoApplyWhenWidgetOpen": "Aplica aquest filtre quan s'obri el widget",
  "info": "Informació",
  "expressions": "Expressions",
  "allowCustom": "Permet la creació de filtres personalitzats",
  "filterActions": "Acciones de filtre personalitzades",
  "custom": "Habilita el filtre personalitzat",
  "resetAll": "Permet restablir tots els valors d'entrada",
  "turnOffAll": "Permet desactivar tots els filtres",
  "matchMsgSetAll": "Mostra les entitats que coincideixin amb tots els filtres",
  "matchMsgSetAny": "Mostra les entitats que coincideixin amb algun filtre"
});