define({
  "settings": "설정",
  "titleSettings": "텍스트 설정",
  "imageSettings": "이미지 설정",
  "backgroundColor": "배경 색상",
  "alignment": "정렬",
  "textSize": "텍스트 크기",
  "textColor": "텍스트 색상",
  "dataSource": "데이터 원본",
  "chartSettings": "차트 설정",
  "data": "데이터",
  "dataLabels": "데이터 레이블",
  "displayMode": "디스플레이 모드",
  "featureOption": "각 피처별로 값 표시",
  "categoryOption": "범주별로 값 표시",
  "countOption": "범주별로 피처 개수 표시",
  "fieldOption": "차트로 속성 값 표시",
  "categoryField": "범주 필드",
  "labelField": "레이블 필드",
  "valueFields": "값 필드",
  "operation": "작업",
  "sumOption": "합계",
  "averageOption": "평균",
  "minOption": "최소값",
  "maxOption": "최대값",
  "dataFormat": "데이터 형식",
  "decimalPlaces": "소수 자릿수",
  "prefix": "접두사",
  "suffix": "접미사",
  "dataType": "데이터 유형",
  "featureCount": "피처 개수",
  "fieldStatistics": "필드 통계",
  "display": "보기",
  "chartColor": "차트 색상",
  "horizontalAxis": "수평축",
  "verticalAxis": "수직축",
  "legend": "범례",
  "position": "위치",
  "top": "위쪽",
  "bottom": "아래쪽",
  "useDataSourceSelection": "선택 사용",
  "dataSourceFilterByExtent": "범위별 필터링",
  "changeTemplate": "템플릿 변경",
  "numberSettings": "숫자 설정",
  "gaugeSettings": "게이지 설정",
  "indicators": "지시자",
  "ifValue": "If 값",
  "and": "그리고",
  "numberOperatorIsLessThan": "다음보다 작음",
  "numberOperatorIsGreaterThan": "다음보다 큼",
  "numberOperatorIsBetween": "다음 사이에 속함",
  "numberOperatorIsEqual": "다음과 같음",
  "numberOperatorIsNotEqual": "다음과 같지 않음",
  "then": "Then",
  "ratio": "비율",
  "trueValue": "True 값",
  "changeValueColor": "다음으로 값 색상 변경",
  "changeGaugeColor": "다음으로 게이지 색상 변경",
  "setIndicatorIcon": "다음으로 지시자 아이콘 설정",
  "icons": "아이콘",
  "style": "스타일",
  "placement": "위치",
  "left": "왼쪽",
  "replace": "바꾸기",
  "right": "오른쪽",
  "color": "색상",
  "dataRange": "데이터 범위",
  "targetValue": "대상 값",
  "currentValue": "현재 값",
  "gaugeColor": "게이지 색상",
  "min": "최소값",
  "max": "최대값",
  "displayValueIn": "다음에 값 표시:",
  "noData": "데이터 없음",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "경고",
  "noSettingWaring1": "요소를 클릭하여 등록정보를 설정하세요.",
  "noSettingWaring2": "드래그하여 요소의 크기를 조정하거나 순서를 변경하세요.",
  "donNotShowAgain": "다시 표시 안 함",
  "changeTemplateWarning": "이 작업을 수행하면 모든 설정이 지워지고 비어 있는 새 템플릿이 열립니다.",
  "requiredFieldWarning": "이 값이 필요합니다(필수).",
  "dataSourceNotSet": "데이터 원본을 설정하세요.",
  "addIndicatorTip": "지시자 추가",
  "chooseTemplatePopupTitle": "템플릿 선택",
  "stringsInTemplate": {
    "name_number": "숫자",
    "name_gauge": "게이지",
    "name_vertical_gauge": "수직 게이지",
    "name_horizontal_gauge": "수평 게이지",
    "name_pie_chart": "원형 차트",
    "name_column_chart": "세로 막대형 차트",
    "name_bar_chart": "막대형 차트",
    "name_line_chart": "선형 차트",
    "titleOfTheInfographic": "인포그래픽 제목",
    "description": "설명: 이 인포그래픽에 대한 추가 정보입니다."
  }
});