define(
   ({
    "tabs_section_Label": "Välilehdet",
    "addTab": "Lisää välilehti",
    "layerName": "Karttataso",
    "layerType": "Analyysityyppi",
    "layerLabel": "Tunnusteksti",
    "actions": "Toimet",
    "closest": "Lähin kohde",
    "proximity": "Läheisyys",
    "summary": "Yhteenveto",
    "select_lbl": "-- Valitse --",
    "general_setting_Label": "Yleiset asetukset",
    "units_text_lbl": "Etäisyyden yksiköt",
    "miles": "Mailia",
    "kilometers": "Kilometriä",
    "feet": "Jalkaa",
    "meters": "Metriä",
    "yards": "Jaardia",
    "nauticalMiles": "Meripeninkulmaa",
    "maximum_distance_lbl": "Lähimmän kohteen enimmäisetäisyys",
    "buffer_text_lbl": "Puskurin nimiö",
    "buffer_lbl": "Puskurin etäisyys",
    "buffer_max_lbl": "Puskurin enimmäisetäisyys",
    "buffer_min_lbl": "Puskurin vähimmäisetäisyys",
    "routing_checkBox": "Ota reititys käyttöön",
    "weather_Label": "Sääolosuhteet",
    "weather_checkBox": "Sisällytä säätiedot",
    "selectLayers": "Valitse sääkarttatasot",
    "currentlySelectedLayer": "Tällä hetkellä valitut sääkarttatasot",
    "missingTabLabel": "Vähintään yhdestä välilehdestä puuttuu nimiö",
    "cancel": "Peruuta",
    "ok": "OK",
    "missingLayerInWebMap": "Toiminnallisia karttatasoja ei löytynyt.",
    "selectFields": "Valitse kentät",
    "addField": "Lisää kenttä",
    "sum": "SUMMA",
    "min": "VÄHINT.",
    "max": "ENINT.",
    "avg": "KESKIARVO",
    "count": "MÄÄRÄ",
    "area": "ALUE",
    "length": "PITUUS",
    "count_checkBox": "Näytä kohteiden määrä",
    "area_checkBox": "Näytä alueen summa",
    "length_checkBox": "Näytä pituuden summa",
    "max_records": "Enimmäisraja saavutettu",
    "save_label": "Tallenna asetukset",
    "save_checkbox": "Ota tallennus käyttöön",
    "csv_label": "Salli tulosten vienti",
    "csv_checkbox": "CSV-asetukset",
    "display_label": "Näytä asetukset",
    "display_checkbox": "Näytä kohteiden yhteenveto",
    "must_select_template": "Valitse yksi muokkausmalleista Tallenna asetukset -kohdassa.",
    "count_label": "Määrän nimiö",
    "area_label": "Alueen nimiö",
    "length_label": "Pituuden nimiö",
    "invalid_string_width": "Arvo on liian pitkä. ",
    "layer_type_not_supported": "Karttatasotyyppiä ei tueta: "
  })
);
