define({
  "addLayer": "Dodaj sloj",
  "layerName": "Sloj",
  "layerRefresh": "Osveži",
  "layerLabel": "Oznaka",
  "actions": "Radnje",
  "mainPanelTextPlaceholder": "ex: Poslednji put ažurirano:",
  "invalidInterval": "Samo numerički karakteri su podržani.",
  "uploadImage": "Otpremi snimak",
  "iconColumnText": "Prikaz",
  "refreshInterval": "Vreme u minutima",
  "refreshIntervalTitle": "Procenjeno kao vreme u minutima",
  "mainPanelText": "Tekst glavne table",
  "mainPanelIcon": "Snimak glavne table",
  "refreshIntervalInstruction": "Osveži slojeve svakih:",
  "optionsText": "Opcije",
  "symbolOptionsText": "Simbolika mape",
  "iconOptionsText": "Simbolika panela",
  "sympolPopupTitle": "Postavke prikaza",
  "rdoLayer": "Podrazumevani simbol",
  "rdoCustom": "Koristi snimak",
  "chkCluster": "Omogući klastering",
  "defineClusterSymbol": "Navedi simbol klastera",
  "rdoEsri": "Izaberi simbol",
  "rdoLayerIcon": "Koristi simbol mape",
  "rdoCustomIcon": "Koristi snimak",
  "editCustomSymbol": "Izmeni prilagođeni simbol",
  "editCustomIcon": "Izmeni prilagođenu ikonu",
  "missingRefreshValue": "Obezbedite vrednost intervala osvežavanja.",
  "panelIconOption": "Prikaži sliku logotipa",
  "enableRefresh": "Omogući osvežavanje sloja",
  "disableRefresh": "Osvežavanje sloja je podržano samo za kolekcije geoobjekata",
  "layer_type_not_supported": "Tip sloja nije podržan: ",
  "refreshUnit": "minuti.",
  "symbolOptions": "Simbol",
  "panelFeatureDisplay": "Panel",
  "chkGroup": "Karakteristike grupe",
  "selectField": "Polje",
  "fieldLabel": "Oznaka",
  "addField": "Dodaj polje",
  "featureOptionsText": "Opcije sloja",
  "groupOptionsText": "Opcije grupe",
  "panelCountOption": "Prikaži brojače geoobjekata",
  "rdoStack": "Prikaži novu liniju za svako polje",
  "rdoAppend": "Dodaj polja na jednoj liniji",
  "missingLayerInWebMap": "Nema pronađenih operativnih slojeva.",
  "displayClusterCnt": "Prikaži izbrojane geoobjekte",
  "defineClusterFont": "Naznači boju fonta",
  "max_records": "Maksimalno ograničenje polja je dostignuto"
});