define({
  "addLayer": "Aggiungi layer",
  "layerName": "Layer",
  "layerRefresh": "Aggiorna",
  "layerLabel": "Etichetta",
  "actions": "Azioni",
  "mainPanelTextPlaceholder": "es.: Ultimo aggiornamento:",
  "invalidInterval": "Sono supportati solo caratteri numerici.",
  "uploadImage": "Carica immagine",
  "iconColumnText": "Visualizza",
  "refreshInterval": "Tempo in minuti",
  "refreshIntervalTitle": "Valutato come tempo in minuti",
  "mainPanelText": "Testo pannello principale",
  "mainPanelIcon": "Immagine pannello principale",
  "refreshIntervalInstruction": "Aggiorna layer ogni:",
  "optionsText": "Opzioni",
  "symbolOptionsText": "Simbologia mappa",
  "iconOptionsText": "Simbologia pannello",
  "sympolPopupTitle": "impostazioni di Visualizzazione",
  "rdoLayer": "Simbolo predefinito",
  "rdoCustom": "Usa immagine",
  "chkCluster": "Abilita clustering",
  "defineClusterSymbol": "Specifica simbolo cluster",
  "rdoEsri": "Seleziona un simbolo",
  "rdoLayerIcon": "Usa simbolo mappa",
  "rdoCustomIcon": "Usa immagine",
  "editCustomSymbol": "Modifica simbolo personalizzato",
  "editCustomIcon": "Modifica icona personalizzata",
  "missingRefreshValue": "Specificare un valore dell'intervallo di aggiornamento.",
  "panelIconOption": "Visualizza immagine logo",
  "enableRefresh": "Abilita aggiornamento layer",
  "disableRefresh": "Aggiornamento layer supportato solo per raccolte feature",
  "layer_type_not_supported": "Il tipo di layer non è supportato: ",
  "refreshUnit": "minuti.",
  "symbolOptions": "Simbolo",
  "panelFeatureDisplay": "Pannello",
  "chkGroup": "Raggruppa feature",
  "selectField": "Campo",
  "fieldLabel": "Etichetta",
  "addField": "Aggiungi Campo",
  "featureOptionsText": "Opzioni layer",
  "groupOptionsText": "Raggruppa opzioni",
  "panelCountOption": "Visualizza conteggi feature",
  "rdoStack": "Visualizza nuova linea per ogni campo",
  "rdoAppend": "Aggiungi campi su una riga singola",
  "missingLayerInWebMap": "Nessun layer operativo trovato.",
  "displayClusterCnt": "Visualizza conteggio feature",
  "defineClusterFont": "Specifica colore carattere",
  "max_records": "Raggiunto limite campo massimo"
});