define(
   ({
    addLayer: "Aggiungi layer",
    layerName: "Layer",
    layerRefresh: "Aggiorna",
    layerLabel: "Etichetta",
    actions: "Azioni",
    popupOk: "OK",
    popupCancel: "Annulla",
    mainPanelTextPlaceholder: "es.: CONDIZIONI AUTOSTRADE",
    invalidInterval: "Sono supportati solo caratteri numerici.",
    uploadImage: "Carica immagine",
    iconColumnText: "Icona",
    refreshInterval: "1 \'Valutato come tempo in minuti\'",
    refreshIntervalTitle: "Valutato come tempo in minuti",
    mainPanelText: "Testo pannello principale",
    mainPanelIcon: "Immagine pannello principale",
    refreshIntervalInstruction: "Intervallo di aggiornamento",
    optionsText: "Opzioni",
    symbolOptionsText: "Opzioni relative ai simboli",
    iconOptionsText: "Opzioni icona",
    sympolPopupTitle: "Imposta simbolo",
    rdoLayer: "Simbolo layer",
    rdoCustom: "Simbolo personalizzato",
    chkCluster: "Abilita clustering",
    defineClusterSymbol: "Simbolo cluster",
    defineThemeClusterSymbol: "Simbolo cluster da tema",
    rdoEsri: "Simbolo Esri",
    rdoLayerIcon: "Usa simbolo come icona",
    rdoCustomIcon: "Carica icona personalizzata",
    editCustomSymbol: "Modifica simbolo personalizzato",
    editCustomIcon: "Modifica icona personalizzata",
    missingRefreshValue: "Specificare un valore dell\'intervallo di aggiornamento.",
    panelIconOption: "Visualizza intestazione pannello",
    enableRefresh: "Abilita aggiornamento layer",
    disableRefresh: "Aggiornamento layer supportato solo per raccolte feature",
    layer_type_not_supported: "Il tipo di layer non è supportato: "
  })
);
