define({
  "_widgetLabel": "Atribūtu tabula",
  "_featureAction_ShowRelatedRecords": "Rādīt saistītos ierakstus",
  "_featureAction_ViewInTable": "Skatīt atribūtu tabulā",
  "ok": "Labi",
  "cancel": "Atcelt",
  "unsupportQueryWarning": "Slānim ir jāatbalsta vaicājuma darbība, lai rādītu atribūtu tabulas logrīkā. Nodrošiniet, lai pakalpojumā būtu ieslēgta vaicājuma iespēja.",
  "exportMessage": "Vai eksportēt datus uz CSV failu?",
  "exportFiles": "Eksportēt uz CSV",
  "exportSelected": "Eksportēt atlasīto CSV failā",
  "exportAll": "Eksportēt visu CSV failā",
  "options": "Opcijas",
  "zoomto": "Pietuvināt",
  "highlight": "Izcelt grafiku",
  "selectAll": "Izvēlēties ierakstus visās lapās",
  "selectPage": "Izvēlēties ierakstus pašreizējā lapā",
  "clearSelection": "Notīrīt izvēlēto",
  "filter": "Filtrs",
  "setFilterTip": "Lūdzu, pareizi iestatiet filtru.",
  "noFilterTip": "Bez definētas filtra izteiksmes šajā vaicājuma uzdevumā būs norādīti visi elementi norādītajā datu avotā.",
  "filterByExtent": "Filtrēt pēc kartes pārklājuma",
  "showSelectedRecords": "Rādīt izvēlētos ierakstus",
  "showAllRecords": "Rādīt visus ierakstus",
  "showRelatedRecords": "Rādīt saistītos ierakstus",
  "noRelatedRecords": "Nav atrasti saistīti ieraksti",
  "attachmentColumn": "Fotoattēli un faili",
  "refresh": "Atjaunot",
  "features": "elementi",
  "records": "ieraksti",
  "selected": "izraudzīts",
  "transparent": "Caurspīdīgs režīms",
  "indicate": "Atrast izvēli",
  "columns": "Rādīt/Paslēpt kolonnas:",
  "selectionSymbol": "Izvēles simbols",
  "closeMessage": "Paslēpt tabulu (izvērst to vēlreiz no lejas)",
  "dataNotAvailable": "Dati nav pieejami.<br>Noklikšķiniet uz pogas [Atsvaidzināt], lai mēģinātu vēlreiz.",
  "openTableTip": "Atvērt atribūtu tabulu",
  "closeTableTip": "Paslēpt atribūtu tabulu",
  "sortAsc": "Šķirot augošā secībā",
  "sortDes": "Šķirot dilstošā secībā",
  "statistics": "Statistika",
  "attachments": "Pielikumi",
  "files": "faili"
});