define({
  "_widgetLabel": "Analiza zagrożeń",
  "threatAnalysisMainPageTitle": "Na podstawie serwisu JCAT Counterterrorism Guide",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Lokalizacja wejściowa",
  "interactive": "Interaktywnie",
  "fromCoord": "Stałe współrzędne",
  "existingFeature": "Od istniejących obiektów",
  "threatAnalysisCoordInputLabel": "Lokalizacja zagrożenia",
  "enterCoords": "Wpisz współrzędne",
  "threatAddPointToolTip": "Dodaj lokalizację zagrożenia",
  "threatDrawPointToolTip": "Kliknij, aby dodać lokalizację zagrożenia",
  "threatType": "Typ zagrożenia",
  "threatPlaceholder": "Rozpocznij wpisywanie, aby wyszukać zagrożenie",
  "mandatoryLabel": "Obowiązkowa odległość ewakuacji",
  "safeLabel": "Bezpieczna odległość ewakuacji",
  "zoneTypeLabel": "Typ strefy",
  "feetLabel": "Stopy",
  "metersLabel": "Metry",
  "unitsLabel": "Jednostki",
  "threatGraphicLayer": "Grafika zagrożeń",
  "settingsTitle": "Ustawienia",
  "mandatoryButtonLabel": "Skonfiguruj ustawienia obowiązkowej odległości ewakuacji",
  "safeButtonLabel": "Skonfiguruj ustawienia schronienia w miejscu bezpiecznym",
  "style": "Styl",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "Kreska",
    "esriSLSDashDot": "Kreska-kropka",
    "esriSLSDashDotDot": "Kreska-kropka-kropka",
    "esriSLSDot": "Kropka",
    "esriSLSLongDash": "Długa kreska",
    "esriSLSLongDashDot": "Długa kreska-kropka",
    "esriSLSNull": "Pusta wartość",
    "esriSLSShortDash": "Krótka kreska",
    "esriSLSShortDashDot": "Krótka kreska-kropka",
    "esriSLSShortDashDotDot": "Krótka kreska-kropka-kropka",
    "esriSLSShortDot": "Krótka kropka",
    "esriSLSSolid": "Stały"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Cofnij",
    "esriSFSCross": "Krzyż",
    "esriSFSDiagonalCross": "Po przekątnej",
    "esriSFSForwardDiagonal": "Dalej",
    "esriSFSHorizontal": "Poziomo",
    "esriSFSNull": "Pusta wartość",
    "esriSFSSolid": "Stały",
    "esriSFSVertical": "Pionowo"
  },
  "resultsTitle": "Wyniki",
  "publishTABtn": "Publikuj",
  "layerName": "Nazwa opublikowanej warstwy",
  "invalidLayerName": "Nazwa warstwy może zawierać tylko znaki alfanumeryczne i znaki podkreślenia",
  "missingLayerName": "Należy podać nazwę warstwy",
  "missingLayerNameMessage": "Przed opublikowaniem warstwy należy wprowadzić jej prawidłową nazwę",
  "publishingFailedLayerExists": "Publikowanie nie powiodło się: Masz tylko usługę obiektową o nazwie {0}. Wybierz inną nazwę warstwy.",
  "checkService": "Sprawdź usługę: {0}",
  "createService": "Utwórz usługę: {0}",
  "unableToCreate": "Nie można utworzyć: {0}",
  "addToDefinition": "Dodaj do definicji: {0}",
  "successfullyPublished": "Pomyślnie opublikowano warstwę internetową{0}Zarządzaj warstwą internetową",
  "successfullyAppended": "Pomyślnie dołączono nowe obiekty do warstwy internetowej{0}Zarządzaj warstwą internetową",
  "userRole": "Nie można utworzyć usługi, ponieważ użytkownik nie ma uprawnień",
  "retrieveExistingLayerError": "Nie można pobrać {0}. Opublikuj, używając innej nazwy warstwy",
  "publishToNewLayer": "Opublikuj wyniki w nowej warstwie obiektowej",
  "pipeBombLabel": "Bomba rurowa",
  "suicideBombLabel": "Bomba samobójcza",
  "briefcaseLabel": "Teczka",
  "carLabel": "Samochód",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Mały samochód dostawczy",
  "containerWaterTruckLabel": "Pojazd kontenerowy/cysterna",
  "semiTrailerLabel": "Naczepa",
  "transparencyLabel": "Przezroczystość",
  "outline": "Obrys",
  "fill": "Wypełnienie (kolor zostanie zastosowany tylko wtedy, gdy wybranym stylem jest styl pełny)",
  "createBtn": "Utwórz strefy",
  "clearBtn": "Wyczyść",
  "invalidNumberMessage": "Wprowadzona wartość nie jest prawidłowa",
  "invalidRangeMessage": "Wartość musi być większa od 0",
  "parseCoordinatesError": "Nie można przeanalizować współrzędnych. Sprawdź wpisane dane.",
  "manualCoordinateInputInfo": "Wprowadź ręcznie współrzędne i kliknij klawisz <b>Enter</b>, aby powiększyć do ich zasięgu",
  "selectDrawModeLabel": "Wybierz tryb rysowania",
  "selectFeatureLabel": "Wybierz obiekt z tej warstwy"
});