define({
  "transparencyLabel": "Prosojnost",
  "outline": "Obroba",
  "fill": "Polnilo (barva se uporablja le, če je slog nastavljen na enobarvno polnilo)",
  "style": "Slog",
  "mandatoryLabel": "Obvezna razdalja za evakuacijo",
  "mandatoryButtonLabel": "Konfiguriraj nastavitve za obvezno razdaljo za evakuacijo",
  "safeLabel": "Varna razdalja za evakuacijo",
  "safeButtonLabel": "Konfiguriraj nastavitve za varno razdaljo za evakuacijo",
  "selectOpLayerLabel": "Izberi operativni sloj za rezultate",
  "selectDefaultMeasurementLabel": "Izberi privzeto mersko enoto",
  "helpIconTooltip": "Seznam operativnega sloja je poseljen s sloji iz trenutne spletne karte, ki so poligonske geometrijske vrste.",
  "lineStyles": {
    "esriSLSDash": "Črtica",
    "esriSLSDashDot": "Črtica pika",
    "esriSLSDashDotDot": "Črtica pika pika",
    "esriSLSDot": "Pika",
    "esriSLSLongDash": "Dolga črtica",
    "esriSLSLongDashDot": "Dolga črtica pika",
    "esriSLSNull": "Brez vrednosti",
    "esriSLSShortDash": "Kratka črtica",
    "esriSLSShortDashDot": "Kratka črtica pika",
    "esriSLSShortDashDotDot": "Kratka črtica pika pika",
    "esriSLSShortDot": "Kratka pika",
    "esriSLSSolid": "Enobarvno"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Nazaj",
    "esriSFSCross": "Križ",
    "esriSFSDiagonalCross": "Diagonalno",
    "esriSFSForwardDiagonal": "Naprej",
    "esriSFSHorizontal": "Horizontalno",
    "esriSFSNull": "Brez vrednosti",
    "esriSFSSolid": "Enobarvno",
    "esriSFSVertical": "Vertikalno"
  },
  "threatTypeLabel": "Vrsta nevarnosti",
  "symbologyLabel": "Simbologija",
  "generalLabel": "Splošno",
  "addThreatTypesLabel": "Dodaj vrsto nevarnosti",
  "threatTypeColLabel": "Vrsta nevarnosti",
  "actions": "Dejanja",
  "newThreatTypePopupLabel": "Nova vrsta nevarnosti",
  "chooseDefaultThreatTypeIconLabel": "Izberite izmed privzetega",
  "mandatoryDistance": "Obvezna razdalja za evakuacijo",
  "safeDistance": "Varna razdalja za evakuacijo",
  "units": "Enote",
  "chooseDefaultThreatLabel": "Izberite privzeto vrsto nevarnosti",
  "defaultThreatTypePopUpLabel": "Privzete vrste nevarnosti",
  "editThreatLabel": "Uredite nevarnost",
  "defaultThreatTypeIconTooltip": "Seznam privzetih vrst nevarnosti",
  "uniqueThreatTypeMsg": "Vnesite enolično vrsto nevarnosti, vrsta nevarnosti s tem imenom že obstaja.",
  "requiredThreatTypeMsg": "To polje je obvezno",
  "unitMeasureLabel": "Razdalje so v {0}",
  "pipeBombLabel": "Cevna bomba",
  "suicideBombLabel": "Samomorilska bomba",
  "briefcaseLabel": "Aktovka",
  "carLabel": "Avto",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Majhno dostavno vozilo",
  "containerWaterTruckLabel": "Zabojnik/tovornjak za prevažanje vode",
  "semiTrailerLabel": "Polpriklopnik"
});