define({
  "_widgetLabel": "Pametni uređivač",
  "_featureAction_SmartEditor": "Pametni uređivač",
  "noEditPrivileges": "Vaš račun nema dopuštenje za stvaranje ili mijenjanje podataka.",
  "widgetActive": "Aktivno",
  "widgetNotActive": "Nije aktivno",
  "pressStr": "Pritisnite ",
  "ctrlStr": " CTRL ",
  "snapStr": " za omogućivanje priljepljivanja",
  "noAvailableTempaltes": "Nema dostupnih predložaka",
  "editorCache": " - Predmemorija uređivača",
  "presetFieldAlias": "Polje",
  "presetValue": "Prethodno postavljena vrijednost",
  "usePresetValues": " Upotrijebi prethodne postavljene vrijednosti (samo novi geoobjekti)",
  "editGeometry": " Uredi geometriju",
  "savePromptTitle": "Spremi geoobjekt",
  "savePrompt": "Želite li spremiti trenutačni geoobjekt?",
  "deletePromptTitle": "Izbriši geoobjekt",
  "deleteAttachment": "Izbriši privitak",
  "deletePrompt": "Jeste li sigurni da želite izbrisati odabrani geoobjekt?",
  "attachmentLoadingError": "Pogreška pri učitavanju privitaka",
  "attachmentSaveDeleteWarning": "Upozorenje: promjene na privicima automatski se spremaju",
  "autoSaveEdits": "Automatski sprema novi geoobjekt",
  "addNewFeature": "Stvori novi geoobjekt",
  "featureCreationFailedMsg": "Nije moguće stvoriti novi zapis/geoobjekt",
  "relatedItemTitle": "Povezana tablica/sloj",
  "relatedFeatureCount": "${layerTitle} s ${featureCount} geoobjektima",
  "createNewFeatureLabel": "Stvori novi geoobjekt za ${layerTitle}",
  "invalidRelationShipMsg": "Pobrinite se da primarno polje ključa: „${parentKeyField}” ima valjanu vrijednost",
  "pendingFeatureSaveMsg": "Spremite uređivanja geoobjekta prije stvaranja povezanog geoobjekta.",
  "attachmentsRequiredMsg": "(*) Privici su obvezni.",
  "coordinatePopupTitle": "Pomakni geoobjekt na XY lokaciju",
  "coordinatesSelectTitle": "Koordinatni sustav:",
  "mapSpecialReferenceDropdownOption": "Prostorna referenca karte",
  "latLongDropdownOption": "Geografska dužina/širina",
  "xAttributeTextBoxLabel": "X-koordinata:",
  "yAttributeTextBoxLabel": "Y-koordinata:",
  "latitudeTextBoxLabel": "Geografska širina:",
  "longitudeTextBoxLabel": "Geografska dužina:",
  "presetGroupFieldsLabel": "'${groupName}' bit će primijenjen na sljedeća polja slojeva:",
  "presetGroupNoFieldsLabel": "'${groupName}’ nema pridruženih polja",
  "groupInfoLabel": "Informacije o grupi za '${groupName}'",
  "editGroupInfoIcon": "Uredi vrijednost grupe za ${groupName}",
  "filterEditor": {
    "all": "Svi",
    "noAvailableTempaltes": "Nema dostupnih predložaka",
    "searchTemplates": "Pretraži predloške",
    "filterLayerLabel": "Slojevi za filtriranje"
  },
  "invalidConfiguration": "Widget nije konfiguriran ili slojevi u konfiguraciji više nisu u karti. Otvorite app u načinu sastavljača i ponovo konfigurirajte widget.",
  "geometryServiceURLNotFoundMSG": "Nije moguće dohvatiti URL usluge geometrije",
  "clearSelection": "Očisti",
  "refreshAttributes": "Ažuriranje atributa geoobjekata",
  "automaticAttributeUpdatesOn": "Automatsko ažuriranje atributa geoobjekata: uključeno",
  "automaticAttributeUpdatesOff": "Automatsko ažuriranje atributa geoobjekata: isključeno",
  "moveSelectedFeatureToGPS": "Pomakni odabrani geoobjekt na trenutnu GPS lokaciju",
  "moveSelectedFeatureToXY": "Pomakni odabrani geoobjekt na XY lokaciju",
  "mapNavigationLocked": "Navigacija karte: zaključana",
  "mapNavigationUnLocked": "Navigacija karte: otključana",
  "copyFeatures": {
    "title": "Kopiraj geoobjekte",
    "createFeatures": "Stvori geoobjekte",
    "createSingleFeature": "Stvori 1 multi geometrijski geoobjekt",
    "noFeaturesSelectedMessage": "Nema odabranog geoobjekta",
    "selectFeatureToCopyMessage": "Odaberite geoobjekte za kopiranje.",
    "multipleFeatureSaveWarning": "Napomena: Stvaranje više geoobjekata pomoću kopiranja geoobjekata odmah će spremiti sve geoobjekte"
  },
  "addingFeatureError": "Pogreška prilikom dodavanja odabranih geoobjekata u sloj. Pokušajte ponovno.",
  "addingFeatureErrorCount": "‘${copyFeatureErrorCount}' geoobjekata nije se uspjelo kopirati.",
  "selectingFeatureError": "Pogreška prilikom odabira geoobjekata u sloju. Pokušajte ponovno.",
  "customSelectOptionLabel": "Odaberi geoobjekte za kopiranje",
  "noFeatureSelectedMessage": "Nema odabranih geoobjekata.",
  "multipleFeatureSaveMessage": "Svi će se geoobjekti odmah spremiti. Želite li nastaviti?",
  "relativeDates": {
    "dateTypeLabel": "Vrsta datuma",
    "valueLabel": "Vrijednost",
    "fixed": "Popravljeno",
    "current": "Trenutačno",
    "past": "Prošli",
    "future": "Buduće",
    "popupTitle": "Odaberi vrijednost",
    "hintForFixedDateType": "Savjet: određeni datum i vrijeme bit će upotrijebljeni kao prethodno postavljene zadane vrijednosti.",
    "hintForCurrentDateType": "Savjet: trenutačni datum i vrijeme bit će upotrijebljeni kao prethodno postavljene zadane vrijednosti.",
    "hintForPastDateType": "Savjet: Određena vrijednost bit će odbijena od trenutačnog datuma i vremena za zadanu prethodno postavljenu vrijednost.",
    "hintForFutureDateType": "Savjet: Određena vrijednost bit će dodana trenutačnom datumu i vremenu za zadanu prethodno postavljenu vrijednost.",
    "noDateDefinedTooltip": "Nije određen datum",
    "relativeDateWarning": "Vrijednost datuma ili vremena mora se specificirati kako bi se mogla spremiti zadana unaprijed postavljena vrijednost."
  }
});