define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Dodajte točko s klikom na karto.",
  "addRingsDtWt": "Dodajte obroče, čas vožnje ali čas hoje.",
  "apply": "Uporabi",
  "back": "Zadaj",
  "colon": ":",
  "creditInformation": "Informacije o kreditih",
  "driveTime": "Čas vožnje",
  "esriInfographics": "Infografika Esri",
  "esriReports": "Poročila Esri",
  "headerDescription_km": "kilometer",
  "headerDescription_miles": "milja",
  "headerDescription_minutes": "minuta",
  "infographics": "Infografike",
  "invalidValueRing": "Vrednosti morajo biti v razponu od 0 do 1.000.",
  "invalidValueDTWT": "Vrednosti morajo biti v razponu od 0 do 300.",
  "km": "km",
  "miles": "milje",
  "minutes": "minut",
  "myInfographics": "Moje infografike",
  "myReports": "Moja poročila",
  "noPermissions": "Vaš račun ne more zagnati pripomočka Business Analyst. Za zagon pripomočka Business Analyst, vam mora administrator vaše organizacije odobriti pravice za GeoEnrichment in Network Analysis <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\"></a ter vam tudi dodeliti <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">kredite</a>.",
  "radii": "premer",
  "radius": "Polmer",
  "radius_lowercase": "polmer",
  "reports": "Poročila",
  "ring": "Obroč",
  "rings": "Obroči",
  "runInfographic": "Zaženi infografiko",
  "runReport": "Zaženi poročilo",
  "selectPointOrPolygon": "Na karti izberite geoobjekt v obliki točke ali poligona, poiščite naslov ali mesto oziroma na karto spustite buciko za ogled več informacij o območjih.",
  "selectReport": "Izberi poročilo",
  "selectTemplate": "Izberi predlogo",
  "sharedInfographics": "Deljena infografika",
  "sharedReports": "Deljena poročila",
  "thisEntryIsNotValid": "Vnos ni veljaven.",
  "time": "Čas",
  "walkTime": "Čas hoje",
  "widgetDescription": "Dostopajte do infografike in poročil, ki povzemajo ključne indikatorje in podatke za katero koli območje.",
  "None": "Izberi ..."
});