define({
  "add": "Клацніть, щоб додати нову",
  "title": "Заголовок",
  "placeholderBookmarkName": "Назва закладки",
  "ok": "OK",
  "cancel": "Скасувати",
  "warning": "Закінчіть редагування!",
  "edit": "Редагувати закладку",
  "errorNameExist": "Закладка існує!",
  "errorNameNull": "Недійсна назва закладки!",
  "addBookmark": "Створити нову",
  "thumbnail": "Зразок",
  "thumbnailHint": "Клацніть на зображенні для оновлення",
  "displayBookmarksAs": "Відображати закладки як",
  "cards": "Картки",
  "list": "Список",
  "cardsTips": "Вид карток",
  "listTips": "Вид списку",
  "makeAsDefault": "Зробити за замовчуванням",
  "default": "За замовчуванням",
  "editable": "Дозволити додавати закладки у віджет.",
  "alwaysSync": "Відображати закладки з веб-карти",
  "configCustom": "Відображати власні закладки",
  "import": "Імпорт",
  "create": "Створити",
  "importTitle": "Імпорт закладок",
  "importFromWeb": "Імпорт закладок з поточної веб-карти",
  "selectAll": "Вибрати всі",
  "noBookmarkInConfig": "Натисніть «Імпорт» або «Створити нову», щоб додати закладки.",
  "noBookmarkInWebMap": "Закладки не налаштовано у карті.",
  "extent": "Екстент",
  "saveExtent": "Зберегти екстент карти для цієї закладки",
  "savelayers": "Зберегти видимість шару",
  "withVisibility": "З видимістю шару",
  "bookmark": "Закладка",
  "addBtn": "Додати",
  "deleteBtn": "Видалити",
  "editBtn": "Редагувати",
  "dragReorderTip": "Утримувати та перетягнути для зміни порядку",
  "deleteBtnTip": "Видалити закладку",
  "editBtnTip": "Редагувати закладку"
});