define({
  "tabs_section_Label": "Tab",
  "addTab": "Thêm Tab",
  "layerName": "Lớp",
  "layerType": "Loại Phân tích",
  "layerLabel": "Nhãn",
  "actions": "Các hành động",
  "closest": "Đối tượng Gần nhất",
  "proximity": "Vùng lân cận",
  "summary": "Tóm tắt",
  "select_lbl": "-- Chọn --",
  "general_setting_Label": "Thiết lập Tổng quan",
  "units_text_lbl": "Đơn vị khoảng cách",
  "maximum_distance_lbl": "Khoảng cách tối đa đối tượng gần nhất",
  "buffer_text_lbl": "Nhãn Vùng đệm",
  "buffer_lbl": "Khoảng cách vùng đệm",
  "buffer_max_lbl": "Khoảng cách vùng đệm tối đa",
  "buffer_min_lbl": "Khoảng cách vùng đệm tối thiểu",
  "routing_checkBox": "Bật định tuyến",
  "weather_Label": "Tùy chọn Thời tiết",
  "weather_checkBox": "Bao gồm thông tin thời tiết",
  "selectLayers": "chọn lớp thời tiết",
  "currentlySelectedLayer": "Các lớp thời tiết đang được chọn",
  "missingTabLabel": "Ít nhất một lớp đang bị thiếu nhãn",
  "missingLayerInWebMap": "Không tìm thấy lớp hoạt động nào.",
  "selectFields": "Chọn Trường",
  "addField": "Thêm Trường",
  "sum": "Tổng",
  "min": "Tối thiểu",
  "max": "Tối đa",
  "avg": "Trung bình",
  "count": "SỐ LƯỢNG",
  "area": "DIỆN TÍCH",
  "length": "ĐỘ DÀI",
  "count_checkBox": "Hiển thị bộ đếm đối tượng",
  "area_checkBox": "Hiển thị tổng khu vực",
  "length_checkBox": "Hiển thị tổng chiều dài",
  "max_records": "Giới hạn tối đa đã đạt đến",
  "save_label": "Lưu Tùy chọn",
  "save_checkbox": "Cho phép lưu",
  "csv_label": "Tùy chọn CSV",
  "csv_checkbox": "Xuất tất cả các trường trong lớp",
  "display_label": "Hiển thị Tùy chọn",
  "display_checkbox": "Hiển thị đối tượng tổng kết",
  "snapshot_label": "Tùy chọn Ảnh chụp nhanh",
  "snapshot_checkbox": "Bật ảnh chụp nhanh",
  "must_select_template": "Vui lòng chọn một trong số các mẫu chỉnh sửa trong Lưu Tùy chọn.",
  "count_label": "Nhãn bộ đếm",
  "area_label": "Nhãn khu vực",
  "length_label": "Nhãn chiều dài",
  "invalid_string_width": "Giá trị quá dài. ",
  "layer_type_not_supported": "Loại lớp không được hỗ trợ: ",
  "groupedSummary": "Đã nhóm Bộ đếm",
  "groupByField": "Nhóm theo Trường",
  "labelType": "Gắn thêm Nhãn",
  "prefix": "Dưới dạng Tiền tố",
  "suffix": "Dưới dạng Hậu tố",
  "need_group_field": "Hãy sử dụng tác vụ chỉnh sửa để xác định Nhóm theo Trường.",
  "fieldTitle": "Trường",
  "typeTitle": "Loại",
  "actionsTitle": "Các hành động",
  "save_point_checkbox": "Lưu điểm",
  "save_line_checkbox": "Lưu đường",
  "save_poly_checkbox": "Lưu vùng",
  "no_valid_popup_fields": "Không có trường hợp lệ nào trong cửa sổ popup. Vui lòng sử dụng thao tác chỉnh sửa để xác định trường.",
  "no_valid_fields": "Không có trường hợp lệ. Vui lòng sử dụng thao tác chỉnh sửa để xác định tùy chọn hiển thị.",
  "incident_label": "Nhãn tab",
  "locate_incident_label": "Vùng nhãn quan tâm",
  "incident": "Sự cố",
  "locate_incident": "Định vị Sự cố",
  "buffer_value": "Khoảng cách Vùng đệm"
});