define({
  "_widgetLabel": "Analýza hrozeb",
  "threatAnalysisMainPageTitle": "Na základě příručky JCAT pro boj proti terorismu",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Vstupní umístění",
  "interactive": "Interaktivní",
  "fromCoord": "Pevná souřadnice",
  "existingFeature": "Z existujících prvků",
  "threatAnalysisCoordInputLabel": "Umístění hrozby",
  "enterCoords": "Zadat souřadnice",
  "threatAddPointToolTip": "Přidat umístění hrozby",
  "threatDrawPointToolTip": "Kliknutím přidejte umístění hrozby",
  "threatType": "Typ hrozby",
  "threatPlaceholder": "Začněte psát pro vyhledání hrozby",
  "mandatoryLabel": "Povinná evakuační vzdálenost",
  "safeLabel": "Bezpečná evakuační vzdálenost",
  "zoneTypeLabel": "Typ zóny",
  "feetLabel": "stopy",
  "metersLabel": "metry",
  "unitsLabel": "Jednotky",
  "threatGraphicLayer": "Grafický symbol hrozby",
  "settingsTitle": "Nastavení",
  "mandatoryButtonLabel": "Konfigurovat nastavení povinné evakuační vzdálenosti",
  "safeButtonLabel": "Konfigurovat nastavení zóny se zavedeným přístřeším",
  "style": "Styl",
  "colorPicker": "Výběr barvy (colorPicker)",
  "lineStyles": {
    "esriSLSDash": "Čárkovaná",
    "esriSLSDashDot": "Čerchovaná",
    "esriSLSDashDotDot": "Dvojčerchovaná",
    "esriSLSDot": "Tečka",
    "esriSLSLongDash": "Čárkovaná s dlouhými čárkami",
    "esriSLSLongDashDot": "Čerchovaná s dlouhými čárkami",
    "esriSLSNull": "Prázdný",
    "esriSLSShortDash": "Krátké čárky",
    "esriSLSShortDashDot": "Čerchovaná s krátkými čárkami",
    "esriSLSShortDashDotDot": "Dvojitě čerchovaná s krátkými čárkami",
    "esriSLSShortDot": "Tečkovaná",
    "esriSLSSolid": "Plný"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Dozadu",
    "esriSFSCross": "Křížek",
    "esriSFSDiagonalCross": "Diagonální",
    "esriSFSForwardDiagonal": "Dopředu",
    "esriSFSHorizontal": "Vodorovně",
    "esriSFSNull": "Prázdný",
    "esriSFSSolid": "Plný",
    "esriSFSVertical": "Svisle"
  },
  "resultsTitle": "Výsledky",
  "publishTABtn": "Publikovat",
  "layerName": "Zveřejněný název vrstvy",
  "invalidLayerName": "Název vrstvy smí obsahovat pouze alfanumerické znaky a podtržítka",
  "missingLayerName": "Musíte zadat název vrstvy",
  "missingLayerNameMessage": "Před zveřejněním musíte zadat platný název vrstvy",
  "publishingFailedLayerExists": "Publikování se nezdařilo: Název feature služby {0} již existuje.Zvolte prosím jiný název vrstvy.",
  "checkService": "Zkontrolovat službu: {0}",
  "createService": "Vytvořit službu: {0}",
  "unableToCreate": "Nelze vytvořit: {0}",
  "addToDefinition": "Přidat do definice: {0}",
  "successfullyPublished": "Webová vrstva {0} úspěšně zveřejněna. Spravovat webovou vrstvu",
  "successfullyAppended": "Nové prvky úspěšně připojeny k webové vrstvě {0}. Spravovat webovou vrstvu",
  "userRole": "Nelze vytvořit službu, protože uživatel nemá oprávnění",
  "retrieveExistingLayerError": "Nepodařilo se získat {0}. Publikujte prosím pomocí jiného názvu vrstvy",
  "publishToNewLayer": "Publikovat výsledky do nové vrstvy prvků",
  "pipeBombLabel": "Trubková bomba",
  "suicideBombLabel": "Bomba pro sebevražedný útok",
  "briefcaseLabel": "Kufřík",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Malá dodávka",
  "containerWaterTruckLabel": "Auto s kontejnerem/cisternou",
  "semiTrailerLabel": "Návěs",
  "transparencyLabel": "Průhlednost",
  "outline": "Obrys",
  "fill": "Výplň (barva se použije, pouze pokud je styl nastaven jako plný)",
  "createBtn": "Vytvořit zóny",
  "clearBtn": "Zrušit",
  "invalidNumberMessage": "Zadaná hodnota je neplatná",
  "invalidRangeMessage": "Hodnota musí být větší než 0",
  "parseCoordinatesError": "Nelze zpracovat souřadnice. Zkontrolujte svůj vstup.",
  "manualCoordinateInputInfo": "Zadejte ručně vstupní souřadnice a přibližte je kliknutím na tlačítko <b>Zadat</b>",
  "selectDrawModeLabel": "Vybrat režim kreslení",
  "selectFeatureLabel": "Vybrat prvek z této vrstvy"
});