define({
  "_widgetLabel": "Koordinatkonvertering",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "formatInput": "Formater inndata",
  "copyAll": "Kopier alt",
  "copySuccessful": "Kopiering vellykket",
  "copyFailed": "Kan ikke kopiere. Brukt Ctrl+C som et alternativ.",
  "parseCoordinatesError": "Kan ikke analysere koordinater. Sjekk inndataene.",
  "comfirmInputNotation": "Bekreft inndatanotasjon",
  "latLongWarningMessage": "Inndatakoordinatene har både et prefiks og et suffiks for bredde- og lengdegradverdi. Den returnerte verdien bygger på prefikset.",
  "inputLabel": "Inndata",
  "outputLabel": "Resultat",
  "cancelButtonLabel": "Avbryt",
  "applyButtonLabel": "Bruk",
  "posNegPrefixLabel": "Legg til prefikset \"+/-\" for positive og negative tall",
  "editCoordinateDialogTitle": "Angi koordinatformatstreng",
  "rememberDecisionLabel": "Husk avgjørelsen og ikke spør igjen.<br/>",
  "coordinateInputLabel": "Angi koordinater eller klikk på kartet",
  "zoomLabel": "Zoom",
  "multipleNotationLabel": "notasjoner funnet som samsvarer med inndataene. Bekreft hvilke du vil bruke:",
  "copyToClipboard": "Kopier til utklippstavle",
  "formatOutput": "Formater utdata",
  "addNewNotation": "Legg til ny notasjon",
  "notationAddedMessage": "Ny notasjon lagt til",
  "addLabel": "Legg til",
  "removeCoordinate": "Fjern koordinat",
  "expandOutput": "Utvid utdata"
});