define(
   ({
    _widgetLabel: "Conocimiento de la situación",
    locate_incident: "Localizar incidente",
    clear_incidents: "Borrar incidentes",
    reverse_geocoded_address: "Dirección más próxima",
    reverse_geocoded_error: "No disponible",
    miles: "Millas",
    kilometers: "Kilómetros",
    feet: "Pies",
    meters: "Metros",
    yards: "Yardas",
    nauticalMiles: "Millas Náuticas",
    now: "AHORA",
    wind: "VIENTO",
    SUN: "DOM",
    MON: "LUN",
    TUE: "MAR",
    WED: "MIÉ",
    THU: "JUE",
    FRI: "VIE",
    SAT: "SÁB",
    defaultTabMsg: "Define un área de incidente.",
    actionLabel: "Establecer como incidente",
    drawPoint: "Dibujar punto",
    drawLine: "Dibujar línea",
    drawPolygon: "Dibujar polígono",
    saveIncident: "Guardar incidente",
    clearIncident: "Borrar incidente",
    useMapExtent: "Usar la extensión del mapa actual",
    noFeaturesFound: "No se encontraron entidades.",
    downloadCSV: "DESCARGAR CSV",
    editComplete: "La entidad se ha guardado correctamente.",
    updateComplete: "La entidad se ha actualizado correctamente.",
    deleteComplete: "La entidad se ha eliminado correctamente.",
    sum: "SUM",
    min: "MIN",
    max: "MÁX",
    avg: "AVG",
    count: "TOTAL",
    area: "ÁREA",
    length: "LONGITUD",
    notPolySave: "Antes de guardar, especifica una distancia de búfer.",
    update_btn: "Hecho",
    delete_btn: "Eliminar",
    get_directions: "Obtener instrucciones",
    incident: "Incidente",
    weather: "Tiempo"
  })
);
