define({
  "settings": "Настройки",
  "titleSettings": "Настройки текста",
  "imageSettings": "Настройки изображения",
  "backgroundColor": "Цвет фона",
  "alignment": "Выравнивание",
  "textSize": "Размер текста",
  "textColor": "Цвет текста",
  "dataSource": "Источник данных",
  "chartSettings": "Настройки диаграммы",
  "data": "Данные",
  "dataLabels": "Надписи данных",
  "displayMode": "Отображать режим",
  "featureOption": "Отображать значения по объектам",
  "categoryOption": "Отображать значения по категории",
  "countOption": "Отображать число объектов по категориям",
  "fieldOption": "Отображать атрибутивные значения в виде диаграмм",
  "categoryField": "Поле категории",
  "labelField": "Поле подписи",
  "valueFields": "Поля значений",
  "operation": "Операция",
  "sumOption": "Сумма",
  "averageOption": "Среднее арифметическое",
  "minOption": "Минимум",
  "maxOption": "Максимум",
  "dataFormat": "Формат данных",
  "decimalPlaces": "Десятичные знаки",
  "prefix": "Префикс",
  "suffix": "Суффикс",
  "dataType": "Тип данных",
  "featureCount": "Число объектов",
  "fieldStatistics": "Поле статистики",
  "display": "Отображение",
  "chartColor": "Цвет диаграммы",
  "horizontalAxis": "Горизонтальная ось",
  "verticalAxis": "Вертикальная ось",
  "legend": "Легенда",
  "position": "Положение",
  "top": "Сверху",
  "bottom": "Cнизу",
  "useDataSourceSelection": "Использовать выборку",
  "dataSourceFilterByExtent": "Фильтр по экстенту",
  "changeTemplate": "Изменить шаблон",
  "numberSettings": "Числовые настройки",
  "gaugeSettings": "Настройки датчика",
  "indicators": "Индикаторы",
  "ifValue": "Если значение",
  "and": "и",
  "numberOperatorIsLessThan": "меньше чем",
  "numberOperatorIsGreaterThan": "больше чем",
  "numberOperatorIsBetween": "между",
  "numberOperatorIsEqual": "равно",
  "numberOperatorIsNotEqual": "не равно",
  "then": "Раньше",
  "ratio": "Относительные",
  "trueValue": "Значение Истина",
  "changeValueColor": "изменить значение цвета на",
  "changeGaugeColor": "изменить цвета датчика на",
  "setIndicatorIcon": "установить значок индикатора как",
  "icons": "Значки",
  "style": "Стиль",
  "placement": "Размещение",
  "left": "Слева",
  "replace": "Заменить",
  "right": "Справа",
  "color": "Цвет",
  "dataRange": "Диапазон данных",
  "targetValue": "Целевое значение",
  "currentValue": "Текущее значение",
  "gaugeColor": "Цвет датчика",
  "min": "Минимум",
  "max": "Максимум",
  "displayValueIn": "Отобразить значение в",
  "noData": "Нет данных",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "М",
  "billionAbbreviation": "G",
  "warning": "Предупреждение",
  "noSettingWaring1": "Щелкните элемент для установки его свойств.",
  "noSettingWaring2": "Потяните для изменения размера или порядка расположения элемента.",
  "donNotShowAgain": "Больше не показывать",
  "changeTemplateWarning": "Ваши настройки будут удалены и откроется новый пустой шаблон.",
  "requiredFieldWarning": "Это значение является обязательным",
  "dataSourceNotSet": "Укажите источник данных.",
  "addIndicatorTip": "Добавьте индикатор",
  "chooseTemplatePopupTitle": "Выбор шаблона",
  "stringsInTemplate": {
    "name_number": "Число",
    "name_gauge": "Датчик",
    "name_vertical_gauge": "Вертикальный датчик",
    "name_horizontal_gauge": "Горизонтальный датчик",
    "name_pie_chart": "Круговая диаграмма",
    "name_column_chart": "Столбчатая диаграмма",
    "name_bar_chart": "Столбчатая диаграмма",
    "name_line_chart": "Диаграмма-график",
    "titleOfTheInfographic": "ЗАГОЛОВОК ИНФОГРАФИКИ",
    "description": "Описание: дополнительная информация об этой инфографике"
  }
});