define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Feu clic al mapa per afegir un punt",
  "addRingsDtWt": "Afegiu anells i temps de recorregut conduint o a peu",
  "apply": "Aplica",
  "back": "Enrere",
  "colon": ":",
  "creditInformation": "Informació de crèdit",
  "driveTime": "Temps de recorregut",
  "esriInfographics": "Infografia d'Esri",
  "esriReports": "Informe d'Esri",
  "headerDescription_km": "quilòmetre",
  "headerDescription_miles": "milla",
  "headerDescription_minutes": "minut",
  "infographics": "Infografia",
  "invalidValueRing": "Els valors han d'estar en un interval de 0 a 1.000.",
  "invalidValueDTWT": "Els valors han d'estar en un interval de 0 a 300.",
  "km": "km",
  "miles": "milles",
  "minutes": "minuts",
  "myInfographics": "La meva infografia",
  "myReports": "Els meus informes",
  "noPermissions": "El vostre compte no pot executar el widget del Business Analyst.  Per poder-lo executar, l'administrador de l'organització us ha d'atorgar <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">permisos</a> de geoenriquiment i anàlisi de xarxa, així com assignar <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">crèdits</a>.",
  "geServiceNotConfigured": "El widget del Business Analyst no es pot executar en aquest portal perquè no té configurat el servei de <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">geoenriquiment</a>.",
  "dirRoutingServiceNotConfigured": "El widget del Business Analyst no es pot executar en aquest portal perquè no té configurat el servei de <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Indicacions i assignació de rutes</a>.",
  "geAndDirRoutingServicesNotConfigured": "El widget del Business Analyst no es pot executar en aquest portal perquè no té configurats els serveis de <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">geoenriquiment</a> i <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Indicacions i assignació de rutes</a>.",
  "radii": "radis",
  "radius": "Radi",
  "radius_lowercase": "radi",
  "reports": "Informes",
  "ring": "Anell",
  "rings": "Anells",
  "runInfographic": "Executa la infografia",
  "runReport": "Executa l'informe",
  "selectPointOrPolygon": "Seleccioneu una entitat de punt o polígon al mapa, cerqueu una adreça o un lloc, o col·loqueu una xinxeta al mapa per veure més informació de les àrees.",
  "selectReport": "Seleccioneu un informe",
  "selectTemplate": "Selecciona una plantilla",
  "sharedInfographics": "Infografia compartida",
  "sharedReports": "Informes compartits",
  "thisEntryIsNotValid": "Aquesta entrada no és vàlida.",
  "time": "Temps",
  "walkTime": "Temps de recorregut a peu",
  "widgetDescription": "Accediu a la infografia i als informes que resumeixen els indicadors i les dades clau de qualsevol àrea.",
  "None": "Seleccioneu..."
});