define({
  "_widgetLabel": "Rediger",
  "_featureAction_Edit": "Rediger",
  "title": "Velg mal for å opprette geoobjekter",
  "pressStr": "Trykk på ",
  "ctrlStr": " CTRL ",
  "snapStr": " for å aktivere festing",
  "close": "Lukk",
  "featureLayers": "Geoobjektlag",
  "searchTemplates": "Søk i maler",
  "noAvailableTempaltes": "Ingen tilgjengelige maler",
  "noCanCreateLayerAreCurrentlyVisible": "Ingen lag som kan opprettes, er synlige for øyeblikket.",
  "layersAreInvisibleOrOutOfScaleRange": "Lag er usynlige eller utenfor målestokkområde.",
  "relatedTables": "Relaterte tabeller:",
  "relatedRecords": "Relaterte poster:",
  "noRelatedRecotds": "Ingen relaterte poster ble funnet.",
  "startToDraw": "Klikk for å begynne å tegne",
  "startToAddPoint": "Klikk for å legge til et punkt",
  "editRelatedFeature": "Redigere relatert geoobjekt",
  "duplicateValueWarning": " Kan ikke sette inn duplisert verdi i ${fieldName} i ${tableName}. Duplikat verdi: ${value}"
});