define({
  "searchTabTitle": "Налаштування джерела пошуку",
  "routeTabTitle": "Налаштування маршруту",
  "add": "Додати джерело пошуку",
  "addGeocoder": "Додати геокодер",
  "geocoder": "Геокодер",
  "setLayerSource": "Задати джерело шару",
  "setGeocoderURL": "Задати URL геодекодера",
  "searchableLayer": "Векторний шар",
  "name": "Назва",
  "countryCode": "Код(-и) країни або регіону",
  "countryCodeEg": "наприклад ",
  "countryCodeHint": "Якщо залишити це поле пустим, буде виконано пошук всіх країн та регіонів",
  "showInfoWindowOnSelect": "Показати спливаюче вікно для знайденого об'єкту або місця розташування",
  "showInfoWindowOnSelect2": "Показати спливаюче вікно, коли знайдено об'єкт або місце розташування.",
  "searchInCurrentMapExtent": "Шукати тільки у поточному екстенті карти",
  "setSearchFields": "Задати поля пошуку",
  "set": "Задати",
  "fieldSearchable": "Доступно для пошуку",
  "zoomScale": "Шкала масштабування",
  "locatorUrl": "URL геодекодера",
  "locatorName": "Назва геодекодера",
  "locatorExample": "Приклад",
  "locatorWarning": "Ця версія сервісу геокодування не підтримується. Віджет підтримує сервіс геокодування версії 10.1 та вище.",
  "locatorTips": "Рекомендації недоступні, оскільки сервіс геокодування не підтримує функцію рекомендування.",
  "layerSource": "Джерело шару",
  "searchLayerTips": "Рекомендації недоступні, оскільки сервіс об'єктів не підтримує функцію розподілення на сторінки.",
  "placeholderText": "Текст заповнювача",
  "searchFields": "Поля пошуку",
  "displayField": "Поле відображення",
  "exactMatch": "Точний збіг",
  "maxSuggestions": "Максимальна кількість рекомендацій",
  "maxResults": "Максимальна кількість результатів",
  "enableLocalSearch": "Активувати локальний пошук",
  "minScale": "Мін. масштаб",
  "minScaleHint": "Якщо масштаб карти більше, ніж цей масштаб, буде застосовуватися локальний пошук",
  "radius": "Радіус",
  "radiusHint": "Визначає радіус області навколо поточного центру карти, який використовується для підняття рангу кандидатів геокодування, щоб кандидати, розташовані найближче до місця розташування, виводилися першими",
  "invalidUrlTip": "URL ${URL} недійсний або недоступний.",
  "routeUrl": "URL маршруту",
  "geocoderOptions": "Опції геокодера",
  "autoComplete": "Автовиконання",
  "maximumSuggestions": "Максимальна кількість рекомендацій",
  "minCharacters": "Максимальна кількість символів",
  "searchDelay": "Затримка пошуку",
  "placeholder": "Текст заповнювача",
  "routeOptions": "Опції маршруту",
  "directionsLanguage": "Мова напрямків",
  "directionsLengthUnits": "Одиниці довжини напрямків",
  "directionsOutputType": "Тип виведення напрямків",
  "impedanceAttribute": "Атрибут імпедансу",
  "kilometers": "Кілометри",
  "miles": "Милі",
  "meters": "Метри",
  "feet": "Фути",
  "yards": "Ярди",
  "nauticalMiles": "Морські милі",
  "parametersTip": "Правильно задайте параметри!",
  "complete": "Виконати",
  "completeNoEvents": "Події не виконано",
  "instructionsOnly": "Тільки інструкції",
  "standard": "Стандартний",
  "summaryOnly": "Тільки коротка інформація",
  "travelModesUrl": "URL режимів поїздки",
  "searchPlaceholder": "Знайти адресу або місце",
  "trafficLayerUrl": "URL транспортного шару",
  "barrierLayerUrl": "URL бар'єрного шару",
  "presetDestinations": "Задані зупинки",
  "startPoint": "Початкова точка",
  "endPoint": "Кінцева точка",
  "destinationHolder": "Адреса або координати",
  "optional": "Необов’язково.",
  "barrierLayers": "Шари бар'єрів",
  "pointBarrier": "Точкові бар'єри",
  "lineBarrier": "Лінійні бар'єри",
  "polygonBarrier": "Полігональні бар'єри",
  "noPointBarrier": "Вибрати точкові бар'єри",
  "noLineBarrier": "Вибрати лінійні бар'єри",
  "noPolygonBarrier": "Вибрати полігональні бар'єри"
});