define({
  "tabs_section_Label": "علامات تبويب",
  "addTab": "إضافة جدول...",
  "layerName": "الطبقة",
  "layerType": "نوع عملية التحليل",
  "layerLabel": "التسمية",
  "actions": "إجراءات",
  "closest": "أقرب معلم",
  "proximity": "المقاربة",
  "summary": "الملخص",
  "select_lbl": "-- تحديد --",
  "general_setting_Label": "إعدادات عامة",
  "units_text_lbl": "وحدات المسافة",
  "maximum_distance_lbl": "الحد الأقصى من مسافة أقرب معلم",
  "buffer_text_lbl": "لافتة تسمية النطاق",
  "buffer_lbl": "مسافة النطاق",
  "buffer_max_lbl": "الحد الأقصى من مسافة النطاق",
  "buffer_min_lbl": "الحد الأدنى من مسافة النطاق",
  "routing_checkBox": "تمكين التوجيه",
  "weather_Label": "خيارات الطقس",
  "weather_checkBox": "يشمل معلومات الطقس",
  "selectLayers": "حدد طبقات الطقس",
  "currentlySelectedLayer": "طبقات الطقس المُحددة حاليًا",
  "missingTabLabel": "تفقد على الأقل علامة تبويب واحدة تسميتها",
  "missingLayerInWebMap": "لا توجد طبقات تشغيلية",
  "selectFields": "Select Fields",
  "addField": "إضافة حقل",
  "sum": "مجموع",
  "min": "الحد الأدنى",
  "max": "الحد الأقصى",
  "avg": "المتوسط",
  "count": "عدد",
  "area": "AREA",
  "length": "LENGTH",
  "count_checkBox": "عرض عدد المعالم",
  "area_checkBox": "عرض مجموع المناطق",
  "length_checkBox": "عرض مجموع الأطوال",
  "max_records": "تم الوصول إلى الحد الأقصى",
  "save_label": "خيارات الحفظ",
  "save_checkbox": "تمكين الحفظ",
  "csv_label": "خيارات CSV",
  "csv_checkbox": "تصدير كل الحقول في الطبقة",
  "display_label": "خيارات العرض",
  "display_checkbox": "عرض مميزات الملخص",
  "snapshot_label": "خيارات الالتقاط",
  "snapshot_checkbox": "تمكين الالتقاط",
  "must_select_template": "يرجى تحديد أحد قوالب التحرير في خيارات الحفظ.",
  "count_label": "عدّ التسميات",
  "area_label": "تسمية المنطقة",
  "length_label": "تسمية الطول",
  "invalid_string_width": "القيمة طويلة للغاية. ",
  "layer_type_not_supported": "نوع الطبقة غير مدعوم: ",
  "groupedSummary": "أعداد مُجمّعَة",
  "groupByField": "تجميع بواسطة الحقل",
  "labelType": "إلحاق التسمية",
  "prefix": "كبادئة",
  "suffix": "كلاحقة",
  "need_group_field": "يرجى استخدام إجراء التحرير لتعريف \"تجميع بواسطة الحقل\".",
  "fieldTitle": "حقل",
  "typeTitle": "النوع",
  "actionsTitle": "إجراءات",
  "save_point_checkbox": "حفظ النقاط",
  "save_line_checkbox": "حفظ الخطوط",
  "save_poly_checkbox": "حفظ المضلعات",
  "no_valid_popup_fields": "لا يوجد حقول صحيحة في النافذة المنبثقة. الرجاء استخدام إجراء التحرير لتعريف الحقل.",
  "no_valid_fields": "لا يوجد حقول صحيحة. الرجاء استخدام إجراء التحرير لعرض الخيارات.",
  "incident_label": "لافتة تسمية علامة التبويب",
  "locate_incident_label": "لافتة تسمية منطقة الاهتمام",
  "incident": "طارئ",
  "locate_incident": "تحديد موقع الحادث",
  "buffer_value": "مسافة النطاق"
});