define({
  "_widgetLabel": "แก้ไขแบบสมาร์ท",
  "_featureAction_SmartEditor": "แก้ไขแบบสมาร์ท",
  "noEditPrivileges": "บัญชีของคุณไม่ได้รับอนุญาตให้สร้างหรือปรับเปลี่ยนข้อมูล",
  "widgetActive": "ใช้การได้",
  "widgetNotActive": "ไม่สามารถใช้งานได้",
  "pressStr": "กด ",
  "ctrlStr": " CTRL ",
  "snapStr": " เพื่อเปิดการใช้งาน Snapping",
  "noAvailableTempaltes": "ไม่มีแม่แบบที่ใช้งานได้",
  "editorCache": " - แคชการแก้ไข",
  "presetFieldAlias": "ฟิลด์",
  "presetValue": "ค่าที่ตั้งไว้ล่วงหน้า",
  "usePresetValues": " ใช้ค่าที่ตั้งไว้ล่วงหน้า (ข้อมูลใหม่เท่านั้น)",
  "editGeometry": " แก้ไขรูปร่างเรขาคณิต",
  "savePromptTitle": "บันทึกข้อมูล",
  "savePrompt": "คุณต้องการที่จะบันทึกข้อมูลปัจจุบันหรือไม่?",
  "deletePromptTitle": "ลบข้อมูลนี้",
  "deleteAttachment": "ลบไฟล์แนบ",
  "deletePrompt": "คุณแน่ใจหรือไม่ว่าคุณต้องการลบข้อมูลที่เลือก?",
  "attachmentLoadingError": "การอัปโหลดสิ่งที่แนบมามีข้อผิดพลาด",
  "attachmentSaveDeleteWarning": "คำเตือน: การเปลี่ยนแปลงสิ่งที่แนบมาจะถูกบันทึกไว้โดยอัตโนมัติ",
  "autoSaveEdits": "บันทึกฟีเจอร์ใหม่โดยอัตโนมัติ",
  "addNewFeature": "สร้างฟีเจอร์ใหม่",
  "featureCreationFailedMsg": "ไม่สามารถสร้างบันทึก/ฟีเจอร์ใหม่",
  "relatedItemTitle": "ตาราง/ชั้นข้อมูลที่เกี่ยวข้อง",
  "relatedFeatureCount": "${layerTitle} กับ ${featureCount} ฟีเจอร์",
  "createNewFeatureLabel": "สร้างฟีเจอร์ใหม่สำหรับ ${layerTitle}",
  "invalidRelationShipMsg": "โปรดตรวจสอบฟิลด์คีย์หลัก: '${parentKeyField}' มีค่าที่ถูกต้อง",
  "pendingFeatureSaveMsg": "โปรดบันทึกการแก้ไขฟีเจอร์ก่อนสร้างฟีเจอร์ที่เกี่ยวข้อง",
  "attachmentsRequiredMsg": "ต้องมีไฟล์แนบ (*)",
  "coordinatePopupTitle": "ย้ายฟีเจอร์ไปยังที่ตั้ง XY",
  "coordinatesSelectTitle": "ระบบพิกัด:",
  "mapSpecialReferenceDropdownOption": "การอ้างอิงเชิงพื้นที่ของแผนที่",
  "latLongDropdownOption": "ละติจูด/ลองจิจูด",
  "xAttributeTextBoxLabel": "พิกัด X:",
  "yAttributeTextBoxLabel": "พิกัด Y:",
  "latitudeTextBoxLabel": "ละติจูด:",
  "longitudeTextBoxLabel": "ลองจิจูด:",
  "presetGroupFieldsLabel": "'${groupName}' จะถูกใช้กับฟิลด์ชั้นข้อมูลต่อไปนี้:",
  "presetGroupNoFieldsLabel": "'${groupName}' ไม่มีฟิลด์ที่เชื่อมโยง",
  "groupInfoLabel": "ข้อมูลกลุ่มสำหรับ '${groupName}'",
  "editGroupInfoIcon": "แก้ไขค่ากลุ่มสำหรับ ${groupName}",
  "filterEditor": {
    "all": "ทั้งหมด",
    "noAvailableTempaltes": "ไม่มีแม่แบบที่ใช้งานได้",
    "searchTemplates": "ค้นหาแม่แบบ",
    "filterLayerLabel": "กรองชั้นข้อมูล"
  },
  "invalidConfiguration": "วิดเจ็ตอย่างใดอย่างหนึ่งไม่ได้กำหนดค่า หรือชั้นข้อมูลที่ใช้ในการกำหนดค่าที่ไม่ได้อยู่ในแผนที่ กรุณาเปิดแอปในโหมดผู้สร้างและกำหนดค่าวิดเจ็ต",
  "geometryServiceURLNotFoundMSG": "ไม่สามารถรับ URL เซอร์วิสเรขาคณิต",
  "clearSelection": "เคลียร์",
  "refreshAttributes": "อัพเดตฟีเจอร์แอตทริบิวต์",
  "automaticAttributeUpdatesOn": "อัพเดตฟีเจอร์แอตทริบิวต์อัตโนมัติ: เปิด",
  "automaticAttributeUpdatesOff": "อัพเดตฟีเจอร์แอตทริบิวต์อัตโนมัติ: ปิด",
  "moveSelectedFeatureToGPS": "ย้ายฟีเจอร์ที่เลือกไปยังที่ตั้ง GPS ปัจจุบัน",
  "moveSelectedFeatureToXY": "ย้ายฟีเจอร์ที่เลือกไปยังที่ตั้ง XY",
  "mapNavigationLocked": "การนำทางแผนที่: ล็อค",
  "mapNavigationUnLocked": "การนำทางแผนที่: ปลดล็อค",
  "copyFeatures": {
    "title": "คัดลอกฟีเจอร์",
    "createFeatures": "สร้างฟีเจอร์",
    "createSingleFeature": "สร้าง 1 รูปทรงเรขาคณิตหลายส่วน",
    "noFeaturesSelectedMessage": "ไม่ได้เลือกฟีเจอร์",
    "selectFeatureToCopyMessage": "โปรดเลือกฟีเจอร์ที่จะคัดลอก",
    "multipleFeatureSaveWarning": "หมายเหตุ: การสร้างหลายฟีเจอร์โดยการคัดลอกฟีเจอร์ จะเป็นการบันทึกฟีเจอร์ทั้งหมดทันที"
  },
  "addingFeatureError": "เกิดข้อผิดพลาดขณะเพิ่มฟีเจอร์ที่เลือกลงในชั้นข้อมูล โปรดลองอีกครั้ง",
  "addingFeatureErrorCount": "ล้มเหลวในการคัดลอกฟีเจอร์ '${copyFeatureErrorCount}'",
  "selectingFeatureError": "เกิดข้อผิดพลาดขณะเลือกฟีเจอร์ในชั้นข้อมูล โปรดลองอีกครั้ง",
  "customSelectOptionLabel": "เลือกฟีเจอร์ที่จะคัดลอก",
  "noFeatureSelectedMessage": "ไม่ได้เลือกฟีเจอร์",
  "multipleFeatureSaveMessage": "ฟีเจอร์ทั้งหมดจะถูกบันทึกในทันที คุณต้องการดำเนินงานหรือไม่",
  "relativeDates": {
    "dateTypeLabel": "ประเภทวันที่",
    "valueLabel": "ค่า",
    "fixed": "คงที่",
    "current": "ปัจจุบัน",
    "past": "อดีต",
    "future": "อนาคต",
    "popupTitle": "เลือกค่า",
    "hintForFixedDateType": "เคล็ดลับ: วันที่และเวลาที่กำหนด จะถูกใช้เป็นค่าเริ่มต้นพรีเซ็ต",
    "hintForCurrentDateType": "เคล็ดลับ: วันที่และเวลาปัจจุบัน จะถูกใช้เป็นค่าเริ่มต้นพรีเซ็ต",
    "hintForPastDateType": "เคล็ดลับ: ค่าที่ระบุจะถูกลบออกจากวันที่และเวลาปัจจุบัน สำหรับค่าเริ่มต้นของพรีเซ็ต",
    "hintForFutureDateType": "เคล็ดลับ: ค่าที่ระบุจะถูกเพิ่มลงในวันที่และเวลาปัจจุบัน สำหรับค่าเริ่มต้นของพรีเซ็ต",
    "noDateDefinedTooltip": "ไม่ได้กำหนดวันที่ไว้",
    "relativeDateWarning": "จะต้องระบุค่าวันที่หรือเวลา เพื่อให้สามารถบันทึกค่าพรีเซ็ตเริ่มต้นได้"
  }
});