define({
  "settings": "Parametrai",
  "titleSettings": "Teksto parametrai",
  "imageSettings": "Atvaizdo parametrai",
  "backgroundColor": "Fono spalva",
  "alignment": "Lygiuotė",
  "textSize": "Teksto dydis",
  "textColor": "Teksto spalva",
  "dataSource": "Duomenų šaltinis",
  "chartSettings": "Diagramos nustatymai",
  "data": "Duomenys",
  "dataLabels": "Duomenų žymės",
  "displayMode": "Rodymo režimas",
  "featureOption": "Rodyti reikšmes po vieną elementą",
  "categoryOption": "Rodyti reikšmes pagal kategoriją",
  "countOption": "Rodyti elementų skaičių kiekvienoje kategorijoje",
  "fieldOption": "Rodyti atributo reikšmes kaip diagramas",
  "categoryField": "Kategorijos laukas",
  "labelField": "Žymės laukas",
  "valueFields": "Reikšmės laukai",
  "operation": "Veiksmas",
  "sumOption": "Suma",
  "averageOption": "Vidurkis",
  "minOption": "Minimumas",
  "maxOption": "Maksimumas",
  "dataFormat": "Datos formatas",
  "decimalPlaces": "Dešimtainės dalys",
  "prefix": "Prefiksas",
  "suffix": "Sufiksas",
  "dataType": "Duomenų tipas",
  "featureCount": "Elementų skaičius",
  "fieldStatistics": "Laukų statistika",
  "display": "Rodyti",
  "chartColor": "Diagramos spalva",
  "horizontalAxis": "Horizontali ašis",
  "verticalAxis": "Vertikali ašis",
  "legend": "Legenda",
  "position": "Padėtis",
  "top": "Viršus",
  "bottom": "Apačia",
  "useDataSourceSelection": "Naudoti pasirinkimą",
  "dataSourceFilterByExtent": "Filtruoti pagal aprėptį",
  "changeTemplate": "Keisti šabloną",
  "numberSettings": "Skaičiaus parametrai",
  "gaugeSettings": "Matuoklio parametrai",
  "indicators": "Indikatoriai",
  "ifValue": "Jei reikšmė",
  "and": "ir",
  "numberOperatorIsLessThan": "yra mažiau nei",
  "numberOperatorIsGreaterThan": "yra daugiau nei",
  "numberOperatorIsBetween": "yra tarp",
  "numberOperatorIsEqual": "lygu",
  "numberOperatorIsNotEqual": "nelygu",
  "then": "Tada",
  "ratio": "Santykis",
  "trueValue": "Tikra reikšmė",
  "changeValueColor": "keisti reikšmės spalvą į",
  "changeGaugeColor": "keisti matuoklio spalvą į",
  "setIndicatorIcon": "nustatyti indikatoriaus piktogramą kaip",
  "icons": "Piktogramos",
  "style": "Stilius",
  "placement": "Vieta",
  "left": "Kairėje",
  "replace": "Pakeisti",
  "right": "Dešinėje",
  "color": "Spalva",
  "dataRange": "Datos intervalas",
  "targetValue": "Paskirties vietos reikšmė",
  "currentValue": "Dabartinė reikšmė:",
  "gaugeColor": "Matuoklio spalva",
  "min": "Minimumas",
  "max": "Maksimumas",
  "displayValueIn": "Rodyti reikšmę",
  "noData": "Nėra duomenų",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Įspėjimas",
  "noSettingWaring1": "Paspauskite elementą, kad nustatytumėte jo savybes.",
  "noSettingWaring2": "Nuvilkti norint pakeisti elemento dydį arba jį pertvarkyti.",
  "donNotShowAgain": "Daugiau nerodyti",
  "changeTemplateWarning": "Tai ištrins visus jūsų parametrus ir atidarys naują tuščią šabloną.",
  "requiredFieldWarning": "Ši reikšmė privaloma:",
  "dataSourceNotSet": "Nustatykite duomenų šaltinį.",
  "addIndicatorTip": "Pridėti indikatorių",
  "chooseTemplatePopupTitle": "Pasirinkite šabloną",
  "stringsInTemplate": {
    "name_number": "Skaičiai",
    "name_gauge": "Matuoklis",
    "name_vertical_gauge": "Vertikalus matuoklis",
    "name_horizontal_gauge": "Horizontalus matuoklis",
    "name_pie_chart": "Skritulinė diagrama",
    "name_column_chart": "Stulpelinė diagrama",
    "name_bar_chart": "Juostinė diagrama",
    "name_line_chart": "Linijinė diagrama",
    "titleOfTheInfographic": "INFOGRAFIKO PAVADINIMAS",
    "description": "Aprašymas: papildoma informacija apie šį infografiką"
  }
});