define({
  "searchTabTitle": "Configuração da fonte de pesquisa",
  "routeTabTitle": "Configurações da rota",
  "add": "Adicionar fonte de pesquisa",
  "addGeocoder": "Adicionar geocodificador",
  "geocoder": "Geocodificador",
  "setLayerSource": "Configurar fonte da camada",
  "setGeocoderURL": "Configurar URL do geocodificador",
  "searchableLayer": "Camada de feição",
  "name": "Nome",
  "countryCode": "Códigos de região e país",
  "countryCodeEg": "por exemplo ",
  "countryCodeHint": "Deixar este valor em branco pesquisará todos os países e regiões",
  "showInfoWindowOnSelect": "Mostrar pop-up do local ou feição localizada",
  "showInfoWindowOnSelect2": "Mostrar pop-up quando a feição ou localização for encontrada.",
  "searchInCurrentMapExtent": "Somente pesquisar na extensão de mapa atual",
  "setSearchFields": "Definir campos de pesquisa",
  "set": "Configurar",
  "fieldSearchable": "pesquisável",
  "zoomScale": "Escala de zoom",
  "locatorUrl": "URL do Geocodificador",
  "locatorName": "Nome de geocodificador",
  "locatorExample": "Exemplo",
  "locatorWarning": "Esta versão do serviço de geocodificação não é suportado. O widget suporta serviço de geocodificação 10.1 e superior.",
  "locatorTips": "As sugestões não estão disponíveis, pois o serviço de geocodificação não suporta o recursos de sugestão.",
  "layerSource": "Fonte da camada",
  "searchLayerTips": "As sugestões não estão disponíveis, pois o serviço da feição não suporta o recursos de paginação.",
  "placeholderText": "Texto de local reservado",
  "searchFields": "Procurar campos",
  "displayField": "Campo de visualização",
  "exactMatch": "Combinação exata",
  "maxSuggestions": "Máximo de sugestões",
  "maxResults": "Máximo de resultados",
  "enableLocalSearch": "Habilitar pesquisa de local",
  "minScale": "Escala mínima",
  "minScaleHint": "Quando a escala do mapa for maior que esta escala, a pesquisa de local será aplicada",
  "radius": "Proporção",
  "radiusHint": "Especifica o raio de uma área ao redor do centro do mapa atual que é utilizado para impulsionar o grau de candidatos de geocodificação de forma que os candidatos mais próximos ao local sejam retornados primeiro",
  "invalidUrlTip": "A URL ${URL} é inválida ou inacessível.",
  "routeUrl": "URL da Rota",
  "geocoderOptions": "Opções do geocodificador",
  "autoComplete": "Auto Completar",
  "maximumSuggestions": "Máximo de sugestões",
  "minCharacters": "Mínimo de caracteres",
  "searchDelay": "Atraso de pesquisa",
  "placeholder": "Espaço Reservado",
  "routeOptions": "Opções da rota",
  "directionsLanguage": "Idioma das direções",
  "directionsLengthUnits": "Unidades de comprimento das direções",
  "directionsOutputType": "Tipo de saída das direções",
  "impedanceAttribute": "Atributo de impedância",
  "kilometers": "Quilômetros",
  "miles": "Milhas",
  "meters": "Metros",
  "feet": "Pés",
  "yards": "Jardas",
  "nauticalMiles": "Milhas náuticas",
  "parametersTip": "Configure parâmetros corretamente !",
  "complete": "Completo",
  "completeNoEvents": "Completar Sem Eventos",
  "instructionsOnly": "Instruções somente",
  "standard": "Padrão",
  "summaryOnly": "Resumo somente",
  "travelModesUrl": "URL de modos de viagem",
  "searchPlaceholder": "Encontrar endereço ou lugar",
  "trafficLayerUrl": "URL da camada de tráfego",
  "barrierLayerUrl": "URL da camada de barreira",
  "presetDestinations": "Paradas pré definidas",
  "startPoint": "Ponto Inicial",
  "endPoint": "Ponto Final",
  "destinationHolder": "Endereço ou coordenadas",
  "optional": "Opcional.",
  "barrierLayers": "Camadas de Barreira",
  "pointBarrier": "Barreiras de ponto",
  "lineBarrier": "Barreiras de linha",
  "polygonBarrier": "Barreiras de polígono",
  "noPointBarrier": "Selecionar barreiras de ponto",
  "noLineBarrier": "Selecionar barreiras de linha",
  "noPolygonBarrier": "Selecionar barreiras de polígono"
});