define({
  "feedbackStyleLabel": "Стиль отзыва расстояния и направления",
  "showTabLabel": "Показать вкладку",
  "feedbackShapeLabel": "Форма отзыва",
  "lineColorLabel": "Цвет линии",
  "lineWidthLabel": "Ширина линии",
  "feedbackLabel": "Подпись отзыва",
  "textColorLabel": "Цвет текста",
  "textSizeLabel": "Размер текста",
  "tabErrorMessage": "Виджет должен быть настроен хотя бы с одной показанной вкладкой",
  "lineLabel": "Линия",
  "circleLabel": "Окружность",
  "ellipseLabel": "Эллипс",
  "ringsLabel": "Кольца",
  "transparency": "Прозрачность",
  "ddFeedbackStyleTabLabel": "Символы",
  "miscellaneousTabLabel": "Разное",
  "operationalLineLayerSelectLabel": "Выберите операционный полилинейный слой для результатов линий и колец",
  "operationalPolygonLayerSelectLabel": "Выберите операционный полигональный слой для результатов круга и эллипса",
  "helpIconPolylineTooltip": "Список операционных слоев заполнен слоями текущей веб-карты с типом геометрии - полилиния.",
  "helpIconPolygonTooltip": "Список операционных слоев заполнен слоями текущей веб-карты с типом геометрии - полигон."
});