define({
  "chartTasks": "Tasques de gràfics",
  "addNew": "Afegeix-ne un de nou",
  "addNewTip": "Afegeix una nova tasca de gràfic",
  "name": "Nom",
  "set": "Defineix",
  "setDataSource": "Defineix l'origen de dades",
  "generalSettingsTip": "Definiu l'origen de dades, el títol i la descripció dels gràfics.",
  "chartModeSettingTip": "Seleccioneu una manera d'analitzar i mostrar les dades com a gràfics.",
  "detailsSettingTip": "Per definir l'aspecte del gràfic, especifiqueu-ne el tipus i el color, així com els valors que s'han de representar:",
  "symbolSettingTip": "Definiu la visualització de mapa de les dades representades.",
  "addFilterTip": "Afegeix un filtre a aquestes dades",
  "dataSource": "Origen de dades",
  "noResults": "No s'ha trobat cap entitat.",
  "chartTitle": "Títol del gràfic",
  "description": "Descripció",
  "chartingMode": "Visualització del gràfic",
  "featureOption": "Mostra els valors entitat per entitat",
  "categoryOption": "Mostra els valors per categoria",
  "countOption": "Mostra els recomptes d'entitats per categoria",
  "fieldOption": "Mostra els valors d'atributs com a gràfics",
  "category": "Categoria",
  "axisLabel": "Etiqueta de categoria",
  "categoryField": "Camp de categoria",
  "operation": "Operació",
  "originalOption": "Utilitza els valors originals",
  "sumOption": "Suma",
  "averageOption": "Mitjana",
  "minOption": "Mínim",
  "maxOption": "Màxim",
  "valueFields": "Camps de valors",
  "moveUp": "Mou cap amunt",
  "moveDown": "Mou cap avall",
  "sortOrder": "Ordena els gràfics per etiquetes de categories",
  "ascending": "Ascendent",
  "descending": "Descendent",
  "chartType": "Tipus de gràfic",
  "column": "Gràfic de columnes",
  "bar": "Gràfic de barres",
  "line": "Gràfic de línies",
  "pie": "Gràfic circular",
  "chartColor": "Color de gràfic",
  "showDataLabels": "Mostra les etiquetes de dades",
  "setSymbol": "Símbol de selecció",
  "setHighLightColor": "Ressalta el color",
  "settings": "Configuració",
  "mapInterationOptions": "Opcions d'interacció del mapa",
  "preview": "Visualització prèvia",
  "ok": "D'acord",
  "cancel": "Cancel·la",
  "close": "Tanca",
  "setFilterTip": "Definiu el filtre correctament. ",
  "setChartTitleTip": "Definiu el títol del gràfic.",
  "setChartTypeTip": "Seleccioneu un tipus de gràfic com a mínim.",
  "setDataFieldTip": "Seleccioneu un camp de valor com a mínim.",
  "setOutputFieldTip": "Definiu els camps de sortida.",
  "count": "Recompte",
  "label": "Etiqueta",
  "horizontalAxis": "Eix horitzontal",
  "verticalAxis": "Eix vertical",
  "dataLabels": "Etiquetes de dades",
  "color": "Color",
  "colorful": "Colorit",
  "monochromatic": "Monocromàtic",
  "noTaskTip": "Feu clic a Afegeix-ne un de nou per afegir una tasca de gràfic",
  "info": "Informació",
  "charts": "Gràfics",
  "options": "Opcions",
  "taskName": "Nom de la tasca",
  "summary": "Resum",
  "resultDescription": "Descripció del resultat",
  "spatialFilterTip": "Trieu els filtres espacials utilitzats al widget per limitar els resultats.",
  "defaultOption": "Per defecte",
  "useCurrentExtentTip": "Parcialment o totalment dins de l'extensió de mapa actual",
  "useDrawGraphicTip": "Parcialment o totalment dins de la forma dibuixada al mapa",
  "useFeaturesTip": "En funció de les ubicacions pel que fa a les entitats d'una altra capa",
  "noSpatialLimitTip": "No limitis espacialment els resultats",
  "drawingTools": "Eines de dibuix",
  "bufferSettings": "Configuració de l'àrea d'influència",
  "defaultDistance": "Distància per defecte",
  "bufferDistance": "Distància d'àrea d'influència",
  "defaultUnit": "Unitat per defecte",
  "miles": "Milles",
  "kilometers": "Quilòmetres",
  "feet": "Peus",
  "meters": "Metres",
  "yards": "Iardes",
  "nauticalMiles": "Milles nàutiques",
  "availableSpatialRelationships": "Relacions espacials disponibles",
  "setSpatialRelationships": "Defineix les relacions espacials",
  "availability": "Disponibilitat",
  "relationship": "Relació",
  "actions": "Accions",
  "intersect": "interseca",
  "contain": "conté",
  "areContainedIn": "s'inclouen a",
  "cross": "creuen",
  "envelopeIntersect": "intersecció amb el contorn",
  "overlap": "superposa",
  "areOverlapped": "se superposen",
  "touche": "es toquen",
  "within": "dins de",
  "areWithin": "estan dins de",
  "indexIntersect": "amb intersecció d'índex",
  "valueStr": "Valor",
  "sortBy": "Ordena per"
});