define({
  "businessAnalyst": "Business Analyst",
  "defineWhichInfographics": "Definovat, jaké informační grafiky jsou dostupné ve widgetu:",
  "defineWhichReports": "Definovat, jaké zprávy jsou dostupné ve widgetu:",
  "defaultValues": "Výchozí hodnoty:",
  "disable": "Zakázat",
  "driveTime": "Doba jízdy",
  "infographics": "Informační grafika",
  "invalidValueRing": "Hodnoty musí být v rozsahu 0 až 1000.",
  "invalidValueDTWT": "Hodnoty musí být v rozsahu 0 až 300.",
  "km": "km",
  "miles": "mil",
  "minutes": "minut",
  "radius": "Poloměr",
  "reports": "Zprávy",
  "rings": "Kružnice",
  "selectCountry": "Vybrat zemi:",
  "thisEntryIsNotValid": "Tento záznam není platný.",
  "time": "Čas",
  "walkTime": "Doba chůze"
});