define(
   ({
    addLayer: "レイヤーの追加",
    layerName: "レイヤー",
    layerRefresh: "更新",
    layerLabel: "ラベル",
    actions: "操作",
    popupOk: "OK",
    popupCancel: "キャンセル",
    mainPanelTextPlaceholder: "例: 高速道路の状態",
    invalidInterval: "数字のみがサポートされています。",
    uploadImage: "画像のアップロード",
    iconColumnText: "アイコン",
    refreshInterval: "1 \'分単位の時間として評価されました\'",
    refreshIntervalTitle: "分単位の時間として評価されました",
    mainPanelText: "メイン パネルのテキスト",
    mainPanelIcon: "メイン パネルの画像",
    refreshIntervalInstruction: "更新間隔",
    optionsText: "オプション",
    symbolOptionsText: "シンボルのオプション",
    iconOptionsText: "アイコンのオプション",
    sympolPopupTitle: "シンボルの設定",
    rdoLayer: "レイヤー シンボル",
    rdoCustom: "カスタム シンボル",
    chkCluster: "クラスタリングの有効化",
    defineClusterSymbol: "クラスター シンボル",
    defineThemeClusterSymbol: "テーマのクラスター シンボル",
    rdoEsri: "Esri シンボル",
    rdoLayerIcon: "シンボルをアイコンとして使用",
    rdoCustomIcon: "カスタム アイコンのアップロード",
    editCustomSymbol: "カスタム シンボルの編集",
    editCustomIcon: "カスタム アイコンの編集",
    missingRefreshValue: "更新間隔の値を入力してください。",
    panelIconOption: "パネルのヘッダーの表示",
    enableRefresh: "レイヤーの更新の有効化",
    disableRefresh: "レイヤーの更新はフィーチャ コレクションでのみサポートされています",
    layer_type_not_supported: "レイヤー タイプはサポートされていません: "
  })
);
