define({
  root: ({
    _widgetLabel: "Smart Editor",
    pressStr: "Press ",
    ctrlStr: " CTRL ",
    snapStr: " to enable snapping",
    noAvailableTempaltes: "No available templates",
    editorCache: " - Editor Cache",
    presetFieldAlias: "Field",
    presetValue: "Preset Value",
    usePresetValues: " Use Preset Values (New features only)",
    editGeometry: " Edit Geometry",
    savePromptTitle: "Save feature",
    savePrompt: "Would you like to save the current feature?",
    deletePromptTitle: "Delete feature",
    deletePrompt: "Are you sure you want to delete the selected feature?",
    attachmentLoadingError: "Error uploading attachments",
    attachmentSaveDeleteWarning: "Warning: Changes to attachments are saved automatically",
    filterEditor:{
      all: "All",
      noAvailableTempaltes: "No available templates",
      searchTemplates: "Search Templates"
    }
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});