define({
  "layerSelect": "Selecione a Camada de Imagens",
  "displayMeasureResultInPopup": "Exibir Resultados de Medição num Pop-up",
  "angularUnitSelect": "Unidade Angular Padrão",
  "linearUnitSelect": "Unidade Linear Padrão",
  "areaUnitSelect": "Unidade de Área padrão",
  "displayOperationSelect": "Seleccionar Operações de Medição",
  "errorSectionMeasage": "Nenhuma das camadas suporta capacidades de medição.",
  "unitLabel": {
    "esriInches": "Polegadas",
    "esriFeet": "Pés",
    "esriYards": "Jardas",
    "esriMiles": "Milhas",
    "esriNauticalMiles": "Milhas Náuticas",
    "esriMillimeters": "Milímetros",
    "esriCentimeters": "Centímetros",
    "esriDecimeters": "Decímetros",
    "esriMeters": "Metros",
    "esriKilometers": "Quilômetros",
    "esriDURadians": "Radians",
    "esriDUDecimalDegrees": "Graus",
    "esriSquareInches": "Sq Polegadas",
    "esriSquareFeet": "Pés Quadrados",
    "esriSquareYards": "Jardas Quadradas",
    "esriAcres": "Acres",
    "esriSquareMiles": "Milhas Quadradas",
    "esriSquareMillimeters": "Sq Milímetros",
    "esriSquareCentimeters": "Sq Centímetros",
    "esriSquareDecimeters": "Sq Decímetros",
    "esriSquareMeters": "Metros Quadrados",
    "esriAres": "Ares",
    "esriHectares": "Hectares",
    "esriSquareKilometers": "Quilómetros Quadrados"
  },
  "operationLabel": {
    "esriMensurationPoint": "Localização",
    "esriMensurationDistanceAndAngle": "Distância e Ângulo",
    "esriMensurationAreaAndPerimeter": "Área e Perimetro",
    "esriMensurationHeightFromBaseAndTop": "Altura: Base até ao Topo",
    "esriMensurationHeightFromBaseAndTopShadow": "Altura: Base até ao Topo-Sombra",
    "esriMensurationHeightFromTopAndTopShadow": "Altura: Topo para o Topo-Sombra",
    "esriMensurationCentroid": "Centroid",
    "esriMensurationPoint3D": "Localização (3D)",
    "esriMensurationDistanceAndAngle3D": "Distância e Ângulo (3D)",
    "esriMensurationAreaAndPerimeter3D": "Área e Perimetro (3D)",
    "esriMensurationCentroid3D": "Centroid (3D)"
  }
});