define({
  "_widgetLabel": "Szerkesztés",
  "_featureAction_Edit": "Szerkesztés",
  "title": "Válasszon sablont a vektoros elemek létrehozásához",
  "pressStr": "Nyomja meg a ",
  "ctrlStr": " CTRL ",
  "snapStr": " billentyűt a hozzáillesztés engedélyezéséhez",
  "close": "Bezárás",
  "featureLayers": "Vektoros rétegek",
  "searchTemplates": "Sablonok keresése",
  "noAvailableTempaltes": "Nincsenek elérhető sablonok",
  "noCanCreateLayerAreCurrentlyVisible": "Jelenleg egyetlen létrehozható réteg sem látható.",
  "layersAreInvisibleOrOutOfScaleRange": "A rétegek nem láthatók vagy kívül esnek a méretarány-tartományon.",
  "relatedTables": "Kapcsolt táblák:",
  "relatedRecords": "Kapcsolt rekordok:",
  "noRelatedRecotds": "Nem találhatók kapcsolt rekordok.",
  "startToDraw": "Kattintson a rajzolás elkezdéséhez",
  "startToAddPoint": "Kattintson egy pont hozzáadásához",
  "editRelatedFeature": "Kapcsolt vektoros elem szerkesztése",
  "duplicateValueWarning": " Duplikált érték nem illeszthető be a következőbe: ${fieldName}/${tableName}. A duplikált érték: ${value}"
});