///////////////////////////////////////////////////////////////////////////
// Copyright © Esri. All Rights Reserved.
//
// Licensed under the Apache License Version 2.0 (the 'License');
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
///////////////////////////////////////////////////////////////////////////
define({
  "units": {
    "areaSquareFeetUnit": "Quadratfuß",
    "areaAcresUnit": "Acres",
    "areaSquareMetersUnit": "Quadratmeter",
    "areaSquareKilometersUnit": "Quadratkilometer",
    "areaHectaresUnit": "Hektar",
    "areaSquareMilesUnit": "Quadratmeilen",
    "lengthFeetUnit": "Fuß",
    "lengthMilesUnit": "Meilen",
    "lengthMetersUnit": "Meter",
    "lengthKilometersUnit": "Kilometer"
  },
  "analysisTab": {
    "analysisTabLabel": "Analyse",
    "selectAnalysisLayerLabel": "Analyse-Layer",
    "addLayerLabel": "Layer hinzufügen",
    "noValidLayersForAnalysis": "Keine gültigen Layer in der ausgewählten Webkarte gefunden.",
    "noValidFieldsForAnalysis": "Keine gültigen Felder in der ausgewählten Webkarte gefunden. Entfernen Sie den ausgewählten Layer.",
    "allowGroupingLabel": "Features nach Feld mit demselben Wert gruppieren",
    "groupingHintDescription": "Hinweis: Standardmäßig werden alle Features mit demselben Wert für die ausgewählten Felder gruppiert und im Bericht als ein einziger Eintrag dargestellt. Deaktivieren Sie die Gruppierung nach ähnlichen Attributen, um stattdessen einen Eintrag für jedes Feature anzuzeigen.",
    "addLayersHintText": "Hinweis: Wählen Sie die Layer und Felder aus, die in die Analyse und den Bericht einbezogen werden sollen.",
    "addLayerNameTitle": "Layer-Name",
    "addFieldsLabel": "Feld hinzufügen",
    "addFieldsPopupTitle": "Felder auswählen",
    "addFieldsNameTitle": "Feldnamen",
    "aoiToolsLegendLabel": "Interessenbereich-Werkzeuge",
    "aoiToolsDescriptionLabel": "Wählen Sie die Werkzeuge zum Erstellen des Interessenbereichs aus, und beschriften Sie sie.",
    "placenameLabel": "Ortsname",
    "drawToolsLabel": "Zeichenwerkzeuge auswählen",
    "uploadShapeFileLabel": "Ein Shapefile hochladen",
    "coordinatesLabel": "Koordinaten",
    "coordinatesDrpDwnHintText": "Hinweis: Wählen Sie die Einheit für die Anzeige der eingegebenen Polygonzüge aus.",
    "coordinatesBearingDrpDwnHintText": "Hinweis: Wählen Sie die Peilung für die Anzeige der eingegebenen Polygonzüge aus.",
    "allowShapefilesUploadLabel": "Hochladen von Shapefiles zum Einbeziehen in die Analyse zulassen",
    "allowShapefilesUploadLabelHintText": "Hinweis: Fügen Sie der Registerkarte \"Bericht\" eine Option hinzu, in der Benutzer eigene Daten als Shapefile hochladen können, um sie in den Analysebericht einzubeziehen.",
    "allowVisibleLayerAnalysisLabel": "Keine Ergebnisse für nicht sichtbare Layer analysieren oder erfassen",
    "allowVisibleLayerAnalysisHintText": "Hinweis: Layer, die deaktiviert oder aufgrund der Sichtbarkeitseinstellungen des Maßstabs nicht sichtbar sind, werden weder analysiert noch in gedruckte oder heruntergeladene Ergebnisse einbezogen.",
    "areaUnitsLabel": "Einheiten für Analyseergebnisse (Fläche)",
    "lengthUnitsLabel": "Einheiten für Analyseergebnisse (Länge)",
    "maxFeatureForAnalysisLabel": "Maximale Anzahl von Features für die Analyse",
    "maxFeatureForAnalysisHintText": "Hinweis: Legen Sie die maximale Anzahl von Features fest, die in die Analyse einbezogen werden können.",
    "searchToleranceLabelText": "Suchtoleranz",
    "searchToleranceHint": "Hinweis: Die Suchtoleranz wird beim Analysieren von Punkt- und Linieneingaben verwendet.",
    "placenameButtonText": "Ortsname",
    "drawToolsButtonText": "Zeichnen",
    "shapefileButtonText": "Shapefile",
    "coordinatesButtonText": "Koordinaten",
    "invalidLayerErrorMsg": "Konfigurieren Sie die Felder für",
    "drawToolSelectableLayersLabel": "Auswählbare Layer festlegen",
    "drawToolSelectableLayersHint": "Hinweis: Wählen Sie die Layer mit den Features aus, die über das Zeichenwerkzeug ausgewählt werden können.",
    "drawToolsSettingsFieldsetLabel": "Zeichenwerkzeuge",
    "drawToolPointLabel": "Punkt",
    "drawToolPolylineLabel": "Polylinie",
    "drawToolExtentLabel": "Ausdehnung",
    "drawToolPolygonLabel": "Polygon",
    "drawToolCircleLabel": "Kreis",
    "selectDrawToolsText": "Zeichenwerkzeuge zum Erstellen des Interessenbereichs auswählen",
    "selectingDrawToolErrorMessage": "Wählen Sie mindestens ein Zeichenwerkzeug oder einen Auswahl-Layer aus, das bzw. der die Option \"Zeichenwerkzeuge\" für AOI-Werkzeuge verwenden soll."
  },
  "downloadTab": {
    "downloadLegend": "Downloadeinstellungen",
    "reportLegend": "Berichtseinstellungen",
    "downloadTabLabel": "Herunterladen",
    "syncEnableOptionLabel": "Feature-Layer",
    "syncEnableOptionHint": "Hinweis: Wählen Sie die Layer aus, die heruntergeladen werden können, und geben Sie die Formate an, in denen die jeweiligen Layer verfügbar sind. Heruntergeladene Datasets enthalten die Features, die sich mit dem Interessenbereich überschneiden.",
    "syncEnableOptionNote": "Hinweis: Zum Herunterladen von File-Geodatabases und Shapefiles sind Feature-Layer erforderlich, für die die Synchronisierung aktiviert wurde. Das Shapefile-Format wird nur in Feature-Layern unterstützt, die in ArcGIS Online gehostet werden.",
    "extractDataTaskOptionLabel": "Task \"Daten extrahieren\" des Geoverarbeitungsservice",
    "extractDataTaskOptionHint": "Hinweis: Verwenden Sie einen veröffentlichten Geoverarbeitungsservice mit dem Task \"Daten extrahieren\", um Features, die sich mit dem Interessenbereich schneiden, in File-Geodatabase- oder Shapefile-Formaten herunterzuladen.",
    "cannotDownloadOptionLabel": "Download deaktivieren",
    "syncEnableTableHeaderTitle": {
      "layerNameLabel": "Layer-Name",
      "csvFileFormatLabel": "CSV",
      "fileGDBFormatLabel": "File-Geodatabase",
      "ShapefileFormatLabel": "Shapefile",
      "allowDownloadLabel": "Download zulassen"
    },
    "setButtonLabel": "Festlegen",
    "GPTaskLabel": "URL für Geoverarbeitungsservice angeben",
    "printGPServiceLabel": "URL des Druckservice",
    "setGPTaskTitle": "Erforderliche URL des Geoverarbeitungsservice angeben",
    "logoLabel": "Logo",
    "logoChooserHint": "Hinweis: Klicken Sie auf das Bildsymbol, um das Logo zu ändern, das links oben im Bericht angezeigt wird.",
    "footnoteLabel": "Fußnote",
    "columnTitleColorPickerLabel": "Farbe von Spaltentiteln des Berichts",
    "reportTitleLabel": "Berichtstitel",
    "displaySummaryLabel": "Zusammenfassung anzeigen",
    "hideZeroValueRowLabel": "Zeilen mit Wert 0 für alle Analysefelder ausblenden",
    "hideNullValueRowLabel": "Zeilen ohne Datenwert (NULL oder leer) für alle Analysefelder ausblenden",
    "errorMessages": {
      "invalidGPTaskURL": "Ungültiger Geoverarbeitungsservice. Wählen Sie einen Geoverarbeitungsservice aus, der den Task \"Daten extrahieren\" beinhaltet.",
      "noExtractDataTaskURL": "Wählen Sie einen Geoverarbeitungsservice aus, der den Task \"Daten extrahieren\" beinhaltet.",
      "duplicateCustomOption": "Doppelter Eintrag für ${duplicateValueSizeName} vorhanden.",
      "invalidLayoutWidth": "Ungültige Breite für ${customLayoutOptionValue} eingegeben.",
      "invalidLayoutHeight": "Ungültige Höhe für ${customLayoutOptionValue} eingegeben.",
      "invalidLayoutPageUnits": "Ungültige Seiteneinheit für ${customLayoutOptionValue} ausgewählt.",
      "failtofetchbuddyTaskDimension": "Fehler beim Abrufen der Buddy-Task-Dimensionsinformationen. Versuchen Sie es erneut.",
      "failtofetchbuddyTaskName": "Fehler beim Abrufen des Buddy-Task-Namens. Versuchen Sie es erneut.",
      "failtofetchChoiceList": "Fehler beim Abrufen der Auswahlliste aus dem Druckservice. Versuchen Sie es erneut.",
      "invalidWidth": "Ungültige Breite.",
      "invalidHeight": "Ungültige Höhe."
    },
    "addCustomLayoutTitle": "Benutzerdefiniertes Layout hinzufügen",
    "customLayoutOptionHint": "Hinweis: Fügen Sie den Druckoptionen ein Layout Ihres Druckservice hinzu.",
    "reportDefaultOptionLabel": "Standard-Layout",
    "pageSizeUnits": {
      "millimeters": "Millimeter",
      "points": "Punkte"
    },
    "noDataTextRepresentation": "Kein Datenwert",
    "naTextRepresentation": "Nicht anwendbarer Wert",
    "noDataDefaultText": "Keine Daten",
    "notApplicableDefaultText": "n. z."
  },
  "generalTab": {
    "generalTabLabel": "Allgemein",
    "tabLabelsLegend": "Bereichsbeschriftungen",
    "tabLabelsHint": "Hinweis: Geben Sie Beschriftungen an.",
    "AOITabLabel": "Bereich \"Interessenbereich\"",
    "ReportTabLabel": "Bereich \"Bericht\"",
    "bufferSettingsLegend": "Puffereinstellungen",
    "defaultBufferDistanceLabel": "Standardpufferabstand",
    "defaultBufferUnitsLabel": "Puffereinheiten",
    "generalBufferSymbologyHint": "Hinweis: Symbolisierung, mit der die Pufferfläche um den definierten Interessenbereich angezeigt wird",
    "aoiGraphicsSymbologyLegend": "Symbolisierung für den Interessenbereich",
    "aoiGraphicsSymbologyHint": "Hinweis: Symbolisierung zur Darstellung der Punkt-, Linien- und Polygon-Interessenbereiche",
    "pointSymbologyLabel": "Punkt",
    "previewLabel": "Vorschau",
    "lineSymbologyLabel": "Linie",
    "polygonSymbologyLabel": "Polygon",
    "aoiBufferSymbologyLabel": "Puffer-Symbolisierung",
    "pointSymbolChooserPopupTitle": "Symbol für Adresse oder Punktposition",
    "polygonSymbolChooserPopupTitle": "Polygon-Symbol",
    "lineSymbolChooserPopupTitle": "Liniensymbol",
    "aoiSymbolChooserPopupTitle": "Puffersymbol",
    "aoiTabText": "AOI",
    "reportTabText": "Bericht",
    "invalidSymbolValue": "Ungültiger Symbolwert."
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Einstellungen der Suchquellen",
    "searchSourceSettingTitle": "Einstellungen der Suchquellen",
    "searchSourceSettingTitleHintText": "Fügen Sie Geokodierungsservices oder Feature-Layer als Suchquellen hinzu, und konfigurieren Sie diese. Anhand dieser angegebenen Quellen wird bestimmt, welche Elemente im Suchfeld durchsucht werden können.",
    "addSearchSourceLabel": "Suchquelle hinzufügen",
    "featureLayerLabel": "Feature-Layer",
    "geocoderLabel": "Geocoder",
    "generalSettingLabel": "Allgemeine Einstellung",
    "allPlaceholderLabel": "Platzhaltertext, um alle zu durchsuchen:",
    "allPlaceholderHintText": "Hinweis: Geben Sie den Platzhaltertext zum Durchsuchen aller Layer und Geocoder ein.",
    "generalSettingCheckboxLabel": "Pop-up für das gefundene Feature oder die gefundene Position anzeigen",
    "countryCode": "Länder- oder Regionscode(s)",
    "countryCodeEg": "z. B. ",
    "countryCodeHint": "Wenn dieser Wert leer gelassen wird, werden alle Länder und Regionen durchsucht.",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Nur in der aktuellen Kartenausdehnung suchen",
    "locatorUrl": "Geocoder-URL",
    "locatorName": "Geocoder-Name",
    "locatorExample": "Beispiel",
    "locatorWarning": "Diese Version des Geokodierungsservice wird nicht unterstützt. Das Widget unterstützt Geokodierungsservices der Version 10.0 und höher.",
    "locatorTips": "Es sind keine Vorschläge verfügbar, da der Geokodierungsservice die Vorschlagsfunktion nicht unterstützt.",
    "layerSource": "Layer-Quelle",
    "setLayerSource": "Layer-Quelle festlegen",
    "setGeocoderURL": "Geocoder-URL festlegen",
    "searchLayerTips": "Es sind keine Vorschläge verfügbar, da der Feature-Service die Paginierungsfunktion nicht unterstützt.",
    "placeholder": "Platzhaltertext",
    "searchFields": "Suchfelder",
    "displayField": "Anzeigefeld",
    "exactMatch": "Exakte Übereinstimmung",
    "maxSuggestions": "Maximale Anzahl von Vorschlägen",
    "maxResults": "Maximale Anzahl von Ergebnissen",
    "enableLocalSearch": "Lokale Suche aktivieren",
    "minScale": "Min. Maßstab",
    "minScaleHint": "Wenn der Kartenmaßstab größer ist als dieser Maßstab, wird die lokale Suche angewendet.",
    "radius": "Radius",
    "radiusHint": "Ermöglicht die Festlegung des Radius einer Fläche um den aktuellen Kartenmittelpunkt, der dazu dient, die Rangfolge von Geokodierungskandidaten zu optimieren. Die Kandidaten, die der Position am nächsten liegen, werden auf diese Weise zuerst ausgegeben.",
    "setSearchFields": "Suchfelder festlegen",
    "set": "Festlegen",
    "invalidUrlTip": "Die URL ${URL} ist ungültig oder es kann nicht darauf zugegriffen werden.",
    "invalidSearchSources": "Ungültige Einstellungen der Suchquelle"
  },
  "errorMsg": {
    "textboxFieldsEmptyErrorMsg": "Füllen Sie die erforderlichen Felder aus.",
    "bufferDistanceFieldsErrorMsg": "Geben Sie gültige Werte ein.",
    "invalidSearchToleranceErrorMsg": "Geben Sie einen gültigen Wert für die Suchtoleranz ein.",
    "atLeastOneCheckboxCheckedErrorMsg": "Ungültige Konfiguration: Mindestens ein Interessenbereich-Werkzeug ist erforderlich.",
    "noLayerAvailableErrorMsg": "Keine Layer verfügbar",
    "layerNotSupportedErrorMsg": "Wird nicht unterstützt ",
    "noFieldSelected": "Verwenden Sie die Aktion \"Bearbeiten\", um Felder für die Analyse auszuwählen.",
    "duplicateFieldsLabels": "Doppelte Bezeichnung \"${labelText}\" für: \"${itemNames}\" hinzugefügt",
    "noLayerSelected": "Wählen Sie mindestens einen Layer für die Analyse aus.",
    "errorInSelectingLayer": "Layer kann nicht ausgewählt werden. Versuchen Sie es erneut.",
    "errorInMaxFeatureCount": "Geben Sie einen gültigen Wert für die maximale Anzahl an Features für die Analyse ein."
  }
});