define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Punkt durch Klicken auf die Karte hinzufügen",
  "addRingsDtWt": "Fügen Sie Ringe, Fahrzeit oder Gehzeit hinzu.",
  "apply": "Übernehmen",
  "back": "Zurück",
  "colon": ":",
  "creditInformation": "Credit-Informationen",
  "driveTime": "Fahrzeit",
  "esriInfographics": "Esri Infografiken",
  "esriReports": "Esri Reports",
  "headerDescription_km": "Kilometer",
  "headerDescription_miles": "Meile",
  "headerDescription_minutes": "Minute",
  "infographics": "Infografiken",
  "invalidValueRing": "Die Werte müssen im Bereich von 0 bis 1.000 liegen.",
  "invalidValueDTWT": "Die Werte müssen im Bereich von 0 bis 300 liegen.",
  "km": "km",
  "miles": "Meilen",
  "minutes": "Minuten",
  "myInfographics": "Eigene Infografiken",
  "myReports": "Eigene Berichte",
  "noPermissions": "Das Widget \"Business Analyst\" kann in Ihrem Konto nicht ausgeführt werden. Damit das Widget \"Business Analyst\" ausgeführt werden kann, muss Ihnen der Administrator der Organisation die <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">Berechtigungen</a> für GeoEnrichment und die Netzwerkanalyse gewähren und ebenfalls <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">Credits</a> zuweisen.",
  "geServiceNotConfigured": "Das Widget \"Business Analyst\" kann auf diesem Portal nicht ausgeführt werden, da der <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">GeoEnrichment</a>-Service nicht darauf konfiguriert ist.",
  "dirRoutingServiceNotConfigured": "Das Widget \"Business Analyst\" kann auf diesem Portal nicht ausgeführt werden, da der <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Wegbeschreibungs- und Routing</a>-Service nicht darauf konfiguriert ist.",
  "geAndDirRoutingServicesNotConfigured": "Das Widget \"Business Analyst\" kann auf diesem Portal nicht ausgeführt werden, da der <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">GeoEnrichment</a>-Service sowie der <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Wegbeschreibungs- und Routing</a>-Service nicht darauf konfiguriert sind.",
  "radii": "Radien",
  "radius": "Radius",
  "radius_lowercase": "Radius",
  "reports": "Berichte",
  "ring": "Ring",
  "rings": "Ringe",
  "runInfographic": "Infografik ausführen",
  "runReport": "Bericht ausführen",
  "selectPointOrPolygon": "Wählen Sie auf der Karte ein Punkt- oder Polygon-Feature aus, suchen Sie nach einer Adresse bzw. einem Ort, oder platzieren Sie einen Pin auf der Karte, um für Bereiche von Interesse weitere Informationen anzuzeigen.",
  "selectReport": "Bericht auswählen",
  "selectTemplate": "Vorlage auswählen",
  "sharedInfographics": "Freigegebene Infografiken",
  "sharedReports": "Freigegebene Berichte",
  "thisEntryIsNotValid": "Dieser Eintrag ist ungültig.",
  "time": "Zeit",
  "walkTime": "Gehzeit",
  "widgetDescription": "Greifen Sie auf Infografiken und Berichte zu, die eine Zusammenfassung wichtiger Indikatoren und Daten für die einzelnen Bereiche enthalten.",
  "None": "Auswählen..."
});