define({
  "_widgetLabel": "Smart redigerare",
  "_featureAction_SmartEditor": "Smart redigerare",
  "noEditPrivileges": "Ditt konto har inte behörighet att skapa eller ändra data.",
  "widgetActive": "Aktiv",
  "widgetNotActive": "Inte aktiv",
  "pressStr": "Tryck på ",
  "ctrlStr": " CTRL ",
  "snapStr": " när du vill aktivera snappning",
  "noAvailableTempaltes": "Inga tillgängliga mallar",
  "editorCache": " – redigerarens cache",
  "presetFieldAlias": "Fält",
  "presetValue": "Förinställt värde",
  "usePresetValues": " Använd förinställda värden (endast nya geoobjekt)",
  "editGeometry": " Redigera geometri",
  "savePromptTitle": "Spara geoobjekt",
  "savePrompt": "Vill du spara det aktuella geoobjektet?",
  "deletePromptTitle": "Ta bort objekt",
  "deleteAttachment": "Ta bort bilaga",
  "deletePrompt": "Är du säker på att du vill ta bort det valda geoobjektet?",
  "attachmentLoadingError": "Ett fel uppstod vid överföring av bilagor",
  "attachmentSaveDeleteWarning": "Varning! Ändringar i bilagor sparas automatiskt",
  "autoSaveEdits": "Sparar nya geoobjekt automatiskt",
  "addNewFeature": "Skapa nytt geoobjekt",
  "featureCreationFailedMsg": "Det går inte att skapa ny post/nytt geoobjekt",
  "relatedItemTitle": "Relaterad tabell/relaterade lager",
  "relatedFeatureCount": "${layerTitle} med ${featureCount} geoobjekt",
  "createNewFeatureLabel": "Skapa nytt geoobjekt för ${layerTitle}",
  "invalidRelationShipMsg": "Kontrollera att primärnyckelfältet: '${parentKeyField}' har ett giltigt värde",
  "pendingFeatureSaveMsg": "Spara ändringarna av geoobjektet innan ett relaterat geoobjekt skapas.",
  "attachmentsRequiredMsg": "(*) Bilagor krävs.",
  "coordinatePopupTitle": "Flytta geoobjekt till XY-position",
  "coordinatesSelectTitle": "Koordinatsystem:",
  "mapSpecialReferenceDropdownOption": "Kartans geografiska referens",
  "latLongDropdownOption": "Latitud/longitud",
  "xAttributeTextBoxLabel": "X-koordinat:",
  "yAttributeTextBoxLabel": "Y-koordinat:",
  "latitudeTextBoxLabel": "Latitud:",
  "longitudeTextBoxLabel": "Longitud:",
  "presetGroupFieldsLabel": "”${groupName}” tillämpas för följande lagerfält:",
  "presetGroupNoFieldsLabel": "”${groupName}” har inga associerade fält",
  "groupInfoLabel": "Gruppinformation för ”${groupName}”",
  "editGroupInfoIcon": "Redigera gruppvärde för ${groupName}",
  "filterEditor": {
    "all": "Alla",
    "noAvailableTempaltes": "Inga tillgängliga mallar",
    "searchTemplates": "Sök efter mallar",
    "filterLayerLabel": "Filtrera lager"
  },
  "invalidConfiguration": "Widgeten är antingen inte konfigurerad eller så finns lagren i konfigurationen inte längre i kartan. Öppna appen i byggläge och konfigurera om widgeten.",
  "geometryServiceURLNotFoundMSG": "Det gick inte att hämta webbadress till geometritjänst",
  "clearSelection": "Avmarkera",
  "refreshAttributes": "Uppdatera attribut för geoobjekt",
  "automaticAttributeUpdatesOn": "Uppdatera attribut för geoobjekt automatiskt: PÅ",
  "automaticAttributeUpdatesOff": "Uppdatera attribut för geoobjekt automatiskt: AV",
  "moveSelectedFeatureToGPS": "Flytta markerat geoobjekt till aktuell GPS-position",
  "moveSelectedFeatureToXY": "Flytta markerat geoobjekt till XY-position",
  "mapNavigationLocked": "Kartnavigering: låst",
  "mapNavigationUnLocked": "Kartnavigering: olåst",
  "copyFeatures": {
    "title": "Kopiera geoobjekt",
    "createFeatures": "Skapa geoobjekt",
    "createSingleFeature": "Skapa 1 multigeometrigeoobjekt",
    "noFeaturesSelectedMessage": "Inga geoobjekt valda",
    "selectFeatureToCopyMessage": "Välj geoobjekt som ska kopieras.",
    "multipleFeatureSaveWarning": "Obs! Om du skapar flera geoobjekt med kopieringsfunktionen sparas alla geoobjekt omedelbart"
  },
  "addingFeatureError": "Det uppstod ett fel medan valda geoobjekt lades till i lagret. Försök igen.",
  "addingFeatureErrorCount": "${copyFeatureErrorCount} geoobjekt gick inte att kopiera.",
  "selectingFeatureError": "Det uppstod ett fel medan geoobjekt valdes i lagret. Försök igen.",
  "customSelectOptionLabel": "Välj geoobjekten som ska kopieras",
  "noFeatureSelectedMessage": "Inga geoobjekt valda.",
  "multipleFeatureSaveMessage": "Alla geoobjekt sparas omedelbart. Vill du fortsätta?",
  "relativeDates": {
    "dateTypeLabel": "Datatyp",
    "valueLabel": "Värde",
    "fixed": "Fast",
    "current": "Aktuell",
    "past": "Förflutna",
    "future": "Framtida",
    "popupTitle": "Välj värde",
    "hintForFixedDateType": "Tips! Angivet datum och tid används som det förinställda standardvärdet.",
    "hintForCurrentDateType": "Tips! Aktuellt datum och tid används som det förinställda standardvärdet.",
    "hintForPastDateType": "Tips! Det angivna värdet dras bort från aktuellt datum och tid för förinställningens standardvärde.",
    "hintForFutureDateType": "Tips! Det angivna värdet läggs till aktuellt datum och tid för förinställningens standardvärde.",
    "noDateDefinedTooltip": "Inget datum angivet",
    "relativeDateWarning": "Ett värde för datum eller tid måste anges för att det ska gå att spara det förinställda värdet."
  }
});