define({
  "defaultAreaUnit": "Unidade de Área padrão",
  "defaultLengthUnit": "Unidade de Comprimento Padrão",
  "acres": "Acres",
  "sqMiles": "Milhas Quadradas",
  "sqKilometers": "Quilômetros Quadrados",
  "hectares": "Hectares",
  "sqYards": "Jardas Quadradas",
  "sqFeet": "Pés Quadrados",
  "sqFeetUS": "Pés Quadrados (EUA)",
  "sqMeters": "Metros Quadrados",
  "miles": "Milhas",
  "kilometers": "Quilómetros",
  "feet": "Pés",
  "feetUS": "Pés (EUA)",
  "meters": "Metros",
  "yards": "Jardas",
  "nauticalMiles": "Milhas Náuticas",
  "showArea": "Área",
  "showDistance": "Distância",
  "showLocation": "Localização",
  "showtools": "Exibir ferramentas de medição:",
  "allHidedTips": "Tem de ser selecionada pelo menos uma ferramenta."
});