define({
  "searchTabTitle": "Configuració de l'origen de la cerca",
  "routeTabTitle": "Configuració de ruta",
  "add": "Afegeix un origen de cerca",
  "addGeocoder": "Afegeix un geocodificador",
  "geocoder": "Geocodificador",
  "setLayerSource": "Defineix l'origen de la capa",
  "setGeocoderURL": "Defineix la URL del geocodificador",
  "searchableLayer": "Capa d'entitats",
  "name": "Nom",
  "countryCode": "Codis de país o regió",
  "countryCodeEg": "per exemple, ",
  "countryCodeHint": "Si aquest valor es deixa en blanc, la cerca es farà en tots els països i regions",
  "showInfoWindowOnSelect": "Mostra la finestra emergent de l'entitat o la ubicació trobada",
  "showInfoWindowOnSelect2": "Mostra la finestra emergent quan es trobi l'entitat o la ubicació.",
  "searchInCurrentMapExtent": "Cerca només a l'extensió de mapa actual",
  "setSearchFields": "Defineix els camps de cerca",
  "set": "Defineix",
  "fieldSearchable": "permet la cerca",
  "zoomScale": "Escala de zoom",
  "locatorUrl": "URL del geocodificador",
  "locatorName": "Nom del geocodificador",
  "locatorExample": "Exemple",
  "locatorWarning": "Aquesta versió del servei de geocodificació no s'admet. El widget admet la versió 10.1 del servei de geocodificació i altres versions posteriors.",
  "locatorTips": "Els suggeriments no estan disponibles perquè el servei de geocodificació no admet la funció de suggeriments.",
  "layerSource": "Origen de la capa",
  "searchLayerTips": "Els suggeriments no estan disponibles perquè el servei d'entitats no admet la funció de paginació.",
  "placeholderText": "Text del marcador de posició",
  "searchFields": "Camps de cerca",
  "displayField": "Camp de visualització",
  "exactMatch": "Coincidència exacta",
  "maxSuggestions": "Màxim de suggeriments",
  "maxResults": "Màxim de resultats",
  "enableLocalSearch": "Habilita la cerca local",
  "minScale": "Escala mínima",
  "minScaleHint": "Si l'escala del mapa és més gran que aquesta escala, s'aplicarà la cerca local",
  "radius": "Radi",
  "radiusHint": "Permet especificar el radi d'una àrea al voltant del centre del mapa actual que s'utilitzarà per millorar la classificació dels candidats de geocodificació per tal que es retornin primer aquells més propers a la ubicació",
  "invalidUrlTip": "L'adreça URL ${URL} no és vàlida o no s'hi pot accedir.",
  "routeUrl": "URL de la ruta",
  "geocoderOptions": "Opcions del geocodificador",
  "autoComplete": "Emplena automàticament",
  "maximumSuggestions": "Màxim de suggeriments",
  "minCharacters": "Mínim de caràcters",
  "searchDelay": "Retard de la cerca",
  "placeholder": "Marcador de posició",
  "routeOptions": "Opcions de ruta",
  "directionsLanguage": "Idioma de les indicacions",
  "directionsLengthUnits": "Unitats de longitud de les indicacions",
  "directionsOutputType": "Tipus de sortida de les indicacions",
  "impedanceAttribute": "Atribut d'impedància",
  "kilometers": "Quilòmetres",
  "miles": "Milles",
  "meters": "Metres",
  "feet": "Peus",
  "yards": "Iardes",
  "nauticalMiles": "Milles nàutiques",
  "parametersTip": "Definiu els paràmetres correctament.",
  "complete": "Completa",
  "completeNoEvents": "No completis cap esdeveniment",
  "instructionsOnly": "Només instruccions",
  "standard": "Estàndard",
  "summaryOnly": "Només resum",
  "travelModesUrl": "URL de modes de viatge",
  "searchPlaceholder": "Cerca una direcció o un lloc",
  "trafficLayerUrl": "URL de la capa de trànsit",
  "barrierLayerUrl": "URL de la capa de barrera",
  "presetDestinations": "Parades predefinides",
  "startPoint": "Punt d'inici",
  "endPoint": "Punt final",
  "destinationHolder": "Adreça o coordenades",
  "optional": "Opcional.",
  "barrierLayers": "Capes de barrera",
  "pointBarrier": "Barreres de punt",
  "lineBarrier": "Barreres de línia",
  "polygonBarrier": "Barreres de polígon",
  "noPointBarrier": "Seleccioneu barreres de punt",
  "noLineBarrier": "Seleccioneu barreres de línia",
  "noPolygonBarrier": "Seleccioneu barreres de polígon"
});