define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Добавить точку, щелкнув на карте",
  "addRingsDtWt": "Добавить окружности, время в пути или время пешком.",
  "apply": "Применить",
  "back": "Назад",
  "colon": ":",
  "creditInformation": "Сведения о кредитах",
  "driveTime": "Время в пути",
  "esriInfographics": "Инфографика Esri",
  "esriReports": "Отчеты Esri",
  "headerDescription_km": "километр",
  "headerDescription_miles": "миля",
  "headerDescription_minutes": "минута",
  "infographics": "Инфографика",
  "invalidValueRing": "Значение должно быть в диапазоне от 0 до 1000.",
  "invalidValueDTWT": "Значение должно быть в диапазоне от 0 до 300.",
  "km": "км",
  "miles": "миль",
  "minutes": "минуты",
  "myInfographics": "Моя инфографика",
  "myReports": "Мои отчеты",
  "noPermissions": "Ваша учетная запись не позволяет запустить виджет Business Analyst.  Для запуска виджета Business Analyst администратор вашей организации должен предоставить вам права GeoEnrichment и Network Analysis <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\"></a>, и также предоставить <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">кредиты</a>.",
  "geServiceNotConfigured": "Виджет Business Analyst не может быть запущен на этом портале, так как <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Сервис Геообогащение</a> на нем не настроен.",
  "dirRoutingServiceNotConfigured": "Виджет Business Analyst не может быть запущен на этом портале, так как <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Сервис Маршрутизация и путевые листы</a> на нем не настроен.",
  "geAndDirRoutingServicesNotConfigured": "Виджет Business Analyst не может быть запущен на этом портале, так как <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Сервисы Геообогащение</a> и <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Маршрутизация и путевые листы</a> на нем не настроены.",
  "radii": "радиус",
  "radius": "Радиус",
  "radius_lowercase": "радиус",
  "reports": "Отчеты",
  "ring": "Кольцо",
  "rings": "Кольца",
  "runInfographic": "Запустить инфографику",
  "runReport": "Запустить отчет",
  "selectPointOrPolygon": "Выбрать точечный или полигональный объект на карте, найти адрес или место, или обозначить место на карте булавкой для просмотра информации об этой области.",
  "selectReport": "Выбрать отчет",
  "selectTemplate": "Выбрать шаблон",
  "sharedInfographics": "Опубликованная инфографика",
  "sharedReports": "Опубликованные отчеты",
  "thisEntryIsNotValid": "Элемент некорректный.",
  "time": "Время",
  "walkTime": "Время пешком",
  "widgetDescription": "Доступ к инфографике и отчетам, суммирующий ключевые индикаторы и данные для любой области.",
  "None": "Выбрать..."
});