define({
  "chartSettingLabel": "Impostazioni grafico",
  "addNewLabel": "Aggiungi nuovo",
  "generalSettingLabel": "Impostazioni generali",
  "layerChooser": {
    "title": "Selezionare layer da rappresentare",
    "selectPolygonLayerLabel": "Seleziona layer",
    "selectPolygonLayerHintText": "Suggerimento: se si configurano più grafici, il tipo di geometria dei layer deve essere identica",
    "selectRelatedTableLayerLabel": "Seleziona tabella correlata a layer",
    "selectRelatedTableLayerHintText": "Suggerimento: vengono visualizzate solo le tabelle con campi numerici",
    "errorInSelectingPolygonLayer": "Selezionare un layer con un layer punto correlato.",
    "errorInSelectingRelatedLayer": "Selezionare una tabella/layer correlato valido nel layer.",
    "polygonLayerNotHavingRelationships": "Il layer selezionato non dispone di tabella/layer correlato."
  },
  "ChartSetting": {
    "sectionTitle": "Titolo sezione",
    "sectionTitleHintText": "Suggerimento: visualizzato nel titolo intestazione sezione",
    "chartTitle": "Titolo grafico",
    "chartTitleHintText": "Suggerimento: visualizzato al centro nella parte superiore del grafico",
    "chartDescription": "Descrizione",
    "chartDescriptionHintText": "Suggerimento: visualizzato sotto il grafico",
    "chartType": "Tipo di grafico",
    "barChart": "Grafico a barre",
    "pieChart": "Grafico a torta",
    "polarChart": "Grafico polare",
    "dataSeriesField": "Campo serie di dati",
    "labelField": "Campo etichetta",
    "chartColor": "Colore grafico",
    "singleColor": "Colore singolo",
    "colorByTheme": "Colore in base a tema",
    "colorByFieldValue": "Colore in base a valore campo",
    "xAxisTitle": "Titolo asse X",
    "xAxisHintText": "Suggerimento: titolo asse X",
    "yAxisTitle": "Titolo asse Y",
    "yAxisHintText": "Suggerimento: titolo asse Y",
    "fieldColorLabel": "Etichetta",
    "fieldColorColor": "Colore",
    "defaultFieldSelectLabel": "Seleziona",
    "errMsgFieldValuesNotFound": "Impossibile trovare i valori per il campo selezionato",
    "errMsgSectionTitle": "Immettere i titolo di sezione",
    "errMsgFieldByValue": "Selezionare un valore campo",
    "settingTabTitle": "Impostazione",
    "layoutTabTitle": "Layout",
    "polarChartSelectFieldsHintText": "Suggerimento: selezionare campi per generare grafico polare",
    "visibilityText": "Visibilità",
    "fieldNameText": "Nome campo",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Selezionare tre o più campi per generare grafico polare",
    "polarChartPolygonFillLabel": "Riempi poligono",
    "polarChartPolygonFillHintText": "Suggerimento: selezionare la casella di controllo per mostrare il riempimento poligono nel grafico polare",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Deserto",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irlanda",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Terreno paludoso",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Impostazioni generali",
    "locationSymbolLabel": "Simbolo posizione grafica",
    "locationSymbolHintText": "Suggerimento: utilizzato per visualizzare simbolo per posizione indirizzo e selezione",
    "refreshIntervalLabel": "Intervallo di aggiornamento",
    "refreshIntervalHintText": "Suggerimento: utilizzato per aggiornare i grafici basati su questo intervallo. Specificare un valore compreso tra 1 e 1440 minuti",
    "errMsgRefreshInterval": "Specificare l'intervallo di aggiornamento compreso tra 0 e 1440 minuti",
    "symbolPickerPreviewText": "Anteprima:"
  }
});