define({
  "symbolologyTabLabel": "Налаштувати умовні позначення",
  "facilitiesDescription": "Допоміжні шари пунктів обслуговування",
  "demographicsDescription": "Шар демографічних характеристик",
  "settingsTitle": "Налаштування",
  "spillLocationLabel": "Місце розташування розливу",
  "spillLocationButtonLabel": "Змінити налаштування місця розташування розливу",
  "IISettingsLabel": "Зона початкової ізоляції",
  "IIButtonLabel": "Змінити налаштування зони початкової ізоляції",
  "PASettingsLabel": "Зона захисних дій",
  "PAButtonLabel": "Змінити налаштування зони захисних дій",
  "downwindSettingsLabel": "Підвітряна зона",
  "downwindButtonLabel": "Змінити налаштування підвітряної зони",
  "fireSettingsLabel": "Зона ізоляції пожежі",
  "fireButtonLabel": "Змінити налаштування зони ізоляції пожежі",
  "bleveSettingsLabel": "Зона ізоляції вибуху внаслідок розширення парів киплячої рідини (BLEVE)",
  "bleveButtonLabel": "Змінити налаштування зони ізоляції вибуху внаслідок розширення парів киплячої рідини (BLEVE)",
  "transparency": "Прозорість",
  "outline": "Контур",
  "fill": "Заливка (колір застосовується, тільки коли для стиля вибрано параметр «Суцільний»)",
  "style": "Стиль",
  "selectOpLayerLabel": "Вибрати робочий шар для результатів",
  "selectDefaultMeasurementLabel": "Вибрати одиниці виміру за замовчуванням",
  "helpIconTooltip": "Робочий шар заповнюється шарами з поточної веб-карти, що відносяться до типу геометрії «полігон».",
  "colorPicker": "Панель вибору кольору",
  "lineStyles": {
    "esriSLSDash": "Пунктир",
    "esriSLSDashDot": "Штрихпунктир",
    "esriSLSDashDotDot": "Штрихпунктир з двома крапками",
    "esriSLSDot": "Точковий пунктир",
    "esriSLSLongDash": "Пунктир з довгим тире",
    "esriSLSLongDashDot": "Штрихпунктир з довгим тире",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Пунктир з коротким тире",
    "esriSLSShortDashDot": "Штрихпунктир з коротким тире",
    "esriSLSShortDashDotDot": "Штрихпунктир з коротким тире та двома крапками",
    "esriSLSShortDot": "Штрихпунктир з коротким тире",
    "esriSLSSolid": "Суцільний"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Назад",
    "esriSFSCross": "Хрест",
    "esriSFSDiagonalCross": "Діагональ",
    "esriSFSForwardDiagonal": "Вперед",
    "esriSFSHorizontal": "Горизонтальний",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Суцільний",
    "esriSFSVertical": "Вертикальний"
  }
});