define({
  "defaultAreaUnit": "Đơn vị Diện tích Mặc định",
  "defaultLengthUnit": "Đơn vị Độ dài Mặc định",
  "acres": "Mẫu Anh",
  "sqMiles": "Dặm vuông",
  "sqKilometers": "Kilômét vuông",
  "hectares": "Hecta",
  "sqYards": "Thước vuông",
  "sqFeet": "Bộ vuông",
  "sqFeetUS": "Feet vuông (Hoa Kỳ)",
  "sqMeters": "Mét vuông",
  "miles": "Dặm",
  "kilometers": "Kilômét",
  "feet": "Feet",
  "feetUS": "Feet (Hoa Kỳ)",
  "meters": "Mét",
  "yards": "Thước",
  "nauticalMiles": "Hải lý",
  "showArea": "Khu vực",
  "showDistance": "Khoảng cách",
  "showLocation": "Vị trí",
  "showtools": "Hiện công cụ đo lường:",
  "allHidedTips": "Phải chọn ít nhất một công cụ."
});