define({
  "searchTabTitle": "Haun lähteen asetus",
  "routeTabTitle": "Reititysasetus",
  "add": "Lisää haun lähde",
  "addGeocoder": "Lisää geokooderi",
  "geocoder": "Geokooderi",
  "setLayerSource": "Määritä karttatason lähde",
  "setGeocoderURL": "Määritä geokooderin URL-osoite",
  "searchableLayer": "Kohdekarttataso",
  "name": "Nimi",
  "countryCode": "Maa- tai aluekoodit",
  "countryCodeEg": "esim. ",
  "countryCodeHint": "Jos jätät tämän arvon tyhjäksi, ohjelma etsii kaikista maista ja kaikilta alueilta",
  "showInfoWindowOnSelect": "Näytä löydetyn kohteen tai sijainnin ponnahdusikkuna",
  "showInfoWindowOnSelect2": "Näytä ponnahdusikkuna, kun kohde tai sijainti on löytynyt.",
  "searchInCurrentMapExtent": "Etsi vain nykyisestä karttalaajuudesta",
  "setSearchFields": "Määritä hakukentät",
  "set": "Aseta",
  "fieldSearchable": "haettavissa oleva",
  "zoomScale": "Tarkennustaso",
  "locatorUrl": "Geokooderin URL-osoite",
  "locatorName": "Geokooderin nimi",
  "locatorExample": "Esimerkki",
  "locatorWarning": "Geokoodauspalvelun versiota ei tueta. Pienoisohjelma tukee geokoodauspalvelun versiota 10.1 ja sitä uudempia versioita.",
  "locatorTips": "Ehdotukset eivät ole käytettävissä, koska geokoodauspalvelu ei tue ehdotustoimintoa.",
  "layerSource": "Karttatason lähde",
  "searchLayerTips": "Ehdotukset eivät ole käytettävissä, koska kohdepalvelu ei tue sivutustoimintoa.",
  "placeholderText": "Muuttujan teksti",
  "searchFields": "Hakukentät",
  "displayField": "Näyttökenttä",
  "exactMatch": "Tarkka vastine",
  "maxSuggestions": "Ehdotusten enimmäismäärä",
  "maxResults": "Tulosten enimmäismäärä",
  "enableLocalSearch": "Ota käyttöön paikallinen haku",
  "minScale": "Vähimmäismittakaava",
  "minScaleHint": "Kun kartan mittakaava on suurempi kuin tämä mittakaava, käytetään paikallista hakua",
  "radius": "Säde",
  "radiusHint": "Määrittää nykyisen kartan keskikohdan ympärillä olevan alueen säteen. Säteen avulla arvioidaan geokoodausehdokkaiden sijoitusta, jotta sijaintia lähinnä olevat ehdokkaat palautetaan ensin",
  "invalidUrlTip": "Syötetty URL-osoite ${URL} on virheellinen, tai se ei ole käytettävissä.",
  "routeUrl": "Reitin URL-osoite",
  "geocoderOptions": "Geokooderin vaihtoehdot",
  "autoComplete": "Täydennä automaattisesti",
  "maximumSuggestions": "Ehdotusten enimmäismäärä",
  "minCharacters": "Merkkien vähimmäismäärä",
  "searchDelay": "Haku viivästyy",
  "placeholder": "Paikkamerkki",
  "routeOptions": "Reittivaihtoehdot",
  "directionsLanguage": "Ohjeiden kieli",
  "directionsLengthUnits": "Ohjeiden pituusyksiköt",
  "directionsOutputType": "Ohjeiden tulosaineiston tyyppi",
  "impedanceAttribute": "Impedanssin ominaisuus",
  "kilometers": "Kilometriä",
  "miles": "Mailia",
  "meters": "Metriä",
  "feet": "Jalkaa",
  "yards": "Jaardia",
  "nauticalMiles": "Meripeninkulmaa",
  "parametersTip": "Määritä parametrit oikein.",
  "complete": "Valmis",
  "completeNoEvents": "Älä suorita loppuun yhtään tapahtumaa",
  "instructionsOnly": "Vain ohjeet",
  "standard": "Vakio",
  "summaryOnly": "Vain yhteenveto",
  "travelModesUrl": "Matkustustapojen URL-osoitteet",
  "searchPlaceholder": "Etsi osoite tai paikka",
  "trafficLayerUrl": "Liikenteen karttatason URL-osoite",
  "barrierLayerUrl": "Estekarttatason URL-osoite",
  "presetDestinations": "Esiaseta pysähdykset",
  "startPoint": "Aloituspiste",
  "endPoint": "Lopetuspiste",
  "destinationHolder": "Osoite tai koordinaatit",
  "optional": "Valinnainen.",
  "barrierLayers": "Esteiden karttatasot",
  "pointBarrier": "Piste-esteet",
  "lineBarrier": "Viivaesteet",
  "polygonBarrier": "Alue-esteet",
  "noPointBarrier": "Valitse piste-esteet",
  "noLineBarrier": "Valitse viivaesteet",
  "noPolygonBarrier": "Valitse alue-esteet"
});