define({
  "transparencyLabel": "โปร่งแสง",
  "outline": "โครงร่าง",
  "fill": "พื้น (ใช้สีเฉพาะเมื่อรูปแบบถูกตั้งค่าเป็นแบบทึบ)",
  "style": "สไตล์",
  "mandatoryLabel": "ระยะห่างบังคับในการอพยพ",
  "mandatoryButtonLabel": "กำหนดการตั้งค่าระยะห่างบังคับในการอพยพ",
  "safeLabel": "ระยะห่างปลอดภัยในการอพยพ",
  "safeButtonLabel": "กำหนดการตั้งค่าระยะห่างปลอดภัยในการอพยพ",
  "selectOpLayerLabel": "เลือกชั้นข้อมูลดำเนินการสำหรับผลลัพธ์",
  "selectDefaultMeasurementLabel": "เลือกหน่วยวัดเริ่มต้น",
  "helpIconTooltip": "รายการชั้นข้อมูลดำเนินการ จะถูกนำเข้าแบบอัตโนมัติพร้อมชั้นข้อมูลจากเว็บแมปปัจจุบัน ซึ่งเป็นประเภทรูปทรงเรขาคณิตโพลีกอน",
  "lineStyles": {
    "esriSLSDash": "เส้นขีด",
    "esriSLSDashDot": "เส้นขีด จุด",
    "esriSLSDashDotDot": "เส้นขีด จุด จุด",
    "esriSLSDot": "จุด",
    "esriSLSLongDash": "เส้นขีดยาว",
    "esriSLSLongDashDot": "เส้นจุดยาว",
    "esriSLSNull": "ไม่มีค่า",
    "esriSLSShortDash": "เส้นขีดสั้น",
    "esriSLSShortDashDot": "เส้นจุดสั้น",
    "esriSLSShortDashDotDot": "เส้นขีดและจุดสั้น",
    "esriSLSShortDot": "จุดสั้น",
    "esriSLSSolid": "สีเดียว"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "ย้อนกลับ",
    "esriSFSCross": "กากบาท",
    "esriSFSDiagonalCross": "เส้นทแยงมุม",
    "esriSFSForwardDiagonal": "ส่งต่อ",
    "esriSFSHorizontal": "แนวนอน",
    "esriSFSNull": "ไม่มีค่า",
    "esriSFSSolid": "สีเดียว",
    "esriSFSVertical": "ตั้งฉาก"
  },
  "threatTypeLabel": "ประเภทภัยคุกคาม",
  "symbologyLabel": "เกี่ยวกับสัญลักษณ์",
  "generalLabel": "ทั่วไป",
  "addThreatTypesLabel": "เพิ่มประเภทภัยคุกคาม",
  "threatTypeColLabel": "ประเภทภัยคุกคาม",
  "actions": "การดำเนินการ",
  "newThreatTypePopupLabel": "ประเภทภัยคุกคามใหม่",
  "chooseDefaultThreatTypeIconLabel": "เลือกจากค่าเริ่มต้น",
  "mandatoryDistance": "ระยะห่างบังคับในการอพยพ",
  "safeDistance": "ระยะห่างปลอดภัยในการอพยพ",
  "units": "หน่วย",
  "chooseDefaultThreatLabel": "เลือกประเภทภัยคุกคามเริ่มต้น",
  "defaultThreatTypePopUpLabel": "ประเภทภัยคุกคามเริ่มต้น",
  "editThreatLabel": "แก้ไขภัยคุกคาม",
  "defaultThreatTypeIconTooltip": "รายการประเภทภัยคุกคามเริ่มต้น",
  "uniqueThreatTypeMsg": "ป้อนประเภทภัยคุกคามที่ไม่ซ้ำกัน มีประเภทภัยคุกคามที่ใช้ชื่อนี้อยู่แล้ว",
  "requiredThreatTypeMsg": "ฟิลด์นี้เป็นฟิลด์บังคับ",
  "unitMeasureLabel": "ระยะทางจะใช้หน่วย {0}",
  "pipeBombLabel": "ระเบิดท่อ",
  "suicideBombLabel": "ระเบิดพลีชีพ",
  "briefcaseLabel": "กระเป๋าเอกสาร",
  "carLabel": "รถยนต์",
  "suvVanLabel": "SUV/รถตู้",
  "smallDeliveryTruckLabel": "รถส่งของขนาดเล็ก",
  "containerWaterTruckLabel": "คอนเทนเนอร์/รถบรรทุกน้ำ",
  "semiTrailerLabel": "รถกึ่งพ่วง"
});