define({
  "tabs_section_Label": "Kategorier",
  "addTab": "Legg til kategori",
  "layerName": "Lag",
  "layerType": "Analysetype",
  "layerLabel": "Etikett",
  "actions": "Handlinger",
  "closest": "Nærmeste geoobjekt",
  "proximity": "Nærhet",
  "summary": "Sammendrag",
  "select_lbl": "-- Velg --",
  "general_setting_Label": "Generelle innstillinger",
  "units_text_lbl": "Avstandsenheter:",
  "maximum_distance_lbl": "Største avstand for nærmeste geoobjekt",
  "buffer_text_lbl": "Bufferetikett",
  "buffer_lbl": "Bufferavstand",
  "buffer_max_lbl": "Største bufferavstand",
  "buffer_min_lbl": "Minste bufferavstand",
  "routing_checkBox": "Aktiver rutetjeneste",
  "weather_Label": "Væralternativer",
  "weather_checkBox": "Inkluder værinformasjon",
  "selectLayers": "velg værlag",
  "currentlySelectedLayer": "Valgte værlag",
  "missingTabLabel": "Minst én kategori mangler påskrift",
  "missingLayerInWebMap": "Finner ingen operative lag.",
  "selectFields": "Velg felter",
  "addField": "Legg til felt",
  "sum": "Summer",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Gjennomsnitt",
  "count": "ANTALL",
  "area": "OMRÅDE",
  "length": "LENGDE",
  "count_checkBox": "Vis antall geoobjekter",
  "area_checkBox": "Vis sum for areal",
  "length_checkBox": "Vis sum for lengde",
  "max_records": "Maksimumsgrensen er nådd",
  "save_label": "Lagre alternativer",
  "save_checkbox": "Aktiver lagring",
  "csv_label": "Alternativer for CSV",
  "csv_checkbox": "Eksporter alle feltene i laget",
  "display_label": "Visningsalternativer",
  "display_checkbox": "Vis geoobjekter for oppsummering",
  "snapshot_label": "Alternativer for snapshot",
  "snapshot_checkbox": "Aktiver snapshot",
  "must_select_template": "Velg en av redigeringsmalene i Lagre alternativer.",
  "count_label": "Etikett for antall",
  "area_label": "Etikett for område",
  "length_label": "Etikett for lengde",
  "invalid_string_width": "Verdien er for lang. ",
  "layer_type_not_supported": "Lagtypen støttes ikke: ",
  "groupedSummary": "Gruppert antall",
  "groupByField": "Grupper etter felt",
  "labelType": "Legg til etikett",
  "prefix": "Som prefiks",
  "suffix": "Som suffiks",
  "need_group_field": "Bruk redigeringshandlingen for å angi gruppering etter felt.",
  "fieldTitle": "Felt",
  "typeTitle": "Type",
  "actionsTitle": "Handlinger",
  "save_point_checkbox": "Lagre punkter",
  "save_line_checkbox": "Lagre linjer",
  "save_poly_checkbox": "Lagre polygoner",
  "no_valid_popup_fields": "Ingen gyldige felt i popupen. Bruk redigeringshandlingen til å definere et felt.",
  "no_valid_fields": "Ingen gyldige felt. Bruk redigeringshandlingen til å definere visningsalternativer.",
  "incident_label": "Faneetikett",
  "locate_incident_label": "Etikett for interesseområde",
  "incident": "Hendelse",
  "locate_incident": "Lokaliser hendelsen",
  "buffer_value": "Bufferavstand"
});