define({
  "_widgetLabel": "インシデント解析",
  "_featureAction_SetAsIncident": "インシデントとして設定",
  "incident": "インシデント",
  "weather": "天気",
  "locate_incident": "インシデントの特定",
  "clear_incidents": "インシデントの消去",
  "reverse_geocoded_address": "最も近い住所",
  "reverse_geocoded_error": "利用不可",
  "miles": "マイル",
  "kilometers": "キロメートル",
  "feet": "フィート",
  "meters": "メートル",
  "yards": "ヤード",
  "nauticalMiles": "海里",
  "now": "現在",
  "wind": "風",
  "SUN": "日",
  "MON": "月",
  "TUE": "火",
  "WED": "水",
  "THU": "木",
  "FRI": "金",
  "SAT": "土",
  "defaultTabMsg": "インシデントが見つかりません。",
  "useMapExtent": "現在のマップ範囲を使用",
  "noFeaturesFound": "フィーチャは見つかりませんでした。",
  "downloadCSV": "CSV のダウンロード",
  "sum": "合計",
  "min": "最小",
  "max": "最大",
  "avg": "平均",
  "count": "総数",
  "area": "面積",
  "length": "長さ"
});