define({
  "_widgetLabel": "Visibilità",
  "observerLocation": "Posizione dell’osservatore",
  "formatIconTooltip": "Input formato",
  "addPointToolTip": "Aggiungi posizione osservatore",
  "fieldOfView": "Campo di vista",
  "useMilsText": "Utilizzare miglia per angoli",
  "observerHeight": "Altezza dell’osservatore",
  "minObsDistance": "Distanza minima dell’osservatore",
  "maxObsDistance": "Distanza massima dell’osservatore",
  "taskURLError": "Il file di configurazione del widget contiene un URL non raggiungibile. Verificare con l'amministratore del sistema.",
  "taskURLInvalid": "L’attività di geoprocessing configurata con questo widget non è valida. Verificare con l'amministratore del sistema.",
  "viewshedError": "Si è verificato un errore durante la creazione della visibilità. Verificare che la posizione dell’osservatore si trovi all’interno della superficie di elevazione.</p>",
  "validationError": "<p>Il modulo di creazione della visibilità contiene valori mancanti o non validi. Verificare:</p><ul><li>Di aver impostato una posizione dell’osservatore.</li><li>Che il Campo di vista dell’osservatore non sia 0.</li><li>Che l'altezza dell’osservatore contenga un valore valido.</li><li>Che le distanze osservabili minima e massima contengano valori validi.</li></ul>",
  "comfirmInputNotation": "Confermare l'input annotato.",
  "notationsMatch": "Notazioni corrispondenti all'input. Confermare quale si desidera utilizzare:",
  "createBtn": "Crea",
  "clearBtn": "Cancella",
  "setCoordFormat": "Imposta stringa di formato coordinata",
  "prefixNumbers": "Aggiungere il prefisso '+/-' ai numeri positivi e negativi",
  "parseCoordinatesError": "Impossibile analizzare le coordinate. Controllare l'input.",
  "cancelBtn": "Annulla",
  "applyBtn": "Applica",
  "invalidMessage": "Immettere un valore numerico.",
  "observerRangeMessage": "Altezza osservatore non valida",
  "minimumRangeMessage": "Intervallo minimo osservabile non valido",
  "maximumRangeMessage": "L’Intervallo massimo osservabile deve essere maggiore dell’Intervallo minimo osservabile e non può essere maggiore di ${limit} ${units}.",
  "portalURLError": "L'URL dell'organizzazione ArcGIS Online o Portal for ArcGIS non è stato configurato. Verificare insieme all'amministratore del sistema",
  "privilegeError": "Il ruolo utente assegnato non consente di eseguire analisi. Per poter eseguire l'analisi, l'amministratore dell'organizzazione deve concedere all’utente determinati <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilegi</a>.",
  "noServiceError": "Servizio di analisi elevazione non disponibile. Verificare le configurazioni dell’organizzazione ArcGIS Online o di Portal for ArcGIS.",
  "pointToolTooltip": "Fare clic per aggiungere la posizione dell’osservatore",
  "degreesLabel": "gradi",
  "milsLabel": "miglia",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Gradi decimali - Latitudine/Longitudine",
  "DDLongLatNotation": "Gradi decimali - Longitudine/Latitudine",
  "DDMLatLongNotation": "(DDM) Degrees Decimal Minutes - Latitude/Longitude",
  "DDMLongLatNotation": "(DDM) Degrees Decimal Minutes - Longitude/Latitude",
  "DMSLatLongNotation": "(DDS) Degrees Minutes Seconds - Latitude/Longitude",
  "DMSLongLatNotation": "(DDS) Degrees Minutes Seconds - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - Hemisphere (N/S)"
});