define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Tambahkan titik dengan mengklik peta",
  "addRingsDtWt": "Tambahkan cincin, waktu mengemudi, atau waktu berjalan.",
  "apply": "Terapkan",
  "back": "Kembali",
  "colon": ":",
  "creditInformation": "Informasi Kredit",
  "driveTime": "Waktu berkendara",
  "esriInfographics": "Infografi Esri",
  "esriReports": "Laporan Esri",
  "headerDescription_km": "kilometer",
  "headerDescription_miles": "mil",
  "headerDescription_minutes": "menit",
  "infographics": "Infografis",
  "invalidValueRing": "Nilai harus berada dalam rentang 0 hingga 1.000.",
  "invalidValueDTWT": "Nilai harus berada dalam rentang 0 hingga 300.",
  "km": "km",
  "miles": "mil",
  "minutes": "menit",
  "myInfographics": "Infografi Saya",
  "myReports": "Laporan Saya",
  "noPermissions": "Akun Anda tidak bisa menjalankan widget Business Analyst.  Untuk menjalankan widget Business Analyst, administrator organisasi Anda perlu memberi Anda <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">hak akses</a> GeoEnrichment and Network Analysis, dan mengalokasikan <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">kredit</a>.",
  "radii": "radius",
  "radius": "Radius",
  "radius_lowercase": "radius",
  "reports": "Laporan",
  "ring": "Cincin",
  "rings": "Cincin",
  "runInfographic": "Jalankan Infografis",
  "runReport": "Jalankan Laporkan",
  "selectPointOrPolygon": "Pilih fitur Titik atau Poligon di peta, cari alamat atau tempat, atau letakkan pin pada peta untuk menampilkan lebih banyak informasi tentang area tersebut.",
  "selectReport": "Pilih Laporan",
  "selectTemplate": "Pilih Template",
  "sharedInfographics": "Infografis Bersama",
  "sharedReports": "Laporan Bersama",
  "thisEntryIsNotValid": "Entri ini tidak valid.",
  "time": "Waktu",
  "walkTime": "Waktu berjalan",
  "widgetDescription": "Akses Infografis dan Laporan yang merangkum indikator utama dan data untuk berbagai area.",
  "None": "Pilih..."
});