define({
  "_widgetLabel": "Lausaline atribuutide redaktor",
  "widgetIntroSelectByArea": "Kasutage mõnda allolevatest tööriistadest, et luua valitud uuendatavaid objekte. Kui rida on <font class='maxRecordInIntro'>esile tõstetud</font>, on maksimaalne kirjete arv ületatud.",
  "widgetIntroSelectByFeature": "Kasutage allolevat tööriista, et valida objekti kihist <font class='layerInIntro'>${0}</font>. Seda objekti kasutatakse kõikide lõikuvate objektide valimiseks ja värskendamiseks. Kui rida on <font class='maxRecordInIntro'>esile tõstetud</font>, on maksimaalne kirjete arv ületatud.",
  "widgetIntroSelectByFeatureQuery": "Kasutage allolevat tööriista, et valida objekti kihist <font class='layerInIntro'>${0}</font>. Objekti <font class='layerInIntro'>${1}</font> atribuuti kasutatakse allolevate kihtide otsinguks ja sellest tulenevate objektide värskendamiseks. Kui rida on <font class='maxRecordInIntro'>esile tõstetud</font>, on maksimaalne kirjete arv ületatud.",
  "widgetIntroSelectByQuery": "Sisestage väärtus valikute loomiseks. Kui rida on <font class='maxRecordInIntro'>esile tõstetud</font>, on maksimaalne kirjete arv ületatud.",
  "layerTable": {
    "colLabel": "Kihi nimi",
    "numSelected": "#",
    "colSyncStatus": ""
  },
  "noConfiguredLayers": "Muudetavaid kihte pole konfigureeritud",
  "editorPopupTitle": "Lausaline atribuutide redaktor",
  "editorPopupSaveBtn": "Salvesta",
  "editorPopupMultipleValues": "",
  "clear": "Eemalda",
  "featuresUpdated": "${0} / ${1} objekt(i) värskendatud",
  "featuresSelected": "${0} objekt(i) valitud",
  "featuresSkipped": "Eiratakse",
  "search": "Otsi",
  "queryInput": "Sisestage päringu jaoks väärtus",
  "noFilterTip": "Määratlemata filtriavaldiseta loendab see päringuülesanne kõik määratud andmeallika funktsioonid.",
  "setFilterTip": "Määrake filter õigesti.",
  "filterPopup": "Filtreeri kiht",
  "cancel": "Tühista",
  "noValue": "Väärtus puudub",
  "emptyString": "Tühi string",
  "existingValue": "Säilita olemasolev väärtus",
  "newDate": "Uus kuupäev",
  "valueChooser": "Valige või sisestage väärtus",
  "ok": "OK",
  "drawBox": {
    "point": "Punkt",
    "line": "Joon",
    "polyline": "Joon",
    "freehandPolyline": "Vabakäe joon",
    "extent": "Kuvaulatus",
    "polygon": "Polügoon",
    "freehandPolygon": "Vabakäe polügoon",
    "clear": "Eemalda",
    "addPointToolTip": "Klõpsake selles alas valimiseks",
    "addShapeToolTip": "Joonistage kujund objektide valimiseks",
    "freehandToolTip": "Hoidke all, et joonistada kujund objektide valimiseks",
    "startToolTip": "Joonistage kujund objektide valimiseks"
  },
  "errors": {
    "layerNotFound": "Kihti ${0} (ID ${1}) ei leitud kaardilt. Võimalik, et kaarti on pärast vidina konfigureerimist muudetud",
    "queryNullID": "Üksuse ${0} objekt tagastas kehtetu ID",
    "noSelectedLayers": "Värskendatavate kirjetega kihte pole valitud",
    "inputValueError": "Kehtetu väärtus vormis",
    "saveError": "${0} objekti ei saa salvestada. Üksikasjad on lisatud konsoolile",
    "requiredValue": "Nõutav väärtus"
  }
});