define({
  "_widgetLabel": "Απόσταση και κατεύθυνση",
  "tabLineTitle": "Γραμμή",
  "tabCircleTitle": "Κύκλος",
  "tabEllipseTitle": "Έλλειψη",
  "tabRingsTitle": "Δακτύλιοι",
  "multipleNotationsMessage": " σημειογραφίες που αντιστοιχούν στην καταχώρισή σας. Επιβεβαιώστε ποια θέλετε να χρησιμοποιήσετε:",
  "invalidCoordinateMessage": "Μη έγκυρη συντεταγμένη",
  "confirmInputNotationMessage": "Επιβεβαίωση σημειογραφίας εισόδου",
  "prefixSuffixMessage": "Προσδιορίστηκε ότι η συντεταγμένη εισόδου έχει και πρόθεμα και επίθημα για την τιμή γεωγραφικού πλάτους ή γεωγραφικού μήκους. Η συντεταγμένη που επιστρέφεται βασίζεται στο πρόθεμα.",
  "rememberDecisionMessage": "Απομνημόνευση της απόφασής μου και να μην ξαναγίνει ερώτηση.<br/>",
  "majorAxisTooltipMessage": "Κάντε κλικ στο μήκος του κύριου άξονα.",
  "minorAxisTooltipMessage": "Μετακινήστε το ποντίκι για να επιστρέψετε στην αρχική θέση για να καθορίσετε τον ελάσσονα άξονα και να τελειώσετε τη σχεδίαση της έλλειψης.",
  "clickToFinishLineMessage": "Κάντε κλικ για να τελειώσετε τη σχεδίαση της γραμμής.",
  "doubleClickEllipseMesage": "Κάντε διπλό κλικ για να τελειώσετε τη σχεδίαση των δακτυλίων περιοχών.",
  "invalidCoordinateTypeMessage": "Δεν είναι δυνατή η εξακρίβωση του τύπου των συντεταγμένων εισόδου. Ελέγξτε την είσοδό σας.",
  "noCenterPointSetMessage": "Δεν καθορίσατε κεντρικό σημείο. Ελέγξτε την είσοδό σας.",
  "ellipseMajorAxis": "Μείζων άξονας",
  "ellipseMinorAxis": "Ελάσσων άξονας",
  "degreesRangeMessage": "Η τιμή πρέπει να είναι από 0 έως 360.",
  "millsRangeMessage": "Η τιμή πρέπει να είναι από 0 έως 6400.",
  "lengthLabel": "Μήκος",
  "angleLabel": "Γωνία",
  "startPointLabel": "Σημείο εκκίνησης",
  "endPointLabel": "Τελικό σημείο",
  "centerPointLabel": "Κεντρικό σημείο",
  "distanceTableErrorMessage": "Ο πίνακας αποστάσεων είναι κενός. Πρέπει να καταχωρίσετε ορισμένες αποστάσεις.",
  "setCoordFormatStringMessage": "Ορισμός συμβολοσειράς μορφής συντεταγμένης",
  "prefixMessage": "Προσθήκη προθέματος «+/-» σε θετικούς και αρνητικούς αριθμούς",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Βαθμοί σε δεκαδική μορφή - Γεωγραφικό πλάτος/μήκος",
  "DDLongLatNotation": "Βαθμοί σε δεκαδική μορφή - Γεωγραφικό μήκος/πλάτος",
  "DDMLatLongNotation": "Βαθμοί με λεπτά σε δεκαδική μορφή - Γεωγραφικό πλάτος/μήκος",
  "DDMLongLatNotation": "Βαθμοί με λεπτά σε δεκαδική μορφή - Γεωγραφικό μήκος/πλάτος",
  "DMSLatLongNotation": "Βαθμοί με λεπτά και δευτερόλεπτα - Γεωγραφικό πλάτος/μήκος",
  "DMSLongLatNotation": "Βαθμοί με λεπτά και δευτερόλεπτα - Γεωγραφικό μήκος/πλάτος",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Γράμμα ζώνης",
  "UTMHemNotation": "UTM - Ημισφαίριο (Β/Ν)",
  "circleTitle": "Δημιουργία κύκλου από",
  "radiusLabel": "Ακτίνα",
  "diameterLabel": "Διάμετρος",
  "startPointPlaceHolderLabel": "Εισαγάγετε συντεταγμένες",
  "formatInputLabel": "Μορφοποίηση εισόδου",
  "drawCircleLabel": "Σχεδίαση κύκλου",
  "drawLineLabel": "Σχεδίαση γραμμής",
  "createCircleInteractivelyLabel": "Δημιουργία κύκλου διαδραστικά",
  "rangeErrorMessage": "Μη έγκυρη ακτίνα ή διάμετρος",
  "numericInvalidMessage": "Καταχωρίστε αριθμική τιμή.",
  "timeLabel": "Χρόνος",
  "invalidTimeMessage": "Μη έγκυρη τιμή χρόνου",
  "hoursLabel": "Ώρες",
  "minutesLabel": "Λεπτά",
  "secondsLabel": "Δευτερόλεπτα",
  "rateLabel": "Αξιολόγηση",
  "invalidDistanceMessage": "Μη έγκυρη τιμή απόστασης",
  "feetSecondsLabel": "Πόδια/δευτερόλεπτο",
  "feetHourLabel": "Πόδια/ώρα",
  "kmSecondLabel": "Χιλιόμετρα/δευτερόλεπτο",
  "kmHourLabel": "Χιλιόμετρο/ώρα",
  "metersSecondLabel": "Μέτρα/δευτερόλεπτο",
  "metersHourLabel": "Μέτρα/ώρα",
  "milesSecondLabel": "Μίλια/δευτερόλεπτο",
  "milesHourLabel": "Μίλια/ώρα",
  "nauticalMilesSecondLabel": "Ναυτικά μίλια/δευτερόλεπτο",
  "nauticalMilesHourLabel": "Ναυτικά μίλια/ώρα",
  "clearGraphicsLabel": "Απαλοιφή γραφικών",
  "ellipseTypeLabel": "Τύπος έλλειψης",
  "ellipseSemiLabel": "Μισή",
  "ellipseFullLabel": "Πλήρης",
  "drawEllipseLabel": "Σχεδίαση έλλειψης",
  "createEllipseInteractively": "Δημιουργία έλλειψης διαδραστικά",
  "axisLabel": "Άξονας",
  "unitLabel": "Μονάδα",
  "majorRadiusLabel": "Μείζων (Ακτίνα)",
  "majorDiameterLabel": "Κύρια (Διάμετρος)",
  "axisErrorMessage": "Η τιμή πρέπει να είναι μεγαλύτερη από το 0.",
  "minorRadiusLabel": "Ελάσσων (Ακτίνα)",
  "minorDiameterLabel": "Δευτερεύουσα (Διάμετρος)",
  "orientationLabel": "Προσανατολισμός",
  "orientationErrorMessage": "Η τιμή πρέπει να είναι από 0 έως 360.",
  "warningMessage": "Προειδοποίηση: Τα γραφικά που δημιουργούνται μέσω το εργαλείο έλλειψης δεν είναι γεωδαιτικά.",
  "fromLabel": "Από",
  "distanceBearingLabel": "Απόσταση και κίνηση",
  "pointsLabel": "Σημεία",
  "createLineInteractively": "Δημιουργία γραμμής διαδραστικά",
  "lineLengthErrorMessage": "Μη έγκυρο μήκος γραμμής",
  "degreesLabel": "Μοίρες",
  "milsLabel": "Mils",
  "lineTypeLabel": "Τύπος",
  "interactiveLabel": "Διαδραστικά",
  "fixedLabel": "Σταθερό",
  "originLabel": "Προέλευση",
  "cumulativeLabel": "Αθροιστικό",
  "numberOfRingsLabel": "Αριθμός δακτυλίων",
  "ringsErrorMessage": "Μη έγκυρος αριθμός δακτυλίων",
  "distanceBetweenRingsLabel": "Απόσταση μεταξύ δακτυλίων",
  "ringsDecimalErrorMessage": "Καταχωρίστε αριθμική τιμή με έως 2 δεκαδικά ψηφία.",
  "distanceUnitsLabel": "Μονάδες απόστασης",
  "distancesLabel": "Αποστάσεις",
  "numberOfRadialsLabel": "Αριθμός ακτίνων",
  "upLabel": "Πάνω",
  "downLabel": "Κάτω",
  "deleteLabel": "Διαγραφή",
  "radialsErrorMessage": "Μη έγκυρος αριθμός ακτίνων. Ο μέγιστος επιτρεπόμενος αριθμός είναι 360.",
  "radialsInvalidMessage": "Μη έγκυρη τιμή για ακτίνες",
  "addPointLabel": "Προσθήκη σημείου",
  "valueLabel": "Τιμή",
  "valueText": "Καταχωρίστε τιμή.",
  "actionLabel": "Ενέργεια",
  "distanceCalculatorLabel": "Εργαλείο Υπολογισμού Απόστασης",
  "abbrevMetersLabel": "μ.",
  "abbrevFeetLabel": "πόδ.",
  "abbrevKmLabel": "χλμ.",
  "abbrevMilesLabel": "μίλ.",
  "abbrevYardsLabel": "γρδ.",
  "abbrevNauticalMilesLabel": "ν.μ.",
  "abbrevDegreesLabel": "°",
  "abbrevMilsLabel": "μίλ.",
  "abbrevHoursLabel": "ώρα",
  "abbrevMinutesLabel": "λεπ.",
  "abbrevSecondsLabel": "δευτ.",
  "abbrevFeetSecondsLabel": "ποδ./δευτ.",
  "abbrevFeetHourLabel": "ποδ./ώρα",
  "abbrevKmSecondLabel": "χλμ./δευτ.",
  "abbrevKmHourLabel": "χλμ./ώρα",
  "abbrevMetersSecondLabel": "μ./δευτ.",
  "abbrevMetersHourLabel": "μ./ώρα",
  "abbrevMilesSecondLabel": "μίλ./δευτ.",
  "abbrevMilesHourLabel": "μίλ./ώρα",
  "abbrevNauticalMilesSecondLabel": "ν.μ./δευτ.",
  "abbrevNauticalMilesHourLabel": "ν.μ./ώρα",
  "publishDDBtn": "Δημοσίευση",
  "publishTitle": "Δημοσίευση γραφικών",
  "ddLayerName": "Όνομα δημοσιευμένου θεματικού επιπέδου",
  "missingDDLayerName": "Πρέπει να καταχωρίσετε όνομα για το θεματικό επίπεδο.",
  "publishToNewLayer": "Δημοσίευση αποτελεσμάτων σε νέο feature layer",
  "checkService": "Έλεγχος υπηρεσίας: {0}",
  "createService": "Δημιουργία υπηρεσίας: {0}",
  "unableToCreate": "Δεν είναι δυνατή η δημιουργία: {0}",
  "addToDefinition": "Προσθήκη στον ορισμό: {0}",
  "successfullyPublished": "Επιτυχής δημοσίευση θεματικού επιπέδου web{0}Διαχείριση του θεματικού επιπέδου web",
  "userRole": "Δεν είναι δυνατή η δημιουργία υπηρεσίας επειδή ο χρήστης δεν έχει τα ανάλογα δικαιώματα.",
  "missingLayerNameMessage": "Πρέπει να καταχωρίσετε έγκυρο όνομα θεματικού επιπέδου για να μπορέσετε να προχωρήσετε στη δημοσίευση.",
  "invalidLayerName": "Το όνομα του θεματικού επιπέδου πρέπει να περιέχει μόνο αλφαριθμικούς χαρακτήρες και κάτω παύλες.",
  "distanceLabel": "Απόσταση",
  "radiusDistance": "Απόσταση ακτίνας",
  "radials": "Ακτινικές αποστάσεις",
  "rings": "Δακτύλιοι",
  "orientationUnit": "Μονάδα προσανατολισμού",
  "radiusUnit": "Μονάδα μέτρησης ακτίνας",
  "angleUnitLabel": "Μονάδα μέτρησης γωνίας"
});