define({
  "_widgetLabel": "Khả năng hiển thị",
  "observerLocation": "Vị trí của Người quan sát",
  "formatIconTooltip": "Định dạng đầu vào",
  "addPointToolTip": "Thêm Vị trí của Người quan sát",
  "fieldOfView": "Góc nhìn",
  "useMilsText": "Sử dụng mil cho góc",
  "observerHeight": "Chiều cao của Người quan sát",
  "minObsDistance": "Khoảng cách có thể quan sát được tối thiểu",
  "maxObsDistance": "Khoảng cách có thể quan sát được tối đa",
  "taskURLError": "Tệp cấu hình tiện ích có chứa một URL không thể truy cập. Vui lòng kiểm tra với quản trị viên hệ thống của bạn",
  "taskURLInvalid": "Tác vụ địa xử lý được cấu hình với tiện ích này không hợp lệ. Vui lòng kiểm tra với quản trị viên hệ thống của bạn",
  "viewshedError": "Đã xảy ra lỗi khi tạo khả năng hiển thị. Vui lòng chắc chắn rằng vị trí của người quan sát nằm trong phạm vi bề mặt độ cao của bạn.</p>",
  "validationError": "<p>Mẫu tạo khả năng hiển thị bị thiếu thông số hoặc chứa thông số không hợp lệ. Vui lòng đảm bảo:</p><ul><li>Vị trí của người quan sát đã được thiết lập.</li><li>Góc nhìn của người quan sát khác 0.</li><li>Chiều cao của người quan sát chứa giá trị hợp lệ.</li><li>Khoảng cách có thể quan sát được tối thiểu và tối đa chứa giá trị hợp lệ.</li></ul>",
  "comfirmInputNotation": "Xác nhận Ký hiệu đầu vào",
  "notationsMatch": "các ký hiệu khớp với thông tin của bạn. Vui lòng xác nhận ký hiệu bạn muốn sử dụng:",
  "createBtn": "Tạo",
  "clearBtn": "Xóa",
  "setCoordFormat": "Thiết lập chuỗi định dạng tọa độ",
  "prefixNumbers": "Thêm tiền tố '+/-' vào số dương và số âm",
  "parseCoordinatesError": "Không thể dán tọa độ. Vui lòng kiểm tra thông tin của bạn.",
  "cancelBtn": "Hủy",
  "applyBtn": "Áp dụng",
  "invalidMessage": "Vui lòng nhập một giá trị số.",
  "observerRangeMessage": "Chiều cao của Người quan sát không hợp lệ",
  "minimumRangeMessage": "Phạm vi quan sát được tối thiểu không hợp lệ",
  "maximumRangeMessage": "Phạm vi Có thể Quan sát Tối đa phải lớn hơn Phạm vi Có thể Quan sát Tối thiểu và không được vượt quá ${limit} ${units}.",
  "portalURLError": "URL đến tổ chức ArcGIS Online hoặc Portal for ArcGIS của bạn chưa được định cấu hình. Vui lòng kiểm tra với quản trị viên hệ thống của bạn",
  "privilegeError": "Vai trò người dùng của bạn không cho phép thực hiện phân tích. Để thực hiện phân tích, quản trị viên của tổ chức của bạn cần cấp cho bạn một số <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">quyền</a>.",
  "noServiceError": "Dịch vụ phân tích độ cao không khả dụng. Vui lòng kiểm tra cấu hình của tổ chức ArcGIS Online hoặc Portal for ArcGIS của bạn.",
  "pointToolTooltip": "Bấm để thêm vị trí người quan sát",
  "degreesLabel": "độ",
  "milsLabel": "mil",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Độ thập phân - Vĩ độ/Kinh độ",
  "DDLongLatNotation": "Độ thập phân - Kinh độ/Vĩ độ",
  "DDMLatLongNotation": "Độ thập phân phút - Vĩ độ/Kinh độ",
  "DDMLongLatNotation": "Độ thập phân phút - Kinh độ/Vĩ độ",
  "DMSLatLongNotation": "Độ thập phân giây - Vĩ độ/Kinh độ",
  "DMSLongLatNotation": "Độ thập phân giây - Kinh độ/Vĩ độ",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Chữ cái dải sóng",
  "UTMHemNotation": "UTM - Bán cầu (Bắc/Nam)",
  "mainPageTitle": "Đường ảnh Cơ sở Xuyên tâm",
  "resultsTitle": "Kết quả",
  "publishBtnLabel": "Xuất bản",
  "layerName": "Tên Lớp đã Xuất bản",
  "invalidLayerName": "Tên lớp chỉ được chứa các ký tự chữ số và dấu gạch dưới",
  "missingLayerName": "Nhập tên lớp",
  "back": "Quay lại",
  "publishingFailedLayerExists": "Xuất bản không thành công: Bạn đã có dịch vụ đối tượng có tên {0}. Vui lòng chọn tên khác.",
  "checkService": "Kiểm tra Dịch vụ: {0}.",
  "createService": "Tạo Dịch vụ: {0}",
  "unableToCreate": "Không thể tạo: {0}",
  "addToDefinition": "Thêm vào định nghĩa: {0}",
  "successfullyPublished": "Xuất bản lớp web thành công{0}Quản lý lớp web",
  "userRole": "Không thể tạo dịch vụ do người dùng không có đủ quyền",
  "publishToNewLayer": "Xuất bản kết quả đến một lớp đối tượng mới",
  "missingLayerNameMessage": "Bạn phải nhập tên lớp hợp lệ trước khi có thể xuất bản",
  "regionTypeLabel": "Loại Vùng",
  "centerPointLabel": "Tâm Điểm",
  "observationHeightLabel": "Chiều cao Quan sát",
  "heightUnitLabel": "Đơn vị Chiều cao",
  "minObservationDistanceLabel": "Khoảng cách Quan sát Tối thiểu",
  "maxObservationDistance": "Khoảng cách Quan sát Tối đa",
  "distanceUnitLabel": "Đơn vị Khoảng cách",
  "fovstartAngleLabel": "Góc Bắt đầu FOV",
  "fovEndAngleLabel": "Góc Kết thúc FOV",
  "andleUnitsLabel": "Đơn vị Góc"
});