define({
  "_widgetLabel": "दृश्यता",
  "observerLocation": "पर्यवेक्षण का स्थान",
  "formatIconTooltip": "इनपुट का प्रारूप तैयार करिये",
  "addPointToolTip": "प्रेक्षक का स्थान जोड़ें",
  "fieldOfView": "देखा जाने वाला क्षेत्र",
  "useMilsText": "कोणों के लिए मिलों को इस्तेमाल करें",
  "observerHeight": "पर्यवेक्षक की लंबाई",
  "minObsDistance": "पर्यवेक्षित की जाने योग्य न्यूनतम दूरी",
  "maxObsDistance": "पर्यवेक्षित की जाने योग्य अधिकतम दूरी",
  "taskURLError": "विजेट कॉन्फ़िगरेशन फाइल में एक ऐसा URL है, जिस तक पहुँचा नहीं जा सकता। कृपया अपने सिस्टम एडमिनिस्ट्रेटर से संपर्क करें",
  "taskURLInvalid": "इस विजेट के साथ कॉन्फ़िगर किया गया जियोप्रोसेसिंग कार्य वैध नहीं है। कृपया अपने सिस्टम एडमिनिस्ट्रेटर से संपर्क करें",
  "viewshedError": "दृश्यता बनाते समय एक त्रुटि उत्पन्न हुई। कृपया सुनिश्चित करें कि आपका पर्यवेक्षक स्थान आपकी ऊंचाई सतह की सीमा के भीतर आता है।</p>",
  "validationError": "<p>दृश्यता निर्माण प्रपत्र अनुपलब्ध है या पैरामीटर अमान्य हैं, कृपया सुनिश्चित करें:</p><ul><li>पर्यवेक्षण का स्थान सेट कर दिया गया है।</li><li>व्यू का पर्यवेक्षण क्षेत्र o नहीं है।</li><li>पर्यवेक्षक की लंबाई का मान मान्य होता है।</li><li>इस न्यूनतम तथा अधिकतम अवलोकन-योग्य दूरी में वैध मान होते हैं।</li></ul>",
  "comfirmInputNotation": "इनपुट नोटेशन की पुष्टि करें",
  "notationsMatch": "ये नोटेशन आपके इनपुट से मेल खाते हैं, कृपया जिसका आप इस्तेमाल करना चाहते हैं, उसकी पुष्टि करें:",
  "createBtn": "बनाएँ",
  "clearBtn": "हटाएँ",
  "setCoordFormat": "निर्देशांक फ़ॉर्मेट स्ट्रिंग को सेट करें",
  "prefixNumbers": "धनात्मक और ऋणात्मक संख्याओं के आगे '+/-' जोड़ें",
  "parseCoordinatesError": "निर्देशांकों की व्याख्या करने में सक्षम नहीं। कृपया अपना इनपुट जांचें।",
  "cancelBtn": "रद्द करें",
  "applyBtn": "लागू करें",
  "invalidMessage": "कृपया एक संख्यात्मक मान डालें।",
  "observerRangeMessage": "प्रेक्षक की लंबाई अमान्य है",
  "minimumRangeMessage": "अमान्य न्यूनतम अवलोकन सीमा",
  "maximumRangeMessage": "अधिकतम पर्यवेक्षण सीमा न्यूनतम पर्यवेक्षण सीमा से अधिक होनी चाहिए और ${limit} ${units} से अधिक नहीं होनी चाहिए।",
  "portalURLError": "ArcGIS के लिए आपके ArcGIS Online संगठन या पोर्टल का URL कॉन्फ़िगर नहीं किया गया है। कृपया अपने सिस्टम व्यवस्थापक से जांचें।",
  "privilegeError": "आपकी उपयोगकर्ता भूमिका विश्लेषण नहीं कर सकती है। विश्लेषण करने के लिए, आपके संगठन के व्यवस्थापक को आपको कुछ <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">विशेषाधिकार</a> प्रदान करने की आवश्यकता है।",
  "noServiceError": "एलिवेशन विश्लेषण सेवा उपलब्ध नहीं है। ArcGIS कॉन्फ़िगरेशन के लिए कृपया अपने ArcGIS Online संगठन या पोर्टल की जांच करें।",
  "pointToolTooltip": "पर्यवेक्षक स्थान जोड़ने के लिए क्लिक करें",
  "degreesLabel": "अंश",
  "milsLabel": "मील",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "दशमलव डिग्री - अक्षांश/देशांतर",
  "DDLongLatNotation": "दशमलव डिग्री - देशांतर/अक्षांश",
  "DDMLatLongNotation": "दशमलव डिग्री मिनट - अक्षांश/देशांतर",
  "DDMLongLatNotation": "दशमलव डिग्री मिनट - देशांतर/अक्षांश",
  "DMSLatLongNotation": "दशमलव डिग्री सेकंड - देशांतर/अक्षांश",
  "DMSLongLatNotation": "दशमलव डिग्री सेकंड - अक्षांश/देशांतर",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - बैंड लेटर",
  "UTMHemNotation": "UTM - गोलार्ध (N/S)"
});