define(
   ({
    addLayer: "Adicionar Camada",
    layerName: "Camada",
    layerRefresh: "Atualizar",
    layerLabel: "Rótulo",
    actions: "Acções",
    popupOk: "OK",
    popupCancel: "Cancelar",
    mainPanelTextPlaceholder: "ex: CONDIÇÕES DE AUTO-ESTRADA",
    invalidInterval: "Apenas suporta caracteres numéricos.",
    uploadImage: "Carregar Imagem",
    iconColumnText: "Ícone",
    refreshInterval: "1 \'Avaliada como o tempo em Minutos\'",
    refreshIntervalTitle: "Avaliada como o tempo em Minutos",
    mainPanelText: "Texto de Painel Principal",
    mainPanelIcon: "Imagem de Painel Principal",
    refreshIntervalInstruction: "Intervalo de actualização",
    optionsText: "Opções",
    symbolOptionsText: "Opções de Símbolo",
    iconOptionsText: "Opções de Ícone",
    sympolPopupTitle: "´Definir Símbolo",
    rdoLayer: "Símbolo Camada",
    rdoCustom: "Símbolo Personalizado",
    chkCluster: "Permitir Clustering",
    defineClusterSymbol: "Símbolo Cluster",
    defineThemeClusterSymbol: "Símbolo Cluster do Tema",
    rdoEsri: "Símbolo Esri",
    rdoLayerIcon: "Use Símbolo como Ícone",
    rdoCustomIcon: "Actualizar Ícone Personalizado",
    editCustomSymbol: "Editar Símbolo Personalizado",
    editCustomIcon: "Editar Ícone Personalizado",
    missingRefreshValue: "Por favor forneça uma actualização de valor de intervalo.",
    panelIconOption: "Exibir Cabeçalho de Painel",
    enableRefresh: "Permitir Actualização de Camada",
    disableRefresh: "Actualização de Camada Apenas Suportada por Conjuntos de Elemento",
    layer_type_not_supported: "Tipo de camada não suportada: "
  })
);
