define({
  "addLayer": "Adicionar Camada",
  "layerName": "Camada",
  "layerRefresh": "Atualizar",
  "layerLabel": "Rótulo",
  "actions": "Acções",
  "mainPanelTextPlaceholder": "ex: Ùltima Atualização:",
  "invalidInterval": "Apenas suporta caracteres numéricos.",
  "uploadImage": "Carregar Imagem",
  "iconColumnText": "Exibir",
  "refreshInterval": "Tempo em Minutos",
  "refreshIntervalTitle": "Avaliada como o tempo em Minutos",
  "mainPanelText": "Texto de Painel Principal",
  "mainPanelIcon": "Imagem de Painel Principal",
  "refreshIntervalInstruction": "Atualizar camadas a cada:",
  "optionsText": "Opções",
  "symbolOptionsText": "Simbologia do Mapa",
  "iconOptionsText": "Simbologia do Painel",
  "sympolPopupTitle": "Exibir Definições",
  "rdoLayer": "Símbolo Padrão",
  "rdoCustom": "Utilizar uma Imagem",
  "chkCluster": "Permitir Clustering",
  "defineClusterSymbol": "Especificar Símbolo do Cluster",
  "rdoEsri": "Escolher um Símbolo",
  "rdoLayerIcon": "Utilizar Símbolo do Mapa",
  "rdoCustomIcon": "Utilizar uma Imagem",
  "editCustomSymbol": "Editar Símbolo Personalizado",
  "editCustomIcon": "Editar Ícone Personalizado",
  "missingRefreshValue": "Por favor forneça uma actualização de valor de intervalo.",
  "panelIconOption": "Exibir Imagem do Logótipo",
  "enableRefresh": "Permitir Actualização de Camada",
  "disableRefresh": "Actualização de Camada Apenas Suportada por Conjuntos de Elemento",
  "layer_type_not_supported": "Tipo de camada não suportada: ",
  "refreshUnit": "minutos.",
  "symbolOptions": "Símbolo",
  "panelFeatureDisplay": "Painel",
  "chkGroup": "Elementos de Grupo",
  "selectField": "Campo",
  "fieldLabel": "Rótulo",
  "addField": "Adicionar Campo",
  "featureOptionsText": "Opções de Camadas",
  "groupOptionsText": "Opções de Grupos",
  "panelCountOption": "Exibir Contagens de Elementos",
  "rdoStack": "Exibir Nova Linha Por Cada Campo",
  "rdoAppend": "Incluir Campos Numa Linha Única",
  "missingLayerInWebMap": "Nenhuma camada operacional encontrada.",
  "displayClusterCnt": "Exibir Contagem de Elementos",
  "defineClusterFont": "Especificar Cor da Letra",
  "max_records": "Limite máximo do campo atingido"
});