define({
  "settings": "Paramètres",
  "titleSettings": "Paramètres de texte",
  "imageSettings": "Paramètres d'image",
  "backgroundColor": "Couleur d'arrière-plan",
  "alignment": "Alignement",
  "textSize": "Taille de texte",
  "textColor": "Couleur du texte",
  "dataSource": "Source de données",
  "chartSettings": "Paramètres de diagramme",
  "data": "Données",
  "dataLabels": "Etiquettes de données",
  "displayMode": "Mode Affichage",
  "featureOption": "Afficher les valeurs entité par entité",
  "categoryOption": "Afficher les valeurs par catégorie",
  "countOption": "Afficher le nombre d’entités par catégorie",
  "fieldOption": "Afficher les valeurs attributaires sous forme de diagrammes",
  "categoryField": "Champ de catégorie",
  "labelField": "Champ d’étiquette",
  "valueFields": "Champs de valeur",
  "operation": "Opération",
  "sumOption": "Somme",
  "averageOption": "Moyenne",
  "minOption": "Minimal",
  "maxOption": "Maximal",
  "dataFormat": "Format des données",
  "decimalPlaces": "Décimales",
  "prefix": "Préfixe",
  "suffix": "Suffixe",
  "dataType": "Type de données",
  "featureCount": "Nombre d'entités",
  "fieldStatistics": "Statistiques du champ",
  "display": "Affichage",
  "chartColor": "Couleur du diagramme",
  "horizontalAxis": "Axe horizontal",
  "verticalAxis": "Axe vertical",
  "legend": "Légende",
  "position": "Position",
  "top": "Haut",
  "bottom": "Bas",
  "useDataSourceSelection": "Utiliser la sélection",
  "dataSourceFilterByExtent": "Filtrer selon l'étendue",
  "changeTemplate": "Changer de modèle",
  "numberSettings": "Paramètres de numérotation",
  "gaugeSettings": "Paramètres de jauge",
  "indicators": "Indicateurs",
  "ifValue": "Si la valeur",
  "and": "et",
  "numberOperatorIsLessThan": "est inférieur à",
  "numberOperatorIsGreaterThan": "est supérieur à",
  "numberOperatorIsBetween": "est entre",
  "numberOperatorIsEqual": "est égal à",
  "numberOperatorIsNotEqual": "est différent de",
  "then": "Avant",
  "ratio": "Ratio",
  "trueValue": "Valeur true",
  "changeValueColor": "remplacer la couleur de valeur par",
  "changeGaugeColor": "remplacer la couleur de jauge par",
  "setIndicatorIcon": "définir l'icône de l'indicateur comme",
  "icons": "Icônes",
  "style": "Style",
  "placement": "Placement",
  "left": "Gauche",
  "replace": "Remplacer",
  "right": "Droite",
  "color": "Couleur",
  "sortBy": "Trier par",
  "labelAxis": "Etiquette",
  "valueAxis": "Valeur",
  "minPeriod": "Période minimale",
  "automatic": "Automatique",
  "periodsWithOutRecords": "Périodes sans enregistrements",
  "nullValue": "Valeur nulle",
  "calculatedAsZero": "Calculé(e) comme zéro",
  "ignored": "Ignoré",
  "maxCategories": "Catégories maximum",
  "useLayerSymbology": "Utiliser la symbologie de la couche",
  "dataRange": "Plage de données",
  "targetValue": "Valeur cible",
  "currentValue": "Valeur actuelle",
  "gaugeColor": "Couleur de jauge",
  "min": "Minimal",
  "max": "Maximal",
  "displayValueIn": "Afficher la valeur dans",
  "noData": "Aucune donnée",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "V",
  "billionAbbreviation": "V",
  "warning": "Avertissement",
  "noSettingWaring1": "Cliquez sur un élément pour en définir les propriétés.",
  "noSettingWaring2": "Faites glisser pour redimensionner ou réorganiser un élément.",
  "donNotShowAgain": "Ne plus afficher",
  "changeTemplateWarning": "Cette action va effacer l'ensemble de vos paramètres et ouvrir un nouveau modèle vide.",
  "requiredFieldWarning": "Cette valeur est obligatoire :",
  "dataSourceNotSet": "Définissez une source de données.",
  "addIndicatorTip": "Ajouter un indicateur",
  "chooseTemplatePopupTitle": "Choisir un modèle",
  "stringsInTemplate": {
    "name_number": "Nombre",
    "name_gauge": "Jauge",
    "name_vertical_gauge": "Jauge verticale",
    "name_horizontal_gauge": "Jauge horizontale",
    "name_pie_chart": "Diagramme à secteurs",
    "name_column_chart": "Diagramme à colonnes",
    "name_bar_chart": "Diagramme à barres",
    "name_line_chart": "Diagramme linéaire",
    "titleOfTheInfographic": "TITLE OF THE INFOGRAPHIC",
    "description": "Description : informations supplémentaires sur cette infographie."
  }
});