define({
  "serviceUrl": "Indstil tjeneste-URL:",
  "minIntSpacingLabel": "Minimal intervalafstand",
  "lineOpacityLabel": "Linje-gennemsigtighed",
  "labelOpacityLabel": "Etiket-gennemsigtighed",
  "centerLabelOpacityLabel": "Central etikets gennemsigtighed",
  "gridZonePlacementLabel": "Placering af gitterzoneetiket",
  "verticalLineLabels": "Vertikale linjeetiketter",
  "styleHeaderLabel": "Type",
  "indexHeaderLabel": "Indeks",
  "colorHeaderLabel": "Farve",
  "fontSizeHeaderLabel": "Skriftstørrelse",
  "lineWidthHeaderLabel": "Linjebredde",
  "horizontalLabel": "Vandret",
  "verticalLabel": "Lodret",
  "upperLeftLabel": "Øverst til venstre",
  "upperRightLabel": "Øverst til højre",
  "lowerLeftLabel": "Nederst til venstre",
  "lowerRightLabel": "Nederst til højre",
  "centerLabel": "Midt",
  "errorMessage": "Konfigurationssiden indeholder fejl. Ret dem, før du gemmer.",
  "checkBoxLabel": "Vis gitter, når widget lukkes"
});