define({
  "_widgetLabel": "Nutikas redaktor",
  "_featureAction_SmartEditor": "Nutikas redaktor",
  "noEditPrivileges": "Teie kontol puudub andmete loomise või muutmise õigus.",
  "widgetActive": "Aktiivne",
  "widgetNotActive": "Pole aktiivne",
  "pressStr": "Snäppimise võimaldamiseks ",
  "ctrlStr": " vajutage ",
  "snapStr": " CTRL",
  "noAvailableTempaltes": "Ühtki malli pole saadaval",
  "editorCache": " - redaktori vahemälu",
  "presetFieldAlias": "Väli",
  "presetValue": "Eelseatud väärtus",
  "usePresetValues": " Kasuta eelseatud väärtusi (ainult uute objektide korral)",
  "editGeometry": " Muuda geomeetriat",
  "savePromptTitle": "Salvesta objekt",
  "savePrompt": "Kas soovite salvestada praeguse objekti?",
  "deletePromptTitle": "Kustuta objekt",
  "deletePrompt": "Kas soovite kindlasti kustutada valitud objekti?",
  "attachmentLoadingError": "Tõrge manuste üleslaadimisel",
  "attachmentSaveDeleteWarning": "Hoiatus: manuste muudatused salvestatakse automaatselt",
  "autoSaveEdits": "Uus objekt salvestatakse automaatselt",
  "addNewFeature": "Loo uus objekt",
  "featureCreationFailedMsg": "Uut kirjet/objekti ei saa luua",
  "relatedItemTitle": "Seotud tabel/kiht",
  "invalidRelationShipMsg": "Veenduge, et primaarvõtme väljal „${parentKeyField}“ oleks sobiv väärtus.",
  "pendingFeatureSaveMsg": "Enne seotud objekti loomist salvestage objekti osas tehtud muudatused.",
  "attachmentsRequiredMsg": "(*) Manused on nõutavad.",
  "coordinatePopupTitle": "Teisalda objekt XY-asukohta",
  "coordinatesSelectTitle": "Koordinaatsüsteem:",
  "mapSpecialReferenceDropdownOption": "Kaardi koordinaatsüsteem",
  "latLongDropdownOption": "Laius/Pikkus",
  "xAttributeTextBoxLabel": "X-koordinaat:",
  "yAttributeTextBoxLabel": "Y-koordinaat:",
  "latitudeTextBoxLabel": "Laiuskraad:",
  "longitudeTextBoxLabel": "Pikkuskraad:",
  "filterEditor": {
    "all": "Kõik",
    "noAvailableTempaltes": "Ühtki malli pole saadaval",
    "searchTemplates": "Otsingumallid"
  },
  "invalidConfiguration": "Vidin on konfigureerimata või pole konfiguratsioonis sisalduvad kihid enam kaardil. Avage rakendus koostajarežiimis ja konfigureerige vidin uuesti.",
  "geometryServiceURLNotFoundMSG": "Geomeetriateenuse URL-i ei saa tuua",
  "clearSelection": "Tühjenda",
  "refreshAttributes": "Uuenda objekti atribuute",
  "automaticAttributeUpdatesOn": "Uuenda objekti atribuudid automaatselt: SEES",
  "automaticAttributeUpdatesOff": "Uuenda objekti atribuudid automaatselt: VÄLJAS",
  "moveSelectedFeatureToGPS": "Teisalda valitud objekt praegusesse GPS-i asukohta",
  "moveSelectedFeatureToXY": "Teisalda valitud objekt XY-asukohta",
  "mapNavigationLocked": "Kaardil navigeerimine: lukustatud",
  "mapNavigationUnLocked": "Kaardil navigeerimine: lukustamata"
});