define({
  "feedbackStyleLabel": "Stil de reacție privind distanța și direcția",
  "showTabLabel": "Prezintă filă",
  "feedbackShapeLabel": "Formă de reacție",
  "lineColorLabel": "Culoare linie",
  "lineWidthLabel": "Grosime linie",
  "feedbackLabel": "Etichetă feedback",
  "textColorLabel": "Culoare text",
  "textSizeLabel": "Dimensiune text",
  "tabErrorMessage": "Widget-ul trebuie configurat cu cel puțin o filă prezentată",
  "lineLabel": "Linie",
  "circleLabel": "Cerc",
  "ellipseLabel": "Elipsă",
  "ringsLabel": "Inele",
  "transparency": "Transparență",
  "ddFeedbackStyleTabLabel": "Simbologie",
  "miscellaneousTabLabel": "Diverse",
  "operationalLineLayerSelectLabel": "Selectați un strat tematic operațional de linii poligonale pentru rezultatele de linii și inele",
  "operationalPolygonLayerSelectLabel": "Selectați un strat tematic operațional de poligoane pentru rezultatele de cercuri și elipse",
  "helpIconPolylineTooltip": "Lista cu straturi tematice operaționale este populată cu straturi tematice din harta web actuală, care au o geometrie de tip linie poligonală.",
  "helpIconPolygonTooltip": "Lista cu straturi tematice operaționale este populată cu straturi tematice din harta web actuală, care au o geometrie de tip poligon."
});