define({
  "showArcgisBasemaps": "Kaasa portaali aluskaardid",
  "add": "Klikkige uue aluskaardi lisamiseks",
  "edit": "Omadused",
  "titlePH": "Aluskaardi pealkiri",
  "thumbnailHint": "Uuendamiseks klõpsake pilti",
  "urlPH": "Kihi URL",
  "addlayer": "Lisa aluskaart",
  "warning": "Vale sisend",
  "save": "Tagasi ja salvesta",
  "back": "Tagasi ja tühista",
  "addUrl": "Lisa URL",
  "autoCheck": "Automaatne kontroll",
  "checking": "Kontrollimine...",
  "result": "Salvestamine õnnestus",
  "spError": "Kõigil galeriisse lisatud aluskaartidel peab olema samasugune koordinaatsüsteem.",
  "invalidTitle1": "Aluskaart nimega '",
  "invalidTitle2": "' on juba olemas. Valige uus pealkiri.",
  "invalidBasemapUrl1": "Seda tüüpi kihti ei saa kasutada aluskaardina.",
  "invalidBasemapUrl2": "Lisatav aluskaart kasutab praegusest kaardist erinevat koordinaatsüsteemi.",
  "addBaselayer": "Lisa aluskaardi kiht"
});