define({
  "tabs_section_Label": "Schede",
  "addTab": "Aggiungi scheda",
  "layerName": "Layer",
  "layerType": "Tipo di analisi",
  "layerLabel": "Etichetta",
  "actions": "Azioni",
  "closest": "Feature più vicina",
  "proximity": "Prossimità",
  "summary": "Riepilogo",
  "select_lbl": "-- Seleziona --",
  "general_setting_Label": "Impostazioni generali",
  "units_text_lbl": "Unità di distanza",
  "maximum_distance_lbl": "Distanza massima della feature più vicina",
  "buffer_text_lbl": "Etichetta del buffer",
  "buffer_lbl": "Distanza di buffer",
  "buffer_max_lbl": "Distanza massima del buffer",
  "buffer_min_lbl": "Distanza minima del buffer",
  "routing_checkBox": "Abilita itinerario",
  "weather_Label": "Opzioni meteo",
  "weather_checkBox": "Includi informazioni meteo",
  "selectLayers": "seleziona layer meteo",
  "currentlySelectedLayer": "Layer meteo attualmente selezionati",
  "missingTabLabel": "Manca l'etichetta ad almeno una scheda",
  "missingLayerInWebMap": "Nessun layer operativo trovato.",
  "selectFields": "Seleziona campi",
  "addField": "Aggiungi Campo",
  "sum": "Somma",
  "min": "Minima",
  "max": "Massima",
  "avg": "Mediocre",
  "count": "COUNT",
  "area": "AREA",
  "length": "LENGTH",
  "count_checkBox": "Visualizza conteggio feature",
  "area_checkBox": "Visualizza somma dell'area",
  "length_checkBox": "Visualizza somma della lunghezza",
  "max_records": "Raggiunto limite massimo",
  "save_label": "Salva opzioni",
  "save_checkbox": "Abilita salvataggio",
  "csv_label": "Opzioni CSV",
  "csv_checkbox": "Esporta tutti i campi del layer",
  "display_label": "Opzioni di visualizzazione",
  "display_checkbox": "Visualizza feature di riepilogo",
  "snapshot_label": "Opzioni snapshot",
  "snapshot_checkbox": "Abilita snapshot",
  "must_select_template": "Selezionare uno dei modelli di modifica nelle opzioni di salvataggio.",
  "count_label": "Etichetta conteggio",
  "area_label": "Etichetta area",
  "length_label": "Etichetta lunghezza",
  "invalid_string_width": "Il valore è troppo lungo. ",
  "layer_type_not_supported": "Il tipo di layer non è supportato: ",
  "groupedSummary": "Conteggi raggruppati",
  "groupByField": "Raggruppa per campo",
  "labelType": "Aggiungi etichetta",
  "prefix": "Come prefisso",
  "suffix": "Come suffisso",
  "need_group_field": "Utilizzare l'azione di modifica per definire un Gruppo per campo.",
  "fieldTitle": "Campo",
  "typeTitle": "Tipo",
  "actionsTitle": "Azioni",
  "save_point_checkbox": "Salva punti",
  "save_line_checkbox": "Salva linee",
  "save_poly_checkbox": "Salva poligoni",
  "no_valid_popup_fields": "Nessun campo valido nel popup. Utilizzare l'azione di modifica per definire un campo.",
  "no_valid_fields": "Nessun campo valido. Utilizzare l'azione di modifica per definire opzioni di visualizzazione.",
  "incident_label": "Etichetta scheda",
  "locate_incident_label": "Etichetta Area di interesse",
  "incident": "Richiesta di assistenza",
  "locate_incident": "Individua incidente",
  "buffer_value": "Distanza di buffer"
});