define({
  "transparencyLabel": "Transparență",
  "outline": "Contur",
  "fill": "Umplere (culoarea se aplică doar când stilul este setat la continuu)",
  "style": "Stil",
  "mandatoryLabel": "Distanță obligatorie de evacuare",
  "mandatoryButtonLabel": "Configurare setări distanță obligatorie de evacuare",
  "safeLabel": "Distanță sigură de evacuare",
  "safeButtonLabel": "Configurare setări distanță sigură de evacuare",
  "selectOpLayerLabel": "Selectați un strat tematic operațional pentru rezultate",
  "selectDefaultMeasurementLabel": "Selectați o unitate de măsură implicită",
  "helpIconTooltip": "Lista cu straturi tematice operaționale este populată cu straturi tematice din harta web actuală, care au o geometrie de tip poligon.",
  "lineStyles": {
    "esriSLSDash": "Linie",
    "esriSLSDashDot": "Linie punct",
    "esriSLSDashDotDot": "Linie punct punct",
    "esriSLSDot": "Punct",
    "esriSLSLongDash": "Linie lungă",
    "esriSLSLongDashDot": "Linie lungă punct",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Linie scurtă",
    "esriSLSShortDashDot": "Linie scurtă punct",
    "esriSLSShortDashDotDot": "Linie scurtă punct punct",
    "esriSLSShortDot": "Punct scurt",
    "esriSLSSolid": "Continuu"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Înapoi",
    "esriSFSCross": "Cruce",
    "esriSFSDiagonalCross": "Diagonală",
    "esriSFSForwardDiagonal": "Înainte",
    "esriSFSHorizontal": "Orizontală",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Continuu",
    "esriSFSVertical": "Verticală"
  },
  "threatTypeLabel": "Tip de amenințare",
  "symbologyLabel": "Simbologie",
  "generalLabel": "General",
  "addThreatTypesLabel": "Adăugare tip de amenințare",
  "threatTypeColLabel": "Tip de amenințare",
  "actions": "Acțiuni",
  "newThreatTypePopupLabel": "Tip de amenințare nou",
  "chooseDefaultThreatTypeIconLabel": "Alegeți din valorile implicite",
  "mandatoryDistance": "Distanță obligatorie de evacuare",
  "safeDistance": "Distanță sigură de evacuare",
  "units": "Unități",
  "chooseDefaultThreatLabel": "Selectați un tip de amenințare implicit",
  "defaultThreatTypePopUpLabel": "Tipuri de amenințare Implicite",
  "editThreatLabel": "Editare amenințare",
  "defaultThreatTypeIconTooltip": "Listă cu tipuri de amenințare implicite",
  "uniqueThreatTypeMsg": "Introduceți un tip de amenințare unic, există deja un tip de amenințare cu acest nume.",
  "requiredThreatTypeMsg": "Acest câmp este obligatoriu",
  "unitMeasureLabel": "Distanțele sunt în {0}",
  "pipeBombLabel": "Bombă artizanală",
  "suicideBombLabel": "Sinucigaș cu bombă",
  "briefcaseLabel": "Servietă",
  "carLabel": "Autoturism",
  "suvVanLabel": "SUV/camionetă",
  "smallDeliveryTruckLabel": "Camion de livrare de mici dimensiuni",
  "containerWaterTruckLabel": "Container/cisternă",
  "semiTrailerLabel": "Semiremorcă"
});