define({
  "_widgetLabel": "Ίχνος δικτύου",
  "_featureAction_NetworkTraceSkip": "Παράλειψη στην ιχνηλάτηση",
  "_featureAction_NetworkTraceUnskip": "Κατάργηση από τις τοποθεσίες προς παράλειψη",
  "removedFromSkipLocations": "Επιτυχής κατάργηση από τις τοποθεσίες προς παράλειψη",
  "alreadyRemovedFromSkipLocations": "Ήδη καταργημένη από τις τοποθεσίες προς παράλειψη",
  "locationSkipped": "Επιτυχής παράλειψη τοποθεσίας",
  "configError": "Το widget είναι παραμετροποιημένο όπως πρέπει.",
  "geometryServiceURLNotFoundMSG": "Δεν είναι δυνατή η λήψη της διεύθυνσης URL του geometry service.",
  "clearButtonValue": "Απαλοιφή",
  "GPExecutionFailed": "Το ίχνος δεν μπορεί να ολοκληρωθεί. Προσπαθήστε ξανά.",
  "backButtonValue": "Πίσω",
  "exportToCSVSuccess": "Η εξαγωγή σε CSV ολοκληρώθηκε με επιτυχία.",
  "lblInputLocTab": "Καταχώριση τοποθεσιών",
  "lblBlockLocTab": "Αποκλεισμός τοποθεσιών",
  "lblInputLocation": "Καταχώριση στοιχείου",
  "lblBlockLocation": "Αποκλεισμός στοιχείου",
  "lblInputLocHeader": "Καταχώριση τοποθεσιών (0)",
  "lblBlockLocHeader": "Αποκλεισμός τοποθεσιών (0)",
  "inputTabTitle": "Είσοδος",
  "outputTabTitle": "Έξοδος",
  "exportSelectAllCheckBoxLabel": "Επιλογή όλων",
  "lblSkipLocHeader": "Παράλειψη τοποθεσιών (0)",
  "lblSkipLocation": "Τοποθεσία",
  "lblSkipLocTab": "Παράλειψη τοποθεσιών",
  "skipAllLocationButtonLabel": "Παράλειψη όλων των τοποθεσιών",
  "confirmSkipAllLocationsMessage": "Θα παραλειφθούν όλες οι τοποθεσίες. Θέλετε να συνεχίσετε;",
  "locationAlreadySkippedMessage": "Η τοποθεσία έχει ήδη παραλειφθεί.",
  "removeAllSkipLocationLabel": "Κατάργηση όλων",
  "newProjectOptionText": "Νέο έργο",
  "selectProject": "Επιλογή έργου",
  "saveButtonLabel": "Αποθήκευση",
  "exportToCSVText": "Εξαγωγή σε CSV",
  "editProjectAttributesToolTip": "Επεξεργασία γνωρισμάτων έργου",
  "projectNameLabel": "Όνομα έργου",
  "saveProjectPopupTitle": "Αποθήκευση",
  "saveAsLabel": "Αποθήκευση ως",
  "saveChangesMsg": "Θέλετε να αποθηκευτούν οι αλλαγές στας στο έργο <b>${loadProjectDropdownlabel}</b> ή να αποθηκευτούν ως νέο έργο;",
  "creatingNewProjectErrorMessage": "Σφάλμα κατά τη δημιουργία νέου έργου. Προσπαθήστε ξανά.",
  "projectNameFetchingErr": "Σφάλμα κατά τη λήψη των ονομάτων υπαρχόντων έργων. Προσπαθήστε ξανά.",
  "projectAttributeLoadingErr": "Σφάλμα κατά τη φόρτωση των γνωρισμάτων του έργου. Προσπαθήστε ξανά.",
  "attributeUpdatedMsg": "Η ενημέρωση των γνωρισμάτων ολοκληρώθηκε με επιτυχία.",
  "projectAttributeUpdatingErr": "Σφάλμα κατά τη ενημέρωση των γνωρισμάτων του έργου.",
  "loadingProjectDetailsErrorMessage": "Σφάλμα κατά τη λήψη σημαιών, φραγμάτων και παράλειψης τοποθεσιών. Προσπαθήστε ξανά.",
  "savingProjectDetailsErr": "Σφάλμα κατά την αποθήκευση των αναλυτικών στοιχείων του έργου. Προσπαθήστε να αποθηκεύσετε το έργο ξανά.",
  "updatingOutagePolygonErr": "Σφάλμα κατά την ενημέρωση του πολυγώνου μη διαθεσιμότητας. Προσπαθήστε να αποθηκεύσετε το έργο ξανά.",
  "deletingExistingPolygonErr": "Σφάλμα κατά τη διαγραφή του υπάρχοντος πολυγώνου μη διαθεσιμότητας. Προσπαθήστε να αποθηκεύσετε το έργο ξανά.",
  "loadingProjectFeaturesErr": "Σφάλμα κατά τη φόρτωση των στοιχείων του έργου. Προσπαθήστε να φορτώσετε το έργο ξανά.",
  "addingProjectFeaturesErr": "Σφάλμα κατά τη προσθήκη στοιχείων του έργου. Προσπαθήστε να αποθηκεύσετε το έργο ξανά.",
  "deletingExistingProjectFeaturesErr": "Σφάλμα κατά τη διαγραφή υπαρχόντων στοιχείων του έργου. Προσπαθήστε να αποθηκεύσετε το έργο ξανά.",
  "projectNotFoundErr": "Το έργο δεν βρέθηκε.",
  "projectLayersNotFound": "Τα παραμετροποιημένα θεματικά επίπεδα των ρυθμίσεων του έργου δεν είναι διαθέσιμα στον χάρτη. Το widget θα φορτωθεί στη 'Λειτουργία σκαριφήματος'.",
  "fetchingOutagePolygonMessage": "Σφάλμα κατά τη λήψη του πολυγώνου μη διαθεσιμότητας. Προσπαθήστε να φορτώσετε το έργο ξανά.",
  "projectNameExistsMessage": "Το όνομα του έργου ήδη υπάρχει. Χρησιμοποιήστε μοναδικό όνομα έργου.",
  "fetchingProjectNamesErrorMessage": "Σφάλμα κατά τη λήψη των ονομάτων υπαρχόντων έργων. Προσπαθήστε να αποθηκεύσετε το έργο ξανά.",
  "enterProjectNameMessage": "Καταχωρίστε το όνομα του έργου.",
  "projectLengthErrorMessage": "Το όνομα του έργου δεν μπορεί να είναι μεγαλύτερο από",
  "gpServiceNotAccessible": "Ο λογαριασμός σας δεν έχει δικαίωμα πρόσβασης στην απαιτούμενη υπηρεσία για να εκτελέσει το ίχνος αυτό.",
  "loadingClonedLayerErrorMessage": "Σφάλμα κατά τη φόρτωση του κλωνοποιημένου feature layer. Προσπαθήστε ξανά.",
  "addingFeatureInClonedLayerError": "Σφάλμα κατά την προσθήκη των γραφικών στο κλωνοποιημένο feature layer. Προσπαθήστε ξανά.",
  "selectingFeatureInClonedLayerError": "Σφάλμα κατά την επιλογή των γραφικών στο κλωνοποιημένο feature layer. Προσπαθήστε ξανά.",
  "filteredProjectError": "Σφάλμα κατά τον έλεγχο των αναλυτικών στοιχείων λήψης του φιλτραρισμένου έργου. Προσπαθήστε ξανά.",
  "filteredProjectMessage": "Τα γνωρίσματα του επιλεγμένου έργου δεν είναι διαθέσιμα λόγω των εφαρμοσμένων φίλτρων από τον web χάρτη ή από κάποιο άλλο widget. Απαλείψτε τα φίλτρα και προσπαθήστε ξανά.",
  "filteredProjectLoadMessage": "Το έργο σας δεν είναι πλέον διαθέσιμο. Επιλέξτε ένα ενεργό έργο.",
  "defaultValueForRunButton": "Εκτέλεση",
  "closeButtonLabel": "Κατάργηση"
});