define({
  "feedbackStyleLabel": "Attāluma un virziena atsauksmju stils",
  "showTabLabel": "Rādīt cilni",
  "feedbackShapeLabel": "Atsauksmju forma",
  "lineColorLabel": "Līnijas krāsa",
  "lineWidthLabel": "Līnijas platums",
  "feedbackLabel": "Atsauksmes nosaukums",
  "textColorLabel": "Teksta krāsa",
  "textSizeLabel": "Teksta lielums",
  "tabErrorMessage": "Logrīkam jābūt konfigurētam ar vismaz vienu redzamu cilni",
  "lineLabel": "Līnija",
  "circleLabel": "Aplis",
  "ellipseLabel": "Elipse",
  "ringsLabel": "Riņķi",
  "transparency": "Caurspīdīgums",
  "ddFeedbackStyleTabLabel": "Simbolizācija",
  "miscellaneousTabLabel": "Dažādi",
  "operationalLineLayerSelectLabel": "Izvēlieties lauztas līnijas darbību slāni līniju un apļu rezultātiem",
  "operationalPolygonLayerSelectLabel": "Izvēlieties daudzstūra darbību slāni apļu un elipšu rezultātiem",
  "helpIconPolylineTooltip": "Darbību slāņu saraksts ir aizpildīts ar pašreizējās tīmekļa kartes slāņiem, kuriem ir lauztas līnijas ģeometrijas veids.",
  "helpIconPolygonTooltip": "Darbību slāņu saraksts ir aizpildīts ar pašreizējās tīmekļa kartes slāņiem, kuriem ir daudzstūra ģeometrijas veids."
});