define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Aggiungere il punto facendo clic sulla mappa",
  "addRingsDtWt": "Aggiungere anello, tempo di guida o tempo di camminata.",
  "apply": "Applica",
  "back": "Indietro",
  "colon": ":",
  "creditInformation": "Informazioni di credito",
  "driveTime": "Tempo di guida",
  "esriInfographics": "Infografica Esri",
  "esriReports": "Report Esri",
  "headerDescription_km": "chilometro",
  "headerDescription_miles": "miglia",
  "headerDescription_minutes": "minuto",
  "infographics": "Infografica",
  "invalidValueRing": "Il valore deve essere compreso tra 0 e 1000.",
  "invalidValueDTWT": "Il valore deve essere compreso tra 0 e 300.",
  "km": "km",
  "miles": "miglia",
  "minutes": "minuti",
  "myInfographics": "La mia infografica",
  "myReports": "I miei report",
  "noPermissions": "L’account non può eseguire il widget Business Analyst. Per eseguire il widget Business Analyst, l'amministratore dell’organizzazione deve concedere <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilegi</a> GeoEnrichment e Network Analysis e anche stanziare <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">crediti</a>.",
  "geServiceNotConfigured": "Il widget Business Analyst non può essere eseguito su questo portale, perché non presenta il servizio <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenrichment</a> configurato.",
  "dirRoutingServiceNotConfigured": "Il widget Business Analyst non può essere eseguito su questo portale, perché non presenta il servizio <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Indicazioni e routing</a> configurato.",
  "geAndDirRoutingServicesNotConfigured": "Il widget Business Analyst non può essere eseguito su questo portale, perché non presenta i servizi <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenrichment</a> e <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Indicazioni e routing</a> configurati.",
  "radii": "raggi",
  "radius": "Raggio",
  "radius_lowercase": "raggio",
  "reports": "Report",
  "ring": "Anello",
  "rings": "Anelli",
  "runInfographic": "Eseguire infografica",
  "runReport": "Esegui report",
  "selectPointOrPolygon": "Selezionare una feature puntuale o Poligonale sulla mappa, cercare un indirizzo o luogo o rilasciare una puntina sulla mappa per visualizzare ulteriori informazioni per le aree.",
  "selectReport": "Seleziona report",
  "selectTemplate": "Seleziona modello",
  "sharedInfographics": "Infografiche condivise",
  "sharedReports": "Report condivisi",
  "thisEntryIsNotValid": "Voce non valida.",
  "time": "Tempo",
  "walkTime": "Tempo di camminata",
  "widgetDescription": "Accedere a infografiche e report che riepilogano indicatori e dati chiave per qualsiasi area.",
  "None": "Seleziona..."
});