define({
  "_widgetLabel": "Dibuixa",
  "selectDrawMode": "Selecciona el mode de dibuix",
  "clear": "Esborra",
  "point": "Punt",
  "line": "Línia",
  "polyline": "Polilínia",
  "freehandPolyline": "Polilínia a mà alçada",
  "triangle": "Triangle",
  "extent": "Contorn",
  "circle": "Cercle",
  "ellipse": "El·lipse",
  "polygon": "Polígon",
  "freehandPolygon": "Polígon a mà alçada",
  "text": "Text",
  "style": "Estil",
  "alpha": "Transparència",
  "width": "Amplada",
  "size": "Mida",
  "color": "Color",
  "markerColor": "Color de marcador",
  "outlineColor": "Color del contorn",
  "lineColor": "Color de línia",
  "fillColor": "Color d'emplenament",
  "showMeasurements": "Mostra les mesures",
  "showLocationMeasurement": "Mostra la mesura d'ubicació",
  "showAreaMeasurement": "Mostra la mesura d'àrea",
  "showDistanceMeasurement": "Mostra la mesura de distància",
  "areaUnits": "Unitats d'àrea",
  "distanceUnits": "Unitats de distància",
  "kilometers": "Quilòmetres",
  "miles": "Milles",
  "meters": "Metres",
  "feet": "Peus",
  "yards": "Iardes",
  "nauticalmiles": "Milles nàutiques",
  "squareKilometers": "Quilòmetres quadrats",
  "squareMiles": "Milles quadrades",
  "acres": "Acres",
  "hectares": "Hectàrees",
  "squareMeters": "Metres quadrats",
  "squareFeet": "Peus quadrats",
  "squareYards": "Iardes quadrades",
  "undo": "Desfés",
  "redo": "Refés",
  "results": "Resultats",
  "points": "Punts",
  "lines": "Línies",
  "areas": "Àrees",
  "locationLabel": "Ubicació: ${value}",
  "areaLabel": "Àrea: ${value} ${unit}",
  "distanceLabel": "Distància: ${value} ${unit}"
});