define({
  "_widgetLabel": "Afstand og retning",
  "tabLineTitle": "Linje",
  "tabCircleTitle": "Cirkel",
  "tabEllipseTitle": "Ellipse",
  "tabRingsTitle": "Ringe",
  "multipleNotationsMessage": " notationer, der matcher dit input. Bekræft, hvilken du vil bruge:",
  "invalidCoordinateMessage": "Ugyldig koordinat",
  "confirmInputNotationMessage": "Bekræft input-notation",
  "prefixSuffixMessage": "Input-koordinaten er blevet registreret med både et præfiks og et suffiks for bredde- længdegradsværdien; den returnerede koordinat er baseret på præfikset.",
  "rememberDecisionMessage": "Husk min beslutning, og spørg ikke igen.<br/>",
  "majorAxisTooltipMessage": "Klik på længden af storaksen",
  "minorAxisTooltipMessage": "Flyt musen tilbage til startpositionen for at angive lille akse og afslutte tegningen af ellipse",
  "clickToFinishLineMessage": "Klik for at afslutte tegning af linje",
  "doubleClickEllipseMesage": "Dobbeltklik for at afslutte tegning af afstandsringe",
  "invalidCoordinateTypeMessage": "Kan ikke fastlægge typen af inputkordinater. Kontrollér dit input",
  "noCenterPointSetMessage": "Der er ikke angivet noget centerpunkt. Kontrollér dit input",
  "ellipseMajorAxis": "Storakse",
  "ellipseMinorAxis": "Lille akse",
  "degreesRangeMessage": "Værdi skal være mellem 0 og 360",
  "millsRangeMessage": "Værdi skal være mellem 0 og 6400",
  "lengthLabel": "Længde",
  "angleLabel": "Vinkel",
  "startPointLabel": "Begyndelsespunkt",
  "endPointLabel": "Slutpunkt",
  "centerPointLabel": "Centerpunkt",
  "distanceTableErrorMessage": "Afstandstabellen er tom. Du skal indtaste nogle afstande.",
  "setCoordFormatStringMessage": "Indstil koordinatformat-streng",
  "prefixMessage": "Tilføj ’+/-’ præfikset til positive og negative tal",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Decimalgrader - Breddegrad/Længdegrad",
  "DDLongLatNotation": "Decimalgrader - Længdegrad/Breddegrad",
  "DDMLatLongNotation": "Grader Decimal Minutter - Breddegrad/Længdegrad",
  "DDMLongLatNotation": "Grader Decimal Minutter - Længdegrad/Breddegrad",
  "DMSLatLongNotation": "Grader Minutter Sekunder - Breddegrad/Længdegrad",
  "DMSLongLatNotation": "Grader Minutter Sekunder - Længdegrad/Breddegrad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Bånd Bogstav",
  "UTMHemNotation": "UTM - Hemisfære (N/S)",
  "circleTitle": "Opret cirkel ud fra",
  "radiusLabel": "Radius",
  "diameterLabel": "Diameter",
  "startPointPlaceHolderLabel": "Angiv koordinater",
  "formatInputLabel": "Formatangivelse",
  "drawCircleLabel": "Tegn cirkel",
  "drawLineLabel": "Tegn linje",
  "createCircleInteractivelyLabel": "Opret cirkel interaktivt",
  "rangeErrorMessage": "Ugyldig radius eller diameter",
  "numericInvalidMessage": "Angiv en numerisk værdi",
  "timeLabel": "Tid",
  "invalidTimeMessage": "Ugyldig tidsværdi",
  "hoursLabel": "Timer",
  "minutesLabel": "Minutter",
  "secondsLabel": "Sekunder",
  "rateLabel": "Vurdér",
  "invalidDistanceMessage": "Ugyldig afstandsværdi",
  "feetSecondsLabel": "Fod / sekund",
  "feetHourLabel": "Fod / time",
  "kmSecondLabel": "Kilometer / sekund",
  "kmHourLabel": "Kilometer / time",
  "metersSecondLabel": "Meter / sekund",
  "metersHourLabel": "Meter / time",
  "milesSecondLabel": "Mil / sekund",
  "milesHourLabel": "Mil / time",
  "nauticalMilesSecondLabel": "Sømil / sekund",
  "nauticalMilesHourLabel": "Sømil / time",
  "clearGraphicsLabel": "Ryd grafik",
  "ellipseTypeLabel": "Ellipse-type",
  "ellipseSemiLabel": "Semi",
  "ellipseFullLabel": "Fuld",
  "drawEllipseLabel": "Tegn ellipse",
  "createEllipseInteractively": "Opret ellipse interaktivt",
  "axisLabel": "Akse",
  "unitLabel": "Enhed",
  "majorRadiusLabel": "Stor akse (radius)",
  "majorDiameterLabel": "Stor akse (diameter)",
  "axisErrorMessage": "Værdien skal være større end 0",
  "minorRadiusLabel": "Lille akse (radius)",
  "minorDiameterLabel": "Lille akse (diameter)",
  "orientationLabel": "Retning",
  "orientationErrorMessage": "Værdien skal være mellem 0 og 360",
  "warningMessage": "Advarsel: Grafik, der er genereret med ellipse-værktøjet, er ikke geodætisk",
  "fromLabel": "Fra",
  "distanceBearingLabel": "Afstand og pejling",
  "pointsLabel": "Punkter",
  "createLineInteractively": "Opret linje interaktivt",
  "lineLengthErrorMessage": "Ugyldig linjelængde",
  "degreesLabel": "Grader",
  "milsLabel": "Mils",
  "lineTypeLabel": "Type",
  "interactiveLabel": "Interaktiv",
  "fixedLabel": "Fast",
  "originLabel": "Oprindelse",
  "cumulativeLabel": "Kumulative",
  "numberOfRingsLabel": "Antal ringe",
  "ringsErrorMessage": "Ugyldigt antal ringe",
  "distanceBetweenRingsLabel": "Afstand mellem ringe",
  "ringsDecimalErrorMessage": "Indtast en numerisk med 2 decimaler",
  "distanceUnitsLabel": "Afstandsenheder",
  "distancesLabel": "Afstande",
  "numberOfRadialsLabel": "Antal radialer",
  "upLabel": "Op",
  "downLabel": "Ned",
  "deleteLabel": "Slet",
  "radialsErrorMessage": "Ugyldigt antal radialer. Højest tilladte er antal er 360",
  "radialsInvalidMessage": "Ugyldig værdi for radialer",
  "addPointLabel": "Tilføj punkt",
  "valueLabel": "Værdi",
  "valueText": "Indtast værdi",
  "actionLabel": "Handling",
  "distanceCalculatorLabel": "Afstandsberegner",
  "abbrevMetersLabel": "m",
  "abbrevFeetLabel": "fod",
  "abbrevKmLabel": "km",
  "abbrevMilesLabel": "mile",
  "abbrevYardsLabel": "yard",
  "abbrevNauticalMilesLabel": "nm",
  "abbrevDegreesLabel": "°",
  "abbrevMilsLabel": "mil",
  "abbrevHoursLabel": "t",
  "abbrevMinutesLabel": "m",
  "abbrevSecondsLabel": "s",
  "abbrevFeetSecondsLabel": "fod/s",
  "abbrevFeetHourLabel": "fod/t",
  "abbrevKmSecondLabel": "km/s",
  "abbrevKmHourLabel": "km/t",
  "abbrevMetersSecondLabel": "m/s",
  "abbrevMetersHourLabel": "m/t",
  "abbrevMilesSecondLabel": "mil/s",
  "abbrevMilesHourLabel": "mi/t",
  "abbrevNauticalMilesSecondLabel": "nm/s",
  "abbrevNauticalMilesHourLabel": "nm/t",
  "publishDDBtn": "Publicér",
  "publishTitle": "Publicer grafik",
  "ddLayerName": "Navn på publiceret lag",
  "missingDDLayerName": "Du skal indtaste et navn til laget",
  "publishToNewLayer": "Publicér resultater til et nyt vektorlag",
  "checkService": "Kontroller tjeneste: {0}",
  "createService": "Opret tjeneste: {0}",
  "unableToCreate": "Kan ikke oprette: {0}",
  "addToDefinition": "Tilføj til definition: {0}",
  "successfullyPublished": "Weblag er oprettet{0}Administrér weblaget",
  "userRole": "Kan ikke oprette tjenesten, fordi brugeren ikke har tilladelser",
  "missingLayerNameMessage": "Du skal indtaste et gyldigt lag-navn, før du kan publicere.",
  "invalidLayerName": "Lagnavnet må kun indeholde alfanumeriske tegn og understregninger",
  "distanceLabel": "Afstand",
  "radiusDistance": "Radius-distance",
  "radials": "Radialer",
  "rings": "Ringe",
  "orientationUnit": "Orienteringsenhed",
  "radiusUnit": "Radius-enhed",
  "angleUnitLabel": "Vinkel-enhed"
});