define({
  "serviceUrl": "Service-URL instellen:",
  "minIntSpacingLabel": "Minimum intervalspatiëring",
  "lineOpacityLabel": "Lijnopaciteit",
  "labelOpacityLabel": "Labelopaciteit",
  "centerLabelOpacityLabel": "Middenlabelopaciteit",
  "gridZonePlacementLabel": "Labelplaatsing Rasterzone",
  "verticalLineLabels": "Verticale lijnlabels",
  "styleHeaderLabel": "Stijl",
  "indexHeaderLabel": "Index",
  "colorHeaderLabel": "Kleur",
  "fontSizeHeaderLabel": "Tekengrootte",
  "lineWidthHeaderLabel": "Lijnbreedte",
  "horizontalLabel": "Horizontaal",
  "verticalLabel": "Verticaal",
  "upperLeftLabel": "Linksboven",
  "upperRightLabel": "Rechtsboven",
  "lowerLeftLabel": "Linksonder",
  "lowerRightLabel": "Rechtsonder",
  "centerLabel": "Centreren"
});