define({
  "tabs_section_Label": "לשוניות",
  "addTab": "הוסף לשונית",
  "layerName": "שכבה",
  "layerType": "סוג ניתוח",
  "layerLabel": "תווית",
  "actions": "פעולות",
  "closest": "היישות הקרובה ביותר",
  "proximity": "קרבה",
  "summary": "סיכום",
  "select_lbl": "-- בחר --",
  "general_setting_Label": "הגדרות כלליות",
  "units_text_lbl": "יחידות מרחק",
  "maximum_distance_lbl": "מרחק מקסימום מהישות הקרובה ביותר",
  "buffer_text_lbl": "תווית חיץ",
  "buffer_lbl": "מרחק חיץ",
  "buffer_max_lbl": "מרחק מקסימום לחיץ",
  "buffer_min_lbl": "מרחק מינימום לחיץ",
  "routing_checkBox": "הפעל ניתוב",
  "weather_Label": "אפשרויות מזג אוויר",
  "weather_checkBox": "כלול מידע על מזג אוויר",
  "selectLayers": "בחר שכבות מזג אוויר",
  "currentlySelectedLayer": "שכבות מזג אוויר בחורות נוכחיות",
  "missingTabLabel": "לפחות לאחת מהלשוניות חסרה תווית",
  "missingLayerInWebMap": "לא נמצאו שכבות אופרטיביות.",
  "selectFields": "בחר שדות",
  "addField": "הוסף שדה",
  "sum": "סכום",
  "min": "מינימום",
  "max": "מקסימום",
  "avg": "ממוצע",
  "count": "ספירה",
  "area": "אזור",
  "length": "אורך",
  "count_checkBox": "הצג ספירת ישויות",
  "area_checkBox": "הצג סכום שטח",
  "length_checkBox": "הצג סכום אורך",
  "max_records": "הגעת למספר המקסימלי",
  "save_label": "שמור אפשרויות",
  "save_checkbox": "הפעל שמירה",
  "csv_label": "אפשרויות CSV",
  "csv_checkbox": "ייצא את כל השדות שבשכבה",
  "display_label": "הצג אפשרויות",
  "display_checkbox": "הצג ישויות סיכום",
  "snapshot_label": "אפשרויות צילום בזק",
  "snapshot_checkbox": "אפשר צילום בזק",
  "must_select_template": "בחר אחת מתבניות העריכה תחת 'שמור אפשרויות'",
  "count_label": "תווית מונה",
  "area_label": "תווית שטח",
  "length_label": "תווית אורך",
  "invalid_string_width": "הערך ארוך מדי. ",
  "layer_type_not_supported": "סוג השכבה לא נתמך: ",
  "groupedSummary": "ספירות מקובצות",
  "groupByField": "קיבוץ לפי שדה",
  "labelType": "הוסף תווית",
  "prefix": "כתחילית",
  "suffix": "כסיומת",
  "need_group_field": "השתמש בפעולת העריכה להגדרת 'קיבוץ לפי שדה'.",
  "fieldTitle": "שדה",
  "typeTitle": "סוג",
  "actionsTitle": "פעולות",
  "save_point_checkbox": "שמור נקודות",
  "save_line_checkbox": "שמור קווים",
  "save_poly_checkbox": "שמור פוליגונים",
  "no_valid_popup_fields": "אין שדות חוקיים ב-Popup. השתמש בפעולת העריכה כדי לקבוע שדה.",
  "no_valid_fields": "אין שדות חוקיים. השתמש בפעולת העריכה כדי לקבוע להגדרות תצוגה.",
  "incident_label": "תווית כרטיסייה",
  "locate_incident_label": "אזור תווית עניין",
  "incident": "מקרה",
  "locate_incident": "אתר מקרים",
  "buffer_value": "מרחק חיץ"
});