define({
  "taskUrl": "कार्य का URL",
  "setTask": "सेट करें",
  "setTaskPopupTitle": "कार्य निर्धारित करें",
  "validate": "सेट करें",
  "inValidGPService": "कृपया मान्य जियोप्रोसेसिंग सेवा दर्ज करें।",
  "GPFeatureRecordSetLayerERR": "कृपया केवल 'GPFeatureRecordSetLayer' प्रकार के इनपुट के साथ जियोप्रोसेसिंग सेवा दर्ज करें।",
  "invalidInputParameters": "इनपुट मापदंडों की संख्या 1 से कम या 3 से अधिक है। कृपया वैध जियोप्रोसेसिंग सेवा दर्ज करें।",
  "projectSetting": {
    "title": "प्रोजेक्ट सेटिंग",
    "note": "ध्यान देः प्रोजेक्ट सेटिंग वैकल्पिक हैं, कॉन्फ़िगर करने के बाद उपयोगकर्ता नेटवर्क आउटेज क्षेत्र और इनपुट मापदंडों वाले वांछित वेबमैप लेयर में प्रोजेक्ट स्टोर कर सकता है। उपयोगकर्ता “आउटपुट” समूह के अन्य आउटपुट मापदंडों को “इनपुट/आउटपुट” टैब में स्टोर कर सकता है।",
    "projectPolygonLayer": "प्रोजेक्ट बहुभुज लेयर",
    "outputParameterName": "आउटपुट मानदंड नाम",
    "projectPointLayer": "प्रोजेक्ट पॉइंट लेयर",
    "selectLabel": "चुनें",
    "polygonLayerHelp": "<p>निम्नलिखित शर्तों के साथ बहुभुज लेयर दिखेंगे:<br/><li>लेयर में संपादन क्षमताएँ होनी चाहिए जैसे कि “बनाएँ”, “हटाएँ” और “अपडेट करें”</li><li>लेयर में सटीक नाम और डेटा प्रकार वाले 2 फ़ील्ड होने चाहिए:</li><ul><li>नाम (स्ट्रिंग प्रकार फ़ील्ड)</li><li>ग्लोबलआईडी (GlobalID प्रकार फ़ील्ड)</li></ul><p/>",
    "outputParameterHelp": "<p>कार्य URL के आउटपुट बहुभुज लेयर दिखेंगे<p/>",
    "pointLayerHelp": "<p>निम्नलिखित शर्तों के साथ पॉइंट लेयर को दिखाया जाएगा: <br/><li>लेयर में संपादन क्षमताएँ होनी चाहिए जैसे कि “बनाएँ”, “हटाएँ” और “अपडेट करें”</li><li>लेयर में सटीक नाम और डेटा प्रकार वाले 2 फ़ील्ड होने चाहिए:</li><ul><li>इनपुटटाइप (स्ट्रिंग प्रकार फ़ील्ड)</li><li>प्रोजेक्टआईडी (GUID प्रकार फ़ील्ड)</li></ul><p/>"
  },
  "inputOutputTab": {
    "title": "इनपुट/आउटपुट",
    "inputSettingsLabel": "इनपुट सेटिंग",
    "outputSettingsLabel": "आउटपुट सेटिंग",
    "inputLabel": "लेबल",
    "inputTooltip": "टूलटिप",
    "symbol": "चिह्न",
    "typeText": "टाइप करें",
    "outputParametersText": "आउटपुट मानदंड",
    "saveToLayerText": "लेयर में सहेजें (वैकल्पिक)",
    "skipText": "छोड़ने योग्य",
    "visibilityText": "दृश्यमान",
    "exportToCsvText": "CSV में निर्यात करें",
    "exportToCsvDisplayText": "CSV",
    "settitngstext": "सेटिंग्स",
    "addFieldTitle": "फील्ड जोडें",
    "enterDisplayText": "प्रदर्शित पाठ दर्ज करें",
    "setScale": "स्केल निर्धरित करें",
    "outputDisplay": "पाठ प्रदर्शित करें",
    "saveToLayerHelp": "<p>निम्नलिखित शर्तों के साथ लेयर दिखेगा:<br/><li>लेयर में संपादन क्षमताएँ होनी चाहिए जैसे कि “बनाएँ”, “हटाएँ” और “अपडेट करें”</li><li>लेयर नाम और डेटा प्रकार वाले दो फ़ील्ड होने चाहिए:</li><ul><li>मापदंड नाम (स्ट्रिंग प्रकार फ़ील्ड)</li><li>प्रोजेक्टआईडी (GUID प्रकार फ़ील्ड)</li></ul><p/>"
  },
  "summaryTab": {
    "title": "सारांश",
    "summaryFieldsetText": "सारांश सेटिंग",
    "inputOutput": "इनपुट/आउटपुट",
    "field": "फ़ील्ड",
    "operator": "ऑपरेटर्स",
    "inputOperatorCountOption": "गणना करें",
    "outputOperatorCountOption": "गणना करें",
    "outputOperatorSkipCountOption": "गणना छोड़ें",
    "fieldOperatorSumOption": "योग",
    "fieldOperatorMinOption": "न्यून",
    "fieldOperatorMaxOption": "अधि",
    "fieldOperatorMeanOption": "माध्य",
    "expressionAddButtonText": "जोड़ें",
    "expressionVerifyButtonText": "सत्यापित करें",
    "summaryEditorText": "सारांश पाठ"
  },
  "generalSettings": {
    "title": "सामान्य सेटिंग",
    "displayTextForButtonLegend": "'चलाएँ' बटन के लिए पाठ प्रदर्शित करें",
    "displayTextforButtonDefaultValue": "रन करें",
    "displayTextForButton": "पाठ प्रदर्शित करें",
    "autoZoomAfterTrace": "ज़ूम के विकल्प",
    "zoomText": "ट्रेस के बाद ऑटो ज़ूम करें"
  },
  "validationErrorMessage": {
    "webMapError": "वेबमैप में कोई भी लेयर मौजूद नहीं है। कृपया वैध वेबमैप चुनें।",
    "inputTypeFlagGreaterThanError": "प्रकार फ़्लैग का इनपुट एक से अधिक नहीं हो सकता।",
    "inputTypeFlagLessThanError": "प्रकार फ़्लैग के कम से कम एक इनपुट की आवश्यकता होती है।",
    "inputTypeBarrierErr": "प्रकार बैरियर का इनपुट एक से अधिक नहीं हो सकता।",
    "inputTypeSkipErr": "प्रकार छोड़ें का इनपुट एक से अधिक नहीं हो सकता।",
    "displayTextForButtonError": "चलाएँ' बटन के लिए प्रदर्शन पाठ रिक्त नहीं हो सकता।",
    "UnableToLoadGeoprocessError": "जियोप्रोसेसिंग सेवा लोड करने में असमर्थ।",
    "invalidSummaryExpression": "अमान्य अभिव्यक्ति।",
    "validSummaryExpression": "सफल !",
    "invalidProjectSettings": "अमान्य प्रोजेक्ट सेटिंग।<br/> कृपया '${projectSetting}' में मान्य मान चुनें।"
  },
  "hintText": {
    "labelTextHint": "संकेत: आउटपुट पैरामीटर के परिणाम पैनल के लिए प्रदर्शन लेबल प्रदान करें।",
    "displayTextHint": "संकेत: यह इस आउटपुट पैरामीटर के लिए विवरण पैनल में प्रदर्शित किया जाएगा।",
    "inputTextHint": "संकेत: इनपुट, आउटपुट और फ़ील्ड के नाम का चयन करके ऊपर अपनी अभिव्यक्ति बनाएँ।",
    "expressionHint": "संकेत: आइटम चुनें और अभिव्यक्ति बनाने के लिए जोड़ें पर क्लिक करें।"
  }
});