define({
  "tabs_section_Label": "Kortelės",
  "addTab": "Pridėti skirtuką",
  "layerName": "Sluoksnis",
  "layerType": "Analizės tipas",
  "layerLabel": "Klausimas",
  "actions": "Veiksmai",
  "closest": "Artimiausias elementas",
  "proximity": "Artumas",
  "summary": "Suvestinė",
  "select_lbl": "-- Pasirinkti --",
  "general_setting_Label": "Bendrieji parametrai",
  "units_text_lbl": "Atstumo vienetai",
  "maximum_distance_lbl": "Artimiausio elemento maksimalus atstumas",
  "buffer_text_lbl": "Buferio žymė",
  "buffer_lbl": "Buferio atstumas",
  "buffer_max_lbl": "Maksimalus buferio atstumas",
  "buffer_min_lbl": "Minimalus buferio atstumas",
  "buffer_default_lbl": "Numatytasis buferio atstumas",
  "not_less_than_max": "Atstumas turi būti mažesnis nei didžiausias buferio atstumas",
  "not_between": "Atstumas turi būti tarp mažiausio ir didžiausio buferio atstumo",
  "not_more_than_min": "Atstumas turi būti didesnis nei mažiausias buferio atstumas",
  "not_valid_number": "Skaičius turi būti tinkamas",
  "invalid_value": "Reikšmė ${type} yra netinkama",
  "routing_checkBox": "Įgalinti maršrutų nustatymą",
  "weather_removed_message": "Šiame valdiklyje orų parinkčių nebėra.",
  "currentlySelectedLayer": "Pasirinkti iš žemėlapių sluoksnių",
  "missingTabLabel": "Bent vienas skirtukas neturi žymės",
  "missingLayerInWebMap": "Darbinių sluoksnių nerasta.",
  "selectFields": "Pasirinkite laukus",
  "addField": "Pridėti lauką",
  "sum": "Suma",
  "min": "Minimumas",
  "max": "Maksimumas",
  "avg": "Vidurkis",
  "count": "KIEKIS",
  "area": "PLOTAS",
  "length": "ILGIS",
  "count_checkBox": "Rodyti elementų skaičių",
  "area_checkBox": "Rodyti bendrą plotą",
  "length_checkBox": "Rodyti bendrą ilgį",
  "max_records": "Pasiekta maksimali riba",
  "save_label": "Įrašyti parinktis",
  "save_checkbox": "Įjungti įrašymą",
  "report_label": "Ataskaitos parinktys",
  "report_checkbox": "Įgalinti ataskaitą",
  "csv_label": "CSV parinktys",
  "display_label": "Rodymo parinktys",
  "display_checkbox": "Pateikti santraukos elementus",
  "setSelectionColor": "Nustatyti žymėjimo spalvą",
  "snapshot_label": "Snapshot parinktys",
  "snapshot_checkbox": "Įjungti Snapshot",
  "must_select_template": "Pasirinkite vieną iš redagavimo šablonų įrašymo parinktyse.",
  "count_label": "Skaičiaus žymė",
  "area_label": "Ploto žymė",
  "length_label": "Ilgio žymė",
  "invalid_string_width": "Reikšmė per ilga. ",
  "layer_type_not_supported": "Nepalaikomas sluoksnio tipas",
  "groupedSummary": "Sugrupuoti skaičiavimai",
  "groupByField": "Grupuoti pagal lauką",
  "labelType": "Pridėti žymę",
  "prefix": "Kaip prefiksą",
  "suffix": "Kaip sufiksą",
  "need_group_field": "Norėdami nustatyti grupavimą pagal lauką, naudokite veiksmą Redaguoti.",
  "fieldTitle": "Laukas",
  "typeTitle": "Tipas",
  "actionsTitle": "Veiksmai",
  "save_point_checkbox": "Įrašyti taškus",
  "save_line_checkbox": "Įrašyti linijas",
  "save_poly_checkbox": "Įrašyti poligonus",
  "no_valid_popup_fields": "Nėra tinkamų laukų iššokančiame lange. Apibrėžkite lauką naudodami veiksmą Redaguoti.",
  "no_valid_fields": "Nėra tinkamų laukų. Apibrėžkite lauką naudodami veiksmą Redaguoti.",
  "incident_label": "Skirtuko žymė",
  "locate_incident_label": "Dominančio ploto žymė",
  "incident": "Įvykis",
  "locate_incident": "Rasti įvykį",
  "buffer_value": "Buferio atstumas",
  "tab_options": "Analizė",
  "export_options": "Išvestis",
  "instruction_save": "Įrašyti vietą elementų paslaugoje.",
  "instruction_snapshot": "Kurti internetinį žemėlapį, pagrįstą padėtimi.",
  "instruction_report": "Kurti spausdintinę padėties ataskaitą.",
  "instruction_all_fields": "Eksportuoti laukus su CSV atsisiuntimu.",
  "data_label": "Duomenų išvesties nustatymai",
  "layer_error": "Sluoksnio trūksta arba jis neleistinas.",
  "visibility_checkBox": "Išjungti sluoksnių matomumo valdymą",
  "allFieldsLabel": "Visi laukai",
  "configuredPopUpFieldsLabel": "Sukonfigūruota iššokančiuose laukuose",
  "analysisTypeFieldsLabel": "Analizės tipo laukai",
  "reportOptionsMsg": "Būtina pasirinkti bent vieną ataskaitos parinktį",
  "analysisSummaryLabelForReport": "Analizės tipo santrauka",
  "popUpSummaryLabelForReport": "Sukonfigūruotų iššokančiųjų laukų santrauka",
  "downloadTab": {
    "reportLegend": "Ataskaitos parametrai",
    "textColorLabel": "Pasirinkite stulpelių antraštės spalvą",
    "setButtonLabel": "Nustatyti",
    "printGPServiceLabel": "Spausdinti paslaugos URL",
    "logoLabel": "Logotipas",
    "logoChooserHint": "Paspauskite vaizdo piktogramą norėdami pakeisti atvaizdą",
    "footnoteLabel": "Išnaša"
  },
  "roundValue": "Suapvalinti iki",
  "roundValueTitle": "Suapvalinti laukų reikšmes",
  "truncateValue": "Trumpinti iki",
  "truncateValueTitle": "Trumpinti laukų reikšmes",
  "significantFigures": "reikšmingi skaičiai",
  "fieldOptions": "Laukų parinktys",
  "modifyValues": "Redaguoti laukų reikšmes",
  "validatePlaces": "Turi būti sveikasis skaičius",
  "onlyDouble": "Papildomos laukų parinktys palaikomos tik skaitiniams laukams.",
  "layerNotAvalible": "Sluoksnis nerastas",
  "missingLayer": "Pavadinimas: ${name}",
  "missingLayerHint": "Vienas ar daugiau šioje konfigūracijoje nurodytų sluoksnių šiuo metu nepasiekiami.",
  "drawGeodesic": "Brėžti geodezines figūras"
});