define({
  "_widgetLabel": "Koordináta-konverzió",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Tizedes fokok - szélesség/hosszúság",
  "DDLongLatNotation": "Tizedes fokok - hosszúság/szélesség",
  "DDMLatLongNotation": "Fokok és tizedes fokpercek - szélesség/hosszúság",
  "DDMLongLatNotation": "Fokok és tizedes fokpercek - hosszúság/szélesség",
  "DMSLatLongNotation": "Fokok, fokpercek és fokmásodpercek - szélesség/hosszúság",
  "DMSLongLatNotation": "Fokok, fokpercek és fokmásodpercek - hosszúság/szélesség",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - sávbetűjel",
  "UTMHemNotation": "UTM - félteke (É/D)",
  "formatInput": "Formátumbemenet",
  "copyAll": "Összes másolása",
  "copySuccessful": "Sikeres másolás",
  "copyFailed": "A másolás nem sikerült. Másik megoldásként próbálkozzon a Ctrl+C billentyűkombinációval.",
  "parseCoordinatesError": "Nem sikerült a koordináták konvertálása. Ellenőrizze a bevitt adatokat.",
  "comfirmInputNotation": "Bemeneti jelölés megerősítése",
  "latLongWarningMessage": "A bemeneti koordináta elő- és utótagot is tartalmaz a szélesség és a hosszúság értékéhez: a visszaadott érték az előtag alapján került megállapításra.",
  "inputLabel": "Bemenet",
  "outputLabel": "Kimenet",
  "cancelButtonLabel": "Mégse",
  "applyButtonLabel": "Alkalmaz",
  "posNegPrefixLabel": "A „+/-” előtag hozzáadása a pozitív és negatív számok jelöléséhez",
  "editCoordinateDialogTitle": "Koordináta-formátum beállítása",
  "rememberDecisionLabel": "Emlékezzen a döntésemre, és ne kérdezze meg újra.<br/>",
  "coordinateInputLabel": "Adja meg a koordinátákat, vagy kattintson a térképre",
  "zoomLabel": "Nagyítás/kicsinyítés",
  "multipleNotationLabel": "olyan jelölés található, amely megfelel a bemenetnek. Pontosítsa, melyiket szeretné használni:",
  "copyToClipboard": "Másolás a vágólapra",
  "formatOutput": "Formátumkimenet",
  "addNewNotation": "Új jelölés hozzáadása",
  "notationAddedMessage": "Új jelölés hozzáadva",
  "addLabel": "Hozzáadás",
  "removeCoordinate": "Koordináta eltávolítása",
  "expandOutput": "Kimenet kibontása",
  "latitudeLabel": "Szélesség",
  "longitudeLabel": "Hosszúság",
  "quadrantLabel": "Negyedkör",
  "keyLabel": "Kulcs",
  "fifteenDegreeLabel": "15° negyedkör",
  "oneDegreeLabel": "1° negyedkör",
  "eastingLabel": "Abszcissza",
  "northingLabel": "Ordináta",
  "zoneLabel": "Zóna",
  "bandLabel": "Sáv",
  "gzdLabel": "GZD",
  "gridSquareLabel": "Négyzetes rácsháló",
  "hemisphereLabel": "Félgömb",
  "addPointLabel": "Pont hozzáadása"
});