define({
  "chartSettingLabel": "Definições de gráfico",
  "addNewLabel": "Adicionar novo",
  "generalSettingLabel": "Configurações gerais",
  "layerChooser": {
    "title": "Seleccionar camada para gráfico",
    "selectPolygonLayerLabel": "Seleccionar Camada",
    "selectPolygonLayerHintText": "Sugestão: Se configurando múltiplos gráficos, então camadas devem ser do mesmo tipo geométrico",
    "selectRelatedTableLayerLabel": "Seleccionar tabela relacionada a camada",
    "selectRelatedTableLayerHintText": "Sugestão: Apenas tabelas com campos numéricos são exibidos",
    "errorInSelectingPolygonLayer": "Por favor seleccione uma camada que tem uma camada de ponto relacionado.",
    "errorInSelectingRelatedLayer": "Por favor seleccione uma tabela/camada relacionada válida para camada.",
    "polygonLayerNotHavingRelationships": "Seleccionar camada que não tenha qualuqer tabela/camada relacionada"
  },
  "ChartSetting": {
    "sectionTitle": "Título da secção",
    "sectionTitleHintText": "Sugestão: Exibido no título do cabeçalho da secção",
    "chartTitle": "Título de gráfico",
    "chartTitleHintText": "Dica: Exibido centrado por cima do gráfico",
    "chartDescription": "Descrição",
    "chartDescriptionHintText": "Dica: Exibido abaixo do gráfico",
    "chartType": "Tipo de gráfico",
    "barChart": "Gráfico de barras",
    "pieChart": "Gráfico circular",
    "polarChart": "Gráfico polar",
    "dataSeriesField": "Campo de série de dados",
    "labelField": "Campo de rótulo",
    "chartColor": "Cor de gráfico",
    "singleColor": "Cor única",
    "colorByTheme": "Cor por tema",
    "colorByFieldValue": "Cor por campo de valor",
    "xAxisTitle": "Título eixo-x",
    "xAxisHintText": "Sugestão: Título eixo-x",
    "yAxisTitle": "Título eixo-y",
    "yAxisHintText": "Sugestão: Título eixo-y",
    "fieldColorLabel": "Rótulo",
    "fieldColorColor": "Cor",
    "defaultFieldSelectLabel": "Seleccionar",
    "errMsgFieldValuesNotFound": "Incapaz de descobrir valores para o campo seleccionado",
    "errMsgSectionTitle": "Por favor introduza o título de secção",
    "errMsgFieldByValue": "Por favor seleccione valor de campo",
    "settingTabTitle": "Definição",
    "layoutTabTitle": "Layout",
    "polarChartSelectFieldsHintText": "Dica: Selecione campos para gerar gráfico polar",
    "visibilityText": "Visibilidade",
    "fieldNameText": "Nome do Campo",
    "aliasNameText": "Nome Alternativo",
    "errMsgPolarFieldsRequired": "Por favor, selecione três ou mais campos para gerar gráfico polar",
    "polarChartPolygonFillLabel": "Preencher polígono",
    "polarChartPolygonFillHintText": "Dica: Selecione a caixa de seleção para exibir o preenchimento do polígono no gráfico polar",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Configurações Gerais",
    "locationSymbolLabel": "Símbolo de gráfico de localização",
    "locationSymbolHintText": "Sugestão: Usado para exibir símbolo para endereço e clique localização",
    "refreshIntervalLabel": "Intervalo de actualização",
    "refreshIntervalHintText": "Sugestão: Usado para actualizar gráficos baseado neste intervalo. Especifique um valor entre 1 até 1440 minutos",
    "errMsgRefreshInterval": "Por favor especifique o intervalo de actualização entre 0 e 1440 minutos",
    "symbolPickerPreviewText": "Visualizar:"
  }
});