define({
  "_widgetLabel": "Nätverksspår",
  "_featureAction_NetworkTraceSkip": "Hoppa över i spåret",
  "_featureAction_NetworkTraceUnskip": "Ta bort från platser att hoppa över",
  "removedFromSkipLocations": "Borttagen från platser att hoppa över",
  "alreadyRemovedFromSkipLocations": "Redan borttagen från platser att hoppa över",
  "locationSkipped": "Platsen har hoppats över",
  "configError": "Widgeten är inte korrekt konfigurerad.",
  "geometryServiceURLNotFoundMSG": "Det gick inte att hämta webbadress till geometritjänst",
  "clearButtonValue": "Avmarkera",
  "GPExecutionFailed": "Spåret kan inte slutföras. Försök igen.",
  "backButtonValue": "BACKA",
  "exportToCSVSuccess": "Export till CSV lyckades.",
  "lblInputLocTab": "Platser för indata",
  "lblBlockLocTab": "Blockera platser",
  "lblInputLocation": "Indatageoobjekt",
  "lblBlockLocation": "Blockera geoobjekt",
  "lblInputLocHeader": "Platser för indata (0)",
  "lblBlockLocHeader": "Blockera platser (0)",
  "inputTabTitle": "Indata",
  "outputTabTitle": "Utdata",
  "exportSelectAllCheckBoxLabel": "Markera alla",
  "lblSkipLocHeader": "Hoppa över platser (0)",
  "lblSkipLocation": "Plats",
  "lblSkipLocTab": "Hoppa över platser",
  "skipAllLocationButtonLabel": "Hoppa över alla platser",
  "confirmSkipAllLocationsMessage": "Alla platser hoppas över, vill du fortsätta?",
  "locationAlreadySkippedMessage": "Platsen har redan hoppats över",
  "removeAllSkipLocationLabel": "Ta bort alla",
  "newProjectOptionText": "Nytt projekt",
  "selectProject": "Välj projekt",
  "saveButtonLabel": "Spara",
  "exportToCSVText": "Exportera till CSV",
  "editProjectAttributesToolTip": "Redigera projektattribut",
  "projectNameLabel": "Projektnamn",
  "saveProjectPopupTitle": "Spara",
  "saveAsLabel": "Spara som",
  "saveChangesMsg": "Vill du spara dina ändringar till <b>${loadProjectDropdownlabel}</b> eller spara som nytt projekt?",
  "creatingNewProjectErrorMessage": "Ett fel uppstod när nytt projekt skapades. Försök igen.",
  "projectNameFetchingErr": "Ett fel uppstod vid hämtning av befintliga projektnamn. Försök igen.",
  "projectAttributeLoadingErr": "Ett fel uppstod vid inläsning av projektattribut. Försök igen.",
  "attributeUpdatedMsg": "Attributen har uppdaterats.",
  "projectAttributeUpdatingErr": "Ett fel uppstod vid uppdatering av projektattribut.",
  "loadingProjectDetailsErrorMessage": "Ett fel uppstod vid hämtning av flaggor, barriärer och platser som ska hoppas över. Försök igen.",
  "savingProjectDetailsErr": "Ett fel uppstod när projektdetaljer sparades. Försök spara projektet igen.",
  "updatingOutagePolygonErr": "Ett fel uppstod vid uppdatering av avbrottspolygon. Försök spara projektet igen.",
  "deletingExistingPolygonErr": "Ett fel uppstod när befintlig avbrottspolygon togs bort. Försök spara projektet igen.",
  "loadingProjectFeaturesErr": "Ett fel uppstod vid inläsning av projektgeoobjekt. Försök läsa in projektet igen.",
  "addingProjectFeaturesErr": "Ett fel uppstod när projektgeoobjekt lades till. Försök spara projektet igen.",
  "deletingExistingProjectFeaturesErr": "Ett fel uppstod när befintliga projektgeoobjekt togs bort. Försök spara projektet igen.",
  "projectNotFoundErr": "Det gick inte att hitta projektet",
  "projectLayersNotFound": "Konfigurerade lager med Projektinställningar är inte tillgängliga i kartan. Widgeten läses in i Sketchläge.",
  "fetchingOutagePolygonMessage": "Ett fel uppstod när avbrottspolygon hämtades. Försök läsa in projektet igen.",
  "projectNameExistsMessage": "Projektnamnet finns redan. Använd ett unikt projektnamn.",
  "fetchingProjectNamesErrorMessage": "Ett fel uppstod vid hämtning av befintliga projektnamn. Försök spara projektet igen.",
  "enterProjectNameMessage": "Ange projektnamn.",
  "projectLengthErrorMessage": "Projektnamnet får inte vara längre än",
  "gpServiceNotAccessible": "Ditt konto har inte åtkomst till den tjänst som krävs för att genomföra det här spåret.",
  "loadingClonedLayerErrorMessage": "Ett fel uppstod när det klonade geoobjektlagret lästes in. Försök igen.",
  "addingFeatureInClonedLayerError": "Ett fel uppstod när grafiken lades till i det klonade geoobjektlagret. Försök igen.",
  "selectingFeatureInClonedLayerError": "Ett fel uppstod när grafiken valdes i det klonade geoobjektlagret. Försök igen.",
  "filteredProjectError": "Ett fel uppstod vid kontroll av hämtning av filtrerade projektdetaljer. Försök igen.",
  "filteredProjectMessage": "Valda projektattribut är inte tillgängliga på grund av de tillämpade filtren från webbkartan eller en annan widget. Rensa filtret/filtren och försök igen.",
  "filteredProjectLoadMessage": "Ditt projekt är inte längre tillgängligt. Välj ett aktivt projekt.",
  "defaultValueForRunButton": "Kör",
  "closeButtonLabel": "Ta bort"
});