define({
  "taskUrl": "URL de tarea",
  "serviceURLPlaceholder": "Introduce la URL de tarea de geoprocesamiento",
  "layerOrder": "Orden de capa",
  "defaultValue": "Valor predeterminado",
  "inputFeatureBy": "Introducir entidad por",
  "inputRecordBy": "Introducir registro por",
  "renderer": "Renderizador",
  "displayType": "Mostrar tipo",
  "helpUrl": "URL de ayuda",
  "useResultMapService": "Ver los resultados con un servicio de mapas",
  "drawOnMap": "Dibujar interactivamente en el mapa",
  "selectLayer": "Seleccionar una capa del mapa",
  "selectTable": "Seleccionar una tabla del mapa",
  "shareResults": "Agregar resultado como capa operativa",
  "setTask": "Establecer",
  "setTaskTitle": "Establecer tarea de geoprocesamiento",
  "enablePopup": "Habilitar ventana emergente",
  "unSupportGeometryType": "No se puede definir el renderizador porque el tipo de geometría es desconocido.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Cargar archivo",
  "selectFileToUpload": "Seleccionar archivo...",
  "rasterFormat": "Formato de datos ráster",
  "noFileSelected": "No hay ningún archivo seleccionado",
  "uploadSuccess": "Archivo cargado correctamente",
  "showLayerContent": "Mostrar contenido de capa",
  "urlPlaceholder": "Dirección URL para acceder a los datos",
  "useShapefile": "Usar shapefile en sistema de archivos local",
  "allowToExport": "Permitir la exportación de resultados",
  "useDynamicSchema": "La salida puede tener un esquema diferente, utiliza el esquema dinámico en lugar del predefinido.",
  "useCurrentMapExtent": "Usar la extensión del mapa actual",
  "ignoreOutput": "Ignorar esta salida",
  "turnOffOutput": "Desactivar esta capa de forma predeterminada",
  "inputJSONString": "Cadena de caracteres de JSON de entrada"
});