define({
  "searchTabTitle": "Cerca impostazione di origine",
  "routeTabTitle": "Impostazione percorso",
  "add": "Aggiungi origine di ricerca",
  "addGeocoder": "Aggiungi geocodificatore",
  "geocoder": "Geocodificatore",
  "setLayerSource": "Imposta layer di origine",
  "setGeocoderURL": "Imposta URL geocodificatore",
  "searchableLayer": "Feature Layer",
  "name": "Nome",
  "countryCode": "Codici paesi o regioni",
  "countryCodeEg": "es. ",
  "countryCodeHint": "Se si lascia vuoto questo campo, la ricerca verrà effettuata in tutti i paesi e le regioni",
  "showInfoWindowOnSelect": "Mostra il popup per la feature o per la posizione trovata",
  "showInfoWindowOnSelect2": "Mostra il popup quando viene trovata la feature o la posizione.",
  "searchInCurrentMapExtent": "Esegui la ricerca nell'estensione mappa corrente",
  "setSearchFields": "Imposta campi di ricerca",
  "set": "Imposta",
  "fieldSearchable": "incluso nella ricerca",
  "zoomScale": "Scala zoom",
  "locatorUrl": "URL del geocodificatore",
  "locatorName": "Nome geocodificatore",
  "locatorExample": "Questa funzione è stata aggiunta a partire da 10.1.",
  "locatorWarning": "Questa versione del servizio di geocodifica non è supportata. Il widget supporta il servizio di geocodifica versione 10.1 e successiva.",
  "locatorTips": "I suggerimenti non sono disponibili perché il servizio di geocodifica non supporta tale funzionalità.",
  "layerSource": "Origine del layer",
  "searchLayerTips": "I suggerimenti non sono disponibili perché il feature service non supporta la funzionalità di paginazione.",
  "placeholderText": "Testo segnaposto",
  "searchFields": "Campi di ricerca",
  "displayField": "Campo di visualizzazione",
  "exactMatch": "Corrispondenza esatta",
  "maxSuggestions": "Suggerimenti massimi",
  "maxResults": "Risultati massimi",
  "enableLocalSearch": "Abilita ricerca locale",
  "minScale": "Scala minima",
  "minScaleHint": "Quando la scala della mappa è più grande di questa scala, verrà applicata la ricerca locale",
  "radius": "Raggio",
  "radiusHint": "Specifica il raggio di un'area intorno al centro della mappa corrente che viene utilizzato per assegnare la priorità alla classificazione dei candidati di geocodifica in modo che i canditati più vicini alla posizione vengano restituiti per primi",
  "invalidUrlTip": "URL ${URL} non valida o non accessibile.",
  "routeUrl": "URL itinerario",
  "geocoderOptions": "Opzioni geocodificatore",
  "autoComplete": "Completamento automatico",
  "maximumSuggestions": "Suggerimenti massimi",
  "minCharacters": "Numero min caratteri",
  "searchDelay": "Ritardo ricerca",
  "placeholder": "Segnaposto",
  "routeOptions": "Opzioni itinerari",
  "directionsLanguage": "Lingua indicazioni",
  "directionsLengthUnits": "Unità di lunghezza indicazioni",
  "directionsOutputType": "Tipo di output indicazioni",
  "impedanceAttribute": "Attributo impedenza",
  "kilometers": "Chilometri",
  "miles": "Miglia",
  "meters": "Metri",
  "feet": "Piedi",
  "yards": "Iarde",
  "nauticalMiles": "Miglia nautiche",
  "parametersTip": "Impostare correttamente i parametri.",
  "complete": "Complete",
  "completeNoEvents": "Complete senza eventi",
  "instructionsOnly": "Solo istruzioni",
  "standard": "Standard",
  "summaryOnly": "Solo riepilogo",
  "travelModesUrl": "URL delle modalità di viaggio",
  "searchPlaceholder": "Trova indirizzo o luogo",
  "trafficLayerUrl": "URL layer per il traffico",
  "barrierLayerUrl": "URL del layer barriera",
  "presetDestinations": "Fermate preimpostate",
  "startPoint": "Punto di partenza",
  "endPoint": "Punto finale",
  "destinationHolder": "Indirizzo o coordinate",
  "optional": "Facoltativo.",
  "barrierLayers": "Layer delle barriere",
  "pointBarrier": "Barriere puntuali",
  "lineBarrier": "Barriere lineari",
  "polygonBarrier": "Barriere poligonali",
  "noPointBarrier": "Scegli barriere puntuali",
  "noLineBarrier": "Scegli barriere lineari",
  "noPolygonBarrier": "Scegli barriere poligonali"
});