define({
  "_widgetLabel": "המרת קואורדינטה",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)‎",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "formatInput": "קלט פורמט",
  "copyAll": "העתק הכל",
  "copySuccessful": "ההעתקה הצליחה",
  "copyFailed": "לא ניתן להעתיק. השתמש ב-ctrl+c כחלופה.",
  "parseCoordinatesError": "לא ניתן לנתח קואורדינטות. בדוק את הקלט שלך.",
  "comfirmInputNotation": "אשר רישום קלט",
  "latLongWarningMessage": "קואורדינטת הקלט זוהתה כבעלת קידומת וסיומת עבור ערך קו הגובה או קו הרוחב, הקואורדינטה שהוחזרה מבוססת על הקידומת.",
  "inputLabel": "קלט",
  "outputLabel": "פלט",
  "cancelButtonLabel": "בטל",
  "applyButtonLabel": "בצע",
  "posNegPrefixLabel": "הוסף קידומת \"+/-\" למספרים חיוביים ושליליים",
  "editCoordinateDialogTitle": "הגדר מחרוזת פורמט לקואורדינטה",
  "rememberDecisionLabel": "זכור את ההחלטה שלי ואל תשאל שוב.<br/>",
  "coordinateInputLabel": "הזן קואורדינטות או לחץ על מפה",
  "zoomLabel": "התמקד",
  "multipleNotationLabel": "נמצאו רישומים שמתאימים לקלט שלך. אשר את הרישומים שברצונך להשתמש בהם:",
  "copyToClipboard": "העתק ללוח עריכה",
  "formatOutput": "פלט פורמט",
  "addNewNotation": "הוסף רישום חדש",
  "notationAddedMessage": "אנוטציה חדשה נוספה",
  "addLabel": "הוספה",
  "removeCoordinate": "הסר קואורדינטה",
  "expandOutput": "הרחב פלט"
});