define({
  "symbolologyTabLabel": "Konfigurasikan Simbologi",
  "facilitiesDescription": "Layer Fasilitas",
  "demographicsDescription": "Layer Demografis",
  "settingsTitle": "Pengaturan",
  "spillLocationLabel": "Lokasi Tumpahan",
  "spillLocationButtonLabel": "Konfigurasikan Pengaturan Lokasi Tumpahan",
  "IISettingsLabel": "Zona Isolasi Awal",
  "IIButtonLabel": "Konfigurasikan Pengaturan Isolasi Awal",
  "PASettingsLabel": "Zona Tindakan Protektif",
  "PAButtonLabel": "Konfigurasikan Pengaturan Tindakan Protektif",
  "downwindSettingsLabel": "Zone Downwind",
  "downwindButtonLabel": "Konfigurasikan Pengaturan Downwind",
  "fireSettingsLabel": "Zona Isolasi Kebakaran",
  "fireButtonLabel": "Konfigurasikan Pengaturan Isolasi Kebakaran",
  "bleveSettingsLabel": "Zona Isolasi BLEVE",
  "bleveButtonLabel": "Konfigurasikan Pengaturan BLEVE",
  "transparency": "Transparansi",
  "outline": "Kerangka",
  "fill": "Isi (Warna hanya berlaku jika gaya diatur ke padat)",
  "style": "Gaya",
  "selectOpLayerLabel": "Pilih layer operasional untuk hasil",
  "selectDefaultMeasurementLabel": "Pilih satuan ukuran default",
  "helpIconTooltip": "Daftar layer operasional dikumpulkan dengan layer dari peta web saat ini yang berjenis geometri poligon.",
  "colorPicker": "Pemilih Warna",
  "lineStyles": {
    "esriSLSDash": "Garis datar",
    "esriSLSDashDot": "Garis Datar Titik",
    "esriSLSDashDotDot": "Garis Datar Titik Titik",
    "esriSLSDot": "Titik",
    "esriSLSLongDash": "Garis Datar Panjang",
    "esriSLSLongDashDot": "Garis Datar Panjang Titik",
    "esriSLSNull": "Nol",
    "esriSLSShortDash": "Garis Datar Pendek",
    "esriSLSShortDashDot": "Garis Datar Pendek Titik",
    "esriSLSShortDashDotDot": "Garis Datar Pendek Titik Titik",
    "esriSLSShortDot": "Titik Pendek",
    "esriSLSSolid": "Padat"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Belakang",
    "esriSFSCross": "Silang",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Maju",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nol",
    "esriSFSSolid": "Padat",
    "esriSFSVertical": "Vertikal"
  }
});