define({
  "serviceUrl": "ตั้งค่าเซอร์วิส URL",
  "minIntSpacingLabel": "ระยะห่างระหว่างกันขั้นต่ำ",
  "lineOpacityLabel": "ความทึบของสาย",
  "labelOpacityLabel": "ความทึบของป้ายกำกับ",
  "centerLabelOpacityLabel": "ความทึบของป้ายศูนย์",
  "gridZonePlacementLabel": "ตำแหน่งป้ายตารางของตาราง",
  "verticalLineLabels": "ป้ายข้อความแนวตั้ง",
  "styleHeaderLabel": "สไตล์",
  "indexHeaderLabel": "อินเด็กซ์",
  "colorHeaderLabel": "สี",
  "fontSizeHeaderLabel": "ขนาดตัวอักษร",
  "lineWidthHeaderLabel": "ความหนาของเส้น",
  "horizontalLabel": "แนวนอน",
  "verticalLabel": "ตั้งฉาก",
  "upperLeftLabel": "ด้านบนซ้าย",
  "upperRightLabel": "ด้านบนขวา",
  "lowerLeftLabel": "ด้านล่างซ้าย",
  "lowerRightLabel": "ด้านล่างขวา",
  "centerLabel": "ศูนย์กลาง",
  "errorMessage": "หน้าการตั้งค่ามีข้อผิดพลาด โปรดแก้ไขก่อนบันทึก",
  "checkBoxLabel": "แสดงตารางกริดเมื่อปิดวิดเจ็ต"
});