define({
  "tabs_section_Label": "Pestañas",
  "addTab": "Agregar pestaña",
  "layerName": "Capa",
  "layerType": "Tipo de análisis",
  "layerLabel": "Etiqueta",
  "actions": "Acciones",
  "closest": "Entidad más próxima",
  "proximity": "Proximidad",
  "summary": "Resumen",
  "select_lbl": "-- Seleccionar --",
  "general_setting_Label": "Configuración general",
  "units_text_lbl": "Unidades de distancia",
  "maximum_distance_lbl": "Distancia máxima a la entidad más próxima",
  "buffer_text_lbl": "Etiqueta de zona de influencia",
  "buffer_lbl": "Distancia de zona de influencia",
  "buffer_max_lbl": "Distancia de zona de influencia máxima",
  "buffer_min_lbl": "Distancia de zona de influencia mínima",
  "routing_checkBox": "Habilitar enrutamiento",
  "weather_Label": "Opciones del tiempo",
  "weather_checkBox": "Incluir información del tiempo",
  "selectLayers": "seleccionar capas de tiempo",
  "currentlySelectedLayer": "Capas del tiempo seleccionadas actualmente",
  "missingTabLabel": "Falta la etiqueta en una pestaña al menos",
  "missingLayerInWebMap": "No se ha encontrado ninguna capa operativa.",
  "selectFields": "Selecciona campos",
  "addField": "Agregar campo",
  "sum": "Suma",
  "min": "Mínimo",
  "max": "Máximo",
  "avg": "Media",
  "count": "TOTAL",
  "area": "ÁREA",
  "length": "LONGITUD",
  "count_checkBox": "Mostrar recuento de entidades",
  "area_checkBox": "Mostrar suma de área",
  "length_checkBox": "Mostrar suma de longitud",
  "max_records": "Se ha alcanzado el límite máximo",
  "save_label": "Opciones para guardar",
  "save_checkbox": "Habilitar guardar",
  "csv_label": "Opciones de CSV",
  "csv_checkbox": "Exportar todos los campos de la capa",
  "display_label": "Opciones de visualización",
  "display_checkbox": "Mostrar entidades de resumen",
  "snapshot_label": "Opciones de instantánea",
  "snapshot_checkbox": "Habilitar instantánea",
  "must_select_template": "Selecciona una de las plantillas de edición en Opciones para guardar.",
  "count_label": "Etiqueta de recuento",
  "area_label": "Etiqueta de área",
  "length_label": "Etiqueta de longitud",
  "invalid_string_width": "El valor es demasiado largo. ",
  "layer_type_not_supported": "El tipo de capa no es compatible: ",
  "groupedSummary": "Recuentos agrupados",
  "groupByField": "Agrupar por campo",
  "labelType": "Adjuntar etiqueta",
  "prefix": "Como prefijo",
  "suffix": "Como sufijo",
  "need_group_field": "Use la acción Editar para definir Agrupar por campo.",
  "fieldTitle": "Campo",
  "typeTitle": "Tipo",
  "actionsTitle": "Acciones",
  "save_point_checkbox": "Guardar puntos",
  "save_line_checkbox": "Guardar líneas",
  "save_poly_checkbox": "Guardar polígonos",
  "no_valid_popup_fields": "No hay campos válidos en el elemento emergente. Utilice la acción editar para definir un campo.",
  "no_valid_fields": "No hay campos válidos. Utilice la acción editar para definir las opciones de visualización.",
  "incident_label": "Etiqueta de pestaña",
  "locate_incident_label": "Etiqueta de área de interés",
  "incident": "Incidente",
  "locate_incident": "Localizar incidente",
  "buffer_value": "Distancia de zona de influencia"
});