define({
  "_widgetLabel": "Розумний редактор",
  "_featureAction_SmartEditor": "Розумний редактор",
  "noEditPrivileges": "Ваш обліковий запис не має дозволу створювати або змінювати дані.",
  "widgetActive": "Активний",
  "widgetNotActive": "Не активний",
  "pressStr": "Натиснути ",
  "ctrlStr": " CTRL ",
  "snapStr": " для активації замикання",
  "noAvailableTempaltes": "Немає доступних шаблонів",
  "editorCache": " - Кеш-пам’ять редактора",
  "presetFieldAlias": "Поле",
  "presetValue": "Значення за замовчуванням",
  "usePresetValues": " Використовувати значення за замовчуванням (тільки нові об'єкти)",
  "editGeometry": " Редагувати геометрію",
  "savePromptTitle": "Зберегти об'єкт",
  "savePrompt": "Бажаєте зберегти поточний об'єкт?",
  "deletePromptTitle": "Видалити об'єкт",
  "deletePrompt": "Бажаєте видалити вибраний об'єкт?",
  "attachmentLoadingError": "Помилка при завантаження прикріплень",
  "attachmentSaveDeleteWarning": "Попередження: зміни до прикріплень зберігаються автоматично",
  "autoSaveEdits": "Автоматично зберігає новий об'єкт",
  "addNewFeature": "Створити новий об'єкт",
  "featureCreationFailedMsg": "Неможливо створити новий запис/об'єкт",
  "relatedItemTitle": "Пов’язана таблиця/шар",
  "invalidRelationShipMsg": "Переконайтесь, що поле первинного ключа: '${parentKeyField}' містить дійсне значення",
  "pendingFeatureSaveMsg": "Збережіть редагування об'єкту перш ніж створювати пов’язаний об'єкт.",
  "attachmentsRequiredMsg": "(*) Потрібні прикріплення.",
  "coordinatePopupTitle": "Перемістити об'єкт у місце розташування XY",
  "coordinatesSelectTitle": "Система координат:",
  "mapSpecialReferenceDropdownOption": "Просторова прив'язка карти",
  "latLongDropdownOption": "Широта/довгота",
  "xAttributeTextBoxLabel": "X-координата:",
  "yAttributeTextBoxLabel": "Y-координата:",
  "latitudeTextBoxLabel": "Широта:",
  "longitudeTextBoxLabel": "Довгота:",
  "filterEditor": {
    "all": "Всі",
    "noAvailableTempaltes": "Немає доступних шаблонів",
    "searchTemplates": "Пошук шаблонів"
  },
  "invalidConfiguration": "Віджет не налаштовано або шари у конфігурації більше не присутні у карті. Відкрийте додаток у режимі розробника та повторно налаштуйте віджет.",
  "geometryServiceURLNotFoundMSG": "Неможливо отримати URL сервісу геометрії",
  "clearSelection": "Очистити",
  "refreshAttributes": "Оновити атрибути об'єкту",
  "automaticAttributeUpdatesOn": "Автоматичне оновлення атрибутів об'єкту: УВІМКН.",
  "automaticAttributeUpdatesOff": "Автоматичне оновлення атрибутів об'єкту: ВИМКН.",
  "moveSelectedFeatureToGPS": "Перемістити вибраний об'єкт у поточне місце розташування GPS",
  "moveSelectedFeatureToXY": "Перемістити вибраний об'єкт у місце розташування XY",
  "mapNavigationLocked": "Навігація по карті: заблоковано",
  "mapNavigationUnLocked": "Навігація по карті: розблоковано",
  "copyFeatures": {
    "title": "Копіювати об'єкти",
    "createFeatures": "Створити об'єкти",
    "createSingleFeature": "Створити 1 мультигеометричний об'єкт",
    "noFeaturesSelectedMessage": "Об'єкти не вибрано",
    "selectFeatureToCopyMessage": "Виберіть об'єкти для копіювання."
  },
  "addingFeatureError": "Помилка під час додавання вибраних об'єктів в шарі. Спробуйте знову.",
  "addingFeatureErrorCount": "Не вдалося копіювати '${copyFeatureErrorCount}' об'єктів.",
  "selectingFeatureError": "Помилка під час вибору об'єктів в шарі. Спробуйте знову.",
  "customSelectOptionLabel": "Виберіть об'єкти для копіювання",
  "noFeatureSelectedMessage": "Об'єкти не вибрано.",
  "multipleFeatureSaveMessage": "Всі об'єкти будуть зразу збережені. Бажаєте продовжити?"
});