define({
  "gridTabLabel": "Ruudustik",
  "labelTabLabel": "Märgised",
  "referenceSystemTabLabel": "Viitesüsteem",
  "gridTabDescription": "Määrake võrgustiku ruutude väljanägemine.",
  "cellOutlineColor": "Ruudu kontuurivärv",
  "cellFillColor": "Ruudu täitevärv",
  "transparency": "Läbipaistvus",
  "cellShapeDropDown": "Ruudu kuju",
  "default": "Nelinurk",
  "hexagon": "Kuusnurk",
  "cellUnitsDropDown": "Ruudu mõõtühikud",
  "miles": "mi",
  "kilometers": "km",
  "feet": "ft",
  "meters": "m",
  "yards": "jardi",
  "nautical-miles": "meremiili",
  "gridOriginDropDown": "Ruudu päritolu",
  "lowerLeft": "All vasakul",
  "lowerRight": "All paremal",
  "upperLeft": "Üleval vasakul",
  "upperRight": "Üleval paremal",
  "center": "Keskel",
  "selectOpLayerLabel": "Tulemuste töökiht",
  "helpIconTooltip": "Töökihtide nimekiri sisaldab kihte praegusest veebikaardist, mis on polügooni tüüpi.",
  "labelTabDescription": "Määrake ruudustiku siltide ilme ja käitumine.",
  "labelSettings": "Sildi laad",
  "font": "Font",
  "textSize": "Teksti suurus",
  "textColor": "Teksti värv",
  "halo": "Halo",
  "show": "Kuva",
  "labelTypeDropDown": "Sildi tüüp",
  "alphaNumeric": "Tähed ja numbrid",
  "alphaAlpha": "Tähed ja tähed",
  "numeric": "Numbriline",
  "labelDirectionDropDown": "Sildi suund",
  "horizontal": "Horisontaalne",
  "vertical": "Vertikaalne",
  "labelOriginDropDown": "Sildi päritolu",
  "referenceSystemlTabDescription": "Määrake vaikimisi kasutatav referentssüsteem",
  "MGRS": "MGRS:",
  "USNG": "USNG",
  "lockSettings": "Lukusta seaded – kasutaja ei saa vidinas konfigureeritud sätteid muuta"
});