define({
  "showArcgisBasemaps": "Sertakan peta dasar Portal",
  "add": "Klik untuk Menambahkan Peta Dasar Baru",
  "edit": "Properti",
  "titlePH": "Judul Peta Dasar",
  "thumbnailHint": "Klik gambar untuk memperbarui",
  "urlPH": "URL Layer",
  "addlayer": "Tambahkan Peta Dasar",
  "warning": "Input salah",
  "save": "Kembali dan Simpan",
  "back": "Kembali dan Batalkan",
  "addUrl": "Tambahkan URL",
  "autoCheck": "Periksa Otomatis",
  "checking": "Memeriksa...",
  "result": "Berhasil disimpan",
  "spError": "Semua peta dasar yang ditambahkan ke galeri harus memiliki referensi spasial yang sama.",
  "invalidTitle1": "Peta dasar '",
  "invalidTitle2": "' sudah ada. Harap pilih judul lain.",
  "invalidBasemapUrl1": "Tipe layer ini tidak dapat digunakan sebagai peta dasar.",
  "invalidBasemapUrl2": "Peta dasar yang Anda tambahkan memiliki referensi spasial berbeda dari peta saat ini.",
  "addBaselayer": "Tambahkan Layer Peta Dasar",
  "repectOnline": "Selalu sinkronkan dengan pengaturan Galeri Peta Dasar organisasi",
  "customBasemap": "Konfigurasikan peta dasar khusus",
  "basemapTips": "Klik \"${import}\" atau \"${createNew}\" untuk menambah peta dasar.",
  "importBasemap": "Impor",
  "createBasemap": "Buat Baru",
  "importTitle": "Impor Peta Dasar",
  "createTitle": "Peta Dasar Baru",
  "selectGroupTip": "Pilih sebuah grup dengan webmap yang dapat dijadikan sebagai peta dasar.",
  "noBasemaps": "Tidak ada peta dasar.",
  "defaultGroup": "Default Esri",
  "defaultOrgGroup": "Default Organisasi",
  "warningTitle": "Peringatan",
  "confirmDelete": "Anda ingin menghapus peta dasar yang dipilih?",
  "noBasemapAvailable": "Tidak ada peta dasar tersedia atau semua peta dasar telah memiliki rujukan spasial berbeda dari peta saat ini."
});