define({
  "addTaskTip": "1 つ以上のフィルターをウィジェットに追加して、各フィルターのパラメーターを構成します。",
  "enableMapFilter": "Web マップに設定済みのフィルターを無効にする",
  "newFilter": "新しいフィルター",
  "filterExpression": "フィルターの条件式",
  "layerDefaultSymbolTip": "レイヤーのデフォルト シンボルの使用",
  "uploadImage": "画像のアップロード",
  "selectLayerTip": "レイヤーを選択してください。",
  "setTitleTip": "タイトルを設定してください。",
  "noTasksTip": "フィルターが構成されていません。\"${newFilter}\" をクリックして新しいフィルターを追加してください。",
  "collapseFiltersTip": "ウィジェットを開くときに、フィルター条件式 (存在する場合) を折りたたむ",
  "zoomtoTip": "フィルターの適用後に残りのフィーチャにズーム",
  "groupByLayerTip": "レイヤーでフィルターをグループ化",
  "autoApplyWhenValueInput": "値の入力後、このフィルターを自動的に適用",
  "autoApplyWhenWidgetOpen": "ウィジェットを開いたときに、このフィルターを適用",
  "info": "情報",
  "expressions": "式",
  "allowCustom": "カスタム フィルターの作成を許可",
  "filterActions": "カスタム フィルター アクション",
  "custom": "カスタム フィルターの有効化",
  "resetAll": "すべてをリセットの有効化",
  "turnOffAll": "すべてをオフの有効化",
  "matchMsgSetAll": "すべてのフィルターに一致するフィーチャを表示",
  "matchMsgSetAny": "いずれかのフィルターに一致するフィーチャを表示"
});