define({
  "_widgetLabel": "Tinklo trasavimas",
  "_featureAction_NetworkTraceSkip": "Praleisti trajektorijoje",
  "_featureAction_NetworkTraceUnskip": "Pašalinti iš praleistų padėčių",
  "removedFromSkipLocations": "Pašalinta iš praleistų padėčių",
  "alreadyRemovedFromSkipLocations": "Jau pašalinta iš praleistų padėčių",
  "locationSkipped": "Padėtis praleista",
  "configError": "Valdiklis netinkamai sukonfigūruotas.",
  "geometryServiceURLNotFoundMSG": "Negalima gauti geometrijos paslaugos URL",
  "clearButtonValue": "Valyti",
  "GPExecutionFailed": "Trasavimo nepavyksta atlikti. Pabandykite dar kartą.",
  "backButtonValue": "Grįžti",
  "exportToCSVSuccess": "Eksportavimas į CSV sėkmingai atliktas.",
  "lblInputLocTab": "Įvesties padėtys",
  "lblBlockLocTab": "Bloko padėtys",
  "lblInputLocation": "Įvesties elementas",
  "lblBlockLocation": "Bloko elementas",
  "lblInputLocHeader": "Įvesties padėtys (0)",
  "lblBlockLocHeader": "Bloko padėtys (0)",
  "inputTabTitle": "Įvestis",
  "outputTabTitle": "Išvestis",
  "exportSelectAllCheckBoxLabel": "Žymėti viską",
  "lblSkipLocHeader": "Praleisti padėtis (0)",
  "lblSkipLocation": "Padėtis",
  "lblSkipLocTab": "Praleisti padėtis",
  "skipAllLocationButtonLabel": "Praleisti visas padėtis",
  "confirmSkipAllLocationsMessage": "Visos padėtys bus praleistos, ar norite tęsti?",
  "locationAlreadySkippedMessage": "Padėtis jau praleista",
  "removeAllSkipLocationLabel": "Šalinti viską",
  "newProjectOptionText": "Naujas projektas",
  "selectProject": "Pasirinkti projektą",
  "saveButtonLabel": "Išsaugoti",
  "exportToCSVText": "Eksportuoti į CSV",
  "editProjectAttributesToolTip": "Redaguoti projekto atributus",
  "projectNameLabel": "Projekto pavadinimas",
  "saveProjectPopupTitle": "Išsaugoti",
  "saveAsLabel": "Išsaugoti kaip",
  "saveChangesMsg": "Norite išsaugoti pakeitimus <b>${loadProjectDropdownlabel}</b> ar įrašyti kaip naują projektą?",
  "creatingNewProjectErrorMessage": "Kuriant naują projektą įvyko klaida. Pabandykite dar kartą.",
  "projectNameFetchingErr": "Gaunant esamų projektų pavadinimus įvyko klaida. Pabandykite dar kartą.",
  "projectAttributeLoadingErr": "Įkeliant projekto atributus įvyko klaida. Pabandykite dar kartą.",
  "attributeUpdatedMsg": "Atributai atnaujinti sėkmingai.",
  "projectAttributeUpdatingErr": "Atnaujinant projekto atributus įvyko klaida.",
  "loadingProjectDetailsErrorMessage": "Gaunant vėliavėles, kliūtis ir padėčių praleidimą įvyko klaida. Pabandykite dar kartą.",
  "savingProjectDetailsErr": "Įrašant projekto išsamią informaciją įvyko klaida. Pabandykite įrašyti projektą dar kartą.",
  "updatingOutagePolygonErr": "Atnaujinant nutrūkimo poligoną įvyko klaida. Pabandykite įrašyti projektą dar kartą.",
  "deletingExistingPolygonErr": "Ištrinant esamą nutrūkimo poligoną įvyko klaida. Pabandykite įrašyti projektą dar kartą.",
  "loadingProjectFeaturesErr": "Įkeliant projekto elementus įvyko klaida. Pabandykite įkelti projektą dar kartą.",
  "addingProjectFeaturesErr": "Įtraukiant projekto elementus įvyko klaida. Pabandykite įrašyti projektą dar kartą.",
  "deletingExistingProjectFeaturesErr": "Ištrinant esamus projekto elementus įvyko klaida. Pabandykite įrašyti projektą dar kartą.",
  "projectNotFoundErr": "Projektas nerastas",
  "projectLayersNotFound": "Žemėlapyje nėra sukonfigūruotų projekto nustatymų sluoksnių. Valdiklis bus įkeltas eskizo režimu.",
  "fetchingOutagePolygonMessage": "Gaunant nutrūkimo poligoną įvyko klaida. Pabandykite įkelti projektą dar kartą.",
  "projectNameExistsMessage": "Projekto pavadinimas jau yra. Naudokite unikalų projekto pavadinimą.",
  "fetchingProjectNamesErrorMessage": "Gaunant esamų projektų pavadinimus įvyko klaida. Pabandykite įrašyti projektą dar kartą.",
  "enterProjectNameMessage": "Įveskite projekto pavadinimą.",
  "projectLengthErrorMessage": "Projekto pavadinimas negali būti ilgesnis nei",
  "gpServiceNotAccessible": "Jūsų paskyra neturi prieigos prie reikiamos paslaugos, kad būtų galima atlikti šį trasavimą.",
  "loadingClonedLayerErrorMessage": "Įkeliant klonuotą elementų sluoksnį įvyko klaida. Pabandykite dar kartą.",
  "addingFeatureInClonedLayerError": "Į klonuotą elementų sluoksnį įtraukiant grafinius elementus įvyko klaida. Pabandykite dar kartą.",
  "selectingFeatureInClonedLayerError": "Klonuotame elementų sluoksnyje pasirenkant grafinius elementus įvyko klaida. Pabandykite dar kartą.",
  "filteredProjectError": "Tikrinant gaunamą filtruotą projekto išsamią informaciją įvyko klaida. Pabandykite dar kartą.",
  "filteredProjectMessage": "Pasirinkti projekto atributai nepasiekiami dėl pritaikytų filtrų, nurodytų internetiniame žemėlapyje arba kitame valdiklyje. Išvalykite filtrą (-us) ir bandykite dar kartą.",
  "filteredProjectLoadMessage": "Jūsų projektas nebepasiekiamas. Pasirinkite aktyvų projektą.",
  "defaultValueForRunButton": "Vykdyti",
  "closeButtonLabel": "Panaikinti"
});