define({
  "businessAnalyst": "Business Analyst",
  "defineWhichInfographics": "Definišite koja infografika je dostupna u vidžetu:",
  "defineWhichReports": "Definišite koji izveštaji su dostupni u vidžetu:",
  "defaultValues": "Podrazumevane vrednosti:",
  "disable": "Onemogući",
  "driveTime": "Vreme vožnje",
  "infographics": "Infografika",
  "invalidValueRing": "Vrednost mora da bude u opsegu od 0 do 1.000.",
  "invalidValueDTWT": "Vrednost mora da bude u opsegu od 0 do 300.",
  "km": "km",
  "miles": "milje",
  "minutes": "minuti",
  "radius": "Poluprečnik",
  "reports": "Izveštaji",
  "rings": "Prstenovi",
  "selectCountry": "Izaberite zemlju:",
  "thisEntryIsNotValid": "Unos nije validan.",
  "time": "Vreme",
  "walkTime": "Vreme pešačenja"
});