define({
  "tabs_section_Label": "Kortelės",
  "addTab": "Pridėti skirtuką",
  "layerName": "Sluoksnis",
  "layerType": "Analizės tipas",
  "layerLabel": "Žymė",
  "actions": "Veiksmai",
  "closest": "Artimiausias elementas",
  "proximity": "Artumas",
  "summary": "Santrauka",
  "select_lbl": "-- Pasirinkti --",
  "general_setting_Label": "Bendrieji parametrai",
  "units_text_lbl": "Atstumo vienetai",
  "miles": "Mylios",
  "kilometers": "Kilometrai",
  "feet": "Pėdos",
  "meters": "Metrai",
  "yards": "Jardai",
  "nauticalMiles": "Jūrmylės",
  "maximum_distance_lbl": "Artimiausio elemento maksimalus atstumas",
  "buffer_text_lbl": "Buferio žymė",
  "buffer_lbl": "Buferio atstumas",
  "buffer_max_lbl": "Maksimalus buferio atstumas",
  "buffer_min_lbl": "Minimalus buferio atstumas",
  "routing_checkBox": "Įgalinti maršrutų nustatymą",
  "weather_Label": "Oro sąlygų parinktys",
  "weather_checkBox": "Įtraukti informaciją apie oro sąlygas",
  "selectLayers": "Pasirinkti oro sąlygų sluoksnius",
  "currentlySelectedLayer": "Dabar pasirinkti meteorologiniai sluoksniai",
  "missingTabLabel": "Bent vienas skirtukas neturi žymės",
  "missingLayerInWebMap": "Darbinių sluoksnių nerasta.",
  "selectFields": "Pasirinkite laukus",
  "addField": "Pridėti lauką",
  "sum": "SUMA",
  "min": "MIN.",
  "max": "MAKS.",
  "avg": "VID.",
  "count": "KIEKIS",
  "area": "PLOTAS",
  "length": "ILGIS",
  "count_checkBox": "Rodyti elementų skaičių",
  "area_checkBox": "Rodyti ploto sumą",
  "length_checkBox": "Rodyti ilgio sumą",
  "max_records": "Pasiekta maksimali riba",
  "save_label": "Įrašyti parinktis",
  "save_checkbox": "Įjungti įrašymą",
  "csv_label": "CSV parinktys",
  "csv_checkbox": "Eksportuoti visus sluoksnio laukus",
  "display_label": "Rodymo parinktys",
  "display_checkbox": "Pateikti santraukos elementus",
  "must_select_template": "Pasirinkite vieną iš redagavimo šablonų įrašymo parinktyse.",
  "count_label": "Skaičiaus žymė",
  "area_label": "Ploto žymė",
  "length_label": "Ilgio žymė",
  "invalid_string_width": "Reikšmė per ilga. ",
  "layer_type_not_supported": "Sluoksnio tipas nepalaikomas: ",
  "groupedSummary": "Sugrupuoti skaičiavimai",
  "groupByField": "Grupuoti pagal lauką",
  "labelType": "Pridėti žymę",
  "prefix": "Kaip prefiksą",
  "suffix": "Kaip sufiksą",
  "need_group_field": "Norėdami nusatyti grupavimą pagal lauką, naudokite veiksmą Redaguoti.",
  "fieldTitle": "Laukas",
  "typeTitle": "Tipas",
  "actionsTitle": "Veiksmai"
});