define({
  "taskUrl": "URL adresa zadatka",
  "setTask": "Postavi",
  "setTaskPopupTitle": "Postavi zadatak",
  "validate": "Postavi",
  "inValidGPService": "Unesite važeći servis geoprocesiranja.",
  "noOutputParameterWithGeometryType": "Izabrana usluga za geoprocesiranje mora da ima bar jedan iz izlazni parametar sa navedenim geometrijskim tipom. Izaberite drugačiji servis geoprocesiranja.",
  "invalidOutputGeometry": "Izlazni tip geometrije za izabranu uslugu geoprocesiranja nije kompatibilan sa podešavanjima projekta. Rezultati usluge geoprocesiranja ne mogu da se sačuvaju.",
  "GPFeatureRecordSetLayerERR": "Unesite servis geoprocesiranja samo sa unosima tipa 'GPFeatureRecordSetLayer'.",
  "invalidInputParameters": "Broj ulaznih parametara je ili manji od 1 ili veći od 3. Unesite važeći servis geoprocesiranja.",
  "projectSetting": {
    "title": "Postavke projekta",
    "note": "Napomena: postavke projekta su opcione, kada se konfiguriše korisnik može da sačuva projekat u željenim slojevima veb mape sa oblastima nestanka mreže i ulaznim parametrima. Korisnik može da sačuva druge izlazne parametre iz grupe „Izlaz“ u kartici „Ulaz/izlaz“.",
    "projectPolygonLayer": "Sloj poligona projekta",
    "outputParameterName": "Ime izlaznog parametra",
    "projectPointLayer": "Tačkasti sloj projekta",
    "selectLabel": "Selektujte",
    "polygonLayerHelp": "<p>Prikazaće se sloj(evi) poligona sa sledećim uslovima:<br/><ul><li>Sloj mora da ima mogućnost uređivanja, tačnije „Kreiraj“, „Izbriši“ i „Ažuriraj“</li><li>Sloj mora da ima 2 polja sa tačnim nazivom i tipom podataka:</li><ul><li>naziv (string tip polja)</li><li>globalid (GlobalID tip polja)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>Prikazaće se sloj(evi) izlaznog poligona iz URL adrese zadatka<p/>",
    "pointLayerHelp": "<p>Prikazaće se tačkasti sloj(evi) sa sledećim uslovima:<br/><ul><li>Sloj mora da ima mogućnost uređivanja, tačnije „Kreiraj“, „Izbriši“ i „Ažuriraj“</li><li>Sloj mora da ima 2 polja sa tačnim nazivom i tipom podataka:</li><ul><li>inputtype (string tip polja)</li><li>projectid (GUID tip polja)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "Zastava",
    "barrier": "Barijera",
    "skip": "Preskoči",
    "title": "Ulaz/izlaz",
    "inputSettingsLabel": "Postavke ulaza",
    "outputSettingsLabel": "Postavke izlaza",
    "inputLabel": "Oznaka",
    "inputTooltip": "Opis alatke",
    "symbol": "Simbol",
    "typeText": "Tip",
    "outputParametersText": "Izlazni parametri",
    "saveToLayerText": "Sačuvaj u sloj (opciono)",
    "skipText": "Moguće preskočiti",
    "visibilityText": "Vidljivo",
    "exportToCsvText": "Izvezi u CSV",
    "exportToCsvDisplayText": "CSV",
    "settitngstext": "Postavke",
    "addFieldTitle": "Dodaj polje",
    "enterDisplayText": "Unesite tekst za prikaz",
    "setScale": "Podesi razmeru",
    "outputDisplay": "Tekst za prikaz",
    "saveToLayerHelp": "<p>Prikazaće se sloj sa sledećim uslovima:<br/><ul><li>Sloj mora da ima mogućnost uređivanja, tačnije „Kreiraj“, „Izbriši“ i „Ažuriraj“</li><li>Sloj mora da ima dva polja sa nazivom i tipom podataka:</li><ul><li>parametername (string tip polja)</li><li>projectid (Guid tip polja)</li><ul></ul><p/>"
  },
  "summaryTab": {
    "title": "Opšte postavke",
    "summaryFieldsetText": "Postavke rezimea",
    "inputOutput": "Ulaz/izlaz",
    "field": "Polje",
    "operator": "Operator",
    "inputOperatorCountOption": "Brojač",
    "outputOperatorCountOption": "Brojač",
    "outputOperatorSkipCountOption": "SkipCount",
    "fieldOperatorSumOption": "Zbir",
    "fieldOperatorMinOption": "Minimum",
    "fieldOperatorMaxOption": "Maksimum",
    "fieldOperatorMeanOption": "Sredina",
    "expressionAddButtonText": "Dodaj",
    "expressionVerifyButtonText": "Potvrdi",
    "summaryEditorText": "Tekst rezimea",
    "autoZoomAfterTrace": "Dodatne opcije",
    "zoomText": "Automatsko zumiranje nakon praćenja",
    "summarSettingTooltipText": "Dodaj broj ulaza/izlaza"
  },
  "validationErrorMessage": {
    "webMapError": "Nema dostupnih slojeva u veb mapi. Izaberite važeću veb mapu.",
    "inputTypeFlagGreaterThanError": "Ulaz tipa zastava ne može biti veći od jedan.",
    "inputTypeFlagLessThanError": "Obavezan je barem jedan ulaz tipa zastava.",
    "inputTypeBarrierErr": "Ulaz tipa barijera ne može biti veći od jedan.",
    "inputTypeSkipErr": "Ulaz tipa preskakanja ne može biti veći od jedan.",
    "displayTextForButtonError": "Tekst za prikaz za dugme 'Pokreni' ne može biti prazan.",
    "UnableToLoadGeoprocessError": "Učitavanje servisa geoprocesiranja nije moguće.",
    "invalidSummaryExpression": "Nevažeći izraz.",
    "validSummaryExpression": "Uspešno!",
    "invalidProjectSettings": "Nevažeće postavke projekta.<br/> Izaberite važeću vrednost u '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "Savet: obezbedite oznaku za prikaz za panel za rezultate izlaznog parametra.",
    "displayTextHint": "Napomena: to će biti prikazano u panelu sa detaljima za ovaj izlazni parametar.",
    "inputTextHint": "Savet: kreirajte gore pomenut izraz biranjem ulaza, izlaza i naziva polja.",
    "expressionHint": "Savet: izaberite stavke i kliknite na dodavanje da biste kreirali izraz."
  }
});