define({
  "_widgetLabel": "Katman Listesi",
  "titleBasemap": "Altlık haritaları",
  "titleLayers": "Operasyonel Katmanlar",
  "labelLayer": "Katman Adı",
  "itemZoomTo": "Şuna Yakınlaştır",
  "itemTransparency": "Saydamlık",
  "itemTransparent": "Saydam",
  "itemOpaque": "Opak",
  "itemMoveUp": "Yukarı taşı",
  "itemMoveDown": "Aşağı taşı",
  "itemDesc": "Açıklama",
  "itemDownload": "İndir",
  "itemToAttributeTable": "Öznitelik Tablosunu Aç",
  "itemShowItemDetails": "Öğe Ayrıntılarını Göster",
  "empty": "boş",
  "removePopup": "Açılır Pencereleri Devre Dışı Bırak",
  "enablePopup": "Açılan Pencereyi Etkinleştir",
  "turnAllLayersOff": "Tüm Katmanları Kapat",
  "turnAllLayersOn": "Tüm Katmanları Aç",
  "expandAllLayers": "Tüm Katmanları Genişlet",
  "collapseAlllayers": "Tüm Katmanları Daralt",
  "turnAllLabelsOff": "Tüm Etiketleri Kapat",
  "turnAllLabelsOn": "Tüm Etiketleri Aç",
  "showLabels": "Etiketleri Göster",
  "hideLables": "Etiketleri Gizle"
});