define(
   ({
    addLayer: "Kaartlaag toevoegen",
    layerName: "Kaartlaag",
    layerRefresh: "Vernieuwen",
    layerLabel: "Label",
    actions: "Acties",
    popupOk: "OK",
    popupCancel: "Annuleren",
    mainPanelTextPlaceholder: "ex: SNELWEGOMSTANDIGHEDEN",
    invalidInterval: "Alleen numerieke tekens worden ondersteund.",
    uploadImage: "Afbeelding uploaden",
    iconColumnText: "Pictogram",
    refreshInterval: "1 \'Beoordeeld als tijd in minuten\'",
    refreshIntervalTitle: "Beoordeeld als tijd in minuten",
    mainPanelText: "Tekst hoofdpaneel",
    mainPanelIcon: "Afbeelding hoofdpaneel",
    refreshIntervalInstruction: "Vernieuwingsinterval",
    optionsText: "Opties",
    symbolOptionsText: "Symboolopties",
    iconOptionsText: "Pictogramopties",
    sympolPopupTitle: "Symbool instellen",
    rdoLayer: "Laagsymbool",
    rdoCustom: "Aangepast symbool",
    chkCluster: "Clustering inschakelen",
    defineClusterSymbol: "Clustersymbool",
    defineThemeClusterSymbol: "Clustersymbool van thema",
    rdoEsri: "Esri symbool",
    rdoLayerIcon: "Symbool gebruiken als pictogram",
    rdoCustomIcon: "Aangepast pictogram uploaden",
    editCustomSymbol: "Aangepast symbool bewerken",
    editCustomIcon: "Aangepast pictogram bewerken",
    missingRefreshValue: "Geef een nieuwe intervalwaarde op.",
    panelIconOption: "Kop van paneel weergeven",
    enableRefresh: "Laag vernieuwen inschakelen",
    disableRefresh: "Laag vernieuwen alleen ondersteund voor objectverzamelingen",
    layer_type_not_supported: "Laagtype wordt niet ondersteund: "
  })
);
