define({
  "_widgetLabel": "Synlighed",
  "observerLocation": "Observatørens placering",
  "formatIconTooltip": "Formatangivelse",
  "addPointToolTip": "Tilføj observatørplacering",
  "fieldOfView": "Synsfelt",
  "useMilsText": "Brug miles til vinkler",
  "observerHeight": "Observatørens højde",
  "minObsDistance": "Min. observerbar afstand",
  "maxObsDistance": "Maks. observerbar afstand",
  "taskURLError": "Widget’ens konfigurationsfil indeholder en URL, som ikke kan nås. Spørg din systemadministrator",
  "taskURLInvalid": "Den geoprocesseringsopgave, der er konfigureret med denne widget, er ikke gyldig. Spørg din systemadministrator",
  "viewshedError": "Der opstod en fejl under oprettelse af synlighed. Kontrollér, at din observatørplacering er inden for udstrækningen af din højdeoverflade.</p>",
  "validationError": "<p>Formularen til oprettelse af synlighed har manglende eller ugyldige parametre. Kontrollér følgende:</p><ul><li>Der er angivet en observatørplacering.</li><li>Observatørens synsfelt er ikke 0.</li><li>Observatørens højde indeholder en gyldig værdi.</li><li>Min. og maks. observationsafstandene indeholder gyldige værdier.</li></ul>",
  "comfirmInputNotation": "Bekræft input-notation",
  "notationsMatch": "notationer matcher dit input. Bekræft, hvilken du vil bruge:",
  "createBtn": "Opret",
  "clearBtn": "Ryd",
  "setCoordFormat": "Indstil koordinatformat-streng",
  "prefixNumbers": "Tilføj ’+/-’ præfikset til positive og negative tal",
  "parseCoordinatesError": "Kan ikke analysere koordinater. Kontrollér dit input.",
  "cancelBtn": "Annuller",
  "applyBtn": "Anvend",
  "invalidMessage": "Angiv en numerisk værdi.",
  "observerRangeMessage": "Ugyldig observatørhøjde",
  "minimumRangeMessage": "Ugyldigt minimalt observerbart område",
  "maximumRangeMessage": "Det maksimalt observerbare område skal være større end det minimalt observerbare område og kan ikke være større end ${limit} ${units}.",
  "portalURLError": "URL-adressen til din ArcGIS Online-organisation eller Portal for ArcGIS er ikke konfigureret. Tjek dette med din systemadministrator",
  "privilegeError": "Din brugerrolle kan ikke udføre analyse. For at du kan udføre analyse, skal din organisations administrator skal give dig bestemte <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">rettigheder</a>.",
  "noServiceError": "Højdeanalysetjenesten er ikke tilgængelig. Kontrollér dine ArcGIS Online-organisations- eller Portal for ArcGIS-konfigurationer.",
  "pointToolTooltip": "Klik for at tilføje observatørplacering",
  "degreesLabel": "grader",
  "milsLabel": "miles",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalgrader - Breddegrad/Længdegrad",
  "DDLongLatNotation": "Decimalgrader - Længdegrad/Breddegrad",
  "DDMLatLongNotation": "Grader Decimal Minutter - Breddegrad/Længdegrad",
  "DDMLongLatNotation": "Grader Decimal Minutter - Længdegrad/Breddegrad",
  "DMSLatLongNotation": "Grader Minutter Sekunder - Breddegrad/Længdegrad",
  "DMSLongLatNotation": "Grader Minutter Sekunder - Længdegrad/Breddegrad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Bånd Bogstav",
  "UTMHemNotation": "UTM - Hemisfære (N/S)",
  "mainPageTitle": "Radial synslinje",
  "resultsTitle": "Resultater",
  "publishBtnLabel": "Publicér",
  "layerName": "Navn på publiceret lag",
  "invalidLayerName": "Lagnavnet må kun indeholde alfanumeriske tegn og understregninger",
  "missingLayerName": "Indtast navn på laget",
  "back": "Bagside",
  "publishingFailedLayerExists": "Publicering mislykkedes: Du har allerede en featuretjeneste med navnet {0}. Vælg et andet navn.",
  "checkService": "Kontroller tjeneste: {0}",
  "createService": "Opret tjeneste: {0}",
  "unableToCreate": "Kan ikke oprette: {0}",
  "addToDefinition": "Tilføj til definition: {0}",
  "successfullyPublished": "Weblag er oprettet{0}Administrér weblaget",
  "userRole": "Kan ikke oprette tjenesten, fordi brugeren ikke har tilladelser",
  "publishToNewLayer": "Publicér resultater til et nyt vektorlag",
  "missingLayerNameMessage": "Du skal indtaste et gyldigt lag-navn, før du kan publicere.",
  "regionTypeLabel": "Regionstype",
  "centerPointLabel": "Centerpunkt",
  "observationHeightLabel": "Observationshøjde",
  "heightUnitLabel": "Højdeenhed",
  "minObservationDistanceLabel": "MinObservation-afstand",
  "maxObservationDistance": "MaxObservation-afstand",
  "distanceUnitLabel": "Afstandsenhed",
  "fovstartAngleLabel": "FOV-startvinkel",
  "fovEndAngleLabel": "FOV-slutvinkel",
  "andleUnitsLabel": "Vinkel-enheder"
});