define({
  "chartSettingLabel": "Grafik ayarları",
  "addNewLabel": "Yeni ekle",
  "generalSettingLabel": "Genel ayarlar",
  "layerChooser": {
    "title": "Grafiği oluşturulacak katmanı seç",
    "selectPolygonLayerLabel": "Katman seç",
    "selectPolygonLayerHintText": "İpucu: Birden çok grafik yapılandırılırken, katmanlar aynı geometri türünde olmalıdır",
    "selectRelatedTableLayerLabel": "Katmanla ilişkili tabloyu seç",
    "selectRelatedTableLayerHintText": "İpucu: Yalnızca sayısal alana sahip tablolar görüntülenir",
    "errorInSelectingPolygonLayer": "İlişkili nokta katmanına sahip bir katman seçin.",
    "errorInSelectingRelatedLayer": "Katman için geçerli ilişkiye sahip bir tablo/katman seçin.",
    "polygonLayerNotHavingRelationships": "Seçilen katmanın ilişkili tablosu/katmanı yok."
  },
  "ChartSetting": {
    "sectionTitle": "Bölüm başlığı",
    "sectionTitleHintText": "İpucu: Bölüm başlığı üstbilgisinde görüntülenir",
    "chartTitle": "Grafik başlığı",
    "chartTitleHintText": "İpucu: Grafiğin en üstünde ortalanmış olarak görüntülenir",
    "chartDescription": "Açıklama",
    "chartDescriptionHintText": "İpucu: Grafiğin altında görüntülenir",
    "chartType": "Grafik türü",
    "barChart": "Çubuk grafik",
    "pieChart": "Pasta grafik",
    "polarChart": "Kutup grafiği",
    "dataSeriesField": "Veri serisi alanı",
    "labelField": "Etiket alanı",
    "chartColor": "Grafik rengi",
    "singleColor": "Tek renk",
    "colorByTheme": "Temaya göre renk",
    "colorByFieldValue": "Alan değerine göre renk",
    "xAxisTitle": "X ekseni başlığı",
    "xAxisHintText": "İpucu: X ekseni başlığı",
    "yAxisTitle": "Y ekseni başlığı",
    "yAxisHintText": "İpucu: Y ekseni başlığı",
    "fieldColorLabel": "Etiket",
    "fieldColorColor": "Renk",
    "defaultFieldSelectLabel": "Seç",
    "errMsgFieldValuesNotFound": "Seçilen alan için değer bulunamıyor",
    "errMsgSectionTitle": "Bölüm başlığını girin",
    "errMsgFieldByValue": "Alan değerini seçin",
    "settingTabTitle": "Ayarlar",
    "layoutTabTitle": "Düzen",
    "polarChartSelectFieldsHintText": "İpucu: Kutup grafiği oluşturmak için alan seçin",
    "visibilityText": "Görünürlük",
    "fieldNameText": "Alan Adı",
    "aliasNameText": "Takma Ad",
    "errMsgPolarFieldsRequired": "Kutup grafiği oluşturmak için üç veya daha fazla alan seçin",
    "polarChartPolygonFillLabel": "Alanı doldur",
    "polarChartPolygonFillHintText": "İpucu: Kutup grafiğinde alan dolgusu göstermek için onay kutusunu işaretleyin",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Çöl",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "İrlanda",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Sulak Alan",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Genel Ayarlar",
    "locationSymbolLabel": "Grafik konumu simgesi",
    "locationSymbolHintText": "İpucu: Adres ve tıklanan konum simgesini görüntülemek için kullanılır",
    "refreshIntervalLabel": "Yenileme aralığı",
    "refreshIntervalHintText": "İpucu: Bu aralığa göre grafikleri yenilemek için kullanılır. 1 - 1440 dakika arasında bir değer belirtin",
    "errMsgRefreshInterval": "0 - 1440 dakika arasında bir yenileme aralığı değeri belirtin",
    "symbolPickerPreviewText": "Önizleme:"
  }
});