define({
  "_widgetLabel": "Pelacakan Jaringan",
  "_featureAction_NetworkTraceSkip": "Lewati dalam Pelacakan",
  "_featureAction_NetworkTraceUnskip": "Hapus dari lewati lokasi",
  "removedFromSkipLocations": "Dihapus dari lewati lokasi",
  "alreadyRemovedFromSkipLocations": "Sudah dihapus dari lewati lokasi",
  "locationSkipped": "Lokasi dilewati",
  "configError": "Widget tidak dikonfigurasi dengan baik.",
  "geometryServiceURLNotFoundMSG": "Tidak dapat memperoleh URL Service Geometri",
  "clearButtonValue": "Hapus",
  "GPExecutionFailed": "Pelacakan tidak dapat diselesaikan. Harap coba lagi.",
  "backButtonValue": "Kembali",
  "exportToCSVSuccess": "Ekspor ke CSV berhasil diselesaikan.",
  "lblInputLocTab": "Input Lokasi",
  "lblBlockLocTab": "Blokir Lokasi",
  "lblInputLocation": "Input Fitur",
  "lblBlockLocation": "Blokir Fitur",
  "lblInputLocHeader": "Input Lokasi (0)",
  "lblBlockLocHeader": "Blokir Lokasi (0)",
  "inputTabTitle": "Input",
  "outputTabTitle": "Output",
  "exportSelectAllCheckBoxLabel": "Pilih Semua",
  "lblSkipLocHeader": "Lewati Lokasi (0)",
  "lblSkipLocation": "Lokasi",
  "lblSkipLocTab": "Lewati Lokasi",
  "skipAllLocationButtonLabel": "Lewati Semua Lokasi",
  "confirmSkipAllLocationsMessage": "Semua lokasi akan dilewati, ingin melanjutkan?",
  "locationAlreadySkippedMessage": "Lokasi sudah dilewati",
  "removeAllSkipLocationLabel": "Hapus Semua",
  "newProjectOptionText": "Proyek Baru",
  "selectProject": "Pilih Proyek",
  "saveButtonLabel": "Simpan",
  "exportToCSVText": "Ekspor ke CSV",
  "editProjectAttributesToolTip": "Edit Atribut Proyek",
  "projectNameLabel": "Nama Proyek",
  "saveProjectPopupTitle": "Simpan",
  "saveAsLabel": "Simpan Sebagai",
  "saveChangesMsg": "Ingin menyimpan perubahan Anda ke <b>${loadProjectDropdownlabel}</b> atau simpan sebagai proyek baru?",
  "creatingNewProjectErrorMessage": "Kesalahan saat membuat proyek baru. Harap coba lagi.",
  "projectNameFetchingErr": "Kesalahan saat mengambil proyek yang ada. Harap coba lagi.",
  "projectAttributeLoadingErr": "Kesalahan saat memuat atribut proyek. Harap coba lagi.",
  "attributeUpdatedMsg": "Atribut berhasil diperbarui.",
  "projectAttributeUpdatingErr": "Kesalahan saat memperbarui atribut proyek.",
  "loadingProjectDetailsErrorMessage": "Kesalahan saat mengambil bendera, penghalang, dan lewati lokasi. Harap coba lagi.",
  "savingProjectDetailsErr": "Kesalahan saat menyimpan detail proyek. Harap coba menyimpan proyek kembali.",
  "updatingOutagePolygonErr": "Kesalahan saat memperbarui poligon pemadaman. Harap coba menyimpan proyek kembali.",
  "deletingExistingPolygonErr": "Kesalahan saat menghapus poligon pemadaman yang ada. Harap coba menyimpan proyek kembali.",
  "loadingProjectFeaturesErr": "Kesalahan saat memuat fitur proyek. Harap coba memuat proyek kembali.",
  "addingProjectFeaturesErr": "Kesalahan saat menambahkan fitur proyek. Harap coba menyimpan proyek kembali.",
  "deletingExistingProjectFeaturesErr": "Kesalahan saat menghapus fitur proyek yang ada. Harap coba menyimpan proyek kembali.",
  "projectNotFoundErr": "Proyek tidak ditemukan",
  "projectLayersNotFound": "Layer Pengaturan Proyek yang Dikonfigurasi tidak tersedia di peta. Widget akan dimuat dalam 'Mode sketsa'.",
  "fetchingOutagePolygonMessage": "Kesalahan saat mengambil poligon pemadaman. Harap coba memuat proyek kembali.",
  "projectNameExistsMessage": "Nama proyek sudah ada. Harap gunakan nama proyek unik.",
  "fetchingProjectNamesErrorMessage": "Kesalahan saat mengambil proyek yang ada. Harap coba menyimpan proyek kembali.",
  "enterProjectNameMessage": "Harap masukkan nama proyek.",
  "projectLengthErrorMessage": "Nama proyek tidak boleh lebih besar dari",
  "gpServiceNotAccessible": "Akun Anda tidak memiliki akses ke layanan yang diperlukan untuk melakukan pelacakan ini.",
  "loadingClonedLayerErrorMessage": "Kesalahan saat memuat feature layer yang diklon. Harap coba lagi.",
  "addingFeatureInClonedLayerError": "Kesalahan saat menambahkan grafik ke feature layer yang diklon. Harap coba lagi.",
  "selectingFeatureInClonedLayerError": "Kesalahan saat memilih grafik di feature layer yang diklon. Harap coba lagi.",
  "filteredProjectError": "Kesalahan saat memeriksa pengambilan detail proyek yang difilter. Harap coba lagi.",
  "filteredProjectMessage": "Atribut proyek pilihan tidak tersedia karena filter yang diterapkan dari webmap atau widget lainnya. Hapus filter dan coba lagi.",
  "filteredProjectLoadMessage": "Proyek Anda tidak lagi tersedia. Harap pilih proyek aktif.",
  "defaultValueForRunButton": "Jalankan",
  "closeButtonLabel": "Hapus"
});