define({
  "addTaskTip": "Lisage vidinale filtreid ja konfigureerige iga filtri parameetrid.",
  "enableMapFilter": "Saate eelseatud kihifiltri kaardilt eemaldada.",
  "newFilter": "Uus filter",
  "filterExpression": "Filtri avaldis",
  "layerDefaultSymbolTip": "Kasuta kihi vaikesümbolit",
  "uploadImage": "Laadi üles pilt",
  "selectLayerTip": "Valige kiht.",
  "setTitleTip": "Määrake pealkiri.",
  "noTasksTip": "Ühtki filtrit pole konfigureeritud. Klõpsake uue filtri lisamiseks \"${newFilter}\".",
  "collapseFiltersTip": "Ahenda vidina avamise korral filtriavaldised (kui on olemas)",
  "zoomtoTip": "Pärast filtri rakendamist suumi ülejäänud objektidele",
  "groupByLayerTip": "Rühmita filtrid kihi järgi",
  "autoApplyWhenValueInput": "Rakenda see filter automaatselt pärast väärtuse sisestamist",
  "autoApplyWhenWidgetOpen": "Rakenda see filter, kui vidin avatakse",
  "info": "Teave",
  "expressions": "Avaldised",
  "allowCustom": "Luba luua kohandatud filtreid",
  "filterActions": "Kohanda filtri toimingud",
  "custom": "Luba kohandatud filtrid",
  "resetAll": "Luba kõige taaslähtestamine",
  "turnOffAll": "Luba kõige väljalülitamine",
  "matchMsgSetAll": "Kuva objektid, mis vastavad kõigile filtritele",
  "matchMsgSetAny": "Kuva objektid, mis vastavad mõnele filtrile"
});