define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "إضافة نقطة بالنقر فوق الخريطة",
  "addRingsDtWt": "إضافة حلقات أو وقت قيادة أو وقت سير.",
  "apply": "تطبيق",
  "back": "الخلف",
  "colon": ":",
  "creditInformation": "معلومات بيانات الاعتماد",
  "driveTime": "وقت القيادة",
  "esriInfographics": "مخططات Esri للمعلومات البيانية",
  "esriReports": "تقارير Esri",
  "headerDescription_km": "كيلومتر",
  "headerDescription_miles": "ميل",
  "headerDescription_minutes": "دقيقة",
  "infographics": "إنفوجرافكس",
  "invalidValueRing": "يجب أن تكون القيم ضمن نطاق من 0 إلى 1000.",
  "invalidValueDTWT": "يجب أن تكون القيم ضمن نطاق من 0 إلى 300.",
  "km": "كيلومتر",
  "miles": "أميال",
  "minutes": "دقائق",
  "myInfographics": "مخططات المعلومات البيانية الخاصة بي",
  "myReports": "التقارير خاصتي",
  "noPermissions": "لا يستطيع حسابك تشغيل عنصر واجهة المستخدم Business Analyst. لتشغيل عنصر واجهة المستخدم Business Analyst، يحتاج مسؤول المؤسسة إلى منحك <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">امتيازات</a> GeoEnrichment وNetwork Analysis وأيضًا تخصيص <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">الاعتمادات</a>.",
  "geServiceNotConfigured": "لا يمكن تشغيل عنصر واجهة المستخدم Business Analyst في هذه البوابة، نظرًا لعدم تكوين خدمة <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenrichment</a> عليها.",
  "dirRoutingServiceNotConfigured": "لا يمكن تشغيل عنصر واجهة المستخدم Business Analyst في هذه البوابة، نظرًا لعدم تكوين خدمة <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">الاتجاهات والتوجيه</a> عليها.",
  "geAndDirRoutingServicesNotConfigured": "لا يمكن تشغيل عنصر واجهة المستخدم Business Analyst في هذه البوابة، نظرًا لعدم تكوين خدمات <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenrichment</a> and <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">الاتجاهات والتوجيه</a> عليها.",
  "radii": "أنصاف الأقطار",
  "radius": "نصف القطر",
  "radius_lowercase": "نصف القطر",
  "reports": "تقارير",
  "ring": "حلقة",
  "rings": "حلقات",
  "runInfographic": "تشغيل مخطط المعلومات البيانية",
  "runReport": "تشغيل التقرير",
  "selectPointOrPolygon": "حدد معلم نقطة أو مضلع على الخريطة وابحث عن عنوان أو مكان أو ضع دبوسًا على الخريطة لعرض المزيد من المعلومات حول المناطق.",
  "selectReport": "تحديد تقرير",
  "selectTemplate": "تحديد قالب",
  "sharedInfographics": "مخططات المعلومات البيانية المشتركة",
  "sharedReports": "التقارير المشتركة",
  "thisEntryIsNotValid": "هذا الإدخال غير صالح.",
  "time": "الوقت",
  "walkTime": "زمن السير",
  "widgetDescription": "صِل إلى مخططات المعلومات البيانية والتقارير التي تلخص المؤشرات الرئيسية والبيانات لأي منطقة.",
  "None": "تحديد..."
});