define({
  "styleText": "スワイプ ツールのスタイルを選択",
  "vertical": "垂直バー",
  "horizontal": "水平バー",
  "scope": "スパイグラス (のぞき窓)",
  "barColor": "バーの色",
  "swipeMode": "スワイプ モード",
  "singleLayer": "単一レイヤー",
  "MultipleLayers": "複数レイヤー",
  "allowToSwipe": "スワイプを許可",
  "layer": "レイヤー",
  "swipeByDefault": "デフォルトでスワイプ",
  "defaultLayerMustBeVisible": "デフォルトのレイヤーは表示可能である必要があります",
  "noDefaultLayer": "レイヤーをデフォルトでスワイプするように設定してください。",
  "defaultLayerHolder": "クリックして選択",
  "selectLayers": "レイヤーの選択",
  "layerText": "デフォルトでスワイプするレイヤーを選択",
  "spyglassText": "デフォルトでスパイグラス内に表示されるレイヤーを選択してください。",
  "layerHint": "注意: レイヤーが上に重なっているレイヤーによって隠れている場合、スワイプは機能しません。",
  "isZoom": "スワイプ レイヤーにズーム",
  "isZooms": "スワイプ レイヤーにズーム",
  "layersAvailable": "スワイプするレイヤーの選択:"
});