define({
  "_widgetLabel": "מנתח עסקי",
  "addPoint": "הוסף נקודה בלחיצה על המפה",
  "addRingsDtWt": "הוסף טבעות, זמן נסיעה או זמן הליכה.",
  "apply": "בצע",
  "back": "חזור",
  "colon": ":",
  "creditInformation": "נתוני קרדיט",
  "driveTime": "זמן נסיעה",
  "esriInfographics": "אינפוגרפיקה של Esri",
  "esriReports": "דוחות של Esri",
  "headerDescription_km": "קילומטר",
  "headerDescription_miles": "מייל",
  "headerDescription_minutes": "דקה",
  "infographics": "אינפוגרפיקה",
  "invalidValueRing": "הערכים חייבים להיות בטווח של 0 עד 1,000.",
  "invalidValueDTWT": "הערכים חייבים להיות בטווח של 0 עד 300.",
  "km": "ק\"מ",
  "miles": "מיילים",
  "minutes": "דקות",
  "myInfographics": "האינפוגרפיקה שלי",
  "myReports": "הדוחות שלי",
  "noPermissions": "לחשבון שלך אין אפשרות להפעיל את הווידג'ט 'מנתח עסקי'.  כדי להפעיל את הווידג'ט 'מנתח עסקי', על מנהל המערכת בארגון להעניק לך את <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">ההרשאות</a>, 'העשרה מרחבית' ו'ניתוח רשת' וכן להקצות לך <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">קרדיטים</a>.",
  "radii": "רדיוסים",
  "radius": "רדיוס",
  "radius_lowercase": "רדיוס",
  "reports": "דוחות",
  "ring": "טבעת",
  "rings": "טבעות",
  "runInfographic": "הפעל איפוגרפיקה",
  "runReport": "הפעל דוח",
  "selectPointOrPolygon": "בחר ישות נקודה או פוליגון על המפה, חפש כתובת או מקום, או מקם סיכה על המפה כדי להציג מידע נוסף על אזורים.",
  "selectReport": "בחר דוח",
  "selectTemplate": "בחר תבנית",
  "sharedInfographics": "אינפוגרפיקה משותפת",
  "sharedReports": "דוחות משותפים",
  "thisEntryIsNotValid": "ערך זה אינו חוקי.",
  "time": "שעה",
  "walkTime": "זמן הליכה",
  "widgetDescription": "גש לאינפוגרפיקה ולדוחות המסכמים מדדים ונתונים מרכזיים של אזור כלשהו.",
  "None": "בחר..."
});