define({
  "_widgetLabel": "Lista de Camadas",
  "titleBasemap": "Mapas base",
  "titleLayers": "Camadas Operacionais",
  "labelLayer": "Nome da Camada",
  "itemZoomTo": "Efetuar zoom para",
  "itemTransparency": "Transparência",
  "itemTransparent": "Transparente",
  "itemOpaque": "Opaco",
  "itemMoveUp": "Mover para cima",
  "itemMoveDown": "Mover para baixo",
  "itemDesc": "Descrição",
  "itemDownload": "Descarregar",
  "itemToAttributeTable": "Abrir tabela de atributos",
  "itemShowItemDetails": "Mostrar Detalhes do Item",
  "empty": "vazio",
  "removePopup": "Desactivar Pop-up",
  "enablePopup": "Ativar Janela Pop-up",
  "turnAllLayersOff": "Desativar Todas as Camadas",
  "turnAllLayersOn": "Ativar Todas as Camadas",
  "expandAllLayers": "Expandir Todas as Camadas",
  "collapseAlllayers": "Fechar Todas as Camadas",
  "turnAllLabelsOff": "Desativar Todos os Rótulos",
  "turnAllLabelsOn": "Ativar Todos os Rótulos",
  "showLabels": "Exibir Rótulos",
  "hideLables": "Ocultar Rótulos"
});