define({
  "_widgetLabel": "Діаграма",
  "executeChartTip": "Виберіть один з наступних елементів задачі для складання діаграми.",
  "invalidConfig": "Недійсна конфігурація.",
  "noneChartTip": "Задачу складання діаграми не налаштовано для цього віджету.",
  "chartParams": "Опції",
  "charts": "ДІАГРАМИ",
  "apply": "ЗАСТОСУВАТИ",
  "useSpatialFilter": "Використовувати просторовий фільтр для обмеження об'єктів",
  "useCurrentMapExtent": "Тільки об'єкти, які перетинають поточну область карти",
  "drawGraphicOnMap": "Тільки об'єкти, які перетинають визначену користувачем область",
  "chartResults": "Відобразити результати на діаграмі",
  "clearResults": "Очистити результати",
  "noPermissionsMsg": "Ви не маєте дозволу на доступ до цього сервісу.",
  "specifySpatialFilterMsg": "Задайте просторовий фільтр для цієї задачі.",
  "queryError": "Запит не вдалося виконати.",
  "noResults": "Об'єкт не знайдено.",
  "category": "Категорія",
  "count": "Лічильник",
  "label": "Напис",
  "horizontalAxis": "Горизонтальна вісь",
  "verticalAxis": "Вертикальна вісь",
  "dataLabels": "Написи даних",
  "color": "Колір",
  "colorful": "Кольоровий",
  "monochromatic": "Монохромний",
  "tasks": "Задачі",
  "results": "Результати",
  "applySpatialFilterToLimitResults": "Застосувати просторовий фільтр для обмеження результатів",
  "useCurrentExtentTip": "Частково чи повністю в межах поточного екстенту карти",
  "useDrawGraphicTip": "Частково чи повністю в межах форми, намальованої на карті",
  "useFeaturesTip": "На основі їх місць розташування відносно об'єктів у іншому шарі",
  "noSpatialLimitTip": "Просторово не обмежувати результати",
  "applySearchDistance": "Застосувати відстань пошуку",
  "spatialRelationship": "Просторове відношення",
  "relatedLayer": "Пов’язаний шар",
  "clear": "Очистити",
  "bufferDistance": "Буферна відстань",
  "miles": "Милі",
  "kilometers": "Кілометри",
  "feet": "Фути",
  "meters": "Метри",
  "yards": "Ярди",
  "nauticalMiles": "Морські милі",
  "back": "Назад",
  "execute": "Застосувати",
  "backCharts": "Назад до діаграм",
  "backOptions": "Назад до опцій",
  "clearCharts": "Очистити всі діаграми"
});