define({
  "defaultAreaUnit": "Varsayılan Alan Birimi",
  "defaultLengthUnit": "Varsayılan Uzunluk Birimi",
  "acres": "İngiliz Dönümü",
  "sqMiles": "Mil Kare",
  "sqKilometers": "Kilometre Kare",
  "hectares": "Hektar",
  "sqYards": "Yarda Kare",
  "sqFeet": "Fit Kare",
  "sqMeters": "Metre Kare",
  "miles": "Mil",
  "kilometers": "Kilometre",
  "feet": "Fit",
  "meters": "Metre",
  "yards": "Yarda",
  "nauticalMiles": "Deniz Mili",
  "showArea": "Alan",
  "showDistance": "Mesafe",
  "showLocation": "Konum",
  "showtools": "Ölçüm araçlarını göster:",
  "allHidedTips": "En az bir araç seçilmelidir."
});