define({
  "_widgetLabel": "Ανάλυση απειλής",
  "threatAnalysisMainPageTitle": "Με βάση τον Οδηγό καταπολέμησης της τρομοκρατίας της JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Καταχώριση τοποθεσίας",
  "interactive": "Διαδραστικά",
  "fromCoord": "Σταθερή συντεταγμένη",
  "existingFeature": "Από υπάρχοντα στοιχεία",
  "threatAnalysisCoordInputLabel": "Τοποθεσία απειλής",
  "enterCoords": "Εισαγάγετε συντεταγμένες",
  "threatAddPointToolTip": "Προσθήκη τοποθεσίας απειλής",
  "threatDrawPointToolTip": "Κάντε κλικ για να προσθέσετε τοποθεσία απειλής.",
  "threatType": "Τύπος απειλής",
  "threatPlaceholder": "Αρχίστε να πληκτρολογείτε ώστε να εκτελεστεί αναζήτηση για μια απειλή.",
  "mandatoryLabel": "Υποχρεωτική απόσταση εκκένωσης",
  "safeLabel": "Ασφαλής απόσταση εκκένωσης",
  "zoneTypeLabel": "Τύπος ζώνης",
  "feetLabel": "Πόδια",
  "metersLabel": "Μέτρα",
  "unitsLabel": "Μονάδες",
  "threatGraphicLayer": "Γραφικό απειλών",
  "settingsTitle": "Ρυθμίσεις",
  "mandatoryButtonLabel": "Διαμόρφωση ρυθμίσεων υποχρεωτικής απόστασης εκκένωσης",
  "safeButtonLabel": "Διαμόρφωση ρυθμίσεων τοπικού καταφυγίου",
  "style": "Στιλ",
  "colorPicker": "εργαλείο επιλογής χρώματος",
  "lineStyles": {
    "esriSLSDash": "Παύλα",
    "esriSLSDashDot": "Παύλα τελεία",
    "esriSLSDashDotDot": "Παύλα τελεία τελεία",
    "esriSLSDot": "Τελεία",
    "esriSLSLongDash": "Μεγάλη παύλα",
    "esriSLSLongDashDot": "Μεγάλη παύλα τελεία",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Μικρή παύλα",
    "esriSLSShortDashDot": "Μικρή παύλα τελεία",
    "esriSLSShortDashDotDot": "Μικρή παύλα τελεία τελεία",
    "esriSLSShortDot": "Μικρή τελεία",
    "esriSLSSolid": "Συμπαγές"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Προς τα πίσω",
    "esriSFSCross": "Σταυρός",
    "esriSFSDiagonalCross": "Διαγώνια",
    "esriSFSForwardDiagonal": "Προώθηση",
    "esriSFSHorizontal": "Οριζόντια",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Συμπαγές",
    "esriSFSVertical": "Κατακόρυφα"
  },
  "resultsTitle": "Αποτελέσματα",
  "publishTABtn": "Δημοσίευση",
  "layerName": "Όνομα δημοσιευμένου θεματικού επιπέδου",
  "invalidLayerName": "Το όνομα του θεματικού επιπέδου πρέπει να περιέχει μόνο αλφαριθμικούς χαρακτήρες και κάτω παύλες.",
  "missingLayerName": "Πρέπει να καταχωρίσετε όνομα για το θεματικό επίπεδο.",
  "missingLayerNameMessage": "Πρέπει να καταχωρίσετε έγκυρο όνομα θεματικού επιπέδου για να μπορέσετε να προχωρήσετε στη δημοσίευση.",
  "publishingFailedLayerExists": "Ανεπιτυχής δημοσίευση: Ήδη έχετε feature service με το όνομα {0}. Επιλέξτε κάποιο άλλο όνομα θεματικού επιπέδου.",
  "checkService": "Έλεγχος υπηρεσίας: {0}",
  "createService": "Δημιουργία υπηρεσίας: {0}",
  "unableToCreate": "Δεν είναι δυνατή η δημιουργία: {0}",
  "addToDefinition": "Προσθήκη στον ορισμό: {0}",
  "successfullyPublished": "Επιτυχής δημοσίευση θεματικού επιπέδου web{0}Διαχείριση του θεματικού επιπέδου web",
  "successfullyAppended": "Επιτυχής προσάρτηση νέων στοιχείων στο θεματικό επίπεδο web {0} Διαχείριση του θεματικού επιπέδου web",
  "userRole": "Δεν είναι δυνατή η δημιουργία υπηρεσίας επειδή ο χρήστης δεν έχει τα ανάλογα δικαιώματα.",
  "retrieveExistingLayerError": "Δεν είναι δυνατή η ανάκτηση του {0}. Προχωρήστε στη δημοσίευση χρησιμοποιώντας κάποιο άλλο όνομα θεματικού επιπέδου.",
  "publishToNewLayer": "Δημοσίευση αποτελεσμάτων σε νέο feature layer",
  "pipeBombLabel": "Βόμβα σε μεταλλικό σωλήνα",
  "suicideBombLabel": "Βόμβα αυτοκτονίας",
  "briefcaseLabel": "Χαρτοφύλακας",
  "carLabel": "Αυτοκίνητο",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Φορτηγάκι παραδόσεων",
  "containerWaterTruckLabel": "Φορτηγό με κοντέινερ/Υδροφόρα",
  "semiTrailerLabel": "Ημιρυμουλκούμενο φορτηγό",
  "transparencyLabel": "Διαφάνεια",
  "outline": "Περίγραμμα",
  "fill": "Γέμισμα (Το χρώμα εφαρμόζεται μόνο όταν έχετε καθορίσει τη χρήση του συμπαγούς στιλ.)",
  "createBtn": "Δημιουργία ζωνών",
  "clearBtn": "Εκκαθάριση",
  "invalidNumberMessage": "Η τιμή που καταχωρίσατε δεν είναι έγκυρη.",
  "invalidRangeMessage": "Η τιμή πρέπει να είναι μεγαλύτερη από το 0.",
  "parseCoordinatesError": "Δεν είναι δυνατή η ανάλυση των συντεταγμένων. Ελέγξτε τα στοιχεία που καταχωρίσατε.",
  "manualCoordinateInputInfo": "Μη αυτόματη καταχώριση συντεταγμένων και κλικ στην επιλογή <b>Καταχώριση</b> για εστίαση",
  "selectDrawModeLabel": "Επιλογή λειτουργίας σχεδίασης",
  "selectFeatureLabel": "Επιλογή στοιχείου από αυτό το θεματικό επίπεδο"
});