define({
  "_widgetLabel": "Téradatfeldolgozás",
  "_featureAction_ReceiveFeatureSet": "A következő bemeneteként való beállítás: ",
  "requiredInfo": "kötelező.",
  "drawnOnMap": "Az eredmény a térképen lesz ábrázolva.",
  "noToolConfig": "Nem érhető el előre konfigurált téradatfeldolgozási feladat.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Fájl feltöltése",
  "selectFileToUpload": "Válasszon fájlt…",
  "rasterFormat": "Raszteres adatformátum",
  "noFileSelected": "Nincs fájl kiválasztva!",
  "uploadSuccess": "Sikeres fájlfeltöltés!",
  "showLayerContent": "Réteg tartalmának megjelenítése",
  "invalidUrl": "Érvénytelen a vektoros adatszolgáltatás URL-címe",
  "urlPlaceholder": "Az adatokhoz való hozzáférésre szolgáló URL",
  "addShapefile": "Shapefile hozzáadása",
  "generateShapefileError": "Shapefile-létrehozási hiba, ellenőrizze a következőt: ",
  "cleared": "Az eredményt törölve lett.",
  "enlargeView": "Nézet nagyítása",
  "exportOutput": "Exportálás",
  "emptyResult": "Az eredmény üres.",
  "useSelectedFeatureset": "Az eredmény vektoros elem(ek) használata.",
  "closeSelectedFeatureset": "Törlés, és a konfigurált bemeneti opció használata.",
  "currentMapExtent": "Aktuális térképkiterjedés",
  "generalize": "Geometriák generalizálása",
  "jsonPlaceholder": "Az adatok JSON-karakterlánca",
  "chooseATable": "---Válasszon táblát---"
});