define({
  "searchTabTitle": "Cari pengaturan sumber",
  "routeTabTitle": "Pengaturan rute",
  "add": "Tambahkan sumber pencarian",
  "addGeocoder": "Tambahkan geocoder",
  "geocoder": "Geocoder",
  "setLayerSource": "Atur sumber layer",
  "setGeocoderURL": "Atur URL geocoder",
  "searchableLayer": "Feature layer",
  "name": "Nama",
  "countryCode": "Kode negara atau wilayah",
  "countryCodeEg": "mis., ",
  "countryCodeHint": "Membiarkan nilai ini kosong berarti akan mencari semua negara dan wilayah",
  "showInfoWindowOnSelect": "Tampilkan pop-up untuk fitur atau lokasi yang ditemukan",
  "showInfoWindowOnSelect2": "Tampilkan pop-up jika fitur atau lokasi ditemukan.",
  "searchInCurrentMapExtent": "Cari hanya dalam jangkauan peta saat ini",
  "setSearchFields": "Atur kolom pencarian",
  "set": "Atur",
  "fieldSearchable": "dapat dicari",
  "zoomScale": "Skala zoom",
  "locatorUrl": "URL Geocoder",
  "locatorName": "Nama geocoder",
  "locatorExample": "Contoh",
  "locatorWarning": "Versi layanan geocoding tidak didukung. Widget mendukung layanan geocoding 10.1 dan di atasnya.",
  "locatorTips": "Saran tidak tersedia karena layanan geocoding tidak mendukung kemampuan saran.",
  "layerSource": "Sumber layer",
  "searchLayerTips": "Saran tidak tersedia karena feature service tidak mendukung kemampuan penomoran halaman.",
  "placeholderText": "Teks placeholder",
  "searchFields": "Kolom pencarian",
  "displayField": "Kolom tampilan",
  "exactMatch": "Benar-benar cocok",
  "maxSuggestions": "Saran maksimum",
  "maxResults": "Hasil maksimum",
  "enableLocalSearch": "Aktifkan pencarian lokal",
  "minScale": "Skala min",
  "minScaleHint": "Apabila skala peta lebih besar daripada skala ini, pencarian lokal akan diterapkan",
  "radius": "Radius",
  "radiusHint": "Menentukan radius dari area di sekitar pusat peta saat ini yang digunakan untuk mendorong peringkat calon geocoding sehingga calon yang terdekat dengan lokasi akan dimunculkan terlebih dahulu",
  "invalidUrlTip": "URL ${URL} tidak valid atau tidak dapat diakses.",
  "routeUrl": "URL Rute",
  "geocoderOptions": "Opsi Geocoder",
  "autoComplete": "Selesaikan otomatis",
  "maximumSuggestions": "Saran maksimal",
  "minCharacters": "Karakter minimal",
  "searchDelay": "Cari penangguhan",
  "placeholder": "Placeholder",
  "routeOptions": "Opsi rute",
  "directionsLanguage": "Bahasa arahan",
  "directionsLengthUnits": "Unit panjang arahan",
  "directionsOutputType": "Tipe output arahan",
  "impedanceAttribute": "Atribut impedansi",
  "kilometers": "Kilometer",
  "miles": "Mil",
  "meters": "Meter",
  "feet": "Kaki",
  "yards": "Yard",
  "nauticalMiles": "Mil laut",
  "parametersTip": "Harap tetapkan parameter dengan benar !",
  "complete": "Selesai",
  "completeNoEvents": "Tidak Menyelesaikan Acara",
  "instructionsOnly": "Khusus instruksi",
  "standard": "Standar",
  "summaryOnly": "Khusus ringkasan",
  "travelModesUrl": "URL mode perjalanan",
  "searchPlaceholder": "Temukan alamat atau tempat",
  "trafficLayerUrl": "URL layer lalu lintas",
  "barrierLayerUrl": "URL layer penghalang",
  "presetDestinations": "Perhentian prasetel",
  "startPoint": "Titik mulai",
  "endPoint": "Titik selesai",
  "destinationHolder": "Alamat atau kordinat",
  "optional": "Opsional.",
  "barrierLayers": "Layer Penghalang",
  "pointBarrier": "Penghalang titik",
  "lineBarrier": "Penghalang garis",
  "polygonBarrier": "Penghalang poligon",
  "noPointBarrier": "Pilih penghalang titik",
  "noLineBarrier": "Pilih penghalang garis",
  "noPolygonBarrier": "Pilih penghalang poligon"
});