define({
  "addLayer": "Tilføj lag",
  "layerName": "Lag",
  "layerRefresh": "Opdatér",
  "layerLabel": "Mærke",
  "actions": "Handlinger",
  "mainPanelTextPlaceholder": "eks.: Senest opdateret:",
  "invalidInterval": "Kun numeriske tegn understøttes.",
  "uploadImage": "Overfør billede",
  "iconColumnText": "Visning",
  "refreshInterval": "Tid i minutter",
  "refreshIntervalTitle": "Evalueret som tid i minutter",
  "mainPanelText": "Hovedpaneltekst",
  "mainPanelIcon": "Hovedpanelbillede",
  "refreshIntervalInstruction": "Opdatér lag hver:",
  "optionsText": "Indstillinger",
  "symbolOptionsText": "Kortsymboler",
  "iconOptionsText": "Panelsymboler",
  "sympolPopupTitle": "Visningsindstillinger",
  "rdoLayer": "Standardsymbol",
  "rdoCustom": "Brug et billede",
  "chkCluster": "Aktivér klyngedannelse",
  "defineClusterSymbol": "Angiv klyngesymbol",
  "rdoEsri": "Vælg et symbol",
  "rdoLayerIcon": "Brug kortsymbol",
  "rdoCustomIcon": "Brug et billede",
  "editCustomSymbol": "Redigér brugerdefineret symbol",
  "editCustomIcon": "Redigér brugerdefineret ikon",
  "missingRefreshValue": "Angiv værdi for opdateringsinterval.",
  "panelIconOption": "Vis logobillede",
  "enableRefresh": "Aktivér opdatering af lag",
  "disableRefresh": "Opdatering af lag understøttes kun for objektsamlinger",
  "layer_type_not_supported": "Lagtype understøttes ikke: ",
  "refreshUnit": "minutter.",
  "symbolOptions": "Symbol",
  "panelFeatureDisplay": "Panel",
  "chkGroup": "Gruppér objekter",
  "selectField": "Felt",
  "fieldLabel": "Mærke",
  "addField": "Tilføj felt",
  "featureOptionsText": "Lagindstillinger",
  "groupOptionsText": "Gruppeindstillinger",
  "panelCountOption": "Vis objekttællinger",
  "rdoStack": "Vis ny linje for hvert felt",
  "rdoAppend": "Tilknyt felter på en enkelt linje",
  "missingLayerInWebMap": "Ingen operationelle lag fundet.",
  "displayClusterCnt": "Vis objekttælling",
  "defineClusterFont": "Angiv skrifttypefarve",
  "max_records": "Maksimal feltgrænse er nået"
});