define(
   ({
    addLayer: "Tilføj lag",
    layerName: "Lag",
    layerRefresh: "Opdatér",
    layerLabel: "Mærke",
    actions: "Handlinger",
    popupOk: "&quot;.prvs&quot; er en ugyldig fil til en enkeltbrugerautorisation.",
    popupCancel: "Annuller",
    mainPanelTextPlaceholder: "eks: MOTORVEJSFORHOLD",
    invalidInterval: "Kun numeriske tegn understøttes.",
    uploadImage: "Overfør billede",
    iconColumnText: "Ikon",
    refreshInterval: "1 \'Evalueret som tid i minutter\'",
    refreshIntervalTitle: "Evalueret som tid i minutter",
    mainPanelText: "Hovedpaneltekst",
    mainPanelIcon: "Hovedpanelbillede",
    refreshIntervalInstruction: "Opdateringsinterval",
    optionsText: "Indstillinger",
    symbolOptionsText: "Symbolindstillinger",
    iconOptionsText: "Ikonindstillinger",
    sympolPopupTitle: "Indstil symbol",
    rdoLayer: "Lagsymbol",
    rdoCustom: "Brugerdefineret symbol",
    chkCluster: "Aktivér klyngedannelse",
    defineClusterSymbol: "Klyngesymbol",
    defineThemeClusterSymbol: "Klyngesymbol fra tema",
    rdoEsri: "Esri-symbol",
    rdoLayerIcon: "Brug symbol som ikon",
    rdoCustomIcon: "Overfør brugerdefineret ikon",
    editCustomSymbol: "Redigér brugerdefineret symbol",
    editCustomIcon: "Redigér brugerdefineret ikon",
    missingRefreshValue: "Angiv værdi for opdateringsinterval.",
    panelIconOption: "Vis paneloverskrift",
    enableRefresh: "Aktivér opdatering af lag",
    disableRefresh: "Opdatering af lag understøttes kun for objektsamlinger",
    layer_type_not_supported: "Lagtype understøttes ikke: "
  })
);
