define({
  "chartSettingLabel": "Pengaturan grafik",
  "addNewLabel": "Tambah baru",
  "generalSettingLabel": "Pengaturan umum",
  "layerChooser": {
    "title": "Pilih layer untuk grafik",
    "selectPolygonLayerLabel": "Pilih layer",
    "selectPolygonLayerHintText": "Petunjuk: Jika mengonfigurasi beberapa grafik, layer harus berjenis geometri yang sama",
    "selectRelatedTableLayerLabel": "Pilih tabel yang terkait dengan layer",
    "selectRelatedTableLayerHintText": "Petunjuk: Hanya tabel dengan kolom angka yang ditampilkan",
    "errorInSelectingPolygonLayer": "Pilihlah layer yang memiliki layer titik terkait.",
    "errorInSelectingRelatedLayer": "Pilihlah tabel/layer terkait yang valid untuk layer.",
    "polygonLayerNotHavingRelationships": "Layer terpilih tidak mempunyai tabel/layer terkait apa pun."
  },
  "ChartSetting": {
    "sectionTitle": "Judul bagian",
    "sectionTitleHintText": "Petunjuk: Ditampilkan pada judul kepala bagian",
    "chartTitle": "Judul grafik",
    "chartTitleHintText": "Petunjuk: Ditampilkan di tengah atas grafik",
    "chartDescription": "Deskripsi",
    "chartDescriptionHintText": "Petunjuk: Ditampilkan di bawah grafik",
    "chartType": "Jenis grafik",
    "barChart": "Bar chart",
    "pieChart": "Pie chart",
    "polarChart": "Polar chart",
    "dataSeriesField": "Kolom rangkaian data",
    "labelField": "Kolom label",
    "chartColor": "Warna grafik",
    "singleColor": "Warna tunggal",
    "colorByTheme": "Warna menurut tema",
    "colorByFieldValue": "Warna menurut nilai kolom",
    "xAxisTitle": "Judul sumbu X",
    "xAxisHintText": "Petunjuk: Judul sumbu X",
    "yAxisTitle": "Judul sumbu Y",
    "yAxisHintText": "Petunjuk: Judul sumbu Y",
    "fieldColorLabel": "Label",
    "fieldColorColor": "Warna",
    "defaultFieldSelectLabel": "Pilih",
    "errMsgFieldValuesNotFound": "Tidak dapat menemukan nilai untuk kolom terpilih",
    "errMsgSectionTitle": "Masukkan judul bagian",
    "errMsgFieldByValue": "Pilihlah nilai kolom",
    "settingTabTitle": "Pengaturan",
    "layoutTabTitle": "Layout",
    "polarChartSelectFieldsHintText": "Petunjuk: Pilih kolom untuk menghasilkan polar chart",
    "visibilityText": "Visibilitas",
    "fieldNameText": "Nama Kolom",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Pilihlah tiga atau lebih kolom untuk menghasilkan polar chart",
    "polarChartPolygonFillLabel": "Isi poligon",
    "polarChartPolygonFillHintText": "Petunjuk: Pilih kotak centang untuk memperlihatkan poligon mengisi bagan polar",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Pengaturan Umum",
    "locationSymbolLabel": "Simbol lokasi grafik",
    "locationSymbolHintText": "Petunjuk: Digunakan untuk menampilkan simbol untuk alamat dan lokasi klik",
    "refreshIntervalLabel": "Interval penyegaran",
    "refreshIntervalHintText": "Petunjuk: Digunakan untuk menyegarkan bagan berdasarkan interval ini. Tentukan nilai antara 1 hingga 1440 menit",
    "errMsgRefreshInterval": "Tentukan interval penyegaran antara 0 hingga 1440 menit",
    "symbolPickerPreviewText": "Pratinjau:"
  }
});