define({
  "searchTabTitle": "Søgekildeindstilling",
  "routeTabTitle": "rute-indstilling",
  "add": "Tilføj søgekilde",
  "addGeocoder": "Tilføj geokodningsfunktion",
  "geocoder": "Geokoder",
  "setLayerSource": "Angiv lagkilde",
  "setGeocoderURL": "Angiv geokodnings-URL",
  "searchableLayer": "Vektorlag",
  "name": "Navn",
  "countryCode": "Lande- eller regionskode(r)",
  "countryCodeEg": "f.eks. ",
  "countryCodeHint": "Hvis denne værdi er tom, bliver der søgt efter alle lande og regioner",
  "showInfoWindowOnSelect": "Vis pop-up for det fundne objekt eller den fundne position",
  "showInfoWindowOnSelect2": "Vis pop-up, når objektet eller positionen er fundet.",
  "searchInCurrentMapExtent": "Søg kun inden for den aktuelle kortudstrækning",
  "setSearchFields": "Indstil søgefelter",
  "set": "Indstil",
  "fieldSearchable": "søgbar",
  "zoomScale": "Zoom-skala",
  "locatorUrl": "Geokodnings-URL",
  "locatorName": "Navn på geokodningsfunktion",
  "locatorExample": "Eksempel",
  "locatorWarning": "Denne versionen af geokodning understøttes ikke. Denne widget understøtter geokodningstjeneste version 10.1 og nyere.",
  "locatorTips": "Forslag er ikke tilgængelige, fordi geokodningstjenesten ikke understøtter forslagsfunktionen.",
  "layerSource": "Lagkilde",
  "searchLayerTips": "Forslag er ikke tilgængelige, fordi featuretjenesten ikke understøtter forslagsfunktionen.",
  "placeholderText": "Pladsholdertekst",
  "searchFields": "Søgefelter",
  "displayField": "Visningsfelt",
  "exactMatch": "Nøjagtigt match",
  "maxSuggestions": "Maksimalt antal forslag",
  "maxResults": "Maksimalt antal resultater",
  "enableLocalSearch": "Aktivér lokal søgning",
  "minScale": "Min. målestok",
  "minScaleHint": "Når kortmålestokken er større end denne målstok, anvendes lokal søgning",
  "radius": "Radius",
  "radiusHint": "Angiver radius for et område omkring det aktuelle kortcentrum, der benyttes til at booste rangordningen af geokodningsforslag, så de forslag, der ligger tættest på placeringen, returneres først",
  "invalidUrlTip": "URL’en ${URL} er ugyldig eller utilgængelig.",
  "routeUrl": "Rute-URL",
  "geocoderOptions": "Indstillinger for geokodning",
  "autoComplete": "Auto-fuldfør",
  "maximumSuggestions": "Maksimalt antal forslag",
  "minCharacters": "Minimalt antal tegn",
  "searchDelay": "Søgeforsinkelse",
  "placeholder": "Pladsholder",
  "routeOptions": "Indstillinger for rute",
  "directionsLanguage": "Sprog til kørselsvejledninger",
  "directionsLengthUnits": "Længdeenheder til kørselsvejledninger",
  "directionsOutputType": "Outputtype til kørselsvejledninger",
  "impedanceAttribute": "Impedansattribut",
  "kilometers": "Kilometer",
  "miles": "Miles",
  "meters": "Meter",
  "feet": "Fod",
  "yards": "Yards",
  "nauticalMiles": "Sømil",
  "parametersTip": "Angiv parametrene korrekt!",
  "complete": "Fuldført",
  "completeNoEvents": "Fuldført uden hændelser",
  "instructionsOnly": "Kun instruktioner",
  "standard": "Standard",
  "summaryOnly": "Kun oversigt",
  "travelModesUrl": "URL til rejsetilstande",
  "searchPlaceholder": "Find adresse eller sted",
  "trafficLayerUrl": "Trafiklag-URL",
  "barrierLayerUrl": "Grænselagets URL",
  "presetDestinations": "Forudindstil stop",
  "startPoint": "Startpunkt",
  "endPoint": "Slutpunkt",
  "destinationHolder": "Adresse eller koordinater",
  "optional": "Valgfri.",
  "barrierLayers": "Grænselag",
  "pointBarrier": "Punktgrænser",
  "lineBarrier": "Linjegrænser",
  "polygonBarrier": "Polygongrænser",
  "noPointBarrier": "Vælg punktgrænser",
  "noLineBarrier": "Vælg linjegrænser",
  "noPolygonBarrier": "Vælg polygongrænser"
});