define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "मानचित्र पर क्लिक कर बिंदु जोड़ें",
  "addRingsDtWt": "छल्ले, ड्राइविंग का समय या पैदल चलने का समय जोड़ें।",
  "apply": "लागू करें",
  "back": "पीछे जाएँ",
  "colon": ":",
  "creditInformation": "क्रेडिट जानकारी",
  "driveTime": "ड्राइविंग का समय",
  "esriInfographics": "Esri इन्फ़ोग्राफ़िक",
  "esriReports": "Esri रिपोर्ट",
  "headerDescription_km": "किलोमीटर",
  "headerDescription_miles": "मील",
  "headerDescription_minutes": "मिनट",
  "infographics": "इन्फ़ोग्राफ़िक",
  "invalidValueRing": "मान 0 से 1,000 के बीच के होने चाहिए।",
  "invalidValueDTWT": "मान 0 से 300 के बीच के होने चाहिए।",
  "km": "किमी",
  "miles": "मील",
  "minutes": "मिनट",
  "myInfographics": "मेरी इन्फ़ोग्राफ़िक",
  "myReports": "मेरी रिपोर्ट",
  "noPermissions": "आपका खाता व्यवसाय विश्लेषक विजेट नहीं चला सकता है।  व्यवसाय विश्लेषक विजेट चलाने के लिए, आपके संगठन के व्यवस्थापक को आपको जियोएनरिचमेंट और नेटवर्क विश्लेषण <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">विशेषाधिकार</a> देने की आवश्यकता है, और साथ ही, <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">क्रेडिट</a> आवंटित करने की आवश्यकता है।",
  "radii": "त्रिज्या",
  "radius": "त्रिज्या",
  "radius_lowercase": "त्रिज्या",
  "reports": "रिपोर्ट",
  "ring": "रिंग",
  "rings": "छल्ले",
  "runInfographic": "इन्फ़ोग्राफ़िक चलाएं",
  "runReport": "रिपोर्ट चलाएं",
  "selectPointOrPolygon": "मानचित्र पर कोई बिंदु या बहुभुज फ़ीचर चुनें, कोई पता या स्थान खोजें, या क्षेत्रों की अधिक जानकारी देखने के लिए मानचित्र पर एक पिन ड्रॉप करें।",
  "selectReport": "रिपोर्ट चुनें",
  "selectTemplate": "टेम्पलेट चुनें",
  "sharedInfographics": "साझा किए गए इन्फ़ोग्राफ़िक",
  "sharedReports": "साझा की गई रिपोर्ट",
  "thisEntryIsNotValid": "यह प्रविष्टि मान्य नहीं है।",
  "time": "समय",
  "walkTime": "पैदल चलने का समय",
  "widgetDescription": "उन इन्फ़ोग्राफ़िक और रिपोर्ट का एक्सेस करें जो किसी भी क्षेत्र के प्रमुख संकेतकों और डेटा को सारांशित करते हैं।",
  "None": "चुनें..."
});