define({
  "_widgetLabel": "Zichtbaarheid",
  "observerLocation": "Observeerderlocatie",
  "formatIconTooltip": "Invoerformaat",
  "addPointToolTip": "Observeerderlocatie toevoegen",
  "fieldOfView": "Blikveld",
  "useMilsText": "Gebruik mil voor hoeken",
  "observerHeight": "Observeerderhoogte",
  "minObsDistance": "Min. observeerbare afstand",
  "maxObsDistance": "Max. observeerbare afstand",
  "taskURLError": "Het widgetconfiguratiebestand bevat een URL die niet bereikbaar is. Controleer bij uw systeembeheerder",
  "taskURLInvalid": "De geoprocessingtaak die met deze widget geconfigureerd werd, is niet geldig. Controleer bij uw systeembeheerder",
  "viewshedError": "Er is een fout opgetreden tijdens het maken van de zichtbaarheid. Zorg ervoor dat uw observeerderlocatie binnen de extent van uw hoogteoppervlak valt.</p>",
  "validationError": "<p>Het zichtbaarheidcreatieformulier heeft ontbrekende of ongeldige parameters, Zorg ervoor dat:</p><ul><li>Er een observeerderlocatie ingesteld is.</li><li>Het Blikveld van observeerder niet 0 is.</li><li>De observeerderhoogte een geldige waarde bevat.</li><li>De min. en max. observeerbare afstanden geldigen waarden bevatten.</li></ul>",
  "comfirmInputNotation": "Bevestig inputnotatie",
  "notationsMatch": "notaties gevonden die overeenstemmen met uw input. Bevestig welke u wenst te gebruiken:",
  "createBtn": "Maken",
  "clearBtn": "Annuleren",
  "setCoordFormat": "Coördinaatindelingtekst",
  "prefixNumbers": "Voeg \"+/-\" prefix toe aan positieve en negatieve cijfers",
  "parseCoordinatesError": "Kan coördinaten niet parsen. Controleer uw input.",
  "cancelBtn": "Afbreken",
  "applyBtn": "Toepassen",
  "invalidMessage": "Voer een numerieke waarde in.",
  "observerRangeMessage": "Ongeldige observeerderhoogte",
  "minimumRangeMessage": "Ongeldig minimaal observeerbaar bereik",
  "maximumRangeMessage": "Het maximaal waarneembare bereik moet groter zijn dan het minimum waarneembare bereik en mag niet meer zijn dan ${limit} ${units}.",
  "portalURLError": "De URL van uw ArcGIS Online-organisatie of Portal for ArcGIS is niet geconfigureerd. Vraag uw systeembeheerder om meer informatie",
  "privilegeError": "Uw gebruikersrol kan geen analyse uitvoeren. Om de analyse te kunnen uitvoeren, moet de beheerder van uw organisatie u bepaalde a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">machtigingen</a> verlenen.",
  "noServiceError": "Hoogte-analyseservice niet beschikbaar. Controleer uw ArcGIS Online-organisatie of Portal voor ArcGIS-configuraties.",
  "pointToolTooltip": "Klik om een waarnemerlocatie toe te voegen",
  "degreesLabel": "graden",
  "milsLabel": "mijl",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimale graden - Breedtegraad/Lengtegraad",
  "DDLongLatNotation": "Decimale graden - Lengtegraad/Breedtegraad",
  "DDMLatLongNotation": "Graden decimale minuten - Breedtegraad/Lengtegraad",
  "DDMLongLatNotation": "Graden decimale minuten - Lengtegraad/Breedtegraad",
  "DMSLatLongNotation": "Graden decimale seconden - Breedtegraad/Lengtegraad",
  "DMSLongLatNotation": "Graden decimale seconden - Lengtegraad/Breedtegraad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - Hemisfeer (N/S)",
  "mainPageTitle": "Radiale gezichtslijn",
  "resultsTitle": "Resultaten",
  "publishBtnLabel": "Publiceren",
  "layerName": "Gepubliceerde laagnaam",
  "invalidLayerName": "Laagnaam mag alleen alfanumerieke tekens en onderstrepingstekens bevatten",
  "missingLayerName": "Laagnaam invoeren",
  "back": "Achterkant",
  "publishingFailedLayerExists": "Publiceren mislukt: u hebt al een featureservice met de naam {0}. Kies een andere naam.",
  "checkService": "Controleer service: {0}",
  "createService": "Maak service: {0}",
  "unableToCreate": "Niet mogelijk om te maken: {0}",
  "addToDefinition": "Voeg toe aan definitie: {0}",
  "successfullyPublished": "Succesvolle publicatie weblaag{0}Beheer de weblaag",
  "userRole": "Kan service niet maken omdat de gebruiker niet gemachtigd is",
  "publishToNewLayer": "Resultaten publiceren naar een nieuwe feature layer",
  "missingLayerNameMessage": "U moet een geldige laagnaam invoeren voordat u kunt publiceren",
  "regionTypeLabel": "Regiotype",
  "centerPointLabel": "Middenpunt",
  "observationHeightLabel": "Observatiehoogte",
  "heightUnitLabel": "Hoogte-eenheid",
  "minObservationDistanceLabel": "MinObservatieafstand",
  "maxObservationDistance": "MaxObservatieafstand",
  "distanceUnitLabel": "Afstandseenheid",
  "fovstartAngleLabel": "FOV Starthoek",
  "fovEndAngleLabel": "FOV Eindhoek",
  "andleUnitsLabel": "Hoekeenheden"
});