define({
  "_widgetLabel": "スマート エディター",
  "_featureAction_SmartEditor": "スマート エディター",
  "noEditPrivileges": "ご使用のアカウントには、データを作成/変更する権限がありません。",
  "widgetActive": "アクティブ",
  "widgetNotActive": "アクティブではない",
  "pressStr": "押す ",
  "ctrlStr": " Ctrl キー ",
  "snapStr": " スナップを有効にします",
  "noAvailableTempaltes": "利用可能なテンプレートがありません",
  "editorCache": " - エディターのキャッシュ",
  "presetFieldAlias": "フィールド",
  "presetValue": "設定済みの値",
  "usePresetValues": " 設定済みの値の使用 (新規フィーチャのみ)",
  "editGeometry": " ジオメトリの編集",
  "savePromptTitle": "フィーチャの保存",
  "savePrompt": "現在のフィーチャを保存しますか？",
  "deletePromptTitle": "フィーチャの削除",
  "deletePrompt": "選択フィーチャを削除しますか？",
  "attachmentLoadingError": "アタッチメントのアップロード中にエラーが発生しました",
  "attachmentSaveDeleteWarning": "警告: アタッチメントへの変更は自動的に保存されます",
  "autoSaveEdits": "自動的に新しいフィーチャを保存",
  "addNewFeature": "新しいフィーチャの作成",
  "featureCreationFailedMsg": "新しいレコード/フィーチャを作成できません。",
  "relatedItemTitle": "関連テーブル/レイヤー",
  "invalidRelationShipMsg": "主キー フィールドを確認してください: '${parentKeyField}' に有効な値があります。",
  "pendingFeatureSaveMsg": "関連フィーチャを作成する前に、フィーチャの編集を保存してください。",
  "attachmentsRequiredMsg": "(*) アタッチメントが必要です。",
  "coordinatePopupTitle": "XY 位置にフィーチャを移動",
  "coordinatesSelectTitle": "座標系:",
  "mapSpecialReferenceDropdownOption": "マップの空間参照",
  "latLongDropdownOption": "緯度/経度",
  "xAttributeTextBoxLabel": "X 座標",
  "yAttributeTextBoxLabel": "Y 座標",
  "latitudeTextBoxLabel": "緯度:",
  "longitudeTextBoxLabel": "経度 :",
  "filterEditor": {
    "all": "すべて",
    "noAvailableTempaltes": "利用可能なテンプレートがありません",
    "searchTemplates": "テンプレートの検索"
  },
  "invalidConfiguration": "ウィジェットが構成されていないか、構成で指定されたレイヤーがマップ内に存在しません。アプリをビルダー モードで開き、ウィジェットを再構成してください。",
  "geometryServiceURLNotFoundMSG": "ジオメトリ サービスの URL を取得できません",
  "clearSelection": "解除",
  "refreshAttributes": "フィーチャ属性の更新",
  "automaticAttributeUpdatesOn": "フィーチャ属性の自動更新: ON",
  "automaticAttributeUpdatesOff": "フィーチャ属性の自動更新: OFF",
  "moveSelectedFeatureToGPS": "現在の GPS 位置に選択したフィーチャを移動",
  "moveSelectedFeatureToXY": "XY 位置に選択したフィーチャを移動",
  "mapNavigationLocked": "マップ ナビゲーション: ロック",
  "mapNavigationUnLocked": "マップ ナビゲーション: ロック解除"
});