define({
  "feedbackStyleLabel": "Mesafe ve Yön Geri Bildirim Stili",
  "showTabLabel": "Sekmeyi Göster",
  "feedbackShapeLabel": "Geri Bildirim Şekli",
  "lineColorLabel": "Çizgi Rengi",
  "lineWidthLabel": "Çizgi Genişliği",
  "feedbackLabel": "Geri Bildirim Etiketi",
  "textColorLabel": "Metin Rengi",
  "textSizeLabel": "Metin Boyutu",
  "tabErrorMessage": "Araç, en az bir gösterilen sekmeyle yapılandırılmalıdır",
  "lineLabel": "Çizgi",
  "circleLabel": "Daire",
  "ellipseLabel": "Elips",
  "ringsLabel": "Halkalar",
  "transparency": "Şeffaflık",
  "ddFeedbackStyleTabLabel": "Semboloji",
  "miscellaneousTabLabel": "Diğer",
  "operationalLineLayerSelectLabel": "Çizgi ve halka sonuçları için operasyonel bir çoklu çizgi katmanı seçin",
  "operationalPolygonLayerSelectLabel": "Daire ve elips sonuçları için operasyonel bir çokgen katmanı seçin",
  "helpIconPolylineTooltip": "İşlem katmanı listesi, geçerli web haritasından çoklu çizgi geometrisi türünde katmanlarla doldurulur.",
  "helpIconPolygonTooltip": "İşlem katmanı listesi, geçerli web haritasından çokgen geometrisi türünde katmanlarla doldurulur."
});