define({
  "searchTabTitle": "Einstellung für Suchquelle",
  "routeTabTitle": "Routeneinstellung",
  "add": "Suchquelle hinzufügen",
  "addGeocoder": "Geocoder hinzufügen",
  "geocoder": "Geocoder",
  "setLayerSource": "Layer-Quelle festlegen",
  "setGeocoderURL": "Geocoder-URL festlegen",
  "searchableLayer": "Feature-Layer",
  "name": "Name",
  "countryCode": "Länder- oder Regionscode(s)",
  "countryCodeEg": "z. B. ",
  "countryCodeHint": "Wenn dieser Wert leer gelassen wird, werden alle Länder und Regionen durchsucht.",
  "showInfoWindowOnSelect": "Pop-up für das gefundene Feature oder die gefundene Position anzeigen",
  "showInfoWindowOnSelect2": "Pop-up anzeigen, wenn das Feature oder die Position gefunden wird.",
  "searchInCurrentMapExtent": "Nur in der aktuellen Kartenausdehnung suchen",
  "setSearchFields": "Suchfelder festlegen",
  "set": "Festlegen",
  "fieldSearchable": "Durchsuchbar",
  "zoomScale": "Zoom-Maßstab",
  "locatorUrl": "Geocoder-URL",
  "locatorName": "Geocoder-Name",
  "locatorExample": "Beispiel",
  "locatorWarning": "Diese Version des Geokodierungs-Service wird nicht unterstützt. Das Widget unterstützt Geokodierungsservice 10.1 und höher.",
  "locatorTips": "Es sind keine Vorschläge verfügbar, da der Geokodierungsservice die Vorschlagsfunktion nicht unterstützt.",
  "layerSource": "Layer-Quelle",
  "searchLayerTips": "Es sind keine Vorschläge verfügbar, da der Feature-Service die Paginierungsfunktion nicht unterstützt.",
  "placeholderText": "Platzhaltertext",
  "searchFields": "Suchfelder",
  "displayField": "Feld anzeigen",
  "exactMatch": "Exakte Übereinstimmung",
  "maxSuggestions": "Maximale Anzahl von Vorschlägen",
  "maxResults": "Maximale Anzahl von Ergebnissen",
  "enableLocalSearch": "Lokale Suche aktivieren",
  "minScale": "Min. Maßstab",
  "minScaleHint": "Wenn der Kartenmaßstab größer ist als dieser Maßstab, wird die lokale Suche angewendet.",
  "radius": "Radius",
  "radiusHint": "Ermöglicht die Festlegung des Radius einer Fläche um den aktuellen Kartenmittelpunkt, der dazu dient, die Rangfolge von Geokodierungskandidaten zu optimieren. Die Kandidaten, die der Position am nächsten liegen, werden auf diese Weise zuerst ausgegeben.",
  "invalidUrlTip": "Die URL ${URL} ist ungültig oder es kann nicht darauf zugegriffen werden.",
  "routeUrl": "Routen-URL",
  "geocoderOptions": "Geocoder-Optionen",
  "autoComplete": "Automatisch vervollständigen",
  "maximumSuggestions": "Maximale Anzahl von Vorschlägen",
  "minCharacters": "Minimale Anzahl von Zeichen",
  "searchDelay": "Suchverzögerung",
  "placeholder": "Platzhalter",
  "routeOptions": "Routen-Optionen",
  "directionsLanguage": "Sprache für Wegbeschreibung",
  "directionsLengthUnits": "Längeneinheiten für Wegbeschreibung",
  "directionsOutputType": "Ausgabetyp der Wegbeschreibung",
  "impedanceAttribute": "Impedanzattribut",
  "kilometers": "Kilometer",
  "miles": "Meilen",
  "meters": "Meter",
  "feet": "Fuß",
  "yards": "Yard",
  "nauticalMiles": "Seemeilen",
  "parametersTip": "Legen Sie die Parameter ordnungsgemäß fest!",
  "complete": "Vollständig",
  "completeNoEvents": "Vollständig, ohne Ereignisse",
  "instructionsOnly": "Nur Anweisungen",
  "standard": "Standard",
  "summaryOnly": "Nur Zusammenfassung",
  "travelModesUrl": "URL zu Reisemodi",
  "searchPlaceholder": "Adresse oder Ort suchen",
  "trafficLayerUrl": "URL des Verkehrsdaten-Layers",
  "barrierLayerUrl": "URL des Barriere-Layers",
  "presetDestinations": "Voreingestellte Stopps",
  "startPoint": "Startpunkt",
  "endPoint": "Endpunkt",
  "destinationHolder": "Adresse oder Koordinaten",
  "optional": "Optional.",
  "barrierLayers": "Barriere-Layer",
  "pointBarrier": "Punkt-Barrieren",
  "lineBarrier": "Linien-Barrieren",
  "polygonBarrier": "Polygon-Barrieren",
  "noPointBarrier": "Punkt-Barrieren auswählen",
  "noLineBarrier": "Linien-Barrieren auswählen",
  "noPolygonBarrier": "Polygon-Barrieren auswählen"
});