define({
  "taskUrl": "URL задачі",
  "setTask": "Задати",
  "setTaskPopupTitle": "Задати задачу",
  "validate": "Задати",
  "inValidGPService": "Введіть припустимий сервіс геообробки.",
  "noOutputParameterWithGeometryType": "Обраний сервіс геообробки повинен мати щонайменше один вихідний параметр із заданим типом геометрії. Оберіть інший сервіс геообробки.",
  "invalidOutputGeometry": "Вихідний тип геометрії обраного сервісу геообробки не сумісний з налаштуваннями проекту. Результати сервісу геообробки не можуть бути збережені.",
  "GPFeatureRecordSetLayerERR": "Введіть сервіс геообробки тільки з типом вхідних даних 'GPFeatureRecordSetLayer'.",
  "invalidInputParameters": "Число вхідних параметрів менше 1 або більше 3. Введіть припустимий сервіс геообробки.",
  "projectSetting": {
    "title": "Настройки проекту",
    "note": "Примітка: настройки проекту є опціональними, після налаштування користувач може зберегти проект в бажаних шарах веб-карти з областю відмови мережі та вхідними параметрами. Користувач може зберігати інші вихідні параметри з групи «Вивід» у вкладці «Ввід/вивід».",
    "projectPolygonLayer": "Шар полігонів проекту",
    "outputParameterName": "Ім'я вихідного параметру",
    "projectPointLayer": "Шар точок проекту",
    "selectLabel": "Вибір",
    "polygonLayerHelp": "<p>Буде показано шар(-и) полігонів з наступними умовами:<br/><ul><li>Шар повинен мати можливості редагування, а саме «Створити», «Видалити» та «Оновити»</li><li>Шар повинен мати 2 поля з точним іменем та типом даних:</li><ul><li>ім'я (поле рядкового типу)</li><li>globalid (поле типу GlobalID)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>Буде показано вихідний шар(и) полігонів з URL задачі<p/>",
    "pointLayerHelp": "<p>Буде показано шар(-и) точок з наступними умовами: <br/><ul><li>Шар повинен мати можливості редагування, а саме «Створити», «Видалити» та «Оновити»</li><li>Шар повинен мати 2 поля з точним іменем та типом даних:</li><ul><li>inputtype (поле рядкового типу)</li><li>projectid (поле типу GUID)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "Прапор",
    "barrier": "Бар’єр",
    "skip": "Пропустити",
    "title": "Ввід/вивід",
    "inputSettingsLabel": "Настройки вводу",
    "outputSettingsLabel": "Настройки виводу",
    "inputLabel": "Напис",
    "inputTooltip": "Підказка інструменту",
    "symbol": "Символ",
    "typeText": "Тип",
    "outputParametersText": "Вихідні параметри",
    "saveToLayerText": "Зберегти в шар (опціонально)",
    "skipText": "Можна пропустити",
    "visibilityText": "Видимий",
    "exportToCsvText": "Експорт в CSV",
    "exportToCsvDisplayText": "CSV",
    "settitngstext": "Налаштування",
    "addFieldTitle": "Додати поле",
    "enterDisplayText": "Ввести текст відображення",
    "setScale": "Задати масштаб",
    "outputDisplay": "Текст відображення",
    "saveToLayerHelp": "<p>Буде показано шар з наступними умовами:<br/><ul><li>Шар повинен мати можливості редагування, а саме «Створити», «Видалити» та «Оновити»</li><li>Шар повинен мати два поля з іменем та типом даних:</li><ul><li>parametername (поле рядкового типу)</li><li>projectid (поле типу Guid)</li></ul></ul><p/>"
  },
  "summaryTab": {
    "title": "Загальні налаштування",
    "summaryFieldsetText": "Настройки короткої інформації",
    "inputOutput": "Ввід/вивід",
    "field": "Поле",
    "operator": "Оператор",
    "inputOperatorCountOption": "Кількість",
    "outputOperatorCountOption": "Кількість",
    "outputOperatorSkipCountOption": "SkipCount",
    "fieldOperatorSumOption": "Сума",
    "fieldOperatorMinOption": "Мін.",
    "fieldOperatorMaxOption": "Макс.",
    "fieldOperatorMeanOption": "Середнє",
    "expressionAddButtonText": "Додавання",
    "expressionVerifyButtonText": "Перевірити",
    "summaryEditorText": "Текст короткої інформації",
    "autoZoomAfterTrace": "Додаткові опції",
    "zoomText": "Автоматичне масштабування після трасування",
    "summarSettingTooltipText": "Додати вхідний/вихідний рахунок"
  },
  "validationErrorMessage": {
    "webMapError": "На веб-карті немає доступних шарів. Виберіть припустиму веб-карту.",
    "inputTypeFlagGreaterThanError": "Вхідне значення прапору типу не може становити більше одного.",
    "inputTypeFlagLessThanError": "Потрібне щонайменше одне вхідне значення прапору типу.",
    "inputTypeBarrierErr": "Вхідне значення бар'єру типу не може становити більше одного.",
    "inputTypeSkipErr": "Вхідне значення пропуску типу не може становити більше одного.",
    "displayTextForButtonError": "Текст відображення для кнопки «Виконати» не може бути пустим.",
    "UnableToLoadGeoprocessError": "Не вдалося завантажити сервіс геообробки.",
    "invalidSummaryExpression": "Неприпустимий вираз.",
    "validSummaryExpression": "Успішно !",
    "invalidProjectSettings": "Неприпустимі настройки проекту<br/> Виберіть припустиме значення в '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "Підказка: надайте відображуваний напис для панелі результату вихідного параметра.",
    "displayTextHint": "Підказка: він відображатиметься в панелі докладної інформації для цього вхідного параметру.",
    "inputTextHint": "Підказка: побудуйте власний вираз вище, вибравши вхідні дані, вихідні дані та імена полів.",
    "expressionHint": "Підказка: виберіть елементи та клацніть «додати», щоб побудувати вираз."
  }
});