define({
  "businessAnalyst": "Business Analyst",
  "defineWhichInfographics": "위젯에서 사용할 수 있는 인포그래픽 정의:",
  "defineWhichReports": "위젯에서 사용할 수 있는 보고서 정의:",
  "defaultValues": "기본값:",
  "disable": "비활성화",
  "driveTime": "운전 시간",
  "infographics": "인포그래픽",
  "invalidValueRing": "값은 0~1,000 범위에 속해야 합니다.",
  "invalidValueDTWT": "값은 0~300 범위에 속해야 합니다.",
  "km": "킬로미터",
  "miles": "마일",
  "minutes": "분",
  "radius": "반경",
  "reports": "보고서",
  "rings": "링",
  "selectCountry": "국가 선택:",
  "thisEntryIsNotValid": "이 항목은 유효하지 않습니다.",
  "time": "시간",
  "walkTime": "도보 시간"
});