define({
  "_widgetLabel": "Helyspecifikus Elemzés",
  "locate_incident": "Incidens megkeresése",
  "reverse_geocoded_address": "Legközelebbi cím",
  "reverse_geocoded_error": "Nem elérhető",
  "now": "MOST",
  "wind": "SZÉL",
  "SUN": "V",
  "MON": "H",
  "TUE": "K",
  "WED": "SZE",
  "THU": "CS",
  "FRI": "P",
  "SAT": "SZO",
  "actionLabel": "Hely beállítása",
  "drawPoint": "Pont rajzolása",
  "drawLine": "Vonal rajzolása",
  "drawPolygon": "Polygon rajzolása",
  "saveIncident": "Mentés",
  "clearIncident": "Újrakezdés",
  "noFeaturesFound": "Nem találhatók vektoros elemek.",
  "downloadCSV": "Letöltés",
  "sum": "Összeg",
  "min": "Minimum",
  "max": "Maximum",
  "avg": "Átlag",
  "count": "SZÁM",
  "area": "TERÜLET",
  "length": "HOSSZ",
  "update_btn": "Kész",
  "delete_btn": "Törlés",
  "get_directions": "Útvonal keresése",
  "incident": "Incidens",
  "incidents": "Incidensek",
  "buffer": "Buffer",
  "buffers": "Bufferek",
  "weather": "Időjárás",
  "poweredBy": "Szolgáltató:",
  "_featureAction_ActionLabel": "Hely beállítása",
  "_featureAction_AddRemoveActionLabel": "Hely hozzáadása/eltávolítása",
  "snapshot": "SnapShot mappa létrehozva alkalmazásazonosító szerint:",
  "user_credentials": "A felhasználónak nincs érvényes jogosultsága.",
  "notPolySnapShot": "Adjon meg egy buffertávolságot a pillanatkép létrehozása előtt.",
  "notPolyReport": "A jelentéshez nincsenek érvényes találatok.",
  "notValidDownload": "Nincsenek letölthető érvényes találatok.",
  "of_append": "\"-nak,-nek\"",
  "layer_append": "réteg",
  "downloadAll": "Összes letöltése",
  "createSnapshot": "Pillanatkép készítése",
  "createReport": "Jelentés létrehozása",
  "calculated_results": "Összefoglaló információk",
  "closest": "Legközelebbi vektoros elem",
  "proximity": "Közelség",
  "summary": "Összefoglalás",
  "groupedSummary": "Csoportosított számok",
  "_count": "Szám",
  "approximate": "hozzávetőleges",
  "snapshot_name": "Pillanatkép tulajdonságainak beállítása",
  "report_name": "Jelentés tulajdonságainak beállítása",
  "invalid_snapshot_name": "A pillanatkép neve érvénytelen.",
  "invalid_report_name": "A bejelentés címe érvénytelen.",
  "orientation": "Tájolás",
  "pageSize": "Oldalméret",
  "comments": "Megjegyzések",
  "choose_group": "Csoportok",
  "forecast": "Előrejelzés",
  "select_group": "Csoport kiválasztása",
  "select_group_instruction": "A pillanatkép elkészül, és meg lesz osztva a kiválasztott csoporttal",
  "information_append": " Információ",
  "distance": "TÁVOLSÁG",
  "buffer_invalid": "Adjon meg egy érvényes számot ${min} és ${max} között"
});