define({
  "addTaskTip": "Přidejte do widgetu jeden nebo více filtrů a konfigurujte parametry těchto dotazů.",
  "enableMapFilter": "Odebrat přednastavený filtr vrstvy z mapy.",
  "newFilter": "Nový filtr",
  "filterExpression": "Výraz filtr",
  "layerDefaultSymbolTip": "Použít výchozí symbol vrstvy",
  "uploadImage": "Nahrát obrázek",
  "selectLayerTip": "Vyberte vrstvu.",
  "setTitleTip": "Nastavte název.",
  "noTasksTip": "Nejsou nakonfigurovány žádné filtry. Přidejte nový filtr kliknutím na tlačítko \"${newFilter}\".",
  "collapseFiltersTip": "Při otevření widgetu sbalit výrazy filtru (pokud jsou zadány)",
  "zoomtoTip": "Po aplikaci filtru přiblížit zbývající prvky",
  "groupByLayerTip": "Seskupit filtry dle vrstvy",
  "autoApplyWhenValueInput": "Po zadání hodnoty použít filtr automaticky",
  "autoApplyWhenWidgetOpen": "Použít filtr při otevření widgetu",
  "info": "Informace",
  "expressions": "Výrazy",
  "allowCustom": "Umožnit vytváření vlastních filtrů",
  "filterActions": "Vlastní akce filtru",
  "custom": "Povolit vlastní filtry",
  "resetAll": "Povolit obnovit vše",
  "turnOffAll": "Povolit vypnout vše",
  "matchMsgSetAll": "Zobrazit prvky, které odpovídají všem filtrům",
  "matchMsgSetAny": "Zobrazit prvky, které odpovídají jakémukoliv filtru"
});