define({
  "chartSettingLabel": "Configuración de gráfico",
  "addNewLabel": "Agregar nuevo",
  "generalSettingLabel": "Configuración general",
  "layerChooser": {
    "title": "Seleccionar capa para gráfico",
    "selectPolygonLayerLabel": "Seleccionar capa",
    "selectPolygonLayerHintText": "Sugerencia: si vas a configurar varios gráficos, las capas tienen que tener el mismo tipo de geometría",
    "selectRelatedTableLayerLabel": "Seleccionar tabla relacionada con capa",
    "selectRelatedTableLayerHintText": "Sugerencia: solo se muestran las tablas que tienen campos numéricos",
    "errorInSelectingPolygonLayer": "Selecciona una capa que tenga una capa de puntos relacionada.",
    "errorInSelectingRelatedLayer": "Selecciona una tabla o capa válida relacionada con la capa.",
    "polygonLayerNotHavingRelationships": "La capa seleccionada no tiene ninguna tabla o capa relacionada."
  },
  "ChartSetting": {
    "sectionTitle": "Título de la sección",
    "sectionTitleHintText": "Sugerencia: se muestra en el título del encabezado de la sección",
    "chartTitle": "Título de gráfico",
    "chartTitleHintText": "Sugerencia: se muestra centrado en la parte superior del gráfico",
    "chartDescription": "Descripción",
    "chartDescriptionHintText": "Sugerencia: se muestra debajo del gráfico",
    "chartType": "Tipo de gráfico",
    "barChart": "Gráfico de barras",
    "pieChart": "Gráfico circular",
    "polarChart": "Gráfico polar",
    "dataSeriesField": "Campo de serie de datos",
    "labelField": "Campo de etiquetado",
    "chartColor": "Color de gráfico",
    "singleColor": "Color único",
    "colorByTheme": "Color por tema",
    "colorByFieldValue": "Color por valor de campo",
    "xAxisTitle": "Título de eje x",
    "xAxisHintText": "Sugerencia: título del eje x",
    "yAxisTitle": "Título de eje y",
    "yAxisHintText": "Sugerencia: título del eje y",
    "fieldColorLabel": "Etiqueta",
    "fieldColorColor": "Color",
    "defaultFieldSelectLabel": "Seleccionar",
    "errMsgFieldValuesNotFound": "No se pueden encontrar valores para el campo seleccionado",
    "errMsgSectionTitle": "Introduce el título de la sección",
    "errMsgFieldByValue": "Selecciona el valor del campo",
    "settingTabTitle": "Configuración",
    "layoutTabTitle": "Diseño",
    "polarChartSelectFieldsHintText": "Sugerencia: seleccione los campos para generar el gráfico polar",
    "visibilityText": "Visibilidad",
    "fieldNameText": "Nombre de campo",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Seleccione tres o más campos para generar el gráfico polar",
    "polarChartPolygonFillLabel": "Rellenar polígono",
    "polarChartPolygonFillHintText": "Sugerencia: active la casilla de verificación para mostrar el relleno de polígonos en el gráfico polar",
    "ThemeSelector": {
      "themeAdobebricks": "LadrillosAdobe",
      "themeAlgae": "Algas",
      "themeBahamation": "Bahamas",
      "themeBlueDusk": "OcasoAzul",
      "themeCubanShirts": "CamisasCubanas",
      "themeDesert": "Desierto",
      "themeDistinctive": "Distintivo",
      "themeDollar": "Dólar",
      "themeGrasshopper": "Saltamontes",
      "themeGrasslands": "Praderas",
      "themeGreySkies": "CielosGrises",
      "themeHarmony": "Armonía",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irlanda",
      "themeMiamiNice": "BonitoMiami",
      "themeMinty": "Mentolado",
      "themePurpleRain": "LluviaMorada",
      "themeRoyalPurples": "PúrpurasReales",
      "themeSageToLime": "SalviaACal",
      "themeTufte": "Mechón",
      "themeWatersEdge": "BordeAgua",
      "themeWetlandText": "Humedal",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Configuración general",
    "locationSymbolLabel": "Símbolo de ubicación de gráfico",
    "locationSymbolHintText": "Sugerencia: se utiliza para visualizar el símbolo para la dirección y ubicación en la que se hace clic",
    "refreshIntervalLabel": "Intervalo de actualización",
    "refreshIntervalHintText": "Sugerencia: se utiliza para actualizar los gráficos según este intervalo. Especifica un valor entre 1 y 1440 minutos",
    "errMsgRefreshInterval": "Especifica el intervalo de actualización entre 0 y 1440 minutos.",
    "symbolPickerPreviewText": "Vista previa:"
  }
});