define({
  "_widgetLabel": "Mise à jour",
  "_featureAction_Edit": "Modifie",
  "title": "Sélectionnez un modèle pour créer des entités",
  "pressStr": "Appuyez sur ",
  "ctrlStr": " CTRL ",
  "snapStr": " pour activer la capture",
  "close": "Fermer",
  "featureLayers": "Couches d'entités",
  "searchTemplates": "Modèles de recherche",
  "noAvailableTempaltes": "Aucun modèle disponible",
  "noCanCreateLayerAreCurrentlyVisible": "Aucune couche à créer n'est actuellement visible.",
  "layersAreInvisibleOrOutOfScaleRange": "Les couches sont invisibles ou hors de la plage d’échelle.",
  "relatedTables": "Tables associées :",
  "relatedRecords": "Enregistrements associés :",
  "noRelatedRecotds": "Enregistrements associés introuvables.",
  "startToDraw": "Cliquez pour commencer à dessiner",
  "startToAddPoint": "Cliquez pour ajouter un point",
  "editRelatedFeature": "Modification des entités associées",
  "duplicateValueWarning": " Impossible d’insérer une valeur dupliquée dans le champ ${fieldName} de la table ${tableName}. La valeur dupliquée est : ${value}"
});