define({
  "addLocation": "Afegeix una unitat d'ubicació",
  "addDistance": "Afegeix una unitat de longitud",
  "addArea": "Afegeix una unitat d'àrea",
  "label": "Etiqueta",
  "abbr": "Abreviació",
  "conversion": "Conversió",
  "actions": "Accions",
  "areaUnits": "Unitats d'àrea",
  "distanceUnits": "Unitats de longitud",
  "kilometers": "Quilòmetres",
  "miles": "Milles",
  "meters": "Metres",
  "feet": "Peus",
  "yards": "Iardes",
  "nauticalmiles": "Milles nàutiques",
  "squareKilometers": "Quilòmetres quadrats",
  "squareMiles": "Milles quadrades",
  "acres": "Acres",
  "hectares": "Hectàrees",
  "squareMeters": "Metres quadrats",
  "squareFeet": "Peus quadrats",
  "squareYards": "Iardes quadrades",
  "location": "Ubicacions",
  "distance": "Distàncies",
  "area": "Àrees",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "mi",
  "metersAbbreviation": "m",
  "feetAbbreviation": "ft",
  "yardsAbbreviation": "yd",
  "nauticalmilesAbbreviation": "nm",
  "squareKilometersAbbreviation": "km²",
  "squareMilesAbbreviation": "mi²",
  "acresAbbreviation": "ac",
  "hectaresAbbreviation": "ha",
  "squareMetersAbbreviation": "m²",
  "squareFeetAbbreviation": "ft²",
  "squareYardsAbbreviation": "yd²",
  "defineUnits": "Definiu les unitats de mesura.",
  "operationalLayer": "Afegiu el dibuix com a una capa operativa del mapa."
});