define({
  "transparencyLabel": "透明度",
  "outline": "輪廓",
  "fill": "填充 (將樣式設為實心時所套用的顏色)",
  "style": "樣式",
  "mandatoryLabel": "強制疏散距離",
  "mandatoryButtonLabel": "配置強制疏散距離設定",
  "safeLabel": "安全疏散距離",
  "safeButtonLabel": "配置安全疏散距離設定",
  "selectOpLayerLabel": "選擇結果的操作圖層",
  "selectDefaultMeasurementLabel": "選擇預設的測量單位",
  "helpIconTooltip": "會在操作圖層清單中，填入多邊形幾何類型的現行 Web 地圖中的圖層。",
  "lineStyles": {
    "esriSLSDash": "虛線",
    "esriSLSDashDot": "虛線點",
    "esriSLSDashDotDot": "虛線點點",
    "esriSLSDot": "點",
    "esriSLSLongDash": "長虛線",
    "esriSLSLongDashDot": "長虛線點",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "短虛線",
    "esriSLSShortDashDot": "短虛線點",
    "esriSLSShortDashDotDot": "短雙虛線點",
    "esriSLSShortDot": "短點",
    "esriSLSSolid": "實心"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "向後",
    "esriSFSCross": "十字形",
    "esriSFSDiagonalCross": "對角線",
    "esriSFSForwardDiagonal": "轉寄",
    "esriSFSHorizontal": "水平對齊",
    "esriSFSNull": "Null",
    "esriSFSSolid": "實心",
    "esriSFSVertical": "垂直"
  },
  "threatTypeLabel": "威脅類型",
  "symbologyLabel": "符號系統",
  "generalLabel": "一般",
  "addThreatTypesLabel": "新增威脅類型",
  "threatTypeColLabel": "威脅類型",
  "actions": "作業",
  "newThreatTypePopupLabel": "新建威脅類型",
  "chooseDefaultThreatTypeIconLabel": "從預設值選擇",
  "mandatoryDistance": "強制疏散距離",
  "safeDistance": "安全疏散距離",
  "units": "單位",
  "chooseDefaultThreatLabel": "選取預設威脅類型",
  "defaultThreatTypePopUpLabel": "預設威脅類型",
  "editThreatLabel": "編輯威脅",
  "defaultThreatTypeIconTooltip": "預設威脅類型清單",
  "uniqueThreatTypeMsg": "輸入唯一威脅類型，已存在此名稱的威脅類型。",
  "requiredThreatTypeMsg": "此欄位為必填項",
  "unitMeasureLabel": "距離以 {0} 為單位",
  "pipeBombLabel": "土製鐵管炸彈",
  "suicideBombLabel": "自殺炸彈",
  "briefcaseLabel": "公事包",
  "carLabel": "汽車",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "小型送貨卡車",
  "containerWaterTruckLabel": "容器/水車",
  "semiTrailerLabel": "半掛車"
});