define({
  "_widgetLabel": "Avstand og retning",
  "tabLineTitle": "Linje",
  "tabCircleTitle": "Sirkel",
  "tabEllipseTitle": "Ellipse",
  "tabRingsTitle": "Ringer",
  "multipleNotationsMessage": " notasjoner som samsvarer med inndataene. Bekreft hvilke du vil bruke:",
  "invalidCoordinateMessage": "Ugyldige koordinat",
  "confirmInputNotationMessage": "Bekreft inndatanotasjon",
  "prefixSuffixMessage": "Inndatakoordinatene har både et prefiks og et suffiks for bredde- og lengdegradverdi. Den returnerte verdien bygger på prefikset.",
  "rememberDecisionMessage": "Husk avgjørelsen og ikke spør igjen.<br/>",
  "majorAxisTooltipMessage": "Klikk lengde for den store aksen",
  "minorAxisTooltipMessage": "Flytt musen tilbake til startposisjonen for å angi den lille aksen og tegne ferdig ellipsen",
  "clickToFinishLineMessage": "Klikk for å fullføre tegning av linjen",
  "doubleClickEllipseMesage": "Dobbeltklikk for å fullføre tegning av avstandsringer",
  "invalidCoordinateTypeMessage": "Kan ikke bestemme koordinattype for inndata. Sjekk inndataene",
  "noCenterPointSetMessage": "Midtpunkt ikke angitt. Sjekk inndataene",
  "ellipseMajorAxis": "Store akse",
  "ellipseMinorAxis": "Lille akse",
  "degreesRangeMessage": "Verdien må være mellom 0 og 360",
  "millsRangeMessage": "Verdien må være mellom 0 og 6400",
  "lengthLabel": "Lengde",
  "angleLabel": "Vinkel",
  "startPointLabel": "Startpunkt",
  "endPointLabel": "Sluttpunkt",
  "centerPointLabel": "Midtpunkt",
  "distanceTableErrorMessage": "Avstandstabellen er tom. Kontroller at det er angitt noen avstander.",
  "setCoordFormatStringMessage": "Angi koordinatformatstreng",
  "prefixMessage": "Legg til prefikset \"+/-\" for positive og negative tall",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Desimalgrader - Breddegrad/lengdegrad",
  "DDLongLatNotation": "Desimalgrader - Lengdegrad/breddegrad",
  "DDMLatLongNotation": "Grader og desimalminutter - Breddegrad/lengdegrad",
  "DDMLongLatNotation": "Grader og desimalminutter - Lengdegrad/breddegrad",
  "DMSLatLongNotation": "Grader Minutter Sekunder - Breddegrad/lengdegrad",
  "DMSLongLatNotation": "Grader Minutter Sekunder - Lengdegrad/breddegrad",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Båndbokstav",
  "UTMHemNotation": "UTM - Halvkule (N/S)",
  "circleTitle": "Opprett sirkel fra",
  "radiusLabel": "Radius",
  "diameterLabel": "Diameter",
  "startPointPlaceHolderLabel": "Angi koordinater",
  "formatInputLabel": "Formater inndata",
  "drawCircleLabel": "Tegn sirkel",
  "drawLineLabel": "Tegn linje",
  "createCircleInteractivelyLabel": "Opprett sirkel interaktivt",
  "rangeErrorMessage": "Ugyldig radius eller diameter",
  "numericInvalidMessage": "Angi en numerisk verdi",
  "timeLabel": "Tid",
  "invalidTimeMessage": "Ugyldig verdi for tid",
  "hoursLabel": "Timer",
  "minutesLabel": "Minutter",
  "secondsLabel": "Sekunder",
  "rateLabel": "Vurder",
  "invalidDistanceMessage": "Ugyldig verdi for avstand",
  "feetSecondsLabel": "Fot/sekund",
  "feetHourLabel": "Fot/time",
  "kmSecondLabel": "Kilometer / sekund",
  "kmHourLabel": "Kilometer / time",
  "metersSecondLabel": "Meter / sekund",
  "metersHourLabel": "Meter / time",
  "milesSecondLabel": "Miles / sekund",
  "milesHourLabel": "Miles / time",
  "nauticalMilesSecondLabel": "Nautiske mil / sekund",
  "nauticalMilesHourLabel": "Nautiske mil / time",
  "clearGraphicsLabel": "Fjern grafikk",
  "ellipseTypeLabel": "Ellipsetype",
  "ellipseSemiLabel": "Semi",
  "ellipseFullLabel": "Full",
  "drawEllipseLabel": "Tegn ellipse",
  "createEllipseInteractively": "Opprett ellipse interaktivt",
  "axisLabel": "Akse",
  "unitLabel": "Enhet",
  "majorRadiusLabel": "Store (radius)",
  "majorDiameterLabel": "Stor (diameter)",
  "axisErrorMessage": "Verdien må være større enn 0",
  "minorRadiusLabel": "Lille (radius)",
  "minorDiameterLabel": "Liten (diameter)",
  "orientationLabel": "Retning",
  "orientationErrorMessage": "Verdien må være mellom 0 og 360",
  "warningMessage": "Advarsel: Grafikk som genereres ved hjelp av ellipseverktøyet, er ikke geodetisk",
  "fromLabel": "fra",
  "distanceBearingLabel": "Avstand og peilevinkel",
  "pointsLabel": "Punkter",
  "createLineInteractively": "Opprett linje interaktivt",
  "lineLengthErrorMessage": "Ugyldig linjelengde",
  "degreesLabel": "Grader",
  "milsLabel": "Mil",
  "lineTypeLabel": "Type",
  "interactiveLabel": "Interaktiv",
  "fixedLabel": "Fast",
  "originLabel": "Opprinnelse",
  "cumulativeLabel": "Kumulativ",
  "numberOfRingsLabel": "Antall ringer",
  "ringsErrorMessage": "Ugyldig antall ringer",
  "distanceBetweenRingsLabel": "Avstand mellom ringer",
  "ringsDecimalErrorMessage": "Angi en numerisk verdi med to desimaler",
  "distanceUnitsLabel": "Avstandsenheter",
  "distancesLabel": "Avstander",
  "numberOfRadialsLabel": "Antall radialer",
  "upLabel": "Opp",
  "downLabel": "Ned",
  "deleteLabel": "Slett",
  "radialsErrorMessage": "Ugyldig antall radialer. Høyeste tillatte antall er 360",
  "radialsInvalidMessage": "Ugyldig verdi for radialer",
  "addPointLabel": "Legge til punkt",
  "valueLabel": "Verdi",
  "valueText": "Angi verdi",
  "actionLabel": "Handling",
  "distanceCalculatorLabel": "Avstandskalkulator",
  "abbrevMetersLabel": "m",
  "abbrevFeetLabel": "ft",
  "abbrevKmLabel": "km",
  "abbrevMilesLabel": "mi",
  "abbrevYardsLabel": "yd",
  "abbrevNauticalMilesLabel": "nm",
  "abbrevDegreesLabel": "°",
  "abbrevMilsLabel": "mil",
  "abbrevHoursLabel": "h",
  "abbrevMinutesLabel": "m",
  "abbrevSecondsLabel": "s",
  "abbrevFeetSecondsLabel": "ft/s",
  "abbrevFeetHourLabel": "ft/t",
  "abbrevKmSecondLabel": "km/s",
  "abbrevKmHourLabel": "km/t",
  "abbrevMetersSecondLabel": "m/s",
  "abbrevMetersHourLabel": "m/t",
  "abbrevMilesSecondLabel": "mi/s",
  "abbrevMilesHourLabel": "mi/t",
  "abbrevNauticalMilesSecondLabel": "nm/s",
  "abbrevNauticalMilesHourLabel": "nm/t",
  "publishDDBtn": "Publiser",
  "publishTitle": "Publiser grafikk",
  "ddLayerName": "Publisert lagnavn",
  "missingDDLayerName": "Du må angi et navn for laget",
  "publishToNewLayer": "Publiser resultater til et nytt geoobjektlag",
  "checkService": "Kontroller tjeneste: {0}",
  "createService": "Opprett tjeneste {0}",
  "unableToCreate": "Kan ikke opprette: {0}",
  "addToDefinition": "Legg til definisjon: {0}",
  "successfullyPublished": "Vellykket publisering av weblag{0}Administrer weblaget",
  "userRole": "Kan ikke opprette tjeneste fordi brukeren ikke har tillatelser",
  "missingLayerNameMessage": "Du må angi et gyldig lagnavn før du kan publisere",
  "invalidLayerName": "Lagnavn kan bare inneholde alfanumeriske tegn og understrekingstegn",
  "distanceLabel": "Avstand",
  "radiusDistance": "Radiusavstand",
  "radials": "Radialer",
  "rings": "Ringer",
  "orientationUnit": "Retningsenhet",
  "radiusUnit": "Radiusenhet",
  "angleUnitLabel": "Vinkelenhet"
});