define({
  "searchTabTitle": "Thiết lập nguồn tìm kiếm",
  "routeTabTitle": "Thiết lập tuyến đường",
  "add": "Thêm nguồn tìm kiếm",
  "addGeocoder": "Thêm bộ mã địa lý",
  "geocoder": "Trình mã hóa địa lý",
  "setLayerSource": "Thiết lập nguồn lớp",
  "setGeocoderURL": "Thiết lập URL trình mã hóa địa lý",
  "searchableLayer": "Lớp đối tượng",
  "name": "Tên",
  "countryCode": "Mã quốc gia hoặc khu vực",
  "countryCodeEg": "ví dụ ",
  "countryCodeHint": "Để trống giá trị này sẽ tìm kiếm tất cả các quốc gia và khu vực",
  "showInfoWindowOnSelect": "Hiển thị cửa sổ pop-up cho vị trí hoặc đối tượng được tìm thấy",
  "showInfoWindowOnSelect2": "Hiển thị pop-up khi tìm thấy đối tượng hoặc vị trí",
  "searchInCurrentMapExtent": "Chỉ tìm kiếm trong kích thước bản đồ hiện tại",
  "setSearchFields": "Thiết lập trường tìm kiếm",
  "set": "Thiết lập",
  "fieldSearchable": "có thể tìm kiếm",
  "zoomScale": "Tỷ lệ thu phóng",
  "locatorUrl": "URL Bộ mã địa lý",
  "locatorName": "Tên bộ mã địa lý",
  "locatorExample": "Ví dụ",
  "locatorWarning": "Phiên bản dịch vụ mã hóa địa lý này không được hỗ trợ. Tiện ích này hỗ trợ dịch vụ mã hóa địa lý 10.1 hoặc cao hơn.",
  "locatorTips": "Các gợi ý không khả dụng do dịch vụ mã hóa địa lý không hỗ trợ khả năng gợi ý.",
  "layerSource": "Nguồn lớp",
  "searchLayerTips": "Các gợi ý không khả dụng do dịch vụ đối tượng không hỗ trợ khả năng phân trang.",
  "placeholderText": "Văn bản trình giữ chỗ",
  "searchFields": "Tìm kiếm trường",
  "displayField": "Hiển thị trường",
  "exactMatch": "Kết quả khớp chính xác",
  "maxSuggestions": "Số đề xuất tối đa",
  "maxResults": "Kết quả tối đa",
  "enableLocalSearch": "Bật tính năng tìm kiếm nội bộ",
  "minScale": "Tỷ lệ tối thiểu",
  "minScaleHint": "Khi tỷ lệ bản đồ lớn hơn tỷ lệ này, tìm kiếm cục bộ sẽ được áp dụng",
  "radius": "Bán kính",
  "radiusHint": "Xác định bán kính của một khu vực xung quanh trung tâm bản đồ hiện tại sẽ làm tăng thứ hạng của các đối tượng mã hóa địa lý, giúp các đối tượng ở gần nhất với vị trí được trả về đầu tiên",
  "invalidUrlTip": "URL ${URL} không hợp lệ hoặc không thể truy cập được.",
  "routeUrl": "URL tuyến đường",
  "geocoderOptions": "Tùy chọn của trình mã hóa địa lý",
  "autoComplete": "Tự động hoàn tất",
  "maximumSuggestions": "Số đề xuất tối đa",
  "minCharacters": "Ký tự tối đa",
  "searchDelay": "Trì hoãn tìm kiếm",
  "placeholder": "Trình giữ chỗ",
  "routeOptions": "Tùy chọn định tuyến",
  "directionsLanguage": "Ngôn ngữ thông tin định hướng",
  "directionsLengthUnits": "Đơn vị độ dài thông tin định hướng",
  "directionsOutputType": "Loại đầu ra của thông tin định hướng",
  "impedanceAttribute": "Thuộc tính trở kháng",
  "kilometers": "Kilômét",
  "miles": "Dặm",
  "meters": "Mét",
  "feet": "Feet",
  "yards": "Thước",
  "nauticalMiles": "Hải lý",
  "parametersTip": "Vui lòng đặt tham số chính xác !",
  "complete": "Hoàn tất",
  "completeNoEvents": "Hoàn tất không có sự kiện nào",
  "instructionsOnly": "Chỉ hướng dẫn",
  "standard": "Tiêu chuẩn",
  "summaryOnly": "Chỉ tóm tắt",
  "travelModesUrl": "URL hình thức di chuyển",
  "searchPlaceholder": "Tìm địa chỉ hoặc địa điểm",
  "trafficLayerUrl": "URL lớp lưu lượng giao thông",
  "barrierLayerUrl": "URL lớp barrier",
  "presetDestinations": "Thiết lập trước điểm dừng",
  "startPoint": "Điểm bắt đầu",
  "endPoint": "Điểm kết thúc",
  "destinationHolder": "Địa chỉ hoặc tọa độ",
  "optional": "Tùy chọn.",
  "barrierLayers": "Lớp Rào cản",
  "pointBarrier": "Lớp Điểm",
  "lineBarrier": "Rào cản dạng đường",
  "polygonBarrier": "Rào cản dạng vùng",
  "noPointBarrier": "Chọn các điểm chặn",
  "noLineBarrier": "Chọn các đường chặn",
  "noPolygonBarrier": "Chọn các vùng chặn"
});