define({
  "_widgetLabel": "Danh sách Lớp",
  "titleBasemap": "Bản đồ nền",
  "titleLayers": "Các lớp hoạt động",
  "labelLayer": "Tên lớp",
  "itemZoomTo": "Phóng tới",
  "itemTransparency": "Độ trong suốt",
  "itemTransparent": "Độ trong suốt",
  "itemOpaque": "Độ mờ",
  "itemMoveUp": "Di chuyển lên trên",
  "itemMoveDown": "Di chuyển xuống dưới",
  "itemDesc": "Mô tả",
  "itemDownload": "Tải xuống",
  "itemToAttributeTable": "Mở Bảng Thuộc tính",
  "itemShowItemDetails": "Hiện Chi tiết của Mục",
  "empty": "trống",
  "removePopup": "Tắt Cửa sổ pop-up",
  "enablePopup": "Bật Cửa sổ pop-up",
  "turnAllLayersOff": "Tắt Tất cả Lớp",
  "turnAllLayersOn": "Bật Tất cả Lớp",
  "expandAllLayers": "Mở rộng Tất cả Lớp",
  "collapseAlllayers": "Thu gọn Tất cả Lớp",
  "turnAllLabelsOff": "Tắt Tất cả Nhãn",
  "turnAllLabelsOn": "Bật Tất cả Nhãn",
  "showLabels": "Hiện Nhãn",
  "hideLables": "Ẩn Nhãn"
});