define({
  "_widgetLabel": "Nakreslit",
  "selectDrawMode": "Vybrat režim kreslení",
  "clear": "Vymazat",
  "point": "Bod",
  "line": "Linie",
  "polyline": "Polylinie",
  "freehandPolyline": "Linie od ruky",
  "triangle": "Trojúhelník",
  "extent": "Obálka",
  "circle": "Kruh",
  "ellipse": "Elipsa",
  "polygon": "Polygon",
  "freehandPolygon": "Polygon od ruky",
  "text": "Text",
  "style": "Styl",
  "alpha": "Průhlednost",
  "width": "Šířka",
  "size": "Velikost",
  "color": "Barva",
  "markerColor": "Barva značky",
  "outlineColor": "Barva obrysu",
  "lineColor": "Barva linie",
  "fillColor": "Barva výplně",
  "showMeasurements": "Zobrazit měření",
  "showLocationMeasurement": "Zobrazit měření polohy",
  "showAreaMeasurement": "Zobrazit měření plochy",
  "showDistanceMeasurement": "Zobrazit měření vzdálenosti",
  "showDistanceMeasurementForLine": "Zobrazit měření délky",
  "showDistanceMeasurementForPolygon": "Zobrazit měření obvodu",
  "locationToggleOn": "Pro zobrazení měření polohy stiskněte přepínací tlačítko",
  "locationToggleOff": "Pro skrytí měření polohy stiskněte přepínací tlačítko",
  "areaToggleOn": "Pro zobrazení měření plochy stiskněte přepínací tlačítko",
  "areaToggleOff": "Pro skrytí měření plochy stiskněte přepínací tlačítko",
  "distanceForLineToggleOn": "Pro zobrazení měření délky stiskněte přepínací tlačítko",
  "distanceForLineToggleOff": "Pro skrytí měření délky stiskněte přepínací tlačítko",
  "distanceForPolygonToggleOn": "Pro zobrazení měření obvodu stiskněte přepínací tlačítko",
  "distanceForPolygonToggleOff": "Pro skrytí měření obvodu stiskněte přepínací tlačítko",
  "areaUnits": "Jednotky plochy",
  "distanceUnits": "Jednotky vzdálenosti",
  "kilometers": "Kilometry",
  "miles": "Míle",
  "meters": "Metry",
  "feet": "Stopy",
  "yards": "Yardy",
  "nauticalmiles": "Námořní míle",
  "squareKilometers": "Čtvereční kilometry",
  "squareMiles": "Čtvereční míle",
  "acres": "Akry",
  "hectares": "Hektary",
  "squareMeters": "Čtvereční metry",
  "squareFeet": "Čtvereční stopy",
  "squareYards": "Čtvereční yardy",
  "undo": "Zpět",
  "redo": "Znovu",
  "results": "Výsledky",
  "points": "Body",
  "lines": "Linie",
  "areas": "Plochy",
  "locationLabel": "Poloha: ${value}",
  "areaLabel": "Plocha: ${value} ${unit}",
  "distanceLabel": "Vzdálenost: ${value} ${unit}",
  "distanceLabelForLine": "Délka: ${value} ${unit}",
  "distanceLabelForPolygon": "Obvod: ${value} ${unit}"
});