define({
  "_widgetLabel": "網路追蹤",
  "_featureAction_NetworkTraceSkip": "在軌跡中略過",
  "_featureAction_NetworkTraceUnskip": "從略過位置移除",
  "removedFromSkipLocations": "已從略過位置移除",
  "alreadyRemovedFromSkipLocations": "已從略過位置移除",
  "locationSkipped": "已略過位置",
  "configError": "未適當配置 widget。",
  "geometryServiceURLNotFoundMSG": "無法取得幾何服務 URL",
  "clearButtonValue": "清除",
  "GPExecutionFailed": "無法完成追蹤。 請再試一次。",
  "backButtonValue": "上一步",
  "exportToCSVSuccess": "已成功匯出到 CSV。",
  "lblInputLocTab": "輸入位置",
  "lblBlockLocTab": "區塊位置",
  "lblInputLocation": "輸入圖徵",
  "lblBlockLocation": "區塊圖徵",
  "lblInputLocHeader": "輸入位置 (0)",
  "lblBlockLocHeader": "區塊位置 (0)",
  "inputTabTitle": "輸入",
  "outputTabTitle": "輸出",
  "exportSelectAllCheckBoxLabel": "全選",
  "lblSkipLocHeader": "略過位置 (0)",
  "lblSkipLocation": "位置",
  "lblSkipLocTab": "略過位置",
  "skipAllLocationButtonLabel": "略過所有位置",
  "confirmSkipAllLocationsMessage": "將略過所有位置，要否要繼續?",
  "locationAlreadySkippedMessage": "已略過位置",
  "removeAllSkipLocationLabel": "全部移除",
  "newProjectOptionText": "新專案",
  "selectProject": "選擇專案",
  "saveButtonLabel": "儲存",
  "exportToCSVText": "匯出到 CSV",
  "editProjectAttributesToolTip": "編輯專案屬性",
  "projectNameLabel": "專案名稱",
  "saveProjectPopupTitle": "儲存",
  "saveAsLabel": "另存新檔",
  "saveChangesMsg": "想要將變更儲存至 <b>${loadProjectDropdownlabel}</b> 或另存為新專案?",
  "creatingNewProjectErrorMessage": "建立新專案時出錯。 請再試一次。",
  "projectNameFetchingErr": "擷取現有的專案名稱時出錯。 請再試一次。",
  "projectAttributeLoadingErr": "載入專案屬性時出錯。 請再試一次。",
  "attributeUpdatedMsg": "已成功更新屬性。",
  "projectAttributeUpdatingErr": "更新專案屬性時出錯。",
  "loadingProjectDetailsErrorMessage": "擷取標記、屏障和略過位置時出錯。 請再試一次。",
  "savingProjectDetailsErr": "儲存專案詳細資訊時出錯。 請嘗試重新儲存專案。",
  "updatingOutagePolygonErr": "更新中斷多邊形時出錯。 請嘗試重新儲存專案。",
  "deletingExistingPolygonErr": "刪除現有的中斷多邊形時出錯。 請嘗試重新儲存專案。",
  "loadingProjectFeaturesErr": "載入專案圖徵時出錯。 請嘗試重新載入專案。",
  "addingProjectFeaturesErr": "新增專案圖徵時出錯。 請嘗試重新儲存專案。",
  "deletingExistingProjectFeaturesErr": "刪除現有的專案圖徵時出錯。 請嘗試重新儲存專案。",
  "projectNotFoundErr": "找不到專案",
  "projectLayersNotFound": "無法在地圖中使用配置的專案設定圖層。 將在「草稿模式」中載入 widget。",
  "fetchingOutagePolygonMessage": "擷取中斷多邊形時出錯。 請嘗試重新載入專案。",
  "projectNameExistsMessage": "專案名稱已存在。 請使用唯一的專案名稱。",
  "fetchingProjectNamesErrorMessage": "擷取現有的專案名稱時出錯。 請嘗試重新儲存專案。",
  "enterProjectNameMessage": "請輸入專案名稱。",
  "projectLengthErrorMessage": "專案名稱不可大於",
  "gpServiceNotAccessible": "您的帳號沒有必要服務的存取權，因此無法執行此追蹤。",
  "loadingClonedLayerErrorMessage": "載入複製的圖徵圖層時出錯。 請再試一次。",
  "addingFeatureInClonedLayerError": "將圖形新增至複製的圖徵圖層時出錯。 請再試一次。",
  "selectingFeatureInClonedLayerError": "選擇複製的圖徵圖層中的圖形時出錯。 請再試一次。",
  "filteredProjectError": "檢查擷取篩選的專案詳細資訊時出錯。 請再試一次。",
  "filteredProjectMessage": "由於從 Web 地圖或其他 widget 套用篩選器，因此無法使用選擇的專案屬性。 清除篩選器並再試一次。",
  "filteredProjectLoadMessage": "您的專案不再可用。 請選擇作用中專案。",
  "defaultValueForRunButton": "執行",
  "closeButtonLabel": "移除"
});