define({
  "tabs_section_Label": "แท็ป",
  "addTab": "เพิ่มแท็ป",
  "layerName": "ชั้นข้อมูล",
  "layerType": "ประเภทการวิเคราะห์",
  "layerLabel": "ป้ายชื่อ",
  "actions": "การดำเนินการ",
  "closest": "ฟีเจอร์ที่ใกล้ที่สุด",
  "proximity": "ความใกล้ชิด",
  "summary": "สรุป",
  "select_lbl": "-- เลือก --",
  "general_setting_Label": "ตั้งค่าทั่วไป",
  "units_text_lbl": "หน่วยระยะทาง",
  "maximum_distance_lbl": "ฟีเจอร์ที่อยู่ใกล้ที่สุดภายในระยะสูงสุด",
  "buffer_text_lbl": "ป้ายแสดงบัฟเฟอร์",
  "buffer_lbl": "ระยะทางบัฟเฟอร์",
  "buffer_max_lbl": "ระยะบัฟเฟอร์สูงสุด",
  "buffer_min_lbl": "ระยะบัฟเฟอร์ขั้นต่ำ",
  "routing_checkBox": "เปิดใช้งานการกำหนดเส้นทาง",
  "weather_Label": "ตัวเลือกอากาศ",
  "weather_checkBox": "รวมถึงข้อมูลสภาพอากาศ",
  "selectLayers": "เลือกชั้นข้อมูลสภาพอากาศ",
  "currentlySelectedLayer": "เลือกชั้นข้อมูลอากาศ",
  "missingTabLabel": "ตัวอักษาหายไปอย่างน้อยหนึ่งในแท็บ",
  "missingLayerInWebMap": "ไม่พบชั้นข้อมูลการดำเนินงาน",
  "selectFields": "เลือกฟิลด์",
  "addField": "เพิ่มฟิลด์",
  "sum": "รวม",
  "min": "น้อยสุด",
  "max": "สูงสุด",
  "avg": "เฉลี่ย",
  "count": "จำนวน",
  "area": "พื้นที่",
  "length": "ความยาว",
  "count_checkBox": "แสดงการนับข้อมูล",
  "area_checkBox": "แสดงการรวมพื้นที่",
  "length_checkBox": "แสดงการรวความยาว",
  "max_records": "วงเงินสูงสุด",
  "save_label": "ตัวเลือกการบันทึก",
  "save_checkbox": "เปิดใช้การบันทึก",
  "csv_label": "ตัวเลือก CSV",
  "csv_checkbox": "ส่งออกทุกฟิลด์ในชั้นข้อมูล",
  "display_label": "แสดงตัวเลือก",
  "display_checkbox": "การแสดงผลสรุปฟีเจอร์",
  "snapshot_label": "ตัวเลือกสแนปซ็อต",
  "snapshot_checkbox": "เปิดใช้งานสแนปซ็อต",
  "must_select_template": "กรุณาเลือกหนึ่งในแม่แบบเพื่อการแก้ไขในตัวเลือกการบันทึก",
  "count_label": "นัดจำนวนป้าย",
  "area_label": "ป้ายข้อความของพื้นที่",
  "length_label": "ป้ายข้อความของความยาว",
  "invalid_string_width": "ค่ายาวมากเกินไป ",
  "layer_type_not_supported": "ประเภทของชั้นข้อมูลไม่สามารถใช้งานได้ ",
  "groupedSummary": "นับจำนวนกลุ่ม",
  "groupByField": "จัดกลุ่มด้วยฟิลด์",
  "labelType": "รวมป้ายชื่อ",
  "prefix": "เป็นคำนำหน้า",
  "suffix": "เป็นคำต่อท้าย",
  "need_group_field": "โปรดใช้การแก้ไข เพื่อกำหนดกลุ่มโดยฟิลด์",
  "fieldTitle": "ฟิลด์",
  "typeTitle": "ชนิด",
  "actionsTitle": "การดำเนินการ",
  "save_point_checkbox": "บันทึกจุด",
  "save_line_checkbox": "บันทึกเส้น",
  "save_poly_checkbox": "บันทึกพื้นที่",
  "no_valid_popup_fields": "ไม่มีฟิลด์ข้อมูลที่ถูกต้องในป๊อปอัพ ให้ใช้การแก้ไขเพื่อกำหนดฟิลด์ข้อมูล",
  "no_valid_fields": "ไม่มีฟิลด์ข้อมูลที่ถูกต้อง ให้ใช้การแก้ไขเพื่อกำหนดฟิลด์ตัวเลือกการแสดง",
  "incident_label": "ป้ายแท็บ",
  "locate_incident_label": "ป้ายของพื้นที่ที่น่าสนใจ",
  "incident": "เหตุการณ์",
  "locate_incident": "ค้นหาเหตุการณ์",
  "buffer_value": "ระยะทางขยายออกไป"
});