define({
  "transparencyLabel": "Caurspīdīgums",
  "outline": "Kontūra",
  "fill": "Pildījums (krāsa tiek lietota tikai tad, ja iestatīts tīrtoņa stils)",
  "style": "Stils",
  "mandatoryLabel": "Obligātais evakuācijas attālums",
  "mandatoryButtonLabel": "Konfigurēt obligātā evakuācijas attāluma iestatījumus",
  "safeLabel": "Drošs evakuācijas attālums",
  "safeButtonLabel": "Konfigurēt droša evakuācijas attāluma iestatījumus",
  "selectOpLayerLabel": "Atlasiet rezultātu darbības slāni",
  "selectDefaultMeasurementLabel": "Atlasiet noklusējuma mērvienību",
  "helpIconTooltip": "Darbības slāņu saraksts ir aizpildīts ar pašreizējās tīmekļa kartes slāņiem, kuriem ir laukuma ģeometrijas veids.",
  "lineStyles": {
    "esriSLSDash": "Svītra",
    "esriSLSDashDot": "Svītra punkts",
    "esriSLSDashDotDot": "Svītra punkts punkts",
    "esriSLSDot": "Punkts",
    "esriSLSLongDash": "Gara svītra",
    "esriSLSLongDashDot": "Gara svītra punkts",
    "esriSLSNull": "Nulle",
    "esriSLSShortDash": "Īsa svītra",
    "esriSLSShortDashDot": "Īsa svītra punkts",
    "esriSLSShortDashDotDot": "Īsa svītra punkts punkts",
    "esriSLSShortDot": "Īsa svītra",
    "esriSLSSolid": "Tīrtoņa"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atpakaļvērsts",
    "esriSFSCross": "Krusts",
    "esriSFSDiagonalCross": "Diagonāls",
    "esriSFSForwardDiagonal": "Uz priekšu",
    "esriSFSHorizontal": "Horizontāli",
    "esriSFSNull": "Nulle",
    "esriSFSSolid": "Tīrtoņa",
    "esriSFSVertical": "Vertikāli"
  },
  "threatTypeLabel": "Apdraudējuma veids",
  "symbologyLabel": "Simbolizācija",
  "generalLabel": "Vispārīgi",
  "addThreatTypesLabel": "Pievienot apdraudējuma veidu",
  "threatTypeColLabel": "Apdraudējuma veids",
  "actions": "Darbības",
  "newThreatTypePopupLabel": "Jauns apdraudējuma veids",
  "chooseDefaultThreatTypeIconLabel": "Izvēlēties no noklusējuma",
  "mandatoryDistance": "Obligātais evakuācijas attālums",
  "safeDistance": "Drošais evakuācijas attālums",
  "units": "Mērvienības",
  "chooseDefaultThreatLabel": "Atlasīt noklusējuma apdraudējuma veidu",
  "defaultThreatTypePopUpLabel": "Noklusējuma apdraudējuma veidi",
  "editThreatLabel": "Rediģēt apdraudējumu",
  "defaultThreatTypeIconTooltip": "Noklusējuma apdraudējuma veidu saraksts",
  "uniqueThreatTypeMsg": "Ievadiet unikālu apdraudējuma veidu; apdraudējuma veids ar šādu nosaukumu jau pastāv.",
  "requiredThreatTypeMsg": "Šis ir obligāti aizpildāms lauks",
  "unitMeasureLabel": "Attālumi ir norādīti {0}",
  "pipeBombLabel": "Spridzeklis",
  "suicideBombLabel": "Pašnāvnieka spridzeklis",
  "briefcaseLabel": "Portfelis",
  "carLabel": "Automašīna",
  "suvVanLabel": "Pilnpiedziņas automašīna/furgons",
  "smallDeliveryTruckLabel": "Maza piegādes automašīna",
  "containerWaterTruckLabel": "Konteineru/ūdens pārvadāšanas mašīna",
  "semiTrailerLabel": "Puspiekabe"
});