define({
  "transparencyLabel": "Transparência",
  "outline": "Contorno",
  "fill": "Preencher (a cor somente se aplica quando o estilo é definido para sólido)",
  "style": "Estilo",
  "mandatoryLabel": "Distância Obrigatória de Evacuação",
  "mandatoryButtonLabel": "Definir Configurações de Distância Obrigatória de Evacuação",
  "safeLabel": "Distância de Evacuação Segura",
  "safeButtonLabel": "Definir Configurações de Distância de Evacuação Segura",
  "selectOpLayerLabel": "Selecione uma camada operacional para resultados",
  "selectDefaultMeasurementLabel": "Selecione uma unidade de medição padrão.",
  "helpIconTooltip": "A lista de camada operacional é preenchida com camadas a partir do mapa da web atual que são do tipo de geometria de polígono.",
  "lineStyles": {
    "esriSLSDash": "Traço",
    "esriSLSDashDot": "Traço Ponto",
    "esriSLSDashDotDot": "Traço Ponto Ponto",
    "esriSLSDot": "Ponto",
    "esriSLSLongDash": "Traço Longo",
    "esriSLSLongDashDot": "Traço Longo Ponto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Traço Curto",
    "esriSLSShortDashDot": "Ponto Traço Curto",
    "esriSLSShortDashDotDot": "Ponto Ponto Traço Curto",
    "esriSLSShortDot": "Ponto Curto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Para Trás",
    "esriSFSCross": "Transversal",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Para Frente",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  },
  "threatTypeLabel": "Tipo de Camada",
  "symbologyLabel": "Simbologia",
  "generalLabel": "Geral",
  "addThreatTypesLabel": "Adicionar Tipo de Camada",
  "threatTypeColLabel": "Tipo de camada",
  "actions": "Ações",
  "newThreatTypePopupLabel": "Novo Tipo de Camada",
  "chooseDefaultThreatTypeIconLabel": "Escolher do padrão",
  "mandatoryDistance": "Distância Obrigatória de Evacuação",
  "safeDistance": "Distância de Evacuação Segura",
  "units": "Unidades",
  "chooseDefaultThreatLabel": "Selecione um tipo de camada padrão",
  "defaultThreatTypePopUpLabel": "Tipos de Camada Padrão",
  "editThreatLabel": "Editar Camada",
  "defaultThreatTypeIconTooltip": "Lista do Tipo de Camada Padrão",
  "uniqueThreatTypeMsg": "Insira o tipo de camada único, o tipo de camada com este nome já existe.",
  "requiredThreatTypeMsg": "Este campo é obrigatório.",
  "unitMeasureLabel": "As distâncias estão em {0}",
  "pipeBombLabel": "Bomba Caseira",
  "suicideBombLabel": "Ataque Suicida",
  "briefcaseLabel": "Porta-arquivos",
  "carLabel": "Carro",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Caminhão de entrega pequeno",
  "containerWaterTruckLabel": "Contêiner/Caminhão Pipa",
  "semiTrailerLabel": "Semi-Trailer"
});