define({
  "chartSettingLabel": "Diagramos nustatymai",
  "addNewLabel": "Pridėti naują",
  "generalSettingLabel": "Bendrieji parametrai",
  "layerChooser": {
    "title": "Pasirinkite diagramos sluoksnį",
    "selectPolygonLayerLabel": "Pasirinkite sluoksnį",
    "selectPolygonLayerHintText": "Patarimas: jei konfigūruojate kelias diagramas, sluoksniai turi būti to paties geometrijos tipo",
    "selectRelatedTableLayerLabel": "Pasirinkti su sluoksniu susijusią lentelę",
    "selectRelatedTableLayerHintText": "Patarimas: rodomos tik lentelės su skaitiniais laukais",
    "errorInSelectingPolygonLayer": "Pasirinkite sluoksnį, kuriame yra susijusių taškų sluoksnis.",
    "errorInSelectingRelatedLayer": "Pasirinkite tinkamą lentelę / sluoksnį, susijusį su sluoksniu.",
    "polygonLayerNotHavingRelationships": "Pasirinktas sluoksnis neturi susijusių lentelių / sluoksnių."
  },
  "ChartSetting": {
    "sectionTitle": "Skilties pavadinimas",
    "sectionTitleHintText": "Patarimas: rodoma skilties antraštės pavadinime",
    "chartTitle": "Diagramos pavadinimas",
    "chartTitleHintText": "Užuomina: rodomas centre diagramos viršuje",
    "chartDescription": "Aprašymas",
    "chartDescriptionHintText": "Užuomina: rodomas po diagrama",
    "chartType": "Diagramos tipas",
    "barChart": "Stulpelinė diagrama",
    "pieChart": "Skritulinė diagrama",
    "polarChart": "Polinė diagrama",
    "dataSeriesField": "Duomenų serijos laukas",
    "labelField": "Žymės laukas",
    "chartColor": "Diagramos spalva",
    "singleColor": "Viena spalva",
    "colorByTheme": "Spalva pagal temą",
    "colorByFieldValue": "Spalvos pagal laukų reikšmę",
    "xAxisTitle": "X ašies pavadinimas",
    "xAxisHintText": "Patarimas: X ašies pavadinimas",
    "yAxisTitle": "Y ašies pavadinimas",
    "yAxisHintText": "Patarimas: Y ašies pavadinimas",
    "fieldColorLabel": "Žymė",
    "fieldColorColor": "Spalva",
    "defaultFieldSelectLabel": "Pasirinkite",
    "errMsgFieldValuesNotFound": "Nepavyko rasti pasirinkto lauko reikšmių",
    "errMsgSectionTitle": "Įveskite skilties pavadinimą",
    "errMsgFieldByValue": "Pasirinkite lauko reikšmę",
    "settingTabTitle": "Nustatymas",
    "layoutTabTitle": "Maketas",
    "polarChartSelectFieldsHintText": "Užuomina: pasirinkite laukus, kuriais remdamiesi norite sugeneruoti polinę diagramą",
    "visibilityText": "Matomumas",
    "fieldNameText": "Lauko pavadinimas",
    "aliasNameText": "Pseudonimas",
    "errMsgPolarFieldsRequired": "Pasirinkite tris ar daugiau laukų, kuriais remdamiesi norite sugeneruoti polinę diagramą",
    "polarChartPolygonFillLabel": "Užpildykite plotą",
    "polarChartPolygonFillHintText": "Užuomina: pasirinkite žymės langelį, parodantį ploto užpildymą polinėje diagramoje",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Bendrieji parametrai",
    "locationSymbolLabel": "Grafinis vietos simbolis",
    "locationSymbolHintText": "Patarimas: naudojama adreso ir paspaudimo vietos simboliui rodyti",
    "refreshIntervalLabel": "Atnaujinimo intervalas",
    "refreshIntervalHintText": "Patarimas: naudojama diagramoms atnaujinti, atsižvelgiant į šį intervalą. Nurodykite reikšmę nuo 1 iki 1440 minučių",
    "errMsgRefreshInterval": "Nurodykite atnaujinimo intervalą nuo 0 iki 1440 minučių",
    "symbolPickerPreviewText": "Peržiūra:"
  }
});