define({
  "transparencyLabel": "투명도",
  "outline": "윤곽선",
  "fill": "채우기(스타일이 솔리드로 설정된 경우에만 색상이 적용됨)",
  "style": "스타일",
  "mandatoryLabel": "의무 대피 거리",
  "mandatoryButtonLabel": "의무 대피 거리 설정 구성",
  "safeLabel": "안전 대피 거리",
  "safeButtonLabel": "안전 대피 거리 설정 구성",
  "selectOpLayerLabel": "결과에 대한 운영 레이어 선택",
  "selectDefaultMeasurementLabel": "측정의 기본 단위 선택",
  "helpIconTooltip": "운영 레이어 목록은 폴리곤 지오메트리 유형인 현재 웹맵의 레이어로 채워집니다.",
  "lineStyles": {
    "esriSLSDash": "대시",
    "esriSLSDashDot": "대시 점",
    "esriSLSDashDotDot": "대시 점 점",
    "esriSLSDot": "점",
    "esriSLSLongDash": "긴 대시",
    "esriSLSLongDashDot": "긴 대시 점",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "짧은 대시",
    "esriSLSShortDashDot": "짧은 대시 점",
    "esriSLSShortDashDotDot": "짧은 대시 점 점",
    "esriSLSShortDot": "짧은 점",
    "esriSLSSolid": "실선"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "뒤로",
    "esriSFSCross": "십자모양",
    "esriSFSDiagonalCross": "대각선",
    "esriSFSForwardDiagonal": "순방향",
    "esriSFSHorizontal": "수평",
    "esriSFSNull": "Null",
    "esriSFSSolid": "실선",
    "esriSFSVertical": "수직"
  },
  "threatTypeLabel": "위협 유형",
  "symbologyLabel": "심볼",
  "generalLabel": "일반(General)",
  "addThreatTypesLabel": "위협 유형 추가",
  "threatTypeColLabel": "위협 유형",
  "actions": "실행",
  "newThreatTypePopupLabel": "새 위협 유형",
  "chooseDefaultThreatTypeIconLabel": "기본 유형에서 선택",
  "mandatoryDistance": "의무 대피 거리",
  "safeDistance": "안전 대피 거리",
  "units": "단위",
  "chooseDefaultThreatLabel": "기본 위협 유형 선택",
  "defaultThreatTypePopUpLabel": "기본 위협 유형",
  "editThreatLabel": "위협 편집",
  "defaultThreatTypeIconTooltip": "기본 위협 유형 목록",
  "uniqueThreatTypeMsg": "고유 위협 유형을 입력하세요. 해당 이름의 위협 유형이 이미 존재합니다.",
  "requiredThreatTypeMsg": "이 필드는 필수 항목입니다.",
  "unitMeasureLabel": "거리는 {0}에 있음",
  "pipeBombLabel": "파이프 폭탄",
  "suicideBombLabel": "자살 폭탄",
  "briefcaseLabel": "서류 가방",
  "carLabel": "자동차",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "소형 배송 트럭",
  "containerWaterTruckLabel": "컨테이너/급수 트럭",
  "semiTrailerLabel": "세미 트레일러"
});