define({
  "_widgetLabel": "Praćenje mreže",
  "_featureAction_NetworkTraceSkip": "Preskoči u tragu",
  "_featureAction_NetworkTraceUnskip": "Ukloni iz lokacija za preskakanje",
  "removedFromSkipLocations": "Uklonjeno iz lokacija za preskakanje",
  "alreadyRemovedFromSkipLocations": "Već uklonjeno iz lokacija za preskakanje",
  "locationSkipped": "Lokacija je preskočena",
  "configError": "Vidžet nije pravilno konfigurisan.",
  "geometryServiceURLNotFoundMSG": "Dobijanje URL servisa geometrije nije moguće",
  "clearButtonValue": "Obriši",
  "GPExecutionFailed": "Nije moguće završiti praćenje toka. Pokušajte ponovo.",
  "backButtonValue": "Nazad",
  "exportToCSVSuccess": "Izvoženje u CSV je uspešno završeno.",
  "lblInputLocTab": "Unos lokacija",
  "lblBlockLocTab": "Blokiraj lokacije",
  "lblInputLocation": "Unos geoobjekta",
  "lblBlockLocation": "Blokiraj geoobjekat",
  "lblInputLocHeader": "Unos lokacija (0)",
  "lblBlockLocHeader": "Blokiraj lokacije (0)",
  "inputTabTitle": "Ulaz",
  "outputTabTitle": "Izlaz",
  "exportSelectAllCheckBoxLabel": "Selektuj sve",
  "lblSkipLocHeader": "Preskoči lokacije (0)",
  "lblSkipLocation": "Lokacija",
  "lblSkipLocTab": "Preskoči lokacije",
  "skipAllLocationButtonLabel": "Preskoči sve lokacije",
  "confirmSkipAllLocationsMessage": "Sve lokacije će biti preskočene, želite li da nastavite?",
  "locationAlreadySkippedMessage": "Lokacija je već preskočena",
  "removeAllSkipLocationLabel": "Ukloni sve",
  "newProjectOptionText": "Novi projekat",
  "selectProject": "Izaberi projekat",
  "saveButtonLabel": "Sačuvaj",
  "exportToCSVText": "Izvezi u CSV",
  "editProjectAttributesToolTip": "Izmeni atribute projekta",
  "projectNameLabel": "Naziv projekta",
  "saveProjectPopupTitle": "Sačuvaj",
  "saveAsLabel": "Sačuvaj kao",
  "saveChangesMsg": "Želite li da sačuvate izmene na <b>${loadProjectDropdownlabel}</b> ili da sačuvate kao novi projekat?",
  "creatingNewProjectErrorMessage": "Greška prilikom kreiranja novog projekta. Pokušajte ponovo.",
  "projectNameFetchingErr": "Greška prilikom dobavljanja postojećih naziva projekata. Pokušajte ponovo.",
  "projectAttributeLoadingErr": "Greška prilikom učitavanja atributa projekta. Pokušajte ponovo.",
  "attributeUpdatedMsg": "Atributi su uspešno ažurirani.",
  "projectAttributeUpdatingErr": "Greška prilikom ažuriranja atributa projekta.",
  "loadingProjectDetailsErrorMessage": "Greška prilikom dobavljanja zastava, barijera i lokacija za preskakanje. Pokušajte ponovo.",
  "savingProjectDetailsErr": "Greška prilikom čuvanja detalja o projektu. Pokušajte ponovo da sačuvate projekat.",
  "updatingOutagePolygonErr": "Greška prilikom ažuriranja poligona nestanka struje. Pokušajte ponovo da sačuvate projekat.",
  "deletingExistingPolygonErr": "Greška prilikom brisanja postojećeg poligona nestanka struje. Pokušajte ponovo da sačuvate projekat.",
  "loadingProjectFeaturesErr": "Greška prilikom učitavanja geoobjekata projekta. Pokušajte ponovo da učitate projekat.",
  "addingProjectFeaturesErr": "Greška prilikom dodavanja geoobjekata projekta. Pokušajte ponovo da sačuvate projekat.",
  "deletingExistingProjectFeaturesErr": "Greška prilikom brisanja postojećih geoobjekata projekta. Pokušajte ponovo da sačuvate projekat.",
  "projectNotFoundErr": "Projekat nije pronađen",
  "projectLayersNotFound": "Slojevi postavki konfigurisanog projekta nisu dostupni na mapi. Vidžet će se učitati u 'Režimu skice'.",
  "fetchingOutagePolygonMessage": "Greška prilikom dobavljanja poligona nestanka struje. Pokušajte ponovo da učitate projekat.",
  "projectNameExistsMessage": "Naziv projekta već postoji. Iskoristite jedinstveni naziv projekta.",
  "fetchingProjectNamesErrorMessage": "Greška prilikom dobavljanja postojećih naziva projekata. Pokušajte ponovo da sačuvate projekat.",
  "enterProjectNameMessage": "Unesite naziv projekta.",
  "projectLengthErrorMessage": "Naziv projekta ne može biti duži od",
  "gpServiceNotAccessible": "Vaš nalog nema pristup servisu koji je potreban za ovo praćenje.",
  "loadingClonedLayerErrorMessage": "Greška prilikom učitavanja kloniranog sloja geoobjekata. Pokušajte ponovo.",
  "addingFeatureInClonedLayerError": "Greška prilikom dodavanja grafike u klonirani sloj geoobjekata. Pokušajte ponovo.",
  "selectingFeatureInClonedLayerError": "Greška prilikom selektovanja grafike u kloniranom sloju geoobjekata. Pokušajte ponovo.",
  "filteredProjectError": "Greška pri proveravanju dobavljanja filtriranih detalja o projektu. Pokušajte ponovo.",
  "filteredProjectMessage": "Izabrani atributi projekta nisu dostupni usled primenjenih filtera iz veb mape ili drugog vidžeta. Obrišite filter(e) i pokušajte ponovo.",
  "filteredProjectLoadMessage": "Vaš projekat više nije dostupan. Izaberite aktivan projekat.",
  "defaultValueForRunButton": "Pokreni",
  "closeButtonLabel": "Ukloni"
});