define({
  "styleText": "Kaydırma aracı için stil seçin",
  "vertical": "Dikey çubuk",
  "horizontal": "Yatay çubuk",
  "scope": "Dürbün",
  "barColor": "Çubuk rengi",
  "swipeMode": "Kaydırma modu",
  "singleLayer": "Tek katman",
  "MultipleLayers": "Birden Çok Katman",
  "allowToSwipe": "Kaydırmaya izin ver",
  "layer": "Katman",
  "swipeByDefault": "Varsayılan olarak kaydır",
  "defaultLayerMustBeVisible": "varsayılan katman görünür olmalıdır",
  "noDefaultLayer": "Lütfen varsayılan olarak kaydırılacak katmanları ayarlayın",
  "defaultLayerHolder": "Seçmek için tıklayın",
  "selectLayers": "Katmanları seç",
  "layerText": "Varsayılan olarak kaydırmak istediğiniz katman(lar)ı seçin",
  "spyglassText": "Küçük dürbünde varsayılan olarak görüntülenecek katmanı seçin.",
  "layerHint": "Not: Katman daha üst katmanlar tarafından gizleniyorsa, kaydırmanın herhangi bir etkisi olmaz.",
  "isZoom": "Kaydırma katmanına yakınlaştır",
  "isZooms": "Kaydırma katman(lar)ına yakınlaştır",
  "layersAvailable": "Kaydırılacak katmanları seç:"
});