define({
  "_widgetLabel": "الرؤية",
  "observerLocation": "موقع المُراقِب",
  "formatIconTooltip": "مدخلات التنسيق",
  "addPointToolTip": "إضافة موقع المراقب",
  "fieldOfView": "حقل العرض",
  "useMilsText": "استخدم الأميال للزوايا",
  "observerHeight": "ارتفاع المراقب",
  "minObsDistance": "أدنى مسافة يمكن ملاحظتها",
  "maxObsDistance": "أقصى مسافة يمكن ملاحظتها",
  "taskURLError": "يحتوي ملف تكوين عنصر واجهة المستخدم على عنوان URL لا يمكن الوصول إليه. يرجى التحقق من مسؤول النظام",
  "taskURLInvalid": "مهمة المعالجة الجغرافية التي تم تكوينها بواسطة عنصر واجهة المستخدم غير صحيحة. يرجى التحقق من مسؤول النظام",
  "viewshedError": "حدث خطأ أثناء إنشاء الرؤية. يرجى التأكد من وقوع موقع المراقِب ضمن مدى ارتفاع السطح.</p>",
  "validationError": "<p>يفتقد نموذج إنشاء الرؤية إلى بعض المعلمات أو أن بعض المعلمات غير صحيحة. يرجى التأكد من:</p><ul><li>تعيين موقع المراقِب.</li><li>ألا يكون حقل عرض المراقب يساوي 0.</li><li>احتواء ارتفاع المراقب على قيمة صحيحة.</li><li>احتواء أدنى وأقصى مسافة ملحوظة على قيم صحيحة.</li></ul>",
  "comfirmInputNotation": "تأكيد علامة المدخلات",
  "notationsMatch": "التعليقات التي تطابق المدخلات. يرجى تأكيد ما تريد استخدامه:",
  "createBtn": "إنشاء",
  "clearBtn": "مسح",
  "setCoordFormat": "تعيين سلسلة تنسيق الإحداثيات",
  "prefixNumbers": "أضف البادئة '+/-' إلى الأرقام السالبة والموجبة",
  "parseCoordinatesError": "يتعذر تحليل الإحداثيات. يرجى التحقق من مدخلاتك.",
  "cancelBtn": "إلغاء الأمر",
  "applyBtn": "تطبيق",
  "invalidMessage": "الرجاء إدخال قيمة عددية.",
  "observerRangeMessage": "ارتفاع المراقب غير صحيح",
  "minimumRangeMessage": "الحد الأدنى للنطاق الملحوظ غير صحيح",
  "maximumRangeMessage": "يجب أن يكون الحد الأقصى للنطاق الملحوظ أكبر من الحد الأدنى للنطاق الملحوظ ولا يمكن أن يكون أكثر من ${limit} ${units}.",
  "portalURLError": "عنوان URL لمؤسسة ArcGIS Online أو Portal for ArcGIS غير مكون. يرجى التحقق مع مسؤول النظام",
  "privilegeError": "دور المستخدم الخاص بك لا يمكنه إجراء تحليل. لتنفيذ التحليل، يتعين على مسئول المؤسسة منحك <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">امتيازات</a> محددة.",
  "noServiceError": "خدمة تحليل الارتفاع غير متوفرة. يرجى التحقق من تكوينات مؤسسة ArcGIS Online أو Portal for ArcGIS.",
  "pointToolTooltip": "انقر لإضافة موقع المراقب",
  "degreesLabel": "درجات",
  "milsLabel": "أميال",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "درجة دقيقة ثانية",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "الدرجات العشرية - دائرة العرض/خط الطول",
  "DDLongLatNotation": "الدرجات العشرية - خط الطول/دائرة العرض",
  "DDMLatLongNotation": "دقائق عشرية درجات - دائرة العرض/خط الطول",
  "DDMLongLatNotation": "دقائق عشرية درجات - خط الطول/دائرة العرض",
  "DMSLatLongNotation": "ثواني دقائق درجات - دائرة العرض/خط الطول",
  "DMSLongLatNotation": "ثواني دقائق درجات - خط الطول/دائرة العرض",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - حرف الحزمة",
  "UTMHemNotation": "UTM - نصف الكرة (N/S)",
  "mainPageTitle": "خط الرؤية الشعاعي",
  "resultsTitle": "النتائج",
  "publishBtnLabel": "نشر",
  "layerName": "اسم الطبقة المنشورة",
  "invalidLayerName": "يجب ألا يحتوي اسم الطبقة إلا على أحرف أبجدية رقمية وتسطير سفلي",
  "missingLayerName": "أدخل اسم الطبقة",
  "back": "رجوع",
  "publishingFailedLayerExists": "فشل النشر: لديك بالفعل خدمة معالم باسم {0}. يرجى اختيار اسم آخر.",
  "checkService": "فحص الخدمة: {0}.",
  "createService": "إنشاء الخدمة: {0}.",
  "unableToCreate": "يتعذر إنشاء: {0}",
  "addToDefinition": "إضافة إلى تعريف: {0}",
  "successfullyPublished": "تم نشر طبقة الويب بشكل ناجح{0}إدارة طبقة الويب",
  "userRole": "يتعذر إنشاء الخدمة لأن المستخدم لا يمتلك الأذونات",
  "publishToNewLayer": "نشر النتائج إلى طبقة معلم جديدة",
  "missingLayerNameMessage": "يجب إدخال اسم طبقة صالح قبل النشر",
  "regionTypeLabel": "نوع المنطقة",
  "centerPointLabel": "نقطة المركز",
  "observationHeightLabel": "ارتفاع الملاحظة",
  "heightUnitLabel": "وحدة الارتفاع",
  "minObservationDistanceLabel": "الحد الأدنى لمسافة الملاحظة",
  "maxObservationDistance": "الحد الأقصى لمسافة الملاحظة",
  "distanceUnitLabel": "وحدة المسافة",
  "fovstartAngleLabel": "زاوية بداية حقل العرض (FoV)",
  "fovEndAngleLabel": "زاوية نهاية حقل العرض (FoV)",
  "andleUnitsLabel": "وحدات الزاوية"
});