define({
  "serviceUrl": "設定服務 url:",
  "minIntSpacingLabel": "最小間隔間距",
  "lineOpacityLabel": "線不透明度",
  "labelOpacityLabel": "標籤不透明度",
  "centerLabelOpacityLabel": "中心標籤不透明度",
  "gridZonePlacementLabel": "網格區域標籤放置",
  "verticalLineLabels": "垂直線標籤",
  "styleHeaderLabel": "樣式",
  "indexHeaderLabel": "索引",
  "colorHeaderLabel": "顏色",
  "fontSizeHeaderLabel": "字型大小",
  "lineWidthHeaderLabel": "線寬度",
  "horizontalLabel": "水平對齊",
  "verticalLabel": "垂直",
  "upperLeftLabel": "左上",
  "upperRightLabel": "右上",
  "lowerLeftLabel": "左下",
  "lowerRightLabel": "右下",
  "centerLabel": "居中對齊",
  "errorMessage": "配置頁面包含錯誤。請先修正再儲存。",
  "checkBoxLabel": "關閉 widget 後顯示方格。"
});