define({
  "businessAnalyst": "Business Analyst",
  "defineWhichInfographics": "Xác định thông tin đồ họa nào có sẵn trong tiện ích:",
  "defineWhichReports": "Xác định báo cáo nào có sẵn trong tiện ích:",
  "defaultValues": "Giá trị mặc định:",
  "disable": "Vô hiệu hóa",
  "driveTime": "Thời gian lái xe",
  "infographics": "Thông tin đồ họa",
  "invalidValueRing": "Giá trị phải nằm trong khoảng 0 đến 1.000.",
  "invalidValueDTWT": "Giá trị phải nằm trong khoảng 0 đến 300.",
  "km": "km",
  "miles": "dặm",
  "minutes": "phút",
  "radius": "Bán kính",
  "reports": "Báo cáo",
  "rings": "Vòng",
  "selectCountry": "Chọn quốc gia:",
  "thisEntryIsNotValid": "Thông tin nhập này không hợp lệ.",
  "time": "Thời gian",
  "walkTime": "Thời gian đi bộ"
});