define({
  "settings": "Beállítások",
  "titleSettings": "Szövegbeállítások",
  "imageSettings": "Képbeállítások",
  "backgroundColor": "Háttérszín",
  "alignment": "Igazítás",
  "textSize": "Szövegméret",
  "textColor": "Szövegszín",
  "dataSource": "Adatforrás",
  "chartSettings": "Diagrambeállítások",
  "data": "Adatok",
  "dataLabels": "Adatfeliratok",
  "displayMode": "Megjelenítési mód",
  "featureOption": "Értékek megjelenítése vektoros elemenként",
  "categoryOption": "Értékek megjelenítése kategóriánként",
  "countOption": "Vektoros elemek számának megjelenítése kategóriánként",
  "fieldOption": "Attribútumértékek megjelenítése diagramként",
  "categoryField": "Kategóriamező",
  "labelField": "Feliratmező",
  "valueFields": "Értékmezők",
  "operation": "Művelet",
  "sumOption": "Összeg",
  "averageOption": "Átlag",
  "minOption": "Minimum",
  "maxOption": "Maximum",
  "countString": "Darabszám",
  "dataFormat": "Adatformátum",
  "decimalPlaces": "Tizedesjegyek",
  "prefix": "Előtag",
  "suffix": "Utótag",
  "dataType": "Adattípus",
  "featureCount": "Vektoros elemek száma",
  "fieldStatistics": "Mezőstatisztika",
  "display": "Megjelenítés",
  "chartColor": "Diagram színe",
  "horizontalAxis": "Vízszintes tengely",
  "verticalAxis": "Függőleges tengely",
  "legend": "Jelmagyarázat",
  "position": "Helyzet",
  "top": "Fent",
  "bottom": "Lent",
  "useDataSourceSelection": "Kijelölés használata",
  "dataSourceFilterByExtent": "Szűrés kiterjedés szerint",
  "changeTemplate": "Sablon módosítása",
  "numberSettings": "Számbeállítások",
  "gaugeSettings": "Mérőpanel-beállítások",
  "indicators": "Jelzők",
  "ifValue": "Ha az érték",
  "and": "és",
  "numberOperatorIsLessThan": "kevesebb, mint",
  "numberOperatorIsGreaterThan": "nagyobb, mint",
  "numberOperatorIsBetween": "közötte van",
  "numberOperatorIsEqual": "egyenlő",
  "numberOperatorIsNotEqual": "nem egyenlő",
  "then": "Akkor",
  "ratio": "Arány",
  "trueValue": "Valós érték",
  "changeValueColor": "az érték színe legyen",
  "changeGaugeColor": "a mérőpanel színe legyen",
  "setIndicatorIcon": "a jelzőikon legyen",
  "icons": "Ikonok",
  "style": "Stílus",
  "placement": "Elhelyezés",
  "left": "Bal",
  "replace": "Csere",
  "right": "Jobb",
  "color": "Szín",
  "categoryExists": "A kategória létezik.",
  "comboxHint": "Írjon be vagy válasszon egyet",
  "comboxDisableInputHint": "Válasszon egyet",
  "sortBy": "Rendezési szempont",
  "labelAxis": "Felirat",
  "valueAxis": "Érték",
  "minPeriod": "Minimum időszak",
  "automatic": "Automatikus",
  "periodsWithOutRecords": "Rekordok nélküli időszakok",
  "nullValue": "Null érték",
  "calculatedAsZero": "Nullaként kiszámított",
  "ignored": "Figyelmen kívül hagyva",
  "maxCategories": "Kategóriák maximális száma",
  "useLayerSymbology": "A réteg szimbólumrendszerének használata",
  "hollowsize": "Kitöltetlen méret",
  "splitField": "Mező felosztása",
  "parsingperiodTip": "A számítás nem sikerült. A rövid elemzési időszak miatt túl sok az időintervallum.",
  "manyCategoryTip": "A túl sok kategória miatt nem sikerült megjeleníteni a diagramot.",
  "setColor": "Szín beállítása",
  "setTheColorOf": "Ezután állítsa be a következő színét:",
  "setTheColorAs": "Ezután állítsa be a színt a következőként:",
  "ifStr": "Ha",
  "as": "mint",
  "is": "ez",
  "isNot": "nem ez",
  "barCluster": "sávklaszter",
  "individualBar": "egyedi sáv",
  "allOthers": "Minden más",
  "category": "Kategória",
  "indicatorSum": "ÖSSZ.",
  "indicatorAve": "ÁTL.",
  "indicatorMax": "MAX.",
  "indicatorMin": "MIN.",
  "setCorrectyIndicatorTip": "Állítsa be a megfelelően a indikátorokat.",
  "dataRange": "Adattartomány",
  "targetValue": "Célérték",
  "currentValue": "Aktuális érték",
  "gaugeColor": "Mérőpanel színe",
  "min": "Minimum",
  "max": "Maximum",
  "displayValueIn": "Érték megjelenítése ebben:",
  "noData": "Nincs adat",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Figyelmeztetés",
  "noSettingWaring1": "Kattintson egy elemre a tulajdonságainak beállításához.",
  "noSettingWaring2": "Húzással átméretezheti vagy átrendezheti az elemeket.",
  "donNotShowAgain": "Ne jelenjen meg még egyszer",
  "changeTemplateWarning": "Ez törli az összes beállítást, és új üres sablont nyit meg.",
  "requiredFieldWarning": "Ezt az értéket kötelező megadni:",
  "dataSourceNotSet": "Állítsa be az adatforrást.",
  "addIndicatorTip": "Jelző hozzáadása",
  "chooseTemplatePopupTitle": "Sablon kiválasztása",
  "filterExtentTipWithaTag": "A szűrőt az Attribútum fülön található <a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>Extra adatforrás</a> lehetőséggel tilthatja le.",
  "filterExtentTip": "A szűrőt az Attribútum fülön található Extra adatforrás lehetőséggel tilthatja le.",
  "customColorByCategory": "Egyéni szín kategória szerint",
  "randomColor": "Véletlen szín",
  "valueString": "Érték",
  "fieldString": "Mező",
  "includeThresholdValue": "Küszöbértékkel együtt",
  "percentage": "Százalék",
  "colorSchema": "Színséma",
  "addCategory": "Kategória hozzáadása",
  "clickToEdit": "Kattintson ide a szerkesztéshez",
  "nullText": "Null",
  "others": "Egyéb",
  "dsErrorTipSuf": "nem érhető el.",
  "front": "Elülső",
  "back": "Hátsó",
  "title": "Cím",
  "titleColor": "Cím színe",
  "labelString": "Felirat",
  "labelSize": "Felirat mérete",
  "labelColor": "Felirat színe",
  "addMarkLine": "Vonaljel hozzáadása",
  "addMarkArea": "Területjel hozzáadása",
  "labelPosition": "Felirat pozíciója",
  "toString": "eddig",
  "start": "Eleje",
  "middle": "Közepe",
  "end": "Vége",
  "inString": "Be",
  "outString": "Ki",
  "lineColor": "Vonalszín",
  "lineWidth": "Vonalvastagság",
  "dashType": "Szaggatott vonal típusa",
  "areaColor": "Terület színe",
  "line": "Vonal",
  "area": "Terület",
  "stringsInTemplate": {
    "name_number": "Szám",
    "name_gauge": "Mérőpanel",
    "name_vertical_gauge": "Függőleges mérőpanel",
    "name_horizontal_gauge": "Vízszintes mérőpanel",
    "name_pie": "Kördiagram",
    "name_donut": "Perec-diagram",
    "name_bar": "Oszlop/sáv",
    "name_stacked_bar": "Halmozott sáv",
    "name_percentage_stacked_bar": "Százalékos halmozott oszlop/sáv",
    "name_column": "Oszlop",
    "name_stacked_column": "Halmozott oszlop",
    "name_percentage_stacked_column": "Százalékos halmozott oszlop",
    "name_line": "Vonal",
    "name_area": "Terület",
    "name_stacked_area": "Halmozott terület",
    "name_percentage_stacked_area": "Százalékos halmozott terület",
    "titleOfTheInfographic": "AZ INFOGRAFIKA CÍME",
    "description": "Leírás: további információ az infografikáról."
  },
  "marks": "Jelölések",
  "displayValue": "Megjelenített érték",
  "statistic": "Statisztika",
  "valueType": "Értéktípus",
  "valueField": "Értékmező",
  "fixed": "Rögzített",
  "sdsTip": "Válasszon az Extra adatforrásban konfigurált statisztikai adatok közül",
  "noSdsTip": "Nincsenek elérhető statisztikai adatok.",
  "intScaleText": "Csak egésszámú méretarányok megjelenítése",
  "resetLayout": "Elrendezés visszaállítása",
  "fbeTip": "Vegye figyelembe, hogy ha az alkalmazást megosztja, és nyilvánossá teszi, akkor ennek a beállításnak az engedélyezése jelentősen lecsökkenti az alkalmazás teljesítményét. Ehelyett javasoljuk, hogy a vektoros elemek nagyításához inkább használjon más widgeteket, mint például Szűrő és Csoportos szűrő."
});