define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Ajouter un point en cliquant sur la carte",
  "addRingsDtWt": "Ajoutez des anneaux, un temps de trajet ou une durée de marche.",
  "apply": "Appliquer",
  "back": "Précédent",
  "colon": ":",
  "creditInformation": "Informations sur les crédits",
  "driveTime": "Temps de conduite",
  "esriInfographics": "Infographie Esri",
  "esriReports": "Rapports Esri",
  "headerDescription_km": "kilomètre",
  "headerDescription_miles": "mile",
  "headerDescription_minutes": "minute",
  "infographics": "Infographie",
  "invalidValueRing": "Les valeurs doivent être comprises entre 0 et 1 000.",
  "invalidValueDTWT": "Les valeurs doivent être comprises entre 0 et 300.",
  "km": "km",
  "miles": "miles",
  "minutes": "minutes",
  "myInfographics": "Mes infographies",
  "myReports": "Mes rapports",
  "noPermissions": "Votre compte ne peut pas exécuter le widget Business Analyst.  Pour exécuter le widget Business Analyst, l’administrateur de votre organisation doit vous accorder les <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilèges</a> Enrichissement géographique et Analyse de réseau, et également allouer des <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">crédits</a>.",
  "geServiceNotConfigured": "Le widget Business Analyst ne peut pas s’exécuter sur ce portail car le service <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Géoenrichissement</a> n’y est pas configuré.",
  "dirRoutingServiceNotConfigured": "Le widget Business Analyst ne peut pas s’exécuter sur ce portail car le service <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Feuille de route et calcul d’itinéraire</a> n’y est pas configuré.",
  "geAndDirRoutingServicesNotConfigured": "Le widget Business Analyst ne peut pas s’exécuter sur ce portail car les services <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Géoenrichissement</a> et <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Feuille de route et calcul d’itinéraire</a> n’y sont pas configurés.",
  "radii": "rayons",
  "radius": "Rayon",
  "radius_lowercase": "rayon",
  "reports": "Rapports",
  "ring": "Anneau",
  "rings": "Anneaux",
  "runInfographic": "Exécuter l’infographie",
  "runReport": "Exécuter le rapport",
  "selectPointOrPolygon": "Sélectionnez une entité ponctuelle ou surfacique sur la carte, recherchez une adresse ou un lieu, ou déposez une épingle sur la carte pour afficher plus d’informations sur les zones.",
  "selectReport": "Sélectionner un rapport",
  "selectTemplate": "Sélectionner un modèle",
  "sharedInfographics": "Infographies partagées",
  "sharedReports": "Rapports partagés",
  "thisEntryIsNotValid": "L’entrée n’est pas valide.",
  "time": "Durée",
  "walkTime": "Temps de marche",
  "widgetDescription": "Accédez aux infographies et rapports qui synthétisent les principaux indicateurs et données sur une zone en particulier.",
  "None": "Sélectionner..."
});