define({
  "_widgetLabel": "座標変換",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "formatInput": "入力の書式設定",
  "copyAll": "すべてコピー",
  "copySuccessful": "コピーに成功しました",
  "copyFailed": "コピーできません。 代替操作として Ctrl + C キーを使用してください。",
  "parseCoordinatesError": "座標を解析できません。 入力を確認してください。",
  "comfirmInputNotation": "入力表記の確認",
  "latLongWarningMessage": "入力座標は、緯度と経度の値に接頭辞と接尾辞が付いていることが検出されました。返される座標は、接頭辞に基づいています。",
  "inputLabel": "入力",
  "outputLabel": "出力",
  "cancelButtonLabel": "キャンセル",
  "applyButtonLabel": "適用",
  "posNegPrefixLabel": "正と負の数値に \"+/-\" の接頭辞を追加",
  "editCoordinateDialogTitle": "座標形式の文字列の設定",
  "rememberDecisionLabel": "選択内容を記憶して、今後このメッセージを表示しません。<br/>",
  "coordinateInputLabel": "座標を入力するか、マップをクリック",
  "zoomLabel": "ズーム",
  "multipleNotationLabel": "入力と一致する表記が見つかりました。 使用する内容を確認してください。",
  "copyToClipboard": "クリップボードにコピー",
  "formatOutput": "出力の書式設定",
  "addNewNotation": "新しい表記の追加",
  "notationAddedMessage": "追加された新しい表記",
  "addLabel": "追加",
  "removeCoordinate": "座標の削除",
  "expandOutput": "出力の展開"
});