///////////////////////////////////////////////////////////////////////////
// Copyright © Esri. All Rights Reserved.
//
// Licensed under the Apache License Version 2.0 (the 'License');
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
///////////////////////////////////////////////////////////////////////////
define({
  "units": {
    "areaSquareFeetUnit": "Kvadratinės pėdos",
    "areaAcresUnit": "Akrai",
    "areaSquareMetersUnit": "Kvadratiniai metrai",
    "areaSquareKilometersUnit": "Kvadratiniai kilometrai",
    "areaHectaresUnit": "Hektarai",
    "areaSquareMilesUnit": "Kvadratinės mylios",
    "lengthFeetUnit": "Pėdos",
    "lengthMilesUnit": "Mylios",
    "lengthMetersUnit": "Metrai",
    "lengthKilometersUnit": "Kilometrai"
  },
  "analysisTab": {
    "analysisTabLabel": "Analizė",
    "selectAnalysisLayerLabel": "Analizės sluoksniai",
    "addLayerLabel": "Pridėti sluoksnius",
    "noValidLayersForAnalysis": "Pasirinktame internetiniame žemėlapyje tinkamų sluoksnių nerasta.",
    "noValidFieldsForAnalysis": "Pasirinktame internetiniame žemėlapyje tinkamų laukų nerasta. Pašalinkite pasirinktą sluoksnį.",
    "allowGroupingLabel": "Grupuoti elementus pagal lauką su ta pačia reikšme",
    "groupingHintDescription": "Patarimas: pagal numatytuosius nustatymus visi elementai su ta pačią pasirinktų laukų reikšme bus sugrupuoti, kad būtų rodomi kaip vienas ataskaitos įrašas. Išjunkite grupavimą pagal panašius atributus, kad būtų rodomas kiekvieno elemento įrašas.",
    "addLayersHintText": "Pastaba: pasirinkite sluoksnius ir laukus, kurie turėtų būti įtraukti į analizę ir ataskaitą",
    "addLayerNameTitle": "Sluoksnio pavadinimas",
    "addFieldsLabel": "Pridėti lauką",
    "addFieldsPopupTitle": "Pasirinkite laukus",
    "addFieldsNameTitle": "Laukų pavadinimai",
    "aoiToolsLegendLabel": "Dominančios teritorijos įrankiai",
    "aoiToolsDescriptionLabel": "Pasirinkite ir pažymėkite įrankius, kuriais galima kurti dominančią teritoriją.",
    "placenameLabel": "Vietos pavadinimas",
    "drawToolsLabel": "Pasirinkite braižymo įrankius",
    "uploadShapeFileLabel": "Įkelti Shape failą",
    "coordinatesLabel": "Koordinatės",
    "coordinatesDrpDwnHintText": "Pastaba: pasirinkite vienetą, skirtą įvestiems pravažiavimams rodyti",
    "coordinatesBearingDrpDwnHintText": "Pastaba: pasirinkite kryptį, skirtą įvestiems pravažiavimams rodyti",
    "allowShapefilesUploadLabel": "Leisti naudotojams įkelti Shape failus, kurie turėtų būti įtraukti į analizę",
    "allowShapefilesUploadLabelHintText": "Pastaba: į skirtuką Ataskaita įtraukite parinktį, kad naudotojai galėtų įkelti savo duomenis kaip Shape failą, skirtą įtraukti į analizės ataskaitą",
    "allowVisibleLayerAnalysisLabel": "Neanalizuokite ir nepraneškite nematomų sluoksnių rezultatų",
    "allowVisibleLayerAnalysisHintText": "Pastaba: sluoksniai, kurie yra išjungti arba nematomi dėl mastelio matomumo parametrų, nebus analizuojami arba įtraukiami į išspausdintus ar atsisiųstus rezultatus.",
    "areaUnitsLabel": "Analizės rezultatų vienetai(Teritorija)",
    "lengthUnitsLabel": "Analizės rezultatų vienetai(Ilgis)",
    "maxFeatureForAnalysisLabel": "Maksimalus analizuotinų elementų skaičius",
    "maxFeatureForAnalysisHintText": "Pastaba: nustatykite didžiausią elementų, kurie bus įtraukti į analizę, skaičių",
    "searchToleranceLabelText": "Paieškos spindulys",
    "searchToleranceHint": "Pastaba: paieškos tolerancija naudojama analizuojant taško ir linijos įvestis",
    "placenameButtonText": "Vietos pavadinimas",
    "drawToolsButtonText": "Brėžti",
    "shapefileButtonText": "Shape failas",
    "coordinatesButtonText": "Koordinatės",
    "invalidLayerErrorMsg": "Sukonfigūruokite laukus, skirtus",
    "drawToolSelectableLayersLabel": "Pasirinkite pasirenkamus sluoksnius",
    "drawToolSelectableLayersHint": "Pastaba: pasirinkite sluoksnius, kuriuose būtų elementų, galimų pasirinkti naudojant pasirinkimo braižymo įrankį",
    "drawToolsSettingsFieldsetLabel": "Braižymo įrankiai",
    "drawToolPointLabel": "Taškas",
    "drawToolPolylineLabel": "Polilinija",
    "drawToolExtentLabel": "Aprėptis",
    "drawToolPolygonLabel": "Poligonas",
    "drawToolCircleLabel": "Apskritimas",
    "selectDrawToolsText": "Pasirinkite braižymo įrankius, kuriais galima kurti dominančią teritoriją",
    "selectingDrawToolErrorMessage": "Pasirinkite bent vieną braižymo įrankį arba pasirinkimo sluoksnį, kad galėtumėte naudoti braižymo įrankių parinktį AOI įrankiai."
  },
  "downloadTab": {
    "downloadLegend": "Atsisiuntimo parametrai",
    "reportLegend": "Ataskaitos parametrai",
    "downloadTabLabel": "Atsisiųsti",
    "syncEnableOptionLabel": "Elementų sluoksniai",
    "syncEnableOptionHint": "Pastaba: pasirinkite sluoksnius, kuriuos galima atsisiųsti ir nurodykite kiekvieno iš sluoksnių formatus. Atsisiųstuose duomenų rinkiniuose bus tie elementai, kurie susikerta su dominančia teritorija.",
    "syncEnableOptionNote": "Pastaba: failinės geoduomenų bazės ir Shape failo atsisiuntimui būtini elementų sluoksniai, kuriuose įgalintas sinchronizavimas. Shape failo formatas palaikomas tik naudojant ArcGIS Online talpinamus elementų sluoksnius.",
    "extractDataTaskOptionLabel": "Duomenų išgavimo geoapdorojimo paslauga",
    "extractDataTaskOptionHint": "Pastaba: norėdami atsisiųsti elementus, kurie susikerta su dominančia teritorija, failinės geoduomenų bazės arba Shape failo formatais, naudokite publikuotą Duomenų išgavimo užduoties geoapdorojimo paslaugą.",
    "cannotDownloadOptionLabel": "Išjungti atsisiuntimą",
    "syncEnableTableHeaderTitle": {
      "layerNameLabel": "Sluoksnio pavadinimas",
      "csvFileFormatLabel": "CSV",
      "fileGDBFormatLabel": "Failinė geoduomenų bazė",
      "ShapefileFormatLabel": "Shape failas",
      "allowDownloadLabel": "Leisti atsisiųsti"
    },
    "setButtonLabel": "Nustatyti",
    "GPTaskLabel": "Nurodykite geoapdorojimo paslaugos URL",
    "printGPServiceLabel": "Spausdinti paslaugos URL",
    "setGPTaskTitle": "Nurodykite reikiamą geoapdorojimo paslaugos URL",
    "logoLabel": "Logotipas",
    "logoChooserHint": "Pastaba: spustelėkite vaizdo piktogramą, kad pakeistumėte viršutiniame kairiajame ataskaitos kampe rodomą logotipą",
    "footnoteLabel": "Išnaša",
    "columnTitleColorPickerLabel": "Ataskaitos stulpelio pavadinimo spalva",
    "reportTitleLabel": "Ataskaitos pavadinimas",
    "displaySummaryLabel": "Pateikti santrauką",
    "hideZeroValueRowLabel": "Slėpti eilutes, jei analizės laukuose nurodyta 0 reikšmė",
    "hideNullValueRowLabel": "Slėpti eilutes, jei analizės laukuose nurodyta reikšmė „nėra duomenų“ (nulinė arba tuščia)",
    "errorMessages": {
      "invalidGPTaskURL": "Netinkama geoduomenų apdorojimo paslauga. Pasirinkite geoapdorojimo paslaugą, kurioje yra duomenų išgavimo užduotis.",
      "noExtractDataTaskURL": "Pasirinkite geoapdorojimo paslaugą, kurioje yra duomenų išgavimo užduotis.",
      "duplicateCustomOption": "Yra pasikartojantis ${duplicateValueSizeName} įrašas.",
      "invalidLayoutWidth": "Įvestas netinkamas ${customLayoutOptionValue} plotis.",
      "invalidLayoutHeight": "Įvestas netinkamas ${customLayoutOptionValue} aukštis.",
      "invalidLayoutPageUnits": "Pasirinktas netinkamas ${customLayoutOptionValue} puslapio vienetas.",
      "failtofetchbuddyTaskDimension": "Gaunant užduoties matmenų informaciją įvyko klaida. Bandykite dar kartą.",
      "failtofetchbuddyTaskName": "Gaunant užduoties pavadinimą įvyko klaida. Bandykite dar kartą.",
      "failtofetchChoiceList": "Gaunant pasirinkimų sąrašą iš spausdinimo paslaugos įvyko klaida. Bandykite dar kartą.",
      "invalidWidth": "Netinkamas plotis.",
      "invalidHeight": "Netinkamas aukštis."
    },
    "addCustomLayoutTitle": "Įtraukti pasirinktinį sluoksnį",
    "customLayoutOptionHint": "Pastaba: į spausdinimo parinktis įtraukite maketą iš savo spausdinimo paslaugos.",
    "reportDefaultOptionLabel": "Numatytasis maketas",
    "pageSizeUnits": {
      "millimeters": "Milimetrai",
      "points": "Taškai"
    },
    "noDataTextRepresentation": "Nėra duomenų reikšmių",
    "naTextRepresentation": "Netaikoma reikšmė",
    "noDataDefaultText": "Nėra duomenų",
    "notApplicableDefaultText": "Netaikoma"
  },
  "generalTab": {
    "generalTabLabel": "Bendra",
    "tabLabelsLegend": "Skydo žymės",
    "tabLabelsHint": "Pastaba: nurodykite žymes",
    "AOITabLabel": "Dominančios teritorijos skiltis",
    "ReportTabLabel": "Ataskaitos skiltis",
    "bufferSettingsLegend": "Buferio parametrai",
    "defaultBufferDistanceLabel": "Numatytasis buferio atstumas",
    "defaultBufferUnitsLabel": "Buferio vienetai",
    "generalBufferSymbologyHint": "Pastaba: simbolizacija, naudojama buferio teritorijai aplink dominančią teritoriją nurodyti",
    "aoiGraphicsSymbologyLegend": "Dominančios teritorijos simbolizacija",
    "aoiGraphicsSymbologyHint": "Pastaba: simbolizacija naudojama taško, linijos ir poligono dominančioms teritorijoms nurodyti",
    "pointSymbologyLabel": "Taškas",
    "previewLabel": "Peržiūra",
    "lineSymbologyLabel": "Linija",
    "polygonSymbologyLabel": "Poligonas",
    "aoiBufferSymbologyLabel": "Buferio simbolizacija",
    "pointSymbolChooserPopupTitle": "Adreso arba taško vietos simbolis",
    "polygonSymbolChooserPopupTitle": "Poligono simbolis",
    "lineSymbolChooserPopupTitle": "Linijos simbolis",
    "aoiSymbolChooserPopupTitle": "Buferio simbolis",
    "aoiTabText": "AOI",
    "reportTabText": "Ataskaita",
    "invalidSymbolValue": "Netinkama simbolio reikšmė."
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Ieškoti šaltinio parametrų",
    "searchSourceSettingTitle": "Ieškoti šaltinio parametrų",
    "searchSourceSettingTitleHintText": "Pridėti ir sukonfigūruoti geokodavimo paslaugas arba elementų sluoksnius kaip paieškos šaltinius. Šie nurodyti šaltiniai nustato, ko galima ieškoti paieškos lauke",
    "addSearchSourceLabel": "Pridėti paieškos šaltinį",
    "featureLayerLabel": "Elementų sluoksnis",
    "geocoderLabel": "Geokoderis",
    "generalSettingLabel": "Bendrieji parametrai",
    "allPlaceholderLabel": "Vietos rezervavimo tekstas visų elementų paieškai:",
    "allPlaceholderHintText": "Pastaba: įveskite tekstą, kuris bus rodomas kaip vietos rezervavimo ženklas ieškant visų sluoksnių ir geokoderio",
    "generalSettingCheckboxLabel": "Rodyti kontekstinį langą, skirtą rastam elementui arba vietai",
    "countryCode": "Šalies arba regiono kodas (-ai)",
    "countryCodeEg": "pvz., ",
    "countryCodeHint": "Jei ši reikšmė nebus nurodyta, bus ieškomos visos šalys ir regionai",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Ieškoti tik esamo žemėlapio aprėptyje",
    "locatorUrl": "Geokoderio URL",
    "locatorName": "Geokoderio pavadinimas",
    "locatorExample": "Pavyzdys",
    "locatorWarning": "Ši geokodavimo paslaugos versija nepalaikoma. Valdiklis palaiko 10.0 arba vėlesnę geokodavimo paslaugą.",
    "locatorTips": "Pasiūlymų nėra, nes geokodavimo paslauga nepalaiko pasiūlymų galimybės.",
    "layerSource": "Sluoksnio šaltinis",
    "setLayerSource": "Nustatyti sluoksnio šaltinį",
    "setGeocoderURL": "Nustatyti geokoderio URL",
    "searchLayerTips": "Pasiūlymų nėra, nes elementų paslauga nepalaiko puslapių numeravimo galimybės.",
    "placeholder": "Naudotojui rodomas tekstas",
    "searchFields": "Paieškos laukai",
    "displayField": "Rodyti lauką",
    "exactMatch": "Tikslus atitikmuo",
    "maxSuggestions": "Maksimalūs pasiūlymai",
    "maxResults": "Maksimalus rezultatų skaičius",
    "enableLocalSearch": "Įgalinti vietinę paiešką",
    "minScale": "Minimalus mastelis",
    "minScaleHint": "Vietinė paieška bus taikoma, kai žemėlapio mastelis bus didesnis nei šis",
    "radius": "Spindulys",
    "radiusHint": "Nurodo ploto aplink dabartinį žemėlapio centrą spindulį, naudojamą geokodavimo objektams išdėstyti taip, kad arčiausiai vietos esantys objektai būtų pateikiami pirmiausia.",
    "setSearchFields": "Nustatyti paieškos laukus",
    "set": "Nustatyti",
    "invalidUrlTip": "URL ${URL} yra neteisingas arba nepasiekiamas.",
    "invalidSearchSources": "Netinkami paieškos šaltinio parametrai"
  },
  "errorMsg": {
    "textboxFieldsEmptyErrorMsg": "Užpildykite reikiamus laukus",
    "bufferDistanceFieldsErrorMsg": "Įveskite leistinas reikšmes",
    "invalidSearchToleranceErrorMsg": "Įveskite leistiną paieškos tolerancijos reikšmę",
    "atLeastOneCheckboxCheckedErrorMsg": "Netinkama konfigūracija: būtinas bent vienas dominančios teritorijos įrankis.",
    "noLayerAvailableErrorMsg": "Sluoksnių nėra",
    "layerNotSupportedErrorMsg": "Nepalaikoma ",
    "noFieldSelected": "Naudokite redagavimo veiksmą analizės laukams pasirinkti.",
    "duplicateFieldsLabels": "Pridėta pasikartojanti žymė ${labelText} skirta: ${itemNames}",
    "noLayerSelected": "Pasirinkite bent vieną analizės sluoksnį.",
    "errorInSelectingLayer": "Nepavyksta pasirinkti sluoksnio. Pabandykite dar kartą.",
    "errorInMaxFeatureCount": "Įveskite leistiną didžiausią analizei skirtų elementų skaičių."
  }
});