define({
  "settings": "सेटिंग्स",
  "titleSettings": "टेक्स्ट सेटिंग",
  "imageSettings": "इमेज सेटिंग",
  "backgroundColor": "पृष्ठभूमि का रंग",
  "alignment": "अलाइनमेंट",
  "textSize": "टेक्स्ट आकार",
  "textColor": "टेक्स्ट रंग",
  "dataSource": "डेटा स्रोत",
  "chartSettings": "चार्ट सेटिंग",
  "data": "डेटा",
  "dataLabels": "डेटा लेबल",
  "displayMode": "डिस्प्ले मोड",
  "featureOption": "फीचर दर फीचर मान प्रदर्शित करें",
  "categoryOption": "श्रेणी के अनुसार मान प्रदर्शित करें",
  "countOption": "श्रेणी के अनुसार फीचर्स की संख्या प्रदर्शित करें",
  "fieldOption": "विशेषता मानों को चार्ट के रूप में प्रदर्शित करें",
  "categoryField": "श्रेणी की फ़ील्ड",
  "labelField": "लेबल फ़ील्ड",
  "valueFields": "मान फ़ील्ड",
  "operation": "परिचालन",
  "sumOption": "योग",
  "averageOption": "औसत",
  "minOption": "न्यूनतम",
  "maxOption": "अधिकतम",
  "dataFormat": "डेटा फ़ॉर्मेट",
  "decimalPlaces": "दशमलव स्थान",
  "prefix": "उपसर्ग",
  "suffix": "प्रत्यय के रूप में",
  "dataType": "डेटा प्रकार",
  "featureCount": "विशेषता की गिनती",
  "fieldStatistics": "फ़ील्ड के आंकड़े",
  "display": "प्रदर्शित करें",
  "chartColor": "चार्ट रंग",
  "horizontalAxis": "क्षैतिज अक्ष",
  "verticalAxis": "ऊर्ध्वाधर अक्ष",
  "legend": "लिजेंड",
  "position": "स्थिति",
  "top": "शीर्ष",
  "bottom": "नीचे",
  "useDataSourceSelection": "चयन का इस्तेमाल करें",
  "dataSourceFilterByExtent": "सीमा अनुसार फ़िल्टर करें",
  "changeTemplate": "टेम्पलेट बदलें",
  "numberSettings": "संख्या सेटिंग",
  "gaugeSettings": "गॉज सेटिंग",
  "indicators": "संकेतक",
  "ifValue": "अगर मान",
  "and": "और",
  "numberOperatorIsLessThan": "से कम",
  "numberOperatorIsGreaterThan": "से अधिक है",
  "numberOperatorIsBetween": "बीच में",
  "numberOperatorIsEqual": "के बराबर है",
  "numberOperatorIsNotEqual": "के बराबर नहीं है",
  "then": "तो",
  "ratio": "अनुपात",
  "trueValue": "सही मान",
  "changeValueColor": "मान के रंग को इसमें बदलें",
  "changeGaugeColor": "गॉज के रंग को इसमें बदलें",
  "setIndicatorIcon": "संकेतक आइकन को इसके रूप में सेट करें",
  "icons": "आइकन",
  "style": "शैली",
  "placement": "प्लेसमेंट",
  "left": "बाएं",
  "replace": "बदलें",
  "right": "दाएं",
  "color": "रंग",
  "sortBy": "इसके अनुसार क्रमबद्ध करें",
  "labelAxis": "लेबल",
  "valueAxis": "मान",
  "minPeriod": "न्यूनतम अवधि",
  "automatic": "स्वचालित",
  "periodsWithOutRecords": "बिना रिकॉर्ड वाली अवधियाँ",
  "nullValue": "शून्य मान",
  "calculatedAsZero": "शून्य के रूप में संगणित",
  "ignored": "अनदेखा किया गया",
  "maxCategories": "अधिकतम श्रेणियाँ",
  "useLayerSymbology": "लेयर की सिंबोलॉजी का उपयोग करें",
  "dataRange": "तिथि सीमा",
  "targetValue": "लक्षित मान",
  "currentValue": "वर्तमान मान",
  "gaugeColor": "गॉज का रंग",
  "min": "न्यूनतम",
  "max": "अधिकतम",
  "displayValueIn": "मान को इसमें दिखाएँ",
  "noData": "कोई डेटा नहीं",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "चेतावनी",
  "noSettingWaring1": "तत्व की विशेषताओं को सेट करने के लिए तत्व पर क्लिक करें।",
  "noSettingWaring2": "तत्व को फिर से आकार देने या फिर से क्रम में लगाने के लिए ड्रैग करें।",
  "donNotShowAgain": "इसे फिर से न दिखाएँ",
  "changeTemplateWarning": "यह आपकी सभी सेटिंग को मिटा देगा और एक नया खाली टेम्पलेट खोलेगा।",
  "requiredFieldWarning": "यह मान अनिवार्य है:",
  "dataSourceNotSet": "कृपया डेटा स्रोत निर्धारित करें।",
  "addIndicatorTip": "संकेतक जोड़ें",
  "chooseTemplatePopupTitle": "टेम्पलेट जोड़ें",
  "stringsInTemplate": {
    "name_number": "संख्या",
    "name_gauge": "गॉज",
    "name_vertical_gauge": "लंबवत गॉज",
    "name_horizontal_gauge": "क्षैतिज गॉज",
    "name_pie_chart": "पाई चार्ट",
    "name_column_chart": "स्तंभ चार्ट",
    "name_bar_chart": "बार चार्ट",
    "name_line_chart": "रेखा चार्ट",
    "titleOfTheInfographic": "इन्फोग्राफ़िक का शीर्षक",
    "description": "विवरण: इस इन्फोग्राफ़िक के बारे में अतिरिक्त जानकारी।"
  }
});