define({
  "_widgetLabel": "Inteligentny edytor",
  "_featureAction_SmartEditor": "Inteligentny edytor",
  "noEditPrivileges": "Twoje konto nie ma uprawnień do tworzenia ani modyfikowania danych.",
  "widgetActive": "Aktywny",
  "widgetNotActive": "Nieaktywny",
  "pressStr": "Naciśnij ",
  "ctrlStr": " CTRL, ",
  "snapStr": " aby włączyć dociąganie",
  "noAvailableTempaltes": "Brak dostępnych szablonów",
  "editorCache": " — bufor edytora",
  "presetFieldAlias": "Pole",
  "presetValue": "Wartość ustawiona wstępnie",
  "usePresetValues": " Użyj wartości ustawionych wstępnie (tylko nowe obiekty)",
  "editGeometry": " Edytuj geometrię",
  "savePromptTitle": "Zapisz obiekt",
  "savePrompt": "Czy chcesz zapisać bieżący obiekt?",
  "deletePromptTitle": "Usuń obiekt",
  "deletePrompt": "Czy na pewno chcesz usunąć wybrany obiekt?",
  "attachmentLoadingError": "Błąd przesyłania załączników",
  "attachmentSaveDeleteWarning": "Ostrzeżenie: zmiany w załącznikach są zapisywane automatycznie",
  "autoSaveEdits": "Automatycznie zapisuje nowy obiekt",
  "addNewFeature": "Utwórz nowy obiekt",
  "featureCreationFailedMsg": "Nie można utworzyć nowego rekordu/obiektu",
  "relatedItemTitle": "Powiązana tabela/warstwa",
  "invalidRelationShipMsg": "Upewnij się, że pole klucza podstawowego: '${parentKeyField}' ma prawidłową wartość",
  "pendingFeatureSaveMsg": "Zapisz edycje obiektów przed utworzeniem powiązanego obiektu.",
  "attachmentsRequiredMsg": "(*) Wymagane są załączniki.",
  "coordinatePopupTitle": "Przesuń obiekt do lokalizacji XY",
  "coordinatesSelectTitle": "Układ współrzędnych:",
  "mapSpecialReferenceDropdownOption": "Odniesienie przestrzenne mapy",
  "latLongDropdownOption": "Szer. geogr./dł. geogr.",
  "xAttributeTextBoxLabel": "Współrzędna X:",
  "yAttributeTextBoxLabel": "Współrzędna Y:",
  "latitudeTextBoxLabel": "Szerokość geograficzna:",
  "longitudeTextBoxLabel": "Długość geograficzna:",
  "filterEditor": {
    "all": "Wszystkie",
    "noAvailableTempaltes": "Brak dostępnych szablonów",
    "searchTemplates": "Szablony wyszukiwania"
  },
  "invalidConfiguration": "Widżet nie został skonfigurowany lub warstwy w tej konfiguracji nie znajdują się już na mapie. Otwórz aplikację w trybie kreatora i ponownie skonfiguruj widżet.",
  "geometryServiceURLNotFoundMSG": "Nie można uzyskać adresu URL usługi geometrii",
  "clearSelection": "Wyczyść",
  "refreshAttributes": "Zaktualizuj atrybuty obiektu",
  "automaticAttributeUpdatesOn": "Automatyczna aktualizacja atrybutów obiektu: Wł.",
  "automaticAttributeUpdatesOff": "Automatyczna aktualizacja atrybutów obiektu: Wył.",
  "moveSelectedFeatureToGPS": "Przesuń wybrany obiekt do bieżącej lokalizacji GPS",
  "moveSelectedFeatureToXY": "Przesuń wybrany obiekt do lokalizacji XY",
  "mapNavigationLocked": "Nawigacja po mapie: Zablokowane",
  "mapNavigationUnLocked": "Nawigacja po mapie: Odblokowane"
});