define({
  "_widgetLabel": "可见性",
  "observerLocation": "观察点位置",
  "formatIconTooltip": "格式输入",
  "addPointToolTip": "添加观察点位置",
  "fieldOfView": "视域",
  "useMilsText": "使用密耳作为角度",
  "observerHeight": "观察点高度",
  "minObsDistance": "最小可观测距离",
  "maxObsDistance": "最大可观测距离",
  "taskURLError": "微件配置文件包含无法访问的 URL。请咨询您的系统管理员",
  "taskURLInvalid": "使用此微件配置的地理处理任务无效。请咨询您的系统管理员",
  "viewshedError": "创建可见性时出错。 请确保观察点位置在高程表面范围内。</p>",
  "validationError": "<p>可见性创建表单缺少参数或包含无效参数，请确保：</p><ul><li>已设置观察点位置。</li><li>观察点视域值不为 0。</li><li>观察点高度为有效值。</li><li>最小和最大可观测距离为有效值。</li></ul>",
  "comfirmInputNotation": "确认输入注记",
  "notationsMatch": "发现与您的输入匹配的注记。请确认您想使用的注记：",
  "createBtn": "创建",
  "clearBtn": "清除",
  "setCoordFormat": "设置坐标格式字符串",
  "prefixNumbers": "向正数和负数添加“+/-”前缀",
  "parseCoordinatesError": "无法解析坐标。请检查您的输入。",
  "cancelBtn": "取消",
  "applyBtn": "应用",
  "invalidMessage": "请输入一个数值。",
  "observerRangeMessage": "观察点高度无效",
  "minimumRangeMessage": "最小观测范围无效",
  "maximumRangeMessage": "最大观测范围必须大于最小观测范围，且不得超过 ${limit} ${units}。",
  "portalURLError": "未配置 ArcGIS Online 组织或 Portal for ArcGIS 的 URL。 请咨询您的系统管理员",
  "privilegeError": "您的用户角色无法执行分析。 要执行分析，组织管理员需要授予您特定<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">权限</a>。",
  "noServiceError": "高程分析服务不可用。 请检查 ArcGIS Online 组织或 Portal for ArcGIS 配置。",
  "pointToolTooltip": "单击添加观察点位置",
  "degreesLabel": "度",
  "milsLabel": "毫英寸",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "十进制度 - 纬度/经度",
  "DDLongLatNotation": "十进制度 - 经度/纬度",
  "DDMLatLongNotation": "度十进制分 - 纬度/经度",
  "DDMLongLatNotation": "度十进制分 - 经度/纬度",
  "DMSLatLongNotation": "度分秒 - 纬度/经度",
  "DMSLongLatNotation": "度分秒 - 经度/纬度",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - 带字母",
  "UTMHemNotation": "UTM - 半球(N/S)",
  "mainPageTitle": "径向通视分析",
  "resultsTitle": "结果",
  "publishBtnLabel": "发布",
  "layerName": "发布的图层名称",
  "invalidLayerName": "图层名称只能包含字母数字字符和下划线",
  "missingLayerName": "输入图层名称",
  "back": "返回",
  "publishingFailedLayerExists": "发布失败：您已拥有名为 {0} 的要素服务。 请选择其他名称。",
  "checkService": "检查服务：{0}",
  "createService": "创建服务：{0}",
  "unableToCreate": "无法创建：{0}",
  "addToDefinition": "添加到定义：{0}",
  "successfullyPublished": "已成功发布 web 图层{0}管理 web 图层",
  "userRole": "用户没有权限，因此无法创建服务",
  "publishToNewLayer": "将结果发布到新要素图层",
  "missingLayerNameMessage": "发布之前，您必须输入有效的图层名称",
  "regionTypeLabel": "区域类型",
  "centerPointLabel": "中心点",
  "observationHeightLabel": "观测高度",
  "heightUnitLabel": "高度单位",
  "minObservationDistanceLabel": "最小观测距离",
  "maxObservationDistance": "最大观测距离",
  "distanceUnitLabel": "距离单位",
  "fovstartAngleLabel": "FOV 起始角",
  "fovEndAngleLabel": "FOV 终止角",
  "andleUnitsLabel": "角度单位"
});