define({
  "taskUrl": "משימת URL",
  "setTask": "הגדר",
  "setTaskPopupTitle": "הגדר משימה",
  "validate": "הגדר",
  "inValidGPService": "הזן שם חוקי של שירות ה-geoprocessing.",
  "GPFeatureRecordSetLayerERR": "הזן שירות geoprocessing עם סוגי קלטים של 'GPFeatureRecordSetLayer' בלבד.",
  "invalidInputParameters": "מספר פרמטרי הקלט קטן מ-1 או גדול מ-3. הזן שם חוקי של שירות ה-geoprocessing.",
  "projectSetting": {
    "title": "הגדרות הפרויקט",
    "note": "שים לב: הגדרות הפרויקט הן אופציונליות, לאחר ההגדרה המשתמש יכול לאחסן את הפרויקט בשכבות מפת האינטרנט הרצויות עם שטח הפסקת רשת ופרמטרי קלט. המשתמש יכול לאחסן פרמטרי קלט אחרים מהקבוצה \"פלט\" בכרטיסיה \"קלט/פלט\".",
    "projectPolygonLayer": "שכבת פוליגונים של הפרויקט",
    "outputParameterName": "שם פרמטר הפלט",
    "projectPointLayer": "שכבה נקודתית של הפרויקט",
    "selectLabel": "בחר",
    "polygonLayerHelp": "<p>יוצגו שכבות פוליגונים שעונות על התנאים הבאים<br/><ul><li>לשכבה צריכות להיות יכולות העריכה 'יצירה', 'מחיקה' ו'עדכון'</li><li>בשכבה צריכים להיות שני שדות עם אותו שם ואותו סוג נתונים:</li><ul><li>שם (שדה מסוג מחרוזת)</li><li>globalid (שדה מסוג GlobalID‏)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>שכבות פוליגונים של פלט מה-URL של המשימה יופיעו<p/>",
    "pointLayerHelp": "<p>יוצגו שכבות נקודות שעונות על התנאים הבאים: <br/><ul><li>לשכבה צריכות להיות יכולות העריכה 'יצירה', 'מחיקה' ו'עדכון'</li><li>בשכבה צריכים להיות שני שדות עם אותו שם ואותו סוג נתונים:</li><ul><li>inputtype (שדה מסוג מחרוזת)</li><li>projectid (שדה מסוג GUID‏)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "דגל",
    "barrier": "מחסום",
    "skip": "דלג",
    "title": "קלט/פלט",
    "inputSettingsLabel": "הגדרות קלט",
    "outputSettingsLabel": "הגדרות פלט",
    "inputLabel": "תווית",
    "inputTooltip": "בועית מידע",
    "symbol": "סמל",
    "typeText": "סוג",
    "outputParametersText": "פרמטרי פלט",
    "saveToLayerText": "שמור לשכבה (אופציונאלי)",
    "skipText": "ניתן לדילוג",
    "visibilityText": "מוצג",
    "exportToCsvText": "ייצוא ל- CSV",
    "exportToCsvDisplayText": "CSV",
    "settitngstext": "הגדרות",
    "addFieldTitle": "הוסף שדה",
    "enterDisplayText": "הזן טקסט לתצוגה",
    "setScale": "קבע קנ\"מ",
    "outputDisplay": "טקסט לתצוגה",
    "saveToLayerHelp": "<p>יוצגו שכבות שעונות על התנאים הבאים: <br/><ul><li>לשכבה צריכות להיות יכולות העריכה 'יצירה', 'מחיקה' ו'עדכון'</li><li>בשכבה צריכים להיות שני שדות עם אותו שם ואותו סוג נתונים:</li><ul><li>inputtype (שדה מסוג מחרוזת)</li><li>projectid (שדה מסוג GUID‏)</li></ul></ul><p/>"
  },
  "summaryTab": {
    "title": "הגדרות כלליות",
    "summaryFieldsetText": "הגדרות סיכום",
    "inputOutput": "קלט/פלט",
    "field": "שדה",
    "operator": "פעולה",
    "inputOperatorCountOption": "מונה",
    "outputOperatorCountOption": "מונה",
    "outputOperatorSkipCountOption": "SkipCount",
    "fieldOperatorSumOption": "סכום",
    "fieldOperatorMinOption": "מינימום",
    "fieldOperatorMaxOption": "מקסימום",
    "fieldOperatorMeanOption": "ממוצע",
    "expressionAddButtonText": "הוספה",
    "expressionVerifyButtonText": "אמת",
    "summaryEditorText": "טקסט סיכום",
    "autoZoomAfterTrace": "אפשרויות נוספות",
    "zoomText": "זום אוטומטי אחרי מעקב",
    "summarSettingTooltipText": "הוסף ספירת פריטי קלט/פלט"
  },
  "validationErrorMessage": {
    "webMapError": "אין שכבות זמינות במפת האינטרנט. בחר מפת אינטרנט חוקית.",
    "inputTypeFlagGreaterThanError": "קלט מסוג דגל לא יכול להיות יותר מאחד.",
    "inputTypeFlagLessThanError": "יש צורך לפחות בקלט אחד מסוג דגל.",
    "inputTypeBarrierErr": "קלט מסוג מחסום לא יכול להיות יותר מאחד.",
    "inputTypeSkipErr": "קלט מסוג דילוג לא יכול להיות יותר מאחד.",
    "displayTextForButtonError": "טקסט לתצוגה של לחצן 'הרץ' לא יכול להיות ריק.",
    "UnableToLoadGeoprocessError": "לא ניתן לטעון שירות geoprocessing.",
    "invalidSummaryExpression": "ביטוי לא חוקי.",
    "validSummaryExpression": "הצלחה!",
    "invalidProjectSettings": "הגדרות הפרויקט לא חוקיות.<br/> יש לבחור ערך חוקי ב- '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "רמז: ציין תווית לתצוגה עבור פאנל התוצאות של פרמטר הפלט.",
    "displayTextHint": "רמז: הוא יופיע בפאנל הפרטים של פרמטר הפלט.",
    "inputTextHint": "רמז: בנה את הביטוי מעל לבחירת הקלט, הפלט ושמות השדות.",
    "expressionHint": "רמז: בחר פריטים ולחץ על הוסף כדי ליצור ביטוי."
  }
});