define({
  "_widgetLabel": "Kartlagliste",
  "titleBasemap": "Bakgrunnskart",
  "titleLayers": "Operative kartlag",
  "labelLayer": "Lagnavn",
  "itemZoomTo": "Zoom til",
  "itemTransparency": "Gjennomsiktighet",
  "itemTransparent": "Gjennomsiktighet",
  "itemOpaque": "Ugjennomsiktig",
  "itemMoveUp": "Flytt opp",
  "itemMoveDown": "Flytt ned",
  "itemDesc": "Beskrivelse",
  "itemDownload": "Last ned",
  "itemToAttributeTable": "Åpne attributtabell",
  "itemShowItemDetails": "Vis elementdetaljene",
  "empty": "tom",
  "removePopup": "Deaktiver popup",
  "enablePopup": "Aktiver popup",
  "turnAllLayersOff": "Slå alle lag av",
  "turnAllLayersOn": "Slå alle lag på",
  "expandAllLayers": "Vis alle lag",
  "collapseAlllayers": "Skjul alle lag",
  "turnAllLabelsOff": "Slå alle etiketter av",
  "turnAllLabelsOn": "Slå alle etiketter på",
  "showLabels": "Vis etiketter",
  "hideLables": "Skjul etiketter"
});