define({
  "chartSettingLabel": "Diagraminnstillinger",
  "addNewLabel": "Legg til ny",
  "generalSettingLabel": "Generelle innstillinger",
  "layerChooser": {
    "title": "Velg laget du vil lage diagram av",
    "selectPolygonLayerLabel": "Velg lag",
    "selectPolygonLayerHintText": "Hint: Hvis du konfigurerer flere diagrammer, må lagene ha samme geomertritype",
    "selectRelatedTableLayerLabel": "Velg tabell knyttet til lag",
    "selectRelatedTableLayerHintText": "Hint: Bare tabeller med numeriske felt vises",
    "errorInSelectingPolygonLayer": "Velg et lag som har et tilknyttet punktlag.",
    "errorInSelectingRelatedLayer": "Velg en gyldig tilknyttet tabell/gyldig lag som det skal opprettes lag for.",
    "polygonLayerNotHavingRelationships": "Det valgte laget har ikke tilknyttet tabell/lag."
  },
  "ChartSetting": {
    "sectionTitle": "Seksjonstittel",
    "sectionTitleHintText": "Hint: Vises i overskriften for seksjonen",
    "chartTitle": "Diagramtittel",
    "chartTitleHintText": "Hint: Vises i midten øverst på diagrammet",
    "chartDescription": "Beskrivelse",
    "chartDescriptionHintText": "Hint: Vises under diagrammet",
    "chartType": "Diagramtype",
    "barChart": "Stolpediagram",
    "pieChart": "Sektordiagram",
    "polarChart": "Polardiagram",
    "dataSeriesField": "Dataseriefelt",
    "labelField": "Påskriftfelt",
    "chartColor": "Diagramfarge",
    "singleColor": "En farge",
    "colorByTheme": "Farge etter tema",
    "colorByFieldValue": "Farge etter feltverdi",
    "xAxisTitle": "Tittel på X-akse",
    "xAxisHintText": "Hint: Tittelen på X-aksen",
    "yAxisTitle": "Tittel på Y-akse",
    "yAxisHintText": "Hint: Tittelen på Y-aksen",
    "fieldColorLabel": "Etikett",
    "fieldColorColor": "Farge",
    "defaultFieldSelectLabel": "Velg",
    "errMsgFieldValuesNotFound": "Finner ingen verdier for feltet som er valgt",
    "errMsgSectionTitle": "Skriv inn seksjonstittelen",
    "errMsgFieldByValue": "Velg en feltverdi",
    "settingTabTitle": "Innstilling",
    "layoutTabTitle": "Oppsett",
    "polarChartSelectFieldsHintText": "Hint: Velg felter for å generere polardiagram",
    "visibilityText": "Synlighet",
    "fieldNameText": "Feltnavn",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Velg tre eller flere felter for å generere polardiagram",
    "polarChartPolygonFillLabel": "Fyll polygon",
    "polarChartPolygonFillHintText": "Hint: Merk av i boksen for å vise polygonfyll i polardiagram",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Ørken",
      "themeDistinctive": "Distinktiv",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Gresshoppe",
      "themeGrasslands": "Gresslette",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmoni",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Mint",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Kratt",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Våtmark",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Generelle innstillinger",
    "locationSymbolLabel": "Grafisk symbol for lokasjon",
    "locationSymbolHintText": "Hint: Brukes til å vise symbol for adresse og klikket lokasjon",
    "refreshIntervalLabel": "Oppdateringsintervall",
    "refreshIntervalHintText": "Hint: Brukes til å oppdatere diagrammer basert på dette intervallet. Angi en verdi mellom 1 tog 1440 minutter.",
    "errMsgRefreshInterval": "Angi et oppdateringsintervall på mellom 0 og 1440 minutter",
    "symbolPickerPreviewText": "Forhåndsvisning:"
  }
});