define({
  "_widgetLabel": "Situationsopmærksomhed",
  "locate_incident": "Find hændelse",
  "reverse_geocoded_address": "Nærmeste adresse",
  "reverse_geocoded_error": "Not available",
  "now": "NU",
  "wind": "VIND",
  "SUN": "SØN",
  "MON": "MAN",
  "TUE": "TIR",
  "WED": "ONS",
  "THU": "TOR",
  "FRI": "FRE",
  "SAT": "LØR",
  "actionLabel": "Angiv placering",
  "drawPoint": "Tegn punkt",
  "drawLine": "Tegn linje",
  "drawPolygon": "Tegn polygon",
  "saveIncident": "Gem",
  "clearIncident": "Start forfra",
  "noFeaturesFound": "Ingen objekte fundet.",
  "downloadCSV": "Hent",
  "sum": "Sum",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Gennemsnit",
  "count": "OPTÆLLING",
  "area": "OMRÅDE",
  "length": "LÆNGDE",
  "update_btn": "Udført",
  "delete_btn": "Slet",
  "get_directions": "Hent kørselsvejledning",
  "incident": "Hændelse",
  "incidents": "Hændelser",
  "buffer": "Buffer",
  "buffers": "Buffere",
  "weather": "Vejr",
  "poweredBy": "Drevet af",
  "_featureAction_ActionLabel": "Angiv placering",
  "_featureAction_AddRemoveActionLabel": "Tilføj/fjern position",
  "snapshot": "SnapShot-mappe oprettet af App-ID:",
  "user_credentials": "Brugeren har ikke gyldige rettigheder.",
  "snapshot_complete": "Snapshot oprettet med succes.",
  "snapshot_failed": "Oprettelse af snapshot mislykkedes.",
  "notPolySnapShot": "Angiv en bufferafstand, før du opretter et snapshot.",
  "notValidDownload": "Ingen gyldige resultater at downloade.",
  "snapshot_append": "Snapshot",
  "of_append": "af",
  "layer_append": "lag",
  "downloadAll": "Hent alle",
  "createSnapshot": "Opret snapshot",
  "calculated_results": "Oversigtsoplysninger",
  "closest": "Nærmeste objekt",
  "proximity": "Nærhed",
  "summary": "Resumé",
  "groupedSummary": "Grupperede optællinger",
  "_count": "Tælling",
  "utc": "UTC",
  "approximate": "cirka",
  "snapshot_name": "Angiv Snapshot-navn",
  "invalid_snapshot_name": "Ugyldigt snapshot-navn."
});