define({
  "settings": "Nastavení",
  "titleSettings": "Nastavení textu",
  "imageSettings": "Nastavení obrázku",
  "backgroundColor": "Barva pozadí",
  "alignment": "Zarovnání",
  "textSize": "Velikost textu",
  "textColor": "Barva textu",
  "dataSource": "Zdroj dat",
  "chartSettings": "Nastavení grafu",
  "data": "Data",
  "dataLabels": "Popisky dat",
  "displayMode": "Režim zobrazení",
  "featureOption": "Zobrazit hodnoty prvek po prvku",
  "categoryOption": "Zobrazit hodnoty podle kategorie",
  "countOption": "Zobrazit počty prvků podle kategorie",
  "fieldOption": "Zobrazit hodnoty atributů jako grafy",
  "categoryField": "Pole kategorie",
  "labelField": "Pole popisků",
  "valueFields": "Pole hodnot",
  "operation": "Operace",
  "sumOption": "Suma",
  "averageOption": "Průměr",
  "minOption": "Minimum",
  "maxOption": "Maximum",
  "dataFormat": "Formát dat",
  "decimalPlaces": "Desetinná místa",
  "prefix": "Předpona",
  "suffix": "Titul",
  "dataType": "Typ dat",
  "featureCount": "Počet prvků",
  "fieldStatistics": "Statistiky pole",
  "display": "Zobrazení",
  "chartColor": "Barva grafu",
  "horizontalAxis": "Vodorovná osa",
  "verticalAxis": "Svislá osa",
  "legend": "Legenda",
  "position": "Pozice",
  "top": "Nahoře",
  "bottom": "Dole",
  "useDataSourceSelection": "Použít výběr",
  "dataSourceFilterByExtent": "Filtrovat podle rozsahu",
  "changeTemplate": "Změnit šablonu",
  "numberSettings": "Nastavení čísel",
  "gaugeSettings": "Nastavení měřiče",
  "indicators": "Ukazatele",
  "ifValue": "Pokud hodnota",
  "and": "a",
  "numberOperatorIsLessThan": "je menší než",
  "numberOperatorIsGreaterThan": "je větší než",
  "numberOperatorIsBetween": "je mezi",
  "numberOperatorIsEqual": "rovná se",
  "numberOperatorIsNotEqual": "nerovná se",
  "then": "Pak",
  "ratio": "Poměr",
  "trueValue": "Hodnota True",
  "changeValueColor": "změnit barvu hodnoty na",
  "changeGaugeColor": "změnit barvu měřiče na",
  "setIndicatorIcon": "nastavit ukazatel ikony jako",
  "icons": "Ikony",
  "style": "Styl",
  "placement": "Umístění",
  "left": "Vlevo",
  "replace": "Nahradit",
  "right": "Vpravo",
  "color": "Barva",
  "dataRange": "Rozmezí dat",
  "targetValue": "Cílová hodnota",
  "currentValue": "Současná hodnota",
  "gaugeColor": "Barva měřiče",
  "min": "Minimum",
  "max": "Maximum",
  "displayValueIn": "Zobrazit hodnotu v",
  "noData": "Žádná data",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "m",
  "billionAbbreviation": "G",
  "warning": "Varování",
  "noSettingWaring1": "Kliknutím na prvek nastavíte jeho vlastnosti.",
  "noSettingWaring2": "Přetažením změníte velikost nebo pořadí prvku.",
  "donNotShowAgain": "Znovu nezobrazovat",
  "changeTemplateWarning": "Veškeré vaše nastavení bude vymazáno a otevře se nová prázdná šablona.",
  "requiredFieldWarning": "Tato hodnota je povinná:",
  "dataSourceNotSet": "Nastavte zdroj dat.",
  "addIndicatorTip": "Přidat ukazatel",
  "chooseTemplatePopupTitle": "Vybrat šablonu",
  "stringsInTemplate": {
    "name_number": "Číslo",
    "name_gauge": "Měřič",
    "name_vertical_gauge": "Svislý měřič",
    "name_horizontal_gauge": "Vodorovný měřič",
    "name_pie_chart": "Výsečový graf",
    "name_column_chart": "Sloupcový graf",
    "name_bar_chart": "Pruhový graf",
    "name_line_chart": "Spojnicový graf",
    "titleOfTheInfographic": "NÁZEV INFOGRAFIKY",
    "description": "Popis: další informace o této infografice."
  }
});