define({
  "symbolologyTabLabel": "Konfigurera symbologi",
  "facilitiesDescription": "Inrättningslager",
  "demographicsDescription": "Demografilager",
  "settingsTitle": "Inställningar",
  "spillLocationLabel": "Spillplats",
  "spillLocationButtonLabel": "Konfigurera inställningar för spillplats",
  "IISettingsLabel": "Ursprunglig isoleringszon",
  "IIButtonLabel": "Konfigurera inställningar för ursprunglig isolering",
  "PASettingsLabel": "Zon för skyddsåtgärd",
  "PAButtonLabel": "Konfigurera inställningar för skyddsåtgärd",
  "downwindSettingsLabel": "Zon i medvind",
  "downwindButtonLabel": "Konfigurera inställningar för medvind",
  "fireSettingsLabel": "Eldisoleringszon",
  "fireButtonLabel": "Konfigurera inställningar för eldisolering",
  "bleveSettingsLabel": "BLEVE-isoleringszon",
  "bleveButtonLabel": "Konfigurera BLEVE-inställningar",
  "transparency": "Transparens",
  "outline": "Kontur",
  "fill": "Fyllningsfärg (Färgen tillämpas enbart när stilen anges till solid)",
  "style": "Format",
  "selectOpLayerLabel": "Välj ett funktionslager för resultat",
  "selectDefaultMeasurementLabel": "Ange en standardmåttenhet",
  "helpIconTooltip": "Listan med funktionslager innehåller lager från den aktuella webbkartan som är av typen polygongeometri.",
  "colorPicker": "Färgurval",
  "lineStyles": {
    "esriSLSDash": "Streck",
    "esriSLSDashDot": "Streck punkt",
    "esriSLSDashDotDot": "Streck punkt punkt",
    "esriSLSDot": "Punkt",
    "esriSLSLongDash": "Långt streck",
    "esriSLSLongDashDot": "Lång streck-punkt",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kort streck",
    "esriSLSShortDashDot": "Kort streck-punkt",
    "esriSLSShortDashDotDot": "Kort streck-punkt-punkt",
    "esriSLSShortDot": "Kort punkt",
    "esriSLSSolid": "Solid"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Bakåt",
    "esriSFSCross": "Kors",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Framåt",
    "esriSFSHorizontal": "Horisontell",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Solid",
    "esriSFSVertical": "Vertikal"
  }
});