define(
   ({
    addLayer: "Adăugare strat tematic",
    layerName: "Strat tematic",
    layerRefresh: "Reîmprospătare",
    layerLabel: "Etichetă",
    actions: "Acţiuni",
    popupOk: "OK",
    popupCancel: "Anulare",
    mainPanelTextPlaceholder: "ex.: CONDIŢII AUTOSTRADĂ",
    invalidInterval: "Sunt acceptate doar caractere numerice.",
    uploadImage: "Încărcare imagine",
    iconColumnText: "Pictogramă",
    refreshInterval: "1 „Evaluate ca timp în Minute”",
    refreshIntervalTitle: "Evaluate ca timp în Minute",
    mainPanelText: "Text panou principal",
    mainPanelIcon: "Imagine panou principal",
    refreshIntervalInstruction: "Interval de reîmprospătare",
    optionsText: "Opţiuni",
    symbolOptionsText: "Opţiuni simbol",
    iconOptionsText: "Opţiuni pictogramă",
    sympolPopupTitle: "Setare simbol",
    rdoLayer: "Simbol strat tematic",
    rdoCustom: "Simbol personalizat",
    chkCluster: "Activare grupare",
    defineClusterSymbol: "Simbol grupare",
    defineThemeClusterSymbol: "Simbol grupare pe baza temei",
    rdoEsri: "Simbol Esri",
    rdoLayerIcon: "Utilizare simbol ca pictogramă",
    rdoCustomIcon: "Încărcare pictogramă particularizată",
    editCustomSymbol: "Editare simbol particularizat",
    editCustomIcon: "Editare pictogramă particularizată",
    missingRefreshValue: "Vă rugăm să furnizaţi o valoare a intervalului de reîmprospătare.",
    panelIconOption: "Antet panou de afişare",
    enableRefresh: "Activaţi reîmprospătarea stratului tematic",
    disableRefresh: "Reîmprospătarea stratului tematic este acceptată numai pentru colecţiile de obiecte spaţiale",
    layer_type_not_supported: "Tipul de strat tematic nu este acceptat: "
  })
);
