define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Agregar un punto haciendo clic en el mapa",
  "addRingsDtWt": "Agregar anillos, tiempo de recorrido por vehículo o tiempo de recorrido a pie.",
  "apply": "Solicitar participación",
  "back": "Atrás",
  "colon": ":",
  "creditInformation": "Información de créditos",
  "driveTime": "Tiempo de recorrido por vehículo",
  "esriInfographics": "Infografía de Esri",
  "esriReports": "Informes de Esri",
  "headerDescription_km": "kilómetro",
  "headerDescription_miles": "milla",
  "headerDescription_minutes": "minuto",
  "infographics": "Infografía",
  "invalidValueRing": "Los valores deben estar entre el rango de 0 a 1.000.",
  "invalidValueDTWT": "Los valores deben estar entre el rango de 0 a 300.",
  "km": "km",
  "miles": "millas",
  "minutes": "minutos",
  "myInfographics": "Mi infografía",
  "myReports": "Mis informes",
  "noPermissions": "Su cuenta no puede ejecutar el widget Business Analyst.  Para poder ejecutar el widget Business Analyst, el administrador de su organización debe otorgarle <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilegios</a> de GeoEnrichment y Análisis de red además de asignar <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">créditos</a>.",
  "radii": "radios",
  "radius": "Radio",
  "radius_lowercase": "radio",
  "reports": "Informes",
  "ring": "Anillo",
  "rings": "Anillos",
  "runInfographic": "Ejecutar infografía",
  "runReport": "Ejecutar informe",
  "selectPointOrPolygon": "Seleccione una entidad poligonal o de punto en el mapa, busque una dirección o lugar, o coloque una chincheta en el mapa para visualizar más información sobre las áreas.",
  "selectReport": "Seleccionar informe",
  "selectTemplate": "Seleccionar plantilla",
  "sharedInfographics": "Infografías compartidas",
  "sharedReports": "Informes compartidos",
  "thisEntryIsNotValid": "Esta entrada no es válida.",
  "time": "Time",
  "walkTime": "Tiempo de recorrido a pie",
  "widgetDescription": "Acceda a Infografías e Informes que resumen los indicadores clave y datos de cualquier área.",
  "None": "Seleccionar..."
});