define({
  "symbolologyTabLabel": "Sembolojiyi Yapılandır",
  "facilitiesDescription": "Tesis Katmanları",
  "demographicsDescription": "Demografi Katmanı",
  "settingsTitle": "Ayarlar",
  "spillLocationLabel": "Sızıntı Konumu",
  "spillLocationButtonLabel": "Sızıntı Konumu Ayarlarını Yapılandır",
  "IISettingsLabel": "İlk İzolasyon Bölgesi",
  "IIButtonLabel": "İzolasyon Bölgesi Ayarlarını Yapılandır",
  "PASettingsLabel": "Koruyucu İşlem Bölgesi",
  "PAButtonLabel": "Koruyucu İşlem Ayarlarını Yapılandır",
  "downwindSettingsLabel": "Rüzgar Altı Bölgesi",
  "downwindButtonLabel": "Rüzgar Altı Ayarlarını Yapılandır",
  "fireSettingsLabel": "Yangın İzolasyon Bölgesi",
  "fireButtonLabel": "Yangın İzolasyon Ayarlarını Yapılandır",
  "bleveSettingsLabel": "BLEVE İzolasyon Bölgesi",
  "bleveButtonLabel": "BLEVE Ayarlarını Yapılandır",
  "transparency": "Şeffaflık",
  "outline": "Ana Hat",
  "fill": "Doldur (Renk sadece stil katı olarak ayarlandığında uygulanır)",
  "style": "Stil",
  "selectOpLayerLabel": "Sonuçlar için bir işlem katmanı seçin",
  "selectDefaultMeasurementLabel": "Varsayılan ölçüm birimini seçin",
  "helpIconTooltip": "İşlem katmanı listesi, geçerli web haritasından çokgen geometrisi türünde katmanlarla doldurulur.",
  "colorPicker": "Renk Seçici",
  "lineStyles": {
    "esriSLSDash": "Çizgi",
    "esriSLSDashDot": "Çizgi Nokta",
    "esriSLSDashDotDot": "Çizgi Nokta Nokta",
    "esriSLSDot": "Nokta",
    "esriSLSLongDash": "Uzun Çizgi",
    "esriSLSLongDashDot": "Uzun Çizgi Nokta",
    "esriSLSNull": "Boş",
    "esriSLSShortDash": "Kısa Çizgi",
    "esriSLSShortDashDot": "Kısa Çizgi Nokta",
    "esriSLSShortDashDotDot": "Kısa Çizgi Nokta Nokta",
    "esriSLSShortDot": "Kısa Nokta",
    "esriSLSSolid": "Katı"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Geri",
    "esriSFSCross": "Çapraz",
    "esriSFSDiagonalCross": "Diyagonal",
    "esriSFSForwardDiagonal": "İleri",
    "esriSFSHorizontal": "Yatay",
    "esriSFSNull": "Boş",
    "esriSFSSolid": "Katı",
    "esriSFSVertical": "Dikey"
  }
});