define({
  "_widgetLabel": "Trusselsanalyse",
  "threatAnalysisMainPageTitle": "Baseret på JCAT Counterterrorism Guide",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Input-placering",
  "interactive": "Interaktiv",
  "fromCoord": "Fast koordinat",
  "existingFeature": "Fra eksisterende objekter",
  "threatAnalysisCoordInputLabel": "Trusselsplacering",
  "enterCoords": "Angiv koordinater",
  "threatAddPointToolTip": "Tilføj trusselsplacering",
  "threatDrawPointToolTip": "Klik for at tilføje trusselsplacering",
  "threatType": "Trusselstype",
  "threatPlaceholder": "Begynd at skrive for at søge efter en trussel",
  "mandatoryLabel": "Obligatorisk evakueringsafstand",
  "safeLabel": "Beskyttelsesrum i stedzone",
  "zoneTypeLabel": "Zonetype",
  "feetLabel": "Fod",
  "metersLabel": "Meter",
  "unitsLabel": "Enheder",
  "settingsTitle": "Indstillinger",
  "mandatoryButtonLabel": "Konfigurér indstillinger for Obligatorisk evakueringsafstand",
  "safeButtonLabel": "Konfigurer indstillinger for Beskyttelsesrum i stedzone",
  "style": "Type",
  "lineStyles": {
    "esriSLSDash": "Streg",
    "esriSLSDashDot": "Streg-prik",
    "esriSLSDashDotDot": "Streg-prik-prik",
    "esriSLSDot": "Prik",
    "esriSLSLongDash": "Lang streg",
    "esriSLSLongDashDot": "Lang streg-prik",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Kort streg",
    "esriSLSShortDashDot": "Kort streg-prik",
    "esriSLSShortDashDotDot": "Kort streg-prik-prik",
    "esriSLSShortDot": "Kort prik",
    "esriSLSSolid": "Udfyldt"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Baglæns",
    "esriSFSCross": "Kryds",
    "esriSFSDiagonalCross": "Diagonalt",
    "esriSFSForwardDiagonal": "Frem",
    "esriSFSHorizontal": "Vandret",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Udfyldt",
    "esriSFSVertical": "Lodret"
  },
  "resultsTitle": "Resultater",
  "publishTABtn": "Publicér",
  "layerName": "Navn på publiceret lag",
  "invalidLayerName": "Lagnavnet må kun indeholde alfanumeriske tegn og understregninger",
  "missingLayerName": "Du skal indtaste et navn til laget",
  "missingLayerNameMessage": "Du skal indtaste et gyldigt lag-navn, før du kan publicere.",
  "publishingFailedLayerExists": "Publicering mislykkedes: Du har allerede en featuretjeneste med navnet {0}. Vælg et andet navn.",
  "checkService": "Kontroller tjeneste: {0}",
  "createService": "Opret tjeneste: {0}",
  "unableToCreate": "Kan ikke oprette: {0}",
  "addToDefinition": "Tilføj til definition: {0}",
  "successfullyPublished": "Weblag er oprettet{0}Administrér weblaget",
  "userRole": "Kan ikke oprette tjenesten, fordi brugeren ikke har tilladelser",
  "transparencyLabel": "Gennemsigtighed",
  "outline": "Kontur",
  "fill": "Fyld (farve anvendes kun, når typografien er indstillet til massiv)",
  "createBtn": "Opret zoner",
  "clearBtn": "Ryd",
  "invalidNumberMessage": "Den indtastede værdi er ikke gyldig",
  "invalidRangeMessage": "Værdien skal være større end 0",
  "parseCoordinatesError": "Kan ikke analysere koordinater. Kontrollér dit input."
});