define({
  "labelBookmarkName": "Aktuális nézet megjelölése könyvjelzővel",
  "labelPlay": "Összes lejátszása",
  "labelStop": "Leállítás",
  "labelDelete": "Törlés",
  "placeholderBookmarkName": "Könyvjelző neve",
  "errorNameExist": "A könyvjelző létezik!",
  "errorNameNull": "Érvénytelen könyvjelzőnév!",
  "editTip": "Könyvjelzők szerkesztése",
  "exitEditTip": "Kilépés a szerkesztési módból",
  "syncTip": "Szinkronizálás",
  "cardsTips": "Grid nézet",
  "listTips": "Listanézet",
  "addBtn": "Hozzáadás",
  "deleteBtn": "Törlés",
  "changeThumbnailTip": "Bélyegkép módosítása",
  "dragReorderTip": "Tartsa lenyomva és húzza az átrendezéshez",
  "deleteBtnTip": "Könyvjelző törlése",
  "editBtnTip": "Könyvjelző szerkesztése",
  "withVisibility": "Réteg láthatóságával",
  "searchBookmark": "Keresés",
  "bookmarksFromConfig": "Előre konfigurált könyvjelzők",
  "bookmarksFromCache": "Helyi ideiglenes könyvjelzők",
  "notice": "Megjegyzés",
  "changeNoticeTips": "A módosítások csak a böngésző gyorsítótárában lesznek elmentve. Ha módosításokat végez, akkor megszűnik a szinkronizálás a widget és annak konfigurációja között.",
  "syncNoticeTips": "Ez törli az összes módosítást és visszaállítja a konfigurált könyvjelzőket.",
  "dontShowAgain": "Ne jelenjen meg újra",
  "saveVisibility": "Réteg láthatóságának mentése",
  "_widgetLabel": "Könyvjelző"
});