define({
  "showArcgisBasemaps": "Bao gồm các bản đồ nền của Cổng thông tin",
  "add": "Bấm để Thêm Bản đồ nền Mới",
  "edit": "Thuộc tính",
  "titlePH": "Tiêu đề Bản đồ nền",
  "thumbnailHint": "Bấm vào hình ảnh để cập nhật",
  "urlPH": "URL của Lớp",
  "addlayer": "Thêm Bản đồ nền",
  "warning": "Đầu vào không đúng",
  "save": "Quay lại và Lưu",
  "back": "Quay lại và Hủy",
  "addUrl": "Thêm URL",
  "autoCheck": "Tự động Kiểm tra",
  "checking": "Đang kiểm tra...",
  "result": "Đã lưu thành công",
  "spError": "Tất cả các bản đồ nền được thêm vào bộ sưu tập phải có cùng tham chiếu không gian.",
  "invalidTitle1": "Bản đồ nền '",
  "invalidTitle2": "đã tồn tại. Vui lòng chọn một tiêu đề khác.",
  "invalidBasemapUrl1": "Không thể sử dụng loại lớp này làm bản đồ nền.",
  "invalidBasemapUrl2": "Bản đồ nền bạn đang thêm có tham chiếu không gian khác với bản đồ hiện tại.",
  "addBaselayer": "Thêm Lớp Bản đồ nền",
  "repectOnline": "Luôn đồng bộ hóa với thiết lập Bộ sưu tập Bản đồ nền của tổ chức",
  "customBasemap": "Định cấu hình bản đồ nền tùy chỉnh",
  "basemapTips": "Nhấp \"${import}\" hoặc \"${createNew}\" để thêm bản đồ nền.",
  "importBasemap": "Nhập",
  "createBasemap": "Tạo mới",
  "importTitle": "Nhập Bản đồ nền",
  "createTitle": "Bản đồ Nền mới",
  "selectGroupTip": "Chọn nhóm có bản đồ web có thể sử dụng làm bản đồ nền.",
  "noBasemaps": "Không có bản đồ nền.",
  "defaultGroup": "Esri Mặc định",
  "defaultOrgGroup": "Mặc định Tổ chức",
  "warningTitle": "Cảnh báo",
  "confirmDelete": "Bạn có muốn xóa bản đồ nền đã chọn không?",
  "noBasemapAvailable": "Không có sẵn bản đồ nền nào hoặc tất cả các bản đồ nền đều có tham chiếu không gian khác với bản đồ hiện tại."
});