define({
  "transparencyLabel": "Độ trong suốt",
  "outline": "Viền",
  "fill": "Tô đầy (Màu chỉ áp dụng khi kiểu được thiết lập thành dạng khối)",
  "style": "Kiểu",
  "mandatoryLabel": "Khoảng cách Sơ tán Bắt buộc",
  "mandatoryButtonLabel": "Cấu hình Thiết lập Khoảng cách Sơ tán Bắt buộc",
  "safeLabel": "Khoảng cách Sơ tán An toàn",
  "safeButtonLabel": "Cấu hình thiết lập Khoảng cách Sơ tán An toàn",
  "selectOpLayerLabel": "Chọn một lớp chuyên đề cho kết quả",
  "selectDefaultMeasurementLabel": "Chọn đơn vị mặc định của kết quả đo",
  "helpIconTooltip": "Danh sách lớp chuyên đề được quản lý với các lớp từ bản đồ web hiện tại là loại hình học dạng vùng.",
  "lineStyles": {
    "esriSLSDash": "Gạch",
    "esriSLSDashDot": "Chấm Gạch",
    "esriSLSDashDotDot": "Gạch Chấm Chấm",
    "esriSLSDot": "Chấm",
    "esriSLSLongDash": "Nét đứt dài",
    "esriSLSLongDashDot": "Chấm đứt dài",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Nét đứt ngắn",
    "esriSLSShortDashDot": "Chấm đứt ngắn",
    "esriSLSShortDashDotDot": "Hai chấm đứt ngắn",
    "esriSLSShortDot": "Chấm ngắn",
    "esriSLSSolid": "Đậm"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Về phía sau",
    "esriSFSCross": "Gạch ngang",
    "esriSFSDiagonalCross": "Chéo",
    "esriSFSForwardDiagonal": "Chuyển tiếp",
    "esriSFSHorizontal": "Ngang",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Đậm",
    "esriSFSVertical": "Dọc"
  },
  "threatTypeLabel": "Loại Mối đe dọa",
  "symbologyLabel": "Biểu tượng",
  "generalLabel": "Chung",
  "addThreatTypesLabel": "Thêm Loại Mối đe dọa",
  "threatTypeColLabel": "Loại mối đe dọa",
  "actions": "Các hành động",
  "newThreatTypePopupLabel": "Loại Mối đe dọa Mới",
  "chooseDefaultThreatTypeIconLabel": "Chọn từ mục mặc định",
  "mandatoryDistance": "Khoảng cách Sơ tán Bắt buộc",
  "safeDistance": "Khoảng cách Sơ tán An toàn",
  "units": "Đơn vị",
  "chooseDefaultThreatLabel": "Chọn loại mối đe dọa mặc định",
  "defaultThreatTypePopUpLabel": "Loại Mối đe dọa Mặc định",
  "editThreatLabel": "Chỉnh sửa Mối đe dọa",
  "defaultThreatTypeIconTooltip": "Danh sách Loại Mối đe dọa Mặc định",
  "uniqueThreatTypeMsg": "Hãy nhập loại mối đe dọa duy nhất, đã tồn tại loại mối đe dọa có tên này.",
  "requiredThreatTypeMsg": "Trường này là bắt buộc",
  "unitMeasureLabel": "Khoảng cách tính bằng {0}",
  "pipeBombLabel": "Bom ống",
  "suicideBombLabel": "Bom tự sát",
  "briefcaseLabel": "Cặp tài liệu",
  "carLabel": "Xe ô tô",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Xe tải giao hàng nhỏ",
  "containerWaterTruckLabel": "Container/Xe tưới nước",
  "semiTrailerLabel": "Xe bán tải"
});