define({
  "gridTabLabel": "Quadrícula",
  "labelTabLabel": "Etiquetes",
  "referenceSystemTabLabel": "Sistema de referència",
  "gridTabDescription": "Definiu l'aspecte i el comportament de les cel·les de la quadrícula.",
  "cellOutlineColor": "Color de contorn de la cel·la",
  "cellFillColor": "Color d'emplenament de la cel·la",
  "transparency": "Transparència",
  "cellShapeDropDown": "Forma de la cel·la",
  "default": "Rectangle",
  "hexagon": "Hexàgon",
  "cellUnitsDropDown": "Unitats de la cel·la",
  "miles": "Milles",
  "kilometers": "Quilòmetres",
  "feet": "Peus",
  "meters": "Metres",
  "yards": "Iardes",
  "nautical-miles": "Milles nàutiques",
  "gridOriginDropDown": "Origen de la quadrícula",
  "lowerLeft": "Inferior esquerra",
  "lowerRight": "Inferior dreta",
  "upperLeft": "Superior esquerra",
  "upperRight": "Superior dreta",
  "center": "Centra",
  "selectOpLayerLabel": "Capes operatives de resultats",
  "helpIconTooltip": "La llista de capes operatives s'emplena amb capes del mapa web actual amb el tipus de geometria de polígon.",
  "labelTabDescription": "Definiu l'aspecte i el comportament de les etiquetes de la quadrícula.",
  "labelSettings": "Estil d'etiqueta",
  "font": "Tipus de lletra",
  "textSize": "Mida del text",
  "textColor": "Color de text",
  "halo": "Halo",
  "show": "Mostra",
  "labelTypeDropDown": "Tipus d'etiqueta",
  "alphaNumeric": "Alfanumèrica",
  "alphaAlpha": "Alfabètica",
  "numeric": "Numèrica",
  "labelDirectionDropDown": "Direcció de l'etiqueta",
  "horizontal": "Horitzontal",
  "vertical": "Vertical",
  "labelOriginDropDown": "Origen de l'etiqueta",
  "referenceSystemlTabDescription": "Definiu el sistema de referència per defecte.",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "lockSettings": "Configuració de bloqueig: impedirà que l'usuari canviï cap de les opcions configurades al widget"
});