define({
  "searchTabTitle": "Pesquisar definição de origem",
  "routeTabTitle": "Definição de rota",
  "add": "Adicionar origem de pesquisa",
  "addGeocoder": "Adicionar geocodificador",
  "geocoder": "Geocodificador",
  "setLayerSource": "Definir origem da camada",
  "setGeocoderURL": "Definir URL do geocodificador",
  "searchableLayer": "Camada de elementos",
  "name": "Nome",
  "countryCode": "Código(s) de país ou região",
  "countryCodeEg": "e.g ",
  "countryCodeHint": "Ao deixar este valor em branco irá pesquisar em todos os países e regiões",
  "showInfoWindowOnSelect": "Exibir janela pop-up para o elemento ou local encontrado.",
  "showInfoWindowOnSelect2": "Exibir janela pop-up quando o elemento ou local é encontrado.",
  "searchInCurrentMapExtent": "Procurar apenas na extensão de mapa actual.",
  "setSearchFields": "Definir campos de pesquisa",
  "set": "Definir",
  "fieldSearchable": "pesquisável",
  "zoomScale": "Escala de zoom",
  "locatorUrl": "URL do Geocodificador",
  "locatorName": "Nome do geocodificador",
  "locatorExample": "Exemplo",
  "locatorWarning": "A versão deste serviço de geocodificação não é suportada... O widget suporta o serviço de geocodificação 10.1 e acima.",
  "locatorTips": "Sugestões não estão disponíveis porque o serviço de geocodificação não suporta a capacidade sugerida.",
  "layerSource": "Origem de camada",
  "searchLayerTips": "Sugestões não estão disponíveis porque o serviço de elemento não suporta capacidades de paginação.",
  "placeholderText": "Espaço reservado a texto",
  "searchFields": "Campos de pesquisa",
  "displayField": "Campo de Visualização",
  "exactMatch": "Correspondência exata",
  "maxSuggestions": "Máximo de sugestões",
  "maxResults": "Máximo de resultados",
  "enableLocalSearch": "Ativar pesquisa local",
  "minScale": "Escala mínima",
  "minScaleHint": "Quando a escala do mapa é superior a esta escala, será aplicada a pesquisa local",
  "radius": "Raio",
  "radiusHint": "Especifica o raio de uma área em torno do atual centro do mapa, que é utilizada para impulsionar a classificação de candidatos a geocodificação para que os candidatos que se encontram mais perto do local sejam apresentados nas primeiras posições.",
  "invalidUrlTip": "O URL ${URL} é inválido ou inacessível.",
  "routeUrl": "URL de rota",
  "geocoderOptions": "Opções do Geocodificador",
  "autoComplete": "Auto Completar",
  "maximumSuggestions": "Máximo de sugestões",
  "minCharacters": "Caracteres mínimos",
  "searchDelay": "Demora na pesquisa",
  "placeholder": "Placeholder",
  "routeOptions": "Opções de rota",
  "directionsLanguage": "Idioma das direções",
  "directionsLengthUnits": "Unidades de comprimento das direções",
  "directionsOutputType": "Tipo de saída das direções",
  "impedanceAttribute": "Atributo de impedância",
  "kilometers": "Quilômetros",
  "miles": "Milhas",
  "meters": "Metros",
  "feet": "Pés",
  "yards": "Jardas",
  "nauticalMiles": "Milhas Náuticas",
  "parametersTip": "Por favor, defina os parâmetros corretamente!",
  "complete": "Completo",
  "completeNoEvents": "Completo Sem Eventos",
  "instructionsOnly": "Apenas instruções",
  "standard": "Padrão",
  "summaryOnly": "Apenas resumo",
  "travelModesUrl": "URL de modos de viagem",
  "searchPlaceholder": "Encontrar um endereço ou local",
  "trafficLayerUrl": "URL da camada de trânsito",
  "barrierLayerUrl": "URL da camada de Barreira",
  "presetDestinations": "Paragens predefinidas",
  "startPoint": "Ponto de partida",
  "endPoint": "Ponto de chegada",
  "destinationHolder": "Endereço ou coordenadas",
  "optional": "Opcional.",
  "barrierLayers": "Camadas de barreira",
  "pointBarrier": "Barreiras de pontos",
  "lineBarrier": "Barreiras de linhas",
  "polygonBarrier": "Barreiras de polígonos",
  "noPointBarrier": "Selecionar barreiras de pontos",
  "noLineBarrier": "Selecionar barreiras de linhas",
  "noPolygonBarrier": "Selecionar barreiras de polígonos"
});