define({
  "_widgetLabel": "Conştientizare situaţie",
  "locate_incident": "Localizare incident",
  "reverse_geocoded_address": "Cea mai apropiată adresă",
  "reverse_geocoded_error": "Indisponibil",
  "now": "ACUM",
  "wind": "VÂNT",
  "SUN": "DUM",
  "MON": "LUN",
  "TUE": "MAR",
  "WED": "MIE",
  "THU": "JOI",
  "FRI": "VIN",
  "SAT": "SÂM",
  "actionLabel": "Setare locație",
  "drawPoint": "Trasare punct",
  "drawLine": "Trasare linie",
  "drawPolygon": "Trasare poligon",
  "saveIncident": "Salvare",
  "clearIncident": "Pornire de la început",
  "noFeaturesFound": "Nu a fost găsit niciun obiect spaţial.",
  "downloadCSV": "Descărcare",
  "sum": "Sumă",
  "min": "Minim",
  "max": "Maxim",
  "avg": "Medie",
  "count": "NUMĂR",
  "area": "SUPRAFAŢĂ",
  "length": "LUNGIME",
  "update_btn": "Gata",
  "delete_btn": "Ştergere",
  "get_directions": "Obţinere instrucţiuni",
  "incident": "Incident",
  "incidents": "Incidente",
  "buffer": "Buffer",
  "buffers": "Buffere",
  "weather": "Vreme",
  "poweredBy": "Sprijinit de",
  "_featureAction_ActionLabel": "Setare locație",
  "_featureAction_AddRemoveActionLabel": "Adăugare/eliminare locaţie",
  "snapshot": "Folder SnapShot creat de aplicaţia cu id-ul:",
  "user_credentials": "Utilizatorul nu are privilegii valide.",
  "snapshot_complete": "Snapshot creat cu succes.",
  "snapshot_failed": "Crearea snapshotului a eşuat.",
  "notPolySnapShot": "Specificaţi o distanţă de buffer înainte de a crea un snapshot.",
  "notValidDownload": "Niciun rezultat valid de descărcat.",
  "snapshot_append": "Snapshot",
  "of_append": "din",
  "layer_append": "strat tematic",
  "downloadAll": "Descărcare toate",
  "createSnapshot": "Creare snapshot",
  "calculated_results": "Informaţii rezumate",
  "closest": "Cel mai apropiat obiect spaţial",
  "proximity": "Proximitate",
  "summary": "Rezumat",
  "groupedSummary": "Numere grupate",
  "_count": "Cont",
  "utc": "UTC",
  "approximate": "aproximare",
  "snapshot_name": "Setare nume Snapshot",
  "invalid_snapshot_name": "Nume snapshot nevalid."
});