define({
  "settings": "Parametry",
  "titleSettings": "Ustawienia tekstu",
  "imageSettings": "Ustawienia obrazu",
  "backgroundColor": "Kolor tła",
  "alignment": "Wyrównanie",
  "textSize": "Rozmiar tekstu",
  "textColor": "Kolor tekstu",
  "dataSource": "Źródło danych",
  "chartSettings": "Ustawienia diagramu",
  "data": "Dane",
  "dataLabels": "Etykiety danych",
  "displayMode": "Tryb wyświetlania",
  "featureOption": "Wyświetlaj wartości dla każdego kolejnego obiektu",
  "categoryOption": "Wyświetlaj wartości wg kategorii",
  "countOption": "Wyświetlaj liczbę obiektów wg kategorii",
  "fieldOption": "Wyświetlaj wartości atrybutów w postaci diagramów",
  "categoryField": "Pole kategorii",
  "labelField": "Pole etykiety",
  "valueFields": "Pola wartości",
  "operation": "Działanie",
  "sumOption": "Suma",
  "averageOption": "Średnia",
  "minOption": "Minimum",
  "maxOption": "Maksimum",
  "dataFormat": "Format danych",
  "decimalPlaces": "Miejsca dziesiętne",
  "prefix": "Prefiks",
  "suffix": "Tytuł",
  "dataType": "Typ danych",
  "featureCount": "Liczba obiektów",
  "fieldStatistics": "Statystyka pól",
  "display": "Wyświetl",
  "chartColor": "Kolor diagramu",
  "horizontalAxis": "Oś pozioma",
  "verticalAxis": "Oś pionowa",
  "legend": "Legenda",
  "position": "Położenie",
  "top": "Góra",
  "bottom": "Dół",
  "useDataSourceSelection": "Użyj zaznaczenia",
  "dataSourceFilterByExtent": "Filtruj wg zasięgu",
  "changeTemplate": "Zmień szablon",
  "numberSettings": "Ustawienia liczb",
  "gaugeSettings": "Ustawienia kontrolki",
  "indicators": "Wskaźniki",
  "ifValue": "jeżeli wartość",
  "and": "and",
  "numberOperatorIsLessThan": "jest mniejsze niż",
  "numberOperatorIsGreaterThan": "jest większe niż",
  "numberOperatorIsBetween": "pomiędzy",
  "numberOperatorIsEqual": "jest równa",
  "numberOperatorIsNotEqual": "nie jest równa",
  "then": "Wówczas",
  "ratio": "Współczynnik",
  "trueValue": "Wartość rzeczywista",
  "changeValueColor": "zmień kolor wartości na",
  "changeGaugeColor": "zmień kolor kontrolki na",
  "setIndicatorIcon": "ustaw ikonę wskaźnika na",
  "icons": "Ikony",
  "style": "Nadaj styl",
  "placement": "Położenie",
  "left": "Lewy",
  "replace": "Zastąp",
  "right": "Prawy",
  "color": "Kolor",
  "sortBy": "Sortuj według",
  "labelAxis": "Etykieta",
  "valueAxis": "Wartość",
  "minPeriod": "Okres minimalny",
  "automatic": "Automatycznie",
  "periodsWithOutRecords": "Okresy bez rekordów",
  "nullValue": "Wartość pusta",
  "calculatedAsZero": "Obliczone jako zero",
  "ignored": "Ignorowane",
  "maxCategories": "Maksymalna liczba kategorii",
  "useLayerSymbology": "Zastosuj symbole warstw",
  "hollowsize": "Wielkość pustej przestrzeni",
  "splitField": "Podziel pole",
  "parsingperiodTip": "Nie powiodło się obliczenie. Zbyt wiele interwałów czasowych z powodu krótkiego okresu analizy.",
  "manyCategoryTip": "Nie powiodło się wyświetlenie wykresu. Zbyt wiele kategorii.",
  "setColor": "Ustaw kolor",
  "setTheColorOf": "Ustaw kolor elementu",
  "setTheColorAs": "Ustaw kolor jako",
  "ifStr": "Jeśli zaznaczono opcję",
  "as": "jako",
  "is": "wynosi",
  "isNot": "nie równa się",
  "barCluster": "skupisko słupków",
  "individualBar": "pojedynczy słupek",
  "allOthers": "Wszystkie pozostałe",
  "dataRange": "Zakres dat",
  "targetValue": "Wartość docelowa",
  "currentValue": "Wartość bieżąca",
  "gaugeColor": "Kolor kontrolki",
  "min": "Minimum",
  "max": "Maksimum",
  "displayValueIn": "Wyświetlaj wartość w",
  "noData": "Brak danych",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Ostrzeżenie",
  "noSettingWaring1": "Kliknij element, aby skonfigurować jego właściwości.",
  "noSettingWaring2": "Przeciągnij, aby zmienić rozmiar lub kolejność elementu.",
  "donNotShowAgain": "Nie pokazuj ponownie",
  "changeTemplateWarning": "Spowoduje to usunięcie wszystkich ustawień i otwarcie nowego pustego szablonu.",
  "requiredFieldWarning": "Ta wartość jest wymagana:",
  "dataSourceNotSet": "Skonfiguruj źródło danych.",
  "addIndicatorTip": "Dodaj wskaźnik",
  "chooseTemplatePopupTitle": "Wybierz szablon",
  "stringsInTemplate": {
    "name_number": "Liczba",
    "name_gauge": "Kontrolka",
    "name_vertical_gauge": "Kontrolka pionowa",
    "name_horizontal_gauge": "Kontrolka pozioma",
    "name_pie": "Kołowy",
    "name_donut": "Pierścieniowy",
    "name_bar": "Słupkowy",
    "name_stacked_bar": "Skumulowany słupkowy",
    "name_percentage_stacked_bar": "Procentowy skumulowany słupkowy",
    "name_column": "Kolumna",
    "name_stacked_column": "Skumulowany kolumnowy",
    "name_percentage_stacked_column": "Procentowy skumulowany kolumnowy",
    "name_line": "Linia",
    "name_area": "obszar",
    "name_stacked_area": "Skumulowany obszar",
    "name_percentage_stacked_area": "Procentowy skumulowany obszar",
    "titleOfTheInfographic": "TYTUŁ INFOGRAFIKI",
    "description": "Opis: dodatkowe informacje o tej infografice."
  }
});