define({
  "settings": "Ρυθμίσεις",
  "titleSettings": "Ρυθμίσεις κειμένου",
  "imageSettings": "Ρυθμίσεις εικόνας",
  "backgroundColor": "Χρώμα φόντου",
  "alignment": "Στοίχιση",
  "textSize": "Μέγεθος κειμένου",
  "textColor": "Χρώμα κειμένου",
  "dataSource": "Προέλευση δεδομένων",
  "chartSettings": "Ρυθμίσεις γραφημάτων",
  "data": "Δεδομένα",
  "dataLabels": "Ετικέτες δεδομένων",
  "displayMode": "Λειτουργία εμφάνισης",
  "featureOption": "Εμφάνιση τιμών ανά στοιχείο",
  "categoryOption": "Εμφάνιση τιμών ανά κατηγορία",
  "countOption": "Εμφάνιση πλήθους στοιχείων ανά κατηγορία",
  "fieldOption": "Εμφάνιση τιμών στοιχείων ως γραφήματα",
  "categoryField": "Πεδίο κατηγορίας",
  "labelField": "Πεδίο ετικέτας",
  "valueFields": "Πεδία τιμών",
  "operation": "Λειτουργία",
  "sumOption": "Άθροισμα",
  "averageOption": "Μέσος όρος",
  "minOption": "Ελάχιστο",
  "maxOption": "Μέγιστο",
  "dataFormat": "Μορφή δεδομένων",
  "decimalPlaces": "Δεκαδικά ψηφία",
  "prefix": "Πρόθεμα",
  "suffix": "Επίθημα",
  "dataType": "Τύπος δεδομένων",
  "featureCount": "Πλήθος στοιχείων",
  "fieldStatistics": "Στατιστικά στοιχεία πεδίου",
  "display": "Εμφάνιση",
  "chartColor": "Χρώμα γραφήματος",
  "horizontalAxis": "Οριζόντιος άξονας",
  "verticalAxis": "Κατακόρυφος άξονας",
  "legend": "Υπόμνημα",
  "position": "Θέση",
  "top": "Επάνω",
  "bottom": "Κάτω",
  "useDataSourceSelection": "Χρήση επιλογής",
  "dataSourceFilterByExtent": "Φιλτράρισμα ανά έκταση",
  "changeTemplate": "Αλλαγή προτύπου",
  "numberSettings": "Ρυθμίσεις αριθμού",
  "gaugeSettings": "Ρυθμίσεις μέτρησης",
  "indicators": "Δείκτες",
  "ifValue": "Αν η τιμή",
  "and": "και",
  "numberOperatorIsLessThan": "είναι λιγότερο από",
  "numberOperatorIsGreaterThan": "είναι μεγαλύτερο από",
  "numberOperatorIsBetween": "είναι μεταξύ",
  "numberOperatorIsEqual": "είναι ίσο με",
  "numberOperatorIsNotEqual": "δεν είναι ίσο με",
  "then": "Τότε",
  "ratio": "Αναλογία",
  "trueValue": "Πραγματική τιμή",
  "changeValueColor": "αλλαγή χρώματος τιμής σε",
  "changeGaugeColor": "αλλαγή χρώματος μέτρησης σε",
  "setIndicatorIcon": "ορισμός εικονιδίου δείκτη σε",
  "icons": "Εικονίδια",
  "style": "Style",
  "placement": "Τοποθέτηση",
  "left": "Αριστερά",
  "replace": "Αντικατάσταση",
  "right": "Δεξιά",
  "color": "Χρώμα",
  "sortBy": "Ταξινόμηση κατά",
  "labelAxis": "Ετικέτα",
  "valueAxis": "Τιμή",
  "minPeriod": "Ελάχιστη περίοδος",
  "automatic": "Αυτόματα",
  "periodsWithOutRecords": "Περίοδοι χωρίς εγγραφές",
  "nullValue": "Μηδενική τιμή",
  "calculatedAsZero": "Με υπολογισμό ως μηδέν",
  "ignored": "Με παράβλεψη",
  "maxCategories": "Ανώτατος αριθμός κατηγοριών",
  "useLayerSymbology": "Χρήση συμβόλων θεματικού επιπέδου",
  "dataRange": "Εύρος δεδομένων",
  "targetValue": "Τιμή προορισμού",
  "currentValue": "Τρέχουσα τιμή",
  "gaugeColor": "Χρώμα μέτρησης",
  "min": "Ελάχιστο",
  "max": "Μέγιστο",
  "displayValueIn": "Εμφάνιση τιμής σε",
  "noData": "Δεν υπάρχουν δεδομένα",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "Μ",
  "billionAbbreviation": "G",
  "warning": "Προειδοποίηση",
  "noSettingWaring1": "Κάντε κλικ σε ένα στοιχείο, για να ορίσετε τις ιδιότητές του.",
  "noSettingWaring2": "Σύρετε για αλλαγή μεγέθους ή ανακατάταξή ενός στοιχείου.",
  "donNotShowAgain": "Να μην εμφανιστεί ξανά",
  "changeTemplateWarning": "Θα διαγραφούν όλες οι ρυθμίσεις σας και θα ανοίξει ένα νέο, κενό πρότυπο.",
  "requiredFieldWarning": "Αυτή η τιμή είναι απαιτούμενη:",
  "dataSourceNotSet": "Ορίστε προέλευση δεδομένων.",
  "addIndicatorTip": "Προσθήκη δείκτη",
  "chooseTemplatePopupTitle": "Επιλέξτε πρότυπο",
  "stringsInTemplate": {
    "name_number": "Αριθμός",
    "name_gauge": "Μέτρηση",
    "name_vertical_gauge": "Κατακόρυφη μέτρηση",
    "name_horizontal_gauge": "Οριζόντια μέτρηση",
    "name_pie_chart": "Γράφημα πίτας",
    "name_column_chart": "Γράφημα στηλών",
    "name_bar_chart": "Ραβδόγραμμα",
    "name_line_chart": "Γράφημα γραμμών",
    "titleOfTheInfographic": "ΤΙΤΛΟΣ ΓΡΑΦΙΚΗΣ ΑΝΑΠΑΡΑΣΤΑΣΗΣ ΔΕΔΟΜΕΝΩΝ",
    "description": "Περιγραφή: πρόσθετες πληροφορίες για αυτήν τη γραφική αναπαράσταση δεδομένων."
  }
});