define({
  "taskUrl": "URL operaţie",
  "setTask": "Setare",
  "setTaskPopupTitle": "Setare activitate",
  "validate": "Setare",
  "inValidGPService": "Introduceți un serviciu valid de geoprocesare.",
  "GPFeatureRecordSetLayerERR": "Introduceți un serviciu de geoprocesare doar cu intrări de tip 'GPFeatureRecordSetLayer'.",
  "invalidInputParameters": "Număr de parametri de intrare este fie sub 1, fie mai mult de 3. Introduceți un serviciu de geoprocesare valid.",
  "projectSetting": {
    "title": "Setări proiect",
    "note": "Notă: Setările de proiect sunt opționale; după configurare, utilizatorul poate stoca proiecte în straturile hartă web dorite cu arie cu rețea indisponibilă și parametri de intrare. Utilizatorul poate stoca alți parametri de ieșire din grupul “Ieșire” în fila “Intrare/Ieșire”.",
    "projectPolygonLayer": "Strat tematic poligon al proiectului",
    "outputParameterName": "Nume parametru de ieșire",
    "projectPointLayer": "Strat tematic punct al proiectului",
    "selectLabel": "Selectare",
    "polygonLayerHelp": "<p>Straturile poligon cu condițiile următoare vor fi afișate:<br/><li>Stratul trebuie să aibă capacități de editare, și anume “Creare”, “Ștergere” și “Actualizare”</li><li>Stratul trebuie să aibă 2 câmpuri cu tipul exact de nume și date:</li><ul><li>nume (câmp tip șir)</li><li>globalid (câmp tip ID global)</li></ul><p/>",
    "outputParameterHelp": "<p>Straturi poligon de ieșire din URL activitate vor fi afișate<p/>",
    "pointLayerHelp": "<p>Straturile punct cu condițiile următoare vor fi afișate:<br/><li>Stratul trebuie să aibă capacități de editare, și anume “Creare”, “Ștergere” și “Actualizare”</li><li>Stratul trebuie să aibă 2 câmpuri cu tipul exact de nume și date:</li><ul><li>inputtype (câmp tip șir)</li><li>projectid (câmp tip GUID)</li></ul><p/>"
  },
  "inputOutputTab": {
    "title": "Intrare/ieșire",
    "inputSettingsLabel": "Setări de ieșire",
    "outputSettingsLabel": "Setări ieșire",
    "inputLabel": "Etichetă",
    "inputTooltip": "Sugestie instrument",
    "symbol": "Simbol",
    "typeText": "Tip",
    "outputParametersText": "Parametri de ieșire",
    "saveToLayerText": "Salvare în strat (opțional)",
    "skipText": "Poate fi omis",
    "visibilityText": "Vizibil",
    "exportToCsvText": "Export în CSV",
    "exportToCsvDisplayText": "CSV",
    "settitngstext": "Setările",
    "addFieldTitle": "Adăugare câmp",
    "enterDisplayText": "Introducere text de afișat",
    "setScale": "Setare scară",
    "outputDisplay": "Text de afişat",
    "saveToLayerHelp": "<p>Stratul cu condițiile următoare va fi afișat:<br/><li>Stratul trebuie să aibă capacități de editare, și anume “Creare”, “Ștergere” și “Actualizare”</li><li>Stratul trebuie să aibă două câmpuri cu tipul exact de nume și date:</li><ul><li>parametername (câmp tip șir)</li><li>projectid (câmp tip GUID)</li></ul><p/>"
  },
  "summaryTab": {
    "title": "Rezumat",
    "summaryFieldsetText": "Setări rezumat",
    "inputOutput": "Intrări/ieșiri",
    "field": "Câmpuri",
    "operator": "Operatori",
    "inputOperatorCountOption": "Număr",
    "outputOperatorCountOption": "Număr",
    "outputOperatorSkipCountOption": "SkipCount",
    "fieldOperatorSumOption": "Sumă",
    "fieldOperatorMinOption": "Min",
    "fieldOperatorMaxOption": "Max",
    "fieldOperatorMeanOption": "Medie",
    "expressionAddButtonText": "Adăugați",
    "expressionVerifyButtonText": "Verificare",
    "summaryEditorText": "Text rezumat"
  },
  "generalSettings": {
    "title": "Setări generale",
    "displayTextForButtonLegend": "Afișare text pentru butonul 'Rulare'",
    "displayTextforButtonDefaultValue": "Executare",
    "displayTextForButton": "Text de afişat",
    "autoZoomAfterTrace": "Opțiuni de zoom",
    "zoomText": "Zoom automat după urmărire"
  },
  "validationErrorMessage": {
    "webMapError": "Niciun strat tematic disponibil în hartă web. Selectați o hartă web validă.",
    "inputTypeFlagGreaterThanError": "Intrare de tip marcator nu poate fi mai mult de unu.",
    "inputTypeFlagLessThanError": "Cel puțin o intrare de tip marcator este necesară.",
    "inputTypeBarrierErr": "Intrare de tip barieră nu poate fi mai mult de unu.",
    "inputTypeSkipErr": "Intrare de tip omitere nu poate fi mai mult de unu.",
    "displayTextForButtonError": "Afișare text pentru butonul 'Rulare’ nu poate fi necompletat.",
    "UnableToLoadGeoprocessError": "Imposibil de încărcat serviciu de geoprocesare.",
    "invalidSummaryExpression": "Expresie nevalidă",
    "validSummaryExpression": "Succes!",
    "invalidProjectSettings": "Setări de proiect nevalide.<br/> Selectați o valoare valabilă în '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "Sugestie: furnizați eticheta de afișare pentru panoul de rezultate al parametrului de ieșire.",
    "displayTextHint": "Sugestie: acesta va fi afișat în panoul detalii pentru acest parametru de ieșire.",
    "inputTextHint": "Sugestie: creați expresia dvs. de mai sus prin selectarea intrării, ieșirii și numelui de câmp.",
    "expressionHint": "Sugestie: selectați elementele și faceți clic pe adăugare pentru a crea expresia."
  }
});