define({
  "chartSettingLabel": "Thiết lập biểu đồ",
  "addNewLabel": "Thêm mới",
  "generalSettingLabel": "Thiết lập tổng quan",
  "layerChooser": {
    "title": "Chọn lớp cho biểu đồ",
    "selectPolygonLayerLabel": "Chọn lớp",
    "selectPolygonLayerHintText": "Gợi ý: Nếu cấu hình nhiều biểu đồ thì các lớp phải thuộc cùng loại hình học",
    "selectRelatedTableLayerLabel": "Chọn bảng liên quan đến lớp",
    "selectRelatedTableLayerHintText": "Mẹo: Chỉ các bảng có trường số được hiển thị",
    "errorInSelectingPolygonLayer": "Vui lòng chọn lớp có lớp điểm liên quan.",
    "errorInSelectingRelatedLayer": "Vui lòng chọn bảng/lớp liên quan đến lớp.",
    "polygonLayerNotHavingRelationships": "Lớp được chọn không có bất kỳ bảng/lớp liên quan nào."
  },
  "ChartSetting": {
    "sectionTitle": "Tiêu đề phần",
    "sectionTitleHintText": "Mẹo: Được hiển thị trong phần tiêu đề đầu trang",
    "chartTitle": "Tiêu đề biểu đồ",
    "chartTitleHintText": "Mẹo: Được hiển thị ở giữa trên cùng của biểu đồ",
    "chartDescription": "Mô tả",
    "chartDescriptionHintText": "Mẹo: Được hiển thị bên dưới biểu đồ",
    "chartType": "Loại biểu đồ",
    "barChart": "Biểu đồ thanh",
    "pieChart": "Biểu đồ hình tròn",
    "polarChart": "Biểu đồ cực",
    "dataSeriesField": "Trường dãy dữ liệu",
    "labelField": "Trường nhãn",
    "chartColor": "Màu sắc biểu đồ",
    "singleColor": "Một màu",
    "colorByTheme": "Màu sắc theo chủ đề",
    "colorByFieldValue": "Màu sắc theo giá trị trường",
    "xAxisTitle": "Tiêu đề trục X",
    "xAxisHintText": "Mẹo: Tiêu đề trục X",
    "yAxisTitle": "Tiêu đề trục Y",
    "yAxisHintText": "Mẹo: Tiêu đề trục Y",
    "fieldColorLabel": "Nhãn",
    "fieldColorColor": "Màu sắc",
    "defaultFieldSelectLabel": "Chọn",
    "errMsgFieldValuesNotFound": "Không tìm thấy giá trị cho trường được chọn",
    "errMsgSectionTitle": "Vui lòng nhập tiêu đề phần",
    "errMsgFieldByValue": "Vui lòng chọn giá trị trường",
    "settingTabTitle": "Thiết lập",
    "layoutTabTitle": "Bố cục",
    "polarChartSelectFieldsHintText": "Mẹo: Chọn các trường để tạo biểu đồ cực",
    "visibilityText": "Khả năng hiển thị",
    "fieldNameText": "Tên trường",
    "aliasNameText": "Bí danh",
    "errMsgPolarFieldsRequired": "Hãy chọn ba trường trở lên để tạo biểu đồ cực",
    "polarChartPolygonFillLabel": "Đa giác đặc",
    "polarChartPolygonFillHintText": "Mẹo: Chọn hộp kiểm để hiện đa giác đặc trong biểu đồ cực",
    "ThemeSelector": {
      "themeAdobebricks": "Gạch không nung",
      "themeAlgae": "Tảo",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "Chạng vạng",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Sa mạc",
      "themeDistinctive": "Khác biệt",
      "themeDollar": "Đô la",
      "themeGrasshopper": "Cào cào",
      "themeGrasslands": "Đồng cỏ",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Hài hòa",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Bạc hà",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Vùng đầm lầy",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Thiết lập Tổng quan",
    "locationSymbolLabel": "Ký hiệu vị trí đồ họa",
    "locationSymbolHintText": "Mẹo: Được sử dụng để hiển thị ký hiệu dành cho địa chỉ và vị trí bấm",
    "refreshIntervalLabel": "Khoảng thời gian làm mới",
    "refreshIntervalHintText": "Mẹo: Được sử dụng để làm mới biểu đồ theo khoảng thời gian này. Xác định giá trị trong khoảng từ 1 đến 1440 phút",
    "errMsgRefreshInterval": "Vui lòng xác định khoảng thời gian làm mới trong khoảng từ 0 đến 1440 phút",
    "symbolPickerPreviewText": "Xem trước:"
  }
});