define({
  "chartSettingLabel": "Configuració de gràfic",
  "addNewLabel": "Afegeix-ne un de nou",
  "generalSettingLabel": "Configuració general",
  "searchSourceSettingLabel": "Configuració de l'origen de la cerca",
  "layerChooser": {
    "title": "Seleccioneu la capa per al gràfic",
    "selectPolygonLayerLabel": "Seleccioneu la capa",
    "selectPolygonLayerHintText": "Suggeriment: si esteu configurant diversos gràfics, les capes han de ser del mateix tipus de geometria",
    "selectRelatedTableLayerLabel": "Seleccioneu la taula relacionada amb la capa",
    "selectRelatedTableLayerHintText": "Suggeriment: només es mostren les taules que tenen camps numèrics",
    "errorInSelectingPolygonLayer": "Seleccioneu una capa que tingui una capa de punts relacionada.",
    "errorInSelectingRelatedLayer": "Seleccioneu una taula o capa vàlida relacionada amb la capa.",
    "polygonLayerNotHavingRelationships": "La capa seleccionada no té cap taula o capa relacionada."
  },
  "ChartSetting": {
    "sectionTitle": "Títol de la secció",
    "sectionTitleHintText": "Suggeriment: es mostra en el títol de la capçalera de la secció",
    "chartTitle": "Títol del gràfic",
    "chartTitleHintText": "Suggeriment: es mostra centrat a la part superior del gràfic",
    "chartDescription": "Descripció",
    "chartDescriptionHintText": "Suggeriment: es mostra a sota del gràfic",
    "chartType": "Tipus de gràfic",
    "barChart": "Gràfic de barres",
    "pieChart": "Gràfic circular",
    "polarChart": "Gràfic polar",
    "lineChart": "Gràfic de línies",
    "dataSeriesField": "Camp de sèrie de dades",
    "lineDataSeriesField": "Camp de valor",
    "labelField": "Camp d'etiqueta",
    "lineLabelSeriesField": "Camp de seqüència",
    "chartColor": "Color de gràfic",
    "singleColor": "Color únic",
    "colorByTheme": "Color per tema",
    "colorByFieldValue": "Color per valor de camp",
    "xAxisTitle": "Títol de l'eix X",
    "xAxisHintText": "Suggeriment: títol de l'eix X",
    "yAxisTitle": "Títol de l'eix Y",
    "yAxisHintText": "Suggeriment: títol de l'eix Y",
    "fieldColorLabel": "Etiqueta",
    "fieldColorColor": "Color",
    "defaultFieldSelectLabel": "Selecciona",
    "errMsgFieldValuesNotFound": "No es troben valors per al camp seleccionat",
    "errMsgSectionTitle": "Introduïu el títol de la secció",
    "errMsgFieldByValue": "Seleccioneu un color per valor de camp",
    "errMsgDataSeriesField": "Seleccioneu un valor de camp",
    "settingTabTitle": "Configuració",
    "layoutTabTitle": "Disseny",
    "polarChartSelectFieldsHintText": "Suggeriment: seleccioneu els camps per generar el gràfic polar",
    "visibilityText": "Visibilitat",
    "fieldNameText": "Nom del camp",
    "aliasNameText": "Àlies",
    "errMsgPolarFieldsRequired": "Seleccioneu tres o més camps per generar el gràfic polar",
    "polarChartPolygonFillLabel": "Emplena el polígon",
    "polarChartPolygonFillHintText": "Suggeriment: activeu la casella de selecció per mostrar l'emplenament dels polígons al gràfic polar",
    "viewLayoutLabel": "Disseny",
    "setValueFields": "Defineix els camps de valors",
    "layoutSeriesLabel": "Sèrie",
    "ThemeSelector": {
      "themeAdobebricks": "Maons de tova",
      "themeAlgae": "Algues",
      "themeBahamation": "Bahames",
      "themeBlueDusk": "CrepuscleBlau",
      "themeCubanShirts": "CamisesCubanes",
      "themeDesert": "Desert",
      "themeDistinctive": "Distintiu",
      "themeDollar": "Dòlar",
      "themeGrasshopper": "Llagosta",
      "themeGrasslands": "Prades",
      "themeGreySkies": "CelsGrisos",
      "themeHarmony": "Harmonia",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irlanda",
      "themeMiamiNice": "BellMiami",
      "themeMinty": "Mentolat",
      "themePurpleRain": "PlujaPorpra",
      "themeRoyalPurples": "PorpresReials",
      "themeSageToLime": "SàlviaACal",
      "themeTufte": "Floc",
      "themeWatersEdge": "VoraAigua",
      "themeWetlandText": "Aiguamoll",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Configuració general",
    "locationSymbolLabel": "Símbol d'ubicació de gràfic",
    "locationSymbolHintText": "Suggeriment: s'utilitza per visualitzar el símbol de l'adreça i la ubicació on es fa clic",
    "refreshIntervalLabel": "Interval d'actualització",
    "refreshIntervalHintText": "Suggeriment: s'utilitza per actualitzar els gràfics segons aquest interval. Especifiqueu un valor entre 1 i 1440 minuts",
    "errMsgRefreshInterval": "Especifiqueu un interval d'actualització d'entre 0 i 1440 minuts.",
    "symbolPickerPreviewText": "Visualització prèvia:",
    "showToolToSelectLabel": "Botó Defineix la ubicació",
    "showToolToSelectHintText": "Suggeriment: proporciona un botó per definir la ubicació al mapa en lloc de definir sempre la ubicació quan es fa clic al mapa"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Configuració de l'origen de la cerca",
    "searchSourceSettingTitle": "Configuració de l'origen de la cerca",
    "searchSourceSettingTitleHintText": "Afegiu i configureu serveis de geocodificació o capes d'entitats com a orígens de cerca. Aquests orígens especificats determinen què es pot cercar al quadre de cerca",
    "addSearchSourceLabel": "Afegeix un origen de cerca",
    "featureLayerLabel": "Capa d'entitats",
    "geocoderLabel": "Geocodificador",
    "nameTitle": "Nom",
    "generalSettingLabel": "Configuració general",
    "allPlaceholderLabel": "Text del marcador de posició per cercar-ho tot:",
    "allPlaceholderHintText": "Suggeriment: introduïu el text que es mostrarà com a marcador de posició mentre cerqueu totes les capes i el geocodificador",
    "generalSettingCheckboxLabel": "Mostra la finestra emergent de l'entitat o la ubicació trobada",
    "countryCode": "Codis de país o regió",
    "countryCodeEg": "per exemple, ",
    "countryCodeHint": "Si aquest valor es deixa en blanc, la cerca es farà en tots els països i regions",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Cerca només a l'extensió de mapa actual",
    "zoomScale": "Escala de zoom",
    "locatorUrl": "URL del geocodificador",
    "locatorName": "Nom del geocodificador",
    "locatorExample": "Exemple",
    "locatorWarning": "Aquesta versió del servei de geocodificació no s'admet. El widget admet la versió 10.0 del servei de geocodificació i altres versions posteriors.",
    "locatorTips": "Els suggeriments no estan disponibles perquè el servei de geocodificació no admet la funció de suggeriments.",
    "layerSource": "Origen de la capa",
    "setLayerSource": "Defineix l'origen de la capa",
    "setGeocoderURL": "Defineix la URL del geocodificador",
    "searchLayerTips": "Els suggeriments no estan disponibles perquè el servei d'entitats no admet la funció de paginació.",
    "placeholder": "Text del marcador de posició",
    "searchFields": "Camps de cerca",
    "displayField": "Camp de visualització",
    "exactMatch": "Coincidència exacta",
    "maxSuggestions": "Màxim de suggeriments",
    "maxResults": "Màxim de resultats",
    "enableLocalSearch": "Habilita la cerca local",
    "minScale": "Escala mínima",
    "minScaleHint": "Si l'escala del mapa és més gran que aquesta escala, s'aplicarà la cerca local",
    "radius": "Radi",
    "radiusHint": "Permet especificar el radi d'una àrea al voltant del centre del mapa actual que s'utilitzarà per millorar la classificació dels candidats de geocodificació per tal que es retornin primer aquells més propers a la ubicació",
    "meters": "Metres",
    "setSearchFields": "Defineix els camps de cerca",
    "set": "Defineix",
    "fieldName": "Nom",
    "invalidSearchSources": "Configuració de l'origen de la cerca no vàlida",
    "invalidUrlTip": "L'adreça URL ${URL} no és vàlida o no s'hi pot accedir.",
    "maxSuggestionErrorMessage": "Introduïu un valor de màxim de suggeriments vàlid. El valor està fora de l'interval o no és vàlid.",
    "maxResultsErrorMessage": "Introduïu un valor de màxim de resultats vàlid. El valor està fora de l'interval o no és vàlid.",
    "zoomScaleErrorMessage": "Introduïu un valor d'escala de zoom vàlid. El valor està fora de l'interval o no és vàlid.",
    "minScaleErrorMessage": "Introduïu un valor d'escala mínima vàlid. El valor està fora de l'interval o no és vàlid.",
    "radiusErrorMessage": "Introduïu un valor de radi vàlid. El valor està fora de l'interval o no és vàlid."
  }
});