define({
  "chartSettingLabel": "Postavke grafikona",
  "addNewLabel": "Dodaj novi",
  "generalSettingLabel": "Opće postavke",
  "layerChooser": {
    "title": "Odaberi sloj za grafikon",
    "selectPolygonLayerLabel": "Odaberi sloj",
    "selectPolygonLayerHintText": "Podsjetnik: ako konfigurirate više grafikona, tada slojevi moraju imati istu vrstu geometrije",
    "selectRelatedTableLayerLabel": "Odaberi tablicu povezanu sa slojem",
    "selectRelatedTableLayerHintText": "Podsjetnik: prikazane su samo tablice s brojčanim poljima",
    "errorInSelectingPolygonLayer": "Odredite sloj koji ima povezani točkasti sloj.",
    "errorInSelectingRelatedLayer": "Odaberite važeću povezanu tablicu/sloj za sloj.",
    "polygonLayerNotHavingRelationships": "Odabrani sloj nema povezanu tablicu/sloj."
  },
  "ChartSetting": {
    "sectionTitle": "Naslov odjeljka",
    "sectionTitleHintText": "Podsjetnik: prikazano u naslovu zaglavlja odjeljka",
    "chartTitle": "Naslov grafikona",
    "chartTitleHintText": "Podsjetnik: prikazano centrirano na vrhu grafikona",
    "chartDescription": "Opis",
    "chartDescriptionHintText": "Podsjetnik: prikazano ispod grafikona",
    "chartType": "Vrsta grafikona",
    "barChart": "Trakasti grafikon",
    "pieChart": "Tortni grafikon",
    "polarChart": "Polarni grafikon",
    "dataSeriesField": "Polje serije podataka",
    "labelField": "Polje oznake",
    "chartColor": "Boja grafikona",
    "singleColor": "Jedna boja",
    "colorByTheme": "Boja prema temi",
    "colorByFieldValue": "Boja prema vrijednosti polja",
    "xAxisTitle": "Naslov X-osi",
    "xAxisHintText": "Podsjetnik: naslov X-osi",
    "yAxisTitle": "Naslov Y-osi",
    "yAxisHintText": "Podsjetnik: naslov Y-osi",
    "fieldColorLabel": "Oznaka",
    "fieldColorColor": "Boja",
    "defaultFieldSelectLabel": "Odaberi",
    "errMsgFieldValuesNotFound": "Nije moguće pronaći vrijednosti za odabrano polje",
    "errMsgSectionTitle": "Unesite naslov odjeljka",
    "errMsgFieldByValue": "Odaberite vrijednost polja",
    "settingTabTitle": "Postavka",
    "layoutTabTitle": "Izgled",
    "polarChartSelectFieldsHintText": "Podsjetnik: odaberite polja za generiranje polarnog grafikona",
    "visibilityText": "Vidljivost",
    "fieldNameText": "Naziv polja",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Odaberite tri ili više polja za generiranje polarnog grafikona",
    "polarChartPolygonFillLabel": "Ispuni poligon",
    "polarChartPolygonFillHintText": "Podsjetnik: odaberite potvrdni okvir za prikaz polarnog grafikona ispunjenog poligona",
    "ThemeSelector": {
      "themeAdobebricks": "Ćerpič",
      "themeAlgae": "Alge",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "Plavi sumrak",
      "themeCubanShirts": "Kubanske košulje",
      "themeDesert": "Pustinja",
      "themeDistinctive": "Izrazito",
      "themeDollar": "Dolar",
      "themeGrasshopper": "Skakavac",
      "themeGrasslands": "Pašnjaci",
      "themeGreySkies": "Sivo nebo",
      "themeHarmony": "Sklad",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irska",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Vlažno područje",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Opće postavke",
    "locationSymbolLabel": "Grafički simbol lokacije",
    "locationSymbolHintText": "Posjetnik: upotrebljava se za prikaz simbola za adresu i lokaciju na koju ste kliknuli",
    "refreshIntervalLabel": "Interval osvježavanja",
    "refreshIntervalHintText": "Posjetnik: upotrebljava se za osvježavanje grafikona na temelju ovog intervala. Odredite vrijednost između 1 do 1440 minuta",
    "errMsgRefreshInterval": "Odredite interval osvježavanja između 0 do 1440 minuta",
    "symbolPickerPreviewText": "Pretpregled:"
  }
});