define(
   ({
    addLayer: "Ajouter une couche",
    layerName: "Couche",
    layerRefresh: "Actualiser",
    layerLabel: "Etiqueter",
    actions: "Actions",
    popupOk: "OK",
    popupCancel: "Annuler",
    mainPanelTextPlaceholder: "ex : CONDITIONS DE CIRCULATION",
    invalidInterval: "Seuls les caractères numériques sont pris en charge.",
    uploadImage: "Télécharger image",
    iconColumnText: "Icône",
    refreshInterval: "1 \'Evalué en tant que durée en minutes\'",
    refreshIntervalTitle: "Evalué en tant que durée en minutes",
    mainPanelText: "Texte du volet principal",
    mainPanelIcon: "Image du volet principal",
    refreshIntervalInstruction: "Intervalle d\'actualisation",
    optionsText: "Options",
    symbolOptionsText: "Options de symbole",
    iconOptionsText: "Options d’icône",
    sympolPopupTitle: "Définir le symbole",
    rdoLayer: "Symbole de couche",
    rdoCustom: "Symbole personnalisé",
    chkCluster: "Activer l’agrégation",
    defineClusterSymbol: "Symbole de groupement",
    defineThemeClusterSymbol: "Symbole de groupement par thème",
    rdoEsri: "Symbole Esri",
    rdoLayerIcon: "Utiliser le symbole en tant qu’icône",
    rdoCustomIcon: "Charger l’icône personnalisée",
    editCustomSymbol: "Modifier le symbole personnalisé",
    editCustomIcon: "Modifier l’icône personnalisée",
    missingRefreshValue: "Indiquez une valeur pour l’intervalle d’actualisation.",
    panelIconOption: "Afficher l’en-tête du volet",
    enableRefresh: "Activer l’actualisation des couches",
    disableRefresh: "Actualisation des couches prises en charge uniquement pour les collections d’entités",
    layer_type_not_supported: "Le type de couche n’est pas pris en charge : "
  })
);
