define({
  "_widgetLabel": "การวิเคราะห์ภัยคุกคาม",
  "threatAnalysisMainPageTitle": "อิงตาม JCAT Counterterrorism Guide",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "อินพุทตำแหน่งที่ตั้ง",
  "interactive": "โต้ตอบ",
  "fromCoord": "พิกัดแบบตายตัว",
  "existingFeature": "จากฟีเจอร์ที่มีอยู่",
  "threatAnalysisCoordInputLabel": "ตำแหน่งที่ตั้งภัยคุกคาม",
  "enterCoords": "ใส่ระบบพิกัด",
  "threatAddPointToolTip": "เพิ่มตำแหน่งที่ตั้งภัยคุกคาม",
  "threatDrawPointToolTip": "คลิกเพื่อเพิ่มตำแหน่งที่ตั้งภัยคุกคาม",
  "threatType": "ประเภทภัยคุกคาม",
  "threatPlaceholder": "เริ่มพิมพ์เพื่อค้นหาภัยคุกคาม",
  "mandatoryLabel": "ระยะห่างบังคับในการอพยพ",
  "safeLabel": "ระยะห่างปลอดภัยในการอพยพ",
  "zoneTypeLabel": "ประเภทโซน",
  "feetLabel": "ฟุต",
  "metersLabel": "เมตร",
  "unitsLabel": "หน่วย",
  "threatGraphicLayer": "ภัยคุกคาม-กราฟิก",
  "settingsTitle": "การตั้งค่า",
  "mandatoryButtonLabel": "กำหนดการตั้งค่าระยะห่างบังคับในการอพยพ",
  "safeButtonLabel": "กำหนดการตั้งค่าการมีที่หลบภัย",
  "style": "สไตล์",
  "colorPicker": "ตัวเลือกสี",
  "lineStyles": {
    "esriSLSDash": "เส้นขีด",
    "esriSLSDashDot": "เส้นขีด จุด",
    "esriSLSDashDotDot": "เส้นขีด จุด จุด",
    "esriSLSDot": "จุด",
    "esriSLSLongDash": "เส้นขีดยาว",
    "esriSLSLongDashDot": "เส้นจุดยาว",
    "esriSLSNull": "ไม่มีค่า",
    "esriSLSShortDash": "เส้นขีดสั้น",
    "esriSLSShortDashDot": "เส้นจุดสั้น",
    "esriSLSShortDashDotDot": "เส้นขีดและจุดสั้น",
    "esriSLSShortDot": "จุดสั้น",
    "esriSLSSolid": "สีเดียว"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "ย้อนกลับ",
    "esriSFSCross": "กากบาท",
    "esriSFSDiagonalCross": "เส้นทแยงมุม",
    "esriSFSForwardDiagonal": "ส่งต่อ",
    "esriSFSHorizontal": "แนวนอน",
    "esriSFSNull": "ไม่มีค่า",
    "esriSFSSolid": "สีเดียว",
    "esriSFSVertical": "ตั้งฉาก"
  },
  "resultsTitle": "ผลลัพธ์",
  "publishTABtn": "เผยแพร่",
  "layerName": "ชื่อชั้นข้อมูลที่เผยแพร่แล้ว",
  "invalidLayerName": "ชื่อชั้นข้อมูลต้องประกอบด้วยอักษรและตัวเลขและขีดล่างเท่านั้น",
  "missingLayerName": "คุณต้องป้อนชื่อให้กับชั้นข้อมูล",
  "missingLayerNameMessage": "คุณต้องป้อนชื่อชั้นข้อมูลที่ถูกต้องก่อนจึงจะสามารถเผยแพร่ได้",
  "publishingFailedLayerExists": "การเผยแพร่ล้มเหลว: คุณมีฟีเจอร์เซอร์วิสชื่อ {0} อยู่แล้ว โปรดเลือกชื่อชั้นข้อมูลอื่น",
  "checkService": "ตรวจสอบบริการ: {0}.",
  "createService": "สร้างบริการ: {0}.",
  "unableToCreate": "ไม่สามารถสร้าง: {0}",
  "addToDefinition": "เพิ่มในคำนิยาม: {0}",
  "successfullyPublished": "เผยแพร่ชั้นข้อมูลเว็บเรียบร้อยแล้ว{0}จัดการชั้นข้อมูลเว็บ",
  "successfullyAppended": "ผนวกฟีเจอร์ใหม่ลงในชั้นข้อมูลเว็บเรียบร้อยแล้ว{0}จัดการชั้นข้อมูลเว็บ",
  "userRole": "ไม่สามารถสร้างบริการเนื่องจากผู้ใช้ไม่มีสิทธิ์",
  "retrieveExistingLayerError": "ไม่สามารถดึงข้อมูล {0} ได้ โปรดเผยแพร่โดยใช้ชื่อชั้นข้อมูลอื่น",
  "publishToNewLayer": "เผยแพร่ผลลัพธ์ลงในชั้นข้อมูลฟีเจอร์ใหม่",
  "pipeBombLabel": "ระเบิดท่อ",
  "suicideBombLabel": "ระเบิดพลีชีพ",
  "briefcaseLabel": "กระเป๋าเอกสาร",
  "carLabel": "รถยนต์",
  "suvVanLabel": "SUV/รถตู้",
  "smallDeliveryTruckLabel": "รถส่งของขนาดเล็ก",
  "containerWaterTruckLabel": "คอนเทนเนอร์/รถบรรทุกน้ำ",
  "semiTrailerLabel": "รถกึ่งพ่วง",
  "transparencyLabel": "โปร่งแสง",
  "outline": "โครงร่าง",
  "fill": "พื้น (ใช้สีเฉพาะเมื่อรูปแบบถูกตั้งค่าเป็นแบบทึบ)",
  "createBtn": "สร้างโซน",
  "clearBtn": "เคลียร์",
  "invalidNumberMessage": "ค่าที่ป้อนไม่ถูกต้อง",
  "invalidRangeMessage": "ค่าต้องมากกว่า 0",
  "parseCoordinatesError": "ไม่สามารถวิเคราะห์พิกัดได้ โปรดตรวจสอบอินพุทของคุณ",
  "manualCoordinateInputInfo": "อินพุทพิกัดด้วยตัวเองแล้วคลิก <b>ป้อน</b> เพื่อซูมเข้า",
  "selectDrawModeLabel": "เลือกโหมดการวาด",
  "selectFeatureLabel": "เลือกฟีเจอร์จากชั้นข้อมูลนี้"
});