define({
  "searchTabTitle": "Otsinguallika seade",
  "routeTabTitle": "Marsruudi seade",
  "add": "Lisa otsinguallikas",
  "addGeocoder": "Lisa geokodeerija",
  "geocoder": "Geokodeerija",
  "setLayerSource": "Määra kihi allikas",
  "setGeocoderURL": "Määra geokodeerija URL",
  "searchableLayer": "Objektikiht",
  "name": "Nimi",
  "countryCode": "Riigi või piirkonna kood(id)",
  "countryCodeEg": "nt ",
  "countryCodeHint": "Kui jätate selle välja tühjaks, teostatakse otsing kõikides riikides ja piirkondades",
  "showInfoWindowOnSelect": "Kuva leitud objekti või asukoha hüpikaken",
  "showInfoWindowOnSelect2": "Kuva objekti või asukoha leidmisel hüpikaken.",
  "searchInCurrentMapExtent": "Otsi ainult praegusest kaardiulatusest",
  "setSearchFields": "Määra otsinguväljad",
  "set": "Määra",
  "fieldSearchable": "otsitav",
  "zoomScale": "Suumiskaala",
  "locatorUrl": "Geokodeerija URL",
  "locatorName": "Geokodeerija nimi",
  "locatorExample": "Näide",
  "locatorWarning": "Seda geokodeerimisteenust ei toetata. Vidin toetab geokodeerimisteenust ArcGIS 10.1 ja sellest uuemate versioonide puhul.",
  "locatorTips": "Soovitused pole saadaval, sest geokodeerimisteenus ei toeta soovituste võimalust.",
  "layerSource": "Kihi allikas",
  "searchLayerTips": "Soovitused pole saadaval, sest objektiteenus ei toeta leheküljelise jaotuse võimalust.",
  "placeholderText": "Kohatäitja tekst",
  "searchFields": "Otsinguväljad",
  "displayField": "Kuvamise väli",
  "exactMatch": "Täpne vaste",
  "maxSuggestions": "Maksimaalsed soovitused",
  "maxResults": "Maksimaalsed tulemused",
  "enableLocalSearch": "Luba kohalik otsing",
  "minScale": "Min mõõtkava",
  "minScaleHint": "Kui kaardi mõõkava on sellest mõõtkavast suurem, rakendatakse kohalik otsing",
  "radius": "Raadius",
  "radiusHint": "Määrab praeguse kaardi keskpunkti ümber asuva ala raadiuse, mida kasutatakse geokodeerimise kandidaatide järjestuse võimendamiseks, nii et asukohale lähimad kandidaadid tagastatakse esimesena",
  "invalidUrlTip": "URL ${URL} ei sobi või pole kättesaadav.",
  "routeUrl": "Marsruudi URL",
  "geocoderOptions": "Geokodeerija valikud",
  "autoComplete": "Automaatne koostamine",
  "maximumSuggestions": "Maksimaalsed soovitused",
  "minCharacters": "Minimaalselt tähemärke",
  "searchDelay": "Otsingu viivitus",
  "placeholder": "Kohatäide",
  "routeOptions": "Marsruudi valikud",
  "directionsLanguage": "Teejuhiste keel",
  "directionsLengthUnits": "Teejuhiste pikkusühikud",
  "directionsOutputType": "Teejuhiste väljundi tüüp",
  "impedanceAttribute": "Takistuse atribuut",
  "kilometers": "Kilomeetrit",
  "miles": "Miili",
  "meters": "Meetrit",
  "feet": "Jalga",
  "yards": "Jardi",
  "nauticalMiles": "Meremiili",
  "parametersTip": "Määrake parameetrid õigesti!",
  "complete": "Valmis",
  "completeNoEvents": "Valmis, sündmusi pole",
  "instructionsOnly": "Ainult juhised",
  "standard": "Standardne",
  "summaryOnly": "Ainult kokkuvõte",
  "travelModesUrl": "Liikumisviiside URL",
  "searchPlaceholder": "Otsi aadressi või kohta",
  "trafficLayerUrl": "Liikluskihi URL",
  "barrierLayerUrl": "Tõkkekihi URL",
  "presetDestinations": "Eelmääratud peatused",
  "startPoint": "Alguspunkt",
  "endPoint": "Lõpp-punkt",
  "destinationHolder": "Aadressid või koordinaadid",
  "optional": "Valikuline.",
  "barrierLayers": "Tõkkekihid",
  "pointBarrier": "Punkttõkked",
  "lineBarrier": "Joonetõkked",
  "polygonBarrier": "Alatõkked",
  "noPointBarrier": "Vali punktilised piirajad",
  "noLineBarrier": "Vali joonelised piirajad",
  "noPolygonBarrier": "Vali polügoonidest piirajad"
});