define({
  "styleText": "Valitse pyyhkäisytyökalun tyyli",
  "vertical": "Pystypalkki",
  "horizontal": "Vaakapalkki",
  "scope": "Kiikari",
  "barColor": "Pylvään väri",
  "swipeMode": "Pyyhkäisytila",
  "singleLayer": "Yksi karttataso",
  "MultipleLayers": "Useita karttatasoja",
  "allowToSwipe": "Salli pyyhkäisy",
  "layer": "Karttataso",
  "swipeByDefault": "Käytä pyyhkäisyä oletusarvoisesti",
  "defaultLayerMustBeVisible": "oletuskarttatason on oltava näkyvissä",
  "noDefaultLayer": "Määritä, että pyyhkäisyä käytetään karttatasoissa oletusarvoisesti",
  "defaultLayerHolder": "Valitse napsauttamalla",
  "selectLayers": "Valitse karttatasot",
  "layerText": "Valitse karttataso(t), joissa haluat käyttää pyyhkäisyä oletusarvoisesti",
  "spyglassText": "Valitse karttataso, joka näkyy kiikarissa oletusarvoisesti.",
  "layerHint": "Huomautus: jos karttataso on piirtojärjestyksessä ylempänä olevien karttatasojen peitossa, pyyhkäisyt eivät vaikuta mitenkään.",
  "isZoom": "Tarkenna pyyhkäisytasoon",
  "isZooms": "Tarkenna pyyhkäisytasoihin",
  "layersAvailable": "Valitse pyyhkäistävät karttatasot:"
});