define({
  "_widgetLabel": "تتبع الشبكات",
  "_featureAction_NetworkTraceSkip": "تخطي في التتبع",
  "_featureAction_NetworkTraceUnskip": "إزالة من تخطي المواقع",
  "removedFromSkipLocations": "تمت الإزالة من تخطي المواقع",
  "alreadyRemovedFromSkipLocations": "تمت الإزالة بالفعل من تخطي المواقع",
  "locationSkipped": "الموقع التي تم تخطيها",
  "configError": "عنصر واجهة المستخدم غير مكون بشكل سليم.",
  "geometryServiceURLNotFoundMSG": "يتعذر الحصول على عنوان URL لخدمة الشكل الهندسي",
  "clearButtonValue": "مسح",
  "GPExecutionFailed": "يتعذر إكمال البيانات. الرجاء إعادة المحاولة مرة أخرى.",
  "backButtonValue": "الخلف",
  "exportToCSVSuccess": "اكتمل التصدير إلى CSV بنجاح.",
  "lblInputLocTab": "مواقع الإدخال",
  "lblBlockLocTab": "حظر مواقع",
  "lblInputLocation": "إدخال مَعلَم",
  "lblBlockLocation": "حظر مَعلَم",
  "lblInputLocHeader": "المواقع المدخلة (0)",
  "lblBlockLocHeader": "المواقع المحظورة (0)",
  "inputTabTitle": "الإدخال",
  "outputTabTitle": "الناتج",
  "exportSelectAllCheckBoxLabel": "تحديد الكل",
  "lblSkipLocHeader": "المواقع المتخطاة (0)",
  "lblSkipLocation": "موقع",
  "lblSkipLocTab": "تخطي مواقع",
  "skipAllLocationButtonLabel": "تخطي جميع المواقع",
  "confirmSkipAllLocationsMessage": "سيتم تخطي كل المواقع، هل ترغب في المتابعة؟",
  "locationAlreadySkippedMessage": "الموقع تم تخطيه بالفعل",
  "removeAllSkipLocationLabel": "إزالة الكل",
  "newProjectOptionText": "مشروع جديد",
  "selectProject": "تحديد مشروع",
  "saveButtonLabel": "حفظ",
  "exportToCSVText": "تصدير إلى CSV",
  "editProjectAttributesToolTip": "تحرير السمات للمشروع",
  "projectNameLabel": "اسم المشروع",
  "saveProjectPopupTitle": "حفظ",
  "saveAsLabel": "حفظ باسم",
  "saveChangesMsg": "هل تريد حفظ تغييراتك على <b>${loadProjectDropdownlabel}</b> أو حفظها كمشروع جديد؟",
  "creatingNewProjectErrorMessage": "حدث خطأ أثناء إنشاء مشروع جديد. الرجاء إعادة المحاولة مرة أخرى.",
  "projectNameFetchingErr": "حدث خطأ أثناء إحضار أسماء المشاريع الجديدة. الرجاء إعادة المحاولة مرة أخرى.",
  "projectAttributeLoadingErr": "حدث خطأ أثناء تحميل سمات المشروع. الرجاء إعادة المحاولة مرة أخرى.",
  "attributeUpdatedMsg": "تم تحديث سمات بنجاح.",
  "projectAttributeUpdatingErr": "حدث خطأ أثناء تحديث سمات المشروع.",
  "loadingProjectDetailsErrorMessage": "حدث خطأ أثناء إحضار الأعلام والحواجز وتخطي المواقع. الرجاء إعادة المحاولة مرة أخرى.",
  "savingProjectDetailsErr": "حدث خطأ أثناء حفظ تفاصيل المشروع. يرجى محاولة حفظ المشروع مرةً أخرى.",
  "updatingOutagePolygonErr": "حدث خطأ أثناء تحديث مضلع الانقطاع. يرجى محاولة حفظ المشروع مرةً أخرى.",
  "deletingExistingPolygonErr": "حدث خطأ أثناء حذف مضلع الانقطاع. يرجى محاولة حفظ المشروع مرةً أخرى.",
  "loadingProjectFeaturesErr": "حدث خطأ أثناء تحميل معالم المشروع. يرجى محاولة تحميل المشروع مرةً أخرى.",
  "addingProjectFeaturesErr": "حدث خطأ أثناء إضافة معالم المشروع. يرجى محاولة حفظ المشروع مرةً أخرى.",
  "deletingExistingProjectFeaturesErr": "حدث خطأ أثناء حذف معالم المشروع الحالية. يرجى محاولة حفظ المشروع مرةً أخرى.",
  "projectNotFoundErr": "لم يتم العثور على المشروع",
  "projectLayersNotFound": "طبقات إعدادات المشروع المكونة غير متاحة في الخريطة. سيتم تحميل عنصر واجهة المستخدم في \"وضع التخطيط\".",
  "fetchingOutagePolygonMessage": "حدث خطأ أثناء إحضار مضلع الانقطاع. يرجى محاولة تحميل المشروع مرةً أخرى.",
  "projectNameExistsMessage": "اسم المشروع موجود بالفعل. يُرجى استخدام اسم مشروع فريد.",
  "fetchingProjectNamesErrorMessage": "حدث خطأ أثناء إحضار أسماء المشاريع الجديدة. يرجى محاولة حفظ المشروع مرةً أخرى.",
  "enterProjectNameMessage": "يرجى إدخال اسم المشروع.",
  "projectLengthErrorMessage": "لا يمكن أن يكون اسم المشروع أكبر من",
  "gpServiceNotAccessible": "لا يتمتع حسابك بالوصول إلى الخدمة المطلوبة لإجراء هذا التتبع.",
  "loadingClonedLayerErrorMessage": "حدث خطأ أثناء تحميل طبقة المعلم المنسوخة. الرجاء إعادة المحاولة مرة أخرى.",
  "addingFeatureInClonedLayerError": "حدث خطأ أثناء إضافة الرسوم إلى طبقة المعلم. الرجاء إعادة المحاولة مرة أخرى.",
  "selectingFeatureInClonedLayerError": "حدث خطأ أثناء تحديد الرسوم في طبقة المعلم المنسوخة. الرجاء إعادة المحاولة مرة أخرى.",
  "filteredProjectError": "حدث خطأ أثناء التحقق من إحضار تفاصيل المشروع المصفاة. الرجاء إعادة المحاولة مرة أخرى.",
  "filteredProjectMessage": "سمات المشروع المحددة غير متوفرة بسبب عوامل التصفية المطبقة من خريطة الويب أو عنصر واجهة مستخدم آخر. امسح عوامل التصفية وحاول مرةً أخرى.",
  "filteredProjectLoadMessage": "لم يعد مشروعك متاحًا. يرجى تحديد مشروع نشط.",
  "defaultValueForRunButton": "تشغيل",
  "closeButtonLabel": "إزالة"
});