define({
  "enableUndoRedo": "Aktivovat funkci Zpět/Znovu",
  "toolbarVisible": "Viditelná lišta nástrojů",
  "toolbarOptions": "Možnosti lišty nástrojů",
  "mergeVisible": "Sloučit",
  "cutVisible": "Rozdělit",
  "reshapeVisible": "Změnit tvar",
  "back": "Zpět",
  "label": "Vrstva",
  "edit": "Editovatelná",
  "update": "Zakázat aktualizaci geometrie",
  "fields": "Pole",
  "actions": "Akce",
  "editpageName": "Název",
  "editpageAlias": "Alternativní název",
  "editpageVisible": "Viditelná",
  "editpageEditable": "Editovatelná",
  "noLayers": "K dispozici nejsou žádné vrstvy prvků, které by bylo možno editovat.",
  "configureFields": "Konfigurovat pole vrstvy",
  "useFilterEdit": "Použít filtr šablon prvků",
  "display": "Zobrazení",
  "autoApplyEditWhenGeometryIsMoved": "Použít změnu automaticky po přesunutí geometrie",
  "snappingTolerance": "Nastavte toleranci přichytávání v pixelech",
  "popupTolerance": "Nastavte toleranci vyskakovacího okna editace atributů v pixelech",
  "stickyMoveTolerance": "Nastavte toleranci přilnutí pohybu v pixelech",
  "usingSaveButton": "Neprovádět změny atributů, dokud nebude stisknuto tlačítko Uložit",
  "generalSettings": "Obecná nastavení",
  "editableLayersSetting": "Nastavení editovatelných vrstev",
  "honorTheWebMapSetting": "Zohlednit nastavení webové mapy",
  "honorTheWebMapSettingTip1": "Mezi tato nastavení patří:",
  "honorTheWebMapSettingTip2": "Které vrstvy jsou editovatelné",
  "honorTheWebMapSettingTip3": "Pole, která chcete zobrazit a editovat",
  "honorTheWebMapSettingTip4": "Alternativní název, pořadí a formát pole",
  "customSettings": "Vlastní nastavení"
});