define({
  "addTaskTip": "Thêm một hoặc nhiều bộ lọc vào tiện ích và cấu hình tham số cho từng bộ lọc.",
  "enableMapFilter": "Gỡ bỏ bộ lọc lớp được thiết lập sẵn ra khỏi bản đồ.",
  "newFilter": "Bộ lọc mới",
  "filterExpression": "Biểu thức bộ lọc",
  "layerDefaultSymbolTip": "Sử dụng ký hiệu mặc định của lớp",
  "uploadImage": "Tải ảnh lên",
  "selectLayerTip": "Vui lòng chọn một lớp.",
  "setTitleTip": "Vui lòng đặt tiêu đề.",
  "noTasksTip": "Không có bộ lọc nào được cấu hình. Nhấp vào \"${newFilter}\" để thêm một bộ lọc mới.",
  "collapseFiltersTip": "Thu gọn các biểu thức bộ lọc (nếu có) khi tiện ích được mở",
  "zoomtoTip": "Thu phóng vào lớp khi áp dụng bộ lọc",
  "groupByLayerTip": "Lọc nhóm theo lớp",
  "autoApplyWhenValueInput": "Tự động áp dụng bộ lọc này sau khi giá trị được nhập",
  "autoApplyWhenWidgetOpen": "Áp dụng bộ lọc này khi tiện ích được mở.",
  "info": "Thông tin",
  "expressions": "Biểu thức",
  "allowCustom": "Cho phép tạo bộ lọc tùy chỉnh",
  "matchMsgSetAll": "Hiển thị các đối tượng phù hợp với tất cả bộ lọc",
  "matchMsgSetAny": "Hiển thị các đối tượng phù hợp với bất kỳ bộ lọc nào"
});