define({
  "enableUndoRedo": "Omogući poništavanje/ponavljanje",
  "toolbarVisible": "Vidljiva alatna traka",
  "toolbarOptions": "Opcije alatne trake",
  "mergeVisible": "Spoji",
  "cutVisible": "Izreži",
  "reshapeVisible": "Preoblikuj",
  "back": "Natrag",
  "label": "Sloj",
  "edit": "Može se uređivati",
  "update": "Onemogući ažuriranje geometrije",
  "fields": "Polja",
  "actions": "Radnje",
  "editpageName": "Naziv",
  "editpageAlias": "Alias",
  "editpageVisible": "Vidljivo",
  "editpageEditable": "Može se uređivati",
  "noLayers": "Nema dostupnih slojeva geoobjekta koji se mogu uređivati",
  "configureFields": "Konfiguriraj polja sloja",
  "useFilterEdit": "Upotrijebi filtar predloška geoobjekta",
  "display": "Prikaži",
  "autoApplyEditWhenGeometryIsMoved": "Automatski primijenite uređivanje kad se pomakne geometrija",
  "snappingTolerance": "Postavite dopušteno odstupanje priljepljivanja u pikselima",
  "popupTolerance": "Postavite skočni prozor dopuštenog odstupanja uređivanja atributa u pikselima",
  "stickyMoveTolerance": "Postavite dopušteno odstupanje pomicanja ljepljive bilješke u pikselima",
  "usingSaveButton": "Nemojte primjenjivati uređivanja atributa dok ne kliknete gumb Spremi",
  "generalSettings": "Opće postavke",
  "editableLayersSetting": "Postavke slojeva koji se mogu uređivati",
  "honorTheWebMapSetting": "Poštivanje postavki web-karte",
  "honorTheWebMapSettingTip1": "Te postavke uključuju:",
  "honorTheWebMapSettingTip2": "Koji se slojevi mogu uređivati",
  "honorTheWebMapSettingTip3": "Polja koja želite prikazivati i uređivati",
  "honorTheWebMapSettingTip4": "Alias, redoslijed i format polja",
  "customSettings": "Prilagođene postavke"
});