define({
  "_widgetLabel": "Görünürlük",
  "observerLocation": "Gözlemci Konumu",
  "formatIconTooltip": "Biçim Girdisi",
  "addPointToolTip": "Gözlemci Konumu Ekle",
  "fieldOfView": "Görüş Alanı",
  "useMilsText": "Açılar için mil kullan",
  "observerHeight": "Gözlemci Yüksekliği",
  "minObsDistance": "Min. Gözlemlenebilir Mesafe",
  "maxObsDistance": "Maks. Gözlemlenebilir Mesafe",
  "taskURLError": "Araç yapılandırma dosyası erişilemeyen URL içeriyor. Lütfen sistem yöneticinize danışın",
  "taskURLInvalid": "Bu araç ile yapılandırılan coğrafi işlem görevi geçerli değil. Lütfen sistem yöneticinize danışın",
  "viewshedError": "Görünürlük oluşturulurken hata oluştu. Lütfen gözlemci konumunuzun yükselti yüzeyinin yayılımına düştüğünden emin olun./p</p>",
  "validationError": "<p>Görünürlük oluşturma formu eksik veya parametreler geçersiz. Lütfen kontrol edin:</p><ul><li>Bir gözlemci konumu ayarlanmış.</li><li>Gözlemci Görüş Alanı 0 değil.</li><li>Gözlemci yüksekliği geçerli bir değer içeriyor.</li><li>Minimum ve maksimum gözlemlenebilir mesafeler geçerli değerler içeriyor.</li></ul>",
  "comfirmInputNotation": "Girdi Gösterimini Onayla",
  "notationsMatch": "gösterimler girdinizle eşleşiyor lütfen hangisini kullanmak istediğinizi belirtin:",
  "createBtn": "Oluştur",
  "clearBtn": "Temizle",
  "setCoordFormat": "Koordinat Biçimi Dizgisini Ayarla",
  "prefixNumbers": "Pozitif ve negatif sayıların önüne ‘+/-’ işareti ekleyin",
  "parseCoordinatesError": "Koordinatlar ayrıştırılamıyor. Girdinizi denetleyin.",
  "cancelBtn": "İptal Et",
  "applyBtn": "Uygula",
  "invalidMessage": "Sayısal bir değer girin.",
  "observerRangeMessage": "Geçersiz Gözlemci Yüksekliği",
  "minimumRangeMessage": "Geçersiz Minimum Gözlemlenebilir Aralık",
  "maximumRangeMessage": "Maksimum Gözlemlenebilir Aralık Minimum Gözlemlenebilir Aralıktan ${limit} ${units} daha fazla olamaz.",
  "portalURLError": "ArcGIS Online kuruluşunuz veya Portal for ArcGIS için uygulama yapılandırılmadı. Lütfen sistem yöneticinize başvurun",
  "privilegeError": "Kullanıcı rolünüz analiz gerçekleştiremiyor. Analiz gerçekleştirmek için kuruluşunuzun yöneticisi size belirli <a href=”http://doc.arcgis.com/en/arcgis-online/reference/roles.htm” target=”_blank”>ayrıcalıklar</a> vermelidir.",
  "noServiceError": "Yükselti analizi servisi kullanılabilir değil. Lütfen ArcGIS Online kuruluşunuzu veya Portal for ArcGIS yapılandırmalarını kontrol edin.",
  "pointToolTooltip": "Gözlemci konumu eklemek için tıkla",
  "degreesLabel": "derece",
  "milsLabel": "mil",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Ondalık Dereceleri - Enlem/Boylam",
  "DDLongLatNotation": "Ondalık Dereceleri  - Boylam/Enlem",
  "DDMLatLongNotation": "Dereceler Ondalık Dakikalar - Enlem/Boylam",
  "DDMLongLatNotation": "Dereceler Ondalık Dakikalar - Boylam/Enlem",
  "DMSLatLongNotation": "Dereceler Dakikalar Saniyeler - Enlem/Boylam",
  "DMSLongLatNotation": "Dereceler Dakikalar Saniyeler - Boylam/Enlem",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Bant Harf",
  "UTMHemNotation": "UTM - Yarıküre (K/G)"
});