define({
  "transparencyLabel": "Прозорість",
  "outline": "Контур",
  "fill": "Заливка (колір застосовується, тільки коли для стиля вибрано параметр «Суцільний»)",
  "style": "Стиль",
  "mandatoryLabel": "Відстань обов'язкової евакуації",
  "mandatoryButtonLabel": "Задати налаштування відстані обов'язкової евакуації",
  "safeLabel": "Відстань безпечної евакуації",
  "safeButtonLabel": "Задати налаштування відстані безпечної евакуації",
  "selectOpLayerLabel": "Вибрати робочий шар для результатів",
  "selectDefaultMeasurementLabel": "Вибрати одиниці виміру за замовчуванням",
  "helpIconTooltip": "Робочий шар заповнюється шарами з поточної веб-карти, що відносяться до типу геометрії «полігон».",
  "lineStyles": {
    "esriSLSDash": "Пунктир",
    "esriSLSDashDot": "Штрихпунктир",
    "esriSLSDashDotDot": "Штрихпунктир з двома крапками",
    "esriSLSDot": "Точковий пунктир",
    "esriSLSLongDash": "Пунктир з довгим тире",
    "esriSLSLongDashDot": "Штрихпунктир з довгим тире",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Пунктир з коротким тире",
    "esriSLSShortDashDot": "Штрихпунктир з коротким тире",
    "esriSLSShortDashDotDot": "Штрихпунктир з коротким тире та двома крапками",
    "esriSLSShortDot": "Штрихпунктир з коротким тире",
    "esriSLSSolid": "Суцільний"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Назад",
    "esriSFSCross": "Хрест",
    "esriSFSDiagonalCross": "Діагональ",
    "esriSFSForwardDiagonal": "Вперед",
    "esriSFSHorizontal": "Горизонтальний",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Суцільний",
    "esriSFSVertical": "Вертикальний"
  },
  "threatTypeLabel": "Тип загрози",
  "symbologyLabel": "Умовні позначення",
  "generalLabel": "Загальна інформація",
  "addThreatTypesLabel": "Додати тип загрози",
  "threatTypeColLabel": "Тип загрози",
  "actions": "Дії",
  "newThreatTypePopupLabel": "Новий тип загрози",
  "chooseDefaultThreatTypeIconLabel": "Вибрати зі значень за замовчуванням",
  "mandatoryDistance": "Відстань обов'язкової евакуації",
  "safeDistance": "Відстань безпечної евакуації",
  "units": "Одиниці",
  "chooseDefaultThreatLabel": "Вибрати тип загрози за замовчуванням",
  "defaultThreatTypePopUpLabel": "Типи загрози за замовчуванням",
  "editThreatLabel": "Редагувати загрози",
  "defaultThreatTypeIconTooltip": "Список типів загрози за замовчуванням",
  "uniqueThreatTypeMsg": "Введіть унікальний тип загрози, тип загрози з цим іменем уже існує.",
  "requiredThreatTypeMsg": "Це поле є обов'язковим",
  "unitMeasureLabel": "Відстані у {0}",
  "pipeBombLabel": "Трубчастий вибуховий пристрій",
  "suicideBombLabel": "Пояс смертника",
  "briefcaseLabel": "Дипломат",
  "carLabel": "Легковий автомобіль",
  "suvVanLabel": "Кросовер/фургон",
  "smallDeliveryTruckLabel": "Невеликий автомобіль для розвезення",
  "containerWaterTruckLabel": "Контейнеровоз/автоцистерна",
  "semiTrailerLabel": "Напівпричіп"
});