define({
  "tabs_section_Label": "Kartice",
  "addTab": "Dodaj karticu",
  "layerName": "Sloj",
  "layerType": "Vrsta analize",
  "layerLabel": "Oznaka",
  "actions": "Radnje",
  "closest": "Najbliži geoobjekt",
  "proximity": "Blizina",
  "summary": "Sažetak",
  "select_lbl": "-- Odaberi --",
  "general_setting_Label": "Opće postavke",
  "units_text_lbl": "Jedinice udaljenosti",
  "maximum_distance_lbl": "Maksimalna udaljenost najbližeg geoobjekta",
  "buffer_text_lbl": "Oznaka pojasa",
  "buffer_lbl": "Udaljenost pojasa",
  "buffer_max_lbl": "Maksimalna udaljenost pojasa",
  "buffer_min_lbl": "Minimalna udaljenost pojasa",
  "routing_checkBox": "Omogući preusmjeravanje",
  "weather_Label": "Opcije vremena",
  "weather_checkBox": "Uključi informacije o vremenu",
  "selectLayers": "odaberi sloj s vremenom",
  "currentlySelectedLayer": "Slojevi s vremenom koji su trenutačno odabrani",
  "missingTabLabel": "Barem jedna kartica nema svoju oznaku",
  "missingLayerInWebMap": "Nema operativnih slojeva.",
  "selectFields": "Odaberi polja",
  "addField": "Dodaj polje",
  "sum": "Zbroj",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Prosječno",
  "count": "BROJ",
  "area": "POVRŠINA",
  "length": "DULJINA",
  "count_checkBox": "Prikaži broj geoobjekata",
  "area_checkBox": "Prikaži zbroj područja",
  "length_checkBox": "Prikaži zbroj duljina",
  "max_records": "Dosegnuto je maksimalno ograničenje",
  "save_label": "Opcije spremanja",
  "save_checkbox": "Omogući spremanje",
  "csv_label": "Opcije CSV-a",
  "csv_checkbox": "Izvezi sva polja u sloju",
  "display_label": "Opcije prikaza",
  "display_checkbox": "Prikaži geoobjekte sažetka",
  "snapshot_label": "Opcije snimke",
  "snapshot_checkbox": "Omogući snimku",
  "must_select_template": "Odaberite jedan od predložaka za uređivanje u opcijama za spremanje.",
  "count_label": "Oznaka zbroja",
  "area_label": "Oznaka područja",
  "length_label": "Oznaka dužine",
  "invalid_string_width": "Vrijednost je predugačka. ",
  "layer_type_not_supported": "Vrsta sloja nije podržana: ",
  "groupedSummary": "Grupirani zbrojevi",
  "groupByField": "Grupiraj po polju",
  "labelType": "Pridodaj oznaku",
  "prefix": "Kao prefiks",
  "suffix": "Kao sufiks",
  "need_group_field": "Upotrijebite radnju uređivanja za određivanje grupe po polju.",
  "fieldTitle": "Polje",
  "typeTitle": "Vrsta",
  "actionsTitle": "Radnje",
  "save_point_checkbox": "Spremi točke",
  "save_line_checkbox": "Spremi linije",
  "save_poly_checkbox": "Spremi poligone",
  "no_valid_popup_fields": "Nema valjanih polja u skočnom prozoru. Upotrijebite radnju uređivanja za određivanje polja.",
  "no_valid_fields": "Nema valjanih polja. Upotrijebite radnju uređivanja za određivanje opcija prikaza.",
  "incident_label": "Oznaka kartice",
  "locate_incident_label": "Oznaka zanimljivih područja",
  "incident": "Incident",
  "locate_incident": "Pronađi incident",
  "buffer_value": "Veličina pojasa"
});