define({
  "feedbackStyleLabel": "סגנון משוב מרחק וכיוון",
  "showTabLabel": "הצג כרטיסייה",
  "feedbackShapeLabel": "צורת משוב",
  "lineColorLabel": "צבע קו",
  "lineWidthLabel": "רוחב קו",
  "feedbackLabel": "תווית משוב",
  "textColorLabel": "צבע טקסט",
  "textSizeLabel": "גודל טקסט",
  "tabErrorMessage": "יש להגדיר את הווידג'ט להצגה של כרטיסייה אחת לפחות",
  "lineLabel": "קו",
  "circleLabel": "מעגל",
  "ellipseLabel": "אליפסה",
  "ringsLabel": "טבעות",
  "transparency": "שקיפות",
  "ddFeedbackStyleTabLabel": "סימבולוגיה",
  "miscellaneousTabLabel": "שונים",
  "operationalLineLayerSelectLabel": "בחר שכבת פולי קו תפעולית עבור תוצאות קו וטבעת",
  "operationalPolygonLayerSelectLabel": "בחר שכבת פוליגון תפעולית עבור תוצאות מעגל ואליפסה",
  "helpIconPolylineTooltip": "הרשימה של שכבת התפעול מתמלאת בשכבות מה-Web Map הנוכחית, שסוג הגיאומטריה שלהן הוא פוליגון.",
  "helpIconPolygonTooltip": "הרשימה של שכבת התפעול מתמלאת בשכבות מה-Web Map הנוכחית, שסוג הגיאומטריה שלהן הוא פוליגון."
});