define({
  "_widgetLabel": "עורך חכם",
  "_featureAction_SmartEditor": "עורך חכם",
  "noEditPrivileges": "לחשבונך אין הרשאות ליצור נתונים או לשנות אותם.",
  "widgetActive": "פעיל",
  "widgetNotActive": "לא פעיל",
  "pressStr": "לחץ ",
  "ctrlStr": " CTRL ",
  "snapStr": " כדי להפעיל הצמדה",
  "noAvailableTempaltes": "אין תבניות זמינות",
  "editorCache": " -- מטמון העורך",
  "presetFieldAlias": "שדה",
  "presetValue": "ערך קבוע מראש",
  "usePresetValues": " השתמש בערכים שנקבעו מראש (ישויות חדשות בלבד)",
  "editGeometry": " ערוך גיאומטריה",
  "savePromptTitle": "שמור ישות",
  "savePrompt": "האם ברצונך לשמור את הישות הנוכחית?",
  "deletePromptTitle": "מחק ישות",
  "deleteAttachment": "מחק קישור",
  "deletePrompt": "האם אתה בטוח שברצונך למחוק את הישות שנבחרה?",
  "attachmentLoadingError": "שגיאה בטעינת קישורי קבצים",
  "attachmentSaveDeleteWarning": "אזהרה: שינויים בקישורי קבצים נשמרים באופן אוטומטי",
  "autoSaveEdits": "שומר את הישות החדשה באופן אוטומטי",
  "addNewFeature": "צור ישות חדשה",
  "featureCreationFailedMsg": "לא ניתן ליצור רשומה/ישות חדשה",
  "relatedItemTitle": "טבלה/שכבה מקושרת",
  "relatedFeatureCount": "${layerTitle} עם ${featureCount} ישויות",
  "createNewFeatureLabel": "צור ישויות חדשות עבור ${layerTitle}",
  "invalidRelationShipMsg": "ודא ששדה המפתח הראשי: '‎${parentKeyField}‎' מכיל ערך חוקי",
  "pendingFeatureSaveMsg": "שמור את עריכת הישות לפני שתיצור ישות מקושרת.",
  "attachmentsRequiredMsg": "(*) נדרשות תוספות.",
  "coordinatePopupTitle": "העבר את הישות למיקום XY",
  "coordinatesSelectTitle": "מערכת קואורדינטות:",
  "mapSpecialReferenceDropdownOption": "ייחוס מרחבי של מפה",
  "latLongDropdownOption": "קו רוחב/אורך",
  "xAttributeTextBoxLabel": "קואורדינטה X:",
  "yAttributeTextBoxLabel": "קואורדינטה Y:",
  "latitudeTextBoxLabel": "קו רוחב:",
  "longitudeTextBoxLabel": "קו אורך:",
  "presetGroupFieldsLabel": "'${groupName}' יוחל על שדות השכבה הבאות:",
  "presetGroupNoFieldsLabel": "ל-'${groupName}' אין שדות מקושרים",
  "groupInfoLabel": "פרטי קבוצה עבור '${groupName}'",
  "editGroupInfoIcon": "ערוך ערך קבוצה עבור ${groupName}",
  "filterEditor": {
    "all": "הכל",
    "noAvailableTempaltes": "אין תבניות זמינות",
    "searchTemplates": "תבניות חיפוש",
    "filterLayerLabel": "סנן שכבות"
  },
  "invalidConfiguration": "תצורת הווידג'ט לא הוגדרה או שהשכבות בתצורה אינן נמצאות עוד במפה. פתח את האפליקציה במצב עריכה והגדר מחדש את תצורת הווידג'ט.",
  "geometryServiceURLNotFoundMSG": "לא ניתן לקבל כתובת URL של שירות גיאומטריה",
  "clearSelection": "נקה",
  "refreshAttributes": "עדכן מאפייני ישויות",
  "automaticAttributeUpdatesOn": "עדכון אוטומטי של מאפייני ישויות: פועל",
  "automaticAttributeUpdatesOff": "עדכון אוטומטי של מאפייני ישויות: כבוי",
  "moveSelectedFeatureToGPS": "העבר את הישות שנבחרה למיקום ה-GPS הנוכחי",
  "moveSelectedFeatureToXY": "העבר את הישות שנבחרה למיקום XY",
  "mapNavigationLocked": "ניווט במפה: נעול",
  "mapNavigationUnLocked": "ניווט במפה: לא נעול",
  "copyFeatures": {
    "title": "העתק ישויות",
    "createFeatures": "צור ישויות",
    "createSingleFeature": "צור ישות מרובת-גיאומטריות אחת",
    "noFeaturesSelectedMessage": "לא נבחרו ישויות",
    "selectFeatureToCopyMessage": "בחר ישויות להעתקה.",
    "multipleFeatureSaveWarning": "הערה: יצירת ישויות מרובות תוך שימוש בהעתקת ישות תשמור את כל הישויות מיד"
  },
  "addingFeatureError": "שגיאה בהוספת ישויות שנבחרו למפה. נסה שוב.",
  "addingFeatureErrorCount": "העתקה של ישויות '${copyFeatureErrorCount}' נכשלה.",
  "selectingFeatureError": "שגיאה בעת בחירת ישויות במפה. נסה שוב.",
  "customSelectOptionLabel": "בחר ישויות להעתקה",
  "noFeatureSelectedMessage": "לא נבחרו ישויות.",
  "multipleFeatureSaveMessage": "כל הישויות יישמרו מיד. האם ברצונך להמשיך?",
  "relativeDates": {
    "dateTypeLabel": "סוג תאריך",
    "valueLabel": "ערך",
    "fixed": "קבוע",
    "current": "נוכחי",
    "past": "עבור",
    "future": "עתיד",
    "popupTitle": "בחר ערך",
    "hintForFixedDateType": "עצה: התאריך והשעה שצוינו ישמשו כערך ברירת מחדל מוגדר מראש",
    "hintForCurrentDateType": "עצה: התאריך והשעה הנוכחיים ישמשו כערך ברירת מחדל מוגדר מראש",
    "hintForPastDateType": "עצה: הערך שצוין יופחת מהתאריך והשעה הנוכחיים לקבלת ערך ברירת המחדל של ההגדרה מראש.",
    "hintForFutureDateType": "עצה: הערך שצוין יתווסף לתאריך ולשעה הנוכחיים לקבלת ערך ברירת המחדל של ההגדרה מראש.",
    "noDateDefinedTooltip": "לא הוגדר תאריך"
  }
});