define({
  "taskUrl": "Užduoties URL",
  "setTask": "Taikyti",
  "setTaskPopupTitle": "Nustatyti užduotį",
  "validate": "Taikyti",
  "inValidGPService": "Įveskite leistiną geoduomenų apdorojimo paslaugą.",
  "GPFeatureRecordSetLayerERR": "Įveskite geoduomenų apdorojimo paslaugą naudodami tik GPFeatureRecordSetLayer tipo įvestis.",
  "invalidInputParameters": "Įvesties parametrų skaičius yra mažesnis nei 1 arba didesnis nei 3. Įveskite leistiną geoduomenų apdorojimo paslaugą.",
  "projectSetting": {
    "title": "Projekto nustatymai",
    "note": "Pastaba: projekto nustatymai yra pasirinktiniai, juos sukonfigūravęs vartotojas gali išsaugoti projektą norimuose internetinio žemėlapio sluoksniuose su tinklo nutrūkimo teritorija ir įvesties parametrais. Vartotojas gali išsaugoti kitus išvesties parametrus skirtuko Įvestis / išvestis grupėje Išvestis.",
    "projectPolygonLayer": "Projekto poligonų sluoksnis",
    "outputParameterName": "Išvesties parametro pavadinimas",
    "projectPointLayer": "Projekto taškų sluoksnis",
    "selectLabel": "Pasirinkti",
    "polygonLayerHelp": "<p>Bus rodomas (-i) poligonų sluoksnis (-iai), esant šioms sąlygoms:<br/><li>Sluoksnyje turi būti redagavimo galimybės, t. y. Kurti, Ištrinti ir Atnaujinti</li><li>Sluoksnyje turi būti 2 laukai su tiksliai tokiu pačiu pavadinimu ir duomenų tipu:</li><ul><li>name (tekstinio tipo laukas)</li><li>globalid (GlobalID tipo laukas)</li></ul><p/>",
    "outputParameterHelp": "<p>Bus rodomas (-i) išvesties poligonų sluoksnis (-iai) iš užduoties URL<p/>",
    "pointLayerHelp": "<p>Bus rodomas (-i) taškų sluoksnis (-iai), esant šioms sąlygoms:<br/><li>Sluoksnyje turi būti redagavimo galimybės, t. y. Kurti, Ištrinti ir Atnaujinti</li><li>Sluoksnyje turi būti 2 laukai su tiksliai tokiu pačiu pavadinimu ir duomenų tipu:</li><ul><li>inputtype (tekstinio tipo laukas)</li><li>projectid (GUID tipo laukas)</li></ul><p/>"
  },
  "inputOutputTab": {
    "title": "Įvestis / išvestis",
    "inputSettingsLabel": "Įvesties nustatymai",
    "outputSettingsLabel": "Išvesties nustatymai",
    "inputLabel": "Klasė",
    "inputTooltip": "Įrankio užuomina",
    "symbol": "Simbolis",
    "typeText": "Tipas",
    "outputParametersText": "Išvesties parametrai",
    "saveToLayerText": "Įrašyti į sluoksnį (pasirinktinai)",
    "skipText": "Galima praleisti",
    "visibilityText": "Matoma",
    "exportToCsvText": "Eksportuoti į CSV",
    "exportToCsvDisplayText": "CSV",
    "settitngstext": "Parametrai",
    "addFieldTitle": "Pridėti lauką",
    "enterDisplayText": "Įveskite rodoma tekstą",
    "setScale": "Nustatyti mastelį",
    "outputDisplay": "Rodyti tekstą",
    "saveToLayerHelp": "<p>Bus rodomas sluoksnis, esant šioms sąlygoms:<br/><li>Sluoksnyje turi būti redagavimo galimybės, t. y. Kurti, Ištrinti ir Atnaujinti</li><li>Sluoksnyje turi būti du laukai su pavadinimu ir duomenų tipu:</li><ul><li>parametername (tekstinio tipo laukas)</li><li>projectid (GUID tipo laukas)</li></ul><p/>"
  },
  "summaryTab": {
    "title": "Santrauka",
    "summaryFieldsetText": "Santraukos nustatymai",
    "inputOutput": "Įvestys / išvestys",
    "field": "Laukai",
    "operator": "Operatoriai",
    "inputOperatorCountOption": "Skaičius",
    "outputOperatorCountOption": "Skaičius",
    "outputOperatorSkipCountOption": "SkipCount",
    "fieldOperatorSumOption": "Suma",
    "fieldOperatorMinOption": "Min.",
    "fieldOperatorMaxOption": "Maks.",
    "fieldOperatorMeanOption": "Vidurkis",
    "expressionAddButtonText": "Pridėti",
    "expressionVerifyButtonText": "Tikrinti",
    "summaryEditorText": "Santraukos tekstas"
  },
  "generalSettings": {
    "title": "Bendrieji parametrai",
    "displayTextForButtonLegend": "Rodyti mygtuko Vykdyti tekstą",
    "displayTextforButtonDefaultValue": "Vykdyti",
    "displayTextForButton": "Rodyti tekstą",
    "autoZoomAfterTrace": "Mastelio keitimo parinktys",
    "zoomText": "Automatinis mastelio keitimas po trasavimo"
  },
  "validationErrorMessage": {
    "webMapError": "Internetiniame žemėlapyje sluoksnių nėra. Pasirinkite galiojantį internetinį žemėlapį.",
    "inputTypeFlagGreaterThanError": "Vėliavėlės tipo įvestis negali būti didesnė nei vienas.",
    "inputTypeFlagLessThanError": "Būtina bent viena vėliavėlės tipo įvestis.",
    "inputTypeBarrierErr": "Kliūties tipo įvestis negali būti didesnė nei vienas.",
    "inputTypeSkipErr": "Praleidimo tipo įvestis negali būti didesnė nei vienas.",
    "displayTextForButtonError": "Negali nebūti mygtuko Vykdyti rodymo teksto.",
    "UnableToLoadGeoprocessError": "Nepavyksta įkelti geoduomenų apdorojimo paslaugos.",
    "invalidSummaryExpression": "Netinkama išraiška.",
    "validSummaryExpression": "Pavyko!",
    "invalidProjectSettings": "Netinkami projekto nustatymai.<br/>Dalyje ${projectSetting} pasirinkite tinkamą reikšmę."
  },
  "hintText": {
    "labelTextHint": "Patarimas: pateikite išvesties parametro rezultatų skilčiai rodomą užrašą.",
    "displayTextHint": "Patarimas: tai bus rodoma šio išvesties parametro išsamios informacijos skiltyje.",
    "inputTextHint": "Patarimas: aukščiau sukurkite išraišką, pasirinkdami įvesties, išvesties ir laukų pavadinimus.",
    "expressionHint": "Patarimas: pasirinkite elementus ir spustelėkite Įtraukti, kad sukurtumėte išraišką."
  }
});