define({
  "_widgetLabel": "Guia de resposta davant d'emergències",
  "ergMainPageTitle": "Basada en el manual de resposta davant d'emergències Emergency Response Guidebook 2016",
  "coordInputLabelStart": "Ubicació de vessament (DD)",
  "coordInputLabel": "Ubicació de vessament",
  "addPointToolTip": "Afegeix una ubicació de vessament",
  "drawPointToolTip": "Feu clic per afegir una ubicació de vessament",
  "material": "Material",
  "materialPlaceholder": "Comença a escriure per cercar un material",
  "table3Message": "El material que heu seleccionat necessita informació addicional si tracteu un vessament gran.\n\nComproveu que teniu seleccionats els valors correctes de velocitat del vent i contenidor de transport.",
  "table2Message": "Pot ser que el material que heu seleccionat produeixi una gran quantitat de gasos perillosos per inhalació tòxica en entrar en contacte amb l'aigua.\n\nPotser voleu repensar si els materials següents són els més adequats en aquest cas:\n\n",
  "spillSize": "Abast del vessament",
  "small": "Petit",
  "large": "Gran",
  "fireLabel": "Mostra la zona d'aïllament d'incendis",
  "weatherLabel": "Clima actual a la ubicació del vessament",
  "weatherIntialText": "<br />S'actualitza un cop identificada la ubicació de vessament",
  "temperature": "Temperatura",
  "wind": "Vent",
  "c": "C",
  "f": "F",
  "weatherErrorMessage": "No s'ha obtingut informació sobre el clima. Actualitza els valors de velocitat del vent i de temps de vessament manualment",
  "windDirection": "Direcció del vent (cap a on bufa)",
  "timeOfSpill": "Temps de vessament",
  "day": "Dia",
  "night": "Nit",
  "windSpeed": "Velocitat del vent",
  "low": "Baixa",
  "moderate": "Moderada",
  "high": "Alta",
  "transportContainer": "Contenidor de transport",
  "rail": "Vagó cisterna",
  "semi": "Tràiler o camió cisterna",
  "mton": "Diversos cilindres d'una tona",
  "ston": "Diversos cilindres petits o un cilindre d'una tona",
  "ag": "Tanc nodrissa agrícola",
  "msm": "Diversos cilindres petits",
  "bleveLabel": "Mostra la zona d'aïllament de BLEVE",
  "capacity": "Capacitat del contenidor (litres)",
  "bleveMessage": "Per al material que heu seleccionat, es pot mostrar una distància d'evacuació addicional per a BLEVE.\n\nPer habilitar aquesta opció, activeu Mostra la zona d'aïllament de BLEVE i seleccioneu la capacitat adequada del contenidor.",
  "noPAZoneMessage": "No hi ha distàncies d'acció de protecció per a aquest material. Només s'han calculat les zones d'aïllament inicial i d'evacuació",
  "settingsTitle": "Configuració",
  "spillLocationLabel": "Ubicació de vessament",
  "spillLocationButtonLabel": "Configura la ubicació de vessament",
  "IISettingsLabel": "Zona d'aïllament inicial",
  "IIButtonLabel": "Configura l'aïllament inicial",
  "PASettingsLabel": "Zona d'acció de protecció",
  "PAButtonLabel": "Configura l'acció de protecció",
  "downwindSettingsLabel": "Zona a favor del vent",
  "downwindButtonLabel": "Configura les opcions a favor del vent",
  "fireSettingsLabel": "Zona d'aïllament d'incendis",
  "fireButtonLabel": "Configura l'aïllament d'incendis",
  "bleveSettingsLabel": "Zona d'aïllament de BLEVE",
  "bleveButtonLabel": "Configura les opcions de BLEVE",
  "style": "Estil",
  "lineStyles": {
    "esriSLSDash": "Guió",
    "esriSLSDashDot": "Guió punt",
    "esriSLSDashDotDot": "Guió punt punt",
    "esriSLSDot": "Punt",
    "esriSLSLongDash": "Guió llarg",
    "esriSLSLongDashDot": "Guió llarg punt",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Guió curt",
    "esriSLSShortDashDot": "Guió curt punt",
    "esriSLSShortDashDotDot": "Guió curt punt punt",
    "esriSLSShortDot": "Punt",
    "esriSLSSolid": "Cos geomètric"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Enrere",
    "esriSFSCross": "Creu",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Endavant",
    "esriSFSHorizontal": "Horitzontal",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Cos geomètric",
    "esriSFSVertical": "Vertical"
  },
  "resultsTitle": "Resultats",
  "publishERGBtn": "Publica",
  "ERGLayerName": "Nom de la capa d'ERG publicada",
  "invalidERGLayerName": "El nom de la capa només pot contenir caràcters alfanumèrics i de subratllat",
  "missingERGLayerName": "Heu d'introduir un nom per a l'ERG",
  "publishingFailedLayerExists": "Error de publicació: ja teniu un servei d'entitats anomenat {0}. Trieu un altre nom.",
  "checkService": "Comprova el servei: {0}",
  "createService": "Crea el servei: {0}",
  "unableToCreate": "No es pot crear: {0}",
  "addToDefinition": "Afegeix a la definició: {0}",
  "successfullyPublished": "S'ha publicat correctament la capa web{0}Administra la capa web",
  "userRole": "No es pot crear el servei perquè l'usuari no té permisos",
  "transparency": "Transparència",
  "outline": "Contorn",
  "fill": "Emplenament (el color només s'aplica quan l'estil està definit com a sòlid)",
  "createERGBtn": "Crea zones",
  "clearERGBtn": "Esborra",
  "labelFormat": "Format de l'etiqueta",
  "helpIconTooltip": "El llindar entre l'abast de vessament petit i gran és:\nLíquids: 55 galons (208 litres)\nSòlids: 60 lliures (300 quilograms)",
  "cellWidth": "Amplada de la cel·la (x)",
  "cellHeight": "Altura de la cel·la (y)",
  "invalidNumberMessage": "El valor que s'ha introduït no és vàlid",
  "invalidRangeMessage": "El valor ha de ser més gran que 0",
  "gridAngleInvalidRangeMessage": "El valor ha d'estar comprès entre -89,9 i 89,9",
  "formatIconTooltip": "Entrada de format",
  "setCoordFormat": "Defineix la cadena de format de coordenades",
  "prefixNumbers": "Afegeix el prefix \"+/-\" als nombres positius i negatius",
  "cancelBtn": "Cancel·la",
  "applyBtn": "Aplica",
  "comfirmInputNotation": "Confirma la notació d'entrada",
  "notationsMatch": "notacions que coincideixen amb la vostra entrada, confirmeu quina voleu utilitzar:",
  "missingLayerNameMessage": "Heu d'introduir un nom de capa vàlid per poder fer la publicació",
  "parseCoordinatesError": "No es poden analitzar les coordenades. Comproveu l'entrada.",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Graus decimals: latitud/longitud",
  "DDLongLatNotation": "Graus decimals: longitud/latitud",
  "DDMLatLongNotation": "Graus minuts decimals: latitud/longitud",
  "DDMLongLatNotation": "Graus minuts decimals: longitud/latitud",
  "DMSLatLongNotation": "Graus minuts segons: latitud/longitud",
  "DMSLongLatNotation": "Graus minuts segons: longitud/latitud",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM: lletra de banda",
  "UTMHemNotation": "UTM: hemisferi (N/S)"
});