define({
  "tabs_section_Label": "Fülek",
  "addTab": "Fül hozzáadása",
  "layerName": "Réteg",
  "layerType": "Elemzés típusa",
  "layerLabel": "Felirat",
  "actions": "Műveletek",
  "closest": "Legközelebbi vektoros elem",
  "proximity": "Közelség",
  "summary": "Összefoglalás",
  "select_lbl": "-- Kijelöl --",
  "general_setting_Label": "Általános beállítások",
  "units_text_lbl": "Távolság-mértékegységek",
  "miles": "mérföld",
  "kilometers": "kilométer",
  "feet": "láb",
  "meters": "méter",
  "yards": "yard",
  "nauticalMiles": "tengeri mérföld",
  "maximum_distance_lbl": "Legközelebbi vektoros elem maximális távolsága",
  "buffer_text_lbl": "Buffer felirata",
  "buffer_lbl": "Buffertávolság",
  "buffer_max_lbl": "Maximum buffertávolság",
  "buffer_min_lbl": "Minimum buffertávolság",
  "routing_checkBox": "Útvonal-megállapítás engedélyezése",
  "weather_Label": "Időjárás beállításai",
  "weather_checkBox": "Időjárási adatokkal együtt",
  "weather_celsius": "Celsius - kilométer",
  "selectLayers": "Időjárásrétegek kiválasztása",
  "currentlySelectedLayer": "Jelenleg kiválasztott időjárásrétegek",
  "missingTabLabel": "Legalább egy fülről hiányzik a felirat",
  "cancel": "Mégse",
  "ok": "OK",
  "missingLayerInWebMap": "Nem találhatók operatív rétegek.",
  "selectFields": "Mezők kiválasztása",
  "addField": "Mező hozzáadása",
  "sum": "ÖSSZ.",
  "min": "MIN.",
  "max": "MAX.",
  "avg": "ÁTL.",
  "count": "SZÁM",
  "area": "TERÜLET",
  "length": "HOSSZ",
  "count_checkBox": "Elemszám megjelenítése",
  "area_checkBox": "Terület megjelenítése",
  "length_checkBox": "Hossz megjelenítése",
  "max_records": "Elértük a maximális határértéket",
  "disable_checkBox": "Rétegláthatóság kezelésének tiltása",
  "optional_lbl": "Opcionális feliratok",
  "incident_lbl": "Incidens",
  "locate_lbl": "Incidens megkeresése"
});