define({
  root: ({
    locatorUrl: "Locator URL",
    set: "Set",
    locatorName: "Locator Name",
    locatorExample: "Example",
    countryCode: "Country or Region Code(s)",
    eg: "e.g. ",
    countryCodeHint: "Leaving this value blank will search all countries and regions",
    minCandidateScore: "Minimum Candidate Score",
    minCandidateScoreHint: "Leaving this value blank will use a minimum candidate score of 90",
    enableSingleField: "Single-field Options",
    singleFieldHint: "Address data will be in a single field",
    enableMultiField: "Multi-field Options",
    multiFieldHint: "Address data will be in multiple fields",
    enableXYField: "X/Y Field Options",
    xyFieldHint: "Data will contain X/Y coordinate values",
    instructionGeocode: "Add and configure locator services.",
    invalidUrlTip: "The URL ${URL} is invalid or inaccessible.",
    geocodeTabLabel: "Location Settings",
    lookupList: "Field Names to Recognize",
    isRecognized: "Field names in the table below are automatically recognized for this field",
    needsEditablePointLayers: "The webmap must contain at least one editable point layer.",
    editpageAlias: "Alias",
    configureFields: "Configure Layer Fields",
    configureSingleFields: "Configure a Single Address Field",
    configureMultiFields: "Configure Multiple Address Fields",
    configureXYFields: "Configure X/Y Fields",
    noFields: "Use the edit action to define one or more fields to display",
    display: "Display",
    duplicate: "Find Duplicate",
    duplicateTip: "Search this field for identical values between the source file and target layer./n When an identical match is found the record from the file will not be located and will be flagged as a duplicate.",
    noSelectField: "Please select the Feature Layer option first",
    newNamePlaceholder: "",
    xyFieldsLabelX: "X (Longitude)",
    xyFieldsLabelY: "Y (Latitude)",
    xyFieldsX: "X",
    xyFieldsY: "Y",
    easting: "Easting",
    northing: "Northing",
    lon: "LON",
    lat: "LAT",
    layerOptionHint: "Choose the layer to submit data to.",
    layerFieldTitle: "Target Layer",
    tempSymbolHint: "Choose the symbol that will be used to display the features.",
    tempSymbolTitle: "Display Symbol",
    maxRecords: "Max records",
    maxRecordsHint: "Max number of records to locate",
    searchRadius: "Search radius",
    searchRadiusHint: "Distance to search for duplicate features from layer",
    requiresInteger: "Please enter a numeric value.",
    requiresInteger0100: "Please enter a numeric value between 0 and 100",
    requiresLocator: "Please add at least one valid locator.",
    layerFields: "Layer Settings",
    layerFieldsHint: "Specify fields from the Target Layer that will be mapped to the source fields.",
    locatorError: "Locator is invalid or inaccessible.",
    optionNotMatch: "Field options not consistent across locators. Failover may not work as expected."
  }),
  "ar": 0,
  "bs": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "hi": 0,
  "hr": 0,
  "it": 0,
  "id": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sl": 0,
  "sr": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0,
  "zh-hk": 0,
  "zh-tw": 0
});