define({
  "_widgetLabel": "Netwerktracering",
  "_featureAction_NetworkTraceSkip": "Overslaan in tracering",
  "_featureAction_NetworkTraceUnskip": "Verwijderen uit locaties overslaan",
  "removedFromSkipLocations": "Verwijderd uit locaties overslaan",
  "alreadyRemovedFromSkipLocations": "Reeds verwijderd uit locaties overslaan",
  "locationSkipped": "Locatie overgeslagen",
  "configError": "Widget is niet naar behoren geconfigureerd.",
  "geometryServiceURLNotFoundMSG": "Kan geometrieservice-URL niet verkrijgen",
  "clearButtonValue": "Annuleren",
  "GPExecutionFailed": "De tracering kan niet worden voltooid. Probeer het opnieuw.",
  "backButtonValue": "Terug",
  "exportToCSVSuccess": "Exporteren naar CSV met succes voltooid.",
  "lblInputLocTab": "Invoerlocaties",
  "lblBlockLocTab": "Bloklocaties",
  "lblInputLocation": "Invoerobject",
  "lblBlockLocation": "Blokobject",
  "lblInputLocHeader": "Invoerlocaties (0)",
  "lblBlockLocHeader": "Bloklocaties (0)",
  "inputTabTitle": "Invoer",
  "outputTabTitle": "Uitvoer",
  "exportSelectAllCheckBoxLabel": "Alles selecteren",
  "lblSkipLocHeader": "Locaties overslaan (0)",
  "lblSkipLocation": "Locatie",
  "lblSkipLocTab": "Locaties overslaan",
  "skipAllLocationButtonLabel": "Alle locaties overslaan",
  "confirmSkipAllLocationsMessage": "Alle locaties worden overgeslagen, wilt u doorgaan?",
  "locationAlreadySkippedMessage": "Locatie reeds overgeslagen",
  "removeAllSkipLocationLabel": "Alles verwijderen",
  "newProjectOptionText": "Nieuw project",
  "selectProject": "Project selecteren",
  "saveButtonLabel": "Opslaan",
  "exportToCSVText": "Exporteren naar CSV",
  "editProjectAttributesToolTip": "Projectattribuut bewerken",
  "projectNameLabel": "Projectnaam",
  "saveProjectPopupTitle": "Opslaan",
  "saveAsLabel": "Opslaan als",
  "saveChangesMsg": "Wilt u de wijzigingen opslaan in <b>${loadProjectDropdownlabel}</b> of als een nieuw project?",
  "creatingNewProjectErrorMessage": "Fout bij aanmaken nieuw project. Probeer het opnieuw.",
  "projectNameFetchingErr": "Fout bij het ophalen van bestaande projectnamen. Probeer het opnieuw.",
  "projectAttributeLoadingErr": "Fout bij het laden van projectattributen. Probeer het opnieuw.",
  "attributeUpdatedMsg": "Attributen succesvol bijgewerkt.",
  "projectAttributeUpdatingErr": "Fout bij het bijwerken van projectattributen.",
  "loadingProjectDetailsErrorMessage": "Fout bij het ophalen van vlaggen, barrières en locaties om over te slaan. Probeer het opnieuw.",
  "savingProjectDetailsErr": "Fout bij het opslaan van projectdetails. Probeer het project opnieuw op te slaan.",
  "updatingOutagePolygonErr": "Fout bij het bijwerken van uitvalpolygoon. Probeer het project opnieuw op te slaan.",
  "deletingExistingPolygonErr": "Fout bij het verwijderen van bestaande uitvalpolygoon. Probeer het project opnieuw op te slaan.",
  "loadingProjectFeaturesErr": "Fout bij het laden van projectobjecten. Probeer het project opnieuw te laden.",
  "addingProjectFeaturesErr": "Fout bij het toevoegen van projectobjecten. Probeer het project opnieuw op te slaan.",
  "deletingExistingProjectFeaturesErr": "Fout bij het verwijderen van bestaande projectobjecten. Probeer het project opnieuw op te slaan.",
  "projectNotFoundErr": "Project niet gevonden",
  "projectLayersNotFound": "Lagen met geconfigureerde projectinstellingen zijn niet beschikbaar op kaart. Widget zal worden geladen in 'schetsmodus'.",
  "fetchingOutagePolygonMessage": "Fout bij het ophalen van uitvalpolygoon. Probeer het project opnieuw te laden.",
  "projectNameExistsMessage": "Projectnaam bestaat al. Voer een unieke projectnaam in.",
  "fetchingProjectNamesErrorMessage": "Fout bij het ophalen van bestaande projectnamen. Probeer het project opnieuw op te slaan.",
  "enterProjectNameMessage": "Voer projectnaam in.",
  "projectLengthErrorMessage": "Projectnaam kan niet groter zijn dan",
  "gpServiceNotAccessible": "Uw account heeft geen toegang tot de vereiste service om deze tracering uit te voeren.",
  "loadingClonedLayerErrorMessage": "Fout bij het laden van de gekloonde feature layer. Probeer het opnieuw.",
  "addingFeatureInClonedLayerError": "Fout bij het toevoegen van de grafische elementen aan de gekloonde feature layer. Probeer het opnieuw.",
  "selectingFeatureInClonedLayerError": "Fout bij het selecteren van de grafische elementen in de gekloonde feature layer. Probeer het opnieuw.",
  "filteredProjectError": "Fout bij het controleren van het ophalen van de gefilterde projectdetails. Probeer het opnieuw.",
  "filteredProjectMessage": "De geselecteerde projectattributen zijn niet beschikbaar wegens de filters uit de webmap of een andere widget die zijn toegepast. Verwijder de/het filter(s) en probeer het nogmaals.",
  "filteredProjectLoadMessage": "Uw project is niet meer beschikbaar. Selecteer een actief project.",
  "defaultValueForRunButton": "Uitvoeren",
  "closeButtonLabel": "Verwijderen"
});