define({
  "addLayer": "लेयर जोड़ें",
  "layerName": "लेयर",
  "layerRefresh": "ताज़ा करें",
  "layerLabel": "लेबल",
  "actions": "कार्रवाइयाँ",
  "mainPanelTextPlaceholder": "उदा: अंतिम अपडेट:",
  "invalidInterval": "केवल धनात्मक पूर्णांकों की अनुमति है",
  "uploadImage": "इमेज अपलोड करें",
  "iconColumnText": "प्रदर्शित करें",
  "refreshInterval": "मिनट में समय",
  "refreshIntervalTitle": "मिनट में समय के रूप में मूल्यांकन करें",
  "mainPanelText": "मुख्य पैनल का पाठ",
  "mainPanelIcon": "मुख्य पैनल की छवि",
  "refreshIntervalInstruction": "लेयर को ताज़ा करें हर:",
  "optionsText": "विकल्प",
  "symbolOptionsText": "मानचित्र सिम्बोलोज़ी",
  "iconOptionsText": "पैनल सिम्बोलोज़ी",
  "sympolPopupTitle": "सेटिंग्स को प्रदर्शित करें",
  "rdoLayer": "डिफ़ॉल्ट चिन्ह",
  "rdoCustom": "एक चित्र का उपयोग करें",
  "chkCluster": "समूहीकरण सक्षम करें",
  "defineClusterSymbol": "समूह चिन्ह निर्दिष्ट करें",
  "rdoEsri": "एक चिन्ह चुनें",
  "rdoLayerIcon": "मानचित्र चिन्ह का प्रयोग करें",
  "rdoCustomIcon": "एक छवि का उपयोग करें",
  "editCustomSymbol": "कस्टम चिन्ह को संशोधित करें",
  "editCustomIcon": "कस्टम आइकन को संशोधित करें",
  "missingRefreshValue": "कृपया ताज़ा अंतराल मान प्रदान करें।",
  "panelIconOption": "लोगो की छवि प्रदर्शित करें",
  "enableRefresh": "लेयर ताज़ा को सक्षम करें",
  "disableRefresh": "लेयर ताज़ा केवल फीचर संग्रह को समर्थित करता है।",
  "refreshUnit": "मिनट।",
  "symbolOptions": "चिह्न",
  "panelFeatureDisplay": "पैनल",
  "chkGroup": "समूह फीचर",
  "selectField": "फ़ील्ड",
  "fieldLabel": "लेबल",
  "addField": "क्षेत्र जोडें",
  "featureOptionsText": "लेयर विकल्प",
  "groupOptionsText": "समूह विकल्प",
  "panelCountOption": "फीचर संख्या प्रदर्शित करें",
  "missingLayerInWebMap": "कोई भी परिचालन लेयर नहीं मिली।",
  "displayClusterCnt": "फीचर संख्या प्रदर्शित करें",
  "defineClusterFont": "फ़ॉन्ट का रंग निर्दिष्ट करें",
  "max_records": "अधिकतम फ़ील्ड सीमा पूरी हो गई है",
  "hidePanel": "पैनल को छिपाएं",
  "hidePanelHelp": "मुख्य पैनल डिस्प्ले को सक्षम/अक्षम करें।",
  "continuousRefreshHelp": "नोट: फीचर संग्रह लगातार ताज़ा होगा।",
  "panelCountOptionHelp": "फीचर संख्या डिस्प्ले को सक्षम/अक्षम करें।",
  "panelIconOptionHelp": "मुख्य पैनल पर एक लोगो के डिस्प्ले को सक्षम/अक्षम करें।",
  "rdoGroupByField": "फ़ील्ड द्वारा",
  "rdoGroupByRenderer": "प्रतिपादक द्वारा"
});