define({
  "_widgetLabel": "Parcours de réseau",
  "_featureAction_NetworkTraceSkip": "Ignorer dans le parcours",
  "_featureAction_NetworkTraceUnskip": "Supprimer des localisations ignorées",
  "removedFromSkipLocations": "Supprimé des localisations ignorées",
  "alreadyRemovedFromSkipLocations": "Déjà supprimé des localisations ignorées",
  "locationSkipped": "Localisation ignorée",
  "configError": "Le widget n’est pas correctement configuré.",
  "geometryServiceURLNotFoundMSG": "Impossible d'obtenir l'URL du service de géométrie",
  "clearButtonValue": "Supprimer",
  "GPExecutionFailed": "Impossible de terminer le parcours. Réessayez ultérieurement.",
  "backButtonValue": "Précédent",
  "exportToCSVSuccess": "L’exportation au format CSV est terminée.",
  "lblInputLocTab": "Emplacements en entrée",
  "lblBlockLocTab": "Bloquer les emplacements",
  "lblInputLocation": "Entité en entrée",
  "lblBlockLocation": "Bloquer l’entité",
  "lblInputLocHeader": "Emplacements en entrée (0)",
  "lblBlockLocHeader": "Bloquer les emplacements (0)",
  "inputTabTitle": "Entrée",
  "outputTabTitle": "Sortie",
  "exportSelectAllCheckBoxLabel": "Sélectionner tout",
  "lblSkipLocHeader": "Ignorer les emplacements (0)",
  "lblSkipLocation": "Emplacement",
  "lblSkipLocTab": "Ignorer les emplacements",
  "skipAllLocationButtonLabel": "Ignorer tous les emplacements",
  "confirmSkipAllLocationsMessage": "Tous les lieux seront ignorés, souhaitez-vous continuer ?",
  "locationAlreadySkippedMessage": "Emplacement déjà ignoré",
  "removeAllSkipLocationLabel": "Supprimer tout",
  "newProjectOptionText": "Nouveau projet",
  "selectProject": "Sélectionner un projet",
  "saveButtonLabel": "Enregistrer",
  "exportToCSVText": "Exporter au format CSV",
  "editProjectAttributesToolTip": "Modifier les attributs de projet",
  "projectNameLabel": "Nom du projet",
  "saveProjectPopupTitle": "Enregistrer",
  "saveAsLabel": "Enregistrer sous",
  "saveChangesMsg": "Voulez-vous enregistrer vos modifications dans <b>${loadProjectDropdownlabel}</b> ou en tant que nouveau projet ?",
  "creatingNewProjectErrorMessage": "Une erreur s’est produite lors de la création du projet. Réessayez ultérieurement.",
  "projectNameFetchingErr": "Une erreur s’est produite lors de la récupération des noms de projet existants. Réessayez ultérieurement.",
  "projectAttributeLoadingErr": "Une erreur s’est produite lors du chargement des attributs du projet. Réessayez ultérieurement.",
  "attributeUpdatedMsg": "Les attributs ont été mis à jour.",
  "projectAttributeUpdatingErr": "Une erreur s’est produite lors de la mise à jour des attributs du projet.",
  "loadingProjectDetailsErrorMessage": "Une erreur s’est produite lors de la récupération des indicateurs, interruptions et emplacements ignorés. Réessayez ultérieurement.",
  "savingProjectDetailsErr": "Une erreur s’est produite lors de l’enregistrement des détails du projet. Réessayez d’enregistrer le projet.",
  "updatingOutagePolygonErr": "Une erreur s’est produite lors de la mise à jour du polygone de panne. Réessayez d’enregistrer le projet.",
  "deletingExistingPolygonErr": "Une erreur s’est produite lors de la suppression du polygone de panne existant. Réessayez d’enregistrer le projet.",
  "loadingProjectFeaturesErr": "Une erreur s’est produite lors du chargement des entités du projet. Réessayez de charger le projet.",
  "addingProjectFeaturesErr": "Une erreur s’est produite lors de l’ajout des entités du projet. Réessayez d’enregistrer le projet.",
  "deletingExistingProjectFeaturesErr": "Une erreur s’est produite lors de la suppression des entités existantes du projet. Réessayez d’enregistrer le projet.",
  "projectNotFoundErr": "Projet introuvable",
  "projectLayersNotFound": "Les couches des paramètres du projet configuré ne sont pas disponibles sur la carte. Le widget va être chargé en 'mode de construction'.",
  "fetchingOutagePolygonMessage": "Une erreur s’est produite lors de la récupération du polygone de panne. Réessayez de charger le projet.",
  "projectNameExistsMessage": "Le nom du projet existe déjà. Utilisez un nom de projet unique.",
  "fetchingProjectNamesErrorMessage": "Une erreur s’est produite lors de la récupération des noms de projet existants. Réessayez d’enregistrer le projet.",
  "enterProjectNameMessage": "Saisissez un nom de projet.",
  "projectLengthErrorMessage": "Le nom du projet ne peut pas être supérieur à",
  "gpServiceNotAccessible": "Votre compte ne peut pas accéder au service requis pour réaliser ce parcours.",
  "loadingClonedLayerErrorMessage": "Une erreur s’est produite lors du chargement de la couche d’entités clonée. Réessayez ultérieurement.",
  "addingFeatureInClonedLayerError": "Une erreur s’est produite lors de l’ajout des graphiques dans la couche d’entités clonée. Réessayez ultérieurement.",
  "selectingFeatureInClonedLayerError": "Une erreur s’est produite lors de la sélection des graphiques dans la couche d’entités clonée. Réessayez ultérieurement.",
  "filteredProjectError": "Une erreur s’est produite lors de la récupération des détails du projet filtré. Réessayez ultérieurement.",
  "filteredProjectMessage": "Les attributs de projet sélectionnés ne sont pas disponibles en raison des filtres appliqués à partir de la carte web ou d’un autre widget. Effacez les filtres et réessayez.",
  "filteredProjectLoadMessage": "Votre projet n’est plus disponible. Sélectionnez un projet actif.",
  "defaultValueForRunButton": "Exécuter",
  "closeButtonLabel": "Retirer"
});