define({
  "_widgetLabel": "Entitat d'informe",
  "select": "Selecciona",
  "draw": "Dibuixa",
  "chooseALayer": "Seleccioneu una capa",
  "clickAFeature": "Feu clic a una entitat del mapa per seleccionar-la.",
  "loadingFeatures": "S'estan obtenint els detalls de l'entitat seleccionada...",
  "errorTitle": "Error",
  "errorIdentify": "Error d'identificació d'entitats. Consulteu el registre de la consola per conèixer els detalls.",
  "infoWindowTitle": "Detalls",
  "layerLabel": "Nom de la capa",
  "reviewStatusLabel": "Estat de la revisió",
  "selectReviewStatusAdd": "Afegeix una entitat",
  "selectReviewStatusDelete": "Suprimeix l'entitat",
  "selectReviewStatusMove": "Mou l'entitat",
  "selectReviewStatusReshape": "Torna a formar l'entitat",
  "drawReviewStatusMissing": "Entitats no trobades",
  "drawReviewStatusPosition": "Error de posició",
  "drawReviewStatusShape": "Error de forma",
  "drawReviewStatusAttribute": "Error d'atribut",
  "notesLabel": "Notes",
  "severityLabel": "Gravetat",
  "reportedByLabel": "Informe de",
  "reportedByDefault": "anònim",
  "reportButton": "Informe",
  "reportMessage": "Informe rebut",
  "errorReportMessage": "S'ha produït un error en informar sobre l'entitat",
  "drawErrorInstructions": "Seleccioneu un punt, una línia o un polígon i dibuixeu la geometria de l'error al mapa:",
  "errorMapService": "S'ha produït un error en obtenir la informació del servei de mapes",
  "noFeatureSelected": "No s'han trobat entitats a la ubicació on s'ha fet clic",
  "selectFeatureMapPoint": "Feu clic per seleccionar una entitat",
  "drawFeatureMapPoint": "Feu clic per afegir un punt",
  "popupMessage": "Missatge",
  "popupError": "Error",
  "manyFeaturesSelected": "S'ha trobat més d'una entitat. Amplieu i seleccioneu una entitat per a l'informe."
});