define({
  "_widgetLabel": "Widoczność",
  "observerLocation": "Lokalizacja obserwatora",
  "formatIconTooltip": "Formatuj dane wejściowe",
  "addPointToolTip": "Dodaj lokalizację obserwatora",
  "fieldOfView": "Pole widzenia",
  "useMilsText": "Użyj milsów dla kątów",
  "observerHeight": "Wysokość obserwatora",
  "minObsDistance": "Minimalna widoczna odległość",
  "maxObsDistance": "Maksymalna widoczna odległość",
  "taskURLError": "Plik konfiguracji widżetu zawiera adres URL, który jest niedostępny. Sprawdź u administratora systemu",
  "taskURLInvalid": "Zadanie geoprzetwarzania skonfigurowane przy użyciu tego widżetu jest nieprawidłowe. Sprawdź u administratora systemu",
  "viewshedError": "Wystąpił błąd podczas tworzenia widoczności. Upewnij się, że lokalizacja obserwatora mieści się w zakresie powierzchni wysokościowej.</p>",
  "validationError": "<p>W formularzu tworzenia grafiki GRG brakuje niektórych parametrów lub są one nieprawidłowe. Upewnij się, że:</p><ul><li>Lokalizacja obserwatora została ustawiona.</li><li>Pole widzenia obserwatora nie jest równe 0.</li><li>Wartość wysokości obserwatora jest prawidłowa.</li><li>Wartości minimalnej i maksymalnej widocznej odległości są prawidłowe.</li></ul>",
  "comfirmInputNotation": "Potwierdź notację danych wejściowych",
  "notationsMatch": "liczba znalezionych notacji zgodnych z danymi wejściowymi. Wybierz, której notacji chcesz użyć:",
  "createBtn": "Tworzenie",
  "clearBtn": "Wyczyść",
  "setCoordFormat": "Skonfiguruj ciąg znakowy formatu współrzędnych",
  "prefixNumbers": "Dodaj prefiks '+/-' do liczb dodatnich i ujemnych",
  "parseCoordinatesError": "Nie można przeanalizować współrzędnych. Sprawdź dane wejściowe.",
  "cancelBtn": "Anuluj",
  "applyBtn": "Zastosuj",
  "invalidMessage": "Wpisz wartość numeryczną.",
  "observerRangeMessage": "Nieprawidłowa wysokość obserwatora",
  "minimumRangeMessage": "Nieprawidłowy minimalny zakres możliwy do obserwacji",
  "maximumRangeMessage": "Maksymalny zakres możliwy do obserwacji musi być większy niż minimalny zakres możliwy do obserwacji i nie może przekraczać ${limit} ${units}.",
  "portalURLError": "Adres URL instytucji w usłudze ArcGIS Online lub witryny Portal for ArcGIS nie jest skonfigurowany. Zwróć się do administratora systemu",
  "privilegeError": "Twoja rola użytkownika nie umożliwia wykonania analizy. Aby możliwe było wykonanie analizy, niezbędne jest nadanie Tobie przez administratora instytucji odpowiednich <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">uprawnień</a>.",
  "noServiceError": "Usługa analizy wysokościowej jest niedostępna. Sprawdź konfigurację instytucji w usłudze ArcGIS Online lub witryny Portal for ArcGIS.",
  "pointToolTooltip": "Kliknij, aby dodać lokalizację obserwatora",
  "degreesLabel": "stopnie",
  "milsLabel": "mile",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "Stopnie-Minuty-Sekundy (DMS)",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Stopnie dziesiętne — szerokość/długość geograficzna",
  "DDLongLatNotation": "Stopnie dziesiętne — długość/szerokość geograficzna",
  "DDMLatLongNotation": "Stopnie i minuty dziesiętne — szerokość/długość geograficzna",
  "DDMLongLatNotation": "Stopnie i minuty dziesiętne — długość/szerokość geograficzna",
  "DMSLatLongNotation": "Stopnie, minuty i sekundy — szerokość/długość geograficzna",
  "DMSLongLatNotation": "Stopnie, minuty i sekundy — długość/szerokość geograficzna",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM — litera pasa",
  "UTMHemNotation": "UTM — półkula (N/S)",
  "mainPageTitle": "Radialna linia widoczności",
  "resultsTitle": "Wyniki",
  "publishBtnLabel": "Publikuj",
  "layerName": "Nazwa opublikowanej warstwy",
  "invalidLayerName": "Nazwa warstwy może zawierać tylko znaki alfanumeryczne i znaki podkreślenia",
  "missingLayerName": "Wprowadź nazwę warstwy",
  "back": "Wstecz",
  "publishingFailedLayerExists": "Publikowanie nie powiodło się: Masz tylko usługę obiektową o nazwie {0}. Wybierz inną nazwę.",
  "checkService": "Sprawdź usługę: {0}",
  "createService": "Utwórz usługę: {0}",
  "unableToCreate": "Nie można utworzyć: {0}",
  "addToDefinition": "Dodaj do definicji: {0}",
  "successfullyPublished": "Pomyślnie opublikowano warstwę internetową{0}Zarządzaj warstwą internetową",
  "userRole": "Nie można utworzyć usługi, ponieważ użytkownik nie ma uprawnień",
  "publishToNewLayer": "Opublikuj wyniki w nowej warstwie obiektowej",
  "missingLayerNameMessage": "Przed opublikowaniem warstwy należy wprowadzić jej prawidłową nazwę",
  "regionTypeLabel": "Typ regionu",
  "centerPointLabel": "Punkt środkowy",
  "observationHeightLabel": "Wysokość obserwacji",
  "heightUnitLabel": "Jednostka wysokości",
  "minObservationDistanceLabel": "Minimalna odległość obserwacji",
  "maxObservationDistance": "Maksymalna odległość obserwacji",
  "distanceUnitLabel": "Jednostka odległości",
  "fovstartAngleLabel": "Początkowy kąt pola widzenia",
  "fovEndAngleLabel": "Końcowy kąt pola widzenia",
  "andleUnitsLabel": "Jednostki kąta"
});