define({
  "taskUrl": "URL úlohy",
  "setTask": "Nastavit",
  "setTaskPopupTitle": "Nastavit úlohu",
  "validate": "Nastavit",
  "inValidGPService": "Zadejte platnou službu geoprocessingu.",
  "noOutputParameterWithGeometryType": "Vybraná geoprocessingová služba musí mít alespoň jeden výstupní parametr zadaného typu geometrie. Vyberte jinou geoprocesní službu.",
  "invalidOutputGeometry": "Typ výstupní geometrie vybrané geoprocessingové služby není kompatibilní s nastavením projektu. Výsledky geoprocessingové služby nelze uložit.",
  "GPFeatureRecordSetLayerERR": "Zadejte službu geoprocessingu pouze pomocí vstupů typu „GPFeatureRecordSetLayer“.",
  "invalidInputParameters": "Počet vstupních parametrů je buď menší než 1, nebo větší než 3. Zadejte platnou službu geoprocessingu.",
  "projectSetting": {
    "title": "Nastavení projektu",
    "note": "Poznámka: Nastavení projektu jsou volitelná, jakmile nakonfigurovaný uživatel může uložit projekt v požadovaných vrstvách webové mapy pomocí oblasti výpadku sítě a vstupních parametrů. Uživatel může uložit ostatní výstupní parametry ze skupiny „Výstup“ na kartě „Vstup/Výstup“.",
    "projectPolygonLayer": "Kartograficky zobrazit polygonovou vrstvu",
    "outputParameterName": "Název výstupního parametru",
    "projectPointLayer": "Kartograficky zobrazit vrstvu bodů",
    "selectLabel": "Výběr",
    "polygonLayerHelp": "<p>Zobrazí se polygonové vrstvy s následujícími podmínkami:<br/><ul><li>Vrstva musí nabízet možnosti editace, jmenovitě „Vytvořit“, „Odstranit“ a „Aktualizovat“</li><li>Vrstva musí mít 2 pole s přesným názvem a typem dat:</li><ul><li>name (typ řetězec)</li><li>globalid (typ GlobalID)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>Zobrazí se výstupní polygonové vrstvy z úlohy URL<p/>",
    "pointLayerHelp": "<p>Zobrazí se bodové vrstvy s následujícími podmínkami: <br/><ul><li>Vrstva musí nabízet možnosti editace, jmenovitě „Vytvořit“, „Odstranit“ a „Aktualizovat“</li><li>Vrstva musí mít 2 pole s přesným názvem a typem dat:</li><ul><li>inputtype (typ řetězec)</li><li>projectid (typ GUID)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "Vlajka",
    "barrier": "Překážka",
    "skip": "Přeskočit",
    "title": "Vstup/výstup",
    "inputSettingsLabel": "Nastavení vstupu",
    "outputSettingsLabel": "Nastavení výstupu",
    "inputLabel": "Popisek",
    "inputTooltip": "Popis tlačítka",
    "symbol": "Symbol",
    "typeText": "Typ",
    "outputParametersText": "Výstupní parametry",
    "saveToLayerText": "Uložit do vrstvy (nepovinné)",
    "skipText": "Lze přeskočit",
    "visibilityText": "Viditelné",
    "exportToCsvText": "Exportovat do souboru CSV",
    "exportToCsvDisplayText": "CSV",
    "settitngstext": "Nastavení",
    "addFieldTitle": "Přidat pole",
    "enterDisplayText": "Zadejte text, který se má zobrazit",
    "setScale": "Nastavení měřítka",
    "outputDisplay": "Text, který se má zobrazit",
    "saveToLayerHelp": "<p>Zobrazí se vrstva s následujícími podmínkami:<br/><ul><li>Vrstva musí nabízet možnosti editace, jmenovitě „Vytvořit“, „Odstranit“ a „Aktualizovat“</li><li>Vrstva musí mít dvě pole s názvem a typem dat:</li><ul><li>parametername (typ řetězec)</li><li>projectid (typ GUID)</li></ul></ul><p/>"
  },
  "summaryTab": {
    "title": "Obecná nastavení",
    "summaryFieldsetText": "Nastavení shrnutí",
    "inputOutput": "Vstup/výstup",
    "field": "Pole",
    "operator": "Operátor",
    "inputOperatorCountOption": "Počet",
    "outputOperatorCountOption": "Počet",
    "outputOperatorSkipCountOption": "SkipCount",
    "fieldOperatorSumOption": "Součet",
    "fieldOperatorMinOption": "Min",
    "fieldOperatorMaxOption": "Max",
    "fieldOperatorMeanOption": "Průměr",
    "expressionAddButtonText": "Přidat",
    "expressionVerifyButtonText": "Ověřit",
    "summaryEditorText": "Text shrnutí",
    "autoZoomAfterTrace": "Další možnosti",
    "zoomText": "Automatické přiblížení po trasování",
    "summarSettingTooltipText": "Přidat vstupní/výstupní počet"
  },
  "validationErrorMessage": {
    "webMapError": "Ve webové mapě nejsou k dispozici žádné vrstvy. Vyberte platnou webovou mapu.",
    "inputTypeFlagGreaterThanError": "Vstup typu vlajka může být pouze jeden.",
    "inputTypeFlagLessThanError": "Je požadován alespoň jeden vstup typu vlajka.",
    "inputTypeBarrierErr": "Vstup typu překážka může být pouze jeden.",
    "inputTypeSkipErr": "Vstup typu přeskočení může být pouze jeden.",
    "displayTextForButtonError": "Text, který se má zobrazit pro tlačítko „Spustit“, musí být vyplněný.",
    "UnableToLoadGeoprocessError": "Nelze načíst službu geoprocessingu.",
    "invalidSummaryExpression": "Neplatný výraz.",
    "validSummaryExpression": "Hotovo!",
    "invalidProjectSettings": "Neplatná nastavení projektu.<br/> Vyberte platnou hodnotu v '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "Nápověda: Zobrazí popisek pro panel výsledků výstupního parametru.",
    "displayTextHint": "Nápověda: Zobrazí se v panelu detailů pro tento výstupní parametr.",
    "inputTextHint": "Nápověda: Sestavte výše uvedený výraz tím, že vyberete vstup, výstup a názvy polí.",
    "expressionHint": "Nápověda: Vyberte položky a klikněte na možnost Přidat, čímž sestavíte výraz."
  }
});