define({
  "settings": "Ayarlar",
  "titleSettings": "Metin ayarları",
  "imageSettings": "Görüntü ayarları",
  "backgroundColor": "Arka plan rengi",
  "alignment": "Hizalama",
  "textSize": "Metin boyutu",
  "textColor": "Metin rengi",
  "dataSource": "Veri kaynağı",
  "chartSettings": "Grafik ayarları",
  "data": "Veri",
  "dataLabels": "Veri etiketleri",
  "displayMode": "Gösterim Modu",
  "featureOption": "Değerleri özelliğe göre görüntüle",
  "categoryOption": "Değerleri kategoriye göre görüntüle",
  "countOption": "Özellik sayımlarını kategoriye göre görüntüle",
  "fieldOption": "Öznitelik değerlerini grafik olarak görüntüle",
  "categoryField": "Kategori alanı",
  "labelField": "Etiket alanı",
  "valueFields": "Değer alanları",
  "operation": "İşlem",
  "sumOption": "Toplam",
  "averageOption": "Ortalama",
  "minOption": "Minimum",
  "maxOption": "Maksimum",
  "dataFormat": "Veri biçimi",
  "decimalPlaces": "Ondalık basamak sayısı",
  "prefix": "Ön Ek",
  "suffix": "Son Ek",
  "dataType": "Veri türü",
  "featureCount": "Detay sayısı",
  "fieldStatistics": "Alan istatistikleri",
  "display": "Görünüm",
  "chartColor": "Grafik rengi",
  "horizontalAxis": "Yatay eksen",
  "verticalAxis": "Dikey eksen",
  "legend": "Gösterim",
  "position": "Konum",
  "top": "En Üst",
  "bottom": "En Alt",
  "useDataSourceSelection": "Seçimi kullan",
  "dataSourceFilterByExtent": "Yayılıma göre filtrele",
  "changeTemplate": "Şablonu değiştir",
  "numberSettings": "Sayı ayarları",
  "gaugeSettings": "Ölçek ayarları",
  "indicators": "Göstergeler",
  "ifValue": "Eğer değer",
  "and": "ve",
  "numberOperatorIsLessThan": "şundan küçük olanlar",
  "numberOperatorIsGreaterThan": "şundan büyük olanlar",
  "numberOperatorIsBetween": "şu değerler arasında olanlar",
  "numberOperatorIsEqual": "eşittir",
  "numberOperatorIsNotEqual": "eşit değildir",
  "then": "Then",
  "ratio": "Oran",
  "trueValue": "True değeri",
  "changeValueColor": "değer rengini şuna değiştir",
  "changeGaugeColor": "ölçek rengini şuna değiştir",
  "setIndicatorIcon": "gösterge simgesini şuna ayarla",
  "icons": "Simgeler",
  "style": "Stil",
  "placement": "Yerleşim",
  "left": "Sol",
  "replace": "Değiştir",
  "right": "Sağ",
  "color": "Renkli",
  "dataRange": "Veri aralığı",
  "targetValue": "Hedef değer",
  "currentValue": "Geçerli değer",
  "gaugeColor": "Ölçek rengi",
  "min": "Minimum",
  "max": "Maksimum",
  "displayValueIn": "Değeri şu cinsten görüntüle:",
  "noData": "Veri yok",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Uyarı",
  "noSettingWaring1": "Özelliklerini ayarlamak için bir ögeye tıklayın.",
  "noSettingWaring2": "Bir ögeyi yeniden boyutlandırmak veya yeniden sıralamak için sürükleyin.",
  "donNotShowAgain": "Tekrar gösterme",
  "changeTemplateWarning": "Bu, tüm ayarlarınızı siler ve yeni bir boş şablon açar.",
  "requiredFieldWarning": "Bu değer gereklidir:",
  "dataSourceNotSet": "Veri kaynağını ayarlayın.",
  "addIndicatorTip": "Gösterge ekle",
  "chooseTemplatePopupTitle": "Şablon seç",
  "stringsInTemplate": {
    "name_number": "Sayı",
    "name_gauge": "Ölçü",
    "name_vertical_gauge": "Dikey Ölçü",
    "name_horizontal_gauge": "Yatay Ölçü",
    "name_pie_chart": "Pasta Grafik",
    "name_column_chart": "Sütun Grafiği",
    "name_bar_chart": "Çubuk Grafik",
    "name_line_chart": "Çizgi Grafik",
    "titleOfTheInfographic": "BİLGİ GRAFİĞİ BAŞLIĞI",
    "description": "Açıklama: bu bilgi grafiği hakkında ek bilgiler."
  }
});