define({
  "_widgetLabel": "Tekenen",
  "selectDrawMode": "Tekenmodus selecteren",
  "clear": "Wissen",
  "point": "Punt",
  "line": "Lijn",
  "polyline": "Polylijn",
  "freehandPolyline": "Polylijn in vrije stijl",
  "triangle": "Driehoek",
  "extent": "Omhulsel",
  "circle": "Cirkel",
  "ellipse": "Ellips",
  "polygon": "Veelhoek",
  "freehandPolygon": "Vrije hand-vlak",
  "text": "Tekst",
  "style": "Stijl",
  "alpha": "Transparant",
  "width": "Breedte",
  "size": "Grootte",
  "color": "Kleur",
  "markerColor": "Kleur van markering",
  "outlineColor": "Omtrekkleur",
  "lineColor": "Lijnkleur",
  "fillColor": "Opvulkleur",
  "showMeasurements": "Metingen weergeven",
  "showLocationMeasurement": "Toon locatiemeting",
  "showAreaMeasurement": "Toon oppervlaktemeting",
  "showDistanceMeasurement": "Toon afstandmeting",
  "showDistanceMeasurementForLine": "Toon lengtemeting",
  "showDistanceMeasurementForPolygon": "Toon omtrekmeting",
  "locationToggleOn": "Druk op de wisselknop om locatiemeting te tonen",
  "locationToggleOff": "Druk op de wisselknop om locatiemeting te verbergen",
  "areaToggleOn": "Druk op de wisselknop om oppervlaktemeting te tonen",
  "areaToggleOff": "Druk op de wisselknop om oppervlaktemeting te verbergen",
  "distanceForLineToggleOn": "Druk op de wisselknop om lengtemeting te tonen",
  "distanceForLineToggleOff": "Druk op de wisselknop om lengtemeting te verbergen",
  "distanceForPolygonToggleOn": "Druk op de wisselknop om omtrekmeting te tonen",
  "distanceForPolygonToggleOff": "Druk op de wisselknop om omtrekmeting te verbergen",
  "areaUnits": "Oppervlakte-eenheden",
  "distanceUnits": "Afstandseenheden",
  "kilometers": "Kilometer",
  "miles": "Mijl",
  "meters": "Meter",
  "feet": "Voet",
  "yards": "Yard",
  "nauticalmiles": "Zeemijl",
  "squareKilometers": "Vierkante kilometer",
  "squareMiles": "Vierkante mijl",
  "acres": "Acres",
  "hectares": "Hectare",
  "squareMeters": "Vierkante meter",
  "squareFeet": "Vierkante voet",
  "squareYards": "Vierkante yard",
  "undo": "Ongedaan maken",
  "redo": "Opnieuw uitvoeren",
  "results": "Resultaten",
  "points": "Punten",
  "lines": "Lijnen",
  "areas": "Gebieden",
  "locationLabel": "Locatie: ${value}",
  "areaLabel": "Oppervlakte: ${value} ${unit}",
  "distanceLabel": "Afstand: ${value} ${unit}",
  "distanceLabelForLine": "Lengte: ${value} ${unit}",
  "distanceLabelForPolygon": "Omtrek: ${value} ${unit}"
});