define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Punktu pievienošana, noklikšķinot kartē",
  "addRingsDtWt": "Pievienojiet apļus, braukšanas laiku un iešanas laiku.",
  "apply": "Lietot",
  "back": "Atpakaļ",
  "colon": ":",
  "creditInformation": "Kredītu informācija",
  "driveTime": "Braukšanas laiks",
  "esriInfographics": "Esri infografika",
  "esriReports": "Esri pārskati",
  "headerDescription_km": "kilometrs",
  "headerDescription_miles": "jūdze",
  "headerDescription_minutes": "minūte",
  "infographics": "Infografika",
  "invalidValueRing": "Vērtībām jābūt diapazonā no 0 līdz 1000.",
  "invalidValueDTWT": "Vērtībām jābūt diapazonā no 0 līdz 300.",
  "km": "km",
  "miles": "jūdzes",
  "minutes": "minūtes",
  "myInfographics": "Mana infografika",
  "myReports": "Mani pārskati",
  "noPermissions": "Jūsu konts neatbalsta Business Analyst logrīka izmantošanu. Lai palaistu Business Analyst logrīku, jūsu organizācijas administratoram jānodrošina jums GeoEnrichment un tīkla analīzes izmantošanas tiesības <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privileges</a>, kā arī jāpiešķir <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">kredītpunkti</a>.",
  "radii": "rādiuss",
  "radius": "Rādiuss",
  "radius_lowercase": "rādiuss",
  "reports": "Pārskati",
  "ring": "Aplis",
  "rings": "Apļi",
  "runInfographic": "Palaist infografiku",
  "runReport": "Palaist pārskatu",
  "selectPointOrPolygon": "Kartē atlasiet punkta vai daudzstūra elementu, sameklējiet adresi vai vietu vai nometiet kartē spraudīti, lai skatītu plašāku informāciju par teritorijām.",
  "selectReport": "Izvēlēties pārskatu",
  "selectTemplate": "Izvēlieties veidni",
  "sharedInfographics": "Koplietota infografika",
  "sharedReports": "Koplietoti pārskati",
  "thisEntryIsNotValid": "Šis ieraksts nav derīgs.",
  "time": "Laiks",
  "walkTime": "Iešanas laiks",
  "widgetDescription": "Piekļūstiet infografikai un pārskatiem, kas apkopo galvenos jebkuras teritorijas rādītājus un datus.",
  "None": "Atlasīt..."
});