define({
  "addLayer": "Dodaj sloj",
  "layerName": "Sloj",
  "layerRefresh": "Osvježi",
  "layerLabel": "Oznaka",
  "actions": "Radnje",
  "mainPanelTextPlaceholder": "npr.: Posljednje ažuriranje:",
  "invalidInterval": "Podržani su samo brojčani znakovi.",
  "uploadImage": "Učitajte sliku",
  "iconColumnText": "Prikaži",
  "refreshInterval": "Vrijeme u minutama",
  "refreshIntervalTitle": "Procijenjeno kao vrijeme u minutama",
  "mainPanelText": "Tekst na glavnoj ploči",
  "mainPanelIcon": "Slika na glavnoj ploči",
  "refreshIntervalInstruction": "Osvježi slojeve svaki/e:",
  "optionsText": "Opcije",
  "symbolOptionsText": "Simbologija karte",
  "iconOptionsText": "Simbologija ploče",
  "sympolPopupTitle": "Postavke prikaza",
  "rdoLayer": "Zadani simbol",
  "rdoCustom": "Upotrijebi sliku",
  "chkCluster": "Omogući grupiranje",
  "defineClusterSymbol": "Odredi simbol klastera",
  "rdoEsri": "Odaberi simbol",
  "rdoLayerIcon": "Upotrijebi simbol karte",
  "rdoCustomIcon": "Upotrijebi sliku",
  "editCustomSymbol": "Uredi prilagođeni simbol",
  "editCustomIcon": "Uredi prilagođenu ikonu",
  "missingRefreshValue": "Navedite vrijednost za interval osvježavanja.",
  "panelIconOption": "Prikaži sliku logotipa",
  "enableRefresh": "Omogući osvježavanje sloja",
  "disableRefresh": "Osvježavanje sloja podržano samo za kolekcije geoobjekata",
  "layer_type_not_supported": "Vrsta sloja nije podržana: ",
  "refreshUnit": "minute.",
  "symbolOptions": "Simbol",
  "panelFeatureDisplay": "Ploča",
  "chkGroup": "Grupiraj geoobjekte",
  "selectField": "Polje",
  "fieldLabel": "Oznaka",
  "addField": "Dodaj polje",
  "featureOptionsText": "Opcije sloja",
  "groupOptionsText": "Opcije grupe",
  "panelCountOption": "Prikaži zbroj geoobjekata",
  "rdoStack": "Prikaži novu liniju za svako polje",
  "rdoAppend": "Pridodaj polja na jednu liniju",
  "missingLayerInWebMap": "Nema operativnih slojeva.",
  "displayClusterCnt": "Prikaži broj geoobjekata",
  "defineClusterFont": "Odredi boju fonta",
  "max_records": "Dosegnuto je maksimalno ograničenje polja"
});