define({
  "_widgetLabel": "Conocimiento de la situación",
  "locate_incident": "Localizar incidente",
  "reverse_geocoded_address": "Dirección más próxima",
  "reverse_geocoded_error": "No disponible",
  "now": "AHORA",
  "wind": "VIENTO",
  "SUN": "DOM",
  "MON": "LUN",
  "TUE": "MAR",
  "WED": "MIÉ",
  "THU": "JUE",
  "FRI": "VIE",
  "SAT": "SÁB",
  "actionLabel": "Definir ubicación",
  "drawPoint": "Dibujar punto",
  "drawLine": "Dibujar línea",
  "drawPolygon": "Dibujar polígono",
  "saveIncident": "Guardar",
  "clearIncident": "Empezar de nuevo",
  "noFeaturesFound": "No se encontraron entidades.",
  "downloadCSV": "Descargar",
  "sum": "Suma",
  "min": "Mínimo",
  "max": "Máximo",
  "avg": "Media",
  "count": "TOTAL",
  "area": "ÁREA",
  "length": "LONGITUD",
  "update_btn": "Hecho",
  "delete_btn": "Eliminar",
  "get_directions": "Obtener instrucciones",
  "incident": "Incidente",
  "incidents": "Incidentes",
  "buffer": "Zona de influencia",
  "buffers": "Zonas de influencia",
  "weather": "Tiempo",
  "poweredBy": "Con tecnología de",
  "_featureAction_ActionLabel": "Definir ubicación",
  "_featureAction_AddRemoveActionLabel": "Agregar/Quitar ubicación",
  "snapshot": "Carpeta SnapShot creada por el id. de la aplicación:",
  "user_credentials": "El usuario no tiene privilegios válidos.",
  "snapshot_complete": "Instantánea creada correctamente.",
  "snapshot_failed": "Error al crear la instantánea.",
  "notPolySnapShot": "Especifique una distancia de zona de influencia antes de crear una instantánea.",
  "notValidDownload": "No hay resultados válidos para descargar.",
  "snapshot_append": "Instantánea",
  "of_append": "de",
  "layer_append": "capa",
  "downloadAll": "Descargar todo",
  "createSnapshot": "Crear instantánea",
  "calculated_results": "Información resumida",
  "closest": "Entidad más próxima",
  "proximity": "Proximidad",
  "summary": "Resumen",
  "groupedSummary": "Recuentos agrupados",
  "_count": "Calcular",
  "utc": "UTC",
  "approximate": "aproximado",
  "snapshot_name": "Establecer nombre de instantánea",
  "invalid_snapshot_name": "Nombre de instantánea no válido."
});