define({
  "_widgetLabel": "Netværkssporing",
  "_featureAction_NetworkTraceSkip": "Skip i sporing",
  "_featureAction_NetworkTraceUnskip": "Fjern fra tilsidesættelse af placeringer",
  "removedFromSkipLocations": "Fjernet fra tilsidesættelse af placeringer",
  "alreadyRemovedFromSkipLocations": "Allerede fjernet fra tilsidesættelse af placeringer",
  "locationSkipped": "Placering tilsidesat",
  "configError": "Widget er ikke korrekt konfigureret.",
  "geometryServiceURLNotFoundMSG": "Kan ikke hente geometritjeneste-URL",
  "clearButtonValue": "Ryd",
  "GPExecutionFailed": "Sporing kan ikke fuldføres. Prøv igen.",
  "backButtonValue": "Bagside",
  "exportToCSVSuccess": "Eksport til CSV er fuldført uden fejl.",
  "lblInputLocTab": "Input-placeringer",
  "lblBlockLocTab": "Blokplaceringer",
  "lblInputLocation": "Input-objekt",
  "lblBlockLocation": "Blokobjekt",
  "lblInputLocHeader": "Input-placeringer (0)",
  "lblBlockLocHeader": "Blokplaceringer (0)",
  "inputTabTitle": "Input",
  "outputTabTitle": "Output",
  "exportSelectAllCheckBoxLabel": "Vælg alle",
  "lblSkipLocHeader": "Tilsidesæt placeringer (0)",
  "lblSkipLocation": "Position",
  "lblSkipLocTab": "Tilsidesæt placeringer",
  "skipAllLocationButtonLabel": "Tilsidesæt alle placeringer",
  "confirmSkipAllLocationsMessage": "Alle placeringer bliver tilsidesat, vil du fortsætte?",
  "locationAlreadySkippedMessage": "Placering allerede tilsidesat",
  "removeAllSkipLocationLabel": "Fjern alle",
  "newProjectOptionText": "Nyt projekt",
  "selectProject": "Vælg projekt",
  "saveButtonLabel": "Gem",
  "exportToCSVText": "Eksportér til CSV",
  "editProjectAttributesToolTip": "Redigér projektattributter",
  "projectNameLabel": "Projektnavn",
  "saveProjectPopupTitle": "Gem",
  "saveAsLabel": "Gem som",
  "saveChangesMsg": "Vil du gemme ændringerne af <b>${loadProjectDropdownlabel}</b> eller gemme som et nyt projekt?",
  "creatingNewProjectErrorMessage": "Fejl under oprettelse af nyt projekt. Prøv igen.",
  "projectNameFetchingErr": "Fejl under hentning af eksisterende projektnavne. Prøv igen.",
  "projectAttributeLoadingErr": "Fejl under indlæsning af projektattributter. Prøv igen.",
  "attributeUpdatedMsg": "Attributter opdateret uden fejl.",
  "projectAttributeUpdatingErr": "Fejl under opdatering af projektattributter.",
  "loadingProjectDetailsErrorMessage": "Fejl under hentning af flag, grænser og tilsidesatte placeringer. Prøv igen.",
  "savingProjectDetailsErr": "Fejl under lagring af projektoplysninger. Prøv at gemme projektet igen.",
  "updatingOutagePolygonErr": "Fejl under opdatering af polygon for nedbrud. Prøv at gemme projektet igen.",
  "deletingExistingPolygonErr": "Fejl under sletning af eksisterende polygon for nedbrud. Prøv at gemme projektet igen.",
  "loadingProjectFeaturesErr": "Fejl under indlæsning af projektegenskaber. Prøv at indlæse projektet igen.",
  "addingProjectFeaturesErr": "Fejl under tilføjelse af projektegenskaber. Prøv at gemme projektet igen.",
  "deletingExistingProjectFeaturesErr": "Fejl under sletning af eksisterende projektegenskaber. Prøv at gemme projektet igen.",
  "projectNotFoundErr": "Projekt ikke fundet",
  "projectLayersNotFound": "De konfigurerede projektindstillingslag findes ikke i kortet. Widget vil blive indlæst i 'Tegnetilstand'.",
  "fetchingOutagePolygonMessage": "Fejl under hentning af polygon for nedbrud. Prøv at indlæse projektet igen.",
  "projectNameExistsMessage": "Projektnavnet findes allerede. Brug et entydigt projektnavn.",
  "fetchingProjectNamesErrorMessage": "Fejl under hentning af eksisterende projektnavne. Prøv at gemme projektet igen.",
  "enterProjectNameMessage": "Indtast projektnavn.",
  "projectLengthErrorMessage": "Projektnavnet kan ikke være større end",
  "gpServiceNotAccessible": "Din konto har ikke adgang til den tjeneste, der er nødvendig for at udføre denne sporing.",
  "loadingClonedLayerErrorMessage": "Fejl under indlæsning af det klonede vektorlag. Prøv igen.",
  "addingFeatureInClonedLayerError": "Fejl under tilføjelse af grafik til det klonede vektorlag. Prøv igen.",
  "selectingFeatureInClonedLayerError": "Fejl under valg af grafik i det klonede vektorlag. Prøv igen.",
  "filteredProjectError": "Fejl under kontrol af hentning af filtrerede projektoplysninger. Prøv igen.",
  "filteredProjectMessage": "De valgte projektattributter er ikke tilgængelige på grund af de anvendte filtre fra webkortet eller en anden widget. Ryd filteret/filtrene, og prøv igen.",
  "filteredProjectLoadMessage": "Dit projekt er ikke længere tilgængeligt. Vælg et aktivt projekt.",
  "defaultValueForRunButton": "Kør",
  "closeButtonLabel": "Fjern"
});