define({
  root: ({
    addLayer: "Add Layer",
    layerName: "Layer",
    layerRefresh: "Refresh",
    layerLabel: "Label",
    actions: "Actions",
    popupOk: "OK",
    popupCancel: "Cancel",
    mainPanelTextPlaceholder: "ex: HIGHWAY CONDITIONS",
    invalidInterval: "Only numeric characters supported.",
    uploadImage: "Upload Image",
    iconColumnText: "Icon",
    refreshInterval: "1 'Evaluated as time in Minutes'",
    refreshIntervalTitle: "Evaluated as time in Minutes",
    mainPanelText: "Main Panel Text",
    mainPanelIcon: "Main Panel Image",
    refreshIntervalInstruction: "Refresh Interval",
    optionsText: "Options",
    symbolOptionsText: "Symbol Options",
    iconOptionsText: "Icon Options",
    sympolPopupTitle: "Set Symbol",
    rdoLayer: "Layer Symbol",
    rdoCustom: "Custom Symbol",
    chkCluster: "Enable Clustering",
    defineClusterSymbol: "Cluster Symbol",
    defineThemeClusterSymbol: "Cluster Symbol from Theme",
    rdoEsri: "Esri Symbol",
    rdoLayerIcon: "Use Symbol as Icon",
    rdoCustomIcon: "Upload Custom Icon",
    editCustomSymbol: "Edit Custom Symbol",
    editCustomIcon: "Edit Custom Icon",
    missingRefreshValue: "Please provide a refresh interval value.",
    panelIconOption: "Display Panel Header",
    enableRefresh: "Enable Layer Refresh",
    disableRefresh: "Layer Refresh Only Supported for Feature Collections",
    layer_type_not_supported: "Layer type is not supported: "
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0,
  "zh-hk": 0,
  "zh-tw": 0
});
