define({
  root: ({
    addLayer: "Add Layer",
    layerName: "Layer",
    layerRefresh: "Refresh",
    layerLabel: "Label",
    actions: "Actions",
    mainPanelTextPlaceholder: "ex: Last Updated:",
    invalidInterval: "Only numeric characters supported.",
    uploadImage: "Upload Image",
    iconColumnText: "Display",
    refreshInterval: "Time in Minutes",
    refreshIntervalTitle: "Evaluated as time in Minutes",
    mainPanelText: "Main Panel Text",
    mainPanelIcon: "Main Panel Image",
    refreshIntervalInstruction: "Refresh layers every:",
    optionsText: "Options",
    symbolOptionsText: "Map Symbology",
    iconOptionsText: "Panel Symbology",
    sympolPopupTitle: "Display Settings",
    rdoLayer: "Default Symbol",
    rdoCustom: "Use an Image",
    chkCluster: "Enable Clustering",
    defineClusterSymbol: "Specify Cluster Symbol",
    rdoEsri: "Pick a Symbol",
    rdoLayerIcon: "Use Map Symbol",
    rdoCustomIcon: "Use an Image",
    editCustomSymbol: "Edit Custom Symbol",
    editCustomIcon: "Edit Custom Icon",
    missingRefreshValue: "Please provide a refresh interval value.",
    panelIconOption: "Display Logo Image",
    enableRefresh: "Enable Layer Refresh",
    disableRefresh: "Layer Refresh Only Supported for Feature Collections",
    layer_type_not_supported: "Layer type is not supported: ",
    refreshUnit: "minutes.",
    symbolOptions: "Symbol",
    panelFeatureDisplay: "Panel",
    chkGroup: "Group Features",
    selectField: "Field",
    fieldLabel: "Label",
    addField: "Add Field",
    featureOptionsText: "Layer Options",
    groupOptionsText: "Group Options",
    panelCountOption: "Display Feature Counts",
    rdoStack: "Display New Line For Each Field",
    rdoAppend: "Append Fields On a Single Line",
    missingLayerInWebMap: "No operational layers found.",
    displayClusterCnt: "Display Feature Count",
    defineClusterFont: "Specify Font Color",
    max_records: "Maximum field limit reached"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
