define({
  "addTaskTip": "Lägg till ett eller flera filter i widgeten och ställ in parametrar för vart och ett.",
  "enableMapFilter": "Ta bort det förinställda lagerfiltret från kartan.",
  "newFilter": "Nytt filter",
  "filterExpression": "Filteruttryck",
  "layerDefaultSymbolTip": "Använd standardsymbolen för lagret",
  "uploadImage": "Överför en bild",
  "selectLayerTip": "Välj ett lager.",
  "setTitleTip": "Ange en titel.",
  "noTasksTip": "Inga filter har konfigurerats. Klicka på ${newFilter} om du vill lägga till ett nytt.",
  "collapseFiltersTip": "Dölj filteruttryck (om det finns några) när widgeten öppnas",
  "zoomtoTip": "Zooma till kvarvarande geoobjekt efter att filtret har använts",
  "groupByLayerTip": "Gruppera filter efter lager",
  "autoApplyWhenValueInput": "Tillämpa det här filtret automatiskt när ett värde har angetts",
  "autoApplyWhenWidgetOpen": "Tillämpa det här filtret när widgeten öppnas",
  "info": "Info",
  "expressions": "Uttryck",
  "allowCustom": "Tillåt att anpassade filter skapas",
  "filterActions": "Åtgärder för anpassade filter",
  "custom": "Aktivera anpassade filter",
  "resetAll": "Aktivera återställning av alla",
  "turnOffAll": "Aktivera avstängning av alla",
  "matchMsgSetAll": "Visa geoobjekt som matchar alla filter",
  "matchMsgSetAny": "Visa geoobjekt som matchar något filter"
});