define({
  "defaultAreaUnit": "Standaard oppervlakte-eenheid",
  "defaultLengthUnit": "Standaard lengte-eenheid",
  "acres": "Acres",
  "sqMiles": "Vierkante mijl",
  "sqKilometers": "Vierkante kilometer",
  "hectares": "Hectare",
  "sqYards": "Vierkante yard",
  "sqFeet": "Vierkante voet",
  "sqFeetUS": "Vierkante voet (US)",
  "sqMeters": "Vierkante meter",
  "miles": "Mijl",
  "kilometers": "Kilometer",
  "feet": "Voet",
  "feetUS": "Voet (US)",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Zeemijl",
  "showArea": "Regio",
  "showDistance": "Afstand",
  "showLocation": "Locatie",
  "showtools": "Toon meetgereedschappen:",
  "operationalLayer": "Voeg de tekening meten toe als een operationele laag van de kaart.",
  "allHidedTips": "Er moet minimaal één gereedschap worden geselecteerd."
});