define({
  "_widgetLabel": "Editor intel·ligent",
  "_featureAction_SmartEditor": "Editor intel·ligent",
  "noEditPrivileges": "El vostre compte no té permís per crear o modificar dades.",
  "widgetActive": "Activa",
  "widgetNotActive": "Inactiva",
  "pressStr": "Premeu ",
  "ctrlStr": " CTRL ",
  "snapStr": " per habilitar l'ajust",
  "noAvailableTempaltes": "No hi ha plantilles disponibles",
  "editorCache": " - Memòria cau de l'editor",
  "presetFieldAlias": "Camp",
  "presetValue": "Valor predefinit",
  "usePresetValues": " Utilitza valors predefinits (només noves entitats)",
  "editGeometry": " Edita la geometria",
  "savePromptTitle": "Desa l'entitat",
  "savePrompt": "Voleu desar l'entitat actual?",
  "deletePromptTitle": "Suprimeix l'entitat",
  "deletePrompt": "Segur que voleu suprimir l'entitat seleccionada?",
  "attachmentLoadingError": "Error en pujar fitxers adjunts",
  "attachmentSaveDeleteWarning": "Avís: els canvis realitzats als fitxers adjunts es desen automàticament",
  "autoSaveEdits": "Desa l'entitat nova automàticament",
  "addNewFeature": "Crea una entitat nova",
  "featureCreationFailedMsg": "No es pot crear un nou registre o entitat",
  "relatedItemTitle": "Taula o capa relacionada",
  "invalidRelationShipMsg": "Assegureu-vos que el camp de la clau principal: '${parentKeyField}' tingui un valor vàlid",
  "pendingFeatureSaveMsg": "Deseu les edicions de les entitats abans de crear una entitat relacionada.",
  "attachmentsRequiredMsg": "(*) Els fitxers adjunts són necessaris.",
  "coordinatePopupTitle": "Mou l'entitat a la ubicació XY",
  "coordinatesSelectTitle": "Sistema de coordenades:",
  "mapSpecialReferenceDropdownOption": "Referència espacial del mapa",
  "latLongDropdownOption": "Latitud/longitud",
  "xAttributeTextBoxLabel": "Coordenada X:",
  "yAttributeTextBoxLabel": "Coordenada Y:",
  "latitudeTextBoxLabel": "Latitud:",
  "longitudeTextBoxLabel": "Longitud:",
  "filterEditor": {
    "all": "Totes",
    "noAvailableTempaltes": "No hi ha plantilles disponibles",
    "searchTemplates": "Cerca plantilles"
  },
  "invalidConfiguration": "El widget no està configurat o les capes de la configuració ja no es troben al mapa. Obriu l'aplicació en el mode del builder i torneu a configurar el widget.",
  "geometryServiceURLNotFoundMSG": "No es pot obtenir l'adreça URL del servei de geometria",
  "clearSelection": "Esborra",
  "refreshAttributes": "Actualitza els atributs d'entitats",
  "automaticAttributeUpdatesOn": "Actualitza els atributs d'entitats automàticament: ON",
  "automaticAttributeUpdatesOff": "Actualitza els atributs d'entitats automàticament: OFF",
  "moveSelectedFeatureToGPS": "Mou l'entitat seleccionada a la ubicació GPS actual",
  "moveSelectedFeatureToXY": "Mou l'entitat seleccionada a la ubicació XY",
  "mapNavigationLocked": "Navegació pel mapa: bloquejada",
  "mapNavigationUnLocked": "Navegació pel mapa: desbloquejada"
});