define({
  "_widgetLabel": "Išmanusis redaktorius",
  "_featureAction_SmartEditor": "Išmanusis redaktorius",
  "noEditPrivileges": "Jūsų paskyra neturi teisės kurti arba modifikuoti duomenų.",
  "widgetActive": "Aktyvus",
  "widgetNotActive": "Neaktyvus",
  "pressStr": "Paspauskite ",
  "ctrlStr": " CTRL ",
  "snapStr": " pritraukimui įjungti",
  "noAvailableTempaltes": "Galimų šablonų nėra",
  "editorCache": " - Redagavimo podėlis",
  "presetFieldAlias": "Laukas",
  "presetValue": "Iš anksto nustatyta reikšmė",
  "usePresetValues": " Naudoti iš anksto nustatytas reikšmes (tik naujiems elementams)",
  "editGeometry": " Redaguoti geometriją",
  "savePromptTitle": "Įrašyti elementą",
  "savePrompt": "Ar norite išsaugoti šį elementą?",
  "deletePromptTitle": "Ištrinti elementą",
  "deletePrompt": "Ar tikrai norite ištrinti šį elementą?",
  "attachmentLoadingError": "Klaida įkeliant priedus",
  "attachmentSaveDeleteWarning": "Įspėjimas: priedų pakeitimai įrašomi automatiškai",
  "autoSaveEdits": "Automatiškai įrašo naują elementą",
  "addNewFeature": "Sukurti naują elementą",
  "featureCreationFailedMsg": "Negalima sukurti naujo įrašo / elemento",
  "relatedItemTitle": "Susijusi lentelė / sluoksnis",
  "invalidRelationShipMsg": "Įsitikinkite, kad pirminio rakto: '${parentKeyField}' reikšmė yra tinkama",
  "pendingFeatureSaveMsg": "Įrašykite pakeistus elementus prieš kurdami susijusį elementą.",
  "attachmentsRequiredMsg": "(*) Reikalingi priedai.",
  "coordinatePopupTitle": "Perkelti elementą į XY vietą",
  "coordinatesSelectTitle": "Koordinačių sistema:",
  "mapSpecialReferenceDropdownOption": "Žemėlapio koordinačių sistema",
  "latLongDropdownOption": "Platuma/Ilguma",
  "xAttributeTextBoxLabel": "X koordinatė:",
  "yAttributeTextBoxLabel": "Y koordinatė:",
  "latitudeTextBoxLabel": "Platuma:",
  "longitudeTextBoxLabel": "Ilguma:",
  "filterEditor": {
    "all": "Viskas",
    "noAvailableTempaltes": "Galimų šablonų nėra",
    "searchTemplates": "Ieškoti šablonų"
  },
  "invalidConfiguration": "Valdiklis nesukonfigūruotas arba konfigūracijos sluoksnių žemėlapyje nebėra. Atidarykite aplikaciją kūrimo režime ir iš naujo sukonfigūruokite valdiklį.",
  "geometryServiceURLNotFoundMSG": "Negalima gauti geometrijos paslaugos URL",
  "clearSelection": "Valyti",
  "refreshAttributes": "Atnaujinti elementų atributus",
  "automaticAttributeUpdatesOn": "Automatiškai atnaujinti elementų atributus: ĮJUNGTA",
  "automaticAttributeUpdatesOff": "Automatiškai atnaujinti elementų atributus: IŠJUNGTA",
  "moveSelectedFeatureToGPS": "Perkelti pasirinktą elementą į dabartinę GPS vietą",
  "moveSelectedFeatureToXY": "Perkelti pasirinktą elementą į XY vietą",
  "mapNavigationLocked": "Žemėlapio naršymas: užrakintas",
  "mapNavigationUnLocked": "Žemėlapio naršymas: atrakintas"
});