define({
  "_widgetLabel": "Traçado da Rede",
  "_featureAction_NetworkTraceSkip": "Ignorar no Traçado",
  "_featureAction_NetworkTraceUnskip": "Remover de locais para ignorar",
  "removedFromSkipLocations": "Removido de locais para ignorar",
  "alreadyRemovedFromSkipLocations": "Já removido de locais para ignorar",
  "locationSkipped": "Localizações ignoradas",
  "configError": "O widget não está configurado corretamente.",
  "geometryServiceURLNotFoundMSG": "Não foi possível obter URL do Serviço de Geometria",
  "clearButtonValue": "Apagar",
  "GPExecutionFailed": "O traçado não pode ser concluído. Tente novamente.",
  "backButtonValue": "Voltar",
  "exportToCSVSuccess": "A exportação para CSV foi concluída com sucesso.",
  "lblInputLocTab": "Locais de Entrada",
  "lblBlockLocTab": "Bloquear Localizações",
  "lblInputLocation": "Feição de Entrada",
  "lblBlockLocation": "Bloquear Feição",
  "lblInputLocHeader": "Localizações de Entrada (0)",
  "lblBlockLocHeader": "Bloquear Localizações (0)",
  "inputTabTitle": "Entrada",
  "outputTabTitle": "Saída",
  "exportSelectAllCheckBoxLabel": "Selecionar Tudo",
  "lblSkipLocHeader": "Pular Localizações (0)",
  "lblSkipLocation": "Localização",
  "lblSkipLocTab": "Pular Localizações",
  "skipAllLocationButtonLabel": "Pular Todas as Localizações",
  "confirmSkipAllLocationsMessage": "Todos os locais serão ignorados, você deseja continuar?",
  "locationAlreadySkippedMessage": "Localizações já puladas",
  "removeAllSkipLocationLabel": "Remover Tudo",
  "newProjectOptionText": "Novo Projeto",
  "selectProject": "Selecionar Projeto",
  "saveButtonLabel": "Salvar",
  "exportToCSVText": "Exportar para CSV",
  "editProjectAttributesToolTip": "Editar Atributos de Projeto",
  "projectNameLabel": "Nome do Projeto",
  "saveProjectPopupTitle": "Salvar",
  "saveAsLabel": "Salvar Como",
  "saveChangesMsg": "Deseja salvar suas alterações para <b>${loadProjectDropdownlabel}</b> ou salvar como novo projeto?",
  "creatingNewProjectErrorMessage": "Erro ao criar novo projeto. Tente novamente.",
  "projectNameFetchingErr": "Erro ao buscar nomes de projetos existentes. Tente novamente.",
  "projectAttributeLoadingErr": "Erro ao carregar atributos de projeto. Tente novamente.",
  "attributeUpdatedMsg": "Atributos atualizados com sucesso.",
  "projectAttributeUpdatingErr": "Erro ao atualizar atributos do projeto.",
  "loadingProjectDetailsErrorMessage": "Erro ao buscar bandeiras, barreiras e pulam localizações. Tente novamente.",
  "savingProjectDetailsErr": "Erro ao salvar detalhes do projeto. Tente salvar o projeto novamente.",
  "updatingOutagePolygonErr": "Erro ao atualizar polígono de interrupção. Tente salvar o projeto novamente.",
  "deletingExistingPolygonErr": "Erro ao excluir polígono de interrupção existente. Tente salvar o projeto novamente.",
  "loadingProjectFeaturesErr": "Erro ao carregar feições do projeto. Tente carregar o projeto novamente.",
  "addingProjectFeaturesErr": "Erro ao adicionar feições do projeto. Tente salvar o projeto novamente.",
  "deletingExistingProjectFeaturesErr": "Erro ao excluir feições de projeto existente. Tente salvar o projeto novamente.",
  "projectNotFoundErr": "Projeto não localizado",
  "projectLayersNotFound": "As camadas de configurações do Projeto configurado não estão disponíveis no mapa. Widget será carregado no 'modo de Esboço'.",
  "fetchingOutagePolygonMessage": "Erro ao buscar polígono de interrupção. Tente carregar o projeto novamente.",
  "projectNameExistsMessage": "Nome do projeto já existe. Utilize um nome do projeto único.",
  "fetchingProjectNamesErrorMessage": "Erro ao buscar nomes de projetos existentes. Tente salvar o projeto novamente.",
  "enterProjectNameMessage": "Insira um nome do projeto.",
  "projectLengthErrorMessage": "O nome do projeto não pode ser maior que",
  "gpServiceNotAccessible": "Sua conta não tem acesso para o serviço exigido para executar este traçado.",
  "loadingClonedLayerErrorMessage": "Erro ao carregar a camada de feição clonada. Tente novamente.",
  "addingFeatureInClonedLayerError": "Erro ao adicionar os gráficos na camada de feição clonada. Tente novamente.",
  "selectingFeatureInClonedLayerError": "Erro ao selecionar os gráficos na camada de feição clonada. Tente novamente.",
  "filteredProjectError": "Erro ao verificar a busca dos detalhes de projeto filtrados. Tente novamente.",
  "filteredProjectMessage": "Os atributos de projeto selecionados não estão disponíveis devido aos filtros aplicados a partir do mapa da web ou outro widget. Limpe o filtro e tente novamente.",
  "filteredProjectLoadMessage": "Seu projeto não está mais disponível. Selecione um projeto ativo.",
  "defaultValueForRunButton": "Executar",
  "closeButtonLabel": "Remover"
});