define({
  "_widgetLabel": "네트워크 추적",
  "_featureAction_NetworkTraceSkip": "추적에서 건너뛰기",
  "_featureAction_NetworkTraceUnskip": "건너뛰기 위치에서 제거",
  "removedFromSkipLocations": "건너뛰기 위치에서 제거됨",
  "alreadyRemovedFromSkipLocations": "건너뛰기 위치에서 이미 제거됨",
  "locationSkipped": "위치를 건너뛰었음",
  "configError": "위젯이 올바르게 구성되지 않았습니다.",
  "geometryServiceURLNotFoundMSG": "지오메트리 서비스 URL을 가져올 수 없음",
  "clearButtonValue": "지우기",
  "GPExecutionFailed": "추적을 완료할 수 없습니다. 다시 시도하세요.",
  "backButtonValue": "뒤로",
  "exportToCSVSuccess": "CSV로 내보내기가 정상적으로 완료되었습니다.",
  "lblInputLocTab": "입력 위치",
  "lblBlockLocTab": "블록 위치",
  "lblInputLocation": "입력 피처",
  "lblBlockLocation": "블록 피처",
  "lblInputLocHeader": "입력 위치(0)",
  "lblBlockLocHeader": "블록 위치(0)",
  "inputTabTitle": "입력",
  "outputTabTitle": "출력",
  "exportSelectAllCheckBoxLabel": "모두 선택",
  "lblSkipLocHeader": "건너뛰기 위치(0)",
  "lblSkipLocation": "위치",
  "lblSkipLocTab": "위치 건너뛰기",
  "skipAllLocationButtonLabel": "모든 위치 건너뛰기",
  "confirmSkipAllLocationsMessage": "모든 위치를 건너뜁니다. 계속하시겠습니까?",
  "locationAlreadySkippedMessage": "위치를 이미 건너뛰었음",
  "removeAllSkipLocationLabel": "모두 제거",
  "newProjectOptionText": "새 프로젝트",
  "selectProject": "프로젝트 선택",
  "saveButtonLabel": "저장",
  "exportToCSVText": "CSV로 내보내기",
  "editProjectAttributesToolTip": "프로젝트 속성 편집",
  "projectNameLabel": "프로젝트 이름",
  "saveProjectPopupTitle": "저장",
  "saveAsLabel": "다른 이름으로 저장",
  "saveChangesMsg": "변경 내용을 <b>${loadProjectDropdownlabel}</b>에 저장하거나 새 프로젝트로 저장하시겠습니까?",
  "creatingNewProjectErrorMessage": "새 프로젝트 생성 중 오류가 발생했습니다. 다시 시도하세요.",
  "projectNameFetchingErr": "기존 프로젝트 이름을 가져오는 중 오류가 발생했습니다. 다시 시도하세요.",
  "projectAttributeLoadingErr": "프로젝트 속성을 불러오는 중 오류가 발생했습니다. 다시 시도하세요.",
  "attributeUpdatedMsg": "속성이 정상적으로 업데이트되었습니다.",
  "projectAttributeUpdatingErr": "프로젝트 속성을 업데이트하는 중 오류가 발생했습니다.",
  "loadingProjectDetailsErrorMessage": "플래그, 장애물, 건너뛰기 위치를 가져오는 중 오류가 발생했습니다. 다시 시도하세요.",
  "savingProjectDetailsErr": "프로젝트 세부정보를 저장하는 중 오류가 발생했습니다. 프로젝트를 다시 저장해 보세요.",
  "updatingOutagePolygonErr": "정전 폴리곤을 업데이트하는 중 오류가 발생했습니다. 프로젝트를 다시 저장해 보세요.",
  "deletingExistingPolygonErr": "기존의 정전 폴리곤을 삭제하는 중 오류가 발생했습니다. 프로젝트를 다시 저장해 보세요.",
  "loadingProjectFeaturesErr": "프로젝트 피처를 불러오는 중 오류가 발생했습니다. 프로젝트를 다시 불러와 보세요.",
  "addingProjectFeaturesErr": "프로젝트 피처를 추가하는 중 오류가 발생했습니다. 프로젝트를 다시 저장해 보세요.",
  "deletingExistingProjectFeaturesErr": "기존의 프로젝트 피처를 삭제하는 중 오류가 발생했습니다. 프로젝트를 다시 저장해 보세요.",
  "projectNotFoundErr": "프로젝트 없음",
  "projectLayersNotFound": "구성된 프로젝트 설정 레이어가 맵에서 제공되지 않습니다. 위젯을 '스케치 모드'로 불러옵니다.",
  "fetchingOutagePolygonMessage": "정전 폴리곤을 가져오는 중 오류가 발생했습니다. 프로젝트를 다시 불러와 보세요.",
  "projectNameExistsMessage": "프로젝트 이름이 이미 있습니다. 고유한 프로젝트 이름을 사용하세요.",
  "fetchingProjectNamesErrorMessage": "기존 프로젝트 이름을 가져오는 중 오류가 발생했습니다. 프로젝트를 다시 저장해 보세요.",
  "enterProjectNameMessage": "프로젝트 이름을 입력하세요.",
  "projectLengthErrorMessage": "프로젝트 이름은 다음 길이보다 짧아야 합니다.",
  "gpServiceNotAccessible": "사용자의 계정에는 이 추적을 수행할 필수 서비스에 대한 접근 권한이 없습니다.",
  "loadingClonedLayerErrorMessage": "복제된 피처 레이어를 불러오는 중 오류가 발생했습니다. 다시 시도하세요.",
  "addingFeatureInClonedLayerError": "복제된 피처 레이어에 그래픽을 추가하는 중 오류가 발생했습니다. 다시 시도하세요.",
  "selectingFeatureInClonedLayerError": "복제된 피처 레이어의 그래픽을 선택하는 중 오류가 발생했습니다. 다시 시도하세요.",
  "filteredProjectError": "필터링된 프로젝트 세부정보 가져오기를 확인하는 중 오류가 발생했습니다. 다시 시도하세요.",
  "filteredProjectMessage": "선택한 프로젝트 속성은 웹맵 또는 다른 위젯에서 적용된 필터로 인해 사용할 수 없습니다. 필터를 해제하고 다시 시도하세요.",
  "filteredProjectLoadMessage": "프로젝트를 더 이상 사용할 수 없습니다. 활성 프로젝트를 선택하세요.",
  "defaultValueForRunButton": "실행",
  "closeButtonLabel": "제거"
});