define({
  "_widgetLabel": "Малювання",
  "selectDrawMode": "Вибрати режим малювання",
  "clear": "Очистити",
  "point": "Точка",
  "line": "Лінія",
  "polyline": "Полілінія",
  "freehandPolyline": "Довільна полілінія",
  "triangle": "Трикутник",
  "extent": "Конверт",
  "circle": "Коло",
  "ellipse": "Еліпс",
  "polygon": "Полігон",
  "freehandPolygon": "Довільний полігон",
  "text": "Текст",
  "style": "Стиль",
  "alpha": "Прозорість",
  "width": "Ширина",
  "size": "Розмір",
  "color": "Колір",
  "markerColor": "Колір маркеру",
  "outlineColor": "Колір контуру",
  "lineColor": "Колір лінії",
  "fillColor": "Колір заливки",
  "showMeasurements": "Показати вимірювання",
  "showLocationMeasurement": "Показати вимірювання місця розташування",
  "showAreaMeasurement": "Показати вимірювання площі",
  "showDistanceMeasurement": "Показати вимірювання відстані",
  "showDistanceMeasurementForLine": "Показати вимірювання довжини",
  "showDistanceMeasurementForPolygon": "Показати вимірювання периметра",
  "locationToggleOn": "Натисніть кнопку-перемикач, щоб показати вимірювання місця розташування",
  "locationToggleOff": "Натисніть кнопку-перемикач, щоб приховати вимірювання місця розташування",
  "areaToggleOn": "Натисніть кнопку-перемикач, щоб показати вимірювання областей",
  "areaToggleOff": "Натисніть кнопку-перемикач, щоб приховати вимірювання областей",
  "distanceForLineToggleOn": "Натисніть кнопку-перемикач, щоб показати вимірювання довжини",
  "distanceForLineToggleOff": "Натисніть кнопку-перемикач, щоб приховати вимірювання довжини",
  "distanceForPolygonToggleOn": "Натисніть кнопку-перемикач, щоб показати вимірювання периметру",
  "distanceForPolygonToggleOff": "Натисніть кнопку-перемикач, щоб приховати вимірювання периметру",
  "areaUnits": "Одиниці площі",
  "distanceUnits": "Одиниці відстані",
  "kilometers": "Кілометри",
  "miles": "Милі",
  "meters": "Метри",
  "feet": "Фути",
  "yards": "Ярди",
  "nauticalmiles": "Морські милі",
  "squareKilometers": "Квадратні кілометри",
  "squareMiles": "Квадратні милі",
  "acres": "Акри",
  "hectares": "Гектари",
  "squareMeters": "Квадратні метри",
  "squareFeet": "Квадратні фути",
  "squareYards": "Квадратні ярди",
  "undo": "Відмінити",
  "redo": "Повторити",
  "results": "Результати",
  "points": "Точки",
  "lines": "Лінії",
  "areas": "Області",
  "locationLabel": "Місце розташування: ${value}",
  "areaLabel": "Площа: ${value} ${unit}",
  "distanceLabel": "Відстань: ${value} ${unit}",
  "distanceLabelForLine": "Довжина: ${value} ${unit}",
  "distanceLabelForPolygon": "Периметр: ${value} ${unit}"
});