define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Додайте точку, клацнувши по карті",
  "addRingsDtWt": "Додати кільця, час подорожування автомобілем або пішки.",
  "apply": "Застосувати",
  "back": "Позаду",
  "colon": ":",
  "creditInformation": "Інформація про кредити",
  "driveTime": "Час подорожування автомобілем",
  "esriInfographics": "Інфографіка Esri",
  "esriReports": "Звіти Esri",
  "headerDescription_km": "кілометр",
  "headerDescription_miles": "миля",
  "headerDescription_minutes": "хвилина",
  "infographics": "Інфографіка",
  "invalidValueRing": "Значення повинні бути в діапазоні від 0 до 1 000.",
  "invalidValueDTWT": "Значення повинні бути в діапазоні від 0 до 300.",
  "km": "км",
  "miles": "миль",
  "minutes": "хвилин",
  "myInfographics": "Моя інфографіка",
  "myReports": "Мої звіти",
  "noPermissions": "Ваш обліковий запис не може використовувати віджет Business Analyst. Для використання віджету Business Analyst адміністратору вашої організації потрібно надати вам <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">права</a> на геозбагачення та мережевий аналіз, а також виділити <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">кредити</a>.",
  "radii": "радіус",
  "radius": "Радіус",
  "radius_lowercase": "радіус",
  "reports": "Звіти",
  "ring": "Кільце",
  "rings": "Кільця",
  "runInfographic": "Запустити інфографіку",
  "runReport": "Запустити звіт",
  "selectPointOrPolygon": "Виберіть на карті точковий або полігональний об'єкт, виконайте пошук адреси або місця, або встановіть на карті шпильку для перегляду додаткової інформації щодо областей.",
  "selectReport": "Вибрати звіт",
  "selectTemplate": "Вибрати шаблон",
  "sharedInfographics": "Спільна інфографіка",
  "sharedReports": "Спільні звіти",
  "thisEntryIsNotValid": "Цей запис недійсний.",
  "time": "Час",
  "walkTime": "Час подорожування пішки",
  "widgetDescription": "Доступ до інфографіки та звітів, що зводять ключові індикаторі та дані для будь-якої області.",
  "None": "Вибрати..."
});