define({
  "_widgetLabel": "Pametni uređivač",
  "_featureAction_SmartEditor": "Pametni uređivač",
  "noEditPrivileges": "Vaš nalog nema dozvolu za kreiranje ili izmenu podataka.",
  "widgetActive": "Aktivno",
  "widgetNotActive": "Nije aktivno",
  "pressStr": "Pritisnite ",
  "ctrlStr": " CTRL ",
  "snapStr": " da biste omogućili snapovanje",
  "noAvailableTempaltes": "Nema dostupnih šablona",
  "editorCache": " - Keš uređivača",
  "presetFieldAlias": "Polje",
  "presetValue": "Unapred postavljena vrednost",
  "usePresetValues": " Koristi unapred postavljene vrednosti (samo za nove geoobjekte)",
  "editGeometry": " Uredi geometriju",
  "savePromptTitle": "Sačuvaj geoobjekat",
  "savePrompt": "Želite li da sačuvate trenutni geoobjekat?",
  "deletePromptTitle": "Obriši geoobjekat",
  "deleteAttachment": "Obriši prilog",
  "deletePrompt": "Želite li zaista da obrišete izabrani geoobjekat?",
  "attachmentLoadingError": "Greška pri otpremanju priloga",
  "attachmentSaveDeleteWarning": "Upozorenje: izmene na prilozima se automatski čuvaju",
  "autoSaveEdits": "Automatski čuva nove geoobjekte",
  "addNewFeature": "Kreiraj novi geoobjekat",
  "featureCreationFailedMsg": "Kreiranje novog zapisa/geoobjekta nije moguće",
  "relatedItemTitle": "Povezana tabela/sloj",
  "relatedFeatureCount": "${layerTitle} sa ${featureCount} geoobjekata",
  "createNewFeatureLabel": "Kreiraj novi geoobjekat za ${layerTitle}",
  "invalidRelationShipMsg": "Vodite računa da primarno ključno polje: '${parentKeyField}' ima važeću vrednost",
  "pendingFeatureSaveMsg": "Sačuvajte izmene geoobjekta pre kreiranja povezanog geoobjekta.",
  "attachmentsRequiredMsg": "(*) Prilozi su obavezni.",
  "coordinatePopupTitle": "Pomeri geoobjekat na XY lokaciju",
  "coordinatesSelectTitle": "Koordinatni sistem:",
  "mapSpecialReferenceDropdownOption": "Prostorna referenca mape",
  "latLongDropdownOption": "Geografska širina/dužina",
  "xAttributeTextBoxLabel": "X koordinata:",
  "yAttributeTextBoxLabel": "Y koordinata:",
  "latitudeTextBoxLabel": "Geografska širina:",
  "longitudeTextBoxLabel": "Geografska dužina:",
  "presetGroupFieldsLabel": "Biće primenjeno '${groupName}’ na sledeća polja sloja:",
  "presetGroupNoFieldsLabel": "'${groupName}’ nema nikakvih povezanih polja",
  "groupInfoLabel": "Informacije grupe za '${groupName}’",
  "editGroupInfoIcon": "Uredi vrednost grupe za '${groupName}’",
  "filterEditor": {
    "all": "Sve",
    "noAvailableTempaltes": "Nema dostupnih šablona",
    "searchTemplates": "Pretraži šablone",
    "filterLayerLabel": "Filtriraj slojeve"
  },
  "invalidConfiguration": "Vidžet nije konfigurisan ili slojevi u konfiguraciji više nisu na mapi. Otvorite aplikaciju u graditeljskom režimu i ponovo konfigurišite vidžet.",
  "geometryServiceURLNotFoundMSG": "Dobijanje URL servisa geometrije nije moguće",
  "clearSelection": "Obriši",
  "refreshAttributes": "Ažuriranje atributa geoobjekta",
  "automaticAttributeUpdatesOn": "Automatsko ažuriranje atributa geoobjekta: UKLJUČENO",
  "automaticAttributeUpdatesOff": "Automatsko ažuriranje atributa geoobjekta: ISKLJUČENO",
  "moveSelectedFeatureToGPS": "Pomeri izabrane geoobjekte na trenutnu GPS lokaciju",
  "moveSelectedFeatureToXY": "Pomeri izabrani geoobjekat na XY lokaciju",
  "mapNavigationLocked": "Navigacija mape: zaključano",
  "mapNavigationUnLocked": "Navigacija mape: otključano",
  "copyFeatures": {
    "title": "Kopiraj geoobjekte",
    "createFeatures": "Kreiraj geoobjekte",
    "createSingleFeature": "Kreiraj 1 geoobjekat višedelne geometrije",
    "noFeaturesSelectedMessage": "Nijedan geoobjekat nije izabran",
    "selectFeatureToCopyMessage": "Izaberite geoobjekte za kopiranje.",
    "multipleFeatureSaveWarning": "Napomena: kreiranje više geoobjekata korišćenjem funkcije kopiranja će odmah sačuvati sve geoobjekte"
  },
  "addingFeatureError": "Greška prilikom dodavanja selektovanih geoobjekata u sloj. Pokušajte ponovo.",
  "addingFeatureErrorCount": "Kopiranje '${copyFeatureErrorCount}' geoobjekata nije uspelo.",
  "selectingFeatureError": "Greška prilikom selektovanja geoobjekata u sloju. Pokušajte ponovo.",
  "customSelectOptionLabel": "Izaberite geoobjekte za kopiranje",
  "noFeatureSelectedMessage": "Nijedan geoobjekat nije izabran.",
  "multipleFeatureSaveMessage": "Svi geoobjekti će odmah biti sačuvani. Želite li da nastavite?",
  "relativeDates": {
    "dateTypeLabel": "Tip datuma",
    "valueLabel": "Vrednost",
    "fixed": "Nepromenljivo",
    "current": "Trenutno",
    "past": "Prošli",
    "future": "Budući",
    "popupTitle": "Selektovana vrednost",
    "hintForFixedDateType": "Savet: navedeni datum i vreme će biti korišćeni kao unapred podešena podrazumevana vrednost",
    "hintForCurrentDateType": "Savet: trenutni datum i vreme će biti korišćeni kao unapred podešena podrazumevana vrednost",
    "hintForPastDateType": "Savet: navedena vrednost će biti oduzeta od trenutnog datuma i vremena za unapred podešene podrazumevane vrednosti.",
    "hintForFutureDateType": "Savet: navedena vrednost će biti dodata trenutnom datumu i vremenu za unapred podešene podrazumevane vrednosti.",
    "noDateDefinedTooltip": "Nema definisanog datuma"
  }
});