define({
  "taskUrl": "Feladat URL-címe",
  "serviceURLPlaceholder": "Adja meg a téradatelemzési feladat URL-címét",
  "layerOrder": "Rétegsorrend",
  "defaultValue": "Alapértelmezett érték",
  "inputFeatureBy": "Vektoros elem beviteli szempontja",
  "inputRecordBy": "Rekord beviteli szempontja",
  "renderer": "Renderelés",
  "displayType": "Megjelenítő típusa",
  "helpUrl": "Súgó URL",
  "useResultMapService": "Eredmény megjelenítése térképi adatszolgáltatással",
  "drawOnMap": "Interaktív rajzolás a térképen",
  "selectLayer": "Réteg kiválasztása a térképről",
  "selectTable": "Tábla kiválasztása a térképről",
  "shareResults": "Eredményt hozzáadása operatív rétegként",
  "setTask": "Beállítás",
  "setTaskTitle": "GP feladat beállítása",
  "enablePopup": "Felugró ablak engedélyezése",
  "unSupportGeometryType": "A renderelés ismeretlen geometriatípus miatt nem állítható be.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Fájl feltöltése",
  "selectFileToUpload": "Válasszon fájlt...",
  "rasterFormat": "Raszteres adatformátum",
  "noFileSelected": "Nincs fájl kijelölve!",
  "uploadSuccess": "Sikeresen feltöltve!",
  "showLayerContent": "Réteg tartalmának megjelenítése",
  "urlPlaceholder": "Az adatokhoz való hozzáférésre szolgáló URL",
  "useShapefile": "Helyi fájlrendszerben lévő shapefile használata",
  "allowToExport": "Eredmények exportálásának engedélyezése",
  "useDynamicSchema": "A kimenet sémája eltérő lehet. Az előre definiált helyett használjon dinamikus sémát.",
  "useCurrentMapExtent": "Aktuális térképkiterjedés használata",
  "ignoreOutput": "Hagyja figyelmen kívül ezt a kimenetet",
  "turnOffOutput": "Alapértelmezés szerint kapcsolja ki ezt a réteget",
  "inputJSONString": "Bemeneti JSON-karakterlánc"
});