define({
  "settings": "Innstillinger",
  "titleSettings": "Tekstinnstillinger",
  "imageSettings": "Bildeinnstillinger",
  "backgroundColor": "Bakgrunnsfarge",
  "alignment": "Justering",
  "textSize": "Tekststørrelse",
  "textColor": "Tekstfarge",
  "dataSource": "Datakilde",
  "chartSettings": "Diagraminnstillinger",
  "data": "Data",
  "dataLabels": "Dataetikketter",
  "displayMode": "Visningsmodus",
  "featureOption": "Vis verdier geoobjekt for geoobjekt",
  "categoryOption": "Vis verdier etter kategori",
  "countOption": "Vis antall geoobjekter etter kategori",
  "fieldOption": "Vis attributtverdier som diagrammer",
  "categoryField": "Kategorifelt",
  "labelField": "Påskriftfelt",
  "valueFields": "Verdifelter",
  "operation": "Operasjon",
  "sumOption": "Summer",
  "averageOption": "Gjennomsnitt",
  "minOption": "Minimum",
  "maxOption": "Maksimum",
  "dataFormat": "Datoformat",
  "decimalPlaces": "Desimaler",
  "prefix": "Prefiks",
  "suffix": "Suffiks",
  "dataType": "Datatype",
  "featureCount": "Geoobjektantall",
  "fieldStatistics": "Feltstatistikk",
  "display": "Vis",
  "chartColor": "Diagramfarge",
  "horizontalAxis": "Horisontal akse",
  "verticalAxis": "Vertikal akse",
  "legend": "Tegnforklaring",
  "position": "Posisjon",
  "top": "Topp",
  "bottom": "Bunn",
  "useDataSourceSelection": "Bruk utvalg",
  "dataSourceFilterByExtent": "Filtrer etter utstrekning",
  "changeTemplate": "Endre mal",
  "numberSettings": "Tallinnstillinger",
  "gaugeSettings": "Målerinnstillinger",
  "indicators": "Indikatorer",
  "ifValue": "Verdien Hvis",
  "and": "og",
  "numberOperatorIsLessThan": "er mindre enn",
  "numberOperatorIsGreaterThan": "er større enn",
  "numberOperatorIsBetween": "er mellom",
  "numberOperatorIsEqual": "er lik",
  "numberOperatorIsNotEqual": "er ikke lik",
  "then": "Så",
  "ratio": "Forhold",
  "trueValue": "Verdien Sann",
  "changeValueColor": "endre verdifarge til",
  "changeGaugeColor": "endre målerfarge til",
  "setIndicatorIcon": "angi indikatorikon som",
  "icons": "Ikoner",
  "style": "Stil",
  "placement": "Plassering",
  "left": "Venstre",
  "replace": "Erstatt",
  "right": "Høyre",
  "color": "Farge",
  "sortBy": "Sorter etter",
  "labelAxis": "Etikett",
  "valueAxis": "Verdi",
  "minPeriod": "Minimumsperiode",
  "automatic": "Automatisk",
  "periodsWithOutRecords": "Perioder uten poster",
  "nullValue": "Null verdi",
  "calculatedAsZero": "Beregnet som null",
  "ignored": "Ignorert",
  "maxCategories": "Maksimalt antall kategorier",
  "useLayerSymbology": "Bruk lagens symboler",
  "dataRange": "Dataområde",
  "targetValue": "Målverdi",
  "currentValue": "Gjeldende verdi",
  "gaugeColor": "Målerfarge",
  "min": "Minimum",
  "max": "Maksimum",
  "displayValueIn": "Vis verdi i",
  "noData": "Ingen data",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Advarsel",
  "noSettingWaring1": "Klikk på et element for å angi egenskaper for elementet.",
  "noSettingWaring2": "Dra for å endre størrelsen eller rekkefølgen for et element.",
  "donNotShowAgain": "Ikke vis igjen",
  "changeTemplateWarning": "Dette fjerner alle innstillinger og åpner en ny tom mal.",
  "requiredFieldWarning": "Denne verdien er obligatorisk:",
  "dataSourceNotSet": "Angi datakilde.",
  "addIndicatorTip": "Legg til en indikator",
  "chooseTemplatePopupTitle": "Velg en mal",
  "stringsInTemplate": {
    "name_number": "Tall",
    "name_gauge": "Måler",
    "name_vertical_gauge": "Vertikal måler",
    "name_horizontal_gauge": "Horisontal måler",
    "name_pie_chart": "Sektordiagram",
    "name_column_chart": "Kolonnediagram",
    "name_bar_chart": "Stolpediagram",
    "name_line_chart": "Linjediagram",
    "titleOfTheInfographic": "TITTEL PÅ INFOGRAFIKK",
    "description": "Beskrivelse: tilleggsinformasjon om denne infografikken."
  }
});