define({
  "settings": "Setări",
  "titleSettings": "Setările de text",
  "imageSettings": "Setări imagine",
  "backgroundColor": "Culoare de fundal",
  "alignment": "Aliniere",
  "textSize": "Dimensiune text",
  "textColor": "Culoare text",
  "dataSource": "Sursă de date",
  "chartSettings": "Setări diagramă",
  "data": "Date",
  "dataLabels": "Etichete date",
  "displayMode": "Mod afişaj",
  "featureOption": "Afişare valori pentru fiecare obiecte spaţial",
  "categoryOption": "Afişare valori pe categorii",
  "countOption": "Afişare număr de obiecte spaţiale pe categorii",
  "fieldOption": "Afişare valori de atribute sub formă de diagramă",
  "categoryField": "Câmp pentru categorie",
  "labelField": "Câmp etichetă",
  "valueFields": "Câmp valoare",
  "operation": "Operaţie",
  "sumOption": "Sumă",
  "averageOption": "Medie",
  "minOption": "Minim",
  "maxOption": "Maxim",
  "dataFormat": "Format date",
  "decimalPlaces": "Zecimale",
  "prefix": "Prefix",
  "suffix": "Sufix",
  "dataType": "Tip de date",
  "featureCount": "Număr obiecte spaţiale",
  "fieldStatistics": "Statistici câmp",
  "display": "Afişare",
  "chartColor": "Culoare diagramă",
  "horizontalAxis": "Axă orizontală",
  "verticalAxis": "Axă verticală",
  "legend": "Legendă",
  "position": "Poziţie",
  "top": "Sus",
  "bottom": "Jos",
  "useDataSourceSelection": "Utilizare selecţie",
  "dataSourceFilterByExtent": "Filtrare după extindere",
  "changeTemplate": "Modificare şablon",
  "numberSettings": "Setări număr",
  "gaugeSettings": "Setări instrument de măsură",
  "indicators": "Indicatoare",
  "ifValue": "Dacă valoarea",
  "and": "şi",
  "numberOperatorIsLessThan": "este mai mică decât",
  "numberOperatorIsGreaterThan": "este mai mare de",
  "numberOperatorIsBetween": "este între",
  "numberOperatorIsEqual": "este egal cu",
  "numberOperatorIsNotEqual": "este diferit de",
  "then": "Atunci",
  "ratio": "Raport",
  "trueValue": "Valoare adevărată",
  "changeValueColor": "modificare culoare valoare la",
  "changeGaugeColor": "modificare culoare instrument de măsură la",
  "setIndicatorIcon": "setare pictogramă indicator ca",
  "icons": "Pictograme",
  "style": "Stil",
  "placement": "Amplasare",
  "left": "Stânga",
  "replace": "Înlocuire",
  "right": "Dreapta",
  "color": "Culoare",
  "dataRange": "Interval date",
  "targetValue": "Valoare ţintă",
  "currentValue": "Valoare curentă",
  "gaugeColor": "Culoare instrument de măsură",
  "min": "Minim",
  "max": "Maxim",
  "displayValueIn": "Afişare valoare în",
  "noData": "Nu există date",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Avertisment",
  "noSettingWaring1": "Faceţi clic pe un element pentru a-i seta proprietăţile.",
  "noSettingWaring2": "Trageţi pentru a redimensiona sau reordona un element.",
  "donNotShowAgain": "Nu se mai afişează",
  "changeTemplateWarning": "Aceasta vă va şterge toate setările şi va deschide un şablon nou, gol.",
  "requiredFieldWarning": "Această valoare este obligatorie:",
  "dataSourceNotSet": "Setaţi sursa datelor.",
  "addIndicatorTip": "Adăugaţi un indicator",
  "chooseTemplatePopupTitle": "Alegeţi un şablon",
  "stringsInTemplate": {
    "name_number": "Număr",
    "name_gauge": "Instrument de măsură",
    "name_vertical_gauge": "Instrument de măsurare vertical",
    "name_horizontal_gauge": "Instrument de măsurare orizontal",
    "name_pie_chart": "Diagramă circulară",
    "name_column_chart": "Diagramă coloane",
    "name_bar_chart": "Diagramă cu bare",
    "name_line_chart": "Diagramă linii",
    "titleOfTheInfographic": "TITLUL GRAFICULUI INFORMATIV",
    "description": "Descriere: informaţii suplimentare despre acest grafic informativ."
  }
});