define({
  "_widgetLabel": "Visibilité",
  "observerLocation": "Position d’observation",
  "formatIconTooltip": "Format d'entrée",
  "addPointToolTip": "Ajouter un point d’observation",
  "fieldOfView": "Champ de vision",
  "useMilsText": "Utiliser des valeurs en mils pour les angles",
  "observerHeight": "Hauteur de l’observateur",
  "minObsDistance": "Distance observable minimale",
  "maxObsDistance": "Distance observable maximale",
  "taskURLError": "Le fichier de configuration du widget contient une URL inaccessible. Consulter l’administrateur système",
  "taskURLInvalid": "La tâche de géotraitement configurée avec ce widget n’est pas valide. Consulter l’administrateur système",
  "viewshedError": "Une erreur est survenue lors de la création de la visibilité. Vérifiez que la position d’observation se trouve dans l’étendue de votre surface d’altitude.</p>",
  "validationError": "<p>Des paramètres sont manquants ou non valides dans le formulaire de création de la visibilité. Vérifiez que :</p><ul><li>Une position d’observation a été définie.</li><li>Le champ de visibilité de l’observateur n’est pas égal à 0.</li><li>Le champ de hauteur de l’observateur contient une valeur valide.</li><li>Les champs des distances observables minimale et maximale contiennent des valeurs valides.</li></ul>",
  "comfirmInputNotation": "Confirmer la notation entrée",
  "notationsMatch": "notations correspondent à votre entrée. Confirmez celle que vous souhaitez utiliser :",
  "createBtn": "Créer",
  "clearBtn": "Effacer",
  "setCoordFormat": "Définir une chaîne de format des coordonnées",
  "prefixNumbers": "Ajouter le préfixe '+/-' aux nombres positifs et négatifs",
  "parseCoordinatesError": "Impossible d'analyser les coordonnées. Vérifiez votre entrée.",
  "cancelBtn": "Annuler",
  "applyBtn": "Appliquer",
  "invalidMessage": "Entrez une valeur numérique.",
  "observerRangeMessage": "Hauteur du point d’observation non valide",
  "minimumRangeMessage": "Plage observable minimale non valide",
  "maximumRangeMessage": "La plage observable maximale doit être supérieure à la plage observable minimale et ne doit pas dépasser ${limit} ${units}.",
  "portalURLError": "L’URL de votre organisation ArcGIS Online ou Portal for ArcGIS n’est pas configurée. Contactez votre administrateur système.",
  "privilegeError": "Votre rôle d’utilisateur ne peut pas réaliser d’analyse. Pour effectuer une analyse, l’administrateur de votre organisation doit vous accorder certains <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilèges</a>.",
  "noServiceError": "Le service d’analyse d’altitude n’est pas disponible. Vérifiez les configurations de votre organisation ArcGIS Online ou Portal for ArcGIS.",
  "pointToolTooltip": "Cliquez pour ajouter un point d’observation",
  "degreesLabel": "degrés",
  "milsLabel": "mils",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Degrés décimaux - Latitude/Longitude",
  "DDLongLatNotation": "Degrés décimaux - Longitude/Latitude",
  "DDMLatLongNotation": "Degrés minutes décimales - Latitude/Longitude",
  "DDMLongLatNotation": "Degrés minutes décimales - Longitude/Latitude",
  "DMSLatLongNotation": "Degrés minutes secondes - Latitude/Longitude",
  "DMSLongLatNotation": "Degrés minutes secondes - Longitude/Latitude",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Lettre du canal",
  "UTMHemNotation": "UTM - Hémisphère (N/S)",
  "mainPageTitle": "Ligne de visée radiale",
  "resultsTitle": "Résultats",
  "publishBtnLabel": "Publier",
  "layerName": "Nom de la couche publiée",
  "invalidLayerName": "Le nom de la couche ne doit contenir que des caractères alphanumériques et des tirets du bas",
  "missingLayerName": "Entrer le nom de la couche",
  "back": "Précédent",
  "publishingFailedLayerExists": "Échec de la publication : un service d’entités nommé {0} existe déjà. Choisissez un autre nom.",
  "checkService": "Vérifier le service : {0}",
  "createService": "Créer le service : {0}",
  "unableToCreate": "Impossible de créer : {0}",
  "addToDefinition": "Ajouter à la définition : {0}",
  "successfullyPublished": "La couche Web a été publiée{0}Gérer la couche Web",
  "userRole": "Impossible de créer le service car l’utilisateur ne dispose pas des autorisations requises",
  "publishToNewLayer": "Publier les résultats dans une nouvelle couche d’entités",
  "missingLayerNameMessage": "Vous devez saisir un nom de couche valide avant la publication",
  "regionTypeLabel": "Type de région",
  "centerPointLabel": "Point central",
  "observationHeightLabel": "Hauteur d’observation",
  "heightUnitLabel": "Unité de hauteur",
  "minObservationDistanceLabel": "Distance d’observation minimale",
  "maxObservationDistance": "Distance d’observation maximale",
  "distanceUnitLabel": "Unité de distance",
  "fovstartAngleLabel": "Angle de départ du champ de visibilité",
  "fovEndAngleLabel": "Angle de fin du champ de visibilité",
  "andleUnitsLabel": "Unités d’angle"
});