define({
  "_widgetLabel": "Incidenselemzés",
  "_featureAction_SetAsIncident": "Beállítás incidensként",
  "incident": "Incidens",
  "weather": "Időjárás",
  "locate_incident": "Incidens megkeresése",
  "clear_incidents": "Incidensek törlése",
  "reverse_geocoded_address": "Legközelebbi cím",
  "reverse_geocoded_error": "Nem elérhető",
  "miles": "mérföld",
  "kilometers": "kilométer",
  "feet": "láb",
  "meters": "méter",
  "yards": "yard",
  "nauticalMiles": "tengeri mérföld",
  "now": "MOST",
  "wind": "SZÉL",
  "SUN": "V",
  "MON": "H",
  "TUE": "K",
  "WED": "SZE",
  "THU": "CS",
  "FRI": "P",
  "SAT": "SZO",
  "defaultTabMsg": "Nincs azonosítva incidens.",
  "useMapExtent": "Aktuális térképkiterjedés használata",
  "noFeaturesFound": "Nem találhatók vektoros elemek.",
  "downloadCSV": "CSV LETÖLTÉSE",
  "sum": "ÖSSZ.",
  "min": "MIN.",
  "max": "MAX.",
  "avg": "ÁTL.",
  "count": "SZÁM",
  "area": "TERÜLET",
  "length": "HOSSZ"
});