define({
  "businessAnalyst": "Business Analyst",
  "defineWhichInfographics": "Defina quais infográficos estão disponíveis no widget:",
  "defineWhichReports": "Defina quais relatórios estão disponíveis no widget:",
  "defaultValues": "Valores padrão:",
  "disable": "Desabilitar",
  "driveTime": "Tempo de percurso",
  "infographics": "Infográficos",
  "invalidValueRing": "Os valores devem estar na faixa de 0 até1,000.",
  "invalidValueDTWT": "Os valores devem estar na faixa de 0 até 300.",
  "km": "km",
  "miles": "milhas",
  "minutes": "minutos",
  "radius": "Proporção",
  "reports": "Relatórios",
  "rings": "Anéis",
  "selectCountryOrRegion": "Selecione país ou região:",
  "thisEntryIsNotValid": "Esta entrada não é válida.",
  "time": "Hora",
  "walkTime": "Tempo de caminhada"
});