define({
  "_widgetLabel": "Atstumai ir kryptys",
  "tabLineTitle": "Linija",
  "tabCircleTitle": "Apskritimas",
  "tabEllipseTitle": "Elipsė",
  "tabRingsTitle": "Žiedai",
  "multipleNotationsMessage": " žymėjimai, kurie atitinka įvestį. Patvirtinkite, kurį norite naudoti:",
  "invalidCoordinateMessage": "Neteisinga koordinatė",
  "confirmInputNotationMessage": "Patvirtinkite įvesties žymėjimą",
  "prefixSuffixMessage": "Įvesties koordinatė buvo nustatyta, nes turimos platumos ir ilgumos prefikso ir sufikso reikšmės pateikė prefiksu pagrįstą koordinatę.",
  "rememberDecisionMessage": "Prisiminti prisijungimo duomenis ir daugiau nebeklausti.<br/>",
  "majorAxisTooltipMessage": "Spustelėkite pagrindinės ašies ilgį",
  "minorAxisTooltipMessage": "Parkelkite pelės žymiklį atgal į pradinę padėtį, kad nustatytumėte šalutinę ašį ir baigtumėte brėžti elipsę",
  "clickToFinishLineMessage": "Spustelėkite, kad baigtumėte brėžti liniją",
  "doubleClickEllipseMesage": "Dukart spustelėkite, kad baigtumėte brėžti atstumo žiedus",
  "invalidCoordinateTypeMessage": "Negalima nustatyti įvesties koordinačių tipo. Patikrinkite savo įvestį",
  "noCenterPointSetMessage": "Nenustatytas centrinis taškas. Patikrinkite įvestį",
  "ellipseMajorAxis": "Pagrindinė ašis",
  "ellipseMinorAxis": "Šalutinė ašis",
  "degreesRangeMessage": "Reikšmė turi būti tarp 0 ir 360",
  "millsRangeMessage": "Reikšmė turi būti tarp 0 ir 6400",
  "lengthLabel": "Ilgis",
  "angleLabel": "Kampas",
  "startPointLabel": "Pradžios taškas",
  "endPointLabel": "Pabaigos taškas",
  "centerPointLabel": "Centro taškas",
  "distanceTableErrorMessage": "Atstumo lentelė tuščia. Įveskite keletą atstumų.",
  "setCoordFormatStringMessage": "Nustatyti koordinačių formato eilutę",
  "prefixMessage": "Pridėti „+/-“ prefiksą prie teigiamų ir neigiamų skaičių",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "Laipsniai, Minutės, Sekundės",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Dešimtainiai laipsniai – platuma / ilguma",
  "DDLongLatNotation": "Dešimtainiai laipsniai – ilguma / platuma",
  "DDMLatLongNotation": "Dešimtainių laipsnių minutės – platuma / ilguma",
  "DDMLongLatNotation": "Dešimtainių laipsnių minutės – ilguma / platuma",
  "DMSLatLongNotation": "Dešimtainių laipsnių sekundės – platuma / ilguma",
  "DMSLongLatNotation": "Dešimtainių laipsnių sekundės – ilguma / platuma",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - dažnio raidė",
  "UTMHemNotation": "UTM – pusrutulis (Š/P)",
  "circleTitle": "Sukurti apskritimą pagal",
  "radiusLabel": "Spindulys",
  "diameterLabel": "Skersmuo",
  "startPointPlaceHolderLabel": "Įveskite koordinates",
  "formatInputLabel": "Formato įvestis",
  "drawCircleLabel": "Piešti apskritimą",
  "drawLineLabel": "Brėžti liniją",
  "createCircleInteractivelyLabel": "Sukurti apskritimą interaktyviai",
  "rangeErrorMessage": "Netinkamas spindulys arba skersmuo",
  "numericInvalidMessage": "Įveskite skaitinę reikšmę",
  "timeLabel": "Laikas",
  "invalidTimeMessage": "Neteisinga laiko reikšmė",
  "hoursLabel": "Valandos",
  "minutesLabel": "Minutės",
  "secondsLabel": "Sekundės",
  "rateLabel": "Sparta",
  "invalidDistanceMessage": "Neteisinga atstumo reikšmė",
  "feetSecondsLabel": "Pėdos / sekundę",
  "feetHourLabel": "Pėdos / valandą",
  "kmSecondLabel": "Kilometrai / sekundę",
  "kmHourLabel": "Kilometrai / valandą",
  "metersSecondLabel": "Metrai / sekundę",
  "metersHourLabel": "Metrai / valandą",
  "milesSecondLabel": "Mylios / sekundę",
  "milesHourLabel": "Mylios / valandą",
  "nauticalMilesSecondLabel": "Jūrmylės / sekundę",
  "nauticalMilesHourLabel": "Jūrmylės / valandą",
  "clearGraphicsLabel": "Valyti grafinius elementus",
  "ellipseTypeLabel": "Elipsės tipas",
  "ellipseSemiLabel": "Pusinė",
  "ellipseFullLabel": "Visa",
  "drawEllipseLabel": "Brėžti elipsę",
  "createEllipseInteractively": "Sukurti elipsę interaktyviai",
  "axisLabel": "Ašis",
  "unitLabel": "Vienetai",
  "majorRadiusLabel": "Pagrindinė (spindulys)",
  "majorDiameterLabel": "Pagrindinis (skersmuo)",
  "axisErrorMessage": "Reikšmė turi būti didesnė nei 0",
  "minorRadiusLabel": "Šalutinė (spindulys)",
  "minorDiameterLabel": "Šalutinis (skersmuo)",
  "orientationLabel": "Padėtis",
  "orientationErrorMessage": "Reikšmė turi būti tarp 0 ir 360",
  "warningMessage": "Įspėjimas: grafiniai elementai sugeneruoti naudojant elipsės įrankį nėra geodeziniai",
  "fromLabel": "Nuo",
  "distanceBearingLabel": "Atstumai ir kryptys",
  "pointsLabel": "Taškai",
  "createLineInteractively": "Sukurti liniją interaktyviai",
  "lineLengthErrorMessage": "Netinkamas linijos ilgis",
  "degreesLabel": "Laipsniai",
  "milsLabel": "Mylios",
  "lineTypeLabel": "Tipas",
  "interactiveLabel": "Interaktyvus",
  "fixedLabel": "Fiksuotas",
  "originLabel": "Iš centro taško",
  "cumulativeLabel": "Suvestinis",
  "numberOfRingsLabel": "Žiedų skaičius",
  "ringsErrorMessage": "Netinkamas žiedų skaičius",
  "distanceBetweenRingsLabel": "Atstumas tarp žiedų",
  "ringsDecimalErrorMessage": "Įveskite skaitinę reikšmę 2 dešimtainių dalių tikslumu",
  "distanceUnitsLabel": "Atstumo vienetai",
  "distancesLabel": "Atstumai",
  "numberOfRadialsLabel": "Spindulių skaičius",
  "upLabel": "Aukštyn",
  "downLabel": "Žemyn",
  "deleteLabel": "Ištrinti",
  "radialsErrorMessage": "Netinkamas spindulių skaičius. Didžiausias leidžiamas skaičius 360",
  "radialsInvalidMessage": "Netinkama spindulių reikšmė",
  "addPointLabel": "Pridėti tašką",
  "valueLabel": "Reikšmė",
  "valueText": "Įvesti reikšmę",
  "actionLabel": "Veiksmas",
  "distanceCalculatorLabel": "Atstumo skaičiuotuvas",
  "abbrevMetersLabel": "m",
  "abbrevFeetLabel": "pėdos",
  "abbrevKmLabel": "km",
  "abbrevMilesLabel": "mi.",
  "abbrevYardsLabel": "jard.",
  "abbrevNauticalMilesLabel": "jūrmyl.",
  "abbrevDegreesLabel": "°",
  "abbrevMilsLabel": "myl.",
  "abbrevHoursLabel": "val.",
  "abbrevMinutesLabel": "min.",
  "abbrevSecondsLabel": "sek.",
  "abbrevFeetSecondsLabel": "pėd./sek.",
  "abbrevFeetHourLabel": "pėd./val.",
  "abbrevKmSecondLabel": "km/sek.",
  "abbrevKmHourLabel": "km/val.",
  "abbrevMetersSecondLabel": "m/sek.",
  "abbrevMetersHourLabel": "m/val.",
  "abbrevMilesSecondLabel": "myl./sek.",
  "abbrevMilesHourLabel": "myl./val.",
  "abbrevNauticalMilesSecondLabel": "jūrm./sek.",
  "abbrevNauticalMilesHourLabel": "jūrm./val.",
  "publishDDBtn": "Publikuoti",
  "publishTitle": "Publikuoti grafiką",
  "ddLayerName": "Publikuotas sluoksnio pavadinimas",
  "missingDDLayerName": "Būtina įvesti sluoksnio pavadinimą",
  "publishToNewLayer": "Publikuoti rezultatus į naują elementų sluoksnį",
  "checkService": "Tikrinti paslaugą: {0}",
  "createService": "Kurti paslaugą: {0}",
  "unableToCreate": "Nepavyko sukurti: {0}",
  "addToDefinition": "Įtraukti į aprašą: {0}",
  "successfullyPublished": "Sėkmingai publikuotas žiniatinklio sluoksnis{0}Tvarkyti žiniatinklio sluoksnį",
  "userRole": "Nepavyksta sukurti paslaugos, nes vartotojas neturi teisių",
  "missingLayerNameMessage": "Prieš publikuojant reikia įvesti tinkamą sluoksnio pavadinimą",
  "invalidLayerName": "Sluoksnio pavadinime gali būti tik raidės, skaičiai ir pabraukimo brūkšniai",
  "distanceLabel": "Atstumas",
  "radiusDistance": "Spindulio ilgis",
  "radials": "Žiediniai",
  "rings": "Žiedai",
  "orientationUnit": "Padėties vienetas",
  "radiusUnit": "Spindulio vienetas",
  "angleUnitLabel": "Kampo vienetas"
});