define({
  root: ({
    settings: "Settings",
    titleSettings: "Text settings",
    imageSettings: "Image settings",
    backgroundColor: "Background color",
    alignment: "Alignment",
    textSize: "Text size",
    textColor: "Text color",
    dataSource: "Data source",
    chartSettings: "Chart settings",
    data: "Data",
    dataLabels: "Data labels",
    displayMode: "Display mode",
    featureOption: "Display values feature by feature",
    categoryOption: "Display values by category",
    countOption: "Display feature counts by category",
    fieldOption: "Display attribute values as charts",
    categoryField: "Category field",
    labelField: "Label field",
    valueFields: "Value fields",
    operation: "Operation",
    sumOption: "Sum",
    averageOption: "Average",
    minOption: "Minimum",
    maxOption: "Maximum",
    dataFormat: "Data format",
    decimalPlaces: "Decimal places",
    prefix: "Prefix",
    suffix: "Suffix",
    dataType: "Data type",
    featureCount: "Feature count",
    fieldStatistics: "Field statistics",
    display: "Display",
    chartColor: "Chart color",
    horizontalAxis: "Horizontal axis",
    verticalAxis: "Vertical axis",
    legend: "Legend",
    position: "Position",
    top: "Top",
    bottom: "Bottom",
    useDataSourceSelection: "Use selection",
    dataSourceFilterByExtent: "Filter by extent",
    changeTemplate: "Change template",
    numberSettings: "Number settings",
    gaugeSettings: "Gauge settings",
    //indicators
    indicators: "Indicators",
    ifValue: "If value",
    and: "and",
    numberOperatorIsLessThan: "is less than",
    numberOperatorIsGreaterThan: "is greater than",
    numberOperatorIsBetween: "is between",
    numberOperatorIsEqual: "is equal to",
    numberOperatorIsNotEqual: "is not equal to",
    then: "Then",
    ratio: "Ratio",
    trueValue: "True value",
    changeValueColor: "change value color to",
    changeGaugeColor: "change gauge color to",
    setIndicatorIcon: "set indicator icon as",
    //iconChooser
    icons: "Icons",
    style: "Style",
    placement: "Placement",
    left: "Left",
    replace: "Replace",
    right: "Right",
    color: "Color",

    dataRange: "Data range",
    targetValue: "Target value",
    currentValue: "Current value",
    gaugeColor: "Gauge color",
    min: "Minimum",
    max: "Maximum",
    displayValueIn: "Display value in",
    noData: "No data",
    thousandAbbreviation: "k",
    millionAbbreviation: "M",
    billionAbbreviation: "G",
    warning: "Warning",
    noSettingWaring1: "Click an element to set its properties.",
    noSettingWaring2: "Drag to resize or reorder an element.",
    donNotShowAgain: "Do not show again",
    changeTemplateWarning: "This will erase all your settings and open a new empty template.",
    requiredFieldWarning: "This value is required:",
    dataSourceNotSet: "Please set data source.",
    addIndicatorTip: "Add an indicator",
    chooseTemplatePopupTitle: "Choose a template",
    stringsInTemplate: {
      name_number: "Number",
      name_gauge: "Gauge",
      name_vertical_gauge: "Vertical Gauge",
      name_horizontal_gauge: "Horizontal Gauge",
      name_pie_chart: "Pie Chart",
      name_column_chart: "Column Chart",
      name_bar_chart: "Bar Chart",
      name_line_chart: "Line Chart",

      titleOfTheInfographic: "TITLE OF THE INFOGRAPHIC",
      description: "Description: additional infomation about this infographic."
    }
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});