define({
  "_widgetLabel": "Nettverkssporing",
  "_featureAction_NetworkTraceSkip": "Hopp over i spor",
  "_featureAction_NetworkTraceUnskip": "Fjern fra lokasjoner som skal hoppes over",
  "removedFromSkipLocations": "Fjernet fra lokasjoner som skal hoppes over",
  "alreadyRemovedFromSkipLocations": "Allerede fjernet fra lokasjoner som skal hoppes over",
  "locationSkipped": "Lokasjonen er hoppet over",
  "configError": "Miniprogrammet er ikke riktig konfigurert.",
  "geometryServiceURLNotFoundMSG": "Kan ikke hente URL for geometritjeneste",
  "clearButtonValue": "Tøm",
  "GPExecutionFailed": "Sporingen kan ikke fullføres. Prøv på nytt.",
  "backButtonValue": "Tilbake",
  "exportToCSVSuccess": "Eksport til CSV er fullført.",
  "lblInputLocTab": "Angi lokasjoner",
  "lblBlockLocTab": "Blokker lokasjoner",
  "lblInputLocation": "Angi geoobjekt",
  "lblBlockLocation": "Blokker geoobjekt",
  "lblInputLocHeader": "Angi lokasjoner (0)",
  "lblBlockLocHeader": "Blokker lokasjoner (0)",
  "inputTabTitle": "Inndata",
  "outputTabTitle": "Resultat",
  "exportSelectAllCheckBoxLabel": "Merk alle",
  "lblSkipLocHeader": "Hopp over lokasjoner (0)",
  "lblSkipLocation": "Stedsangivelse",
  "lblSkipLocTab": "Hopp over lokasjoner",
  "skipAllLocationButtonLabel": "Hopp over alle lokasjoner",
  "confirmSkipAllLocationsMessage": "Alle lokasjonene blir hoppet over. Vil du fortsette?",
  "locationAlreadySkippedMessage": "Lokasjonen er allerede hoppet over",
  "removeAllSkipLocationLabel": "Fjern alt",
  "newProjectOptionText": "Nytt prosjekt",
  "selectProject": "Velg prosjekt",
  "saveButtonLabel": "Lagre",
  "exportToCSVText": "Eksporter til CSV",
  "editProjectAttributesToolTip": "Rediger prosjektattributter",
  "projectNameLabel": "Prosjektnavn",
  "saveProjectPopupTitle": "Lagre",
  "saveAsLabel": "Lagre som",
  "saveChangesMsg": "Vil du lagre endringene i <b>${loadProjectDropdownlabel}</b> eller lagre som nytt prosjekt?",
  "creatingNewProjectErrorMessage": "Feil under opprettelse av nytt prosjekt. Prøv på nytt.",
  "projectNameFetchingErr": "Feil under henting av eksisterende prosjektnavn. Prøv på nytt.",
  "projectAttributeLoadingErr": "Feil under lasting av prosjektattributter. Prøv på nytt.",
  "attributeUpdatedMsg": "Attributtene er oppdatert.",
  "projectAttributeUpdatingErr": "Feil under oppdatering av prosjektattributter.",
  "loadingProjectDetailsErrorMessage": "Feil under henting av flagg, hinder og lokasjoner som hoppes over. Prøv på nytt.",
  "savingProjectDetailsErr": "Feil under lagring av prosjektdetaljer. Prøv å lagre prosjektet på nytt.",
  "updatingOutagePolygonErr": "Feil under oppdatering av nedetidspolygon. Prøv å lagre prosjektet på nytt.",
  "deletingExistingPolygonErr": "Feil under sletting av eksisterende nedetidspolygon. Prøv å lagre prosjektet på nytt.",
  "loadingProjectFeaturesErr": "Feil under lasting av prosjektgeoobjekter. Prøv å laste prosjektet på nytt.",
  "addingProjectFeaturesErr": "Feil under tillegging av prosjektgeoobjekter. Prøv å lagre prosjektet på nytt.",
  "deletingExistingProjectFeaturesErr": "Feil under sletting av eksisterende prosjektgeoobjekter. Prøv å lagre prosjektet på nytt.",
  "projectNotFoundErr": "Finner ikke prosjektet",
  "projectLayersNotFound": "Konfigurerte lag for prosjektinnstillinger er ikke tilgjengelige i kartet. Miniprogrammet blir lastet i skissemodus.",
  "fetchingOutagePolygonMessage": "Feil under henting av nedetidspolygon. Prøv å laste prosjektet på nytt.",
  "projectNameExistsMessage": "Prosjektnavnet finnes allerede. Bruk et unikt prosjektnavn.",
  "fetchingProjectNamesErrorMessage": "Feil under henting av eksisterende prosjektnavn. Prøv å lagre prosjektet på nytt.",
  "enterProjectNameMessage": "Skriv inn et prosjektnavn.",
  "projectLengthErrorMessage": "Prosjektnavnet kan ikke være større enn",
  "gpServiceNotAccessible": "Kontoen din har ikke tilgang til den nødvendige tjenesten for å utføre denne sporingen.",
  "loadingClonedLayerErrorMessage": "Feil under lasting av klonet geoobjektlag. Prøv på nytt.",
  "addingFeatureInClonedLayerError": "Feil under tillegging av grafikk i klonet geoobjektlag. Prøv på nytt.",
  "selectingFeatureInClonedLayerError": "Feil under valg av grafikk i klonet geoobjektlag. Prøv på nytt.",
  "filteredProjectError": "Feil under kontroll av henting av filtrerte prosjektdetaljer. Prøv på nytt.",
  "filteredProjectMessage": "Valgte prosjektattributter er ikke tilgjengelige på grunn av de brukte filtrene fra webkartet eller et annet miniprogram. Slett filteret/filtrene og prøv på nytt.",
  "filteredProjectLoadMessage": "Prosjektet ditt er ikke lenger tilgjengelig. Velg et aktivt prosjekt.",
  "defaultValueForRunButton": "Kjør",
  "closeButtonLabel": "Fjern"
});