define({
  "tabs_section_Label": "Karty",
  "addTab": "Dodaj kartę",
  "layerName": "Warstwa",
  "layerType": "Rodzaj analizy",
  "layerLabel": "Etykieta",
  "actions": "Działania",
  "closest": "Najbliższy obiekt",
  "proximity": "Bliskość",
  "summary": "Podsumowanie",
  "select_lbl": "-- Wybierz --",
  "general_setting_Label": "Ustawienia ogólne",
  "units_text_lbl": "Jednostki odległości",
  "maximum_distance_lbl": "Odległość maksymalna najbliższego obiektu",
  "buffer_text_lbl": "Etykieta buforowania",
  "buffer_lbl": "Odległość buforowania",
  "buffer_max_lbl": "Maksymalna odległość buforowania",
  "buffer_min_lbl": "Minimalna odległość buforowania",
  "routing_checkBox": "Włącz wyznaczanie tras",
  "weather_Label": "Opcje pogodowe",
  "weather_checkBox": "Dołącz informacje pogodowe",
  "selectLayers": "wybierz warstwy pogodowe",
  "currentlySelectedLayer": "Aktualnie wybrane warstwy pogodowe",
  "missingTabLabel": "Brak etykiety w przynajmniej jednej zakładce",
  "missingLayerInWebMap": "Nie znaleziono warstw operacyjnych.",
  "selectFields": "Wybierz pola",
  "addField": "Dodaj pole",
  "sum": "Sum",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Średnia",
  "count": "LICZBA",
  "area": "POWIERZCHNIA",
  "length": "DŁUGOŚĆ",
  "count_checkBox": "Wyświetl liczbę obiektów",
  "area_checkBox": "Wyświetl sumę powierzchni",
  "length_checkBox": "Wyświetl sumę długości",
  "max_records": "Osiągnięto limit maksymalny",
  "save_label": "Opcje zapisywania",
  "save_checkbox": "Włącz zapisywanie",
  "csv_label": "Opcje CSV",
  "csv_checkbox": "Wyeksportuj wszystkie pola w warstwie",
  "display_label": "Opcje wyświetlania",
  "display_checkbox": "Wyświetl obiekty podsumowania",
  "snapshot_label": "Opcje migawki",
  "snapshot_checkbox": "Włącz migawkę",
  "must_select_template": "W opcjach zapisywania wybierz jeden z szablonów edycji.",
  "count_label": "Etykieta liczby",
  "area_label": "Etykieta obszaru",
  "length_label": "Etykieta długości",
  "invalid_string_width": "Wartość jest za długa. ",
  "layer_type_not_supported": "Typ warstwy jest nieobsługiwany: ",
  "groupedSummary": "Pogrupowane zliczenia",
  "groupByField": "Pole Grupuj wg",
  "labelType": "Dołącz etykietę",
  "prefix": "Jako prefiks",
  "suffix": "Jako sufiks",
  "need_group_field": "Użyj czynności edycji, aby zdefiniować pole Grupuj wg.",
  "fieldTitle": "Pole",
  "typeTitle": "Typ",
  "actionsTitle": "Działania",
  "save_point_checkbox": "Zapisz punkty",
  "save_line_checkbox": "Zapisz linie",
  "save_poly_checkbox": "Zapisz poligony",
  "no_valid_popup_fields": "Brak prawidłowych pól w oknie podręcznym. Użyj działania edycji, aby zdefiniować pole.",
  "no_valid_fields": "Brak prawidłowych pól. Użyj działania edycji, aby zdefiniować opcje wyświetlania.",
  "incident_label": "Etykieta karty",
  "locate_incident_label": "Etykieta obszaru zainteresowania",
  "incident": "Zdarzenie",
  "locate_incident": "Zlokalizuj zdarzenie",
  "buffer_value": "Odległość buforowania"
});