define({
  "layerSelect": "Seleccioneu la capa d'imatges",
  "displayMeasureResultInPopup": "Mostra els resultats de la mesura en una finestra emergent",
  "angularUnitSelect": "Unitat angular per defecte",
  "linearUnitSelect": "Unitat lineal per defecte",
  "areaUnitSelect": "Unitat d'àrea per defecte",
  "displayOperationSelect": "Seleccioneu les operacions de mesura",
  "errorSectionMessage": "Cap de les capes admet les funcions de mesurament.",
  "unitLabel": {
    "esriInches": "Polzades",
    "esriFeet": "Peus",
    "esriYards": "Iardes",
    "esriMiles": "Milles",
    "esriNauticalMiles": "Milles nàutiques",
    "esriMillimeters": "Mil·límetres",
    "esriCentimeters": "Centímetres",
    "esriDecimeters": "Decímetres",
    "esriMeters": "Metres",
    "esriKilometers": "Quilòmetres",
    "esriDURadians": "Radians",
    "esriDUDecimalDegrees": "Graus",
    "esriSquareInches": "Polzades quadrades",
    "esriSquareFeet": "Peus quadrats",
    "esriSquareYards": "Iardes quadrades",
    "esriAcres": "Acres",
    "esriSquareMiles": "Milles quadrades",
    "esriSquareMillimeters": "Mil·límetres quadrats",
    "esriSquareCentimeters": "Centímetres quadrats",
    "esriSquareDecimeters": "Decímetres quadrats",
    "esriSquareMeters": "Metres quadrats",
    "esriAres": "Àrees",
    "esriHectares": "Hectàrees",
    "esriSquareKilometers": "Quilòmetres quadrats"
  },
  "operationLabel": {
    "esriMensurationPoint": "Ubicació",
    "esriMensurationDistanceAndAngle": "Distància i angle",
    "esriMensurationAreaAndPerimeter": "Àrea i perímetre",
    "esriMensurationHeightFromBaseAndTop": "Altura: de la base a la part superior",
    "esriMensurationHeightFromBaseAndTopShadow": "Altura: de la base a l'ombra superior",
    "esriMensurationHeightFromTopAndTopShadow": "Altura: de la part superior a l'ombra superior",
    "esriMensurationCentroid": "Centroide",
    "esriMensurationPoint3D": "Ubicació (3D)",
    "esriMensurationDistanceAndAngle3D": "Distància i angle (3D)",
    "esriMensurationAreaAndPerimeter3D": "Àrea i perímetre (3D)",
    "esriMensurationCentroid3D": "Centroide (3D)"
  }
});