define({
  "_widgetLabel": "Älykäs muokkausohjelma",
  "_featureAction_SmartEditor": "Älykäs muokkausohjelma",
  "noEditPrivileges": "Tililläsi ei ole tietojen luonti- tai muokkausoikeuksia.",
  "widgetActive": "Aktiivinen",
  "widgetNotActive": "Ei aktiivinen",
  "pressStr": "Paina ",
  "ctrlStr": " CTRL ",
  "snapStr": " tartunnan käyttöön ottamiseksi",
  "noAvailableTempaltes": "Yhtään mallia ei ole käytettävissä",
  "editorCache": " - Muokkausohjelman välimuisti",
  "presetFieldAlias": "Kenttä",
  "presetValue": "Esiasetettu arvo",
  "usePresetValues": " Käytä esiasetettuja arvoja (vain uudet kohteet)",
  "editGeometry": " Muokkaa geometriaa",
  "savePromptTitle": "Tallenna kohde",
  "savePrompt": "Haluatko tallentaa nykyisen kohteen?",
  "deletePromptTitle": "Poista kohde",
  "deleteAttachment": "Poista liite",
  "deletePrompt": "Haluatko varmasti poistaa valitun kohteen?",
  "attachmentLoadingError": "Virhe ladattaessa liitteitä",
  "attachmentSaveDeleteWarning": "Varoitus: liitteiden muutokset tallennetaan automaattisesti",
  "autoSaveEdits": "Tallentaa uuden kohteen automaattisesti",
  "addNewFeature": "Luo uusi kohde",
  "featureCreationFailedMsg": "Uutta tietuetta tai kohdetta ei voi luoda",
  "relatedItemTitle": "Liittyvä taulukko tai karttataso",
  "relatedFeatureCount": "${layerTitle}, jossa on ${featureCount} kohdetta",
  "createNewFeatureLabel": "Luo uusi kohde karttatasolle ${layerTitle}",
  "invalidRelationShipMsg": "Varmista, että ensisijaisen avainkentän ${parentKeyField} arvo on kelvollinen",
  "pendingFeatureSaveMsg": "Tallenna kohteen muokkaukset ennen liittyvän kohteen luontia.",
  "attachmentsRequiredMsg": "(*) Liitteet ovat pakollisia.",
  "coordinatePopupTitle": "Siirrä kohde XY-sijaintiin",
  "coordinatesSelectTitle": "Koordinaattijärjestelmä:",
  "mapSpecialReferenceDropdownOption": "Kartan koordinaatistotieto",
  "latLongDropdownOption": "Leveysaste/Pituusaste",
  "xAttributeTextBoxLabel": "X-koordinaatti:",
  "yAttributeTextBoxLabel": "Y-koordinaatti:",
  "latitudeTextBoxLabel": "Leveysaste:",
  "longitudeTextBoxLabel": "Pituusaste:",
  "presetGroupFieldsLabel": "Ryhmää ${groupName} käytetään seuraavissa karttatason kentissä:",
  "presetGroupNoFieldsLabel": "Ryhmään ${groupName}’ ei ole liitetty kenttiä",
  "groupInfoLabel": "Ryhmän ${groupName} tiedot",
  "editGroupInfoIcon": "Muokkaa ryhmän ${groupName} ryhmäarvoa",
  "filterEditor": {
    "all": "Kaikki",
    "noAvailableTempaltes": "Yhtään mallia ei ole käytettävissä",
    "searchTemplates": "Hae malleja",
    "filterLayerLabel": "Suodata karttatasot"
  },
  "invalidConfiguration": "Pienoisohjelmaa ei ole joko määritetty tai määrityksen karttatasoja ei ole enää kartassa. Avaa sovellus luontitilassa ja määritä pienoisohjelma uudelleen.",
  "geometryServiceURLNotFoundMSG": "Geometriapalvelun URL-osoitetta ei voi noutaa",
  "clearSelection": "Tyhjennä",
  "refreshAttributes": "Päivitä kohteen ominaisuustiedot",
  "automaticAttributeUpdatesOn": "Päivitä kohteen ominaisuustiedot automaattisesti: KÄYTÖSSÄ",
  "automaticAttributeUpdatesOff": "Päivitä kohteen ominaisuustiedot automaattisesti: POIS KÄYTÖSTÄ",
  "moveSelectedFeatureToGPS": "Siirrä valittu kohde nykyiseen GPS-sijaintiin",
  "moveSelectedFeatureToXY": "Siirrä valittu kohde XY-sijaintiin",
  "mapNavigationLocked": "Kartan navigointi: lukittu",
  "mapNavigationUnLocked": "Kartan navigointi: ei lukittu",
  "copyFeatures": {
    "title": "Kopioi kohteet",
    "createFeatures": "Luo kohteet",
    "createSingleFeature": "Luo yksi Multi-Geometry-kohde",
    "noFeaturesSelectedMessage": "Yhtään kohdetta ei ole valittu",
    "selectFeatureToCopyMessage": "Valitse kopioitavat kohteet.",
    "multipleFeatureSaveWarning": "Huomautus: useiden kohteiden luonti kohteen kopiointitoiminnolla tallentaa kaikki kohteet heti"
  },
  "addingFeatureError": "Virhe lisättäessä valittuja kohteita karttatasoon. Yritä uudelleen.",
  "addingFeatureErrorCount": "${copyFeatureErrorCount} kohteen kopiointi epäonnistui.",
  "selectingFeatureError": "Virhe valittaessa kohteita karttatasosta. Yritä uudelleen.",
  "customSelectOptionLabel": "Valitse kopioitavat kohteet",
  "noFeatureSelectedMessage": "Kohteita ei ole valittu.",
  "multipleFeatureSaveMessage": "Kaikki kohteet tallennetaan heti. Haluatko jatkaa?",
  "relativeDates": {
    "dateTypeLabel": "Päivämäärätyyppi",
    "valueLabel": "Arvo",
    "fixed": "Kiinteä",
    "current": "Nykyinen",
    "past": "Menneet",
    "future": "Tuleva",
    "popupTitle": "Valittu arvo",
    "hintForFixedDateType": "Vihje: määritettyä päivämäärää ja aikaa käytetään ennalta määritettynä oletusarvona",
    "hintForCurrentDateType": "Vihje: nykyistä päivämäärää ja aikaa käytetään ennalta määritettynä oletusarvona",
    "hintForPastDateType": "Vihje: määritetty arvo vähennetään nykyisestä päivämäärästä ja ajasta ennalta määritettyä oletusarvoa varten.",
    "hintForFutureDateType": "Vihje: määritetty arvo lisätään nykyiseen päivämäärään ja ajasta ennalta määritettyä oletusarvoa varten.",
    "noDateDefinedTooltip": "Päivämäärää ei ole määritetty"
  }
});