define({
  "_widgetLabel": "Bedrohungsanalyse",
  "threatAnalysisMainPageTitle": "Basierend auf dem Handbuch \"JCAT Counterterrorism Guide\"",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Eingabeposition",
  "interactive": "Interaktiv",
  "fromCoord": "Feste Koordinate",
  "existingFeature": "Aus vorhandenen Features",
  "threatAnalysisCoordInputLabel": "Position der Bedrohung",
  "enterCoords": "Koordinaten eingeben",
  "threatAddPointToolTip": "Position für Bedrohung hinzufügen",
  "threatDrawPointToolTip": "Klicken Sie hier, um eine Position für eine Bedrohung hinzuzufügen.",
  "threatType": "Bedrohungstyp",
  "threatPlaceholder": "Beginnen Sie mit der Eingabe, um nach einer Bedrohung zu suchen.",
  "mandatoryLabel": "Entfernung für obligatorische Evakuierung",
  "safeLabel": "Entfernung für sichere Evakuierung",
  "zoneTypeLabel": "Zonentyp",
  "feetLabel": "Fuß",
  "metersLabel": "Meter",
  "unitsLabel": "Einheiten",
  "threatGraphicLayer": "Bedrohungsgrafik",
  "settingsTitle": "Einstellungen",
  "mandatoryButtonLabel": "Einstellungen für Entfernung für obligatorische Evakuierung konfigurieren",
  "safeButtonLabel": "Einstellungen für Zufluchtszone vor Ort konfigurieren",
  "style": "Style",
  "colorPicker": "colorPicker",
  "lineStyles": {
    "esriSLSDash": "Strich",
    "esriSLSDashDot": "Strich-Punkt",
    "esriSLSDashDotDot": "Strich-Punkt-Punkt",
    "esriSLSDot": "Punkt",
    "esriSLSLongDash": "Langer Strich",
    "esriSLSLongDashDot": "Langer Strich-Punkt",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Kurzer Strich",
    "esriSLSShortDashDot": "Kurzer Strich-Punkt",
    "esriSLSShortDashDotDot": "Kurzer Strich-Punkt-Punkt",
    "esriSLSShortDot": "Kurzer Punkt",
    "esriSLSSolid": "Vollfarbe"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Rückwärts",
    "esriSFSCross": "Kreuzförmig",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Vorwärts",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Vollfarbe",
    "esriSFSVertical": "Vertikal"
  },
  "resultsTitle": "Ergebnisse",
  "publishTABtn": "Veröffentlichen",
  "layerName": "Name des veröffentlichten Layers",
  "invalidLayerName": "Der Layer-Name darf nur alphanumerische Zeichen und Unterstriche enthalten.",
  "missingLayerName": "Sie müssen einen Namen für den Layer eingeben",
  "missingLayerNameMessage": "Sie müssen einen gültigen Layer-Namen eingeben, bevor Sie ihn veröffentlichen können.",
  "publishingFailedLayerExists": "Fehler beim Veröffentlichen: Sie verfügen bereits über einen Service mit dem Namen {0}. Wählen Sie einen anderen Layer-Namen.",
  "checkService": "Service {0} überprüfen",
  "createService": "Service {0} erstellen",
  "unableToCreate": "{0} kann nicht erstellt werden",
  "addToDefinition": "Zur Definition {0} hinzufügen",
  "successfullyPublished": "Web-Layer wurde erfolgreich veröffentlicht{0}Web-Layer verwalten",
  "successfullyAppended": "An den Web-Layer wurden erfolgreich neue Features angehängt{0}Web-Layer verwalten",
  "userRole": "Der Service kann nicht erstellt werden, da dem Benutzer nicht die entsprechenden Berechtigungen zugewiesen sind.",
  "retrieveExistingLayerError": "Abrufen von {0} nicht möglich. Nehmen Sie die Veröffentlichung mit einem anderen Layer-Namen vor.",
  "publishToNewLayer": "Ergebnisse in einem neuen Feature-Layer veröffentlichen",
  "pipeBombLabel": "Rohrbombe",
  "suicideBombLabel": "Selbstmordattentat",
  "briefcaseLabel": "Aktenkoffer",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/Van",
  "smallDeliveryTruckLabel": "Kleiner Lieferwagen",
  "containerWaterTruckLabel": "Container-Lkw/Wassertankwagen",
  "semiTrailerLabel": "Sattelschlepper",
  "transparencyLabel": "Transparenz",
  "outline": "Umrisslinie",
  "fill": "Füllung (Farbe wird nur angewendet, wenn der Style auf Vollfarbe festgelegt ist)",
  "createBtn": "Zonen erstellen",
  "clearBtn": "Entfernen",
  "invalidNumberMessage": "Der eingegebene Wert ist ungültig",
  "invalidRangeMessage": "Wert muss größer als 0 sein",
  "parseCoordinatesError": "Koordinaten können nicht analysiert werden. Überprüfen Sie die Eingabe.",
  "manualCoordinateInputInfo": "Geben Sie die Koordinaten manuell ein, und drücken Sie die <b>Eingabetaste</b>, um darauf zu zoomen",
  "selectDrawModeLabel": "Zeichenmodus auswählen",
  "selectFeatureLabel": "Feature aus diesem Layer auswählen"
});