define({
  "taskUrl": "URL задачі",
  "serviceURLPlaceholder": "Введіть URL задачі геообробки",
  "layerOrder": "Порядок шарів",
  "defaultValue": "Значення за замовчуванням",
  "inputFeatureBy": "Вхідний об'єкт за",
  "inputRecordBy": "Вхідний запис за",
  "renderer": "Рендерер",
  "displayType": "Тип відображення",
  "helpUrl": "URL довідки",
  "useResultMapService": "Переглянути результат за допомогою сервісу карти",
  "drawOnMap": "Інтерактивно намалювати на карті",
  "selectLayer": "Вибрати шар з карти",
  "selectTable": "Вибрати таблицю з карти",
  "shareResults": "Додати результат як робочий шар",
  "setTask": "Задати",
  "setTaskTitle": "Задати задачу GP",
  "enablePopup": "Активувати спливаюче вікно",
  "unSupportGeometryType": "Неможливо задати рендерер через невідомий тип геометрії.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Передати файл",
  "selectFileToUpload": "Вибрати файл...",
  "rasterFormat": "Формат растрових даних",
  "noFileSelected": "Файл не вибрано!",
  "uploadSuccess": "Файл успішно передано!",
  "showLayerContent": "Показати зміст шару",
  "urlPlaceholder": "URL для доступу до даних",
  "useShapefile": "Використовувати шейп-файл у локальній файловій системі",
  "allowToExport": "Дозволити експорт результатів",
  "useDynamicSchema": "Виведення може мати різні схеми; використовуйте динамічну схему замість попередньо визначеної.",
  "useCurrentMapExtent": "Використовувати поточний екстент карти",
  "ignoreOutput": "Ігнорувати це виведення",
  "turnOffOutput": "Вимкнути цей шар за замовчуванням",
  "inputJSONString": "Ввести рядок JSON"
});