define({
  "_widgetLabel": "Situācijas apzināšana",
  "locate_incident": "Atrast gadījumu",
  "reverse_geocoded_address": "Tuvākā adrese",
  "reverse_geocoded_error": "Nav pieejami",
  "now": "TŪLĪT",
  "wind": "VĒJŠ",
  "SUN": "SVĒTD.",
  "MON": "PIRMD.",
  "TUE": "OTRD.",
  "WED": "TREŠD.",
  "THU": "CETURTD.",
  "FRI": "PIEKTD.",
  "SAT": "SESTD.",
  "actionLabel": "Iestatīt izvietojumu",
  "drawPoint": "Zīmēt punktu",
  "drawLine": "Zīmēt līniju",
  "drawPolygon": "Zīmēt laukumu",
  "saveIncident": "Saglabāt",
  "clearIncident": "Sākt vēlreiz",
  "noFeaturesFound": "Nav atrasts neviens elements.",
  "downloadCSV": "Lejupielāde",
  "sum": "Summa",
  "min": "Minimums",
  "max": "Maksimums",
  "avg": "Vidējais",
  "count": "SKAITĪT",
  "area": "APGABALS",
  "length": "GARUMS",
  "update_btn": "Pabeigts",
  "delete_btn": "Dzēst",
  "get_directions": "Iegūt virzienus",
  "incident": "Negadījums",
  "incidents": "Negadījumi",
  "buffer": "Buferzona",
  "buffers": "Buferzonas",
  "weather": "Laikapstākļi",
  "poweredBy": "Darbina",
  "_featureAction_ActionLabel": "Iestatīt izvietojumu",
  "_featureAction_AddRemoveActionLabel": "Pievienot/noņemt izvietojumu",
  "snapshot": "Momentuzņēmumu mape, ko izveidoja lietotne ar šādu ID:",
  "user_credentials": "Lietotājam nav derīgu privilēģiju.",
  "snapshot_complete": "Momentuzņēmums ir veiksmīgi izveidots.",
  "snapshot_failed": "Neizdevās izveidot momentuzņēmumu.",
  "notPolySnapShot": "Pirms momentuzņēmuma izveidošanas norādiet buferzonas attālumu.",
  "notValidDownload": "Nav derīgu rezultātu, ko lejupielādēt.",
  "snapshot_append": "Momentuzņēmums",
  "of_append": "no",
  "layer_append": "slānis",
  "downloadAll": "Lejupielādēt visu",
  "createSnapshot": "Izveidot momentuzņēmumu",
  "calculated_results": "Informācijas kopsavilkums",
  "closest": "Tuvākais elements",
  "proximity": "Tuvums",
  "summary": "Kopsavilkums",
  "groupedSummary": "Grupētie rezultāti",
  "_count": "Skaits",
  "utc": "UTC",
  "approximate": "aptuvena vērtība",
  "snapshot_name": "Iestatīt momentuzņēmuma nosaukumu",
  "invalid_snapshot_name": "Nederīgs momentuzņēmuma nosaukums."
});