define({
  "_widgetLabel": "Análisis de amenazas",
  "threatAnalysisMainPageTitle": "Basado en la Guía de la lucha contra el terrorismo del JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Ubicación de entrada",
  "interactive": "Interactiva",
  "fromCoord": "Coordenada fija",
  "existingFeature": "De entidades existentes",
  "threatAnalysisCoordInputLabel": "Ubicación de la amenaza",
  "enterCoords": "Introducir coordenadas",
  "threatAddPointToolTip": "Agregar ubicación de la amenaza",
  "threatDrawPointToolTip": "Haga clic para agregar una ubicación de amenaza",
  "threatType": "Tipo de amenaza",
  "threatPlaceholder": "Comience a escribir para buscar una amenaza",
  "mandatoryLabel": "Distancia de evacuación obligatoria",
  "safeLabel": "Zona de refugio designado",
  "zoneTypeLabel": "Tipo de zona",
  "feetLabel": "Pies",
  "metersLabel": "Metros",
  "unitsLabel": "Unidades",
  "settingsTitle": "Ajustes",
  "mandatoryButtonLabel": "Configurar los ajustes de Distancia de evacuación obligatoria",
  "safeButtonLabel": "Configurar los ajustes de Refugio designado",
  "style": "Estilo",
  "lineStyles": {
    "esriSLSDash": "Guion",
    "esriSLSDashDot": "Guion Punto",
    "esriSLSDashDotDot": "Guion Punto Punto",
    "esriSLSDot": "Punto",
    "esriSLSLongDash": "Guion largo",
    "esriSLSLongDashDot": "Guion largo, Punto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Guion corto",
    "esriSLSShortDashDot": "Guion corto Punto",
    "esriSLSShortDashDotDot": "Guion corto Punto Punto",
    "esriSLSShortDot": "Corto Punto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Atrás",
    "esriSFSCross": "Cruz",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Hacia delante",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  },
  "resultsTitle": "Resultados",
  "publishTABtn": "Publicar",
  "layerName": "Nombre de capa publicado",
  "invalidLayerName": "El nombre de la capa solo debe contener caracteres alfanuméricos y guiones bajos",
  "missingLayerName": "Debe introducir un nombre para la capa",
  "missingLayerNameMessage": "Debe introducir un nombre de capa válido antes de publicar",
  "publishingFailedLayerExists": "Fallo de publicación: ya tiene un servicio de entidades denominado {0}. Elija otro nombre.",
  "checkService": "Comprobar servicio: {0}",
  "createService": "Crear servicio: {0}",
  "unableToCreate": "Imposible crear: {0}",
  "addToDefinition": "Agregar a definición: {0}",
  "successfullyPublished": "Capa web publicada correctamente{0}Administar la capa web",
  "userRole": "Imposible crear el servicio porque el usuario no tiene permisos",
  "transparencyLabel": "Transparencia",
  "outline": "Lista",
  "fill": "Relleno (el color solo se aplica si el estilo es sólido)",
  "createBtn": "Crear zonas",
  "clearBtn": "Borrar",
  "invalidNumberMessage": "El valor introducido no es válido",
  "invalidRangeMessage": "El valor debe ser mayor que 0",
  "parseCoordinatesError": "Imposible analizar las coordenadas. Compruebe la entrada."
});