define({
  "_widgetLabel": "Editor Inteligente",
  "_featureAction_SmartEditor": "Editor Inteligente",
  "noEditPrivileges": "A sua conta não tem permissão para criar ou modificar dados.",
  "widgetActive": "Ativo",
  "widgetNotActive": "Não Ativo",
  "pressStr": "Pressione ",
  "ctrlStr": " CTRL ",
  "snapStr": " para ativar o ajuste automático",
  "noAvailableTempaltes": "Modelos não disponíveis",
  "editorCache": " - Cache de Editor",
  "presetFieldAlias": "Campo",
  "presetValue": "Valor Predefinido",
  "usePresetValues": " Utilizar Valores Predefinidos (Novos elementos apenas)",
  "editGeometry": " Editar Geometria",
  "savePromptTitle": "Guardar elemento",
  "savePrompt": "Pretende guardar o elemento atual?",
  "deletePromptTitle": "Eliminar elemento",
  "deleteAttachment": "Eliminar anexo",
  "deletePrompt": "Tem a certeza que pretende eliminar o elemento selecionado?",
  "attachmentLoadingError": "Erro ao carregar anexos",
  "attachmentSaveDeleteWarning": "Aviso: As alterações aplicadas a anexos são guardadas automaticamente",
  "autoSaveEdits": "Guarda novo elemento automaticamente",
  "addNewFeature": "Criar novo elemento",
  "featureCreationFailedMsg": "Não é possível criar novo registo/elemento",
  "relatedItemTitle": "Tabela/Camada Relacionada",
  "relatedFeatureCount": "${layerTitle} com ${featureCount} elementos",
  "createNewFeatureLabel": "Criar um novo elemento para ${layerTitle}",
  "invalidRelationShipMsg": "Por favor, assegure que o campo chave primário: '${parentKeyField}' tem um valor válido",
  "pendingFeatureSaveMsg": "Por favpr, guarde as edições ao elemento antes de criar um elemento relacionado.",
  "attachmentsRequiredMsg": "(*) Os anexos são necessários.",
  "coordinatePopupTitle": "Mover elemento para localização XY",
  "coordinatesSelectTitle": "Sistema de Coordenadas:",
  "mapSpecialReferenceDropdownOption": "Referência Espacial do Mapa",
  "latLongDropdownOption": "Latitude/Longitude",
  "xAttributeTextBoxLabel": "Coordenada X:",
  "yAttributeTextBoxLabel": "Coordenada Y:",
  "latitudeTextBoxLabel": "Latitude:",
  "longitudeTextBoxLabel": "Longitude:",
  "presetGroupFieldsLabel": "'${groupName}' será aplicado aos seguintes campos de camada:",
  "presetGroupNoFieldsLabel": "'${groupName}' não tem quaisquer campos associados",
  "groupInfoLabel": "Informações do grupo para '${groupName}'",
  "editGroupInfoIcon": "Editar valor do grupo para ${groupName}",
  "filterEditor": {
    "all": "Todas",
    "noAvailableTempaltes": "Modelos não disponíveis",
    "searchTemplates": "Modelos Pesquisáveis",
    "filterLayerLabel": "Filtrar Camadas"
  },
  "invalidConfiguration": "O widget não se encontra configurado ou as camadas da configuração já não se encontram no mapa.  Por favor, abra a aplicação no modo de builder e reconfigure o widget.",
  "geometryServiceURLNotFoundMSG": "Não é possível obter o URL do Serviço de Geometria",
  "clearSelection": "Apagar",
  "refreshAttributes": "Atualizar atributos de elementos",
  "automaticAttributeUpdatesOn": "Atualizar atributos de elementos automaticamente: LIGADO",
  "automaticAttributeUpdatesOff": "Atualizar atributos de elementos automaticamente: DESLIGADO",
  "moveSelectedFeatureToGPS": "Mover elemento selecionado para a localização de GPS atual",
  "moveSelectedFeatureToXY": "Mover elemento selecionado para localização XY",
  "mapNavigationLocked": "Navegação de Mapa: Bloqueada",
  "mapNavigationUnLocked": "Navegação de Mapa: Desbloqueada",
  "copyFeatures": {
    "title": "Copiar Elementos",
    "createFeatures": "Criar Elementos",
    "createSingleFeature": "Criar 1 Elemento de Multi-Geometria",
    "noFeaturesSelectedMessage": "Sem Elementos Selecionados",
    "selectFeatureToCopyMessage": "Por favor, selecione elementos para copiar.",
    "multipleFeatureSaveWarning": "Nota: a criação de múltiplos elementos utilizando copiar elemento irá guardar todos os elementos de imediato"
  },
  "addingFeatureError": "Erro ao adicionar os elementos selecionados na camada. Tente novamente.",
  "addingFeatureErrorCount": "Não foi possível copiar '${copyFeatureErrorCount}' elementos.",
  "selectingFeatureError": "Erro ao selecionar elementos na camada. Tente novamente.",
  "customSelectOptionLabel": "Selecionar elementos para copiar",
  "noFeatureSelectedMessage": "Nenhum elemento selecionado.",
  "multipleFeatureSaveMessage": "Todos os elementos serão guardados de imediato. Pretende continuar?",
  "relativeDates": {
    "dateTypeLabel": "Tipo de Dados",
    "valueLabel": "Valor",
    "fixed": "Corrigido",
    "current": "Actual",
    "past": "Passados",
    "future": "Futuro",
    "popupTitle": "Selecionar Valor",
    "hintForFixedDateType": "Sugestão: a data e hora especificadas serão utilizadas como valor padrão predefinido.",
    "hintForCurrentDateType": "Sugestão: a data e hora atuais serão utilizadas como valor padrão predefinido.",
    "hintForPastDateType": "Sugestão: o valor especificado será subtraído à data e hora atuais para o valor padrão da definição.",
    "hintForFutureDateType": "Sugestão: o valor especificado será adicionado à data e hora atuais para o valor padrão da definição.",
    "noDateDefinedTooltip": "Nenhuma data definida",
    "relativeDateWarning": "Deve ser especificado um valor para a data ou hora para permitir guardar o valor padrão predefinido."
  }
});