define({
  "_widgetLabel": "Anàlisi d'amenaces",
  "threatAnalysisMainPageTitle": "Es basa en la guia antiterrorisme del JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Ubicació d'entrada",
  "interactive": "Interactiva",
  "fromCoord": "Coordenada fixa",
  "existingFeature": "Des de les entitats existents",
  "threatAnalysisCoordInputLabel": "Ubicació de l'amenaça",
  "enterCoords": "Introduïu les coordenades",
  "threatAddPointToolTip": "Afegeix la ubicació de l'amenaça",
  "threatDrawPointToolTip": "Feu clic per afegir la ubicació de l'amenaça",
  "threatType": "Tipus d'amenaça",
  "threatPlaceholder": "Comenceu a escriure per cercar una amenaça",
  "mandatoryLabel": "Distància d'evacuació obligatòria",
  "safeLabel": "Zona de refugi existent",
  "zoneTypeLabel": "Tipus de zona",
  "feetLabel": "Peus",
  "metersLabel": "Metres",
  "unitsLabel": "Unitats",
  "settingsTitle": "Configuració",
  "mandatoryButtonLabel": "Configura la distància d'evacuació obligatòria",
  "safeButtonLabel": "Configura les opcions del refugi existent",
  "style": "Estil",
  "lineStyles": {
    "esriSLSDash": "Guió",
    "esriSLSDashDot": "Guió punt",
    "esriSLSDashDotDot": "Guió punt punt",
    "esriSLSDot": "Punt",
    "esriSLSLongDash": "Guió llarg",
    "esriSLSLongDashDot": "Guió llarg punt",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Guió curt",
    "esriSLSShortDashDot": "Guió curt punt",
    "esriSLSShortDashDotDot": "Guió curt punt punt",
    "esriSLSShortDot": "Punt",
    "esriSLSSolid": "Cos geomètric"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Enrere",
    "esriSFSCross": "Creu",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Endavant",
    "esriSFSHorizontal": "Horitzontal",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Cos geomètric",
    "esriSFSVertical": "Vertical"
  },
  "resultsTitle": "Resultats",
  "publishTABtn": "Publica",
  "layerName": "Nom de la capa publicada",
  "invalidLayerName": "El nom de la capa només pot contenir caràcters alfanumèrics i de subratllat",
  "missingLayerName": "Heu d'introduir un nom per a la capa",
  "missingLayerNameMessage": "Heu d'introduir un nom de capa vàlid per poder fer la publicació",
  "publishingFailedLayerExists": "Error de publicació: ja teniu un servei d'entitats anomenat {0}. Trieu un altre nom.",
  "checkService": "Comprova el servei: {0}",
  "createService": "Crea el servei: {0}",
  "unableToCreate": "No es pot crear: {0}",
  "addToDefinition": "Afegeix a la definició: {0}",
  "successfullyPublished": "S'ha publicat correctament la capa web{0}Administra la capa web",
  "userRole": "No es pot crear el servei perquè l'usuari no té permisos",
  "transparencyLabel": "Transparència",
  "outline": "Contorn",
  "fill": "Emplenament (el color només s'aplica quan l'estil està definit com a cos geomètric)",
  "createBtn": "Crea zones",
  "clearBtn": "Esborra",
  "invalidNumberMessage": "El valor que s'ha introduït no és vàlid",
  "invalidRangeMessage": "El valor ha de ser més gran que 0",
  "parseCoordinatesError": "No es poden analitzar les coordenades. Comproveu l'entrada."
});