define({
  "_widgetLabel": "Analisi delle minacce",
  "threatAnalysisMainPageTitle": "Basata sulla guida antiterrorismo della JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Posizione di input",
  "interactive": "Interattivo",
  "fromCoord": "Coordinata fissa",
  "existingFeature": "Da feature esistenti",
  "threatAnalysisCoordInputLabel": "Posizione della minaccia",
  "enterCoords": "Immettere le coordinate",
  "threatAddPointToolTip": "Aggiungi posizione della minaccia",
  "threatDrawPointToolTip": "Fare clic per aggiungere la posizione della minaccia",
  "threatType": "Tipo di minaccia",
  "threatPlaceholder": "Iniziare a digitare per cercare una minaccia",
  "mandatoryLabel": "Distanza di evacuazione obbligatoria",
  "safeLabel": "Zona del rifugio sul posto",
  "zoneTypeLabel": "Tipo di zona",
  "feetLabel": "Piedi",
  "metersLabel": "Metri",
  "unitsLabel": "Unità",
  "settingsTitle": "Impostazioni",
  "mandatoryButtonLabel": "Configurare le impostazioni della distanza di evacuazione obbligatoria",
  "safeButtonLabel": "Configurare le impostazioni del rifugio sul posto",
  "style": "Stile",
  "lineStyles": {
    "esriSLSDash": "Trattino",
    "esriSLSDashDot": "Trattino punto",
    "esriSLSDashDotDot": "Trattino Punto Punto",
    "esriSLSDot": "Punto",
    "esriSLSLongDash": "Trattino lungo",
    "esriSLSLongDashDot": "Trattino lungo punto",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Trattino corto",
    "esriSLSShortDashDot": "Trattino corto punto",
    "esriSLSShortDashDotDot": "Trattino corto punto punto",
    "esriSLSShortDot": "Punto corto",
    "esriSLSSolid": "Tinta unita"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Indietro",
    "esriSFSCross": "Croce",
    "esriSFSDiagonalCross": "Diagonale",
    "esriSFSForwardDiagonal": "Avanti",
    "esriSFSHorizontal": "Orizzontale",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Tinta unita",
    "esriSFSVertical": "Verticale"
  },
  "resultsTitle": "Risultati",
  "publishTABtn": "Pubblica",
  "layerName": "Nome del layer pubblicato",
  "invalidLayerName": "Il nome del layer deve contenere soltanto caratteri alfanumerici e sottolineature",
  "missingLayerName": "È necessario inserire un nome per il layer",
  "missingLayerNameMessage": "È necessario inserire un nome valido per il layer prima della pubblicazione",
  "publishingFailedLayerExists": "Pubblicazione non riuscita: esiste già un Feature Service chiamato {0}. Scegliere un altro nome.",
  "checkService": "Verifica servizio: {0}",
  "createService": "Crea servizio: {0}",
  "unableToCreate": "Creazione non riuscita: {0}",
  "addToDefinition": "Aggiungi a definizione: {0}",
  "successfullyPublished": "Web Layer pubblicato con successo{0}Gestisci  Web Layer",
  "userRole": "Impossibile creare il servizio poiché l’utente non dispone delle autorizzazioni.",
  "transparencyLabel": "Trasparenza",
  "outline": "Bordo",
  "fill": "Riempimento (Il colore si applica solo quando lo stile è impostato su tinta unita)",
  "createBtn": "Crea zone",
  "clearBtn": "Cancellare",
  "invalidNumberMessage": "Il valore immesso non è valido",
  "invalidRangeMessage": "Il valore deve essere maggiore di 0",
  "parseCoordinatesError": "Impossibile analizzare le coordinare. Controllare l’input."
});