define({
  "_widgetLabel": "Attālums un virziens",
  "tabLineTitle": "Līnija",
  "tabCircleTitle": "Aplis",
  "tabEllipseTitle": "Elipse",
  "tabRingsTitle": "Riņķi",
  "multipleNotationsMessage": " notācijas, kas atbilst jūsu ievadei. Lūdzu, apstipriniet, kuras vēlaties izmantot:",
  "invalidCoordinateMessage": "Nederīga koordināta",
  "confirmInputNotationMessage": "Apstiprināt ievades notāciju",
  "prefixSuffixMessage": "Tika konstatēts, ka ievades koordinātas platuma vai garuma vērtībai ir gan prefikss, gan sufikss. Atgrieztās koordinātas pamatā ir prefikss.",
  "rememberDecisionMessage": "Atcerēties manu izvēli un vairs nejautāt.<br/>",
  "majorAxisTooltipMessage": "Noklikšķiniet uz galvenās ass garuma",
  "minorAxisTooltipMessage": "Pārvietojiet peli atpakaļ uz sākuma pozīciju, lai iestatītu palīgasi un pabeigtu elipses zīmēšanu",
  "clickToFinishLineMessage": "Noklikšķiniet, lai pabeigtu līnijas zīmēšanu",
  "doubleClickEllipseMesage": "Veiciet dubultklikšķi, lai pabeigtu diapazona gredzenu zīmēšanu",
  "invalidCoordinateTypeMessage": "Nevar noteikt ievades koordinātu tipu. Lūdzu, pārbaudiet ievadi",
  "noCenterPointSetMessage": "Nav iestatīts centra punkts. Lūdzu, pārbaudiet ievadi",
  "ellipseMajorAxis": "Galvenā ass",
  "ellipseMinorAxis": "Palīgass",
  "degreesRangeMessage": "Vērtībai ir jābūt no 0 līdz 360",
  "millsRangeMessage": "Vērtībai ir jābūt no 0 līdz 6400",
  "lengthLabel": "Garums",
  "angleLabel": "Leņķis",
  "startPointLabel": "Sākuma punkts",
  "endPointLabel": "Beigu punkts",
  "centerPointLabel": "Centra punkts",
  "distanceTableErrorMessage": "Attālumu tabula ir tukša. Lūdzu, ievadiet dažus attālumus.",
  "setCoordFormatStringMessage": "Iestatīt koordinātu formātu virkni",
  "prefixMessage": "Pievienot prefiksu '+/-' pozitīviem un negatīviem skaitļiem",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "GMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)",
  "DDLatLongNotation": "Decimālgrādi — platums/garums",
  "DDLongLatNotation": "Decimālgrādi — garums/platums",
  "DDMLatLongNotation": "Grādi, decimālminūtes — platums/garums",
  "DDMLongLatNotation": "Grādi, decimālminūtes — garums/platums",
  "DMSLatLongNotation": "Grādi, minūtes, sekundes — platums/garums",
  "DMSLongLatNotation": "Grādi, minūtes, sekundes — garums/platums",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM — joslas burts",
  "UTMHemNotation": "UTM — puslode (Z/D)",
  "circleTitle": "Izveidot apli no:",
  "radiusLabel": "Rādiuss",
  "diameterLabel": "Diametrs",
  "startPointPlaceHolderLabel": "Ievadīt koordinātas",
  "formatInputLabel": "Formatēt ievadi",
  "drawCircleLabel": "Zīmēt apli",
  "drawLineLabel": "Zīmēt līniju",
  "createCircleInteractivelyLabel": "Izveidot apli interaktīvi",
  "rangeErrorMessage": "Nederīgs rādiuss vai diametrs",
  "numericInvalidMessage": "Lūdzu, ievadiet skaitlisku vērtību",
  "timeLabel": "Laiks",
  "invalidTimeMessage": "Nederīga laika vērtība",
  "hoursLabel": "Stundas",
  "minutesLabel": "Minūtes",
  "secondsLabel": "Sekundes",
  "rateLabel": "Ātrums",
  "invalidDistanceMessage": "Nederīga attāluma vērtība",
  "feetSecondsLabel": "Pēdas/sekunde",
  "feetHourLabel": "Pēdas/stunda",
  "kmSecondLabel": "Kilometri/sekunde",
  "kmHourLabel": "Kilometri/stunda",
  "metersSecondLabel": "Metri/sekunde",
  "metersHourLabel": "Metri/stunda",
  "milesSecondLabel": "Jūdzes/sekunde",
  "milesHourLabel": "Jūdzes/stunda",
  "nauticalMilesSecondLabel": "Jūras jūdzes/sekunde",
  "nauticalMilesHourLabel": "Jūras jūdzes/stunda",
  "clearGraphicsLabel": "Notīrīt grafiku",
  "ellipseTypeLabel": "Elipses veids",
  "ellipseSemiLabel": "Puse",
  "ellipseFullLabel": "Pilna",
  "drawEllipseLabel": "Zīmēt elipsi",
  "createEllipseInteractively": "Izveidot elipsi interaktīvi",
  "axisLabel": "Ass",
  "unitLabel": "Mērvienība",
  "majorRadiusLabel": "Galvenā (rādiuss)",
  "majorDiameterLabel": "Galvenā (diametrs)",
  "axisErrorMessage": "Vērtībai jābūt lielākai par 0",
  "minorRadiusLabel": "Palīgass (rādiuss)",
  "minorDiameterLabel": "Palīgass (diametrs)",
  "orientationLabel": "Orientācija",
  "orientationErrorMessage": "Vērtībai ir jābūt no 0 līdz 360",
  "warningMessage": "Brīdinājums: ar elipses rīku ģenerētā grafika nav ģeodēziska",
  "fromLabel": "No",
  "distanceBearingLabel": "Attālums un virziens",
  "pointsLabel": "Punkti",
  "createLineInteractively": "Izveidot līniju interaktīvi",
  "lineLengthErrorMessage": "Nederīgs līnijas garums",
  "degreesLabel": "Grādi",
  "milsLabel": "Miliradiāni",
  "lineTypeLabel": "Veids",
  "interactiveLabel": "Interaktīvs",
  "fixedLabel": "Fiksēts",
  "originLabel": "Koordinātu sākuma punkts",
  "cumulativeLabel": "Kumulatīvs",
  "numberOfRingsLabel": "Gredzenu skaits",
  "ringsErrorMessage": "Nederīgs gredzenu skaits",
  "distanceBetweenRingsLabel": "Attālums starp gredzeniem",
  "ringsDecimalErrorMessage": "Ievadiet skaitlisku vērtību 2 decimāldaļu vietās",
  "distanceUnitsLabel": "Garuma vienības",
  "distancesLabel": "Attālumi",
  "numberOfRadialsLabel": "Radiālu skaits",
  "upLabel": "Augšup",
  "downLabel": "Lejup",
  "deleteLabel": "Izdzēst",
  "radialsErrorMessage": "Nederīgs radiālu skaits. Atļautais maksimums ir 360",
  "radialsInvalidMessage": "Nederīga radiālu vērtība",
  "addPointLabel": "Pievienot punktu",
  "valueLabel": "Vērtība",
  "valueText": "Ievadiet vērtību",
  "actionLabel": "Darbība",
  "distanceCalculatorLabel": "Attāluma kalkulators",
  "abbrevMetersLabel": "m",
  "abbrevFeetLabel": "pēdas",
  "abbrevKmLabel": "km",
  "abbrevMilesLabel": "jūdzes",
  "abbrevYardsLabel": "jardi",
  "abbrevNauticalMilesLabel": "jj",
  "abbrevDegreesLabel": "°",
  "abbrevMilsLabel": "mm",
  "abbrevHoursLabel": "gar.",
  "abbrevMinutesLabel": "m",
  "abbrevSecondsLabel": "s",
  "abbrevFeetSecondsLabel": "pēdas/s",
  "abbrevFeetHourLabel": "pēdas/st.",
  "abbrevKmSecondLabel": "km/s",
  "abbrevKmHourLabel": "km/h",
  "abbrevMetersSecondLabel": "m/s",
  "abbrevMetersHourLabel": "m/st.",
  "abbrevMilesSecondLabel": "jūdzes/s",
  "abbrevMilesHourLabel": "jūdzes/st.",
  "abbrevNauticalMilesSecondLabel": "jj/s",
  "abbrevNauticalMilesHourLabel": "jj/st.",
  "publishDDBtn": "Publicēt",
  "publishTitle": "Publicēt grafikas",
  "ddLayerName": "Publicētā slāņa nosaukums",
  "missingDDLayerName": "Jums jāievada slāņa nosaukums",
  "publishToNewLayer": "Publicēt rezultātus jaunā elementu slānī",
  "checkService": "Pārbaudīt servisu: {0}.",
  "createService": "Izveidot servisu: {0}",
  "unableToCreate": "Nevar izveidot: {0}",
  "addToDefinition": "Pievienot definīcijai: {0}",
  "successfullyPublished": "Veiksmīgi publicēts tīmekļa slānis{0}Pārvaldīt tīmekļa slāni",
  "userRole": "Nevar izveidot servisu, jo lietotājam nav atļauju",
  "missingLayerNameMessage": "Lai varētu publicēt, jāievada derīgs slāņa nosaukums",
  "invalidLayerName": "Slāņa nosaukums var saturēt tikai burtu un ciparu rakstzīmes, kā arī pasvītrojumus.",
  "distanceLabel": "Attālums",
  "radiusDistance": "Rādiusa attālums",
  "radials": "Radiālie",
  "rings": "Apļi",
  "orientationUnit": "Orientācijas mērvienība",
  "radiusUnit": "Rādiusa mērvienība",
  "angleUnitLabel": "Leņķa mērvienība"
});