define({
  "_widgetLabel": "Przeliczanie współrzędnych",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "formatInput": "Formatuj dane wejściowe",
  "copyAll": "Kopiuj wszystko",
  "copySuccessful": "Skopiowano pomyślnie",
  "copyFailed": "Nie można skopiować. Zamiast tego użyj kombinacji klawiszy ctrl+c.",
  "parseCoordinatesError": "Nie można przeanalizować współrzędnych. Sprawdź dane wejściowe.",
  "comfirmInputNotation": "Potwierdź notację danych wejściowych",
  "latLongWarningMessage": "Wykryto, że współrzędna wejściowa zawiera prefiks i sufiks wartości szerokości lub długości geograficznej. Zwracana współrzędna jest oparta na prefiksie.",
  "inputLabel": "Dane wejściowe",
  "outputLabel": "Dane wynikowe",
  "cancelButtonLabel": "Anuluj",
  "applyButtonLabel": "Zastosuj",
  "posNegPrefixLabel": "Dodaj prefiks \"+/-\" do liczb dodatnich i ujemnych",
  "editCoordinateDialogTitle": "Skonfiguruj ciąg znakowy formatu współrzędnych",
  "rememberDecisionLabel": "Zapamiętaj moją decyzję i nie pytaj ponownie.<br/>",
  "coordinateInputLabel": "Wprowadź współrzędne lub kliknij mapę.",
  "zoomLabel": "Zmiana skali",
  "multipleNotationLabel": "— liczba znalezionych notacji zgodnych z danymi wejściowymi. Wybierz, której notacji chcesz użyć:",
  "copyToClipboard": "Kopiuj do schowka",
  "formatOutput": "Formatuj dane wynikowe",
  "addNewNotation": "Dodaj nową notację",
  "notationAddedMessage": "Dodano nową notację",
  "addLabel": "Dodaj",
  "removeCoordinate": "Usuń współrzędną",
  "expandOutput": "Rozwiń dane wynikowe"
});