define({
  "transparencyLabel": "שקיפות",
  "outline": "קו מתאר",
  "fill": "מילוי (הצבע חל רק כשהסגנון הוא 'מלא')",
  "style": "סגנון",
  "mandatoryLabel": "מרחק פינוי חובה",
  "mandatoryButtonLabel": "קבע את ההגדרות של מרחק פינוי החובה",
  "safeLabel": "מרחק פינוי בטוח",
  "safeButtonLabel": "קבע את ההגדרות של מרחק הפינוי הבטוח",
  "selectOpLayerLabel": "בחר שכבת תפעול לקבלת תוצאות",
  "selectDefaultMeasurementLabel": "בחר יחידת מידה שתהווה ברירת מחדל",
  "helpIconTooltip": "הרשימה של שכבת התפעול מתמלאת בשכבות מה-Web Map הנוכחית, שסוג הגיאומטריה שלהן הוא פוליגון.",
  "lineStyles": {
    "esriSLSDash": "מקווקו",
    "esriSLSDashDot": "קו נקודה",
    "esriSLSDashDotDot": "קו נקודה נקודה",
    "esriSLSDot": "נקודה",
    "esriSLSLongDash": "קו ארוך",
    "esriSLSLongDashDot": "קו נקודה ארוך",
    "esriSLSNull": "ריק",
    "esriSLSShortDash": "קו קצר",
    "esriSLSShortDashDot": "קו נקודה קצר",
    "esriSLSShortDashDotDot": "קו נקודה נקודה קצר",
    "esriSLSShortDot": "נקודה קצרה",
    "esriSLSSolid": "מלא"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "לאחור",
    "esriSFSCross": "צלב",
    "esriSFSDiagonalCross": "אלכסוני",
    "esriSFSForwardDiagonal": "לפנים",
    "esriSFSHorizontal": "אופקי",
    "esriSFSNull": "ריק",
    "esriSFSSolid": "מלא",
    "esriSFSVertical": "אנכי"
  },
  "threatTypeLabel": "סוג איום",
  "symbologyLabel": "סימבולוגיה",
  "generalLabel": "כללי",
  "addThreatTypesLabel": "הוסף סוג איום",
  "threatTypeColLabel": "סוג איום",
  "actions": "פעולות",
  "newThreatTypePopupLabel": "סוג איום חדש",
  "chooseDefaultThreatTypeIconLabel": "בחר מתוך ברירת מחדל",
  "mandatoryDistance": "מרחק פינוי חובה",
  "safeDistance": "מרחק פינוי בטוח",
  "units": "יחידות",
  "chooseDefaultThreatLabel": "בחר סוג איום שמוגדר כברירת מחדל",
  "defaultThreatTypePopUpLabel": "סוגי איום שמוגדרים כברירת מחדל",
  "editThreatLabel": "ערוך איום",
  "defaultThreatTypeIconTooltip": "רשימת סוגי איומים שמוגדרים כברירת מחדל",
  "uniqueThreatTypeMsg": "הזן סוג איום ייחודי, סוג איום בשם זה כבר קיים.",
  "requiredThreatTypeMsg": "זהו שדה חובה",
  "unitMeasureLabel": "מרחקים הם ב-{0}",
  "pipeBombLabel": "פצצת צינור",
  "suicideBombLabel": "פצצה של מתאבדים",
  "briefcaseLabel": "מזוודה",
  "carLabel": "מכונית",
  "suvVanLabel": "רכב קרוסאובר/ואן",
  "smallDeliveryTruckLabel": "משאית קטנה",
  "containerWaterTruckLabel": "משאית מכולה/להובלת מים",
  "semiTrailerLabel": "סמיטריילר"
});