define({
  "showArcgisBasemaps": "Inclui Mapas Base do Portal",
  "add": "Clique para Adicionar um Novo Mapa Base",
  "edit": "Propriedades",
  "titlePH": "Título do Mapa Base",
  "thumbnailHint": "Clique na imagem para atualizar",
  "urlPH": "URL da Camada",
  "addlayer": "Adicionar Mapa Base",
  "warning": "Entrada incorreta",
  "save": "Voltar e Salvar",
  "back": "Voltar e Cancelar",
  "addUrl": "Adicionar URL",
  "autoCheck": "Verificação Automática",
  "checking": "Verificando...",
  "result": "Salvo com sucesso",
  "spError": "Todo os mapas base adicionados na galeria precisam ter a mesma referência espacial.",
  "invalidTitle1": "Um mapa base '",
  "invalidTitle2": "' já existe. Escolha outro título.",
  "invalidBasemapUrl1": "Este tipo de camada não pode ser utilizada como um mapa base.",
  "invalidBasemapUrl2": "O mapa base que você está adicionando tem uma referência espacial diferente do mapa atual.",
  "addBaselayer": "Adicionar Camada de Mapa Base"
});