define({
  "layerSelect": "Velg bildelaget",
  "displayMeasureResultInPopup": "Vis måleresultater i en popup",
  "angularUnitSelect": "Standard vinkelenhet",
  "linearUnitSelect": "Standard lineærenhet",
  "areaUnitSelect": "Standard arealenhet",
  "displayOperationSelect": "Velg måleoperasjoner",
  "errorSectionMessage": "Ingen av lagene støtter målingsfunksjoner.",
  "unitLabel": {
    "esriInches": "Tommer",
    "esriFeet": "Fot",
    "esriYards": "Yards",
    "esriMiles": "Miles",
    "esriNauticalMiles": "Nautiske mil",
    "esriMillimeters": "Millimeter",
    "esriCentimeters": "Centimeter",
    "esriDecimeters": "Desimeter",
    "esriMeters": "Meter",
    "esriKilometers": "Kilometer",
    "esriDURadians": "Radianer",
    "esriDUDecimalDegrees": "Grader",
    "esriSquareInches": "tommer²",
    "esriSquareFeet": "fot²",
    "esriSquareYards": "yard²",
    "esriAcres": "acre",
    "esriSquareMiles": "miles²",
    "esriSquareMillimeters": "mm²",
    "esriSquareCentimeters": "cm²",
    "esriSquareDecimeters": "dm²",
    "esriSquareMeters": "m²",
    "esriAres": "ar",
    "esriHectares": "hektar",
    "esriSquareKilometers": "km²"
  },
  "operationLabel": {
    "esriMensurationPoint": "Lokasjon",
    "esriMensurationDistanceAndAngle": "Avstand og vinkel",
    "esriMensurationAreaAndPerimeter": "Areal og omkrets",
    "esriMensurationHeightFromBaseAndTop": "Høyde: Bunn til topp",
    "esriMensurationHeightFromBaseAndTopShadow": "Høyde: Bunn til topp skygge",
    "esriMensurationHeightFromTopAndTopShadow": "Høyde: Topp til topp skygge",
    "esriMensurationCentroid": "Tyngdepunkt",
    "esriMensurationPoint3D": "Lokasjon (3D)",
    "esriMensurationDistanceAndAngle3D": "Avstand og vinkel (3D)",
    "esriMensurationAreaAndPerimeter3D": "Areal og omkrets (3D)",
    "esriMensurationCentroid3D": "Tyngdepunkt (3D)"
  }
});