define({
  "add": "Feu clic per afegir nou",
  "title": "Títol",
  "placeholderBookmarkName": "Nom del marcador",
  "ok": "D'acord",
  "cancel": "Cancel·la",
  "warning": "Acabeu l'edició.",
  "edit": "Edita el marcador",
  "errorNameExist": "El marcador ja existeix.",
  "errorNameNull": "Nom de marcador no vàlid.",
  "addBookmark": "Crea'n un de nou",
  "thumbnail": "Miniatura",
  "thumbnailHint": "Feu clic a la imatge per actualitzar-la",
  "displayBookmarksAs": "Mostra els marcadors com a",
  "cards": "Targetes",
  "list": "Llista",
  "cardsTips": "Visualització de targetes",
  "listTips": "Visualització de llista",
  "makeAsDefault": "Defineix-lo per defecte",
  "default": "Per defecte",
  "editable": "Permeteu afegir marcadors al widget.",
  "alwaysSync": "Mostra marcadors del mapa web",
  "configCustom": "Mostra marcadors personalitzats",
  "import": "Importa",
  "create": "Crea",
  "importTitle": "Importa marcadors",
  "importFromWeb": "Importa els marcadors del mapa web actual",
  "selectAll": "Selecciona-ho tot",
  "noBookmarkInConfig": "Feu clic a \"Importa\" o a \"Crea'n un de nou\" per afegir marcadors.",
  "noBookmarkInWebMap": "No hi ha cap marcador configurat al mapa.",
  "extent": "Extensió",
  "saveExtent": "Desa l'extensió de mapa en aquest marcador",
  "savelayers": "Desa la visibilitat de la capa",
  "withVisibility": "Amb visibilitat de capes",
  "bookmark": "Marcador",
  "addBtn": "Afegeix",
  "deleteBtn": "Suprimeix",
  "editBtn": "Edita",
  "dragReorderTip": "Mantén i arrossega per reordenar-ho",
  "deleteBtnTip": "Suprimeix el marcador",
  "editBtnTip": "Edita el marcador"
});