define(
   ({
    addLayer: "Lisa kiht",
    layerName: "Kiht",
    layerRefresh: "Värskenda",
    layerLabel: "Märgis",
    actions: "Toimingud",
    popupOk: "OK",
    popupCancel: "Tühista",
    mainPanelTextPlaceholder: "nt TINGIMUSED MAANTEEDEL",
    invalidInterval: "Toetatud on ainult numbrid.",
    uploadImage: "Lae üles pilt",
    iconColumnText: "Ikoon",
    refreshInterval: "1 \'Hinnatud vahemaa minutites\'",
    refreshIntervalTitle: "Hinnatud vahemaa minutites",
    mainPanelText: "Peapaneeli tekst",
    mainPanelIcon: "Peapaneeli pilt",
    refreshIntervalInstruction: "Värskendamise intervall",
    optionsText: "Valikud",
    symbolOptionsText: "Sümbolivalikud",
    iconOptionsText: "Ikoonivalikud",
    sympolPopupTitle: "Määra sümbol",
    rdoLayer: "Kohandatud sümbol",
    rdoCustom: "Kohandatud sümbol",
    chkCluster: "Luba klasterdamine",
    defineClusterSymbol: "Klastri sümbol",
    defineThemeClusterSymbol: "Klastri sümbol teemast",
    rdoEsri: "Esri sümbol",
    rdoLayerIcon: "Kasuta sümbolit ikoonina",
    rdoCustomIcon: "Laadi kohandatud sümbol üles",
    editCustomSymbol: "Muuda kohandatud sümbolit",
    editCustomIcon: "Muuda kohandatud ikooni",
    missingRefreshValue: "Sisestage värskendamise intervalli väärtus",
    panelIconOption: "Kuva paneeli päis",
    enableRefresh: "Luba kihi värskendamine",
    disableRefresh: "Kihi värskendamine on toetatud ainult objektide kogumite puhul",
    layer_type_not_supported: "Kihi tüüpi ei toetata: "
  })
);
