define({
  "transparencyLabel": "Διαφάνεια",
  "outline": "Περίγραμμα",
  "fill": "Γέμισμα (Το χρώμα εφαρμόζεται μόνο όταν έχετε καθορίσει τη χρήση του συμπαγούς στιλ.)",
  "style": "Στιλ",
  "mandatoryLabel": "Υποχρεωτική απόσταση εκκένωσης",
  "mandatoryButtonLabel": "Διαμόρφωση ρυθμίσεων υποχρεωτικής απόστασης εκκένωσης",
  "safeLabel": "Ασφαλής απόσταση εκκένωσης",
  "safeButtonLabel": "Διαμόρφωση ρυθμίσεων ασφαλούς απόστασης εκκένωσης",
  "selectOpLayerLabel": "Επιλέξτε ένα λειτουργικό θεματικό επίπεδο για αποτελέσματα.",
  "selectDefaultMeasurementLabel": "Επιλέξτε μια προεπιλεγμένη μονάδα μέτρησης.",
  "helpIconTooltip": "Η λίστα των λειτουργικών θεματικών επιπέδων συμπληρώνεται με θεματικά επίπεδα τύπου γεωμετρίας πολυγώνου από τον τρέχοντα web χάρτη.",
  "lineStyles": {
    "esriSLSDash": "Παύλα",
    "esriSLSDashDot": "Παύλα τελεία",
    "esriSLSDashDotDot": "Παύλα τελεία τελεία",
    "esriSLSDot": "Τελεία",
    "esriSLSLongDash": "Μεγάλη παύλα",
    "esriSLSLongDashDot": "Μεγάλη παύλα τελεία",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Μικρή παύλα",
    "esriSLSShortDashDot": "Μικρή παύλα τελεία",
    "esriSLSShortDashDotDot": "Μικρή παύλα τελεία τελεία",
    "esriSLSShortDot": "Μικρή τελεία",
    "esriSLSSolid": "Συμπαγές"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Προς τα πίσω",
    "esriSFSCross": "Σταυρός",
    "esriSFSDiagonalCross": "Διαγώνια",
    "esriSFSForwardDiagonal": "Προώθηση",
    "esriSFSHorizontal": "Οριζόντια",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Συμπαγές",
    "esriSFSVertical": "Κατακόρυφα"
  },
  "threatTypeLabel": "Τύπος απειλής",
  "symbologyLabel": "Συμβολολογία",
  "generalLabel": "Γενική",
  "addThreatTypesLabel": "Προσθήκη τύπου απειλής",
  "threatTypeColLabel": "Τύπος απειλής",
  "actions": "Ενέργειες",
  "newThreatTypePopupLabel": "Νέος τύπος απειλής",
  "chooseDefaultThreatTypeIconLabel": "Επιλογή από προεπιλεγμένους τύπους",
  "mandatoryDistance": "Υποχρεωτική απόσταση εκκένωσης",
  "safeDistance": "Ασφαλής απόσταση εκκένωσης",
  "units": "Μονάδες",
  "chooseDefaultThreatLabel": "Επιλογή ενός προεπιλεγμένου τύπου απειλής",
  "defaultThreatTypePopUpLabel": "Προεπιλεγμένοι τύποι απειλής",
  "editThreatLabel": "Επεξεργασία απειλής",
  "defaultThreatTypeIconTooltip": "Λίστα προεπιλεγμένων τύπων απειλής",
  "uniqueThreatTypeMsg": "Καταχωρίστε έναν μοναδικό τύπο απειλής. Ο τύπος απειλής με το όνομα αυτό ήδη υπάρχει.",
  "requiredThreatTypeMsg": "Αυτό το πεδίο είναι απαιτούμενο.",
  "unitMeasureLabel": "Οι αποστάσεις είναι σε {0}.",
  "pipeBombLabel": "Βόμβα σε μεταλλικό σωλήνα",
  "suicideBombLabel": "Βόμβα αυτοκτονίας",
  "briefcaseLabel": "Χαρτοφύλακας",
  "carLabel": "Αυτοκίνητο",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Μικρό φορτηγό παραδόσεων",
  "containerWaterTruckLabel": "Φορτηγό με κοντέινερ/Υδροφόρα",
  "semiTrailerLabel": "Ημιρυμουλκούμενο"
});