define({
  "defaultAreaUnit": "Oletuspinta-alayksikkö",
  "defaultLengthUnit": "Oletuspituusyksikkö",
  "acres": "Eekkeriä",
  "sqMiles": "Neliömailia",
  "sqKilometers": "Neliökilometriä",
  "hectares": "Hehtaaria",
  "sqYards": "Neliöjaardia",
  "sqFeet": "Neliöjalkaa",
  "sqFeetUS": "Neliöjalkaa (Yhdysvallat)",
  "sqMeters": "Neliömetriä",
  "miles": "Mailia",
  "kilometers": "Kilometriä",
  "feet": "Jalkaa",
  "feetUS": "Jalkaa (Yhdysvallat)",
  "meters": "Metriä",
  "yards": "Jaardia",
  "nauticalMiles": "Meripeninkulmaa",
  "showArea": "Alue",
  "showDistance": "Etäisyys",
  "showLocation": "Sijainti",
  "showtools": "Näytä mittaustyökalut:",
  "operationalLayer": "Lisää mittagrafiikka kartan toiminnallisena karttatasona.",
  "allHidedTips": "Vähintään yksi työkalu on valittava."
});