define({
  "enableUndoRedo": "Luba tühistamine ja ennistamine",
  "toolbarVisible": "Tööriistariba nähtav",
  "toolbarOptions": "Tööriistariba valikud",
  "mergeVisible": "Ühenda",
  "cutVisible": "Lõika",
  "reshapeVisible": "Muuda kuju",
  "back": "Tagasi",
  "label": "Kiht",
  "edit": "Muudetav",
  "update": "Keela geomeetria uuendamine",
  "fields": "Väljad",
  "actions": "Tegevused",
  "editpageName": "Nimi",
  "editpageAlias": "Alias",
  "editpageVisible": "Nähtav",
  "editpageEditable": "Muudetav",
  "noLayers": "Muudetavaid objektikihte pole saadaval",
  "configureFields": "Kihi väljade seadistamine",
  "useFilterEdit": "Kasuta objekti malli filtrit",
  "display": "Kuva",
  "autoApplyEditWhenGeometryIsMoved": "Rakenda muudatus geomeetria liigutamisel automaatselt",
  "snappingTolerance": "Määra snäpiga seotud tolerants pikslites",
  "popupTolerance": "Määra atribuudi muutmise hüpikakna tolerants pikslites",
  "stickyMoveTolerance": "Määra kleepuva liikumise tolerants pikslites",
  "usingSaveButton": "Ärge rakendage muudatusi atribuutidele enne nupu Salvesta klõpsamist",
  "generalSettings": "Üldseaded",
  "editableLayersSetting": "Muudetavate kihtide seaded",
  "honorTheWebMapSetting": "Säilita veebikaardi seaded",
  "honorTheWebMapSettingTip1": "Nende seadete seas on järgmine teave:",
  "honorTheWebMapSettingTip2": "millised kihid on muudetavad;",
  "honorTheWebMapSettingTip3": "väljad, mida soovite kuvada ja muuta;",
  "honorTheWebMapSettingTip4": "välja pseudonüüm, järjestus ja vorming;",
  "customSettings": "kohandatud seaded"
});