define({
  "serviceUrl": "Définir l'URL du service :",
  "minIntSpacingLabel": "Espacement d'intervalle minimum",
  "lineOpacityLabel": "Opacité des lignes",
  "labelOpacityLabel": "Opacité des étiquettes",
  "centerLabelOpacityLabel": "Opacité du centre des étiquettes",
  "gridZonePlacementLabel": "Placement des étiquettes dans la zone de la grille",
  "verticalLineLabels": "Etiquettes de lignes verticales",
  "styleHeaderLabel": "Style",
  "indexHeaderLabel": "Indice",
  "colorHeaderLabel": "Couleur",
  "fontSizeHeaderLabel": "Taille de police",
  "lineWidthHeaderLabel": "Largeur de la ligne",
  "horizontalLabel": "Horizontale",
  "verticalLabel": "Verticale",
  "upperLeftLabel": "Supérieur gauche",
  "upperRightLabel": "Supérieur droit",
  "lowerLeftLabel": "Inférieur gauche",
  "lowerRightLabel": "Inférieur droit",
  "centerLabel": "Centre"
});