define({
  "taskUrl": "URL operaţie",
  "serviceURLPlaceholder": "Introduceţi URL-ul operaţiei de geoprocesare",
  "layerOrder": "Ordine straturi tematice",
  "defaultValue": "Valoare implicită",
  "inputFeatureBy": "Introducere obiect spaţial după",
  "inputRecordBy": "Introducere înregistrare în funcție de",
  "renderer": "Autor reproducere",
  "displayType": "Tip afişare",
  "helpUrl": "URL ajutor",
  "useResultMapService": "Vizualizaţi rezultatul cu un serviciu de hartă",
  "drawOnMap": "Trasare interactivă pe hartă",
  "selectLayer": "Selectați un strat tematic de pe hartă",
  "selectTable": "Selectați un tabel de pe hartă",
  "shareResults": "Adăugare rezultat drept strat tematic operaţional",
  "setTask": "Setare",
  "setTaskTitle": "Setare operaţie GP",
  "enablePopup": "Activare pop-up",
  "unSupportGeometryType": "Nu se poate seta autorul reproducerii deoarece tipul de geometrie este necunoscut.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Încărcare fişier",
  "selectFileToUpload": "Selectare fişier...",
  "rasterFormat": "Format date raster",
  "noFileSelected": "Niciun fişier selectat!",
  "uploadSuccess": "Fişier încărcat cu succes!",
  "showLayerContent": "Afişare conţinut strat tematic",
  "urlPlaceholder": "URL pentru a accesa datele",
  "useShapefile": "Utilizare shapefile într-un sistem local de fişiere",
  "allowToExport": "Permitere exportare rezultate",
  "useDynamicSchema": "Este posibil ca ieşirea să aibă o schemă diferită, utilizaţi schema dinamică în locul celei predefinite.",
  "useCurrentMapExtent": "Utilizare extindere curentă a hărţii",
  "ignoreOutput": "Ignoraţi acest rezultat",
  "turnOffOutput": "Dezactivați acest strat tematic în mod implicit",
  "inputJSONString": "Introducere șir JSON"
});