define({
  "serviceUrl": "Establecer dirección URL del servicio:",
  "minIntSpacingLabel": "Espaciado de intervalo mínimo",
  "lineOpacityLabel": "Opacidad de línea",
  "labelOpacityLabel": "Opacidad de etiqueta",
  "centerLabelOpacityLabel": "Opacidad de etiqueta central",
  "gridZonePlacementLabel": "Colocación de etiqueta en zona de cuadrícula",
  "verticalLineLabels": "Etiquetas de línea vertical",
  "styleHeaderLabel": "Estilo",
  "indexHeaderLabel": "Índice",
  "colorHeaderLabel": "Color",
  "fontSizeHeaderLabel": "Tamaño de fuente",
  "lineWidthHeaderLabel": "Ancho de línea",
  "horizontalLabel": "Horizontal",
  "verticalLabel": "Vertical",
  "upperLeftLabel": "Superior izquierda",
  "upperRightLabel": "Superior derecha",
  "lowerLeftLabel": "Inferior izquierda",
  "lowerRightLabel": "Inferior derecha",
  "centerLabel": "Centro"
});