define({
  "_widgetLabel": "Моделювання придатності",
  "general": {
    "clear": "Очистити",
    "cancel": "Скасувати",
    "save": "Запустити",
    "saveAs": "Експорт"
  },
  "saveModel": {
    "save": "Експорт",
    "title": "Заголовок: ",
    "summary": "Коротка інформація: ",
    "description": "Опис: ",
    "tags": "Теги: ",
    "folder": "Папка: ",
    "homeFolderPattern": "{username} (Головна сторінка)",
    "failed": "Експорт не вдався."
  },
  "util": {
    "colorRamp": {
      "1": "Надзвичайно низький",
      "2": "Дуже низький",
      "3": "Низький",
      "4": "Нижче середнього",
      "5": "Середній",
      "6": "Вище середнього",
      "7": "Високий",
      "8": "Дуже високий",
      "9": "Надзвичайно високий",
      "low": "Низький",
      "high": "Високий",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Перекинути"
    }
  },
  "wro": {
    "caption": "Моделювання придатності",
    "browsePrompt": "Сервіс зваженого накладення",
    "selectLayersCaption": "Вибрати шари",
    "selectLayers": "Шари",
    "designModelCaption": "Проектна модель",
    "designModel": "Проектна модель",
    "transparency": "Прозорість",
    "visible": "Видимий",
    "total": "Всього",
    "unableToLoad": "Неможливо завантажити модель.",
    "projectNotOpen": "Проект не відкрито.",
    "readMore": "Прочитати більше",
    "validation": {
      "validating": "Виконується перевірка...",
      "invalidItemCaption": "Попередження сервісу зваженого накладення",
      "notAnImageService": "Цей елемент не є сервісом зображень.",
      "notAWroService": "Цей елемент не є сервісом зваженого накладення.",
      "undefinedUrl": "URL цього елементу не визначено.",
      "inaccessible": "Сервіс недоступний.",
      "generalError": "Неможливо відкрити елемент.",
      "missingFieldPattern": "{field} є обов’язковим полем",
      "notAllowRasterFunction": "Для allowRasterFunction повинно бути задане значення «істинне»",
      "notNearestResampling": "Для defaultResamplingMethod повинен бути вибраний режим «найближчій»",
      "notIsWeightedOverlayProp": "Для ключової властивості IsWeightedOverlay повинно бути задане значення «істинне»",
      "invalidLink": "URL недійсний. Не вдалося відкрити сайт для вибраного шару.",
      "unexpectedError": "Виник неочікуваний стан.",
      "rangeMessage": "Значення повинно бути в діапазоні від ${0} до ${1}",
      "rangeMessage100": "Значення повинно бути в діапазоні від 0 до 100",
      "maxLayers": "Сервіс дозволяє максимум ${0} шарів; необхідно видалити певний шар, перш ніж додавати новий.",
      "notFound": "Шар ${0} не знайдено у сервісі зваженого накладення",
      "wroServiceNotDefined": "Сервіс зваженого накладення не визначено для моделі.",
      "overlayLayerOutputInvalid": "Вихідне значення діапазонів перерозподілу [${1}] шару накладення [${0}] відсутнє або недійсне",
      "overlayLayerInputInvalid": "Мін./макс. вхідне значення діапазонів перерозподілу [${1}] шару накладення [${0}] відсутнє або недійсне",
      "overlayLayerRangesMissing": "У шарі накладення [${0}] відсутні діапазони перерозподілу",
      "overlayLayerWeight": "Ваги шарів накладення повинні складати в сумі 100",
      "overlayLayerRequired": "Потрібен щонайменше один шар накладення",
      "overlayLayerNotDefined": "Шари накладення не визначено",
      "requiresColormap": "Ця растрова функція вимагає колірної карти, проте модель не має визначення дійсної колірної карти",
      "createModelError": "Помилка створення моделі",
      "invalidModel": "Модель недійсна",
      "imageServiceNotDefined": "Шар сервісу зображень не визначено",
      "imageLayerNotDefined": "Шар сервісу зображень не визначено",
      "histogramNotDefined": "Відсутня визначена функція гістограми зваженого накладення."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Зелений, жовтий, червоний",
      "Red Yellow Green": "Червоний, жовтий, зелений",
      "Yellow to Dark Red": "Від жовтого до темно-червоного",
      "Dark Red to Yellow": "Від темно-червоного до жовтого",
      "Light Gray to Dark Gray": "Від світло-сірого до темно-сірого",
      "Dark Gray to Light Gray": "Від темно-сірого до світло-сірого",
      "Light Brown to Dark Brown": "Від світло-коричневого до темно-коричневого",
      "Dark Brown to Light Brown": "Від темно-коричневого до світло-коричневого",
      "Full Spectrum - Bright Red to Blue": "Повний спектр – від яскраво-червоного до блакитного",
      "Full Spectrum - Bright Blue to Red": "Повний спектр – від яскраво-блакитного до червоного",
      "Partial Spectrum - Yellow to Blue": "Частковий спектр – від жовтого до синього",
      "Partial Spectrum - Blue to Yellow": "Частковий спектр – від синього до жовтого",
      "Yellow-Green to Dark Blue": "Від жовто-зеленого до темно-синього",
      "Dark Blue to Yellow-Green": "Від темно-синього до жовто-зеленого",
      "Cold to Hot Diverging": "Від холодного до гарячого відхилення",
      "Hot to Cold Diverging": "Від гарячого до холодного відхилення",
      "Surface - Low to High": "Поверхня – від низької до високої",
      "Surface - High to Low": "Поверхня – від високої до низької"
    }
  },
  "tabs": {
    "layers": "Шари",
    "model": "Модель",
    "chart": "Діаграма"
  },
  "chart": {
    "prompt": "Об’єкти",
    "working": "Виконується оновлення...",
    "polygonTool": "Накреслити полігон",
    "freehandPolygonTool": "Накреслити довільний полігон",
    "selectTool": "Вибрати з шару",
    "panTool": "Переміщення",
    "clearButton": "Очистити",
    "noModelLayer": "Без моделі.",
    "noSubjectLayers": "Ваша карта не має шарів полігонів.",
    "tipPattern": "${category} - ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} - ${label}"
  }
});