define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Dodaj punkt, klikając na mapie",
  "addRingsDtWt": "Dodaj pierścienie, czas przejazdu lub czas pokonania trasy pieszej.",
  "apply": "Zastosuj",
  "back": "Wstecz",
  "colon": ":",
  "creditInformation": "Informacje o kredytach",
  "driveTime": "Czas przejazdu",
  "esriInfographics": "Infografiki Esri",
  "esriReports": "Raporty Esri",
  "headerDescription_km": "kilometr",
  "headerDescription_miles": "mila",
  "headerDescription_minutes": "minuta",
  "infographics": "Infografiki",
  "invalidValueRing": "Wartości muszą należeć do zakresu od 0 do 1 000.",
  "invalidValueDTWT": "Wartości muszą należeć do zakresu od 0 do 300.",
  "km": "km",
  "miles": "mil",
  "minutes": "minut(y)",
  "myInfographics": "Moje infografiki",
  "myReports": "Moje raporty",
  "noPermissions": "Na Twoim koncie nie można uruchomić widżetu Business Analyst.  Aby uruchomić widżet Business Analyst, administrator instytucji musi nadać Tobie <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">uprawnienia</a> do wzbogacania danych przestrzennych i analizy sieciowej, a także przydzielić <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">kredyty</a>.",
  "radii": "promienie",
  "radius": "Promień",
  "radius_lowercase": "promień",
  "reports": "Raporty",
  "ring": "Pierścień",
  "rings": "Pierścienie",
  "runInfographic": "Uruchom infografikę",
  "runReport": "Uruchom raport",
  "selectPointOrPolygon": "Wybierz na mapie obiekt punktowy lub poligonowy, wyszukaj adres lub miejsce albo umieść na mapie szpilkę, aby wyświetlić więcej informacji o obszarach.",
  "selectReport": "Wybierz raport",
  "selectTemplate": "Wybierz szablon",
  "sharedInfographics": "Udostępnione infografiki",
  "sharedReports": "Udostępnione raporty",
  "thisEntryIsNotValid": "Ten wpis nie jest prawidłowy.",
  "time": "Czas",
  "walkTime": "Czas pokonania trasy pieszej",
  "widgetDescription": "Uzyskaj dostęp do infografik i raportów podsumowujących kluczowe wskaźniki i dane w dowolnym obszarze.",
  "None": "Wybierz..."
});