define({
  "defaultAreaUnit": "Výchozí jednotky plochy",
  "defaultLengthUnit": "Výchozí jednotky délky",
  "acres": "Akry",
  "sqMiles": "Čtver. míle",
  "sqKilometers": "Čtver. kilometry",
  "hectares": "Hektary",
  "sqYards": "Čtver. yardy",
  "sqFeet": "Čtver. stopy",
  "sqFeetUS": "Čtver. stopy (US)",
  "sqMeters": "Čtver. metry",
  "miles": "Míle",
  "kilometers": "Kilometry",
  "feet": "Stopy",
  "feetUS": "Stopy (US)",
  "meters": "Metry",
  "yards": "Yardy",
  "nauticalMiles": "Námořní míle",
  "showArea": "Plocha",
  "showDistance": "Vzdálenost",
  "showLocation": "Umístění",
  "showtools": "Zobrazit nástroje měření:",
  "operationalLayer": "Přidejte měřící grafiku jako operační vrstvu mapy.",
  "allHidedTips": "Musí být vybrán alespoň jeden nástroj."
});