define({
  "searchTabTitle": "検索ソースの設定",
  "routeTabTitle": "ルート検索の設定",
  "add": "検索ソースの追加",
  "addGeocoder": "ジオコーダーの追加",
  "geocoder": "ジオコーダー",
  "setLayerSource": "レイヤー ソースの設定",
  "setGeocoderURL": "ジオコーダーの URL の設定",
  "searchableLayer": "フィーチャ レイヤー",
  "name": "名前",
  "countryCode": "国コードまたは地域コード",
  "countryCodeEg": "例: ",
  "countryCodeHint": "この値を空白のままにすると、すべての国および地域を検索します",
  "showInfoWindowOnSelect": "検出されたフィーチャまたは位置のポップアップを表示",
  "showInfoWindowOnSelect2": "フィーチャまたは位置が見つかった場合にポップアップを表示",
  "searchInCurrentMapExtent": "現在のマップ範囲内のみを検索",
  "setSearchFields": "検索フィールドの設定",
  "set": "設定",
  "fieldSearchable": "検索可能",
  "zoomScale": "ズーム縮尺",
  "locatorUrl": "ジオコーダーの URL",
  "locatorName": "ジオコーダー名",
  "locatorExample": "例",
  "locatorWarning": "このバージョンのジオコーディング サービスはサポートされていません。 このウィジェットでサポートされているジオコーディング サービスは 10.1 以降です。",
  "locatorTips": "ジオコーディング サービスがヒント機能をサポートしていないため、ヒントは使用できません。",
  "layerSource": "レイヤー ソース",
  "searchLayerTips": "フィーチャ サービスがページネーション機能をサポートしていないため、ヒントは使用できません。",
  "placeholderText": "プレースホルダー テキスト",
  "searchFields": "検索フィールド",
  "displayField": "表示フィールド",
  "exactMatch": "完全一致",
  "maxSuggestions": "最大候補数",
  "maxResults": "結果の最大数",
  "enableLocalSearch": "ローカル検索の有効化",
  "minScale": "最小縮尺",
  "minScaleHint": "マップ縮尺がこの縮尺より大きい場合は、ローカル検索が適用されます。",
  "radius": "半径",
  "radiusHint": "現在のマップの中心を起点としたエリアの半径を指定します。この半径は、検索位置に最も近い候補が最初に返されるようにジオコーディング候補のランクを高めるために使用されます。",
  "invalidUrlTip": "URL ${URL} は無効であるか、アクセスできません。",
  "routeUrl": "ルート URL",
  "geocoderOptions": "ジオコーダ オプション",
  "autoComplete": "自動入力",
  "maximumSuggestions": "最大候補数",
  "minCharacters": "最小文字数",
  "searchDelay": "検索の遅延",
  "placeholder": "プレースホルダー",
  "routeOptions": "ルート オプション",
  "directionsLanguage": "ルート案内の言語",
  "directionsLengthUnits": "ルート案内の長さの単位",
  "directionsOutputType": "ルート案内の出力タイプ",
  "impedanceAttribute": "インピーダンス属性",
  "kilometers": "キロメートル",
  "miles": "マイル",
  "meters": "メートル",
  "feet": "フィート",
  "yards": "ヤード",
  "nauticalMiles": "海里",
  "parametersTip": "パラメーターを正しく設定してください",
  "complete": "完了",
  "completeNoEvents": "完了したイベントはありません",
  "instructionsOnly": "手順のみ",
  "standard": "標準",
  "summaryOnly": "サマリーのみ",
  "travelModesUrl": "移動モードの URL",
  "searchPlaceholder": "住所または場所の検索",
  "trafficLayerUrl": "交通量レイヤーの URL",
  "barrierLayerUrl": "バリア レイヤーの URL",
  "presetDestinations": "設定済みのストップ",
  "startPoint": "始点",
  "endPoint": "終点",
  "destinationHolder": "住所または座標",
  "optional": "オプション。",
  "barrierLayers": "バリア レイヤー",
  "pointBarrier": "ポイント バリア",
  "lineBarrier": "ライン バリア",
  "polygonBarrier": "ポリゴン バリア",
  "noPointBarrier": "ポイント バリアの選択",
  "noLineBarrier": "ライン バリアの選択",
  "noPolygonBarrier": "ポリゴン バリアの選択"
});