define({
  "_widgetLabel": "編集",
  "_featureAction_Edit": "編集",
  "title": "作成するフィーチャのテンプレートを選択",
  "pressStr": "押す ",
  "ctrlStr": " Ctrl ",
  "snapStr": " スナップを有効にします",
  "close": "閉じる",
  "featureLayers": "フィーチャ レイヤー",
  "searchTemplates": "テンプレートの検索",
  "noAvailableTempaltes": "利用可能なテンプレートがありません",
  "noCanCreateLayerAreCurrentlyVisible": "作成可能なレイヤーが現在表示されていません。",
  "layersAreInvisibleOrOutOfScaleRange": "レイヤーが非表示になっているか、縮尺範囲から外れています。",
  "relatedTables": "関連テーブル:",
  "relatedRecords": "関連レコード:",
  "noRelatedRecotds": "関連するレコードが見つかりませんでした。",
  "startToDraw": "クリックして描画を開始します",
  "startToAddPoint": "クリックしてポイントを追加します",
  "editRelatedFeature": "関連フィーチャの編集",
  "duplicateValueWarning": " ${tableName} の ${fieldName} に重複値を挿入できません。 重複値: ${value}"
});