define(
   ({
    "tabs_section_Label": "File",
    "addTab": "Adăugare filă",
    "layerName": "Strat tematic",
    "layerType": "Tip analiză",
    "layerLabel": "Etichetă",
    "actions": "Acţiuni",
    "closest": "Cel mai apropiat obiect spaţial",
    "proximity": "Proximitate",
    "summary": "Rezumat",
    "select_lbl": "-- Selectare --",
    "general_setting_Label": "Setări generale",
    "units_text_lbl": "Unităţi distanţă",
    "miles": "Mile",
    "kilometers": "Kilometri",
    "feet": "Ft",
    "meters": "Metri",
    "yards": "Iarzi",
    "nauticalMiles": "Mile marine",
    "maximum_distance_lbl": "Distanţă maximă cel mai apropiat obiect spaţial",
    "buffer_text_lbl": "Etichetă buffer",
    "buffer_lbl": "Distanţă buffer",
    "buffer_max_lbl": "Distanţă maximă buffer",
    "buffer_min_lbl": "Distanţă minimă buffer",
    "routing_checkBox": "Activare rutare",
    "weather_Label": "Opţiuni condiţii meteo",
    "weather_checkBox": "Includere informaţii condiţii meteo",
    "selectLayers": "Selectare straturi tematice condiţii meteo",
    "currentlySelectedLayer": "Straturile tematice cu condiţii meteo selectate în mod curent",
    "missingTabLabel": "Cel puţin o filă nu are etichetă",
    "cancel": "Anulare",
    "ok": "OK",
    "missingLayerInWebMap": "Nu s-a găsit niciun strat tematic operaţional.",
    "selectFields": "Selectare câmpuri",
    "addField": "Adăugare câmp",
    "sum": "SUMĂ",
    "min": "MIN.",
    "max": "MAX",
    "avg": "MED.",
    "count": "NUMĂR",
    "area": "SUPRAFAŢĂ",
    "length": "LUNGIME",
    "count_checkBox": "Afişare număr obiecte spaţiale",
    "area_checkBox": "Afişare sumă suprafeţe",
    "length_checkBox": "Afişare sumă lungimi",
    "max_records": "Limită maximă atinsă",
    "save_label": "Opţiuni salvare",
    "save_checkbox": "Activare salvare",
    "csv_label": "Opţiuni CSV",
    "csv_checkbox": "Exportaţi toate câmpurile din stratul tematic.",
    "display_label": "Opţiuni de afişare",
    "display_checkbox": "Afişare obiecte spaţiale rezumat",
    "must_select_template": "Selectaţi unul dintre şabloanele de editare din Opţiuni salvare.",
    "count_label": "Etichetă număr",
    "area_label": "Etichetă suprafaţă",
    "length_label": "Etichetă lungime",
    "invalid_string_width": "Valoarea este prea lungă. ",
    "layer_type_not_supported": "Tipul de strat tematic nu este acceptat: "
  })
);
