define({
  "serviceUrl": "Thiết lập url dịch vụ:",
  "minIntSpacingLabel": "Khoảng cách tối thiểu",
  "lineOpacityLabel": "Độ mờ đục của dòng",
  "labelOpacityLabel": "Độ mờ đục của nhãn",
  "centerLabelOpacityLabel": "Độ mờ đục của nhãn trung tâm",
  "gridZonePlacementLabel": "Đặt nhãn vùng lưới",
  "verticalLineLabels": "Nhãn dòng thẳng đứng",
  "styleHeaderLabel": "Kiểu",
  "indexHeaderLabel": "Chỉ mục",
  "colorHeaderLabel": "Màu sắc",
  "fontSizeHeaderLabel": "Cỡ Chữ",
  "lineWidthHeaderLabel": "Chiều rộng đường",
  "horizontalLabel": "Ngang",
  "verticalLabel": "Dọc",
  "upperLeftLabel": "Phía trên Bên trái",
  "upperRightLabel": "Phía trên Bên phải",
  "lowerLeftLabel": "Phía dưới Bên trái",
  "lowerRightLabel": "Phía dưới Bên phải",
  "centerLabel": "Tâm",
  "errorMessage": "Trang cấu hình có một số lỗi. Vui lòng khắc phục trước khi lưu.",
  "checkBoxLabel": "Hiển thị lưới khi tiện ích được đóng"
});