define({
  "enableUndoRedo": "启用撤消/恢复",
  "toolbarVisible": "工具栏可见",
  "toolbarOptions": "工具栏选项",
  "mergeVisible": "合并",
  "cutVisible": "剪切",
  "reshapeVisible": "整形",
  "back": "返回",
  "label": "图层",
  "edit": "可编辑",
  "update": "禁用更新几何",
  "fields": "字段",
  "actions": "操作",
  "editpageName": "名称",
  "editpageAlias": "别名",
  "editpageVisible": "可见",
  "editpageEditable": "可编辑",
  "noLayers": "没有可用的可编辑要素图层",
  "configureFields": "配置图层字段",
  "useFilterEdit": "使用要素模板过滤器",
  "display": "显示",
  "autoApplyEditWhenGeometryIsMoved": "移动几何后，自动应用编辑内容",
  "snappingTolerance": "设置捕捉容差，以像素为单位",
  "popupTolerance": "设置属性编辑弹出窗口的容差，以像素为单位",
  "stickyMoveTolerance": "设置粘滞移动容差，以像素为单位",
  "usingSaveButton": "单击“保存”按钮才可以对属性应用编辑内容",
  "generalSettings": "常规设置",
  "editableLayersSetting": "可编辑图层设置",
  "honorTheWebMapSetting": "支持 web 地图中的设置",
  "honorTheWebMapSettingTip1": "这些设置包括：",
  "honorTheWebMapSettingTip2": "哪些图层是可编辑的",
  "honorTheWebMapSettingTip3": "您想要显示和编辑的字段",
  "honorTheWebMapSettingTip4": "字段的别名、顺序和格式",
  "customSettings": "自定义设置"
});