define({
  "serviceUrl": "设置服务 URL：",
  "minIntSpacingLabel": "最小间距",
  "lineOpacityLabel": "线不透明度",
  "labelOpacityLabel": "标注不透明度",
  "centerLabelOpacityLabel": "中心标注不透明度",
  "gridZonePlacementLabel": "网格区域标注放置",
  "verticalLineLabels": "垂直线标注",
  "styleHeaderLabel": "样式",
  "indexHeaderLabel": "索引",
  "colorHeaderLabel": "颜色",
  "fontSizeHeaderLabel": "字号",
  "lineWidthHeaderLabel": "线宽度",
  "horizontalLabel": "水平",
  "verticalLabel": "竖直",
  "upperLeftLabel": "左上角",
  "upperRightLabel": "右上角",
  "lowerLeftLabel": "左下角",
  "lowerRightLabel": "右下角",
  "centerLabel": "中心",
  "errorMessage": "配置页面包含错误。请在保存前修正。",
  "checkBoxLabel": "微件关闭时显示格网"
});