define({
  "defaultAreaUnit": "Domyślna jednostka powierzchni",
  "defaultLengthUnit": "Domyślna jednostka długości",
  "acres": "Akry",
  "sqMiles": "Mile kw.",
  "sqKilometers": "Kilometry kw.",
  "hectares": "Hektary",
  "sqYards": "Jardy kw.",
  "sqFeet": "Stopy kw.",
  "sqFeetUS": "Stopy kw. (US)",
  "sqMeters": "Metry kw.",
  "miles": "Mile",
  "kilometers": "Kilometry",
  "feet": "Stopy",
  "feetUS": "Stopy (US)",
  "meters": "Metry",
  "yards": "Jardy",
  "nauticalMiles": "Mile Morskie",
  "showArea": "Obszar",
  "showDistance": "Odległość",
  "showLocation": "Lokalizacja",
  "showtools": "Pokaż narzędzia pomiarowe:",
  "allHidedTips": "Należy wybrać co najmniej jedno narzędzie."
});