define({
  "settings": "Nastavitve",
  "titleSettings": "Nastavitve besedila",
  "imageSettings": "Nastavitve slike",
  "backgroundColor": "Barva ozadja",
  "alignment": "Poravnava",
  "textSize": "Velikost besedila",
  "textColor": "Barva besedila",
  "dataSource": "Vir podatkov",
  "chartSettings": "Nastavitve grafikona",
  "data": "Podatki",
  "dataLabels": "Napisi podatkov",
  "displayMode": "Način prikaza",
  "featureOption": "Prikaži vrednosti po geoobjektih",
  "categoryOption": "Prikaži vrednosti po kategorijah",
  "countOption": "Prikaži števce geoobjektov po kategorijah",
  "fieldOption": "Prikaži vrednosti atributov kot grafikone",
  "categoryField": "Polje kategorije",
  "labelField": "Polje napisa",
  "valueFields": "Polja vrednosti",
  "operation": "Operacija",
  "sumOption": "Vsota",
  "averageOption": "Povprečje",
  "minOption": "Najmanj",
  "maxOption": "Največ",
  "dataFormat": "Podatkovni format",
  "decimalPlaces": "Decimalna mesta",
  "prefix": "Predpona",
  "suffix": "Pripona",
  "dataType": "Tip podatkov",
  "featureCount": "Števec geoobjektov",
  "fieldStatistics": "Statistika polja",
  "display": "Prikaz",
  "chartColor": "Barva grafikona",
  "horizontalAxis": "Horizontalna os",
  "verticalAxis": "Vertikalna os",
  "legend": "Legenda",
  "position": "Položaj",
  "top": "Zgoraj",
  "bottom": "Spodaj",
  "useDataSourceSelection": "Uporabi izbiro",
  "dataSourceFilterByExtent": "Filtriraj po obsegu",
  "changeTemplate": "Spremeni predlogo",
  "numberSettings": "Nastavitve številk",
  "gaugeSettings": "Nastavitve števca",
  "indicators": "Indikatorji",
  "ifValue": "Vrednost ČE",
  "and": "in",
  "numberOperatorIsLessThan": "je manj kot",
  "numberOperatorIsGreaterThan": "je več kot",
  "numberOperatorIsBetween": "je med",
  "numberOperatorIsEqual": "je enako",
  "numberOperatorIsNotEqual": "ni enako",
  "then": "Kot",
  "ratio": "Razmerje",
  "trueValue": "Resnična vrednost",
  "changeValueColor": "spremeni barvo vrednosti v",
  "changeGaugeColor": "spremeni barvo števca v",
  "setIndicatorIcon": "nastavi indikator ikon kot",
  "icons": "Ikone",
  "style": "Slog",
  "placement": "Postavitev",
  "left": "Levo",
  "replace": "Zamenjaj",
  "right": "Desno",
  "color": "Barva",
  "sortBy": "Razvrsti po",
  "labelAxis": "Napis",
  "valueAxis": "Vrednost",
  "minPeriod": "Najkrajše obdobje",
  "automatic": "Samodejno",
  "periodsWithOutRecords": "Obdobja brez zapisov",
  "nullValue": "Prazna vrednost",
  "calculatedAsZero": "Izračunano kot ničla",
  "ignored": "Prezrto",
  "maxCategories": "Največ kategorij",
  "useLayerSymbology": "Uporabi simbologijo sloja",
  "hollowsize": "Prazna velikost",
  "splitField": "Razdeli polje",
  "parsingperiodTip": "Izračun ni uspel. Preveč časovnih intervalov zaradi kratkega obdobja razčlenjevanja.",
  "manyCategoryTip": "Grafikona ni bilo mogoče prikazati. Preveč kategorij.",
  "setColor": "Nastavi barvo",
  "setTheColorOf": "Nastavi barvo",
  "setTheColorAs": "Nastavi barvo kot",
  "ifStr": "Če",
  "as": "kot",
  "is": "je",
  "isNot": "ni",
  "barCluster": "gruča vrstic",
  "individualBar": "posamezna vrstica",
  "allOthers": "Vse drugo",
  "dataRange": "Datumski razpon",
  "targetValue": "Ciljna vrednost",
  "currentValue": "Trenutna vrednost",
  "gaugeColor": "Barva števca",
  "min": "Najmanj",
  "max": "Največ",
  "displayValueIn": "Prikaži vrednost v",
  "noData": "Ni podatkov",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Opozorilo",
  "noSettingWaring1": "Kliknite element, da nastavite njegove lastnosti.",
  "noSettingWaring2": "Povlecite za spremembo velikosti ali preureditev elementa.",
  "donNotShowAgain": "Ne pokaži več",
  "changeTemplateWarning": "To bo izbrisalo vse vaše nastavitve in odprlo novo prazno predlogo.",
  "requiredFieldWarning": "Ta vrednost je obvezna:",
  "dataSourceNotSet": "Nastavite vir podatkov.",
  "addIndicatorTip": "Dodajte indikator",
  "chooseTemplatePopupTitle": "Izberite predlogo",
  "stringsInTemplate": {
    "name_number": "Številka",
    "name_gauge": "Števec",
    "name_vertical_gauge": "Vertikalni števec",
    "name_horizontal_gauge": "Horizontalni števec",
    "name_pie": "Tortni",
    "name_donut": "Kolobarni",
    "name_bar": "Palični",
    "name_stacked_bar": "Naložen palični",
    "name_percentage_stacked_bar": "Odstotno naložen palični",
    "name_column": "Stolpčni",
    "name_stacked_column": "Naložen stolpčni",
    "name_percentage_stacked_column": "Odstotno naložen stolpčni",
    "name_line": "Črtni",
    "name_area": "Ploščinski",
    "name_stacked_area": "Naložen ploščinski",
    "name_percentage_stacked_area": "Odstotno naložen ploščinski",
    "titleOfTheInfographic": "NASLOV INFOGRAFIKE",
    "description": "Opis: Dodatne informacije o tej infografiki."
  }
});