define({
  "feedbackStyleLabel": "Stil för återkoppling på avstånd och riktning",
  "showTabLabel": "Visa flik",
  "feedbackShapeLabel": "Form för återkoppling",
  "lineColorLabel": "Linjefärg",
  "lineWidthLabel": "Linjebredd",
  "feedbackLabel": "Etikett för återkoppling",
  "textColorLabel": "Textfärg",
  "textSizeLabel": "Textstorlek",
  "tabErrorMessage": "Widgeten måste konfigureras med minst en flik som visas",
  "lineLabel": "Linje",
  "circleLabel": "Cirkel",
  "ellipseLabel": "Ellips",
  "ringsLabel": "Ringar",
  "transparency": "Transparens",
  "ddFeedbackStyleTabLabel": "Symbologi",
  "miscellaneousTabLabel": "Diverse",
  "operationalLineLayerSelectLabel": "Välj ett operationellt polylinjelager för resultat med linjer och ringar",
  "operationalPolygonLayerSelectLabel": "Välj ett operationellt polylinjelager för resultat med cirklar och ellipser",
  "helpIconPolylineTooltip": "Listan med funktionslager innehåller lager från den aktuella webbkartan som är av typen polylinjegeometri.",
  "helpIconPolygonTooltip": "Listan med funktionslager innehåller lager från den aktuella webbkartan som är av typen polygongeometri."
});