define({
  "symbolologyTabLabel": "Szimbólumrendszer konfigurálása",
  "facilitiesDescription": "Épületrétegek",
  "demographicsDescription": "Demográfiai adatok rétege",
  "settingsTitle": "Beállítások",
  "spillLocationLabel": "Kifolyás helye",
  "spillLocationButtonLabel": "Kifolyás helyére vonatkozó beállítások konfigurálása",
  "IISettingsLabel": "Első izolációs zóna",
  "IIButtonLabel": "Első izolációs zóna beállításainak konfigurálása",
  "PASettingsLabel": "Védelmi műveletek zónája",
  "PAButtonLabel": "Védelmi műveletekre vonatkozó beállítások konfigurálása",
  "downwindSettingsLabel": "Szélárnyékos zóna",
  "downwindButtonLabel": "Széllel ellentétes (szélárnyékos) oldal beállításainak konfigurálása",
  "fireSettingsLabel": "Tűzzáró zóna",
  "fireButtonLabel": "Tűzzáró zóna beállításainak konfigurálása",
  "bleveSettingsLabel": "BLEVE izolációs zóna",
  "bleveButtonLabel": "BLEVE beállításainak konfigurálása",
  "transparency": "Átlátszóság",
  "outline": "Kontúr",
  "fill": "Kitöltés (a Szín beállítás csak az egyszínű stílus beállítása esetén érhető el)",
  "style": "Stílus",
  "lineStyles": {
    "esriSLSDash": "Szaggatott",
    "esriSLSDashDot": "Vonal-pont",
    "esriSLSDashDotDot": "Vonal-pont-pont",
    "esriSLSDot": "Pont",
    "esriSLSLongDash": "Hosszú vonal",
    "esriSLSLongDashDot": "Hosszú vonal-pont",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Rövid vonal",
    "esriSLSShortDashDot": "Rövid vonal-pont",
    "esriSLSShortDashDotDot": "Rövid vonal-pont-pont",
    "esriSLSShortDot": "Rövid pont",
    "esriSLSSolid": "Egyszínű"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Hátra",
    "esriSFSCross": "Kereszt",
    "esriSFSDiagonalCross": "Átlós",
    "esriSFSForwardDiagonal": "Előre",
    "esriSFSHorizontal": "Vízszintes",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Folytonos",
    "esriSFSVertical": "Függőleges"
  }
});