define({
  "chartSettingLabel": "Diagrammas iestatījumi",
  "addNewLabel": "Pievienot jaunu",
  "generalSettingLabel": "Vispārīgi iestatījumi",
  "layerChooser": {
    "title": "Izvēlieties diagrammā attēlojamo slāni",
    "selectPolygonLayerLabel": "Izvēlēties slāni",
    "selectPolygonLayerHintText": "Padoms. Ja tiek konfigurētas vairākas diagrammas, tad slāņiem jābūt viena ģeometrijas tipa slāņiem.",
    "selectRelatedTableLayerLabel": "Izvēlieties ar slāni saistīto tabulu",
    "selectRelatedTableLayerHintText": "Padoms. Tiek rādītas tikai tabulas ar skaitliskiem laukiem",
    "errorInSelectingPolygonLayer": "Izvēlieties slāni, kam ir saistīts punktu slānis.",
    "errorInSelectingRelatedLayer": "Izvēlieties derīgu ar slāni saistīto tabulu/slāni.",
    "polygonLayerNotHavingRelationships": "Izvēlētajam slānim nav nevienas saistītas tabulas/slāņa."
  },
  "ChartSetting": {
    "sectionTitle": "Sadaļas virsraksts",
    "sectionTitleHintText": "Padoms. Rādīts sadaļas galvenes virsrakstā",
    "chartTitle": "Diagrammas virsraksts",
    "chartTitleHintText": "Padoms. Rādīts diagrammas augšdaļas centrā",
    "chartDescription": "Apraksts",
    "chartDescriptionHintText": "Padoms. Rādīts zem diagrammas",
    "chartType": "Digarammas tips",
    "barChart": "Joslu diagramma",
    "pieChart": "Sektoru diagramma",
    "polarChart": "Polārā diagramma",
    "dataSeriesField": "Datu sērijas lauks",
    "labelField": "Kartes teksta lauks",
    "chartColor": "Diagrammas krāsa",
    "singleColor": "Vienkrāsaina",
    "colorByTheme": "Tēmas krāsa",
    "colorByFieldValue": "Lauka vērtības krāsa",
    "xAxisTitle": "X ass virsraksts",
    "xAxisHintText": "Padoms. X ass virsraksts",
    "yAxisTitle": "Y ass virsraksts",
    "yAxisHintText": "Padoms. Y ass virsraksts",
    "fieldColorLabel": "Kartes teksts",
    "fieldColorColor": "Krāsa",
    "defaultFieldSelectLabel": "Izvēlēties",
    "errMsgFieldValuesNotFound": "Nevar atrast vērtības izvēlētajam laukam",
    "errMsgSectionTitle": "Ievadiet sadaļas virsrakstu",
    "errMsgFieldByValue": "Izvēlieties lauka vērtību",
    "settingTabTitle": "Iestatījums",
    "layoutTabTitle": "Izkārtojums",
    "polarChartSelectFieldsHintText": "Padoms. Atlasiet laukus, lai ģenerētu polāro diagrammu",
    "visibilityText": "Redzamība",
    "fieldNameText": "Lauka nosaukums",
    "aliasNameText": "Aizstājvārds",
    "errMsgPolarFieldsRequired": "Izvēlieties trīs vai vairāk laukus, lai ģenerētu polāro diagrammu",
    "polarChartPolygonFillLabel": "Aizpildīt laukumu",
    "polarChartPolygonFillHintText": "Padoms. Atlasiet izvēles rūtiņu, lai polārajā diagrammā rādītu laukuma aizpildījumu",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Vispārīgie iestatījumi",
    "locationSymbolLabel": "Grafiskais izvietojuma simbols",
    "locationSymbolHintText": "Padoms. Izmanto, lai parādītu adresi un noklikšķinātu uz izvietojuma",
    "refreshIntervalLabel": "Atjaunošanas intervāls",
    "refreshIntervalHintText": "Padoms. Izmanto diagrammu atjaunošanai norādītajā intervālā. Norādiet vērtību no 1 līdz 1440 minūtēm",
    "errMsgRefreshInterval": "Norādiet atjaunošanas intervālu no 0 līdz 1440 minūtēm",
    "symbolPickerPreviewText": "Priekšskatījums:"
  }
});