define({
  "_widgetLabel": "Karttatasot",
  "titleBasemap": "Taustakartat",
  "titleLayers": "Toiminnalliset karttatasot",
  "labelLayer": "Karttatason nimi",
  "itemZoomTo": "Tarkenna kohteeseen",
  "itemTransparency": "Läpinäkyvyys",
  "itemTransparent": "Läpinäkyvä",
  "itemOpaque": "Läpinäkymätön",
  "itemMoveUp": "Siirrä ylös",
  "itemMoveDown": "Siirrä alas",
  "itemDesc": "Kuvaus",
  "itemDownload": "Lataa",
  "itemToAttributeTable": "Avaa ominaisuustietotaulu",
  "itemShowItemDetails": "Näytä kohteen tiedot",
  "empty": "tyhjä",
  "removePopup": "Poista popup-ikkuna käytöstä",
  "enablePopup": "Ota ponnahdusikkunat käyttöön",
  "turnAllLayersOff": "Poista kaikki karttatasot käytöstä",
  "turnAllLayersOn": "Ota kaikki karttatasot käyttöön",
  "expandAllLayers": "Laajenna kaikki karttatasot",
  "collapseAlllayers": "Tiivistä kaikki karttatasot",
  "turnAllLabelsOff": "Poista kaikki selitteet käytöstä",
  "turnAllLabelsOn": "Ota kaikki selitteet käyttöön",
  "showLabels": "Näytä tunnustekstit",
  "hideLables": "Piilota selitteet"
});