define({
  "chartTasks": "Задачі складання діаграми",
  "addNew": "Додати нову",
  "addNewTip": "Додати нову задачу складання діаграми",
  "name": "Назва",
  "set": "Задати",
  "setDataSource": "Задати джерело даних",
  "generalSettingsTip": "Задати джерело даних, назву та опис для діаграм.",
  "chartModeSettingTip": "Вибрати спосіб аналізу та відображення даних у вигляді діаграм.",
  "detailsSettingTip": "Задати вигляд діаграми, вказавши її типи та колір, а також значення, які необхідно відобразити на діаграмі:",
  "symbolSettingTip": "Задати відображення карти для даних на діаграмі.",
  "addFilterTip": "Додати фільтр до цих даних",
  "dataSource": "Джерело даних",
  "noResults": "Об'єкт не знайдено.",
  "chartTitle": "Заголовок діаграми",
  "description": "Опис",
  "chartingMode": "Відображення діаграми",
  "featureOption": "Відображати значення по кожному об’єкту",
  "categoryOption": "Відображати значення за категорією",
  "countOption": "Відображати лічильники об'єктів за категорією",
  "fieldOption": "Відображати значення атрибутів як діаграми",
  "category": "Категорія",
  "axisLabel": "Напис категорії",
  "categoryField": "Поле категорії",
  "operation": "Операція",
  "originalOption": "Використовувати початкові значення",
  "sumOption": "Сума",
  "averageOption": "Середнє",
  "minOption": "Мінімум",
  "maxOption": "Максимум",
  "valueFields": "Поля значень",
  "moveUp": "Перемістити вгору",
  "moveDown": "Перемістити вниз",
  "sortOrder": "Сортувати діаграми за написами категорій",
  "ascending": "У висхідному порядку",
  "descending": "У низхідному порядку",
  "chartType": "Тип діаграми",
  "column": "Стовпчаста діаграма",
  "bar": "Гістограма",
  "line": "Лінійна діаграма",
  "pie": "Кругова діаграма",
  "chartColor": "Колір діаграми",
  "showDataLabels": "Показати написи даних",
  "setSymbol": "Символ вибору",
  "setHighLightColor": "Колір виділення",
  "settings": "Налаштування",
  "mapInterationOptions": "Опції взаємодії з картою",
  "preview": "Попередній перегляд",
  "ok": "OK",
  "cancel": "Скасувати",
  "close": "Закрити",
  "setFilterTip": "Правильно задайте фільтр. ",
  "setChartTitleTip": "Задайте заголовок діаграми.",
  "setChartTypeTip": "Виберіть щонайменше один тип діаграми.",
  "setDataFieldTip": "Виберіть щонайменше одне поле значення.",
  "setOutputFieldTip": "Задайте вихідні поля.",
  "count": "Лічильник",
  "label": "Напис",
  "horizontalAxis": "Горизонтальна вісь",
  "verticalAxis": "Вертикальна вісь",
  "dataLabels": "Написи даних",
  "color": "Колір",
  "colorful": "Кольоровий",
  "monochromatic": "Монохромний",
  "noTaskTip": "Клацніть «Додати нову», щоб додати задачу складання діаграми",
  "info": "Інформація",
  "charts": "Діаграми",
  "options": "Опції",
  "taskName": "Назва задачі",
  "summary": "Коротка інформація",
  "resultDescription": "Опис результату",
  "spatialFilterTip": "Виберіть просторовий фільтр(-и), який використовується у віджеті для обмеження результатів.",
  "defaultOption": "За замовчуванням",
  "useCurrentExtentTip": "Частково чи повністю в межах поточного екстенту карти",
  "useDrawGraphicTip": "Частково чи повністю в межах форми, намальованої на карті",
  "useFeaturesTip": "На основі їх місць розташування відносно об'єктів у іншому шарі",
  "noSpatialLimitTip": "Просторово не обмежувати результати",
  "drawingTools": "Інструменти малювання",
  "bufferSettings": "Налаштування буфера",
  "defaultDistance": "Відстань за замовчуванням",
  "bufferDistance": "Буферна відстань",
  "defaultUnit": "Одиниця за замовчуванням",
  "miles": "Милі",
  "kilometers": "Кілометри",
  "feet": "Фути",
  "meters": "Метри",
  "yards": "Ярди",
  "nauticalMiles": "Морські милі",
  "availableSpatialRelationships": "Доступні просторові відношення",
  "setSpatialRelationships": "Задати просторові відношення",
  "availability": "Доступність",
  "relationship": "Відношення",
  "actions": "Дії",
  "intersect": "перетинають",
  "contain": "містять",
  "areContainedIn": "містяться в",
  "cross": "виходять за межі",
  "envelopeIntersect": "перетинають «конверт»",
  "overlap": "перекривають",
  "areOverlapped": "перекриваються",
  "touche": "торкаються",
  "within": "в межах",
  "areWithin": "знаходяться в межах",
  "indexIntersect": "перетинають індекс",
  "valueStr": "Значення",
  "sortBy": "Сортувати за"
});