define({
  "addTaskTip": "Voeg één of meer filters toe aan de widget en configureer de parameters voor elke zoekopdracht.",
  "enableMapFilter": "De vooraf ingestelde laagfilter uit de kaart verwijderen.",
  "newFilter": "Nieuw filter",
  "filterExpression": "Filterexpressie",
  "layerDefaultSymbolTip": "Gebruik het standaardsymbool van de laag",
  "uploadImage": "Een afbeelding uploaden",
  "selectLayerTip": "Selecteer een laag.",
  "setTitleTip": "Stel een titel in.",
  "noTasksTip": "Geen filters geconfigureerd. Klik op \"${newFilter}\" om een nieuwe toe te voegen.",
  "collapseFiltersTip": "Vouw de filterexpressies (indien van toepassing) samen als de widget wordt geopend",
  "zoomtoTip": "Inzoomen op de resterende objecten nadat het filter toegepast is",
  "groupByLayerTip": "Groepeer filters per laag",
  "autoApplyWhenValueInput": "Pas dit filter automatisch toe nadat een waarde is ingevoerd",
  "autoApplyWhenWidgetOpen": "Pas dit filter toe wanneer de widget wordt geopend",
  "info": "Info",
  "expressions": "Expressies",
  "allowCustom": "Aanmaken van aangepaste filters toestaan",
  "filterActions": "Acties voor aangepast filter",
  "custom": "Aangepaste filters inschakelen",
  "resetAll": "‘Alles resetten’ inschakelen",
  "turnOffAll": "‘Alles uitschakelen’ inschakelen",
  "matchMsgSetAll": "Objecten weergeven die overeenkomen met alle filters",
  "matchMsgSetAny": "Objecten weergeven die overeenkomen met één van de filters"
});