define({
  "_widgetLabel": "Alkalmasságmodellező",
  "general": {
    "clear": "Törlés",
    "cancel": "Mégse",
    "save": "Futtatás",
    "saveAs": "Exportálás"
  },
  "saveModel": {
    "save": "Exportálás",
    "title": "Cím: ",
    "summary": "Összefoglalás: ",
    "description": "Leírás: ",
    "tags": "Címkék: ",
    "folder": "Mappa: ",
    "homeFolderPattern": "{username} (Kezdőlap)",
    "failed": "Az exportálás nem sikerült."
  },
  "util": {
    "colorRamp": {
      "1": "Rendkívül alacsony",
      "2": "Nagyon alacsony",
      "3": "Alacsony",
      "4": "Közepesen alacsony",
      "5": "Közepes",
      "6": "Közepesen magas",
      "7": "Magas",
      "8": "Nagyon magas",
      "9": "Rendkívül magas",
      "low": "Alacsony",
      "high": "Magas",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Tükrözés"
    }
  },
  "wro": {
    "caption": "Alkalmasságmodellező",
    "browsePrompt": "Súlyozott átfedés szolgáltatás",
    "selectLayersCaption": "Rétegek kiválasztása",
    "selectLayers": "Rétegek",
    "designModelCaption": "Modell tervezése",
    "designModel": "Modell tervezése",
    "transparency": "Átlátszóság",
    "visible": "Látható",
    "total": "Összesen",
    "unableToLoad": "Nem sikerült a modell betöltése.",
    "projectNotOpen": "Nincs megnyitva projekt.",
    "readMore": "További információk",
    "validation": {
      "validating": "Érvényesítés...",
      "invalidItemCaption": "Súlyozott átfedés szolgáltatásra vonatkozó figyelmeztetés",
      "notAnImageService": "Ez az elem nem Raszteres adatszolgáltatás.",
      "notAWroService": "Ez az elem nem Súlyozott átfedés szolgáltatás.",
      "undefinedUrl": "Ennek az elemnek az URL-címe nincs meghatározva.",
      "inaccessible": "A szolgáltatás nem érhető el.",
      "generalError": "Nem sikerült megnyitni az elemet.",
      "missingFieldPattern": "A(z) {field} mezőt kötelező megadni",
      "notAllowRasterFunction": "Az allowRasterFunction paramétert igaz értékűre kell állítani",
      "notNearestResampling": "Az alapértelmezett újramintavitelezési eljárást a legközelebbi szomszéd szerint  kell elvégezni",
      "notIsWeightedOverlayProp": "Az IsWeightedOverlay alaptulajdonságot igaz értékűre kell állítani",
      "invalidLink": "Az URL érvénytelen. Nem sikerült megnyitni az oldalt a kiválasztott réteghez.",
      "unexpectedError": "Váratlan állapot.",
      "rangeMessage": "Az értéknek ${0} és ${1} között kell lennie",
      "rangeMessage100": "Az értéknek 0 és 100 között kell lennie",
      "maxLayers": "A szolgáltatás maximum ${0} réteget engedélyez. El kell távolítania egy réteget, mielőtt újat adna hozzá.",
      "notFound": "A(z) ${0} réteg nem található a súlyozott átfedés szolgáltatásban",
      "wroServiceNotDefined": "A modellhez nincs meghatározva súlyozott átfedés szolgáltatás.",
      "overlayLayerOutputInvalid": "A(z) [${0}] fedvényművelet újraleképezési térképtartományának [${1}] kimeneti értékei hiányznak vagy érvénytelenek",
      "overlayLayerInputInvalid": "A(z) [${0}] fedvényművelet újraleképezési térképtartományának[${1}] bemeneti min./max. értékei hiányoznak vagy érvénytelenek",
      "overlayLayerRangesMissing": "A(z) [${0}] fedvényműveletnél hiányoznak az újraleképezési értéktartományok",
      "overlayLayerWeight": "A fedvényművelet-súlyozások összegének 100-nak kell lennie",
      "overlayLayerRequired": "Legalább egy fedvényművelet szükséges",
      "overlayLayerNotDefined": "A fedvényműveletek nincsenek meghatározva",
      "requiresColormap": "Ez a raszterfunkció színtérképet igényel, de a modell nem rendelkezik érvényes színtérkép-meghatározással",
      "createModelError": "Hiba a modell létrehozásakor",
      "invalidModel": "A modell nem érvényes",
      "imageServiceNotDefined": "A raszteres adatszolgáltatási réteg nincs meghatározva",
      "imageLayerNotDefined": "A raszteres adatszolgáltatási réteg nincs meghatározva",
      "histogramNotDefined": "Nincs meghatározva súlyozott átfedési hisztogramfunkció."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Zöld sárga piros",
      "Red Yellow Green": "Piros sárga zöld",
      "Yellow to Dark Red": "Sárgától a sötétvörösig",
      "Dark Red to Yellow": "Sötétvöröstől a sárgáig",
      "Light Gray to Dark Gray": "Világosszürkétől a sötétszürkéig",
      "Dark Gray to Light Gray": "Sötétszürkétől a világosszürkéig",
      "Light Brown to Dark Brown": "Világosbarnától a sötétbarnáig",
      "Dark Brown to Light Brown": "Sötétbarnától a világosbarnáig",
      "Full Spectrum - Bright Red to Blue": "Teljes spektrum - Világospirostól a kékig",
      "Full Spectrum - Bright Blue to Red": "Teljes spektrum - Világoskéktől a pirosig",
      "Partial Spectrum - Yellow to Blue": "Részleges spektrum - Sárgától a kékig",
      "Partial Spectrum - Blue to Yellow": "Részleges spektrum - Kéktől a sárgáig",
      "Yellow-Green to Dark Blue": "Sárgászöldtől a sötétkékig",
      "Dark Blue to Yellow-Green": "Sötétkéktől a sárgászöldig",
      "Cold to Hot Diverging": "Hideg-meleg színek színskála",
      "Hot to Cold Diverging": "Forrótól a hidegig, divergens",
      "Surface - Low to High": "Felszín - alacsonytól a magasig",
      "Surface - High to Low": "Felszín - magastól az alacsonyig"
    }
  },
  "tabs": {
    "layers": "Rétegek",
    "model": "Modell",
    "chart": "Diagram"
  },
  "chart": {
    "prompt": "Vektoros elemek",
    "working": "Frissítés...",
    "polygonTool": "Polygon rajzolása",
    "freehandPolygonTool": "Szabadkézi polygon rajzolása",
    "selectTool": "Kiválasztás egy rétegről",
    "panTool": "Mozgatás",
    "clearButton": "Törlés",
    "noModelLayer": "Nincs modell.",
    "noSubjectLayers": "A térképen nincsenek polygonrétegek.",
    "tipPattern": "${category} – ${label}: ${percent}%",
    "tipPattern2": "${category}: ${percent}%",
    "labelPattern": "${category} – ${label}"
  }
});