define({
  "_widgetLabel": "Vidljivost",
  "observerLocation": "Lokacija promatrača",
  "formatIconTooltip": "Format unosa",
  "addPointToolTip": "Dodaj lokaciju promatrača",
  "fieldOfView": "Vidno polje",
  "useMilsText": "Koristite mjernu jedinicu mil za kutove",
  "observerHeight": "Visina promatrača",
  "minObsDistance": "Min. udaljenost koja se može promatrati",
  "maxObsDistance": "Maks. udaljenost koja se može promatrati",
  "taskURLError": "Datoteka za konfiguraciju widgeta sadrži URL koji nije dostupan. Provjerite kod svog administratora sustava",
  "taskURLInvalid": "Zadatak geoprocesiranja konfiguriran ovim widgetom nije valjan. Provjerite kod svog administratora sustava",
  "viewshedError": "Došlo je do pogreške pri stvaranju vidljivosti. Osigurajte da je vaše mjesto promatrača unutar obuhvata visine terena.</p>",
  "validationError": "<p>U obrascu za stvaranje vidljivosti nedostaju parametri ili nisu valjani, osigurajte sljedeće:</p><ul><li>Postavljena je lokacija promatrača.</li><li>Vidno polje promatrača nije 0.</li><li>Visina promatrača sadrži valjanu vrijednost.</li><li>Min. i maks. udaljenosti koje se mogu promatrati sadrže valjane vrijednosti.</li></ul>",
  "comfirmInputNotation": "Notacija potvrde unosa",
  "notationsMatch": "bilješke se podudaraju s vašim unosom, potvrdite što biste htjeli upotrijebiti:",
  "createBtn": "Stvori",
  "clearBtn": "Očisti",
  "setCoordFormat": "Postavi niz formata koordinata",
  "prefixNumbers": "Dodajte prefiks „+/-” pozitivnim i negativnim brojevima",
  "parseCoordinatesError": "Nije moguće parsirati koordinate. Provjerite unos.",
  "cancelBtn": "Odustani",
  "applyBtn": "Primijeni",
  "invalidMessage": "Unesite brojčanu vrijednost.",
  "observerRangeMessage": "Nevažeća visina promatrača",
  "minimumRangeMessage": "Nevažeći minimalni raspon koji se može promatrati",
  "maximumRangeMessage": "Maksimalni raspon koji se može promatrati mora biti veći od minimalnog raspona koji se može promatrati i ne smije biti veći od ${limit} ${units}.",
  "portalURLError": "URL vaše organizacije za ArcGIS Online ili Portal for ArcGIS nije konfiguriran. Provjerite kod svog administratora sustava",
  "privilegeError": "Vaša korisnička uloga ne može izvršiti analizu. Za izvršavanje analize administrator vaše organizacije treba vam dodijeliti određene <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilegije</a>.",
  "noServiceError": "Usluga analize visine terena nije dostupna. Provjerite svoje konfiguracije organizacije za ArcGIS Online ili Portal for ArcGIS.",
  "pointToolTooltip": "Kliknite da biste dodali lokaciju promatrača",
  "degreesLabel": "stupnjevi",
  "milsLabel": "mil",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalni stupnjevi - geografska širina/dužina",
  "DDLongLatNotation": "Decimalni stupnjevi - geografska dužina/širina",
  "DDMLatLongNotation": "Stupnjevi decimalne minute - geografska širina/dužina",
  "DDMLongLatNotation": "Stupnjevi decimalne minute - geografska dužina/širina",
  "DMSLatLongNotation": "Stupnjevi minute sekunde - geografska širina/dužina",
  "DMSLongLatNotation": "Stupnjevi minute sekunde - geografska dužina/širina",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - slovo retka",
  "UTMHemNotation": "UTM - hemisfera (N/S)",
  "mainPageTitle": "Radijalno vidno polje",
  "resultsTitle": "Rezultati",
  "publishBtnLabel": "Objavi",
  "layerName": "Naziv objavljenog sloja",
  "invalidLayerName": "Naziv sloja mora sadržavati samo alfanumeričke znakove i podvlake",
  "missingLayerName": "Unesite naziv sloja",
  "back": "Natrag",
  "publishingFailedLayerExists": "Objavljivanje nije uspjelo: već imate uslugu geoobjekata s nazivom {0}. Odaberite drugi naziv.",
  "checkService": "Provjeri uslugu: {0}",
  "createService": "Stvori uslugu: {0}",
  "unableToCreate": "Nije moguće stvoriti: {0}",
  "addToDefinition": "Dodaj definiciji: {0}",
  "successfullyPublished": "Uspješno objavljen web-sloj{0}Upravljaj web-slojem",
  "userRole": "Nije moguće stvoriti uslugu jer korisnik nema dopuštenja",
  "publishToNewLayer": "Objava rezultata na novom sloju geoobjekta",
  "missingLayerNameMessage": "Morate unijeti važeći naziv sloja prije objavljivanja",
  "regionTypeLabel": "Vrsta regije",
  "centerPointLabel": "Središnja točka",
  "observationHeightLabel": "Visina promatranja",
  "heightUnitLabel": "Jedinica visine",
  "minObservationDistanceLabel": "Udaljenost min. promatranja",
  "maxObservationDistance": "Udaljenost maks. promatranja",
  "distanceUnitLabel": "Jedinica udaljenosti",
  "fovstartAngleLabel": "Početni kut FOV-a",
  "fovEndAngleLabel": "Krajnji kut FOV-a",
  "andleUnitsLabel": "Jedinice kuta"
});