define({
  "_widgetLabel": "Joonistamine",
  "selectDrawMode": "Valige joonistusrežiim",
  "clear": "Puhasta",
  "point": "Punkt",
  "line": "Joon",
  "polyline": "Murdjoon",
  "freehandPolyline": "Vabakäeline murdjoon",
  "triangle": "Kolmnurk",
  "extent": "Ümbriskast",
  "circle": "Ring",
  "ellipse": "Ellips",
  "polygon": "Pind",
  "freehandPolygon": "Vabakäeline polügoon",
  "text": "Tekst",
  "style": "Stiil",
  "alpha": "Läbipaistvus",
  "width": "Laius",
  "size": "Suurus",
  "color": "Värv",
  "markerColor": "Markeri värv",
  "outlineColor": "Äärejoone värv",
  "lineColor": "Joone värv",
  "fillColor": "Täitevärv",
  "showMeasurements": "Näita mõõtühikuid",
  "showLocationMeasurement": "Kuva asukoha mõõtmine",
  "showAreaMeasurement": "Kuva pindala mõõtmine",
  "showDistanceMeasurement": "Kuva kauguse mõõtmine",
  "showDistanceMeasurementForLine": "Kuva pikkuse mõõtmed",
  "showDistanceMeasurementForPolygon": "Kuva ümbermõõdu mõõtmed",
  "locationToggleOn": "Asukoha mõõtmise kuvamiseks vajutage vahetamise nuppu",
  "locationToggleOff": "Asukoha mõõtmise peitmiseks vajutage vahetamise nuppu",
  "areaToggleOn": "Pindala mõõtmise kuvamiseks vajutage vahetamise nuppu",
  "areaToggleOff": "Pindala mõõtmise peitmiseks vajutage vahetamise nuppu",
  "distanceForLineToggleOn": "Pikkuse mõõtmise kuvamiseks vajutage vahetamise nuppu",
  "distanceForLineToggleOff": "Pikkuse mõõtmise peitmiseks vajutage vahetamise nuppu",
  "distanceForPolygonToggleOn": "Ümbermõõdu mõõtmise kuvamiseks vajutage vahetamise nuppu",
  "distanceForPolygonToggleOff": "Ümbermõõdu mõõtmise peitmiseks vajutage vahetamise nuppu",
  "areaUnits": "Pindalaühikud",
  "distanceUnits": "Vahemaa ühikud",
  "kilometers": "Kilomeetrit",
  "miles": "Miili",
  "meters": "Meetrit",
  "feet": "Jalga",
  "yards": "Jardi",
  "nauticalmiles": "Meremiili",
  "squareKilometers": "Ruutkilomeetrit",
  "squareMiles": "Ruutmiili",
  "acres": "Aakrit",
  "hectares": "Hektarit",
  "squareMeters": "Ruutmeetrit",
  "squareFeet": "Ruutjalga",
  "squareYards": "Ruutjardi",
  "undo": "Tühista",
  "redo": "Ennista",
  "results": "Tulemused",
  "points": "Punktid",
  "lines": "Jooned",
  "areas": "Pindalad",
  "locationLabel": "Asukoht: ${value}",
  "areaLabel": "Pindala: ${value} ${unit}",
  "distanceLabel": "Kaugus: ${value} ${unit}",
  "distanceLabelForLine": "Pikkus: ${value} ${unit}",
  "distanceLabelForPolygon": "Ümbermõõt: ${value} ${unit}"
});