define({
  "styleText": "Velg en stil for sveipeverktøyet",
  "vertical": "Vertikal stolpe",
  "horizontal": "Vannrett stolpe",
  "scope": "Kikkert",
  "placement": "Veibeskrivelse",
  "showLeftSide": "Vis sveipede lag på venstre side",
  "showRigthSide": "Vis sveipede lag på høyre side",
  "showUpSide": "Vis sveipede lag øverst",
  "showDownSide": "Vis sveipede lag på nederst",
  "barColor": "Stolpefarge",
  "swipeMode": "Sveipemodus",
  "singleLayer": "Ett lag",
  "MultipleLayers": "Flere lag",
  "allowToSwipe": "Tillat sveiping",
  "layer": "Lag",
  "swipeByDefault": "Sveiping som standard",
  "defaultLayerMustBeVisible": "standardlaget må være synlig",
  "noDefaultLayer": "Angi sveiping som standard i lagene",
  "defaultLayerHolder": "Klikk for å velge",
  "selectLayers": "Velg lag",
  "layerText": "Velg laget/lagene du vil sveipe som standard",
  "spyglassText": "Velg laget som skal vises i forstørrelsesglasset som standard.",
  "layerHint": "Merk: Hvis laget er skjult av overliggende lag, har ikke sveipingen noen virkning.",
  "isZoom": "Zoom til sveipelaget",
  "isZooms": "Zoom til sveipelaget/-lagene",
  "layersAvailable": "Velg hvilke lag som skal sveipes:"
});