define({
  "_widgetLabel": "Inteligentny edytor",
  "_featureAction_SmartEditor": "Inteligentny edytor",
  "noEditPrivileges": "Twoje konto nie ma uprawnień do tworzenia ani modyfikowania danych.",
  "widgetActive": "Aktywny",
  "widgetNotActive": "Nieaktywny",
  "pressStr": "Naciśnij ",
  "ctrlStr": " CTRL, ",
  "snapStr": " aby włączyć dociąganie",
  "noAvailableTempaltes": "Brak dostępnych szablonów",
  "editorCache": " — bufor edytora",
  "presetFieldAlias": "Pole",
  "presetValue": "Wartość ustawiona wstępnie",
  "usePresetValues": " Użyj wartości ustawionych wstępnie (tylko nowe obiekty)",
  "editGeometry": " Edytuj geometrię",
  "savePromptTitle": "Zapisz obiekt",
  "savePrompt": "Czy chcesz zapisać bieżący obiekt?",
  "deletePromptTitle": "Usuń obiekt",
  "deleteAttachment": "Usuń załącznik",
  "deletePrompt": "Czy na pewno chcesz usunąć wybrany obiekt?",
  "attachmentLoadingError": "Błąd przesyłania załączników",
  "attachmentSaveDeleteWarning": "Ostrzeżenie: zmiany w załącznikach są zapisywane automatycznie",
  "autoSaveEdits": "Automatycznie zapisuje nowy obiekt",
  "addNewFeature": "Utwórz nowy obiekt",
  "featureCreationFailedMsg": "Nie można utworzyć nowego rekordu/obiektu",
  "relatedItemTitle": "Powiązana tabela/warstwa",
  "relatedFeatureCount": "${layerTitle} z obiektami (${featureCount})",
  "createNewFeatureLabel": "Utwórz nowy obiekt dla warstwy ${layerTitle}",
  "invalidRelationShipMsg": "Upewnij się, że pole klucza podstawowego: '${parentKeyField}' ma prawidłową wartość",
  "pendingFeatureSaveMsg": "Zapisz edycje obiektów przed utworzeniem powiązanego obiektu.",
  "attachmentsRequiredMsg": "(*) Wymagane są załączniki.",
  "coordinatePopupTitle": "Przesuń obiekt do lokalizacji XY",
  "coordinatesSelectTitle": "Układ współrzędnych:",
  "mapSpecialReferenceDropdownOption": "Odniesienie przestrzenne mapy",
  "latLongDropdownOption": "Szer. geogr./dł. geogr.",
  "xAttributeTextBoxLabel": "Współrzędna X:",
  "yAttributeTextBoxLabel": "Współrzędna Y:",
  "latitudeTextBoxLabel": "Szerokość geograficzna:",
  "longitudeTextBoxLabel": "Długość geograficzna:",
  "presetGroupFieldsLabel": "Grupa '${groupName}' zostanie zastosowana dla następujących pól warstwy:",
  "presetGroupNoFieldsLabel": "Grupa '${groupName}' nie ma żadnych powiązanych pól",
  "groupInfoLabel": "Informacje o grupie dla grupy '${groupName}'",
  "editGroupInfoIcon": "Edytuj wartość grupy dla grupy ${groupName}",
  "filterEditor": {
    "all": "Wszystkie",
    "noAvailableTempaltes": "Brak dostępnych szablonów",
    "searchTemplates": "Szablony wyszukiwania",
    "filterLayerLabel": "Filtrowanie warstw"
  },
  "invalidConfiguration": "Widżet nie został skonfigurowany lub warstwy w tej konfiguracji nie znajdują się już na mapie. Otwórz aplikację w trybie kreatora i ponownie skonfiguruj widżet.",
  "geometryServiceURLNotFoundMSG": "Nie można uzyskać adresu URL usługi geometrii",
  "clearSelection": "Wyczyść",
  "refreshAttributes": "Zaktualizuj atrybuty obiektu",
  "automaticAttributeUpdatesOn": "Automatyczna aktualizacja atrybutów obiektu: Wł.",
  "automaticAttributeUpdatesOff": "Automatyczna aktualizacja atrybutów obiektu: Wył.",
  "moveSelectedFeatureToGPS": "Przesuń wybrany obiekt do bieżącej lokalizacji GPS",
  "moveSelectedFeatureToXY": "Przesuń wybrany obiekt do lokalizacji XY",
  "mapNavigationLocked": "Nawigacja po mapie: Zablokowane",
  "mapNavigationUnLocked": "Nawigacja po mapie: Odblokowane",
  "copyFeatures": {
    "title": "Kopiuj obiekty",
    "createFeatures": "Utwórz obiekty",
    "createSingleFeature": "Utwórz jeden obiekt o wielu geometriach",
    "noFeaturesSelectedMessage": "Nie wybrano obiektów",
    "selectFeatureToCopyMessage": "Wybierz obiekty do skopiowania.",
    "multipleFeatureSaveWarning": "Uwaga: tworzenie wielu obiektów za pomocą kopiowania obiektów spowoduje natychmiastowe zapisanie wszystkich obiektów"
  },
  "addingFeatureError": "Wystąpił błąd podczas dodawania wybranych obiektów na warstwie. Spróbuj ponownie.",
  "addingFeatureErrorCount": "Nie udało się skopiować '${copyFeatureErrorCount}' obiektów.",
  "selectingFeatureError": "Wystąpił błąd podczas wybierania obiektów na warstwie. Spróbuj ponownie.",
  "customSelectOptionLabel": "Wybierz obiekty do skopiowania",
  "noFeatureSelectedMessage": "Nie wybrano żadnych obiektów.",
  "multipleFeatureSaveMessage": "Wszystkie obiekty zostaną zapisane niezwłocznie. Czy chcesz kontynuować?",
  "relativeDates": {
    "dateTypeLabel": "Rodzaj dat",
    "valueLabel": "Wartość",
    "fixed": "Stała",
    "current": "Bieżący",
    "past": "Przeszły",
    "future": "Przyszły",
    "popupTitle": "Wybierz wartość",
    "hintForFixedDateType": "Wskazówka: podana data i czas zostaną użyte jako wstępnie ustawiona wartość domyślna.",
    "hintForCurrentDateType": "Wskazówka: bieżąca data i czas zostaną użyte jako wstępnie ustawiona wartość domyślna.",
    "hintForPastDateType": "Wskazówka: podana wartość zostanie odjęta od bieżącej daty i czasu dla wartości domyślnej ustawienia wstępnego.",
    "hintForFutureDateType": "Wskazówka: podana wartość zostanie dodana do bieżącej daty i czasu dla wartości domyślnej ustawienia wstępnego.",
    "noDateDefinedTooltip": "Nie zdefiniowano daty",
    "relativeDateWarning": "Należy podać wartość daty lub czasu, aby można było zapisać domyślną wartość skonfigurowaną wstępnie."
  }
});