define({
  "styleText": "Valige rullimistööriista stiil",
  "vertical": "Vertikaalne riba",
  "horizontal": "Horisontaalne riba",
  "scope": "Pikksilm",
  "barColor": "Riba värv",
  "swipeMode": "Rullimisrežiim",
  "singleLayer": "Üks kiht",
  "MultipleLayers": "Mitu kihti",
  "allowToSwipe": "Luba rullida",
  "layer": "Kiht",
  "swipeByDefault": "Rulli vaikimisi",
  "defaultLayerMustBeVisible": "vaikekiht peab olema nähtav",
  "noDefaultLayer": "Vaikimisi rullimiseks määrake kihid",
  "defaultLayerHolder": "Klõpsake valimiseks",
  "selectLayers": "Vali kihid",
  "layerText": "Valige rullimise kaudu vaikimisi võrreldavad kihid",
  "spyglassText": "Valige pikksilmas vaikimisi kuvatav kiht.",
  "layerHint": "Märkus: Rullimine ei mõju, kui vastav kiht on peidetud ülemiste kihtide alla.",
  "isZoom": "Suumi rullitavale kihile",
  "isZooms": "Suumi rullitavatele kihtidele",
  "layersAvailable": "Valige, milliseid kihte rullida:"
});