define({
  "defaultAreaUnit": "क्षेत्रफल की डिफ़ॉल्ट इकाई",
  "defaultLengthUnit": "लंबाई की डिफ़ॉल्ट इकाई",
  "acres": "एकड़",
  "sqMiles": "वर्ग मील",
  "sqKilometers": "वर्ग किलोमीटर",
  "hectares": "हेक्टेयर",
  "sqYards": "वर्ग गज",
  "sqFeet": "वर्ग फीट",
  "sqFeetUS": "वर्ग फीट (यूएस)",
  "sqMeters": "वर्ग मीटर",
  "miles": "मील",
  "kilometers": "किलोमीटर",
  "feet": "फ़ीट",
  "feetUS": "फीट (US)",
  "meters": "मीटर",
  "yards": "गज",
  "nauticalMiles": "समुद्री मील",
  "showArea": "क्षेत्र",
  "showDistance": "दूरी",
  "showLocation": "स्थान",
  "showtools": "माप टूल दिखाएं:",
  "operationalLayer": "मैप की परिचालनात्मक लेयर के रूप में मापे गए ग्राफ़िक को जोड़ें।",
  "allHidedTips": "कम से कम एक टूल का चयन किया जाना चाहिए।"
});