define({
  "_widgetLabel": "Truy tìm Mạng",
  "_featureAction_NetworkTraceSkip": "Bỏ qua trong Truy tìm",
  "_featureAction_NetworkTraceUnskip": "Xóa khỏi các vị trí bỏ qua",
  "removedFromSkipLocations": "Bị xóa khỏi các vị trí bỏ qua",
  "alreadyRemovedFromSkipLocations": "Đã xóa khỏi các vị trí bỏ qua",
  "locationSkipped": "Vị trí bị bỏ qua",
  "configError": "Tiện ích không được cấu hình đúng.",
  "geometryServiceURLNotFoundMSG": "Không thể nhận URL Dịch vụ hình học",
  "clearButtonValue": "Xóa",
  "GPExecutionFailed": "Không thể hoàn thành truy tìm. Vui lòng thử lại.",
  "backButtonValue": "Quay lại",
  "exportToCSVSuccess": "Xuất sang CSV được hoàn tất thành công.",
  "lblInputLocTab": "Nhập Vị trí",
  "lblBlockLocTab": "Chặn Vị trí",
  "lblInputLocation": "Nhập Đối tượng",
  "lblBlockLocation": "Chặn Đối tượng",
  "lblInputLocHeader": "Nhập Vị trí (0)",
  "lblBlockLocHeader": "Chặn Vị trí (0)",
  "inputTabTitle": "Đầu vào",
  "outputTabTitle": "Đầu ra",
  "exportSelectAllCheckBoxLabel": "Chọn Tất cả",
  "lblSkipLocHeader": "Bỏ qua Vị trí (0)",
  "lblSkipLocation": "Vị trí",
  "lblSkipLocTab": "Bỏ qua Vị trí",
  "skipAllLocationButtonLabel": "Bỏ qua Tất cả Vị trí",
  "confirmSkipAllLocationsMessage": "Tất cả các vị trí sẽ được bỏ qua, bạn có muốn tiếp tục?",
  "locationAlreadySkippedMessage": "Vị trí đã bị bỏ qua",
  "removeAllSkipLocationLabel": "Loại bỏ Tất cả",
  "newProjectOptionText": "Dự án mới",
  "selectProject": "Chọn dự án",
  "saveButtonLabel": "Lưu",
  "exportToCSVText": "Xuất ra CSV",
  "editProjectAttributesToolTip": "Chỉnh sửa Thuộc tính Dự án",
  "projectNameLabel": "Tên dự án",
  "saveProjectPopupTitle": "Lưu",
  "saveAsLabel": "Lưu thành",
  "saveChangesMsg": "Bạn muốn lưu các thay đổi vào <b>${loadProjectDropdownlabel}</b> hoặc lưu thành dự án mới?",
  "creatingNewProjectErrorMessage": "Lỗi xảy ra khi tạo dự án mới. Vui lòng thử lại.",
  "projectNameFetchingErr": "Lỗi xảy ra khi tìm nạp tên dự án hiện có. Vui lòng thử lại.",
  "projectAttributeLoadingErr": "Lỗi xảy ra khi tải thuộc tính dự án. Vui lòng thử lại.",
  "attributeUpdatedMsg": "Cập nhật thuộc tính thành công.",
  "projectAttributeUpdatingErr": "Lỗi xảy ra khi cập nhật thuộc tính dự án.",
  "loadingProjectDetailsErrorMessage": "Lỗi xảy ra khi tìm nạp cờ, rào cản và bỏ qua vị trí. Vui lòng thử lại.",
  "savingProjectDetailsErr": "Lỗi xảy ra khi lưu chi tiết dự án. Vui lòng thử lưu lại dự án.",
  "updatingOutagePolygonErr": "Lỗi xảy ra khi cập nhật vùng mất điện. Vui lòng thử lưu lại dự án.",
  "deletingExistingPolygonErr": "Lỗi xảy ra khi xóa vùng mất điện hiện tại. Vui lòng thử lưu lại dự án.",
  "loadingProjectFeaturesErr": "Lỗi xảy ra khi tải đối tượng dự án. Vui lòng thử tải dự án một lần nữa.",
  "addingProjectFeaturesErr": "Lỗi xảy ra khi thêm đối tượng dự án. Vui lòng thử lưu lại dự án.",
  "deletingExistingProjectFeaturesErr": "Lỗi xảy ra khi xóa đối tượng dự án hiện tại. Vui lòng thử lưu lại dự án.",
  "projectNotFoundErr": "Không tìm thấy dự án",
  "projectLayersNotFound": "Các lớp cài đặt Dự án đã cấu hình không có sẵn trong bản đồ. Tiện ích sẽ được tải trong 'Chế độ phác họa'.",
  "fetchingOutagePolygonMessage": "Lỗi xảy ra khi tìm nạp vùng mất điện. Vui lòng thử tải dự án một lần nữa.",
  "projectNameExistsMessage": "Tên dự án đã tồn tại. Vui lòng sử dụng tên dự án duy nhất.",
  "fetchingProjectNamesErrorMessage": "Lỗi xảy ra khi tìm nạp tên dự án hiện có. Vui lòng thử lưu lại dự án.",
  "enterProjectNameMessage": "Vui lòng nhập tên dự án.",
  "projectLengthErrorMessage": "Tên dự án không được nhiều hơn",
  "gpServiceNotAccessible": "Tài khoản của bạn không có quyền truy cập vào dịch vụ cần thiết để thực hiện truy tìm này.",
  "loadingClonedLayerErrorMessage": "Lỗi xảy ra khi tải lớp đối tượng nhân bản. Vui lòng thử lại.",
  "addingFeatureInClonedLayerError": "Lỗi xảy ra khi thêm đồ họa vào lớp đối tượng nhân bản. Vui lòng thử lại.",
  "selectingFeatureInClonedLayerError": "Lỗi xảy ra khi chọn đồ họa trong lớp đối tượng nhân bản. Vui lòng thử lại.",
  "filteredProjectError": "Lỗi xảy ra khi kiểm tra quá trình tìm nạp chi tiết dự án được lọc. Vui lòng thử lại.",
  "filteredProjectMessage": "Các thuộc tính dự án đã chọn không có sẵn do việc áp dụng các bộ lọc từ bản đồ web hoặc tiện ích khác. Xóa (các) bộ lọc và thử lại.",
  "filteredProjectLoadMessage": "Dự án của bạn không còn nữa. Vui lòng chọn một dự án đang hoạt động.",
  "defaultValueForRunButton": "Chạy",
  "closeButtonLabel": "Gỡ bỏ"
});