define({
  "taskUrl": "URL opravila",
  "setTask": "Nastavi",
  "setTaskPopupTitle": "Nastavi opravilo",
  "validate": "Nastavi",
  "inValidGPService": "Vnesite veljavno geoprocesno storitev.",
  "GPFeatureRecordSetLayerERR": "Vnesite geoprocesno storitev samo z vnosi tipa 'GPFeatureRecordSetLayer'.",
  "invalidInputParameters": "Število vhodnih parametrov je manj kot 1 ali več kot 3. Vnesite veljavno geoprocesno storitev.",
  "projectSetting": {
    "title": "Nastavitve projekta",
    "note": "Opomba: nastavitve projekta so izbirne. Ko so konfigurirane, lahko uporabnik projekt shrani v želene sloje spletne karte z območji izpada omrežja z vhodnimi parametri. Uporabnik lahko shrani izhodne parametre v skupini »Izhod« na zavihku »Vhod/Izhod«.",
    "projectPolygonLayer": "Sloj poligona projekta",
    "outputParameterName": "Ime izhodnega parametra",
    "projectPointLayer": "Točkovni sloj projekta",
    "selectLabel": "Izberi",
    "polygonLayerHelp": "<p>Prikazani bodo poligonski sloji z naslednjimi pogoji:<br/><li>sloj mora imeti zmožnosti urejanja, tj. »Ustvari«, »Izbriši« in »Posodobi«;</li><li>sloj mora imeti dve polji s točnim imenom in tipom podatkov:</li><ul><li>ime (polje tipa niza)</li><li>globalid (polje tipa GlobalID).</li></ul><p/>",
    "outputParameterHelp": "<p>Prikazani bodo izhodni poligonski sloji z URL-ja opravila.<p/>",
    "pointLayerHelp": "<p>Prikazani bodo točkovni sloji naslednjimi pogoji:<br/><li>sloj mora imeti zmožnosti urejanja, tj. »Ustvari«, »Izbriši« in »Posodobi«;</li><li>sloj mora imeti dve polji s točnim imenom in tipom podatkov:</li><ul><li>tip vhoda (polje tipa niza)</li><li>id projekta (tip polja GUID).</li></ul><p/>"
  },
  "inputOutputTab": {
    "title": "Vhod/izhod",
    "inputSettingsLabel": "Vhodne nastavitve",
    "outputSettingsLabel": "Izhodne nastavitve",
    "inputLabel": "Napis",
    "inputTooltip": "Zaslonski namig",
    "symbol": "Simbol",
    "typeText": "Vrsta",
    "outputParametersText": "Izhodni parametri",
    "saveToLayerText": "Shrani v sloj (izbirno)",
    "skipText": "Je mogoče preskočiti",
    "visibilityText": "Vidno",
    "exportToCsvText": "Izvozi v CSV",
    "exportToCsvDisplayText": "CSV",
    "settitngstext": "Nastavitve",
    "addFieldTitle": "Dodaj polje",
    "enterDisplayText": "Vnesi prikazno besedilo",
    "setScale": "Nastavi merilo",
    "outputDisplay": "Prikazno besedilo",
    "saveToLayerHelp": "<p>Prikazan bo sloj z naslednjimi pogoji:<br/><li>sloj mora imeti zmožnosti urejanja, tj. »Ustvari«, »Izbriši« in »Posodobi«;</li><li>sloj mora imeti dve polji z imenom in tipom podatkov:</li><ul><li>ime parametra (polje tipa niza)</li><li>ID projekta (tip polja Guid).</li></ul><p/>"
  },
  "summaryTab": {
    "title": "Povzetek",
    "summaryFieldsetText": "Nastavitve povzetka",
    "inputOutput": "Vhodi/izhodi",
    "field": "Polja",
    "operator": "Operatorji",
    "inputOperatorCountOption": "Število",
    "outputOperatorCountOption": "Število",
    "outputOperatorSkipCountOption": "Preskoči štetje",
    "fieldOperatorSumOption": "Vsota",
    "fieldOperatorMinOption": "Min",
    "fieldOperatorMaxOption": "Maks",
    "fieldOperatorMeanOption": "Srednja vrednost",
    "expressionAddButtonText": "Dodaj",
    "expressionVerifyButtonText": "Preveri",
    "summaryEditorText": "Besedilo povzetka"
  },
  "generalSettings": {
    "title": "Splošne nastavitve",
    "displayTextForButtonLegend": "Prikazno besedilo za gumb »Zaženi«",
    "displayTextforButtonDefaultValue": "Zaženi",
    "displayTextForButton": "Prikazno besedilo",
    "autoZoomAfterTrace": "Možnosti povečave",
    "zoomText": "Samodejna povečava po sledi"
  },
  "validationErrorMessage": {
    "webMapError": "Na spletni karti ni na voljo noben sloj. Izberite veljavno spletno karto.",
    "inputTypeFlagGreaterThanError": "Vhod tipa zastavice ne more biti več kot ena.",
    "inputTypeFlagLessThanError": "Zahtevan je vsaj en vhod tipa zastavice.",
    "inputTypeBarrierErr": "Vhod tipa pregrade ne more biti več kot ena.",
    "inputTypeSkipErr": "Vhod tipa preskoka ne more biti več kot ena.",
    "displayTextForButtonError": "Prikazno besedilo za gumb »Zaženi« ne more biti prazno.",
    "UnableToLoadGeoprocessError": "Geoprocesne storitve ni mogoče naložiti.",
    "invalidSummaryExpression": "Neveljaven izraz",
    "validSummaryExpression": "Uspešno!",
    "invalidProjectSettings": "Neveljavne nastavitve projekta<br/> Izberite veljavno vrednost v '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "Namig: zagotovite oznako prikaza za ploščo z rezultati izhodnega parametra.",
    "displayTextHint": "Namig: to bo prikazano na plošči s podrobnostmi za ta izhodni parameter.",
    "inputTextHint": "Namig: zgradite svoj izraz zgoraj z izbiro vhoda, izhoda in imen polj.",
    "expressionHint": "Namig: izberite elemente in kliknite dodaj, da zgradite izraz."
  }
});