define({
  "serviceUrl": "Szolgáltatás URL-címének beállítása:",
  "minIntSpacingLabel": "Rácsháló minimális mérete",
  "lineOpacityLabel": "Vonal átlátszatlansága",
  "labelOpacityLabel": "Felirat átlátszatlansága",
  "centerLabelOpacityLabel": "Középső felirat átlátszatlansága",
  "gridZonePlacementLabel": "Rácszóna-felirat elhelyezése",
  "verticalLineLabels": "Függőleges vonalfeliratok",
  "styleHeaderLabel": "Stílus",
  "indexHeaderLabel": "Rácsháló komponense",
  "colorHeaderLabel": "Szín",
  "fontSizeHeaderLabel": "Betűméret",
  "lineWidthHeaderLabel": "Vonalvastagság",
  "horizontalLabel": "Vízszintes",
  "verticalLabel": "Függőleges",
  "upperLeftLabel": "Bal felső",
  "upperRightLabel": "Jobb felső",
  "lowerLeftLabel": "Bal alsó",
  "lowerRightLabel": "Jobb alsó",
  "centerLabel": "Középen",
  "errorMessage": "A konfigurációs oldal hibákat tartalmaz. Mentés előtt javítsa.",
  "checkBoxLabel": "Rács megjelenítése amikor a widget zárva van.",
  "checkBoxLabelDashboard": "Rácsháló megjelenítése",
  "gzd": "Rácsháló zónajelölője (GZD)",
  "gsid": "100000 méteres rácsháló-azonosítás (GSID)",
  "grid10k": "10000 méteres rácshálóvonalak",
  "grid1k": "1000 méteres rácshálóvonalak",
  "grid100m": "100 méteres rácshálóvonalak",
  "grid10m": "10 méteres rácshálóvonalak",
  "switchBasemap": "Alaptérkép váltása"
});