define({
  "enableUndoRedo": "Onemogoči razveljavi/uveljavi",
  "toolbarVisible": "Orodna vrstica vidna",
  "toolbarOptions": "Možnosti orodne vrstice",
  "mergeVisible": "Združi",
  "cutVisible": "Izreži",
  "reshapeVisible": "Preoblikuj",
  "back": "Nazaj",
  "label": "Sloj",
  "edit": "Za urejanje",
  "update": "Onemogoči posodobitev geometrije",
  "fields": "Polja",
  "actions": "Dejanja",
  "editpageName": "Ime",
  "editpageAlias": "Vzdevek",
  "editpageVisible": "Vidno",
  "editpageEditable": "Za urejanje",
  "noLayers": "Geoobjektni sloji za urejanje niso na voljo",
  "configureFields": "Konfigurirajte polja slojev",
  "useFilterEdit": "Uporabite filter za predloge geoobjektov",
  "display": "Prikaz",
  "autoApplyEditWhenGeometryIsMoved": "Uporabi samodejno urejanje, ko je geometrija premaknjena",
  "snappingTolerance": "Nastavite doseg magnetenja v pikslih",
  "popupTolerance": "Nastavite pojavno okno dovoljenega odstopanja urejanja atributov v pikslih",
  "stickyMoveTolerance": "Nastavite dovoljeno odstopanje lepljivega premika v pikslih",
  "usingSaveButton": "Ne uporabite sprememb na atributih, dokler ne pritisnete Shrani"
});