define(
   ({
    addLayer: "Adicionar Camada",
    layerName: "Camada",
    layerRefresh: "Atualizar",
    layerLabel: "Rótulo",
    actions: "Ações",
    popupOk: "Ok",
    popupCancel: "Cancelar",
    mainPanelTextPlaceholder: "ex: CONDIÇÕES DA ESTRADA",
    invalidInterval: "Somente caracteres numéricos são suportados.",
    uploadImage: "Transferir Imagem",
    iconColumnText: "Ícone",
    refreshInterval: "1 \'Avaliado como tempo em Minutos\'",
    refreshIntervalTitle: "Avaliado como tempo em Minutos",
    mainPanelText: "Principal Texto do Painel",
    mainPanelIcon: "Principal Imagem do Painel",
    refreshIntervalInstruction: "Intervalo de Atualização",
    optionsText: "Opções",
    symbolOptionsText: "Opções de Símbolo",
    iconOptionsText: "Opções de Ícone",
    sympolPopupTitle: "Configurar Símbolo",
    rdoLayer: "Símbolo de Camada",
    rdoCustom: "Personalizar Símbolo",
    chkCluster: "Habilitar Agrupamento",
    defineClusterSymbol: "Símbolo de Agrupamento",
    defineThemeClusterSymbol: "Símbolo de Agrupamento do Tema",
    rdoEsri: "Símbolo da Esri",
    rdoLayerIcon: "Utilizar Símbolo como Ícone",
    rdoCustomIcon: "Transferir Ícone Personalizado",
    editCustomSymbol: "Editar Símbolo Personalizado",
    editCustomIcon: "Editar Ícone Personalizado",
    missingRefreshValue: "Forneça um valor do intervalo de atualização.",
    panelIconOption: "Exibir Cabeçalho do Painel",
    enableRefresh: "Habilitar Atualização da Camada",
    disableRefresh: "Atualização da Camada Somente Suportada para Coleções de Feição",
    layer_type_not_supported: "O tipo de camada não é suportado: "
  })
);
