define({
  "addLayer": "Adicionar Camada",
  "layerName": "Camada",
  "layerRefresh": "Atualizar",
  "layerLabel": "Rótulo",
  "actions": "Ações",
  "mainPanelTextPlaceholder": "ex: Última Atualização:",
  "invalidInterval": "Somente caracteres numéricos são suportados.",
  "uploadImage": "Transferir Imagem",
  "iconColumnText": "Exibir",
  "refreshInterval": "Tempo em Minutos",
  "refreshIntervalTitle": "Avaliado como tempo em Minutos",
  "mainPanelText": "Principal Texto do Painel",
  "mainPanelIcon": "Principal Imagem do Painel",
  "refreshIntervalInstruction": "Atualizar camadas a cada:",
  "optionsText": "Opções",
  "symbolOptionsText": "Simbologia do Mapa",
  "iconOptionsText": "Simbologia do Painel",
  "sympolPopupTitle": "Configurações de Visualização",
  "rdoLayer": "Símbolo Padrão",
  "rdoCustom": "Utilizar uma Imagem",
  "chkCluster": "Habilitar Agrupamento",
  "defineClusterSymbol": "Especificar Símbolo de Agrupamento",
  "rdoEsri": "Selecione um Símbolo",
  "rdoLayerIcon": "Utilizar Símbolo de Mapa",
  "rdoCustomIcon": "Utilizar uma Imagem",
  "editCustomSymbol": "Editar Símbolo Personalizado",
  "editCustomIcon": "Editar Ícone Personalizado",
  "missingRefreshValue": "Forneça um valor do intervalo de atualização.",
  "panelIconOption": "Exibir Imagem do Logo",
  "enableRefresh": "Habilitar Atualização da Camada",
  "disableRefresh": "Atualização da Camada Somente Suportada para Coleções de Feição",
  "layer_type_not_supported": "O tipo de camada não é suportado: ",
  "refreshUnit": "minutos.",
  "symbolOptions": "Símbolo",
  "panelFeatureDisplay": "Painel",
  "chkGroup": "Agrupar Feições",
  "selectField": "Campo",
  "fieldLabel": "Rótulo",
  "addField": "Adicionar Campo",
  "featureOptionsText": "Opções da Camada",
  "groupOptionsText": "Opções de Agrupamento",
  "panelCountOption": "Exibir Contagens de Feição",
  "rdoStack": "Exibir Nova Linha para Cada Campo",
  "rdoAppend": "Anexar Campos em Única Linha",
  "missingLayerInWebMap": "Nenhuma camada operacional encontrada.",
  "displayClusterCnt": "Exibir Contagem de Feição",
  "defineClusterFont": "Especificar Cor da Fonte",
  "max_records": "Limite de campo máximo alcançado"
});