define({
  "searchTabTitle": "Ustawienie źródła wyszukiwania",
  "routeTabTitle": "Ustawienie trasy",
  "add": "Dodaj źródło wyszukiwania",
  "addGeocoder": "Dodaj geokoder",
  "geocoder": "Geokoder",
  "setLayerSource": "Skonfiguruj źródło warstwy",
  "setGeocoderURL": "Skonfiguruj adres URL geokodera",
  "searchableLayer": "Warstwa",
  "name": "Nazwa",
  "countryCode": "Kody kraju lub regionu",
  "countryCodeEg": "np. ",
  "countryCodeHint": "Pozostawienie pustego pola uruchomi wyszukiwanie we wszystkich krajach i regionach",
  "showInfoWindowOnSelect": "Wyświetl odrębne okno ze znalezionym elementem: obiektem lub miejscem",
  "showInfoWindowOnSelect2": "Wyświetla okno podręczne po znalezieniu obiektu lub lokalizacji.",
  "searchInCurrentMapExtent": "Wyszukaj tylko w bieżącym zasięgu mapy",
  "setSearchFields": "Skonfiguruj pola wyszukiwania",
  "set": "Zestaw",
  "fieldSearchable": "możliwe do wyszukiwania",
  "zoomScale": "Skala powiększenia",
  "locatorUrl": "Adres URL geokodera",
  "locatorName": "Nazwa geokodera",
  "locatorExample": "Przykład",
  "locatorWarning": "Ta wersja usługi geokodowania nie jest obsługiwana. Ten widżet obsługuje usługi geokodowania w wersji 10.1 i nowsze.",
  "locatorTips": "Sugestie są niedostępne ponieważ usługa geokodowania nie obsługuje funkcji sugestii.",
  "layerSource": "Źródło warstwy",
  "searchLayerTips": "Sugestie są niedostępne ponieważ usługa obiektowa nie obsługuje funkcji paginacji.",
  "placeholderText": "Tekst zastępczy",
  "searchFields": "Pola wyszukiwania",
  "displayField": "Pole wyświetlania",
  "exactMatch": "Dokładne dopasowanie",
  "maxSuggestions": "Maksymalna liczba sugestii",
  "maxResults": "Maksymalna liczba wyników",
  "enableLocalSearch": "Włącz wyszukiwanie lokalne",
  "minScale": "Skala min.",
  "minScaleHint": "Kiedy skala mapy będzie większa niż ta skala, zostanie zastosowane wyszukiwanie lokalne",
  "radius": "Promień",
  "radiusHint": "Określa promień obszaru wokół bieżącego centrum mapy używanego do przyspieszenia oceny propozycji geokodowania, aby propozycje znajdujące się najbliżej lokalizacji były zwracane jako pierwsze",
  "invalidUrlTip": "Adres URL ${URL} jest nieprawidłowy lub nieosiągalny.",
  "routeUrl": "Adres URL trasy",
  "geocoderOptions": "Opcje geokodera",
  "autoComplete": "Autouzupełnianie",
  "maximumSuggestions": "Maksymalna liczba sugestii",
  "minCharacters": "Minimalna liczba znaków",
  "searchDelay": "Opóźnienie wyszukiwania",
  "placeholder": "Symbol zastępczy",
  "routeOptions": "Opcje trasy",
  "directionsLanguage": "Język wskazówek",
  "directionsLengthUnits": "Jednostki długości używane we wskazówkach",
  "directionsOutputType": "Typ wynikowych wskazówek",
  "impedanceAttribute": "Atrybut impedancji",
  "kilometers": "Kilometry",
  "miles": "Mile",
  "meters": "Metry",
  "feet": "Stopy",
  "yards": "Jardy",
  "nauticalMiles": "Mile morskie",
  "parametersTip": "Skonfiguruj poprawnie atrybuty!",
  "complete": "Zakończone",
  "completeNoEvents": "Zakończone brakiem zdarzeń",
  "instructionsOnly": "Tylko instrukcje",
  "standard": "Standard",
  "summaryOnly": "Tylko podsumowanie",
  "travelModesUrl": "Adres URL trybów podróżowania",
  "searchPlaceholder": "Znajdź adres lub miejsce",
  "trafficLayerUrl": "Adres URL warstwy ruchu drogowego",
  "barrierLayerUrl": "Adres URL warstwy barier",
  "presetDestinations": "Przystanki ustawione wstępnie",
  "startPoint": "Punkt początkowy",
  "endPoint": "Punkt końcowy",
  "destinationHolder": "Adres lub współrzędne",
  "optional": "Opcjonalne.",
  "barrierLayers": "Warstwy barier",
  "pointBarrier": "Bariery punktowe",
  "lineBarrier": "Bariery liniowe",
  "polygonBarrier": "Bariery poligonowe",
  "noPointBarrier": "Wybierz bariery punktowe",
  "noLineBarrier": "Wybierz bariery liniowe",
  "noPolygonBarrier": "Wybierz bariery poligonowe"
});