define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Lägg till en punkt genom att klicka på kartan",
  "addRingsDtWt": "Lägg till ringar, körtid eller gångtid.",
  "apply": "Verkställ",
  "back": "BACKA",
  "colon": ":",
  "creditInformation": "Kreditinformation",
  "driveTime": "Körtid",
  "esriInfographics": "Esri Infographics",
  "esriReports": "Esri Reports",
  "headerDescription_km": "kilometer",
  "headerDescription_miles": "engelsk mil",
  "headerDescription_minutes": "minut",
  "infographics": "Infografik",
  "invalidValueRing": "Värdena måste vara inom intervallet 0 till 1 000.",
  "invalidValueDTWT": "Värdena måste vara inom intervallet 0 till 300.",
  "km": "km",
  "miles": "engelska mil",
  "minutes": "minuter",
  "myInfographics": "Min infografik",
  "myReports": "Mina rapporter",
  "noPermissions": "Ditt konto kan inte köra Business Analyst-widgeten. För att köra Business Analyst-widgeten måste organisationens administratör bevilja dig GeoEnrichment- och Network Analysis-<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">behörighet</a>, och dessutom tilldela <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">krediter</a>.",
  "radii": "radier",
  "radius": "Radie",
  "radius_lowercase": "radie",
  "reports": "Rapporter",
  "ring": "Ring",
  "rings": "Ringar",
  "runInfographic": "Kör infografik",
  "runReport": "Kör rapport",
  "selectPointOrPolygon": "Välj ett punkt- eller polygongeoobjekt på kartan, sök efter en adress eller plats eller släpp en nål på kartan för att visa mer information om områdena.",
  "selectReport": "Välj rapport",
  "selectTemplate": "Välj mall",
  "sharedInfographics": "Delad infografik",
  "sharedReports": "Delade rapporter",
  "thisEntryIsNotValid": "Den här inmatningen är inte giltig.",
  "time": "Tid",
  "walkTime": "Gångtid",
  "widgetDescription": "Få åtkomst till infografik och rapporter som sammanfattar nyckeltal och data för alla områden.",
  "None": "Välj..."
});