define({
  "_widgetLabel": "Išmanusis redaktorius",
  "_featureAction_SmartEditor": "Išmanusis redaktorius",
  "noEditPrivileges": "Jūsų paskyra neturi teisės kurti arba modifikuoti duomenų.",
  "widgetActive": "Aktyvus",
  "widgetNotActive": "Neaktyvus",
  "pressStr": "Paspauskite ",
  "ctrlStr": " CTRL ",
  "snapStr": " pritraukimui įjungti",
  "noAvailableTempaltes": "Galimų šablonų nėra",
  "editorCache": " - Redagavimo podėlis",
  "presetFieldAlias": "Laukas",
  "presetValue": "Iš anksto nustatyta reikšmė",
  "usePresetValues": " Naudoti iš anksto nustatytas reikšmes (tik naujiems elementams)",
  "editGeometry": " Redaguoti geometriją",
  "savePromptTitle": "Įrašyti elementą",
  "savePrompt": "Ar norite išsaugoti šį elementą?",
  "deletePromptTitle": "Ištrinti elementą",
  "deleteAttachment": "Ištrinti priedą",
  "deletePrompt": "Ar tikrai norite ištrinti šį elementą?",
  "attachmentLoadingError": "Klaida įkeliant priedus",
  "attachmentSaveDeleteWarning": "Įspėjimas: priedų pakeitimai įrašomi automatiškai",
  "autoSaveEdits": "Automatiškai įrašo naują elementą",
  "addNewFeature": "Sukurti naują elementą",
  "featureCreationFailedMsg": "Negalima sukurti naujo įrašo / elemento",
  "relatedItemTitle": "Susijusi lentelė / sluoksnis",
  "relatedFeatureCount": "${layerTitle} su ${featureCount} elementais",
  "createNewFeatureLabel": "Kurti naują elementą, skirtą ${layerTitle}",
  "invalidRelationShipMsg": "Įsitikinkite, kad pirminio rakto: '${parentKeyField}' reikšmė yra tinkama",
  "pendingFeatureSaveMsg": "Įrašykite pakeistus elementus prieš kurdami susijusį elementą.",
  "attachmentsRequiredMsg": "(*) Reikalingi priedai.",
  "coordinatePopupTitle": "Perkelti elementą į XY vietą",
  "coordinatesSelectTitle": "Koordinačių sistema:",
  "mapSpecialReferenceDropdownOption": "Žemėlapio koordinačių sistema",
  "latLongDropdownOption": "Platuma/Ilguma",
  "xAttributeTextBoxLabel": "X koordinatė:",
  "yAttributeTextBoxLabel": "Y koordinatė:",
  "latitudeTextBoxLabel": "Platuma:",
  "longitudeTextBoxLabel": "Ilguma:",
  "presetGroupFieldsLabel": "${groupName} bus taikomas šiems sluoksnio laukams:",
  "presetGroupNoFieldsLabel": "${groupName} neturi jokių susijusių laukų",
  "groupInfoLabel": "${groupName} grupės informacija",
  "editGroupInfoIcon": "Redaguoti ${groupName} grupės reikšmę",
  "filterEditor": {
    "all": "Viskas",
    "noAvailableTempaltes": "Galimų šablonų nėra",
    "searchTemplates": "Ieškoti šablonų",
    "filterLayerLabel": "Filtruoti sluoksnius"
  },
  "invalidConfiguration": "Valdiklis nesukonfigūruotas arba konfigūracijos sluoksnių žemėlapyje nebėra. Atidarykite aplikaciją kūrimo režime ir iš naujo sukonfigūruokite valdiklį.",
  "geometryServiceURLNotFoundMSG": "Negalima gauti geometrijos paslaugos URL",
  "clearSelection": "Valyti",
  "refreshAttributes": "Atnaujinti elementų atributus",
  "automaticAttributeUpdatesOn": "Automatiškai atnaujinti elementų atributus: ĮJUNGTA",
  "automaticAttributeUpdatesOff": "Automatiškai atnaujinti elementų atributus: IŠJUNGTA",
  "moveSelectedFeatureToGPS": "Perkelti pasirinktą elementą į dabartinę GPS vietą",
  "moveSelectedFeatureToXY": "Perkelti pasirinktą elementą į XY vietą",
  "mapNavigationLocked": "Žemėlapio naršymas: užrakintas",
  "mapNavigationUnLocked": "Žemėlapio naršymas: atrakintas",
  "copyFeatures": {
    "title": "Kopijuoti elementus",
    "createFeatures": "Kurti elementus",
    "createSingleFeature": "Kurti 1 kelių geometrijų elementą",
    "noFeaturesSelectedMessage": "Pasirinktų elementų nėra",
    "selectFeatureToCopyMessage": "Pasirinkite norimus kopijuoti elementus.",
    "multipleFeatureSaveWarning": "Pastaba: kuriant kelių dalių elementus kopijuojant elementą išsaugos visus elementus iš karto"
  },
  "addingFeatureError": "Sluoksnyje pridedant pasirinktus elementus įvyko klaida. Pabandykite dar kartą.",
  "addingFeatureErrorCount": "Nepavyko nukopijuoti elementų: '${copyFeatureErrorCount}'.",
  "selectingFeatureError": "Sluoksnyje pasirenkant elementus įvyko klaida. Pabandykite dar kartą.",
  "customSelectOptionLabel": "Pasirinkite norimus kopijuoti elementus",
  "noFeatureSelectedMessage": "Pasirinktų elementų nėra.",
  "multipleFeatureSaveMessage": "Visi elementai bus iš karto įrašyti. Norite tęsti?",
  "relativeDates": {
    "dateTypeLabel": "Datos tipas",
    "valueLabel": "Reikšmė",
    "fixed": "Fiksuotas",
    "current": "Dabartinis",
    "past": "Praėjęs",
    "future": "Būsimas",
    "popupTitle": "Pasirinkite reikšmę",
    "hintForFixedDateType": "Patarimas: nurodyta data ir laikas bus naudojami kaip iš anksto nustatyta numatytoji reikšmė.",
    "hintForCurrentDateType": "Patarimas: dabartinė data ir laikas bus naudojami kaip iš anksto nustatyta numatytoji reikšmė.",
    "hintForPastDateType": "Patarimas: nurodyta data ir laikas bus atimti iš dabartinės datos ir laiko ir skirti iš anksto nustatytai numatytai reikšmei.",
    "hintForFutureDateType": "Patarimas: nurodyta data ir laikas bus pridėti prie dabartinės datos ir laiko ir skirti iš anksto nustatytai numatytai reikšmei.",
    "noDateDefinedTooltip": "Data neapibrėžta",
    "relativeDateWarning": "Kad galėtumėte įrašyti numatytąją iš anksto nustatytą reikšmę, turi būti nurodyti datos ir laiko reikšmę."
  }
});