define({
  "_widgetLabel": "상황 인식",
  "locate_incident": "사건 찾기",
  "reverse_geocoded_address": "가장 가까운 주소",
  "reverse_geocoded_error": "사용할 수 없음",
  "now": "지금",
  "wind": "풍력",
  "SUN": "일",
  "MON": "월",
  "TUE": "화",
  "WED": "수",
  "THU": "목",
  "FRI": "금",
  "SAT": "토",
  "actionLabel": "위치 설정",
  "drawPoint": "포인트 그리기",
  "drawLine": "라인 그리기",
  "drawPolygon": "폴리곤 그리기",
  "saveIncident": "저장",
  "clearIncident": "시작",
  "noFeaturesFound": "피처를 찾을 수 없습니다.",
  "downloadCSV": "다운로드",
  "sum": "합계",
  "min": "최소",
  "max": "최대",
  "avg": "평균",
  "count": "COUNT",
  "area": "AREA",
  "length": "LENGTH",
  "update_btn": "완료",
  "delete_btn": "삭제",
  "get_directions": "길찾기",
  "incident": "사건",
  "incidents": "사건",
  "buffer": "버퍼",
  "buffers": "버퍼",
  "weather": "날씨",
  "poweredBy": "제공:",
  "_featureAction_ActionLabel": "위치 설정",
  "_featureAction_AddRemoveActionLabel": "위치 추가/제거",
  "snapshot": "앱 ID로 생성한 스냅샷 폴더:",
  "user_credentials": "사용자에게 유효한 권한이 없습니다.",
  "snapshot_complete": "스냅샷이 생성되었습니다.",
  "snapshot_failed": "스냅샷을 생성하지 못했습니다.",
  "notPolySnapShot": "스냅샷을 생성하려면 먼저 버퍼 거리를 지정하세요.",
  "notValidDownload": "다운로드할 올바른 결과가 없습니다.",
  "snapshot_append": "스냅샷",
  "of_append": "/",
  "layer_append": "레이어",
  "downloadAll": "모두 다운로드",
  "createSnapshot": "스냅샷 생성",
  "calculated_results": "요약된 정보",
  "closest": "가장 가까운 피처",
  "proximity": "인접도",
  "summary": "요약",
  "groupedSummary": "그룹화된 개수",
  "_count": "개수",
  "utc": "UTC",
  "approximate": "대략",
  "snapshot_name": "스냅샷 이름 설정",
  "invalid_snapshot_name": "잘못된 스냅샷 이름입니다."
});