define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Legg til punkt ved å klikke på kartet",
  "addRingsDtWt": "Legg til ringer, kjøretid eller gåtid.",
  "apply": "Bruk",
  "back": "Tilbake",
  "colon": ":",
  "creditInformation": "Creditinformasjon",
  "driveTime": "Kjøretid",
  "esriInfographics": "Esri-infografikk",
  "esriReports": "Esri-rapporter",
  "headerDescription_km": "kilometer",
  "headerDescription_miles": "mile",
  "headerDescription_minutes": "minutt",
  "infographics": "Infografikk",
  "invalidValueRing": "Verdiene må være fra 0 til 1000.",
  "invalidValueDTWT": "Verdiene må være fra 0 til 300.",
  "km": "km",
  "miles": "miles",
  "minutes": "minutter",
  "myInfographics": "Min infografikk",
  "myReports": "Mine rapporter",
  "noPermissions": "Kontoen din kan ikke kjøre miniprogrammet Business Analyst. Hvis du vil kjøre Business Analyst, må administratoren for organisasjonen gi deg <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">tillatelsene</a> Geoberikelse og Nettverksanalyse samt tildele <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">credits</a>.",
  "radii": "radier",
  "radius": "Radius",
  "radius_lowercase": "radius",
  "reports": "Rapporter",
  "ring": "Ring",
  "rings": "Ringer",
  "runInfographic": "Kjør infografikk",
  "runReport": "Kjør rapport",
  "selectPointOrPolygon": "Velg et punkt- eller polygongeoobjekt i kartet, søk etter en adresse eller et sted, eller plasser en nål på kartet for å vise med informasjon om områder.",
  "selectReport": "Velg rapport",
  "selectTemplate": "Velg mal",
  "sharedInfographics": "Delt infografikk",
  "sharedReports": "Delte rapporter",
  "thisEntryIsNotValid": "Denne oppføringen er ikke gyldig.",
  "time": "Tid",
  "walkTime": "Gåtid",
  "widgetDescription": "Åpne infografikk og rapporter som oppsummerer viktige indikatorer og data for et område.",
  "None": "Velg..."
});