define({
  "taskUrl": "URL úlohy",
  "serviceURLPlaceholder": "Zadejte URL úlohy geoprocessingu.",
  "layerOrder": "Pořadí vrstev",
  "defaultValue": "Výchozí hodnota",
  "inputFeatureBy": "Jak zadávat prvek",
  "inputRecordBy": "Jak zadávat záznam",
  "renderer": "Vykreslovač",
  "displayType": "Typ zobrazení",
  "helpUrl": "URL nápovědy",
  "useResultMapService": "Zobrazit výsledek mapovou službou",
  "drawOnMap": "Interaktivně kreslit do mapy",
  "selectLayer": "Vybrat vrstvu z mapy",
  "selectTable": "Vybrat tabulku z mapy",
  "shareResults": "Přidat výsledek jako operační vrstvu",
  "setTask": "Nastavit",
  "setTaskTitle": "Nastavit GP úlohu",
  "enablePopup": "Povolit vyskakovací okna",
  "unSupportGeometryType": "Vykreslovač nelze nastavit, protože je typ geometrie neznámý.",
  "useUrlForGPInput": "Zadat adresu URL",
  "useUploadForGPInput": "Nahrát soubor",
  "selectFileToUpload": "Vybrat soubor…",
  "rasterFormat": "Formát rastrových dat",
  "noFileSelected": "Nebyl vybrán žádný soubor.",
  "uploadSuccess": "Soubor byl úspěšně nahrán.",
  "showLayerContent": "Zobrazit obsah vrstvy",
  "urlPlaceholder": "Adresa URL pro přístup k datům",
  "useShapefile": "Použít shapefile v místním souborovém systému",
  "allowToExport": "Povolit export výsledků",
  "useDynamicSchema": "Výstup může používat odlišné schéma, použijte dynamické schéma namísto předdefinovaného schématu.",
  "useCurrentMapExtent": "Použít aktuální rozsah mapy",
  "ignoreOutput": "Ignorovat tento výstup",
  "turnOffOutput": "Ve výchozím nastavení vypnout tuto vrstvu",
  "inputJSONString": "Vstupní řetězec JSON"
});