define({
  "_widgetLabel": "การติดตามเครือข่าย",
  "_featureAction_NetworkTraceSkip": "ข้ามการติดตาม",
  "_featureAction_NetworkTraceUnskip": "ลบออกจากตำแหน่งการข้าม",
  "removedFromSkipLocations": "ลบออกจากตำแหน่งการข้าม",
  "alreadyRemovedFromSkipLocations": "ลบออกจากตำแหน่งการข้ามอยู่แล้ว",
  "locationSkipped": "ตำแหน่งที่ตั้งที่ข้าม",
  "configError": "ไม่ได้กำหนดค่าวิดเจ็ตอย่างถูกต้อง",
  "geometryServiceURLNotFoundMSG": "ไม่สามารถรับ URL เซอร์วิสเรขาคณิต",
  "clearButtonValue": "เคลียร์",
  "GPExecutionFailed": "ไม่สามารถดำเนินการติดตามได้ โปรดลองอีกครั้ง",
  "backButtonValue": "กลับ",
  "exportToCSVSuccess": "บันทึกเป็นไฟล์ CSV เสร็จสมบูรณ์",
  "lblInputLocTab": "อินพุทตำแหน่งที่ตั้ง",
  "lblBlockLocTab": "บล็อคตำแหน่งที่ตั้ง",
  "lblInputLocation": "อินพุทฟีเจอร์",
  "lblBlockLocation": "บล็อคฟีเจอร์",
  "lblInputLocHeader": "อินพุทตำแหน่งที่ตั้ง (0)",
  "lblBlockLocHeader": "บล็อคตำแหน่งที่ตั้ง (0)",
  "inputTabTitle": "ข้อมูลนำเข้า",
  "outputTabTitle": "ผลลัพธ์",
  "exportSelectAllCheckBoxLabel": "เลือกทั้งหมด",
  "lblSkipLocHeader": "ข้ามตำแหน่งที่ตั้ง (0)",
  "lblSkipLocation": "ตำแหน่ง",
  "lblSkipLocTab": "ข้ามตำแหน่งที่ตั้ง",
  "skipAllLocationButtonLabel": "ข้ามตำแหน่งที่ตั้งทั้งหมด",
  "confirmSkipAllLocationsMessage": "ตำแหน่งทั้งหมดจะถูกข้าม คุณต้องการดำเนินการต่อหรือไม่",
  "locationAlreadySkippedMessage": "ข้ามตำแหน่งที่ตั้งไปแล้ว",
  "removeAllSkipLocationLabel": "ลบข้อมูลทั้งหมด",
  "newProjectOptionText": "โปรเจกต์ใหม่",
  "selectProject": "เลือกโครงการ",
  "saveButtonLabel": "บันทึก",
  "exportToCSVText": "บันทึกเป็นไฟล์ CSV",
  "editProjectAttributesToolTip": "แก้ไขลักษณะของโครงการ",
  "projectNameLabel": "ชื่อโครงการ",
  "saveProjectPopupTitle": "บันทึก",
  "saveAsLabel": "บันทึกเป็น",
  "saveChangesMsg": "ต้องการบันทึกการเปลี่ยนแปลงของคุณไปยัง <b>${loadProjectDropdownlabel}</b> หรือบันทึกในรูปแบบโปรเจคใหม่หรือไม่",
  "creatingNewProjectErrorMessage": "เกิดข้อผิดพลาดขณะสร้างโปรเจคใหม่ โปรดลองอีกครั้ง",
  "projectNameFetchingErr": "เกิดข้อผิดพลาดขณะดึงข้อมูลชื่อโปรเจคที่มีอยู่ โปรดลองอีกครั้ง",
  "projectAttributeLoadingErr": "เกิดข้อผิดพลาดขณะโหลดแอตทริบิวต์โปรเจค โปรดลองอีกครั้ง",
  "attributeUpdatedMsg": "อัปเดตแอตทริบิวต์เรียบร้อยแล้ว",
  "projectAttributeUpdatingErr": "เกิดข้อผิดพลาดขณะอัปเดตแอตทริบิวต์โปรเจค",
  "loadingProjectDetailsErrorMessage": "เกิดข้อผิดพลาดขณะดึงข้อมูลธง อุปสรรค และข้ามตำแหน่งที่ตั้ง โปรดลองอีกครั้ง",
  "savingProjectDetailsErr": "เกิดข้อผิดพลาดขณะบันทึกรายละเอียดโปรเจค โปรดลองบันทึกโปรเจคอีกครั้ง",
  "updatingOutagePolygonErr": "เกิดข้อผิดพลาดขณะอัปเดตโพลีกอนไฟดับ โปรดลองบันทึกโปรเจคอีกครั้ง",
  "deletingExistingPolygonErr": "เกิดข้อผิดพลาดขณะลบโพลีกอนไฟดับที่มีอยู่ โปรดลองบันทึกโปรเจคอีกครั้ง",
  "loadingProjectFeaturesErr": "เกิดข้อผิดพลาดขณะโหลดฟีเจอร์โปรเจค โปรดลองโหลดโปรเจคอีกครั้ง",
  "addingProjectFeaturesErr": "เกิดข้อผิดพลาดขณะเพิ่มฟีเจอร์โปรเจค โปรดลองบันทึกโปรเจคอีกครั้ง",
  "deletingExistingProjectFeaturesErr": "เกิดข้อผิดพลาดขณะลบฟีเจอร์โปรเจคที่มีอยู่ โปรดลองบันทึกโปรเจคอีกครั้ง",
  "projectNotFoundErr": "ไม่พบโปรเจค",
  "projectLayersNotFound": "ไม่พบชั้นข้อมูลการตั้งค่าโปรเจคที่กำหนดค่าไว้ในแผนที่ วิดเจ็ตจะถูกโหลดใน 'โหมดร่าง'",
  "fetchingOutagePolygonMessage": "เกิดข้อผิดพลาดขณะดึงข้อมูลโพลีกอนไฟดับ โปรดลองโหลดโปรเจคอีกครั้ง",
  "projectNameExistsMessage": "มีชื่อโปรเจคอยู่แล้ว โปรดใช้ชื่อโปรเจคที่ไม่ซ้ำกัน",
  "fetchingProjectNamesErrorMessage": "เกิดข้อผิดพลาดขณะดึงข้อมูลชื่อโปรเจคที่มีอยู่ โปรดลองบันทึกโปรเจคอีกครั้ง",
  "enterProjectNameMessage": "โปรดป้อนชื่อโปรเจค",
  "projectLengthErrorMessage": "ชื่อโปรเจคต้องไม่ยาวเกิน",
  "gpServiceNotAccessible": "บัญชีผู้ใช้ของคุณไม่สามารถเข้าใช้งานเซอร์วิสที่จำเป็นในการดำเนินการติดตามนี้ได้",
  "loadingClonedLayerErrorMessage": "เกิดข้อผิดพลาดขณะโหลดชั้นข้อมูลฟีเจอร์ที่โคลน โปรดลองอีกครั้ง",
  "addingFeatureInClonedLayerError": "เกิดข้อผิดพลาดขณะเพิ่มกราฟิกลงในชั้นข้อมูลฟีเจอร์ที่โคลน โปรดลองอีกครั้ง",
  "selectingFeatureInClonedLayerError": "เกิดข้อผิดพลาดขณะเลือกกราฟิกในชั้นข้อมูลฟีเจอร์ที่โคลน โปรดลองอีกครั้ง",
  "filteredProjectError": "เกิดข้อผิดพลาดขณะตรวจสอบการดึงข้อมูลรายละเอียดโปรเจคที่กรอง โปรดลองอีกครั้ง",
  "filteredProjectMessage": "แอตทริบิวต์โปรเจคที่เลือกไม่พร้อมใช้งาน เนื่องจากตัวกรองที่ใช้งานจากเว็บแมปหรือวิดเจ็ทอื่น ลบตัวกรองแล้วลองใหม่อีกครั้ง",
  "filteredProjectLoadMessage": "โปรเจคนี้ไม่พร้อมใช้งานอีกต่อไป โปรดเลือกโปรเจคที่ใช้งาน",
  "defaultValueForRunButton": "ทำงาน",
  "closeButtonLabel": "เอาออก"
});