define({
  "taskUrl": "URL Tugas",
  "serviceURLPlaceholder": "Harap masukkan URL tugas Geoprocessing",
  "layerOrder": "Urutan Layer",
  "defaultValue": "Nilai Default",
  "inputFeatureBy": "Input Fitur menurut",
  "renderer": "Perender",
  "displayType": "Tipe tampilan",
  "helpUrl": "URL Bantuan",
  "useResultMapService": "Gunakan opsi gambar dari layanan peta hasil",
  "drawOnMap": "Menggambar secara interaktif pada peta",
  "selectLayer": "Memilih sebuah layer dari peta",
  "shareResults": "Tambahkan hasil sebagai layer operasional",
  "setTask": "Atur",
  "setTaskTitle": "Tetapkan Tugas GP",
  "enablePopup": "Aktifkan popup",
  "unSupportGeometryType": "Tidak dapat menetapkan perender karena tipe geometri tidak diketahui.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Unggah file",
  "selectFileToUpload": "Pilih file...",
  "rasterFormat": "Format data Raster",
  "noFileSelected": "Tidak ada file yang dipilih!",
  "uploadSuccess": "Berhasil mengunggah file!",
  "showLayerContent": "Tampilkan konten layer",
  "urlPlaceholder": "URL rangkaian fitur",
  "useShapefile": "Gunakan shapefile dalam sistem file lokal",
  "allowToExport": "Izinkan untuk mengekspor hasil",
  "useDynamicSchema": "Output mungkin menggunakan skema yang berbeda, gunakan skema dinamik selain skema yang sudah ada."
});