define({
  "_widgetLabel": "可視解析",
  "observerLocation": "観測点",
  "formatIconTooltip": "入力の書式設定",
  "addPointToolTip": "観測点の追加",
  "fieldOfView": "視野",
  "useMilsText": "角度にはミルを使用",
  "observerHeight": "観測点の高度",
  "minObsDistance": "最小観測距離",
  "maxObsDistance": "最大観測距離",
  "taskURLError": "ウィジェットの構成ファイルにアクセスできない URL が含まれています。システム管理者に確認してください。",
  "taskURLInvalid": "このウィジェットで構成されたジオプロセシング タスクが有効ではありません。システム管理者に確認してください。",
  "viewshedError": "可視解析設定の作成中にエラーが発生しました。 観測点が標高サーフェスの範囲内にあることを確認してください。</p>",
  "validationError": "<p>可視解析設定の作成フォームが見つからないか、無効なパラメーターです。次のことを確認してください:</p><ul><li>観測点が設定済みである。</li><li>観測点の視野が 0 でない。</li><li>観測点の高度に有効な値が含まれている。</li><li>最小および最大観測距離に有効な値が含まれている。</li></ul>",
  "comfirmInputNotation": "入力表記の確認",
  "notationsMatch": "入力と一致する表記。使用する内容を確認してください。",
  "createBtn": "作成",
  "clearBtn": "消去",
  "setCoordFormat": "座標形式の文字列の設定",
  "prefixNumbers": "正と負の数値に '+/-' の接頭辞を追加",
  "parseCoordinatesError": "座標を解析できません。 入力を確認してください。",
  "cancelBtn": "キャンセル",
  "applyBtn": "適用",
  "invalidMessage": "数値を入力してください。",
  "observerRangeMessage": "無効な観測点の高度",
  "minimumRangeMessage": "無効な最小観測範囲",
  "maximumRangeMessage": "最大観測範囲は最小観測範囲より大きい必要があり、${limit} ${units} を超えてはなりません。",
  "portalURLError": "ArcGIS Online 組織サイトまたは Portal for ArcGIS の URL が構成されていません。 システム管理者に確認してください。",
  "privilegeError": "このユーザー ロールでは、解析を実行できません。 解析を実行するには、組織の管理者が特定の<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">権限</a>を付与する必要があります。",
  "noServiceError": "標高解析サービスが利用できません。 ArcGIS Online 組織サイトまたは Portal for ArcGIS の URL の構成を確認してください。",
  "pointToolTooltip": "クリックして観測点の位置を追加",
  "degreesLabel": "度",
  "milsLabel": "ミル",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "度 (10進) - 緯度/経度",
  "DDLongLatNotation": "度 (10進) - 経度/緯度",
  "DDMLatLongNotation": "度分 (10進) - 緯度/経度",
  "DDMLongLatNotation": "度分 (10進) - 経度/緯度",
  "DMSLatLongNotation": "度分秒 - 緯度/経度",
  "DMSLongLatNotation": "度分秒 - 経度/緯度",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - バンド文字",
  "UTMHemNotation": "UTM - 半球 (N/S)",
  "mainPageTitle": "放射状見通し線",
  "resultsTitle": "結果",
  "publishBtnLabel": "公開",
  "layerName": "公開されたレイヤー名",
  "invalidLayerName": "レイヤー名は、英数字とアンダースコア (_) だけを含むようにする必要があります。",
  "missingLayerName": "レイヤー名の入力",
  "back": "戻る",
  "publishingFailedLayerExists": "公開に失敗しました: フィーチャ サービス名 {0} はすでに存在しています。 別の名前を選択してください。",
  "checkService": "次のサービスを確認: {0}",
  "createService": "次のサービスを作成: {0}",
  "unableToCreate": "次のものを作成できません: {0}",
  "addToDefinition": "定義に追加: {0}",
  "successfullyPublished": "Web レイヤー {0} を正常に公開できました。Web レイヤーの管理",
  "userRole": "ユーザーにアクセス権限がないため、サービスを作成できません。",
  "publishToNewLayer": "新しいフィーチャ レイヤーに結果を公開",
  "missingLayerNameMessage": "公開の前に、有効なレイヤー名を入力する必要があります。",
  "regionTypeLabel": "地域タイプ",
  "centerPointLabel": "中心点",
  "observationHeightLabel": "観測点の高さ",
  "heightUnitLabel": "高さ単位",
  "minObservationDistanceLabel": "最小観測距離",
  "maxObservationDistance": "最大観測距離",
  "distanceUnitLabel": "距離単位",
  "fovstartAngleLabel": "FOV 開始角度",
  "fovEndAngleLabel": "FOV 終了角度",
  "andleUnitsLabel": "角度単位"
});