define({
  "showArcgisBasemaps": "Incluir mapas base do Portal",
  "add": "Clique para Adicionar um Novo Mapa Base",
  "edit": "Propriedades",
  "titlePH": "Título do Mapa Base",
  "thumbnailHint": "Clique na imagem para atualizar",
  "urlPH": "URL da Camada",
  "addlayer": "Adicionar Mapa Base",
  "warning": "Entrada incorreta",
  "save": "Retroceder e Guardar",
  "back": "Retroceder e Cancelar",
  "addUrl": "Adicionar URL",
  "autoCheck": "Verificar Automaticamente",
  "checking": "Verificando...",
  "result": "Guardado com sucesso",
  "spError": "Todos os mapas base adicionados à galeria tem de ter a mesma referência espacial.",
  "invalidTitle1": "Um mapa base '",
  "invalidTitle2": "' já existe. Por favor, escolha outro título.",
  "invalidBasemapUrl1": "Este tipo de camada não pode ser utilizado como mapa base.",
  "invalidBasemapUrl2": "O mapa base que está a adicionar tem uma referência espacial diferente do mapa actual.",
  "addBaselayer": "Adicionar Camada de Mapa Base",
  "repectOnline": "Sincronizar sempre com as definições de Galeria de Mapas Base da organização",
  "customBasemap": "Configurar mapas base personalizados",
  "basemapTips": "Clique em \"${import}\" ou em \"${createNew}\" para adicionar mapas base.",
  "importBasemap": "Importar",
  "createBasemap": "Criar Novo",
  "importTitle": "Importar Mapas Base",
  "createTitle": "Novo Mapa Base",
  "selectGroupTip": "Selecione um grupo cujos mapas web podem ser utilizados como mapas base.",
  "noBasemaps": "Não existem mapas base.",
  "defaultGroup": "Padrão Esri",
  "defaultOrgGroup": "Padrão da Organização",
  "warningTitle": "Aviso",
  "confirmDelete": "Pretende eliminar os mapas base selecionados?",
  "noBasemapAvailable": "Não existem quaisquer mapas base disponíveis, ou todos os mapas base têm referências espaciais diferentes da do mapa base atual."
});