define({
  "_widgetLabel": "Synlighet",
  "observerLocation": "Observatörsplats",
  "formatIconTooltip": "Formatinmatning",
  "addPointToolTip": "Lägg till observatörsplats",
  "fieldOfView": "Synfält",
  "useMilsText": "Använd streck för vinklar",
  "observerHeight": "Observatörs höjd över marken",
  "minObsDistance": "Minsta observerbara avstånd",
  "maxObsDistance": "Största observerbara avstånd",
  "taskURLError": "Widgetens konfigurationsfil innehåller en URL-adress som inte kan nås. Kontakta systemadministratören",
  "taskURLInvalid": "Geobearbetningsåtgärden som konfigurerats med denna widget är inte giltig. Kontakta systemadministratören",
  "viewshedError": "Ett fel inträffade medan synligheten skapades. Säkerställ att observatörsplatsen hamnar inom utbredningen för höjdytan.</p>",
  "validationError": "<p>Formuläret för att skapa synlighet innehåller saknade eller ogiltiga parametrar. Säkerställ att:</p><ul><li>En observatörsplats har angetts.</li><li>Observatörens synfält inte är 0.</li><li>Observatörens höjd innehåller ett giltigt värde.</li><li>Det minimala och maximala observerbara avståndet innehåller giltiga värden.</li></ul>",
  "comfirmInputNotation": "Bekräfta inmatningsnotation",
  "notationsMatch": "notationer matchar inmatningen. Bekräfta vilka du vill använda:",
  "createBtn": "Skapa",
  "clearBtn": "Avmarkera",
  "setCoordFormat": "Ange koordinatsträng",
  "prefixNumbers": "Lägg till prefixet \"+/-\" för positiva och negativa tal",
  "parseCoordinatesError": "Det gick inte att tolka koordinaterna. Kontrollera din inmatning.",
  "cancelBtn": "Avbryt",
  "applyBtn": "Verkställ",
  "invalidMessage": "Ange ett numeriskt värde.",
  "observerRangeMessage": "Ogiltig observatörshöjd",
  "minimumRangeMessage": "Ogiltigt minimalt observerbart intervall",
  "maximumRangeMessage": "Maximalt observerbart intervall måste vara större än minimalt observerbart intervall och får inte vara mer än ${limit} ${units}.",
  "portalURLError": "URL:en till ArcGIS Online-organisationen eller Portal for ArcGIS har inte angetts. Fråga din systemadministratör.",
  "privilegeError": "Din användarroll kan inte utföra analyser. För att du ska kunna utföra analyser måste organisationens administratör bevilja dig vissa <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">behörigheter</a>.",
  "noServiceError": "Tjänsten för höjdanalys är inte tillgänglig. Kontrollera konfigurationerna för din ArcGIS Online-organisation eller Portal for ArcGIS.",
  "pointToolTooltip": "Klicka för att lägga till observatörsplats",
  "degreesLabel": "grader",
  "milsLabel": "streck",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Decimalgrader – Latitud/longitud",
  "DDLongLatNotation": "Decimalgrader – Longitud/latitud",
  "DDMLatLongNotation": "Grader decimalminuter – Latitud/longitud",
  "DDMLongLatNotation": "Grader decimalminuter – Longitud/latitud",
  "DMSLatLongNotation": "Grader minuter sekunder – Latitud/longitud",
  "DMSLongLatNotation": "Grader minuter sekunder – Longitud/latitud",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – Bandbokstav",
  "UTMHemNotation": "UTM – Halvklot (N/S)"
});