define({
  "styleText": "Escolha um estilo para a ferramenta Oscilar",
  "vertical": "Barra vertical",
  "horizontal": "Barra horizontal",
  "scope": "Luneta",
  "barColor": "Cor da barra",
  "swipeMode": "Modo Oscilar",
  "singleLayer": "Única camada",
  "MultipleLayers": "Múltiplas Camadas",
  "allowToSwipe": "Permitir oscilar",
  "layer": "Camada",
  "swipeByDefault": "Utilizar por padrão",
  "defaultLayerMustBeVisible": "A camada padrão deve ser visível",
  "noDefaultLayer": "Defina as camadas para oscilar por padrão",
  "defaultLayerHolder": "Clique para selecionar",
  "selectLayers": "Selecionar camadas",
  "layerText": "Selecione as camadas que deseja oscilar por padrão",
  "spyglassText": "Selecione a camada para aparecer dentro da luneta por padrão.",
  "layerHint": "Nota: Se a camada estiver ocultada por camadas superiores, a oscilação não terá efeito.",
  "isZoom": "Zoom na camada de oscilação",
  "isZooms": "Zoom nas camadas de oscilação",
  "layersAvailable": "Escolha quais camadas oscilar:"
});