define({
  "_widgetLabel": "Звіт про об’єкт",
  "select": "Вибрати",
  "draw": "Намалювати",
  "chooseALayer": "Вибрати шар",
  "clickAFeature": "Клацніть на об’єкті на карті, щоб вибрати його.",
  "loadingFeatures": "Виконується отримання даних про вибраний об'єкт...",
  "errorTitle": "Помилка",
  "errorIdentify": "Помилка визначення елементів. Перевірте журнал консолі для отримання детальної інформації.",
  "infoWindowTitle": "Детальна інформація",
  "layerLabel": "Назва шару",
  "reviewStatusLabel": "Стан перегляду",
  "selectReviewStatusAdd": "Додати об'єкт",
  "selectReviewStatusDelete": "Видалити об'єкт",
  "selectReviewStatusMove": "Перемістити об'єкт",
  "selectReviewStatusReshape": "Змінити форму об'єкту",
  "drawReviewStatusMissing": "Відсутній об'єкт(-и)",
  "drawReviewStatusPosition": "Помилка визначення положення",
  "drawReviewStatusShape": "Помилка форми",
  "drawReviewStatusAttribute": "Помилка атрибуту",
  "notesLabel": "Примітки",
  "severityLabel": "Ступінь серйозності",
  "reportedByLabel": "Повідомив",
  "reportedByDefault": "анонімний",
  "reportButton": "Звіт",
  "reportMessage": "Звіт отримано",
  "errorReportMessage": "При складанні звіту про ваш об’єкт виникла помилка",
  "drawErrorInstructions": "Виберіть точку, лінію або полігон та намалюйте геометрію помилки на карті:",
  "errorMapService": "При отриманні інформації про картографічний сервіс виникла помилка",
  "noFeatureSelected": "На вибраному місці розташування не було знайдено жодних об'єктів",
  "selectFeatureMapPoint": "Клацніть, щоб вибрати об'єкт",
  "drawFeatureMapPoint": "Клацніть, щоб додати точку",
  "popupMessage": "Повідомлення",
  "popupError": "Помилка",
  "manyFeaturesSelected": "Знайдено більше одного об’єкту. Збільшіть масштаб та виберіть об'єкт для складання звіту."
});