define({
  "_widgetLabel": "Świadomość sytuacji",
  "locate_incident": "Zlokalizuj zdarzenie",
  "reverse_geocoded_address": "Najbliższy adres",
  "reverse_geocoded_error": "Niedostępny",
  "now": "TERAZ",
  "wind": "WIATR",
  "SUN": "NIEDZ",
  "MON": "PON",
  "TUE": "WT",
  "WED": "ŚR",
  "THU": "CZW",
  "FRI": "PT",
  "SAT": "SOB",
  "actionLabel": "Skonfiguruj lokalizację",
  "drawPoint": "Rysuj punkt",
  "drawLine": "Rysuj linię",
  "drawPolygon": "Rysuj poligon",
  "saveIncident": "Zapisz",
  "clearIncident": "Rozpocznij od nowa",
  "noFeaturesFound": "Nie odnaleziono obiektów.",
  "downloadCSV": "Pobierz",
  "sum": "Sum",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Średnia",
  "count": "LICZBA",
  "area": "POWIERZCHNIA",
  "length": "DŁUGOŚĆ",
  "update_btn": "Wykonano",
  "delete_btn": "Usuń",
  "get_directions": "Wyznacz wskazówki dojazdu",
  "incident": "Zdarzenie",
  "incidents": "Zdarzenia",
  "buffer": "Bufor",
  "buffers": "Bufory",
  "weather": "Pogoda",
  "poweredBy": "Korzysta z",
  "_featureAction_ActionLabel": "Skonfiguruj lokalizację",
  "_featureAction_AddRemoveActionLabel": "Dodaj/usuń lokalizację",
  "snapshot": "Folder SnapShot utworzony przez aplikację o identyfikatorze:",
  "user_credentials": "Użytkownik nie ma prawidłowych uprawnień.",
  "snapshot_complete": "Pomyślnie utworzono migawkę.",
  "snapshot_failed": "Tworzenie migawki nie powiodło się.",
  "notPolySnapShot": "Podaj odległość buforowania przed utworzeniem migawki.",
  "notValidDownload": "Brak prawidłowych wyników do pobrania.",
  "snapshot_append": "Migawka",
  "of_append": "z",
  "layer_append": "warstwa",
  "downloadAll": "Pobierz wszystko",
  "createSnapshot": "Utwórz migawkę",
  "calculated_results": "Informacje zbiorcze",
  "closest": "Najbliższy obiekt",
  "proximity": "Bliskość",
  "summary": "Podsumowanie",
  "groupedSummary": "Pogrupowane zliczenia",
  "_count": "Liczba",
  "utc": "UTC",
  "approximate": "w przybliżeniu",
  "snapshot_name": "Skonfiguruj nazwę migawki",
  "invalid_snapshot_name": "Nieprawidłowa nazwa migawki."
});