define({
  "_widgetLabel": "Hálózati nyomkövetés",
  "_featureAction_NetworkTraceSkip": "Kihagyás követéskor",
  "_featureAction_NetworkTraceUnskip": "Eltávolítás helyek kihagyásakor",
  "removedFromSkipLocations": "Eltávolítva a helyek kihagyásakor",
  "alreadyRemovedFromSkipLocations": "Már eltávolítva a helyek kihagyásakor",
  "locationSkipped": "Hely kihagyva",
  "configError": "A widget nincs megfelelően konfigurálva.",
  "geometryServiceURLNotFoundMSG": "Nem sikerült meghatározni a geometriai adatszolgáltatás URL-címét",
  "clearButtonValue": "Törlés",
  "GPExecutionFailed": "A nyomkövetés nem végezhető el. Próbálja meg újra.",
  "backButtonValue": "Vissza",
  "exportToCSVSuccess": "A CSV-fájlba történ exportálás sikeresen megtörtént.",
  "lblInputLocTab": "Bemeneti helyek",
  "lblBlockLocTab": "Blokkhelyek",
  "lblInputLocation": "Bemeneti vektoros elem",
  "lblBlockLocation": "Blokk vektoros elem",
  "lblInputLocHeader": "Bemeneti helyek (0)",
  "lblBlockLocHeader": "Blokkhelyek (0)",
  "inputTabTitle": "Bemenet",
  "outputTabTitle": "Kimenet",
  "exportSelectAllCheckBoxLabel": "Összes kijelölése",
  "lblSkipLocHeader": "Helyek kihagyása (0)",
  "lblSkipLocation": "Hely",
  "lblSkipLocTab": "Helyek kihagyása",
  "skipAllLocationButtonLabel": "Minden hely kihagyása",
  "confirmSkipAllLocationsMessage": "Minden hely ki lesz hagyva. Folytatja?",
  "locationAlreadySkippedMessage": "A helyet már kihagyta",
  "removeAllSkipLocationLabel": "Összes eltávolítása",
  "newProjectOptionText": "Új projekt",
  "selectProject": "Projekt kiválasztása",
  "saveButtonLabel": "Mentés",
  "exportToCSVText": "Exportálás CSV-fájlba",
  "editProjectAttributesToolTip": "Projektattribútumok szerkesztése",
  "projectNameLabel": "Projektnév",
  "saveProjectPopupTitle": "Mentés",
  "saveAsLabel": "Mentés másként",
  "saveChangesMsg": "Menti a következővel kapcsolatos módosításait: <b>${loadProjectDropdownlabel}</b>, vagy pedig új projektként menti őket?",
  "creatingNewProjectErrorMessage": "Hiba történt az új projekt létrehozásakor. Próbálja meg újra.",
  "projectNameFetchingErr": "Hiba történt a meglévő projektnevek lekérése közben. Próbálja meg újra.",
  "projectAttributeLoadingErr": "Hiba történt a projektattribútumok betöltése közben. Próbálja meg újra.",
  "attributeUpdatedMsg": "Az attribútumok frissítése sikeresen megtörtént.",
  "projectAttributeUpdatingErr": "Hiba történt a projektattribútumok frissítése közben.",
  "loadingProjectDetailsErrorMessage": "Hiba történt a jelölők, akadályok lekérésekor és helyek kihagyásakor. Próbálja meg újra.",
  "savingProjectDetailsErr": "Hiba történt a projekt adatainak mentésekor. Próbálja meg ismét menteni a projektet.",
  "updatingOutagePolygonErr": "Hiba történt a szolgáltatáskimaradási polygon frissítése közben. Próbálja meg ismét menteni a projektet.",
  "deletingExistingPolygonErr": "Hiba történt a meglévő szolgáltatáskimaradási polygon törlése közben. Próbálja meg ismét menteni a projektet.",
  "loadingProjectFeaturesErr": "Hiba történt a projekt vektoros elemeinek betöltése közben. Próbálja meg ismét betölteni a projektet.",
  "addingProjectFeaturesErr": "Hiba történt a projekt vektoros elemeinek hozzáadása közben. Próbálja meg ismét menteni a projektet.",
  "deletingExistingProjectFeaturesErr": "Hiba történt a projekt meglévő vektoros elemeinek törlése közben. Próbálja meg ismét menteni a projektet.",
  "projectNotFoundErr": "A projekt nem található",
  "projectLayersNotFound": "A konfigurált projektbeállítási rétegek nem állnak rendelkezésre a térképen. A rendszer „Vázlat módban” tölti be a widgetet.",
  "fetchingOutagePolygonMessage": "Hiba történt a szolgáltatáskimaradási polygon lekérése közben. Próbálja meg ismét betölteni a projektet.",
  "projectNameExistsMessage": "A projektnév már létezik. Használjon egyedi projektnevet.",
  "fetchingProjectNamesErrorMessage": "Hiba történt a meglévő projektnevek lekérése közben. Próbálja meg ismét menteni a projektet.",
  "enterProjectNameMessage": "Adjon meg egy projektnevet.",
  "projectLengthErrorMessage": "A projektnév nem lehet hosszabb ennél:",
  "gpServiceNotAccessible": "A fiókja nem rendelkezik hozzáféréssel a szükséges szolgáltatáshoz a nyomvonal elkészítéséhez.",
  "loadingClonedLayerErrorMessage": "Hiba történt a klónozott vektoros réteg betöltésekor. Próbálja meg újra.",
  "addingFeatureInClonedLayerError": "Hiba történt a grafikának a klónozott vektoros réteghez való hozzáadása közben. Próbálja meg újra.",
  "selectingFeatureInClonedLayerError": "Hiba történt a grafikának a klónozott vektoros rétegben való kiválasztása közben. Próbálja meg újra.",
  "filteredProjectError": "Hiba történt a szűrt projektadatok lekérésekor. Próbálja meg újra.",
  "filteredProjectMessage": "A kiválasztott projektadatok az alkalmazott szűrők miatt nem érhetők el a webtérképről vagy másik widgetből. Törölje a szűrő(ke)t, majd próbálkozzon újra.",
  "filteredProjectLoadMessage": "Ez a projekt a továbbiakban nem érhető el. Válasszon aktív projektet.",
  "defaultValueForRunButton": "Futtatás",
  "closeButtonLabel": "Eltávolítás"
});