define({
  "labelBookmarkName": "Marca la visualització actual",
  "labelPlay": "Reprodueix-ho tot",
  "labelStop": "Atura",
  "labelDelete": "Suprimeix",
  "placeholderBookmarkName": "Nom del marcador",
  "errorNameExist": "El marcador ja existeix.",
  "errorNameNull": "Nom de marcador no vàlid.",
  "editTip": "Edita els marcadors",
  "exitEditTip": "Surt del mode d'edició",
  "syncTip": "Sincronitza",
  "cardsTips": "Visualització de quadrícula",
  "listTips": "Visualització de llista",
  "addBtn": "Afegeix",
  "deleteBtn": "Suprimeix",
  "changeThumbnailTip": "Canvia la miniatura",
  "dragReorderTip": "Mantén i arrossega per reordenar-ho",
  "deleteBtnTip": "Suprimeix el marcador",
  "editBtnTip": "Edita el marcador",
  "withVisibility": "Amb visibilitat de capes",
  "searchBookmark": "Cerca",
  "bookmarksFromConfig": "Marcadors preconfigurats",
  "bookmarksFromCache": "Marcadors temporals locals",
  "notice": "Avís",
  "changeNoticeTips": "Els canvis es desaran només a la memòria cau del navegador. La sincronització entre el widget i la seva configuració es desconnecta quan feu canvis.",
  "syncNoticeTips": "S'esborraran totes les vostres modificacions i es restauraran els marcadors configurats.",
  "dontShowAgain": "No ho tornis a mostrar",
  "saveVisibility": "Desa la visibilitat de la capa",
  "_widgetLabel": "Marcador"
});