define({
  "_widgetLabel": "Vizibilitate",
  "observerLocation": "Amplasarea observatorului",
  "formatIconTooltip": "Intrare format",
  "addPointToolTip": "Adăugați localizarea observatorului",
  "fieldOfView": "Câmp vizual",
  "useMilsText": "Utilizați miimi pentru unghiuri",
  "observerHeight": "Înălțimea observatorului",
  "minObsDistance": "Distanța minimă observabilă",
  "maxObsDistance": "Distanța maximă observabilă",
  "taskURLError": "Fişierul de configurare a widgetului conține un URL inaccesibil. Verificați cu administratorul dvs. de sistem",
  "taskURLInvalid": "Sarcina de geoprocesare configurată cu acest widget nu este valabilă. Verificați cu administratorul dvs. de sistem",
  "viewshedError": "A apărut o eroare la crearea vizibilității. Asigurați-vă că amplasarea observatorului dvs. intră în acoperirea suprafeței dvs. de elevație.</p>",
  "validationError": "<p>Formularul de creare a vizibilității are parametri lipsă sau nevalabili, Vă rugăm să vă asigurați că:</p><ul><li>A fost setată o amplasare a observatorului.</li><li>Câmpul Vizual al observatorului nu este 0.</li><li>Înălțimea observatorului include o valoare valabilă.</li><li>Distanțele minime și maxime includ valori valabile.</li></ul>",
  "comfirmInputNotation": "Confirmare notare intrare",
  "notationsMatch": "notaţii se potrivesc cu introducerea dvs. Confirmaţi ce doriţi să folosiţi:",
  "createBtn": "Creare",
  "clearBtn": "Golire",
  "setCoordFormat": "Setare şir format coordonate",
  "prefixNumbers": "Adăugați prefixul „+/-” la numerele pozitive și negative",
  "parseCoordinatesError": "Imposibil de analizat coordonatele. Verificaţi intrarea.",
  "cancelBtn": "Anulare",
  "applyBtn": "Aplicare",
  "invalidMessage": "Introduceţi o valoare numerică.",
  "observerRangeMessage": "Înălțimea observatorului nevalidă",
  "minimumRangeMessage": "Interval Observabil Minim Nevalid",
  "maximumRangeMessage": "Intervalul Observabil Maxim trebuie să fie mai mare decât Intervalul Observabil Minim și nu poate fi mai mare decât ${limit} ${units}.",
  "portalURLError": "Adresa URL a organizației dvs. ArcGIS Online sau a Portal for ArcGIS nu este configurată. Consultați administratorul de sistem",
  "privilegeError": "Rolul dvs. de utilizator nu poate efectua analize. Pentru a efectua o analiză, administratorul organizației trebuie să vă acorde anumite <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilegii</a>.",
  "noServiceError": "Serviciul de analiză a elevației nu este disponibil. Verificați configurările pentru organizația dvs. ArcGIS Online sau Portal for ArcGIS.",
  "pointToolTooltip": "Faceți clic pentru a adăuga localizarea observatorului",
  "degreesLabel": "grade",
  "milsLabel": "mile",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Grade zecimale - latitudine/longitudine",
  "DDLongLatNotation": "Grade zecimale - longitudine/latitudine",
  "DDMLatLongNotation": "Grade zecimale minute - latitudine/longitudine",
  "DDMLongLatNotation": "Grade zecimale minute - longitudine/latitudine",
  "DMSLatLongNotation": "Grade minute secunde - latitudine/longitudine",
  "DMSLongLatNotation": "Grade minute secunde - longitudine/latitudine",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - literă bandă",
  "UTMHemNotation": "UTM - emisferă (N/S)",
  "mainPageTitle": "Linie de vizare radială",
  "resultsTitle": "Rezultate",
  "publishBtnLabel": "Publicare",
  "layerName": "Nume strat tematic publicat",
  "invalidLayerName": "Numele stratului tematic trebuie să includă doar caractere alfanumerice și de subliniere",
  "missingLayerName": "Introduceți numele stratului tematic",
  "back": "Înapoi",
  "publishingFailedLayerExists": "Publicarea a eșuat: Aveți deja un serviciu de obiecte spațiale denumit {0}. Alegeți un alt nume.",
  "checkService": "Bifare serviciu: {0}",
  "createService": "Creare serviciu: {0}",
  "unableToCreate": "Nu se poate crea: {0}",
  "addToDefinition": "Adăugare la definiție: {0}",
  "successfullyPublished": "Publicare cu succes a stratului tematic web{0}Administrare strat tematic web",
  "userRole": "Nu se poate crea serviciul, deoarece utilizatorul nu are permisiunile necesare",
  "publishToNewLayer": "Publicați rezultatele în cadrul unui nou strat tematic de obiect spațial",
  "missingLayerNameMessage": "Trebuie să introduceți un nume valabil al stratului tematic înainte de a putea publica",
  "regionTypeLabel": "Tip de regiune",
  "centerPointLabel": "Punct central",
  "observationHeightLabel": "Înălțime de observare",
  "heightUnitLabel": "Unitate de înălțime",
  "minObservationDistanceLabel": "Distanță minimă de observare",
  "maxObservationDistance": "Distanță maximă de observare",
  "distanceUnitLabel": "Unitate de distanță",
  "fovstartAngleLabel": "Unghi de pornire câmp vizual",
  "fovEndAngleLabel": "Unghi de finalizare câmp vizual",
  "andleUnitsLabel": "Unitate de unghi"
});