define({
  "settings": "Configuració",
  "titleSettings": "Configuració de text",
  "imageSettings": "Configuració d'imatge",
  "backgroundColor": "Color de fons",
  "alignment": "Alineació",
  "textSize": "Mida de text",
  "textColor": "Color de text",
  "dataSource": "Origen de dades",
  "chartSettings": "Configuració de gràfic",
  "data": "Dades",
  "dataLabels": "Etiquetes de dades",
  "displayMode": "Mode de visualització",
  "featureOption": "Mostra els valors entitat per entitat",
  "categoryOption": "Mostra els valors per categoria",
  "countOption": "Mostra els recomptes d'entitats per categoria",
  "fieldOption": "Mostra els valors d'atributs com a gràfics",
  "categoryField": "Camp de categoria",
  "labelField": "Camp d'etiqueta",
  "valueFields": "Camps de valors",
  "operation": "Operació",
  "sumOption": "Suma",
  "averageOption": "Mitjana",
  "minOption": "Mínim",
  "maxOption": "Màxim",
  "countString": "Recompte",
  "dataFormat": "Format de dades",
  "decimalPlaces": "Posicions decimals",
  "prefix": "Prefix",
  "suffix": "Sufix",
  "dataType": "Tipus de dades",
  "featureCount": "Recompte d'entitats",
  "fieldStatistics": "Estadístiques de camp",
  "display": "Mostra",
  "chartColor": "Color de gràfic",
  "horizontalAxis": "Eix horitzontal",
  "verticalAxis": "Eix vertical",
  "legend": "Llegenda",
  "position": "Posició",
  "top": "Superior",
  "bottom": "Inferior",
  "useDataSourceSelection": "Utilitza la selecció",
  "dataSourceFilterByExtent": "Filtra per extensió",
  "changeTemplate": "Canvia la plantilla",
  "numberSettings": "Configuració de nombre",
  "gaugeSettings": "Configuració d'indicador",
  "indicators": "Indicadors",
  "ifValue": "Valor If",
  "and": "i",
  "numberOperatorIsLessThan": "és menys que",
  "numberOperatorIsGreaterThan": "és més gran que",
  "numberOperatorIsBetween": "està entre",
  "numberOperatorIsEqual": "és igual que",
  "numberOperatorIsNotEqual": "no és igual que",
  "then": "Aleshores",
  "ratio": "Relació",
  "trueValue": "Valor True",
  "changeValueColor": "canvia el color del valor a",
  "changeGaugeColor": "canvia el color de l'indicador a",
  "setIndicatorIcon": "defineix la icona d'indicador com a",
  "icons": "Icones",
  "style": "Estil",
  "placement": "Col·locació",
  "left": "Esquerra",
  "replace": "Substitueix",
  "right": "Dreta",
  "color": "Color",
  "categoryExists": "La categoria existeix.",
  "comboxHint": "Escriviu-ne o seleccioneu-ne una",
  "comboxDisableInputHint": "Seleccioneu-ne una",
  "sortBy": "Ordena per",
  "labelAxis": "Etiqueta",
  "valueAxis": "Valor",
  "minPeriod": "Període mínim",
  "automatic": "Automàtic",
  "periodsWithOutRecords": "Períodes sense registres",
  "nullValue": "Valor nul",
  "calculatedAsZero": "Calculat com a zero",
  "ignored": "Ignorat",
  "maxCategories": "Màxim de categories",
  "useLayerSymbology": "Utilitza la simbologia de la capa",
  "hollowsize": "Mida del buit",
  "splitField": "Camp de divisió",
  "parsingperiodTip": "No s'ha pogut fer el càlcul. Hi ha massa intervals de temps a causa d'un període d'anàlisi curt.",
  "manyCategoryTip": "No s'ha pogut mostrar el gràfic. Hi ha massa categories.",
  "setColor": "Defineix el color",
  "setTheColorOf": "A continuació, definiu el color de",
  "setTheColorAs": "A continuació, definiu el color com a",
  "ifStr": "Si",
  "as": "com a",
  "is": "és",
  "isNot": "no és",
  "barCluster": "clúster de barres",
  "individualBar": "barra individual",
  "allOthers": "Tota la resta",
  "category": "Categoria",
  "indicatorSum": "SUM",
  "indicatorAve": "AVE",
  "indicatorMax": "MAX",
  "indicatorMin": "MIN",
  "setCorrectyIndicatorTip": "Definiu els indicadors correctament.",
  "dataRange": "Interval de dades",
  "targetValue": "Valor de destinació",
  "currentValue": "Valor actual",
  "gaugeColor": "Color de l'indicador",
  "min": "Mínim",
  "max": "Màxim",
  "displayValueIn": "Mostra el valor en",
  "noData": "Sense dades",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Avís",
  "noSettingWaring1": "Feu clic en un element per definir-ne les propietats.",
  "noSettingWaring2": "Arrossegueu per ajustar la mida d'un element o reordenar-lo.",
  "donNotShowAgain": "No ho tornis a mostrar",
  "changeTemplateWarning": "S'esborrarà tota la configuració i s'obrirà una plantilla buida nova.",
  "requiredFieldWarning": "Aquest valor és obligatori:",
  "dataSourceNotSet": "Definiu l'origen de dades.",
  "addIndicatorTip": "Afegeix un indicador",
  "chooseTemplatePopupTitle": "Trieu una plantilla",
  "filterExtentTipWithaTag": "Podeu deshabilitar el filtre mitjançant l'<a target='_blank' href='http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'>origen de dades addicional</a> a la pestanya Atribut.",
  "filterExtentTip": "Podeu deshabilitar el filtre mitjançant l'origen de dades addicional a la pestanya Atribut.",
  "customColorByCategory": "Color personalitzat per categoria",
  "randomColor": "Color aleatori",
  "valueString": "Valor",
  "fieldString": "Camp",
  "includeThresholdValue": "Inclou el valor de llindar",
  "percentage": "Percentatge",
  "colorSchema": "Esquema de colors",
  "addCategory": "Afegeix una categoria",
  "clickToEdit": "Feu clic per editar",
  "nullText": "Nul",
  "others": "Altres",
  "dsErrorTipSuf": "no està disponible.",
  "front": "Part frontal",
  "back": "Part posterior",
  "title": "Títol",
  "titleColor": "Color del títol",
  "labelString": "Etiqueta",
  "labelSize": "Mida de l'etiqueta",
  "labelColor": "Color de l'etiqueta",
  "addMarkLine": "Afegeix una marca de línia",
  "addMarkArea": "Afegeix una marca d'àrea",
  "labelPosition": "Posició de l'etiqueta",
  "toString": "a",
  "start": "Principi",
  "middle": "Mig",
  "end": "Final",
  "inString": "Dins",
  "outString": "Fora",
  "lineColor": "Color de la línia",
  "lineWidth": "Amplada de la línia",
  "dashType": "Tipus de guió",
  "areaColor": "Color de l'àrea",
  "line": "Línia",
  "area": "Àrea",
  "stringsInTemplate": {
    "name_number": "Nombre",
    "name_gauge": "Indicador",
    "name_vertical_gauge": "Indicador vertical",
    "name_horizontal_gauge": "Indicador horitzontal",
    "name_pie": "Circular",
    "name_donut": "Anella",
    "name_bar": "Barra",
    "name_stacked_bar": "Barra apilada",
    "name_percentage_stacked_bar": "Barra apilada percentual",
    "name_column": "Columna",
    "name_stacked_column": "Columna apilada",
    "name_percentage_stacked_column": "Columna apilada percentual",
    "name_line": "Línia",
    "name_area": "Àrea",
    "name_stacked_area": "Àrea apilada",
    "name_percentage_stacked_area": "Àrea apilada percentual",
    "titleOfTheInfographic": "TÍTOL DE LA INFOGRAFIA",
    "description": "Descripció: informació addicional sobre aquesta infografia."
  },
  "marks": "Marques",
  "displayValue": "Mostra el valor",
  "statistic": "Estadística",
  "valueType": "Tipus de valor",
  "valueField": "Camp de valor",
  "fixed": "Fixa",
  "sdsTip": "Trieu una dada estadística configurada a Origen de dades addicional",
  "noSdsTip": "No hi ha cap dada estadística disponible.",
  "intScaleText": "Mostra només l'escala d'enters",
  "resetLayout": "Restableix el disseny",
  "fbeTip": "Tingueu en compte que, si la vostra aplicació es comparteix públicament i es fa viral, l'habilitació d'aquesta opció alentirà dràsticament el rendiment de l'aplicació. Es recomana encaridament utilitzar altres widgets, com ara Filtre i Filtre de grup, per aplicar el zoom a les entitats com a alternativa."
});