define({
  "searchTabTitle": "Keresési forrás beállítása",
  "routeTabTitle": "Útvonal beállítása",
  "add": "Keresési forrás hozzáadása",
  "addGeocoder": "Geokódoló hozzádása",
  "geocoder": "Geokódoló",
  "setLayerSource": "Rétegforrás beállítása",
  "setGeocoderURL": "Geokódoló URL-címének beállítása",
  "searchableLayer": "Vektoros réteg",
  "name": "Név",
  "countryCode": "Ország- vagy régiókód(ok)",
  "countryCodeEg": "pl. ",
  "countryCodeHint": "Ha üresen hagyja ezt az értéket, a keresés minden országra és régióra ki fog terjedni",
  "showInfoWindowOnSelect": "Felugró ablak megjelenítése a megtalált vektoros elemhez vagy helyhez",
  "showInfoWindowOnSelect2": "Felugró ablak megjelenítése a vektoros elem vagy a hely megtalálásakor.",
  "searchInCurrentMapExtent": "Csak az aktuális térképkiterjedésen belül keressen",
  "setSearchFields": "Keresőmezők beállítása",
  "set": "Beállítás",
  "fieldSearchable": "kereshető",
  "zoomScale": "Zoom-méretarány",
  "locatorUrl": "Geokódoló URL-címe",
  "locatorName": "Geokódoló neve",
  "locatorExample": "Példa",
  "locatorWarning": "A geokódoló szolgáltatás ezen verziója nem támogatott. A widget csak a 10.1-es és újabb verziójú geokódoló szolgáltatást támogatja.",
  "locatorTips": "Nem állnak rendelkezésre a javaslatok, mert a geokódoló szolgáltatás nem támogatja ezt a funkciót.",
  "layerSource": "Rétegforrás",
  "searchLayerTips": "Nem állnak rendelkezésre a javaslatok, mert a vektoros adatszolgáltatás nem támogatja az oldalszámozást.",
  "placeholderText": "Helyőrző szöveg",
  "searchFields": "Mezők keresése",
  "displayField": "Megjelenítési mező",
  "exactMatch": "Pontos találat",
  "maxSuggestions": "Javaslatok maximális száma",
  "maxResults": "Találatok maximális száma",
  "enableLocalSearch": "Helyi keresés engedélyezése",
  "minScale": "Min. méretarány",
  "minScaleHint": "Ha a térkép méretaránya nagyobb, mint ez a méretarány, akkor a helyi keresés lesz aktív",
  "radius": "Sugár",
  "radiusHint": "A térkép aktuális középpontja körül annak a területnek a sugarát határozza meg, amelyen belül megnő a geokódoló jelöltjeinek prioritása, hogy az adott helyhez legközelebb lévő jelöltek elsőbbséget élvezzenek",
  "invalidUrlTip": "A(z) ${URL} URL-cím érvénytelen vagy nem érhető el.",
  "routeUrl": "Útvonal URL-címe",
  "geocoderOptions": "Geokódoló beállításai",
  "autoComplete": "Automatikus kiegészítés",
  "maximumSuggestions": "Javaslatok maximális száma",
  "minCharacters": "Karakterek minimális száma",
  "searchDelay": "Keresési késleltetés",
  "placeholder": "Helyőrző",
  "routeOptions": "Útvonal-beállítások",
  "directionsLanguage": "Útvonalterv nyelve",
  "directionsLengthUnits": "Útvonalterv hosszmértékegysége",
  "directionsOutputType": "Útvonalterv kimenettípusa",
  "impedanceAttribute": "Impedancia attribútum",
  "kilometers": "kilométer",
  "miles": "mérföld",
  "meters": "méter",
  "feet": "láb",
  "yards": "yard",
  "nauticalMiles": "tengeri mérföld",
  "parametersTip": "Állítsa be megfelelően a paramétereket!",
  "complete": "Teljes",
  "completeNoEvents": "Teljes, események nélkül",
  "instructionsOnly": "Csak utasítások",
  "standard": "Normál",
  "summaryOnly": "Csak összefoglalás",
  "travelModesUrl": "Utazási módok URL-címe",
  "searchPlaceholder": "Cím vagy hely keresése",
  "trafficLayerUrl": "Forgalomréteg URL-címe",
  "barrierLayerUrl": "Határréteg URL-címe",
  "presetDestinations": "Előre beállított megállítások",
  "startPoint": "Kezdőpont",
  "endPoint": "Végpont",
  "destinationHolder": "Cím vagy koordináták",
  "optional": "Opcionális.",
  "barrierLayers": "Határrétegek",
  "pointBarrier": "Pontszerű akadályok",
  "lineBarrier": "Vonalas akadályok",
  "polygonBarrier": "Polygon akadályok",
  "noPointBarrier": "Pontszerű határok kiválasztása",
  "noLineBarrier": "Vonalas határok kiválasztása",
  "noPolygonBarrier": "Sokszög határok kiválasztása"
});