define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "通过单击地图来添加点",
  "addRingsDtWt": "添加环、行驶时间或步行时间。",
  "apply": "应用",
  "back": "返回",
  "colon": "：",
  "creditInformation": "配额信息",
  "driveTime": "行驶时间",
  "esriInfographics": "Esri 信息图表",
  "esriReports": "Esri 报表",
  "headerDescription_km": "千米",
  "headerDescription_miles": "英里",
  "headerDescription_minutes": "分",
  "infographics": "信息图表",
  "invalidValueRing": "值的取值范围是 0 到 1,000。",
  "invalidValueDTWT": "值的取值范围是 0 到 300。",
  "km": "千米",
  "miles": "英里",
  "minutes": "分钟",
  "myInfographics": "我的信息图表",
  "myReports": "我的报表",
  "noPermissions": "您的帐户无法运行 Business Analyst 微件。 要运行 Business Analyst 微件，贵组织的管理员需要授予您 GeoEnrichment 和 Network Analysis <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">权限</a>并分配<a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">配额</a>。",
  "radii": "半径",
  "radius": "半径",
  "radius_lowercase": "半径",
  "reports": "报表",
  "ring": "环",
  "rings": "环",
  "runInfographic": "运行信息图表",
  "runReport": "运行报表",
  "selectPointOrPolygon": "在地图上选择点或面要素、搜索地址或地点，或者在地图上放置图钉以查看相应地区的详细信息。",
  "selectReport": "选择报表",
  "selectTemplate": "选择模板",
  "sharedInfographics": "共享的信息图表",
  "sharedReports": "共享的报表",
  "thisEntryIsNotValid": "此条目无效。",
  "time": "时间",
  "walkTime": "步行时间",
  "widgetDescription": "访问汇总任何地区关键指标和数据的信息图表和报表。",
  "None": "选择..."
});