define({
  "feedbackStyleLabel": "거리 및 방향 피드백 스타일",
  "showTabLabel": "탭 보기",
  "feedbackShapeLabel": "피드백 모양",
  "lineColorLabel": "라인 색상",
  "lineWidthLabel": "라인 너비",
  "feedbackLabel": "피드백 레이블",
  "textColorLabel": "텍스트 색상",
  "textSizeLabel": "텍스트 크기",
  "tabErrorMessage": "위젯은 하나 이상의 탭이 표시되도록 구성되어야 함",
  "lineLabel": "선형",
  "circleLabel": "원",
  "ellipseLabel": "타원",
  "ringsLabel": "링",
  "transparency": "투명도",
  "ddFeedbackStyleTabLabel": "심볼",
  "miscellaneousTabLabel": "기타",
  "operationalLineLayerSelectLabel": "라인 및 링 결과에 대한 운영 폴리라인 레이어 선택",
  "operationalPolygonLayerSelectLabel": "원 및 타원 결과에 대한 운영 폴리곤 레이어 선택",
  "helpIconPolylineTooltip": "운영 레이어 목록은 폴리라인 지오메트리 유형인 현재 웹맵의 레이어로 채워집니다.",
  "helpIconPolygonTooltip": "운영 레이어 목록은 폴리곤 지오메트리 유형인 현재 웹맵의 레이어로 채워집니다."
});