define({
  "addLocation": "Helyszínegység hozzáadása",
  "addDistance": "Hosszmértékegység hozzáadása",
  "addArea": "Terület-mértékegység hozzáadása",
  "label": "Felirat",
  "abbr": "Rövidítés",
  "conversion": "Átváltás",
  "actions": "Műveletek",
  "areaUnits": "Terület mértékegységek",
  "distanceUnits": "Hosszmértékegység",
  "kilometers": "kilométer",
  "miles": "mérföld",
  "meters": "méter",
  "feet": "láb",
  "yards": "yard",
  "nauticalmiles": "tengeri mérföld",
  "squareKilometers": "négyzetkilométer",
  "squareMiles": "négyzetmérföld",
  "acres": "acre",
  "hectares": "hektár",
  "squareMeters": "négyzetméter",
  "squareFeet": "négyzetláb",
  "squareYards": "négyzetyard",
  "location": "Helyszínek",
  "distance": "Távolságok",
  "area": "Területek",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "mi",
  "metersAbbreviation": "m",
  "feetAbbreviation": "ft",
  "yardsAbbreviation": "yd",
  "nauticalmilesAbbreviation": "nm",
  "squareKilometersAbbreviation": "km2",
  "squareMilesAbbreviation": "mi2",
  "acresAbbreviation": "ac",
  "hectaresAbbreviation": "ha",
  "squareMetersAbbreviation": "m2",
  "squareFeetAbbreviation": "sq ft",
  "squareYardsAbbreviation": "yd2",
  "defineUnits": "Határozza meg a mértékegységeket.",
  "operationalLayer": "Adja hozzá a rajzot a térkép operatív rétegeként."
});