define({
  "transparencyLabel": "Transparansi",
  "outline": "Kerangka",
  "fill": "Isi (Warna hanya berlaku jika gaya diatur ke padat)",
  "style": "Gaya",
  "mandatoryLabel": "Jarak Evakuasi Wajib",
  "mandatoryButtonLabel": "Konfigurasikan Pengaturan Jarak Evakuasi Wajib",
  "safeLabel": "Jarak Evakuasi Aman",
  "safeButtonLabel": "Konfigurasikan Pengaturan Jarak Evakuasi Aman",
  "selectOpLayerLabel": "Pilih layer operasional untuk hasil",
  "selectDefaultMeasurementLabel": "Pilih satuan ukuran default",
  "helpIconTooltip": "Daftar layer operasional dikumpulkan dengan layer dari peta web saat ini yang berjenis geometri poligon.",
  "lineStyles": {
    "esriSLSDash": "Garis Datar",
    "esriSLSDashDot": "Garis Datar Titik",
    "esriSLSDashDotDot": "Garis Datar Titik Titik",
    "esriSLSDot": "Titik",
    "esriSLSLongDash": "Garis Datar Panjang",
    "esriSLSLongDashDot": "Garis Datar Panjang Titik",
    "esriSLSNull": "Nol",
    "esriSLSShortDash": "Garis Datar Pendek",
    "esriSLSShortDashDot": "Garis Datar Pendek Titik",
    "esriSLSShortDashDotDot": "Garis Datar Pendek Titik Titik",
    "esriSLSShortDot": "Titik Pendek",
    "esriSLSSolid": "Padat"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Belakang",
    "esriSFSCross": "Silang",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Depan",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nol",
    "esriSFSSolid": "Padat",
    "esriSFSVertical": "Vertikal"
  },
  "threatTypeLabel": "Jenis Ancaman",
  "symbologyLabel": "Simbologi",
  "generalLabel": "Umum",
  "addThreatTypesLabel": "Tambahkan Jenis Ancaman",
  "threatTypeColLabel": "Jenis ancaman",
  "actions": "Tindakan",
  "newThreatTypePopupLabel": "Jenis Ancaman Baru",
  "chooseDefaultThreatTypeIconLabel": "Pilih dari default",
  "mandatoryDistance": "Jarak Evakuasi Wajib",
  "safeDistance": "Jarak Evakuasi Aman",
  "units": "Unit",
  "chooseDefaultThreatLabel": "Pilih jenis ancaman default",
  "defaultThreatTypePopUpLabel": "Jenis Ancaman Default",
  "editThreatLabel": "Edit Ancaman",
  "defaultThreatTypeIconTooltip": "Daftar Jenis Ancaman Default",
  "uniqueThreatTypeMsg": "Masukkan jenis ancaman unik, jenis ancaman dengan nama ini sudah ada.",
  "requiredThreatTypeMsg": "Kolom ini wajib diisi",
  "unitMeasureLabel": "Jarak dalam {0}",
  "pipeBombLabel": "Bom Pipa",
  "suicideBombLabel": "Bom Bunuh Diri",
  "briefcaseLabel": "Tas kerja",
  "carLabel": "Mobil",
  "suvVanLabel": "SUV/VAN",
  "smallDeliveryTruckLabel": "Truk Pengiriman Kecil",
  "containerWaterTruckLabel": "Truk Kontainer/Truk Air",
  "semiTrailerLabel": "Truk Semi-Trailer"
});