define({
  "serviceUrl": "サービス URL の設定:",
  "minIntSpacingLabel": "最小間隔",
  "lineOpacityLabel": "ラインの不透明度",
  "labelOpacityLabel": "ラベルの不透明度",
  "centerLabelOpacityLabel": "中央ラベルの不透明度",
  "gridZonePlacementLabel": "グリッド ゾーン ラベルの配置",
  "verticalLineLabels": "縦軸のラベル",
  "styleHeaderLabel": "スタイル",
  "indexHeaderLabel": "インデックス",
  "colorHeaderLabel": "色",
  "fontSizeHeaderLabel": "フォント サイズ",
  "lineWidthHeaderLabel": "ライン幅",
  "horizontalLabel": "水平方向",
  "verticalLabel": "垂直方向",
  "upperLeftLabel": "左上",
  "upperRightLabel": "右上",
  "lowerLeftLabel": "左下",
  "lowerRightLabel": "右下",
  "centerLabel": "中央",
  "errorMessage": "構成ページにエラーが含まれています。修正してから保存してください。",
  "checkBoxLabel": "ウィジェットを閉じたときにグリッドを表示します"
});