define({
  "tabs_section_Label": "Schede",
  "addTab": "Aggiungi scheda",
  "layerName": "Layer",
  "layerType": "Tipo di analisi",
  "layerLabel": "Etichetta",
  "actions": "Azioni",
  "closest": "Feature più vicina",
  "proximity": "Prossimità",
  "summary": "Riepilogo",
  "select_lbl": "-- Seleziona --",
  "general_setting_Label": "Impostazioni generali",
  "units_text_lbl": "Unità di distanza",
  "maximum_distance_lbl": "Distanza massima della feature più vicina",
  "buffer_text_lbl": "Etichetta del buffer",
  "buffer_lbl": "Distanza di buffer",
  "buffer_max_lbl": "Distanza massima del buffer",
  "buffer_min_lbl": "Distanza minima del buffer",
  "buffer_default_lbl": "Distanza predefinita del buffer",
  "not_less_than_max": "La distanza deve essere inferiore alla distanza massima del buffer",
  "not_between": "La distanza deve essere compresa tra la distanza minima del buffer e quella massima",
  "not_more_than_min": "La distanza deve essere superiore alla distanza minima del buffer",
  "not_valid_number": "Deve essere un numero valido",
  "invalid_value": "Il valore ${type} non è valido",
  "routing_checkBox": "Abilita itinerario",
  "weather_removed_message": "Le opzioni meteo non sono più disponibili per questo widget.",
  "currentlySelectedLayer": "Seleziona da layer mappa",
  "missingTabLabel": "Manca l'etichetta ad almeno una scheda",
  "missingLayerInWebMap": "Nessun layer operativo trovato.",
  "selectFields": "Seleziona campi",
  "addField": "Aggiungi campo",
  "sum": "Somma",
  "min": "Minimo",
  "max": "Massimo",
  "avg": "Media",
  "count": "COUNT",
  "area": "AREA",
  "length": "LENGTH",
  "count_checkBox": "Visualizza conteggio feature",
  "area_checkBox": "Visualizza somma dell'area",
  "length_checkBox": "Visualizza somma della lunghezza",
  "max_records": "Raggiunto limite massimo",
  "save_label": "Salva opzioni",
  "save_checkbox": "Abilita salvataggio",
  "report_label": "Opzioni di report",
  "report_checkbox": "Abilita report",
  "csv_label": "Opzioni CSV",
  "display_label": "Opzioni di visualizzazione",
  "display_checkbox": "Visualizza feature di riepilogo",
  "setSelectionColor": "Imposta colore di selezione",
  "snapshot_label": "Opzioni snapshot",
  "snapshot_checkbox": "Abilita snapshot",
  "must_select_template": "Selezionare uno dei modelli di modifica nelle opzioni di salvataggio.",
  "count_label": "Etichetta conteggio",
  "area_label": "Etichetta area",
  "length_label": "Etichetta lunghezza",
  "invalid_string_width": "Il valore è troppo lungo. ",
  "layer_type_not_supported": "Tipo di layer non supportato",
  "groupedSummary": "Conteggi raggruppati",
  "groupByField": "Raggruppa per campo",
  "labelType": "Aggiungi etichetta",
  "prefix": "Come prefisso",
  "suffix": "Come suffisso",
  "need_group_field": "Utilizzare l'azione di modifica per definire un Gruppo per campo.",
  "fieldTitle": "Campo",
  "typeTitle": "Tipo",
  "actionsTitle": "Azioni",
  "save_point_checkbox": "Salva punti",
  "save_line_checkbox": "Salva linee",
  "save_poly_checkbox": "Salva poligoni",
  "no_valid_popup_fields": "Nessun campo valido nel popup. Utilizzare l'azione di modifica per definire un campo.",
  "no_valid_fields": "Nessun campo valido. Utilizzare l'azione di modifica per definire opzioni di visualizzazione.",
  "incident_label": "Etichetta scheda",
  "locate_incident_label": "Etichetta Area di interesse",
  "incident": "Richiesta di assistenza",
  "locate_incident": "Individua incidente",
  "buffer_value": "Distanza di buffer",
  "tab_options": "Analisi",
  "export_options": "Output",
  "instruction_save": "Salva la posizione in un feature service.",
  "instruction_snapshot": "Crea una mappa Web in basa alla posizione.",
  "instruction_report": "Crea e stampa un report della posizione.",
  "instruction_all_fields": "Esportare campi con il download CSV.",
  "data_label": "Impostazioni output dati",
  "layer_error": "Layer mancante o non valido.",
  "visibility_checkBox": "Disabilita gestione visibilità layer",
  "allFieldsLabel": "Tutti i campi",
  "configuredPopUpFieldsLabel": "Campi pop-up configurati",
  "analysisTypeFieldsLabel": "Campi del tipo di analisi",
  "reportOptionsMsg": "È necessario selezionare almeno un'opzione di report",
  "analysisSummaryLabelForReport": "Riepilogo del tipo di analisi",
  "popUpSummaryLabelForReport": "Riepilogo dei campi pop-up configurati",
  "downloadTab": {
    "reportLegend": "Impostazioni report",
    "textColorLabel": "Seleziona colore per l’intestazione di colonna",
    "setButtonLabel": "Imposta",
    "printGPServiceLabel": "URL servizio di stampa",
    "logoLabel": "Logo",
    "logoChooserHint": "Fare clic sull'icona dell'immagine per modificare l'immagine",
    "footnoteLabel": "Nota a piè di pagina"
  },
  "roundValue": "Arrotonda a",
  "roundValueTitle": "Arrotonda i valori del campo",
  "truncateValue": "Tronca a",
  "truncateValueTitle": "Tronca i valori del campo",
  "significantFigures": "cifre significative",
  "fieldOptions": "Opzioni campo",
  "modifyValues": "Modifica i valori del campo",
  "validatePlaces": "Deve essere un numero intero",
  "onlyDouble": "Opzioni campo aggiuntive supportate solo per i campi numerici.",
  "layerNotAvalible": "Layer non trovato",
  "missingLayer": "Nome: ${name}",
  "missingLayerHint": "Uno o più layer interessati da questa configurazione sono attualmente non disponibili.",
  "drawGeodesic": "Disegna forme geodetiche"
});