define({
  "addTaskTip": "Fügen Sie dem Widget mindestens einen Filter hinzu, und konfigurieren Sie Parameter für jeden von ihnen.",
  "enableMapFilter": "Voreingestellten Layer-Filter aus der Karte entfernen",
  "newFilter": "Neuer Filter",
  "filterExpression": "Filterausdruck",
  "layerDefaultSymbolTip": "Standardsymbol des Layers verwenden",
  "uploadImage": "Ein Bild hochladen",
  "selectLayerTip": "Wählen Sie einen Layer aus.",
  "setTitleTip": "Legen Sie einen Titel fest.",
  "noTasksTip": "Keine Filter konfiguriert. Klicken Sie auf \"${newFilter}\", um einen neuen Filter hinzuzufügen.",
  "collapseFiltersTip": "Filterausdrücke (falls vorhanden) ausblenden, wenn das Widget geöffnet wird",
  "zoomtoTip": "Nach Anwendung des Filters auf die verbleibenden Features zoomen",
  "groupByLayerTip": "Filter nach Layer gruppieren",
  "autoApplyWhenValueInput": "Diesen Filter automatisch nach der Eingabe eines Wertes anwenden",
  "autoApplyWhenWidgetOpen": "Diesen Filter bei geöffnetem Widget anwenden",
  "info": "Info",
  "expressions": "Ausdrücke",
  "allowCustom": "Erstellung benutzerdefinierter Filter zulassen",
  "filterActions": "Benutzerdefinierte Filteraktionen",
  "custom": "Benutzerdefinierte Filter aktivieren",
  "resetAll": "\"Alle zurücksetzen\" aktivieren",
  "turnOffAll": "\"Alle deaktivieren\" aktivieren",
  "matchMsgSetAll": "Features anzeigen, die allen Filtern entsprechen",
  "matchMsgSetAny": "Features anzeigen, die beliebigen Filtern entsprechen"
});