define({
  "taskUrl": "Uzdevuma URL",
  "setTask": "Iestatīt",
  "setTaskPopupTitle": "Iestatīt uzdevumu",
  "validate": "Iestatīt",
  "inValidGPService": "Ievadiet derīgu ģeodatu apstrādes servisu.",
  "GPFeatureRecordSetLayerERR": "Ievadiet ģeodatu apstrādes servisu tikai ar ievadņu veidu “GPFeatureRecordSetLayer”.",
  "invalidInputParameters": "Ievades parametru skaits ir mazāks par 1 vai lielāks par 3. Lūdzu, atveriet derīgu ģeodatu apstrādes servisu.",
  "projectSetting": {
    "title": "Projekta iestatījumi",
    "note": "Piezīme. Projekta iestatījumi nav obligāti, jo lietotājs var saglabāt projektu vēlamajos tīmekļa kartes slāņos ar tīkla zuduma teritoriju un ievades parametriem. Lietotājs var saglabāt citus izvades parametrus no grupas “Izvade” cilnē “Ievade/izvade”.",
    "projectPolygonLayer": "Projekta laukumu slānis",
    "outputParameterName": "Izvades parametra nosaukums",
    "projectPointLayer": "Projekta punktu slānis",
    "selectLabel": "Atlasīt",
    "polygonLayerHelp": "<p>Tiks parādīts laukuma slānis ar šādiem nosacījumiem:<br/><li>Slānī jābūt rediģēšanas iespējām, piemēram, “Izveidot”, “Dzēst” un “Atjaunināt”</li><li>Slānī jābūt diviem laukiem ar precīzu nosaukumu un datu tipu:</li><ul><li>nosaukums (virknes tipa lauks)</li><li>GlobalID (GlobalID tipa lauks)</li></ul><p/>",
    "outputParameterHelp": "<p>Tiks parādīti izvades laukuma slāņi no uzdevuma vietrāža (URL)<p/>",
    "pointLayerHelp": "<p>Tiks parādīts punktu slānis ar šādiem nosacījumiem:<br/><li>Slānī jābūt rediģēšanas iespējām, piemēram, “Izveidot”, “Dzēst” un “Atjaunināt”</li><li>Slānī jābūt diviem laukiem ar precīzu nosaukumu un datu tipu:</li><ul><li>inputtype (virknes tipa lauks)</li><li>projectid (GUID tipa lauks)</li></ul><p/>"
  },
  "inputOutputTab": {
    "title": "Ievade/izvade",
    "inputSettingsLabel": "Ievades iestatījumi",
    "outputSettingsLabel": "Izvades iestatījumi",
    "inputLabel": "Kartes teksts",
    "inputTooltip": "Rīka padoms",
    "symbol": "Simbols",
    "typeText": "Veids",
    "outputParametersText": "Izvades parametri",
    "saveToLayerText": "Saglabāt slānī (pēc izvēles)",
    "skipText": "Izlaižams",
    "visibilityText": "Redzams",
    "exportToCsvText": "Eksportēt uz CSV",
    "exportToCsvDisplayText": "CSV",
    "settitngstext": "Iestatījumi",
    "addFieldTitle": "Pievienot lauku",
    "enterDisplayText": "Ievadīt parādāmo tekstu",
    "setScale": "Iestatīt mērogu",
    "outputDisplay": "Parādīt tekstu",
    "saveToLayerHelp": "<p>Tiks parādīts slānis ar šādiem nosacījumiem<br/><li>Slānī jābūt rediģēšanas iespējām, piemēram, “Izveidot”, “Dzēst” un “Atjaunināt”</li><li>Slānī jābūt diviem laukiem ar nosaukumu un datu tipu:</li><ul><li>parametername (virknes tipa lauks)</li><li>projectid (Guid tipa lauks)</li></ul><p/>"
  },
  "summaryTab": {
    "title": "Kopsavilkums",
    "summaryFieldsetText": "Kopsavilkuma iestatījumi",
    "inputOutput": "Ievades/izvades",
    "field": "Lauki",
    "operator": "Operatori",
    "inputOperatorCountOption": "Skaits",
    "outputOperatorCountOption": "Skaits",
    "outputOperatorSkipCountOption": "Izlaist skaitu",
    "fieldOperatorSumOption": "Summa",
    "fieldOperatorMinOption": "Min.",
    "fieldOperatorMaxOption": "Maks.",
    "fieldOperatorMeanOption": "Vidējais",
    "expressionAddButtonText": "Pievienot",
    "expressionVerifyButtonText": "Verificēt",
    "summaryEditorText": "Kopsavilkuma teksts"
  },
  "generalSettings": {
    "title": "Vispārīgie iestatījumi",
    "displayTextForButtonLegend": "Pogas “Palaist” parādāmais teksts",
    "displayTextforButtonDefaultValue": "Palaist",
    "displayTextForButton": "Parādīt tekstu",
    "autoZoomAfterTrace": "Tālummaiņas opcijas",
    "zoomText": "Automātiska tālummaiņa pēc trasēšanas"
  },
  "validationErrorMessage": {
    "webMapError": "Tīmekļa karte nav neviena pieejama slāņa. Lūdzu, izvēlieties derīgu tīmekļa karti.",
    "inputTypeFlagGreaterThanError": "Nevar būt vairāk par vienu veida karogs (sākuma punkts) ievadi.",
    "inputTypeFlagLessThanError": "Ir nepieciešama vismaz viena veida karogs (sākuma punkts) ievade.",
    "inputTypeBarrierErr": "Nevar būt vairāk par vienu veida barjera ievadi.",
    "inputTypeSkipErr": "Nevar būt vairāk par vienu veida izlaišana ievadi.",
    "displayTextForButtonError": "Pogas “Palaist” parādāmais teksts nevar būt tukšs.",
    "UnableToLoadGeoprocessError": "Nevar ielādēt ģeodatu apstrādes servisu.",
    "invalidSummaryExpression": "Nederīga izteiksme.",
    "validSummaryExpression": "Izdevās!",
    "invalidProjectSettings": "Nederīgi projekta iestatījumi.<br/> Lūdzu, izvēlieties derīgu vērtību sadaļā “${projectSetting}”."
  },
  "hintText": {
    "labelTextHint": "Padoms. Nodrošiniet kartes attēlojuma tekstu izvades parametru rezultātu panelim.",
    "displayTextHint": "Padoms. Tas tiks parādīts šī izvades parametra datu panelī.",
    "inputTextHint": "Padoms. Izveidojiet savu izteiksmi, izvēloties ievades, izvades un lauka nosaukumus.",
    "expressionHint": "Padoms. Izvēlieties vienumus un noklikšķiniet uz Pievienot, lai izveidotu izteiksmi."
  }
});