define({
  "searchTabTitle": "Paramètre de source de recherche",
  "routeTabTitle": "Paramètre d’itinéraire",
  "add": "Ajouter une source de recherche",
  "addGeocoder": "Ajouter un géocodeur",
  "geocoder": "Géocodeur",
  "setLayerSource": "Définir une source de couche",
  "setGeocoderURL": "Définir l'URL du géocodeur",
  "searchableLayer": "Couche d'entités",
  "name": "Nom",
  "countryCode": "Codes de pays ou de régions",
  "countryCodeEg": "par ex. ",
  "countryCodeHint": "Si cette valeur n'est pas renseignée, la recherche s'effectue dans tous les pays et toutes les régions",
  "showInfoWindowOnSelect": "Afficher la fenêtre contextuelle de l'entité ou de l'emplacement trouvé",
  "showInfoWindowOnSelect2": "Afficher la fenêtre contextuelle lorsque l’entité ou l’emplacement est trouvé.",
  "searchInCurrentMapExtent": "Rechercher uniquement dans l'étendue de la carte actuelle",
  "setSearchFields": "Définir les champs de recherche",
  "set": "Définir",
  "fieldSearchable": "Peut faire l'objet d’une recherche",
  "zoomScale": "Echelle de zoom",
  "locatorUrl": "URL du géocodeur",
  "locatorName": "Nom du géocodeur",
  "locatorExample": "Exemple",
  "locatorWarning": "Cette version du service de géocodage n'est pas prise en charge. Le widget prend en charge le service de géocodage 10.1 et version supérieure.",
  "locatorTips": "Les suggestions ne sont pas disponibles, car le service de géocodage ne prend pas en charge la fonction de suggestion.",
  "layerSource": "Source de la couche",
  "searchLayerTips": "Les suggestions ne sont pas disponibles, car le service d'entités ne prend pas en charge la fonction de pagination.",
  "placeholderText": "Texte de l'espace réservé",
  "searchFields": "Champs de recherche",
  "displayField": "Champ d’affichage",
  "exactMatch": "Correspondance parfaite",
  "maxSuggestions": "Nombre maximal de suggestions",
  "maxResults": "Nombre maximal de résultats",
  "enableLocalSearch": "Activer la recherche locale",
  "minScale": "Echelle min.",
  "minScaleHint": "Lorsque l'échelle de la carte est supérieure à cette échelle, la recherche locale est appliquée",
  "radius": "Rayon",
  "radiusHint": "Indique le rayon d'une surface autour du centre de la carte qui permet d'optimiser le classement des candidats de géocodage, afin que les plus proches de l'emplacement soient renvoyés en premier",
  "invalidUrlTip": "L’URL ${URL} est incorrecte ou inaccessible.",
  "routeUrl": "URL de l’itinéraire",
  "geocoderOptions": "Options du géocodeur",
  "autoComplete": "Terminer automatiquement",
  "maximumSuggestions": "Nombre maximal de suggestions",
  "minCharacters": "Nombre minimum de caractères",
  "searchDelay": "Délai de recherche",
  "placeholder": "Espace réservé",
  "routeOptions": "Options de l’itinéraire",
  "directionsLanguage": "Langue de la feuille de route",
  "directionsLengthUnits": "Unités de distance de la feuille de route",
  "directionsOutputType": "Type de sortie de la feuille de route",
  "impedanceAttribute": "Attribut d’impédance",
  "kilometers": "Kilomètres",
  "miles": "Miles",
  "meters": "Mètres",
  "feet": "Pieds",
  "yards": "Yards",
  "nauticalMiles": "Milles marins",
  "parametersTip": "Définissez les paramètres correctement.",
  "complete": "Complet",
  "completeNoEvents": "Complet sans événements",
  "instructionsOnly": "Instructions uniquement",
  "standard": "Standard",
  "summaryOnly": "Résumé uniquement",
  "travelModesUrl": "URL des modes de déplacement",
  "searchPlaceholder": "Rechercher une adresse ou un lieu",
  "trafficLayerUrl": "URL de la couche de trafic",
  "barrierLayerUrl": "URL de la couche d’interruption",
  "presetDestinations": "Arrêts prédéfinis",
  "startPoint": "Point de départ",
  "endPoint": "Point d'arrivée",
  "destinationHolder": "Adresse ou coordonnées",
  "optional": "Facultatif."
});