define(
   ({
    addLayer: "Pievienot slāni",
    layerName: "Slānis",
    layerRefresh: "Atjaunot",
    layerLabel: "Etiķete",
    actions: "Darbības",
    popupOk: "Labi",
    popupCancel: "Atcelt",
    mainPanelTextPlaceholder: "piem.: AUTOMAĢISTRĀLES APSTĀKĻI",
    invalidInterval: "Tiek atbalstītas tikai ciparu rakstzīmes.",
    uploadImage: "Augšupielādēt attēlu",
    iconColumnText: "Ikona",
    refreshInterval: "1 \"Novērtēts kā laiks minūtēs\"",
    refreshIntervalTitle: "Novērtēts kā laiks minūtēs",
    mainPanelText: "Galvenā paneļa teksts",
    mainPanelIcon: "Galvenā paneļa attēls",
    refreshIntervalInstruction: "Atjaunošanas intervāls",
    optionsText: "Varianti",
    symbolOptionsText: "Simbolu varianti",
    iconOptionsText: "Ikonu varianti",
    sympolPopupTitle: "Iestatīt simbolu",
    rdoLayer: "Slāņa simbols",
    rdoCustom: "Pielāgots simbols",
    chkCluster: "Aktivizēt klasterus",
    defineClusterSymbol: "Klastera simbols",
    defineThemeClusterSymbol: "Klastera simbols no tēmas",
    rdoEsri: "Esri simbols",
    rdoLayerIcon: "Izmantot simbolu kā ikonu",
    rdoCustomIcon: "Augšupielādēt pielāgotu ikonu",
    editCustomSymbol: "Rediģēt pielāgotu simbolu",
    editCustomIcon: "Rediģēt pielāgotu ikonu",
    missingRefreshValue: "Norādiet atjaunošanas intervāla vērtību.",
    panelIconOption: "Rādīt paneļa galveni",
    enableRefresh: "Aktivizēt slāņu atjaunošanu",
    disableRefresh: "Slāņu atjaunošana tiek atbalstīta tikai elementu kolekcijām",
    layer_type_not_supported: "Slāņa tips netiek atbalstīts: "
  })
);
