define({
  "searchTabTitle": "Postavka izvora pretraživanja",
  "routeTabTitle": "Postavka rute",
  "add": "Dodaj izvor pretraživanja",
  "addGeocoder": "Dodaj geokoder",
  "geocoder": "Geokoder",
  "setLayerSource": "Postavi izvor sloja",
  "setGeocoderURL": "Postavi URL geokodera",
  "searchableLayer": "Sloj geoobjekta",
  "name": "Naziv",
  "countryCode": "Pozivni broj za državu ili regiju",
  "countryCodeEg": "npr. ",
  "countryCodeHint": "Ako ostavite ovu vrijednost praznom, pretražit će se sve države i regije",
  "showInfoWindowOnSelect": "Prikaži skočni prozor za pronađeni geoobjekt ili lokaciju",
  "showInfoWindowOnSelect2": "Prikazivanje skočnog prozora kada se pronađe geoobjekt ili lokacija.",
  "searchInCurrentMapExtent": "Pretraži samo trenutačni obuhvat karte",
  "setSearchFields": "Postavi polja za pretraživanje",
  "set": "Postavi",
  "fieldSearchable": "pretraživo",
  "zoomScale": "Mjerilo uvećanja",
  "locatorUrl": "URL geokodera",
  "locatorName": "Naziv geokodera",
  "locatorExample": "Primjer",
  "locatorWarning": "Ova verzija usluge geokodiranja nije podržana. Widget podržava uslugu geokodiranja 10.1 i novije.",
  "locatorTips": "Prijedlozi nisu dostupni jer usluga geokodiranja ne podržava mogućnost predlaganja.",
  "layerSource": "Izvor sloja",
  "searchLayerTips": "Prijedlozi nisu dostupni jer usluga geoobjekata ne podržava mogućnost numeriranja stranica.",
  "placeholderText": "Mjesto za unos teksta",
  "searchFields": "Polja za pretraživanje",
  "displayField": "Polje za prikaz",
  "exactMatch": "Točno podudaranje",
  "maxSuggestions": "Maksimalni broj prijedloga",
  "maxResults": "Maksimalni rezultati",
  "enableLocalSearch": "Omogući lokalno pretraživanje",
  "minScale": "Min. mjerilo",
  "minScaleHint": "Kad je mjerilo karte veće od ovog mjerila, primijenit će se lokalno pretraživanje",
  "radius": "Polumjer",
  "radiusHint": "Određuje polumjer područja oko trenutačnog središta karte koje se upotrebljava za povećanje broja kandidata za geokodiranje kako bi se prvi prikazali kandidati koji su najbliži lokaciji",
  "invalidUrlTip": "URL ${URL} nije valjan ili dostupan.",
  "routeUrl": "URL rute",
  "geocoderOptions": "Opcije geokodera",
  "autoComplete": "Automatsko završavanje",
  "maximumSuggestions": "Maksimalni prijedlozi",
  "minCharacters": "Minimum znakova",
  "searchDelay": "Odgoda pri pretraživanju",
  "placeholder": "Mjesto za unos",
  "routeOptions": "Opcije rute",
  "directionsLanguage": "Jezik uputa za vožnju",
  "directionsLengthUnits": "Jedinice duljine uputa za vožnju",
  "directionsOutputType": "Vrsta izvoza uputa za vožnju",
  "impedanceAttribute": "Atribut impedancije",
  "kilometers": "Kilometri",
  "miles": "Milje",
  "meters": "Metri",
  "feet": "Stope",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "parametersTip": "Ispravno postavite parametre!",
  "complete": "Završeno",
  "completeNoEvents": "Završeno bez događaja",
  "instructionsOnly": "Samo upute",
  "standard": "Standardno",
  "summaryOnly": "Samo sažetak",
  "travelModesUrl": "URL načina putovanja",
  "searchPlaceholder": "Pronađi adresu ili mjesto",
  "trafficLayerUrl": "URL sloja prometa",
  "barrierLayerUrl": "URL sloja barijere",
  "presetDestinations": "Unaprijed postavljena zaustavljanja",
  "startPoint": "Početna točka",
  "endPoint": "Završna točka",
  "destinationHolder": "Adresa ili koordinate",
  "optional": "Neobavezno.",
  "barrierLayers": "Slojevi ograničenja",
  "pointBarrier": "Točkasta ograničenja",
  "lineBarrier": "Linijska ograničenja",
  "polygonBarrier": "Poligonska ograničenja",
  "noPointBarrier": "Odaberite točkasta ograničenja",
  "noLineBarrier": "Odaberite linijska ograničenja",
  "noPolygonBarrier": "Odaberite poligonska ograničenja"
});