define({
  "feedbackStyleLabel": "Vahemaa ja suuna tagasiside laad",
  "showTabLabel": "Kuva vahekaart",
  "feedbackShapeLabel": "Tagasiside kuju",
  "lineColorLabel": "Joone värv",
  "lineWidthLabel": "Joone laius",
  "feedbackLabel": "Tagasiside silt",
  "textColorLabel": "Teksti värv",
  "textSizeLabel": "Teksti suurus",
  "tabErrorMessage": "Vidin tuleb konfigureerida nii, et vähemalt üks vahekaart oleks kuvatud",
  "lineLabel": "Joon",
  "circleLabel": "Ring",
  "ellipseLabel": "Ellips",
  "ringsLabel": "Ringid",
  "transparency": "Läbipaistvus",
  "ddFeedbackStyleTabLabel": "Sümboloogia",
  "miscellaneousTabLabel": "Varia",
  "operationalLineLayerSelectLabel": "Valige murdjoone töökiht joonte ja ringide tulemuste jaoks",
  "operationalPolygonLayerSelectLabel": "Valige murdjoone töökiht ringide ja ellipsite tulemuste jaoks",
  "helpIconPolylineTooltip": "Töökihtide nimekiri sisaldab kihte praeguselt veebikaardilt, mis on murdjoone geomeetria tüüpi.",
  "helpIconPolygonTooltip": "Töökihtide nimekiri sisaldab kihte praeguselt veebikaardilt, mis on polügooni geomeetria tüüpi."
});