define({
  "searchTabTitle": "Ieškoti šaltinio parametro",
  "routeTabTitle": "Maršruto parametras",
  "add": "Pridėti paieškos šaltinį",
  "addGeocoder": "Pridėti geokoderį",
  "geocoder": "Geokoderis",
  "setLayerSource": "Nustatyti sluoksnio šaltinį",
  "setGeocoderURL": "Nustatyti geokoderio URL",
  "searchableLayer": "Elementų sluoksnis",
  "name": "Pavadinimas",
  "countryCode": "Šalies arba regiono kodas (-ai)",
  "countryCodeEg": "pvz., ",
  "countryCodeHint": "Jei ši reikšmė nebus nurodyta, bus ieškomos visos šalys ir regionai",
  "showInfoWindowOnSelect": "Rodyti iškylantį langą, skirtą rastam elementui arba vietai",
  "showInfoWindowOnSelect2": "Rodyti iškylantį langą, kai randamas elementas arba vieta.",
  "searchInCurrentMapExtent": "Ieškoti tik esamo žemėlapio aprėptyje",
  "setSearchFields": "Nustatyti paieškos laukus",
  "set": "Taikyti",
  "fieldSearchable": "ieškotina",
  "zoomScale": "Mastelis",
  "locatorUrl": "Geokoderio URL",
  "locatorName": "Geokoderio pavadinimas",
  "locatorExample": "Pavyzdys",
  "locatorWarning": "Ši geokodavimo paslaugos versija nepalaikoma. Valdiklis palaiko 10.1 arba vėlesnę geokodavimo paslaugą.",
  "locatorTips": "Pasiūlymų nėra, nes geokodavimo paslauga nepalaiko siūlomų galimybių.",
  "layerSource": "Sluoksnio šaltinis",
  "searchLayerTips": "Pasiūlymų nėra, nes elementų paslauga nepalaiko puslapių numeravimo galimybės.",
  "placeholderText": "Naudotojui rodomas tekstas",
  "searchFields": "Paieškos laukai",
  "displayField": "Rodyti lauką",
  "exactMatch": "Tikslus atitikmuo",
  "maxSuggestions": "Maksimalūs pasiūlymai",
  "maxResults": "Maksimalus rezultatų skaičius",
  "enableLocalSearch": "Įgalinti vietinę paiešką",
  "minScale": "Minimalus mastelis",
  "minScaleHint": "Vietinė paieška bus taikoma, kai žemėlapio mastelis bus didesnis nei šis",
  "radius": "Spindulys",
  "radiusHint": "Nurodo ploto spindulį aplink dabartinį žemėlapio centrą, naudojamą geokodavimo objektams išdėstyti taip, kad arčiausiai vietos esantys objektai būtų pateikiami pirmiausia.",
  "invalidUrlTip": "URL ${URL} yra neteisingas arba nepasiekiamas.",
  "routeUrl": "Maršruto URL",
  "geocoderOptions": "Geokodavimo parinktys",
  "autoComplete": "Automatiškai užbaigti",
  "maximumSuggestions": "Maksimalūs patarimai",
  "minCharacters": "Minimalus simbolių skaičius",
  "searchDelay": "Paieškos delsa",
  "placeholder": "Vietos žymė",
  "routeOptions": "Maršruto parinktys",
  "directionsLanguage": "Krypčių kalba",
  "directionsLengthUnits": "Krypčių ilgio vienetai",
  "directionsOutputType": "Krypčių išvesties tipas",
  "impedanceAttribute": "Varžos atributas",
  "kilometers": "Kilometrai",
  "miles": "Mylios",
  "meters": "Metrai",
  "feet": "Pėdos",
  "yards": "Jardai",
  "nauticalMiles": "Jūrmylės",
  "parametersTip": "Nustatykite parametrus tinkamai!",
  "complete": "Pilnas",
  "completeNoEvents": "Pilnas be instrukcijų",
  "instructionsOnly": "Tik instrukcijos",
  "standard": "Standartinis",
  "summaryOnly": "Tik suvestinė",
  "travelModesUrl": "Kelionės režimų URL",
  "searchPlaceholder": "Surasti adresą arba vietą",
  "trafficLayerUrl": "Eismo sluoksnio URL",
  "barrierLayerUrl": "Kliūčių sluoksnio URL",
  "presetDestinations": "Nustatyti stoteles iš naujo",
  "startPoint": "Pradžios taškas",
  "endPoint": "Pabaigos taškas",
  "destinationHolder": "Adresas arba koordinatės",
  "optional": "Neprivaloma.",
  "barrierLayers": "Kliūčių sluoksniai",
  "pointBarrier": "Taškinės kliūtys",
  "lineBarrier": "Linijinės kliūtys",
  "polygonBarrier": "Plotinės kliūtys",
  "noPointBarrier": "Pasirinkti taškines kliūtis",
  "noLineBarrier": "Pasirinkti linijines kliūtis",
  "noPolygonBarrier": "Pasirinkti plotines kliūtis"
});