define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Dodajte točke klikanjem na kartu",
  "addRingsDtWt": "Dodajte prstene, vrijeme vožnje ili hodanja.",
  "apply": "Primijeni",
  "back": "Natrag",
  "colon": ":",
  "creditInformation": "Informacije o kreditima",
  "driveTime": "Vrijeme vožnje",
  "esriInfographics": "Esri infografika",
  "esriReports": "Esri izvješća",
  "headerDescription_km": "kilometar",
  "headerDescription_miles": "milja",
  "headerDescription_minutes": "minuta",
  "infographics": "Grafički prikaz",
  "invalidValueRing": "Vrijednosti moraju biti u rasponu od 0 do 1000.",
  "invalidValueDTWT": "Vrijednosti moraju biti u rasponu od 0 do 300.",
  "km": "km",
  "miles": "milja",
  "minutes": "minuta",
  "myInfographics": "Moja infografika",
  "myReports": "Moja izvješća",
  "noPermissions": "Widget Business Analyst ne može se pokrenuti na vašem računu.  Da biste pokrenuli widget Business Analyst, administrator vaše organizacije mora vam dodijeliti <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">ovlasti</a> za GeoEnrichment and Network Analysis i <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">kredite</a>.",
  "geServiceNotConfigured": "Widget Business Analyst nije moguće pokrenuti na ovom portalu jer usluga <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Obogaćivanje geopodacima</a> nije konfigurirana na njemu.",
  "dirRoutingServiceNotConfigured": "Widget Business Analyst nije moguće pokrenuti na ovom portalu jer usluga <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Upute za vožnju i rutiranje</a> nije konfigurirana na njemu.",
  "geAndDirRoutingServicesNotConfigured": "Widget Business Analyst nije moguće pokrenuti na ovom portalu jer usluge <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Obogaćivanje geopodacima</a> i <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Upute za vožnju i rutiranje</a> nisu konfigurirane na njemu.",
  "radii": "polumjeri",
  "radius": "Polumjer",
  "radius_lowercase": "polumjer",
  "reports": "Izvješća",
  "ring": "Prsten",
  "rings": "Prsteni",
  "runInfographic": "Pokreni infografiku",
  "runReport": "Pokreni izvješće",
  "selectPointOrPolygon": "Na karti odaberite točkasti ili poligonalni geoobjekt, pretražite adresu ili mjesto ili na kartu ispustite pribadaču za prikaz više informacija o područjima.",
  "selectReport": "Odabir izvješća",
  "selectTemplate": "Odabir predloška",
  "sharedInfographics": "Zajedničke infografike",
  "sharedReports": "Zajednička izvješća",
  "thisEntryIsNotValid": "Unos nije važeći.",
  "time": "Vrijeme",
  "walkTime": "Vrijeme hodanja",
  "widgetDescription": "Pristupite infografikama i izvješćima koja sažimaju ključne indikatore i podatke za svako područje.",
  "None": "Odabir..."
});