define({
  "enableUndoRedo": "Habilita les opcions per desfer/refer",
  "toolbarVisible": "Barra d'eines visible",
  "toolbarOptions": "Opcions de la barra d'eines",
  "mergeVisible": "Fusiona",
  "cutVisible": "Retalla",
  "reshapeVisible": "Canvia de forma",
  "back": "Enrere",
  "label": "Capa",
  "edit": "Editable",
  "update": "Deshabilita l'actualització de geometria",
  "fields": "Camps",
  "actions": "Accions",
  "editpageName": "Nom",
  "editpageAlias": "Àlies",
  "editpageVisible": "Visible",
  "editpageEditable": "Editable",
  "noLayers": "No hi ha cap capa d'entitats editable disponible",
  "configureFields": "Configura els camps de capa",
  "useFilterEdit": "Utilitza el filtre de plantilla d'entitat",
  "display": "Mostra",
  "autoApplyEditWhenGeometryIsMoved": "Aplica l'edició automàticament quan es mogui la geometria",
  "snappingTolerance": "Defineix la tolerància d'alineació en píxels",
  "popupTolerance": "Defineix la tolerància de l'element emergent d'edició d'atributs en píxels",
  "stickyMoveTolerance": "Defineix la tolerància de moviment en píxels",
  "usingSaveButton": "No apliquis les edicions als atributs fins que s'hagi fet clic al botó Desa"
});