define({
  "_widgetLabel": "智慧編輯器",
  "_featureAction_SmartEditor": "智慧編輯器",
  "noEditPrivileges": "您的帳號沒有建立或修改資料的權限。",
  "widgetActive": "使用中",
  "widgetNotActive": "非使用中",
  "pressStr": "按 ",
  "ctrlStr": " Ctrl 鍵 ",
  "snapStr": " 啟用貼齊",
  "noAvailableTempaltes": "沒有可用的樣板",
  "editorCache": " - 編輯器快取",
  "presetFieldAlias": "欄位",
  "presetValue": "預設值",
  "usePresetValues": " 使用預設值 (僅限新圖徵)",
  "editGeometry": " 編輯幾何",
  "savePromptTitle": "儲存圖徵",
  "savePrompt": "是否要儲存目前圖徵?",
  "deletePromptTitle": "刪除圖徵",
  "deleteAttachment": "刪除附件",
  "deletePrompt": "是否確定要刪除所選圖徵?",
  "attachmentLoadingError": "上傳附件出錯",
  "attachmentSaveDeleteWarning": "警告: 會自動儲存對附件的變更",
  "autoSaveEdits": "自動儲存新圖徵",
  "addNewFeature": "建立新圖徵",
  "featureCreationFailedMsg": "無法建立新記錄/圖徵",
  "relatedItemTitle": "相關表格/圖層",
  "relatedFeatureCount": "包含 ${featureCount} 個圖徵的 ${layerTitle}",
  "createNewFeatureLabel": "為 ${layerTitle} 建立新圖徵",
  "invalidRelationShipMsg": "請確定主要索引鍵欄位 '${parentKeyField}’ 具備有效值",
  "pendingFeatureSaveMsg": "請先儲存圖徵編輯內容再建立相關圖徵。",
  "attachmentsRequiredMsg": "(*) 附件為必填項。",
  "coordinatePopupTitle": "將圖徵移至 XY 位置",
  "coordinatesSelectTitle": "座標系統:",
  "mapSpecialReferenceDropdownOption": "地圖空間參考",
  "latLongDropdownOption": "緯度/經度",
  "xAttributeTextBoxLabel": "X 座標:",
  "yAttributeTextBoxLabel": "Y 座標:",
  "latitudeTextBoxLabel": "緯度:",
  "longitudeTextBoxLabel": "經度:",
  "presetGroupFieldsLabel": "會將 ‘${groupName}’ 套用到下列圖層欄位:",
  "presetGroupNoFieldsLabel": "'${groupName}’ 沒有任何相關欄位",
  "groupInfoLabel": "'${groupName}’ 的群組資訊",
  "editGroupInfoIcon": "編輯 ${groupName} 的群組值",
  "filterEditor": {
    "all": "全部",
    "noAvailableTempaltes": "沒有可用的樣板",
    "searchTemplates": "搜尋樣板",
    "filterLayerLabel": "篩選圖層"
  },
  "invalidConfiguration": "未配置 widget，或配置中的圖層已從地圖中消失。請在建構器模式中開啟應用程式，並重新配置 widget。",
  "geometryServiceURLNotFoundMSG": "無法取得幾何服務 URL",
  "clearSelection": "清除",
  "refreshAttributes": "更新圖徵屬性",
  "automaticAttributeUpdatesOn": "自動更新圖徵屬性: 開啟",
  "automaticAttributeUpdatesOff": "自動更新圖徵屬性: 關閉",
  "moveSelectedFeatureToGPS": "將所選圖徵移至目前的 GPS 位置",
  "moveSelectedFeatureToXY": "將所選圖徵移至 XY 位置",
  "mapNavigationLocked": "地圖導覽: 已鎖定",
  "mapNavigationUnLocked": "地圖導覽: 已解除鎖定",
  "copyFeatures": {
    "title": "複製圖徵",
    "createFeatures": "建立圖徽",
    "createSingleFeature": "建立 1 個多重幾何圖徵",
    "noFeaturesSelectedMessage": "未選擇任何圖徵",
    "selectFeatureToCopyMessage": "請選擇要複製的圖徵。",
    "multipleFeatureSaveWarning": "附註: 使用複製圖徵建立多個圖徵時，將立即儲存所有圖徵"
  },
  "addingFeatureError": "在圖層上新增所選圖徵時發生錯誤。 請再試一次。",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}’ 圖徵無法複製。",
  "selectingFeatureError": "在圖層中選擇圖徵時出錯。 請再試一次。",
  "customSelectOptionLabel": "選擇要複製的圖徵",
  "noFeatureSelectedMessage": "未選擇任何圖徵。",
  "multipleFeatureSaveMessage": "將立即儲存所有圖徵。 是否要繼續?",
  "relativeDates": {
    "dateTypeLabel": "日期類型",
    "valueLabel": "數值",
    "fixed": "已修正",
    "current": "目前",
    "past": "過去",
    "future": "未來",
    "popupTitle": "選擇值",
    "hintForFixedDateType": "提示: 會將指定的日期和時間作為預設值",
    "hintForCurrentDateType": "提示: 會將目前的日期和時間作為預設值",
    "hintForPastDateType": "提示: 將從預設值的目前日期和時間減去指定值。",
    "hintForFutureDateType": "提示: 會將指定值新增至預設值的目前日期和時間。",
    "noDateDefinedTooltip": "未定義日期"
  }
});