define({
  "_widgetLabel": "Chytrá editace",
  "_featureAction_SmartEditor": "Chytrá editace",
  "noEditPrivileges": "Váš online účet nemá přístupová práva k vytváření nebo úpravě dat.",
  "widgetActive": "Aktivní",
  "widgetNotActive": "Neaktivní",
  "pressStr": "Stisknutím ",
  "ctrlStr": " CTRL ",
  "snapStr": " aktivujete přichytávání.",
  "noAvailableTempaltes": "Žádné šablony nejsou k dispozici.",
  "editorCache": " – cache editoru",
  "presetFieldAlias": "Pole",
  "presetValue": "Přednastavená hodnota",
  "usePresetValues": " Použít přednastavené hodnoty (pouze nové prvky)",
  "editGeometry": " Upravit geometrii",
  "savePromptTitle": "Uložit prvek",
  "savePrompt": "Přejete si uložit aktuální prvek?",
  "deletePromptTitle": "Odstranit prvek",
  "deleteAttachment": "Smazat přílohu",
  "deletePrompt": "Určitě chcete odstranit vybraný prvek?",
  "attachmentLoadingError": "Při nahrávání příloh došlo k chybě.",
  "attachmentSaveDeleteWarning": "Varování: Změny příloh se automaticky uloží.",
  "autoSaveEdits": "Automaticky uloží nový prvek",
  "addNewFeature": "Vytvořit nový prvek",
  "featureCreationFailedMsg": "Nelze vytvořit nový záznam/prvek",
  "relatedItemTitle": "Související tabulka/vrstva",
  "relatedFeatureCount": "${layerTitle} s ${featureCount} prvky",
  "createNewFeatureLabel": "Vytvořit nový prvek pro ${layerTitle}",
  "invalidRelationShipMsg": "Ujistěte se prosím, že primární klíčové pole: ‚${parentKeyField}‘ obsahuje platnou hodnotu",
  "pendingFeatureSaveMsg": "Před tím, než vytvoříte související prvek, uložte prosím editaci prvku.",
  "attachmentsRequiredMsg": "(*) Jsou vyžadovány přílohy.",
  "coordinatePopupTitle": "Přesunout prvek na umístění XY",
  "coordinatesSelectTitle": "Souřadnicový systém:",
  "mapSpecialReferenceDropdownOption": "Souřadnicový systém mapy",
  "latLongDropdownOption": "zeměpisné šířky/délky",
  "xAttributeTextBoxLabel": "Souřadnice X:",
  "yAttributeTextBoxLabel": "Souřadnice Y:",
  "latitudeTextBoxLabel": "Zeměpisná šířka:",
  "longitudeTextBoxLabel": "Zeměpisná délka:",
  "presetGroupFieldsLabel": "'${groupName}' bude použito pro následující pole vrstvy:",
  "presetGroupNoFieldsLabel": "'${groupName}' nemá přidružená žádná pole",
  "groupInfoLabel": "Informace o skupině pro '${groupName}'",
  "editGroupInfoIcon": "Upravit skupinovou hodnotu pro ${groupName}",
  "filterEditor": {
    "all": "Všechny",
    "noAvailableTempaltes": "Žádné šablony nejsou k dispozici.",
    "searchTemplates": "Vyhledávání šablon",
    "filterLayerLabel": "Filtrovat vrstvy"
  },
  "invalidConfiguration": "Widget není nakonfigurován nebo se vrstvy v konfiguraci již nenacházejí v mapě. Spusťte aplikaci v režimu tvorby a upravte konfiguraci widgetu.",
  "geometryServiceURLNotFoundMSG": "Nelze načíst adresu URL služby geometrie",
  "clearSelection": "Zrušit výběr",
  "refreshAttributes": "Aktualizovat atributy prvků",
  "automaticAttributeUpdatesOn": "Automaticky aktualizovat atributy prvků: ZAPNOUT",
  "automaticAttributeUpdatesOff": "Automaticky aktualizovat atributy prvků: VYPNOUT",
  "moveSelectedFeatureToGPS": "Přesunout vybraný prvek na aktuální umístění GPS",
  "moveSelectedFeatureToXY": "Přesunout vybraný prvek na umístění XY",
  "mapNavigationLocked": "Mapová navigace: Uzamknuto",
  "mapNavigationUnLocked": "Mapová navigace: Odemknuto",
  "copyFeatures": {
    "title": "Kopírovat prvky",
    "createFeatures": "Vytvořit prvky",
    "createSingleFeature": "Vytvořit 1 prvek s vícenásobnou geometrií",
    "noFeaturesSelectedMessage": "Nejsou vybrány žádné prvky",
    "selectFeatureToCopyMessage": "Vyberte prvky ke zkopírování.",
    "multipleFeatureSaveWarning": "Poznámka: Vytvoření více prvků pomocí nástroje kopírovat prvky všechny prvky okamžitě uloží."
  },
  "addingFeatureError": "Během přidávání vybraných prvků ve vrstvě došlo k chybě. Zkuste to prosím znovu.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' prvků se nepodařilo zkopírovat.",
  "selectingFeatureError": "Během výběru prvků ve vrstvě došlo k chybě. Zkuste to prosím znovu.",
  "customSelectOptionLabel": "Vyberte prvky, které se mají zkopírovat",
  "noFeatureSelectedMessage": "Nejsou vybrány žádné prvky.",
  "multipleFeatureSaveMessage": "Všechny prvky budou ihned uloženy. Chcete pokračovat?",
  "relativeDates": {
    "dateTypeLabel": "Typ data",
    "valueLabel": "Hodnota",
    "fixed": "Fixní",
    "current": "Aktuální",
    "past": "Minulé",
    "future": "Budoucí",
    "popupTitle": "Vybrat hodnotu",
    "hintForFixedDateType": "Nápověda: Nastavené datum a čas bude použito jako přednastavená výchozí hodnota.",
    "hintForCurrentDateType": "Nápověda: Aktuální datum a čas bude použito jako přednastavená výchozí hodnota.",
    "hintForPastDateType": "Nápověda: Zadaná hodnota bude odečtena od aktuálního data a času, a bude tak určena výchozí hodnota pro přednastavení.",
    "hintForFutureDateType": "Nápověda: Zadaná hodnota bude přidána od aktuálního data a času, a bude tak určena výchozí hodnota pro přednastavení.",
    "noDateDefinedTooltip": "Není určeno žádné datum",
    "relativeDateWarning": "Aby bylo možné uložit výchozí přednastavenou hodnotu, musí být zadána hodnota pro datum nebo čas."
  }
});