define({
  "showArcgisBasemaps": "Portal altlık haritalarını dahil et",
  "add": "Yeni Altlık Haritası Eklemek için tıkla",
  "edit": "Özellikler",
  "titlePH": "Altlık Haritası Başlığı",
  "thumbnailHint": "Güncellemek için resme tıkla",
  "urlPH": "Katman URL'si",
  "addlayer": "Altlık Haritası Ekle",
  "warning": "Hatalı girdi",
  "save": "Dön ve Kaydet",
  "back": "Dön ve İptal Et",
  "addUrl": "URL Ekle",
  "autoCheck": "Otomatik Denetle",
  "checking": "Denetleniyor...",
  "result": "Başarıyla kaydedildi",
  "spError": "Galeriye eklenen tüm altlık haritalar aynı mekansal başvuruya sahip olmalıdır.",
  "invalidTitle1": "Bir altlık haritası '",
  "invalidTitle2": "' zaten mevcut. Başka bir başlık seçin.",
  "invalidBasemapUrl1": "Bu katman türü altlık haritası olarak kullanılamaz.",
  "invalidBasemapUrl2": "Eklediğiniz altlık haritası geçerli haritadan farklı bir mekansal başvuruya sahip.",
  "addBaselayer": "Altlık Haritası Katmanı Ekle"
});