define({
  "transparencyLabel": "Transparência",
  "outline": "Contorno",
  "fill": "Preenchimento (Apenas é aplicada cor quando o estilo é definido como sólido)",
  "style": "Estilo",
  "mandatoryLabel": "Distância de evacuação obrigatória",
  "mandatoryButtonLabel": "Configurar definições de distância de evacuação obrigatória",
  "safeLabel": "Distância de evacuação segura",
  "safeButtonLabel": "Configurar definições de distância de evacuação segura",
  "selectOpLayerLabel": "Selecionar uma nova camada operacional para os resultados",
  "selectDefaultMeasurementLabel": "Selecionar a unidade de medida predefinida",
  "helpIconTooltip": "A lista de camadas operacionais é preenchida com camadas do mapa web atual do tipo de geometria de polígono.",
  "lineStyles": {
    "esriSLSDash": "Traço",
    "esriSLSDashDot": "Traço e Ponto",
    "esriSLSDashDotDot": "Traço, Ponto e Ponto",
    "esriSLSDot": "Ponto",
    "esriSLSLongDash": "Traço Longo",
    "esriSLSLongDashDot": "Traço Longo e Ponto",
    "esriSLSNull": "Nulo",
    "esriSLSShortDash": "Traço Curto",
    "esriSLSShortDashDot": "Traço Curto e Ponto",
    "esriSLSShortDashDotDot": "Traço Curto, Ponto e Ponto",
    "esriSLSShortDot": "Traço Curto",
    "esriSLSSolid": "Sólido"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Ao Contrário",
    "esriSFSCross": "Cruz",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Para a frente",
    "esriSFSHorizontal": "Horizontal",
    "esriSFSNull": "Nulo",
    "esriSFSSolid": "Sólido",
    "esriSFSVertical": "Vertical"
  },
  "threatTypeLabel": "Tipo de ameaça",
  "symbologyLabel": "Simbologia",
  "generalLabel": "Geral",
  "addThreatTypesLabel": "Adicionar Tipo de Ameaça",
  "threatTypeColLabel": "Tipo de ameaça",
  "actions": "Ações",
  "newThreatTypePopupLabel": "Novo Tipo de Ameaça",
  "chooseDefaultThreatTypeIconLabel": "Escolher de predefinição",
  "mandatoryDistance": "Distância de evacuação obrigatória",
  "safeDistance": "Distância de evacuação segura",
  "units": "Unidades",
  "chooseDefaultThreatLabel": "Selecionar um tipo de ameaça predefinido",
  "defaultThreatTypePopUpLabel": "Tipos de Ameaça Predefinidos",
  "editThreatLabel": "Editar Ameaça",
  "defaultThreatTypeIconTooltip": "Lista de Tipos de Ameaça Predefinidos",
  "uniqueThreatTypeMsg": "Introduza um tipo de ameaça único; já existe um tipo de ameaça com este nome.",
  "requiredThreatTypeMsg": "Este campo é necessário",
  "unitMeasureLabel": "As distâncias estão em {0}",
  "pipeBombLabel": "Bomba de Tubo",
  "suicideBombLabel": "Bomba Suicida",
  "briefcaseLabel": "Pasta",
  "carLabel": "Carro",
  "suvVanLabel": "SUV/CARRINHA",
  "smallDeliveryTruckLabel": "Carrinha de Entregas Pequena",
  "containerWaterTruckLabel": "Camião Cisterna/de Água",
  "semiTrailerLabel": "Semirreboque"
});