define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Haritaya tıklayarak nokta ekleyin",
  "addRingsDtWt": "Halkalar, sürüş süresi veya yürüyüş süresi ekleyin.",
  "apply": "Uygula",
  "back": "Geri",
  "colon": ":",
  "creditInformation": "Kredi Bilgisi",
  "driveTime": "Sürüş zamanı",
  "esriInfographics": "Esri İnfografi",
  "esriReports": "Esri Rapor",
  "headerDescription_km": "kilometre",
  "headerDescription_miles": "mil",
  "headerDescription_minutes": "dakika",
  "infographics": "Bilgi Grafikleri",
  "invalidValueRing": "Değerler 0 - 1.000 aralığında olmalıdır.",
  "invalidValueDTWT": "Değerler 0 - 300 aralığında olmalıdır.",
  "km": "km",
  "miles": "mil",
  "minutes": "dakika",
  "myInfographics": "İnfografim",
  "myReports": "Raporlarım",
  "noPermissions": "Hesabınız Business Analyst aracını çalıştıramaz. Business Analyst aracını çalıştırmak için kuruluşunuzun yöneticisi size GeoEnrichment ve Network Analysis <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">ayrıcalıklarını</a> vermeli ve ayrıca <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">kredi</a> tahsis etmelidir.",
  "geServiceNotConfigured": "Business Analyst aracı bu portalda çalışamaz, çünkü <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Coğrafi Zenginleştirme</a> servisi bunun üzerinde yapılandırılmadı.",
  "dirRoutingServiceNotConfigured": "Business Analyst aracı bu portalda çalışamaz, çünkü <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Yol Tarifleri ve Yönlendirme</a> servisi bunun üzerinde yapılandırılmadı.",
  "geAndDirRoutingServicesNotConfigured": "Business Analyst aracı bu portalda çalışamaz, çünkü <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Coğrafi Zenginleştirme</a> ve <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Yol Tarifleri ve Yönlendirme</a> servisleri bunun üzerinde yapılandırılmadı.",
  "radii": "yarıçaplar",
  "radius": "Yarıçap",
  "radius_lowercase": "yarıçap",
  "reports": "Raporlar",
  "ring": "Çember",
  "rings": "Halkalar",
  "runInfographic": "İnfografi çalıştır",
  "runReport": "Raporu Çalıştır",
  "selectPointOrPolygon": "Haritada bir Nokta veya Çokgen detayı seçin, bir adres veya yer arayın veya alanlar hakkında daha fazla bilgi görüntülemek için haritaya bir raptiye saplayın.",
  "selectReport": "Rapor Seç",
  "selectTemplate": "Şablon Seç",
  "sharedInfographics": "Paylaşılan İnfografi",
  "sharedReports": "Paylaşılan Raporlar",
  "thisEntryIsNotValid": "Giriş geçerli değil.",
  "time": "Saat",
  "walkTime": "Yürüme süresi",
  "widgetDescription": "Herhangi bir alanın anahtar göstergeleri veya verilerini özetleyen İnfografi ve Raporlara erişim sağlayın.",
  "None": "Seç..."
});