define({
  "enableUndoRedo": "Leisti atšaukimą/grąžinimą",
  "toolbarVisible": "Įrankių juosta matoma",
  "toolbarOptions": "Įrankių juostos parinktys",
  "mergeVisible": "Sulieti",
  "cutVisible": "Kirpti",
  "reshapeVisible": "Performuoti",
  "back": "Atgal",
  "label": "Sluoksnis",
  "edit": "Redaguojama",
  "update": "Išjungti geometrijos atnaujinimą",
  "fields": "Laukai",
  "actions": "Veiksmai",
  "editpageName": "Pavadinimas",
  "editpageAlias": "Pseudonimas",
  "editpageVisible": "Matoma",
  "editpageEditable": "Redaguojama",
  "noLayers": "Galimų redaguoti elementų sluoksnių nėra",
  "configureFields": "Konfigūruoti sluoksnio laukus",
  "useFilterEdit": "Naudoti elementų šablonų filtrą",
  "display": "Rodyti",
  "autoApplyEditWhenGeometryIsMoved": "Įrašyti automatiškai, kai geometrija perkeliama",
  "snappingTolerance": "Nustatyti pritraukimo toleranciją pikseliais",
  "popupTolerance": "Nustatyti atributų redagavimo iškylančiojo lango toleranciją pikseliais",
  "stickyMoveTolerance": "Nustatyti prilimpančio postūmio toleranciją pikseliais",
  "usingSaveButton": "Netaikyti pakeitimų atributams, nespustelėjus mygtuko Įrašyti",
  "generalSettings": "Bendrieji parametrai",
  "editableLayersSetting": "Redaguojamų sluoksnių parametrai",
  "honorTheWebMapSetting": "Paisyti internetinio žemėlapio parametrų",
  "honorTheWebMapSettingTip1": "Šie parametrai apima:",
  "honorTheWebMapSettingTip2": "Kurie sluoksniai yra redaguojami",
  "honorTheWebMapSettingTip3": "Laukai, kuriuos norite rodyti ir redaguoti",
  "honorTheWebMapSettingTip4": "Lauko pseudonimas, išsidėstymas ir formatas",
  "customSettings": "Adaptuoti parametrai"
});