define({
  "showArcgisBasemaps": "Incluir mapas base del portal",
  "add": "Haz clic para agregar un nuevo mapa base",
  "edit": "Propiedades",
  "titlePH": "Título del mapa base",
  "thumbnailHint": "Haz clic en la imagen para actualizar",
  "urlPH": "URL de la capa",
  "addlayer": "Agregar mapa base",
  "warning": "Entrada incorrecta",
  "save": "Volver y guardar",
  "back": "Volver y cancelar",
  "addUrl": "Agregar URL",
  "autoCheck": "Comprobación automática",
  "checking": "Comprobando...",
  "result": "Se ha guardado correctamente",
  "spError": "Todos los mapas base agregados a la galería deben tener la misma referencia espacial.",
  "invalidTitle1": "Ya existe un mapa base '",
  "invalidTitle2": "'. Elige otro título.",
  "invalidBasemapUrl1": "Este tipo de capa no se puede usar como mapa base.",
  "invalidBasemapUrl2": "El mapa base que va a agregar tiene una referencia espacial distinta de la del mapa actual.",
  "addBaselayer": "Agregar capa de mapa base"
});