define({
  "chartSettingLabel": "Diagrambeállítások",
  "addNewLabel": "Új hozzáadása",
  "generalSettingLabel": "Általános beállítások",
  "searchSourceSettingLabel": "Keresési forrás beállításai",
  "layerChooser": {
    "title": "Válassza ki az ábrázolni kívánt réteget",
    "selectPolygonLayerLabel": "Réteg kiválasztása",
    "selectPolygonLayerHintText": "Tipp: Ha több diagramot konfigurál, akkor a rétegeknek azonos geometriatípushoz kell tartozniuk",
    "selectRelatedTableLayerLabel": "Réteghez kapcsolt tábla kiválasztása",
    "selectRelatedTableLayerHintText": "Tipp: Csak a numerikus mezőkkel rendelkező táblák jelennek meg",
    "errorInSelectingPolygonLayer": "Olyan réteget válasszon, amelyhez kapcsolt pontréteg tartozik.",
    "errorInSelectingRelatedLayer": "A réteghez kapcsolt érvényes táblát/réteget válasszon ki.",
    "polygonLayerNotHavingRelationships": "A kiválasztott réteghez nem tartozik kapcsolt tábla/réteg."
  },
  "ChartSetting": {
    "sectionTitle": "Szakaszcím",
    "sectionTitleHintText": "Tipp: A szakasz fejlécének címében jelenik meg",
    "chartTitle": "Diagram címe",
    "chartTitleHintText": "Tipp: A diagram tetején, középen jelenik meg",
    "chartDescription": "Leírás",
    "chartDescriptionHintText": "Tipp: A diagram alatt jelenik meg",
    "chartType": "Diagram típusa",
    "barChart": "Oszlop/sáv diagram",
    "pieChart": "Kördiagram",
    "polarChart": "Polárdiagram",
    "lineChart": "Vonaldiagram",
    "dataSeriesField": "Adatsormező",
    "lineDataSeriesField": "Értékmező",
    "labelField": "Feliratmező",
    "lineLabelSeriesField": "Sorozatmező",
    "chartColor": "Diagram színe",
    "singleColor": "Egyszínű",
    "colorByTheme": "Szín téma szerint",
    "colorByFieldValue": "Szín a mezőérték alapján",
    "xAxisTitle": "X tengely felirata",
    "xAxisHintText": "Tipp: Az X-tengely felirata",
    "yAxisTitle": "Y tengely felirata",
    "yAxisHintText": "Tipp: Az Y-tengely felirata",
    "fieldColorLabel": "Felirat",
    "fieldColorColor": "Szín",
    "defaultFieldSelectLabel": "Kiválasztás",
    "errMsgFieldValuesNotFound": "Nem találhatók a kiválasztott mező értékei",
    "errMsgSectionTitle": "Adja meg a szekció címét",
    "errMsgFieldByValue": "Válasszon színt a mezőérték alapján",
    "errMsgDataSeriesField": "Válasszon mezőértéket",
    "settingTabTitle": "Beállítás",
    "layoutTabTitle": "Elrendezés",
    "polarChartSelectFieldsHintText": "Tipp: Válassza ki a sugárdiagram létrehozásához szükséges mezőket",
    "visibilityText": "Láthatóság",
    "fieldNameText": "Mező neve",
    "aliasNameText": "Aliasnév",
    "errMsgPolarFieldsRequired": "Polárdiagram létrehozásához válasszon három vagy több mezőt",
    "polarChartPolygonFillLabel": "Polygon kitöltése",
    "polarChartPolygonFillHintText": "Tipp: Jelölje be a jelölőnégyzetet a polygonkitöltéshez a polárdiagramon",
    "viewLayoutLabel": "Elrendezés",
    "setValueFields": "Értékmezők beállítása",
    "layoutSeriesLabel": "Sorozat",
    "ThemeSelector": {
      "themeAdobebricks": "Adobe téglák",
      "themeAlgae": "Alga",
      "themeBahamation": "Bahama",
      "themeBlueDusk": "KékAlkony",
      "themeCubanShirts": "KubaiIng",
      "themeDesert": "Sivatag",
      "themeDistinctive": "Jellegzetes",
      "themeDollar": "Dollár",
      "themeGrasshopper": "Szöcske",
      "themeGrasslands": "Füves területek",
      "themeGreySkies": "SzürkeÉgbolt",
      "themeHarmony": "Harmónia",
      "themeIndigoNation": "Indigó",
      "themeIreland": "Írország",
      "themeMiamiNice": "Miami",
      "themeMinty": "Mentol",
      "themePurpleRain": "LilaEső",
      "themeRoyalPurples": "KirályiBíbor",
      "themeSageToLime": "ZsályaCitrus",
      "themeTufte": "Tufte",
      "themeWatersEdge": "Vízpart",
      "themeWetlandText": "Mocsárvidék",
      "themePlotKitblue": "PlotKit.kék",
      "themePlotKitcyan": "PlotKit.cián",
      "themePlotKitgreen": "PlotKit.zöld",
      "themePlotKitorange": "PlotKit.narancs",
      "themePlotKitpurple": "PlotKit.lila",
      "themePlotKitred": "PlotKit.piros"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Általános beállítások",
    "locationSymbolLabel": "Grafikus helyszimbólum",
    "locationSymbolHintText": "Tipp: A cím és a kattintás helyének szimbólumát jeleníti meg",
    "refreshIntervalLabel": "Frissítési időköz",
    "refreshIntervalHintText": "Tipp: A diagramok frissítésének időköze 1 és 1440 perc között lehet",
    "errMsgRefreshInterval": "A frissítési időközhöz 0 és 1440 perc közötti értéket adjon meg",
    "symbolPickerPreviewText": "Előnézet:",
    "showToolToSelectLabel": "Hely beállítása gomb",
    "showToolToSelectHintText": "Tipp: A helynek a térképen történő beállítására gombot biztosít – a térképre kattintás helyett"
  },
  "searchSourceSetting": {
    "searchSourceSettingTabTitle": "Keresési forrás beállításai",
    "searchSourceSettingTitle": "Keresési forrás beállításai",
    "searchSourceSettingTitleHintText": "Geokódoló szolgáltatások vagy vektoros rétegek hozzáadása és konfigurálása keresési forrásként. Ezek a megadott források határozzák meg, hogy mi kereshető a keresőmezőben.",
    "addSearchSourceLabel": "Keresési forrás hozzáadása",
    "featureLayerLabel": "Vektoros réteg",
    "geocoderLabel": "Geokódoló",
    "nameTitle": "Név",
    "generalSettingLabel": "Általános beállítás",
    "allPlaceholderLabel": "Helyőrző szöveg az összes kereséséhez:",
    "allPlaceholderHintText": "Tipp: Adja meg az összes réteg és geokódoló keresésekor helyőrzőként megjelenítendő szöveget",
    "generalSettingCheckboxLabel": "Felugró ablak megjelenítése a megtalált vektoros elemhez vagy helyhez",
    "countryCode": "Ország- vagy régiókód(ok)",
    "countryCodeEg": "pl. ",
    "countryCodeHint": "Ha üresen hagyja ezt az értéket, a keresés minden országra és régióra ki fog terjedni",
    "questionMark": "?",
    "searchInCurrentMapExtent": "Csak az aktuális térképkiterjedésen belül keressen",
    "zoomScale": "Zoom-méretarány",
    "locatorUrl": "Geokódoló URL-címe",
    "locatorName": "Geokódoló neve",
    "locatorExample": "Példa",
    "locatorWarning": "A geokódoló szolgáltatás ezen verziója nem támogatott. A widget csak a 10.0 és újabb verziójú geokódoló szolgáltatást támogatja.",
    "locatorTips": "Nem érhetők el a javaslatok, mert a geokódoló szolgáltatás nem támogatja ezt a funkciót.",
    "layerSource": "Rétegforrás",
    "setLayerSource": "Rétegforrás beállítása",
    "setGeocoderURL": "Geokódoló URL-címének beállítása",
    "searchLayerTips": "Nem érhetők el a javaslatok, mert a vektoros adatszolgáltatás nem támogatja az oldalszámozást.",
    "placeholder": "Helyőrző szöveg",
    "searchFields": "Mezők keresése",
    "displayField": "Megjelenítési mező",
    "exactMatch": "Pontos találat",
    "maxSuggestions": "Javaslatok maximális száma",
    "maxResults": "Találatok maximális száma",
    "enableLocalSearch": "Helyi keresés engedélyezése",
    "minScale": "Min. méretarány",
    "minScaleHint": "Ha a térkép méretaránya nagyobb, mint ez a méretarány, akkor a helyi keresés lesz aktív",
    "radius": "Sugár",
    "radiusHint": "A térkép aktuális középpontja körül annak a területnek a sugarát határozza meg, amelyen belül megnő a geokódoló jelöltjeinek prioritása, hogy az adott helyhez legközelebb lévő jelöltek elsőbbséget élvezzenek",
    "meters": "Méter",
    "setSearchFields": "Keresőmezők beállítása",
    "set": "Állítsa be",
    "fieldName": "Név",
    "invalidSearchSources": "A keresési forrás beállításai érvénytelenek",
    "invalidUrlTip": "A(z) ${URL} URL-cím érvénytelen vagy nem érhető el.",
    "maxSuggestionErrorMessage": "Adjon meg érvényes maximális javaslati értéket. A beírt érték kívül esik a tartományon vagy érvénytelen",
    "maxResultsErrorMessage": "Adjon meg érvényes maximális eredményértéket. A beírt érték kívül esik a tartományon vagy érvénytelen",
    "zoomScaleErrorMessage": "Adjon meg érvényes nagyítási/kicsinyítési skála értéket. A beírt érték kívül esik a tartományon vagy érvénytelen",
    "minScaleErrorMessage": "Adjon meg érvényes minimális skála értéket. A beírt érték kívül esik a tartományon vagy érvénytelen",
    "radiusErrorMessage": "Adjon meg érvényes sugárértéket. A beírt érték kívül esik a tartományon vagy érvénytelen"
  }
});