define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Adicione ponto clicando no mapa",
  "addRingsDtWt": "Adicionar anéis, tempo do percurso ou tempo de caminhada.",
  "apply": "Aplicar",
  "back": "Voltar",
  "colon": ":",
  "creditInformation": "Informações de créditos",
  "driveTime": "Tempo de percurso",
  "esriInfographics": "Infográficos da Esri",
  "esriReports": "Relatórios da Esri",
  "headerDescription_km": "quilômetro",
  "headerDescription_miles": "milha",
  "headerDescription_minutes": "minuto",
  "infographics": "Infográficos",
  "invalidValueRing": "Os valores devem estar na faixa de 0 até 1,000.",
  "invalidValueDTWT": "Os valores devem estar na faixa de 0 até 300.",
  "km": "km",
  "miles": "milhas",
  "minutes": "minutos",
  "myInfographics": "Meus Infográficos",
  "myReports": "Meus Relatórios",
  "noPermissions": "Sua conta não pode executar o widget Business Analyst.  Para executar o widget Business Analyst, o administrador de sua organização precisa conceder a você os <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilégios</a> do GeoEnrichment e Network Analysis e também alocar <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">créditos</a>.",
  "geServiceNotConfigured": "O widget Analista de Negócios não pode ser executado neste portal, pois o serviço <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenriquecimento</a> não está configurado nele.",
  "dirRoutingServiceNotConfigured": "O widget Analista de Negócios não pode ser executado neste portal, pois o serviço <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Direções e Rota</a> não está configurado nele.",
  "geAndDirRoutingServicesNotConfigured": "O widget Analista de Negócios não pode ser executado neste portal, pois o serviço <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenriquecimento</a> e <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Direções e Rota</a> não estão configurados nele.",
  "radii": "radii",
  "radius": "Proporção",
  "radius_lowercase": "raio",
  "reports": "Relatórios",
  "ring": "Anel",
  "rings": "Anéis",
  "runInfographic": "Executar Infográficos",
  "runReport": "Executar Relatório",
  "selectPointOrPolygon": "Selecione uma feição de Ponto ou Polígono no mapa, procure por um endereço ou lugar, ou posicione um alfinete no mapa para visualizar mais informações das áreas.",
  "selectReport": "Selecionar Relatório",
  "selectTemplate": "Selecionar Modelo",
  "sharedInfographics": "Infográficos Compartilhados",
  "sharedReports": "Relatórios Compartilhados",
  "thisEntryIsNotValid": "Esta entrada não é válida.",
  "time": "Hora",
  "walkTime": "Tempo de caminhada",
  "widgetDescription": "Acessar Infográficos e Relatórios que resumem indicadores chaves e dados de qualquer área.",
  "None": "Selecionar..."
});