define({
  "transparencyLabel": "Transparantie",
  "outline": "Omtreklijn",
  "fill": "Vullen (kleur wordt alleen toegepast als stijl ingesteld is al solid)",
  "style": "Stijl",
  "mandatoryLabel": "Verplichte evacuatie-afstand",
  "mandatoryButtonLabel": "Verplichte afstandsinstellingen configureren",
  "safeLabel": "Veilige evacuatie-afstand",
  "safeButtonLabel": "Veilige afstandsinstellingen configureren",
  "selectOpLayerLabel": "Selecteer een operationele laag voor resultaten",
  "selectDefaultMeasurementLabel": "Selecteer een standaard meeteenheid",
  "helpIconTooltip": "De lijst met operationele lagen is bevolkt met lagen van de huidige web map van het type polygoongeometrie.",
  "lineStyles": {
    "esriSLSDash": "Streep",
    "esriSLSDashDot": "Streep punt",
    "esriSLSDashDotDot": "Streep punt punt",
    "esriSLSDot": "Punt",
    "esriSLSLongDash": "Lange streep",
    "esriSLSLongDashDot": "Lange streep punt",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Korte streep",
    "esriSLSShortDashDot": "Korte streep punt",
    "esriSLSShortDashDotDot": "Korte streep punt punt",
    "esriSLSShortDot": "Korte punt",
    "esriSLSSolid": "Ononderbroken"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Achterwaarts",
    "esriSFSCross": "Kruis",
    "esriSFSDiagonalCross": "Diagonaal",
    "esriSFSForwardDiagonal": "Voorwaarts",
    "esriSFSHorizontal": "Horizontaal",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Ononderbroken",
    "esriSFSVertical": "Verticaal"
  },
  "threatTypeLabel": "Dreigingstype",
  "symbologyLabel": "Symbologie",
  "generalLabel": "Algemeen",
  "addThreatTypesLabel": "Dreigingstype toevoegen",
  "threatTypeColLabel": "Dreigingstype",
  "actions": "Acties",
  "newThreatTypePopupLabel": "Nieuw dreigingstype",
  "chooseDefaultThreatTypeIconLabel": "Kies uit standaard opties",
  "mandatoryDistance": "Verplichte evacuatie-afstand",
  "safeDistance": "Veilige evacuatie-afstand",
  "units": "Eenheden",
  "chooseDefaultThreatLabel": "Selecteer een standaarddreigingstype",
  "defaultThreatTypePopUpLabel": "Standaarddreigingstypes",
  "editThreatLabel": "Dreiging bewerken",
  "defaultThreatTypeIconTooltip": "Lijst standaarddreigingstype",
  "uniqueThreatTypeMsg": "Voer een uniek dreigingstype in, dreigingstype met deze naam bestaat al.",
  "requiredThreatTypeMsg": "Dit veld is verplicht.",
  "unitMeasureLabel": "Afstanden zijn in {0}",
  "pipeBombLabel": "Pijpbom",
  "suicideBombLabel": "Zelfmoordaanslag",
  "briefcaseLabel": "Aktetas",
  "carLabel": "Auto",
  "suvVanLabel": "SUV/busje",
  "smallDeliveryTruckLabel": "Klein bestelbusje",
  "containerWaterTruckLabel": "Container/vrachtwagen voor vervoer van water",
  "semiTrailerLabel": "Oplegger"
});