define({
  "styleText": "เลือกสไตล์สำหรับเครื่องมือเลื่อน",
  "vertical": "แถบแนวตั้ง",
  "horizontal": "แถบแนวนอน",
  "scope": "กล้องขยาย",
  "barColor": "สีของแถบ",
  "swipeMode": "โหมดการเลื่อน",
  "singleLayer": "ชั้นเดียว",
  "MultipleLayers": "หลายชั้่น",
  "allowToSwipe": "อนุญาตการเลื่อน",
  "layer": "ชั้นข้อมูล",
  "swipeByDefault": "เลื่อนตามค่าเริ่มต้น",
  "defaultLayerMustBeVisible": "ชั้นเริ่มต้นจะต้องมองเห็นได้",
  "noDefaultLayer": "โปรดตั้งค่าชั้นให้เลื่อนตามค่าเริ่มต้น",
  "defaultLayerHolder": "คลิกเพื่อเลือก",
  "selectLayers": "เลือกชั้น",
  "layerText": "เลือกชั้นที่คุณต้องการเลื่อนตามค่าเริ่มต้น",
  "spyglassText": "เลือกชั้นข้อมูลที่จะแสดงผลในกล้องขยายจากค่าเริ่มต้น",
  "layerHint": "Note: ถ้าชั้นข้อมูลถูกซ่อนไว้โดยชั้นข้อมูลบน เลื่อนจะไม่ได้มีผลกระทบใด ๆ",
  "isZoom": "ขยายไปยัง swipe layer",
  "isZooms": "ซูมเพื่อเลื่อนชั้น",
  "layersAvailable": "เลือกชั้นข้อมูลที่จะกวาด:"
});