define({
  "serviceUrl": "Ange tjänst-URL:",
  "minIntSpacingLabel": "Minsta intervallavstånd",
  "lineOpacityLabel": "Linjeopacitet",
  "labelOpacityLabel": "Etikettopacitet",
  "centerLabelOpacityLabel": "Opacitet i mitten av etiketten",
  "gridZonePlacementLabel": "Placering av etiketter i rutnätszon",
  "verticalLineLabels": "Etiketter för vertikal linje",
  "styleHeaderLabel": "Format",
  "indexHeaderLabel": "Index",
  "colorHeaderLabel": "Färg",
  "fontSizeHeaderLabel": "Teckenstorlek",
  "lineWidthHeaderLabel": "Linjebredd",
  "horizontalLabel": "Horisontell",
  "verticalLabel": "Vertikal",
  "upperLeftLabel": "Övre vänstra",
  "upperRightLabel": "Övre högra",
  "lowerLeftLabel": "Nedre vänstra",
  "lowerRightLabel": "Nedre högra",
  "centerLabel": "Centrera"
});