define({
  "settings": "Definições",
  "titleSettings": "Definições de texto",
  "imageSettings": "Definições de imagem",
  "backgroundColor": "Cor de fundo",
  "alignment": "Alinhamento",
  "textSize": "Tamanho do texto",
  "textColor": "Cor do texto",
  "dataSource": "Fonte de Dados",
  "chartSettings": "Definições de gráficos",
  "data": "Dados",
  "dataLabels": "Rótulos de dados",
  "displayMode": "Modo de exibição",
  "featureOption": "Exibir valores elemento a elemento",
  "categoryOption": "Exibir valores por categoria",
  "countOption": "Exibir contagens de elementos por categoria",
  "fieldOption": "Exibir valores de atributos como gráficos",
  "categoryField": "Campo de categoria",
  "labelField": "Campo de rótulo",
  "valueFields": "Campos de valor",
  "operation": "Operação",
  "sumOption": "Soma",
  "averageOption": "Média",
  "minOption": "Mínimo",
  "maxOption": "Máximo",
  "dataFormat": "Formato de dados",
  "decimalPlaces": "Casas decimais",
  "prefix": "Prefixo",
  "suffix": "Sufixo",
  "dataType": "Tipo de Dados",
  "featureCount": "Contagem de elementos",
  "fieldStatistics": "Estatísticas de campos",
  "display": "Exibir",
  "chartColor": "Cor do gráfico",
  "horizontalAxis": "Eixo horizontal",
  "verticalAxis": "Eixo vertical",
  "legend": "Legenda",
  "position": "Posição",
  "top": "Superior",
  "bottom": "Inferior",
  "useDataSourceSelection": "Utilizar seleção",
  "dataSourceFilterByExtent": "Filtrar por extensão",
  "changeTemplate": "Alterar modelo",
  "numberSettings": "Definições de números",
  "gaugeSettings": "Definições de medidor",
  "indicators": "Indicadores",
  "ifValue": "Valor If",
  "and": "e",
  "numberOperatorIsLessThan": "é inferior a",
  "numberOperatorIsGreaterThan": "é superior a",
  "numberOperatorIsBetween": "é entre",
  "numberOperatorIsEqual": "é igual a",
  "numberOperatorIsNotEqual": "não é igual a",
  "then": "Portanto",
  "ratio": "Rácio",
  "trueValue": "Valor real",
  "changeValueColor": "Alterar cor do valor para",
  "changeGaugeColor": "Alterar cor do medidor para",
  "setIndicatorIcon": "Definir ícone de indicador como",
  "icons": "Ícones",
  "style": "Estilo",
  "placement": "Colocação",
  "left": "Esquerda",
  "replace": "Substituir",
  "right": "Direita",
  "color": "Cor",
  "sortBy": "Ordenar por",
  "labelAxis": "Rótulo",
  "valueAxis": "Valor",
  "minPeriod": "Período mínimo",
  "automatic": "Automático",
  "periodsWithOutRecords": "Períodos sem registos",
  "nullValue": "Valor nulo",
  "calculatedAsZero": "Calculado como zero",
  "ignored": "Ignorado",
  "maxCategories": "Máximo de categorias",
  "useLayerSymbology": "Utilizar simbologia da camada",
  "dataRange": "Intervalo de datas",
  "targetValue": "Valor alvo",
  "currentValue": "Valor atual",
  "gaugeColor": "Cor do medidor",
  "min": "Mínimo",
  "max": "Máximo",
  "displayValueIn": "Exibir valor em",
  "noData": "Sem dados",
  "thousandAbbreviation": "q",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Aviso",
  "noSettingWaring1": "Clique num elemento para definir as respetivas propriedades.",
  "noSettingWaring2": "Arraste para redimensionar ou reordenar um elemento.",
  "donNotShowAgain": "Não exibir novamente",
  "changeTemplateWarning": "Esta ação irá apagar todas as suas definições e abrirá um novo modelo vazio",
  "requiredFieldWarning": "Este valor é exigido:",
  "dataSourceNotSet": "Por favor, defina a fonte de dados.",
  "addIndicatorTip": "Adicionar um indicador",
  "chooseTemplatePopupTitle": "Seleccione um modelo",
  "stringsInTemplate": {
    "name_number": "Número",
    "name_gauge": "Medidor",
    "name_vertical_gauge": "Medidor Vertical",
    "name_horizontal_gauge": "Medidor Horizontal",
    "name_pie_chart": "Gráfico Circular",
    "name_column_chart": "Gráfico de Colunas",
    "name_bar_chart": "Gráfico de Barras",
    "name_line_chart": "Gráfico de Linhas",
    "titleOfTheInfographic": "TÍTULO DA INFOGRAFIA",
    "description": "Descrição: informações adicionais dobre esta infografia."
  }
});