define({
  "_widgetLabel": "Grafik",
  "executeChartTip": "Klik salah satu dari item tugas berikut untuk menjalankan grafik.",
  "invalidConfig": "Konfigurasi tidak valid.",
  "noneChartTip": "Tidak ada grafik tugas yang dikonfigurasikan untuk widget ini.",
  "chartParams": "Opsi",
  "charts": "GRAFIK",
  "apply": "TERAPKAN",
  "useSpatialFilter": "Gunakan filter spasial untuk membatasi fitur",
  "useCurrentMapExtent": "Hanya fitur yang memotong area peta saat ini",
  "drawGraphicOnMap": "Hanya fitur yang memotong area yang telah ditentukan pengguna",
  "chartResults": "Hasil Grafik",
  "clearResults": "Kosongkan Hasil",
  "noPermissionsMsg": "Anda tidak memiliki izin untuk mengakses layanan ini.",
  "specifySpatialFilterMsg": "Tentukan filter spasial untuk tugas ini.",
  "queryError": "Query gagal.",
  "noResults": "Fitur tidak ditemukan.",
  "category": "Kategori",
  "count": "Count",
  "label": "Label",
  "horizontalAxis": "Sumbu Horizontal",
  "verticalAxis": "Sumbu Vertikal",
  "dataLabels": "Label Data",
  "color": "Warna",
  "colorful": "Penuh warna",
  "monochromatic": "Monokromatik",
  "tasks": "Tugas",
  "results": "Hasil",
  "applySpatialFilterToLimitResults": "Terapkan filter spasial untuk membatasi hasil",
  "useCurrentExtentTip": "Sebagian atau sepenuhnya berada dalam jangkauan peta saat ini",
  "useDrawGraphicTip": "Sebagian atau sepenuhnya berada dalam bentuk yang digambarkan pada peta",
  "useFeaturesTip": "Berdasarkan lokasinya yang relatif terhadap fitur di layer lainnya",
  "noSpatialLimitTip": "Jangan membatasi hasil secara spasial",
  "applySearchDistance": "Terapkan jarak pencarian",
  "spatialRelationship": "Hubungan Spasial",
  "relatedLayer": "Layer Terkait",
  "clear": "Kosongkan",
  "bufferDistance": "Jarak Buffer",
  "miles": "Mil",
  "kilometers": "Kilometer",
  "feet": "Kaki",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Mil Laut",
  "back": "Kembali",
  "execute": "Jalankan",
  "enlarge": "Perbesar",
  "setting": "Pengaturan"
});