define({
  "_widgetLabel": "Smart redigering",
  "_featureAction_SmartEditor": "Smart redigering",
  "noEditPrivileges": "Kontoen har ikke rettigheter til å opprette eller endre data.",
  "widgetActive": "Aktiv",
  "widgetNotActive": "Ikke aktiv",
  "pressStr": "Trykk på ",
  "ctrlStr": " CTRL ",
  "snapStr": " for å aktivere festing",
  "noAvailableTempaltes": "Ingen tilgjengelige maler",
  "editorCache": " - Redigeringsbuffer",
  "presetFieldAlias": "Felt",
  "presetValue": "Forhåndsinnstilt verdi",
  "usePresetValues": " Bruk forhåndsinnstilte verdier (kun nye geoobjekter)",
  "editGeometry": " Rediger geometri",
  "savePromptTitle": "Lagre geoobjekt",
  "savePrompt": "Vil du lagre gjeldende geoobjekt?",
  "deletePromptTitle": "Slett geoobjekt",
  "deleteAttachment": "Slett vedlegg",
  "deletePrompt": "Er du sikker på at du vil slette det valgte geoobjektet?",
  "attachmentLoadingError": "Feil under opplasting av vedlegg",
  "attachmentSaveDeleteWarning": "Advarsel: Endringer i vedlegg lagres automatisk",
  "autoSaveEdits": "Lagrer nytt geoobjekt automatisk",
  "addNewFeature": "Opprett nytt geoobjekt",
  "featureCreationFailedMsg": "Kan ikke opprette ny post / nytt geoobjekt",
  "relatedItemTitle": "Relatert tabell/lag",
  "relatedFeatureCount": "${layerTitle} med ${featureCount} geoobjekter",
  "createNewFeatureLabel": "Opprett nytt geoobjekt for ${layerTitle}",
  "invalidRelationShipMsg": "Kontroller at feltet for primærnøkkel: '${parentKeyField}' inneholder en gyldig verdi",
  "pendingFeatureSaveMsg": "Lagre geoobjektsredigeringene før du oppretter et relatert geoobjekt.",
  "attachmentsRequiredMsg": "(*) Vedlegg er obligatorisk.",
  "coordinatePopupTitle": "Flytt geoobjekt til XY-posisjonen",
  "coordinatesSelectTitle": "Koordinatsystem:",
  "mapSpecialReferenceDropdownOption": "Kartets romlige referanse",
  "latLongDropdownOption": "Lengdegrad/breddegrad",
  "xAttributeTextBoxLabel": "X-koordinat:",
  "yAttributeTextBoxLabel": "Y-koordinat:",
  "latitudeTextBoxLabel": "Breddegrad:",
  "longitudeTextBoxLabel": "Lengdegrad:",
  "presetGroupFieldsLabel": "${groupName} blir brukt på følgende lagfelt:",
  "presetGroupNoFieldsLabel": "${groupName} har ingen tilknyttede felt",
  "groupInfoLabel": "Gruppeinformasjon for ${groupName}",
  "editGroupInfoIcon": "Rediger gruppeverdi for ${groupName}",
  "filterEditor": {
    "all": "Alle",
    "noAvailableTempaltes": "Ingen tilgjengelige maler",
    "searchTemplates": "Søk i maler",
    "filterLayerLabel": "Filtrer kartlag"
  },
  "invalidConfiguration": "Widgeten er ikke konfigurert eller lagene i konfigurasjonen finnes ikke i kartet lenger. Åpne appen i byggemodus, og konfigurer widgeten på nytt.",
  "geometryServiceURLNotFoundMSG": "Kan ikke hente URL for geometritjeneste",
  "clearSelection": "Tøm",
  "refreshAttributes": "Oppdater geoobjektattributter",
  "automaticAttributeUpdatesOn": "Oppdater geoobjektattributter automatisk: PÅ",
  "automaticAttributeUpdatesOff": "Oppdater geoobjektattributter automatisk: AV",
  "moveSelectedFeatureToGPS": "Flytt det valgte geoobjektet til gjeldende GPS-posisjon",
  "moveSelectedFeatureToXY": "Flytt det valgte geoobjektet til XY-posisjonen",
  "mapNavigationLocked": "Kartnavigering: Låst",
  "mapNavigationUnLocked": "Kartnavigering: Ulåst",
  "copyFeatures": {
    "title": "Kopier geoobjekter",
    "createFeatures": "Opprett geoobjekter",
    "createSingleFeature": "Opprett ett geoobjekt med flerdelt geometri",
    "noFeaturesSelectedMessage": "Ingen geoobjekter valgt",
    "selectFeatureToCopyMessage": "Velg geoobjekter som skal kopieres.",
    "multipleFeatureSaveWarning": "Merk: Hvis du oppretter flere geoobjekter med kopifunksjonen, lagres alle geoobjektene umiddelbart"
  },
  "addingFeatureError": "Feil under tillegging av valgte geoobjekter i laget. Prøv på nytt.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' geoobjekter ble ikke kopiert.",
  "selectingFeatureError": "Feil under valg av geoobjekter i laget. Prøv på nytt.",
  "customSelectOptionLabel": "Velg geoobjekter som skal kopieres",
  "noFeatureSelectedMessage": "Ingen geoobjekter er valgt.",
  "multipleFeatureSaveMessage": "Alle geoobjektene blir lagret umiddelbart. Vil du fortsette?",
  "relativeDates": {
    "dateTypeLabel": "Datotype",
    "valueLabel": "Verdi",
    "fixed": "Fast",
    "current": "Gjeldende",
    "past": "Tidligere",
    "future": "Fremtidig",
    "popupTitle": "Velg verdi",
    "hintForFixedDateType": "Hint: Angitt dato og klokkeslett brukes som forhåndsinnstilt standardverdi.",
    "hintForCurrentDateType": "Hint: Gjeldende dato og klokkeslett brukes som forhåndsinnstilt standardverdi.",
    "hintForPastDateType": "Hint:  Den angitte verdien trekkes fra gjeldende dato og klokkeslett for standardverdien for forhåndsinnstillingen.",
    "hintForFutureDateType": "Hint: Den angitte verdien legges til gjeldende dato og klokkeslett for standardverdien for forhåndsinnstillingen.",
    "noDateDefinedTooltip": "Ingen dato angitt",
    "relativeDateWarning": "Det må angis en verdi for dato og klokkeslett for å kunne lagre standardverdien for forhåndsinnstilling."
  }
});