define({
  "_widgetLabel": "Smart Editor",
  "_featureAction_SmartEditor": "Smart Editor",
  "noEditPrivileges": "L'account non dispone dell'autorizzazione per creare o modificare dati.",
  "widgetActive": "Attivo",
  "widgetNotActive": "Non attiva",
  "pressStr": "Premere ",
  "ctrlStr": " CTRL ",
  "snapStr": " per abilitare lo snap",
  "noAvailableTempaltes": "Nessun modello disponibile",
  "editorCache": " - Cache editor",
  "presetFieldAlias": "Campo",
  "presetValue": "Valore preimpostato",
  "usePresetValues": " Utilizza valori preimpostati (Solo nuove feature)",
  "editGeometry": " Modifica geometria",
  "savePromptTitle": "Salva feature",
  "savePrompt": "Salvare la feature corrente?",
  "deletePromptTitle": "Elimina feature",
  "deletePrompt": "Eliminare la feature selezionata?",
  "attachmentLoadingError": "Errore durante il caricamento degli allegati",
  "attachmentSaveDeleteWarning": "Avviso: le modifiche agli allegati non vengono salvate automaticamente",
  "autoSaveEdits": "Salva automaticamente nuove feature",
  "addNewFeature": "Crea nuova feature",
  "featureCreationFailedMsg": "Impossibile creare nuovo record/feature",
  "relatedItemTitle": "Tabella/layer correlato",
  "invalidRelationShipMsg": "Verificare che il campo della chiave primaria: '${parentKeyField}' contenga un valore valido",
  "pendingFeatureSaveMsg": "Salvare le modifiche apportate alla feature prima di creare una feature correlata.",
  "attachmentsRequiredMsg": "(*) Allegati richiesti.",
  "coordinatePopupTitle": "Sposta feature in posizione XY",
  "coordinatesSelectTitle": "Sistema di coordinate:",
  "mapSpecialReferenceDropdownOption": "Riferimento spaziale della mappa",
  "latLongDropdownOption": "Latitudine/Longitudine",
  "xAttributeTextBoxLabel": "Coordinate X:",
  "yAttributeTextBoxLabel": "Coordinate Y:",
  "latitudeTextBoxLabel": "Latitudine:",
  "longitudeTextBoxLabel": "Longitudine:",
  "filterEditor": {
    "all": "Tutto",
    "noAvailableTempaltes": "Nessun modello disponibile",
    "searchTemplates": "Cerca modelli"
  },
  "invalidConfiguration": "Il widget non è configurato o i layer nella configurazione non sono più presenti nella mappa. Aprire l'app nella modalità generatore e riconfigurare il widget.",
  "geometryServiceURLNotFoundMSG": "Impossibile ottenere l'URL del servizio geometria",
  "clearSelection": "Cancellare",
  "refreshAttributes": "Aggiorna attributi feature",
  "automaticAttributeUpdatesOn": "Aggiorna automaticamente attributi delle feature: ON",
  "automaticAttributeUpdatesOff": "Aggiorna automaticamente attributi delle feature: OFF",
  "moveSelectedFeatureToGPS": "Sposta feature selezionata nella posizione GPS attuale",
  "moveSelectedFeatureToXY": "Sposta feature selezionata in posizione XY",
  "mapNavigationLocked": "Navigazione mappa: bloccata",
  "mapNavigationUnLocked": "Navigazione mappa: sbloccata",
  "copyFeatures": {
    "title": "Copia Feature",
    "createFeatures": "Crea feature",
    "createSingleFeature": "Crea 1 feature multi-geometria",
    "noFeaturesSelectedMessage": "Nessuna feature selezionata",
    "selectFeatureToCopyMessage": "Selezionare le feature da copiare."
  },
  "addingFeatureError": "Errore durante l'aggiunta di feature selezionate nel layer. Riprovare.",
  "addingFeatureErrorCount": "Feature '${copyFeatureErrorCount}' non copiate.",
  "selectingFeatureError": "Errore durante la selezione di feature nel layer. Riprovare.",
  "customSelectOptionLabel": "Seleziona feature da copiare",
  "noFeatureSelectedMessage": "Nessuna feature selezionata.",
  "multipleFeatureSaveMessage": "Verranno salvate immediatamente tutte le feature. Continuare?"
});