define({
  "chartSettingLabel": "إعدادات الدردشة",
  "addNewLabel": "إضافة جديد",
  "generalSettingLabel": "الإعدادات العامة",
  "layerChooser": {
    "title": "حدد طبقة لتخطيطها",
    "selectPolygonLayerLabel": "حدد الطبقة",
    "selectPolygonLayerHintText": "تلميح: إذا قمت بتكوين مخططات متعددة، يجب أن تكون الطبقات بنفس نوع الشكل الهندسي",
    "selectRelatedTableLayerLabel": "حدد جدولاً متصلا بطبقة",
    "selectRelatedTableLayerHintText": "تلميح: يتم عرض الجداول ذات الحقول الرقمية فقط",
    "errorInSelectingPolygonLayer": "يرجى تحديد مضلع بطبقة نقطية ذات صلة.",
    "errorInSelectingRelatedLayer": "يرجى تحديد طبقة/جدول صحيح ذو/ذات صلة بالطبقة.",
    "polygonLayerNotHavingRelationships": "الطبقة المحددة لا تحتوي على أي طبقة/جدول ذات/ذي صلة."
  },
  "ChartSetting": {
    "sectionTitle": "عنوان المقطع",
    "sectionTitleHintText": "تلميح: يُعرَض في عنوان رأس صفحة القسم",
    "chartTitle": "عنوان المخطط",
    "chartTitleHintText": "تلميح: معروضة مُتمركزة أعلى المخطط",
    "chartDescription": "الوصف",
    "chartDescriptionHintText": "تلميح: معروضة أدنى المخطط",
    "chartType": "نوع المخطط",
    "barChart": "المخطط الشريطي",
    "pieChart": "المخطط الدائري",
    "polarChart": "مخطط قطبي",
    "dataSeriesField": "حقل سلسلة البيانات",
    "labelField": "حقل التسمية",
    "chartColor": "لون المخطط",
    "singleColor": "لون واحد",
    "colorByTheme": "اللون بواسطة النّسُق",
    "colorByFieldValue": "اللون بواسطة قيمة الحقل",
    "xAxisTitle": "عنوان محور X",
    "xAxisHintText": "تلميح: عنوان محور X",
    "yAxisTitle": "عنوان محور Y",
    "yAxisHintText": "تلميح: عنوان محور Y",
    "fieldColorLabel": "التسمية",
    "fieldColorColor": "لون",
    "defaultFieldSelectLabel": "تحديد",
    "errMsgFieldValuesNotFound": "يتعذر العثور على قيم الحقل المحدد",
    "errMsgSectionTitle": "يرجى إدخال عنوان القسم",
    "errMsgFieldByValue": "يرجى تحديد قيمة الحقل",
    "settingTabTitle": "إعداد",
    "layoutTabTitle": "تخطيط",
    "polarChartSelectFieldsHintText": "تلميح: حدد حقولاً لإنشاء مخطط قطبي",
    "visibilityText": "إمكانية الرؤية",
    "fieldNameText": "اسم الحقل",
    "aliasNameText": "الاسم المستعار",
    "errMsgPolarFieldsRequired": "يرجى تحديد ثلاثة حقول أو أكثر لإنشاء مخطط قطبي",
    "polarChartPolygonFillLabel": "تعبئة المُضلع",
    "polarChartPolygonFillHintText": "تلميح: حدد خانة الاختيار لعرض تعبئة المضلع في الشكل البياني القطبي",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "صحراء",
      "themeDistinctive": "مُميز",
      "themeDollar": "دولار",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "تناغُم",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "إيرلندا",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "مستنقع",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "إعدادات عامة",
    "locationSymbolLabel": "رمز الموقع البياني",
    "locationSymbolHintText": "تلميح: يُستخدم لعرض رمز العنوان والموقع الذي تم النقر عليه",
    "refreshIntervalLabel": "تحديث الفاصل",
    "refreshIntervalHintText": "تلميح: يُستخدم لتحديث المخططات بناءً على هذا الفاصل. حدد قيمة بين 1 و1440 دقيقة",
    "errMsgRefreshInterval": "يرجى تحديد فاصل التحديث بين 0 و1440 دقيقة",
    "symbolPickerPreviewText": "معاينة:"
  }
});