define({
  "addTaskTip": "Dodaj vidžetu jedan ili više filtera i konfiguriši parametre za svaki od njih.",
  "enableMapFilter": "Uklonite unapred podešeni filter slojeva sa mape.",
  "newFilter": "Novi filter",
  "filterExpression": "Izraz filtera",
  "layerDefaultSymbolTip": "Koristi podrazumevani simbol sloja",
  "uploadImage": "Otpremi snimak",
  "selectLayerTip": "Izaberite sloj.",
  "setTitleTip": "Postavite naslov.",
  "noTasksTip": "Nema konfigurisanih filtera. Kliknite na \"${newFilter}\" da biste dodali novi.",
  "collapseFiltersTip": "Skupi izraze filtera (ako postoje) kada je vidžet otvoren",
  "zoomtoTip": "Zumiraj na sloj kada se primeni filter",
  "groupByLayerTip": "Grupiši filtere prema sloju",
  "autoApplyWhenValueInput": "Automatski primeni ovaj filter nakon što je vrednost uneta",
  "autoApplyWhenWidgetOpen": "Primeni ovaj filter kada je vidžet otvoren",
  "info": "Informacije",
  "expressions": "Izrazi",
  "allowCustom": "Dozvoli kreiranje prilagođenih filtera",
  "matchMsgSetAll": "Prikaži geoobjekte koji se podudaraju sa svim filterima",
  "matchMsgSetAny": "Prikaži geoobjekte koji se podudaraju sa bilo kojim filterom"
});