define({
  "_widgetLabel": "Умный редактор",
  "_featureAction_SmartEditor": "Умный редактор",
  "noEditPrivileges": "У вашей учетной записи нет прав на создание или изменение данных.",
  "widgetActive": "Активный",
  "widgetNotActive": "Неактивно",
  "pressStr": "Нажмите ",
  "ctrlStr": " CTRL ",
  "snapStr": " чтобы включить замыкание",
  "noAvailableTempaltes": "Нет доступных шаблонов",
  "editorCache": " – Кэш редактора",
  "presetFieldAlias": "Поле",
  "presetValue": "Заданное значение",
  "usePresetValues": " Использовать заданные значения (только для новых объектов)",
  "editGeometry": " Редактировать геометрию",
  "savePromptTitle": "Сохранить объект",
  "savePrompt": "Вы хотите сохранить текущий объект?",
  "deletePromptTitle": "Удалить объект",
  "deletePrompt": "Действительно удалить выбранный объект?",
  "attachmentLoadingError": "Ошибка загрузки вложений",
  "attachmentSaveDeleteWarning": "Внимание: изменения вложений сохраняются автоматически",
  "autoSaveEdits": "Сохраняет новые объекты автоматически",
  "addNewFeature": "Создать новый объект",
  "featureCreationFailedMsg": "Невозможно создать новую запись/объект",
  "relatedItemTitle": "Связанная таблица/слой",
  "invalidRelationShipMsg": "Проверьте, что поле первичного ключа: '${parentKeyField}' имеет корректное значение",
  "pendingFeatureSaveMsg": "Сохраните изменения объекта для создания связанного объекта.",
  "attachmentsRequiredMsg": "(*) Необходимы вложения.",
  "coordinatePopupTitle": "Переместить объект в местоположение XY",
  "coordinatesSelectTitle": "Система координат:",
  "mapSpecialReferenceDropdownOption": "Пространственная привязка карты",
  "latLongDropdownOption": "Широта/Долгота",
  "xAttributeTextBoxLabel": "X-координата:",
  "yAttributeTextBoxLabel": "Y-координата:",
  "latitudeTextBoxLabel": "Широта:",
  "longitudeTextBoxLabel": "Долгота:",
  "filterEditor": {
    "all": "Все",
    "noAvailableTempaltes": "Нет доступных шаблонов",
    "searchTemplates": "Поиск шаблонов"
  },
  "invalidConfiguration": "Виджет не настроен, или на карте больше нет слоёв из конфигурации. Откройте приложение в режиме конструктора и настройте виджет.",
  "geometryServiceURLNotFoundMSG": "Невозможно получить URL сервиса геометрии",
  "clearSelection": "Сбросить",
  "refreshAttributes": "Обновить атрибуты объекта",
  "automaticAttributeUpdatesOn": "Автоматически обновлять атрибуты объекта: ВКЛ",
  "automaticAttributeUpdatesOff": "Автоматически обновлять атрибуты объекта: ВЫКЛ",
  "moveSelectedFeatureToGPS": "Переместить выбранный объект в текущее местоположение GPS",
  "moveSelectedFeatureToXY": "Переместить выбранный объект в местоположение XY",
  "mapNavigationLocked": "Навигация по карте: Блокирована",
  "mapNavigationUnLocked": "Навигация по карте: Разблокирована"
});