define({
  "_widgetLabel": "المحرر الذكي",
  "_featureAction_SmartEditor": "المحرر الذكي",
  "noEditPrivileges": "لا يحتوي حسابك على أذونات لإنشاء أو تعديل البيانات.",
  "widgetActive": "نشط",
  "widgetNotActive": "غير نشط",
  "pressStr": "اضغط ",
  "ctrlStr": " CTRL ",
  "snapStr": " لتمكين الالتقاط",
  "noAvailableTempaltes": "لا توجد أي قوالب",
  "editorCache": " - ذاكرة التخزين المؤقت للمحرر",
  "presetFieldAlias": "حقل",
  "presetValue": "قيمة معينة مُسبقًا",
  "usePresetValues": " استخدم قيمة مُعينة مُسبقًا (معالم جديد فقط)",
  "editGeometry": " تحرير الشكل الهندسي",
  "savePromptTitle": "حفظ المعلم",
  "savePrompt": "هل تريد حفظ المعلم الحالي؟",
  "deletePromptTitle": "حذف المعلم",
  "deleteAttachment": "حذف المرفق",
  "deletePrompt": "هل أنت متأكد من رغبتك في حذف المعالم المحددة؟",
  "attachmentLoadingError": "خطأ في تحميل المرفقات",
  "attachmentSaveDeleteWarning": "تحذير: يتم حفظ التغييرات على المرفقات تلقائيًا",
  "autoSaveEdits": "يحفظ المعالم الجديدة تلقائياً",
  "addNewFeature": "إنشاء معلم جديد",
  "featureCreationFailedMsg": "يتعذر إنشاء سجل/معلم جديد",
  "relatedItemTitle": "الطبقة/الجدول ذي الصلة",
  "relatedFeatureCount": "${layerTitle} مع ${featureCount} من المعالم",
  "createNewFeatureLabel": "إنشاء معلم جديد لـ ${layerTitle}",
  "invalidRelationShipMsg": "يرجى التأكد من أن حقل المفتاح الرئيسي '${parentKeyField}' يحتوي على قيمة صحيحة",
  "pendingFeatureSaveMsg": "يرجى إدخال عمليات تحرير المعلم قبل إنشاء معلم ذي صلة.",
  "attachmentsRequiredMsg": "(*) المرفقات مطلوبة.",
  "coordinatePopupTitle": "تحريك معلم إلى موقع XY",
  "coordinatesSelectTitle": "نظام الإحداثيات:",
  "mapSpecialReferenceDropdownOption": "الإسناد المكاني للخريطة",
  "latLongDropdownOption": "دائرة العرض/خط الطول",
  "xAttributeTextBoxLabel": "إحداثيات X:",
  "yAttributeTextBoxLabel": "أحداثيات Y:",
  "latitudeTextBoxLabel": "خط عرض:",
  "longitudeTextBoxLabel": "خط طول:",
  "presetGroupFieldsLabel": "ستُطبق \"${groupName}\" على حقول الطبقة التالية:",
  "presetGroupNoFieldsLabel": "لا تتضمن \"${groupName}\" أي حقول مرتبطة",
  "groupInfoLabel": "معلومات مجموعة \"${groupName}\"",
  "editGroupInfoIcon": "تحرير قيمة مجموعة ${groupName}",
  "filterEditor": {
    "all": "الكل",
    "noAvailableTempaltes": "لا توجد أي قوالب",
    "searchTemplates": "البحث في القوالب",
    "filterLayerLabel": "تصفية الطبقات"
  },
  "invalidConfiguration": "لم يتم تكوين عنصر واجهة المستخدم أو أن الطبقات التي توجد في التكوين لم تُعد موجودة في الخريطة. يرجى فتح التطبيق في وضع المُنشئ وإعادة تكوين عنصر واجهة المستخدم.",
  "geometryServiceURLNotFoundMSG": "يتعذر الحصول على عنوان URL لخدمة الشكل الهندسي",
  "clearSelection": "مسح",
  "refreshAttributes": "تحديث البيانات الجدولية للمعلم",
  "automaticAttributeUpdatesOn": "تحديث البيانات الجدولية للمعلم تلقائياً: تشغيل",
  "automaticAttributeUpdatesOff": "تحديث البيانات الجدولية للمعلم تلقائياً: إيقاف",
  "moveSelectedFeatureToGPS": "تحريك المعلم المحدد إلى موقع GPS الحالي",
  "moveSelectedFeatureToXY": "تحريك المعلم المحدد إلى موقع XY",
  "mapNavigationLocked": "تنقل الخريطة: مقفول",
  "mapNavigationUnLocked": "تنقل الخريطة: مفتوح",
  "copyFeatures": {
    "title": "نسخ المعالم",
    "createFeatures": "إنشاء معالم",
    "createSingleFeature": "إنشاء معلم واحد متعدد الأشكال الهندسية",
    "noFeaturesSelectedMessage": "لا توجد معالم مُحددة",
    "selectFeatureToCopyMessage": "يرجى تحديد المعالم المطلوب نسخها.",
    "multipleFeatureSaveWarning": "ملاحظة: سيحفظ إنشاء المعالم المتعددة باستخدام معلم نسخ كل المعالم على الفور"
  },
  "addingFeatureError": "حدث خطأ أثناء إضافة المعالم المحددة في الطبقة. الرجاء إعادة المحاولة مرة أخرى.",
  "addingFeatureErrorCount": "فشل معالم '${copyFeatureErrorCount}' التي سيتم نسخها.",
  "selectingFeatureError": "حدث خطأ أثناء تحديد المعالم في الطبقة. الرجاء إعادة المحاولة مرة أخرى.",
  "customSelectOptionLabel": "تحديد المعالم المطلوب نسخها",
  "noFeatureSelectedMessage": "لا توجد معالم مُحددة.",
  "multipleFeatureSaveMessage": "سيتم حفظ جميع المعالم على الفور. هل تود المتابعة؟",
  "relativeDates": {
    "dateTypeLabel": "نوع التاريخ",
    "valueLabel": "قيمة",
    "fixed": "ثابت",
    "current": "حالي",
    "past": "ماضي",
    "future": "مستقبل",
    "popupTitle": "تحديد قيمة",
    "hintForFixedDateType": "تلميح: سيُستخدم التاريخ والوقت المحددين كقيمة إعداد مسبق افتراضية.",
    "hintForCurrentDateType": "تلميح: سيُستخدم التاريخ والوقت الحاليين كقيمة إعداد مسبق افتراضية.",
    "hintForPastDateType": "تلميح: ستطرح القيمة المحددة من التاريخ والوقت الحاليين للقيمة الافتراضية للإعداد المسبق.",
    "hintForFutureDateType": "تلميح: ستضاف القيمة المحددة إلى التاريخ والوقت الحاليين للقيمة الافتراضية للإعداد المسبق.",
    "noDateDefinedTooltip": "لا توجد بيانات محددة",
    "relativeDateWarning": "يجب تحديد قيمة للتاريخ أو الوقت لتتمكن من حفظ القيمة الافتراضية المحددة مسبقًا."
  }
});