define({
  "_widgetLabel": "Consapevolezza situazionale",
  "locate_incident": "Individua incidente",
  "reverse_geocoded_address": "Indirizzo più vicino",
  "reverse_geocoded_error": "Non disponibile",
  "now": "ORA",
  "wind": "VENTO",
  "SUN": "DOM",
  "MON": "LUN",
  "TUE": "MAR",
  "WED": "MER",
  "THU": "GIO",
  "FRI": "VEN",
  "SAT": "SAB",
  "actionLabel": "Imposta posizione",
  "drawPoint": "Disegna punto",
  "drawLine": "Disegna linea",
  "drawPolygon": "Disegna poligono",
  "saveIncident": "Salva",
  "clearIncident": "Ricomincia",
  "noFeaturesFound": "Nessuna feature trovata.",
  "downloadCSV": "Scarica",
  "sum": "Somma",
  "min": "Minima",
  "max": "Massima",
  "avg": "Mediocre",
  "count": "COUNT",
  "area": "AREA",
  "length": "LENGTH",
  "update_btn": "Completato",
  "delete_btn": "Elimina",
  "get_directions": "Ottieni indicazioni",
  "incident": "Richiesta di assistenza",
  "incidents": "Incidenti",
  "buffer": "Distanza di buffer",
  "buffers": "Buffer",
  "weather": "Meteo",
  "poweredBy": "Basato su",
  "_featureAction_ActionLabel": "Imposta posizione",
  "_featureAction_AddRemoveActionLabel": "Aggiungi/rimuovi posizione",
  "snapshot": "Cartella SnapShot creata da ID app:",
  "user_credentials": "L'utente non dispone di privilegi validi.",
  "snapshot_complete": "Creazione dello snapshot completata.",
  "snapshot_failed": "Impossibile creare snapshot.",
  "notPolySnapShot": "Specificare una distanza di buffer prima di creare uno snapshot.",
  "notValidDownload": "Nessun risultato valido da scaricare.",
  "snapshot_append": "Snapshot",
  "of_append": "di",
  "layer_append": "layer",
  "downloadAll": "Scarica tutto",
  "createSnapshot": "Crea snapshot",
  "calculated_results": "Informazioni di riepilogo",
  "closest": "Feature più vicina",
  "proximity": "Prossimità",
  "summary": "Riepilogo",
  "groupedSummary": "Conteggi raggruppati",
  "_count": "Conteggio",
  "utc": "UTC",
  "approximate": "approssimativo",
  "snapshot_name": "Imposta nome snapshot",
  "invalid_snapshot_name": "Nome snapshot non valido."
});