define({
  "_widgetLabel": "Situationsopmærksomhed",
  "locate_incident": "Find hændelse",
  "reverse_geocoded_address": "Nærmeste adresse",
  "reverse_geocoded_error": "Not available",
  "actionLabel": "Angiv placering",
  "drawPoint": "Tegn punkt",
  "drawLine": "Tegn linje",
  "drawPolygon": "Tegn polygon",
  "saveIncident": "Gem",
  "clearIncident": "Start forfra",
  "noFeaturesFound": "Ingen objekte fundet.",
  "downloadCSV": "Hent",
  "sum": "Sum",
  "min": "Minimum",
  "max": "Maksimum",
  "avg": "Gennemsnit",
  "count": "OPTÆLLING",
  "area": "OMRÅDE",
  "length": "LÆNGDE",
  "update_btn": "Udført",
  "delete_btn": "Slet",
  "get_directions": "Hent kørselsvejledning",
  "incident": "Hændelse",
  "incidents": "Hændelser",
  "buffer": "Buffer",
  "buffers": "Buffere",
  "_featureAction_ActionLabel": "Angiv placering",
  "_featureAction_AddRemoveActionLabel": "Tilføj/fjern position",
  "snapshot": "SnapShot-mappe oprettet af App-ID:",
  "user_credentials": "Brugeren har ikke gyldige rettigheder.",
  "notPolySnapShot": "Angiv en bufferafstand, før du opretter et snapshot.",
  "notPolyReport": "Ingen gyldige resultater at tilføje til rapporten.",
  "notValidDownload": "Ingen gyldige resultater at downloade.",
  "of_append": "af",
  "layer_append": "lag",
  "downloadAll": "Hent alle",
  "createSnapshot": "Opret snapshot",
  "createReport": "Opret rapport",
  "calculated_results": "Oversigtsoplysninger",
  "closest": "Nærmeste objekt",
  "proximity": "Nærhed",
  "summary": "Resumé",
  "groupedSummary": "Grupperede optællinger",
  "_count": "Tælling",
  "approximate": "cirka",
  "snapshot_name": "Angiv Snapshot-egenskaber",
  "report_name": "Angiv Rapport-egenskaber",
  "invalid_snapshot_name": "Ugyldigt snapshot-navn.",
  "invalid_report_name": "Ugyldig rapporttitel.",
  "orientation": "Retning",
  "pageSize": "Sidestørrelse",
  "comments": "Kommentarer",
  "choose_group": "Grupper",
  "forecast": "Prognose",
  "select_group": "Vælg gruppe",
  "select_group_instruction": "Snapshot'et vil blive oprettet og delt med den valgte gruppe",
  "information_append": " Oplysninger",
  "distance": "DISTANCE",
  "buffer_invalid": "Skriv et gyldigt tal mellem ${min} og ${max}",
  "layerNotAvalible": "Lag ikke fundet",
  "missingLayer": "Navn: ${name}",
  "missingLayerHint": "Ét eller flere lag, der henvises til i denne konfiguration, er ikke tilgængelige lige nu."
});