define({
  "feedbackStyleLabel": "Stil povratnih informacija o udaljenosti i smjeru",
  "showTabLabel": "Prikaži karticu",
  "feedbackShapeLabel": "Oblik povratnih informacija",
  "lineColorLabel": "Boja linija",
  "lineWidthLabel": "Širina linije",
  "feedbackLabel": "Oznaka povratnih informacija",
  "textColorLabel": "Boja teksta",
  "textSizeLabel": "Veličina teksta",
  "tabErrorMessage": "Widget se mora konfigurirati s barem jednom prikazanom karticom",
  "lineLabel": "Linija",
  "circleLabel": "Krug",
  "ellipseLabel": "Elipsa",
  "ringsLabel": "Prsteni",
  "transparency": "Prozirnost",
  "ddFeedbackStyleTabLabel": "Simbologija",
  "miscellaneousTabLabel": "Razno",
  "operationalLineLayerSelectLabel": "Odaberite sloj operativne polilinije za rezultate linije i rezultata",
  "operationalPolygonLayerSelectLabel": "Odaberite sloj operativnog poligona za rezultate kruga i elipse",
  "helpIconPolylineTooltip": "Operativni sloj popunjen je slojevima polilinijskog tipa geometrije iz trenutačne web-karte.",
  "helpIconPolygonTooltip": "Operativni sloj popunjen je slojevima poligonalnog tipa geometrije iz trenutačne web-karte."
});