define({
  "showArcgisBasemaps": "Sisällytä portaalin taustakartat",
  "add": "Lisää uusi taustakartta napsauttamalla",
  "edit": "Ominaisuudet",
  "titlePH": "Taustakartan otsikko",
  "thumbnailHint": "Päivitä napsauttamalla kuvaa",
  "urlPH": "Karttatason URL-osoite",
  "addlayer": "Lisää taustakartta",
  "warning": "Virheellinen lähtöaineisto",
  "save": "Takaisin ja tallenna",
  "back": "Takaisin ja peruuta",
  "addUrl": "Lisää URL-osoite",
  "autoCheck": "Automaattinen tarkistus",
  "checking": "Tarkistetaan...",
  "result": "Tallennus onnistui",
  "spError": "Kaikilla galleriaan lisätyillä taustakartoilla täytyy olla sama koordinaattijärjestelmä.",
  "invalidTitle1": "Taustakartta '",
  "invalidTitle2": "' on jo olemassa. Valitse toinen otsikko.",
  "invalidBasemapUrl1": "Tämän tyyppistä karttatasoa ei voi käyttää taustakarttana.",
  "invalidBasemapUrl2": "Lisättävän taustakartan koordinaattijärjestelmä ei ole sama kuin nykyisessä kartassa.",
  "addBaselayer": "Lisää taustakarttataso"
});