define({
  "symbolologyTabLabel": "Configura la simbologia",
  "facilitiesDescription": "Capes d'installacions",
  "demographicsDescription": "Capa de demografia",
  "settingsTitle": "Configuració",
  "spillLocationLabel": "Ubicació de vessament",
  "spillLocationButtonLabel": "Configura la ubicació de vessament",
  "IISettingsLabel": "Zona d'aïllament inicial",
  "IIButtonLabel": "Configura l'aïllament inicial",
  "PASettingsLabel": "Zona d'acció de protecció",
  "PAButtonLabel": "Configura l'acció de protecció",
  "downwindSettingsLabel": "Zona a favor del vent",
  "downwindButtonLabel": "Configura les opcions a favor del vent",
  "fireSettingsLabel": "Zona d'aïllament d'incendis",
  "fireButtonLabel": "Configura l'aïllament d'incendis",
  "bleveSettingsLabel": "Zona d'aïllament de BLEVE",
  "bleveButtonLabel": "Configura les opcions de BLEVE",
  "transparency": "Transparència",
  "outline": "Contorn",
  "fill": "Emplenament (el color només s'aplica quan l'estil està definit com a cos geomètric)",
  "style": "Estil",
  "selectOpLayerLabel": "Seleccioneu una capa operativa per als resultats",
  "selectDefaultMeasurementLabel": "Seleccioneu una unitat de mesura per defecte",
  "helpIconTooltip": "La llista de capes operatives s'emplena amb capes del mapa web actual amb el tipus de geometria de polígon.",
  "colorPicker": "Selector de color",
  "lineStyles": {
    "esriSLSDash": "Guió",
    "esriSLSDashDot": "Guió punt",
    "esriSLSDashDotDot": "Guió punt punt",
    "esriSLSDot": "Punt",
    "esriSLSLongDash": "Guió llarg",
    "esriSLSLongDashDot": "Guió llarg punt",
    "esriSLSNull": "Nul",
    "esriSLSShortDash": "Guió curt",
    "esriSLSShortDashDot": "Guió curt punt",
    "esriSLSShortDashDotDot": "Guió curt punt punt",
    "esriSLSShortDot": "Punt",
    "esriSLSSolid": "Cos geomètric"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Enrere",
    "esriSFSCross": "Creu",
    "esriSFSDiagonalCross": "Diagonal",
    "esriSFSForwardDiagonal": "Endavant",
    "esriSFSHorizontal": "Horitzontal",
    "esriSFSNull": "Nul",
    "esriSFSSolid": "Cos geomètric",
    "esriSFSVertical": "Vertical"
  }
});