define({
  "_widgetLabel": "Straumēt",
  "streamControls": "Straumēšanas vadīklas",
  "streamFilter": "Filtrs",
  "startStreaming": "Sākt straumēšanu",
  "stopStreaming": "Apturēt straumēšanu",
  "streamLayers": "Straumējamie slāņi",
  "startStopStream": "Iespējot opciju Apturēt straumēšanu vai Sākt straumēšanu",
  "clearStream": "Iespējot opciju Notīrīt iepriekšējos novērojumus",
  "attributeFilter": "Aktivizēt atribūtu filtru",
  "spatialFilter": "Aktivizēt telpisko filtru",
  "configFilter": "Konfigurēt straumēšanas atribūtu filtru",
  "drawPrevious": "Iespējot opciju Zīmēt iepriekšējos novērojumus",
  "addNew": "Pievienot filtru",
  "setFilterName": "Iestatīt filtra nosaukumu",
  "filterNameExists": "Filtra nosaukums jau eksistē tabulā!",
  "invalidFilterName": "Nosaukumam jābūt vārdam, kurā ir rakstzīmes a-z, A-Z, 0-9 vai _.",
  "noFilterTip": "Nav konfigurētu filtru.",
  "addFilterFailed": "Neizdevās pievienot filtru.",
  "filterName": "Filtra nosaukums",
  "limitMapExtent": "Ierobežot novērojumus pašreizējā kartes teritorijā",
  "limitDrawExtent": "Ierobežot novērojumus lietotāja definētā teritorijā",
  "newFilter": "Jauns filtrs",
  "filterReadOnly": "No tīmekļa kartes pārmantotais filtrs ir tikai lasāms."
});