define({
  "addTaskTip": "Pripomočku dodajte enega ali več filtrov in za vsakega konfigurirajte parametre.",
  "enableMapFilter": "Odstranite prednastavljeni filter sloja s karte.",
  "newFilter": "Nov filter",
  "filterExpression": "Izraz fitra",
  "layerDefaultSymbolTip": "Uporabi privzeti simbol sloja",
  "uploadImage": "Naloži sliko",
  "selectLayerTip": "Izberite sloj.",
  "setTitleTip": "Nastavite naslov.",
  "noTasksTip": "Filtri niso konfigurirani. Kliknite »${newFilter}« za dodajanje novega.",
  "collapseFiltersTip": "Strni izraze filtra (če obstajajo), ko je pripomoček odprt",
  "zoomtoTip": "Približaj na sloj, ko je uporabljen filter",
  "groupByLayerTip": "Skupini filtre po slojih",
  "autoApplyWhenValueInput": "Po vnosu vrednosti samodejno uporabi ta filter",
  "autoApplyWhenWidgetOpen": "Ko je pripomoček odprt, uporabi ta filter",
  "info": "Informacije",
  "expressions": "Izrazi",
  "allowCustom": "Dovoli ustvarjanje filtrov po meri",
  "matchMsgSetAll": "Prikaži geoobjekte, ki se ujemajo z vsemi filtri",
  "matchMsgSetAny": "Prikaži geoobjekte, ki se ujemajo s katerim koli filtrom"
});