define({
  "_widgetLabel": "Traccia di rete",
  "_featureAction_NetworkTraceSkip": "Salta in Traccia",
  "_featureAction_NetworkTraceUnskip": "Rimuovere da posizioni di salto",
  "removedFromSkipLocations": "Rimosso da posizioni di salto",
  "alreadyRemovedFromSkipLocations": "Già rimosso da posizioni di salto",
  "locationSkipped": "Posizione saltata",
  "configError": "Widget non configurato correttamente.",
  "geometryServiceURLNotFoundMSG": "Impossibile ottenere l'URL del servizio geometria",
  "clearButtonValue": "Cancellare",
  "GPExecutionFailed": "Impossibile completare la traccia. Riprovare.",
  "backButtonValue": "Indietro",
  "exportToCSVSuccess": "Esportazione in CSV completata correttamente.",
  "lblInputLocTab": "Posizioni di input",
  "lblBlockLocTab": "Posizioni di blocco",
  "lblInputLocation": "Feature di input",
  "lblBlockLocation": "Feature di blocco",
  "lblInputLocHeader": "Posizioni di input (0)",
  "lblBlockLocHeader": "Posizioni di blocco (0)",
  "inputTabTitle": "Input",
  "outputTabTitle": "Output",
  "exportSelectAllCheckBoxLabel": "Seleziona tutto",
  "lblSkipLocHeader": "Posizioni di salto (0)",
  "lblSkipLocation": "Localizzazione",
  "lblSkipLocTab": "Posizioni di salto",
  "skipAllLocationButtonLabel": "Tutte le posizioni di salto",
  "confirmSkipAllLocationsMessage": "Verranno saltate tutte le posizioni, continuare?",
  "locationAlreadySkippedMessage": "Posizione già saltata",
  "removeAllSkipLocationLabel": "Elimina tutto",
  "newProjectOptionText": "Nuovo progetto",
  "selectProject": "Seleziona progetto",
  "saveButtonLabel": "Salva",
  "exportToCSVText": "Esporta in CSV",
  "editProjectAttributesToolTip": "Modifica gli attributi progetto",
  "projectNameLabel": "Nome progetto",
  "saveProjectPopupTitle": "Salva",
  "saveAsLabel": "Salva con nome",
  "saveChangesMsg": "Salvare le modifiche a <b>${loadProjectDropdownlabel}</b> o salvare come nuovo progetto?",
  "creatingNewProjectErrorMessage": "Errore durante la creazione di un nuovo progetto. Riprovare.",
  "projectNameFetchingErr": "Errore durante il recupero dei nomi di progetto esistenti. Riprovare.",
  "projectAttributeLoadingErr": "Errore durante il caricamento di attributi di progetto. Riprovare.",
  "attributeUpdatedMsg": "Attributi aggiornati correttamente.",
  "projectAttributeUpdatingErr": "Errore durante l'aggiornamento di attributi di progetto.",
  "loadingProjectDetailsErrorMessage": "Errore durante il recupero di flag, barriere e posizioni di salto. Riprovare.",
  "savingProjectDetailsErr": "Errore durante il salvataggio dei dettagli del progetto. Provare a salvare di nuovo il progetto.",
  "updatingOutagePolygonErr": "Errore durante l'aggiornamento del poligono di interruzione. Provare a salvare di nuovo il progetto.",
  "deletingExistingPolygonErr": "Errore durante l'eliminazione del poligono di interruzione esistente. Provare a salvare di nuovo il progetto.",
  "loadingProjectFeaturesErr": "Errore durante il caricamento di feature di progetto. Provare a caricare di nuovo il progetto.",
  "addingProjectFeaturesErr": "Errore durante l'aggiunta di feature di progetto. Provare a salvare di nuovo il progetto.",
  "deletingExistingProjectFeaturesErr": "Errore durante l'eliminazione delle feature di progetto esistenti. Provare a salvare di nuovo il progetto.",
  "projectNotFoundErr": "Progetto non trovato",
  "projectLayersNotFound": "I layer delle impostazioni di progetto configurati non sono disponibili nella mappa. Il widget verrà caricato in 'Modalità schizzo'.",
  "fetchingOutagePolygonMessage": "Errore durante il recupero del poligono di interruzione. Provare a caricare di nuovo il progetto.",
  "projectNameExistsMessage": "Nome progetto già esistente. Utilizzare un nome progetto univoco.",
  "fetchingProjectNamesErrorMessage": "Errore durante il recupero dei nomi di progetto esistenti. Provare a salvare di nuovo il progetto.",
  "enterProjectNameMessage": "Immettere il nome progetto.",
  "projectLengthErrorMessage": "Il nome progetto non può essere maggiore di",
  "gpServiceNotAccessible": "L’account non ha accesso al servizio richiesto per eseguire questa traccia.",
  "loadingClonedLayerErrorMessage": "Errore durante il caricamento del feature layer clonato. Riprovare.",
  "addingFeatureInClonedLayerError": "Errore durante l’aggiunta di grafica nel feature layer clonato. Riprovare.",
  "selectingFeatureInClonedLayerError": "Errore durante la selezione di grafica nel feature layer clonato. Riprovare.",
  "filteredProjectError": "Errore durante il controllo del recupero dei dettagli di progetto filtrati. Riprovare.",
  "filteredProjectMessage": "Gli attributi di progetto selezionati non sono disponibili a causa dei filtri applicati da mappa web o un altro widget. Cancellare i filtri e riprovare.",
  "filteredProjectLoadMessage": "Il progetto non è più disponibile. Selezionare un progetto attivo.",
  "defaultValueForRunButton": "Esegui",
  "closeButtonLabel": "Rimuovi"
});