define({
  "tabs_section_Label": "Fülek",
  "addTab": "Fül hozzáadása",
  "layerName": "Réteg",
  "layerType": "Elemzés típusa",
  "layerLabel": "Felirat",
  "actions": "Műveletek",
  "closest": "Legközelebbi vektoros elem",
  "proximity": "Közelség",
  "summary": "Összefoglalás",
  "select_lbl": "-- Kijelöl --",
  "general_setting_Label": "Általános beállítások",
  "units_text_lbl": "Távolság-mértékegységek",
  "maximum_distance_lbl": "Legközelebbi vektoros elem maximális távolsága",
  "buffer_text_lbl": "Buffer felirata",
  "buffer_lbl": "Buffer távolsága",
  "buffer_max_lbl": "Maximum buffertávolság",
  "buffer_min_lbl": "Minimum buffertávolság",
  "buffer_default_lbl": "Alapértelmezett puffertávolság",
  "not_less_than_max": "A távolságnak kisebbnek kell lennie a maximális buffertávolságnál",
  "not_between": "A távolságnak a minimális és a maximális buffertávolság között kell lennie",
  "not_more_than_min": "A távolságnak nagyobbnak kell lennie a minimális buffertávolságnál",
  "not_valid_number": "Érvényes számnak kell lennie",
  "invalid_value": "A(z) ${type} érték érvénytelen",
  "routing_checkBox": "Útvonal-megállapítás engedélyezése",
  "weather_removed_message": "Az időjárás-beállítások már nem érhetők el ehhez a widgethez.",
  "currentlySelectedLayer": "Válasszon a térképrétegekből",
  "missingTabLabel": "Legalább egy fülről hiányzik a felirat",
  "missingLayerInWebMap": "Nem találhatók operatív rétegek.",
  "selectFields": "Mezők kiválasztása",
  "addField": "Mező hozzáadása",
  "sum": "Összeg",
  "min": "Minimum",
  "max": "Maximum",
  "avg": "Átlag",
  "count": "SZÁM",
  "area": "TERÜLET",
  "length": "HOSSZ",
  "count_checkBox": "Vektoros elemek számának megjelenítése",
  "area_checkBox": "Teljes terület megjelenítése",
  "length_checkBox": "Teljes hosszúság megjelenítése",
  "max_records": "Elértük a maximális mezőértéket",
  "save_label": "Mentési opciók",
  "save_checkbox": "Mentés engedélyezése",
  "report_label": "Jelentési opciók",
  "report_checkbox": "Jelentés engedélyezése",
  "csv_label": "CSV-opciók",
  "display_label": "Megjelenítési opciók",
  "display_checkbox": "Vektoros elemek összesítésének megjelenítése",
  "setSelectionColor": "Kijelölési szín beállítása",
  "snapshot_label": "Pillanatkép beállítások",
  "snapshot_checkbox": "Pillanatkép engedélyezése",
  "must_select_template": "Válasszon ki egy szerkesztési sablont a Mentési opciók alatt.",
  "count_label": "Szám felirat",
  "area_label": "Terület felirat",
  "length_label": "Hossz felirat",
  "invalid_string_width": "Az érték túl hosszú. ",
  "layer_type_not_supported": "A rétegtípus nem támogatott",
  "groupedSummary": "Csoportosított számok",
  "groupByField": "Csoportosítás mezők szerint",
  "labelType": "Felirat hozzáfűzése",
  "prefix": "Előtagként",
  "suffix": "Utótagként",
  "need_group_field": "A szerkesztési művelet segítségével határozzon meg egy mezők szerinti csoportosítást.",
  "fieldTitle": "Mező",
  "typeTitle": "Típus",
  "actionsTitle": "Műveletek",
  "save_point_checkbox": "Pontok mentése",
  "save_line_checkbox": "Vonalak mentése",
  "save_poly_checkbox": "Polygonok mentése",
  "no_valid_popup_fields": "Nincsenek érvényes mezők a felugró ablakban. A szerkesztési művelet segítségével határozzon meg egy mezőt.",
  "no_valid_fields": "Nincsenek érvényes mezők. A szerkesztési művelet segítségével adja meg a megjelenítési beállításokat.",
  "incident_label": "Fül felirata",
  "locate_incident_label": "Vizsgálati terület felirata",
  "incident": "Incidens",
  "locate_incident": "Incidens megkeresése",
  "buffer_value": "Buffer távolsága",
  "tab_options": "Elemzés",
  "export_options": "Kimenet",
  "instruction_save": "Helyszín mentése vektoros adatszolgáltatásba.",
  "instruction_snapshot": "Webes térkép létrehozása a helyszín alapján.",
  "instruction_report": "Nyomtatott jelentés létrehozása a helyszínről.",
  "instruction_all_fields": "Mezők exportálása letölthető CSV-be.",
  "data_label": "Adatkimeneti beállítások",
  "layer_error": "Hiányzó vagy érvénytelen réteg.",
  "visibility_checkBox": "Rétegláthatóság kezelésének tiltása",
  "allFieldsLabel": "Összes mező",
  "configuredPopUpFieldsLabel": "Konfigurált felugró mezők",
  "analysisTypeFieldsLabel": "Elemzés típusa mezők",
  "reportOptionsMsg": "Legalább egy jelentési opciót ki kell választani",
  "analysisSummaryLabelForReport": "Elemzéstípus összefoglalása",
  "popUpSummaryLabelForReport": "Konfigurált felugró mezők összefoglalása",
  "downloadTab": {
    "reportLegend": "Jelentésbeállítások",
    "textColorLabel": "Oszlopcímek színének kiválasztása",
    "setButtonLabel": "Beállítás",
    "printGPServiceLabel": "Nyomtatási szolgáltatás URL-címe",
    "logoLabel": "Logó",
    "logoChooserHint": "Kattintson a kép ikonra a kép cseréjéhez",
    "footnoteLabel": "Lábjegyzet"
  },
  "roundValue": "Kerekítés erre:",
  "roundValueTitle": "Mezőértékek kerekítése",
  "truncateValue": "Csonkolás erre:",
  "truncateValueTitle": "Mezőértékek csonkolása",
  "significantFigures": "értékes számjegyek",
  "fieldOptions": "Mező opciók",
  "modifyValues": "Mezőértékek módosítása",
  "validatePlaces": "Egész számnak kell lennie",
  "onlyDouble": "A további mező opciókat csak numerikus mezőknél támogatja a rendszer.",
  "layerNotAvalible": "Réteg nem található",
  "missingLayer": "Név: ${name}",
  "missingLayerHint": "Az ezen konfiguráció áltak hivatkozott egy vagy több réteg jelenleg nem érhető el.",
  "drawGeodesic": "Geodéziai alakzat rajzolása"
});