define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Pridėkite tašką paspausdami žemėlapyje",
  "addRingsDtWt": "Pridėkite žiedus, važiavimo laiką arba ėjimo laiką.",
  "apply": "Taikyti",
  "back": "Atgal",
  "colon": ":",
  "creditInformation": "Kredito informacija",
  "driveTime": "Važiavimo laikas",
  "esriInfographics": "Esri infografikai",
  "esriReports": "Esri ataskaitos",
  "headerDescription_km": "kilometras",
  "headerDescription_miles": "mylia",
  "headerDescription_minutes": "minutė",
  "infographics": "Infografikai",
  "invalidValueRing": "Reikšmės turi būti nuo 0 iki 1 000.",
  "invalidValueDTWT": "Reikšmės turi būti nuo 0 iki 300.",
  "km": "km",
  "miles": "mylios",
  "minutes": "min.",
  "myInfographics": "Mano infografikai",
  "myReports": "Mano ataskaitos",
  "noPermissions": "Jūsų paskyra negali naudoti Business Analyst valdiklio.  Kad galėtumėte naudoti Business Analyst valdiklį, jūsų organizacijos administratorius turi jums suteikti geopraturtinimo ir tinklo analizės <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">teises</a> ir paskirti <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">kreditų</a>.",
  "radii": "spinduliai",
  "radius": "Spindulys",
  "radius_lowercase": "spindulys",
  "reports": "Ataskaitos",
  "ring": "Žiedas",
  "rings": "Žiedai",
  "runInfographic": "Paleisti infografiką",
  "runReport": "Paleisti ataskaitą",
  "selectPointOrPolygon": "Žemėlapyje pasirinkite taškinį arba plotinį elementą, ieškokite adreso ar vietos arba padėkite smeigtuką žemėlapyje, jei norite peržiūrėti daugiau informacijos apie teritorijas.",
  "selectReport": "Pasirinkti ataskaitą",
  "selectTemplate": "Pasirinkti šabloną",
  "sharedInfographics": "Bendrinami infografikai",
  "sharedReports": "Bendrinamos ataskaitos",
  "thisEntryIsNotValid": "Šis įrašas yra netinkamas.",
  "time": "Laikas",
  "walkTime": "Ėjimo laikas",
  "widgetDescription": "Pasiekti infografikus ir ataskaitas, kuriuose pateikiami svarbiausi bet kurios teritorijos rodikliai ir duomenys.",
  "None": "Pasirinkti..."
});