define({
  "enableUndoRedo": "Onemogoči razveljavi/uveljavi",
  "toolbarVisible": "Vidnost orodne vrstice",
  "toolbarOptions": "Možnosti orodne vrstice",
  "mergeVisible": "Združi",
  "cutVisible": "Izreži",
  "reshapeVisible": "Preoblikuj",
  "back": "Nazaj",
  "label": "Sloj",
  "edit": "Uredljiv",
  "update": "Onemogoči posodobitev geometrije",
  "fields": "Polja",
  "actions": "Dejanja",
  "editpageName": "Ime",
  "editpageAlias": "Vzdevek",
  "editpageVisible": "Vidno",
  "editpageEditable": "Uredljiv",
  "noLayers": "Ni na voljo uredljivih geoobjektnih slojev",
  "configureFields": "Konfigurirajte polja slojev",
  "useFilterEdit": "Uporabite filter predlog geoobjektov",
  "display": "Prikaz",
  "autoApplyEditWhenGeometryIsMoved": "Uporabi samodejno urejanje, ko je geometrija premaknjena",
  "snappingTolerance": "Nastavite doseg privlačnosti v pikslih",
  "popupTolerance": "Nastavite toleranco klika na pojavno okno za urejanje atributov v pikslih",
  "stickyMoveTolerance": "Nastavite toleranco nenamernega premika geoobjekta v pikslih",
  "usingSaveButton": "Urejanj za atribute ne uporabite, dokler ne kliknete na gumb Shrani",
  "generalSettings": "Splošne nastavitve",
  "editableLayersSetting": "Uredljive nastavitve slojev",
  "honorTheWebMapSetting": "Upoštevajte nastavitve spletne karte",
  "honorTheWebMapSettingTip1": "Nastavitve vključujejo:",
  "honorTheWebMapSettingTip2": "Kateri sloji so uredljivi",
  "honorTheWebMapSettingTip3": "Polja, ki jih želite prikazati in urediti",
  "honorTheWebMapSettingTip4": "Vzdevek, vrstni red in oblika polja",
  "customSettings": "Nastavitve po meri"
});