define({
  "businessAnalyst": "Business Analyst",
  "defineWhichInfographics": "Apibrėžkite, kurie infografikai pasiekiami valdiklyje:",
  "defineWhichReports": "Apibrėžkite, kurios ataskaitos pasiekiamos valdiklyje:",
  "defaultValues": "Numatytosios reikšmės:",
  "disable": "Išjungti",
  "driveTime": "Važiavimo laikas",
  "infographics": "Infografikai",
  "invalidValueRing": "Reikšmės turi būti nuo 0 iki 1 000.",
  "invalidValueDTWT": "Reikšmės turi būti nuo 0 iki 300.",
  "km": "km",
  "miles": "mylios",
  "minutes": "min.",
  "radius": "Spindulys",
  "reports": "Ataskaitos",
  "rings": "Žiedai",
  "selectCountryOrRegion": "Pasirinkite šalį arba regioną:",
  "thisEntryIsNotValid": "Šis įrašas yra netinkamas.",
  "time": "Laikas",
  "walkTime": "Ėjimo laikas"
});