define({
  "enableUndoRedo": "Permitir Undo/Redo",
  "toolbarVisible": "Barra de Ferramentas Visível",
  "toolbarOptions": "Opções da Barra de Ferramentas",
  "mergeVisible": "Juntar",
  "cutVisible": "Cortar",
  "reshapeVisible": "Redefinir",
  "back": "Regressar",
  "label": "Camada",
  "edit": "Editável",
  "update": "Desativar Atualizar Geometria",
  "fields": "Campos",
  "actions": "Ações",
  "editpageName": "Nome",
  "editpageAlias": "Nome Alternativo",
  "editpageVisible": "Visível",
  "editpageEditable": "Editável",
  "noLayers": "Não há camadas de elementos editáveis",
  "configureFields": "Configurar Campos de Camadas",
  "useFilterEdit": "Utilizar filtro de modelo de elemento",
  "display": "Exibir",
  "autoApplyEditWhenGeometryIsMoved": "Aplicar a edição automaticamente quando a geometria é movida",
  "snappingTolerance": "Definir a tolerância de ajuste em píxeis",
  "popupTolerance": "Definir a tolerância da janela pop-up de edição de atributos em píxeis",
  "stickyMoveTolerance": "Definir a tolerância de sticky move em píxeis"
});