define({
  "styleText": "Izvēlieties pārvilkšanas rīka stilu",
  "vertical": "Vertikālā josla",
  "horizontal": "Horizontālā josla",
  "scope": "Tālskatis",
  "barColor": "Joslas krāsa",
  "swipeMode": "Pārvilkšanas režīms",
  "singleLayer": "Viens slānis",
  "MultipleLayers": "Vairāki slāņi",
  "allowToSwipe": "Atļaut pārvilkt",
  "layer": "Slānis",
  "swipeByDefault": "Pārvilkt pēc noklusējuma",
  "defaultLayerMustBeVisible": "jābūt redzamam noklusējuma slānim",
  "noDefaultLayer": "Lūdzu, iestatiet slāņu pārvilkšanu pēc noklusējuma",
  "defaultLayerHolder": "Noklikšķiniet, lai izvēlētos",
  "selectLayers": "Izvēlieties slāņus",
  "layerText": "Izvēlieties slāni(us), kas jāpārvelk pēc noklusējuma",
  "spyglassText": "Izvēlieties slāni, kas tiks rādīts tālskatī pēc noklusējuma.",
  "layerHint": "Piezīme. Ja slānis ir paslēpts augšējos slāņos, pārvilkšanai nebūs nekāda efekta.",
  "isZoom": "Pietuvināt uz pārvilkto slāni",
  "isZooms": "Pietuvināt uz pārvilkto slāni(iem)",
  "layersAvailable": "Izvēlieties pārvelkamos slāņus:"
});