define({
  "_widgetLabel": "Näkyvyys",
  "observerLocation": "Tarkkailijan sijainti",
  "formatIconTooltip": "Muodon lähtöaineisto",
  "addPointToolTip": "Lisää tarkkailijan sijainti",
  "fieldOfView": "Näkökenttä",
  "useMilsText": "Käytä maileja kulmissa",
  "observerHeight": "Tarkkailjan korkeus",
  "minObsDistance": "Vähimmäistarkasteluetäisyys",
  "maxObsDistance": "Enimmäistarkasteluetäisyys",
  "taskURLError": "Pienoisohjelman määritystiedosto sisältää URL-osoitteen, johon ei saada yhteyttä. Pyydä apua järjestelmän pääkäyttäjältä",
  "taskURLInvalid": "Tässä pienoisohjelmassa määritetty geoprosessointitehtävä ei kelpaa. Pyydä apua järjestelmän pääkäyttäjältä",
  "viewshedError": "Virhe näkyvyyden luonnissa. Varmista, että tarkkailijan sijainti osuu pintakorkeustietojesi alueelle.</p>",
  "validationError": "<p>Näkyvyyden luontilomakkeesta puuttuu parametreja tai ne ovat virheellisiä. Varmista seuraavat asiat:</p><ul><li>Tarkkailijan sijainti on määritetty.</li><li>Tarkkailijan näkökentän arvo ei ole 0.</li><li>Tarkkailijan korkeus sisältää kelvollisen arvon.</li><li>Tarkkailuetäisyyden vähimmäis- ja enimmäisarvot sisältävät kelvolliset arvot.</li></ul>",
  "comfirmInputNotation": "Vahvista lähtöaineiston esitysmuoto",
  "notationsMatch": "lähtöaineistoasi vastaavia esitystapoja. Vahvista käytettävä esitystapa:",
  "createBtn": "Luo",
  "clearBtn": "Tyhjennä",
  "setCoordFormat": "Määritä koordinaatin muotomerkkijono",
  "prefixNumbers": "Lisää etuliite +/- positiivisiin ja negatiivisiin numeroihin",
  "parseCoordinatesError": "Koordinaattien jäsennys ei onnistu. Tarkista lähtöaineistosi.",
  "cancelBtn": "Peruuta",
  "applyBtn": "Käytä",
  "invalidMessage": "Anna numeroarvo.",
  "observerRangeMessage": "Virheellinen tarkkailijan korkeus",
  "minimumRangeMessage": "Virheellinen tarkkailualueen vähimmäisarvo",
  "maximumRangeMessage": "Tarkkailualueen enimmäisarvon on oltava suurempi kuin tarkkailualueen vähimmäisarvo eikä se saa olla suurempi kuin ${limit} ${units}.",
  "portalURLError": "ArcGIS Online -organisaatiosi tai Portal for ArcGIS -ohjelman URL-osoitetta ei ole määritetty. Pyydä apua järjestelmän pääkäyttäjältä",
  "privilegeError": "käyttäjäroolisi ei voi suorittaa analyysia. Analyysin suoritus edellyttää, että organisaatiosi pääkäyttäjä myöntää sinulle tietyt <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">käyttöoikeudet</a>.",
  "noServiceError": "Korkeustason analyysipalvelu ei ole käytettävissä. Tarkista ArcGIS Online -organisaatiosi tai Portal for ArcGIS -kokoonpanoasetuksesi.",
  "pointToolTooltip": "Lisää tarkkailijan sijainti napsauttamalla",
  "degreesLabel": "astetta",
  "milsLabel": "mailia",
  "DD": "da",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Desimaaliasteet – leveys-/pituusaste",
  "DDLongLatNotation": "Desimaaliasteet – pituus-/leveysaste",
  "DDMLatLongNotation": "Asteet, desimaaliminuutit – leveys-/pituusaste",
  "DDMLongLatNotation": "Asteet, desimaaliminuutit – pituus-/leveysaste",
  "DMSLatLongNotation": "Asteet, minuutit, sekunnit – leveys-/pituusaste",
  "DMSLongLatNotation": "Asteet, minuutit, sekunnit – pituus-/leveysaste",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM – kaistan kirjain",
  "UTMHemNotation": "UTM – pallonpuolisko (P/E)"
});