define({
  "_widgetLabel": "Zīmēšana",
  "selectDrawMode": "Atlasiet zīmēšanas režīmu",
  "clear": "Notīrīt",
  "point": "Punkts",
  "line": "Līnija",
  "polyline": "Polilīnija",
  "freehandPolyline": "Brīvrokas līnija",
  "triangle": "Trīsstūris",
  "extent": "Pārklājuma taisnstūris",
  "circle": "Aplis",
  "ellipse": "Elipse",
  "polygon": "Laukums",
  "freehandPolygon": "Brīvrokas laukums",
  "text": "Teksts",
  "style": "Stils",
  "alpha": "Caurspīdīgums",
  "width": "Platums",
  "size": "Lielums",
  "color": "Krāsa",
  "markerColor": "Marķiera krāsa",
  "outlineColor": "Kontūras krāsa",
  "lineColor": "Līnijas krāsa",
  "fillColor": "Pildījuma krāsa",
  "showMeasurements": "Rādīt mērījumus",
  "showLocationMeasurement": "Rādīt novietojuma mērījumu",
  "showAreaMeasurement": "Rādīt platības mērījumu",
  "showDistanceMeasurement": "Rādīt attāluma mērījumu",
  "showDistanceMeasurementForLine": "Rādīt garuma mērījumu",
  "showDistanceMeasurementForPolygon": "Rādīt perimetra mērījumu",
  "locationToggleOn": "Nospiediet pārslēgšanas pogu, lai rādītu novietojuma mērījumu",
  "locationToggleOff": "Nospiediet pārslēgšanas pogu, lai paslēptu novietojuma mērījumu",
  "areaToggleOn": "Nospiediet pārslēgšanas pogu, lai rādītu laukuma mērījumu",
  "areaToggleOff": "Nospiediet pārslēgšanas pogu, lai paslēptu laukuma mērījumu",
  "distanceForLineToggleOn": "Nospiediet pārslēgšanas pogu, lai rādītu garuma mērījumu",
  "distanceForLineToggleOff": "Nospiediet pārslēgšanas pogu, lai paslēptu garuma mērījumu",
  "distanceForPolygonToggleOn": "Nospiediet pārslēgšanas pogu, lai rādītu perimetra mērījumu",
  "distanceForPolygonToggleOff": "Nospiediet pārslēgšanas pogu, lai paslēptu perimetra mērījumu",
  "areaUnits": "Laukuma mērvienības",
  "distanceUnits": "Attāluma mērvienības",
  "kilometers": "Kilometri",
  "miles": "Jūdzes",
  "meters": "Metri",
  "feet": "Pēdas",
  "yards": "Jardi",
  "nauticalmiles": "Jūras jūdzes",
  "squareKilometers": "Kvadrātkilometri",
  "squareMiles": "Kvadrātjūdzes",
  "acres": "Akri",
  "hectares": "Hektāri",
  "squareMeters": "Kvadrātmetri",
  "squareFeet": "Kvadrātpēdas",
  "squareYards": "Kvadrātjardi",
  "undo": "Atsaukt",
  "redo": "Atcelt atsaukšanu",
  "results": "Rezultāti",
  "points": "Punkti",
  "lines": "Līnijas",
  "areas": "Platības",
  "locationLabel": "Novietojums: ${value}",
  "areaLabel": "Platība: ${value} ${unit}",
  "distanceLabel": "Attālums: ${value} ${unit}",
  "distanceLabelForLine": "Garums: ${value} ${unit}",
  "distanceLabelForPolygon": "Perimetrs: ${value} ${unit}"
});