define({
  "selectAnalysisTools": "Vyberte nástroje analýzy, které si přejete používat ve widgetu.",
  "graphicalDisplay": "Grafické zobrazení",
  "toolSetting": "Nastavte podrobnosti nástrojů",
  "toolLabel": "Zobrazovaný název nástroje",
  "showHelpTip": "Zobrazovat ve widgetu odkazy na nápovědu",
  "showCurrentMapExtent": "Zobrazovat možnost použití aktuálního rozsahu mapy",
  "showCredits": "Zobrazovat možnost <b>Zobrazit kredity</b>",
  "saveAsFeatureService": "Uložit výsledky do uživatelského účtu",
  "showReadyToUseLayers": "Zobrazovat vrstvy připravené k použití z živého atlasu světa ArcGIS Online",
  "toolNotAvailable": "Tento nástroj není k dispozici, protože mapa neobsahuje požadované vrstvy prvků.",
  "aggregatePoints": "Seskupit body",
  "aggregatePointsUsage": "Umožňuje seskupit body do polygonů, ve kterých se tyto body nacházejí.",
  "calculateDensity": "Vypočítat hustotu",
  "calculateDensityUsage": "Umožňuje vytvářet mapu hustoty z bodových nebo liniových prvků rozprostřením známého množství určitého jevu (v podobě atributů bodů nebo linií) po mapě.",
  "connectOriginsToDestinations": "Spojení počátků s cíli",
  "connectOriginsToDestinationsUsage": "Umožňuje měřit čas cesty nebo vzdálenost mezi dvojicí bodů.",
  "createBuffers": "Vytvořit obalové zóny",
  "createBuffersUsage": "Umožňuje vytvářet polygony obalové zóny ze vstupních prvků.",
  "createDriveTimeAreas": "Vytvořit oblasti podle doby jízdy",
  "createDriveTimeAreasUsage": "Umožňuje vytvářet polygony doby jízdy (nebo jízdní vzdálenosti) okolo vstupních bodů pro zadané hodnoty doby jízdy.",
  "createViewshed": "Vytvořit viditelnost",
  "createViewshedUsage": "Umožňuje vytvářet oblasti, které jsou viditelné na základě vámi určených umístění.",
  "createWatersheds": "Vytvořit povodí",
  "createWatershedsUsage": "Umožňuje vytvářet oblasti povodí na základě vámi určených umístění.",
  "deriveNewLocations": "Odvodit nové lokality",
  "deriveNewLocationsUsage": "Umožňuje odvodit ze vstupních vrstev nové prvky, které splňují zadaná kritéria.",
  "dissolveBoundaries": "Sloučit hranice",
  "dissolveBoundariesUsage": "Umožňuje sloučit polygony, které se překrývají nebo mají společné hranice.",
  "enrichLayer": "Obohatit vrstvu",
  "enrichLayerUsage": "Umožňuje obohatit vstupní prvky informacemi o lidech, místech a obchodními údaji přilehlých oblastí.",
  "extractData": "Extrahovat data",
  "extractDataDesc": "Umožňuje extrahovat data z jedné nebo více vrstev v daném rozsahu.",
  "findCentroids": "Vyhledat centroidy",
  "findCentroidsUsage": "Nástroj vyhledá reprezentativní střed (centroid) pro každý vstupní prvek vícenásobného bodu, linie nebo plochy.",
  "findExistingLocations": "Najít stávající lokality",
  "findExistingLocationsUsage": "Umožňuje vybrat prvky ve vstupní vrstvě, které splňují požadavky zadaného atributu nebo prostorového dotazu.",
  "findHotSpots": "Hot spot analýza",
  "findHotSpotsUsage": "Umožňuje najít statisticky významné shluky vstupních prvků nebo vysokých/nízkých hodnot.",
  "findNearest": "Najít nejbližší",
  "findNearestUsage": "Umožňuje najít pro každý prvek vstupní vrstvy nejbližší prvek v jiné vrstvě.",
  "findPointClusters": "Najít shluky bodů",
  "findPointClustersUsage": "Tento nástroj odhalí oblasti, kde jsou koncentrované body a kde jsou oddělené oblastmi, které jsou prázdné či řídké.",
  "findSimilarLocations": "Najít podobné lokality",
  "findSimilarLocationsUsage": "Umožňuje měřit podobnost kandidátských umístění s jedním nebo více referenčními umístěními.",
  "geocodeLocations": "Geokódovat umístění z tabulky",
  "geocodeLocationsUsage": "Pohodlný způsob geokódování velkých tabulek a souborů s adresami do bodů.",
  "interpolatePoints": "Interpolovat body",
  "interpolatePointsUsage": "Umožňuje odhadovat hodnoty v nových místech na základě hodnot existujících bodů.",
  "mergeLayers": "Sloučit vrstvy",
  "mergeLayersUsage": "Umožňuje sloučit prvky z několika vrstev do nové vrstvy.",
  "overlayLayers": "Překrýt vrstvy",
  "overlayLayersUsage": "Umožňuje zkombinovat několik vrstev do jedné vrstvy se zachováním informací z původních vrstev.",
  "planRoutes": "Plánovat trasy",
  "planRoutesUsage": "Umožňuje určit efektivní rozdělení úkolů mezi mobilní pracovníky.",
  "summarizeCenterAndDispersion": "Souhrn středové hodnoty a rozptýlení",
  "summarizeCenterAndDispersionUsage": "Použijte bodové prvky k výpočtu středového prvku, geografického středu prvků, geografického mediánu prvků nebo elipsy (rozložení).",
  "summarizeNearby": "Souhrn hodnot v okolí",
  "summarizeNearbyUsage": "Umožňuje pro všechny prvky vstupní vrstvy sumarizovat data v dané vzdálenosti od prvků v jiné vrstvě.",
  "summarizeWithin": "Souhrn hodnot v rozmezí",
  "summarizeWithinUsage": "Umožňuje pro všechny polygony ve vstupní vrstvě sumarizovat obsažená data pomocí prvků v jiné vrstvě.",
  "traceDownstream": "Sledovat po proudu",
  "traceDownstreamUsage": "Umožňuje určit trasy toku směrem po proudu od vámi určených umístění.",
  "allowToExport": "Povolit export výsledků",
  "joinFeatures": "Připojit prvky",
  "joinFeaturesUsage": "Nástroj Připojit prvky přenese atributy jedné vrstvy nebo tabulky k jiné na základě prostorových a atributových vztahů. Můžete také vypočítat statistiku připojených prvků.",
  "includeRouteLayer": "Zahrnout vrstvy tras",
  "findOutliers": "Najít odlehlé prvky",
  "findOutliersUsage": "Nástroj Najít odlehlé prvky umožňuje zjistit, zda se v prostorové struktuře vašich dat nevyskytují statisticky významné odlehlé prvky."
});