define({
  "showArcgisBasemaps": "Portal altlık haritalarını dahil et",
  "add": "Yeni Altlık Haritası Eklemek için tıkla",
  "edit": "Özellikler",
  "titlePH": "Altlık Haritası Başlığı",
  "thumbnailHint": "Güncellemek için resme tıkla",
  "urlPH": "Katman URL'si",
  "addlayer": "Altlık Haritası Ekle",
  "warning": "Hatalı girdi",
  "save": "Dön ve Kaydet",
  "back": "Dön ve İptal Et",
  "addUrl": "URL Ekle",
  "autoCheck": "Otomatik Denetle",
  "checking": "Denetleniyor...",
  "result": "Başarıyla kaydedildi",
  "spError": "Galeriye eklenen tüm altlık haritalar aynı mekansal başvuruya sahip olmalıdır.",
  "invalidTitle1": "Bir altlık haritası '",
  "invalidTitle2": "' zaten mevcut. Başka bir başlık seçin.",
  "invalidBasemapUrl1": "Bu katman türü altlık haritası olarak kullanılamaz.",
  "invalidBasemapUrl2": "Eklediğiniz altlık haritası geçerli haritadan farklı bir mekansal başvuruya sahip.",
  "addBaselayer": "Altlık Haritası Katmanı Ekle",
  "repectOnline": "Her zaman kuruluşun Altlık Harita Galerisi ayarıyla senkronize edin",
  "customBasemap": "Özel altlık haritaları yapılandırın",
  "basemapTips": "Yeni altlık harita eklemek için \"${import}\" veya \"${createNew}\" öğesine tıklayın.",
  "importBasemap": "İçe Aktar",
  "createBasemap": "Yeni Oluştur",
  "importTitle": "Altlık Haritaları İçe Aktar",
  "createTitle": "Yeni Altlık Haritası",
  "selectGroupTip": "Web haritaları altlık harita olarak kullanılabilen bir grup seçin.",
  "noBasemaps": "Altlık harita yok.",
  "defaultGroup": "Esri Varsayılan",
  "defaultOrgGroup": "Kuruluş Varsayılanı",
  "warningTitle": "Uyarı",
  "confirmDelete": "Seçili altlık haritaları silmek istiyor musunuz?",
  "noBasemapAvailable": "Kullanılabilir altlık harita yok veya tüm altlık haritalarında geçerli haritadan daha farklı mekansal başvuru var."
});