define({
  "_widgetLabel": "Pametni urejevalnik",
  "_featureAction_SmartEditor": "Pametni urejevalnik",
  "noEditPrivileges": "Vaš račun nima dovoljenja za ustvarjanje ali spreminjanje podatkov.",
  "widgetActive": "Aktivno",
  "widgetNotActive": "Neaktivno",
  "pressStr": "Pritisnite ",
  "ctrlStr": " CTRL, ",
  "snapStr": " da omogočite privlačnost",
  "noAvailableTempaltes": "Predloge niso na voljo",
  "editorCache": " – predpomnilnik urejevalnika",
  "presetFieldAlias": "Polje",
  "presetValue": "Prednastavljena vrednost",
  "usePresetValues": " Uporabi prednastavljeno vrednost (samo novi geoobjekti)",
  "editGeometry": " Uredi geometrijo",
  "savePromptTitle": "Shrani geoobjekt",
  "savePrompt": "Želite shraniti trenutni geoobjekt?",
  "deletePromptTitle": "Izbriši geoobjekt",
  "deleteAttachment": "Izbriši prilogo",
  "deletePrompt": "Ste prepričani, da želite izbrisati izbrani geoobjekt?",
  "attachmentLoadingError": "Napaka pri nalaganju prilog",
  "attachmentSaveDeleteWarning": "Opozorilo: Spremembe v prilogah so shranjene samodejno",
  "autoSaveEdits": "Samodejno shrani nov geoobjekt",
  "addNewFeature": "Ustvari nov geoobjekt",
  "featureCreationFailedMsg": "Ni bilo mogoče ustvariti novega zapisa/geoobjekta",
  "relatedItemTitle": "Relacijska tabela/sloj",
  "relatedFeatureCount": "${layerTitle} z geoobjekti ${featureCount}",
  "createNewFeatureLabel": "Ustvari nov geoobjekt za ${layerTitle}",
  "invalidRelationShipMsg": "Zagotovite, da ima polje primarnega ključa: »${parentKeyField}« veljavno vrednost",
  "pendingFeatureSaveMsg": "Shranite urejanja geoobjektov pred ustvarjanjem relacijskega geoobjekta.",
  "attachmentsRequiredMsg": "(*) Zahtevane so priloge.",
  "coordinatePopupTitle": "Premakni geoobjekt na lokacijo XY",
  "coordinatesSelectTitle": "Koordinatni sistem:",
  "mapSpecialReferenceDropdownOption": "Koordinatni sistem karte",
  "latLongDropdownOption": "Geografska širina/geografska dolžina",
  "xAttributeTextBoxLabel": "Koordinata X:",
  "yAttributeTextBoxLabel": "Koordinata Y:",
  "latitudeTextBoxLabel": "Geografska širina:",
  "longitudeTextBoxLabel": "Geografska dolžina:",
  "presetGroupFieldsLabel": "'${groupName}' bo uporabljeno za naslednja polja slojev:",
  "presetGroupNoFieldsLabel": "'${groupName}' nima nobenih povezanih polj",
  "groupInfoLabel": "Informacije skupine za '${groupName}'",
  "editGroupInfoIcon": "Uredi vrednost skupine za ${groupName}",
  "filterEditor": {
    "all": "Vsi",
    "noAvailableTempaltes": "Predloge niso na voljo",
    "searchTemplates": "Iskanje predlog",
    "filterLayerLabel": "Filtriraj sloje"
  },
  "invalidConfiguration": "Pripomoček morda ni konfiguriran ali pa slojev v konfiguraciji ni več na zemljevidu. Odprite aplikacijo v načinu izdelave in ponovno konfigurirajte pripomoček.",
  "geometryServiceURLNotFoundMSG": "URL geometrijske storitve ni mogoče pridobiti",
  "clearSelection": "Počisti",
  "refreshAttributes": "Posodobi atribute geoobjektov",
  "automaticAttributeUpdatesOn": "Samodejno posodabljajo atribute geoobjektov: VKLOP",
  "automaticAttributeUpdatesOff": "Samodejno posodobi atribute geoobjektov: IZKLOP",
  "moveSelectedFeatureToGPS": "Premakni izbrani geoobjekt na trenutno lokacijo GPS",
  "moveSelectedFeatureToXY": "Premakni izbrani geoobjekt na lokacijo XY",
  "mapNavigationLocked": "Navigacija po karti: zaklenjeno",
  "mapNavigationUnLocked": "Navigacija po karti: odklenjeno",
  "copyFeatures": {
    "title": "Kopiraj geoobjekte",
    "createFeatures": "Ustvari geoobjekte",
    "createSingleFeature": "Ustvari 1 večgeometrijski geoobjekt",
    "noFeaturesSelectedMessage": "Ni izbranih geoobjektov",
    "selectFeatureToCopyMessage": "Izberite geoobjekte za kopiranje.",
    "multipleFeatureSaveWarning": "Opomba: ustvarjanje večdelnih geoobjektov z uporabo kopiranja geoobjekta bo takoj shranilo vse geoobjekte"
  },
  "addingFeatureError": "Pri dodajanju izbranih geoobjektov v sloj se je pojavila napaka. Poskusite znova.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' geoobjektov ni bilo mogoče kopirati.",
  "selectingFeatureError": "Pri izbiranju geoobjektov v sloj se je pojavila napaka. Poskusite znova.",
  "customSelectOptionLabel": "Izberite geoobjekte za kopiranje.",
  "noFeatureSelectedMessage": "Ni izbranih geoobjektov.",
  "multipleFeatureSaveMessage": "Vsi geoobjekti bodo takoj shranjeni. Želite nadaljevati?",
  "relativeDates": {
    "dateTypeLabel": "Tip podatkov",
    "valueLabel": "Vrednost",
    "fixed": "Fiksno",
    "current": "Trenutno",
    "past": "Pretekli",
    "future": "Prihodnost",
    "popupTitle": "Izberi vrednost",
    "hintForFixedDateType": "Namig: določena datum in čas bosta uporabljena kot prednastavljena privzeta vrednost.",
    "hintForCurrentDateType": "Namig: trenutni datum in čas bosta uporabljena kot prednastavljena privzeta vrednost.",
    "hintForPastDateType": "Namig: določena vrednost bo odšteta od trenutnega datuma in časa za privzeto vrednost prednastavitve.",
    "hintForFutureDateType": "Namig: določena vrednost bo dodana trenutnemu datumu in času za privzeto vrednost prednastavitve.",
    "noDateDefinedTooltip": "Noben datum ni določen",
    "relativeDateWarning": "Vrednost za datum ali čas mora biti določena, da jo lahko shranite kot privzeto prednastavljeno vrednost."
  }
});