define({
  "_widgetLabel": "Query",
  "executeQueryTip": "Klik salah satu dari item tugas berikut untuk menjalankan query.",
  "invalidConfig": "Konfigurasi tidak valid. Harap gunakan halaman pengaturan Query untuk mendapatkan konfigurasi yang tepat.",
  "queryParams": "Opsi",
  "parameters": "OPSI",
  "queries": "QUERY",
  "apply": "TERAPKAN",
  "queryResults": "Hasil",
  "clear": "Kosongkan",
  "noResults": "Fitur tidak ditemukan.",
  "queryError": "Query gagal !",
  "numberFound": "Jumlah fitur yang ditemukan",
  "mapExtentTip": "Batasi hasil hingga area peta saat ini",
  "noValue": "Tidak ada nilai",
  "and": "dan",
  "stringOperatorIs": "adalah",
  "stringOperatorIsNot": "bukan",
  "stringOperatorStartsWith": "mulai dengan",
  "stringOperatorEndsWith": "berakhir dengan",
  "stringOperatorContains": "berisi",
  "stringOperatorDoesNotContain": "tidak berisi",
  "stringOperatorIsBlank": "kosong",
  "stringOperatorIsNotBlank": "tidak kosong",
  "dateOperatorIsOn": "berada di",
  "dateOperatorIsNotOn": "tidak berada di",
  "dateOperatorIsBefore": "sebelum",
  "dateOperatorIsAfter": "setelah",
  "dateOperatorDays": "hari",
  "dateOperatorWeeks": "minggu",
  "dateOperatorMonths": "bulan",
  "dateOperatorInTheLast": "terakhir",
  "dateOperatorNotInTheLast": "bukan terakhir",
  "dateOperatorIsBetween": "di antara",
  "dateOperatorIsNotBetween": "bukan di antara",
  "dateOperatorIsBlank": "kosong",
  "dateOperatorIsNotBlank": "tidak kosong",
  "numberOperatorIs": "adalah",
  "numberOperatorIsNot": "bukan",
  "numberOperatorIsAtLeast": "paling sedikit",
  "numberOperatorIsLessThan": "kurang dari",
  "numberOperatorIsAtMost": "paling banyak",
  "numberOperatorIsGreaterThan": "lebih besar dari",
  "numberOperatorIsBetween": "di antara",
  "numberOperatorIsNotBetween": "bukan di antara",
  "numberOperatorIsBlank": "kosong",
  "numberOperatorIsNotBlank": "tidak kosong",
  "operationalLayerTip": "Tambahkan hasil sebagai layer operasional",
  "queryResult": "Hasil Query",
  "specifyParamsTip": "Tentukan parameter untuk tugas ini",
  "useSpatialFilter": "Gunakan filter spasial untuk membatasi fitur",
  "useCurrentMapExtent": "Hanya fitur yang memotong area peta saat ini",
  "drawGraphicOnMap": "Hanya fitur yang berpotongan dalam area yang ditentukan pengguna",
  "specifySpatialFilterMsg": "Tentukan filter spasial untuk tugas ini.",
  "clearResults": "Kosongkan Hasil",
  "operationalTip": "Dengan dicentangnya opsi ini, hasil akan tetap berada dalam peta hingga tombol \"${clearResults}\" diklik.",
  "noneQueryTip": "Tidak ada tugas query yang dikonfigurasikan untuk widget ini.",
  "noPermissionsMsg": "Anda tidak memiliki izin untuk mengakses layanan ini.",
  "attributesFromRelationship": "Atribut dari tabel terkait",
  "tasks": "Tugas",
  "applySpatialFilterToLimitResults": "Terapkan filter spasial untuk membatasi hasil",
  "useCurrentExtentTip": "Hanya mengembalikan fitur di dalam jangkauan peta saat ini",
  "useDrawGraphicTip": "Hanya mengembalikan fitur yang berpotongan dengan bentuk yang digambar pada peta",
  "useFeaturesTip": "Hanya mengembalikan fitur yang mempunyai hubungan spasial dengan fitur dalam layer lain",
  "noSpatialLimitTip": "Kembalikan fitur dalam jangkauan penuh dari peta",
  "applySearchDistance": "Terapkan jarak pencarian",
  "spatialRelationship": "Hubungan Spasial",
  "relatedLayer": "Layer Terkait",
  "bufferDistance": "Jarak Buffer",
  "miles": "Mil",
  "kilometers": "Kilometer",
  "feet": "Kaki",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Mil Laut",
  "back": "Kembali",
  "execute": "Jalankan",
  "zoomTo": "Perbesar hingga",
  "openAttributeTable": "Buka dalam Tabel Atribute",
  "noResult": "Tidak ada hasil.",
  "noTask": "Tidak ada tugas.",
  "removeThisResult": "Hapus Hasil Ini",
  "attributeCriteira": "Kriteria atribut",
  "spatialFilter": "Filter spasial",
  "value": "NILAI",
  "noAttributeSpatialFilterTip": "Tidak ada filter yang ditentukan. Semua fitur akan dikembalikan.",
  "showAllRelatedRecords": "Tampilkan Semua Catatan Terkait",
  "changeSymbol": "Ganti Simbol"
});