define({
  "tabs_section_Label": "Sekmeler",
  "addTab": "Sekme Ekle",
  "layerName": "Katman",
  "layerType": "Analiz Türü",
  "layerLabel": "Etiket",
  "actions": "İşlemler",
  "closest": "En Yakın Detay",
  "proximity": "Yakınlık",
  "summary": "Özet",
  "select_lbl": "-- Seç --",
  "general_setting_Label": "Genel Ayarlar",
  "units_text_lbl": "Mesafe Birimleri",
  "miles": "Mil",
  "kilometers": "Kilometre",
  "feet": "Fit",
  "meters": "Metre",
  "yards": "Yarda",
  "nauticalMiles": "Deniz Mili",
  "maximum_distance_lbl": "En Yakın Detayın Maksimum Mesafesi",
  "buffer_text_lbl": "Tampon Etiketi",
  "buffer_lbl": "Tampon Mesafesi",
  "buffer_max_lbl": "Maksimum Tampon Mesafesi",
  "buffer_min_lbl": "Minimum Tampon Mesafesi",
  "routing_checkBox": "Rotalamayı Etkinleştir",
  "weather_Label": "Hava Durumu Seçenekleri",
  "weather_checkBox": "Hava Durumu Bilgilerini Ekle",
  "selectLayers": "Hava Durumu Katmanı Seç",
  "currentlySelectedLayer": "Şu Anda Seçili Hava Durumu Katmanları",
  "missingTabLabel": "En az bir sekmenin etiketi yok",
  "missingLayerInWebMap": "Hiçbir işlem katmanı bulunamadı.",
  "selectFields": "Alanları Seç",
  "addField": "Alan Ekle",
  "sum": "TOP",
  "min": "MIN",
  "max": "MAKS",
  "avg": "ORT",
  "count": "SAYIM",
  "area": "ALAN",
  "length": "UZUNLUK",
  "count_checkBox": "Detay Sayısını Görüntüle",
  "area_checkBox": "Alan Toplamını Görüntüle",
  "length_checkBox": "Uzunluk Toplamını Görüntüle",
  "max_records": "Maksimum sınıra ulaşıldı",
  "save_label": "Seçenekleri Kaydet",
  "save_checkbox": "Kaydetmeyi Etkinleştir",
  "csv_label": "CSV Seçenekleri",
  "csv_checkbox": "Katmandaki Tüm Alanları Dışa Aktar",
  "display_label": "Görüntüleme Seçenekleri",
  "display_checkbox": "Özet Detaylarını Görüntüle",
  "must_select_template": "Kaydetme Seçeneklerindeki düzenleme şablonlarından birini seçin.",
  "count_label": "Sayı Etiketi",
  "area_label": "Alan Etiketi",
  "length_label": "Uzunluk Etiketi",
  "invalid_string_width": "Değer çok uzun. ",
  "layer_type_not_supported": "Katman türü desteklenmiyor: ",
  "groupedSummary": "Gruplanan Sayısı",
  "groupByField": "Alana Göre Grupla",
  "labelType": "Etiket Ekle",
  "prefix": "Ön Ek Olarak",
  "suffix": "Son Ek Olarak",
  "need_group_field": "Bir Gruplandırma Ölçütü alanı tanımlamak için Düzenle eylemini kullanın.",
  "fieldTitle": "Alan",
  "typeTitle": "Tür",
  "actionsTitle": "İşlemler"
});