define({
  "_widgetLabel": "Láthatóság",
  "observerLocation": "Megfigyelési hely",
  "formatIconTooltip": "Formátumbemenet",
  "addPointToolTip": "Megfigyelési hely hozzáadása",
  "fieldOfView": "Látótér",
  "useMilsText": "Ezredek használata a szögekhez",
  "observerHeight": "Megfigyelési magasság",
  "minObsDistance": "Min. megfigyelhető távolság",
  "maxObsDistance": "Max. megfigyelhető távolság",
  "taskURLError": "A widget konfigurációs fájlja olyan URL-címet tartalmaz, amely nem érhető el. Forduljon a rendszergazdához.",
  "taskURLInvalid": "A widgettel konfigurált téradatfeldolgozási feladat érvénytelen. Forduljon a rendszergazdához.",
  "viewshedError": "Hiba történt a láthatóság létrehozása közben. Ügyeljen arra, hogy a megfigyelési pozíció a felszínmagasság kiterjedésén belül legyen.</p>",
  "validationError": "<p>A láthatóságot létrehozó űrlapon hiányzó vagy érvénytelen paraméterek találhatók. Ellenőrizze a következőt:</p><ul><li>A megfigyelési hely beállított.</li><li>A megfigyelés látótere nem 0.</li><li>A megfigyelési magasság érvényes értéket tartalmaz.</li><li>A minimális és a maximális megfigyelhető távolság érvényes értéket tartalmaz.</li></ul>",
  "comfirmInputNotation": "Bemeneti jelölés megerősítése",
  "notationsMatch": "A bemenetnek több jelölések felel meg. Pontosítsa, hogy melyiket szeretné használni:",
  "createBtn": "Létrehozás",
  "clearBtn": "Törlés",
  "setCoordFormat": "Koordináta-formátum beállítása",
  "prefixNumbers": "A „+/-” előtag hozzáadása a pozitív és negatív számok jelöléséhez",
  "parseCoordinatesError": "Nem sikerült a koordináták elemzése. Ellenőrizze a bevitt adatokat.",
  "cancelBtn": "Mégse",
  "applyBtn": "Alkalmaz",
  "invalidMessage": "Numerikus értéket adjon meg.",
  "observerRangeMessage": "Érvénytelen megfigyelési magasság",
  "minimumRangeMessage": "Érvénytelen minimális megfigyelhető tartomány",
  "maximumRangeMessage": "A maximális megfigyelhető terjedelemnek nagyobbnak kell lennie a minimális megfigyelhető terjedelemnél, és nem lehet nagyobb, mint ${limit} ${units}.",
  "portalURLError": "Az ArcGIS Online URL-címe vagy a Portal for ArcGIS URL-címe nincs konfigurálva. Forduljon a rendszeradminisztrátorához.",
  "privilegeError": "Az Ön felhasználói szerepe nem alkalmas az elemzés elvégzésére. Az elemzések végrehajtásához az Ön szervezetének adminisztrátora által adott megfelelő <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank”a>jogosultság</a> szükséges.",
  "noServiceError": "A magasságelemzési szolgáltatás nem érhető el. Ellenőrizze az ArcGIS Online vagy a Portal for ArcGIS konfigurációját.",
  "pointToolTooltip": "Kattintson ide a megfigyelési pozíció hozzáadásához",
  "degreesLabel": "fok",
  "milsLabel": "ezred",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "Tized fokok - szélesség/hosszúság",
  "DDLongLatNotation": "Tized fokok - szélesség/hosszúság",
  "DDMLatLongNotation": "Fokok és tized fokpercek - szélesség/hosszúság",
  "DDMLongLatNotation": "Fokok és tized fokpercek - szélesség/hosszúság",
  "DMSLatLongNotation": "Fokok, fokpercek és fokmásodpercek - szélesség/hosszúság",
  "DMSLongLatNotation": "Fokok, fokpercek és fokmásodpercek - hosszúság/szélesség",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - sávbetűjel",
  "UTMHemNotation": "UTM - félteke (É/D)"
});