define({
  "_widgetLabel": "Edit",
  "_featureAction_Edit": "Edit",
  "title": "Pilih template untuk membuat fitur",
  "pressStr": "Tekan ",
  "ctrlStr": " CTRL ",
  "snapStr": " untuk mengaktifkan snapping",
  "close": "Tutup",
  "featureLayers": "Feature layer",
  "searchTemplates": "Cari template",
  "noAvailableTempaltes": "Template tidak tersedia",
  "noCanCreateLayerAreCurrentlyVisible": "Tidak nampak saat ini layer yang dapat dibuat.",
  "layersAreInvisibleOrOutOfScaleRange": "Layer tidak terlihat atau di luar rentang skala.",
  "relatedTables": "Tabel terkait:",
  "relatedRecords": "Catatan terkait:",
  "noRelatedRecotds": "Tidak ada rekaman terkait yang ditemukan",
  "startToDraw": "Klik untuk mulai menggambar",
  "startToAddPoint": "Klik untuk menambahkan titik",
  "editRelatedFeature": "Mengedit fitur terkait",
  "duplicateValueWarning": " Tidak dapat menyisipkan nilai duplikat pada ${fieldName} dari ${tableName}. Nilai duplikat: ${value}"
});