define(
   ({
    addLayer: "Pridėti sluoksnį",
    layerName: "Sluoksnis",
    layerRefresh: "Atnaujinti",
    layerLabel: "Žymė",
    actions: "Veiksmai",
    popupOk: "Gerai",
    popupCancel: "Atšaukti",
    mainPanelTextPlaceholder: "pvz.: GREITKELIO SĄLYGOS",
    invalidInterval: "Palaikomi tik skaitiniai simboliai.",
    uploadImage: "Įkelti vaizdą",
    iconColumnText: "Piktograma",
    refreshInterval: "1 Vertinama kaip laikas minutėmis",
    refreshIntervalTitle: "Vertinama kaip laikas minutėmis",
    mainPanelText: "Pagrindinio skydelio tekstas",
    mainPanelIcon: "Pagrindinio skydelio paveikslėlis",
    refreshIntervalInstruction: "Atnaujinimo intervalas",
    optionsText: "Parinktys",
    symbolOptionsText: "Simbolio parinktys",
    iconOptionsText: "Piktogramos parinktys",
    sympolPopupTitle: "Nustatyti simbolį",
    rdoLayer: "Sluoksnio simbolis",
    rdoCustom: "Asmeninis simbolis",
    chkCluster: "Įgalinti sankaupas",
    defineClusterSymbol: "Sankaupos simbolis",
    defineThemeClusterSymbol: "Sankaupos simbolis iš temos",
    rdoEsri: "Esri simbolis",
    rdoLayerIcon: "Naudoti simbolį kaip piktogramą",
    rdoCustomIcon: "Nusiųsti asmeninę piktogramą",
    editCustomSymbol: "Redaguoti asmeninį simbolį",
    editCustomIcon: "Redaguoti asmeninę piktogramą",
    missingRefreshValue: "Pateikite atnaujinimo intervalo reikšmę.",
    panelIconOption: "Rodyti skydelio antraštę",
    enableRefresh: "Įgalinti sluoksnių naujinimą",
    disableRefresh: "Palaikomas tik elementų rinkinių sluoksnių naujinimas",
    layer_type_not_supported: "Sluoksnio tipas nepalaikomas: "
  })
);
