define({
  "styleText": "Sélectionner un style pour l'outil de balayage",
  "vertical": "Barre verticale",
  "horizontal": "Barre horizontale",
  "scope": "Longue-vue",
  "barColor": "Couleur de la barre",
  "swipeMode": "Mode de balayage",
  "singleLayer": "Couche unique",
  "MultipleLayers": "Couches multiples",
  "allowToSwipe": "Autoriser le balayage",
  "layer": "Couche",
  "swipeByDefault": "Balayage par défaut",
  "defaultLayerMustBeVisible": "La couche par défaut doit être visible.",
  "noDefaultLayer": "Définissez le balayage par défaut des couches.",
  "defaultLayerHolder": "Cliquer pour sélectionner",
  "selectLayers": "Sélectionner des couches",
  "layerText": "Sélectionnez les couches à balayer par défaut.",
  "spyglassText": "Sélectionnez la couche qui doit apparaître dans la longue-vue par défaut.",
  "layerHint": "Remarque : si la couche est masquée par des couches supérieures, le balayage sera sans effet.",
  "isZoom": "Zoomer sur la couche de balayage",
  "isZooms": "Zoomer sur les couches de balayage",
  "layersAvailable": "Choisissez la couche à balayer :"
});