define({
  "_widgetLabel": "Võrgujälitus",
  "configError": "Vidin ei ole õigesti konfigureeritud.",
  "clearButtonValue": "Tühista",
  "GPExecutionFailed": "Jälitust ei saa lõpetada. Palun proovige uuesti",
  "backButtonValue": "Tagasi",
  "exportToCSVSuccess": "Eksportimine CSV-formaati oli edukas.",
  "lblInputLocTab": "Sisendi asukohad",
  "lblBlockLocTab": "Blokeeri asukohad",
  "lblInputLocation": "Sisendobjekt",
  "lblBlockLocation": "Blokeeri objekt",
  "lblInputLocHeader": "Sisendi asukohad (0)",
  "lblBlockLocHeader": "Blokeeri asukohad (0)",
  "inputTabTitle": "Sisend",
  "outputTabTitle": "Väljund",
  "exportSelectAllCheckBoxLabel": "Vali kõik",
  "lblSkipLocHeader": "Jäta asukohad vahele (0)",
  "lblSkipLocation": "Asukoht",
  "lblSkipLocTab": "Jäta asukohad vahele",
  "skipAllLocationButtonLabel": "Jäta kõik asukohad vahele",
  "allLocationSkippedMessage": "Kõik asukohad jäeti vahele",
  "locationAlreadySkippedMessage": "Asukoht on juba vahele jäetud",
  "locationSkippedMessage": "Asukoht jäeti vahele",
  "removeAllSkipLocationLabel": "Eemalda kõik",
  "newProjectOptionText": "Uus projekt",
  "saveButtonLabel": "Salvesta",
  "exportToCSVText": "Ekspordi CSV-formaati",
  "editProjectAttributesToolTip": "Redigeeri projekti atribuute",
  "projectNameLabel": "Projekti nimi",
  "saveProjectPopupTitle": "Salvesta",
  "saveAsLabel": "Salvesta nimega",
  "saveChangesMsg": "Kas soovite salvestada oma muudatused nimega <b>${loadProjectDropdownlabel}</b> või uue projektina?",
  "creatingNewProjectErrorMessage": "Viga uue projekti loomisel. Palun proovige uuesti",
  "projectNameFetchingErr": "Viga olemasolevate projektinimede toomisel. Palun proovige uuesti",
  "projectAttributeLoadingErr": "Viga projekti atribuutide laadimisel. Palun proovige uuesti",
  "attributeUpdatedMsg": "Atribuudid uuendati edukalt.",
  "projectAttributeUpdatingErr": "Viga projekti atribuutide uuendamisel.",
  "loadingProjectDetailsErrorMessage": "Viga lipikute, tõkete ja vahelejäetud asukohtade toomisel. Palun proovige uuesti",
  "savingProjectDetailsErr": "Viga projekti üksikasjade salvestamisel. Palun proovige projekti uuesti salvestada.",
  "updatingOutagePolygonErr": "Viga katkestatud hulknurga uuendamisel. Palun proovige projekti uuesti salvestada.",
  "deletingExistingPolygonErr": "Viga olemasoleva katkestatud hulknurga kustutamisel. Palun proovige projekti uuesti salvestada.",
  "loadingProjectFeaturesErr": "Viga projekti objektide laadimisel. Palun proovige projekti uuesti laadida.",
  "addingProjectFeaturesErr": "Viga projekti objektide lisamisel. Palun proovige projekti uuesti salvestada.",
  "deletingExistingProjectFeaturesErr": "Viga projekti olemasolevate omaduste kustutamisel. Palun proovige projekti uuesti salvestada.",
  "projectNotFoundErr": "Projekti ei leitud",
  "projectLayersNotFound": "Projekti konfigureeritud seadekihid ei ole kaardil saadaval. Vidinat ei saa laadida „visandi režiimis“.",
  "fetchingOutagePolygonMessage": "Viga katkestatud hulknurga toomisel. Palun proovige projekti uuesti laadida.",
  "projectNameExistsMessage": "Projekti nimi on juba olemas. Sisestage projekti unikaalne nimi.",
  "fetchingProjectNamesErrorMessage": "Viga olemasolevate projektinimede toomisel. Palun proovige projekti uuesti salvestada.",
  "enterProjectNameMessage": "Sisestage projekti nimi.",
  "projectLengthErrorMessage": "Projekti nimi ei tohi olla pikem kui",
  "gpServiceNotAccessible": "Teie kontol pole juurdepääsu selle jälituse läbiviimiseks vajalikule teenusele.",
  "loadingClonedLayerErrorMessage": "Viga kloonitud objektikihi laadimisel. Palun proovige uuesti",
  "addingFeatureInClonedLayerError": "Viga graafika lisamisel kloonitud objektikihile. Palun proovige uuesti",
  "selectingFeatureInClonedLayerError": "Viga graafika valimisel kloonitud objektikihis. Palun proovige uuesti",
  "filteredProjectError": "Viga filtreeritud projekti üksikasjade toomise kontrollimisel. Palun proovige uuesti",
  "filteredProjectMessage": "Projekti valitud atribuudid ei ole saadaval filtrite tõttu, mida rakendatakse veebikaardilt või mõnelt muult vidinalt. Kustutage filter (filtrid) ja proovige uuesti.",
  "filteredProjectLoadMessage": "Teie projekt ei ole enam saadaval. Palun valige aktiivne projekt.",
  "defaultValueForRunButton": "Käivita"
});