define({
  "tabs_section_Label": "Záložky",
  "addTab": "Přidat kartu",
  "layerName": "Vrstva",
  "layerType": "Typ analýzy",
  "layerLabel": "Popisek",
  "actions": "Akce",
  "closest": "Nejbližší prvek",
  "proximity": "Obalové zóny, vzdálenost",
  "summary": "Souhrn",
  "select_lbl": "– Vybrat –",
  "general_setting_Label": "Obecná nastavení",
  "units_text_lbl": "Jednotky vzdálenosti",
  "maximum_distance_lbl": "Maximální vzdálenost k nejbližšímu prvku",
  "buffer_text_lbl": "Popisek obalové zóny",
  "buffer_lbl": "Šířka obalové zóny",
  "buffer_max_lbl": "Maximální šířka obalové zóny",
  "buffer_min_lbl": "Minimální šířka obalové zóny",
  "buffer_default_lbl": "Výchozí šířka obalové zóny",
  "not_less_than_max": "Vzdálenost musí být menší než maximální vzdálenost obalové zóny",
  "not_between": "Vzdálenost se musí nacházet mezi minimální a maximální vzdáleností obalové zóny",
  "not_more_than_min": "Vzdálenost musí být větší než minimální vzdálenost obalové zóny",
  "not_valid_number": "Musí se jednat o platné číslo",
  "invalid_value": "Hodnota ${type} je neplatná",
  "routing_checkBox": "Povolit vyhledávání trasy",
  "weather_removed_message": "Pro tento widget již nejsou dostupné možnosti informací o počasí.",
  "currentlySelectedLayer": "Vybrat z vrstev mapy",
  "missingTabLabel": "Nejméně jedna karta neobsahuje popisek.",
  "missingLayerInWebMap": "Nebyly nalezeny žádné operační vrstvy.",
  "selectFields": "Vybrat pole",
  "addField": "Přidat pole",
  "sum": "Suma",
  "min": "Minimum",
  "max": "Maximum",
  "avg": "Průměr",
  "count": "POČET",
  "area": "PLOCHA",
  "length": "DÉLKA",
  "count_checkBox": "Zobrazit počet prvků",
  "area_checkBox": "Zobrazit součet oblasti",
  "length_checkBox": "Zobrazit součet délky",
  "max_records": "Byl dosažen maximální limit",
  "save_label": "Možnosti ukládání",
  "save_checkbox": "Povolit ukládání",
  "report_label": "Možnosti zpráv",
  "report_checkbox": "Povolit zprávy",
  "csv_label": "Možnosti CSV",
  "display_label": "Možnosti zobrazení",
  "display_checkbox": "Zobrazit prvky souhrnu",
  "setSelectionColor": "Nastavte barvu výběru",
  "snapshot_label": "Možnosti snímku",
  "snapshot_checkbox": "Povolit vytvoření snímku",
  "must_select_template": "Vyberte jednu z editačních šablon v možnostech ukládání.",
  "count_label": "Popisek počtu",
  "area_label": "Popisek oblasti",
  "length_label": "Popisek délky",
  "invalid_string_width": "Hodnota je příliš dlouhá. ",
  "layer_type_not_supported": "Typ vrstvy není podporován",
  "groupedSummary": "Počty seskupených",
  "groupByField": "Seskupit podle pole",
  "labelType": "Připojit popisek",
  "prefix": "Jako předponu",
  "suffix": "Jako příponu",
  "need_group_field": "K definování funkce 'Seskupit podle pole' použijte režim Upravit ve sloupci Akce.",
  "fieldTitle": "Pole",
  "typeTitle": "Typ",
  "actionsTitle": "Akce",
  "save_point_checkbox": "Uložit body",
  "save_line_checkbox": "Uložit linie",
  "save_poly_checkbox": "Uložit polygony",
  "no_valid_popup_fields": "Vyskakovací okno neobsahuje žádná platná pole. Definujte pole pomocí akce Upravit.",
  "no_valid_fields": "Žádná platná pole. Definujte možnosti zobrazení pomocí akce Upravit.",
  "incident_label": "Název karty",
  "locate_incident_label": "Název zájmové oblasti",
  "incident": "Událost",
  "locate_incident": "Vyhledat událost",
  "buffer_value": "Šířka obalové zóny",
  "tab_options": "Analýza",
  "export_options": "Výstup",
  "instruction_save": "Uložit polohu do Feature služby",
  "instruction_snapshot": "Vytvořit webovou mapu na základě polohy",
  "instruction_report": "Vytvořit tištěnou zprávu o poloze",
  "instruction_all_fields": "Exportovat pole se stažením ve formátu CSV.",
  "data_label": "Nastavení výstupu dat",
  "layer_error": "Vrstva chybí nebo je neplatná.",
  "visibility_checkBox": "Vypnout správu viditelnosti vrstvy",
  "allFieldsLabel": "Všechna pole",
  "configuredPopUpFieldsLabel": "Konfigurovaná vyskakovací pole",
  "analysisTypeFieldsLabel": "Pole typu analýzy",
  "reportOptionsMsg": "Měla by být vybrána alespoň jedna možnost zprávy.",
  "analysisSummaryLabelForReport": "Souhrn typu analýzy",
  "popUpSummaryLabelForReport": "Souhrn ve formě nakonfigurovaných vyskakovacích polí",
  "downloadTab": {
    "reportLegend": "Nastavení zpráv",
    "textColorLabel": "Vyberte barvu záhlaví sloupce",
    "setButtonLabel": "Nastavit",
    "printGPServiceLabel": "Adresa URL tiskové služby",
    "logoLabel": "Logo",
    "logoChooserHint": "Kliknutím na ikonu obrázku změníte obrázek",
    "footnoteLabel": "Poznámka pod čarou"
  },
  "roundValue": "Zaokrouhlit na",
  "roundValueTitle": "Zaokrouhlit hodnoty polí",
  "truncateValue": "Zkrátit na",
  "truncateValueTitle": "Zkrátit hodnoty polí",
  "significantFigures": "platné číslice",
  "fieldOptions": "Možnosti polí",
  "modifyValues": "Upravit hodnoty polí",
  "validatePlaces": "Musí být celé číslo.",
  "onlyDouble": "Další možnosti polí jsou podporovány pouze pro číselná pole.",
  "layerNotAvalible": "Vrstva nebyla nalezena",
  "missingLayer": "Název: ${name}",
  "missingLayerHint": "Jedna nebo více vrstev uvedených v této konfiguraci nejsou momentálně k dispozici.",
  "drawGeodesic": "Kreslit geodetické tvary"
});