define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Dodajte tačku klikom na mapu",
  "addRingsDtWt": "Dodajte prstenove, vreme vožnje ili vreme pešačenja.",
  "apply": "Primeni",
  "back": "Nazad",
  "colon": ":",
  "creditInformation": "Informacije o kreditu",
  "driveTime": "Vreme vožnje",
  "esriInfographics": "Esri infografika",
  "esriReports": "Esri izveštaji",
  "headerDescription_km": "kilometar",
  "headerDescription_miles": "milja",
  "headerDescription_minutes": "minut",
  "infographics": "Infografika",
  "invalidValueRing": "Vrednost mora da bude u opsegu od 0 do 1.000.",
  "invalidValueDTWT": "Vrednost mora da bude u opsegu od 0 do 300.",
  "km": "km",
  "miles": "milje",
  "minutes": "minuti",
  "myInfographics": "Moja infografika",
  "myReports": "Moji izveštaji",
  "noPermissions": "Vaš nalog ne može da pokrene vidžet Business Analyst.  Da biste pokrenuli vidžet Business Analyst, administrator vaše organizacije treba da vam omogući <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilegije</a> za GeoEnrichment i mrežnu analizu, kao i da vam dodeli <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">kredite</a>.",
  "radii": "poluprečnici",
  "radius": "Poluprečnik",
  "radius_lowercase": "poluprečnik",
  "reports": "Izveštaji",
  "ring": "Prsten",
  "rings": "Prstenovi",
  "runInfographic": "Pokreni infografiku",
  "runReport": "Pokreni izveštaj",
  "selectPointOrPolygon": "Izaberite tačkasti ili poligonalni geoobjekat na mapi, pretražite adresu ili mesto, ili zakačite pribadaču na mapi da iste prikazali više informacija za oblasti.",
  "selectReport": "Izaberite izveštaj",
  "selectTemplate": "Izaberite šablon",
  "sharedInfographics": "Deljena infografika",
  "sharedReports": "Deljeni izveštaji",
  "thisEntryIsNotValid": "Unos nije validan.",
  "time": "Vreme",
  "walkTime": "Vreme pešačenja",
  "widgetDescription": "Pristupite infografici i izveštajima koji sumiraju ključne indikatore i podatke za bilo koju oblast.",
  "None": "Selektovanje..."
});