define({
  "chartSettingLabel": "Diagrammeinstellungen",
  "addNewLabel": "Neue hinzufügen",
  "generalSettingLabel": "Allgemeine Einstellungen",
  "layerChooser": {
    "title": "Layer zur Darstellung auswählen",
    "selectPolygonLayerLabel": "Layer auswählen",
    "selectPolygonLayerHintText": "Hinweis: Wenn Sie mehrere Diagramme darstellen, müssen die Layer denselben Geometrietyp aufweisen",
    "selectRelatedTableLayerLabel": "Mit Layer in Beziehung stehende Tabelle auswählen",
    "selectRelatedTableLayerHintText": "Hinweis: Nur Tabellen mit numerischen Feldern können angezeigt werden",
    "errorInSelectingPolygonLayer": "Wählen Sie einen Layer aus, der einen zugehörigen Punkt-Layer aufweist",
    "errorInSelectingRelatedLayer": "Wählen Sie eine(n) gültige(n) Tabelle/Layer aus, die/der mit dem Layer in Beziehung steht",
    "polygonLayerNotHavingRelationships": "Der ausgewählte Layer weist keine(n) zugehörige(n) Tabelle/Layer auf."
  },
  "ChartSetting": {
    "sectionTitle": "Abschnittstitel",
    "sectionTitleHintText": "Hinweis: Wird in der Überschrift (im Titel) des Abschnitts angezeigt",
    "chartTitle": "Diagrammtitel",
    "chartTitleHintText": "Hinweis: Wird zentriert über dem Diagramm angezeigt",
    "chartDescription": "Beschreibung",
    "chartDescriptionHintText": "Hinweis: Wird unter dem Diagramm angezeigt.",
    "chartType": "Diagrammtyp",
    "barChart": "Balkendiagramm",
    "pieChart": "Kreisdiagramm",
    "polarChart": "Polardiagramm",
    "dataSeriesField": "Datenreihenfeld",
    "labelField": "Beschriftungsfeld",
    "chartColor": "Diagrammfarbe",
    "singleColor": "Einzelfarbe",
    "colorByTheme": "Farbe nach Design",
    "colorByFieldValue": "Farbe nach Feldwert",
    "xAxisTitle": "Titel der X-Achse",
    "xAxisHintText": "Hinweis: Titel der X-Achse",
    "yAxisTitle": "Titel der Y-Achse",
    "yAxisHintText": "Hinweis: Titel der Y-Achse",
    "fieldColorLabel": "Beschriftung",
    "fieldColorColor": "Farbe",
    "defaultFieldSelectLabel": "Auswählen",
    "errMsgFieldValuesNotFound": "Für das ausgewählte Feld konnten keine Werte gefunden werden.",
    "errMsgSectionTitle": "Geben Sie den Abschnittstitel ein.",
    "errMsgFieldByValue": "Wählen Sie den Feldwert aus.",
    "settingTabTitle": "Einstellung",
    "layoutTabTitle": "Layout",
    "polarChartSelectFieldsHintText": "Hinweis: Wählen Sie zum Erstellen des Polardiagramms Felder aus.",
    "visibilityText": "Sichtbarkeit",
    "fieldNameText": "Feldname",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Wählen Sie mindestens drei Felder zum Erstellen des Polardiagramms aus.",
    "polarChartPolygonFillLabel": "Füllpolygon",
    "polarChartPolygonFillHintText": "Hinweis: Aktivieren Sie das Kontrollkästchen, um die Polygonfüllung im Polardiagramm anzuzeigen.",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Desert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Ireland",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Wetland",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Allgemeine Einstellungen",
    "locationSymbolLabel": "Symbol für grafische Position",
    "locationSymbolHintText": "Hinweis: Wird zum Anzeigen eines Symbols für die Adresse und aktivierte Position verwendet",
    "refreshIntervalLabel": "Aktualisierungsintervall",
    "refreshIntervalHintText": "Hinweis: Wird zum Aktualisieren von Diagrammen basierend auf diesem Intervall verwendet. Geben Sie einen Wert zwischen 1 und 1440 Minuten ein.",
    "errMsgRefreshInterval": "Legen Sie das Aktualisierungsintervall auf einen Wert zwischen 0 und 1440 Minuten fest.",
    "symbolPickerPreviewText": "Vorschau:"
  }
});