define({
  "_widgetLabel": "Контроль за ситуацією",
  "locate_incident": "Знайти інцидент",
  "reverse_geocoded_address": "Найближча адреса",
  "reverse_geocoded_error": "Не доступно",
  "actionLabel": "Задати місце розташування",
  "drawPoint": "Намалювати точку",
  "drawLine": "Намалювати лінію",
  "drawPolygon": "Намалювати полігон",
  "saveIncident": "Зберегти",
  "clearIncident": "Розпочати заново",
  "noFeaturesFound": "Об'єкти не знайдено.",
  "downloadCSV": "Завантажити",
  "sum": "Сума",
  "min": "Мінімум",
  "max": "Максимум",
  "avg": "Середнє",
  "count": "ЛІЧИЛЬНИК",
  "area": "ПЛОЩА",
  "length": "ДОВЖИНА",
  "update_btn": "Завершено",
  "delete_btn": "Видалити",
  "get_directions": "Отримати напрямки",
  "incident": "Інцидент",
  "incidents": "Інциденти",
  "buffer": "Буфер",
  "buffers": "Буфери",
  "_featureAction_ActionLabel": "Задати місце розташування",
  "_featureAction_AddRemoveActionLabel": "Додати/вилучити місце розташування",
  "snapshot": "Ідентифікатор папки «Знімок», створеної додатком:",
  "user_credentials": "Користувач не має дійсних прав.",
  "notPolySnapShot": "Вкажіть відстань буфера перед створенням знімку.",
  "notPolyReport": "Відсутні дійсні результати для додання у звіт.",
  "notValidDownload": "Відсутні дійсні результати для завантаження.",
  "of_append": "з",
  "layer_append": "шар",
  "downloadAll": "Завантажити всі",
  "createSnapshot": "Створити знімок",
  "createReport": "Створити звіт",
  "calculated_results": "Узагальнена інформація",
  "closest": "Найближчий об'єкт",
  "proximity": "Наближеність",
  "summary": "Коротка інформація",
  "groupedSummary": "Згруповані лічильники",
  "_count": "Лічильник",
  "approximate": "приблизний",
  "snapshot_name": "Задати властивості знімку",
  "report_name": "Задати властивості звіту",
  "invalid_snapshot_name": "Недійсна назва знімку.",
  "invalid_report_name": "Недійсний заголовок звіту.",
  "orientation": "Орієнтація",
  "pageSize": "Розмір сторінки",
  "comments": "Коментарі",
  "choose_group": "Групи",
  "forecast": "Прогноз",
  "select_group": "Вибрати групу",
  "select_group_instruction": "Знімок буде створено та надано у спільне використання вибраній групі",
  "information_append": " Інформація",
  "distance": "ВІДСТАНЬ",
  "buffer_invalid": "Введіть дійсне число від ${min} до ${max}",
  "layerNotAvalible": "Шар не знайдено",
  "missingLayer": "Ім'я: ${name}",
  "missingLayerHint": "Один або більше шарів, на які є посилання в цій конфігурації, на поточний момент не доступні."
});