define({
  "addLocation": "Přidat jednotky polohy",
  "addDistance": "Přidat jednotky délky",
  "addArea": "Přidat jednotky plochy",
  "label": "Popisek",
  "abbr": "Zkratka",
  "conversion": "Konverze",
  "actions": "Akce",
  "areaUnits": "Jednotky plochy",
  "distanceUnits": "Jednotky délky",
  "kilometers": "Kilometry",
  "miles": "míle",
  "meters": "metry",
  "feet": "Stopy",
  "yards": "Yardy",
  "nauticalmiles": "námořní míle",
  "squareKilometers": "Čtvereční kilometry",
  "squareMiles": "Čtvereční míle",
  "acres": "Akry",
  "hectares": "Hektary",
  "squareMeters": "Čtvereční metry",
  "squareFeet": "Čtvereční stopy",
  "squareYards": "Čtvereční yardy",
  "location": "Poloha",
  "distance": "Vzdálenosti",
  "area": "Plochy",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "míle",
  "metersAbbreviation": "m",
  "feetAbbreviation": "stopy",
  "yardsAbbreviation": "yd",
  "nauticalmilesAbbreviation": "nm",
  "squareKilometersAbbreviation": "čtver. km",
  "squareMilesAbbreviation": "čtver. míl.",
  "acresAbbreviation": "akr",
  "hectaresAbbreviation": "ha",
  "squareMetersAbbreviation": "čtver. m",
  "squareFeetAbbreviation": "čtver. stopy",
  "squareYardsAbbreviation": "čtver. yd.",
  "defineUnits": "Definujte jednotky měření.",
  "operationalLayer": "Přidat kresbu do mapy jako operační vrstvu."
});