define({
  "defaultAreaUnit": "Unità di superficie predefinita",
  "defaultLengthUnit": "Unità di lunghezza predefinita",
  "acres": "Acri",
  "sqMiles": "Miglia quadre",
  "sqKilometers": "Chilometri quadri",
  "hectares": "Ettari",
  "sqYards": "Iarde quadre",
  "sqFeet": "Piedi quadri",
  "sqFeetUS": "Piede quadrato (USA)",
  "sqMeters": "Metri quadri",
  "miles": "Miglia",
  "kilometers": "Chilometri",
  "feet": "Piedi",
  "feetUS": "Piede (USA)",
  "meters": "Metri",
  "yards": "Iarde",
  "nauticalMiles": "Miglia nautiche",
  "showArea": "Area",
  "showDistance": "Distanza",
  "showLocation": "Posizione",
  "showtools": "Mostra strumenti di misurazione:",
  "allHidedTips": "Selezionare almeno uno strumento."
});