define({
  "_widgetLabel": "Svesnost situacije",
  "locate_incident": "Lociraj incident",
  "clear_incidents": "Obriši incidente",
  "reverse_geocoded_address": "Najbliža adresa",
  "reverse_geocoded_error": "Nije dostupno",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "now": "SADA",
  "wind": "VETAR",
  "SUN": "NED",
  "MON": "PON",
  "TUE": "UTO",
  "WED": "SRE",
  "THU": "ČET",
  "FRI": "PET",
  "SAT": "SUB",
  "defaultTabMsg": "Definišite oblast incidenta.",
  "actionLabel": "Postavi kao incident",
  "drawPoint": "Nacrtaj tačku",
  "drawLine": "Nacrtaj liniju",
  "drawPolygon": "Nacrtaj poligon",
  "saveIncident": "Sačuvaj incident",
  "clearIncident": "Obriši incident",
  "useMapExtent": "Koristi trenutni obuhvat mape",
  "noFeaturesFound": "Nema pronađenih geoobjekata.",
  "downloadCSV": "PREUZMI CSV",
  "editComplete": "Geoobjekat uspešno sačuvan.",
  "updateComplete": "Geoobjekat uspešno ažuriran.",
  "deleteComplete": "Geoobjekat uspešno obrisan.",
  "sum": "ZBIR",
  "min": "MIN",
  "max": "MAKS",
  "avg": "PROS.",
  "count": "BROJAČ",
  "area": "POVRŠINA",
  "length": "DUŽINA",
  "notPolySave": "Definišite rastojanje zone bliskosti pre čuvanja.",
  "update_btn": "Završeno",
  "delete_btn": "Obriši",
  "get_directions": "Traži uputstva za navigaciju",
  "incident": "Incident",
  "weather": "Vreme",
  "poweredBy": "Omogućeno od"
});