define({
  "defaultAreaUnit": "Unidade de Área Padrão",
  "defaultLengthUnit": "Unidade de Comprimento Padrão",
  "acres": "Acres",
  "sqMiles": "Milhas Quadradas",
  "sqKilometers": "Quilômetros Quadrados",
  "hectares": "Hectares",
  "sqYards": "Jardas Quadradas",
  "sqFeet": "Pés Quadrados",
  "sqFeetUS": "Pés Quadrados (US)",
  "sqMeters": "Metros Quadrados",
  "miles": "Milhas",
  "kilometers": "Quilômetros",
  "feet": "Pés",
  "feetUS": "Pés (US)",
  "meters": "Metros",
  "yards": "Jardas",
  "nauticalMiles": "Milhas Náuticas",
  "showArea": "Área",
  "showDistance": "Distância",
  "showLocation": "Localização",
  "showtools": "Mostrar ferramentas de medição:",
  "allHidedTips": "Pelo menos uma ferramenta deve ser selecionada."
});