define({
  "businessAnalyst": "Business Analyst",
  "defineWhichInfographics": "Definiți ce grafice informative sunt disponibile în widget:",
  "defineWhichReports": "Definiți ce rapoarte sunt disponibile în widget:",
  "defaultValues": "Valori implicite:",
  "disable": "Dezactivare",
  "driveTime": "Timp de conducere",
  "infographics": "Grafice informative",
  "invalidValueRing": "Valorile trebuie să fie cuprinse între 0 și 1.000.",
  "invalidValueDTWT": "Valorile trebuie să fie cuprinse între 0 și 300.",
  "km": "km",
  "miles": "mile",
  "minutes": "minute",
  "radius": "Rază",
  "reports": "Rapoarte",
  "rings": "Inele",
  "selectCountry": "Selectați țara:",
  "thisEntryIsNotValid": "Această intrare nu este validă.",
  "time": "Timp",
  "walkTime": "Timp de deplasare"
});