define({
  "_widgetLabel": "Wyświetl",
  "selectDrawMode": "Wybierz tryb rysowania",
  "clear": "Wyczyść",
  "point": "Punkt",
  "line": "Linia",
  "polyline": "Polilinia",
  "freehandPolyline": "Polilinia odręczna",
  "triangle": "Trójkąt",
  "extent": "Obwiednia",
  "circle": "Koło",
  "ellipse": "Elipsa",
  "polygon": "Poligon",
  "freehandPolygon": "Poligon odręczny",
  "text": "Tekst",
  "style": "Styl",
  "alpha": "Przezroczystość",
  "width": "Szerokość",
  "size": "Rozmiar",
  "color": "Kolor",
  "markerColor": "Kolor sygnatury",
  "outlineColor": "Kolor obrysu",
  "lineColor": "Kolor linii",
  "fillColor": "Kolor wypełnienia",
  "showMeasurements": "Pokaż pomiary",
  "showLocationMeasurement": "Pokaż pomiar lokalizacji",
  "showAreaMeasurement": "Pokaż pomiar pola powierzchni",
  "showDistanceMeasurement": "Pokaż pomiar odległości",
  "showDistanceMeasurementForLine": "Pokaż pomiar długości",
  "showDistanceMeasurementForPolygon": "Pokaż pomiar obwodu",
  "locationToggleOn": "Naciśnij przełącznik, aby wyświetlić pomiar lokalizacji",
  "locationToggleOff": "Naciśnij przełącznik, aby ukryć pomiar lokalizacji",
  "areaToggleOn": "Naciśnij przełącznik, aby wyświetlić pomiar pola powierzchni",
  "areaToggleOff": "Naciśnij przełącznik, aby ukryć pomiar pola powierzchni",
  "distanceForLineToggleOn": "Naciśnij przełącznik, aby wyświetlić pomiar długości",
  "distanceForLineToggleOff": "Naciśnij przełącznik, aby ukryć pomiar długości",
  "distanceForPolygonToggleOn": "Naciśnij przełącznik, aby wyświetlić pomiar obwodu",
  "distanceForPolygonToggleOff": "Naciśnij przełącznik, aby ukryć pomiar obwodu",
  "areaUnits": "Jednostki powierzchni",
  "distanceUnits": "Jednostki odległości",
  "kilometers": "Kilometry",
  "miles": "Mile",
  "meters": "Metry",
  "feet": "Stopy",
  "yards": "Jardy",
  "nauticalmiles": "Mile morskie",
  "squareKilometers": "Kilometry kwadratowe",
  "squareMiles": "Mile kwadratowe",
  "acres": "Akry",
  "hectares": "Hektary",
  "squareMeters": "Metry kwadratowe",
  "squareFeet": "Stopy kwadratowe",
  "squareYards": "Jardy kwadratowe",
  "undo": "Cofnij",
  "redo": "Ponów",
  "results": "Wyniki",
  "points": "Punkty",
  "lines": "Linie",
  "areas": "Powierzchnie",
  "locationLabel": "Lokalizacja: ${value}",
  "areaLabel": "Pole powierzchni: ${value} ${unit}",
  "distanceLabel": "Odległość: ${value} ${unit}",
  "distanceLabelForLine": "Długość: ${value} ${unit}",
  "distanceLabelForPolygon": "Obwód: ${value} ${unit}"
});