define({
  "tabs_section_Label": "タブ",
  "addTab": "タブの追加",
  "layerName": "レイヤー",
  "layerType": "分析タイプ",
  "layerLabel": "ラベル",
  "actions": "アクション",
  "closest": "最近隣フィーチャ",
  "proximity": "近接",
  "summary": "サマリー",
  "select_lbl": "-- 選択 --",
  "general_setting_Label": "一般設定",
  "units_text_lbl": "距離単位",
  "maximum_distance_lbl": "最近隣フィーチャの最大距離",
  "buffer_text_lbl": "バッファー ラベル",
  "buffer_lbl": "バッファー距離",
  "buffer_max_lbl": "最大バッファー距離",
  "buffer_min_lbl": "最小バッファー距離",
  "buffer_default_lbl": "デフォルトのバッファー距離",
  "not_less_than_max": "距離は最大バッファー距離より小さい必要があります。",
  "not_between": "距離は最小バッファー距離から最大バッファー距離までの範囲内でなければなりません。",
  "not_more_than_min": "距離は最小バッファー距離より大きくなければなりません。",
  "not_valid_number": "有効な値でなくてはなりません。",
  "invalid_value": "${Type} 値が無効です。",
  "routing_checkBox": "ルート検索の有効化",
  "weather_removed_message": "天気オプションは、このウィジェットでは使用できなくなりました。",
  "currentlySelectedLayer": "マップ レイヤーから選択",
  "missingTabLabel": "少なくとも 1 つのタブにラベルがありません",
  "missingLayerInWebMap": "操作レイヤーが見つかりません",
  "selectFields": "フィールド選択",
  "addField": "フィールドの追加",
  "sum": "合計",
  "min": "最小",
  "max": "最大",
  "avg": "平均",
  "count": "総数",
  "area": "面積",
  "length": "長さ",
  "count_checkBox": "フィーチャ数の表示",
  "area_checkBox": "面積の合計の表示",
  "length_checkBox": "長さの合計の表示",
  "max_records": "最大制限に達しました",
  "save_label": "保存オプション",
  "save_checkbox": "保存の有効化",
  "report_label": "レポート オプション",
  "report_checkbox": "レポートの有効化",
  "csv_label": "CSV オプション",
  "display_label": "表示オプション",
  "display_checkbox": "集計フィーチャの表示",
  "setSelectionColor": "選択色の設定",
  "snapshot_label": "スナップショット オプション",
  "snapshot_checkbox": "スナップショットの有効化",
  "must_select_template": "保存オプションで編集テンプレートのいずれかを選択してください。",
  "count_label": "数のラベル",
  "area_label": "面積のラベル",
  "length_label": "長さのラベル",
  "invalid_string_width": "値が長すぎます。 ",
  "layer_type_not_supported": "レイヤー タイプがサポートされていません",
  "groupedSummary": "グループ化された数",
  "groupByField": "フィールドでグループ化",
  "labelType": "ラベルの追加",
  "prefix": "接頭辞として",
  "suffix": "接尾辞として",
  "need_group_field": "[フィールドでグループ化] を定義するには、編集アクションを使用してください。",
  "fieldTitle": "フィールド",
  "typeTitle": "タイプ",
  "actionsTitle": "アクション",
  "save_point_checkbox": "ポイントの保存",
  "save_line_checkbox": "ラインの保存",
  "save_poly_checkbox": "ポリゴンの保存",
  "no_valid_popup_fields": "ポップアップに有効なフィールドがありません。 フィールドを定義するには、編集アクションを使用してください。",
  "no_valid_fields": "有効なフィールドがありません。 表示オプションを定義するには、編集アクションを使用してください。",
  "incident_label": "タブのラベル",
  "locate_incident_label": "表示領域のラベル",
  "incident": "インシデント",
  "locate_incident": "インシデントの特定",
  "buffer_value": "バッファー距離",
  "tab_options": "解析",
  "export_options": "出力",
  "instruction_save": "位置をフィーチャ サービスに保存します。",
  "instruction_snapshot": "位置に基づいて Web マップを作成します。",
  "instruction_report": "位置の印刷レポートを作成します。",
  "instruction_all_fields": "CSV のダウンロードでフィールドをエクスポートします。",
  "data_label": "データ出力設定",
  "layer_error": "レイヤーが見つからないか無効です。",
  "visibility_checkBox": "レイヤー表示設定管理の無効化",
  "allFieldsLabel": "すべてのフィールド",
  "configuredPopUpFieldsLabel": "構成されたポップアップ フィールド",
  "analysisTypeFieldsLabel": "解析タイプ フィールド",
  "reportOptionsMsg": "最低 1 つのレポート オプションを選択する必要があります",
  "analysisSummaryLabelForReport": "解析タイプ サマリー",
  "popUpSummaryLabelForReport": "構成されたポップアップ フィールド サマリー",
  "downloadTab": {
    "reportLegend": "レポート設定",
    "textColorLabel": "列ヘッダーの色を選択",
    "setButtonLabel": "設定",
    "printGPServiceLabel": "印刷サービスの URL",
    "logoLabel": "ロゴ",
    "logoChooserHint": "画像アイコンをクリックして画像を変更",
    "footnoteLabel": "脚注"
  },
  "roundValue": "丸める",
  "roundValueTitle": "フィールド値を丸める",
  "truncateValue": "切り捨て",
  "truncateValueTitle": "切り捨て",
  "significantFigures": "有効数字",
  "fieldOptions": "フィールド オプション",
  "modifyValues": "フィールド値の変更",
  "validatePlaces": "整数でなければなりません",
  "onlyDouble": "追加フィールド オプションは、数値フィールドでのみサポートされています。",
  "layerNotAvalible": "レイヤーが見つかりません",
  "missingLayer": "名前: ${name}",
  "missingLayerHint": "この構成で参照されている 1 つ以上のレイヤーが現在利用できません。",
  "drawGeodesic": "測地線の形状の描画"
});