define({
  "tabs_section_Label": "Kartice",
  "addTab": "Dodaj karticu",
  "layerName": "Sloj",
  "layerType": "Tip analize",
  "layerLabel": "Oznaka",
  "actions": "Radnje",
  "closest": "Najbliži geoobjekat",
  "proximity": "Blizina",
  "summary": "Rezime",
  "select_lbl": "-- Izaberi --",
  "general_setting_Label": "Opšte postavke",
  "units_text_lbl": "Jedinice rastojanja",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "maximum_distance_lbl": "Maksimalna udaljenost najbližeg geoobjekta",
  "buffer_text_lbl": "Oznaka zone bliskosti",
  "buffer_lbl": "Rastojanje zone bliskosti",
  "buffer_max_lbl": "Maksimalno rastojanje zone bliskosti",
  "buffer_min_lbl": "Minimalno rastojanje zone bliskosti",
  "routing_checkBox": "Omogući rutiranje",
  "weather_Label": "Opcije vremena",
  "weather_checkBox": "Uključi informacije o vremenu",
  "selectLayers": "Izaberite slojeve vremena",
  "currentlySelectedLayer": "Trenutno izabrani slojevi vremena",
  "missingTabLabel": "Bar jednoj kartici nedostaje oznaka",
  "missingLayerInWebMap": "Nema pronađenih operativnih slojeva.",
  "selectFields": "Izaberi polja",
  "addField": "Dodaj polje",
  "sum": "ZBIR",
  "min": "MIN",
  "max": "MAKS",
  "avg": "PROS.",
  "count": "BROJAČ",
  "area": "POVRŠINA",
  "length": "DUŽINA",
  "count_checkBox": "Prikaži izbrojane geoobjekte",
  "area_checkBox": "Prikaži sumu površina",
  "length_checkBox": "Prikaži sumu dužina",
  "max_records": "Maksimalno ograničenje je dostignuto",
  "save_label": "Opcije čuvanja",
  "save_checkbox": "Omogući čuvanje",
  "csv_label": "Opcije CSV datoteke",
  "csv_checkbox": "Izvezite sva polja u sloju.",
  "display_label": "Opcije prikaza",
  "display_checkbox": "Prikaži sumu geoobjekata",
  "must_select_template": "Izaberite jedan od šablona izmena u opcijama čuvanja.",
  "count_label": "Oznaka brojača",
  "area_label": "Oznaka oblasti",
  "length_label": "Oznaka dužine",
  "invalid_string_width": "Vrednost je suviše duga. ",
  "layer_type_not_supported": "Tip sloja nije podržan: ",
  "groupedSummary": "Grupisani brojači",
  "groupByField": "Polje „Grupiši na osnovu“",
  "labelType": "Dodaj oznaku",
  "prefix": "Kao prefiks",
  "suffix": "Kao sufiks",
  "need_group_field": "Koristite radnju Izmeni kako biste definisali polje „Grupiši na osnovu“.",
  "fieldTitle": "Polje",
  "typeTitle": "Tip",
  "actionsTitle": "Radnje"
});