define({
  "_widgetLabel": "Diagram",
  "executeChartTip": "Klikk på ett av følgende oppgaveelementer for å lage diagrammet.",
  "invalidConfig": "Ugyldig konfigurasjon.",
  "noneChartTip": "Ingen diagramoppgave er konfigurert for dette miniprogrammet.",
  "chartParams": "Alternativer",
  "charts": "DIAGRAMMER",
  "apply": "BRUK",
  "useSpatialFilter": "Bruk geografisk filter til å begrense antall geoobjekter",
  "useCurrentMapExtent": "Bare geoobjekter som krysser det gjeldende kartområdet",
  "drawGraphicOnMap": "Bare geoobjekter som krysser et brukerdefinert område",
  "chartResults": "Diagramresultater",
  "clearResults": "Fjern resultater",
  "noPermissionsMsg": "Du har ikke tillatelse til å bruke denne tjenesten.",
  "specifySpatialFilterMsg": "Angi et romlig filter for denne oppgaven.",
  "queryError": "Spørringen mislyktes.",
  "noResults": "Fant ingen geoobjekter.",
  "category": "Kategori",
  "count": "Antall",
  "label": "Etikett",
  "horizontalAxis": "Horisontal akse",
  "verticalAxis": "Vertikal akse",
  "dataLabels": "Dataetikketter",
  "color": "Farge",
  "colorful": "Fargerik",
  "monochromatic": "Monokromatisk",
  "tasks": "Oppgaver",
  "results": "Resultater",
  "applySpatialFilterToLimitResults": "Bruk et romlig filter til å begrense resultatene",
  "useCurrentExtentTip": "Delvis eller helt innenfor gjeldende kartutstrekning",
  "useDrawGraphicTip": "Delvis eller helt innenfor formen tegnet på kartet",
  "useFeaturesTip": "Basert på deres lokasjoner i forhold til geoobjekter i andre lag",
  "noSpatialLimitTip": "Ikke bruk romlig begrensing på resultater",
  "applySearchDistance": "Bruk en søkeavstand",
  "spatialRelationship": "Romlig relasjon",
  "relatedLayer": "Relatert lag",
  "clear": "Tøm",
  "bufferDistance": "Bufferavstand",
  "miles": "Miles",
  "kilometers": "Kilometer",
  "feet": "Fot",
  "meters": "Meter",
  "yards": "Yards",
  "nauticalMiles": "Nautiske mil",
  "back": "Tilbake",
  "execute": "Bruk",
  "backCharts": "Tilbake til diagrammer",
  "backOptions": "Tilbake til alternativer",
  "clearCharts": "Fjern alle diagrammer"
});