define({
  "_widgetLabel": "Piešti",
  "selectDrawMode": "Pasirinkti piešimo režimą",
  "clear": "Valyti",
  "point": "Taškas",
  "line": "Linija",
  "polyline": "Kreivė",
  "freehandPolyline": "Laisvai piešiama kreivė",
  "triangle": "Trikampis",
  "extent": "Apgaubas",
  "circle": "Apskritimas",
  "ellipse": "Elipsė",
  "polygon": "Plotas",
  "freehandPolygon": "Laisvai piešiamas poligonas",
  "text": "Tekstas",
  "style": "Stilius",
  "alpha": "Permatomumas",
  "width": "Plotis",
  "size": "Dydis",
  "color": "Spalva",
  "markerColor": "Žymeklio spalva",
  "outlineColor": "Kontūro spalva",
  "lineColor": "Linijos spalva",
  "fillColor": "Užpildo spalva",
  "showMeasurements": "Rodyti matavimus",
  "showLocationMeasurement": "Rodyti vietos matmenis",
  "showAreaMeasurement": "Rodyti ploto matmenis",
  "showDistanceMeasurement": "Rodyti atstumo matmenis",
  "showDistanceMeasurementForLine": "Rodyti ilgio matmenis",
  "showDistanceMeasurementForPolygon": "Rodyti perimetro matmenis",
  "locationToggleOn": "Paspauskite perjungimo mygtuką, kad būtų rodomas padėties matmuo",
  "locationToggleOff": "Paspauskite perjungimo mygtuką, kad nebūtų rodomas padėties matmuo",
  "areaToggleOn": "Paspauskite perjungimo mygtuką, kad būtų rodomas ploto matmuo",
  "areaToggleOff": "Paspauskite perjungimo mygtuką, kad nebūtų rodomas ploto matmuo",
  "distanceForLineToggleOn": "Paspauskite perjungimo mygtuką, kad būtų rodomas ilgio matmuo",
  "distanceForLineToggleOff": "Paspauskite perjungimo mygtuką, kad nebūtų rodomas ilgio matmuo",
  "distanceForPolygonToggleOn": "Paspauskite perjungimo mygtuką, kad būtų rodomas perimetro matmuo",
  "distanceForPolygonToggleOff": "Paspauskite perjungimo mygtuką, kad nebūtų rodomas perimetro matmuo",
  "areaUnits": "Ploto vienetai",
  "distanceUnits": "Atstumo vienetai",
  "kilometers": "Kilometrai",
  "miles": "Mylios",
  "meters": "Metrai",
  "feet": "Pėdos",
  "yards": "Jardai",
  "nauticalmiles": "Jūrmylės",
  "squareKilometers": "Kvadratiniai kilometrai",
  "squareMiles": "Kvadratinės mylios",
  "acres": "Akrai",
  "hectares": "Hektarai",
  "squareMeters": "Kvadratiniai metrai",
  "squareFeet": "Kvadratinė pėda",
  "squareYards": "Kvadratiniai jardai",
  "undo": "Atšaukti",
  "redo": "Grąžinti",
  "results": "Rezultatai",
  "points": "Taškai",
  "lines": "Linijos",
  "areas": "Plotai",
  "locationLabel": "Vieta: ${value}",
  "areaLabel": "Plotas: ${value} ${unit}",
  "distanceLabel": "Atstumas: ${value} ${unit}",
  "distanceLabelForLine": "Ilgis: ${value} ${unit}",
  "distanceLabelForPolygon": "Perimetras: ${value} ${unit}"
});