define({
  "searchTabTitle": "Broninstelling zoeken",
  "routeTabTitle": "Route-instelling",
  "add": "Zoekbron toevoegen",
  "addGeocoder": "Geocoder toevoegen",
  "geocoder": "Geocoder",
  "setLayerSource": "Laagbron instellen",
  "setGeocoderURL": "Geocoder-URL instellen",
  "searchableLayer": "Objectlaag",
  "name": "Naam",
  "countryCode": "Land- of regiocode(s)",
  "countryCodeEg": "bijv. ",
  "countryCodeHint": "Laat deze waarde leeg en alle landen en regio's worden doorzocht",
  "showInfoWindowOnSelect": "Pop-up weergeven voor gevonden object of locatie",
  "showInfoWindowOnSelect2": "Toon pop-up als het object of de locatie gevonden is.",
  "searchInCurrentMapExtent": "Alleen zoeken in huidige kaartextent",
  "setSearchFields": "Zoekvelden instellen",
  "set": "Instellen",
  "fieldSearchable": "doorzoekbaar",
  "zoomScale": "Schaal voor voor in-/uitzoomen",
  "locatorUrl": "Geocoder-URL",
  "locatorName": "Naam van geocoder",
  "locatorExample": "Voorbeeld",
  "locatorWarning": "Deze versie van de geocodeerservice wordt niet ondersteund. De widget ondersteunt geocodeerservice 10.1 en hoger.",
  "locatorTips": "Suggesties zijn niet beschikbaar omdat de geocodeerservice geen suggesties ondersteunt.",
  "layerSource": "Laagbron",
  "searchLayerTips": "Suggesties zijn niet beschikbaar omdat de feautureservice geen paginering ondersteunt.",
  "placeholderText": "Tekst van tijdelijke aanduiding",
  "searchFields": "Zoekvelden",
  "displayField": "Weergaveveld",
  "exactMatch": "Exacte match",
  "maxSuggestions": "Maximale suggesties",
  "maxResults": "Maximum aantal resultaten",
  "enableLocalSearch": "Lokaal zoeken inschakelen",
  "minScale": "Min.schaal",
  "minScaleHint": "Als de kaartschaal groter is dan deze schaal, dan zal lokaal zoeken toegepast worden",
  "radius": "Straal",
  "radiusHint": "Bepaalt de straal van een gebied rond het midden van de huidige kaart, die gebruikt wordt om de rangorde van geocoding-kandidaten te versterken zodat kandidaten die het dichtst in de buurt zijn eerst weergegeven worden",
  "invalidUrlTip": "De URL ${URL} is ongeldig of ontoegankelijk.",
  "routeUrl": "Route-URL",
  "geocoderOptions": "Geocodingopties",
  "autoComplete": "Automatisch invullen",
  "maximumSuggestions": "Maximale suggesties",
  "minCharacters": "Minimale tekens",
  "searchDelay": "Zoekvertraging",
  "placeholder": "Tijdelijke aanduiding",
  "routeOptions": "Routeopties",
  "directionsLanguage": "Taal van de routebeschrijving",
  "directionsLengthUnits": "Lengte-eenheden van de routebeschrijving",
  "directionsOutputType": "Uitvoertype van de routebeschrijving",
  "impedanceAttribute": "Impedantieattribuut",
  "kilometers": "Kilometer",
  "miles": "Mijl",
  "meters": "Meter",
  "feet": "Voet",
  "yards": "Yard",
  "nauticalMiles": "Zeemijl",
  "parametersTip": "Stel de parameters correct in!",
  "complete": "Voltooid",
  "completeNoEvents": "Voltooid geen gebeurtenissen",
  "instructionsOnly": "Alleen instructies",
  "standard": "Standaard",
  "summaryOnly": "Alleen samenvatting",
  "travelModesUrl": "URL Reismodi",
  "searchPlaceholder": "Adres of plaats zoeken",
  "trafficLayerUrl": "URL van verkeerlaag",
  "barrierLayerUrl": "URL van barrièrelaag",
  "presetDestinations": "Preset stops",
  "startPoint": "Startpunt",
  "endPoint": "Eindpunt",
  "destinationHolder": "Adres of coördinaten",
  "optional": "Optioneel.",
  "barrierLayers": "Barrièrelagen",
  "pointBarrier": "Puntbarrières",
  "lineBarrier": "Lijnbarrières",
  "polygonBarrier": "Polygoonbarrières",
  "noPointBarrier": "Puntbarrières kiezen",
  "noLineBarrier": "Lijnbarrières kiezen",
  "noPolygonBarrier": "Polygoonbarrières kiezen"
});