define({
  "settings": "Configurações",
  "titleSettings": "Configurações de texto",
  "imageSettings": "Configurações de imagem",
  "backgroundColor": "Cor do plano de fundo",
  "alignment": "Alinhamento",
  "textSize": "Tamanho de texto",
  "textColor": "Cor de texto",
  "dataSource": "Fonte de dados",
  "chartSettings": "Configurações do gráfico",
  "data": "Dados",
  "dataLabels": "Rótulos de dados",
  "displayMode": "Modo de Visualização",
  "featureOption": "Exibir valores feição por feição",
  "categoryOption": "Exibir valores por categoria",
  "countOption": "Exibir contagem de feição por categoria",
  "fieldOption": "Exibir valores de atributo como gráficos",
  "categoryField": "Campo de Categoria",
  "labelField": "Campo de rótulo",
  "valueFields": "Campos de valores",
  "operation": "Operação",
  "sumOption": "Soma",
  "averageOption": "Média",
  "minOption": "Mínimo",
  "maxOption": "Máximo",
  "dataFormat": "Formato dos dados",
  "decimalPlaces": "Casas decimais",
  "prefix": "Prefixo",
  "suffix": "Sufixo",
  "dataType": "Tipo de dados",
  "featureCount": "Contagem de feições",
  "fieldStatistics": "Estatística de campo",
  "display": "Exibir",
  "chartColor": "Cor do gráfico",
  "horizontalAxis": "Eixo horizontal",
  "verticalAxis": "Eixo vertical",
  "legend": "Legenda",
  "position": "Posição",
  "top": "Superior",
  "bottom": "Inferior",
  "useDataSourceSelection": "Utilizar seleção",
  "dataSourceFilterByExtent": "Filtrar por extensão",
  "changeTemplate": "Alterar modelo",
  "numberSettings": "Configurações de número",
  "gaugeSettings": "Configurações do Medidor",
  "indicators": "Indicadores",
  "ifValue": "Se valor",
  "and": "l",
  "numberOperatorIsLessThan": "é menor que",
  "numberOperatorIsGreaterThan": "é maior que",
  "numberOperatorIsBetween": "está entre",
  "numberOperatorIsEqual": "é igual a",
  "numberOperatorIsNotEqual": "não é igual a",
  "then": "Então",
  "ratio": "Taxa",
  "trueValue": "Valor verdadeiro",
  "changeValueColor": "altera cor de valor para",
  "changeGaugeColor": "altere cor de medidor para",
  "setIndicatorIcon": "configurar ícone de indicador como",
  "icons": "Ícones",
  "style": "Estilo",
  "placement": "Disposição",
  "left": "Esquerda",
  "replace": "Substituir",
  "right": "Direita",
  "color": "Cor",
  "dataRange": "Faixa de dados",
  "targetValue": "Valor de alvo",
  "currentValue": "Valor atual",
  "gaugeColor": "Cor do medidor",
  "min": "Mínimo",
  "max": "Máximo",
  "displayValueIn": "Exibe o valor em",
  "noData": "Sem dados",
  "thousandAbbreviation": "k",
  "millionAbbreviation": "M",
  "billionAbbreviation": "G",
  "warning": "Aviso",
  "noSettingWaring1": "Clique em um elemento para configurar suas propriedades.",
  "noSettingWaring2": "Arraste para dimensionar ou reordenar um elemento.",
  "donNotShowAgain": "Não mostrar novamente",
  "changeTemplateWarning": "Isto apagará todas suas configurações e abre um novo modelo vazio.",
  "requiredFieldWarning": "Este valor é exigido:",
  "dataSourceNotSet": "Configure a fonte de dados.",
  "addIndicatorTip": "Adicionar um indicador",
  "chooseTemplatePopupTitle": "Escolher um modelo",
  "stringsInTemplate": {
    "name_number": "Número",
    "name_gauge": "Medidor",
    "name_vertical_gauge": "Medidor Vertical",
    "name_horizontal_gauge": "Medidor Horizontal",
    "name_pie_chart": "Gráfico de Pizza",
    "name_column_chart": "Gráfico de Colunas",
    "name_bar_chart": "Gráfico de Barras",
    "name_line_chart": "Gráfico de Linha",
    "titleOfTheInfographic": "TÍTULO DO INFOGRÁFICO",
    "description": "Descrição: informações adicionais sobre este infográfico."
  }
});