define({
  "chartSettingLabel": "Paramètres de diagramme",
  "addNewLabel": "Ajouter une action",
  "generalSettingLabel": "paramètres généraux",
  "layerChooser": {
    "title": "Sélectionner une couche à afficher sous forme de diagramme",
    "selectPolygonLayerLabel": "Sélectionner une couche",
    "selectPolygonLayerHintText": "Astuce : si vous configurez plusieurs diagrammes, les couches doivent être du même type de géométrie",
    "selectRelatedTableLayerLabel": "Sélectionner une table associée à une couche",
    "selectRelatedTableLayerHintText": "Astuce : seules les tables contenant des champs numériques sont affichées",
    "errorInSelectingPolygonLayer": "Sélectionnez une couche possédant une couche de points associée.",
    "errorInSelectingRelatedLayer": "Sélectionnez une table/couche associée valide pour la couche.",
    "polygonLayerNotHavingRelationships": "La couche sélectionnée ne possède pas de table/couche associée."
  },
  "ChartSetting": {
    "sectionTitle": "Titre de la section",
    "sectionTitleHintText": "Astuce : affiché dans le titre de l’en-tête de la section",
    "chartTitle": "Titre du diagramme",
    "chartTitleHintText": "Astuce : affiché de façon centrée en haut du diagramme",
    "chartDescription": "Description",
    "chartDescriptionHintText": "Astuce : affiché sous le diagramme",
    "chartType": "Type de diagramme",
    "barChart": "Diagramme à barres",
    "pieChart": "Diagramme circulaire",
    "polarChart": "Diagramme polaire",
    "dataSeriesField": "Champ de série de données",
    "labelField": "Champ d’étiquette",
    "chartColor": "Couleur du diagramme",
    "singleColor": "Uni",
    "colorByTheme": "Couleur par thème",
    "colorByFieldValue": "Couleur par valeur de champ",
    "xAxisTitle": "Titre de l’axe des x",
    "xAxisHintText": "Astuce : titre de l’axe des x",
    "yAxisTitle": "Titre de l’axe des y",
    "yAxisHintText": "Astuce : titre de l’axe des y",
    "fieldColorLabel": "Etiqueter",
    "fieldColorColor": "Couleur",
    "defaultFieldSelectLabel": "Sélectionner",
    "errMsgFieldValuesNotFound": "Impossible de trouver des valeurs pour le champ sélectionné",
    "errMsgSectionTitle": "Saisissez le titre de la section",
    "errMsgFieldByValue": "Sélectionnez une valeur de champ",
    "settingTabTitle": "Paramètre",
    "layoutTabTitle": "Mise en page",
    "polarChartSelectFieldsHintText": "Astuce : sélectionnez les champs pour générer le diagramme polaire",
    "visibilityText": "Visibilité",
    "fieldNameText": "Nom de champ",
    "aliasNameText": "Alias",
    "errMsgPolarFieldsRequired": "Sélectionnez trois champs ou plus pour générer le diagramme polaire",
    "polarChartPolygonFillLabel": "Remplir le polygone",
    "polarChartPolygonFillHintText": "Astuce : cochez la case pour afficher le remplissage de polygones dans le diagramme polaire",
    "ThemeSelector": {
      "themeAdobebricks": "Adobebricks",
      "themeAlgae": "Algae",
      "themeBahamation": "Bahamation",
      "themeBlueDusk": "BlueDusk",
      "themeCubanShirts": "CubanShirts",
      "themeDesert": "Désert",
      "themeDistinctive": "Distinctive",
      "themeDollar": "Dollar",
      "themeGrasshopper": "Grasshopper",
      "themeGrasslands": "Grasslands",
      "themeGreySkies": "GreySkies",
      "themeHarmony": "Harmony",
      "themeIndigoNation": "IndigoNation",
      "themeIreland": "Irlande",
      "themeMiamiNice": "MiamiNice",
      "themeMinty": "Minty",
      "themePurpleRain": "PurpleRain",
      "themeRoyalPurples": "RoyalPurples",
      "themeSageToLime": "SageToLime",
      "themeTufte": "Tufte",
      "themeWatersEdge": "WatersEdge",
      "themeWetlandText": "Zone humide",
      "themePlotKitblue": "PlotKit.blue",
      "themePlotKitcyan": "PlotKit.cyan",
      "themePlotKitgreen": "PlotKit.green",
      "themePlotKitorange": "PlotKit.orange",
      "themePlotKitpurple": "PlotKit.purple",
      "themePlotKitred": "PlotKit.red"
    }
  },
  "GeneralSetting": {
    "legendGeneralSettingText": "Paramètres généraux",
    "locationSymbolLabel": "Symbole d’emplacement graphique",
    "locationSymbolHintText": "Astuce : utilisé pour afficher le symbole d’adresse et d’emplacement sélectionné",
    "refreshIntervalLabel": "Intervalle d'actualisation",
    "refreshIntervalHintText": "Astuce : utilisé pour actualiser les diagrammes en fonction de cet intervalle. Spécifiez une valeur entre 1 et 1 440 minutes",
    "errMsgRefreshInterval": "Spécifiez l’intervalle d’actualisation entre 0 et 1 440 minutes",
    "symbolPickerPreviewText": "Aperçu :"
  }
});