define(
   ({
    addLayer: "Dodaj warstwę",
    layerName: "Warstwa",
    layerRefresh: "Odśwież",
    layerLabel: "Etykieta",
    actions: "Działania",
    popupOk: "OK",
    popupCancel: "Anuluj",
    mainPanelTextPlaceholder: "np.: WARUNKI NA AUTOSTRADZIE",
    invalidInterval: "Obsługiwane są tylko cyfry.",
    uploadImage: "Wczytaj obraz",
    iconColumnText: "Ikona",
    refreshInterval: "1 „Oceniono jako czas w minutach”",
    refreshIntervalTitle: "Oceniono jako czas w minutach",
    mainPanelText: "Tekst w panelu głównym",
    mainPanelIcon: "Obraz w panelu głównym",
    refreshIntervalInstruction: "Interwał odświeżania",
    optionsText: "Opcje",
    symbolOptionsText: "Opcje symboli",
    iconOptionsText: "Opcje ikon",
    sympolPopupTitle: "Ustaw symbol",
    rdoLayer: "Symbol warstwy",
    rdoCustom: "Symbol niestandardowy",
    chkCluster: "Włącz klastrowanie",
    defineClusterSymbol: "Symbol klastra",
    defineThemeClusterSymbol: "Symbol klastra z motywu",
    rdoEsri: "Symbol Esri",
    rdoLayerIcon: "Użyj symbolu jako ikony",
    rdoCustomIcon: "Prześlij ikonę niestandardową",
    editCustomSymbol: "Edytuj symbol niestandardowy",
    editCustomIcon: "Edytuj ikonę niestandardową",
    missingRefreshValue: "Podaj wartość interwału odświeżania.",
    panelIconOption: "Wyświetl nagłówek panelu",
    enableRefresh: "Włącz odświeżanie warstwy",
    disableRefresh: "Odświeżanie warstwy jest obsługiwane tylko dla zbiorów obiektów",
    layer_type_not_supported: "Typ warstwy jest nieobsługiwany: "
  })
);
