define({
  "_widgetLabel": "Аналіз загрози",
  "threatAnalysisMainPageTitle": "На основі Інструкцій з боротьби проти тероризму JCAT",
  "jcatURL": "https://www.dni.gov/nctc/jcat/references.html",
  "inputLocation": "Ввести місце розташування",
  "interactive": "Інтерактивний",
  "fromCoord": "Фіксована координата",
  "existingFeature": "З існуючих об'єктів",
  "threatAnalysisCoordInputLabel": "Місце розташування загрози",
  "enterCoords": "Ввести координати",
  "threatAddPointToolTip": "Додати місце розташування загрози",
  "threatDrawPointToolTip": "Клацніть, щоб додати місце розташування загрози",
  "threatType": "Тип загрози",
  "threatPlaceholder": "Почніть вводити текст для пошуку загрози",
  "mandatoryLabel": "Відстань обов'язкової евакуації",
  "safeLabel": "Відстань безпечної евакуації",
  "zoneTypeLabel": "Тип зони",
  "feetLabel": "Фути",
  "metersLabel": "Метри",
  "unitsLabel": "Одиниці",
  "threatGraphicLayer": "Графіка загроз",
  "settingsTitle": "Налаштування",
  "mandatoryButtonLabel": "Задати налаштування відстані обов'язкової евакуації",
  "safeButtonLabel": "Задати налаштування місцевого сховища",
  "style": "Стиль",
  "colorPicker": "Вибір кольору",
  "lineStyles": {
    "esriSLSDash": "Пунктир",
    "esriSLSDashDot": "Штрихпунктир",
    "esriSLSDashDotDot": "Штрихпунктир з двома крапками",
    "esriSLSDot": "Точковий пунктир",
    "esriSLSLongDash": "Пунктир з довгим тире",
    "esriSLSLongDashDot": "Штрихпунктир з довгим тире",
    "esriSLSNull": "Null",
    "esriSLSShortDash": "Пунктир з коротким тире",
    "esriSLSShortDashDot": "Штрихпунктир з коротким тире",
    "esriSLSShortDashDotDot": "Штрихпунктир з коротким тире та двома крапками",
    "esriSLSShortDot": "Штрихпунктир з коротким тире",
    "esriSLSSolid": "Суцільний"
  },
  "fillStyles": {
    "esriSFSBackwardDiagonal": "Назад",
    "esriSFSCross": "Хрест",
    "esriSFSDiagonalCross": "Діагональ",
    "esriSFSForwardDiagonal": "Вперед",
    "esriSFSHorizontal": "Горизонтальний",
    "esriSFSNull": "Null",
    "esriSFSSolid": "Суцільний",
    "esriSFSVertical": "Вертикальний"
  },
  "resultsTitle": "Результати",
  "publishTABtn": "Публікувати",
  "layerName": "Опублікована назва шару",
  "invalidLayerName": "Назва шару повинна містити тільки буквено-цифрові символи та нижнє підкреслення",
  "missingLayerName": "Необхідно ввести назву для шару",
  "missingLayerNameMessage": "Необхідно ввести дійсну назву шару переш ніж публікувати",
  "publishingFailedLayerExists": "Публікування не вдалося: вже існує сервіс об'єктів з назвою {0}. Виберіть іншу назву шару.",
  "checkService": "Перевірити сервіс: {0}",
  "createService": "Створити сервіс: {0}",
  "unableToCreate": "Неможливо створити: {0}",
  "addToDefinition": "Додати до визначення: {0}",
  "successfullyPublished": "Успішно опубліковано веб-шар{0}Управління веб-шаром",
  "successfullyAppended": "Успішно приєднано нові об'єкти до веб-шару{0}Управління веб-шаром",
  "userRole": "Неможливо створити сервіс, оскільки користувач не має дозволу",
  "retrieveExistingLayerError": "Неможливо отримати {0}. Виконайте публікацію, використовуючи іншу назву шару",
  "publishToNewLayer": "Публікувати результати в новий векторний шар",
  "pipeBombLabel": "Трубчастий вибуховий пристрій",
  "suicideBombLabel": "Пояс смертника",
  "briefcaseLabel": "Дипломат",
  "carLabel": "Легковий автомобіль",
  "suvVanLabel": "Кросовер/фургон",
  "smallDeliveryTruckLabel": "Невеликий автомобіль для розвезення",
  "containerWaterTruckLabel": "Контейнеровоз/автоцистерна",
  "semiTrailerLabel": "Напівпричіп",
  "transparencyLabel": "Прозорість",
  "outline": "Контур",
  "fill": "Заливка (колір застосовується, тільки коли для стиля вибрано параметр «Суцільний»)",
  "createBtn": "Створити зони",
  "clearBtn": "Очистити",
  "invalidNumberMessage": "Введене значення недійсне",
  "invalidRangeMessage": "Значення повинно бути більше, ніж 0",
  "parseCoordinatesError": "Неможливо аналізувати координати. Перевірте своє введення.",
  "manualCoordinateInputInfo": "Вручну введіть координати та клацніть <b>Ввести</b>, щоб на них масштабуватися",
  "selectDrawModeLabel": "Вибрати режим малювання",
  "selectFeatureLabel": "Вибрати об'єкт з цього шару"
});