define({
  "addLayer": "إضافة طبقة",
  "layerName": "الطبقة",
  "layerRefresh": "تحديث",
  "layerLabel": "التسمية",
  "actions": "إجراءات",
  "mainPanelTextPlaceholder": "مثال: آخر تحديث:",
  "invalidInterval": "يتم دعم الأحرف الرقمية فقط.",
  "uploadImage": "تحميل صورة",
  "iconColumnText": "العرض",
  "refreshInterval": "الوقت بالدقائق",
  "refreshIntervalTitle": "تم تقييمها في شكل وقت بالدقائق",
  "mainPanelText": "نص اللوحة الرئيسية",
  "mainPanelIcon": "صورة اللوحة الرئيسية",
  "refreshIntervalInstruction": "تحديث الطبقات كل:",
  "optionsText": "خيارات",
  "symbolOptionsText": "رموز الخريطة",
  "iconOptionsText": "رموز اللوحة",
  "sympolPopupTitle": "عرض الإعدادات",
  "rdoLayer": "الرمز الافتراضي",
  "rdoCustom": "استخدام صورة",
  "chkCluster": "تمكين التجمُّع",
  "defineClusterSymbol": "حدد رمز التجمّع",
  "rdoEsri": "اختر رمزًا",
  "rdoLayerIcon": "استخدم رمز الخريطة",
  "rdoCustomIcon": "استخدام صورة",
  "editCustomSymbol": "تحرير رمز مخصص",
  "editCustomIcon": "تحرير الأيقونة المخصصة",
  "missingRefreshValue": "يرجى توفير قيمة فاصل تحديث.",
  "panelIconOption": "اعرض صورة الشعار",
  "enableRefresh": "تمكين تحديث الطبقة",
  "disableRefresh": "يتم دعم تحديث الطبقة فقط لمجموعات المعالم",
  "layer_type_not_supported": "نوع الطبقة غير مدعوم: ",
  "refreshUnit": "دقيقة.",
  "symbolOptions": "رمز",
  "panelFeatureDisplay": "لوحة",
  "chkGroup": "معالم المجموعة",
  "selectField": "حقل",
  "fieldLabel": "التسمية",
  "addField": "إضافة حقل",
  "featureOptionsText": "خيارات الطبقة",
  "groupOptionsText": "خيارات المجموعة",
  "panelCountOption": "عرض أعداد المعالم",
  "rdoStack": "عرض خط جديد لكل حقل",
  "rdoAppend": "إلحاق الحقول بخط فردي",
  "missingLayerInWebMap": "لا توجد طبقات تشغيلية",
  "displayClusterCnt": "عرض عدد المعالم",
  "defineClusterFont": "حدد لون الخط",
  "max_records": "تم الوصول إلى الحد الأقصى لحد الحقل"
});