define({
  "_widgetLabel": "מרחק וכיוון",
  "tabLineTitle": "קו",
  "tabCircleTitle": "מעגל",
  "tabEllipseTitle": "אליפסה",
  "tabRingsTitle": "טבעות",
  "multipleNotationsMessage": " רישומים שמתאימים לקלט שלך. אשר את הרישומים שברצונך להשתמש בהם:",
  "invalidCoordinateMessage": "קואורדינטה לא חוקית",
  "confirmInputNotationMessage": "אשר רישום קלט",
  "prefixSuffixMessage": "קואורדינטת הקלט זוהתה כבעלת קידומת וסיומת עבור ערך קו הגובה או קו הרוחב, הקואורדינטה שהוחזרה מבוססת על הקידומת.",
  "rememberDecisionMessage": "זכור את ההחלטה שלי ואל תשאל שוב.<br/>",
  "majorAxisTooltipMessage": "לחץ על אורך הציר הראשי",
  "minorAxisTooltipMessage": "הזז את העכבר בחזרה לנקודת המוצא כדי להגדיר ציר משני ולסיים את ציור האליפסה",
  "clickToFinishLineMessage": "לחץ כדי לסיים את ציור הקו",
  "doubleClickEllipseMesage": "לחץ פעמיים כדי לסיים את ציור טבעות הטווח",
  "invalidCoordinateTypeMessage": "לא ניתן לקבוע את סוג קואורדינטת הקלט. בדוק את הקלט שלך",
  "noCenterPointSetMessage": "לא הוגדרה נקודת מרכז. בדוק את הקלט שלך",
  "ellipseMajorAxis": "ציר ראשי",
  "ellipseMinorAxis": "ציר משני",
  "degreesRangeMessage": "הערך חייב להיות בין 0 לבין 360",
  "millsRangeMessage": "הערך חייב להיות בין 0 לבין 6400",
  "lengthLabel": "אורך",
  "angleLabel": "זווית",
  "startPointLabel": "נקודת התחלה",
  "endPointLabel": "נקודת סיום",
  "centerPointLabel": "נקודת מרכז",
  "distanceTableErrorMessage": "טבלת המרחקים ריקה. הקפד להזין כמה מרחקים.",
  "setCoordFormatStringMessage": "הגדר מחרוזת פורמט לקואורדינטה",
  "prefixMessage": "הוסף קידומת '+/-' למספרים חיוביים ושליליים",
  "ddLabel": "DD",
  "ddmLabel": "DDM",
  "dmsLabel": "DMS",
  "garsLabel": "GARS",
  "georefLabel": "GEOREF",
  "mgrsLabel": "MGRS",
  "usngLabel": "USNG",
  "utmLabel": "UTM",
  "utmhLabel": "UTM (H)‎",
  "DDLatLongNotation": "מעלות עשרוניות - קו רוחב/קו אורך",
  "DDLongLatNotation": "מעלות עשרוניות  - קו אורך/קו רוחב",
  "DDMLatLongNotation": "מעלות עשרוניות בדקות - קו רוחב/קו אורך",
  "DDMLongLatNotation": "מעלות עשרוניות בדקות - קו אורך/קו רוחב",
  "DMSLatLongNotation": "מעלות עשרוניות בשניות - קו רוחב/קו אורך",
  "DMSLongLatNotation": "מעלות עשרוניות בשניות - קו אורך/קו רוחב",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - חצי הכדור (צפ'/דר')",
  "circleTitle": "צור מעגל באמצעות",
  "radiusLabel": "רדיוס",
  "diameterLabel": "קוטר",
  "startPointPlaceHolderLabel": "הקלד קואורדינטות",
  "formatInputLabel": "קלט פורמט",
  "drawCircleLabel": "שרטט עיגול",
  "drawLineLabel": "שרטט קו",
  "createCircleInteractivelyLabel": "צור מעגל באופן אינטראקטיבי",
  "rangeErrorMessage": "רדיוס או קוטר לא חוקי",
  "numericInvalidMessage": "הזן ערך מספרי",
  "timeLabel": "זמן",
  "invalidTimeMessage": "ערך זמן לא חוקי",
  "hoursLabel": "שעות",
  "minutesLabel": "דקות",
  "secondsLabel": "שניות",
  "rateLabel": "שיעור",
  "invalidDistanceMessage": "ערך מרחק לא חוקי",
  "feetSecondsLabel": "רגל / שנייה",
  "feetHourLabel": "רגל / שעה",
  "kmSecondLabel": "ק\"מ / שנייה",
  "kmHourLabel": "ק\"מ / שעה",
  "metersSecondLabel": "מטר / שנייה",
  "metersHourLabel": "מטר / שעה",
  "milesSecondLabel": "מייל / שנייה",
  "milesHourLabel": "מייל / שעה",
  "nauticalMilesSecondLabel": "מייל ימי / שנייה",
  "nauticalMilesHourLabel": "מייל ימי / שעה",
  "clearGraphicsLabel": "נקה גרפיקה",
  "ellipseTypeLabel": "סוג אליפסה",
  "ellipseSemiLabel": "חצי",
  "ellipseFullLabel": "מלא",
  "drawEllipseLabel": "שרטט אליפסה",
  "createEllipseInteractively": "צור אליפסה באופן אינטראקטיבי",
  "axisLabel": "ציר",
  "unitLabel": "יחידה",
  "majorRadiusLabel": "ראשי (רדיוס)",
  "majorDiameterLabel": "ראשי (קוטר)",
  "axisErrorMessage": "הערך חייב להיות גדול מאפס",
  "minorRadiusLabel": "משני (רדיוס)",
  "minorDiameterLabel": "משני (קוטר)",
  "orientationLabel": "מיקום",
  "orientationErrorMessage": "הערך חייב להיות בין 0 לבין 360",
  "warningMessage": "אזהרה: הגרפיקה שנוצרה בעזרת כלי האליפסה אינה גיאודטית",
  "fromLabel": "מאת",
  "distanceBearingLabel": "מרחק וכיוון",
  "pointsLabel": "נקודות",
  "createLineInteractively": "צור קו באופן אינטראקטיבי",
  "lineLengthErrorMessage": "אורך קו לא חוקי",
  "degreesLabel": "מעלות",
  "milsLabel": "אלפיות",
  "lineTypeLabel": "סוג",
  "interactiveLabel": "אינטראקטיבי",
  "fixedLabel": "קבוע",
  "originLabel": "מקור",
  "cumulativeLabel": "מצטבר",
  "numberOfRingsLabel": "מספר טבעות",
  "ringsErrorMessage": "מספר טבעות לא חוקי",
  "distanceBetweenRingsLabel": "מרחק בין טבעות",
  "ringsDecimalErrorMessage": "הזן ערך מספרי ל-2 ספרות עשרוניות",
  "distanceUnitsLabel": "יחידות מרחק",
  "distancesLabel": "מרחקים",
  "numberOfRadialsLabel": "מספר רדיאלים",
  "upLabel": "למעלה",
  "downLabel": "למטה",
  "deleteLabel": "מחיקה",
  "radialsErrorMessage": "מספר רדיאלים לא חוקי. הערך המרבי המותר הוא 360",
  "radialsInvalidMessage": "ערך לא חוקי עבור רדיאלים",
  "addPointLabel": "הוסף נקודה",
  "valueLabel": "ערך",
  "valueText": "הזן ערך",
  "actionLabel": "פעולה",
  "distanceCalculatorLabel": "מחשבון מרחק",
  "abbrevMetersLabel": "מ'",
  "abbrevFeetLabel": "רגל",
  "abbrevKmLabel": "ק\"מ",
  "abbrevMilesLabel": "מייל",
  "abbrevYardsLabel": "יארד",
  "abbrevNauticalMilesLabel": "מייל ימי",
  "abbrevDegreesLabel": "°",
  "abbrevMilsLabel": "mil",
  "abbrevHoursLabel": "h",
  "abbrevMinutesLabel": "מ'",
  "abbrevSecondsLabel": "s",
  "abbrevFeetSecondsLabel": "רגל לשנייה",
  "abbrevFeetHourLabel": "רגל לשעה",
  "abbrevKmSecondLabel": "קילומטר לשנייה",
  "abbrevKmHourLabel": "קילומטר לשעה",
  "abbrevMetersSecondLabel": "מטר לשנייה",
  "abbrevMetersHourLabel": "מטר לשעה",
  "abbrevMilesSecondLabel": "מייל לשנייה",
  "abbrevMilesHourLabel": "מייל לשעה",
  "abbrevNauticalMilesSecondLabel": "מייל ימי לשנייה",
  "abbrevNauticalMilesHourLabel": "מייל ימי לשעה",
  "publishDDBtn": "פרסם",
  "publishTitle": "פרסם גרפיקה",
  "ddLayerName": "שם השכבה פורסם",
  "missingDDLayerName": "עליך להזין שם עבור השכבה",
  "publishToNewLayer": "פרסם את התוצאות לשכבת ישויות חדשה",
  "checkService": "בדוק שירות: {0}",
  "createService": "צור שירות: {0}",
  "unableToCreate": "לא ניתן ליצור: {0}",
  "addToDefinition": "הוסף להגדרה: {0}",
  "successfullyPublished": "שכבת האינטרנט {0} פורסמה בהצלחה. נהל את שכבת האינטרנט",
  "userRole": "לא ניתן ליצור את השירות משום למשתמש אין הרשאות",
  "missingLayerNameMessage": "עליך להזין שם חוקי של שכבה לפני שתוכל לפרסם",
  "invalidLayerName": "שם השכבה חייב להכיל תווי אותיות ומספרים וקווים תחתונים בלבד",
  "distanceLabel": "מרחק",
  "radiusDistance": "מרחק רדיוס",
  "radials": "רדיאלים",
  "rings": "טבעות",
  "orientationUnit": "יחידת כיוון",
  "radiusUnit": "יחידת רדיוס",
  "angleUnitLabel": "יחידת זווית"
});