define({
  "_widgetLabel": "Okos szerkesztő",
  "_featureAction_SmartEditor": "Okos szerkesztő",
  "noEditPrivileges": "A fiókja nem teszi lehetővé az adatok létrehozását vagy módosítását.",
  "widgetActive": "Aktív",
  "widgetNotActive": "Nem aktív",
  "pressStr": "Nyomja meg a ",
  "ctrlStr": " CTRL ",
  "snapStr": " billentyűt a hozzáillesztés engedélyezéséhez",
  "noAvailableTempaltes": "Nincsenek elérhető sablonok",
  "editorCache": " - Szerkesztő gyorsítótára",
  "presetFieldAlias": "Mező",
  "presetValue": "Előre beállított érték",
  "usePresetValues": " Előre beállított értékek használata (csak új vektoros elemekhez)",
  "editGeometry": " Geometria szerkesztése",
  "savePromptTitle": "Vektoros elem mentése",
  "savePrompt": "Szeretné menteni az aktuális vektoros elemet?",
  "deletePromptTitle": "Vektoros elem törlése",
  "deleteAttachment": "Csatolmány törlése",
  "deletePrompt": "Biztosan törli a kiválasztott vektoros elemet?",
  "attachmentLoadingError": "Hiba a csatolmányok feltöltésekor",
  "attachmentSaveDeleteWarning": "Figyelmeztetés: A csatolmányok módosításai automatikusan mentésre kerülnek",
  "autoSaveEdits": "Automatikusan menti az új vektoros elemet",
  "addNewFeature": "Új vektoros elem létrehozása",
  "featureCreationFailedMsg": "Nem lehet új rekordot/vektoros elemet létrehozni",
  "relatedItemTitle": "Kapcsolt tábla/réteg",
  "relatedFeatureCount": "${layerTitle} ${featureCount} vektoros elemmel",
  "createNewFeatureLabel": "Új vektoros elem létrehozása ehhez: ${layerTitle}",
  "invalidRelationShipMsg": "Győződjön meg arról, hogy az elsődleges kulcs '${parentKeyField}' mezőjében érvényes érték szerepel",
  "pendingFeatureSaveMsg": "Mentse a vektoros elem módosításait, mielőtt kapcsolt vektoros elemet hoz létre.",
  "attachmentsRequiredMsg": "(*) A csatolmányok megadása kötelező.",
  "coordinatePopupTitle": "A vektoros elem áthelyezése XY helyszínre",
  "coordinatesSelectTitle": "Koordináta-rendszer:",
  "mapSpecialReferenceDropdownOption": "Térkép koordináta-rendszere",
  "latLongDropdownOption": "Hosszúság/szélesség",
  "xAttributeTextBoxLabel": "X-koordináta:",
  "yAttributeTextBoxLabel": "Y-koordináta:",
  "latitudeTextBoxLabel": "Szélesség:",
  "longitudeTextBoxLabel": "Hosszúság:",
  "presetGroupFieldsLabel": "A(z) '${groupName}' a következő rétegmezőkre lesz alkalmazva:",
  "presetGroupNoFieldsLabel": "A(z) '${groupName}' nem rendelkezik egyetlen kapcsolódó mezővel sem",
  "groupInfoLabel": "Csoportinformációk ehhez: '${groupName}'",
  "editGroupInfoIcon": "Csoportérték szerkesztése ehhez: ${groupName}",
  "filterEditor": {
    "all": "Mind",
    "noAvailableTempaltes": "Nincsenek elérhető sablonok",
    "searchTemplates": "Sablonok keresése",
    "filterLayerLabel": "Szűrőrétegek"
  },
  "invalidConfiguration": "A widget nincs konfigurálva, vagy a konfigurációban lévő rétegek már nem szerepelnek a térképen. Nyissa meg az alkalmazást építő módban, és konfigurálja újra a widgetet.",
  "geometryServiceURLNotFoundMSG": "Nem sikerült meghatározni a geometriai adatszolgáltatás URL-címét",
  "clearSelection": "Törlés",
  "refreshAttributes": "Vektoroselem-attribútumok frissítése",
  "automaticAttributeUpdatesOn": "A vektoros elemek attribútumainak frissítése: BE",
  "automaticAttributeUpdatesOff": "A vektoros elemek attribútumainak frissítése: KI",
  "moveSelectedFeatureToGPS": "A kijelölt vektoros elem áthelyezése az aktuális GPS helyszínre",
  "moveSelectedFeatureToXY": "A kijelölt vektoros elem áthelyezése XY helyszínre",
  "mapNavigationLocked": "Térképnavigáció: zárolva",
  "mapNavigationUnLocked": "Térképnavigáció: engedélyezve",
  "copyFeatures": {
    "title": "Vektoros elemek másolása",
    "createFeatures": "Vektoros elemek létrehozása",
    "createSingleFeature": "1 többgeometriájú vektoros elem létrehozása",
    "noFeaturesSelectedMessage": "Nincsenek vektoros elemek kijelölve",
    "selectFeatureToCopyMessage": "Válassza ki a másolni kívánt vektoros elemet.",
    "multipleFeatureSaveWarning": "Tipp: Ha a vektoros elemek másolására szolgáló funkcióval több példányt hoz létre egy vektoros elemből, a vektoros elem összes példánya azonnal mentésre kerül"
  },
  "addingFeatureError": "Hiba történt a rétegben lévő, kiválasztott vektoros elemek hozzáadásakor. Próbálja meg újra.",
  "addingFeatureErrorCount": "'${copyFeatureErrorCount}' vektoros elem másolása nem sikerült.",
  "selectingFeatureError": "Hiba történt a rétegben lévő vektoros elemek kiválasztásakor. Próbálja meg újra.",
  "customSelectOptionLabel": "Válassza ki a másolni kívánt vektoros elemeket.",
  "noFeatureSelectedMessage": "Nincsenek vektoros elemek kiválasztva.",
  "multipleFeatureSaveMessage": "A rendszer az összes vektoros elemet azonnal menti. Folytatja?",
  "relativeDates": {
    "dateTypeLabel": "Dátumtípus",
    "valueLabel": "Érték",
    "fixed": "Rögzített",
    "current": "Jelenlegi",
    "past": "Elmúlt",
    "future": "Jövőbeli",
    "popupTitle": "Érték kiválasztása",
    "hintForFixedDateType": "Tipp: A rendszer előre beállított alapértelmezett értékként kezeli a megadott dátumot és időt.",
    "hintForCurrentDateType": "Tipp: A rendszer előre beállított alapértelmezett értékként kezeli az aktuális dátumot és időt.",
    "hintForPastDateType": "Tipp: Az előre beállított alapértelmezett érték meghatározásához a rendszer levonja a megadott értéket az aktuális dátumból és időből.",
    "hintForFutureDateType": "Tipp: Az előre beállított alapértelmezett érték meghatározásához a rendszer hozzáadja a megadott értéket az aktuális dátumhoz és időhöz.",
    "noDateDefinedTooltip": "Nincs meghatározva dátum",
    "relativeDateWarning": "Ahhoz, hogy menteni lehessen az alapértelmezett beállított értéket, meg kell adni a dátum vagy az idő értékét."
  }
});