define({
  "_widgetLabel": "Pametni urejevalnik",
  "_featureAction_SmartEditor": "Pametni urejevalnik",
  "noEditPrivileges": "Vaš račun nima dovoljenja za ustvarjanje ali spreminjanje podatkov.",
  "widgetActive": "Aktivno",
  "widgetNotActive": "Neaktivno",
  "pressStr": "Pritisnite ",
  "ctrlStr": " CTRL, ",
  "snapStr": " da omogočite privlačnost",
  "noAvailableTempaltes": "Predloge niso na voljo",
  "editorCache": " – predpomnilnik urejevalnika",
  "presetFieldAlias": "Polje",
  "presetValue": "Prednastavljena vrednost",
  "usePresetValues": " Uporabi prednastavljeno vrednost (samo novi geoobjekti)",
  "editGeometry": " Uredi geometrijo",
  "savePromptTitle": "Shrani geoobjekt",
  "savePrompt": "Želite shraniti trenutni geoobjekt?",
  "deletePromptTitle": "Izbriši geoobjekt",
  "deletePrompt": "Ste prepričani, da želite izbrisati izbrani geoobjekt?",
  "attachmentLoadingError": "Napaka pri nalaganju prilog",
  "attachmentSaveDeleteWarning": "Opozorilo: Spremembe v prilogah so shranjene samodejno",
  "autoSaveEdits": "Samodejno shrani nov geoobjekt",
  "addNewFeature": "Ustvari nov geoobjekt",
  "featureCreationFailedMsg": "Ni bilo mogoče ustvariti novega zapisa/geoobjekta",
  "relatedItemTitle": "Relacijska tabela/sloj",
  "invalidRelationShipMsg": "Zagotovite, da ima polje primarnega ključa: »${parentKeyField}« veljavno vrednost",
  "pendingFeatureSaveMsg": "Shranite urejanja geoobjektov pred ustvarjanjem relacijskega geoobjekta.",
  "attachmentsRequiredMsg": "(*) Zahtevane so priloge.",
  "coordinatePopupTitle": "Premakni geoobjekt na lokacijo XY",
  "coordinatesSelectTitle": "Koordinatni sistem:",
  "mapSpecialReferenceDropdownOption": "Koordinatni sistem karte",
  "latLongDropdownOption": "Geografska širina/geografska dolžina",
  "xAttributeTextBoxLabel": "Koordinata X:",
  "yAttributeTextBoxLabel": "Koordinata Y:",
  "latitudeTextBoxLabel": "Geografska širina:",
  "longitudeTextBoxLabel": "Geografska dolžina:",
  "filterEditor": {
    "all": "Vsi",
    "noAvailableTempaltes": "Predloge niso na voljo",
    "searchTemplates": "Iskanje predlog"
  },
  "invalidConfiguration": "Pripomoček morda ni konfiguriran ali pa slojev v konfiguraciji ni več na zemljevidu. Odprite aplikacijo v načinu izdelave in ponovno konfigurirajte pripomoček.",
  "geometryServiceURLNotFoundMSG": "URL geometrijske storitve ni mogoče pridobiti",
  "clearSelection": "Počisti",
  "refreshAttributes": "Posodobi atribute geoobjektov",
  "automaticAttributeUpdatesOn": "Samodejno posodabljajo atribute geoobjektov: VKLOP",
  "automaticAttributeUpdatesOff": "Samodejno posodobi atribute geoobjektov: IZKLOP",
  "moveSelectedFeatureToGPS": "Premakni izbrani geoobjekt na trenutno lokacijo GPS",
  "moveSelectedFeatureToXY": "Premakni izbrani geoobjekt na lokacijo XY",
  "mapNavigationLocked": "Navigacija po karti: zaklenjeno",
  "mapNavigationUnLocked": "Navigacija po karti: odklenjeno"
});