define({
  "_widgetLabel": "נראות",
  "observerLocation": "מיקום תצפית",
  "formatIconTooltip": "קלט פורמט",
  "addPointToolTip": "הוסף מיקום תצפית",
  "fieldOfView": "שדה ראייה",
  "useMilsText": "השתמש באלפיות עבור זוויות",
  "observerHeight": "גובה תצפית",
  "minObsDistance": "מרחק תצפית מינימלי",
  "maxObsDistance": "מרחק תצפית מרבי",
  "taskURLError": "קובץ התצורה של הווידג'ט מכיל כתובת URL לא נגישה. פנה למנהל המערכת שלך",
  "taskURLInvalid": "משימת העיבוד הגיאוגרפי שהוגדרה באמצעות ווידג'ט זה אינה חוקית. פנה למנהל המערכת שלך",
  "viewshedError": "אירעה שגיאה במהלך יצירת הנראות. ודא שמיקום התצפית שלך מתאים לגובה פני השטח.‎</p>‎",
  "validationError": "<p>טופס יצירת הנראות מכיל פרמטרים לא חוקיים או שחסרים בו פרמטרים, ודא כי:</p><ul><li>הוגדר מיקום תצפית.</li><li>שדה הראייה של התצפית אינו 0.</li><li>גובה התצפית מכיל ערך חוקי.</li><li>ערכי המינימום והמקסימום של מרחק התצפית חוקיים.</li></ul>",
  "comfirmInputNotation": "אשר רישום קלט",
  "notationsMatch": "הרישומים מתאימים לקלט שלך. אשר את הרישומים שבהם תרצה להשתמש:",
  "createBtn": "צור",
  "clearBtn": "נקה",
  "setCoordFormat": "הגדר מחרוזת פורמט לקואורדינטה",
  "prefixNumbers": "הוסף קידומת '+/-' למספרים חיוביים ושליליים",
  "parseCoordinatesError": "לא ניתן לנתח קואורדינטות. בדוק את הקלט שלך.",
  "cancelBtn": "בטל",
  "applyBtn": "בצע",
  "invalidMessage": "הזן בבקשה ערך מספרי.",
  "observerRangeMessage": "גובה תצפית לא חוקי",
  "minimumRangeMessage": "טווח תצפית מינימלי לא חוקי",
  "maximumRangeMessage": "טווח התצפית המרבי חייב להיות גדול מטווח התצפית המינימלי והוא אינו יוכל להיות גדול מ-‎${limit}‎‏ ‎${units}.",
  "portalURLError": "כתובת ה-URL של ארגון ArcGIS Online או הפורטל של ArcGIS לא הוגדרה. פנה למנהל המערכת שלך",
  "privilegeError": "תפקיד המשתמש שלך לא יכול לבצע ניתוח. כדי שתוכל לבצע ניתוח, מנהל המערכת של הארגון צריך להעניק לך ‎<a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">‎הרשאות‎</a>‎ מסוימות.",
  "noServiceError": "שירות ניתוח הגובה לא זמין. בדוק את התצורה של ארגון ArcGIS Online או הפורטל של ArcGIS.",
  "pointToolTooltip": "לחץ להוספת מיקום תצפית",
  "degreesLabel": "מעלות",
  "milsLabel": "אלפיות אינץ'",
  "DD": "DD",
  "DDM": "DDM",
  "DMS": "DMS",
  "DDRev": "DDRev",
  "DDMRev": "DDMRev",
  "DMSRev": "DMSRev",
  "USNG": "USNG",
  "MGRS": "MGRS",
  "UTM_H": "UTM (H)‎",
  "UTM": "UTM",
  "GARS": "GARS",
  "GEOREF": "GEOREF",
  "DDLatLongNotation": "מעלות עשרוניות - קו רוחב/קו אורך",
  "DDLongLatNotation": "מעלות עשרוניות  - קו אורך/קו רוחב",
  "DDMLatLongNotation": "מעלות עשרוניות בדקות - קו רוחב/קו אורך",
  "DDMLongLatNotation": "מעלות עשרוניות בדקות - קו אורך/קו רוחב",
  "DMSLatLongNotation": "מעלות עשרוניות בשניות - קו רוחב/קו אורך",
  "DMSLongLatNotation": "מעלות עשרוניות בשניות - קו אורך/קו רוחב",
  "GARSNotation": "GARS",
  "GEOREFNotation": "GEOREF",
  "MGRSNotation": "MGRS",
  "USNGNotation": "USNG",
  "UTMBandNotation": "UTM - Band Letter",
  "UTMHemNotation": "UTM - חצי הכדור (צפ'/דר')"
});