define({
  "addLayer": "Layer hinzufügen",
  "layerName": "Layer",
  "layerRefresh": "Aktualisieren",
  "layerLabel": "Beschriftung",
  "actions": "Aktionen",
  "mainPanelTextPlaceholder": "Z. B.: Zuletzt aktualisiert:",
  "invalidInterval": "Es werden nur numerische Zeichen unterstützt.",
  "uploadImage": "Bild hochladen",
  "iconColumnText": "Anzeige",
  "refreshInterval": "Zeit in Minuten",
  "refreshIntervalTitle": "Wird als Zeit in Minuten ausgewertet",
  "mainPanelText": "Text im Hauptbereich",
  "mainPanelIcon": "Bild im Hauptbereich",
  "refreshIntervalInstruction": "Layer-Aktualisierung alle:",
  "optionsText": "Optionen",
  "symbolOptionsText": "Kartensymbolisierung",
  "iconOptionsText": "Bereichssymbolisierung",
  "sympolPopupTitle": "Anzeigeeinstellungen",
  "rdoLayer": "Standardsymbol",
  "rdoCustom": "Bild verwenden",
  "chkCluster": "Cluster-Bildung aktivieren",
  "defineClusterSymbol": "Cluster-Symbol festlegen",
  "rdoEsri": "Ein Symbol auswählen",
  "rdoLayerIcon": "Kartensymbol verwenden",
  "rdoCustomIcon": "Bild verwenden",
  "editCustomSymbol": "Benutzerdefiniertes Symbol bearbeiten",
  "editCustomIcon": "Benutzerdefinierte Grafik bearbeiten",
  "missingRefreshValue": "Geben Sie einen Wert für das Aktualisierungsintervall ein.",
  "panelIconOption": "Logobild anzeigen",
  "enableRefresh": "Layer-Aktualisierung aktivieren",
  "disableRefresh": "Layer-Aktualisierung wird nur für Feature-Sammlungen unterstützt",
  "layer_type_not_supported": "Layer-Typ wird nicht unterstützt: ",
  "refreshUnit": "Minuten.",
  "symbolOptions": "Symbol",
  "panelFeatureDisplay": "Fenster",
  "chkGroup": "Features gruppieren",
  "selectField": "Feld",
  "fieldLabel": "Beschriftung",
  "addField": "Feld hinzufügen",
  "featureOptionsText": "Layer-Optionen",
  "groupOptionsText": "Gruppenoptionen",
  "panelCountOption": "Feature-Anzahl anzeigen",
  "rdoStack": "Neue Linie für jedes Feld anzeigen",
  "rdoAppend": "Felder für eine einzelne Zeile anhängen",
  "missingLayerInWebMap": "Keine operationalen Layer gefunden.",
  "displayClusterCnt": "Feature-Anzahl anzeigen",
  "defineClusterFont": "Schriftfarbe festlegen",
  "max_records": "Maximaler Feldgrenzwert erreicht"
});