define({
  "_widgetLabel": "Business Analyst",
  "addPoint": "Adicionar ponto clicando no mapa",
  "addRingsDtWt": "Adicionar anéis, tempo de condução ou tempo de caminhada",
  "apply": "Aplicar",
  "back": "Voltar",
  "colon": ":",
  "creditInformation": "Informações de Crédito",
  "driveTime": "Tempo de condução",
  "esriInfographics": "Infografia Esri",
  "esriReports": "Relatórios Esri",
  "headerDescription_km": "quilómetro",
  "headerDescription_miles": "milha",
  "headerDescription_minutes": "minuto",
  "infographics": "Infográficos",
  "invalidValueRing": "Os valores devem estar no intervalo de 0 a 1000.",
  "invalidValueDTWT": "Os valores devem estar no intervalo de 0 a 300.",
  "km": "km",
  "miles": "milhas",
  "minutes": "minutos",
  "myInfographics": "A minha Infografia",
  "myReports": "Meus Relatórios",
  "noPermissions": "A sua conta não está autorizada a executar o widget Business Analyst. Para executar o widget Business Analyst, o administrador da sua organização deverá atribuir-lhe <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privilégios</a> Geoenriquecimento e Análise de Rede e ainda <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">créditos</a>.",
  "geServiceNotConfigured": "Não é possível executar o widget Business Analyst neste portal, porque este não possui o serviço de <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenriquecimento</a> configurado.",
  "dirRoutingServiceNotConfigured": "Não é possível executar o widget Business Analyst neste portal, porque este não possui o serviço de <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Direções e Rotas</a> configurado.",
  "geAndDirRoutingServicesNotConfigured": "Não é possível executar o widget Business Analyst neste portal, porque este não possui os serviços de <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_1E0134BF60A049FFB388265B5A6AAE7F\" target=\"_blank\">Geoenriquecimento</a> e <a href=\"https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-services.htm#ESRI_SECTION2_9CEB83540DC04715941D8A8EDEB11A85\" target=\"_blank\">Direções e Rotas</a> configurados.",
  "radii": "raios",
  "radius": "Raio",
  "radius_lowercase": "raio",
  "reports": "Relatórios",
  "ring": "Anel",
  "rings": "Anéis",
  "runInfographic": "Executar Infografia",
  "runReport": "Executar Relatório",
  "selectPointOrPolygon": "Selecione um elemento de Ponto ou Polígono no mapa, pesquise um endereço ou local ou coloque um alfinete no mapa para ver mais informações sobre essas áreas.",
  "selectReport": "Selecionar Relatório",
  "selectTemplate": "Seleccionar Modelo",
  "sharedInfographics": "Infografia Partilhada",
  "sharedReports": "Relatórios Partilhados",
  "thisEntryIsNotValid": "Esta entrada não é válida.",
  "time": "Hora",
  "walkTime": "Tempo de Caminhada",
  "widgetDescription": "Aceda a Infografia e Relatórios que resumam indicadores-chave e dados de qualquer área.",
  "None": "Selecionar..."
});