define({
  "_widgetLabel": "Modelador d'idoneïtat",
  "general": {
    "clear": "Esborra",
    "cancel": "Cancel·la",
    "save": "Executa",
    "saveAs": "Exporta"
  },
  "saveModel": {
    "save": "Exporta",
    "title": "Títol: ",
    "summary": "Resum: ",
    "description": "Descripció: ",
    "tags": "Etiquetes: ",
    "folder": "Carpeta: ",
    "homeFolderPattern": "{username} (Inici)",
    "failed": "Error en exportar."
  },
  "util": {
    "colorRamp": {
      "1": "Excessivament baix",
      "2": "Molt baix",
      "3": "Baix",
      "4": "Baix-mitjà",
      "5": "Mitjà",
      "6": "Alt-mitjà",
      "7": "Alt",
      "8": "Molt alt",
      "9": "Excessivament alt",
      "low": "Baixa",
      "high": "Alta",
      "tipPattern": "{label} ({value})",
      "flipCaption": "Inverteix"
    }
  },
  "wro": {
    "caption": "Modelador d'idoneïtat",
    "browsePrompt": "Servei de superposició ponderada",
    "selectLayersCaption": "Seleccioneu les capes",
    "selectLayers": "Capes",
    "designModelCaption": "Model de disseny",
    "designModel": "Model de disseny",
    "transparency": "Transparència",
    "visible": "Visible",
    "total": "Total",
    "unableToLoad": "No es pot carregar el model.",
    "projectNotOpen": "No hi ha cap projecte obert.",
    "readMore": "Més informació",
    "validation": {
      "validating": "S'està validant...",
      "invalidItemCaption": "Avís sobre el servei de superposició ponderada",
      "notAnImageService": "Aquest element no és un servei d'imatges.",
      "notAWroService": "Aquest element no és un servei de superposició ponderada.",
      "undefinedUrl": "No s'ha definit l'adreça URL d'aquest element.",
      "inaccessible": "No es pot accedir al servei.",
      "generalError": "No es pot obrir l'element.",
      "missingFieldPattern": "{field} és un camp obligatori",
      "notAllowRasterFunction": "allowRasterFunction s'ha de definir en Cert",
      "notNearestResampling": "defaultResamplingMethod ha de ser Més proper",
      "notIsWeightedOverlayProp": "La propietat clau IsWeightedOverlay ha d'estar definida en Cert",
      "invalidLink": "L'adreça URL no és vàlida. No s'ha pogut obrir el lloc de la capa seleccionada.",
      "unexpectedError": "S'ha produït un estat inesperat.",
      "rangeMessage": "El valor ha d'estar comprès entre ${0} i ${1}",
      "rangeMessage100": "El valor ha d'estar comprès entre 0 i 100",
      "maxLayers": "Es permet un màxim de ${0} capes per servei i s'ha d'eliminar una capa abans d'afegir-ne una de nova.",
      "notFound": "No s'ha trobat la capa ${0} al servei de superposició ponderada",
      "wroServiceNotDefined": "No hi ha cap servei de superposició ponderada definit per al model.",
      "overlayLayerOutputInvalid": "Falta el valor de sortida dels intervals de nova representació cartogràfica [${1}] de la capa de superposició [${0}] o no és vàlid",
      "overlayLayerInputInvalid": "Falta el valor mínim/màxim d'entrada dels intervals de nova representació cartogràfica [${1}] de la capa de superposició [${0}] o no és vàlid",
      "overlayLayerRangesMissing": "Falten els intervals de nova representació cartogràfica de la capa de superposició [${0}]",
      "overlayLayerWeight": "Les ponderacions de la capa de superposició han de sumar 100 com a màxim",
      "overlayLayerRequired": "És necessària almenys una capa de superposició",
      "overlayLayerNotDefined": "No s'han definit les capes de superposició",
      "requiresColormap": "Aquesta funció de ràster requereix un mapa de color, però el model no té una definició de mapa de color vàlida",
      "createModelError": "Error en crear el model",
      "invalidModel": "El model no és vàlid",
      "imageServiceNotDefined": "No s'ha definit la capa del servei d'imatges",
      "imageLayerNotDefined": "No s'ha definit la capa del servei d'imatges",
      "histogramNotDefined": "No s'ha definit cap funció d'histograma de superposició ponderada."
    },
    "colorRampLabel": {
      "Green Yellow Red": "Verd Groc Vermell",
      "Red Yellow Green": "Vermell Groc Verd",
      "Yellow to Dark Red": "De groc a vermell fosc",
      "Dark Red to Yellow": "De vermell fosc a groc",
      "Light Gray to Dark Gray": "De gris clar a gris fosc",
      "Dark Gray to Light Gray": "De gris fosc a gris clar",
      "Light Brown to Dark Brown": "De marró clar a marró fosc",
      "Dark Brown to Light Brown": "De marró fosc a marró clar",
      "Full Spectrum - Bright Red to Blue": "Espectre complet: de vermell brillant a blau",
      "Full Spectrum - Bright Blue to Red": "Espectre complet: de blau brillant a vermell",
      "Partial Spectrum - Yellow to Blue": "Espectre parcial: de groc a blau",
      "Partial Spectrum - Blue to Yellow": "Espectre parcial: de blau a groc",
      "Yellow-Green to Dark Blue": "De groc-verd a blau fosc",
      "Dark Blue to Yellow-Green": "De blau fosc a groc-verd",
      "Cold to Hot Diverging": "De fred a càlid divergent",
      "Hot to Cold Diverging": "De calent a fred divergent",
      "Surface - Low to High": "Superfície: de menys a més",
      "Surface - High to Low": "Superfície: de més a menys"
    }
  },
  "tabs": {
    "layers": "Capes",
    "model": "Model",
    "chart": "Gràfic"
  },
  "chart": {
    "prompt": "Entitats",
    "working": "S'està actualitzant...",
    "polygonTool": "Dibuixa un polígon",
    "freehandPolygonTool": "Dibuixa un polígon a mà alçada",
    "selectTool": "Seleccioneu-ne d'una capa",
    "panTool": "Panoràmica",
    "clearButton": "Esborra",
    "noModelLayer": "No hi ha cap model.",
    "noSubjectLayers": "El mapa no té capes de polígon.",
    "tipPattern": "${category} - ${label}: ${percent} %",
    "tipPattern2": "${category}: ${percent} %",
    "labelPattern": "${category} - ${label}"
  }
});